// 自动生成 scripts/gen_chi_channel.py —— 勿手改
module Decoupled2LCredit_1_xs(
  input clock,
  input reset,
  output io_in_ready,
  input io_in_valid,
  input [3:0] io_in_bits_qos,
  input [10:0] io_in_bits_tgtID,
  input [10:0] io_in_bits_srcID,
  input [11:0] io_in_bits_txnID,
  input [4:0] io_in_bits_opcode,
  input [1:0] io_in_bits_respErr,
  input [2:0] io_in_bits_resp,
  input [2:0] io_in_bits_fwdState,
  input [2:0] io_in_bits_cBusy,
  input [11:0] io_in_bits_dbID,
  input [3:0] io_in_bits_pCrdType,
  input [1:0] io_in_bits_tagOp,
  input io_in_bits_traceTag,
  output io_out_flitpend,
  output io_out_flitv,
  output [72:0] io_out_flit,
  input io_out_lcrdv,
  input [1:0] io_state_state
);
  xs_Decoupled2LCredit_1_core u_core (
    .clock(clock),
    .reset(reset),
    .io_in_ready(io_in_ready),
    .io_in_valid(io_in_valid),
    .io_in_bits_qos(io_in_bits_qos),
    .io_in_bits_tgtID(io_in_bits_tgtID),
    .io_in_bits_srcID(io_in_bits_srcID),
    .io_in_bits_txnID(io_in_bits_txnID),
    .io_in_bits_opcode(io_in_bits_opcode),
    .io_in_bits_respErr(io_in_bits_respErr),
    .io_in_bits_resp(io_in_bits_resp),
    .io_in_bits_fwdState(io_in_bits_fwdState),
    .io_in_bits_cBusy(io_in_bits_cBusy),
    .io_in_bits_dbID(io_in_bits_dbID),
    .io_in_bits_pCrdType(io_in_bits_pCrdType),
    .io_in_bits_tagOp(io_in_bits_tagOp),
    .io_in_bits_traceTag(io_in_bits_traceTag),
    .io_out_flitpend(io_out_flitpend),
    .io_out_flitv(io_out_flitv),
    .io_out_flit(io_out_flit),
    .io_out_lcrdv(io_out_lcrdv),
    .io_state_state(io_state_state)
  );
endmodule
