// 自动生成:scripts/gen_openllc.py —— golden 叶子传递闭包文件列表(每文件一次)
// 顶: OpenLLC;模块数=70;文件数=70
// 用 -f 显式编译,规避 -y 对自包含 pkg+module 文件的重复声明冲突。
../../../golden/chisel-rtl/DataStorage_4.sv
../../../golden/chisel-rtl/Decoupled2LCredit.sv
../../../golden/chisel-rtl/Decoupled2LCredit_1.sv
../../../golden/chisel-rtl/Decoupled2LCredit_2.sv
../../../golden/chisel-rtl/Decoupled2LCredit_5.sv
../../../golden/chisel-rtl/Directory_4.sv
../../../golden/chisel-rtl/FastArbiter_27.sv
../../../golden/chisel-rtl/FastArbiter_30.sv
../../../golden/chisel-rtl/FastArbiter_31.sv
../../../golden/chisel-rtl/FastArbiter_36.sv
../../../golden/chisel-rtl/FastArbiter_44.sv
../../../golden/chisel-rtl/FastArbiter_46.sv
../../../golden/chisel-rtl/FastArbiter_47.sv
../../../golden/chisel-rtl/FastArbiter_49.sv
../../../golden/chisel-rtl/FastArbiter_50.sv
../../../golden/chisel-rtl/FastArbiter_52.sv
../../../golden/chisel-rtl/LCredit2Decoupled_3.sv
../../../golden/chisel-rtl/LCredit2Decoupled_4.sv
../../../golden/chisel-rtl/LCredit2Decoupled_5.sv
../../../golden/chisel-rtl/MMIODiverger.sv
../../../golden/chisel-rtl/MMIOMerger.sv
../../../golden/chisel-rtl/MainPipe_5.sv
../../../golden/chisel-rtl/MaxPeriodFibonacciLFSR_3.sv
../../../golden/chisel-rtl/MemUnit.sv
../../../golden/chisel-rtl/OpenLLC.sv
../../../golden/chisel-rtl/Queue15_CHIDAT.sv
../../../golden/chisel-rtl/Queue15_CHIREQ.sv
../../../golden/chisel-rtl/Queue15_CHIRSP.sv
../../../golden/chisel-rtl/Queue1_CHIRSP.sv
../../../golden/chisel-rtl/RNLinkMonitor.sv
../../../golden/chisel-rtl/RNXbar.sv
../../../golden/chisel-rtl/RXDAT_4.sv
../../../golden/chisel-rtl/RXREQ.sv
../../../golden/chisel-rtl/RXRSP_4.sv
../../../golden/chisel-rtl/RefillUnit.sv
../../../golden/chisel-rtl/RequestArb_4.sv
../../../golden/chisel-rtl/RequestBuffer_4.sv
../../../golden/chisel-rtl/ResponseUnit.sv
../../../golden/chisel-rtl/SNLinkMonitor.sv
../../../golden/chisel-rtl/SNXbar.sv
../../../golden/chisel-rtl/SRAMTemplate_197.sv
../../../golden/chisel-rtl/SRAMTemplate_198.sv
../../../golden/chisel-rtl/SRAMTemplate_199.sv
../../../golden/chisel-rtl/SRAMTemplate_200.sv
../../../golden/chisel-rtl/SRAMTemplate_201.sv
../../../golden/chisel-rtl/SRAMTemplate_202.sv
../../../golden/chisel-rtl/Slice_4.sv
../../../golden/chisel-rtl/SnoopUnit.sv
../../../golden/chisel-rtl/SubDirectory.sv
../../../golden/chisel-rtl/SubDirectory_1.sv
../../../golden/chisel-rtl/TXDAT_4.sv
../../../golden/chisel-rtl/TXREQ_4.sv
../../../golden/chisel-rtl/TXRSP_4.sv
../../../golden/chisel-rtl/TXSNP.sv
../../../golden/chisel-rtl/TopDownMonitor_1.sv
../../../golden/chisel-rtl/array_0_0.sv
../../../golden/chisel-rtl/array_0_0_ext.v
../../../golden/chisel-rtl/array_0_1.sv
../../../golden/chisel-rtl/array_0_1_ext.v
../../../golden/chisel-rtl/array_19.sv
../../../golden/chisel-rtl/array_19_ext.v
../../../golden/chisel-rtl/array_20.sv
../../../golden/chisel-rtl/array_20_ext.v
../../../golden/chisel-rtl/array_21.sv
../../../golden/chisel-rtl/array_21_ext.v
../../../golden/chisel-rtl/array_22.sv
../../../golden/chisel-rtl/array_22_ext.v
../../../golden/chisel-rtl/ram_15x162.sv
../../../golden/chisel-rtl/ram_15x422.sv
../../../golden/chisel-rtl/ram_15x73.sv
