// 自动生成:scripts/gen_openllc.py —— 勿手改(顶层 glue 为从 Scala 意图的可读重写)

module OpenLLC_xs(
  input  clock,
  input  reset,
  input  io_rn_0_txsactive,
  output  io_rn_0_rxsactive,
  input  io_rn_0_syscoreq,
  output  io_rn_0_syscoack,
  input  io_rn_0_tx_linkactivereq,
  output  io_rn_0_tx_linkactiveack,
  input  io_rn_0_tx_req_flitpend,
  input  io_rn_0_tx_req_flitv,
  input  [161:0] io_rn_0_tx_req_flit,
  output  io_rn_0_tx_req_lcrdv,
  input  io_rn_0_tx_rsp_flitpend,
  input  io_rn_0_tx_rsp_flitv,
  input  [72:0] io_rn_0_tx_rsp_flit,
  output  io_rn_0_tx_rsp_lcrdv,
  input  io_rn_0_tx_dat_flitpend,
  input  io_rn_0_tx_dat_flitv,
  input  [421:0] io_rn_0_tx_dat_flit,
  output  io_rn_0_tx_dat_lcrdv,
  output  io_rn_0_rx_linkactivereq,
  input  io_rn_0_rx_linkactiveack,
  output  io_rn_0_rx_rsp_flitpend,
  output  io_rn_0_rx_rsp_flitv,
  output  [72:0] io_rn_0_rx_rsp_flit,
  input  io_rn_0_rx_rsp_lcrdv,
  output  io_rn_0_rx_dat_flitpend,
  output  io_rn_0_rx_dat_flitv,
  output  [421:0] io_rn_0_rx_dat_flit,
  input  io_rn_0_rx_dat_lcrdv,
  output  io_rn_0_rx_snp_flitpend,
  output  io_rn_0_rx_snp_flitv,
  output  [114:0] io_rn_0_rx_snp_flit,
  input  io_rn_0_rx_snp_lcrdv,
  output  io_sn_txsactive,
  input  io_sn_rxsactive,
  output  io_sn_tx_linkactivereq,
  input  io_sn_tx_linkactiveack,
  output  io_sn_tx_req_flitpend,
  output  io_sn_tx_req_flitv,
  output  [161:0] io_sn_tx_req_flit,
  input  io_sn_tx_req_lcrdv,
  output  io_sn_tx_dat_flitpend,
  output  io_sn_tx_dat_flitv,
  output  [421:0] io_sn_tx_dat_flit,
  input  io_sn_tx_dat_lcrdv,
  input  io_sn_rx_linkactivereq,
  output  io_sn_rx_linkactiveack,
  input  io_sn_rx_rsp_flitpend,
  input  io_sn_rx_rsp_flitv,
  input  [72:0] io_sn_rx_rsp_flit,
  output  io_sn_rx_rsp_lcrdv,
  input  io_sn_rx_dat_flitpend,
  input  io_sn_rx_dat_flitv,
  input  [421:0] io_sn_rx_dat_flit,
  output  io_sn_rx_dat_lcrdv,
  input  io_debugTopDown_robHeadPaddr_0_valid,
  input  [47:0] io_debugTopDown_robHeadPaddr_0_bits,
  output  io_debugTopDown_addrMatch_0,
  output  io_l3Miss
);
  xs_OpenLLC_core u_core (
    .clock(clock),
    .reset(reset),
    .io_rn_0_txsactive(io_rn_0_txsactive),
    .io_rn_0_rxsactive(io_rn_0_rxsactive),
    .io_rn_0_syscoreq(io_rn_0_syscoreq),
    .io_rn_0_syscoack(io_rn_0_syscoack),
    .io_rn_0_tx_linkactivereq(io_rn_0_tx_linkactivereq),
    .io_rn_0_tx_linkactiveack(io_rn_0_tx_linkactiveack),
    .io_rn_0_tx_req_flitpend(io_rn_0_tx_req_flitpend),
    .io_rn_0_tx_req_flitv(io_rn_0_tx_req_flitv),
    .io_rn_0_tx_req_flit(io_rn_0_tx_req_flit),
    .io_rn_0_tx_req_lcrdv(io_rn_0_tx_req_lcrdv),
    .io_rn_0_tx_rsp_flitpend(io_rn_0_tx_rsp_flitpend),
    .io_rn_0_tx_rsp_flitv(io_rn_0_tx_rsp_flitv),
    .io_rn_0_tx_rsp_flit(io_rn_0_tx_rsp_flit),
    .io_rn_0_tx_rsp_lcrdv(io_rn_0_tx_rsp_lcrdv),
    .io_rn_0_tx_dat_flitpend(io_rn_0_tx_dat_flitpend),
    .io_rn_0_tx_dat_flitv(io_rn_0_tx_dat_flitv),
    .io_rn_0_tx_dat_flit(io_rn_0_tx_dat_flit),
    .io_rn_0_tx_dat_lcrdv(io_rn_0_tx_dat_lcrdv),
    .io_rn_0_rx_linkactivereq(io_rn_0_rx_linkactivereq),
    .io_rn_0_rx_linkactiveack(io_rn_0_rx_linkactiveack),
    .io_rn_0_rx_rsp_flitpend(io_rn_0_rx_rsp_flitpend),
    .io_rn_0_rx_rsp_flitv(io_rn_0_rx_rsp_flitv),
    .io_rn_0_rx_rsp_flit(io_rn_0_rx_rsp_flit),
    .io_rn_0_rx_rsp_lcrdv(io_rn_0_rx_rsp_lcrdv),
    .io_rn_0_rx_dat_flitpend(io_rn_0_rx_dat_flitpend),
    .io_rn_0_rx_dat_flitv(io_rn_0_rx_dat_flitv),
    .io_rn_0_rx_dat_flit(io_rn_0_rx_dat_flit),
    .io_rn_0_rx_dat_lcrdv(io_rn_0_rx_dat_lcrdv),
    .io_rn_0_rx_snp_flitpend(io_rn_0_rx_snp_flitpend),
    .io_rn_0_rx_snp_flitv(io_rn_0_rx_snp_flitv),
    .io_rn_0_rx_snp_flit(io_rn_0_rx_snp_flit),
    .io_rn_0_rx_snp_lcrdv(io_rn_0_rx_snp_lcrdv),
    .io_sn_txsactive(io_sn_txsactive),
    .io_sn_rxsactive(io_sn_rxsactive),
    .io_sn_tx_linkactivereq(io_sn_tx_linkactivereq),
    .io_sn_tx_linkactiveack(io_sn_tx_linkactiveack),
    .io_sn_tx_req_flitpend(io_sn_tx_req_flitpend),
    .io_sn_tx_req_flitv(io_sn_tx_req_flitv),
    .io_sn_tx_req_flit(io_sn_tx_req_flit),
    .io_sn_tx_req_lcrdv(io_sn_tx_req_lcrdv),
    .io_sn_tx_dat_flitpend(io_sn_tx_dat_flitpend),
    .io_sn_tx_dat_flitv(io_sn_tx_dat_flitv),
    .io_sn_tx_dat_flit(io_sn_tx_dat_flit),
    .io_sn_tx_dat_lcrdv(io_sn_tx_dat_lcrdv),
    .io_sn_rx_linkactivereq(io_sn_rx_linkactivereq),
    .io_sn_rx_linkactiveack(io_sn_rx_linkactiveack),
    .io_sn_rx_rsp_flitpend(io_sn_rx_rsp_flitpend),
    .io_sn_rx_rsp_flitv(io_sn_rx_rsp_flitv),
    .io_sn_rx_rsp_flit(io_sn_rx_rsp_flit),
    .io_sn_rx_rsp_lcrdv(io_sn_rx_rsp_lcrdv),
    .io_sn_rx_dat_flitpend(io_sn_rx_dat_flitpend),
    .io_sn_rx_dat_flitv(io_sn_rx_dat_flitv),
    .io_sn_rx_dat_flit(io_sn_rx_dat_flit),
    .io_sn_rx_dat_lcrdv(io_sn_rx_dat_lcrdv),
    .io_debugTopDown_robHeadPaddr_0_valid(io_debugTopDown_robHeadPaddr_0_valid),
    .io_debugTopDown_robHeadPaddr_0_bits(io_debugTopDown_robHeadPaddr_0_bits),
    .io_debugTopDown_addrMatch_0(io_debugTopDown_addrMatch_0),
    .io_l3Miss(io_l3Miss)
  );
endmodule
