// 自动生成 scripts/gen_chi_channel.py —— 勿手改
module CHILogger_xs(
  input io_up_txsactive,
  output io_up_rxsactive,
  input io_up_syscoreq,
  output io_up_syscoack,
  input io_up_tx_linkactivereq,
  output io_up_tx_linkactiveack,
  input io_up_tx_req_flitpend,
  input io_up_tx_req_flitv,
  input [161:0] io_up_tx_req_flit,
  output io_up_tx_req_lcrdv,
  input io_up_tx_rsp_flitpend,
  input io_up_tx_rsp_flitv,
  input [72:0] io_up_tx_rsp_flit,
  output io_up_tx_rsp_lcrdv,
  input io_up_tx_dat_flitpend,
  input io_up_tx_dat_flitv,
  input [421:0] io_up_tx_dat_flit,
  output io_up_tx_dat_lcrdv,
  output io_up_rx_linkactivereq,
  input io_up_rx_linkactiveack,
  output io_up_rx_rsp_flitpend,
  output io_up_rx_rsp_flitv,
  output [72:0] io_up_rx_rsp_flit,
  input io_up_rx_rsp_lcrdv,
  output io_up_rx_dat_flitpend,
  output io_up_rx_dat_flitv,
  output [421:0] io_up_rx_dat_flit,
  input io_up_rx_dat_lcrdv,
  output io_up_rx_snp_flitpend,
  output io_up_rx_snp_flitv,
  output [114:0] io_up_rx_snp_flit,
  input io_up_rx_snp_lcrdv,
  output io_down_txsactive,
  input io_down_rxsactive,
  output io_down_syscoreq,
  input io_down_syscoack,
  output io_down_tx_linkactivereq,
  input io_down_tx_linkactiveack,
  output io_down_tx_req_flitpend,
  output io_down_tx_req_flitv,
  output [161:0] io_down_tx_req_flit,
  input io_down_tx_req_lcrdv,
  output io_down_tx_rsp_flitpend,
  output io_down_tx_rsp_flitv,
  output [72:0] io_down_tx_rsp_flit,
  input io_down_tx_rsp_lcrdv,
  output io_down_tx_dat_flitpend,
  output io_down_tx_dat_flitv,
  output [421:0] io_down_tx_dat_flit,
  input io_down_tx_dat_lcrdv,
  input io_down_rx_linkactivereq,
  output io_down_rx_linkactiveack,
  input io_down_rx_rsp_flitpend,
  input io_down_rx_rsp_flitv,
  input [72:0] io_down_rx_rsp_flit,
  output io_down_rx_rsp_lcrdv,
  input io_down_rx_dat_flitpend,
  input io_down_rx_dat_flitv,
  input [421:0] io_down_rx_dat_flit,
  output io_down_rx_dat_lcrdv,
  input io_down_rx_snp_flitpend,
  input io_down_rx_snp_flitv,
  input [114:0] io_down_rx_snp_flit,
  output io_down_rx_snp_lcrdv
);
  xs_CHILogger_core u_core (
    .io_up_txsactive(io_up_txsactive),
    .io_up_rxsactive(io_up_rxsactive),
    .io_up_syscoreq(io_up_syscoreq),
    .io_up_syscoack(io_up_syscoack),
    .io_up_tx_linkactivereq(io_up_tx_linkactivereq),
    .io_up_tx_linkactiveack(io_up_tx_linkactiveack),
    .io_up_tx_req_flitpend(io_up_tx_req_flitpend),
    .io_up_tx_req_flitv(io_up_tx_req_flitv),
    .io_up_tx_req_flit(io_up_tx_req_flit),
    .io_up_tx_req_lcrdv(io_up_tx_req_lcrdv),
    .io_up_tx_rsp_flitpend(io_up_tx_rsp_flitpend),
    .io_up_tx_rsp_flitv(io_up_tx_rsp_flitv),
    .io_up_tx_rsp_flit(io_up_tx_rsp_flit),
    .io_up_tx_rsp_lcrdv(io_up_tx_rsp_lcrdv),
    .io_up_tx_dat_flitpend(io_up_tx_dat_flitpend),
    .io_up_tx_dat_flitv(io_up_tx_dat_flitv),
    .io_up_tx_dat_flit(io_up_tx_dat_flit),
    .io_up_tx_dat_lcrdv(io_up_tx_dat_lcrdv),
    .io_up_rx_linkactivereq(io_up_rx_linkactivereq),
    .io_up_rx_linkactiveack(io_up_rx_linkactiveack),
    .io_up_rx_rsp_flitpend(io_up_rx_rsp_flitpend),
    .io_up_rx_rsp_flitv(io_up_rx_rsp_flitv),
    .io_up_rx_rsp_flit(io_up_rx_rsp_flit),
    .io_up_rx_rsp_lcrdv(io_up_rx_rsp_lcrdv),
    .io_up_rx_dat_flitpend(io_up_rx_dat_flitpend),
    .io_up_rx_dat_flitv(io_up_rx_dat_flitv),
    .io_up_rx_dat_flit(io_up_rx_dat_flit),
    .io_up_rx_dat_lcrdv(io_up_rx_dat_lcrdv),
    .io_up_rx_snp_flitpend(io_up_rx_snp_flitpend),
    .io_up_rx_snp_flitv(io_up_rx_snp_flitv),
    .io_up_rx_snp_flit(io_up_rx_snp_flit),
    .io_up_rx_snp_lcrdv(io_up_rx_snp_lcrdv),
    .io_down_txsactive(io_down_txsactive),
    .io_down_rxsactive(io_down_rxsactive),
    .io_down_syscoreq(io_down_syscoreq),
    .io_down_syscoack(io_down_syscoack),
    .io_down_tx_linkactivereq(io_down_tx_linkactivereq),
    .io_down_tx_linkactiveack(io_down_tx_linkactiveack),
    .io_down_tx_req_flitpend(io_down_tx_req_flitpend),
    .io_down_tx_req_flitv(io_down_tx_req_flitv),
    .io_down_tx_req_flit(io_down_tx_req_flit),
    .io_down_tx_req_lcrdv(io_down_tx_req_lcrdv),
    .io_down_tx_rsp_flitpend(io_down_tx_rsp_flitpend),
    .io_down_tx_rsp_flitv(io_down_tx_rsp_flitv),
    .io_down_tx_rsp_flit(io_down_tx_rsp_flit),
    .io_down_tx_rsp_lcrdv(io_down_tx_rsp_lcrdv),
    .io_down_tx_dat_flitpend(io_down_tx_dat_flitpend),
    .io_down_tx_dat_flitv(io_down_tx_dat_flitv),
    .io_down_tx_dat_flit(io_down_tx_dat_flit),
    .io_down_tx_dat_lcrdv(io_down_tx_dat_lcrdv),
    .io_down_rx_linkactivereq(io_down_rx_linkactivereq),
    .io_down_rx_linkactiveack(io_down_rx_linkactiveack),
    .io_down_rx_rsp_flitpend(io_down_rx_rsp_flitpend),
    .io_down_rx_rsp_flitv(io_down_rx_rsp_flitv),
    .io_down_rx_rsp_flit(io_down_rx_rsp_flit),
    .io_down_rx_rsp_lcrdv(io_down_rx_rsp_lcrdv),
    .io_down_rx_dat_flitpend(io_down_rx_dat_flitpend),
    .io_down_rx_dat_flitv(io_down_rx_dat_flitv),
    .io_down_rx_dat_flit(io_down_rx_dat_flit),
    .io_down_rx_dat_lcrdv(io_down_rx_dat_lcrdv),
    .io_down_rx_snp_flitpend(io_down_rx_snp_flitpend),
    .io_down_rx_snp_flitv(io_down_rx_snp_flitv),
    .io_down_rx_snp_flit(io_down_rx_snp_flit),
    .io_down_rx_snp_lcrdv(io_down_rx_snp_lcrdv)
  );
endmodule
