// 自动生成：scripts/gen_mulunit.py —— 勿手改
module MulUnit_xs(
  input  clock,
  input  reset,
  input  io_in_valid,
  input  [8:0] io_in_bits_ctrl_fuOpType,
  input  io_in_bits_ctrlPipe_2_robIdx_flag,
  input  [7:0] io_in_bits_ctrlPipe_2_robIdx_value,
  input  [7:0] io_in_bits_ctrlPipe_2_pdest,
  input  io_in_bits_ctrlPipe_2_rfWen,
  input  io_in_bits_validPipe_0,
  input  io_in_bits_validPipe_1,
  input  io_in_bits_validPipe_2,
  input  [63:0] io_in_bits_data_src_1,
  input  [63:0] io_in_bits_data_src_0,
  input  [63:0] io_in_bits_perfDebugInfo_enqRsTime,
  input  [63:0] io_in_bits_perfDebugInfo_selectTime,
  input  [63:0] io_in_bits_perfDebugInfo_issueTime,
  output io_out_valid,
  output io_out_bits_ctrl_robIdx_flag,
  output [7:0] io_out_bits_ctrl_robIdx_value,
  output [7:0] io_out_bits_ctrl_pdest,
  output io_out_bits_ctrl_rfWen,
  output [63:0] io_out_bits_res_data,
  output [63:0] io_out_bits_perfDebugInfo_enqRsTime,
  output [63:0] io_out_bits_perfDebugInfo_selectTime,
  output [63:0] io_out_bits_perfDebugInfo_issueTime
);
  xs_MulUnit_core u_core (
    .clock(clock),
    .reset(reset),
    .io_in_valid(io_in_valid),
    .io_in_bits_ctrl_fuOpType(io_in_bits_ctrl_fuOpType),
    .io_in_bits_ctrlPipe_2_robIdx_flag(io_in_bits_ctrlPipe_2_robIdx_flag),
    .io_in_bits_ctrlPipe_2_robIdx_value(io_in_bits_ctrlPipe_2_robIdx_value),
    .io_in_bits_ctrlPipe_2_pdest(io_in_bits_ctrlPipe_2_pdest),
    .io_in_bits_ctrlPipe_2_rfWen(io_in_bits_ctrlPipe_2_rfWen),
    .io_in_bits_validPipe_0(io_in_bits_validPipe_0),
    .io_in_bits_validPipe_1(io_in_bits_validPipe_1),
    .io_in_bits_validPipe_2(io_in_bits_validPipe_2),
    .io_in_bits_data_src_1(io_in_bits_data_src_1),
    .io_in_bits_data_src_0(io_in_bits_data_src_0),
    .io_in_bits_perfDebugInfo_enqRsTime(io_in_bits_perfDebugInfo_enqRsTime),
    .io_in_bits_perfDebugInfo_selectTime(io_in_bits_perfDebugInfo_selectTime),
    .io_in_bits_perfDebugInfo_issueTime(io_in_bits_perfDebugInfo_issueTime),
    .io_out_valid(io_out_valid),
    .io_out_bits_ctrl_robIdx_flag(io_out_bits_ctrl_robIdx_flag),
    .io_out_bits_ctrl_robIdx_value(io_out_bits_ctrl_robIdx_value),
    .io_out_bits_ctrl_pdest(io_out_bits_ctrl_pdest),
    .io_out_bits_ctrl_rfWen(io_out_bits_ctrl_rfWen),
    .io_out_bits_res_data(io_out_bits_res_data),
    .io_out_bits_perfDebugInfo_enqRsTime(io_out_bits_perfDebugInfo_enqRsTime),
    .io_out_bits_perfDebugInfo_selectTime(io_out_bits_perfDebugInfo_selectTime),
    .io_out_bits_perfDebugInfo_issueTime(io_out_bits_perfDebugInfo_issueTime)
  );
endmodule
