// 自动生成：scripts/gen_fastarbiter4.py —— 勿手改
module FastArbiter_5_xs(
  input clock,
  input reset,
  output io_in_0_ready,
  input io_in_0_valid,
  input [10:0] io_in_0_bits_tgtID,
  input [11:0] io_in_0_bits_txnID,
  input io_in_0_bits_traceTag,
  output io_in_1_ready,
  input io_in_1_valid,
  input [10:0] io_in_1_bits_tgtID,
  input [11:0] io_in_1_bits_txnID,
  input io_in_1_bits_traceTag,
  output io_in_2_ready,
  input io_in_2_valid,
  input [10:0] io_in_2_bits_tgtID,
  input [11:0] io_in_2_bits_txnID,
  input io_in_2_bits_traceTag,
  output io_in_3_ready,
  input io_in_3_valid,
  input [10:0] io_in_3_bits_tgtID,
  input [11:0] io_in_3_bits_txnID,
  input io_in_3_bits_traceTag,
  output io_in_4_ready,
  input io_in_4_valid,
  input [10:0] io_in_4_bits_tgtID,
  input [11:0] io_in_4_bits_txnID,
  input io_in_4_bits_traceTag,
  output io_in_5_ready,
  input io_in_5_valid,
  input [10:0] io_in_5_bits_tgtID,
  input [11:0] io_in_5_bits_txnID,
  input io_in_5_bits_traceTag,
  output io_in_6_ready,
  input io_in_6_valid,
  input [10:0] io_in_6_bits_tgtID,
  input [11:0] io_in_6_bits_txnID,
  input io_in_6_bits_traceTag,
  output io_in_7_ready,
  input io_in_7_valid,
  input [10:0] io_in_7_bits_tgtID,
  input [11:0] io_in_7_bits_txnID,
  input io_in_7_bits_traceTag,
  output io_in_8_ready,
  input io_in_8_valid,
  input [10:0] io_in_8_bits_tgtID,
  input [11:0] io_in_8_bits_txnID,
  input io_in_8_bits_traceTag,
  output io_in_9_ready,
  input io_in_9_valid,
  input [10:0] io_in_9_bits_tgtID,
  input [11:0] io_in_9_bits_txnID,
  input io_in_9_bits_traceTag,
  output io_in_10_ready,
  input io_in_10_valid,
  input [10:0] io_in_10_bits_tgtID,
  input [11:0] io_in_10_bits_txnID,
  input io_in_10_bits_traceTag,
  output io_in_11_ready,
  input io_in_11_valid,
  input [10:0] io_in_11_bits_tgtID,
  input [11:0] io_in_11_bits_txnID,
  input io_in_11_bits_traceTag,
  output io_in_12_ready,
  input io_in_12_valid,
  input [10:0] io_in_12_bits_tgtID,
  input [11:0] io_in_12_bits_txnID,
  input io_in_12_bits_traceTag,
  output io_in_13_ready,
  input io_in_13_valid,
  input [10:0] io_in_13_bits_tgtID,
  input [11:0] io_in_13_bits_txnID,
  input io_in_13_bits_traceTag,
  output io_in_14_ready,
  input io_in_14_valid,
  input [10:0] io_in_14_bits_tgtID,
  input [11:0] io_in_14_bits_txnID,
  input io_in_14_bits_traceTag,
  output io_in_15_ready,
  input io_in_15_valid,
  input [10:0] io_in_15_bits_tgtID,
  input [11:0] io_in_15_bits_txnID,
  input io_in_15_bits_traceTag,
  input io_out_ready,
  output io_out_valid,
  output [10:0] io_out_bits_tgtID,
  output [11:0] io_out_bits_txnID,
  output [4:0] io_out_bits_opcode,
  output io_out_bits_traceTag
);
  xs_FastArbiter_5_core u_core (
    .clock(clock),
    .reset(reset),
    .io_in_0_ready(io_in_0_ready),
    .io_in_0_valid(io_in_0_valid),
    .io_in_0_bits_tgtID(io_in_0_bits_tgtID),
    .io_in_0_bits_txnID(io_in_0_bits_txnID),
    .io_in_0_bits_traceTag(io_in_0_bits_traceTag),
    .io_in_1_ready(io_in_1_ready),
    .io_in_1_valid(io_in_1_valid),
    .io_in_1_bits_tgtID(io_in_1_bits_tgtID),
    .io_in_1_bits_txnID(io_in_1_bits_txnID),
    .io_in_1_bits_traceTag(io_in_1_bits_traceTag),
    .io_in_2_ready(io_in_2_ready),
    .io_in_2_valid(io_in_2_valid),
    .io_in_2_bits_tgtID(io_in_2_bits_tgtID),
    .io_in_2_bits_txnID(io_in_2_bits_txnID),
    .io_in_2_bits_traceTag(io_in_2_bits_traceTag),
    .io_in_3_ready(io_in_3_ready),
    .io_in_3_valid(io_in_3_valid),
    .io_in_3_bits_tgtID(io_in_3_bits_tgtID),
    .io_in_3_bits_txnID(io_in_3_bits_txnID),
    .io_in_3_bits_traceTag(io_in_3_bits_traceTag),
    .io_in_4_ready(io_in_4_ready),
    .io_in_4_valid(io_in_4_valid),
    .io_in_4_bits_tgtID(io_in_4_bits_tgtID),
    .io_in_4_bits_txnID(io_in_4_bits_txnID),
    .io_in_4_bits_traceTag(io_in_4_bits_traceTag),
    .io_in_5_ready(io_in_5_ready),
    .io_in_5_valid(io_in_5_valid),
    .io_in_5_bits_tgtID(io_in_5_bits_tgtID),
    .io_in_5_bits_txnID(io_in_5_bits_txnID),
    .io_in_5_bits_traceTag(io_in_5_bits_traceTag),
    .io_in_6_ready(io_in_6_ready),
    .io_in_6_valid(io_in_6_valid),
    .io_in_6_bits_tgtID(io_in_6_bits_tgtID),
    .io_in_6_bits_txnID(io_in_6_bits_txnID),
    .io_in_6_bits_traceTag(io_in_6_bits_traceTag),
    .io_in_7_ready(io_in_7_ready),
    .io_in_7_valid(io_in_7_valid),
    .io_in_7_bits_tgtID(io_in_7_bits_tgtID),
    .io_in_7_bits_txnID(io_in_7_bits_txnID),
    .io_in_7_bits_traceTag(io_in_7_bits_traceTag),
    .io_in_8_ready(io_in_8_ready),
    .io_in_8_valid(io_in_8_valid),
    .io_in_8_bits_tgtID(io_in_8_bits_tgtID),
    .io_in_8_bits_txnID(io_in_8_bits_txnID),
    .io_in_8_bits_traceTag(io_in_8_bits_traceTag),
    .io_in_9_ready(io_in_9_ready),
    .io_in_9_valid(io_in_9_valid),
    .io_in_9_bits_tgtID(io_in_9_bits_tgtID),
    .io_in_9_bits_txnID(io_in_9_bits_txnID),
    .io_in_9_bits_traceTag(io_in_9_bits_traceTag),
    .io_in_10_ready(io_in_10_ready),
    .io_in_10_valid(io_in_10_valid),
    .io_in_10_bits_tgtID(io_in_10_bits_tgtID),
    .io_in_10_bits_txnID(io_in_10_bits_txnID),
    .io_in_10_bits_traceTag(io_in_10_bits_traceTag),
    .io_in_11_ready(io_in_11_ready),
    .io_in_11_valid(io_in_11_valid),
    .io_in_11_bits_tgtID(io_in_11_bits_tgtID),
    .io_in_11_bits_txnID(io_in_11_bits_txnID),
    .io_in_11_bits_traceTag(io_in_11_bits_traceTag),
    .io_in_12_ready(io_in_12_ready),
    .io_in_12_valid(io_in_12_valid),
    .io_in_12_bits_tgtID(io_in_12_bits_tgtID),
    .io_in_12_bits_txnID(io_in_12_bits_txnID),
    .io_in_12_bits_traceTag(io_in_12_bits_traceTag),
    .io_in_13_ready(io_in_13_ready),
    .io_in_13_valid(io_in_13_valid),
    .io_in_13_bits_tgtID(io_in_13_bits_tgtID),
    .io_in_13_bits_txnID(io_in_13_bits_txnID),
    .io_in_13_bits_traceTag(io_in_13_bits_traceTag),
    .io_in_14_ready(io_in_14_ready),
    .io_in_14_valid(io_in_14_valid),
    .io_in_14_bits_tgtID(io_in_14_bits_tgtID),
    .io_in_14_bits_txnID(io_in_14_bits_txnID),
    .io_in_14_bits_traceTag(io_in_14_bits_traceTag),
    .io_in_15_ready(io_in_15_ready),
    .io_in_15_valid(io_in_15_valid),
    .io_in_15_bits_tgtID(io_in_15_bits_tgtID),
    .io_in_15_bits_txnID(io_in_15_bits_txnID),
    .io_in_15_bits_traceTag(io_in_15_bits_traceTag),
    .io_out_ready(io_out_ready),
    .io_out_valid(io_out_valid),
    .io_out_bits_tgtID(io_out_bits_tgtID),
    .io_out_bits_txnID(io_out_bits_txnID),
    .io_out_bits_opcode(io_out_bits_opcode),
    .io_out_bits_traceTag(io_out_bits_traceTag)
  );
endmodule
