// 自动生成: gen_l2cache_ut.py —— L2Cache_xs (UT 变体, 例化可读核 xs_L2Cache_core)
module L2Cache_xs(
  input clock,
  input reset,
  input [5:0] mbist_array,
  input mbist_all,
  input mbist_req,
  output mbist_ack,
  input mbist_writeen,
  input [7:0] mbist_be,
  input [12:0] mbist_addr,
  input [103:0] mbist_indata,
  input mbist_readen,
  input [12:0] mbist_addr_rd,
  output [103:0] mbist_outdata,
  output toNextPipeline_0_array,
  output toNextPipeline_0_all,
  output toNextPipeline_0_req,
  input toNextPipeline_0_ack,
  output toNextPipeline_0_writeen,
  output toNextPipeline_0_be,
  output [8:0] toNextPipeline_0_addr,
  output [12:0] toNextPipeline_0_indata,
  output toNextPipeline_0_readen,
  output [8:0] toNextPipeline_0_addr_rd,
  input [12:0] toNextPipeline_0_outdata,
  output [4:0] toNextPipeline_1_array,
  output toNextPipeline_1_all,
  output toNextPipeline_1_req,
  input toNextPipeline_1_ack,
  output toNextPipeline_1_writeen,
  output [7:0] toNextPipeline_1_be,
  output [12:0] toNextPipeline_1_addr,
  output [103:0] toNextPipeline_1_indata,
  output toNextPipeline_1_readen,
  output [12:0] toNextPipeline_1_addr_rd,
  input [103:0] toNextPipeline_1_outdata,
  output [4:0] toNextPipeline_2_array,
  output toNextPipeline_2_all,
  output toNextPipeline_2_req,
  input toNextPipeline_2_ack,
  output toNextPipeline_2_writeen,
  output [7:0] toNextPipeline_2_be,
  output [12:0] toNextPipeline_2_addr,
  output [103:0] toNextPipeline_2_indata,
  output toNextPipeline_2_readen,
  output [12:0] toNextPipeline_2_addr_rd,
  input [103:0] toNextPipeline_2_outdata,
  output [5:0] toNextPipeline_3_array,
  output toNextPipeline_3_all,
  output toNextPipeline_3_req,
  input toNextPipeline_3_ack,
  output toNextPipeline_3_writeen,
  output [7:0] toNextPipeline_3_be,
  output [12:0] toNextPipeline_3_addr,
  output [103:0] toNextPipeline_3_indata,
  output toNextPipeline_3_readen,
  output [12:0] toNextPipeline_3_addr_rd,
  input [103:0] toNextPipeline_3_outdata,
  output [5:0] toNextPipeline_4_array,
  output toNextPipeline_4_all,
  output toNextPipeline_4_req,
  input toNextPipeline_4_ack,
  output toNextPipeline_4_writeen,
  output [7:0] toNextPipeline_4_be,
  output [12:0] toNextPipeline_4_addr,
  output [103:0] toNextPipeline_4_indata,
  output toNextPipeline_4_readen,
  output [12:0] toNextPipeline_4_addr_rd,
  input [103:0] toNextPipeline_4_outdata
);
  xs_L2Cache_core u_core (
    .clock(clock),
    .reset(reset),
    .mbist_array(mbist_array),
    .mbist_all(mbist_all),
    .mbist_req(mbist_req),
    .mbist_ack(mbist_ack),
    .mbist_writeen(mbist_writeen),
    .mbist_be(mbist_be),
    .mbist_addr(mbist_addr),
    .mbist_indata(mbist_indata),
    .mbist_readen(mbist_readen),
    .mbist_addr_rd(mbist_addr_rd),
    .mbist_outdata(mbist_outdata),
    .toNextPipeline_0_array(toNextPipeline_0_array),
    .toNextPipeline_0_all(toNextPipeline_0_all),
    .toNextPipeline_0_req(toNextPipeline_0_req),
    .toNextPipeline_0_ack(toNextPipeline_0_ack),
    .toNextPipeline_0_writeen(toNextPipeline_0_writeen),
    .toNextPipeline_0_be(toNextPipeline_0_be),
    .toNextPipeline_0_addr(toNextPipeline_0_addr),
    .toNextPipeline_0_indata(toNextPipeline_0_indata),
    .toNextPipeline_0_readen(toNextPipeline_0_readen),
    .toNextPipeline_0_addr_rd(toNextPipeline_0_addr_rd),
    .toNextPipeline_0_outdata(toNextPipeline_0_outdata),
    .toNextPipeline_1_array(toNextPipeline_1_array),
    .toNextPipeline_1_all(toNextPipeline_1_all),
    .toNextPipeline_1_req(toNextPipeline_1_req),
    .toNextPipeline_1_ack(toNextPipeline_1_ack),
    .toNextPipeline_1_writeen(toNextPipeline_1_writeen),
    .toNextPipeline_1_be(toNextPipeline_1_be),
    .toNextPipeline_1_addr(toNextPipeline_1_addr),
    .toNextPipeline_1_indata(toNextPipeline_1_indata),
    .toNextPipeline_1_readen(toNextPipeline_1_readen),
    .toNextPipeline_1_addr_rd(toNextPipeline_1_addr_rd),
    .toNextPipeline_1_outdata(toNextPipeline_1_outdata),
    .toNextPipeline_2_array(toNextPipeline_2_array),
    .toNextPipeline_2_all(toNextPipeline_2_all),
    .toNextPipeline_2_req(toNextPipeline_2_req),
    .toNextPipeline_2_ack(toNextPipeline_2_ack),
    .toNextPipeline_2_writeen(toNextPipeline_2_writeen),
    .toNextPipeline_2_be(toNextPipeline_2_be),
    .toNextPipeline_2_addr(toNextPipeline_2_addr),
    .toNextPipeline_2_indata(toNextPipeline_2_indata),
    .toNextPipeline_2_readen(toNextPipeline_2_readen),
    .toNextPipeline_2_addr_rd(toNextPipeline_2_addr_rd),
    .toNextPipeline_2_outdata(toNextPipeline_2_outdata),
    .toNextPipeline_3_array(toNextPipeline_3_array),
    .toNextPipeline_3_all(toNextPipeline_3_all),
    .toNextPipeline_3_req(toNextPipeline_3_req),
    .toNextPipeline_3_ack(toNextPipeline_3_ack),
    .toNextPipeline_3_writeen(toNextPipeline_3_writeen),
    .toNextPipeline_3_be(toNextPipeline_3_be),
    .toNextPipeline_3_addr(toNextPipeline_3_addr),
    .toNextPipeline_3_indata(toNextPipeline_3_indata),
    .toNextPipeline_3_readen(toNextPipeline_3_readen),
    .toNextPipeline_3_addr_rd(toNextPipeline_3_addr_rd),
    .toNextPipeline_3_outdata(toNextPipeline_3_outdata),
    .toNextPipeline_4_array(toNextPipeline_4_array),
    .toNextPipeline_4_all(toNextPipeline_4_all),
    .toNextPipeline_4_req(toNextPipeline_4_req),
    .toNextPipeline_4_ack(toNextPipeline_4_ack),
    .toNextPipeline_4_writeen(toNextPipeline_4_writeen),
    .toNextPipeline_4_be(toNextPipeline_4_be),
    .toNextPipeline_4_addr(toNextPipeline_4_addr),
    .toNextPipeline_4_indata(toNextPipeline_4_indata),
    .toNextPipeline_4_readen(toNextPipeline_4_readen),
    .toNextPipeline_4_addr_rd(toNextPipeline_4_addr_rd),
    .toNextPipeline_4_outdata(toNextPipeline_4_outdata)
  );
endmodule
