// SCTable _xs 同体副本（UT 双例化用，逻辑与同名 golden 包装层一致）

module SCTable_xs(
  input         clock,
  input         reset,
  input         io_req_valid,
  input  [49:0] io_req_bits_pc,
  output [5:0]  io_resp_ctrs_0_0,
  output [5:0]  io_resp_ctrs_0_1,
  output [5:0]  io_resp_ctrs_1_0,
  output [5:0]  io_resp_ctrs_1_1,
  input  [49:0] io_update_pc,
  input         io_update_mask_0,
  input         io_update_mask_1,
  input  [5:0]  io_update_oldCtrs_0,
  input  [5:0]  io_update_oldCtrs_1,
  input         io_update_tagePreds_0,
  input         io_update_tagePreds_1,
  input         io_update_takens_0,
  input         io_update_takens_1,
  input  [6:0]  boreChildrenBd_bore_array,
  input         boreChildrenBd_bore_all,
  input         boreChildrenBd_bore_req,
  output        boreChildrenBd_bore_ack,
  input         boreChildrenBd_bore_writeen,
  input  [3:0]  boreChildrenBd_bore_be,
  input  [8:0]  boreChildrenBd_bore_addr,
  input  [23:0] boreChildrenBd_bore_indata,
  input         boreChildrenBd_bore_readen,
  input  [8:0]  boreChildrenBd_bore_addr_rd,
  output [23:0] boreChildrenBd_bore_outdata,
  input         sigFromSrams_bore_ram_hold,
  input         sigFromSrams_bore_ram_bypass,
  input         sigFromSrams_bore_ram_bp_clken,
  input         sigFromSrams_bore_ram_aux_clk,
  input         sigFromSrams_bore_ram_aux_ckbp,
  input         sigFromSrams_bore_ram_mcp_hold,
  input         sigFromSrams_bore_cgen
);
  xs_SCTable_core #(
    .IDX_SCHEME(0), .HIST_W(1), .MBIST_ARRAY_ID(7'h42)
  ) u_core (
    .clock(clock), .reset(reset),
    .io_req_valid(io_req_valid),
    .io_req_bits_pc(io_req_bits_pc),
    .io_req_folded_hist(1'b0),
    .io_resp_ctrs_0_0(io_resp_ctrs_0_0),
    .io_resp_ctrs_0_1(io_resp_ctrs_0_1),
    .io_resp_ctrs_1_0(io_resp_ctrs_1_0),
    .io_resp_ctrs_1_1(io_resp_ctrs_1_1),
    .io_update_pc(io_update_pc),
    .io_update_ghist(256'h0),
    .io_update_mask_0(io_update_mask_0),
    .io_update_mask_1(io_update_mask_1),
    .io_update_oldCtrs_0(io_update_oldCtrs_0),
    .io_update_oldCtrs_1(io_update_oldCtrs_1),
    .io_update_tagePreds_0(io_update_tagePreds_0),
    .io_update_tagePreds_1(io_update_tagePreds_1),
    .io_update_takens_0(io_update_takens_0),
    .io_update_takens_1(io_update_takens_1),
    .boreChildrenBd_bore_array(boreChildrenBd_bore_array),
    .boreChildrenBd_bore_all(boreChildrenBd_bore_all),
    .boreChildrenBd_bore_req(boreChildrenBd_bore_req),
    .boreChildrenBd_bore_ack(boreChildrenBd_bore_ack),
    .boreChildrenBd_bore_writeen(boreChildrenBd_bore_writeen),
    .boreChildrenBd_bore_be(boreChildrenBd_bore_be),
    .boreChildrenBd_bore_addr(boreChildrenBd_bore_addr),
    .boreChildrenBd_bore_indata(boreChildrenBd_bore_indata),
    .boreChildrenBd_bore_readen(boreChildrenBd_bore_readen),
    .boreChildrenBd_bore_addr_rd(boreChildrenBd_bore_addr_rd),
    .boreChildrenBd_bore_outdata(boreChildrenBd_bore_outdata),
    .sigFromSrams_bore_ram_hold(sigFromSrams_bore_ram_hold),
    .sigFromSrams_bore_ram_bypass(sigFromSrams_bore_ram_bypass),
    .sigFromSrams_bore_ram_bp_clken(sigFromSrams_bore_ram_bp_clken),
    .sigFromSrams_bore_ram_aux_clk(sigFromSrams_bore_ram_aux_clk),
    .sigFromSrams_bore_ram_aux_ckbp(sigFromSrams_bore_ram_aux_ckbp),
    .sigFromSrams_bore_ram_mcp_hold(sigFromSrams_bore_ram_mcp_hold),
    .sigFromSrams_bore_cgen(sigFromSrams_bore_cgen)
  );
endmodule

module SCTable_1_xs(
  input         clock,
  input         reset,
  input         io_req_valid,
  input  [49:0] io_req_bits_pc,
  input  [3:0] io_req_bits_folded_hist_hist_12_folded_hist,
  output [5:0]  io_resp_ctrs_0_0,
  output [5:0]  io_resp_ctrs_0_1,
  output [5:0]  io_resp_ctrs_1_0,
  output [5:0]  io_resp_ctrs_1_1,
  input  [49:0] io_update_pc,
  input  [255:0] io_update_ghist,
  input         io_update_mask_0,
  input         io_update_mask_1,
  input  [5:0]  io_update_oldCtrs_0,
  input  [5:0]  io_update_oldCtrs_1,
  input         io_update_tagePreds_0,
  input         io_update_tagePreds_1,
  input         io_update_takens_0,
  input         io_update_takens_1,
  input  [6:0]  boreChildrenBd_bore_array,
  input         boreChildrenBd_bore_all,
  input         boreChildrenBd_bore_req,
  output        boreChildrenBd_bore_ack,
  input         boreChildrenBd_bore_writeen,
  input  [3:0]  boreChildrenBd_bore_be,
  input  [8:0]  boreChildrenBd_bore_addr,
  input  [23:0] boreChildrenBd_bore_indata,
  input         boreChildrenBd_bore_readen,
  input  [8:0]  boreChildrenBd_bore_addr_rd,
  output [23:0] boreChildrenBd_bore_outdata,
  input         sigFromSrams_bore_ram_hold,
  input         sigFromSrams_bore_ram_bypass,
  input         sigFromSrams_bore_ram_bp_clken,
  input         sigFromSrams_bore_ram_aux_clk,
  input         sigFromSrams_bore_ram_aux_ckbp,
  input         sigFromSrams_bore_ram_mcp_hold,
  input         sigFromSrams_bore_cgen
);
  xs_SCTable_core #(
    .IDX_SCHEME(1), .HIST_W(4), .MBIST_ARRAY_ID(7'h43)
  ) u_core (
    .clock(clock), .reset(reset),
    .io_req_valid(io_req_valid),
    .io_req_bits_pc(io_req_bits_pc),
    .io_req_folded_hist(io_req_bits_folded_hist_hist_12_folded_hist),
    .io_resp_ctrs_0_0(io_resp_ctrs_0_0),
    .io_resp_ctrs_0_1(io_resp_ctrs_0_1),
    .io_resp_ctrs_1_0(io_resp_ctrs_1_0),
    .io_resp_ctrs_1_1(io_resp_ctrs_1_1),
    .io_update_pc(io_update_pc),
    .io_update_ghist(io_update_ghist),
    .io_update_mask_0(io_update_mask_0),
    .io_update_mask_1(io_update_mask_1),
    .io_update_oldCtrs_0(io_update_oldCtrs_0),
    .io_update_oldCtrs_1(io_update_oldCtrs_1),
    .io_update_tagePreds_0(io_update_tagePreds_0),
    .io_update_tagePreds_1(io_update_tagePreds_1),
    .io_update_takens_0(io_update_takens_0),
    .io_update_takens_1(io_update_takens_1),
    .boreChildrenBd_bore_array(boreChildrenBd_bore_array),
    .boreChildrenBd_bore_all(boreChildrenBd_bore_all),
    .boreChildrenBd_bore_req(boreChildrenBd_bore_req),
    .boreChildrenBd_bore_ack(boreChildrenBd_bore_ack),
    .boreChildrenBd_bore_writeen(boreChildrenBd_bore_writeen),
    .boreChildrenBd_bore_be(boreChildrenBd_bore_be),
    .boreChildrenBd_bore_addr(boreChildrenBd_bore_addr),
    .boreChildrenBd_bore_indata(boreChildrenBd_bore_indata),
    .boreChildrenBd_bore_readen(boreChildrenBd_bore_readen),
    .boreChildrenBd_bore_addr_rd(boreChildrenBd_bore_addr_rd),
    .boreChildrenBd_bore_outdata(boreChildrenBd_bore_outdata),
    .sigFromSrams_bore_ram_hold(sigFromSrams_bore_ram_hold),
    .sigFromSrams_bore_ram_bypass(sigFromSrams_bore_ram_bypass),
    .sigFromSrams_bore_ram_bp_clken(sigFromSrams_bore_ram_bp_clken),
    .sigFromSrams_bore_ram_aux_clk(sigFromSrams_bore_ram_aux_clk),
    .sigFromSrams_bore_ram_aux_ckbp(sigFromSrams_bore_ram_aux_ckbp),
    .sigFromSrams_bore_ram_mcp_hold(sigFromSrams_bore_ram_mcp_hold),
    .sigFromSrams_bore_cgen(sigFromSrams_bore_cgen)
  );
endmodule

module SCTable_2_xs(
  input         clock,
  input         reset,
  input         io_req_valid,
  input  [49:0] io_req_bits_pc,
  input  [7:0] io_req_bits_folded_hist_hist_11_folded_hist,
  output [5:0]  io_resp_ctrs_0_0,
  output [5:0]  io_resp_ctrs_0_1,
  output [5:0]  io_resp_ctrs_1_0,
  output [5:0]  io_resp_ctrs_1_1,
  input  [49:0] io_update_pc,
  input  [255:0] io_update_ghist,
  input         io_update_mask_0,
  input         io_update_mask_1,
  input  [5:0]  io_update_oldCtrs_0,
  input  [5:0]  io_update_oldCtrs_1,
  input         io_update_tagePreds_0,
  input         io_update_tagePreds_1,
  input         io_update_takens_0,
  input         io_update_takens_1,
  input  [6:0]  boreChildrenBd_bore_array,
  input         boreChildrenBd_bore_all,
  input         boreChildrenBd_bore_req,
  output        boreChildrenBd_bore_ack,
  input         boreChildrenBd_bore_writeen,
  input  [3:0]  boreChildrenBd_bore_be,
  input  [8:0]  boreChildrenBd_bore_addr,
  input  [23:0] boreChildrenBd_bore_indata,
  input         boreChildrenBd_bore_readen,
  input  [8:0]  boreChildrenBd_bore_addr_rd,
  output [23:0] boreChildrenBd_bore_outdata,
  input         sigFromSrams_bore_ram_hold,
  input         sigFromSrams_bore_ram_bypass,
  input         sigFromSrams_bore_ram_bp_clken,
  input         sigFromSrams_bore_ram_aux_clk,
  input         sigFromSrams_bore_ram_aux_ckbp,
  input         sigFromSrams_bore_ram_mcp_hold,
  input         sigFromSrams_bore_cgen
);
  xs_SCTable_core #(
    .IDX_SCHEME(2), .HIST_W(8), .MBIST_ARRAY_ID(7'h44)
  ) u_core (
    .clock(clock), .reset(reset),
    .io_req_valid(io_req_valid),
    .io_req_bits_pc(io_req_bits_pc),
    .io_req_folded_hist(io_req_bits_folded_hist_hist_11_folded_hist),
    .io_resp_ctrs_0_0(io_resp_ctrs_0_0),
    .io_resp_ctrs_0_1(io_resp_ctrs_0_1),
    .io_resp_ctrs_1_0(io_resp_ctrs_1_0),
    .io_resp_ctrs_1_1(io_resp_ctrs_1_1),
    .io_update_pc(io_update_pc),
    .io_update_ghist(io_update_ghist),
    .io_update_mask_0(io_update_mask_0),
    .io_update_mask_1(io_update_mask_1),
    .io_update_oldCtrs_0(io_update_oldCtrs_0),
    .io_update_oldCtrs_1(io_update_oldCtrs_1),
    .io_update_tagePreds_0(io_update_tagePreds_0),
    .io_update_tagePreds_1(io_update_tagePreds_1),
    .io_update_takens_0(io_update_takens_0),
    .io_update_takens_1(io_update_takens_1),
    .boreChildrenBd_bore_array(boreChildrenBd_bore_array),
    .boreChildrenBd_bore_all(boreChildrenBd_bore_all),
    .boreChildrenBd_bore_req(boreChildrenBd_bore_req),
    .boreChildrenBd_bore_ack(boreChildrenBd_bore_ack),
    .boreChildrenBd_bore_writeen(boreChildrenBd_bore_writeen),
    .boreChildrenBd_bore_be(boreChildrenBd_bore_be),
    .boreChildrenBd_bore_addr(boreChildrenBd_bore_addr),
    .boreChildrenBd_bore_indata(boreChildrenBd_bore_indata),
    .boreChildrenBd_bore_readen(boreChildrenBd_bore_readen),
    .boreChildrenBd_bore_addr_rd(boreChildrenBd_bore_addr_rd),
    .boreChildrenBd_bore_outdata(boreChildrenBd_bore_outdata),
    .sigFromSrams_bore_ram_hold(sigFromSrams_bore_ram_hold),
    .sigFromSrams_bore_ram_bypass(sigFromSrams_bore_ram_bypass),
    .sigFromSrams_bore_ram_bp_clken(sigFromSrams_bore_ram_bp_clken),
    .sigFromSrams_bore_ram_aux_clk(sigFromSrams_bore_ram_aux_clk),
    .sigFromSrams_bore_ram_aux_ckbp(sigFromSrams_bore_ram_aux_ckbp),
    .sigFromSrams_bore_ram_mcp_hold(sigFromSrams_bore_ram_mcp_hold),
    .sigFromSrams_bore_cgen(sigFromSrams_bore_cgen)
  );
endmodule

module SCTable_3_xs(
  input         clock,
  input         reset,
  input         io_req_valid,
  input  [49:0] io_req_bits_pc,
  input  [7:0] io_req_bits_folded_hist_hist_2_folded_hist,
  output [5:0]  io_resp_ctrs_0_0,
  output [5:0]  io_resp_ctrs_0_1,
  output [5:0]  io_resp_ctrs_1_0,
  output [5:0]  io_resp_ctrs_1_1,
  input  [49:0] io_update_pc,
  input  [255:0] io_update_ghist,
  input         io_update_mask_0,
  input         io_update_mask_1,
  input  [5:0]  io_update_oldCtrs_0,
  input  [5:0]  io_update_oldCtrs_1,
  input         io_update_tagePreds_0,
  input         io_update_tagePreds_1,
  input         io_update_takens_0,
  input         io_update_takens_1,
  input  [6:0]  boreChildrenBd_bore_array,
  input         boreChildrenBd_bore_all,
  input         boreChildrenBd_bore_req,
  output        boreChildrenBd_bore_ack,
  input         boreChildrenBd_bore_writeen,
  input  [3:0]  boreChildrenBd_bore_be,
  input  [8:0]  boreChildrenBd_bore_addr,
  input  [23:0] boreChildrenBd_bore_indata,
  input         boreChildrenBd_bore_readen,
  input  [8:0]  boreChildrenBd_bore_addr_rd,
  output [23:0] boreChildrenBd_bore_outdata,
  input         sigFromSrams_bore_ram_hold,
  input         sigFromSrams_bore_ram_bypass,
  input         sigFromSrams_bore_ram_bp_clken,
  input         sigFromSrams_bore_ram_aux_clk,
  input         sigFromSrams_bore_ram_aux_ckbp,
  input         sigFromSrams_bore_ram_mcp_hold,
  input         sigFromSrams_bore_cgen
);
  xs_SCTable_core #(
    .IDX_SCHEME(3), .HIST_W(8), .MBIST_ARRAY_ID(7'h45)
  ) u_core (
    .clock(clock), .reset(reset),
    .io_req_valid(io_req_valid),
    .io_req_bits_pc(io_req_bits_pc),
    .io_req_folded_hist(io_req_bits_folded_hist_hist_2_folded_hist),
    .io_resp_ctrs_0_0(io_resp_ctrs_0_0),
    .io_resp_ctrs_0_1(io_resp_ctrs_0_1),
    .io_resp_ctrs_1_0(io_resp_ctrs_1_0),
    .io_resp_ctrs_1_1(io_resp_ctrs_1_1),
    .io_update_pc(io_update_pc),
    .io_update_ghist(io_update_ghist),
    .io_update_mask_0(io_update_mask_0),
    .io_update_mask_1(io_update_mask_1),
    .io_update_oldCtrs_0(io_update_oldCtrs_0),
    .io_update_oldCtrs_1(io_update_oldCtrs_1),
    .io_update_tagePreds_0(io_update_tagePreds_0),
    .io_update_tagePreds_1(io_update_tagePreds_1),
    .io_update_takens_0(io_update_takens_0),
    .io_update_takens_1(io_update_takens_1),
    .boreChildrenBd_bore_array(boreChildrenBd_bore_array),
    .boreChildrenBd_bore_all(boreChildrenBd_bore_all),
    .boreChildrenBd_bore_req(boreChildrenBd_bore_req),
    .boreChildrenBd_bore_ack(boreChildrenBd_bore_ack),
    .boreChildrenBd_bore_writeen(boreChildrenBd_bore_writeen),
    .boreChildrenBd_bore_be(boreChildrenBd_bore_be),
    .boreChildrenBd_bore_addr(boreChildrenBd_bore_addr),
    .boreChildrenBd_bore_indata(boreChildrenBd_bore_indata),
    .boreChildrenBd_bore_readen(boreChildrenBd_bore_readen),
    .boreChildrenBd_bore_addr_rd(boreChildrenBd_bore_addr_rd),
    .boreChildrenBd_bore_outdata(boreChildrenBd_bore_outdata),
    .sigFromSrams_bore_ram_hold(sigFromSrams_bore_ram_hold),
    .sigFromSrams_bore_ram_bypass(sigFromSrams_bore_ram_bypass),
    .sigFromSrams_bore_ram_bp_clken(sigFromSrams_bore_ram_bp_clken),
    .sigFromSrams_bore_ram_aux_clk(sigFromSrams_bore_ram_aux_clk),
    .sigFromSrams_bore_ram_aux_ckbp(sigFromSrams_bore_ram_aux_ckbp),
    .sigFromSrams_bore_ram_mcp_hold(sigFromSrams_bore_ram_mcp_hold),
    .sigFromSrams_bore_cgen(sigFromSrams_bore_cgen)
  );
endmodule

