// 自动生成 scripts/gen_chi_channel.py —— 勿手改
module Decoupled2LCredit_2_xs(
  input clock,
  input reset,
  output io_in_ready,
  input io_in_valid,
  input [3:0] io_in_bits_qos,
  input [10:0] io_in_bits_tgtID,
  input [10:0] io_in_bits_srcID,
  input [11:0] io_in_bits_txnID,
  input [10:0] io_in_bits_homeNID,
  input [3:0] io_in_bits_opcode,
  input [1:0] io_in_bits_respErr,
  input [2:0] io_in_bits_resp,
  input [3:0] io_in_bits_dataSource,
  input [2:0] io_in_bits_cBusy,
  input [11:0] io_in_bits_dbID,
  input [1:0] io_in_bits_ccID,
  input [1:0] io_in_bits_dataID,
  input [1:0] io_in_bits_tagOp,
  input [7:0] io_in_bits_tag,
  input [1:0] io_in_bits_tu,
  input io_in_bits_traceTag,
  input [3:0] io_in_bits_rsvdc,
  input [31:0] io_in_bits_be,
  input [255:0] io_in_bits_data,
  input [31:0] io_in_bits_dataCheck,
  input [3:0] io_in_bits_poison,
  output io_out_flitpend,
  output io_out_flitv,
  output [421:0] io_out_flit,
  input io_out_lcrdv,
  input [1:0] io_state_state
);
  xs_Decoupled2LCredit_2_core u_core (
    .clock(clock),
    .reset(reset),
    .io_in_ready(io_in_ready),
    .io_in_valid(io_in_valid),
    .io_in_bits_qos(io_in_bits_qos),
    .io_in_bits_tgtID(io_in_bits_tgtID),
    .io_in_bits_srcID(io_in_bits_srcID),
    .io_in_bits_txnID(io_in_bits_txnID),
    .io_in_bits_homeNID(io_in_bits_homeNID),
    .io_in_bits_opcode(io_in_bits_opcode),
    .io_in_bits_respErr(io_in_bits_respErr),
    .io_in_bits_resp(io_in_bits_resp),
    .io_in_bits_dataSource(io_in_bits_dataSource),
    .io_in_bits_cBusy(io_in_bits_cBusy),
    .io_in_bits_dbID(io_in_bits_dbID),
    .io_in_bits_ccID(io_in_bits_ccID),
    .io_in_bits_dataID(io_in_bits_dataID),
    .io_in_bits_tagOp(io_in_bits_tagOp),
    .io_in_bits_tag(io_in_bits_tag),
    .io_in_bits_tu(io_in_bits_tu),
    .io_in_bits_traceTag(io_in_bits_traceTag),
    .io_in_bits_rsvdc(io_in_bits_rsvdc),
    .io_in_bits_be(io_in_bits_be),
    .io_in_bits_data(io_in_bits_data),
    .io_in_bits_dataCheck(io_in_bits_dataCheck),
    .io_in_bits_poison(io_in_bits_poison),
    .io_out_flitpend(io_out_flitpend),
    .io_out_flitv(io_out_flitv),
    .io_out_flit(io_out_flit),
    .io_out_lcrdv(io_out_lcrdv),
    .io_state_state(io_state_state)
  );
endmodule
