// 自动生成:scripts/gen_scheduler_variants.py —— 勿手改
// =============================================================================
// Scheduler_2 —— 香山 V2R2 Vf Scheduler 可读核(golden 同名顶层)
// 设计源:src/main/scala/xiangshan/backend/issue/Scheduler.scala
//        golden:Scheduler_2.sv
//
// 见 scripts/gen_scheduler_variants.py 头部「设计意图 / 重写方式」。
// 本核做四件可读的事:
//   A) 例化 3 个 IssueQueue 并互联(唤醒网络/响应/cancel,机械连线在 .svh);
//   B) dispatch-ready 透传:把各 IQ 的 enq0.ready 回送给 fromDispatch.uops.ready;
//   C) deqDelay 输出扇出:各 IQ 的 deqDelay_0_valid 引到对应 toDataPathAfterDelay;
//   D) 发射 perf 统计:enq_fire popcount + 各 IQ full 位,两级 RegNext 后输出。
// =============================================================================
module Scheduler_2_xs import scheduler_vf_pkg::*; (
  input         clock,
  input         reset,
  input  [2:0] io_fromWbFuBusyTable_fuBusyTableRead_1_1_fpWbBusyTable,
  input  [2:0] io_fromWbFuBusyTable_fuBusyTableRead_1_1_vfWbBusyTable,
  input  [2:0] io_fromWbFuBusyTable_fuBusyTableRead_1_1_v0WbBusyTable,
  input  [4:0] io_fromWbFuBusyTable_fuBusyTableRead_1_0_vfWbBusyTable,
  input  [4:0] io_fromWbFuBusyTable_fuBusyTableRead_1_0_v0WbBusyTable,
  input  [4:0] io_fromWbFuBusyTable_fuBusyTableRead_0_1_intWbBusyTable,
  input  [2:0] io_fromWbFuBusyTable_fuBusyTableRead_0_1_fpWbBusyTable,
  input  [3:0] io_fromWbFuBusyTable_fuBusyTableRead_0_1_vfWbBusyTable,
  input  [3:0] io_fromWbFuBusyTable_fuBusyTableRead_0_1_v0WbBusyTable,
  input  [1:0] io_fromWbFuBusyTable_fuBusyTableRead_0_1_vlWbBusyTable,
  input  [4:0] io_fromWbFuBusyTable_fuBusyTableRead_0_0_vfWbBusyTable,
  input  [4:0] io_fromWbFuBusyTable_fuBusyTableRead_0_0_v0WbBusyTable,
  output [2:0] io_wbFuBusyTable_1_1_fpWbBusyTable,
  output [2:0] io_wbFuBusyTable_1_1_vfWbBusyTable,
  output [2:0] io_wbFuBusyTable_1_1_v0WbBusyTable,
  output [4:0] io_wbFuBusyTable_1_0_vfWbBusyTable,
  output [4:0] io_wbFuBusyTable_1_0_v0WbBusyTable,
  output [4:0] io_wbFuBusyTable_0_1_intWbBusyTable,
  output [2:0] io_wbFuBusyTable_0_1_fpWbBusyTable,
  output [3:0] io_wbFuBusyTable_0_1_vfWbBusyTable,
  output [3:0] io_wbFuBusyTable_0_1_v0WbBusyTable,
  output [1:0] io_wbFuBusyTable_0_1_vlWbBusyTable,
  output [4:0] io_wbFuBusyTable_0_0_vfWbBusyTable,
  output [4:0] io_wbFuBusyTable_0_0_v0WbBusyTable,
  output [4:0] io_IQValidNumVec_0,
  output [4:0] io_IQValidNumVec_1,
  output [4:0] io_IQValidNumVec_2,
  output [4:0] io_IQValidNumVec_3,
  input  io_fromCtrlBlock_flush_valid,
  input  io_fromCtrlBlock_flush_bits_robIdx_flag,
  input  [7:0] io_fromCtrlBlock_flush_bits_robIdx_value,
  input  io_fromCtrlBlock_flush_bits_level,
  output io_fromDispatch_uops_0_ready,
  input  io_fromDispatch_uops_0_valid,
  input  [3:0] io_fromDispatch_uops_0_bits_srcType_0,
  input  [3:0] io_fromDispatch_uops_0_bits_srcType_1,
  input  [3:0] io_fromDispatch_uops_0_bits_srcType_2,
  input  [3:0] io_fromDispatch_uops_0_bits_srcType_3,
  input  [3:0] io_fromDispatch_uops_0_bits_srcType_4,
  input  [34:0] io_fromDispatch_uops_0_bits_fuType,
  input  [8:0] io_fromDispatch_uops_0_bits_fuOpType,
  input  io_fromDispatch_uops_0_bits_rfWen,
  input  io_fromDispatch_uops_0_bits_fpWen,
  input  io_fromDispatch_uops_0_bits_vecWen,
  input  io_fromDispatch_uops_0_bits_v0Wen,
  input  io_fromDispatch_uops_0_bits_vlWen,
  input  [3:0] io_fromDispatch_uops_0_bits_selImm,
  input  [31:0] io_fromDispatch_uops_0_bits_imm,
  input  io_fromDispatch_uops_0_bits_fpu_wflags,
  input  io_fromDispatch_uops_0_bits_vpu_vma,
  input  io_fromDispatch_uops_0_bits_vpu_vta,
  input  [1:0] io_fromDispatch_uops_0_bits_vpu_vsew,
  input  [2:0] io_fromDispatch_uops_0_bits_vpu_vlmul,
  input  io_fromDispatch_uops_0_bits_vpu_vm,
  input  [7:0] io_fromDispatch_uops_0_bits_vpu_vstart,
  input  io_fromDispatch_uops_0_bits_vpu_fpu_isFoldTo1_2,
  input  io_fromDispatch_uops_0_bits_vpu_fpu_isFoldTo1_4,
  input  io_fromDispatch_uops_0_bits_vpu_fpu_isFoldTo1_8,
  input  io_fromDispatch_uops_0_bits_vpu_isExt,
  input  io_fromDispatch_uops_0_bits_vpu_isNarrow,
  input  io_fromDispatch_uops_0_bits_vpu_isDstMask,
  input  io_fromDispatch_uops_0_bits_vpu_isOpMask,
  input  io_fromDispatch_uops_0_bits_vpu_isDependOldVd,
  input  io_fromDispatch_uops_0_bits_vpu_isWritePartVd,
  input  [6:0] io_fromDispatch_uops_0_bits_uopIdx,
  input  io_fromDispatch_uops_0_bits_lastUop,
  input  io_fromDispatch_uops_0_bits_srcState_0,
  input  io_fromDispatch_uops_0_bits_srcState_1,
  input  io_fromDispatch_uops_0_bits_srcState_2,
  input  io_fromDispatch_uops_0_bits_srcState_3,
  input  io_fromDispatch_uops_0_bits_srcState_4,
  input  [7:0] io_fromDispatch_uops_0_bits_psrc_0,
  input  [7:0] io_fromDispatch_uops_0_bits_psrc_1,
  input  [7:0] io_fromDispatch_uops_0_bits_psrc_2,
  input  [7:0] io_fromDispatch_uops_0_bits_psrc_3,
  input  [7:0] io_fromDispatch_uops_0_bits_psrc_4,
  input  [7:0] io_fromDispatch_uops_0_bits_pdest,
  input  io_fromDispatch_uops_0_bits_robIdx_flag,
  input  [7:0] io_fromDispatch_uops_0_bits_robIdx_value,
  input  io_fromDispatch_uops_1_valid,
  input  [3:0] io_fromDispatch_uops_1_bits_srcType_0,
  input  [3:0] io_fromDispatch_uops_1_bits_srcType_1,
  input  [3:0] io_fromDispatch_uops_1_bits_srcType_2,
  input  [3:0] io_fromDispatch_uops_1_bits_srcType_3,
  input  [3:0] io_fromDispatch_uops_1_bits_srcType_4,
  input  [34:0] io_fromDispatch_uops_1_bits_fuType,
  input  [8:0] io_fromDispatch_uops_1_bits_fuOpType,
  input  io_fromDispatch_uops_1_bits_rfWen,
  input  io_fromDispatch_uops_1_bits_fpWen,
  input  io_fromDispatch_uops_1_bits_vecWen,
  input  io_fromDispatch_uops_1_bits_v0Wen,
  input  io_fromDispatch_uops_1_bits_vlWen,
  input  [3:0] io_fromDispatch_uops_1_bits_selImm,
  input  [31:0] io_fromDispatch_uops_1_bits_imm,
  input  io_fromDispatch_uops_1_bits_fpu_wflags,
  input  io_fromDispatch_uops_1_bits_vpu_vma,
  input  io_fromDispatch_uops_1_bits_vpu_vta,
  input  [1:0] io_fromDispatch_uops_1_bits_vpu_vsew,
  input  [2:0] io_fromDispatch_uops_1_bits_vpu_vlmul,
  input  io_fromDispatch_uops_1_bits_vpu_vm,
  input  [7:0] io_fromDispatch_uops_1_bits_vpu_vstart,
  input  io_fromDispatch_uops_1_bits_vpu_fpu_isFoldTo1_2,
  input  io_fromDispatch_uops_1_bits_vpu_fpu_isFoldTo1_4,
  input  io_fromDispatch_uops_1_bits_vpu_fpu_isFoldTo1_8,
  input  io_fromDispatch_uops_1_bits_vpu_isExt,
  input  io_fromDispatch_uops_1_bits_vpu_isNarrow,
  input  io_fromDispatch_uops_1_bits_vpu_isDstMask,
  input  io_fromDispatch_uops_1_bits_vpu_isOpMask,
  input  io_fromDispatch_uops_1_bits_vpu_isDependOldVd,
  input  io_fromDispatch_uops_1_bits_vpu_isWritePartVd,
  input  [6:0] io_fromDispatch_uops_1_bits_uopIdx,
  input  io_fromDispatch_uops_1_bits_lastUop,
  input  io_fromDispatch_uops_1_bits_srcState_0,
  input  io_fromDispatch_uops_1_bits_srcState_1,
  input  io_fromDispatch_uops_1_bits_srcState_2,
  input  io_fromDispatch_uops_1_bits_srcState_3,
  input  io_fromDispatch_uops_1_bits_srcState_4,
  input  [7:0] io_fromDispatch_uops_1_bits_psrc_0,
  input  [7:0] io_fromDispatch_uops_1_bits_psrc_1,
  input  [7:0] io_fromDispatch_uops_1_bits_psrc_2,
  input  [7:0] io_fromDispatch_uops_1_bits_psrc_3,
  input  [7:0] io_fromDispatch_uops_1_bits_psrc_4,
  input  [7:0] io_fromDispatch_uops_1_bits_pdest,
  input  io_fromDispatch_uops_1_bits_robIdx_flag,
  input  [7:0] io_fromDispatch_uops_1_bits_robIdx_value,
  output io_fromDispatch_uops_2_ready,
  input  io_fromDispatch_uops_2_valid,
  input  [3:0] io_fromDispatch_uops_2_bits_srcType_0,
  input  [3:0] io_fromDispatch_uops_2_bits_srcType_1,
  input  [3:0] io_fromDispatch_uops_2_bits_srcType_2,
  input  [3:0] io_fromDispatch_uops_2_bits_srcType_3,
  input  [3:0] io_fromDispatch_uops_2_bits_srcType_4,
  input  [34:0] io_fromDispatch_uops_2_bits_fuType,
  input  [8:0] io_fromDispatch_uops_2_bits_fuOpType,
  input  io_fromDispatch_uops_2_bits_fpWen,
  input  io_fromDispatch_uops_2_bits_vecWen,
  input  io_fromDispatch_uops_2_bits_v0Wen,
  input  io_fromDispatch_uops_2_bits_fpu_wflags,
  input  io_fromDispatch_uops_2_bits_vpu_vma,
  input  io_fromDispatch_uops_2_bits_vpu_vta,
  input  [1:0] io_fromDispatch_uops_2_bits_vpu_vsew,
  input  [2:0] io_fromDispatch_uops_2_bits_vpu_vlmul,
  input  io_fromDispatch_uops_2_bits_vpu_vm,
  input  [7:0] io_fromDispatch_uops_2_bits_vpu_vstart,
  input  io_fromDispatch_uops_2_bits_vpu_fpu_isFoldTo1_2,
  input  io_fromDispatch_uops_2_bits_vpu_fpu_isFoldTo1_4,
  input  io_fromDispatch_uops_2_bits_vpu_fpu_isFoldTo1_8,
  input  io_fromDispatch_uops_2_bits_vpu_isExt,
  input  io_fromDispatch_uops_2_bits_vpu_isNarrow,
  input  io_fromDispatch_uops_2_bits_vpu_isDstMask,
  input  io_fromDispatch_uops_2_bits_vpu_isOpMask,
  input  io_fromDispatch_uops_2_bits_vpu_isDependOldVd,
  input  io_fromDispatch_uops_2_bits_vpu_isWritePartVd,
  input  [6:0] io_fromDispatch_uops_2_bits_uopIdx,
  input  io_fromDispatch_uops_2_bits_lastUop,
  input  io_fromDispatch_uops_2_bits_srcState_0,
  input  io_fromDispatch_uops_2_bits_srcState_1,
  input  io_fromDispatch_uops_2_bits_srcState_2,
  input  io_fromDispatch_uops_2_bits_srcState_3,
  input  io_fromDispatch_uops_2_bits_srcState_4,
  input  [7:0] io_fromDispatch_uops_2_bits_psrc_0,
  input  [7:0] io_fromDispatch_uops_2_bits_psrc_1,
  input  [7:0] io_fromDispatch_uops_2_bits_psrc_2,
  input  [7:0] io_fromDispatch_uops_2_bits_psrc_3,
  input  [7:0] io_fromDispatch_uops_2_bits_psrc_4,
  input  [7:0] io_fromDispatch_uops_2_bits_pdest,
  input  io_fromDispatch_uops_2_bits_robIdx_flag,
  input  [7:0] io_fromDispatch_uops_2_bits_robIdx_value,
  input  io_fromDispatch_uops_3_valid,
  input  [3:0] io_fromDispatch_uops_3_bits_srcType_0,
  input  [3:0] io_fromDispatch_uops_3_bits_srcType_1,
  input  [3:0] io_fromDispatch_uops_3_bits_srcType_2,
  input  [3:0] io_fromDispatch_uops_3_bits_srcType_3,
  input  [3:0] io_fromDispatch_uops_3_bits_srcType_4,
  input  [34:0] io_fromDispatch_uops_3_bits_fuType,
  input  [8:0] io_fromDispatch_uops_3_bits_fuOpType,
  input  io_fromDispatch_uops_3_bits_fpWen,
  input  io_fromDispatch_uops_3_bits_vecWen,
  input  io_fromDispatch_uops_3_bits_v0Wen,
  input  io_fromDispatch_uops_3_bits_fpu_wflags,
  input  io_fromDispatch_uops_3_bits_vpu_vma,
  input  io_fromDispatch_uops_3_bits_vpu_vta,
  input  [1:0] io_fromDispatch_uops_3_bits_vpu_vsew,
  input  [2:0] io_fromDispatch_uops_3_bits_vpu_vlmul,
  input  io_fromDispatch_uops_3_bits_vpu_vm,
  input  [7:0] io_fromDispatch_uops_3_bits_vpu_vstart,
  input  io_fromDispatch_uops_3_bits_vpu_fpu_isFoldTo1_2,
  input  io_fromDispatch_uops_3_bits_vpu_fpu_isFoldTo1_4,
  input  io_fromDispatch_uops_3_bits_vpu_fpu_isFoldTo1_8,
  input  io_fromDispatch_uops_3_bits_vpu_isExt,
  input  io_fromDispatch_uops_3_bits_vpu_isNarrow,
  input  io_fromDispatch_uops_3_bits_vpu_isDstMask,
  input  io_fromDispatch_uops_3_bits_vpu_isOpMask,
  input  io_fromDispatch_uops_3_bits_vpu_isDependOldVd,
  input  io_fromDispatch_uops_3_bits_vpu_isWritePartVd,
  input  [6:0] io_fromDispatch_uops_3_bits_uopIdx,
  input  io_fromDispatch_uops_3_bits_lastUop,
  input  io_fromDispatch_uops_3_bits_srcState_0,
  input  io_fromDispatch_uops_3_bits_srcState_1,
  input  io_fromDispatch_uops_3_bits_srcState_2,
  input  io_fromDispatch_uops_3_bits_srcState_3,
  input  io_fromDispatch_uops_3_bits_srcState_4,
  input  [7:0] io_fromDispatch_uops_3_bits_psrc_0,
  input  [7:0] io_fromDispatch_uops_3_bits_psrc_1,
  input  [7:0] io_fromDispatch_uops_3_bits_psrc_2,
  input  [7:0] io_fromDispatch_uops_3_bits_psrc_3,
  input  [7:0] io_fromDispatch_uops_3_bits_psrc_4,
  input  [7:0] io_fromDispatch_uops_3_bits_pdest,
  input  io_fromDispatch_uops_3_bits_robIdx_flag,
  input  [7:0] io_fromDispatch_uops_3_bits_robIdx_value,
  output io_fromDispatch_uops_4_ready,
  input  io_fromDispatch_uops_4_valid,
  input  [3:0] io_fromDispatch_uops_4_bits_srcType_0,
  input  [3:0] io_fromDispatch_uops_4_bits_srcType_1,
  input  [3:0] io_fromDispatch_uops_4_bits_srcType_2,
  input  [3:0] io_fromDispatch_uops_4_bits_srcType_3,
  input  [3:0] io_fromDispatch_uops_4_bits_srcType_4,
  input  [34:0] io_fromDispatch_uops_4_bits_fuType,
  input  [8:0] io_fromDispatch_uops_4_bits_fuOpType,
  input  io_fromDispatch_uops_4_bits_vecWen,
  input  io_fromDispatch_uops_4_bits_v0Wen,
  input  io_fromDispatch_uops_4_bits_fpu_wflags,
  input  io_fromDispatch_uops_4_bits_vpu_vma,
  input  io_fromDispatch_uops_4_bits_vpu_vta,
  input  [1:0] io_fromDispatch_uops_4_bits_vpu_vsew,
  input  [2:0] io_fromDispatch_uops_4_bits_vpu_vlmul,
  input  io_fromDispatch_uops_4_bits_vpu_vm,
  input  [7:0] io_fromDispatch_uops_4_bits_vpu_vstart,
  input  io_fromDispatch_uops_4_bits_vpu_isExt,
  input  io_fromDispatch_uops_4_bits_vpu_isNarrow,
  input  io_fromDispatch_uops_4_bits_vpu_isDstMask,
  input  io_fromDispatch_uops_4_bits_vpu_isOpMask,
  input  io_fromDispatch_uops_4_bits_vpu_isDependOldVd,
  input  io_fromDispatch_uops_4_bits_vpu_isWritePartVd,
  input  [6:0] io_fromDispatch_uops_4_bits_uopIdx,
  input  io_fromDispatch_uops_4_bits_srcState_0,
  input  io_fromDispatch_uops_4_bits_srcState_1,
  input  io_fromDispatch_uops_4_bits_srcState_2,
  input  io_fromDispatch_uops_4_bits_srcState_3,
  input  io_fromDispatch_uops_4_bits_srcState_4,
  input  [7:0] io_fromDispatch_uops_4_bits_psrc_0,
  input  [7:0] io_fromDispatch_uops_4_bits_psrc_1,
  input  [7:0] io_fromDispatch_uops_4_bits_psrc_2,
  input  [7:0] io_fromDispatch_uops_4_bits_psrc_3,
  input  [7:0] io_fromDispatch_uops_4_bits_psrc_4,
  input  [7:0] io_fromDispatch_uops_4_bits_pdest,
  input  io_fromDispatch_uops_4_bits_robIdx_flag,
  input  [7:0] io_fromDispatch_uops_4_bits_robIdx_value,
  input  io_fromDispatch_uops_5_valid,
  input  [3:0] io_fromDispatch_uops_5_bits_srcType_0,
  input  [3:0] io_fromDispatch_uops_5_bits_srcType_1,
  input  [3:0] io_fromDispatch_uops_5_bits_srcType_2,
  input  [3:0] io_fromDispatch_uops_5_bits_srcType_3,
  input  [3:0] io_fromDispatch_uops_5_bits_srcType_4,
  input  [34:0] io_fromDispatch_uops_5_bits_fuType,
  input  [8:0] io_fromDispatch_uops_5_bits_fuOpType,
  input  io_fromDispatch_uops_5_bits_vecWen,
  input  io_fromDispatch_uops_5_bits_v0Wen,
  input  io_fromDispatch_uops_5_bits_fpu_wflags,
  input  io_fromDispatch_uops_5_bits_vpu_vma,
  input  io_fromDispatch_uops_5_bits_vpu_vta,
  input  [1:0] io_fromDispatch_uops_5_bits_vpu_vsew,
  input  [2:0] io_fromDispatch_uops_5_bits_vpu_vlmul,
  input  io_fromDispatch_uops_5_bits_vpu_vm,
  input  [7:0] io_fromDispatch_uops_5_bits_vpu_vstart,
  input  io_fromDispatch_uops_5_bits_vpu_isExt,
  input  io_fromDispatch_uops_5_bits_vpu_isNarrow,
  input  io_fromDispatch_uops_5_bits_vpu_isDstMask,
  input  io_fromDispatch_uops_5_bits_vpu_isOpMask,
  input  io_fromDispatch_uops_5_bits_vpu_isDependOldVd,
  input  io_fromDispatch_uops_5_bits_vpu_isWritePartVd,
  input  [6:0] io_fromDispatch_uops_5_bits_uopIdx,
  input  io_fromDispatch_uops_5_bits_srcState_0,
  input  io_fromDispatch_uops_5_bits_srcState_1,
  input  io_fromDispatch_uops_5_bits_srcState_2,
  input  io_fromDispatch_uops_5_bits_srcState_3,
  input  io_fromDispatch_uops_5_bits_srcState_4,
  input  [7:0] io_fromDispatch_uops_5_bits_psrc_0,
  input  [7:0] io_fromDispatch_uops_5_bits_psrc_1,
  input  [7:0] io_fromDispatch_uops_5_bits_psrc_2,
  input  [7:0] io_fromDispatch_uops_5_bits_psrc_3,
  input  [7:0] io_fromDispatch_uops_5_bits_psrc_4,
  input  [7:0] io_fromDispatch_uops_5_bits_pdest,
  input  io_fromDispatch_uops_5_bits_robIdx_flag,
  input  [7:0] io_fromDispatch_uops_5_bits_robIdx_value,
  input  io_vfWriteBack_5_wen,
  input  [6:0] io_vfWriteBack_5_addr,
  input  io_vfWriteBack_5_vecWen,
  input  io_vfWriteBack_4_wen,
  input  [6:0] io_vfWriteBack_4_addr,
  input  io_vfWriteBack_4_vecWen,
  input  io_vfWriteBack_3_wen,
  input  [6:0] io_vfWriteBack_3_addr,
  input  io_vfWriteBack_3_vecWen,
  input  io_vfWriteBack_2_wen,
  input  [6:0] io_vfWriteBack_2_addr,
  input  io_vfWriteBack_2_vecWen,
  input  io_vfWriteBack_1_wen,
  input  [6:0] io_vfWriteBack_1_addr,
  input  io_vfWriteBack_1_vecWen,
  input  io_vfWriteBack_0_wen,
  input  [6:0] io_vfWriteBack_0_addr,
  input  io_vfWriteBack_0_vecWen,
  input  io_v0WriteBack_5_wen,
  input  [4:0] io_v0WriteBack_5_addr,
  input  io_v0WriteBack_5_v0Wen,
  input  io_v0WriteBack_4_wen,
  input  [4:0] io_v0WriteBack_4_addr,
  input  io_v0WriteBack_4_v0Wen,
  input  io_v0WriteBack_3_wen,
  input  [4:0] io_v0WriteBack_3_addr,
  input  io_v0WriteBack_3_v0Wen,
  input  io_v0WriteBack_2_wen,
  input  [4:0] io_v0WriteBack_2_addr,
  input  io_v0WriteBack_2_v0Wen,
  input  io_v0WriteBack_1_wen,
  input  [4:0] io_v0WriteBack_1_addr,
  input  io_v0WriteBack_1_v0Wen,
  input  io_v0WriteBack_0_wen,
  input  [4:0] io_v0WriteBack_0_addr,
  input  io_v0WriteBack_0_v0Wen,
  input  io_vlWriteBack_3_wen,
  input  [4:0] io_vlWriteBack_3_addr,
  input  io_vlWriteBack_3_vlWen,
  input  io_vlWriteBack_2_wen,
  input  [4:0] io_vlWriteBack_2_addr,
  input  io_vlWriteBack_2_vlWen,
  input  io_vlWriteBack_1_wen,
  input  [4:0] io_vlWriteBack_1_addr,
  input  io_vlWriteBack_1_vlWen,
  input  io_vlWriteBack_0_wen,
  input  [4:0] io_vlWriteBack_0_addr,
  input  io_vlWriteBack_0_vlWen,
  input  io_vfWriteBackDelayed_5_wen,
  input  [6:0] io_vfWriteBackDelayed_5_addr,
  input  io_vfWriteBackDelayed_5_vecWen,
  input  io_vfWriteBackDelayed_4_wen,
  input  [6:0] io_vfWriteBackDelayed_4_addr,
  input  io_vfWriteBackDelayed_4_vecWen,
  input  io_vfWriteBackDelayed_3_wen,
  input  [6:0] io_vfWriteBackDelayed_3_addr,
  input  io_vfWriteBackDelayed_3_vecWen,
  input  io_vfWriteBackDelayed_2_wen,
  input  [6:0] io_vfWriteBackDelayed_2_addr,
  input  io_vfWriteBackDelayed_2_vecWen,
  input  io_vfWriteBackDelayed_1_wen,
  input  [6:0] io_vfWriteBackDelayed_1_addr,
  input  io_vfWriteBackDelayed_1_vecWen,
  input  io_vfWriteBackDelayed_0_wen,
  input  [6:0] io_vfWriteBackDelayed_0_addr,
  input  io_vfWriteBackDelayed_0_vecWen,
  input  io_v0WriteBackDelayed_5_wen,
  input  [4:0] io_v0WriteBackDelayed_5_addr,
  input  io_v0WriteBackDelayed_5_v0Wen,
  input  io_v0WriteBackDelayed_4_wen,
  input  [4:0] io_v0WriteBackDelayed_4_addr,
  input  io_v0WriteBackDelayed_4_v0Wen,
  input  io_v0WriteBackDelayed_3_wen,
  input  [4:0] io_v0WriteBackDelayed_3_addr,
  input  io_v0WriteBackDelayed_3_v0Wen,
  input  io_v0WriteBackDelayed_2_wen,
  input  [4:0] io_v0WriteBackDelayed_2_addr,
  input  io_v0WriteBackDelayed_2_v0Wen,
  input  io_v0WriteBackDelayed_1_wen,
  input  [4:0] io_v0WriteBackDelayed_1_addr,
  input  io_v0WriteBackDelayed_1_v0Wen,
  input  io_v0WriteBackDelayed_0_wen,
  input  [4:0] io_v0WriteBackDelayed_0_addr,
  input  io_v0WriteBackDelayed_0_v0Wen,
  input  io_vlWriteBackDelayed_3_wen,
  input  [4:0] io_vlWriteBackDelayed_3_addr,
  input  io_vlWriteBackDelayed_3_vlWen,
  input  io_vlWriteBackDelayed_2_wen,
  input  [4:0] io_vlWriteBackDelayed_2_addr,
  input  io_vlWriteBackDelayed_2_vlWen,
  input  io_vlWriteBackDelayed_1_wen,
  input  [4:0] io_vlWriteBackDelayed_1_addr,
  input  io_vlWriteBackDelayed_1_vlWen,
  input  io_vlWriteBackDelayed_0_wen,
  input  [4:0] io_vlWriteBackDelayed_0_addr,
  input  io_vlWriteBackDelayed_0_vlWen,
  input  io_toDataPathAfterDelay_2_0_ready,
  output io_toDataPathAfterDelay_2_0_valid,
  output [6:0] io_toDataPathAfterDelay_2_0_bits_rf_4_0_addr,
  output [6:0] io_toDataPathAfterDelay_2_0_bits_rf_3_0_addr,
  output [6:0] io_toDataPathAfterDelay_2_0_bits_rf_2_0_addr,
  output [6:0] io_toDataPathAfterDelay_2_0_bits_rf_1_0_addr,
  output [6:0] io_toDataPathAfterDelay_2_0_bits_rf_0_0_addr,
  output [34:0] io_toDataPathAfterDelay_2_0_bits_common_fuType,
  output [8:0] io_toDataPathAfterDelay_2_0_bits_common_fuOpType,
  output io_toDataPathAfterDelay_2_0_bits_common_robIdx_flag,
  output [7:0] io_toDataPathAfterDelay_2_0_bits_common_robIdx_value,
  output [6:0] io_toDataPathAfterDelay_2_0_bits_common_pdest,
  output io_toDataPathAfterDelay_2_0_bits_common_vecWen,
  output io_toDataPathAfterDelay_2_0_bits_common_v0Wen,
  output io_toDataPathAfterDelay_2_0_bits_common_fpu_wflags,
  output io_toDataPathAfterDelay_2_0_bits_common_vpu_vma,
  output io_toDataPathAfterDelay_2_0_bits_common_vpu_vta,
  output [1:0] io_toDataPathAfterDelay_2_0_bits_common_vpu_vsew,
  output [2:0] io_toDataPathAfterDelay_2_0_bits_common_vpu_vlmul,
  output io_toDataPathAfterDelay_2_0_bits_common_vpu_vm,
  output [7:0] io_toDataPathAfterDelay_2_0_bits_common_vpu_vstart,
  output [6:0] io_toDataPathAfterDelay_2_0_bits_common_vpu_vuopIdx,
  output io_toDataPathAfterDelay_2_0_bits_common_vpu_isExt,
  output io_toDataPathAfterDelay_2_0_bits_common_vpu_isNarrow,
  output io_toDataPathAfterDelay_2_0_bits_common_vpu_isDstMask,
  output io_toDataPathAfterDelay_2_0_bits_common_vpu_isOpMask,
  output [3:0] io_toDataPathAfterDelay_2_0_bits_common_dataSources_0_value,
  output [3:0] io_toDataPathAfterDelay_2_0_bits_common_dataSources_1_value,
  output [3:0] io_toDataPathAfterDelay_2_0_bits_common_dataSources_2_value,
  output [3:0] io_toDataPathAfterDelay_2_0_bits_common_dataSources_3_value,
  output [3:0] io_toDataPathAfterDelay_2_0_bits_common_dataSources_4_value,
  input  io_toDataPathAfterDelay_1_1_ready,
  output io_toDataPathAfterDelay_1_1_valid,
  output [6:0] io_toDataPathAfterDelay_1_1_bits_rf_4_0_addr,
  output [6:0] io_toDataPathAfterDelay_1_1_bits_rf_3_0_addr,
  output [6:0] io_toDataPathAfterDelay_1_1_bits_rf_2_0_addr,
  output [6:0] io_toDataPathAfterDelay_1_1_bits_rf_1_0_addr,
  output [6:0] io_toDataPathAfterDelay_1_1_bits_rf_0_0_addr,
  output [34:0] io_toDataPathAfterDelay_1_1_bits_common_fuType,
  output [8:0] io_toDataPathAfterDelay_1_1_bits_common_fuOpType,
  output io_toDataPathAfterDelay_1_1_bits_common_robIdx_flag,
  output [7:0] io_toDataPathAfterDelay_1_1_bits_common_robIdx_value,
  output [7:0] io_toDataPathAfterDelay_1_1_bits_common_pdest,
  output io_toDataPathAfterDelay_1_1_bits_common_fpWen,
  output io_toDataPathAfterDelay_1_1_bits_common_vecWen,
  output io_toDataPathAfterDelay_1_1_bits_common_v0Wen,
  output io_toDataPathAfterDelay_1_1_bits_common_fpu_wflags,
  output io_toDataPathAfterDelay_1_1_bits_common_vpu_vma,
  output io_toDataPathAfterDelay_1_1_bits_common_vpu_vta,
  output [1:0] io_toDataPathAfterDelay_1_1_bits_common_vpu_vsew,
  output [2:0] io_toDataPathAfterDelay_1_1_bits_common_vpu_vlmul,
  output io_toDataPathAfterDelay_1_1_bits_common_vpu_vm,
  output [7:0] io_toDataPathAfterDelay_1_1_bits_common_vpu_vstart,
  output io_toDataPathAfterDelay_1_1_bits_common_vpu_fpu_isFoldTo1_2,
  output io_toDataPathAfterDelay_1_1_bits_common_vpu_fpu_isFoldTo1_4,
  output io_toDataPathAfterDelay_1_1_bits_common_vpu_fpu_isFoldTo1_8,
  output [6:0] io_toDataPathAfterDelay_1_1_bits_common_vpu_vuopIdx,
  output io_toDataPathAfterDelay_1_1_bits_common_vpu_lastUop,
  output io_toDataPathAfterDelay_1_1_bits_common_vpu_isNarrow,
  output io_toDataPathAfterDelay_1_1_bits_common_vpu_isDstMask,
  output [3:0] io_toDataPathAfterDelay_1_1_bits_common_dataSources_0_value,
  output [3:0] io_toDataPathAfterDelay_1_1_bits_common_dataSources_1_value,
  output [3:0] io_toDataPathAfterDelay_1_1_bits_common_dataSources_2_value,
  output [3:0] io_toDataPathAfterDelay_1_1_bits_common_dataSources_3_value,
  output [3:0] io_toDataPathAfterDelay_1_1_bits_common_dataSources_4_value,
  input  io_toDataPathAfterDelay_1_0_ready,
  output io_toDataPathAfterDelay_1_0_valid,
  output [6:0] io_toDataPathAfterDelay_1_0_bits_rf_4_0_addr,
  output [6:0] io_toDataPathAfterDelay_1_0_bits_rf_3_0_addr,
  output [6:0] io_toDataPathAfterDelay_1_0_bits_rf_2_0_addr,
  output [6:0] io_toDataPathAfterDelay_1_0_bits_rf_1_0_addr,
  output [6:0] io_toDataPathAfterDelay_1_0_bits_rf_0_0_addr,
  output [34:0] io_toDataPathAfterDelay_1_0_bits_common_fuType,
  output [8:0] io_toDataPathAfterDelay_1_0_bits_common_fuOpType,
  output io_toDataPathAfterDelay_1_0_bits_common_robIdx_flag,
  output [7:0] io_toDataPathAfterDelay_1_0_bits_common_robIdx_value,
  output [6:0] io_toDataPathAfterDelay_1_0_bits_common_pdest,
  output io_toDataPathAfterDelay_1_0_bits_common_vecWen,
  output io_toDataPathAfterDelay_1_0_bits_common_v0Wen,
  output io_toDataPathAfterDelay_1_0_bits_common_fpu_wflags,
  output io_toDataPathAfterDelay_1_0_bits_common_vpu_vma,
  output io_toDataPathAfterDelay_1_0_bits_common_vpu_vta,
  output [1:0] io_toDataPathAfterDelay_1_0_bits_common_vpu_vsew,
  output [2:0] io_toDataPathAfterDelay_1_0_bits_common_vpu_vlmul,
  output io_toDataPathAfterDelay_1_0_bits_common_vpu_vm,
  output [7:0] io_toDataPathAfterDelay_1_0_bits_common_vpu_vstart,
  output [6:0] io_toDataPathAfterDelay_1_0_bits_common_vpu_vuopIdx,
  output io_toDataPathAfterDelay_1_0_bits_common_vpu_isExt,
  output io_toDataPathAfterDelay_1_0_bits_common_vpu_isNarrow,
  output io_toDataPathAfterDelay_1_0_bits_common_vpu_isDstMask,
  output io_toDataPathAfterDelay_1_0_bits_common_vpu_isOpMask,
  output [3:0] io_toDataPathAfterDelay_1_0_bits_common_dataSources_0_value,
  output [3:0] io_toDataPathAfterDelay_1_0_bits_common_dataSources_1_value,
  output [3:0] io_toDataPathAfterDelay_1_0_bits_common_dataSources_2_value,
  output [3:0] io_toDataPathAfterDelay_1_0_bits_common_dataSources_3_value,
  output [3:0] io_toDataPathAfterDelay_1_0_bits_common_dataSources_4_value,
  input  io_toDataPathAfterDelay_0_1_ready,
  output io_toDataPathAfterDelay_0_1_valid,
  output [6:0] io_toDataPathAfterDelay_0_1_bits_rf_4_0_addr,
  output [6:0] io_toDataPathAfterDelay_0_1_bits_rf_3_0_addr,
  output [6:0] io_toDataPathAfterDelay_0_1_bits_rf_2_0_addr,
  output [6:0] io_toDataPathAfterDelay_0_1_bits_rf_1_0_addr,
  output [6:0] io_toDataPathAfterDelay_0_1_bits_rf_0_0_addr,
  output [3:0] io_toDataPathAfterDelay_0_1_bits_immType,
  output [34:0] io_toDataPathAfterDelay_0_1_bits_common_fuType,
  output [8:0] io_toDataPathAfterDelay_0_1_bits_common_fuOpType,
  output [63:0] io_toDataPathAfterDelay_0_1_bits_common_imm,
  output io_toDataPathAfterDelay_0_1_bits_common_robIdx_flag,
  output [7:0] io_toDataPathAfterDelay_0_1_bits_common_robIdx_value,
  output [7:0] io_toDataPathAfterDelay_0_1_bits_common_pdest,
  output io_toDataPathAfterDelay_0_1_bits_common_rfWen,
  output io_toDataPathAfterDelay_0_1_bits_common_fpWen,
  output io_toDataPathAfterDelay_0_1_bits_common_vecWen,
  output io_toDataPathAfterDelay_0_1_bits_common_v0Wen,
  output io_toDataPathAfterDelay_0_1_bits_common_vlWen,
  output io_toDataPathAfterDelay_0_1_bits_common_fpu_wflags,
  output io_toDataPathAfterDelay_0_1_bits_common_vpu_vma,
  output io_toDataPathAfterDelay_0_1_bits_common_vpu_vta,
  output [1:0] io_toDataPathAfterDelay_0_1_bits_common_vpu_vsew,
  output [2:0] io_toDataPathAfterDelay_0_1_bits_common_vpu_vlmul,
  output io_toDataPathAfterDelay_0_1_bits_common_vpu_vm,
  output [7:0] io_toDataPathAfterDelay_0_1_bits_common_vpu_vstart,
  output io_toDataPathAfterDelay_0_1_bits_common_vpu_fpu_isFoldTo1_2,
  output io_toDataPathAfterDelay_0_1_bits_common_vpu_fpu_isFoldTo1_4,
  output io_toDataPathAfterDelay_0_1_bits_common_vpu_fpu_isFoldTo1_8,
  output [6:0] io_toDataPathAfterDelay_0_1_bits_common_vpu_vuopIdx,
  output io_toDataPathAfterDelay_0_1_bits_common_vpu_lastUop,
  output io_toDataPathAfterDelay_0_1_bits_common_vpu_isNarrow,
  output io_toDataPathAfterDelay_0_1_bits_common_vpu_isDstMask,
  output [3:0] io_toDataPathAfterDelay_0_1_bits_common_dataSources_0_value,
  output [3:0] io_toDataPathAfterDelay_0_1_bits_common_dataSources_1_value,
  output [3:0] io_toDataPathAfterDelay_0_1_bits_common_dataSources_2_value,
  output [3:0] io_toDataPathAfterDelay_0_1_bits_common_dataSources_3_value,
  output [3:0] io_toDataPathAfterDelay_0_1_bits_common_dataSources_4_value,
  input  io_toDataPathAfterDelay_0_0_ready,
  output io_toDataPathAfterDelay_0_0_valid,
  output [6:0] io_toDataPathAfterDelay_0_0_bits_rf_4_0_addr,
  output [6:0] io_toDataPathAfterDelay_0_0_bits_rf_3_0_addr,
  output [6:0] io_toDataPathAfterDelay_0_0_bits_rf_2_0_addr,
  output [6:0] io_toDataPathAfterDelay_0_0_bits_rf_1_0_addr,
  output [6:0] io_toDataPathAfterDelay_0_0_bits_rf_0_0_addr,
  output [34:0] io_toDataPathAfterDelay_0_0_bits_common_fuType,
  output [8:0] io_toDataPathAfterDelay_0_0_bits_common_fuOpType,
  output io_toDataPathAfterDelay_0_0_bits_common_robIdx_flag,
  output [7:0] io_toDataPathAfterDelay_0_0_bits_common_robIdx_value,
  output [6:0] io_toDataPathAfterDelay_0_0_bits_common_pdest,
  output io_toDataPathAfterDelay_0_0_bits_common_vecWen,
  output io_toDataPathAfterDelay_0_0_bits_common_v0Wen,
  output io_toDataPathAfterDelay_0_0_bits_common_fpu_wflags,
  output io_toDataPathAfterDelay_0_0_bits_common_vpu_vma,
  output io_toDataPathAfterDelay_0_0_bits_common_vpu_vta,
  output [1:0] io_toDataPathAfterDelay_0_0_bits_common_vpu_vsew,
  output [2:0] io_toDataPathAfterDelay_0_0_bits_common_vpu_vlmul,
  output io_toDataPathAfterDelay_0_0_bits_common_vpu_vm,
  output [7:0] io_toDataPathAfterDelay_0_0_bits_common_vpu_vstart,
  output [6:0] io_toDataPathAfterDelay_0_0_bits_common_vpu_vuopIdx,
  output io_toDataPathAfterDelay_0_0_bits_common_vpu_isExt,
  output io_toDataPathAfterDelay_0_0_bits_common_vpu_isNarrow,
  output io_toDataPathAfterDelay_0_0_bits_common_vpu_isDstMask,
  output io_toDataPathAfterDelay_0_0_bits_common_vpu_isOpMask,
  output [3:0] io_toDataPathAfterDelay_0_0_bits_common_dataSources_0_value,
  output [3:0] io_toDataPathAfterDelay_0_0_bits_common_dataSources_1_value,
  output [3:0] io_toDataPathAfterDelay_0_0_bits_common_dataSources_2_value,
  output [3:0] io_toDataPathAfterDelay_0_0_bits_common_dataSources_3_value,
  output [3:0] io_toDataPathAfterDelay_0_0_bits_common_dataSources_4_value,
  input  io_vlWriteBackInfo_vlFromIntIsZero,
  input  io_vlWriteBackInfo_vlFromIntIsVlmax,
  input  io_vlWriteBackInfo_vlFromVfIsZero,
  input  io_vlWriteBackInfo_vlFromVfIsVlmax,
  input  io_fromDataPath_resp_2_0_og0resp_valid,
  input  io_fromDataPath_resp_2_0_og1resp_valid,
  input  io_fromDataPath_resp_1_1_og0resp_valid,
  input  [34:0] io_fromDataPath_resp_1_1_og0resp_bits_fuType,
  input  io_fromDataPath_resp_1_1_og1resp_valid,
  input  io_fromDataPath_resp_1_0_og0resp_valid,
  input  [34:0] io_fromDataPath_resp_1_0_og0resp_bits_fuType,
  input  io_fromDataPath_resp_1_0_og1resp_valid,
  input  io_fromDataPath_resp_0_1_og0resp_valid,
  input  [34:0] io_fromDataPath_resp_0_1_og0resp_bits_fuType,
  input  io_fromDataPath_resp_0_1_og1resp_valid,
  input  io_fromDataPath_resp_0_0_og0resp_valid,
  input  [34:0] io_fromDataPath_resp_0_0_og0resp_bits_fuType,
  input  io_fromDataPath_resp_0_0_og1resp_valid,
  input  io_fromOg2Resp_2_0_valid,
  input  [1:0] io_fromOg2Resp_2_0_bits_resp,
  input  io_fromOg2Resp_1_1_valid,
  input  io_fromOg2Resp_1_0_valid,
  input  [1:0] io_fromOg2Resp_1_0_bits_resp,
  input  io_fromOg2Resp_0_1_valid,
  input  io_fromOg2Resp_0_0_valid,
  input  [1:0] io_fromOg2Resp_0_0_bits_resp,
  output [5:0] io_perf_0_value,
  output [5:0] io_perf_1_value,
  output [5:0] io_perf_2_value,
  output [5:0] io_perf_3_value
);

  // ===== A) 例化 3 个 IssueQueue 并互联(唤醒网络/响应/cancel) =====
  `include "scheduler_vf_iq_connect.svh"

  // ===== B) dispatch-ready 透传 =====
  // 每个 dispatch 入端口的 ready 来自承接它的 IQ 的 enq0.ready。
  assign io_fromDispatch_uops_0_ready = IssueQueueVfmaVialuFixVimacVppuVfaluVfcvtVipuVsetrvfwvf_enq_0_ready;
  assign io_fromDispatch_uops_2_ready = IssueQueueVfmaVialuFixVfalu_enq_0_ready;
  assign io_fromDispatch_uops_4_ready = IssueQueueVfdivVidiv_enq_0_ready;

  // ===== C) deqDelay 发射有效 输出扇出 =====
  // 各 IQ 的 deqDelay_0_valid 在 .svh 里引到内部线,这里扇出到对应输出端口。
  assign io_toDataPathAfterDelay_2_0_valid = IssueQueueVfdivVidiv_deqDelay_0_valid;

  // ===== D) 发射 perf 统计 =====
  // enq_fire[i] = 第 i 个统计端口本拍 fire(IQ enq.ready & 对应 valid);
  // iq_full[k]  = 第 k 个 IQ 的 enq0.ready(队列是否还能收)。
  logic [NUM_ENQ_FIRE-1:0] enq_fire;
  logic [NUM_IQ-1:0]       iq_full;
  assign enq_fire[0] = IssueQueueVfmaVialuFixVimacVppuVfaluVfcvtVipuVsetrvfwvf_enq_0_ready & io_fromDispatch_uops_0_valid;
  assign enq_fire[1] = IssueQueueVfmaVialuFixVimacVppuVfaluVfcvtVipuVsetrvfwvf_enq_1_ready & io_fromDispatch_uops_1_valid;
  assign enq_fire[2] = IssueQueueVfmaVialuFixVfalu_enq_0_ready & io_fromDispatch_uops_2_valid;
  assign enq_fire[3] = IssueQueueVfmaVialuFixVfalu_enq_1_ready & io_fromDispatch_uops_3_valid;
  assign enq_fire[4] = IssueQueueVfdivVidiv_enq_0_ready & io_fromDispatch_uops_4_valid;
  assign enq_fire[5] = IssueQueueVfdivVidiv_enq_1_ready & io_fromDispatch_uops_5_valid;

  assign iq_full[IQ_VF_COMBO] = IssueQueueVfmaVialuFixVimacVppuVfaluVfcvtVipuVsetrvfwvf_enq_0_ready;
  assign iq_full[IQ_VFMA_VFALU] = IssueQueueVfmaVialuFixVfalu_enq_0_ready;
  assign iq_full[IQ_VF_DIV] = IssueQueueVfdivVidiv_enq_0_ready;

  // perf 三级流水(与 firtool 一致):
  //   stage0(last_cycle):先把本拍 enq_fire / iq_full 各打一拍;
  //   stage1(perf_s1)   :对 stage0 的 enq_fire 求 popcount;full 位直接打拍;
  //   stage2(perf_s2)   :再打一拍,作为对外 io_perf 输出。
  // popcount 作用在「已寄存」的 enq_fire 上(故计数比 fire 晚一拍),保留以逐拍等价。
  logic [NUM_ENQ_FIRE-1:0] last_cycle_enq_fire;
  logic [NUM_IQ-1:0]       last_cycle_iq_full;
  perf_sample_t perf_s1, perf_s2;
  always_ff @(posedge clock) begin
    last_cycle_enq_fire  <= enq_fire;
    last_cycle_iq_full   <= iq_full;
    perf_s1.enq_fire_cnt <= popcount(last_cycle_enq_fire);
    perf_s1.iq_full      <= last_cycle_iq_full;
    perf_s2              <= perf_s1;
  end

  // perf 输出:enq_fire_cnt 端口 6bit(高位补 3'h0);各 full 端口 6bit(高位补 5'h0)。
  assign io_perf_0_value = {3'h0, perf_s2.enq_fire_cnt};
  assign io_perf_1_value = {5'h0, perf_s2.iq_full[IQ_VF_COMBO]};
  assign io_perf_2_value = {5'h0, perf_s2.iq_full[IQ_VFMA_VFALU]};
  assign io_perf_3_value = {5'h0, perf_s2.iq_full[IQ_VF_DIV]};

endmodule
