// 自动生成：scripts/gen_icachemainpipe.py —— 勿手改
module ICacheMainPipe_xs(
  input  clock,
  input  reset,
  output io_dataArray_toIData_0_valid,
  output [7:0] io_dataArray_toIData_0_bits_vSetIdx_0,
  output [7:0] io_dataArray_toIData_0_bits_vSetIdx_1,
  output io_dataArray_toIData_0_bits_waymask_0_0,
  output io_dataArray_toIData_0_bits_waymask_0_1,
  output io_dataArray_toIData_0_bits_waymask_0_2,
  output io_dataArray_toIData_0_bits_waymask_0_3,
  output io_dataArray_toIData_0_bits_waymask_1_0,
  output io_dataArray_toIData_0_bits_waymask_1_1,
  output io_dataArray_toIData_0_bits_waymask_1_2,
  output io_dataArray_toIData_0_bits_waymask_1_3,
  output [5:0] io_dataArray_toIData_0_bits_blkOffset,
  output io_dataArray_toIData_1_valid,
  output [7:0] io_dataArray_toIData_1_bits_vSetIdx_0,
  output [7:0] io_dataArray_toIData_1_bits_vSetIdx_1,
  output io_dataArray_toIData_2_valid,
  output [7:0] io_dataArray_toIData_2_bits_vSetIdx_0,
  output [7:0] io_dataArray_toIData_2_bits_vSetIdx_1,
  input  io_dataArray_toIData_3_ready,
  output io_dataArray_toIData_3_valid,
  output [7:0] io_dataArray_toIData_3_bits_vSetIdx_0,
  output [7:0] io_dataArray_toIData_3_bits_vSetIdx_1,
  input  [63:0] io_dataArray_fromIData_datas_0,
  input  [63:0] io_dataArray_fromIData_datas_1,
  input  [63:0] io_dataArray_fromIData_datas_2,
  input  [63:0] io_dataArray_fromIData_datas_3,
  input  [63:0] io_dataArray_fromIData_datas_4,
  input  [63:0] io_dataArray_fromIData_datas_5,
  input  [63:0] io_dataArray_fromIData_datas_6,
  input  [63:0] io_dataArray_fromIData_datas_7,
  input  io_dataArray_fromIData_codes_0,
  input  io_dataArray_fromIData_codes_1,
  input  io_dataArray_fromIData_codes_2,
  input  io_dataArray_fromIData_codes_3,
  input  io_dataArray_fromIData_codes_4,
  input  io_dataArray_fromIData_codes_5,
  input  io_dataArray_fromIData_codes_6,
  input  io_dataArray_fromIData_codes_7,
  output io_metaArrayFlush_0_valid,
  output [7:0] io_metaArrayFlush_0_bits_virIdx,
  output [3:0] io_metaArrayFlush_0_bits_waymask,
  output io_metaArrayFlush_1_valid,
  output [7:0] io_metaArrayFlush_1_bits_virIdx,
  output [3:0] io_metaArrayFlush_1_bits_waymask,
  output io_touch_0_valid,
  output [7:0] io_touch_0_bits_vSetIdx,
  output [1:0] io_touch_0_bits_way,
  output io_touch_1_valid,
  output [7:0] io_touch_1_bits_vSetIdx,
  output [1:0] io_touch_1_bits_way,
  output io_wayLookupRead_ready,
  input  io_wayLookupRead_valid,
  input  [7:0] io_wayLookupRead_bits_entry_vSetIdx_0,
  input  [7:0] io_wayLookupRead_bits_entry_vSetIdx_1,
  input  [3:0] io_wayLookupRead_bits_entry_waymask_0,
  input  [3:0] io_wayLookupRead_bits_entry_waymask_1,
  input  [35:0] io_wayLookupRead_bits_entry_ptag_0,
  input  [35:0] io_wayLookupRead_bits_entry_ptag_1,
  input  [1:0] io_wayLookupRead_bits_entry_itlb_exception_0,
  input  [1:0] io_wayLookupRead_bits_entry_itlb_exception_1,
  input  [1:0] io_wayLookupRead_bits_entry_itlb_pbmt_0,
  input  [1:0] io_wayLookupRead_bits_entry_itlb_pbmt_1,
  input  io_wayLookupRead_bits_entry_meta_codes_0,
  input  io_wayLookupRead_bits_entry_meta_codes_1,
  input  [55:0] io_wayLookupRead_bits_gpf_gpaddr,
  input  io_wayLookupRead_bits_gpf_isForVSnonLeafPTE,
  input  io_mshr_req_ready,
  output io_mshr_req_valid,
  output [41:0] io_mshr_req_bits_blkPaddr,
  output [7:0] io_mshr_req_bits_vSetIdx,
  input  io_mshr_resp_valid,
  input  [41:0] io_mshr_resp_bits_blkPaddr,
  input  [7:0] io_mshr_resp_bits_vSetIdx,
  input  [511:0] io_mshr_resp_bits_data,
  input  io_mshr_resp_bits_corrupt,
  input  io_ecc_enable,
  output io_fetch_req_ready,
  input  io_fetch_req_valid,
  input  [49:0] io_fetch_req_bits_pcMemRead_0_startAddr,
  input  [49:0] io_fetch_req_bits_pcMemRead_0_nextlineStart,
  input  [49:0] io_fetch_req_bits_pcMemRead_1_startAddr,
  input  [49:0] io_fetch_req_bits_pcMemRead_1_nextlineStart,
  input  [49:0] io_fetch_req_bits_pcMemRead_2_startAddr,
  input  [49:0] io_fetch_req_bits_pcMemRead_2_nextlineStart,
  input  [49:0] io_fetch_req_bits_pcMemRead_3_startAddr,
  input  [49:0] io_fetch_req_bits_pcMemRead_3_nextlineStart,
  input  [49:0] io_fetch_req_bits_pcMemRead_4_startAddr,
  input  [49:0] io_fetch_req_bits_pcMemRead_4_nextlineStart,
  input  io_fetch_req_bits_readValid_0,
  input  io_fetch_req_bits_readValid_1,
  input  io_fetch_req_bits_readValid_2,
  input  io_fetch_req_bits_readValid_3,
  input  io_fetch_req_bits_readValid_4,
  input  io_fetch_req_bits_backendException,
  output io_fetch_resp_valid,
  output io_fetch_resp_bits_doubleline,
  output [49:0] io_fetch_resp_bits_vaddr_0,
  output [49:0] io_fetch_resp_bits_vaddr_1,
  output [511:0] io_fetch_resp_bits_data,
  output [47:0] io_fetch_resp_bits_paddr_0,
  output [1:0] io_fetch_resp_bits_exception_0,
  output [1:0] io_fetch_resp_bits_exception_1,
  output io_fetch_resp_bits_pmp_mmio_0,
  output io_fetch_resp_bits_pmp_mmio_1,
  output [1:0] io_fetch_resp_bits_itlb_pbmt_0,
  output [1:0] io_fetch_resp_bits_itlb_pbmt_1,
  output io_fetch_resp_bits_backendException,
  output [55:0] io_fetch_resp_bits_gpaddr,
  output io_fetch_resp_bits_isForVSnonLeafPTE,
  output io_fetch_topdownIcacheMiss,
  output io_fetch_topdownItlbMiss,
  input  io_flush,
  output [47:0] io_pmp_0_req_bits_addr,
  input  io_pmp_0_resp_instr,
  input  io_pmp_0_resp_mmio,
  output [47:0] io_pmp_1_req_bits_addr,
  input  io_pmp_1_resp_instr,
  input  io_pmp_1_resp_mmio,
  input  io_respStall,
  output io_errors_0_valid,
  output [47:0] io_errors_0_bits_paddr,
  output io_errors_0_bits_report_to_beu,
  output io_errors_1_valid,
  output [47:0] io_errors_1_bits_paddr,
  output io_errors_1_bits_report_to_beu,
  output io_perfInfo_only_0_hit,
  output io_perfInfo_only_0_miss,
  output io_perfInfo_hit_0_hit_1,
  output io_perfInfo_hit_0_miss_1,
  output io_perfInfo_miss_0_hit_1,
  output io_perfInfo_miss_0_miss_1,
  output io_perfInfo_hit_0_except_1,
  output io_perfInfo_miss_0_except_1,
  output io_perfInfo_except_0,
  output io_perfInfo_bank_hit_0,
  output io_perfInfo_bank_hit_1,
  output io_perfInfo_hit
);
  xs_ICacheMainPipe_core u_core (
    .clock(clock),
    .reset(reset),
    .io_dataArray_toIData_0_valid(io_dataArray_toIData_0_valid),
    .io_dataArray_toIData_0_bits_vSetIdx_0(io_dataArray_toIData_0_bits_vSetIdx_0),
    .io_dataArray_toIData_0_bits_vSetIdx_1(io_dataArray_toIData_0_bits_vSetIdx_1),
    .io_dataArray_toIData_0_bits_waymask_0_0(io_dataArray_toIData_0_bits_waymask_0_0),
    .io_dataArray_toIData_0_bits_waymask_0_1(io_dataArray_toIData_0_bits_waymask_0_1),
    .io_dataArray_toIData_0_bits_waymask_0_2(io_dataArray_toIData_0_bits_waymask_0_2),
    .io_dataArray_toIData_0_bits_waymask_0_3(io_dataArray_toIData_0_bits_waymask_0_3),
    .io_dataArray_toIData_0_bits_waymask_1_0(io_dataArray_toIData_0_bits_waymask_1_0),
    .io_dataArray_toIData_0_bits_waymask_1_1(io_dataArray_toIData_0_bits_waymask_1_1),
    .io_dataArray_toIData_0_bits_waymask_1_2(io_dataArray_toIData_0_bits_waymask_1_2),
    .io_dataArray_toIData_0_bits_waymask_1_3(io_dataArray_toIData_0_bits_waymask_1_3),
    .io_dataArray_toIData_0_bits_blkOffset(io_dataArray_toIData_0_bits_blkOffset),
    .io_dataArray_toIData_1_valid(io_dataArray_toIData_1_valid),
    .io_dataArray_toIData_1_bits_vSetIdx_0(io_dataArray_toIData_1_bits_vSetIdx_0),
    .io_dataArray_toIData_1_bits_vSetIdx_1(io_dataArray_toIData_1_bits_vSetIdx_1),
    .io_dataArray_toIData_2_valid(io_dataArray_toIData_2_valid),
    .io_dataArray_toIData_2_bits_vSetIdx_0(io_dataArray_toIData_2_bits_vSetIdx_0),
    .io_dataArray_toIData_2_bits_vSetIdx_1(io_dataArray_toIData_2_bits_vSetIdx_1),
    .io_dataArray_toIData_3_ready(io_dataArray_toIData_3_ready),
    .io_dataArray_toIData_3_valid(io_dataArray_toIData_3_valid),
    .io_dataArray_toIData_3_bits_vSetIdx_0(io_dataArray_toIData_3_bits_vSetIdx_0),
    .io_dataArray_toIData_3_bits_vSetIdx_1(io_dataArray_toIData_3_bits_vSetIdx_1),
    .io_dataArray_fromIData_datas_0(io_dataArray_fromIData_datas_0),
    .io_dataArray_fromIData_datas_1(io_dataArray_fromIData_datas_1),
    .io_dataArray_fromIData_datas_2(io_dataArray_fromIData_datas_2),
    .io_dataArray_fromIData_datas_3(io_dataArray_fromIData_datas_3),
    .io_dataArray_fromIData_datas_4(io_dataArray_fromIData_datas_4),
    .io_dataArray_fromIData_datas_5(io_dataArray_fromIData_datas_5),
    .io_dataArray_fromIData_datas_6(io_dataArray_fromIData_datas_6),
    .io_dataArray_fromIData_datas_7(io_dataArray_fromIData_datas_7),
    .io_dataArray_fromIData_codes_0(io_dataArray_fromIData_codes_0),
    .io_dataArray_fromIData_codes_1(io_dataArray_fromIData_codes_1),
    .io_dataArray_fromIData_codes_2(io_dataArray_fromIData_codes_2),
    .io_dataArray_fromIData_codes_3(io_dataArray_fromIData_codes_3),
    .io_dataArray_fromIData_codes_4(io_dataArray_fromIData_codes_4),
    .io_dataArray_fromIData_codes_5(io_dataArray_fromIData_codes_5),
    .io_dataArray_fromIData_codes_6(io_dataArray_fromIData_codes_6),
    .io_dataArray_fromIData_codes_7(io_dataArray_fromIData_codes_7),
    .io_metaArrayFlush_0_valid(io_metaArrayFlush_0_valid),
    .io_metaArrayFlush_0_bits_virIdx(io_metaArrayFlush_0_bits_virIdx),
    .io_metaArrayFlush_0_bits_waymask(io_metaArrayFlush_0_bits_waymask),
    .io_metaArrayFlush_1_valid(io_metaArrayFlush_1_valid),
    .io_metaArrayFlush_1_bits_virIdx(io_metaArrayFlush_1_bits_virIdx),
    .io_metaArrayFlush_1_bits_waymask(io_metaArrayFlush_1_bits_waymask),
    .io_touch_0_valid(io_touch_0_valid),
    .io_touch_0_bits_vSetIdx(io_touch_0_bits_vSetIdx),
    .io_touch_0_bits_way(io_touch_0_bits_way),
    .io_touch_1_valid(io_touch_1_valid),
    .io_touch_1_bits_vSetIdx(io_touch_1_bits_vSetIdx),
    .io_touch_1_bits_way(io_touch_1_bits_way),
    .io_wayLookupRead_ready(io_wayLookupRead_ready),
    .io_wayLookupRead_valid(io_wayLookupRead_valid),
    .io_wayLookupRead_bits_entry_vSetIdx_0(io_wayLookupRead_bits_entry_vSetIdx_0),
    .io_wayLookupRead_bits_entry_vSetIdx_1(io_wayLookupRead_bits_entry_vSetIdx_1),
    .io_wayLookupRead_bits_entry_waymask_0(io_wayLookupRead_bits_entry_waymask_0),
    .io_wayLookupRead_bits_entry_waymask_1(io_wayLookupRead_bits_entry_waymask_1),
    .io_wayLookupRead_bits_entry_ptag_0(io_wayLookupRead_bits_entry_ptag_0),
    .io_wayLookupRead_bits_entry_ptag_1(io_wayLookupRead_bits_entry_ptag_1),
    .io_wayLookupRead_bits_entry_itlb_exception_0(io_wayLookupRead_bits_entry_itlb_exception_0),
    .io_wayLookupRead_bits_entry_itlb_exception_1(io_wayLookupRead_bits_entry_itlb_exception_1),
    .io_wayLookupRead_bits_entry_itlb_pbmt_0(io_wayLookupRead_bits_entry_itlb_pbmt_0),
    .io_wayLookupRead_bits_entry_itlb_pbmt_1(io_wayLookupRead_bits_entry_itlb_pbmt_1),
    .io_wayLookupRead_bits_entry_meta_codes_0(io_wayLookupRead_bits_entry_meta_codes_0),
    .io_wayLookupRead_bits_entry_meta_codes_1(io_wayLookupRead_bits_entry_meta_codes_1),
    .io_wayLookupRead_bits_gpf_gpaddr(io_wayLookupRead_bits_gpf_gpaddr),
    .io_wayLookupRead_bits_gpf_isForVSnonLeafPTE(io_wayLookupRead_bits_gpf_isForVSnonLeafPTE),
    .io_mshr_req_ready(io_mshr_req_ready),
    .io_mshr_req_valid(io_mshr_req_valid),
    .io_mshr_req_bits_blkPaddr(io_mshr_req_bits_blkPaddr),
    .io_mshr_req_bits_vSetIdx(io_mshr_req_bits_vSetIdx),
    .io_mshr_resp_valid(io_mshr_resp_valid),
    .io_mshr_resp_bits_blkPaddr(io_mshr_resp_bits_blkPaddr),
    .io_mshr_resp_bits_vSetIdx(io_mshr_resp_bits_vSetIdx),
    .io_mshr_resp_bits_data(io_mshr_resp_bits_data),
    .io_mshr_resp_bits_corrupt(io_mshr_resp_bits_corrupt),
    .io_ecc_enable(io_ecc_enable),
    .io_fetch_req_ready(io_fetch_req_ready),
    .io_fetch_req_valid(io_fetch_req_valid),
    .io_fetch_req_bits_pcMemRead_0_startAddr(io_fetch_req_bits_pcMemRead_0_startAddr),
    .io_fetch_req_bits_pcMemRead_0_nextlineStart(io_fetch_req_bits_pcMemRead_0_nextlineStart),
    .io_fetch_req_bits_pcMemRead_1_startAddr(io_fetch_req_bits_pcMemRead_1_startAddr),
    .io_fetch_req_bits_pcMemRead_1_nextlineStart(io_fetch_req_bits_pcMemRead_1_nextlineStart),
    .io_fetch_req_bits_pcMemRead_2_startAddr(io_fetch_req_bits_pcMemRead_2_startAddr),
    .io_fetch_req_bits_pcMemRead_2_nextlineStart(io_fetch_req_bits_pcMemRead_2_nextlineStart),
    .io_fetch_req_bits_pcMemRead_3_startAddr(io_fetch_req_bits_pcMemRead_3_startAddr),
    .io_fetch_req_bits_pcMemRead_3_nextlineStart(io_fetch_req_bits_pcMemRead_3_nextlineStart),
    .io_fetch_req_bits_pcMemRead_4_startAddr(io_fetch_req_bits_pcMemRead_4_startAddr),
    .io_fetch_req_bits_pcMemRead_4_nextlineStart(io_fetch_req_bits_pcMemRead_4_nextlineStart),
    .io_fetch_req_bits_readValid_0(io_fetch_req_bits_readValid_0),
    .io_fetch_req_bits_readValid_1(io_fetch_req_bits_readValid_1),
    .io_fetch_req_bits_readValid_2(io_fetch_req_bits_readValid_2),
    .io_fetch_req_bits_readValid_3(io_fetch_req_bits_readValid_3),
    .io_fetch_req_bits_readValid_4(io_fetch_req_bits_readValid_4),
    .io_fetch_req_bits_backendException(io_fetch_req_bits_backendException),
    .io_fetch_resp_valid(io_fetch_resp_valid),
    .io_fetch_resp_bits_doubleline(io_fetch_resp_bits_doubleline),
    .io_fetch_resp_bits_vaddr_0(io_fetch_resp_bits_vaddr_0),
    .io_fetch_resp_bits_vaddr_1(io_fetch_resp_bits_vaddr_1),
    .io_fetch_resp_bits_data(io_fetch_resp_bits_data),
    .io_fetch_resp_bits_paddr_0(io_fetch_resp_bits_paddr_0),
    .io_fetch_resp_bits_exception_0(io_fetch_resp_bits_exception_0),
    .io_fetch_resp_bits_exception_1(io_fetch_resp_bits_exception_1),
    .io_fetch_resp_bits_pmp_mmio_0(io_fetch_resp_bits_pmp_mmio_0),
    .io_fetch_resp_bits_pmp_mmio_1(io_fetch_resp_bits_pmp_mmio_1),
    .io_fetch_resp_bits_itlb_pbmt_0(io_fetch_resp_bits_itlb_pbmt_0),
    .io_fetch_resp_bits_itlb_pbmt_1(io_fetch_resp_bits_itlb_pbmt_1),
    .io_fetch_resp_bits_backendException(io_fetch_resp_bits_backendException),
    .io_fetch_resp_bits_gpaddr(io_fetch_resp_bits_gpaddr),
    .io_fetch_resp_bits_isForVSnonLeafPTE(io_fetch_resp_bits_isForVSnonLeafPTE),
    .io_fetch_topdownIcacheMiss(io_fetch_topdownIcacheMiss),
    .io_fetch_topdownItlbMiss(io_fetch_topdownItlbMiss),
    .io_flush(io_flush),
    .io_pmp_0_req_bits_addr(io_pmp_0_req_bits_addr),
    .io_pmp_0_resp_instr(io_pmp_0_resp_instr),
    .io_pmp_0_resp_mmio(io_pmp_0_resp_mmio),
    .io_pmp_1_req_bits_addr(io_pmp_1_req_bits_addr),
    .io_pmp_1_resp_instr(io_pmp_1_resp_instr),
    .io_pmp_1_resp_mmio(io_pmp_1_resp_mmio),
    .io_respStall(io_respStall),
    .io_errors_0_valid(io_errors_0_valid),
    .io_errors_0_bits_paddr(io_errors_0_bits_paddr),
    .io_errors_0_bits_report_to_beu(io_errors_0_bits_report_to_beu),
    .io_errors_1_valid(io_errors_1_valid),
    .io_errors_1_bits_paddr(io_errors_1_bits_paddr),
    .io_errors_1_bits_report_to_beu(io_errors_1_bits_report_to_beu),
    .io_perfInfo_only_0_hit(io_perfInfo_only_0_hit),
    .io_perfInfo_only_0_miss(io_perfInfo_only_0_miss),
    .io_perfInfo_hit_0_hit_1(io_perfInfo_hit_0_hit_1),
    .io_perfInfo_hit_0_miss_1(io_perfInfo_hit_0_miss_1),
    .io_perfInfo_miss_0_hit_1(io_perfInfo_miss_0_hit_1),
    .io_perfInfo_miss_0_miss_1(io_perfInfo_miss_0_miss_1),
    .io_perfInfo_hit_0_except_1(io_perfInfo_hit_0_except_1),
    .io_perfInfo_miss_0_except_1(io_perfInfo_miss_0_except_1),
    .io_perfInfo_except_0(io_perfInfo_except_0),
    .io_perfInfo_bank_hit_0(io_perfInfo_bank_hit_0),
    .io_perfInfo_bank_hit_1(io_perfInfo_bank_hit_1),
    .io_perfInfo_hit(io_perfInfo_hit)
  );
endmodule
