// 自动生成: verif/bt/MemBlock/gen_bt.py —— 勿手改
// DCacheWrapper_bt: 全 golden 端口 BT 包装, 例化已验证的 DCacheWrapper_xs(暴露 golden 名子集 + 真重写 glue + xs_DCacheWrapper_core),
//   golden-only input 悬空 / golden-only output 透传重建或接 '0(rewrite 省略的元数据/debug 端口)。
module DCacheWrapper_bt(
  input clock,
  input reset,
  output auto_uncache_in_a_ready,
  input auto_uncache_in_a_valid,
  input [3:0] auto_uncache_in_a_bits_opcode,
  input [1:0] auto_uncache_in_a_bits_size,
  input [1:0] auto_uncache_in_a_bits_source,
  input [29:0] auto_uncache_in_a_bits_address,
  input [7:0] auto_uncache_in_a_bits_mask,
  input [63:0] auto_uncache_in_a_bits_data,
  input auto_uncache_in_d_ready,
  output auto_uncache_in_d_valid,
  output [3:0] auto_uncache_in_d_bits_opcode,
  output [1:0] auto_uncache_in_d_bits_size,
  output [1:0] auto_uncache_in_d_bits_source,
  output [63:0] auto_uncache_in_d_bits_data,
  input auto_client_out_a_ready,
  output auto_client_out_a_valid,
  output [3:0] auto_client_out_a_bits_opcode,
  output [2:0] auto_client_out_a_bits_param,
  output [2:0] auto_client_out_a_bits_size,
  output [5:0] auto_client_out_a_bits_source,
  output [47:0] auto_client_out_a_bits_address,
  output [1:0] auto_client_out_a_bits_user_alias,
  output [43:0] auto_client_out_a_bits_user_vaddr,
  output [4:0] auto_client_out_a_bits_user_reqSource,
  output auto_client_out_a_bits_user_needHint,
  output auto_client_out_a_bits_echo_isKeyword,
  output [31:0] auto_client_out_a_bits_mask,
  output auto_client_out_b_ready,
  input auto_client_out_b_valid,
  input [2:0] auto_client_out_b_bits_opcode,
  input [1:0] auto_client_out_b_bits_param,
  input [47:0] auto_client_out_b_bits_address,
  input [255:0] auto_client_out_b_bits_data,
  input auto_client_out_c_ready,
  output auto_client_out_c_valid,
  output [2:0] auto_client_out_c_bits_opcode,
  output [2:0] auto_client_out_c_bits_param,
  output [2:0] auto_client_out_c_bits_size,
  output [5:0] auto_client_out_c_bits_source,
  output [47:0] auto_client_out_c_bits_address,
  output [255:0] auto_client_out_c_bits_data,
  output auto_client_out_c_bits_corrupt,
  output auto_client_out_d_ready,
  input auto_client_out_d_valid,
  input [3:0] auto_client_out_d_bits_opcode,
  input [1:0] auto_client_out_d_bits_param,
  input [2:0] auto_client_out_d_bits_size,
  input [5:0] auto_client_out_d_bits_source,
  input [9:0] auto_client_out_d_bits_sink,
  input auto_client_out_d_bits_denied,
  input auto_client_out_d_bits_echo_isKeyword,
  input [255:0] auto_client_out_d_bits_data,
  input auto_client_out_d_bits_corrupt,
  input auto_client_out_e_ready,
  output auto_client_out_e_valid,
  output [9:0] auto_client_out_e_bits_sink,
  input [5:0] io_hartId,
  input io_l2_pf_store_only,
  output io_lsu_load_0_req_ready,
  input io_lsu_load_0_req_valid,
  input [4:0] io_lsu_load_0_req_bits_cmd,
  input [49:0] io_lsu_load_0_req_bits_vaddr,
  input [49:0] io_lsu_load_0_req_bits_vaddr_dup,
  input [3:0] io_lsu_load_0_req_bits_instrtype,
  input io_lsu_load_0_req_bits_isFirstIssue,
  input io_lsu_load_0_req_bits_lqIdx_flag,
  input [6:0] io_lsu_load_0_req_bits_lqIdx_value,
  output io_lsu_load_0_resp_valid,
  output [127:0] io_lsu_load_0_resp_bits_data,
  output [127:0] io_lsu_load_0_resp_bits_data_delayed,
  output io_lsu_load_0_resp_bits_miss,
  output [3:0] io_lsu_load_0_resp_bits_mshr_id,
  output [2:0] io_lsu_load_0_resp_bits_meta_prefetch,
  output io_lsu_load_0_resp_bits_handled,
  output io_lsu_load_0_resp_bits_error_delayed,
  input io_lsu_load_0_s1_kill,
  input io_lsu_load_0_s2_kill,
  input io_lsu_load_0_is128Req,
  input [2:0] io_lsu_load_0_pf_source,
  input [47:0] io_lsu_load_0_s1_paddr_dup_lsu,
  input [47:0] io_lsu_load_0_s1_paddr_dup_dcache,
  output io_lsu_load_0_s2_bank_conflict,
  output io_lsu_load_0_s2_mq_nack,
  output io_lsu_load_1_req_ready,
  input io_lsu_load_1_req_valid,
  input [4:0] io_lsu_load_1_req_bits_cmd,
  input [49:0] io_lsu_load_1_req_bits_vaddr,
  input [49:0] io_lsu_load_1_req_bits_vaddr_dup,
  input [3:0] io_lsu_load_1_req_bits_instrtype,
  input io_lsu_load_1_req_bits_isFirstIssue,
  input io_lsu_load_1_req_bits_lqIdx_flag,
  input [6:0] io_lsu_load_1_req_bits_lqIdx_value,
  output io_lsu_load_1_resp_valid,
  output [127:0] io_lsu_load_1_resp_bits_data,
  output io_lsu_load_1_resp_bits_miss,
  output [3:0] io_lsu_load_1_resp_bits_mshr_id,
  output [2:0] io_lsu_load_1_resp_bits_meta_prefetch,
  output io_lsu_load_1_resp_bits_handled,
  output io_lsu_load_1_resp_bits_error_delayed,
  input io_lsu_load_1_s1_kill,
  input io_lsu_load_1_s2_kill,
  input io_lsu_load_1_is128Req,
  input [2:0] io_lsu_load_1_pf_source,
  input [47:0] io_lsu_load_1_s1_paddr_dup_lsu,
  input [47:0] io_lsu_load_1_s1_paddr_dup_dcache,
  output io_lsu_load_1_s2_bank_conflict,
  output io_lsu_load_1_s2_mq_nack,
  output io_lsu_load_2_req_ready,
  input io_lsu_load_2_req_valid,
  input [4:0] io_lsu_load_2_req_bits_cmd,
  input [49:0] io_lsu_load_2_req_bits_vaddr,
  input [49:0] io_lsu_load_2_req_bits_vaddr_dup,
  input [3:0] io_lsu_load_2_req_bits_instrtype,
  input io_lsu_load_2_req_bits_isFirstIssue,
  input io_lsu_load_2_req_bits_lqIdx_flag,
  input [6:0] io_lsu_load_2_req_bits_lqIdx_value,
  output io_lsu_load_2_resp_valid,
  output [127:0] io_lsu_load_2_resp_bits_data,
  output io_lsu_load_2_resp_bits_miss,
  output [3:0] io_lsu_load_2_resp_bits_mshr_id,
  output [2:0] io_lsu_load_2_resp_bits_meta_prefetch,
  output io_lsu_load_2_resp_bits_handled,
  output io_lsu_load_2_resp_bits_error_delayed,
  input io_lsu_load_2_s1_kill,
  input io_lsu_load_2_s2_kill,
  input io_lsu_load_2_is128Req,
  input [2:0] io_lsu_load_2_pf_source,
  input [47:0] io_lsu_load_2_s1_paddr_dup_lsu,
  input [47:0] io_lsu_load_2_s1_paddr_dup_dcache,
  output io_lsu_load_2_s2_bank_conflict,
  output io_lsu_load_2_s2_mq_nack,
  input io_lsu_sta_0_req_valid,
  input io_lsu_sta_1_req_valid,
  output io_lsu_tl_d_channel_valid,
  output [3:0] io_lsu_tl_d_channel_mshrid,
  output io_lsu_store_req_ready,
  input io_lsu_store_req_valid,
  input [49:0] io_lsu_store_req_bits_vaddr,
  input [47:0] io_lsu_store_req_bits_addr,
  input [511:0] io_lsu_store_req_bits_data,
  input [63:0] io_lsu_store_req_bits_mask,
  input [5:0] io_lsu_store_req_bits_id,
  output io_lsu_store_main_pipe_hit_resp_valid,
  output [5:0] io_lsu_store_main_pipe_hit_resp_bits_id,
  output io_lsu_store_replay_resp_valid,
  output [5:0] io_lsu_store_replay_resp_bits_id,
  output io_lsu_atomics_req_ready,
  input io_lsu_atomics_req_valid,
  input [4:0] io_lsu_atomics_req_bits_cmd,
  input [49:0] io_lsu_atomics_req_bits_vaddr,
  input [47:0] io_lsu_atomics_req_bits_addr,
  input [2:0] io_lsu_atomics_req_bits_word_idx,
  input [127:0] io_lsu_atomics_req_bits_amo_data,
  input [15:0] io_lsu_atomics_req_bits_amo_mask,
  input [127:0] io_lsu_atomics_req_bits_amo_cmp,
  output io_lsu_atomics_resp_valid,
  output [127:0] io_lsu_atomics_resp_bits_data,
  output io_lsu_atomics_resp_bits_miss,
  output io_lsu_atomics_resp_bits_replay,
  output io_lsu_atomics_resp_bits_error,
  output [5:0] io_lsu_atomics_resp_bits_id,
  output io_lsu_atomics_block_lr,
  output io_lsu_release_valid,
  output [47:0] io_lsu_release_bits_paddr,
  output io_lsu_forward_D_0_valid,
  output [255:0] io_lsu_forward_D_0_data,
  output [3:0] io_lsu_forward_D_0_mshrid,
  output io_lsu_forward_D_0_last,
  output io_lsu_forward_D_0_corrupt,
  output io_lsu_forward_D_1_valid,
  output [255:0] io_lsu_forward_D_1_data,
  output [3:0] io_lsu_forward_D_1_mshrid,
  output io_lsu_forward_D_1_last,
  output io_lsu_forward_D_1_corrupt,
  output io_lsu_forward_D_2_valid,
  output [255:0] io_lsu_forward_D_2_data,
  output [3:0] io_lsu_forward_D_2_mshrid,
  output io_lsu_forward_D_2_last,
  output io_lsu_forward_D_2_corrupt,
  input io_lsu_forward_mshr_0_valid,
  input [3:0] io_lsu_forward_mshr_0_mshrid,
  input [47:0] io_lsu_forward_mshr_0_paddr,
  output io_lsu_forward_mshr_0_forward_mshr,
  output [7:0] io_lsu_forward_mshr_0_forwardData_0,
  output [7:0] io_lsu_forward_mshr_0_forwardData_1,
  output [7:0] io_lsu_forward_mshr_0_forwardData_2,
  output [7:0] io_lsu_forward_mshr_0_forwardData_3,
  output [7:0] io_lsu_forward_mshr_0_forwardData_4,
  output [7:0] io_lsu_forward_mshr_0_forwardData_5,
  output [7:0] io_lsu_forward_mshr_0_forwardData_6,
  output [7:0] io_lsu_forward_mshr_0_forwardData_7,
  output [7:0] io_lsu_forward_mshr_0_forwardData_8,
  output [7:0] io_lsu_forward_mshr_0_forwardData_9,
  output [7:0] io_lsu_forward_mshr_0_forwardData_10,
  output [7:0] io_lsu_forward_mshr_0_forwardData_11,
  output [7:0] io_lsu_forward_mshr_0_forwardData_12,
  output [7:0] io_lsu_forward_mshr_0_forwardData_13,
  output [7:0] io_lsu_forward_mshr_0_forwardData_14,
  output [7:0] io_lsu_forward_mshr_0_forwardData_15,
  output io_lsu_forward_mshr_0_forward_result_valid,
  output io_lsu_forward_mshr_0_corrupt,
  input io_lsu_forward_mshr_1_valid,
  input [3:0] io_lsu_forward_mshr_1_mshrid,
  input [47:0] io_lsu_forward_mshr_1_paddr,
  output io_lsu_forward_mshr_1_forward_mshr,
  output [7:0] io_lsu_forward_mshr_1_forwardData_0,
  output [7:0] io_lsu_forward_mshr_1_forwardData_1,
  output [7:0] io_lsu_forward_mshr_1_forwardData_2,
  output [7:0] io_lsu_forward_mshr_1_forwardData_3,
  output [7:0] io_lsu_forward_mshr_1_forwardData_4,
  output [7:0] io_lsu_forward_mshr_1_forwardData_5,
  output [7:0] io_lsu_forward_mshr_1_forwardData_6,
  output [7:0] io_lsu_forward_mshr_1_forwardData_7,
  output [7:0] io_lsu_forward_mshr_1_forwardData_8,
  output [7:0] io_lsu_forward_mshr_1_forwardData_9,
  output [7:0] io_lsu_forward_mshr_1_forwardData_10,
  output [7:0] io_lsu_forward_mshr_1_forwardData_11,
  output [7:0] io_lsu_forward_mshr_1_forwardData_12,
  output [7:0] io_lsu_forward_mshr_1_forwardData_13,
  output [7:0] io_lsu_forward_mshr_1_forwardData_14,
  output [7:0] io_lsu_forward_mshr_1_forwardData_15,
  output io_lsu_forward_mshr_1_forward_result_valid,
  output io_lsu_forward_mshr_1_corrupt,
  input io_lsu_forward_mshr_2_valid,
  input [3:0] io_lsu_forward_mshr_2_mshrid,
  input [47:0] io_lsu_forward_mshr_2_paddr,
  output io_lsu_forward_mshr_2_forward_mshr,
  output [7:0] io_lsu_forward_mshr_2_forwardData_0,
  output [7:0] io_lsu_forward_mshr_2_forwardData_1,
  output [7:0] io_lsu_forward_mshr_2_forwardData_2,
  output [7:0] io_lsu_forward_mshr_2_forwardData_3,
  output [7:0] io_lsu_forward_mshr_2_forwardData_4,
  output [7:0] io_lsu_forward_mshr_2_forwardData_5,
  output [7:0] io_lsu_forward_mshr_2_forwardData_6,
  output [7:0] io_lsu_forward_mshr_2_forwardData_7,
  output [7:0] io_lsu_forward_mshr_2_forwardData_8,
  output [7:0] io_lsu_forward_mshr_2_forwardData_9,
  output [7:0] io_lsu_forward_mshr_2_forwardData_10,
  output [7:0] io_lsu_forward_mshr_2_forwardData_11,
  output [7:0] io_lsu_forward_mshr_2_forwardData_12,
  output [7:0] io_lsu_forward_mshr_2_forwardData_13,
  output [7:0] io_lsu_forward_mshr_2_forwardData_14,
  output [7:0] io_lsu_forward_mshr_2_forwardData_15,
  output io_lsu_forward_mshr_2_forward_result_valid,
  output io_lsu_forward_mshr_2_corrupt,
  output io_error_valid,
  output [47:0] io_error_bits_paddr,
  output io_error_bits_report_to_beu,
  input io_lqEmpty,
  output io_pf_ctrl_enable,
  output io_pf_ctrl_confidence,
  output io_sms_agt_evict_req_valid,
  output [49:0] io_sms_agt_evict_req_bits_vaddr,
  input io_debugTopDown_robHeadVaddr_valid,
  input [49:0] io_debugTopDown_robHeadVaddr_bits,
  output io_debugTopDown_robHeadMissInDCache,
  input io_l2_hint_valid,
  input [3:0] io_l2_hint_bits_sourceId,
  output io_cmoOpReq_ready,
  input io_cmoOpReq_valid,
  input [2:0] io_cmoOpReq_bits_opcode,
  input [63:0] io_cmoOpReq_bits_address,
  input io_cmoOpResp_ready,
  output io_cmoOpResp_valid,
  output io_cmoOpResp_bits_nderr,
  output io_l1Miss,
  input io_wfi_wfiReq,
  output io_wfi_wfiSafe,
  output [5:0] io_perf_0_value,
  output [5:0] io_perf_1_value,
  output [5:0] io_perf_2_value,
  output [5:0] io_perf_3_value,
  output [5:0] io_perf_4_value,
  output [5:0] io_perf_5_value,
  output [5:0] io_perf_6_value,
  output [5:0] io_perf_7_value,
  output [5:0] io_perf_8_value,
  output [5:0] io_perf_9_value,
  output [5:0] io_perf_10_value,
  output [5:0] io_perf_11_value,
  output [5:0] io_perf_12_value,
  output [5:0] io_perf_13_value,
  output [5:0] io_perf_14_value,
  output [5:0] io_perf_15_value,
  output [5:0] io_perf_16_value,
  output [5:0] io_perf_17_value,
  output [5:0] io_perf_18_value,
  output [5:0] io_perf_19_value,
  output [5:0] io_perf_20_value,
  output [5:0] io_perf_21_value,
  output [5:0] io_perf_22_value,
  output [5:0] io_perf_23_value,
  output [5:0] io_perf_24_value,
  output [5:0] io_perf_25_value,
  output [5:0] io_perf_26_value,
  output [5:0] io_perf_27_value,
  output [5:0] io_perf_28_value,
  output [5:0] io_perf_29_value,
  output [5:0] io_perf_30_value,
  output [5:0] io_perf_31_value,
  input [4:0] boreChildrenBd_bore_array,
  input boreChildrenBd_bore_all,
  input boreChildrenBd_bore_req,
  output boreChildrenBd_bore_ack,
  input boreChildrenBd_bore_writeen,
  input boreChildrenBd_bore_be,
  input [8:0] boreChildrenBd_bore_addr,
  input [71:0] boreChildrenBd_bore_indata,
  input boreChildrenBd_bore_readen,
  input [8:0] boreChildrenBd_bore_addr_rd,
  output [71:0] boreChildrenBd_bore_outdata,
  input [5:0] boreChildrenBd_bore_1_array,
  input boreChildrenBd_bore_1_all,
  input boreChildrenBd_bore_1_req,
  output boreChildrenBd_bore_1_ack,
  input boreChildrenBd_bore_1_writeen,
  input [1:0] boreChildrenBd_bore_1_be,
  input [8:0] boreChildrenBd_bore_1_addr,
  input [85:0] boreChildrenBd_bore_1_indata,
  input boreChildrenBd_bore_1_readen,
  input [8:0] boreChildrenBd_bore_1_addr_rd,
  output [85:0] boreChildrenBd_bore_1_outdata,
  input sigFromSrams_bore_ram_hold,
  input sigFromSrams_bore_ram_bypass,
  input sigFromSrams_bore_ram_bp_clken,
  input sigFromSrams_bore_ram_aux_clk,
  input sigFromSrams_bore_ram_aux_ckbp,
  input sigFromSrams_bore_ram_mcp_hold,
  input sigFromSrams_bore_cgen,
  input sigFromSrams_bore_1_ram_hold,
  input sigFromSrams_bore_1_ram_bypass,
  input sigFromSrams_bore_1_ram_bp_clken,
  input sigFromSrams_bore_1_ram_aux_clk,
  input sigFromSrams_bore_1_ram_aux_ckbp,
  input sigFromSrams_bore_1_ram_mcp_hold,
  input sigFromSrams_bore_1_cgen,
  input sigFromSrams_bore_2_ram_hold,
  input sigFromSrams_bore_2_ram_bypass,
  input sigFromSrams_bore_2_ram_bp_clken,
  input sigFromSrams_bore_2_ram_aux_clk,
  input sigFromSrams_bore_2_ram_aux_ckbp,
  input sigFromSrams_bore_2_ram_mcp_hold,
  input sigFromSrams_bore_2_cgen,
  input sigFromSrams_bore_3_ram_hold,
  input sigFromSrams_bore_3_ram_bypass,
  input sigFromSrams_bore_3_ram_bp_clken,
  input sigFromSrams_bore_3_ram_aux_clk,
  input sigFromSrams_bore_3_ram_aux_ckbp,
  input sigFromSrams_bore_3_ram_mcp_hold,
  input sigFromSrams_bore_3_cgen,
  input sigFromSrams_bore_4_ram_hold,
  input sigFromSrams_bore_4_ram_bypass,
  input sigFromSrams_bore_4_ram_bp_clken,
  input sigFromSrams_bore_4_ram_aux_clk,
  input sigFromSrams_bore_4_ram_aux_ckbp,
  input sigFromSrams_bore_4_ram_mcp_hold,
  input sigFromSrams_bore_4_cgen,
  input sigFromSrams_bore_5_ram_hold,
  input sigFromSrams_bore_5_ram_bypass,
  input sigFromSrams_bore_5_ram_bp_clken,
  input sigFromSrams_bore_5_ram_aux_clk,
  input sigFromSrams_bore_5_ram_aux_ckbp,
  input sigFromSrams_bore_5_ram_mcp_hold,
  input sigFromSrams_bore_5_cgen,
  input sigFromSrams_bore_6_ram_hold,
  input sigFromSrams_bore_6_ram_bypass,
  input sigFromSrams_bore_6_ram_bp_clken,
  input sigFromSrams_bore_6_ram_aux_clk,
  input sigFromSrams_bore_6_ram_aux_ckbp,
  input sigFromSrams_bore_6_ram_mcp_hold,
  input sigFromSrams_bore_6_cgen,
  input sigFromSrams_bore_7_ram_hold,
  input sigFromSrams_bore_7_ram_bypass,
  input sigFromSrams_bore_7_ram_bp_clken,
  input sigFromSrams_bore_7_ram_aux_clk,
  input sigFromSrams_bore_7_ram_aux_ckbp,
  input sigFromSrams_bore_7_ram_mcp_hold,
  input sigFromSrams_bore_7_cgen,
  input sigFromSrams_bore_8_ram_hold,
  input sigFromSrams_bore_8_ram_bypass,
  input sigFromSrams_bore_8_ram_bp_clken,
  input sigFromSrams_bore_8_ram_aux_clk,
  input sigFromSrams_bore_8_ram_aux_ckbp,
  input sigFromSrams_bore_8_ram_mcp_hold,
  input sigFromSrams_bore_8_cgen,
  input sigFromSrams_bore_9_ram_hold,
  input sigFromSrams_bore_9_ram_bypass,
  input sigFromSrams_bore_9_ram_bp_clken,
  input sigFromSrams_bore_9_ram_aux_clk,
  input sigFromSrams_bore_9_ram_aux_ckbp,
  input sigFromSrams_bore_9_ram_mcp_hold,
  input sigFromSrams_bore_9_cgen,
  input sigFromSrams_bore_10_ram_hold,
  input sigFromSrams_bore_10_ram_bypass,
  input sigFromSrams_bore_10_ram_bp_clken,
  input sigFromSrams_bore_10_ram_aux_clk,
  input sigFromSrams_bore_10_ram_aux_ckbp,
  input sigFromSrams_bore_10_ram_mcp_hold,
  input sigFromSrams_bore_10_cgen,
  input sigFromSrams_bore_11_ram_hold,
  input sigFromSrams_bore_11_ram_bypass,
  input sigFromSrams_bore_11_ram_bp_clken,
  input sigFromSrams_bore_11_ram_aux_clk,
  input sigFromSrams_bore_11_ram_aux_ckbp,
  input sigFromSrams_bore_11_ram_mcp_hold,
  input sigFromSrams_bore_11_cgen,
  input sigFromSrams_bore_12_ram_hold,
  input sigFromSrams_bore_12_ram_bypass,
  input sigFromSrams_bore_12_ram_bp_clken,
  input sigFromSrams_bore_12_ram_aux_clk,
  input sigFromSrams_bore_12_ram_aux_ckbp,
  input sigFromSrams_bore_12_ram_mcp_hold,
  input sigFromSrams_bore_12_cgen,
  input sigFromSrams_bore_13_ram_hold,
  input sigFromSrams_bore_13_ram_bypass,
  input sigFromSrams_bore_13_ram_bp_clken,
  input sigFromSrams_bore_13_ram_aux_clk,
  input sigFromSrams_bore_13_ram_aux_ckbp,
  input sigFromSrams_bore_13_ram_mcp_hold,
  input sigFromSrams_bore_13_cgen,
  input sigFromSrams_bore_14_ram_hold,
  input sigFromSrams_bore_14_ram_bypass,
  input sigFromSrams_bore_14_ram_bp_clken,
  input sigFromSrams_bore_14_ram_aux_clk,
  input sigFromSrams_bore_14_ram_aux_ckbp,
  input sigFromSrams_bore_14_ram_mcp_hold,
  input sigFromSrams_bore_14_cgen,
  input sigFromSrams_bore_15_ram_hold,
  input sigFromSrams_bore_15_ram_bypass,
  input sigFromSrams_bore_15_ram_bp_clken,
  input sigFromSrams_bore_15_ram_aux_clk,
  input sigFromSrams_bore_15_ram_aux_ckbp,
  input sigFromSrams_bore_15_ram_mcp_hold,
  input sigFromSrams_bore_15_cgen,
  input sigFromSrams_bore_16_ram_hold,
  input sigFromSrams_bore_16_ram_bypass,
  input sigFromSrams_bore_16_ram_bp_clken,
  input sigFromSrams_bore_16_ram_aux_clk,
  input sigFromSrams_bore_16_ram_aux_ckbp,
  input sigFromSrams_bore_16_ram_mcp_hold,
  input sigFromSrams_bore_16_cgen,
  input sigFromSrams_bore_17_ram_hold,
  input sigFromSrams_bore_17_ram_bypass,
  input sigFromSrams_bore_17_ram_bp_clken,
  input sigFromSrams_bore_17_ram_aux_clk,
  input sigFromSrams_bore_17_ram_aux_ckbp,
  input sigFromSrams_bore_17_ram_mcp_hold,
  input sigFromSrams_bore_17_cgen,
  input sigFromSrams_bore_18_ram_hold,
  input sigFromSrams_bore_18_ram_bypass,
  input sigFromSrams_bore_18_ram_bp_clken,
  input sigFromSrams_bore_18_ram_aux_clk,
  input sigFromSrams_bore_18_ram_aux_ckbp,
  input sigFromSrams_bore_18_ram_mcp_hold,
  input sigFromSrams_bore_18_cgen,
  input sigFromSrams_bore_19_ram_hold,
  input sigFromSrams_bore_19_ram_bypass,
  input sigFromSrams_bore_19_ram_bp_clken,
  input sigFromSrams_bore_19_ram_aux_clk,
  input sigFromSrams_bore_19_ram_aux_ckbp,
  input sigFromSrams_bore_19_ram_mcp_hold,
  input sigFromSrams_bore_19_cgen,
  input sigFromSrams_bore_20_ram_hold,
  input sigFromSrams_bore_20_ram_bypass,
  input sigFromSrams_bore_20_ram_bp_clken,
  input sigFromSrams_bore_20_ram_aux_clk,
  input sigFromSrams_bore_20_ram_aux_ckbp,
  input sigFromSrams_bore_20_ram_mcp_hold,
  input sigFromSrams_bore_20_cgen,
  input sigFromSrams_bore_21_ram_hold,
  input sigFromSrams_bore_21_ram_bypass,
  input sigFromSrams_bore_21_ram_bp_clken,
  input sigFromSrams_bore_21_ram_aux_clk,
  input sigFromSrams_bore_21_ram_aux_ckbp,
  input sigFromSrams_bore_21_ram_mcp_hold,
  input sigFromSrams_bore_21_cgen,
  input sigFromSrams_bore_22_ram_hold,
  input sigFromSrams_bore_22_ram_bypass,
  input sigFromSrams_bore_22_ram_bp_clken,
  input sigFromSrams_bore_22_ram_aux_clk,
  input sigFromSrams_bore_22_ram_aux_ckbp,
  input sigFromSrams_bore_22_ram_mcp_hold,
  input sigFromSrams_bore_22_cgen,
  input sigFromSrams_bore_23_ram_hold,
  input sigFromSrams_bore_23_ram_bypass,
  input sigFromSrams_bore_23_ram_bp_clken,
  input sigFromSrams_bore_23_ram_aux_clk,
  input sigFromSrams_bore_23_ram_aux_ckbp,
  input sigFromSrams_bore_23_ram_mcp_hold,
  input sigFromSrams_bore_23_cgen,
  input sigFromSrams_bore_24_ram_hold,
  input sigFromSrams_bore_24_ram_bypass,
  input sigFromSrams_bore_24_ram_bp_clken,
  input sigFromSrams_bore_24_ram_aux_clk,
  input sigFromSrams_bore_24_ram_aux_ckbp,
  input sigFromSrams_bore_24_ram_mcp_hold,
  input sigFromSrams_bore_24_cgen,
  input sigFromSrams_bore_25_ram_hold,
  input sigFromSrams_bore_25_ram_bypass,
  input sigFromSrams_bore_25_ram_bp_clken,
  input sigFromSrams_bore_25_ram_aux_clk,
  input sigFromSrams_bore_25_ram_aux_ckbp,
  input sigFromSrams_bore_25_ram_mcp_hold,
  input sigFromSrams_bore_25_cgen,
  input sigFromSrams_bore_26_ram_hold,
  input sigFromSrams_bore_26_ram_bypass,
  input sigFromSrams_bore_26_ram_bp_clken,
  input sigFromSrams_bore_26_ram_aux_clk,
  input sigFromSrams_bore_26_ram_aux_ckbp,
  input sigFromSrams_bore_26_ram_mcp_hold,
  input sigFromSrams_bore_26_cgen,
  input sigFromSrams_bore_27_ram_hold,
  input sigFromSrams_bore_27_ram_bypass,
  input sigFromSrams_bore_27_ram_bp_clken,
  input sigFromSrams_bore_27_ram_aux_clk,
  input sigFromSrams_bore_27_ram_aux_ckbp,
  input sigFromSrams_bore_27_ram_mcp_hold,
  input sigFromSrams_bore_27_cgen,
  input sigFromSrams_bore_28_ram_hold,
  input sigFromSrams_bore_28_ram_bypass,
  input sigFromSrams_bore_28_ram_bp_clken,
  input sigFromSrams_bore_28_ram_aux_clk,
  input sigFromSrams_bore_28_ram_aux_ckbp,
  input sigFromSrams_bore_28_ram_mcp_hold,
  input sigFromSrams_bore_28_cgen,
  input sigFromSrams_bore_29_ram_hold,
  input sigFromSrams_bore_29_ram_bypass,
  input sigFromSrams_bore_29_ram_bp_clken,
  input sigFromSrams_bore_29_ram_aux_clk,
  input sigFromSrams_bore_29_ram_aux_ckbp,
  input sigFromSrams_bore_29_ram_mcp_hold,
  input sigFromSrams_bore_29_cgen,
  input sigFromSrams_bore_30_ram_hold,
  input sigFromSrams_bore_30_ram_bypass,
  input sigFromSrams_bore_30_ram_bp_clken,
  input sigFromSrams_bore_30_ram_aux_clk,
  input sigFromSrams_bore_30_ram_aux_ckbp,
  input sigFromSrams_bore_30_ram_mcp_hold,
  input sigFromSrams_bore_30_cgen,
  input sigFromSrams_bore_31_ram_hold,
  input sigFromSrams_bore_31_ram_bypass,
  input sigFromSrams_bore_31_ram_bp_clken,
  input sigFromSrams_bore_31_ram_aux_clk,
  input sigFromSrams_bore_31_ram_aux_ckbp,
  input sigFromSrams_bore_31_ram_mcp_hold,
  input sigFromSrams_bore_31_cgen,
  input sigFromSrams_bore_32_ram_hold,
  input sigFromSrams_bore_32_ram_bypass,
  input sigFromSrams_bore_32_ram_bp_clken,
  input sigFromSrams_bore_32_ram_aux_clk,
  input sigFromSrams_bore_32_ram_aux_ckbp,
  input sigFromSrams_bore_32_ram_mcp_hold,
  input sigFromSrams_bore_32_cgen,
  input sigFromSrams_bore_33_ram_hold,
  input sigFromSrams_bore_33_ram_bypass,
  input sigFromSrams_bore_33_ram_bp_clken,
  input sigFromSrams_bore_33_ram_aux_clk,
  input sigFromSrams_bore_33_ram_aux_ckbp,
  input sigFromSrams_bore_33_ram_mcp_hold,
  input sigFromSrams_bore_33_cgen,
  input sigFromSrams_bore_34_ram_hold,
  input sigFromSrams_bore_34_ram_bypass,
  input sigFromSrams_bore_34_ram_bp_clken,
  input sigFromSrams_bore_34_ram_aux_clk,
  input sigFromSrams_bore_34_ram_aux_ckbp,
  input sigFromSrams_bore_34_ram_mcp_hold,
  input sigFromSrams_bore_34_cgen,
  input sigFromSrams_bore_35_ram_hold,
  input sigFromSrams_bore_35_ram_bypass,
  input sigFromSrams_bore_35_ram_bp_clken,
  input sigFromSrams_bore_35_ram_aux_clk,
  input sigFromSrams_bore_35_ram_aux_ckbp,
  input sigFromSrams_bore_35_ram_mcp_hold,
  input sigFromSrams_bore_35_cgen,
  input sigFromSrams_bore_36_ram_hold,
  input sigFromSrams_bore_36_ram_bypass,
  input sigFromSrams_bore_36_ram_bp_clken,
  input sigFromSrams_bore_36_ram_aux_clk,
  input sigFromSrams_bore_36_ram_aux_ckbp,
  input sigFromSrams_bore_36_ram_mcp_hold,
  input sigFromSrams_bore_36_cgen,
  input sigFromSrams_bore_37_ram_hold,
  input sigFromSrams_bore_37_ram_bypass,
  input sigFromSrams_bore_37_ram_bp_clken,
  input sigFromSrams_bore_37_ram_aux_clk,
  input sigFromSrams_bore_37_ram_aux_ckbp,
  input sigFromSrams_bore_37_ram_mcp_hold,
  input sigFromSrams_bore_37_cgen,
  input sigFromSrams_bore_38_ram_hold,
  input sigFromSrams_bore_38_ram_bypass,
  input sigFromSrams_bore_38_ram_bp_clken,
  input sigFromSrams_bore_38_ram_aux_clk,
  input sigFromSrams_bore_38_ram_aux_ckbp,
  input sigFromSrams_bore_38_ram_mcp_hold,
  input sigFromSrams_bore_38_cgen,
  input sigFromSrams_bore_39_ram_hold,
  input sigFromSrams_bore_39_ram_bypass,
  input sigFromSrams_bore_39_ram_bp_clken,
  input sigFromSrams_bore_39_ram_aux_clk,
  input sigFromSrams_bore_39_ram_aux_ckbp,
  input sigFromSrams_bore_39_ram_mcp_hold,
  input sigFromSrams_bore_39_cgen
);
  DCacheWrapper_xs u_xs (
    .clock(clock),
    .reset(reset),
    .auto_uncache_in_a_ready(auto_uncache_in_a_ready),
    .auto_uncache_in_a_valid(auto_uncache_in_a_valid),
    .auto_uncache_in_a_bits_opcode(auto_uncache_in_a_bits_opcode),
    .auto_uncache_in_a_bits_size(auto_uncache_in_a_bits_size),
    .auto_uncache_in_a_bits_source(auto_uncache_in_a_bits_source),
    .auto_uncache_in_a_bits_address(auto_uncache_in_a_bits_address),
    .auto_uncache_in_a_bits_mask(auto_uncache_in_a_bits_mask),
    .auto_uncache_in_a_bits_data(auto_uncache_in_a_bits_data),
    .auto_uncache_in_d_ready(auto_uncache_in_d_ready),
    .auto_uncache_in_d_valid(auto_uncache_in_d_valid),
    .auto_uncache_in_d_bits_opcode(auto_uncache_in_d_bits_opcode),
    .auto_uncache_in_d_bits_size(auto_uncache_in_d_bits_size),
    .auto_uncache_in_d_bits_source(auto_uncache_in_d_bits_source),
    .auto_uncache_in_d_bits_data(auto_uncache_in_d_bits_data),
    .auto_client_out_a_ready(auto_client_out_a_ready),
    .auto_client_out_a_valid(auto_client_out_a_valid),
    .auto_client_out_a_bits_opcode(auto_client_out_a_bits_opcode),
    .auto_client_out_a_bits_param(auto_client_out_a_bits_param),
    .auto_client_out_a_bits_size(auto_client_out_a_bits_size),
    .auto_client_out_a_bits_source(auto_client_out_a_bits_source),
    .auto_client_out_a_bits_address(auto_client_out_a_bits_address),
    .auto_client_out_a_bits_user_alias(auto_client_out_a_bits_user_alias),
    .auto_client_out_a_bits_user_vaddr(auto_client_out_a_bits_user_vaddr),
    .auto_client_out_a_bits_user_reqSource(auto_client_out_a_bits_user_reqSource),
    .auto_client_out_a_bits_user_needHint(auto_client_out_a_bits_user_needHint),
    .auto_client_out_a_bits_echo_isKeyword(auto_client_out_a_bits_echo_isKeyword),
    .auto_client_out_a_bits_mask(auto_client_out_a_bits_mask),
    .auto_client_out_b_ready(auto_client_out_b_ready),
    .auto_client_out_b_valid(auto_client_out_b_valid),
    .auto_client_out_b_bits_opcode(auto_client_out_b_bits_opcode),
    .auto_client_out_b_bits_param(auto_client_out_b_bits_param),
    .auto_client_out_b_bits_address(auto_client_out_b_bits_address),
    .auto_client_out_b_bits_data(auto_client_out_b_bits_data),
    .auto_client_out_c_ready(auto_client_out_c_ready),
    .auto_client_out_c_valid(auto_client_out_c_valid),
    .auto_client_out_c_bits_opcode(auto_client_out_c_bits_opcode),
    .auto_client_out_c_bits_param(auto_client_out_c_bits_param),
    .auto_client_out_c_bits_size(auto_client_out_c_bits_size),
    .auto_client_out_c_bits_source(auto_client_out_c_bits_source),
    .auto_client_out_c_bits_address(auto_client_out_c_bits_address),
    .auto_client_out_c_bits_data(auto_client_out_c_bits_data),
    .auto_client_out_c_bits_corrupt(auto_client_out_c_bits_corrupt),
    .auto_client_out_d_ready(auto_client_out_d_ready),
    .auto_client_out_d_valid(auto_client_out_d_valid),
    .auto_client_out_d_bits_opcode(auto_client_out_d_bits_opcode),
    .auto_client_out_d_bits_param(auto_client_out_d_bits_param),
    .auto_client_out_d_bits_size(auto_client_out_d_bits_size),
    .auto_client_out_d_bits_source(auto_client_out_d_bits_source),
    .auto_client_out_d_bits_sink(auto_client_out_d_bits_sink),
    .auto_client_out_d_bits_denied(auto_client_out_d_bits_denied),
    .auto_client_out_d_bits_echo_isKeyword(auto_client_out_d_bits_echo_isKeyword),
    .auto_client_out_d_bits_data(auto_client_out_d_bits_data),
    .auto_client_out_d_bits_corrupt(auto_client_out_d_bits_corrupt),
    .auto_client_out_e_ready(auto_client_out_e_ready),
    .auto_client_out_e_valid(auto_client_out_e_valid),
    .auto_client_out_e_bits_sink(auto_client_out_e_bits_sink),
    .io_l2_pf_store_only(io_l2_pf_store_only),
    .io_lsu_load_0_req_ready(io_lsu_load_0_req_ready),
    .io_lsu_load_0_req_valid(io_lsu_load_0_req_valid),
    .io_lsu_load_0_req_bits_cmd(io_lsu_load_0_req_bits_cmd),
    .io_lsu_load_0_req_bits_vaddr(io_lsu_load_0_req_bits_vaddr),
    .io_lsu_load_0_req_bits_vaddr_dup(io_lsu_load_0_req_bits_vaddr_dup),
    .io_lsu_load_0_req_bits_instrtype(io_lsu_load_0_req_bits_instrtype),
    .io_lsu_load_0_req_bits_isFirstIssue(io_lsu_load_0_req_bits_isFirstIssue),
    .io_lsu_load_0_req_bits_lqIdx_flag(io_lsu_load_0_req_bits_lqIdx_flag),
    .io_lsu_load_0_req_bits_lqIdx_value(io_lsu_load_0_req_bits_lqIdx_value),
    .io_lsu_load_0_resp_valid(io_lsu_load_0_resp_valid),
    .io_lsu_load_0_resp_bits_data(io_lsu_load_0_resp_bits_data),
    .io_lsu_load_0_resp_bits_data_delayed(io_lsu_load_0_resp_bits_data_delayed),
    .io_lsu_load_0_resp_bits_miss(io_lsu_load_0_resp_bits_miss),
    .io_lsu_load_0_resp_bits_mshr_id(io_lsu_load_0_resp_bits_mshr_id),
    .io_lsu_load_0_resp_bits_meta_prefetch(io_lsu_load_0_resp_bits_meta_prefetch),
    .io_lsu_load_0_resp_bits_handled(io_lsu_load_0_resp_bits_handled),
    .io_lsu_load_0_resp_bits_error_delayed(io_lsu_load_0_resp_bits_error_delayed),
    .io_lsu_load_0_s1_kill(io_lsu_load_0_s1_kill),
    .io_lsu_load_0_s2_kill(io_lsu_load_0_s2_kill),
    .io_lsu_load_0_is128Req(io_lsu_load_0_is128Req),
    .io_lsu_load_0_pf_source(io_lsu_load_0_pf_source),
    .io_lsu_load_0_s1_paddr_dup_lsu(io_lsu_load_0_s1_paddr_dup_lsu),
    .io_lsu_load_0_s1_paddr_dup_dcache(io_lsu_load_0_s1_paddr_dup_dcache),
    .io_lsu_load_0_s2_bank_conflict(io_lsu_load_0_s2_bank_conflict),
    .io_lsu_load_0_s2_mq_nack(io_lsu_load_0_s2_mq_nack),
    .io_lsu_load_1_req_ready(io_lsu_load_1_req_ready),
    .io_lsu_load_1_req_valid(io_lsu_load_1_req_valid),
    .io_lsu_load_1_req_bits_cmd(io_lsu_load_1_req_bits_cmd),
    .io_lsu_load_1_req_bits_vaddr(io_lsu_load_1_req_bits_vaddr),
    .io_lsu_load_1_req_bits_vaddr_dup(io_lsu_load_1_req_bits_vaddr_dup),
    .io_lsu_load_1_req_bits_instrtype(io_lsu_load_1_req_bits_instrtype),
    .io_lsu_load_1_req_bits_isFirstIssue(io_lsu_load_1_req_bits_isFirstIssue),
    .io_lsu_load_1_req_bits_lqIdx_flag(io_lsu_load_1_req_bits_lqIdx_flag),
    .io_lsu_load_1_req_bits_lqIdx_value(io_lsu_load_1_req_bits_lqIdx_value),
    .io_lsu_load_1_resp_valid(io_lsu_load_1_resp_valid),
    .io_lsu_load_1_resp_bits_data(io_lsu_load_1_resp_bits_data),
    .io_lsu_load_1_resp_bits_miss(io_lsu_load_1_resp_bits_miss),
    .io_lsu_load_1_resp_bits_mshr_id(io_lsu_load_1_resp_bits_mshr_id),
    .io_lsu_load_1_resp_bits_meta_prefetch(io_lsu_load_1_resp_bits_meta_prefetch),
    .io_lsu_load_1_resp_bits_handled(io_lsu_load_1_resp_bits_handled),
    .io_lsu_load_1_resp_bits_error_delayed(io_lsu_load_1_resp_bits_error_delayed),
    .io_lsu_load_1_s1_kill(io_lsu_load_1_s1_kill),
    .io_lsu_load_1_s2_kill(io_lsu_load_1_s2_kill),
    .io_lsu_load_1_is128Req(io_lsu_load_1_is128Req),
    .io_lsu_load_1_pf_source(io_lsu_load_1_pf_source),
    .io_lsu_load_1_s1_paddr_dup_lsu(io_lsu_load_1_s1_paddr_dup_lsu),
    .io_lsu_load_1_s1_paddr_dup_dcache(io_lsu_load_1_s1_paddr_dup_dcache),
    .io_lsu_load_1_s2_bank_conflict(io_lsu_load_1_s2_bank_conflict),
    .io_lsu_load_1_s2_mq_nack(io_lsu_load_1_s2_mq_nack),
    .io_lsu_load_2_req_ready(io_lsu_load_2_req_ready),
    .io_lsu_load_2_req_valid(io_lsu_load_2_req_valid),
    .io_lsu_load_2_req_bits_cmd(io_lsu_load_2_req_bits_cmd),
    .io_lsu_load_2_req_bits_vaddr(io_lsu_load_2_req_bits_vaddr),
    .io_lsu_load_2_req_bits_vaddr_dup(io_lsu_load_2_req_bits_vaddr_dup),
    .io_lsu_load_2_req_bits_instrtype(io_lsu_load_2_req_bits_instrtype),
    .io_lsu_load_2_req_bits_isFirstIssue(io_lsu_load_2_req_bits_isFirstIssue),
    .io_lsu_load_2_req_bits_lqIdx_flag(io_lsu_load_2_req_bits_lqIdx_flag),
    .io_lsu_load_2_req_bits_lqIdx_value(io_lsu_load_2_req_bits_lqIdx_value),
    .io_lsu_load_2_resp_valid(io_lsu_load_2_resp_valid),
    .io_lsu_load_2_resp_bits_data(io_lsu_load_2_resp_bits_data),
    .io_lsu_load_2_resp_bits_miss(io_lsu_load_2_resp_bits_miss),
    .io_lsu_load_2_resp_bits_mshr_id(io_lsu_load_2_resp_bits_mshr_id),
    .io_lsu_load_2_resp_bits_meta_prefetch(io_lsu_load_2_resp_bits_meta_prefetch),
    .io_lsu_load_2_resp_bits_handled(io_lsu_load_2_resp_bits_handled),
    .io_lsu_load_2_resp_bits_error_delayed(io_lsu_load_2_resp_bits_error_delayed),
    .io_lsu_load_2_s1_kill(io_lsu_load_2_s1_kill),
    .io_lsu_load_2_s2_kill(io_lsu_load_2_s2_kill),
    .io_lsu_load_2_is128Req(io_lsu_load_2_is128Req),
    .io_lsu_load_2_pf_source(io_lsu_load_2_pf_source),
    .io_lsu_load_2_s1_paddr_dup_lsu(io_lsu_load_2_s1_paddr_dup_lsu),
    .io_lsu_load_2_s1_paddr_dup_dcache(io_lsu_load_2_s1_paddr_dup_dcache),
    .io_lsu_load_2_s2_bank_conflict(io_lsu_load_2_s2_bank_conflict),
    .io_lsu_load_2_s2_mq_nack(io_lsu_load_2_s2_mq_nack),
    .io_lsu_sta_0_req_valid(io_lsu_sta_0_req_valid),
    .io_lsu_sta_1_req_valid(io_lsu_sta_1_req_valid),
    .io_lsu_tl_d_channel_valid(io_lsu_tl_d_channel_valid),
    .io_lsu_tl_d_channel_mshrid(io_lsu_tl_d_channel_mshrid),
    .io_lsu_store_req_ready(io_lsu_store_req_ready),
    .io_lsu_store_req_valid(io_lsu_store_req_valid),
    .io_lsu_store_req_bits_vaddr(io_lsu_store_req_bits_vaddr),
    .io_lsu_store_req_bits_addr(io_lsu_store_req_bits_addr),
    .io_lsu_store_req_bits_data(io_lsu_store_req_bits_data),
    .io_lsu_store_req_bits_mask(io_lsu_store_req_bits_mask),
    .io_lsu_store_req_bits_id(io_lsu_store_req_bits_id),
    .io_lsu_store_main_pipe_hit_resp_valid(io_lsu_store_main_pipe_hit_resp_valid),
    .io_lsu_store_main_pipe_hit_resp_bits_id(io_lsu_store_main_pipe_hit_resp_bits_id),
    .io_lsu_store_replay_resp_valid(io_lsu_store_replay_resp_valid),
    .io_lsu_store_replay_resp_bits_id(io_lsu_store_replay_resp_bits_id),
    .io_lsu_atomics_req_ready(io_lsu_atomics_req_ready),
    .io_lsu_atomics_req_valid(io_lsu_atomics_req_valid),
    .io_lsu_atomics_req_bits_cmd(io_lsu_atomics_req_bits_cmd),
    .io_lsu_atomics_req_bits_vaddr(io_lsu_atomics_req_bits_vaddr),
    .io_lsu_atomics_req_bits_addr(io_lsu_atomics_req_bits_addr),
    .io_lsu_atomics_req_bits_word_idx(io_lsu_atomics_req_bits_word_idx),
    .io_lsu_atomics_req_bits_amo_data(io_lsu_atomics_req_bits_amo_data),
    .io_lsu_atomics_req_bits_amo_mask(io_lsu_atomics_req_bits_amo_mask),
    .io_lsu_atomics_req_bits_amo_cmp(io_lsu_atomics_req_bits_amo_cmp),
    .io_lsu_atomics_resp_valid(io_lsu_atomics_resp_valid),
    .io_lsu_atomics_resp_bits_data(io_lsu_atomics_resp_bits_data),
    .io_lsu_atomics_resp_bits_miss(io_lsu_atomics_resp_bits_miss),
    .io_lsu_atomics_resp_bits_replay(io_lsu_atomics_resp_bits_replay),
    .io_lsu_atomics_resp_bits_error(io_lsu_atomics_resp_bits_error),
    .io_lsu_atomics_resp_bits_id(io_lsu_atomics_resp_bits_id),
    .io_lsu_atomics_block_lr(io_lsu_atomics_block_lr),
    .io_lsu_release_valid(io_lsu_release_valid),
    .io_lsu_release_bits_paddr(io_lsu_release_bits_paddr),
    .io_lsu_forward_D_0_valid(io_lsu_forward_D_0_valid),
    .io_lsu_forward_D_0_data(io_lsu_forward_D_0_data),
    .io_lsu_forward_D_0_mshrid(io_lsu_forward_D_0_mshrid),
    .io_lsu_forward_D_0_last(io_lsu_forward_D_0_last),
    .io_lsu_forward_D_0_corrupt(io_lsu_forward_D_0_corrupt),
    .io_lsu_forward_D_1_valid(io_lsu_forward_D_1_valid),
    .io_lsu_forward_D_1_data(io_lsu_forward_D_1_data),
    .io_lsu_forward_D_1_mshrid(io_lsu_forward_D_1_mshrid),
    .io_lsu_forward_D_1_last(io_lsu_forward_D_1_last),
    .io_lsu_forward_D_1_corrupt(io_lsu_forward_D_1_corrupt),
    .io_lsu_forward_D_2_valid(io_lsu_forward_D_2_valid),
    .io_lsu_forward_D_2_data(io_lsu_forward_D_2_data),
    .io_lsu_forward_D_2_mshrid(io_lsu_forward_D_2_mshrid),
    .io_lsu_forward_D_2_last(io_lsu_forward_D_2_last),
    .io_lsu_forward_D_2_corrupt(io_lsu_forward_D_2_corrupt),
    .io_lsu_forward_mshr_0_valid(io_lsu_forward_mshr_0_valid),
    .io_lsu_forward_mshr_0_mshrid(io_lsu_forward_mshr_0_mshrid),
    .io_lsu_forward_mshr_0_paddr(io_lsu_forward_mshr_0_paddr),
    .io_lsu_forward_mshr_0_forward_mshr(io_lsu_forward_mshr_0_forward_mshr),
    .io_lsu_forward_mshr_0_forwardData_0(io_lsu_forward_mshr_0_forwardData_0),
    .io_lsu_forward_mshr_0_forwardData_1(io_lsu_forward_mshr_0_forwardData_1),
    .io_lsu_forward_mshr_0_forwardData_2(io_lsu_forward_mshr_0_forwardData_2),
    .io_lsu_forward_mshr_0_forwardData_3(io_lsu_forward_mshr_0_forwardData_3),
    .io_lsu_forward_mshr_0_forwardData_4(io_lsu_forward_mshr_0_forwardData_4),
    .io_lsu_forward_mshr_0_forwardData_5(io_lsu_forward_mshr_0_forwardData_5),
    .io_lsu_forward_mshr_0_forwardData_6(io_lsu_forward_mshr_0_forwardData_6),
    .io_lsu_forward_mshr_0_forwardData_7(io_lsu_forward_mshr_0_forwardData_7),
    .io_lsu_forward_mshr_0_forwardData_8(io_lsu_forward_mshr_0_forwardData_8),
    .io_lsu_forward_mshr_0_forwardData_9(io_lsu_forward_mshr_0_forwardData_9),
    .io_lsu_forward_mshr_0_forwardData_10(io_lsu_forward_mshr_0_forwardData_10),
    .io_lsu_forward_mshr_0_forwardData_11(io_lsu_forward_mshr_0_forwardData_11),
    .io_lsu_forward_mshr_0_forwardData_12(io_lsu_forward_mshr_0_forwardData_12),
    .io_lsu_forward_mshr_0_forwardData_13(io_lsu_forward_mshr_0_forwardData_13),
    .io_lsu_forward_mshr_0_forwardData_14(io_lsu_forward_mshr_0_forwardData_14),
    .io_lsu_forward_mshr_0_forwardData_15(io_lsu_forward_mshr_0_forwardData_15),
    .io_lsu_forward_mshr_0_forward_result_valid(io_lsu_forward_mshr_0_forward_result_valid),
    .io_lsu_forward_mshr_0_corrupt(io_lsu_forward_mshr_0_corrupt),
    .io_lsu_forward_mshr_1_valid(io_lsu_forward_mshr_1_valid),
    .io_lsu_forward_mshr_1_mshrid(io_lsu_forward_mshr_1_mshrid),
    .io_lsu_forward_mshr_1_paddr(io_lsu_forward_mshr_1_paddr),
    .io_lsu_forward_mshr_1_forward_mshr(io_lsu_forward_mshr_1_forward_mshr),
    .io_lsu_forward_mshr_1_forwardData_0(io_lsu_forward_mshr_1_forwardData_0),
    .io_lsu_forward_mshr_1_forwardData_1(io_lsu_forward_mshr_1_forwardData_1),
    .io_lsu_forward_mshr_1_forwardData_2(io_lsu_forward_mshr_1_forwardData_2),
    .io_lsu_forward_mshr_1_forwardData_3(io_lsu_forward_mshr_1_forwardData_3),
    .io_lsu_forward_mshr_1_forwardData_4(io_lsu_forward_mshr_1_forwardData_4),
    .io_lsu_forward_mshr_1_forwardData_5(io_lsu_forward_mshr_1_forwardData_5),
    .io_lsu_forward_mshr_1_forwardData_6(io_lsu_forward_mshr_1_forwardData_6),
    .io_lsu_forward_mshr_1_forwardData_7(io_lsu_forward_mshr_1_forwardData_7),
    .io_lsu_forward_mshr_1_forwardData_8(io_lsu_forward_mshr_1_forwardData_8),
    .io_lsu_forward_mshr_1_forwardData_9(io_lsu_forward_mshr_1_forwardData_9),
    .io_lsu_forward_mshr_1_forwardData_10(io_lsu_forward_mshr_1_forwardData_10),
    .io_lsu_forward_mshr_1_forwardData_11(io_lsu_forward_mshr_1_forwardData_11),
    .io_lsu_forward_mshr_1_forwardData_12(io_lsu_forward_mshr_1_forwardData_12),
    .io_lsu_forward_mshr_1_forwardData_13(io_lsu_forward_mshr_1_forwardData_13),
    .io_lsu_forward_mshr_1_forwardData_14(io_lsu_forward_mshr_1_forwardData_14),
    .io_lsu_forward_mshr_1_forwardData_15(io_lsu_forward_mshr_1_forwardData_15),
    .io_lsu_forward_mshr_1_forward_result_valid(io_lsu_forward_mshr_1_forward_result_valid),
    .io_lsu_forward_mshr_1_corrupt(io_lsu_forward_mshr_1_corrupt),
    .io_lsu_forward_mshr_2_valid(io_lsu_forward_mshr_2_valid),
    .io_lsu_forward_mshr_2_mshrid(io_lsu_forward_mshr_2_mshrid),
    .io_lsu_forward_mshr_2_paddr(io_lsu_forward_mshr_2_paddr),
    .io_lsu_forward_mshr_2_forward_mshr(io_lsu_forward_mshr_2_forward_mshr),
    .io_lsu_forward_mshr_2_forwardData_0(io_lsu_forward_mshr_2_forwardData_0),
    .io_lsu_forward_mshr_2_forwardData_1(io_lsu_forward_mshr_2_forwardData_1),
    .io_lsu_forward_mshr_2_forwardData_2(io_lsu_forward_mshr_2_forwardData_2),
    .io_lsu_forward_mshr_2_forwardData_3(io_lsu_forward_mshr_2_forwardData_3),
    .io_lsu_forward_mshr_2_forwardData_4(io_lsu_forward_mshr_2_forwardData_4),
    .io_lsu_forward_mshr_2_forwardData_5(io_lsu_forward_mshr_2_forwardData_5),
    .io_lsu_forward_mshr_2_forwardData_6(io_lsu_forward_mshr_2_forwardData_6),
    .io_lsu_forward_mshr_2_forwardData_7(io_lsu_forward_mshr_2_forwardData_7),
    .io_lsu_forward_mshr_2_forwardData_8(io_lsu_forward_mshr_2_forwardData_8),
    .io_lsu_forward_mshr_2_forwardData_9(io_lsu_forward_mshr_2_forwardData_9),
    .io_lsu_forward_mshr_2_forwardData_10(io_lsu_forward_mshr_2_forwardData_10),
    .io_lsu_forward_mshr_2_forwardData_11(io_lsu_forward_mshr_2_forwardData_11),
    .io_lsu_forward_mshr_2_forwardData_12(io_lsu_forward_mshr_2_forwardData_12),
    .io_lsu_forward_mshr_2_forwardData_13(io_lsu_forward_mshr_2_forwardData_13),
    .io_lsu_forward_mshr_2_forwardData_14(io_lsu_forward_mshr_2_forwardData_14),
    .io_lsu_forward_mshr_2_forwardData_15(io_lsu_forward_mshr_2_forwardData_15),
    .io_lsu_forward_mshr_2_forward_result_valid(io_lsu_forward_mshr_2_forward_result_valid),
    .io_lsu_forward_mshr_2_corrupt(io_lsu_forward_mshr_2_corrupt),
    .io_error_valid(io_error_valid),
    .io_error_bits_paddr(io_error_bits_paddr),
    .io_error_bits_report_to_beu(io_error_bits_report_to_beu),
    .io_lqEmpty(io_lqEmpty),
    .io_pf_ctrl_enable(io_pf_ctrl_enable),
    .io_pf_ctrl_confidence(io_pf_ctrl_confidence),
    .io_sms_agt_evict_req_valid(io_sms_agt_evict_req_valid),
    .io_sms_agt_evict_req_bits_vaddr(io_sms_agt_evict_req_bits_vaddr),
    .io_debugTopDown_robHeadVaddr_valid(io_debugTopDown_robHeadVaddr_valid),
    .io_debugTopDown_robHeadVaddr_bits(io_debugTopDown_robHeadVaddr_bits),
    .io_debugTopDown_robHeadMissInDCache(io_debugTopDown_robHeadMissInDCache),
    .io_l2_hint_valid(io_l2_hint_valid),
    .io_l2_hint_bits_sourceId(io_l2_hint_bits_sourceId),
    .io_cmoOpReq_ready(io_cmoOpReq_ready),
    .io_cmoOpReq_valid(io_cmoOpReq_valid),
    .io_cmoOpReq_bits_opcode(io_cmoOpReq_bits_opcode),
    .io_cmoOpReq_bits_address(io_cmoOpReq_bits_address),
    .io_cmoOpResp_ready(io_cmoOpResp_ready),
    .io_cmoOpResp_valid(io_cmoOpResp_valid),
    .io_cmoOpResp_bits_nderr(io_cmoOpResp_bits_nderr),
    .io_l1Miss(io_l1Miss),
    .io_wfi_wfiReq(io_wfi_wfiReq),
    .io_wfi_wfiSafe(io_wfi_wfiSafe),
    .io_perf_0_value(io_perf_0_value),
    .io_perf_1_value(io_perf_1_value),
    .io_perf_2_value(io_perf_2_value),
    .io_perf_3_value(io_perf_3_value),
    .io_perf_4_value(io_perf_4_value),
    .io_perf_5_value(io_perf_5_value),
    .io_perf_6_value(io_perf_6_value),
    .io_perf_7_value(io_perf_7_value),
    .io_perf_8_value(io_perf_8_value),
    .io_perf_9_value(io_perf_9_value),
    .io_perf_10_value(io_perf_10_value),
    .io_perf_11_value(io_perf_11_value),
    .io_perf_12_value(io_perf_12_value),
    .io_perf_13_value(io_perf_13_value),
    .io_perf_14_value(io_perf_14_value),
    .io_perf_15_value(io_perf_15_value),
    .io_perf_16_value(io_perf_16_value),
    .io_perf_17_value(io_perf_17_value),
    .io_perf_18_value(io_perf_18_value),
    .io_perf_19_value(io_perf_19_value),
    .io_perf_20_value(io_perf_20_value),
    .io_perf_21_value(io_perf_21_value),
    .io_perf_22_value(io_perf_22_value),
    .io_perf_23_value(io_perf_23_value),
    .io_perf_24_value(io_perf_24_value),
    .io_perf_25_value(io_perf_25_value),
    .io_perf_26_value(io_perf_26_value),
    .io_perf_27_value(io_perf_27_value),
    .io_perf_28_value(io_perf_28_value),
    .io_perf_29_value(io_perf_29_value),
    .io_perf_30_value(io_perf_30_value),
    .io_perf_31_value(io_perf_31_value),
    .boreChildrenBd_bore_array(boreChildrenBd_bore_array),
    .boreChildrenBd_bore_all(boreChildrenBd_bore_all),
    .boreChildrenBd_bore_req(boreChildrenBd_bore_req),
    .boreChildrenBd_bore_ack(boreChildrenBd_bore_ack),
    .boreChildrenBd_bore_writeen(boreChildrenBd_bore_writeen),
    .boreChildrenBd_bore_be(boreChildrenBd_bore_be),
    .boreChildrenBd_bore_addr(boreChildrenBd_bore_addr),
    .boreChildrenBd_bore_indata(boreChildrenBd_bore_indata),
    .boreChildrenBd_bore_readen(boreChildrenBd_bore_readen),
    .boreChildrenBd_bore_addr_rd(boreChildrenBd_bore_addr_rd),
    .boreChildrenBd_bore_outdata(boreChildrenBd_bore_outdata),
    .boreChildrenBd_bore_1_array(boreChildrenBd_bore_1_array),
    .boreChildrenBd_bore_1_all(boreChildrenBd_bore_1_all),
    .boreChildrenBd_bore_1_req(boreChildrenBd_bore_1_req),
    .boreChildrenBd_bore_1_ack(boreChildrenBd_bore_1_ack),
    .boreChildrenBd_bore_1_writeen(boreChildrenBd_bore_1_writeen),
    .boreChildrenBd_bore_1_be(boreChildrenBd_bore_1_be),
    .boreChildrenBd_bore_1_addr(boreChildrenBd_bore_1_addr),
    .boreChildrenBd_bore_1_indata(boreChildrenBd_bore_1_indata),
    .boreChildrenBd_bore_1_readen(boreChildrenBd_bore_1_readen),
    .boreChildrenBd_bore_1_addr_rd(boreChildrenBd_bore_1_addr_rd),
    .boreChildrenBd_bore_1_outdata(boreChildrenBd_bore_1_outdata),
    .sigFromSrams_bore_ram_hold(sigFromSrams_bore_ram_hold),
    .sigFromSrams_bore_ram_bypass(sigFromSrams_bore_ram_bypass),
    .sigFromSrams_bore_ram_bp_clken(sigFromSrams_bore_ram_bp_clken),
    .sigFromSrams_bore_ram_aux_clk(sigFromSrams_bore_ram_aux_clk),
    .sigFromSrams_bore_ram_aux_ckbp(sigFromSrams_bore_ram_aux_ckbp),
    .sigFromSrams_bore_ram_mcp_hold(sigFromSrams_bore_ram_mcp_hold),
    .sigFromSrams_bore_cgen(sigFromSrams_bore_cgen),
    .sigFromSrams_bore_1_ram_hold(sigFromSrams_bore_1_ram_hold),
    .sigFromSrams_bore_1_ram_bypass(sigFromSrams_bore_1_ram_bypass),
    .sigFromSrams_bore_1_ram_bp_clken(sigFromSrams_bore_1_ram_bp_clken),
    .sigFromSrams_bore_1_ram_aux_clk(sigFromSrams_bore_1_ram_aux_clk),
    .sigFromSrams_bore_1_ram_aux_ckbp(sigFromSrams_bore_1_ram_aux_ckbp),
    .sigFromSrams_bore_1_ram_mcp_hold(sigFromSrams_bore_1_ram_mcp_hold),
    .sigFromSrams_bore_1_cgen(sigFromSrams_bore_1_cgen),
    .sigFromSrams_bore_2_ram_hold(sigFromSrams_bore_2_ram_hold),
    .sigFromSrams_bore_2_ram_bypass(sigFromSrams_bore_2_ram_bypass),
    .sigFromSrams_bore_2_ram_bp_clken(sigFromSrams_bore_2_ram_bp_clken),
    .sigFromSrams_bore_2_ram_aux_clk(sigFromSrams_bore_2_ram_aux_clk),
    .sigFromSrams_bore_2_ram_aux_ckbp(sigFromSrams_bore_2_ram_aux_ckbp),
    .sigFromSrams_bore_2_ram_mcp_hold(sigFromSrams_bore_2_ram_mcp_hold),
    .sigFromSrams_bore_2_cgen(sigFromSrams_bore_2_cgen),
    .sigFromSrams_bore_3_ram_hold(sigFromSrams_bore_3_ram_hold),
    .sigFromSrams_bore_3_ram_bypass(sigFromSrams_bore_3_ram_bypass),
    .sigFromSrams_bore_3_ram_bp_clken(sigFromSrams_bore_3_ram_bp_clken),
    .sigFromSrams_bore_3_ram_aux_clk(sigFromSrams_bore_3_ram_aux_clk),
    .sigFromSrams_bore_3_ram_aux_ckbp(sigFromSrams_bore_3_ram_aux_ckbp),
    .sigFromSrams_bore_3_ram_mcp_hold(sigFromSrams_bore_3_ram_mcp_hold),
    .sigFromSrams_bore_3_cgen(sigFromSrams_bore_3_cgen),
    .sigFromSrams_bore_4_ram_hold(sigFromSrams_bore_4_ram_hold),
    .sigFromSrams_bore_4_ram_bypass(sigFromSrams_bore_4_ram_bypass),
    .sigFromSrams_bore_4_ram_bp_clken(sigFromSrams_bore_4_ram_bp_clken),
    .sigFromSrams_bore_4_ram_aux_clk(sigFromSrams_bore_4_ram_aux_clk),
    .sigFromSrams_bore_4_ram_aux_ckbp(sigFromSrams_bore_4_ram_aux_ckbp),
    .sigFromSrams_bore_4_ram_mcp_hold(sigFromSrams_bore_4_ram_mcp_hold),
    .sigFromSrams_bore_4_cgen(sigFromSrams_bore_4_cgen),
    .sigFromSrams_bore_5_ram_hold(sigFromSrams_bore_5_ram_hold),
    .sigFromSrams_bore_5_ram_bypass(sigFromSrams_bore_5_ram_bypass),
    .sigFromSrams_bore_5_ram_bp_clken(sigFromSrams_bore_5_ram_bp_clken),
    .sigFromSrams_bore_5_ram_aux_clk(sigFromSrams_bore_5_ram_aux_clk),
    .sigFromSrams_bore_5_ram_aux_ckbp(sigFromSrams_bore_5_ram_aux_ckbp),
    .sigFromSrams_bore_5_ram_mcp_hold(sigFromSrams_bore_5_ram_mcp_hold),
    .sigFromSrams_bore_5_cgen(sigFromSrams_bore_5_cgen),
    .sigFromSrams_bore_6_ram_hold(sigFromSrams_bore_6_ram_hold),
    .sigFromSrams_bore_6_ram_bypass(sigFromSrams_bore_6_ram_bypass),
    .sigFromSrams_bore_6_ram_bp_clken(sigFromSrams_bore_6_ram_bp_clken),
    .sigFromSrams_bore_6_ram_aux_clk(sigFromSrams_bore_6_ram_aux_clk),
    .sigFromSrams_bore_6_ram_aux_ckbp(sigFromSrams_bore_6_ram_aux_ckbp),
    .sigFromSrams_bore_6_ram_mcp_hold(sigFromSrams_bore_6_ram_mcp_hold),
    .sigFromSrams_bore_6_cgen(sigFromSrams_bore_6_cgen),
    .sigFromSrams_bore_7_ram_hold(sigFromSrams_bore_7_ram_hold),
    .sigFromSrams_bore_7_ram_bypass(sigFromSrams_bore_7_ram_bypass),
    .sigFromSrams_bore_7_ram_bp_clken(sigFromSrams_bore_7_ram_bp_clken),
    .sigFromSrams_bore_7_ram_aux_clk(sigFromSrams_bore_7_ram_aux_clk),
    .sigFromSrams_bore_7_ram_aux_ckbp(sigFromSrams_bore_7_ram_aux_ckbp),
    .sigFromSrams_bore_7_ram_mcp_hold(sigFromSrams_bore_7_ram_mcp_hold),
    .sigFromSrams_bore_7_cgen(sigFromSrams_bore_7_cgen),
    .sigFromSrams_bore_8_ram_hold(sigFromSrams_bore_8_ram_hold),
    .sigFromSrams_bore_8_ram_bypass(sigFromSrams_bore_8_ram_bypass),
    .sigFromSrams_bore_8_ram_bp_clken(sigFromSrams_bore_8_ram_bp_clken),
    .sigFromSrams_bore_8_ram_aux_clk(sigFromSrams_bore_8_ram_aux_clk),
    .sigFromSrams_bore_8_ram_aux_ckbp(sigFromSrams_bore_8_ram_aux_ckbp),
    .sigFromSrams_bore_8_ram_mcp_hold(sigFromSrams_bore_8_ram_mcp_hold),
    .sigFromSrams_bore_8_cgen(sigFromSrams_bore_8_cgen),
    .sigFromSrams_bore_9_ram_hold(sigFromSrams_bore_9_ram_hold),
    .sigFromSrams_bore_9_ram_bypass(sigFromSrams_bore_9_ram_bypass),
    .sigFromSrams_bore_9_ram_bp_clken(sigFromSrams_bore_9_ram_bp_clken),
    .sigFromSrams_bore_9_ram_aux_clk(sigFromSrams_bore_9_ram_aux_clk),
    .sigFromSrams_bore_9_ram_aux_ckbp(sigFromSrams_bore_9_ram_aux_ckbp),
    .sigFromSrams_bore_9_ram_mcp_hold(sigFromSrams_bore_9_ram_mcp_hold),
    .sigFromSrams_bore_9_cgen(sigFromSrams_bore_9_cgen),
    .sigFromSrams_bore_10_ram_hold(sigFromSrams_bore_10_ram_hold),
    .sigFromSrams_bore_10_ram_bypass(sigFromSrams_bore_10_ram_bypass),
    .sigFromSrams_bore_10_ram_bp_clken(sigFromSrams_bore_10_ram_bp_clken),
    .sigFromSrams_bore_10_ram_aux_clk(sigFromSrams_bore_10_ram_aux_clk),
    .sigFromSrams_bore_10_ram_aux_ckbp(sigFromSrams_bore_10_ram_aux_ckbp),
    .sigFromSrams_bore_10_ram_mcp_hold(sigFromSrams_bore_10_ram_mcp_hold),
    .sigFromSrams_bore_10_cgen(sigFromSrams_bore_10_cgen),
    .sigFromSrams_bore_11_ram_hold(sigFromSrams_bore_11_ram_hold),
    .sigFromSrams_bore_11_ram_bypass(sigFromSrams_bore_11_ram_bypass),
    .sigFromSrams_bore_11_ram_bp_clken(sigFromSrams_bore_11_ram_bp_clken),
    .sigFromSrams_bore_11_ram_aux_clk(sigFromSrams_bore_11_ram_aux_clk),
    .sigFromSrams_bore_11_ram_aux_ckbp(sigFromSrams_bore_11_ram_aux_ckbp),
    .sigFromSrams_bore_11_ram_mcp_hold(sigFromSrams_bore_11_ram_mcp_hold),
    .sigFromSrams_bore_11_cgen(sigFromSrams_bore_11_cgen),
    .sigFromSrams_bore_12_ram_hold(sigFromSrams_bore_12_ram_hold),
    .sigFromSrams_bore_12_ram_bypass(sigFromSrams_bore_12_ram_bypass),
    .sigFromSrams_bore_12_ram_bp_clken(sigFromSrams_bore_12_ram_bp_clken),
    .sigFromSrams_bore_12_ram_aux_clk(sigFromSrams_bore_12_ram_aux_clk),
    .sigFromSrams_bore_12_ram_aux_ckbp(sigFromSrams_bore_12_ram_aux_ckbp),
    .sigFromSrams_bore_12_ram_mcp_hold(sigFromSrams_bore_12_ram_mcp_hold),
    .sigFromSrams_bore_12_cgen(sigFromSrams_bore_12_cgen),
    .sigFromSrams_bore_13_ram_hold(sigFromSrams_bore_13_ram_hold),
    .sigFromSrams_bore_13_ram_bypass(sigFromSrams_bore_13_ram_bypass),
    .sigFromSrams_bore_13_ram_bp_clken(sigFromSrams_bore_13_ram_bp_clken),
    .sigFromSrams_bore_13_ram_aux_clk(sigFromSrams_bore_13_ram_aux_clk),
    .sigFromSrams_bore_13_ram_aux_ckbp(sigFromSrams_bore_13_ram_aux_ckbp),
    .sigFromSrams_bore_13_ram_mcp_hold(sigFromSrams_bore_13_ram_mcp_hold),
    .sigFromSrams_bore_13_cgen(sigFromSrams_bore_13_cgen),
    .sigFromSrams_bore_14_ram_hold(sigFromSrams_bore_14_ram_hold),
    .sigFromSrams_bore_14_ram_bypass(sigFromSrams_bore_14_ram_bypass),
    .sigFromSrams_bore_14_ram_bp_clken(sigFromSrams_bore_14_ram_bp_clken),
    .sigFromSrams_bore_14_ram_aux_clk(sigFromSrams_bore_14_ram_aux_clk),
    .sigFromSrams_bore_14_ram_aux_ckbp(sigFromSrams_bore_14_ram_aux_ckbp),
    .sigFromSrams_bore_14_ram_mcp_hold(sigFromSrams_bore_14_ram_mcp_hold),
    .sigFromSrams_bore_14_cgen(sigFromSrams_bore_14_cgen),
    .sigFromSrams_bore_15_ram_hold(sigFromSrams_bore_15_ram_hold),
    .sigFromSrams_bore_15_ram_bypass(sigFromSrams_bore_15_ram_bypass),
    .sigFromSrams_bore_15_ram_bp_clken(sigFromSrams_bore_15_ram_bp_clken),
    .sigFromSrams_bore_15_ram_aux_clk(sigFromSrams_bore_15_ram_aux_clk),
    .sigFromSrams_bore_15_ram_aux_ckbp(sigFromSrams_bore_15_ram_aux_ckbp),
    .sigFromSrams_bore_15_ram_mcp_hold(sigFromSrams_bore_15_ram_mcp_hold),
    .sigFromSrams_bore_15_cgen(sigFromSrams_bore_15_cgen),
    .sigFromSrams_bore_16_ram_hold(sigFromSrams_bore_16_ram_hold),
    .sigFromSrams_bore_16_ram_bypass(sigFromSrams_bore_16_ram_bypass),
    .sigFromSrams_bore_16_ram_bp_clken(sigFromSrams_bore_16_ram_bp_clken),
    .sigFromSrams_bore_16_ram_aux_clk(sigFromSrams_bore_16_ram_aux_clk),
    .sigFromSrams_bore_16_ram_aux_ckbp(sigFromSrams_bore_16_ram_aux_ckbp),
    .sigFromSrams_bore_16_ram_mcp_hold(sigFromSrams_bore_16_ram_mcp_hold),
    .sigFromSrams_bore_16_cgen(sigFromSrams_bore_16_cgen),
    .sigFromSrams_bore_17_ram_hold(sigFromSrams_bore_17_ram_hold),
    .sigFromSrams_bore_17_ram_bypass(sigFromSrams_bore_17_ram_bypass),
    .sigFromSrams_bore_17_ram_bp_clken(sigFromSrams_bore_17_ram_bp_clken),
    .sigFromSrams_bore_17_ram_aux_clk(sigFromSrams_bore_17_ram_aux_clk),
    .sigFromSrams_bore_17_ram_aux_ckbp(sigFromSrams_bore_17_ram_aux_ckbp),
    .sigFromSrams_bore_17_ram_mcp_hold(sigFromSrams_bore_17_ram_mcp_hold),
    .sigFromSrams_bore_17_cgen(sigFromSrams_bore_17_cgen),
    .sigFromSrams_bore_18_ram_hold(sigFromSrams_bore_18_ram_hold),
    .sigFromSrams_bore_18_ram_bypass(sigFromSrams_bore_18_ram_bypass),
    .sigFromSrams_bore_18_ram_bp_clken(sigFromSrams_bore_18_ram_bp_clken),
    .sigFromSrams_bore_18_ram_aux_clk(sigFromSrams_bore_18_ram_aux_clk),
    .sigFromSrams_bore_18_ram_aux_ckbp(sigFromSrams_bore_18_ram_aux_ckbp),
    .sigFromSrams_bore_18_ram_mcp_hold(sigFromSrams_bore_18_ram_mcp_hold),
    .sigFromSrams_bore_18_cgen(sigFromSrams_bore_18_cgen),
    .sigFromSrams_bore_19_ram_hold(sigFromSrams_bore_19_ram_hold),
    .sigFromSrams_bore_19_ram_bypass(sigFromSrams_bore_19_ram_bypass),
    .sigFromSrams_bore_19_ram_bp_clken(sigFromSrams_bore_19_ram_bp_clken),
    .sigFromSrams_bore_19_ram_aux_clk(sigFromSrams_bore_19_ram_aux_clk),
    .sigFromSrams_bore_19_ram_aux_ckbp(sigFromSrams_bore_19_ram_aux_ckbp),
    .sigFromSrams_bore_19_ram_mcp_hold(sigFromSrams_bore_19_ram_mcp_hold),
    .sigFromSrams_bore_19_cgen(sigFromSrams_bore_19_cgen),
    .sigFromSrams_bore_20_ram_hold(sigFromSrams_bore_20_ram_hold),
    .sigFromSrams_bore_20_ram_bypass(sigFromSrams_bore_20_ram_bypass),
    .sigFromSrams_bore_20_ram_bp_clken(sigFromSrams_bore_20_ram_bp_clken),
    .sigFromSrams_bore_20_ram_aux_clk(sigFromSrams_bore_20_ram_aux_clk),
    .sigFromSrams_bore_20_ram_aux_ckbp(sigFromSrams_bore_20_ram_aux_ckbp),
    .sigFromSrams_bore_20_ram_mcp_hold(sigFromSrams_bore_20_ram_mcp_hold),
    .sigFromSrams_bore_20_cgen(sigFromSrams_bore_20_cgen),
    .sigFromSrams_bore_21_ram_hold(sigFromSrams_bore_21_ram_hold),
    .sigFromSrams_bore_21_ram_bypass(sigFromSrams_bore_21_ram_bypass),
    .sigFromSrams_bore_21_ram_bp_clken(sigFromSrams_bore_21_ram_bp_clken),
    .sigFromSrams_bore_21_ram_aux_clk(sigFromSrams_bore_21_ram_aux_clk),
    .sigFromSrams_bore_21_ram_aux_ckbp(sigFromSrams_bore_21_ram_aux_ckbp),
    .sigFromSrams_bore_21_ram_mcp_hold(sigFromSrams_bore_21_ram_mcp_hold),
    .sigFromSrams_bore_21_cgen(sigFromSrams_bore_21_cgen),
    .sigFromSrams_bore_22_ram_hold(sigFromSrams_bore_22_ram_hold),
    .sigFromSrams_bore_22_ram_bypass(sigFromSrams_bore_22_ram_bypass),
    .sigFromSrams_bore_22_ram_bp_clken(sigFromSrams_bore_22_ram_bp_clken),
    .sigFromSrams_bore_22_ram_aux_clk(sigFromSrams_bore_22_ram_aux_clk),
    .sigFromSrams_bore_22_ram_aux_ckbp(sigFromSrams_bore_22_ram_aux_ckbp),
    .sigFromSrams_bore_22_ram_mcp_hold(sigFromSrams_bore_22_ram_mcp_hold),
    .sigFromSrams_bore_22_cgen(sigFromSrams_bore_22_cgen),
    .sigFromSrams_bore_23_ram_hold(sigFromSrams_bore_23_ram_hold),
    .sigFromSrams_bore_23_ram_bypass(sigFromSrams_bore_23_ram_bypass),
    .sigFromSrams_bore_23_ram_bp_clken(sigFromSrams_bore_23_ram_bp_clken),
    .sigFromSrams_bore_23_ram_aux_clk(sigFromSrams_bore_23_ram_aux_clk),
    .sigFromSrams_bore_23_ram_aux_ckbp(sigFromSrams_bore_23_ram_aux_ckbp),
    .sigFromSrams_bore_23_ram_mcp_hold(sigFromSrams_bore_23_ram_mcp_hold),
    .sigFromSrams_bore_23_cgen(sigFromSrams_bore_23_cgen),
    .sigFromSrams_bore_24_ram_hold(sigFromSrams_bore_24_ram_hold),
    .sigFromSrams_bore_24_ram_bypass(sigFromSrams_bore_24_ram_bypass),
    .sigFromSrams_bore_24_ram_bp_clken(sigFromSrams_bore_24_ram_bp_clken),
    .sigFromSrams_bore_24_ram_aux_clk(sigFromSrams_bore_24_ram_aux_clk),
    .sigFromSrams_bore_24_ram_aux_ckbp(sigFromSrams_bore_24_ram_aux_ckbp),
    .sigFromSrams_bore_24_ram_mcp_hold(sigFromSrams_bore_24_ram_mcp_hold),
    .sigFromSrams_bore_24_cgen(sigFromSrams_bore_24_cgen),
    .sigFromSrams_bore_25_ram_hold(sigFromSrams_bore_25_ram_hold),
    .sigFromSrams_bore_25_ram_bypass(sigFromSrams_bore_25_ram_bypass),
    .sigFromSrams_bore_25_ram_bp_clken(sigFromSrams_bore_25_ram_bp_clken),
    .sigFromSrams_bore_25_ram_aux_clk(sigFromSrams_bore_25_ram_aux_clk),
    .sigFromSrams_bore_25_ram_aux_ckbp(sigFromSrams_bore_25_ram_aux_ckbp),
    .sigFromSrams_bore_25_ram_mcp_hold(sigFromSrams_bore_25_ram_mcp_hold),
    .sigFromSrams_bore_25_cgen(sigFromSrams_bore_25_cgen),
    .sigFromSrams_bore_26_ram_hold(sigFromSrams_bore_26_ram_hold),
    .sigFromSrams_bore_26_ram_bypass(sigFromSrams_bore_26_ram_bypass),
    .sigFromSrams_bore_26_ram_bp_clken(sigFromSrams_bore_26_ram_bp_clken),
    .sigFromSrams_bore_26_ram_aux_clk(sigFromSrams_bore_26_ram_aux_clk),
    .sigFromSrams_bore_26_ram_aux_ckbp(sigFromSrams_bore_26_ram_aux_ckbp),
    .sigFromSrams_bore_26_ram_mcp_hold(sigFromSrams_bore_26_ram_mcp_hold),
    .sigFromSrams_bore_26_cgen(sigFromSrams_bore_26_cgen),
    .sigFromSrams_bore_27_ram_hold(sigFromSrams_bore_27_ram_hold),
    .sigFromSrams_bore_27_ram_bypass(sigFromSrams_bore_27_ram_bypass),
    .sigFromSrams_bore_27_ram_bp_clken(sigFromSrams_bore_27_ram_bp_clken),
    .sigFromSrams_bore_27_ram_aux_clk(sigFromSrams_bore_27_ram_aux_clk),
    .sigFromSrams_bore_27_ram_aux_ckbp(sigFromSrams_bore_27_ram_aux_ckbp),
    .sigFromSrams_bore_27_ram_mcp_hold(sigFromSrams_bore_27_ram_mcp_hold),
    .sigFromSrams_bore_27_cgen(sigFromSrams_bore_27_cgen),
    .sigFromSrams_bore_28_ram_hold(sigFromSrams_bore_28_ram_hold),
    .sigFromSrams_bore_28_ram_bypass(sigFromSrams_bore_28_ram_bypass),
    .sigFromSrams_bore_28_ram_bp_clken(sigFromSrams_bore_28_ram_bp_clken),
    .sigFromSrams_bore_28_ram_aux_clk(sigFromSrams_bore_28_ram_aux_clk),
    .sigFromSrams_bore_28_ram_aux_ckbp(sigFromSrams_bore_28_ram_aux_ckbp),
    .sigFromSrams_bore_28_ram_mcp_hold(sigFromSrams_bore_28_ram_mcp_hold),
    .sigFromSrams_bore_28_cgen(sigFromSrams_bore_28_cgen),
    .sigFromSrams_bore_29_ram_hold(sigFromSrams_bore_29_ram_hold),
    .sigFromSrams_bore_29_ram_bypass(sigFromSrams_bore_29_ram_bypass),
    .sigFromSrams_bore_29_ram_bp_clken(sigFromSrams_bore_29_ram_bp_clken),
    .sigFromSrams_bore_29_ram_aux_clk(sigFromSrams_bore_29_ram_aux_clk),
    .sigFromSrams_bore_29_ram_aux_ckbp(sigFromSrams_bore_29_ram_aux_ckbp),
    .sigFromSrams_bore_29_ram_mcp_hold(sigFromSrams_bore_29_ram_mcp_hold),
    .sigFromSrams_bore_29_cgen(sigFromSrams_bore_29_cgen),
    .sigFromSrams_bore_30_ram_hold(sigFromSrams_bore_30_ram_hold),
    .sigFromSrams_bore_30_ram_bypass(sigFromSrams_bore_30_ram_bypass),
    .sigFromSrams_bore_30_ram_bp_clken(sigFromSrams_bore_30_ram_bp_clken),
    .sigFromSrams_bore_30_ram_aux_clk(sigFromSrams_bore_30_ram_aux_clk),
    .sigFromSrams_bore_30_ram_aux_ckbp(sigFromSrams_bore_30_ram_aux_ckbp),
    .sigFromSrams_bore_30_ram_mcp_hold(sigFromSrams_bore_30_ram_mcp_hold),
    .sigFromSrams_bore_30_cgen(sigFromSrams_bore_30_cgen),
    .sigFromSrams_bore_31_ram_hold(sigFromSrams_bore_31_ram_hold),
    .sigFromSrams_bore_31_ram_bypass(sigFromSrams_bore_31_ram_bypass),
    .sigFromSrams_bore_31_ram_bp_clken(sigFromSrams_bore_31_ram_bp_clken),
    .sigFromSrams_bore_31_ram_aux_clk(sigFromSrams_bore_31_ram_aux_clk),
    .sigFromSrams_bore_31_ram_aux_ckbp(sigFromSrams_bore_31_ram_aux_ckbp),
    .sigFromSrams_bore_31_ram_mcp_hold(sigFromSrams_bore_31_ram_mcp_hold),
    .sigFromSrams_bore_31_cgen(sigFromSrams_bore_31_cgen),
    .sigFromSrams_bore_32_ram_hold(sigFromSrams_bore_32_ram_hold),
    .sigFromSrams_bore_32_ram_bypass(sigFromSrams_bore_32_ram_bypass),
    .sigFromSrams_bore_32_ram_bp_clken(sigFromSrams_bore_32_ram_bp_clken),
    .sigFromSrams_bore_32_ram_aux_clk(sigFromSrams_bore_32_ram_aux_clk),
    .sigFromSrams_bore_32_ram_aux_ckbp(sigFromSrams_bore_32_ram_aux_ckbp),
    .sigFromSrams_bore_32_ram_mcp_hold(sigFromSrams_bore_32_ram_mcp_hold),
    .sigFromSrams_bore_32_cgen(sigFromSrams_bore_32_cgen),
    .sigFromSrams_bore_33_ram_hold(sigFromSrams_bore_33_ram_hold),
    .sigFromSrams_bore_33_ram_bypass(sigFromSrams_bore_33_ram_bypass),
    .sigFromSrams_bore_33_ram_bp_clken(sigFromSrams_bore_33_ram_bp_clken),
    .sigFromSrams_bore_33_ram_aux_clk(sigFromSrams_bore_33_ram_aux_clk),
    .sigFromSrams_bore_33_ram_aux_ckbp(sigFromSrams_bore_33_ram_aux_ckbp),
    .sigFromSrams_bore_33_ram_mcp_hold(sigFromSrams_bore_33_ram_mcp_hold),
    .sigFromSrams_bore_33_cgen(sigFromSrams_bore_33_cgen),
    .sigFromSrams_bore_34_ram_hold(sigFromSrams_bore_34_ram_hold),
    .sigFromSrams_bore_34_ram_bypass(sigFromSrams_bore_34_ram_bypass),
    .sigFromSrams_bore_34_ram_bp_clken(sigFromSrams_bore_34_ram_bp_clken),
    .sigFromSrams_bore_34_ram_aux_clk(sigFromSrams_bore_34_ram_aux_clk),
    .sigFromSrams_bore_34_ram_aux_ckbp(sigFromSrams_bore_34_ram_aux_ckbp),
    .sigFromSrams_bore_34_ram_mcp_hold(sigFromSrams_bore_34_ram_mcp_hold),
    .sigFromSrams_bore_34_cgen(sigFromSrams_bore_34_cgen),
    .sigFromSrams_bore_35_ram_hold(sigFromSrams_bore_35_ram_hold),
    .sigFromSrams_bore_35_ram_bypass(sigFromSrams_bore_35_ram_bypass),
    .sigFromSrams_bore_35_ram_bp_clken(sigFromSrams_bore_35_ram_bp_clken),
    .sigFromSrams_bore_35_ram_aux_clk(sigFromSrams_bore_35_ram_aux_clk),
    .sigFromSrams_bore_35_ram_aux_ckbp(sigFromSrams_bore_35_ram_aux_ckbp),
    .sigFromSrams_bore_35_ram_mcp_hold(sigFromSrams_bore_35_ram_mcp_hold),
    .sigFromSrams_bore_35_cgen(sigFromSrams_bore_35_cgen),
    .sigFromSrams_bore_36_ram_hold(sigFromSrams_bore_36_ram_hold),
    .sigFromSrams_bore_36_ram_bypass(sigFromSrams_bore_36_ram_bypass),
    .sigFromSrams_bore_36_ram_bp_clken(sigFromSrams_bore_36_ram_bp_clken),
    .sigFromSrams_bore_36_ram_aux_clk(sigFromSrams_bore_36_ram_aux_clk),
    .sigFromSrams_bore_36_ram_aux_ckbp(sigFromSrams_bore_36_ram_aux_ckbp),
    .sigFromSrams_bore_36_ram_mcp_hold(sigFromSrams_bore_36_ram_mcp_hold),
    .sigFromSrams_bore_36_cgen(sigFromSrams_bore_36_cgen),
    .sigFromSrams_bore_37_ram_hold(sigFromSrams_bore_37_ram_hold),
    .sigFromSrams_bore_37_ram_bypass(sigFromSrams_bore_37_ram_bypass),
    .sigFromSrams_bore_37_ram_bp_clken(sigFromSrams_bore_37_ram_bp_clken),
    .sigFromSrams_bore_37_ram_aux_clk(sigFromSrams_bore_37_ram_aux_clk),
    .sigFromSrams_bore_37_ram_aux_ckbp(sigFromSrams_bore_37_ram_aux_ckbp),
    .sigFromSrams_bore_37_ram_mcp_hold(sigFromSrams_bore_37_ram_mcp_hold),
    .sigFromSrams_bore_37_cgen(sigFromSrams_bore_37_cgen),
    .sigFromSrams_bore_38_ram_hold(sigFromSrams_bore_38_ram_hold),
    .sigFromSrams_bore_38_ram_bypass(sigFromSrams_bore_38_ram_bypass),
    .sigFromSrams_bore_38_ram_bp_clken(sigFromSrams_bore_38_ram_bp_clken),
    .sigFromSrams_bore_38_ram_aux_clk(sigFromSrams_bore_38_ram_aux_clk),
    .sigFromSrams_bore_38_ram_aux_ckbp(sigFromSrams_bore_38_ram_aux_ckbp),
    .sigFromSrams_bore_38_ram_mcp_hold(sigFromSrams_bore_38_ram_mcp_hold),
    .sigFromSrams_bore_38_cgen(sigFromSrams_bore_38_cgen),
    .sigFromSrams_bore_39_ram_hold(sigFromSrams_bore_39_ram_hold),
    .sigFromSrams_bore_39_ram_bypass(sigFromSrams_bore_39_ram_bypass),
    .sigFromSrams_bore_39_ram_bp_clken(sigFromSrams_bore_39_ram_bp_clken),
    .sigFromSrams_bore_39_ram_aux_clk(sigFromSrams_bore_39_ram_aux_clk),
    .sigFromSrams_bore_39_ram_aux_ckbp(sigFromSrams_bore_39_ram_aux_ckbp),
    .sigFromSrams_bore_39_ram_mcp_hold(sigFromSrams_bore_39_ram_mcp_hold),
    .sigFromSrams_bore_39_cgen(sigFromSrams_bore_39_cgen)
  );
endmodule
