// 自动生成：scripts/gen_axi4xbar.py —— 勿手改
module AXI4Xbar_xs(
  input clock,
  input reset,
  output auto_in_1_aw_ready,
  input auto_in_1_aw_valid,
  input [4:0] auto_in_1_aw_bits_id,
  input [48:0] auto_in_1_aw_bits_addr,
  input [7:0] auto_in_1_aw_bits_len,
  input [2:0] auto_in_1_aw_bits_size,
  input [1:0] auto_in_1_aw_bits_burst,
  input [3:0] auto_in_1_aw_bits_cache,
  input [3:0] auto_in_1_aw_bits_qos,
  output auto_in_1_w_ready,
  input auto_in_1_w_valid,
  input [255:0] auto_in_1_w_bits_data,
  input [31:0] auto_in_1_w_bits_strb,
  input auto_in_1_w_bits_last,
  output auto_in_1_b_valid,
  output [4:0] auto_in_1_b_bits_id,
  output auto_in_1_ar_ready,
  input auto_in_1_ar_valid,
  input [4:0] auto_in_1_ar_bits_id,
  input [48:0] auto_in_1_ar_bits_addr,
  input [7:0] auto_in_1_ar_bits_len,
  input [2:0] auto_in_1_ar_bits_size,
  input [1:0] auto_in_1_ar_bits_burst,
  input [3:0] auto_in_1_ar_bits_cache,
  input [3:0] auto_in_1_ar_bits_qos,
  output auto_in_1_r_valid,
  output [4:0] auto_in_1_r_bits_id,
  output [255:0] auto_in_1_r_bits_data,
  output auto_in_1_r_bits_last,
  output auto_in_0_aw_ready,
  input auto_in_0_aw_valid,
  input [5:0] auto_in_0_aw_bits_id,
  input [48:0] auto_in_0_aw_bits_addr,
  input [7:0] auto_in_0_aw_bits_len,
  input [2:0] auto_in_0_aw_bits_size,
  input [1:0] auto_in_0_aw_bits_burst,
  input [3:0] auto_in_0_aw_bits_qos,
  output auto_in_0_w_ready,
  input auto_in_0_w_valid,
  input [255:0] auto_in_0_w_bits_data,
  input [31:0] auto_in_0_w_bits_strb,
  input auto_in_0_w_bits_last,
  output auto_in_0_b_valid,
  output [5:0] auto_in_0_b_bits_id,
  output auto_in_0_ar_ready,
  input auto_in_0_ar_valid,
  input [5:0] auto_in_0_ar_bits_id,
  input [48:0] auto_in_0_ar_bits_addr,
  input [7:0] auto_in_0_ar_bits_len,
  input [2:0] auto_in_0_ar_bits_size,
  input [1:0] auto_in_0_ar_bits_burst,
  input [3:0] auto_in_0_ar_bits_qos,
  output auto_in_0_r_valid,
  output [5:0] auto_in_0_r_bits_id,
  output [255:0] auto_in_0_r_bits_data,
  output auto_in_0_r_bits_last,
  input auto_out_1_aw_ready,
  output auto_out_1_aw_valid,
  output [6:0] auto_out_1_aw_bits_id,
  output [48:0] auto_out_1_aw_bits_addr,
  output [7:0] auto_out_1_aw_bits_len,
  output [2:0] auto_out_1_aw_bits_size,
  output [3:0] auto_out_1_aw_bits_cache,
  output [2:0] auto_out_1_aw_bits_prot,
  input auto_out_1_w_ready,
  output auto_out_1_w_valid,
  output [255:0] auto_out_1_w_bits_data,
  output [31:0] auto_out_1_w_bits_strb,
  output auto_out_1_w_bits_last,
  output auto_out_1_b_ready,
  input auto_out_1_b_valid,
  input [6:0] auto_out_1_b_bits_id,
  input auto_out_1_ar_ready,
  output auto_out_1_ar_valid,
  output [6:0] auto_out_1_ar_bits_id,
  output [48:0] auto_out_1_ar_bits_addr,
  output [7:0] auto_out_1_ar_bits_len,
  output [2:0] auto_out_1_ar_bits_size,
  output [3:0] auto_out_1_ar_bits_cache,
  output [2:0] auto_out_1_ar_bits_prot,
  output auto_out_1_r_ready,
  input auto_out_1_r_valid,
  input [6:0] auto_out_1_r_bits_id,
  input [255:0] auto_out_1_r_bits_data,
  input auto_out_1_r_bits_last,
  input auto_out_0_aw_ready,
  output auto_out_0_aw_valid,
  output [6:0] auto_out_0_aw_bits_id,
  output [47:0] auto_out_0_aw_bits_addr,
  output [7:0] auto_out_0_aw_bits_len,
  output [2:0] auto_out_0_aw_bits_size,
  output [1:0] auto_out_0_aw_bits_burst,
  output [3:0] auto_out_0_aw_bits_cache,
  output [2:0] auto_out_0_aw_bits_prot,
  output [3:0] auto_out_0_aw_bits_qos,
  input auto_out_0_w_ready,
  output auto_out_0_w_valid,
  output [255:0] auto_out_0_w_bits_data,
  output [31:0] auto_out_0_w_bits_strb,
  output auto_out_0_w_bits_last,
  output auto_out_0_b_ready,
  input auto_out_0_b_valid,
  input [6:0] auto_out_0_b_bits_id,
  input auto_out_0_ar_ready,
  output auto_out_0_ar_valid,
  output [6:0] auto_out_0_ar_bits_id,
  output [47:0] auto_out_0_ar_bits_addr,
  output [7:0] auto_out_0_ar_bits_len,
  output [2:0] auto_out_0_ar_bits_size,
  output [1:0] auto_out_0_ar_bits_burst,
  output [3:0] auto_out_0_ar_bits_cache,
  output [2:0] auto_out_0_ar_bits_prot,
  output [3:0] auto_out_0_ar_bits_qos,
  output auto_out_0_r_ready,
  input auto_out_0_r_valid,
  input [6:0] auto_out_0_r_bits_id,
  input [255:0] auto_out_0_r_bits_data,
  input auto_out_0_r_bits_last
);
  xs_AXI4Xbar_core u_core (
    .clock(clock),
    .reset(reset),
    .auto_in_1_aw_ready(auto_in_1_aw_ready),
    .auto_in_1_aw_valid(auto_in_1_aw_valid),
    .auto_in_1_aw_bits_id(auto_in_1_aw_bits_id),
    .auto_in_1_aw_bits_addr(auto_in_1_aw_bits_addr),
    .auto_in_1_aw_bits_len(auto_in_1_aw_bits_len),
    .auto_in_1_aw_bits_size(auto_in_1_aw_bits_size),
    .auto_in_1_aw_bits_burst(auto_in_1_aw_bits_burst),
    .auto_in_1_aw_bits_cache(auto_in_1_aw_bits_cache),
    .auto_in_1_aw_bits_qos(auto_in_1_aw_bits_qos),
    .auto_in_1_w_ready(auto_in_1_w_ready),
    .auto_in_1_w_valid(auto_in_1_w_valid),
    .auto_in_1_w_bits_data(auto_in_1_w_bits_data),
    .auto_in_1_w_bits_strb(auto_in_1_w_bits_strb),
    .auto_in_1_w_bits_last(auto_in_1_w_bits_last),
    .auto_in_1_b_valid(auto_in_1_b_valid),
    .auto_in_1_b_bits_id(auto_in_1_b_bits_id),
    .auto_in_1_ar_ready(auto_in_1_ar_ready),
    .auto_in_1_ar_valid(auto_in_1_ar_valid),
    .auto_in_1_ar_bits_id(auto_in_1_ar_bits_id),
    .auto_in_1_ar_bits_addr(auto_in_1_ar_bits_addr),
    .auto_in_1_ar_bits_len(auto_in_1_ar_bits_len),
    .auto_in_1_ar_bits_size(auto_in_1_ar_bits_size),
    .auto_in_1_ar_bits_burst(auto_in_1_ar_bits_burst),
    .auto_in_1_ar_bits_cache(auto_in_1_ar_bits_cache),
    .auto_in_1_ar_bits_qos(auto_in_1_ar_bits_qos),
    .auto_in_1_r_valid(auto_in_1_r_valid),
    .auto_in_1_r_bits_id(auto_in_1_r_bits_id),
    .auto_in_1_r_bits_data(auto_in_1_r_bits_data),
    .auto_in_1_r_bits_last(auto_in_1_r_bits_last),
    .auto_in_0_aw_ready(auto_in_0_aw_ready),
    .auto_in_0_aw_valid(auto_in_0_aw_valid),
    .auto_in_0_aw_bits_id(auto_in_0_aw_bits_id),
    .auto_in_0_aw_bits_addr(auto_in_0_aw_bits_addr),
    .auto_in_0_aw_bits_len(auto_in_0_aw_bits_len),
    .auto_in_0_aw_bits_size(auto_in_0_aw_bits_size),
    .auto_in_0_aw_bits_burst(auto_in_0_aw_bits_burst),
    .auto_in_0_aw_bits_qos(auto_in_0_aw_bits_qos),
    .auto_in_0_w_ready(auto_in_0_w_ready),
    .auto_in_0_w_valid(auto_in_0_w_valid),
    .auto_in_0_w_bits_data(auto_in_0_w_bits_data),
    .auto_in_0_w_bits_strb(auto_in_0_w_bits_strb),
    .auto_in_0_w_bits_last(auto_in_0_w_bits_last),
    .auto_in_0_b_valid(auto_in_0_b_valid),
    .auto_in_0_b_bits_id(auto_in_0_b_bits_id),
    .auto_in_0_ar_ready(auto_in_0_ar_ready),
    .auto_in_0_ar_valid(auto_in_0_ar_valid),
    .auto_in_0_ar_bits_id(auto_in_0_ar_bits_id),
    .auto_in_0_ar_bits_addr(auto_in_0_ar_bits_addr),
    .auto_in_0_ar_bits_len(auto_in_0_ar_bits_len),
    .auto_in_0_ar_bits_size(auto_in_0_ar_bits_size),
    .auto_in_0_ar_bits_burst(auto_in_0_ar_bits_burst),
    .auto_in_0_ar_bits_qos(auto_in_0_ar_bits_qos),
    .auto_in_0_r_valid(auto_in_0_r_valid),
    .auto_in_0_r_bits_id(auto_in_0_r_bits_id),
    .auto_in_0_r_bits_data(auto_in_0_r_bits_data),
    .auto_in_0_r_bits_last(auto_in_0_r_bits_last),
    .auto_out_1_aw_ready(auto_out_1_aw_ready),
    .auto_out_1_aw_valid(auto_out_1_aw_valid),
    .auto_out_1_aw_bits_id(auto_out_1_aw_bits_id),
    .auto_out_1_aw_bits_addr(auto_out_1_aw_bits_addr),
    .auto_out_1_aw_bits_len(auto_out_1_aw_bits_len),
    .auto_out_1_aw_bits_size(auto_out_1_aw_bits_size),
    .auto_out_1_aw_bits_cache(auto_out_1_aw_bits_cache),
    .auto_out_1_aw_bits_prot(auto_out_1_aw_bits_prot),
    .auto_out_1_w_ready(auto_out_1_w_ready),
    .auto_out_1_w_valid(auto_out_1_w_valid),
    .auto_out_1_w_bits_data(auto_out_1_w_bits_data),
    .auto_out_1_w_bits_strb(auto_out_1_w_bits_strb),
    .auto_out_1_w_bits_last(auto_out_1_w_bits_last),
    .auto_out_1_b_ready(auto_out_1_b_ready),
    .auto_out_1_b_valid(auto_out_1_b_valid),
    .auto_out_1_b_bits_id(auto_out_1_b_bits_id),
    .auto_out_1_ar_ready(auto_out_1_ar_ready),
    .auto_out_1_ar_valid(auto_out_1_ar_valid),
    .auto_out_1_ar_bits_id(auto_out_1_ar_bits_id),
    .auto_out_1_ar_bits_addr(auto_out_1_ar_bits_addr),
    .auto_out_1_ar_bits_len(auto_out_1_ar_bits_len),
    .auto_out_1_ar_bits_size(auto_out_1_ar_bits_size),
    .auto_out_1_ar_bits_cache(auto_out_1_ar_bits_cache),
    .auto_out_1_ar_bits_prot(auto_out_1_ar_bits_prot),
    .auto_out_1_r_ready(auto_out_1_r_ready),
    .auto_out_1_r_valid(auto_out_1_r_valid),
    .auto_out_1_r_bits_id(auto_out_1_r_bits_id),
    .auto_out_1_r_bits_data(auto_out_1_r_bits_data),
    .auto_out_1_r_bits_last(auto_out_1_r_bits_last),
    .auto_out_0_aw_ready(auto_out_0_aw_ready),
    .auto_out_0_aw_valid(auto_out_0_aw_valid),
    .auto_out_0_aw_bits_id(auto_out_0_aw_bits_id),
    .auto_out_0_aw_bits_addr(auto_out_0_aw_bits_addr),
    .auto_out_0_aw_bits_len(auto_out_0_aw_bits_len),
    .auto_out_0_aw_bits_size(auto_out_0_aw_bits_size),
    .auto_out_0_aw_bits_burst(auto_out_0_aw_bits_burst),
    .auto_out_0_aw_bits_cache(auto_out_0_aw_bits_cache),
    .auto_out_0_aw_bits_prot(auto_out_0_aw_bits_prot),
    .auto_out_0_aw_bits_qos(auto_out_0_aw_bits_qos),
    .auto_out_0_w_ready(auto_out_0_w_ready),
    .auto_out_0_w_valid(auto_out_0_w_valid),
    .auto_out_0_w_bits_data(auto_out_0_w_bits_data),
    .auto_out_0_w_bits_strb(auto_out_0_w_bits_strb),
    .auto_out_0_w_bits_last(auto_out_0_w_bits_last),
    .auto_out_0_b_ready(auto_out_0_b_ready),
    .auto_out_0_b_valid(auto_out_0_b_valid),
    .auto_out_0_b_bits_id(auto_out_0_b_bits_id),
    .auto_out_0_ar_ready(auto_out_0_ar_ready),
    .auto_out_0_ar_valid(auto_out_0_ar_valid),
    .auto_out_0_ar_bits_id(auto_out_0_ar_bits_id),
    .auto_out_0_ar_bits_addr(auto_out_0_ar_bits_addr),
    .auto_out_0_ar_bits_len(auto_out_0_ar_bits_len),
    .auto_out_0_ar_bits_size(auto_out_0_ar_bits_size),
    .auto_out_0_ar_bits_burst(auto_out_0_ar_bits_burst),
    .auto_out_0_ar_bits_cache(auto_out_0_ar_bits_cache),
    .auto_out_0_ar_bits_prot(auto_out_0_ar_bits_prot),
    .auto_out_0_ar_bits_qos(auto_out_0_ar_bits_qos),
    .auto_out_0_r_ready(auto_out_0_r_ready),
    .auto_out_0_r_valid(auto_out_0_r_valid),
    .auto_out_0_r_bits_id(auto_out_0_r_bits_id),
    .auto_out_0_r_bits_data(auto_out_0_r_bits_data),
    .auto_out_0_r_bits_last(auto_out_0_r_bits_last)
  );
endmodule
