// 自动生成：scripts/gen_l2mbist.py —— 勿手改
module L2Directory_xs(
  input clock,
  input reset,
  input [3:0] mbist_array,
  input mbist_all,
  input mbist_req,
  output mbist_ack,
  input mbist_writeen,
  input [7:0] mbist_be,
  input [9:0] mbist_addr,
  input [103:0] mbist_indata,
  input mbist_readen,
  input [9:0] mbist_addr_rd,
  output [103:0] mbist_outdata,
  output [9:0] toSRAM_0_addr,
  output [9:0] toSRAM_0_addr_rd,
  output [75:0] toSRAM_0_wdata,
  output [3:0] toSRAM_0_wmask,
  output toSRAM_0_re,
  output toSRAM_0_we,
  input [75:0] toSRAM_0_rdata,
  output toSRAM_0_ack,
  output toSRAM_0_selectedOH,
  output [1:0] toSRAM_0_array,
  output [9:0] toSRAM_1_addr,
  output [9:0] toSRAM_1_addr_rd,
  output [75:0] toSRAM_1_wdata,
  output [3:0] toSRAM_1_wmask,
  output toSRAM_1_re,
  output toSRAM_1_we,
  input [75:0] toSRAM_1_rdata,
  output toSRAM_1_ack,
  output toSRAM_1_selectedOH,
  output [1:0] toSRAM_1_array,
  output [9:0] toSRAM_2_addr,
  output [9:0] toSRAM_2_addr_rd,
  output [75:0] toSRAM_2_wdata,
  output [3:0] toSRAM_2_wmask,
  output toSRAM_2_re,
  output toSRAM_2_we,
  input [75:0] toSRAM_2_rdata,
  output toSRAM_2_ack,
  output toSRAM_2_selectedOH,
  output [2:0] toSRAM_2_array,
  output [9:0] toSRAM_3_addr,
  output [9:0] toSRAM_3_addr_rd,
  output [75:0] toSRAM_3_wdata,
  output [3:0] toSRAM_3_wmask,
  output toSRAM_3_re,
  output toSRAM_3_we,
  input [75:0] toSRAM_3_rdata,
  output toSRAM_3_ack,
  output toSRAM_3_selectedOH,
  output [2:0] toSRAM_3_array,
  output [9:0] toSRAM_4_addr,
  output [9:0] toSRAM_4_addr_rd,
  output [103:0] toSRAM_4_wdata,
  output [7:0] toSRAM_4_wmask,
  output toSRAM_4_re,
  output toSRAM_4_we,
  input [103:0] toSRAM_4_rdata,
  output toSRAM_4_ack,
  output toSRAM_4_selectedOH,
  output [2:0] toSRAM_4_array,
  output [9:0] toSRAM_5_addr,
  output [9:0] toSRAM_5_addr_rd,
  output [15:0] toSRAM_5_wdata,
  output toSRAM_5_wmask,
  output toSRAM_5_re,
  output toSRAM_5_we,
  input [15:0] toSRAM_5_rdata,
  output toSRAM_5_ack,
  output toSRAM_5_selectedOH,
  output [2:0] toSRAM_5_array,
  output [9:0] toSRAM_6_addr,
  output [9:0] toSRAM_6_addr_rd,
  output [7:0] toSRAM_6_wdata,
  output [7:0] toSRAM_6_wmask,
  output toSRAM_6_re,
  output toSRAM_6_we,
  input [7:0] toSRAM_6_rdata,
  output toSRAM_6_ack,
  output toSRAM_6_selectedOH,
  output [3:0] toSRAM_6_array
);
  xs_L2Directory_core u_core (
    .clock(clock),
    .reset(reset),
    .mbist_array(mbist_array),
    .mbist_all(mbist_all),
    .mbist_req(mbist_req),
    .mbist_ack(mbist_ack),
    .mbist_writeen(mbist_writeen),
    .mbist_be(mbist_be),
    .mbist_addr(mbist_addr),
    .mbist_indata(mbist_indata),
    .mbist_readen(mbist_readen),
    .mbist_addr_rd(mbist_addr_rd),
    .mbist_outdata(mbist_outdata),
    .toSRAM_0_addr(toSRAM_0_addr),
    .toSRAM_0_addr_rd(toSRAM_0_addr_rd),
    .toSRAM_0_wdata(toSRAM_0_wdata),
    .toSRAM_0_wmask(toSRAM_0_wmask),
    .toSRAM_0_re(toSRAM_0_re),
    .toSRAM_0_we(toSRAM_0_we),
    .toSRAM_0_rdata(toSRAM_0_rdata),
    .toSRAM_0_ack(toSRAM_0_ack),
    .toSRAM_0_selectedOH(toSRAM_0_selectedOH),
    .toSRAM_0_array(toSRAM_0_array),
    .toSRAM_1_addr(toSRAM_1_addr),
    .toSRAM_1_addr_rd(toSRAM_1_addr_rd),
    .toSRAM_1_wdata(toSRAM_1_wdata),
    .toSRAM_1_wmask(toSRAM_1_wmask),
    .toSRAM_1_re(toSRAM_1_re),
    .toSRAM_1_we(toSRAM_1_we),
    .toSRAM_1_rdata(toSRAM_1_rdata),
    .toSRAM_1_ack(toSRAM_1_ack),
    .toSRAM_1_selectedOH(toSRAM_1_selectedOH),
    .toSRAM_1_array(toSRAM_1_array),
    .toSRAM_2_addr(toSRAM_2_addr),
    .toSRAM_2_addr_rd(toSRAM_2_addr_rd),
    .toSRAM_2_wdata(toSRAM_2_wdata),
    .toSRAM_2_wmask(toSRAM_2_wmask),
    .toSRAM_2_re(toSRAM_2_re),
    .toSRAM_2_we(toSRAM_2_we),
    .toSRAM_2_rdata(toSRAM_2_rdata),
    .toSRAM_2_ack(toSRAM_2_ack),
    .toSRAM_2_selectedOH(toSRAM_2_selectedOH),
    .toSRAM_2_array(toSRAM_2_array),
    .toSRAM_3_addr(toSRAM_3_addr),
    .toSRAM_3_addr_rd(toSRAM_3_addr_rd),
    .toSRAM_3_wdata(toSRAM_3_wdata),
    .toSRAM_3_wmask(toSRAM_3_wmask),
    .toSRAM_3_re(toSRAM_3_re),
    .toSRAM_3_we(toSRAM_3_we),
    .toSRAM_3_rdata(toSRAM_3_rdata),
    .toSRAM_3_ack(toSRAM_3_ack),
    .toSRAM_3_selectedOH(toSRAM_3_selectedOH),
    .toSRAM_3_array(toSRAM_3_array),
    .toSRAM_4_addr(toSRAM_4_addr),
    .toSRAM_4_addr_rd(toSRAM_4_addr_rd),
    .toSRAM_4_wdata(toSRAM_4_wdata),
    .toSRAM_4_wmask(toSRAM_4_wmask),
    .toSRAM_4_re(toSRAM_4_re),
    .toSRAM_4_we(toSRAM_4_we),
    .toSRAM_4_rdata(toSRAM_4_rdata),
    .toSRAM_4_ack(toSRAM_4_ack),
    .toSRAM_4_selectedOH(toSRAM_4_selectedOH),
    .toSRAM_4_array(toSRAM_4_array),
    .toSRAM_5_addr(toSRAM_5_addr),
    .toSRAM_5_addr_rd(toSRAM_5_addr_rd),
    .toSRAM_5_wdata(toSRAM_5_wdata),
    .toSRAM_5_wmask(toSRAM_5_wmask),
    .toSRAM_5_re(toSRAM_5_re),
    .toSRAM_5_we(toSRAM_5_we),
    .toSRAM_5_rdata(toSRAM_5_rdata),
    .toSRAM_5_ack(toSRAM_5_ack),
    .toSRAM_5_selectedOH(toSRAM_5_selectedOH),
    .toSRAM_5_array(toSRAM_5_array),
    .toSRAM_6_addr(toSRAM_6_addr),
    .toSRAM_6_addr_rd(toSRAM_6_addr_rd),
    .toSRAM_6_wdata(toSRAM_6_wdata),
    .toSRAM_6_wmask(toSRAM_6_wmask),
    .toSRAM_6_re(toSRAM_6_re),
    .toSRAM_6_we(toSRAM_6_we),
    .toSRAM_6_rdata(toSRAM_6_rdata),
    .toSRAM_6_ack(toSRAM_6_ack),
    .toSRAM_6_selectedOH(toSRAM_6_selectedOH),
    .toSRAM_6_array(toSRAM_6_array)
  );
endmodule
