// 自动生成：scripts/gen_ftq.py —— 勿手改
module Ftq_xs(
  input  clock,
  input  reset,
  output io_fromBpu_resp_ready,
  input  io_fromBpu_resp_valid,
  input  [49:0] io_fromBpu_resp_bits_s1_pc_3,
  input  [63:0] io_fromBpu_resp_bits_s1_full_pred_0_predCycle,
  input  io_fromBpu_resp_bits_s1_full_pred_3_br_taken_mask_0,
  input  io_fromBpu_resp_bits_s1_full_pred_3_br_taken_mask_1,
  input  io_fromBpu_resp_bits_s1_full_pred_3_slot_valids_0,
  input  io_fromBpu_resp_bits_s1_full_pred_3_slot_valids_1,
  input  [49:0] io_fromBpu_resp_bits_s1_full_pred_3_targets_0,
  input  [49:0] io_fromBpu_resp_bits_s1_full_pred_3_targets_1,
  input  [3:0] io_fromBpu_resp_bits_s1_full_pred_3_offsets_0,
  input  [3:0] io_fromBpu_resp_bits_s1_full_pred_3_offsets_1,
  input  [49:0] io_fromBpu_resp_bits_s1_full_pred_3_fallThroughAddr,
  input  io_fromBpu_resp_bits_s1_full_pred_3_fallThroughErr,
  input  io_fromBpu_resp_bits_s1_full_pred_3_is_br_sharing,
  input  io_fromBpu_resp_bits_s1_full_pred_3_hit,
  input  [49:0] io_fromBpu_resp_bits_s2_pc_3,
  input  io_fromBpu_resp_bits_s2_valid_3,
  input  io_fromBpu_resp_bits_s2_hasRedirect_3,
  input  io_fromBpu_resp_bits_s2_ftq_idx_flag,
  input  [5:0] io_fromBpu_resp_bits_s2_ftq_idx_value,
  input  [63:0] io_fromBpu_resp_bits_s2_full_pred_0_predCycle,
  input  io_fromBpu_resp_bits_s2_full_pred_3_br_taken_mask_0,
  input  io_fromBpu_resp_bits_s2_full_pred_3_br_taken_mask_1,
  input  io_fromBpu_resp_bits_s2_full_pred_3_slot_valids_0,
  input  io_fromBpu_resp_bits_s2_full_pred_3_slot_valids_1,
  input  [49:0] io_fromBpu_resp_bits_s2_full_pred_3_targets_0,
  input  [49:0] io_fromBpu_resp_bits_s2_full_pred_3_targets_1,
  input  [3:0] io_fromBpu_resp_bits_s2_full_pred_3_offsets_0,
  input  [3:0] io_fromBpu_resp_bits_s2_full_pred_3_offsets_1,
  input  [49:0] io_fromBpu_resp_bits_s2_full_pred_3_fallThroughAddr,
  input  io_fromBpu_resp_bits_s2_full_pred_3_fallThroughErr,
  input  io_fromBpu_resp_bits_s2_full_pred_3_is_br_sharing,
  input  io_fromBpu_resp_bits_s2_full_pred_3_hit,
  input  [49:0] io_fromBpu_resp_bits_s3_pc_0,
  input  [49:0] io_fromBpu_resp_bits_s3_pc_3,
  input  io_fromBpu_resp_bits_s3_valid_3,
  input  io_fromBpu_resp_bits_s3_hasRedirect_3,
  input  io_fromBpu_resp_bits_s3_ftq_idx_flag,
  input  [5:0] io_fromBpu_resp_bits_s3_ftq_idx_value,
  input  [63:0] io_fromBpu_resp_bits_s3_full_pred_0_predCycle,
  input  io_fromBpu_resp_bits_s3_full_pred_3_br_taken_mask_0,
  input  io_fromBpu_resp_bits_s3_full_pred_3_br_taken_mask_1,
  input  io_fromBpu_resp_bits_s3_full_pred_3_slot_valids_0,
  input  io_fromBpu_resp_bits_s3_full_pred_3_slot_valids_1,
  input  [49:0] io_fromBpu_resp_bits_s3_full_pred_3_targets_0,
  input  [49:0] io_fromBpu_resp_bits_s3_full_pred_3_targets_1,
  input  [3:0] io_fromBpu_resp_bits_s3_full_pred_3_offsets_0,
  input  [3:0] io_fromBpu_resp_bits_s3_full_pred_3_offsets_1,
  input  [49:0] io_fromBpu_resp_bits_s3_full_pred_3_fallThroughAddr,
  input  io_fromBpu_resp_bits_s3_full_pred_3_fallThroughErr,
  input  io_fromBpu_resp_bits_s3_full_pred_3_is_br_sharing,
  input  io_fromBpu_resp_bits_s3_full_pred_3_hit,
  input  [515:0] io_fromBpu_resp_bits_last_stage_meta,
  input  io_fromBpu_resp_bits_last_stage_spec_info_histPtr_flag,
  input  [7:0] io_fromBpu_resp_bits_last_stage_spec_info_histPtr_value,
  input  [3:0] io_fromBpu_resp_bits_last_stage_spec_info_ssp,
  input  [2:0] io_fromBpu_resp_bits_last_stage_spec_info_sctr,
  input  io_fromBpu_resp_bits_last_stage_spec_info_TOSW_flag,
  input  [4:0] io_fromBpu_resp_bits_last_stage_spec_info_TOSW_value,
  input  io_fromBpu_resp_bits_last_stage_spec_info_TOSR_flag,
  input  [4:0] io_fromBpu_resp_bits_last_stage_spec_info_TOSR_value,
  input  io_fromBpu_resp_bits_last_stage_spec_info_NOS_flag,
  input  [4:0] io_fromBpu_resp_bits_last_stage_spec_info_NOS_value,
  input  [49:0] io_fromBpu_resp_bits_last_stage_spec_info_topAddr,
  input  io_fromBpu_resp_bits_last_stage_spec_info_sc_disagree_0,
  input  io_fromBpu_resp_bits_last_stage_spec_info_sc_disagree_1,
  input  io_fromBpu_resp_bits_last_stage_ftb_entry_isCall,
  input  io_fromBpu_resp_bits_last_stage_ftb_entry_isRet,
  input  io_fromBpu_resp_bits_last_stage_ftb_entry_isJalr,
  input  io_fromBpu_resp_bits_last_stage_ftb_entry_valid,
  input  [3:0] io_fromBpu_resp_bits_last_stage_ftb_entry_brSlots_0_offset,
  input  io_fromBpu_resp_bits_last_stage_ftb_entry_brSlots_0_sharing,
  input  io_fromBpu_resp_bits_last_stage_ftb_entry_brSlots_0_valid,
  input  [11:0] io_fromBpu_resp_bits_last_stage_ftb_entry_brSlots_0_lower,
  input  [1:0] io_fromBpu_resp_bits_last_stage_ftb_entry_brSlots_0_tarStat,
  input  [3:0] io_fromBpu_resp_bits_last_stage_ftb_entry_tailSlot_offset,
  input  io_fromBpu_resp_bits_last_stage_ftb_entry_tailSlot_sharing,
  input  io_fromBpu_resp_bits_last_stage_ftb_entry_tailSlot_valid,
  input  [19:0] io_fromBpu_resp_bits_last_stage_ftb_entry_tailSlot_lower,
  input  [1:0] io_fromBpu_resp_bits_last_stage_ftb_entry_tailSlot_tarStat,
  input  [3:0] io_fromBpu_resp_bits_last_stage_ftb_entry_pftAddr,
  input  io_fromBpu_resp_bits_last_stage_ftb_entry_carry,
  input  io_fromBpu_resp_bits_last_stage_ftb_entry_last_may_be_rvi_call,
  input  io_fromBpu_resp_bits_last_stage_ftb_entry_strong_bias_0,
  input  io_fromBpu_resp_bits_last_stage_ftb_entry_strong_bias_1,
  input  io_fromBpu_resp_bits_topdown_info_reasons_1,
  input  io_fromBpu_resp_bits_topdown_info_reasons_2,
  input  io_fromBpu_resp_bits_topdown_info_reasons_3,
  input  io_fromBpu_resp_bits_topdown_info_reasons_4,
  input  io_fromBpu_resp_bits_topdown_info_reasons_5,
  input  io_fromBpu_resp_bits_topdown_info_reasons_6,
  input  io_fromBpu_resp_bits_topdown_info_reasons_7,
  input  io_fromBpu_resp_bits_topdown_info_reasons_8,
  input  io_fromBpu_resp_bits_topdown_info_reasons_9,
  input  io_fromBpu_resp_bits_topdown_info_reasons_12,
  input  io_fromIfu_pdWb_valid,
  input  [49:0] io_fromIfu_pdWb_bits_pc_0,
  input  [49:0] io_fromIfu_pdWb_bits_pc_1,
  input  [49:0] io_fromIfu_pdWb_bits_pc_2,
  input  [49:0] io_fromIfu_pdWb_bits_pc_3,
  input  [49:0] io_fromIfu_pdWb_bits_pc_4,
  input  [49:0] io_fromIfu_pdWb_bits_pc_5,
  input  [49:0] io_fromIfu_pdWb_bits_pc_6,
  input  [49:0] io_fromIfu_pdWb_bits_pc_7,
  input  [49:0] io_fromIfu_pdWb_bits_pc_8,
  input  [49:0] io_fromIfu_pdWb_bits_pc_9,
  input  [49:0] io_fromIfu_pdWb_bits_pc_10,
  input  [49:0] io_fromIfu_pdWb_bits_pc_11,
  input  [49:0] io_fromIfu_pdWb_bits_pc_12,
  input  [49:0] io_fromIfu_pdWb_bits_pc_13,
  input  [49:0] io_fromIfu_pdWb_bits_pc_14,
  input  [49:0] io_fromIfu_pdWb_bits_pc_15,
  input  io_fromIfu_pdWb_bits_pd_0_valid,
  input  io_fromIfu_pdWb_bits_pd_0_isRVC,
  input  [1:0] io_fromIfu_pdWb_bits_pd_0_brType,
  input  io_fromIfu_pdWb_bits_pd_0_isCall,
  input  io_fromIfu_pdWb_bits_pd_0_isRet,
  input  io_fromIfu_pdWb_bits_pd_1_valid,
  input  io_fromIfu_pdWb_bits_pd_1_isRVC,
  input  [1:0] io_fromIfu_pdWb_bits_pd_1_brType,
  input  io_fromIfu_pdWb_bits_pd_1_isCall,
  input  io_fromIfu_pdWb_bits_pd_1_isRet,
  input  io_fromIfu_pdWb_bits_pd_2_valid,
  input  io_fromIfu_pdWb_bits_pd_2_isRVC,
  input  [1:0] io_fromIfu_pdWb_bits_pd_2_brType,
  input  io_fromIfu_pdWb_bits_pd_2_isCall,
  input  io_fromIfu_pdWb_bits_pd_2_isRet,
  input  io_fromIfu_pdWb_bits_pd_3_valid,
  input  io_fromIfu_pdWb_bits_pd_3_isRVC,
  input  [1:0] io_fromIfu_pdWb_bits_pd_3_brType,
  input  io_fromIfu_pdWb_bits_pd_3_isCall,
  input  io_fromIfu_pdWb_bits_pd_3_isRet,
  input  io_fromIfu_pdWb_bits_pd_4_valid,
  input  io_fromIfu_pdWb_bits_pd_4_isRVC,
  input  [1:0] io_fromIfu_pdWb_bits_pd_4_brType,
  input  io_fromIfu_pdWb_bits_pd_4_isCall,
  input  io_fromIfu_pdWb_bits_pd_4_isRet,
  input  io_fromIfu_pdWb_bits_pd_5_valid,
  input  io_fromIfu_pdWb_bits_pd_5_isRVC,
  input  [1:0] io_fromIfu_pdWb_bits_pd_5_brType,
  input  io_fromIfu_pdWb_bits_pd_5_isCall,
  input  io_fromIfu_pdWb_bits_pd_5_isRet,
  input  io_fromIfu_pdWb_bits_pd_6_valid,
  input  io_fromIfu_pdWb_bits_pd_6_isRVC,
  input  [1:0] io_fromIfu_pdWb_bits_pd_6_brType,
  input  io_fromIfu_pdWb_bits_pd_6_isCall,
  input  io_fromIfu_pdWb_bits_pd_6_isRet,
  input  io_fromIfu_pdWb_bits_pd_7_valid,
  input  io_fromIfu_pdWb_bits_pd_7_isRVC,
  input  [1:0] io_fromIfu_pdWb_bits_pd_7_brType,
  input  io_fromIfu_pdWb_bits_pd_7_isCall,
  input  io_fromIfu_pdWb_bits_pd_7_isRet,
  input  io_fromIfu_pdWb_bits_pd_8_valid,
  input  io_fromIfu_pdWb_bits_pd_8_isRVC,
  input  [1:0] io_fromIfu_pdWb_bits_pd_8_brType,
  input  io_fromIfu_pdWb_bits_pd_8_isCall,
  input  io_fromIfu_pdWb_bits_pd_8_isRet,
  input  io_fromIfu_pdWb_bits_pd_9_valid,
  input  io_fromIfu_pdWb_bits_pd_9_isRVC,
  input  [1:0] io_fromIfu_pdWb_bits_pd_9_brType,
  input  io_fromIfu_pdWb_bits_pd_9_isCall,
  input  io_fromIfu_pdWb_bits_pd_9_isRet,
  input  io_fromIfu_pdWb_bits_pd_10_valid,
  input  io_fromIfu_pdWb_bits_pd_10_isRVC,
  input  [1:0] io_fromIfu_pdWb_bits_pd_10_brType,
  input  io_fromIfu_pdWb_bits_pd_10_isCall,
  input  io_fromIfu_pdWb_bits_pd_10_isRet,
  input  io_fromIfu_pdWb_bits_pd_11_valid,
  input  io_fromIfu_pdWb_bits_pd_11_isRVC,
  input  [1:0] io_fromIfu_pdWb_bits_pd_11_brType,
  input  io_fromIfu_pdWb_bits_pd_11_isCall,
  input  io_fromIfu_pdWb_bits_pd_11_isRet,
  input  io_fromIfu_pdWb_bits_pd_12_valid,
  input  io_fromIfu_pdWb_bits_pd_12_isRVC,
  input  [1:0] io_fromIfu_pdWb_bits_pd_12_brType,
  input  io_fromIfu_pdWb_bits_pd_12_isCall,
  input  io_fromIfu_pdWb_bits_pd_12_isRet,
  input  io_fromIfu_pdWb_bits_pd_13_valid,
  input  io_fromIfu_pdWb_bits_pd_13_isRVC,
  input  [1:0] io_fromIfu_pdWb_bits_pd_13_brType,
  input  io_fromIfu_pdWb_bits_pd_13_isCall,
  input  io_fromIfu_pdWb_bits_pd_13_isRet,
  input  io_fromIfu_pdWb_bits_pd_14_valid,
  input  io_fromIfu_pdWb_bits_pd_14_isRVC,
  input  [1:0] io_fromIfu_pdWb_bits_pd_14_brType,
  input  io_fromIfu_pdWb_bits_pd_14_isCall,
  input  io_fromIfu_pdWb_bits_pd_14_isRet,
  input  io_fromIfu_pdWb_bits_pd_15_valid,
  input  io_fromIfu_pdWb_bits_pd_15_isRVC,
  input  [1:0] io_fromIfu_pdWb_bits_pd_15_brType,
  input  io_fromIfu_pdWb_bits_pd_15_isCall,
  input  io_fromIfu_pdWb_bits_pd_15_isRet,
  input  io_fromIfu_pdWb_bits_ftqIdx_flag,
  input  [5:0] io_fromIfu_pdWb_bits_ftqIdx_value,
  input  io_fromIfu_pdWb_bits_misOffset_valid,
  input  [3:0] io_fromIfu_pdWb_bits_misOffset_bits,
  input  io_fromIfu_pdWb_bits_cfiOffset_valid,
  input  [49:0] io_fromIfu_pdWb_bits_target,
  input  [49:0] io_fromIfu_pdWb_bits_jalTarget,
  input  io_fromIfu_pdWb_bits_instrRange_0,
  input  io_fromIfu_pdWb_bits_instrRange_1,
  input  io_fromIfu_pdWb_bits_instrRange_2,
  input  io_fromIfu_pdWb_bits_instrRange_3,
  input  io_fromIfu_pdWb_bits_instrRange_4,
  input  io_fromIfu_pdWb_bits_instrRange_5,
  input  io_fromIfu_pdWb_bits_instrRange_6,
  input  io_fromIfu_pdWb_bits_instrRange_7,
  input  io_fromIfu_pdWb_bits_instrRange_8,
  input  io_fromIfu_pdWb_bits_instrRange_9,
  input  io_fromIfu_pdWb_bits_instrRange_10,
  input  io_fromIfu_pdWb_bits_instrRange_11,
  input  io_fromIfu_pdWb_bits_instrRange_12,
  input  io_fromIfu_pdWb_bits_instrRange_13,
  input  io_fromIfu_pdWb_bits_instrRange_14,
  input  io_fromIfu_pdWb_bits_instrRange_15,
  input  io_fromBackend_rob_commits_0_valid,
  input  [2:0] io_fromBackend_rob_commits_0_bits_commitType,
  input  io_fromBackend_rob_commits_0_bits_ftqIdx_flag,
  input  [5:0] io_fromBackend_rob_commits_0_bits_ftqIdx_value,
  input  [3:0] io_fromBackend_rob_commits_0_bits_ftqOffset,
  input  io_fromBackend_rob_commits_1_valid,
  input  [2:0] io_fromBackend_rob_commits_1_bits_commitType,
  input  io_fromBackend_rob_commits_1_bits_ftqIdx_flag,
  input  [5:0] io_fromBackend_rob_commits_1_bits_ftqIdx_value,
  input  [3:0] io_fromBackend_rob_commits_1_bits_ftqOffset,
  input  io_fromBackend_rob_commits_2_valid,
  input  [2:0] io_fromBackend_rob_commits_2_bits_commitType,
  input  io_fromBackend_rob_commits_2_bits_ftqIdx_flag,
  input  [5:0] io_fromBackend_rob_commits_2_bits_ftqIdx_value,
  input  [3:0] io_fromBackend_rob_commits_2_bits_ftqOffset,
  input  io_fromBackend_rob_commits_3_valid,
  input  [2:0] io_fromBackend_rob_commits_3_bits_commitType,
  input  io_fromBackend_rob_commits_3_bits_ftqIdx_flag,
  input  [5:0] io_fromBackend_rob_commits_3_bits_ftqIdx_value,
  input  [3:0] io_fromBackend_rob_commits_3_bits_ftqOffset,
  input  io_fromBackend_rob_commits_4_valid,
  input  [2:0] io_fromBackend_rob_commits_4_bits_commitType,
  input  io_fromBackend_rob_commits_4_bits_ftqIdx_flag,
  input  [5:0] io_fromBackend_rob_commits_4_bits_ftqIdx_value,
  input  [3:0] io_fromBackend_rob_commits_4_bits_ftqOffset,
  input  io_fromBackend_rob_commits_5_valid,
  input  [2:0] io_fromBackend_rob_commits_5_bits_commitType,
  input  io_fromBackend_rob_commits_5_bits_ftqIdx_flag,
  input  [5:0] io_fromBackend_rob_commits_5_bits_ftqIdx_value,
  input  [3:0] io_fromBackend_rob_commits_5_bits_ftqOffset,
  input  io_fromBackend_rob_commits_6_valid,
  input  [2:0] io_fromBackend_rob_commits_6_bits_commitType,
  input  io_fromBackend_rob_commits_6_bits_ftqIdx_flag,
  input  [5:0] io_fromBackend_rob_commits_6_bits_ftqIdx_value,
  input  [3:0] io_fromBackend_rob_commits_6_bits_ftqOffset,
  input  io_fromBackend_rob_commits_7_valid,
  input  [2:0] io_fromBackend_rob_commits_7_bits_commitType,
  input  io_fromBackend_rob_commits_7_bits_ftqIdx_flag,
  input  [5:0] io_fromBackend_rob_commits_7_bits_ftqIdx_value,
  input  [3:0] io_fromBackend_rob_commits_7_bits_ftqOffset,
  input  io_fromBackend_redirect_valid,
  input  io_fromBackend_redirect_bits_ftqIdx_flag,
  input  [5:0] io_fromBackend_redirect_bits_ftqIdx_value,
  input  [3:0] io_fromBackend_redirect_bits_ftqOffset,
  input  io_fromBackend_redirect_bits_level,
  input  [49:0] io_fromBackend_redirect_bits_cfiUpdate_pc,
  input  [49:0] io_fromBackend_redirect_bits_cfiUpdate_target,
  input  io_fromBackend_redirect_bits_cfiUpdate_taken,
  input  io_fromBackend_redirect_bits_cfiUpdate_isMisPred,
  input  io_fromBackend_redirect_bits_cfiUpdate_backendIGPF,
  input  io_fromBackend_redirect_bits_cfiUpdate_backendIPF,
  input  io_fromBackend_redirect_bits_cfiUpdate_backendIAF,
  input  io_fromBackend_redirect_bits_debugIsCtrl,
  input  io_fromBackend_redirect_bits_debugIsMemVio,
  input  io_fromBackend_ftqIdxAhead_0_valid,
  input  [5:0] io_fromBackend_ftqIdxAhead_0_bits_value,
  input  [2:0] io_fromBackend_ftqIdxSelOH_bits,
  output io_toBpu_redirect_valid,
  output io_toBpu_redirect_bits_level,
  output [49:0] io_toBpu_redirect_bits_cfiUpdate_pc,
  output io_toBpu_redirect_bits_cfiUpdate_pd_valid,
  output io_toBpu_redirect_bits_cfiUpdate_pd_isRVC,
  output io_toBpu_redirect_bits_cfiUpdate_pd_isCall,
  output io_toBpu_redirect_bits_cfiUpdate_pd_isRet,
  output [3:0] io_toBpu_redirect_bits_cfiUpdate_ssp,
  output [2:0] io_toBpu_redirect_bits_cfiUpdate_sctr,
  output io_toBpu_redirect_bits_cfiUpdate_TOSW_flag,
  output [4:0] io_toBpu_redirect_bits_cfiUpdate_TOSW_value,
  output io_toBpu_redirect_bits_cfiUpdate_TOSR_flag,
  output [4:0] io_toBpu_redirect_bits_cfiUpdate_TOSR_value,
  output io_toBpu_redirect_bits_cfiUpdate_NOS_flag,
  output [4:0] io_toBpu_redirect_bits_cfiUpdate_NOS_value,
  output io_toBpu_redirect_bits_cfiUpdate_histPtr_flag,
  output [7:0] io_toBpu_redirect_bits_cfiUpdate_histPtr_value,
  output io_toBpu_redirect_bits_cfiUpdate_br_hit,
  output io_toBpu_redirect_bits_cfiUpdate_jr_hit,
  output io_toBpu_redirect_bits_cfiUpdate_sc_hit,
  output [49:0] io_toBpu_redirect_bits_cfiUpdate_target,
  output io_toBpu_redirect_bits_cfiUpdate_taken,
  output [1:0] io_toBpu_redirect_bits_cfiUpdate_shift,
  output io_toBpu_redirect_bits_cfiUpdate_addIntoHist,
  output io_toBpu_redirect_bits_debugIsCtrl,
  output io_toBpu_redirect_bits_debugIsMemVio,
  output io_toBpu_redirect_bits_BTBMissBubble,
  output io_toBpu_update_valid,
  output [49:0] io_toBpu_update_bits_pc,
  output [7:0] io_toBpu_update_bits_spec_info_histPtr_value,
  output io_toBpu_update_bits_ftb_entry_isCall,
  output io_toBpu_update_bits_ftb_entry_isRet,
  output io_toBpu_update_bits_ftb_entry_isJalr,
  output io_toBpu_update_bits_ftb_entry_valid,
  output [3:0] io_toBpu_update_bits_ftb_entry_brSlots_0_offset,
  output io_toBpu_update_bits_ftb_entry_brSlots_0_sharing,
  output io_toBpu_update_bits_ftb_entry_brSlots_0_valid,
  output [11:0] io_toBpu_update_bits_ftb_entry_brSlots_0_lower,
  output [1:0] io_toBpu_update_bits_ftb_entry_brSlots_0_tarStat,
  output [3:0] io_toBpu_update_bits_ftb_entry_tailSlot_offset,
  output io_toBpu_update_bits_ftb_entry_tailSlot_sharing,
  output io_toBpu_update_bits_ftb_entry_tailSlot_valid,
  output [19:0] io_toBpu_update_bits_ftb_entry_tailSlot_lower,
  output [1:0] io_toBpu_update_bits_ftb_entry_tailSlot_tarStat,
  output [3:0] io_toBpu_update_bits_ftb_entry_pftAddr,
  output io_toBpu_update_bits_ftb_entry_carry,
  output io_toBpu_update_bits_ftb_entry_last_may_be_rvi_call,
  output io_toBpu_update_bits_ftb_entry_strong_bias_0,
  output io_toBpu_update_bits_ftb_entry_strong_bias_1,
  output io_toBpu_update_bits_cfi_idx_valid,
  output [3:0] io_toBpu_update_bits_cfi_idx_bits,
  output io_toBpu_update_bits_br_taken_mask_0,
  output io_toBpu_update_bits_br_taken_mask_1,
  output io_toBpu_update_bits_jmp_taken,
  output io_toBpu_update_bits_mispred_mask_0,
  output io_toBpu_update_bits_mispred_mask_1,
  output io_toBpu_update_bits_mispred_mask_2,
  output io_toBpu_update_bits_false_hit,
  output io_toBpu_update_bits_old_entry,
  output [515:0] io_toBpu_update_bits_meta,
  output [49:0] io_toBpu_update_bits_full_target,
  output io_toBpu_enq_ptr_flag,
  output [5:0] io_toBpu_enq_ptr_value,
  output io_toBpu_redirctFromIFU,
  input  io_toIfu_req_ready,
  output io_toIfu_req_valid,
  output [49:0] io_toIfu_req_bits_startAddr,
  output [49:0] io_toIfu_req_bits_nextlineStart,
  output [49:0] io_toIfu_req_bits_nextStartAddr,
  output io_toIfu_req_bits_ftqIdx_flag,
  output [5:0] io_toIfu_req_bits_ftqIdx_value,
  output io_toIfu_req_bits_ftqOffset_valid,
  output [3:0] io_toIfu_req_bits_ftqOffset_bits,
  output io_toIfu_req_bits_topdown_info_reasons_0,
  output io_toIfu_req_bits_topdown_info_reasons_1,
  output io_toIfu_req_bits_topdown_info_reasons_2,
  output io_toIfu_req_bits_topdown_info_reasons_3,
  output io_toIfu_req_bits_topdown_info_reasons_4,
  output io_toIfu_req_bits_topdown_info_reasons_5,
  output io_toIfu_req_bits_topdown_info_reasons_6,
  output io_toIfu_req_bits_topdown_info_reasons_7,
  output io_toIfu_req_bits_topdown_info_reasons_8,
  output io_toIfu_req_bits_topdown_info_reasons_9,
  output io_toIfu_req_bits_topdown_info_reasons_10,
  output io_toIfu_req_bits_topdown_info_reasons_11,
  output io_toIfu_req_bits_topdown_info_reasons_12,
  output io_toIfu_req_bits_topdown_info_reasons_13,
  output io_toIfu_req_bits_topdown_info_reasons_14,
  output io_toIfu_req_bits_topdown_info_reasons_15,
  output io_toIfu_req_bits_topdown_info_reasons_16,
  output io_toIfu_req_bits_topdown_info_reasons_17,
  output io_toIfu_req_bits_topdown_info_reasons_18,
  output io_toIfu_req_bits_topdown_info_reasons_19,
  output io_toIfu_req_bits_topdown_info_reasons_20,
  output io_toIfu_req_bits_topdown_info_reasons_21,
  output io_toIfu_req_bits_topdown_info_reasons_22,
  output io_toIfu_req_bits_topdown_info_reasons_23,
  output io_toIfu_req_bits_topdown_info_reasons_24,
  output io_toIfu_req_bits_topdown_info_reasons_25,
  output io_toIfu_req_bits_topdown_info_reasons_26,
  output io_toIfu_req_bits_topdown_info_reasons_27,
  output io_toIfu_req_bits_topdown_info_reasons_28,
  output io_toIfu_req_bits_topdown_info_reasons_29,
  output io_toIfu_req_bits_topdown_info_reasons_30,
  output io_toIfu_req_bits_topdown_info_reasons_31,
  output io_toIfu_req_bits_topdown_info_reasons_32,
  output io_toIfu_req_bits_topdown_info_reasons_33,
  output io_toIfu_req_bits_topdown_info_reasons_34,
  output io_toIfu_req_bits_topdown_info_reasons_35,
  output io_toIfu_req_bits_topdown_info_reasons_36,
  output io_toIfu_req_bits_topdown_info_reasons_37,
  output io_toIfu_redirect_valid,
  output io_toIfu_redirect_bits_ftqIdx_flag,
  output [5:0] io_toIfu_redirect_bits_ftqIdx_value,
  output [3:0] io_toIfu_redirect_bits_ftqOffset,
  output io_toIfu_redirect_bits_level,
  output io_toIfu_topdown_redirect_valid,
  output io_toIfu_topdown_redirect_bits_cfiUpdate_pd_isRet,
  output io_toIfu_topdown_redirect_bits_cfiUpdate_br_hit,
  output io_toIfu_topdown_redirect_bits_cfiUpdate_jr_hit,
  output io_toIfu_topdown_redirect_bits_cfiUpdate_sc_hit,
  output io_toIfu_topdown_redirect_bits_debugIsCtrl,
  output io_toIfu_topdown_redirect_bits_debugIsMemVio,
  output io_toIfu_flushFromBpu_s2_valid,
  output io_toIfu_flushFromBpu_s2_bits_flag,
  output [5:0] io_toIfu_flushFromBpu_s2_bits_value,
  output io_toIfu_flushFromBpu_s3_valid,
  output io_toIfu_flushFromBpu_s3_bits_flag,
  output [5:0] io_toIfu_flushFromBpu_s3_bits_value,
  output io_toICache_req_valid,
  output [49:0] io_toICache_req_bits_pcMemRead_0_startAddr,
  output [49:0] io_toICache_req_bits_pcMemRead_0_nextlineStart,
  output [49:0] io_toICache_req_bits_pcMemRead_1_startAddr,
  output [49:0] io_toICache_req_bits_pcMemRead_1_nextlineStart,
  output [49:0] io_toICache_req_bits_pcMemRead_2_startAddr,
  output [49:0] io_toICache_req_bits_pcMemRead_2_nextlineStart,
  output [49:0] io_toICache_req_bits_pcMemRead_3_startAddr,
  output [49:0] io_toICache_req_bits_pcMemRead_3_nextlineStart,
  output [49:0] io_toICache_req_bits_pcMemRead_4_startAddr,
  output [49:0] io_toICache_req_bits_pcMemRead_4_nextlineStart,
  output io_toICache_req_bits_readValid_0,
  output io_toICache_req_bits_readValid_1,
  output io_toICache_req_bits_readValid_2,
  output io_toICache_req_bits_readValid_3,
  output io_toICache_req_bits_readValid_4,
  output io_toICache_req_bits_backendException,
  output io_toBackend_pc_mem_wen,
  output [5:0] io_toBackend_pc_mem_waddr,
  output [49:0] io_toBackend_pc_mem_wdata_startAddr,
  output io_toBackend_newest_entry_en,
  output [49:0] io_toBackend_newest_entry_target,
  output [5:0] io_toBackend_newest_entry_ptr_value,
  input  io_toPrefetch_req_ready,
  output io_toPrefetch_req_valid,
  output [49:0] io_toPrefetch_req_bits_startAddr,
  output [49:0] io_toPrefetch_req_bits_nextlineStart,
  output io_toPrefetch_req_bits_ftqIdx_flag,
  output [5:0] io_toPrefetch_req_bits_ftqIdx_value,
  output io_toPrefetch_flushFromBpu_s2_valid,
  output io_toPrefetch_flushFromBpu_s2_bits_flag,
  output [5:0] io_toPrefetch_flushFromBpu_s2_bits_value,
  output io_toPrefetch_flushFromBpu_s3_valid,
  output io_toPrefetch_flushFromBpu_s3_bits_flag,
  output [5:0] io_toPrefetch_flushFromBpu_s3_bits_value,
  output [1:0] io_toPrefetch_backendException,
  output io_icacheFlush,
  input  io_mmioCommitRead_mmioFtqPtr_flag,
  input  [5:0] io_mmioCommitRead_mmioFtqPtr_value,
  output io_mmioCommitRead_mmioLastCommit,
  output io_ControlBTBMissBubble,
  output io_TAGEMissBubble,
  output io_SCMissBubble,
  output io_ITTAGEMissBubble,
  output io_RASMissBubble,
  output [5:0] io_perf_0_value,
  output [5:0] io_perf_1_value,
  output [5:0] io_perf_2_value,
  output [5:0] io_perf_3_value,
  output [5:0] io_perf_4_value,
  output [5:0] io_perf_5_value,
  output [5:0] io_perf_6_value,
  output [5:0] io_perf_7_value,
  output [5:0] io_perf_8_value,
  output [5:0] io_perf_9_value,
  output [5:0] io_perf_10_value,
  output [5:0] io_perf_11_value,
  output [5:0] io_perf_12_value,
  output [5:0] io_perf_13_value,
  output [5:0] io_perf_14_value,
  output [5:0] io_perf_15_value,
  output [5:0] io_perf_16_value,
  output [5:0] io_perf_17_value,
  output [5:0] io_perf_18_value,
  output [5:0] io_perf_19_value,
  output [5:0] io_perf_20_value,
  output [5:0] io_perf_21_value,
  output [5:0] io_perf_22_value,
  output [5:0] io_perf_23_value,
  input  [6:0] boreChildrenBd_bore_array,
  input  boreChildrenBd_bore_all,
  input  boreChildrenBd_bore_req,
  output boreChildrenBd_bore_ack,
  input  boreChildrenBd_bore_writeen,
  input  boreChildrenBd_bore_be,
  input  [6:0] boreChildrenBd_bore_addr,
  input  [143:0] boreChildrenBd_bore_indata,
  input  boreChildrenBd_bore_readen,
  input  [6:0] boreChildrenBd_bore_addr_rd,
  output [143:0] boreChildrenBd_bore_outdata,
  input  sigFromSrams_bore_ram_hold,
  input  sigFromSrams_bore_ram_bypass,
  input  sigFromSrams_bore_ram_bp_clken,
  input  sigFromSrams_bore_ram_aux_clk,
  input  sigFromSrams_bore_ram_aux_ckbp,
  input  sigFromSrams_bore_ram_mcp_hold,
  input  sigFromSrams_bore_cgen,
  input  sigFromSrams_bore_1_ram_hold,
  input  sigFromSrams_bore_1_ram_bypass,
  input  sigFromSrams_bore_1_ram_bp_clken,
  input  sigFromSrams_bore_1_ram_aux_clk,
  input  sigFromSrams_bore_1_ram_aux_ckbp,
  input  sigFromSrams_bore_1_ram_mcp_hold,
  input  sigFromSrams_bore_1_cgen,
  input  sigFromSrams_bore_2_ram_hold,
  input  sigFromSrams_bore_2_ram_bypass,
  input  sigFromSrams_bore_2_ram_bp_clken,
  input  sigFromSrams_bore_2_ram_aux_clk,
  input  sigFromSrams_bore_2_ram_aux_ckbp,
  input  sigFromSrams_bore_2_ram_mcp_hold,
  input  sigFromSrams_bore_2_cgen,
  input  sigFromSrams_bore_3_ram_hold,
  input  sigFromSrams_bore_3_ram_bypass,
  input  sigFromSrams_bore_3_ram_bp_clken,
  input  sigFromSrams_bore_3_ram_aux_clk,
  input  sigFromSrams_bore_3_ram_aux_ckbp,
  input  sigFromSrams_bore_3_ram_mcp_hold,
  input  sigFromSrams_bore_3_cgen
);
  xs_Ftq_core u_core (
    .clock(clock),
    .reset(reset),
    .io_fromBpu_resp_ready(io_fromBpu_resp_ready),
    .io_fromBpu_resp_valid(io_fromBpu_resp_valid),
    .io_fromBpu_resp_bits_s1_pc_3(io_fromBpu_resp_bits_s1_pc_3),
    .io_fromBpu_resp_bits_s1_full_pred_0_predCycle(io_fromBpu_resp_bits_s1_full_pred_0_predCycle),
    .io_fromBpu_resp_bits_s1_full_pred_3_br_taken_mask_0(io_fromBpu_resp_bits_s1_full_pred_3_br_taken_mask_0),
    .io_fromBpu_resp_bits_s1_full_pred_3_br_taken_mask_1(io_fromBpu_resp_bits_s1_full_pred_3_br_taken_mask_1),
    .io_fromBpu_resp_bits_s1_full_pred_3_slot_valids_0(io_fromBpu_resp_bits_s1_full_pred_3_slot_valids_0),
    .io_fromBpu_resp_bits_s1_full_pred_3_slot_valids_1(io_fromBpu_resp_bits_s1_full_pred_3_slot_valids_1),
    .io_fromBpu_resp_bits_s1_full_pred_3_targets_0(io_fromBpu_resp_bits_s1_full_pred_3_targets_0),
    .io_fromBpu_resp_bits_s1_full_pred_3_targets_1(io_fromBpu_resp_bits_s1_full_pred_3_targets_1),
    .io_fromBpu_resp_bits_s1_full_pred_3_offsets_0(io_fromBpu_resp_bits_s1_full_pred_3_offsets_0),
    .io_fromBpu_resp_bits_s1_full_pred_3_offsets_1(io_fromBpu_resp_bits_s1_full_pred_3_offsets_1),
    .io_fromBpu_resp_bits_s1_full_pred_3_fallThroughAddr(io_fromBpu_resp_bits_s1_full_pred_3_fallThroughAddr),
    .io_fromBpu_resp_bits_s1_full_pred_3_fallThroughErr(io_fromBpu_resp_bits_s1_full_pred_3_fallThroughErr),
    .io_fromBpu_resp_bits_s1_full_pred_3_is_br_sharing(io_fromBpu_resp_bits_s1_full_pred_3_is_br_sharing),
    .io_fromBpu_resp_bits_s1_full_pred_3_hit(io_fromBpu_resp_bits_s1_full_pred_3_hit),
    .io_fromBpu_resp_bits_s2_pc_3(io_fromBpu_resp_bits_s2_pc_3),
    .io_fromBpu_resp_bits_s2_valid_3(io_fromBpu_resp_bits_s2_valid_3),
    .io_fromBpu_resp_bits_s2_hasRedirect_3(io_fromBpu_resp_bits_s2_hasRedirect_3),
    .io_fromBpu_resp_bits_s2_ftq_idx_flag(io_fromBpu_resp_bits_s2_ftq_idx_flag),
    .io_fromBpu_resp_bits_s2_ftq_idx_value(io_fromBpu_resp_bits_s2_ftq_idx_value),
    .io_fromBpu_resp_bits_s2_full_pred_0_predCycle(io_fromBpu_resp_bits_s2_full_pred_0_predCycle),
    .io_fromBpu_resp_bits_s2_full_pred_3_br_taken_mask_0(io_fromBpu_resp_bits_s2_full_pred_3_br_taken_mask_0),
    .io_fromBpu_resp_bits_s2_full_pred_3_br_taken_mask_1(io_fromBpu_resp_bits_s2_full_pred_3_br_taken_mask_1),
    .io_fromBpu_resp_bits_s2_full_pred_3_slot_valids_0(io_fromBpu_resp_bits_s2_full_pred_3_slot_valids_0),
    .io_fromBpu_resp_bits_s2_full_pred_3_slot_valids_1(io_fromBpu_resp_bits_s2_full_pred_3_slot_valids_1),
    .io_fromBpu_resp_bits_s2_full_pred_3_targets_0(io_fromBpu_resp_bits_s2_full_pred_3_targets_0),
    .io_fromBpu_resp_bits_s2_full_pred_3_targets_1(io_fromBpu_resp_bits_s2_full_pred_3_targets_1),
    .io_fromBpu_resp_bits_s2_full_pred_3_offsets_0(io_fromBpu_resp_bits_s2_full_pred_3_offsets_0),
    .io_fromBpu_resp_bits_s2_full_pred_3_offsets_1(io_fromBpu_resp_bits_s2_full_pred_3_offsets_1),
    .io_fromBpu_resp_bits_s2_full_pred_3_fallThroughAddr(io_fromBpu_resp_bits_s2_full_pred_3_fallThroughAddr),
    .io_fromBpu_resp_bits_s2_full_pred_3_fallThroughErr(io_fromBpu_resp_bits_s2_full_pred_3_fallThroughErr),
    .io_fromBpu_resp_bits_s2_full_pred_3_is_br_sharing(io_fromBpu_resp_bits_s2_full_pred_3_is_br_sharing),
    .io_fromBpu_resp_bits_s2_full_pred_3_hit(io_fromBpu_resp_bits_s2_full_pred_3_hit),
    .io_fromBpu_resp_bits_s3_pc_0(io_fromBpu_resp_bits_s3_pc_0),
    .io_fromBpu_resp_bits_s3_pc_3(io_fromBpu_resp_bits_s3_pc_3),
    .io_fromBpu_resp_bits_s3_valid_3(io_fromBpu_resp_bits_s3_valid_3),
    .io_fromBpu_resp_bits_s3_hasRedirect_3(io_fromBpu_resp_bits_s3_hasRedirect_3),
    .io_fromBpu_resp_bits_s3_ftq_idx_flag(io_fromBpu_resp_bits_s3_ftq_idx_flag),
    .io_fromBpu_resp_bits_s3_ftq_idx_value(io_fromBpu_resp_bits_s3_ftq_idx_value),
    .io_fromBpu_resp_bits_s3_full_pred_0_predCycle(io_fromBpu_resp_bits_s3_full_pred_0_predCycle),
    .io_fromBpu_resp_bits_s3_full_pred_3_br_taken_mask_0(io_fromBpu_resp_bits_s3_full_pred_3_br_taken_mask_0),
    .io_fromBpu_resp_bits_s3_full_pred_3_br_taken_mask_1(io_fromBpu_resp_bits_s3_full_pred_3_br_taken_mask_1),
    .io_fromBpu_resp_bits_s3_full_pred_3_slot_valids_0(io_fromBpu_resp_bits_s3_full_pred_3_slot_valids_0),
    .io_fromBpu_resp_bits_s3_full_pred_3_slot_valids_1(io_fromBpu_resp_bits_s3_full_pred_3_slot_valids_1),
    .io_fromBpu_resp_bits_s3_full_pred_3_targets_0(io_fromBpu_resp_bits_s3_full_pred_3_targets_0),
    .io_fromBpu_resp_bits_s3_full_pred_3_targets_1(io_fromBpu_resp_bits_s3_full_pred_3_targets_1),
    .io_fromBpu_resp_bits_s3_full_pred_3_offsets_0(io_fromBpu_resp_bits_s3_full_pred_3_offsets_0),
    .io_fromBpu_resp_bits_s3_full_pred_3_offsets_1(io_fromBpu_resp_bits_s3_full_pred_3_offsets_1),
    .io_fromBpu_resp_bits_s3_full_pred_3_fallThroughAddr(io_fromBpu_resp_bits_s3_full_pred_3_fallThroughAddr),
    .io_fromBpu_resp_bits_s3_full_pred_3_fallThroughErr(io_fromBpu_resp_bits_s3_full_pred_3_fallThroughErr),
    .io_fromBpu_resp_bits_s3_full_pred_3_is_br_sharing(io_fromBpu_resp_bits_s3_full_pred_3_is_br_sharing),
    .io_fromBpu_resp_bits_s3_full_pred_3_hit(io_fromBpu_resp_bits_s3_full_pred_3_hit),
    .io_fromBpu_resp_bits_last_stage_meta(io_fromBpu_resp_bits_last_stage_meta),
    .io_fromBpu_resp_bits_last_stage_spec_info_histPtr_flag(io_fromBpu_resp_bits_last_stage_spec_info_histPtr_flag),
    .io_fromBpu_resp_bits_last_stage_spec_info_histPtr_value(io_fromBpu_resp_bits_last_stage_spec_info_histPtr_value),
    .io_fromBpu_resp_bits_last_stage_spec_info_ssp(io_fromBpu_resp_bits_last_stage_spec_info_ssp),
    .io_fromBpu_resp_bits_last_stage_spec_info_sctr(io_fromBpu_resp_bits_last_stage_spec_info_sctr),
    .io_fromBpu_resp_bits_last_stage_spec_info_TOSW_flag(io_fromBpu_resp_bits_last_stage_spec_info_TOSW_flag),
    .io_fromBpu_resp_bits_last_stage_spec_info_TOSW_value(io_fromBpu_resp_bits_last_stage_spec_info_TOSW_value),
    .io_fromBpu_resp_bits_last_stage_spec_info_TOSR_flag(io_fromBpu_resp_bits_last_stage_spec_info_TOSR_flag),
    .io_fromBpu_resp_bits_last_stage_spec_info_TOSR_value(io_fromBpu_resp_bits_last_stage_spec_info_TOSR_value),
    .io_fromBpu_resp_bits_last_stage_spec_info_NOS_flag(io_fromBpu_resp_bits_last_stage_spec_info_NOS_flag),
    .io_fromBpu_resp_bits_last_stage_spec_info_NOS_value(io_fromBpu_resp_bits_last_stage_spec_info_NOS_value),
    .io_fromBpu_resp_bits_last_stage_spec_info_topAddr(io_fromBpu_resp_bits_last_stage_spec_info_topAddr),
    .io_fromBpu_resp_bits_last_stage_spec_info_sc_disagree_0(io_fromBpu_resp_bits_last_stage_spec_info_sc_disagree_0),
    .io_fromBpu_resp_bits_last_stage_spec_info_sc_disagree_1(io_fromBpu_resp_bits_last_stage_spec_info_sc_disagree_1),
    .io_fromBpu_resp_bits_last_stage_ftb_entry_isCall(io_fromBpu_resp_bits_last_stage_ftb_entry_isCall),
    .io_fromBpu_resp_bits_last_stage_ftb_entry_isRet(io_fromBpu_resp_bits_last_stage_ftb_entry_isRet),
    .io_fromBpu_resp_bits_last_stage_ftb_entry_isJalr(io_fromBpu_resp_bits_last_stage_ftb_entry_isJalr),
    .io_fromBpu_resp_bits_last_stage_ftb_entry_valid(io_fromBpu_resp_bits_last_stage_ftb_entry_valid),
    .io_fromBpu_resp_bits_last_stage_ftb_entry_brSlots_0_offset(io_fromBpu_resp_bits_last_stage_ftb_entry_brSlots_0_offset),
    .io_fromBpu_resp_bits_last_stage_ftb_entry_brSlots_0_sharing(io_fromBpu_resp_bits_last_stage_ftb_entry_brSlots_0_sharing),
    .io_fromBpu_resp_bits_last_stage_ftb_entry_brSlots_0_valid(io_fromBpu_resp_bits_last_stage_ftb_entry_brSlots_0_valid),
    .io_fromBpu_resp_bits_last_stage_ftb_entry_brSlots_0_lower(io_fromBpu_resp_bits_last_stage_ftb_entry_brSlots_0_lower),
    .io_fromBpu_resp_bits_last_stage_ftb_entry_brSlots_0_tarStat(io_fromBpu_resp_bits_last_stage_ftb_entry_brSlots_0_tarStat),
    .io_fromBpu_resp_bits_last_stage_ftb_entry_tailSlot_offset(io_fromBpu_resp_bits_last_stage_ftb_entry_tailSlot_offset),
    .io_fromBpu_resp_bits_last_stage_ftb_entry_tailSlot_sharing(io_fromBpu_resp_bits_last_stage_ftb_entry_tailSlot_sharing),
    .io_fromBpu_resp_bits_last_stage_ftb_entry_tailSlot_valid(io_fromBpu_resp_bits_last_stage_ftb_entry_tailSlot_valid),
    .io_fromBpu_resp_bits_last_stage_ftb_entry_tailSlot_lower(io_fromBpu_resp_bits_last_stage_ftb_entry_tailSlot_lower),
    .io_fromBpu_resp_bits_last_stage_ftb_entry_tailSlot_tarStat(io_fromBpu_resp_bits_last_stage_ftb_entry_tailSlot_tarStat),
    .io_fromBpu_resp_bits_last_stage_ftb_entry_pftAddr(io_fromBpu_resp_bits_last_stage_ftb_entry_pftAddr),
    .io_fromBpu_resp_bits_last_stage_ftb_entry_carry(io_fromBpu_resp_bits_last_stage_ftb_entry_carry),
    .io_fromBpu_resp_bits_last_stage_ftb_entry_last_may_be_rvi_call(io_fromBpu_resp_bits_last_stage_ftb_entry_last_may_be_rvi_call),
    .io_fromBpu_resp_bits_last_stage_ftb_entry_strong_bias_0(io_fromBpu_resp_bits_last_stage_ftb_entry_strong_bias_0),
    .io_fromBpu_resp_bits_last_stage_ftb_entry_strong_bias_1(io_fromBpu_resp_bits_last_stage_ftb_entry_strong_bias_1),
    .io_fromBpu_resp_bits_topdown_info_reasons_1(io_fromBpu_resp_bits_topdown_info_reasons_1),
    .io_fromBpu_resp_bits_topdown_info_reasons_2(io_fromBpu_resp_bits_topdown_info_reasons_2),
    .io_fromBpu_resp_bits_topdown_info_reasons_3(io_fromBpu_resp_bits_topdown_info_reasons_3),
    .io_fromBpu_resp_bits_topdown_info_reasons_4(io_fromBpu_resp_bits_topdown_info_reasons_4),
    .io_fromBpu_resp_bits_topdown_info_reasons_5(io_fromBpu_resp_bits_topdown_info_reasons_5),
    .io_fromBpu_resp_bits_topdown_info_reasons_6(io_fromBpu_resp_bits_topdown_info_reasons_6),
    .io_fromBpu_resp_bits_topdown_info_reasons_7(io_fromBpu_resp_bits_topdown_info_reasons_7),
    .io_fromBpu_resp_bits_topdown_info_reasons_8(io_fromBpu_resp_bits_topdown_info_reasons_8),
    .io_fromBpu_resp_bits_topdown_info_reasons_9(io_fromBpu_resp_bits_topdown_info_reasons_9),
    .io_fromBpu_resp_bits_topdown_info_reasons_12(io_fromBpu_resp_bits_topdown_info_reasons_12),
    .io_fromIfu_pdWb_valid(io_fromIfu_pdWb_valid),
    .io_fromIfu_pdWb_bits_pc_0(io_fromIfu_pdWb_bits_pc_0),
    .io_fromIfu_pdWb_bits_pc_1(io_fromIfu_pdWb_bits_pc_1),
    .io_fromIfu_pdWb_bits_pc_2(io_fromIfu_pdWb_bits_pc_2),
    .io_fromIfu_pdWb_bits_pc_3(io_fromIfu_pdWb_bits_pc_3),
    .io_fromIfu_pdWb_bits_pc_4(io_fromIfu_pdWb_bits_pc_4),
    .io_fromIfu_pdWb_bits_pc_5(io_fromIfu_pdWb_bits_pc_5),
    .io_fromIfu_pdWb_bits_pc_6(io_fromIfu_pdWb_bits_pc_6),
    .io_fromIfu_pdWb_bits_pc_7(io_fromIfu_pdWb_bits_pc_7),
    .io_fromIfu_pdWb_bits_pc_8(io_fromIfu_pdWb_bits_pc_8),
    .io_fromIfu_pdWb_bits_pc_9(io_fromIfu_pdWb_bits_pc_9),
    .io_fromIfu_pdWb_bits_pc_10(io_fromIfu_pdWb_bits_pc_10),
    .io_fromIfu_pdWb_bits_pc_11(io_fromIfu_pdWb_bits_pc_11),
    .io_fromIfu_pdWb_bits_pc_12(io_fromIfu_pdWb_bits_pc_12),
    .io_fromIfu_pdWb_bits_pc_13(io_fromIfu_pdWb_bits_pc_13),
    .io_fromIfu_pdWb_bits_pc_14(io_fromIfu_pdWb_bits_pc_14),
    .io_fromIfu_pdWb_bits_pc_15(io_fromIfu_pdWb_bits_pc_15),
    .io_fromIfu_pdWb_bits_pd_0_valid(io_fromIfu_pdWb_bits_pd_0_valid),
    .io_fromIfu_pdWb_bits_pd_0_isRVC(io_fromIfu_pdWb_bits_pd_0_isRVC),
    .io_fromIfu_pdWb_bits_pd_0_brType(io_fromIfu_pdWb_bits_pd_0_brType),
    .io_fromIfu_pdWb_bits_pd_0_isCall(io_fromIfu_pdWb_bits_pd_0_isCall),
    .io_fromIfu_pdWb_bits_pd_0_isRet(io_fromIfu_pdWb_bits_pd_0_isRet),
    .io_fromIfu_pdWb_bits_pd_1_valid(io_fromIfu_pdWb_bits_pd_1_valid),
    .io_fromIfu_pdWb_bits_pd_1_isRVC(io_fromIfu_pdWb_bits_pd_1_isRVC),
    .io_fromIfu_pdWb_bits_pd_1_brType(io_fromIfu_pdWb_bits_pd_1_brType),
    .io_fromIfu_pdWb_bits_pd_1_isCall(io_fromIfu_pdWb_bits_pd_1_isCall),
    .io_fromIfu_pdWb_bits_pd_1_isRet(io_fromIfu_pdWb_bits_pd_1_isRet),
    .io_fromIfu_pdWb_bits_pd_2_valid(io_fromIfu_pdWb_bits_pd_2_valid),
    .io_fromIfu_pdWb_bits_pd_2_isRVC(io_fromIfu_pdWb_bits_pd_2_isRVC),
    .io_fromIfu_pdWb_bits_pd_2_brType(io_fromIfu_pdWb_bits_pd_2_brType),
    .io_fromIfu_pdWb_bits_pd_2_isCall(io_fromIfu_pdWb_bits_pd_2_isCall),
    .io_fromIfu_pdWb_bits_pd_2_isRet(io_fromIfu_pdWb_bits_pd_2_isRet),
    .io_fromIfu_pdWb_bits_pd_3_valid(io_fromIfu_pdWb_bits_pd_3_valid),
    .io_fromIfu_pdWb_bits_pd_3_isRVC(io_fromIfu_pdWb_bits_pd_3_isRVC),
    .io_fromIfu_pdWb_bits_pd_3_brType(io_fromIfu_pdWb_bits_pd_3_brType),
    .io_fromIfu_pdWb_bits_pd_3_isCall(io_fromIfu_pdWb_bits_pd_3_isCall),
    .io_fromIfu_pdWb_bits_pd_3_isRet(io_fromIfu_pdWb_bits_pd_3_isRet),
    .io_fromIfu_pdWb_bits_pd_4_valid(io_fromIfu_pdWb_bits_pd_4_valid),
    .io_fromIfu_pdWb_bits_pd_4_isRVC(io_fromIfu_pdWb_bits_pd_4_isRVC),
    .io_fromIfu_pdWb_bits_pd_4_brType(io_fromIfu_pdWb_bits_pd_4_brType),
    .io_fromIfu_pdWb_bits_pd_4_isCall(io_fromIfu_pdWb_bits_pd_4_isCall),
    .io_fromIfu_pdWb_bits_pd_4_isRet(io_fromIfu_pdWb_bits_pd_4_isRet),
    .io_fromIfu_pdWb_bits_pd_5_valid(io_fromIfu_pdWb_bits_pd_5_valid),
    .io_fromIfu_pdWb_bits_pd_5_isRVC(io_fromIfu_pdWb_bits_pd_5_isRVC),
    .io_fromIfu_pdWb_bits_pd_5_brType(io_fromIfu_pdWb_bits_pd_5_brType),
    .io_fromIfu_pdWb_bits_pd_5_isCall(io_fromIfu_pdWb_bits_pd_5_isCall),
    .io_fromIfu_pdWb_bits_pd_5_isRet(io_fromIfu_pdWb_bits_pd_5_isRet),
    .io_fromIfu_pdWb_bits_pd_6_valid(io_fromIfu_pdWb_bits_pd_6_valid),
    .io_fromIfu_pdWb_bits_pd_6_isRVC(io_fromIfu_pdWb_bits_pd_6_isRVC),
    .io_fromIfu_pdWb_bits_pd_6_brType(io_fromIfu_pdWb_bits_pd_6_brType),
    .io_fromIfu_pdWb_bits_pd_6_isCall(io_fromIfu_pdWb_bits_pd_6_isCall),
    .io_fromIfu_pdWb_bits_pd_6_isRet(io_fromIfu_pdWb_bits_pd_6_isRet),
    .io_fromIfu_pdWb_bits_pd_7_valid(io_fromIfu_pdWb_bits_pd_7_valid),
    .io_fromIfu_pdWb_bits_pd_7_isRVC(io_fromIfu_pdWb_bits_pd_7_isRVC),
    .io_fromIfu_pdWb_bits_pd_7_brType(io_fromIfu_pdWb_bits_pd_7_brType),
    .io_fromIfu_pdWb_bits_pd_7_isCall(io_fromIfu_pdWb_bits_pd_7_isCall),
    .io_fromIfu_pdWb_bits_pd_7_isRet(io_fromIfu_pdWb_bits_pd_7_isRet),
    .io_fromIfu_pdWb_bits_pd_8_valid(io_fromIfu_pdWb_bits_pd_8_valid),
    .io_fromIfu_pdWb_bits_pd_8_isRVC(io_fromIfu_pdWb_bits_pd_8_isRVC),
    .io_fromIfu_pdWb_bits_pd_8_brType(io_fromIfu_pdWb_bits_pd_8_brType),
    .io_fromIfu_pdWb_bits_pd_8_isCall(io_fromIfu_pdWb_bits_pd_8_isCall),
    .io_fromIfu_pdWb_bits_pd_8_isRet(io_fromIfu_pdWb_bits_pd_8_isRet),
    .io_fromIfu_pdWb_bits_pd_9_valid(io_fromIfu_pdWb_bits_pd_9_valid),
    .io_fromIfu_pdWb_bits_pd_9_isRVC(io_fromIfu_pdWb_bits_pd_9_isRVC),
    .io_fromIfu_pdWb_bits_pd_9_brType(io_fromIfu_pdWb_bits_pd_9_brType),
    .io_fromIfu_pdWb_bits_pd_9_isCall(io_fromIfu_pdWb_bits_pd_9_isCall),
    .io_fromIfu_pdWb_bits_pd_9_isRet(io_fromIfu_pdWb_bits_pd_9_isRet),
    .io_fromIfu_pdWb_bits_pd_10_valid(io_fromIfu_pdWb_bits_pd_10_valid),
    .io_fromIfu_pdWb_bits_pd_10_isRVC(io_fromIfu_pdWb_bits_pd_10_isRVC),
    .io_fromIfu_pdWb_bits_pd_10_brType(io_fromIfu_pdWb_bits_pd_10_brType),
    .io_fromIfu_pdWb_bits_pd_10_isCall(io_fromIfu_pdWb_bits_pd_10_isCall),
    .io_fromIfu_pdWb_bits_pd_10_isRet(io_fromIfu_pdWb_bits_pd_10_isRet),
    .io_fromIfu_pdWb_bits_pd_11_valid(io_fromIfu_pdWb_bits_pd_11_valid),
    .io_fromIfu_pdWb_bits_pd_11_isRVC(io_fromIfu_pdWb_bits_pd_11_isRVC),
    .io_fromIfu_pdWb_bits_pd_11_brType(io_fromIfu_pdWb_bits_pd_11_brType),
    .io_fromIfu_pdWb_bits_pd_11_isCall(io_fromIfu_pdWb_bits_pd_11_isCall),
    .io_fromIfu_pdWb_bits_pd_11_isRet(io_fromIfu_pdWb_bits_pd_11_isRet),
    .io_fromIfu_pdWb_bits_pd_12_valid(io_fromIfu_pdWb_bits_pd_12_valid),
    .io_fromIfu_pdWb_bits_pd_12_isRVC(io_fromIfu_pdWb_bits_pd_12_isRVC),
    .io_fromIfu_pdWb_bits_pd_12_brType(io_fromIfu_pdWb_bits_pd_12_brType),
    .io_fromIfu_pdWb_bits_pd_12_isCall(io_fromIfu_pdWb_bits_pd_12_isCall),
    .io_fromIfu_pdWb_bits_pd_12_isRet(io_fromIfu_pdWb_bits_pd_12_isRet),
    .io_fromIfu_pdWb_bits_pd_13_valid(io_fromIfu_pdWb_bits_pd_13_valid),
    .io_fromIfu_pdWb_bits_pd_13_isRVC(io_fromIfu_pdWb_bits_pd_13_isRVC),
    .io_fromIfu_pdWb_bits_pd_13_brType(io_fromIfu_pdWb_bits_pd_13_brType),
    .io_fromIfu_pdWb_bits_pd_13_isCall(io_fromIfu_pdWb_bits_pd_13_isCall),
    .io_fromIfu_pdWb_bits_pd_13_isRet(io_fromIfu_pdWb_bits_pd_13_isRet),
    .io_fromIfu_pdWb_bits_pd_14_valid(io_fromIfu_pdWb_bits_pd_14_valid),
    .io_fromIfu_pdWb_bits_pd_14_isRVC(io_fromIfu_pdWb_bits_pd_14_isRVC),
    .io_fromIfu_pdWb_bits_pd_14_brType(io_fromIfu_pdWb_bits_pd_14_brType),
    .io_fromIfu_pdWb_bits_pd_14_isCall(io_fromIfu_pdWb_bits_pd_14_isCall),
    .io_fromIfu_pdWb_bits_pd_14_isRet(io_fromIfu_pdWb_bits_pd_14_isRet),
    .io_fromIfu_pdWb_bits_pd_15_valid(io_fromIfu_pdWb_bits_pd_15_valid),
    .io_fromIfu_pdWb_bits_pd_15_isRVC(io_fromIfu_pdWb_bits_pd_15_isRVC),
    .io_fromIfu_pdWb_bits_pd_15_brType(io_fromIfu_pdWb_bits_pd_15_brType),
    .io_fromIfu_pdWb_bits_pd_15_isCall(io_fromIfu_pdWb_bits_pd_15_isCall),
    .io_fromIfu_pdWb_bits_pd_15_isRet(io_fromIfu_pdWb_bits_pd_15_isRet),
    .io_fromIfu_pdWb_bits_ftqIdx_flag(io_fromIfu_pdWb_bits_ftqIdx_flag),
    .io_fromIfu_pdWb_bits_ftqIdx_value(io_fromIfu_pdWb_bits_ftqIdx_value),
    .io_fromIfu_pdWb_bits_misOffset_valid(io_fromIfu_pdWb_bits_misOffset_valid),
    .io_fromIfu_pdWb_bits_misOffset_bits(io_fromIfu_pdWb_bits_misOffset_bits),
    .io_fromIfu_pdWb_bits_cfiOffset_valid(io_fromIfu_pdWb_bits_cfiOffset_valid),
    .io_fromIfu_pdWb_bits_target(io_fromIfu_pdWb_bits_target),
    .io_fromIfu_pdWb_bits_jalTarget(io_fromIfu_pdWb_bits_jalTarget),
    .io_fromIfu_pdWb_bits_instrRange_0(io_fromIfu_pdWb_bits_instrRange_0),
    .io_fromIfu_pdWb_bits_instrRange_1(io_fromIfu_pdWb_bits_instrRange_1),
    .io_fromIfu_pdWb_bits_instrRange_2(io_fromIfu_pdWb_bits_instrRange_2),
    .io_fromIfu_pdWb_bits_instrRange_3(io_fromIfu_pdWb_bits_instrRange_3),
    .io_fromIfu_pdWb_bits_instrRange_4(io_fromIfu_pdWb_bits_instrRange_4),
    .io_fromIfu_pdWb_bits_instrRange_5(io_fromIfu_pdWb_bits_instrRange_5),
    .io_fromIfu_pdWb_bits_instrRange_6(io_fromIfu_pdWb_bits_instrRange_6),
    .io_fromIfu_pdWb_bits_instrRange_7(io_fromIfu_pdWb_bits_instrRange_7),
    .io_fromIfu_pdWb_bits_instrRange_8(io_fromIfu_pdWb_bits_instrRange_8),
    .io_fromIfu_pdWb_bits_instrRange_9(io_fromIfu_pdWb_bits_instrRange_9),
    .io_fromIfu_pdWb_bits_instrRange_10(io_fromIfu_pdWb_bits_instrRange_10),
    .io_fromIfu_pdWb_bits_instrRange_11(io_fromIfu_pdWb_bits_instrRange_11),
    .io_fromIfu_pdWb_bits_instrRange_12(io_fromIfu_pdWb_bits_instrRange_12),
    .io_fromIfu_pdWb_bits_instrRange_13(io_fromIfu_pdWb_bits_instrRange_13),
    .io_fromIfu_pdWb_bits_instrRange_14(io_fromIfu_pdWb_bits_instrRange_14),
    .io_fromIfu_pdWb_bits_instrRange_15(io_fromIfu_pdWb_bits_instrRange_15),
    .io_fromBackend_rob_commits_0_valid(io_fromBackend_rob_commits_0_valid),
    .io_fromBackend_rob_commits_0_bits_commitType(io_fromBackend_rob_commits_0_bits_commitType),
    .io_fromBackend_rob_commits_0_bits_ftqIdx_flag(io_fromBackend_rob_commits_0_bits_ftqIdx_flag),
    .io_fromBackend_rob_commits_0_bits_ftqIdx_value(io_fromBackend_rob_commits_0_bits_ftqIdx_value),
    .io_fromBackend_rob_commits_0_bits_ftqOffset(io_fromBackend_rob_commits_0_bits_ftqOffset),
    .io_fromBackend_rob_commits_1_valid(io_fromBackend_rob_commits_1_valid),
    .io_fromBackend_rob_commits_1_bits_commitType(io_fromBackend_rob_commits_1_bits_commitType),
    .io_fromBackend_rob_commits_1_bits_ftqIdx_flag(io_fromBackend_rob_commits_1_bits_ftqIdx_flag),
    .io_fromBackend_rob_commits_1_bits_ftqIdx_value(io_fromBackend_rob_commits_1_bits_ftqIdx_value),
    .io_fromBackend_rob_commits_1_bits_ftqOffset(io_fromBackend_rob_commits_1_bits_ftqOffset),
    .io_fromBackend_rob_commits_2_valid(io_fromBackend_rob_commits_2_valid),
    .io_fromBackend_rob_commits_2_bits_commitType(io_fromBackend_rob_commits_2_bits_commitType),
    .io_fromBackend_rob_commits_2_bits_ftqIdx_flag(io_fromBackend_rob_commits_2_bits_ftqIdx_flag),
    .io_fromBackend_rob_commits_2_bits_ftqIdx_value(io_fromBackend_rob_commits_2_bits_ftqIdx_value),
    .io_fromBackend_rob_commits_2_bits_ftqOffset(io_fromBackend_rob_commits_2_bits_ftqOffset),
    .io_fromBackend_rob_commits_3_valid(io_fromBackend_rob_commits_3_valid),
    .io_fromBackend_rob_commits_3_bits_commitType(io_fromBackend_rob_commits_3_bits_commitType),
    .io_fromBackend_rob_commits_3_bits_ftqIdx_flag(io_fromBackend_rob_commits_3_bits_ftqIdx_flag),
    .io_fromBackend_rob_commits_3_bits_ftqIdx_value(io_fromBackend_rob_commits_3_bits_ftqIdx_value),
    .io_fromBackend_rob_commits_3_bits_ftqOffset(io_fromBackend_rob_commits_3_bits_ftqOffset),
    .io_fromBackend_rob_commits_4_valid(io_fromBackend_rob_commits_4_valid),
    .io_fromBackend_rob_commits_4_bits_commitType(io_fromBackend_rob_commits_4_bits_commitType),
    .io_fromBackend_rob_commits_4_bits_ftqIdx_flag(io_fromBackend_rob_commits_4_bits_ftqIdx_flag),
    .io_fromBackend_rob_commits_4_bits_ftqIdx_value(io_fromBackend_rob_commits_4_bits_ftqIdx_value),
    .io_fromBackend_rob_commits_4_bits_ftqOffset(io_fromBackend_rob_commits_4_bits_ftqOffset),
    .io_fromBackend_rob_commits_5_valid(io_fromBackend_rob_commits_5_valid),
    .io_fromBackend_rob_commits_5_bits_commitType(io_fromBackend_rob_commits_5_bits_commitType),
    .io_fromBackend_rob_commits_5_bits_ftqIdx_flag(io_fromBackend_rob_commits_5_bits_ftqIdx_flag),
    .io_fromBackend_rob_commits_5_bits_ftqIdx_value(io_fromBackend_rob_commits_5_bits_ftqIdx_value),
    .io_fromBackend_rob_commits_5_bits_ftqOffset(io_fromBackend_rob_commits_5_bits_ftqOffset),
    .io_fromBackend_rob_commits_6_valid(io_fromBackend_rob_commits_6_valid),
    .io_fromBackend_rob_commits_6_bits_commitType(io_fromBackend_rob_commits_6_bits_commitType),
    .io_fromBackend_rob_commits_6_bits_ftqIdx_flag(io_fromBackend_rob_commits_6_bits_ftqIdx_flag),
    .io_fromBackend_rob_commits_6_bits_ftqIdx_value(io_fromBackend_rob_commits_6_bits_ftqIdx_value),
    .io_fromBackend_rob_commits_6_bits_ftqOffset(io_fromBackend_rob_commits_6_bits_ftqOffset),
    .io_fromBackend_rob_commits_7_valid(io_fromBackend_rob_commits_7_valid),
    .io_fromBackend_rob_commits_7_bits_commitType(io_fromBackend_rob_commits_7_bits_commitType),
    .io_fromBackend_rob_commits_7_bits_ftqIdx_flag(io_fromBackend_rob_commits_7_bits_ftqIdx_flag),
    .io_fromBackend_rob_commits_7_bits_ftqIdx_value(io_fromBackend_rob_commits_7_bits_ftqIdx_value),
    .io_fromBackend_rob_commits_7_bits_ftqOffset(io_fromBackend_rob_commits_7_bits_ftqOffset),
    .io_fromBackend_redirect_valid(io_fromBackend_redirect_valid),
    .io_fromBackend_redirect_bits_ftqIdx_flag(io_fromBackend_redirect_bits_ftqIdx_flag),
    .io_fromBackend_redirect_bits_ftqIdx_value(io_fromBackend_redirect_bits_ftqIdx_value),
    .io_fromBackend_redirect_bits_ftqOffset(io_fromBackend_redirect_bits_ftqOffset),
    .io_fromBackend_redirect_bits_level(io_fromBackend_redirect_bits_level),
    .io_fromBackend_redirect_bits_cfiUpdate_pc(io_fromBackend_redirect_bits_cfiUpdate_pc),
    .io_fromBackend_redirect_bits_cfiUpdate_target(io_fromBackend_redirect_bits_cfiUpdate_target),
    .io_fromBackend_redirect_bits_cfiUpdate_taken(io_fromBackend_redirect_bits_cfiUpdate_taken),
    .io_fromBackend_redirect_bits_cfiUpdate_isMisPred(io_fromBackend_redirect_bits_cfiUpdate_isMisPred),
    .io_fromBackend_redirect_bits_cfiUpdate_backendIGPF(io_fromBackend_redirect_bits_cfiUpdate_backendIGPF),
    .io_fromBackend_redirect_bits_cfiUpdate_backendIPF(io_fromBackend_redirect_bits_cfiUpdate_backendIPF),
    .io_fromBackend_redirect_bits_cfiUpdate_backendIAF(io_fromBackend_redirect_bits_cfiUpdate_backendIAF),
    .io_fromBackend_redirect_bits_debugIsCtrl(io_fromBackend_redirect_bits_debugIsCtrl),
    .io_fromBackend_redirect_bits_debugIsMemVio(io_fromBackend_redirect_bits_debugIsMemVio),
    .io_fromBackend_ftqIdxAhead_0_valid(io_fromBackend_ftqIdxAhead_0_valid),
    .io_fromBackend_ftqIdxAhead_0_bits_value(io_fromBackend_ftqIdxAhead_0_bits_value),
    .io_fromBackend_ftqIdxSelOH_bits(io_fromBackend_ftqIdxSelOH_bits),
    .io_toBpu_redirect_valid(io_toBpu_redirect_valid),
    .io_toBpu_redirect_bits_level(io_toBpu_redirect_bits_level),
    .io_toBpu_redirect_bits_cfiUpdate_pc(io_toBpu_redirect_bits_cfiUpdate_pc),
    .io_toBpu_redirect_bits_cfiUpdate_pd_valid(io_toBpu_redirect_bits_cfiUpdate_pd_valid),
    .io_toBpu_redirect_bits_cfiUpdate_pd_isRVC(io_toBpu_redirect_bits_cfiUpdate_pd_isRVC),
    .io_toBpu_redirect_bits_cfiUpdate_pd_isCall(io_toBpu_redirect_bits_cfiUpdate_pd_isCall),
    .io_toBpu_redirect_bits_cfiUpdate_pd_isRet(io_toBpu_redirect_bits_cfiUpdate_pd_isRet),
    .io_toBpu_redirect_bits_cfiUpdate_ssp(io_toBpu_redirect_bits_cfiUpdate_ssp),
    .io_toBpu_redirect_bits_cfiUpdate_sctr(io_toBpu_redirect_bits_cfiUpdate_sctr),
    .io_toBpu_redirect_bits_cfiUpdate_TOSW_flag(io_toBpu_redirect_bits_cfiUpdate_TOSW_flag),
    .io_toBpu_redirect_bits_cfiUpdate_TOSW_value(io_toBpu_redirect_bits_cfiUpdate_TOSW_value),
    .io_toBpu_redirect_bits_cfiUpdate_TOSR_flag(io_toBpu_redirect_bits_cfiUpdate_TOSR_flag),
    .io_toBpu_redirect_bits_cfiUpdate_TOSR_value(io_toBpu_redirect_bits_cfiUpdate_TOSR_value),
    .io_toBpu_redirect_bits_cfiUpdate_NOS_flag(io_toBpu_redirect_bits_cfiUpdate_NOS_flag),
    .io_toBpu_redirect_bits_cfiUpdate_NOS_value(io_toBpu_redirect_bits_cfiUpdate_NOS_value),
    .io_toBpu_redirect_bits_cfiUpdate_histPtr_flag(io_toBpu_redirect_bits_cfiUpdate_histPtr_flag),
    .io_toBpu_redirect_bits_cfiUpdate_histPtr_value(io_toBpu_redirect_bits_cfiUpdate_histPtr_value),
    .io_toBpu_redirect_bits_cfiUpdate_br_hit(io_toBpu_redirect_bits_cfiUpdate_br_hit),
    .io_toBpu_redirect_bits_cfiUpdate_jr_hit(io_toBpu_redirect_bits_cfiUpdate_jr_hit),
    .io_toBpu_redirect_bits_cfiUpdate_sc_hit(io_toBpu_redirect_bits_cfiUpdate_sc_hit),
    .io_toBpu_redirect_bits_cfiUpdate_target(io_toBpu_redirect_bits_cfiUpdate_target),
    .io_toBpu_redirect_bits_cfiUpdate_taken(io_toBpu_redirect_bits_cfiUpdate_taken),
    .io_toBpu_redirect_bits_cfiUpdate_shift(io_toBpu_redirect_bits_cfiUpdate_shift),
    .io_toBpu_redirect_bits_cfiUpdate_addIntoHist(io_toBpu_redirect_bits_cfiUpdate_addIntoHist),
    .io_toBpu_redirect_bits_debugIsCtrl(io_toBpu_redirect_bits_debugIsCtrl),
    .io_toBpu_redirect_bits_debugIsMemVio(io_toBpu_redirect_bits_debugIsMemVio),
    .io_toBpu_redirect_bits_BTBMissBubble(io_toBpu_redirect_bits_BTBMissBubble),
    .io_toBpu_update_valid(io_toBpu_update_valid),
    .io_toBpu_update_bits_pc(io_toBpu_update_bits_pc),
    .io_toBpu_update_bits_spec_info_histPtr_value(io_toBpu_update_bits_spec_info_histPtr_value),
    .io_toBpu_update_bits_ftb_entry_isCall(io_toBpu_update_bits_ftb_entry_isCall),
    .io_toBpu_update_bits_ftb_entry_isRet(io_toBpu_update_bits_ftb_entry_isRet),
    .io_toBpu_update_bits_ftb_entry_isJalr(io_toBpu_update_bits_ftb_entry_isJalr),
    .io_toBpu_update_bits_ftb_entry_valid(io_toBpu_update_bits_ftb_entry_valid),
    .io_toBpu_update_bits_ftb_entry_brSlots_0_offset(io_toBpu_update_bits_ftb_entry_brSlots_0_offset),
    .io_toBpu_update_bits_ftb_entry_brSlots_0_sharing(io_toBpu_update_bits_ftb_entry_brSlots_0_sharing),
    .io_toBpu_update_bits_ftb_entry_brSlots_0_valid(io_toBpu_update_bits_ftb_entry_brSlots_0_valid),
    .io_toBpu_update_bits_ftb_entry_brSlots_0_lower(io_toBpu_update_bits_ftb_entry_brSlots_0_lower),
    .io_toBpu_update_bits_ftb_entry_brSlots_0_tarStat(io_toBpu_update_bits_ftb_entry_brSlots_0_tarStat),
    .io_toBpu_update_bits_ftb_entry_tailSlot_offset(io_toBpu_update_bits_ftb_entry_tailSlot_offset),
    .io_toBpu_update_bits_ftb_entry_tailSlot_sharing(io_toBpu_update_bits_ftb_entry_tailSlot_sharing),
    .io_toBpu_update_bits_ftb_entry_tailSlot_valid(io_toBpu_update_bits_ftb_entry_tailSlot_valid),
    .io_toBpu_update_bits_ftb_entry_tailSlot_lower(io_toBpu_update_bits_ftb_entry_tailSlot_lower),
    .io_toBpu_update_bits_ftb_entry_tailSlot_tarStat(io_toBpu_update_bits_ftb_entry_tailSlot_tarStat),
    .io_toBpu_update_bits_ftb_entry_pftAddr(io_toBpu_update_bits_ftb_entry_pftAddr),
    .io_toBpu_update_bits_ftb_entry_carry(io_toBpu_update_bits_ftb_entry_carry),
    .io_toBpu_update_bits_ftb_entry_last_may_be_rvi_call(io_toBpu_update_bits_ftb_entry_last_may_be_rvi_call),
    .io_toBpu_update_bits_ftb_entry_strong_bias_0(io_toBpu_update_bits_ftb_entry_strong_bias_0),
    .io_toBpu_update_bits_ftb_entry_strong_bias_1(io_toBpu_update_bits_ftb_entry_strong_bias_1),
    .io_toBpu_update_bits_cfi_idx_valid(io_toBpu_update_bits_cfi_idx_valid),
    .io_toBpu_update_bits_cfi_idx_bits(io_toBpu_update_bits_cfi_idx_bits),
    .io_toBpu_update_bits_br_taken_mask_0(io_toBpu_update_bits_br_taken_mask_0),
    .io_toBpu_update_bits_br_taken_mask_1(io_toBpu_update_bits_br_taken_mask_1),
    .io_toBpu_update_bits_jmp_taken(io_toBpu_update_bits_jmp_taken),
    .io_toBpu_update_bits_mispred_mask_0(io_toBpu_update_bits_mispred_mask_0),
    .io_toBpu_update_bits_mispred_mask_1(io_toBpu_update_bits_mispred_mask_1),
    .io_toBpu_update_bits_mispred_mask_2(io_toBpu_update_bits_mispred_mask_2),
    .io_toBpu_update_bits_false_hit(io_toBpu_update_bits_false_hit),
    .io_toBpu_update_bits_old_entry(io_toBpu_update_bits_old_entry),
    .io_toBpu_update_bits_meta(io_toBpu_update_bits_meta),
    .io_toBpu_update_bits_full_target(io_toBpu_update_bits_full_target),
    .io_toBpu_enq_ptr_flag(io_toBpu_enq_ptr_flag),
    .io_toBpu_enq_ptr_value(io_toBpu_enq_ptr_value),
    .io_toBpu_redirctFromIFU(io_toBpu_redirctFromIFU),
    .io_toIfu_req_ready(io_toIfu_req_ready),
    .io_toIfu_req_valid(io_toIfu_req_valid),
    .io_toIfu_req_bits_startAddr(io_toIfu_req_bits_startAddr),
    .io_toIfu_req_bits_nextlineStart(io_toIfu_req_bits_nextlineStart),
    .io_toIfu_req_bits_nextStartAddr(io_toIfu_req_bits_nextStartAddr),
    .io_toIfu_req_bits_ftqIdx_flag(io_toIfu_req_bits_ftqIdx_flag),
    .io_toIfu_req_bits_ftqIdx_value(io_toIfu_req_bits_ftqIdx_value),
    .io_toIfu_req_bits_ftqOffset_valid(io_toIfu_req_bits_ftqOffset_valid),
    .io_toIfu_req_bits_ftqOffset_bits(io_toIfu_req_bits_ftqOffset_bits),
    .io_toIfu_req_bits_topdown_info_reasons_0(io_toIfu_req_bits_topdown_info_reasons_0),
    .io_toIfu_req_bits_topdown_info_reasons_1(io_toIfu_req_bits_topdown_info_reasons_1),
    .io_toIfu_req_bits_topdown_info_reasons_2(io_toIfu_req_bits_topdown_info_reasons_2),
    .io_toIfu_req_bits_topdown_info_reasons_3(io_toIfu_req_bits_topdown_info_reasons_3),
    .io_toIfu_req_bits_topdown_info_reasons_4(io_toIfu_req_bits_topdown_info_reasons_4),
    .io_toIfu_req_bits_topdown_info_reasons_5(io_toIfu_req_bits_topdown_info_reasons_5),
    .io_toIfu_req_bits_topdown_info_reasons_6(io_toIfu_req_bits_topdown_info_reasons_6),
    .io_toIfu_req_bits_topdown_info_reasons_7(io_toIfu_req_bits_topdown_info_reasons_7),
    .io_toIfu_req_bits_topdown_info_reasons_8(io_toIfu_req_bits_topdown_info_reasons_8),
    .io_toIfu_req_bits_topdown_info_reasons_9(io_toIfu_req_bits_topdown_info_reasons_9),
    .io_toIfu_req_bits_topdown_info_reasons_10(io_toIfu_req_bits_topdown_info_reasons_10),
    .io_toIfu_req_bits_topdown_info_reasons_11(io_toIfu_req_bits_topdown_info_reasons_11),
    .io_toIfu_req_bits_topdown_info_reasons_12(io_toIfu_req_bits_topdown_info_reasons_12),
    .io_toIfu_req_bits_topdown_info_reasons_13(io_toIfu_req_bits_topdown_info_reasons_13),
    .io_toIfu_req_bits_topdown_info_reasons_14(io_toIfu_req_bits_topdown_info_reasons_14),
    .io_toIfu_req_bits_topdown_info_reasons_15(io_toIfu_req_bits_topdown_info_reasons_15),
    .io_toIfu_req_bits_topdown_info_reasons_16(io_toIfu_req_bits_topdown_info_reasons_16),
    .io_toIfu_req_bits_topdown_info_reasons_17(io_toIfu_req_bits_topdown_info_reasons_17),
    .io_toIfu_req_bits_topdown_info_reasons_18(io_toIfu_req_bits_topdown_info_reasons_18),
    .io_toIfu_req_bits_topdown_info_reasons_19(io_toIfu_req_bits_topdown_info_reasons_19),
    .io_toIfu_req_bits_topdown_info_reasons_20(io_toIfu_req_bits_topdown_info_reasons_20),
    .io_toIfu_req_bits_topdown_info_reasons_21(io_toIfu_req_bits_topdown_info_reasons_21),
    .io_toIfu_req_bits_topdown_info_reasons_22(io_toIfu_req_bits_topdown_info_reasons_22),
    .io_toIfu_req_bits_topdown_info_reasons_23(io_toIfu_req_bits_topdown_info_reasons_23),
    .io_toIfu_req_bits_topdown_info_reasons_24(io_toIfu_req_bits_topdown_info_reasons_24),
    .io_toIfu_req_bits_topdown_info_reasons_25(io_toIfu_req_bits_topdown_info_reasons_25),
    .io_toIfu_req_bits_topdown_info_reasons_26(io_toIfu_req_bits_topdown_info_reasons_26),
    .io_toIfu_req_bits_topdown_info_reasons_27(io_toIfu_req_bits_topdown_info_reasons_27),
    .io_toIfu_req_bits_topdown_info_reasons_28(io_toIfu_req_bits_topdown_info_reasons_28),
    .io_toIfu_req_bits_topdown_info_reasons_29(io_toIfu_req_bits_topdown_info_reasons_29),
    .io_toIfu_req_bits_topdown_info_reasons_30(io_toIfu_req_bits_topdown_info_reasons_30),
    .io_toIfu_req_bits_topdown_info_reasons_31(io_toIfu_req_bits_topdown_info_reasons_31),
    .io_toIfu_req_bits_topdown_info_reasons_32(io_toIfu_req_bits_topdown_info_reasons_32),
    .io_toIfu_req_bits_topdown_info_reasons_33(io_toIfu_req_bits_topdown_info_reasons_33),
    .io_toIfu_req_bits_topdown_info_reasons_34(io_toIfu_req_bits_topdown_info_reasons_34),
    .io_toIfu_req_bits_topdown_info_reasons_35(io_toIfu_req_bits_topdown_info_reasons_35),
    .io_toIfu_req_bits_topdown_info_reasons_36(io_toIfu_req_bits_topdown_info_reasons_36),
    .io_toIfu_req_bits_topdown_info_reasons_37(io_toIfu_req_bits_topdown_info_reasons_37),
    .io_toIfu_redirect_valid(io_toIfu_redirect_valid),
    .io_toIfu_redirect_bits_ftqIdx_flag(io_toIfu_redirect_bits_ftqIdx_flag),
    .io_toIfu_redirect_bits_ftqIdx_value(io_toIfu_redirect_bits_ftqIdx_value),
    .io_toIfu_redirect_bits_ftqOffset(io_toIfu_redirect_bits_ftqOffset),
    .io_toIfu_redirect_bits_level(io_toIfu_redirect_bits_level),
    .io_toIfu_topdown_redirect_valid(io_toIfu_topdown_redirect_valid),
    .io_toIfu_topdown_redirect_bits_cfiUpdate_pd_isRet(io_toIfu_topdown_redirect_bits_cfiUpdate_pd_isRet),
    .io_toIfu_topdown_redirect_bits_cfiUpdate_br_hit(io_toIfu_topdown_redirect_bits_cfiUpdate_br_hit),
    .io_toIfu_topdown_redirect_bits_cfiUpdate_jr_hit(io_toIfu_topdown_redirect_bits_cfiUpdate_jr_hit),
    .io_toIfu_topdown_redirect_bits_cfiUpdate_sc_hit(io_toIfu_topdown_redirect_bits_cfiUpdate_sc_hit),
    .io_toIfu_topdown_redirect_bits_debugIsCtrl(io_toIfu_topdown_redirect_bits_debugIsCtrl),
    .io_toIfu_topdown_redirect_bits_debugIsMemVio(io_toIfu_topdown_redirect_bits_debugIsMemVio),
    .io_toIfu_flushFromBpu_s2_valid(io_toIfu_flushFromBpu_s2_valid),
    .io_toIfu_flushFromBpu_s2_bits_flag(io_toIfu_flushFromBpu_s2_bits_flag),
    .io_toIfu_flushFromBpu_s2_bits_value(io_toIfu_flushFromBpu_s2_bits_value),
    .io_toIfu_flushFromBpu_s3_valid(io_toIfu_flushFromBpu_s3_valid),
    .io_toIfu_flushFromBpu_s3_bits_flag(io_toIfu_flushFromBpu_s3_bits_flag),
    .io_toIfu_flushFromBpu_s3_bits_value(io_toIfu_flushFromBpu_s3_bits_value),
    .io_toICache_req_valid(io_toICache_req_valid),
    .io_toICache_req_bits_pcMemRead_0_startAddr(io_toICache_req_bits_pcMemRead_0_startAddr),
    .io_toICache_req_bits_pcMemRead_0_nextlineStart(io_toICache_req_bits_pcMemRead_0_nextlineStart),
    .io_toICache_req_bits_pcMemRead_1_startAddr(io_toICache_req_bits_pcMemRead_1_startAddr),
    .io_toICache_req_bits_pcMemRead_1_nextlineStart(io_toICache_req_bits_pcMemRead_1_nextlineStart),
    .io_toICache_req_bits_pcMemRead_2_startAddr(io_toICache_req_bits_pcMemRead_2_startAddr),
    .io_toICache_req_bits_pcMemRead_2_nextlineStart(io_toICache_req_bits_pcMemRead_2_nextlineStart),
    .io_toICache_req_bits_pcMemRead_3_startAddr(io_toICache_req_bits_pcMemRead_3_startAddr),
    .io_toICache_req_bits_pcMemRead_3_nextlineStart(io_toICache_req_bits_pcMemRead_3_nextlineStart),
    .io_toICache_req_bits_pcMemRead_4_startAddr(io_toICache_req_bits_pcMemRead_4_startAddr),
    .io_toICache_req_bits_pcMemRead_4_nextlineStart(io_toICache_req_bits_pcMemRead_4_nextlineStart),
    .io_toICache_req_bits_readValid_0(io_toICache_req_bits_readValid_0),
    .io_toICache_req_bits_readValid_1(io_toICache_req_bits_readValid_1),
    .io_toICache_req_bits_readValid_2(io_toICache_req_bits_readValid_2),
    .io_toICache_req_bits_readValid_3(io_toICache_req_bits_readValid_3),
    .io_toICache_req_bits_readValid_4(io_toICache_req_bits_readValid_4),
    .io_toICache_req_bits_backendException(io_toICache_req_bits_backendException),
    .io_toBackend_pc_mem_wen(io_toBackend_pc_mem_wen),
    .io_toBackend_pc_mem_waddr(io_toBackend_pc_mem_waddr),
    .io_toBackend_pc_mem_wdata_startAddr(io_toBackend_pc_mem_wdata_startAddr),
    .io_toBackend_newest_entry_en(io_toBackend_newest_entry_en),
    .io_toBackend_newest_entry_target(io_toBackend_newest_entry_target),
    .io_toBackend_newest_entry_ptr_value(io_toBackend_newest_entry_ptr_value),
    .io_toPrefetch_req_ready(io_toPrefetch_req_ready),
    .io_toPrefetch_req_valid(io_toPrefetch_req_valid),
    .io_toPrefetch_req_bits_startAddr(io_toPrefetch_req_bits_startAddr),
    .io_toPrefetch_req_bits_nextlineStart(io_toPrefetch_req_bits_nextlineStart),
    .io_toPrefetch_req_bits_ftqIdx_flag(io_toPrefetch_req_bits_ftqIdx_flag),
    .io_toPrefetch_req_bits_ftqIdx_value(io_toPrefetch_req_bits_ftqIdx_value),
    .io_toPrefetch_flushFromBpu_s2_valid(io_toPrefetch_flushFromBpu_s2_valid),
    .io_toPrefetch_flushFromBpu_s2_bits_flag(io_toPrefetch_flushFromBpu_s2_bits_flag),
    .io_toPrefetch_flushFromBpu_s2_bits_value(io_toPrefetch_flushFromBpu_s2_bits_value),
    .io_toPrefetch_flushFromBpu_s3_valid(io_toPrefetch_flushFromBpu_s3_valid),
    .io_toPrefetch_flushFromBpu_s3_bits_flag(io_toPrefetch_flushFromBpu_s3_bits_flag),
    .io_toPrefetch_flushFromBpu_s3_bits_value(io_toPrefetch_flushFromBpu_s3_bits_value),
    .io_toPrefetch_backendException(io_toPrefetch_backendException),
    .io_icacheFlush(io_icacheFlush),
    .io_mmioCommitRead_mmioFtqPtr_flag(io_mmioCommitRead_mmioFtqPtr_flag),
    .io_mmioCommitRead_mmioFtqPtr_value(io_mmioCommitRead_mmioFtqPtr_value),
    .io_mmioCommitRead_mmioLastCommit(io_mmioCommitRead_mmioLastCommit),
    .io_ControlBTBMissBubble(io_ControlBTBMissBubble),
    .io_TAGEMissBubble(io_TAGEMissBubble),
    .io_SCMissBubble(io_SCMissBubble),
    .io_ITTAGEMissBubble(io_ITTAGEMissBubble),
    .io_RASMissBubble(io_RASMissBubble),
    .io_perf_0_value(io_perf_0_value),
    .io_perf_1_value(io_perf_1_value),
    .io_perf_2_value(io_perf_2_value),
    .io_perf_3_value(io_perf_3_value),
    .io_perf_4_value(io_perf_4_value),
    .io_perf_5_value(io_perf_5_value),
    .io_perf_6_value(io_perf_6_value),
    .io_perf_7_value(io_perf_7_value),
    .io_perf_8_value(io_perf_8_value),
    .io_perf_9_value(io_perf_9_value),
    .io_perf_10_value(io_perf_10_value),
    .io_perf_11_value(io_perf_11_value),
    .io_perf_12_value(io_perf_12_value),
    .io_perf_13_value(io_perf_13_value),
    .io_perf_14_value(io_perf_14_value),
    .io_perf_15_value(io_perf_15_value),
    .io_perf_16_value(io_perf_16_value),
    .io_perf_17_value(io_perf_17_value),
    .io_perf_18_value(io_perf_18_value),
    .io_perf_19_value(io_perf_19_value),
    .io_perf_20_value(io_perf_20_value),
    .io_perf_21_value(io_perf_21_value),
    .io_perf_22_value(io_perf_22_value),
    .io_perf_23_value(io_perf_23_value),
    .boreChildrenBd_bore_array(boreChildrenBd_bore_array),
    .boreChildrenBd_bore_all(boreChildrenBd_bore_all),
    .boreChildrenBd_bore_req(boreChildrenBd_bore_req),
    .boreChildrenBd_bore_ack(boreChildrenBd_bore_ack),
    .boreChildrenBd_bore_writeen(boreChildrenBd_bore_writeen),
    .boreChildrenBd_bore_be(boreChildrenBd_bore_be),
    .boreChildrenBd_bore_addr(boreChildrenBd_bore_addr),
    .boreChildrenBd_bore_indata(boreChildrenBd_bore_indata),
    .boreChildrenBd_bore_readen(boreChildrenBd_bore_readen),
    .boreChildrenBd_bore_addr_rd(boreChildrenBd_bore_addr_rd),
    .boreChildrenBd_bore_outdata(boreChildrenBd_bore_outdata),
    .sigFromSrams_bore_ram_hold(sigFromSrams_bore_ram_hold),
    .sigFromSrams_bore_ram_bypass(sigFromSrams_bore_ram_bypass),
    .sigFromSrams_bore_ram_bp_clken(sigFromSrams_bore_ram_bp_clken),
    .sigFromSrams_bore_ram_aux_clk(sigFromSrams_bore_ram_aux_clk),
    .sigFromSrams_bore_ram_aux_ckbp(sigFromSrams_bore_ram_aux_ckbp),
    .sigFromSrams_bore_ram_mcp_hold(sigFromSrams_bore_ram_mcp_hold),
    .sigFromSrams_bore_cgen(sigFromSrams_bore_cgen),
    .sigFromSrams_bore_1_ram_hold(sigFromSrams_bore_1_ram_hold),
    .sigFromSrams_bore_1_ram_bypass(sigFromSrams_bore_1_ram_bypass),
    .sigFromSrams_bore_1_ram_bp_clken(sigFromSrams_bore_1_ram_bp_clken),
    .sigFromSrams_bore_1_ram_aux_clk(sigFromSrams_bore_1_ram_aux_clk),
    .sigFromSrams_bore_1_ram_aux_ckbp(sigFromSrams_bore_1_ram_aux_ckbp),
    .sigFromSrams_bore_1_ram_mcp_hold(sigFromSrams_bore_1_ram_mcp_hold),
    .sigFromSrams_bore_1_cgen(sigFromSrams_bore_1_cgen),
    .sigFromSrams_bore_2_ram_hold(sigFromSrams_bore_2_ram_hold),
    .sigFromSrams_bore_2_ram_bypass(sigFromSrams_bore_2_ram_bypass),
    .sigFromSrams_bore_2_ram_bp_clken(sigFromSrams_bore_2_ram_bp_clken),
    .sigFromSrams_bore_2_ram_aux_clk(sigFromSrams_bore_2_ram_aux_clk),
    .sigFromSrams_bore_2_ram_aux_ckbp(sigFromSrams_bore_2_ram_aux_ckbp),
    .sigFromSrams_bore_2_ram_mcp_hold(sigFromSrams_bore_2_ram_mcp_hold),
    .sigFromSrams_bore_2_cgen(sigFromSrams_bore_2_cgen),
    .sigFromSrams_bore_3_ram_hold(sigFromSrams_bore_3_ram_hold),
    .sigFromSrams_bore_3_ram_bypass(sigFromSrams_bore_3_ram_bypass),
    .sigFromSrams_bore_3_ram_bp_clken(sigFromSrams_bore_3_ram_bp_clken),
    .sigFromSrams_bore_3_ram_aux_clk(sigFromSrams_bore_3_ram_aux_clk),
    .sigFromSrams_bore_3_ram_aux_ckbp(sigFromSrams_bore_3_ram_aux_ckbp),
    .sigFromSrams_bore_3_ram_mcp_hold(sigFromSrams_bore_3_ram_mcp_hold),
    .sigFromSrams_bore_3_cgen(sigFromSrams_bore_3_cgen)
  );
endmodule
