// Generated by scripts/gen_frontendtrigger.py — do not hand-edit.
//
// xs_FrontendTrigger_core — readable faithful (bug-for-bug) core for golden
// FrontendTrigger (前端硬件断点/触发器: 4 个 tdata 触发器 × 16 取指 lane 的
// PC 匹配 + 链式触发 + action 译码)。
//
// 结构(golden firtool 单模块, 0 子模块 0 mem, 异步 reset):
//   REG:  tdataVec_0..3_{matchType,select,timing,action,chain,tdata2} —— tUpdate
//         按 addr 写入(timing 无更新位: 写入即清 0, 否则保持);
//         triggerEnableVec_0..3 逐拍采样 tEnableVec。
//   COMB: hit[j][i] = 触发器 j 在 lane i 的 PC 匹配(matchType: 3=less,
//         2=greater-equal, 0=equal, 1=保留不命中)。50 位比较拆成 高位块
//         pc[49:5](lane 跨 32B 半行时用块号+1)+低 5 位 —— 仅 lane0 的 PC 参与
//         高位比较, 其余 lane 用 bit5 翻转(laneCarry)选块号/块号+1;
//         canFire[i][j] = 链式发射资格(链中段不发射, 链尾需前驱命中+timing 一致);
//         io_triggered_i = 最低可发射触发器 action 译码(0=断点异常须
//         triggerCanRaiseBpExp, 1=进 debug, 否则 F=未触发)。
//
// RENAME 映射(golden → 本核, 其余 golden 具名 wire/reg 逐字保留):
//   _GEN/_GEN_0/_GEN_1/_GEN_2                → tdataWen[j] (tUpdate 命中触发器 j)
//   _triggerHitVec_highPC1_T_1/_3/_5/_7      → pcHigh1(4 份相同加法, 合 1 净)
//   triggerHitVec_highPC{Equal,Greater,Less}[_j]/highPC1* → highEq/highGt/highLt[j] 等
//   triggerHitVec_carry_[j_]i                → laneCarry[i] (与触发器无关, 合 1 净)
//   triggerHitVec_lowPC{Equal,Less}_[j_]i    → g_hit_t[j].g_hit_l[i].lowEq/lowLt
//   _triggerHitVec_overallGreater_i_T_*      → g_hit_t[j].g_hit_l[i].lowGe(保留冗余 equal|>=)
//   _triggerHitVec_ret_15_T*(matchType 译码) → (&matchTypeQ[j]) / ==2'h2 / ==2'h0 内联
//   triggerHitVec_<i>_<j>                    → hit[j][i]
//   triggerCanFireVec_[i_]j / _hasTriggerFire_T_<i> → canFire[i][j] / hasFire
//   triggerFireOH_enc_<i> + triggerFireAction_<i>   → fireAction(等价优先 mux 折叠)
// 寄存器集逐字保留; 唯一收窄 tdata2: 64b → [49:0](见文件头)。
module xs_FrontendTrigger_core(
  input          clock,
  input          reset,
  input          io_frontendTrigger_tUpdate_valid,
  input  [1:0]   io_frontendTrigger_tUpdate_bits_addr,
  input  [1:0]   io_frontendTrigger_tUpdate_bits_tdata_matchType,
  input          io_frontendTrigger_tUpdate_bits_tdata_select,
  input  [3:0]   io_frontendTrigger_tUpdate_bits_tdata_action,
  input          io_frontendTrigger_tUpdate_bits_tdata_chain,
  input  [63:0]  io_frontendTrigger_tUpdate_bits_tdata_tdata2,
  input          io_frontendTrigger_tEnableVec_0,
  input          io_frontendTrigger_tEnableVec_1,
  input          io_frontendTrigger_tEnableVec_2,
  input          io_frontendTrigger_tEnableVec_3,
  input          io_frontendTrigger_debugMode,
  input          io_frontendTrigger_triggerCanRaiseBpExp,
  output [3:0]   io_triggered_0,
  output [3:0]   io_triggered_1,
  output [3:0]   io_triggered_2,
  output [3:0]   io_triggered_3,
  output [3:0]   io_triggered_4,
  output [3:0]   io_triggered_5,
  output [3:0]   io_triggered_6,
  output [3:0]   io_triggered_7,
  output [3:0]   io_triggered_8,
  output [3:0]   io_triggered_9,
  output [3:0]   io_triggered_10,
  output [3:0]   io_triggered_11,
  output [3:0]   io_triggered_12,
  output [3:0]   io_triggered_13,
  output [3:0]   io_triggered_14,
  output [3:0]   io_triggered_15,
  input  [49:0]  io_pc_0,
  input  [49:0]  io_pc_1,
  input  [49:0]  io_pc_2,
  input  [49:0]  io_pc_3,
  input  [49:0]  io_pc_4,
  input  [49:0]  io_pc_5,
  input  [49:0]  io_pc_6,
  input  [49:0]  io_pc_7,
  input  [49:0]  io_pc_8,
  input  [49:0]  io_pc_9,
  input  [49:0]  io_pc_10,
  input  [49:0]  io_pc_11,
  input  [49:0]  io_pc_12,
  input  [49:0]  io_pc_13,
  input  [49:0]  io_pc_14,
  input  [49:0]  io_pc_15
);

  localparam int PW = 16;   // PredictWidth (取指 lane 数)
  localparam int NT = 4;   // 前端触发器数

  // ---------------- 寄存器集(golden 名逐字保留) ----------------
  reg  [1:0]  tdataVec_0_matchType;
  reg         tdataVec_0_select;
  reg         tdataVec_0_timing;
  reg  [3:0]  tdataVec_0_action;
  reg         tdataVec_0_chain;
  reg  [49:0] tdataVec_0_tdata2;
  reg  [1:0]  tdataVec_1_matchType;
  reg         tdataVec_1_select;
  reg         tdataVec_1_timing;
  reg  [3:0]  tdataVec_1_action;
  reg         tdataVec_1_chain;
  reg  [49:0] tdataVec_1_tdata2;
  reg  [1:0]  tdataVec_2_matchType;
  reg         tdataVec_2_select;
  reg         tdataVec_2_timing;
  reg  [3:0]  tdataVec_2_action;
  reg         tdataVec_2_chain;
  reg  [49:0] tdataVec_2_tdata2;
  reg  [1:0]  tdataVec_3_matchType;
  reg         tdataVec_3_select;
  reg         tdataVec_3_timing;
  reg  [3:0]  tdataVec_3_action;
  reg         tdataVec_3_chain;
  reg  [49:0] tdataVec_3_tdata2;
  reg         triggerEnableVec_0;
  reg         triggerEnableVec_1;
  reg         triggerEnableVec_2;
  reg         triggerEnableVec_3;

  // tdataWen[j]: tUpdate 命中触发器 j
  wire [NT-1:0] tdataWen;
  genvar i, j;
  generate
    for (j = 0; j < NT; j = j + 1) begin : g_wen
      assign tdataWen[j] = io_frontendTrigger_tUpdate_valid
                         & (io_frontendTrigger_tUpdate_bits_addr == j);
    end
  endgenerate

  always @(posedge clock or posedge reset) begin
    if (reset) begin
      tdataVec_0_matchType <= 2'h0;
      tdataVec_0_select <= 1'h0;
      tdataVec_0_timing <= 1'h0;
      tdataVec_0_action <= 4'h0;
      tdataVec_0_chain <= 1'h0;
      tdataVec_0_tdata2 <= 50'h0;
      tdataVec_1_matchType <= 2'h0;
      tdataVec_1_select <= 1'h0;
      tdataVec_1_timing <= 1'h0;
      tdataVec_1_action <= 4'h0;
      tdataVec_1_chain <= 1'h0;
      tdataVec_1_tdata2 <= 50'h0;
      tdataVec_2_matchType <= 2'h0;
      tdataVec_2_select <= 1'h0;
      tdataVec_2_timing <= 1'h0;
      tdataVec_2_action <= 4'h0;
      tdataVec_2_chain <= 1'h0;
      tdataVec_2_tdata2 <= 50'h0;
      tdataVec_3_matchType <= 2'h0;
      tdataVec_3_select <= 1'h0;
      tdataVec_3_timing <= 1'h0;
      tdataVec_3_action <= 4'h0;
      tdataVec_3_chain <= 1'h0;
      tdataVec_3_tdata2 <= 50'h0;
      triggerEnableVec_0 <= 1'h0;
      triggerEnableVec_1 <= 1'h0;
      triggerEnableVec_2 <= 1'h0;
      triggerEnableVec_3 <= 1'h0;
    end
    else begin
      if (tdataWen[0]) begin
        tdataVec_0_matchType <= io_frontendTrigger_tUpdate_bits_tdata_matchType;
        tdataVec_0_select <= io_frontendTrigger_tUpdate_bits_tdata_select;
        tdataVec_0_action <= io_frontendTrigger_tUpdate_bits_tdata_action;
        tdataVec_0_chain <= io_frontendTrigger_tUpdate_bits_tdata_chain;
        tdataVec_0_tdata2 <= io_frontendTrigger_tUpdate_bits_tdata_tdata2[49:0];
      end
      // tdata1 更新不带 timing 位: 写入即清 0, 否则保持
      tdataVec_0_timing <= ~tdataWen[0] & tdataVec_0_timing;
      if (tdataWen[1]) begin
        tdataVec_1_matchType <= io_frontendTrigger_tUpdate_bits_tdata_matchType;
        tdataVec_1_select <= io_frontendTrigger_tUpdate_bits_tdata_select;
        tdataVec_1_action <= io_frontendTrigger_tUpdate_bits_tdata_action;
        tdataVec_1_chain <= io_frontendTrigger_tUpdate_bits_tdata_chain;
        tdataVec_1_tdata2 <= io_frontendTrigger_tUpdate_bits_tdata_tdata2[49:0];
      end
      // tdata1 更新不带 timing 位: 写入即清 0, 否则保持
      tdataVec_1_timing <= ~tdataWen[1] & tdataVec_1_timing;
      if (tdataWen[2]) begin
        tdataVec_2_matchType <= io_frontendTrigger_tUpdate_bits_tdata_matchType;
        tdataVec_2_select <= io_frontendTrigger_tUpdate_bits_tdata_select;
        tdataVec_2_action <= io_frontendTrigger_tUpdate_bits_tdata_action;
        tdataVec_2_chain <= io_frontendTrigger_tUpdate_bits_tdata_chain;
        tdataVec_2_tdata2 <= io_frontendTrigger_tUpdate_bits_tdata_tdata2[49:0];
      end
      // tdata1 更新不带 timing 位: 写入即清 0, 否则保持
      tdataVec_2_timing <= ~tdataWen[2] & tdataVec_2_timing;
      if (tdataWen[3]) begin
        tdataVec_3_matchType <= io_frontendTrigger_tUpdate_bits_tdata_matchType;
        tdataVec_3_select <= io_frontendTrigger_tUpdate_bits_tdata_select;
        tdataVec_3_action <= io_frontendTrigger_tUpdate_bits_tdata_action;
        tdataVec_3_chain <= io_frontendTrigger_tUpdate_bits_tdata_chain;
        tdataVec_3_tdata2 <= io_frontendTrigger_tUpdate_bits_tdata_tdata2[49:0];
      end
      // tdata1 更新不带 timing 位: 写入即清 0, 否则保持
      tdataVec_3_timing <= ~tdataWen[3] & tdataVec_3_timing;
      triggerEnableVec_0 <= io_frontendTrigger_tEnableVec_0;
      triggerEnableVec_1 <= io_frontendTrigger_tEnableVec_1;
      triggerEnableVec_2 <= io_frontendTrigger_tEnableVec_2;
      triggerEnableVec_3 <= io_frontendTrigger_tEnableVec_3;
    end
  end

  // ---------------- 数组视图(机械 扁平->数组 打包) ----------------
  wire [1:0]  matchTypeQ [0:NT-1];
  wire [3:0]  actionQ    [0:NT-1];
  wire [49:0] tdata2Q    [0:NT-1];
  assign matchTypeQ[0] = tdataVec_0_matchType;
  assign matchTypeQ[1] = tdataVec_1_matchType;
  assign matchTypeQ[2] = tdataVec_2_matchType;
  assign matchTypeQ[3] = tdataVec_3_matchType;
  assign actionQ[0] = tdataVec_0_action;
  assign actionQ[1] = tdataVec_1_action;
  assign actionQ[2] = tdataVec_2_action;
  assign actionQ[3] = tdataVec_3_action;
  assign tdata2Q[0] = tdataVec_0_tdata2;
  assign tdata2Q[1] = tdataVec_1_tdata2;
  assign tdata2Q[2] = tdataVec_2_tdata2;
  assign tdata2Q[3] = tdataVec_3_tdata2;
  wire [NT-1:0] selectQ = {tdataVec_3_select, tdataVec_2_select, tdataVec_1_select, tdataVec_0_select};
  wire [NT-1:0] timingQ = {tdataVec_3_timing, tdataVec_2_timing, tdataVec_1_timing, tdataVec_0_timing};
  wire [NT-1:0] chainQ = {tdataVec_3_chain, tdataVec_2_chain, tdataVec_1_chain, tdataVec_0_chain};
  wire [NT-1:0] enableQ = {triggerEnableVec_3, triggerEnableVec_2, triggerEnableVec_1, triggerEnableVec_0};
  wire [49:0] pcVec [0:PW-1];
  assign pcVec[0] = io_pc_0;
  assign pcVec[1] = io_pc_1;
  assign pcVec[2] = io_pc_2;
  assign pcVec[3] = io_pc_3;
  assign pcVec[4] = io_pc_4;
  assign pcVec[5] = io_pc_5;
  assign pcVec[6] = io_pc_6;
  assign pcVec[7] = io_pc_7;
  assign pcVec[8] = io_pc_8;
  assign pcVec[9] = io_pc_9;
  assign pcVec[10] = io_pc_10;
  assign pcVec[11] = io_pc_11;
  assign pcVec[12] = io_pc_12;
  assign pcVec[13] = io_pc_13;
  assign pcVec[14] = io_pc_14;
  assign pcVec[15] = io_pc_15;

  // ---------------- PC 高位块 / lane 进位 ----------------
  wire [44:0] pcHigh  = pcVec[0][49:5];             // 32B 半行块号(仅 lane0 参与)
  wire [44:0] pcHigh1 = 45'(pcVec[0][49:5] + 45'h1); // lane 跨半行进位后的块号
  // laneCarry[i]: lane 相对 lane0 跨入下一半行(bit5 翻转; lane0 恒 0 —— golden
  // 直接省略 lane0 的 carry 路径, 常量折叠一致)
  wire [PW-1:0] laneCarry;
  generate
    for (i = 0; i < PW; i = i + 1) begin : g_carry
      assign laneCarry[i] = pcVec[i][5] != pcVec[0][5];
    end
  endgenerate

  wire [NT-1:0] highEq, highEq1, highGt, highGt1, highLt, highLt1;
  generate
    for (j = 0; j < NT; j = j + 1) begin : g_high
      assign highEq[j]  = pcHigh  == tdata2Q[j][49:5];
      assign highEq1[j] = pcHigh1 == tdata2Q[j][49:5];
      assign highGt[j]  = pcHigh  >  tdata2Q[j][49:5];
      assign highGt1[j] = pcHigh1 >  tdata2Q[j][49:5];
      assign highLt[j]  = pcHigh  <  tdata2Q[j][49:5];
      assign highLt1[j] = pcHigh1 <  tdata2Q[j][49:5];
    end
  endgenerate

  // ---------------- hit[j][i]: 触发器 j 在 lane i 的 PC 匹配 ----------------
  wire [PW-1:0] hit [0:NT-1];
  generate
    for (j = 0; j < NT; j = j + 1) begin : g_hit_t
      for (i = 0; i < PW; i = i + 1) begin : g_hit_l
        wire lowEq = pcVec[i][4:0] == tdata2Q[j][4:0];
        wire lowLt = pcVec[i][4:0] <  tdata2Q[j][4:0];
        wire lowGe = lowEq | (pcVec[i][4:0] >= tdata2Q[j][4:0]);  // golden 冗余保留
        assign hit[j][i] =
          ((&matchTypeQ[j])
             ? ~laneCarry[i] & (highLt[j] | highEq[j] & lowLt)
               | laneCarry[i] & (highLt1[j] | highEq1[j] & lowLt)
             : (matchTypeQ[j] == 2'h2)
                 ? ~laneCarry[i] & (highGt[j] | highEq[j] & lowGe)
                   | laneCarry[i] & (highGt1[j] | highEq1[j] & lowGe)
                 : (matchTypeQ[j] == 2'h0)
                   & (~laneCarry[i] & highEq[j] & lowEq
                      | laneCarry[i] & highEq1[j] & lowEq))
          & enableQ[j] & ~selectQ[j] & ~io_frontendTrigger_debugMode;
      end
    end
  endgenerate

  // ---------------- 链式发射 + action 译码 ----------------
  // trigger2TimingSameVec(golden 名保留): 相邻触发器 timing 一致才可续链
  wire trigger2TimingSameVec_1 = tdataVec_0_timing == tdataVec_1_timing;
  wire trigger2TimingSameVec_2 = tdataVec_1_timing == tdataVec_2_timing;
  wire trigger2TimingSameVec_3 = tdataVec_2_timing == tdataVec_3_timing;
  wire [NT-1:0] timingSame = {trigger2TimingSameVec_3, trigger2TimingSameVec_2,
                              trigger2TimingSameVec_1, 1'b1};

  wire [NT-1:0] canFire [0:PW-1];
  wire [3:0] triggeredVec [0:PW-1];
  generate
    for (i = 0; i < PW; i = i + 1) begin : g_fire
      // 触发器 0 无前驱: 命中且自身非链中段即可发射
      assign canFire[i][0] = hit[0][i] & ~chainQ[0];
      for (j = 1; j < NT; j = j + 1) begin : g_chain
        assign canFire[i][j] =
          (chainQ[j-1] & hit[j-1][i] | ~chainQ[j-1])
          & (chainQ[j-1] & ~chainQ[j] & timingSame[j] | ~chainQ[j-1])
          & hit[j][i] & ~chainQ[j];
      end
      wire hasFire = |canFire[i];
      // 最低可发射触发器的 action(无可发射时缺省 actionQ[3], 被 hasFire 门控)
      wire [3:0] fireAction = canFire[i][0] ? actionQ[0]
                            : canFire[i][1] ? actionQ[1]
                            : canFire[i][2] ? actionQ[2] : actionQ[3];
      // triggered 编码: 0=断点异常(须 triggerCanRaiseBpExp), 1=进 debug, F=未触发
      assign triggeredVec[i] =
        hasFire & (fireAction == 4'h0) & io_frontendTrigger_triggerCanRaiseBpExp
          ? 4'h0
          : hasFire & (fireAction == 4'h1) ? 4'h1 : 4'hF;
    end
  endgenerate

  assign io_triggered_0 = triggeredVec[0];
  assign io_triggered_1 = triggeredVec[1];
  assign io_triggered_2 = triggeredVec[2];
  assign io_triggered_3 = triggeredVec[3];
  assign io_triggered_4 = triggeredVec[4];
  assign io_triggered_5 = triggeredVec[5];
  assign io_triggered_6 = triggeredVec[6];
  assign io_triggered_7 = triggeredVec[7];
  assign io_triggered_8 = triggeredVec[8];
  assign io_triggered_9 = triggeredVec[9];
  assign io_triggered_10 = triggeredVec[10];
  assign io_triggered_11 = triggeredVec[11];
  assign io_triggered_12 = triggeredVec[12];
  assign io_triggered_13 = triggeredVec[13];
  assign io_triggered_14 = triggeredVec[14];
  assign io_triggered_15 = triggeredVec[15];
endmodule
