// 自动生成：scripts/gen_ftbentrygen.py —— 勿手改
module FTBEntryGen(
  input  logic [49:0] io_start_addr,
  input  logic io_old_entry_isCall,
  input  logic io_old_entry_isRet,
  input  logic io_old_entry_isJalr,
  input  logic io_old_entry_valid,
  input  logic [3:0] io_old_entry_brSlots_0_offset,
  input  logic io_old_entry_brSlots_0_sharing,
  input  logic io_old_entry_brSlots_0_valid,
  input  logic [11:0] io_old_entry_brSlots_0_lower,
  input  logic [1:0] io_old_entry_brSlots_0_tarStat,
  input  logic [3:0] io_old_entry_tailSlot_offset,
  input  logic io_old_entry_tailSlot_sharing,
  input  logic io_old_entry_tailSlot_valid,
  input  logic [19:0] io_old_entry_tailSlot_lower,
  input  logic [1:0] io_old_entry_tailSlot_tarStat,
  input  logic [3:0] io_old_entry_pftAddr,
  input  logic io_old_entry_carry,
  input  logic io_old_entry_last_may_be_rvi_call,
  input  logic io_old_entry_strong_bias_0,
  input  logic io_old_entry_strong_bias_1,
  input  logic io_pd_brMask_0,
  input  logic io_pd_brMask_1,
  input  logic io_pd_brMask_2,
  input  logic io_pd_brMask_3,
  input  logic io_pd_brMask_4,
  input  logic io_pd_brMask_5,
  input  logic io_pd_brMask_6,
  input  logic io_pd_brMask_7,
  input  logic io_pd_brMask_8,
  input  logic io_pd_brMask_9,
  input  logic io_pd_brMask_10,
  input  logic io_pd_brMask_11,
  input  logic io_pd_brMask_12,
  input  logic io_pd_brMask_13,
  input  logic io_pd_brMask_14,
  input  logic io_pd_brMask_15,
  input  logic io_pd_jmpInfo_valid,
  input  logic io_pd_jmpInfo_bits_0,
  input  logic io_pd_jmpInfo_bits_1,
  input  logic io_pd_jmpInfo_bits_2,
  input  logic [3:0] io_pd_jmpOffset,
  input  logic [49:0] io_pd_jalTarget,
  input  logic io_pd_rvcMask_0,
  input  logic io_pd_rvcMask_1,
  input  logic io_pd_rvcMask_2,
  input  logic io_pd_rvcMask_3,
  input  logic io_pd_rvcMask_4,
  input  logic io_pd_rvcMask_5,
  input  logic io_pd_rvcMask_6,
  input  logic io_pd_rvcMask_7,
  input  logic io_pd_rvcMask_8,
  input  logic io_pd_rvcMask_9,
  input  logic io_pd_rvcMask_10,
  input  logic io_pd_rvcMask_11,
  input  logic io_pd_rvcMask_12,
  input  logic io_pd_rvcMask_13,
  input  logic io_pd_rvcMask_14,
  input  logic io_pd_rvcMask_15,
  input  logic io_cfiIndex_valid,
  input  logic [3:0] io_cfiIndex_bits,
  input  logic [49:0] io_target,
  input  logic io_hit,
  input  logic io_mispredict_vec_0,
  input  logic io_mispredict_vec_1,
  input  logic io_mispredict_vec_2,
  input  logic io_mispredict_vec_3,
  input  logic io_mispredict_vec_4,
  input  logic io_mispredict_vec_5,
  input  logic io_mispredict_vec_6,
  input  logic io_mispredict_vec_7,
  input  logic io_mispredict_vec_8,
  input  logic io_mispredict_vec_9,
  input  logic io_mispredict_vec_10,
  input  logic io_mispredict_vec_11,
  input  logic io_mispredict_vec_12,
  input  logic io_mispredict_vec_13,
  input  logic io_mispredict_vec_14,
  input  logic io_mispredict_vec_15,
  output logic io_new_entry_isCall,
  output logic io_new_entry_isRet,
  output logic io_new_entry_isJalr,
  output logic io_new_entry_valid,
  output logic [3:0] io_new_entry_brSlots_0_offset,
  output logic io_new_entry_brSlots_0_sharing,
  output logic io_new_entry_brSlots_0_valid,
  output logic [11:0] io_new_entry_brSlots_0_lower,
  output logic [1:0] io_new_entry_brSlots_0_tarStat,
  output logic [3:0] io_new_entry_tailSlot_offset,
  output logic io_new_entry_tailSlot_sharing,
  output logic io_new_entry_tailSlot_valid,
  output logic [19:0] io_new_entry_tailSlot_lower,
  output logic [1:0] io_new_entry_tailSlot_tarStat,
  output logic [3:0] io_new_entry_pftAddr,
  output logic io_new_entry_carry,
  output logic io_new_entry_last_may_be_rvi_call,
  output logic io_new_entry_strong_bias_0,
  output logic io_new_entry_strong_bias_1,
  output logic io_taken_mask_0,
  output logic io_taken_mask_1,
  output logic io_jmp_taken,
  output logic io_mispred_mask_0,
  output logic io_mispred_mask_1,
  output logic io_mispred_mask_2,
  output logic io_is_init_entry,
  output logic io_is_old_entry,
  output logic io_is_new_br,
  output logic io_is_jalr_target_modified,
  output logic io_is_strong_bias_modified,
  output logic io_is_br_full
);
  xs_FTBEntryGen_core u_core (
    .io_start_addr(io_start_addr),
    .io_old_entry_isCall(io_old_entry_isCall),
    .io_old_entry_isRet(io_old_entry_isRet),
    .io_old_entry_isJalr(io_old_entry_isJalr),
    .io_old_entry_valid(io_old_entry_valid),
    .io_old_entry_brSlots_0_offset(io_old_entry_brSlots_0_offset),
    .io_old_entry_brSlots_0_sharing(io_old_entry_brSlots_0_sharing),
    .io_old_entry_brSlots_0_valid(io_old_entry_brSlots_0_valid),
    .io_old_entry_brSlots_0_lower(io_old_entry_brSlots_0_lower),
    .io_old_entry_brSlots_0_tarStat(io_old_entry_brSlots_0_tarStat),
    .io_old_entry_tailSlot_offset(io_old_entry_tailSlot_offset),
    .io_old_entry_tailSlot_sharing(io_old_entry_tailSlot_sharing),
    .io_old_entry_tailSlot_valid(io_old_entry_tailSlot_valid),
    .io_old_entry_tailSlot_lower(io_old_entry_tailSlot_lower),
    .io_old_entry_tailSlot_tarStat(io_old_entry_tailSlot_tarStat),
    .io_old_entry_pftAddr(io_old_entry_pftAddr),
    .io_old_entry_carry(io_old_entry_carry),
    .io_old_entry_last_may_be_rvi_call(io_old_entry_last_may_be_rvi_call),
    .io_old_entry_strong_bias_0(io_old_entry_strong_bias_0),
    .io_old_entry_strong_bias_1(io_old_entry_strong_bias_1),
    .io_pd_brMask_0(io_pd_brMask_0),
    .io_pd_brMask_1(io_pd_brMask_1),
    .io_pd_brMask_2(io_pd_brMask_2),
    .io_pd_brMask_3(io_pd_brMask_3),
    .io_pd_brMask_4(io_pd_brMask_4),
    .io_pd_brMask_5(io_pd_brMask_5),
    .io_pd_brMask_6(io_pd_brMask_6),
    .io_pd_brMask_7(io_pd_brMask_7),
    .io_pd_brMask_8(io_pd_brMask_8),
    .io_pd_brMask_9(io_pd_brMask_9),
    .io_pd_brMask_10(io_pd_brMask_10),
    .io_pd_brMask_11(io_pd_brMask_11),
    .io_pd_brMask_12(io_pd_brMask_12),
    .io_pd_brMask_13(io_pd_brMask_13),
    .io_pd_brMask_14(io_pd_brMask_14),
    .io_pd_brMask_15(io_pd_brMask_15),
    .io_pd_jmpInfo_valid(io_pd_jmpInfo_valid),
    .io_pd_jmpInfo_bits_0(io_pd_jmpInfo_bits_0),
    .io_pd_jmpInfo_bits_1(io_pd_jmpInfo_bits_1),
    .io_pd_jmpInfo_bits_2(io_pd_jmpInfo_bits_2),
    .io_pd_jmpOffset(io_pd_jmpOffset),
    .io_pd_jalTarget(io_pd_jalTarget),
    .io_pd_rvcMask_0(io_pd_rvcMask_0),
    .io_pd_rvcMask_1(io_pd_rvcMask_1),
    .io_pd_rvcMask_2(io_pd_rvcMask_2),
    .io_pd_rvcMask_3(io_pd_rvcMask_3),
    .io_pd_rvcMask_4(io_pd_rvcMask_4),
    .io_pd_rvcMask_5(io_pd_rvcMask_5),
    .io_pd_rvcMask_6(io_pd_rvcMask_6),
    .io_pd_rvcMask_7(io_pd_rvcMask_7),
    .io_pd_rvcMask_8(io_pd_rvcMask_8),
    .io_pd_rvcMask_9(io_pd_rvcMask_9),
    .io_pd_rvcMask_10(io_pd_rvcMask_10),
    .io_pd_rvcMask_11(io_pd_rvcMask_11),
    .io_pd_rvcMask_12(io_pd_rvcMask_12),
    .io_pd_rvcMask_13(io_pd_rvcMask_13),
    .io_pd_rvcMask_14(io_pd_rvcMask_14),
    .io_pd_rvcMask_15(io_pd_rvcMask_15),
    .io_cfiIndex_valid(io_cfiIndex_valid),
    .io_cfiIndex_bits(io_cfiIndex_bits),
    .io_target(io_target),
    .io_hit(io_hit),
    .io_mispredict_vec_0(io_mispredict_vec_0),
    .io_mispredict_vec_1(io_mispredict_vec_1),
    .io_mispredict_vec_2(io_mispredict_vec_2),
    .io_mispredict_vec_3(io_mispredict_vec_3),
    .io_mispredict_vec_4(io_mispredict_vec_4),
    .io_mispredict_vec_5(io_mispredict_vec_5),
    .io_mispredict_vec_6(io_mispredict_vec_6),
    .io_mispredict_vec_7(io_mispredict_vec_7),
    .io_mispredict_vec_8(io_mispredict_vec_8),
    .io_mispredict_vec_9(io_mispredict_vec_9),
    .io_mispredict_vec_10(io_mispredict_vec_10),
    .io_mispredict_vec_11(io_mispredict_vec_11),
    .io_mispredict_vec_12(io_mispredict_vec_12),
    .io_mispredict_vec_13(io_mispredict_vec_13),
    .io_mispredict_vec_14(io_mispredict_vec_14),
    .io_mispredict_vec_15(io_mispredict_vec_15),
    .io_new_entry_isCall(io_new_entry_isCall),
    .io_new_entry_isRet(io_new_entry_isRet),
    .io_new_entry_isJalr(io_new_entry_isJalr),
    .io_new_entry_valid(io_new_entry_valid),
    .io_new_entry_brSlots_0_offset(io_new_entry_brSlots_0_offset),
    .io_new_entry_brSlots_0_sharing(io_new_entry_brSlots_0_sharing),
    .io_new_entry_brSlots_0_valid(io_new_entry_brSlots_0_valid),
    .io_new_entry_brSlots_0_lower(io_new_entry_brSlots_0_lower),
    .io_new_entry_brSlots_0_tarStat(io_new_entry_brSlots_0_tarStat),
    .io_new_entry_tailSlot_offset(io_new_entry_tailSlot_offset),
    .io_new_entry_tailSlot_sharing(io_new_entry_tailSlot_sharing),
    .io_new_entry_tailSlot_valid(io_new_entry_tailSlot_valid),
    .io_new_entry_tailSlot_lower(io_new_entry_tailSlot_lower),
    .io_new_entry_tailSlot_tarStat(io_new_entry_tailSlot_tarStat),
    .io_new_entry_pftAddr(io_new_entry_pftAddr),
    .io_new_entry_carry(io_new_entry_carry),
    .io_new_entry_last_may_be_rvi_call(io_new_entry_last_may_be_rvi_call),
    .io_new_entry_strong_bias_0(io_new_entry_strong_bias_0),
    .io_new_entry_strong_bias_1(io_new_entry_strong_bias_1),
    .io_taken_mask_0(io_taken_mask_0),
    .io_taken_mask_1(io_taken_mask_1),
    .io_jmp_taken(io_jmp_taken),
    .io_mispred_mask_0(io_mispred_mask_0),
    .io_mispred_mask_1(io_mispred_mask_1),
    .io_mispred_mask_2(io_mispred_mask_2),
    .io_is_init_entry(io_is_init_entry),
    .io_is_old_entry(io_is_old_entry),
    .io_is_new_br(io_is_new_br),
    .io_is_jalr_target_modified(io_is_jalr_target_modified),
    .io_is_strong_bias_modified(io_is_strong_bias_modified),
    .io_is_br_full(io_is_br_full)
  );
endmodule
