// 自动生成: scripts/gen_ibuffer.py —— 勿手改
module IBuffer(
  input clock,
  input reset,
  input io_flush,
  input io_ControlRedirect,
  input io_ControlBTBMissBubble,
  input io_TAGEMissBubble,
  input io_SCMissBubble,
  input io_ITTAGEMissBubble,
  input io_RASMissBubble,
  input io_MemVioRedirect,
  input io_in_valid,
  input [31:0] io_in_bits_instrs_0,
  input [31:0] io_in_bits_instrs_1,
  input [31:0] io_in_bits_instrs_2,
  input [31:0] io_in_bits_instrs_3,
  input [31:0] io_in_bits_instrs_4,
  input [31:0] io_in_bits_instrs_5,
  input [31:0] io_in_bits_instrs_6,
  input [31:0] io_in_bits_instrs_7,
  input [31:0] io_in_bits_instrs_8,
  input [31:0] io_in_bits_instrs_9,
  input [31:0] io_in_bits_instrs_10,
  input [31:0] io_in_bits_instrs_11,
  input [31:0] io_in_bits_instrs_12,
  input [31:0] io_in_bits_instrs_13,
  input [31:0] io_in_bits_instrs_14,
  input [31:0] io_in_bits_instrs_15,
  input [15:0] io_in_bits_valid,
  input [15:0] io_in_bits_enqEnable,
  input io_in_bits_pd_0_isRVC,
  input [1:0] io_in_bits_pd_0_brType,
  input io_in_bits_pd_1_isRVC,
  input [1:0] io_in_bits_pd_1_brType,
  input io_in_bits_pd_2_isRVC,
  input [1:0] io_in_bits_pd_2_brType,
  input io_in_bits_pd_3_isRVC,
  input [1:0] io_in_bits_pd_3_brType,
  input io_in_bits_pd_4_isRVC,
  input [1:0] io_in_bits_pd_4_brType,
  input io_in_bits_pd_5_isRVC,
  input [1:0] io_in_bits_pd_5_brType,
  input io_in_bits_pd_6_isRVC,
  input [1:0] io_in_bits_pd_6_brType,
  input io_in_bits_pd_7_isRVC,
  input [1:0] io_in_bits_pd_7_brType,
  input io_in_bits_pd_8_isRVC,
  input [1:0] io_in_bits_pd_8_brType,
  input io_in_bits_pd_9_isRVC,
  input [1:0] io_in_bits_pd_9_brType,
  input io_in_bits_pd_10_isRVC,
  input [1:0] io_in_bits_pd_10_brType,
  input io_in_bits_pd_11_isRVC,
  input [1:0] io_in_bits_pd_11_brType,
  input io_in_bits_pd_12_isRVC,
  input [1:0] io_in_bits_pd_12_brType,
  input io_in_bits_pd_13_isRVC,
  input [1:0] io_in_bits_pd_13_brType,
  input io_in_bits_pd_14_isRVC,
  input [1:0] io_in_bits_pd_14_brType,
  input io_in_bits_pd_15_isRVC,
  input [1:0] io_in_bits_pd_15_brType,
  input [9:0] io_in_bits_foldpc_0,
  input [9:0] io_in_bits_foldpc_1,
  input [9:0] io_in_bits_foldpc_2,
  input [9:0] io_in_bits_foldpc_3,
  input [9:0] io_in_bits_foldpc_4,
  input [9:0] io_in_bits_foldpc_5,
  input [9:0] io_in_bits_foldpc_6,
  input [9:0] io_in_bits_foldpc_7,
  input [9:0] io_in_bits_foldpc_8,
  input [9:0] io_in_bits_foldpc_9,
  input [9:0] io_in_bits_foldpc_10,
  input [9:0] io_in_bits_foldpc_11,
  input [9:0] io_in_bits_foldpc_12,
  input [9:0] io_in_bits_foldpc_13,
  input [9:0] io_in_bits_foldpc_14,
  input [9:0] io_in_bits_foldpc_15,
  input io_in_bits_ftqOffset_0_valid,
  input io_in_bits_ftqOffset_1_valid,
  input io_in_bits_ftqOffset_2_valid,
  input io_in_bits_ftqOffset_3_valid,
  input io_in_bits_ftqOffset_4_valid,
  input io_in_bits_ftqOffset_5_valid,
  input io_in_bits_ftqOffset_6_valid,
  input io_in_bits_ftqOffset_7_valid,
  input io_in_bits_ftqOffset_8_valid,
  input io_in_bits_ftqOffset_9_valid,
  input io_in_bits_ftqOffset_10_valid,
  input io_in_bits_ftqOffset_11_valid,
  input io_in_bits_ftqOffset_12_valid,
  input io_in_bits_ftqOffset_13_valid,
  input io_in_bits_ftqOffset_14_valid,
  input io_in_bits_ftqOffset_15_valid,
  input io_in_bits_backendException_0,
  input [1:0] io_in_bits_exceptionType_0,
  input [1:0] io_in_bits_exceptionType_1,
  input [1:0] io_in_bits_exceptionType_2,
  input [1:0] io_in_bits_exceptionType_3,
  input [1:0] io_in_bits_exceptionType_4,
  input [1:0] io_in_bits_exceptionType_5,
  input [1:0] io_in_bits_exceptionType_6,
  input [1:0] io_in_bits_exceptionType_7,
  input [1:0] io_in_bits_exceptionType_8,
  input [1:0] io_in_bits_exceptionType_9,
  input [1:0] io_in_bits_exceptionType_10,
  input [1:0] io_in_bits_exceptionType_11,
  input [1:0] io_in_bits_exceptionType_12,
  input [1:0] io_in_bits_exceptionType_13,
  input [1:0] io_in_bits_exceptionType_14,
  input [1:0] io_in_bits_exceptionType_15,
  input io_in_bits_crossPageIPFFix_0,
  input io_in_bits_crossPageIPFFix_1,
  input io_in_bits_crossPageIPFFix_2,
  input io_in_bits_crossPageIPFFix_3,
  input io_in_bits_crossPageIPFFix_4,
  input io_in_bits_crossPageIPFFix_5,
  input io_in_bits_crossPageIPFFix_6,
  input io_in_bits_crossPageIPFFix_7,
  input io_in_bits_crossPageIPFFix_8,
  input io_in_bits_crossPageIPFFix_9,
  input io_in_bits_crossPageIPFFix_10,
  input io_in_bits_crossPageIPFFix_11,
  input io_in_bits_crossPageIPFFix_12,
  input io_in_bits_crossPageIPFFix_13,
  input io_in_bits_crossPageIPFFix_14,
  input io_in_bits_crossPageIPFFix_15,
  input io_in_bits_illegalInstr_0,
  input io_in_bits_illegalInstr_1,
  input io_in_bits_illegalInstr_2,
  input io_in_bits_illegalInstr_3,
  input io_in_bits_illegalInstr_4,
  input io_in_bits_illegalInstr_5,
  input io_in_bits_illegalInstr_6,
  input io_in_bits_illegalInstr_7,
  input io_in_bits_illegalInstr_8,
  input io_in_bits_illegalInstr_9,
  input io_in_bits_illegalInstr_10,
  input io_in_bits_illegalInstr_11,
  input io_in_bits_illegalInstr_12,
  input io_in_bits_illegalInstr_13,
  input io_in_bits_illegalInstr_14,
  input io_in_bits_illegalInstr_15,
  input [3:0] io_in_bits_triggered_0,
  input [3:0] io_in_bits_triggered_1,
  input [3:0] io_in_bits_triggered_2,
  input [3:0] io_in_bits_triggered_3,
  input [3:0] io_in_bits_triggered_4,
  input [3:0] io_in_bits_triggered_5,
  input [3:0] io_in_bits_triggered_6,
  input [3:0] io_in_bits_triggered_7,
  input [3:0] io_in_bits_triggered_8,
  input [3:0] io_in_bits_triggered_9,
  input [3:0] io_in_bits_triggered_10,
  input [3:0] io_in_bits_triggered_11,
  input [3:0] io_in_bits_triggered_12,
  input [3:0] io_in_bits_triggered_13,
  input [3:0] io_in_bits_triggered_14,
  input [3:0] io_in_bits_triggered_15,
  input io_in_bits_isLastInFtqEntry_0,
  input io_in_bits_isLastInFtqEntry_1,
  input io_in_bits_isLastInFtqEntry_2,
  input io_in_bits_isLastInFtqEntry_3,
  input io_in_bits_isLastInFtqEntry_4,
  input io_in_bits_isLastInFtqEntry_5,
  input io_in_bits_isLastInFtqEntry_6,
  input io_in_bits_isLastInFtqEntry_7,
  input io_in_bits_isLastInFtqEntry_8,
  input io_in_bits_isLastInFtqEntry_9,
  input io_in_bits_isLastInFtqEntry_10,
  input io_in_bits_isLastInFtqEntry_11,
  input io_in_bits_isLastInFtqEntry_12,
  input io_in_bits_isLastInFtqEntry_13,
  input io_in_bits_isLastInFtqEntry_14,
  input io_in_bits_isLastInFtqEntry_15,
  input [49:0] io_in_bits_pc_0,
  input [49:0] io_in_bits_pc_1,
  input [49:0] io_in_bits_pc_2,
  input [49:0] io_in_bits_pc_3,
  input [49:0] io_in_bits_pc_4,
  input [49:0] io_in_bits_pc_5,
  input [49:0] io_in_bits_pc_6,
  input [49:0] io_in_bits_pc_7,
  input [49:0] io_in_bits_pc_8,
  input [49:0] io_in_bits_pc_9,
  input [49:0] io_in_bits_pc_10,
  input [49:0] io_in_bits_pc_11,
  input [49:0] io_in_bits_pc_12,
  input [49:0] io_in_bits_pc_13,
  input [49:0] io_in_bits_pc_14,
  input [49:0] io_in_bits_pc_15,
  input io_in_bits_ftqPtr_flag,
  input [5:0] io_in_bits_ftqPtr_value,
  input io_in_bits_topdown_info_reasons_0,
  input io_in_bits_topdown_info_reasons_1,
  input io_in_bits_topdown_info_reasons_2,
  input io_in_bits_topdown_info_reasons_3,
  input io_in_bits_topdown_info_reasons_4,
  input io_in_bits_topdown_info_reasons_5,
  input io_in_bits_topdown_info_reasons_6,
  input io_in_bits_topdown_info_reasons_7,
  input io_in_bits_topdown_info_reasons_8,
  input io_in_bits_topdown_info_reasons_9,
  input io_in_bits_topdown_info_reasons_10,
  input io_in_bits_topdown_info_reasons_11,
  input io_in_bits_topdown_info_reasons_12,
  input io_in_bits_topdown_info_reasons_13,
  input io_in_bits_topdown_info_reasons_14,
  input io_in_bits_topdown_info_reasons_15,
  input io_in_bits_topdown_info_reasons_16,
  input io_in_bits_topdown_info_reasons_17,
  input io_in_bits_topdown_info_reasons_18,
  input io_in_bits_topdown_info_reasons_19,
  input io_in_bits_topdown_info_reasons_20,
  input io_in_bits_topdown_info_reasons_21,
  input io_in_bits_topdown_info_reasons_22,
  input io_in_bits_topdown_info_reasons_23,
  input io_in_bits_topdown_info_reasons_24,
  input io_in_bits_topdown_info_reasons_25,
  input io_in_bits_topdown_info_reasons_26,
  input io_in_bits_topdown_info_reasons_27,
  input io_in_bits_topdown_info_reasons_28,
  input io_in_bits_topdown_info_reasons_29,
  input io_in_bits_topdown_info_reasons_30,
  input io_in_bits_topdown_info_reasons_31,
  input io_in_bits_topdown_info_reasons_32,
  input io_in_bits_topdown_info_reasons_33,
  input io_in_bits_topdown_info_reasons_34,
  input io_in_bits_topdown_info_reasons_35,
  input io_in_bits_topdown_info_reasons_36,
  input io_in_bits_topdown_info_reasons_37,
  input io_decodeCanAccept,
  input io_stallReason_backReason_valid,
  input [5:0] io_stallReason_backReason_bits,
  output io_in_ready,
  output io_out_0_valid,
  output [31:0] io_out_0_bits_instr,
  output [49:0] io_out_0_bits_pc,
  output [9:0] io_out_0_bits_foldpc,
  output io_out_0_bits_exceptionVec_1,
  output io_out_0_bits_exceptionVec_2,
  output io_out_0_bits_exceptionVec_12,
  output io_out_0_bits_exceptionVec_20,
  output io_out_0_bits_backendException,
  output [3:0] io_out_0_bits_trigger,
  output io_out_0_bits_pd_isRVC,
  output [1:0] io_out_0_bits_pd_brType,
  output io_out_0_bits_pred_taken,
  output io_out_0_bits_crossPageIPFFix,
  output io_out_0_bits_ftqPtr_flag,
  output [5:0] io_out_0_bits_ftqPtr_value,
  output [3:0] io_out_0_bits_ftqOffset,
  output io_out_0_bits_isLastInFtqEntry,
  output io_out_1_valid,
  output [31:0] io_out_1_bits_instr,
  output [49:0] io_out_1_bits_pc,
  output [9:0] io_out_1_bits_foldpc,
  output io_out_1_bits_exceptionVec_1,
  output io_out_1_bits_exceptionVec_2,
  output io_out_1_bits_exceptionVec_12,
  output io_out_1_bits_exceptionVec_20,
  output io_out_1_bits_backendException,
  output [3:0] io_out_1_bits_trigger,
  output io_out_1_bits_pd_isRVC,
  output [1:0] io_out_1_bits_pd_brType,
  output io_out_1_bits_pred_taken,
  output io_out_1_bits_crossPageIPFFix,
  output io_out_1_bits_ftqPtr_flag,
  output [5:0] io_out_1_bits_ftqPtr_value,
  output [3:0] io_out_1_bits_ftqOffset,
  output io_out_1_bits_isLastInFtqEntry,
  output io_out_2_valid,
  output [31:0] io_out_2_bits_instr,
  output [49:0] io_out_2_bits_pc,
  output [9:0] io_out_2_bits_foldpc,
  output io_out_2_bits_exceptionVec_1,
  output io_out_2_bits_exceptionVec_2,
  output io_out_2_bits_exceptionVec_12,
  output io_out_2_bits_exceptionVec_20,
  output io_out_2_bits_backendException,
  output [3:0] io_out_2_bits_trigger,
  output io_out_2_bits_pd_isRVC,
  output [1:0] io_out_2_bits_pd_brType,
  output io_out_2_bits_pred_taken,
  output io_out_2_bits_crossPageIPFFix,
  output io_out_2_bits_ftqPtr_flag,
  output [5:0] io_out_2_bits_ftqPtr_value,
  output [3:0] io_out_2_bits_ftqOffset,
  output io_out_2_bits_isLastInFtqEntry,
  output io_out_3_valid,
  output [31:0] io_out_3_bits_instr,
  output [49:0] io_out_3_bits_pc,
  output [9:0] io_out_3_bits_foldpc,
  output io_out_3_bits_exceptionVec_1,
  output io_out_3_bits_exceptionVec_2,
  output io_out_3_bits_exceptionVec_12,
  output io_out_3_bits_exceptionVec_20,
  output io_out_3_bits_backendException,
  output [3:0] io_out_3_bits_trigger,
  output io_out_3_bits_pd_isRVC,
  output [1:0] io_out_3_bits_pd_brType,
  output io_out_3_bits_pred_taken,
  output io_out_3_bits_crossPageIPFFix,
  output io_out_3_bits_ftqPtr_flag,
  output [5:0] io_out_3_bits_ftqPtr_value,
  output [3:0] io_out_3_bits_ftqOffset,
  output io_out_3_bits_isLastInFtqEntry,
  output io_out_4_valid,
  output [31:0] io_out_4_bits_instr,
  output [49:0] io_out_4_bits_pc,
  output [9:0] io_out_4_bits_foldpc,
  output io_out_4_bits_exceptionVec_1,
  output io_out_4_bits_exceptionVec_2,
  output io_out_4_bits_exceptionVec_12,
  output io_out_4_bits_exceptionVec_20,
  output io_out_4_bits_backendException,
  output [3:0] io_out_4_bits_trigger,
  output io_out_4_bits_pd_isRVC,
  output [1:0] io_out_4_bits_pd_brType,
  output io_out_4_bits_pred_taken,
  output io_out_4_bits_crossPageIPFFix,
  output io_out_4_bits_ftqPtr_flag,
  output [5:0] io_out_4_bits_ftqPtr_value,
  output [3:0] io_out_4_bits_ftqOffset,
  output io_out_4_bits_isLastInFtqEntry,
  output io_out_5_valid,
  output [31:0] io_out_5_bits_instr,
  output [49:0] io_out_5_bits_pc,
  output [9:0] io_out_5_bits_foldpc,
  output io_out_5_bits_exceptionVec_1,
  output io_out_5_bits_exceptionVec_2,
  output io_out_5_bits_exceptionVec_12,
  output io_out_5_bits_exceptionVec_20,
  output io_out_5_bits_backendException,
  output [3:0] io_out_5_bits_trigger,
  output io_out_5_bits_pd_isRVC,
  output [1:0] io_out_5_bits_pd_brType,
  output io_out_5_bits_pred_taken,
  output io_out_5_bits_crossPageIPFFix,
  output io_out_5_bits_ftqPtr_flag,
  output [5:0] io_out_5_bits_ftqPtr_value,
  output [3:0] io_out_5_bits_ftqOffset,
  output io_out_5_bits_isLastInFtqEntry,
  output [5:0] io_stallReason_reason_0,
  output [5:0] io_stallReason_reason_1,
  output [5:0] io_stallReason_reason_2,
  output [5:0] io_stallReason_reason_3,
  output [5:0] io_stallReason_reason_4,
  output [5:0] io_stallReason_reason_5,
  output [5:0] io_perf_0_value,
  output [5:0] io_perf_1_value,
  output [5:0] io_perf_2_value,
  output [5:0] io_perf_3_value,
  output [5:0] io_perf_4_value,
  output [5:0] io_perf_5_value,
  output [5:0] io_perf_6_value,
  output [5:0] io_perf_7_value,
  output [5:0] io_perf_8_value
);
  xs_IBuffer_core u_core (
    .clock(clock),
    .reset(reset),
    .io_flush(io_flush),
    .io_ControlRedirect(io_ControlRedirect),
    .io_ControlBTBMissBubble(io_ControlBTBMissBubble),
    .io_TAGEMissBubble(io_TAGEMissBubble),
    .io_SCMissBubble(io_SCMissBubble),
    .io_ITTAGEMissBubble(io_ITTAGEMissBubble),
    .io_RASMissBubble(io_RASMissBubble),
    .io_MemVioRedirect(io_MemVioRedirect),
    .io_in_valid(io_in_valid),
    .io_in_bits_instrs_0(io_in_bits_instrs_0),
    .io_in_bits_instrs_1(io_in_bits_instrs_1),
    .io_in_bits_instrs_2(io_in_bits_instrs_2),
    .io_in_bits_instrs_3(io_in_bits_instrs_3),
    .io_in_bits_instrs_4(io_in_bits_instrs_4),
    .io_in_bits_instrs_5(io_in_bits_instrs_5),
    .io_in_bits_instrs_6(io_in_bits_instrs_6),
    .io_in_bits_instrs_7(io_in_bits_instrs_7),
    .io_in_bits_instrs_8(io_in_bits_instrs_8),
    .io_in_bits_instrs_9(io_in_bits_instrs_9),
    .io_in_bits_instrs_10(io_in_bits_instrs_10),
    .io_in_bits_instrs_11(io_in_bits_instrs_11),
    .io_in_bits_instrs_12(io_in_bits_instrs_12),
    .io_in_bits_instrs_13(io_in_bits_instrs_13),
    .io_in_bits_instrs_14(io_in_bits_instrs_14),
    .io_in_bits_instrs_15(io_in_bits_instrs_15),
    .io_in_bits_valid(io_in_bits_valid),
    .io_in_bits_enqEnable(io_in_bits_enqEnable),
    .io_in_bits_pd_0_isRVC(io_in_bits_pd_0_isRVC),
    .io_in_bits_pd_0_brType(io_in_bits_pd_0_brType),
    .io_in_bits_pd_1_isRVC(io_in_bits_pd_1_isRVC),
    .io_in_bits_pd_1_brType(io_in_bits_pd_1_brType),
    .io_in_bits_pd_2_isRVC(io_in_bits_pd_2_isRVC),
    .io_in_bits_pd_2_brType(io_in_bits_pd_2_brType),
    .io_in_bits_pd_3_isRVC(io_in_bits_pd_3_isRVC),
    .io_in_bits_pd_3_brType(io_in_bits_pd_3_brType),
    .io_in_bits_pd_4_isRVC(io_in_bits_pd_4_isRVC),
    .io_in_bits_pd_4_brType(io_in_bits_pd_4_brType),
    .io_in_bits_pd_5_isRVC(io_in_bits_pd_5_isRVC),
    .io_in_bits_pd_5_brType(io_in_bits_pd_5_brType),
    .io_in_bits_pd_6_isRVC(io_in_bits_pd_6_isRVC),
    .io_in_bits_pd_6_brType(io_in_bits_pd_6_brType),
    .io_in_bits_pd_7_isRVC(io_in_bits_pd_7_isRVC),
    .io_in_bits_pd_7_brType(io_in_bits_pd_7_brType),
    .io_in_bits_pd_8_isRVC(io_in_bits_pd_8_isRVC),
    .io_in_bits_pd_8_brType(io_in_bits_pd_8_brType),
    .io_in_bits_pd_9_isRVC(io_in_bits_pd_9_isRVC),
    .io_in_bits_pd_9_brType(io_in_bits_pd_9_brType),
    .io_in_bits_pd_10_isRVC(io_in_bits_pd_10_isRVC),
    .io_in_bits_pd_10_brType(io_in_bits_pd_10_brType),
    .io_in_bits_pd_11_isRVC(io_in_bits_pd_11_isRVC),
    .io_in_bits_pd_11_brType(io_in_bits_pd_11_brType),
    .io_in_bits_pd_12_isRVC(io_in_bits_pd_12_isRVC),
    .io_in_bits_pd_12_brType(io_in_bits_pd_12_brType),
    .io_in_bits_pd_13_isRVC(io_in_bits_pd_13_isRVC),
    .io_in_bits_pd_13_brType(io_in_bits_pd_13_brType),
    .io_in_bits_pd_14_isRVC(io_in_bits_pd_14_isRVC),
    .io_in_bits_pd_14_brType(io_in_bits_pd_14_brType),
    .io_in_bits_pd_15_isRVC(io_in_bits_pd_15_isRVC),
    .io_in_bits_pd_15_brType(io_in_bits_pd_15_brType),
    .io_in_bits_foldpc_0(io_in_bits_foldpc_0),
    .io_in_bits_foldpc_1(io_in_bits_foldpc_1),
    .io_in_bits_foldpc_2(io_in_bits_foldpc_2),
    .io_in_bits_foldpc_3(io_in_bits_foldpc_3),
    .io_in_bits_foldpc_4(io_in_bits_foldpc_4),
    .io_in_bits_foldpc_5(io_in_bits_foldpc_5),
    .io_in_bits_foldpc_6(io_in_bits_foldpc_6),
    .io_in_bits_foldpc_7(io_in_bits_foldpc_7),
    .io_in_bits_foldpc_8(io_in_bits_foldpc_8),
    .io_in_bits_foldpc_9(io_in_bits_foldpc_9),
    .io_in_bits_foldpc_10(io_in_bits_foldpc_10),
    .io_in_bits_foldpc_11(io_in_bits_foldpc_11),
    .io_in_bits_foldpc_12(io_in_bits_foldpc_12),
    .io_in_bits_foldpc_13(io_in_bits_foldpc_13),
    .io_in_bits_foldpc_14(io_in_bits_foldpc_14),
    .io_in_bits_foldpc_15(io_in_bits_foldpc_15),
    .io_in_bits_ftqOffset_0_valid(io_in_bits_ftqOffset_0_valid),
    .io_in_bits_ftqOffset_1_valid(io_in_bits_ftqOffset_1_valid),
    .io_in_bits_ftqOffset_2_valid(io_in_bits_ftqOffset_2_valid),
    .io_in_bits_ftqOffset_3_valid(io_in_bits_ftqOffset_3_valid),
    .io_in_bits_ftqOffset_4_valid(io_in_bits_ftqOffset_4_valid),
    .io_in_bits_ftqOffset_5_valid(io_in_bits_ftqOffset_5_valid),
    .io_in_bits_ftqOffset_6_valid(io_in_bits_ftqOffset_6_valid),
    .io_in_bits_ftqOffset_7_valid(io_in_bits_ftqOffset_7_valid),
    .io_in_bits_ftqOffset_8_valid(io_in_bits_ftqOffset_8_valid),
    .io_in_bits_ftqOffset_9_valid(io_in_bits_ftqOffset_9_valid),
    .io_in_bits_ftqOffset_10_valid(io_in_bits_ftqOffset_10_valid),
    .io_in_bits_ftqOffset_11_valid(io_in_bits_ftqOffset_11_valid),
    .io_in_bits_ftqOffset_12_valid(io_in_bits_ftqOffset_12_valid),
    .io_in_bits_ftqOffset_13_valid(io_in_bits_ftqOffset_13_valid),
    .io_in_bits_ftqOffset_14_valid(io_in_bits_ftqOffset_14_valid),
    .io_in_bits_ftqOffset_15_valid(io_in_bits_ftqOffset_15_valid),
    .io_in_bits_backendException_0(io_in_bits_backendException_0),
    .io_in_bits_exceptionType_0(io_in_bits_exceptionType_0),
    .io_in_bits_exceptionType_1(io_in_bits_exceptionType_1),
    .io_in_bits_exceptionType_2(io_in_bits_exceptionType_2),
    .io_in_bits_exceptionType_3(io_in_bits_exceptionType_3),
    .io_in_bits_exceptionType_4(io_in_bits_exceptionType_4),
    .io_in_bits_exceptionType_5(io_in_bits_exceptionType_5),
    .io_in_bits_exceptionType_6(io_in_bits_exceptionType_6),
    .io_in_bits_exceptionType_7(io_in_bits_exceptionType_7),
    .io_in_bits_exceptionType_8(io_in_bits_exceptionType_8),
    .io_in_bits_exceptionType_9(io_in_bits_exceptionType_9),
    .io_in_bits_exceptionType_10(io_in_bits_exceptionType_10),
    .io_in_bits_exceptionType_11(io_in_bits_exceptionType_11),
    .io_in_bits_exceptionType_12(io_in_bits_exceptionType_12),
    .io_in_bits_exceptionType_13(io_in_bits_exceptionType_13),
    .io_in_bits_exceptionType_14(io_in_bits_exceptionType_14),
    .io_in_bits_exceptionType_15(io_in_bits_exceptionType_15),
    .io_in_bits_crossPageIPFFix_0(io_in_bits_crossPageIPFFix_0),
    .io_in_bits_crossPageIPFFix_1(io_in_bits_crossPageIPFFix_1),
    .io_in_bits_crossPageIPFFix_2(io_in_bits_crossPageIPFFix_2),
    .io_in_bits_crossPageIPFFix_3(io_in_bits_crossPageIPFFix_3),
    .io_in_bits_crossPageIPFFix_4(io_in_bits_crossPageIPFFix_4),
    .io_in_bits_crossPageIPFFix_5(io_in_bits_crossPageIPFFix_5),
    .io_in_bits_crossPageIPFFix_6(io_in_bits_crossPageIPFFix_6),
    .io_in_bits_crossPageIPFFix_7(io_in_bits_crossPageIPFFix_7),
    .io_in_bits_crossPageIPFFix_8(io_in_bits_crossPageIPFFix_8),
    .io_in_bits_crossPageIPFFix_9(io_in_bits_crossPageIPFFix_9),
    .io_in_bits_crossPageIPFFix_10(io_in_bits_crossPageIPFFix_10),
    .io_in_bits_crossPageIPFFix_11(io_in_bits_crossPageIPFFix_11),
    .io_in_bits_crossPageIPFFix_12(io_in_bits_crossPageIPFFix_12),
    .io_in_bits_crossPageIPFFix_13(io_in_bits_crossPageIPFFix_13),
    .io_in_bits_crossPageIPFFix_14(io_in_bits_crossPageIPFFix_14),
    .io_in_bits_crossPageIPFFix_15(io_in_bits_crossPageIPFFix_15),
    .io_in_bits_illegalInstr_0(io_in_bits_illegalInstr_0),
    .io_in_bits_illegalInstr_1(io_in_bits_illegalInstr_1),
    .io_in_bits_illegalInstr_2(io_in_bits_illegalInstr_2),
    .io_in_bits_illegalInstr_3(io_in_bits_illegalInstr_3),
    .io_in_bits_illegalInstr_4(io_in_bits_illegalInstr_4),
    .io_in_bits_illegalInstr_5(io_in_bits_illegalInstr_5),
    .io_in_bits_illegalInstr_6(io_in_bits_illegalInstr_6),
    .io_in_bits_illegalInstr_7(io_in_bits_illegalInstr_7),
    .io_in_bits_illegalInstr_8(io_in_bits_illegalInstr_8),
    .io_in_bits_illegalInstr_9(io_in_bits_illegalInstr_9),
    .io_in_bits_illegalInstr_10(io_in_bits_illegalInstr_10),
    .io_in_bits_illegalInstr_11(io_in_bits_illegalInstr_11),
    .io_in_bits_illegalInstr_12(io_in_bits_illegalInstr_12),
    .io_in_bits_illegalInstr_13(io_in_bits_illegalInstr_13),
    .io_in_bits_illegalInstr_14(io_in_bits_illegalInstr_14),
    .io_in_bits_illegalInstr_15(io_in_bits_illegalInstr_15),
    .io_in_bits_triggered_0(io_in_bits_triggered_0),
    .io_in_bits_triggered_1(io_in_bits_triggered_1),
    .io_in_bits_triggered_2(io_in_bits_triggered_2),
    .io_in_bits_triggered_3(io_in_bits_triggered_3),
    .io_in_bits_triggered_4(io_in_bits_triggered_4),
    .io_in_bits_triggered_5(io_in_bits_triggered_5),
    .io_in_bits_triggered_6(io_in_bits_triggered_6),
    .io_in_bits_triggered_7(io_in_bits_triggered_7),
    .io_in_bits_triggered_8(io_in_bits_triggered_8),
    .io_in_bits_triggered_9(io_in_bits_triggered_9),
    .io_in_bits_triggered_10(io_in_bits_triggered_10),
    .io_in_bits_triggered_11(io_in_bits_triggered_11),
    .io_in_bits_triggered_12(io_in_bits_triggered_12),
    .io_in_bits_triggered_13(io_in_bits_triggered_13),
    .io_in_bits_triggered_14(io_in_bits_triggered_14),
    .io_in_bits_triggered_15(io_in_bits_triggered_15),
    .io_in_bits_isLastInFtqEntry_0(io_in_bits_isLastInFtqEntry_0),
    .io_in_bits_isLastInFtqEntry_1(io_in_bits_isLastInFtqEntry_1),
    .io_in_bits_isLastInFtqEntry_2(io_in_bits_isLastInFtqEntry_2),
    .io_in_bits_isLastInFtqEntry_3(io_in_bits_isLastInFtqEntry_3),
    .io_in_bits_isLastInFtqEntry_4(io_in_bits_isLastInFtqEntry_4),
    .io_in_bits_isLastInFtqEntry_5(io_in_bits_isLastInFtqEntry_5),
    .io_in_bits_isLastInFtqEntry_6(io_in_bits_isLastInFtqEntry_6),
    .io_in_bits_isLastInFtqEntry_7(io_in_bits_isLastInFtqEntry_7),
    .io_in_bits_isLastInFtqEntry_8(io_in_bits_isLastInFtqEntry_8),
    .io_in_bits_isLastInFtqEntry_9(io_in_bits_isLastInFtqEntry_9),
    .io_in_bits_isLastInFtqEntry_10(io_in_bits_isLastInFtqEntry_10),
    .io_in_bits_isLastInFtqEntry_11(io_in_bits_isLastInFtqEntry_11),
    .io_in_bits_isLastInFtqEntry_12(io_in_bits_isLastInFtqEntry_12),
    .io_in_bits_isLastInFtqEntry_13(io_in_bits_isLastInFtqEntry_13),
    .io_in_bits_isLastInFtqEntry_14(io_in_bits_isLastInFtqEntry_14),
    .io_in_bits_isLastInFtqEntry_15(io_in_bits_isLastInFtqEntry_15),
    .io_in_bits_pc_0(io_in_bits_pc_0),
    .io_in_bits_pc_1(io_in_bits_pc_1),
    .io_in_bits_pc_2(io_in_bits_pc_2),
    .io_in_bits_pc_3(io_in_bits_pc_3),
    .io_in_bits_pc_4(io_in_bits_pc_4),
    .io_in_bits_pc_5(io_in_bits_pc_5),
    .io_in_bits_pc_6(io_in_bits_pc_6),
    .io_in_bits_pc_7(io_in_bits_pc_7),
    .io_in_bits_pc_8(io_in_bits_pc_8),
    .io_in_bits_pc_9(io_in_bits_pc_9),
    .io_in_bits_pc_10(io_in_bits_pc_10),
    .io_in_bits_pc_11(io_in_bits_pc_11),
    .io_in_bits_pc_12(io_in_bits_pc_12),
    .io_in_bits_pc_13(io_in_bits_pc_13),
    .io_in_bits_pc_14(io_in_bits_pc_14),
    .io_in_bits_pc_15(io_in_bits_pc_15),
    .io_in_bits_ftqPtr_flag(io_in_bits_ftqPtr_flag),
    .io_in_bits_ftqPtr_value(io_in_bits_ftqPtr_value),
    .io_in_bits_topdown_info_reasons_0(io_in_bits_topdown_info_reasons_0),
    .io_in_bits_topdown_info_reasons_1(io_in_bits_topdown_info_reasons_1),
    .io_in_bits_topdown_info_reasons_2(io_in_bits_topdown_info_reasons_2),
    .io_in_bits_topdown_info_reasons_3(io_in_bits_topdown_info_reasons_3),
    .io_in_bits_topdown_info_reasons_4(io_in_bits_topdown_info_reasons_4),
    .io_in_bits_topdown_info_reasons_5(io_in_bits_topdown_info_reasons_5),
    .io_in_bits_topdown_info_reasons_6(io_in_bits_topdown_info_reasons_6),
    .io_in_bits_topdown_info_reasons_7(io_in_bits_topdown_info_reasons_7),
    .io_in_bits_topdown_info_reasons_8(io_in_bits_topdown_info_reasons_8),
    .io_in_bits_topdown_info_reasons_9(io_in_bits_topdown_info_reasons_9),
    .io_in_bits_topdown_info_reasons_10(io_in_bits_topdown_info_reasons_10),
    .io_in_bits_topdown_info_reasons_11(io_in_bits_topdown_info_reasons_11),
    .io_in_bits_topdown_info_reasons_12(io_in_bits_topdown_info_reasons_12),
    .io_in_bits_topdown_info_reasons_13(io_in_bits_topdown_info_reasons_13),
    .io_in_bits_topdown_info_reasons_14(io_in_bits_topdown_info_reasons_14),
    .io_in_bits_topdown_info_reasons_15(io_in_bits_topdown_info_reasons_15),
    .io_in_bits_topdown_info_reasons_16(io_in_bits_topdown_info_reasons_16),
    .io_in_bits_topdown_info_reasons_17(io_in_bits_topdown_info_reasons_17),
    .io_in_bits_topdown_info_reasons_18(io_in_bits_topdown_info_reasons_18),
    .io_in_bits_topdown_info_reasons_19(io_in_bits_topdown_info_reasons_19),
    .io_in_bits_topdown_info_reasons_20(io_in_bits_topdown_info_reasons_20),
    .io_in_bits_topdown_info_reasons_21(io_in_bits_topdown_info_reasons_21),
    .io_in_bits_topdown_info_reasons_22(io_in_bits_topdown_info_reasons_22),
    .io_in_bits_topdown_info_reasons_23(io_in_bits_topdown_info_reasons_23),
    .io_in_bits_topdown_info_reasons_24(io_in_bits_topdown_info_reasons_24),
    .io_in_bits_topdown_info_reasons_25(io_in_bits_topdown_info_reasons_25),
    .io_in_bits_topdown_info_reasons_26(io_in_bits_topdown_info_reasons_26),
    .io_in_bits_topdown_info_reasons_27(io_in_bits_topdown_info_reasons_27),
    .io_in_bits_topdown_info_reasons_28(io_in_bits_topdown_info_reasons_28),
    .io_in_bits_topdown_info_reasons_29(io_in_bits_topdown_info_reasons_29),
    .io_in_bits_topdown_info_reasons_30(io_in_bits_topdown_info_reasons_30),
    .io_in_bits_topdown_info_reasons_31(io_in_bits_topdown_info_reasons_31),
    .io_in_bits_topdown_info_reasons_32(io_in_bits_topdown_info_reasons_32),
    .io_in_bits_topdown_info_reasons_33(io_in_bits_topdown_info_reasons_33),
    .io_in_bits_topdown_info_reasons_34(io_in_bits_topdown_info_reasons_34),
    .io_in_bits_topdown_info_reasons_35(io_in_bits_topdown_info_reasons_35),
    .io_in_bits_topdown_info_reasons_36(io_in_bits_topdown_info_reasons_36),
    .io_in_bits_topdown_info_reasons_37(io_in_bits_topdown_info_reasons_37),
    .io_decodeCanAccept(io_decodeCanAccept),
    .io_stallReason_backReason_valid(io_stallReason_backReason_valid),
    .io_stallReason_backReason_bits(io_stallReason_backReason_bits),
    .io_in_ready(io_in_ready),
    .io_out_0_valid(io_out_0_valid),
    .io_out_0_bits_instr(io_out_0_bits_instr),
    .io_out_0_bits_pc(io_out_0_bits_pc),
    .io_out_0_bits_foldpc(io_out_0_bits_foldpc),
    .io_out_0_bits_exceptionVec_1(io_out_0_bits_exceptionVec_1),
    .io_out_0_bits_exceptionVec_2(io_out_0_bits_exceptionVec_2),
    .io_out_0_bits_exceptionVec_12(io_out_0_bits_exceptionVec_12),
    .io_out_0_bits_exceptionVec_20(io_out_0_bits_exceptionVec_20),
    .io_out_0_bits_backendException(io_out_0_bits_backendException),
    .io_out_0_bits_trigger(io_out_0_bits_trigger),
    .io_out_0_bits_pd_isRVC(io_out_0_bits_pd_isRVC),
    .io_out_0_bits_pd_brType(io_out_0_bits_pd_brType),
    .io_out_0_bits_pred_taken(io_out_0_bits_pred_taken),
    .io_out_0_bits_crossPageIPFFix(io_out_0_bits_crossPageIPFFix),
    .io_out_0_bits_ftqPtr_flag(io_out_0_bits_ftqPtr_flag),
    .io_out_0_bits_ftqPtr_value(io_out_0_bits_ftqPtr_value),
    .io_out_0_bits_ftqOffset(io_out_0_bits_ftqOffset),
    .io_out_0_bits_isLastInFtqEntry(io_out_0_bits_isLastInFtqEntry),
    .io_out_1_valid(io_out_1_valid),
    .io_out_1_bits_instr(io_out_1_bits_instr),
    .io_out_1_bits_pc(io_out_1_bits_pc),
    .io_out_1_bits_foldpc(io_out_1_bits_foldpc),
    .io_out_1_bits_exceptionVec_1(io_out_1_bits_exceptionVec_1),
    .io_out_1_bits_exceptionVec_2(io_out_1_bits_exceptionVec_2),
    .io_out_1_bits_exceptionVec_12(io_out_1_bits_exceptionVec_12),
    .io_out_1_bits_exceptionVec_20(io_out_1_bits_exceptionVec_20),
    .io_out_1_bits_backendException(io_out_1_bits_backendException),
    .io_out_1_bits_trigger(io_out_1_bits_trigger),
    .io_out_1_bits_pd_isRVC(io_out_1_bits_pd_isRVC),
    .io_out_1_bits_pd_brType(io_out_1_bits_pd_brType),
    .io_out_1_bits_pred_taken(io_out_1_bits_pred_taken),
    .io_out_1_bits_crossPageIPFFix(io_out_1_bits_crossPageIPFFix),
    .io_out_1_bits_ftqPtr_flag(io_out_1_bits_ftqPtr_flag),
    .io_out_1_bits_ftqPtr_value(io_out_1_bits_ftqPtr_value),
    .io_out_1_bits_ftqOffset(io_out_1_bits_ftqOffset),
    .io_out_1_bits_isLastInFtqEntry(io_out_1_bits_isLastInFtqEntry),
    .io_out_2_valid(io_out_2_valid),
    .io_out_2_bits_instr(io_out_2_bits_instr),
    .io_out_2_bits_pc(io_out_2_bits_pc),
    .io_out_2_bits_foldpc(io_out_2_bits_foldpc),
    .io_out_2_bits_exceptionVec_1(io_out_2_bits_exceptionVec_1),
    .io_out_2_bits_exceptionVec_2(io_out_2_bits_exceptionVec_2),
    .io_out_2_bits_exceptionVec_12(io_out_2_bits_exceptionVec_12),
    .io_out_2_bits_exceptionVec_20(io_out_2_bits_exceptionVec_20),
    .io_out_2_bits_backendException(io_out_2_bits_backendException),
    .io_out_2_bits_trigger(io_out_2_bits_trigger),
    .io_out_2_bits_pd_isRVC(io_out_2_bits_pd_isRVC),
    .io_out_2_bits_pd_brType(io_out_2_bits_pd_brType),
    .io_out_2_bits_pred_taken(io_out_2_bits_pred_taken),
    .io_out_2_bits_crossPageIPFFix(io_out_2_bits_crossPageIPFFix),
    .io_out_2_bits_ftqPtr_flag(io_out_2_bits_ftqPtr_flag),
    .io_out_2_bits_ftqPtr_value(io_out_2_bits_ftqPtr_value),
    .io_out_2_bits_ftqOffset(io_out_2_bits_ftqOffset),
    .io_out_2_bits_isLastInFtqEntry(io_out_2_bits_isLastInFtqEntry),
    .io_out_3_valid(io_out_3_valid),
    .io_out_3_bits_instr(io_out_3_bits_instr),
    .io_out_3_bits_pc(io_out_3_bits_pc),
    .io_out_3_bits_foldpc(io_out_3_bits_foldpc),
    .io_out_3_bits_exceptionVec_1(io_out_3_bits_exceptionVec_1),
    .io_out_3_bits_exceptionVec_2(io_out_3_bits_exceptionVec_2),
    .io_out_3_bits_exceptionVec_12(io_out_3_bits_exceptionVec_12),
    .io_out_3_bits_exceptionVec_20(io_out_3_bits_exceptionVec_20),
    .io_out_3_bits_backendException(io_out_3_bits_backendException),
    .io_out_3_bits_trigger(io_out_3_bits_trigger),
    .io_out_3_bits_pd_isRVC(io_out_3_bits_pd_isRVC),
    .io_out_3_bits_pd_brType(io_out_3_bits_pd_brType),
    .io_out_3_bits_pred_taken(io_out_3_bits_pred_taken),
    .io_out_3_bits_crossPageIPFFix(io_out_3_bits_crossPageIPFFix),
    .io_out_3_bits_ftqPtr_flag(io_out_3_bits_ftqPtr_flag),
    .io_out_3_bits_ftqPtr_value(io_out_3_bits_ftqPtr_value),
    .io_out_3_bits_ftqOffset(io_out_3_bits_ftqOffset),
    .io_out_3_bits_isLastInFtqEntry(io_out_3_bits_isLastInFtqEntry),
    .io_out_4_valid(io_out_4_valid),
    .io_out_4_bits_instr(io_out_4_bits_instr),
    .io_out_4_bits_pc(io_out_4_bits_pc),
    .io_out_4_bits_foldpc(io_out_4_bits_foldpc),
    .io_out_4_bits_exceptionVec_1(io_out_4_bits_exceptionVec_1),
    .io_out_4_bits_exceptionVec_2(io_out_4_bits_exceptionVec_2),
    .io_out_4_bits_exceptionVec_12(io_out_4_bits_exceptionVec_12),
    .io_out_4_bits_exceptionVec_20(io_out_4_bits_exceptionVec_20),
    .io_out_4_bits_backendException(io_out_4_bits_backendException),
    .io_out_4_bits_trigger(io_out_4_bits_trigger),
    .io_out_4_bits_pd_isRVC(io_out_4_bits_pd_isRVC),
    .io_out_4_bits_pd_brType(io_out_4_bits_pd_brType),
    .io_out_4_bits_pred_taken(io_out_4_bits_pred_taken),
    .io_out_4_bits_crossPageIPFFix(io_out_4_bits_crossPageIPFFix),
    .io_out_4_bits_ftqPtr_flag(io_out_4_bits_ftqPtr_flag),
    .io_out_4_bits_ftqPtr_value(io_out_4_bits_ftqPtr_value),
    .io_out_4_bits_ftqOffset(io_out_4_bits_ftqOffset),
    .io_out_4_bits_isLastInFtqEntry(io_out_4_bits_isLastInFtqEntry),
    .io_out_5_valid(io_out_5_valid),
    .io_out_5_bits_instr(io_out_5_bits_instr),
    .io_out_5_bits_pc(io_out_5_bits_pc),
    .io_out_5_bits_foldpc(io_out_5_bits_foldpc),
    .io_out_5_bits_exceptionVec_1(io_out_5_bits_exceptionVec_1),
    .io_out_5_bits_exceptionVec_2(io_out_5_bits_exceptionVec_2),
    .io_out_5_bits_exceptionVec_12(io_out_5_bits_exceptionVec_12),
    .io_out_5_bits_exceptionVec_20(io_out_5_bits_exceptionVec_20),
    .io_out_5_bits_backendException(io_out_5_bits_backendException),
    .io_out_5_bits_trigger(io_out_5_bits_trigger),
    .io_out_5_bits_pd_isRVC(io_out_5_bits_pd_isRVC),
    .io_out_5_bits_pd_brType(io_out_5_bits_pd_brType),
    .io_out_5_bits_pred_taken(io_out_5_bits_pred_taken),
    .io_out_5_bits_crossPageIPFFix(io_out_5_bits_crossPageIPFFix),
    .io_out_5_bits_ftqPtr_flag(io_out_5_bits_ftqPtr_flag),
    .io_out_5_bits_ftqPtr_value(io_out_5_bits_ftqPtr_value),
    .io_out_5_bits_ftqOffset(io_out_5_bits_ftqOffset),
    .io_out_5_bits_isLastInFtqEntry(io_out_5_bits_isLastInFtqEntry),
    .io_stallReason_reason_0(io_stallReason_reason_0),
    .io_stallReason_reason_1(io_stallReason_reason_1),
    .io_stallReason_reason_2(io_stallReason_reason_2),
    .io_stallReason_reason_3(io_stallReason_reason_3),
    .io_stallReason_reason_4(io_stallReason_reason_4),
    .io_stallReason_reason_5(io_stallReason_reason_5),
    .io_perf_0_value(io_perf_0_value),
    .io_perf_1_value(io_perf_1_value),
    .io_perf_2_value(io_perf_2_value),
    .io_perf_3_value(io_perf_3_value),
    .io_perf_4_value(io_perf_4_value),
    .io_perf_5_value(io_perf_5_value),
    .io_perf_6_value(io_perf_6_value),
    .io_perf_7_value(io_perf_7_value),
    .io_perf_8_value(io_perf_8_value)
  );
endmodule
