// 自动生成：scripts/gen_icache.py —— 勿手改
module ICache(
  input  clock,
  input  reset,
  output auto_ctrlUnitOpt_in_a_ready,
  input  auto_ctrlUnitOpt_in_a_valid,
  input  [3:0] auto_ctrlUnitOpt_in_a_bits_opcode,
  input  [1:0] auto_ctrlUnitOpt_in_a_bits_size,
  input  [2:0] auto_ctrlUnitOpt_in_a_bits_source,
  input  [29:0] auto_ctrlUnitOpt_in_a_bits_address,
  input  [7:0] auto_ctrlUnitOpt_in_a_bits_mask,
  input  [63:0] auto_ctrlUnitOpt_in_a_bits_data,
  input  auto_ctrlUnitOpt_in_d_ready,
  output auto_ctrlUnitOpt_in_d_valid,
  output [3:0] auto_ctrlUnitOpt_in_d_bits_opcode,
  output [1:0] auto_ctrlUnitOpt_in_d_bits_size,
  output [2:0] auto_ctrlUnitOpt_in_d_bits_source,
  output [63:0] auto_ctrlUnitOpt_in_d_bits_data,
  input  auto_client_out_a_ready,
  output auto_client_out_a_valid,
  output [3:0] auto_client_out_a_bits_source,
  output [47:0] auto_client_out_a_bits_address,
  input  auto_client_out_d_valid,
  input  [3:0] auto_client_out_d_bits_opcode,
  input  [2:0] auto_client_out_d_bits_size,
  input  [3:0] auto_client_out_d_bits_source,
  input  [255:0] auto_client_out_d_bits_data,
  input  auto_client_out_d_bits_corrupt,
  output io_fetch_req_ready,
  input  io_fetch_req_valid,
  input  [49:0] io_fetch_req_bits_pcMemRead_0_startAddr,
  input  [49:0] io_fetch_req_bits_pcMemRead_0_nextlineStart,
  input  [49:0] io_fetch_req_bits_pcMemRead_1_startAddr,
  input  [49:0] io_fetch_req_bits_pcMemRead_1_nextlineStart,
  input  [49:0] io_fetch_req_bits_pcMemRead_2_startAddr,
  input  [49:0] io_fetch_req_bits_pcMemRead_2_nextlineStart,
  input  [49:0] io_fetch_req_bits_pcMemRead_3_startAddr,
  input  [49:0] io_fetch_req_bits_pcMemRead_3_nextlineStart,
  input  [49:0] io_fetch_req_bits_pcMemRead_4_startAddr,
  input  [49:0] io_fetch_req_bits_pcMemRead_4_nextlineStart,
  input  io_fetch_req_bits_readValid_0,
  input  io_fetch_req_bits_readValid_1,
  input  io_fetch_req_bits_readValid_2,
  input  io_fetch_req_bits_readValid_3,
  input  io_fetch_req_bits_readValid_4,
  input  io_fetch_req_bits_backendException,
  output io_fetch_resp_valid,
  output io_fetch_resp_bits_doubleline,
  output [49:0] io_fetch_resp_bits_vaddr_0,
  output [49:0] io_fetch_resp_bits_vaddr_1,
  output [511:0] io_fetch_resp_bits_data,
  output [47:0] io_fetch_resp_bits_paddr_0,
  output [1:0] io_fetch_resp_bits_exception_0,
  output [1:0] io_fetch_resp_bits_exception_1,
  output io_fetch_resp_bits_pmp_mmio_0,
  output io_fetch_resp_bits_pmp_mmio_1,
  output [1:0] io_fetch_resp_bits_itlb_pbmt_0,
  output [1:0] io_fetch_resp_bits_itlb_pbmt_1,
  output io_fetch_resp_bits_backendException,
  output [55:0] io_fetch_resp_bits_gpaddr,
  output io_fetch_resp_bits_isForVSnonLeafPTE,
  output io_fetch_topdownIcacheMiss,
  output io_fetch_topdownItlbMiss,
  output io_ftqPrefetch_req_ready,
  input  io_ftqPrefetch_req_valid,
  input  [49:0] io_ftqPrefetch_req_bits_startAddr,
  input  [49:0] io_ftqPrefetch_req_bits_nextlineStart,
  input  io_ftqPrefetch_req_bits_ftqIdx_flag,
  input  [5:0] io_ftqPrefetch_req_bits_ftqIdx_value,
  input  io_ftqPrefetch_flushFromBpu_s2_valid,
  input  io_ftqPrefetch_flushFromBpu_s2_bits_flag,
  input  [5:0] io_ftqPrefetch_flushFromBpu_s2_bits_value,
  input  io_ftqPrefetch_flushFromBpu_s3_valid,
  input  io_ftqPrefetch_flushFromBpu_s3_bits_flag,
  input  [5:0] io_ftqPrefetch_flushFromBpu_s3_bits_value,
  input  [1:0] io_ftqPrefetch_backendException,
  input  io_softPrefetch_0_valid,
  input  [49:0] io_softPrefetch_0_bits_vaddr,
  input  io_softPrefetch_1_valid,
  input  [49:0] io_softPrefetch_1_bits_vaddr,
  input  io_softPrefetch_2_valid,
  input  [49:0] io_softPrefetch_2_bits_vaddr,
  input  io_stop,
  output io_toIFU,
  output [47:0] io_pmp_0_req_bits_addr,
  input  io_pmp_0_resp_instr,
  input  io_pmp_0_resp_mmio,
  output [47:0] io_pmp_1_req_bits_addr,
  input  io_pmp_1_resp_instr,
  input  io_pmp_1_resp_mmio,
  output [47:0] io_pmp_2_req_bits_addr,
  input  io_pmp_2_resp_instr,
  input  io_pmp_2_resp_mmio,
  output [47:0] io_pmp_3_req_bits_addr,
  input  io_pmp_3_resp_instr,
  input  io_pmp_3_resp_mmio,
  output io_itlb_0_req_valid,
  output [49:0] io_itlb_0_req_bits_vaddr,
  input  [47:0] io_itlb_0_resp_bits_paddr_0,
  input  [63:0] io_itlb_0_resp_bits_gpaddr_0,
  input  [1:0] io_itlb_0_resp_bits_pbmt_0,
  input  io_itlb_0_resp_bits_miss,
  input  io_itlb_0_resp_bits_isForVSnonLeafPTE,
  input  io_itlb_0_resp_bits_excp_0_gpf_instr,
  input  io_itlb_0_resp_bits_excp_0_pf_instr,
  input  io_itlb_0_resp_bits_excp_0_af_instr,
  output io_itlb_1_req_valid,
  output [49:0] io_itlb_1_req_bits_vaddr,
  input  [47:0] io_itlb_1_resp_bits_paddr_0,
  input  [63:0] io_itlb_1_resp_bits_gpaddr_0,
  input  [1:0] io_itlb_1_resp_bits_pbmt_0,
  input  io_itlb_1_resp_bits_miss,
  input  io_itlb_1_resp_bits_isForVSnonLeafPTE,
  input  io_itlb_1_resp_bits_excp_0_gpf_instr,
  input  io_itlb_1_resp_bits_excp_0_pf_instr,
  input  io_itlb_1_resp_bits_excp_0_af_instr,
  output io_itlbFlushPipe,
  output io_error_valid,
  output [47:0] io_error_bits_paddr,
  output io_error_bits_report_to_beu,
  input  io_csr_pf_enable,
  input  io_fencei,
  input  io_flush,
  input  io_wfi_wfiReq,
  output io_wfi_wfiSafe,
  output io_perfInfo_only_0_hit,
  output io_perfInfo_only_0_miss,
  output io_perfInfo_hit_0_hit_1,
  output io_perfInfo_hit_0_miss_1,
  output io_perfInfo_miss_0_hit_1,
  output io_perfInfo_miss_0_miss_1,
  output io_perfInfo_hit_0_except_1,
  output io_perfInfo_miss_0_except_1,
  output io_perfInfo_except_0,
  output io_perfInfo_bank_hit_0,
  output io_perfInfo_bank_hit_1,
  output io_perfInfo_hit,
  input  [1:0] boreChildrenBd_bore_array,
  input  boreChildrenBd_bore_all,
  input  boreChildrenBd_bore_req,
  output boreChildrenBd_bore_ack,
  input  boreChildrenBd_bore_writeen,
  input  [1:0] boreChildrenBd_bore_be,
  input  [7:0] boreChildrenBd_bore_addr,
  input  [73:0] boreChildrenBd_bore_indata,
  input  boreChildrenBd_bore_readen,
  input  [7:0] boreChildrenBd_bore_addr_rd,
  output [73:0] boreChildrenBd_bore_outdata,
  input  [3:0] boreChildrenBd_bore_1_array,
  input  boreChildrenBd_bore_1_all,
  input  boreChildrenBd_bore_1_req,
  output boreChildrenBd_bore_1_ack,
  input  boreChildrenBd_bore_1_writeen,
  input  boreChildrenBd_bore_1_be,
  input  [8:0] boreChildrenBd_bore_1_addr,
  input  [65:0] boreChildrenBd_bore_1_indata,
  input  boreChildrenBd_bore_1_readen,
  input  [8:0] boreChildrenBd_bore_1_addr_rd,
  output [65:0] boreChildrenBd_bore_1_outdata,
  input  [4:0] boreChildrenBd_bore_2_array,
  input  boreChildrenBd_bore_2_all,
  input  boreChildrenBd_bore_2_req,
  output boreChildrenBd_bore_2_ack,
  input  boreChildrenBd_bore_2_writeen,
  input  boreChildrenBd_bore_2_be,
  input  [8:0] boreChildrenBd_bore_2_addr,
  input  [65:0] boreChildrenBd_bore_2_indata,
  input  boreChildrenBd_bore_2_readen,
  input  [8:0] boreChildrenBd_bore_2_addr_rd,
  output [65:0] boreChildrenBd_bore_2_outdata,
  input  [4:0] boreChildrenBd_bore_3_array,
  input  boreChildrenBd_bore_3_all,
  input  boreChildrenBd_bore_3_req,
  output boreChildrenBd_bore_3_ack,
  input  boreChildrenBd_bore_3_writeen,
  input  boreChildrenBd_bore_3_be,
  input  [8:0] boreChildrenBd_bore_3_addr,
  input  [65:0] boreChildrenBd_bore_3_indata,
  input  boreChildrenBd_bore_3_readen,
  input  [8:0] boreChildrenBd_bore_3_addr_rd,
  output [65:0] boreChildrenBd_bore_3_outdata,
  input  [5:0] boreChildrenBd_bore_4_array,
  input  boreChildrenBd_bore_4_all,
  input  boreChildrenBd_bore_4_req,
  output boreChildrenBd_bore_4_ack,
  input  boreChildrenBd_bore_4_writeen,
  input  boreChildrenBd_bore_4_be,
  input  [8:0] boreChildrenBd_bore_4_addr,
  input  [65:0] boreChildrenBd_bore_4_indata,
  input  boreChildrenBd_bore_4_readen,
  input  [8:0] boreChildrenBd_bore_4_addr_rd,
  output [65:0] boreChildrenBd_bore_4_outdata,
  input  sigFromSrams_bore_ram_hold,
  input  sigFromSrams_bore_ram_bypass,
  input  sigFromSrams_bore_ram_bp_clken,
  input  sigFromSrams_bore_ram_aux_clk,
  input  sigFromSrams_bore_ram_aux_ckbp,
  input  sigFromSrams_bore_ram_mcp_hold,
  input  sigFromSrams_bore_cgen,
  input  sigFromSrams_bore_1_ram_hold,
  input  sigFromSrams_bore_1_ram_bypass,
  input  sigFromSrams_bore_1_ram_bp_clken,
  input  sigFromSrams_bore_1_ram_aux_clk,
  input  sigFromSrams_bore_1_ram_aux_ckbp,
  input  sigFromSrams_bore_1_ram_mcp_hold,
  input  sigFromSrams_bore_1_cgen,
  input  sigFromSrams_bore_2_ram_hold,
  input  sigFromSrams_bore_2_ram_bypass,
  input  sigFromSrams_bore_2_ram_bp_clken,
  input  sigFromSrams_bore_2_ram_aux_clk,
  input  sigFromSrams_bore_2_ram_aux_ckbp,
  input  sigFromSrams_bore_2_ram_mcp_hold,
  input  sigFromSrams_bore_2_cgen,
  input  sigFromSrams_bore_3_ram_hold,
  input  sigFromSrams_bore_3_ram_bypass,
  input  sigFromSrams_bore_3_ram_bp_clken,
  input  sigFromSrams_bore_3_ram_aux_clk,
  input  sigFromSrams_bore_3_ram_aux_ckbp,
  input  sigFromSrams_bore_3_ram_mcp_hold,
  input  sigFromSrams_bore_3_cgen,
  input  sigFromSrams_bore_4_ram_hold,
  input  sigFromSrams_bore_4_ram_bypass,
  input  sigFromSrams_bore_4_ram_bp_clken,
  input  sigFromSrams_bore_4_ram_aux_clk,
  input  sigFromSrams_bore_4_ram_aux_ckbp,
  input  sigFromSrams_bore_4_ram_mcp_hold,
  input  sigFromSrams_bore_4_cgen,
  input  sigFromSrams_bore_5_ram_hold,
  input  sigFromSrams_bore_5_ram_bypass,
  input  sigFromSrams_bore_5_ram_bp_clken,
  input  sigFromSrams_bore_5_ram_aux_clk,
  input  sigFromSrams_bore_5_ram_aux_ckbp,
  input  sigFromSrams_bore_5_ram_mcp_hold,
  input  sigFromSrams_bore_5_cgen,
  input  sigFromSrams_bore_6_ram_hold,
  input  sigFromSrams_bore_6_ram_bypass,
  input  sigFromSrams_bore_6_ram_bp_clken,
  input  sigFromSrams_bore_6_ram_aux_clk,
  input  sigFromSrams_bore_6_ram_aux_ckbp,
  input  sigFromSrams_bore_6_ram_mcp_hold,
  input  sigFromSrams_bore_6_cgen,
  input  sigFromSrams_bore_7_ram_hold,
  input  sigFromSrams_bore_7_ram_bypass,
  input  sigFromSrams_bore_7_ram_bp_clken,
  input  sigFromSrams_bore_7_ram_aux_clk,
  input  sigFromSrams_bore_7_ram_aux_ckbp,
  input  sigFromSrams_bore_7_ram_mcp_hold,
  input  sigFromSrams_bore_7_cgen,
  input  sigFromSrams_bore_8_ram_hold,
  input  sigFromSrams_bore_8_ram_bypass,
  input  sigFromSrams_bore_8_ram_bp_clken,
  input  sigFromSrams_bore_8_ram_aux_clk,
  input  sigFromSrams_bore_8_ram_aux_ckbp,
  input  sigFromSrams_bore_8_ram_mcp_hold,
  input  sigFromSrams_bore_8_cgen,
  input  sigFromSrams_bore_9_ram_hold,
  input  sigFromSrams_bore_9_ram_bypass,
  input  sigFromSrams_bore_9_ram_bp_clken,
  input  sigFromSrams_bore_9_ram_aux_clk,
  input  sigFromSrams_bore_9_ram_aux_ckbp,
  input  sigFromSrams_bore_9_ram_mcp_hold,
  input  sigFromSrams_bore_9_cgen,
  input  sigFromSrams_bore_10_ram_hold,
  input  sigFromSrams_bore_10_ram_bypass,
  input  sigFromSrams_bore_10_ram_bp_clken,
  input  sigFromSrams_bore_10_ram_aux_clk,
  input  sigFromSrams_bore_10_ram_aux_ckbp,
  input  sigFromSrams_bore_10_ram_mcp_hold,
  input  sigFromSrams_bore_10_cgen,
  input  sigFromSrams_bore_11_ram_hold,
  input  sigFromSrams_bore_11_ram_bypass,
  input  sigFromSrams_bore_11_ram_bp_clken,
  input  sigFromSrams_bore_11_ram_aux_clk,
  input  sigFromSrams_bore_11_ram_aux_ckbp,
  input  sigFromSrams_bore_11_ram_mcp_hold,
  input  sigFromSrams_bore_11_cgen,
  input  sigFromSrams_bore_12_ram_hold,
  input  sigFromSrams_bore_12_ram_bypass,
  input  sigFromSrams_bore_12_ram_bp_clken,
  input  sigFromSrams_bore_12_ram_aux_clk,
  input  sigFromSrams_bore_12_ram_aux_ckbp,
  input  sigFromSrams_bore_12_ram_mcp_hold,
  input  sigFromSrams_bore_12_cgen,
  input  sigFromSrams_bore_13_ram_hold,
  input  sigFromSrams_bore_13_ram_bypass,
  input  sigFromSrams_bore_13_ram_bp_clken,
  input  sigFromSrams_bore_13_ram_aux_clk,
  input  sigFromSrams_bore_13_ram_aux_ckbp,
  input  sigFromSrams_bore_13_ram_mcp_hold,
  input  sigFromSrams_bore_13_cgen,
  input  sigFromSrams_bore_14_ram_hold,
  input  sigFromSrams_bore_14_ram_bypass,
  input  sigFromSrams_bore_14_ram_bp_clken,
  input  sigFromSrams_bore_14_ram_aux_clk,
  input  sigFromSrams_bore_14_ram_aux_ckbp,
  input  sigFromSrams_bore_14_ram_mcp_hold,
  input  sigFromSrams_bore_14_cgen,
  input  sigFromSrams_bore_15_ram_hold,
  input  sigFromSrams_bore_15_ram_bypass,
  input  sigFromSrams_bore_15_ram_bp_clken,
  input  sigFromSrams_bore_15_ram_aux_clk,
  input  sigFromSrams_bore_15_ram_aux_ckbp,
  input  sigFromSrams_bore_15_ram_mcp_hold,
  input  sigFromSrams_bore_15_cgen,
  input  sigFromSrams_bore_16_ram_hold,
  input  sigFromSrams_bore_16_ram_bypass,
  input  sigFromSrams_bore_16_ram_bp_clken,
  input  sigFromSrams_bore_16_ram_aux_clk,
  input  sigFromSrams_bore_16_ram_aux_ckbp,
  input  sigFromSrams_bore_16_ram_mcp_hold,
  input  sigFromSrams_bore_16_cgen,
  input  sigFromSrams_bore_17_ram_hold,
  input  sigFromSrams_bore_17_ram_bypass,
  input  sigFromSrams_bore_17_ram_bp_clken,
  input  sigFromSrams_bore_17_ram_aux_clk,
  input  sigFromSrams_bore_17_ram_aux_ckbp,
  input  sigFromSrams_bore_17_ram_mcp_hold,
  input  sigFromSrams_bore_17_cgen,
  input  sigFromSrams_bore_18_ram_hold,
  input  sigFromSrams_bore_18_ram_bypass,
  input  sigFromSrams_bore_18_ram_bp_clken,
  input  sigFromSrams_bore_18_ram_aux_clk,
  input  sigFromSrams_bore_18_ram_aux_ckbp,
  input  sigFromSrams_bore_18_ram_mcp_hold,
  input  sigFromSrams_bore_18_cgen,
  input  sigFromSrams_bore_19_ram_hold,
  input  sigFromSrams_bore_19_ram_bypass,
  input  sigFromSrams_bore_19_ram_bp_clken,
  input  sigFromSrams_bore_19_ram_aux_clk,
  input  sigFromSrams_bore_19_ram_aux_ckbp,
  input  sigFromSrams_bore_19_ram_mcp_hold,
  input  sigFromSrams_bore_19_cgen,
  input  sigFromSrams_bore_20_ram_hold,
  input  sigFromSrams_bore_20_ram_bypass,
  input  sigFromSrams_bore_20_ram_bp_clken,
  input  sigFromSrams_bore_20_ram_aux_clk,
  input  sigFromSrams_bore_20_ram_aux_ckbp,
  input  sigFromSrams_bore_20_ram_mcp_hold,
  input  sigFromSrams_bore_20_cgen,
  input  sigFromSrams_bore_21_ram_hold,
  input  sigFromSrams_bore_21_ram_bypass,
  input  sigFromSrams_bore_21_ram_bp_clken,
  input  sigFromSrams_bore_21_ram_aux_clk,
  input  sigFromSrams_bore_21_ram_aux_ckbp,
  input  sigFromSrams_bore_21_ram_mcp_hold,
  input  sigFromSrams_bore_21_cgen,
  input  sigFromSrams_bore_22_ram_hold,
  input  sigFromSrams_bore_22_ram_bypass,
  input  sigFromSrams_bore_22_ram_bp_clken,
  input  sigFromSrams_bore_22_ram_aux_clk,
  input  sigFromSrams_bore_22_ram_aux_ckbp,
  input  sigFromSrams_bore_22_ram_mcp_hold,
  input  sigFromSrams_bore_22_cgen,
  input  sigFromSrams_bore_23_ram_hold,
  input  sigFromSrams_bore_23_ram_bypass,
  input  sigFromSrams_bore_23_ram_bp_clken,
  input  sigFromSrams_bore_23_ram_aux_clk,
  input  sigFromSrams_bore_23_ram_aux_ckbp,
  input  sigFromSrams_bore_23_ram_mcp_hold,
  input  sigFromSrams_bore_23_cgen,
  input  sigFromSrams_bore_24_ram_hold,
  input  sigFromSrams_bore_24_ram_bypass,
  input  sigFromSrams_bore_24_ram_bp_clken,
  input  sigFromSrams_bore_24_ram_aux_clk,
  input  sigFromSrams_bore_24_ram_aux_ckbp,
  input  sigFromSrams_bore_24_ram_mcp_hold,
  input  sigFromSrams_bore_24_cgen,
  input  sigFromSrams_bore_25_ram_hold,
  input  sigFromSrams_bore_25_ram_bypass,
  input  sigFromSrams_bore_25_ram_bp_clken,
  input  sigFromSrams_bore_25_ram_aux_clk,
  input  sigFromSrams_bore_25_ram_aux_ckbp,
  input  sigFromSrams_bore_25_ram_mcp_hold,
  input  sigFromSrams_bore_25_cgen,
  input  sigFromSrams_bore_26_ram_hold,
  input  sigFromSrams_bore_26_ram_bypass,
  input  sigFromSrams_bore_26_ram_bp_clken,
  input  sigFromSrams_bore_26_ram_aux_clk,
  input  sigFromSrams_bore_26_ram_aux_ckbp,
  input  sigFromSrams_bore_26_ram_mcp_hold,
  input  sigFromSrams_bore_26_cgen,
  input  sigFromSrams_bore_27_ram_hold,
  input  sigFromSrams_bore_27_ram_bypass,
  input  sigFromSrams_bore_27_ram_bp_clken,
  input  sigFromSrams_bore_27_ram_aux_clk,
  input  sigFromSrams_bore_27_ram_aux_ckbp,
  input  sigFromSrams_bore_27_ram_mcp_hold,
  input  sigFromSrams_bore_27_cgen,
  input  sigFromSrams_bore_28_ram_hold,
  input  sigFromSrams_bore_28_ram_bypass,
  input  sigFromSrams_bore_28_ram_bp_clken,
  input  sigFromSrams_bore_28_ram_aux_clk,
  input  sigFromSrams_bore_28_ram_aux_ckbp,
  input  sigFromSrams_bore_28_ram_mcp_hold,
  input  sigFromSrams_bore_28_cgen,
  input  sigFromSrams_bore_29_ram_hold,
  input  sigFromSrams_bore_29_ram_bypass,
  input  sigFromSrams_bore_29_ram_bp_clken,
  input  sigFromSrams_bore_29_ram_aux_clk,
  input  sigFromSrams_bore_29_ram_aux_ckbp,
  input  sigFromSrams_bore_29_ram_mcp_hold,
  input  sigFromSrams_bore_29_cgen,
  input  sigFromSrams_bore_30_ram_hold,
  input  sigFromSrams_bore_30_ram_bypass,
  input  sigFromSrams_bore_30_ram_bp_clken,
  input  sigFromSrams_bore_30_ram_aux_clk,
  input  sigFromSrams_bore_30_ram_aux_ckbp,
  input  sigFromSrams_bore_30_ram_mcp_hold,
  input  sigFromSrams_bore_30_cgen,
  input  sigFromSrams_bore_31_ram_hold,
  input  sigFromSrams_bore_31_ram_bypass,
  input  sigFromSrams_bore_31_ram_bp_clken,
  input  sigFromSrams_bore_31_ram_aux_clk,
  input  sigFromSrams_bore_31_ram_aux_ckbp,
  input  sigFromSrams_bore_31_ram_mcp_hold,
  input  sigFromSrams_bore_31_cgen,
  input  sigFromSrams_bore_32_ram_hold,
  input  sigFromSrams_bore_32_ram_bypass,
  input  sigFromSrams_bore_32_ram_bp_clken,
  input  sigFromSrams_bore_32_ram_aux_clk,
  input  sigFromSrams_bore_32_ram_aux_ckbp,
  input  sigFromSrams_bore_32_ram_mcp_hold,
  input  sigFromSrams_bore_32_cgen,
  input  sigFromSrams_bore_33_ram_hold,
  input  sigFromSrams_bore_33_ram_bypass,
  input  sigFromSrams_bore_33_ram_bp_clken,
  input  sigFromSrams_bore_33_ram_aux_clk,
  input  sigFromSrams_bore_33_ram_aux_ckbp,
  input  sigFromSrams_bore_33_ram_mcp_hold,
  input  sigFromSrams_bore_33_cgen,
  input  sigFromSrams_bore_34_ram_hold,
  input  sigFromSrams_bore_34_ram_bypass,
  input  sigFromSrams_bore_34_ram_bp_clken,
  input  sigFromSrams_bore_34_ram_aux_clk,
  input  sigFromSrams_bore_34_ram_aux_ckbp,
  input  sigFromSrams_bore_34_ram_mcp_hold,
  input  sigFromSrams_bore_34_cgen,
  input  sigFromSrams_bore_35_ram_hold,
  input  sigFromSrams_bore_35_ram_bypass,
  input  sigFromSrams_bore_35_ram_bp_clken,
  input  sigFromSrams_bore_35_ram_aux_clk,
  input  sigFromSrams_bore_35_ram_aux_ckbp,
  input  sigFromSrams_bore_35_ram_mcp_hold,
  input  sigFromSrams_bore_35_cgen
);
  xs_ICache_core u_core (
    .clock(clock),
    .reset(reset),
    .auto_ctrlUnitOpt_in_a_ready(auto_ctrlUnitOpt_in_a_ready),
    .auto_ctrlUnitOpt_in_a_valid(auto_ctrlUnitOpt_in_a_valid),
    .auto_ctrlUnitOpt_in_a_bits_opcode(auto_ctrlUnitOpt_in_a_bits_opcode),
    .auto_ctrlUnitOpt_in_a_bits_size(auto_ctrlUnitOpt_in_a_bits_size),
    .auto_ctrlUnitOpt_in_a_bits_source(auto_ctrlUnitOpt_in_a_bits_source),
    .auto_ctrlUnitOpt_in_a_bits_address(auto_ctrlUnitOpt_in_a_bits_address),
    .auto_ctrlUnitOpt_in_a_bits_mask(auto_ctrlUnitOpt_in_a_bits_mask),
    .auto_ctrlUnitOpt_in_a_bits_data(auto_ctrlUnitOpt_in_a_bits_data),
    .auto_ctrlUnitOpt_in_d_ready(auto_ctrlUnitOpt_in_d_ready),
    .auto_ctrlUnitOpt_in_d_valid(auto_ctrlUnitOpt_in_d_valid),
    .auto_ctrlUnitOpt_in_d_bits_opcode(auto_ctrlUnitOpt_in_d_bits_opcode),
    .auto_ctrlUnitOpt_in_d_bits_size(auto_ctrlUnitOpt_in_d_bits_size),
    .auto_ctrlUnitOpt_in_d_bits_source(auto_ctrlUnitOpt_in_d_bits_source),
    .auto_ctrlUnitOpt_in_d_bits_data(auto_ctrlUnitOpt_in_d_bits_data),
    .auto_client_out_a_ready(auto_client_out_a_ready),
    .auto_client_out_a_valid(auto_client_out_a_valid),
    .auto_client_out_a_bits_source(auto_client_out_a_bits_source),
    .auto_client_out_a_bits_address(auto_client_out_a_bits_address),
    .auto_client_out_d_valid(auto_client_out_d_valid),
    .auto_client_out_d_bits_opcode(auto_client_out_d_bits_opcode),
    .auto_client_out_d_bits_size(auto_client_out_d_bits_size),
    .auto_client_out_d_bits_source(auto_client_out_d_bits_source),
    .auto_client_out_d_bits_data(auto_client_out_d_bits_data),
    .auto_client_out_d_bits_corrupt(auto_client_out_d_bits_corrupt),
    .io_fetch_req_ready(io_fetch_req_ready),
    .io_fetch_req_valid(io_fetch_req_valid),
    .io_fetch_req_bits_pcMemRead_0_startAddr(io_fetch_req_bits_pcMemRead_0_startAddr),
    .io_fetch_req_bits_pcMemRead_0_nextlineStart(io_fetch_req_bits_pcMemRead_0_nextlineStart),
    .io_fetch_req_bits_pcMemRead_1_startAddr(io_fetch_req_bits_pcMemRead_1_startAddr),
    .io_fetch_req_bits_pcMemRead_1_nextlineStart(io_fetch_req_bits_pcMemRead_1_nextlineStart),
    .io_fetch_req_bits_pcMemRead_2_startAddr(io_fetch_req_bits_pcMemRead_2_startAddr),
    .io_fetch_req_bits_pcMemRead_2_nextlineStart(io_fetch_req_bits_pcMemRead_2_nextlineStart),
    .io_fetch_req_bits_pcMemRead_3_startAddr(io_fetch_req_bits_pcMemRead_3_startAddr),
    .io_fetch_req_bits_pcMemRead_3_nextlineStart(io_fetch_req_bits_pcMemRead_3_nextlineStart),
    .io_fetch_req_bits_pcMemRead_4_startAddr(io_fetch_req_bits_pcMemRead_4_startAddr),
    .io_fetch_req_bits_pcMemRead_4_nextlineStart(io_fetch_req_bits_pcMemRead_4_nextlineStart),
    .io_fetch_req_bits_readValid_0(io_fetch_req_bits_readValid_0),
    .io_fetch_req_bits_readValid_1(io_fetch_req_bits_readValid_1),
    .io_fetch_req_bits_readValid_2(io_fetch_req_bits_readValid_2),
    .io_fetch_req_bits_readValid_3(io_fetch_req_bits_readValid_3),
    .io_fetch_req_bits_readValid_4(io_fetch_req_bits_readValid_4),
    .io_fetch_req_bits_backendException(io_fetch_req_bits_backendException),
    .io_fetch_resp_valid(io_fetch_resp_valid),
    .io_fetch_resp_bits_doubleline(io_fetch_resp_bits_doubleline),
    .io_fetch_resp_bits_vaddr_0(io_fetch_resp_bits_vaddr_0),
    .io_fetch_resp_bits_vaddr_1(io_fetch_resp_bits_vaddr_1),
    .io_fetch_resp_bits_data(io_fetch_resp_bits_data),
    .io_fetch_resp_bits_paddr_0(io_fetch_resp_bits_paddr_0),
    .io_fetch_resp_bits_exception_0(io_fetch_resp_bits_exception_0),
    .io_fetch_resp_bits_exception_1(io_fetch_resp_bits_exception_1),
    .io_fetch_resp_bits_pmp_mmio_0(io_fetch_resp_bits_pmp_mmio_0),
    .io_fetch_resp_bits_pmp_mmio_1(io_fetch_resp_bits_pmp_mmio_1),
    .io_fetch_resp_bits_itlb_pbmt_0(io_fetch_resp_bits_itlb_pbmt_0),
    .io_fetch_resp_bits_itlb_pbmt_1(io_fetch_resp_bits_itlb_pbmt_1),
    .io_fetch_resp_bits_backendException(io_fetch_resp_bits_backendException),
    .io_fetch_resp_bits_gpaddr(io_fetch_resp_bits_gpaddr),
    .io_fetch_resp_bits_isForVSnonLeafPTE(io_fetch_resp_bits_isForVSnonLeafPTE),
    .io_fetch_topdownIcacheMiss(io_fetch_topdownIcacheMiss),
    .io_fetch_topdownItlbMiss(io_fetch_topdownItlbMiss),
    .io_ftqPrefetch_req_ready(io_ftqPrefetch_req_ready),
    .io_ftqPrefetch_req_valid(io_ftqPrefetch_req_valid),
    .io_ftqPrefetch_req_bits_startAddr(io_ftqPrefetch_req_bits_startAddr),
    .io_ftqPrefetch_req_bits_nextlineStart(io_ftqPrefetch_req_bits_nextlineStart),
    .io_ftqPrefetch_req_bits_ftqIdx_flag(io_ftqPrefetch_req_bits_ftqIdx_flag),
    .io_ftqPrefetch_req_bits_ftqIdx_value(io_ftqPrefetch_req_bits_ftqIdx_value),
    .io_ftqPrefetch_flushFromBpu_s2_valid(io_ftqPrefetch_flushFromBpu_s2_valid),
    .io_ftqPrefetch_flushFromBpu_s2_bits_flag(io_ftqPrefetch_flushFromBpu_s2_bits_flag),
    .io_ftqPrefetch_flushFromBpu_s2_bits_value(io_ftqPrefetch_flushFromBpu_s2_bits_value),
    .io_ftqPrefetch_flushFromBpu_s3_valid(io_ftqPrefetch_flushFromBpu_s3_valid),
    .io_ftqPrefetch_flushFromBpu_s3_bits_flag(io_ftqPrefetch_flushFromBpu_s3_bits_flag),
    .io_ftqPrefetch_flushFromBpu_s3_bits_value(io_ftqPrefetch_flushFromBpu_s3_bits_value),
    .io_ftqPrefetch_backendException(io_ftqPrefetch_backendException),
    .io_softPrefetch_0_valid(io_softPrefetch_0_valid),
    .io_softPrefetch_0_bits_vaddr(io_softPrefetch_0_bits_vaddr),
    .io_softPrefetch_1_valid(io_softPrefetch_1_valid),
    .io_softPrefetch_1_bits_vaddr(io_softPrefetch_1_bits_vaddr),
    .io_softPrefetch_2_valid(io_softPrefetch_2_valid),
    .io_softPrefetch_2_bits_vaddr(io_softPrefetch_2_bits_vaddr),
    .io_stop(io_stop),
    .io_toIFU(io_toIFU),
    .io_pmp_0_req_bits_addr(io_pmp_0_req_bits_addr),
    .io_pmp_0_resp_instr(io_pmp_0_resp_instr),
    .io_pmp_0_resp_mmio(io_pmp_0_resp_mmio),
    .io_pmp_1_req_bits_addr(io_pmp_1_req_bits_addr),
    .io_pmp_1_resp_instr(io_pmp_1_resp_instr),
    .io_pmp_1_resp_mmio(io_pmp_1_resp_mmio),
    .io_pmp_2_req_bits_addr(io_pmp_2_req_bits_addr),
    .io_pmp_2_resp_instr(io_pmp_2_resp_instr),
    .io_pmp_2_resp_mmio(io_pmp_2_resp_mmio),
    .io_pmp_3_req_bits_addr(io_pmp_3_req_bits_addr),
    .io_pmp_3_resp_instr(io_pmp_3_resp_instr),
    .io_pmp_3_resp_mmio(io_pmp_3_resp_mmio),
    .io_itlb_0_req_valid(io_itlb_0_req_valid),
    .io_itlb_0_req_bits_vaddr(io_itlb_0_req_bits_vaddr),
    .io_itlb_0_resp_bits_paddr_0(io_itlb_0_resp_bits_paddr_0),
    .io_itlb_0_resp_bits_gpaddr_0(io_itlb_0_resp_bits_gpaddr_0),
    .io_itlb_0_resp_bits_pbmt_0(io_itlb_0_resp_bits_pbmt_0),
    .io_itlb_0_resp_bits_miss(io_itlb_0_resp_bits_miss),
    .io_itlb_0_resp_bits_isForVSnonLeafPTE(io_itlb_0_resp_bits_isForVSnonLeafPTE),
    .io_itlb_0_resp_bits_excp_0_gpf_instr(io_itlb_0_resp_bits_excp_0_gpf_instr),
    .io_itlb_0_resp_bits_excp_0_pf_instr(io_itlb_0_resp_bits_excp_0_pf_instr),
    .io_itlb_0_resp_bits_excp_0_af_instr(io_itlb_0_resp_bits_excp_0_af_instr),
    .io_itlb_1_req_valid(io_itlb_1_req_valid),
    .io_itlb_1_req_bits_vaddr(io_itlb_1_req_bits_vaddr),
    .io_itlb_1_resp_bits_paddr_0(io_itlb_1_resp_bits_paddr_0),
    .io_itlb_1_resp_bits_gpaddr_0(io_itlb_1_resp_bits_gpaddr_0),
    .io_itlb_1_resp_bits_pbmt_0(io_itlb_1_resp_bits_pbmt_0),
    .io_itlb_1_resp_bits_miss(io_itlb_1_resp_bits_miss),
    .io_itlb_1_resp_bits_isForVSnonLeafPTE(io_itlb_1_resp_bits_isForVSnonLeafPTE),
    .io_itlb_1_resp_bits_excp_0_gpf_instr(io_itlb_1_resp_bits_excp_0_gpf_instr),
    .io_itlb_1_resp_bits_excp_0_pf_instr(io_itlb_1_resp_bits_excp_0_pf_instr),
    .io_itlb_1_resp_bits_excp_0_af_instr(io_itlb_1_resp_bits_excp_0_af_instr),
    .io_itlbFlushPipe(io_itlbFlushPipe),
    .io_error_valid(io_error_valid),
    .io_error_bits_paddr(io_error_bits_paddr),
    .io_error_bits_report_to_beu(io_error_bits_report_to_beu),
    .io_csr_pf_enable(io_csr_pf_enable),
    .io_fencei(io_fencei),
    .io_flush(io_flush),
    .io_wfi_wfiReq(io_wfi_wfiReq),
    .io_wfi_wfiSafe(io_wfi_wfiSafe),
    .io_perfInfo_only_0_hit(io_perfInfo_only_0_hit),
    .io_perfInfo_only_0_miss(io_perfInfo_only_0_miss),
    .io_perfInfo_hit_0_hit_1(io_perfInfo_hit_0_hit_1),
    .io_perfInfo_hit_0_miss_1(io_perfInfo_hit_0_miss_1),
    .io_perfInfo_miss_0_hit_1(io_perfInfo_miss_0_hit_1),
    .io_perfInfo_miss_0_miss_1(io_perfInfo_miss_0_miss_1),
    .io_perfInfo_hit_0_except_1(io_perfInfo_hit_0_except_1),
    .io_perfInfo_miss_0_except_1(io_perfInfo_miss_0_except_1),
    .io_perfInfo_except_0(io_perfInfo_except_0),
    .io_perfInfo_bank_hit_0(io_perfInfo_bank_hit_0),
    .io_perfInfo_bank_hit_1(io_perfInfo_bank_hit_1),
    .io_perfInfo_hit(io_perfInfo_hit),
    .boreChildrenBd_bore_array(boreChildrenBd_bore_array),
    .boreChildrenBd_bore_all(boreChildrenBd_bore_all),
    .boreChildrenBd_bore_req(boreChildrenBd_bore_req),
    .boreChildrenBd_bore_ack(boreChildrenBd_bore_ack),
    .boreChildrenBd_bore_writeen(boreChildrenBd_bore_writeen),
    .boreChildrenBd_bore_be(boreChildrenBd_bore_be),
    .boreChildrenBd_bore_addr(boreChildrenBd_bore_addr),
    .boreChildrenBd_bore_indata(boreChildrenBd_bore_indata),
    .boreChildrenBd_bore_readen(boreChildrenBd_bore_readen),
    .boreChildrenBd_bore_addr_rd(boreChildrenBd_bore_addr_rd),
    .boreChildrenBd_bore_outdata(boreChildrenBd_bore_outdata),
    .boreChildrenBd_bore_1_array(boreChildrenBd_bore_1_array),
    .boreChildrenBd_bore_1_all(boreChildrenBd_bore_1_all),
    .boreChildrenBd_bore_1_req(boreChildrenBd_bore_1_req),
    .boreChildrenBd_bore_1_ack(boreChildrenBd_bore_1_ack),
    .boreChildrenBd_bore_1_writeen(boreChildrenBd_bore_1_writeen),
    .boreChildrenBd_bore_1_be(boreChildrenBd_bore_1_be),
    .boreChildrenBd_bore_1_addr(boreChildrenBd_bore_1_addr),
    .boreChildrenBd_bore_1_indata(boreChildrenBd_bore_1_indata),
    .boreChildrenBd_bore_1_readen(boreChildrenBd_bore_1_readen),
    .boreChildrenBd_bore_1_addr_rd(boreChildrenBd_bore_1_addr_rd),
    .boreChildrenBd_bore_1_outdata(boreChildrenBd_bore_1_outdata),
    .boreChildrenBd_bore_2_array(boreChildrenBd_bore_2_array),
    .boreChildrenBd_bore_2_all(boreChildrenBd_bore_2_all),
    .boreChildrenBd_bore_2_req(boreChildrenBd_bore_2_req),
    .boreChildrenBd_bore_2_ack(boreChildrenBd_bore_2_ack),
    .boreChildrenBd_bore_2_writeen(boreChildrenBd_bore_2_writeen),
    .boreChildrenBd_bore_2_be(boreChildrenBd_bore_2_be),
    .boreChildrenBd_bore_2_addr(boreChildrenBd_bore_2_addr),
    .boreChildrenBd_bore_2_indata(boreChildrenBd_bore_2_indata),
    .boreChildrenBd_bore_2_readen(boreChildrenBd_bore_2_readen),
    .boreChildrenBd_bore_2_addr_rd(boreChildrenBd_bore_2_addr_rd),
    .boreChildrenBd_bore_2_outdata(boreChildrenBd_bore_2_outdata),
    .boreChildrenBd_bore_3_array(boreChildrenBd_bore_3_array),
    .boreChildrenBd_bore_3_all(boreChildrenBd_bore_3_all),
    .boreChildrenBd_bore_3_req(boreChildrenBd_bore_3_req),
    .boreChildrenBd_bore_3_ack(boreChildrenBd_bore_3_ack),
    .boreChildrenBd_bore_3_writeen(boreChildrenBd_bore_3_writeen),
    .boreChildrenBd_bore_3_be(boreChildrenBd_bore_3_be),
    .boreChildrenBd_bore_3_addr(boreChildrenBd_bore_3_addr),
    .boreChildrenBd_bore_3_indata(boreChildrenBd_bore_3_indata),
    .boreChildrenBd_bore_3_readen(boreChildrenBd_bore_3_readen),
    .boreChildrenBd_bore_3_addr_rd(boreChildrenBd_bore_3_addr_rd),
    .boreChildrenBd_bore_3_outdata(boreChildrenBd_bore_3_outdata),
    .boreChildrenBd_bore_4_array(boreChildrenBd_bore_4_array),
    .boreChildrenBd_bore_4_all(boreChildrenBd_bore_4_all),
    .boreChildrenBd_bore_4_req(boreChildrenBd_bore_4_req),
    .boreChildrenBd_bore_4_ack(boreChildrenBd_bore_4_ack),
    .boreChildrenBd_bore_4_writeen(boreChildrenBd_bore_4_writeen),
    .boreChildrenBd_bore_4_be(boreChildrenBd_bore_4_be),
    .boreChildrenBd_bore_4_addr(boreChildrenBd_bore_4_addr),
    .boreChildrenBd_bore_4_indata(boreChildrenBd_bore_4_indata),
    .boreChildrenBd_bore_4_readen(boreChildrenBd_bore_4_readen),
    .boreChildrenBd_bore_4_addr_rd(boreChildrenBd_bore_4_addr_rd),
    .boreChildrenBd_bore_4_outdata(boreChildrenBd_bore_4_outdata),
    .sigFromSrams_bore_ram_hold(sigFromSrams_bore_ram_hold),
    .sigFromSrams_bore_ram_bypass(sigFromSrams_bore_ram_bypass),
    .sigFromSrams_bore_ram_bp_clken(sigFromSrams_bore_ram_bp_clken),
    .sigFromSrams_bore_ram_aux_clk(sigFromSrams_bore_ram_aux_clk),
    .sigFromSrams_bore_ram_aux_ckbp(sigFromSrams_bore_ram_aux_ckbp),
    .sigFromSrams_bore_ram_mcp_hold(sigFromSrams_bore_ram_mcp_hold),
    .sigFromSrams_bore_cgen(sigFromSrams_bore_cgen),
    .sigFromSrams_bore_1_ram_hold(sigFromSrams_bore_1_ram_hold),
    .sigFromSrams_bore_1_ram_bypass(sigFromSrams_bore_1_ram_bypass),
    .sigFromSrams_bore_1_ram_bp_clken(sigFromSrams_bore_1_ram_bp_clken),
    .sigFromSrams_bore_1_ram_aux_clk(sigFromSrams_bore_1_ram_aux_clk),
    .sigFromSrams_bore_1_ram_aux_ckbp(sigFromSrams_bore_1_ram_aux_ckbp),
    .sigFromSrams_bore_1_ram_mcp_hold(sigFromSrams_bore_1_ram_mcp_hold),
    .sigFromSrams_bore_1_cgen(sigFromSrams_bore_1_cgen),
    .sigFromSrams_bore_2_ram_hold(sigFromSrams_bore_2_ram_hold),
    .sigFromSrams_bore_2_ram_bypass(sigFromSrams_bore_2_ram_bypass),
    .sigFromSrams_bore_2_ram_bp_clken(sigFromSrams_bore_2_ram_bp_clken),
    .sigFromSrams_bore_2_ram_aux_clk(sigFromSrams_bore_2_ram_aux_clk),
    .sigFromSrams_bore_2_ram_aux_ckbp(sigFromSrams_bore_2_ram_aux_ckbp),
    .sigFromSrams_bore_2_ram_mcp_hold(sigFromSrams_bore_2_ram_mcp_hold),
    .sigFromSrams_bore_2_cgen(sigFromSrams_bore_2_cgen),
    .sigFromSrams_bore_3_ram_hold(sigFromSrams_bore_3_ram_hold),
    .sigFromSrams_bore_3_ram_bypass(sigFromSrams_bore_3_ram_bypass),
    .sigFromSrams_bore_3_ram_bp_clken(sigFromSrams_bore_3_ram_bp_clken),
    .sigFromSrams_bore_3_ram_aux_clk(sigFromSrams_bore_3_ram_aux_clk),
    .sigFromSrams_bore_3_ram_aux_ckbp(sigFromSrams_bore_3_ram_aux_ckbp),
    .sigFromSrams_bore_3_ram_mcp_hold(sigFromSrams_bore_3_ram_mcp_hold),
    .sigFromSrams_bore_3_cgen(sigFromSrams_bore_3_cgen),
    .sigFromSrams_bore_4_ram_hold(sigFromSrams_bore_4_ram_hold),
    .sigFromSrams_bore_4_ram_bypass(sigFromSrams_bore_4_ram_bypass),
    .sigFromSrams_bore_4_ram_bp_clken(sigFromSrams_bore_4_ram_bp_clken),
    .sigFromSrams_bore_4_ram_aux_clk(sigFromSrams_bore_4_ram_aux_clk),
    .sigFromSrams_bore_4_ram_aux_ckbp(sigFromSrams_bore_4_ram_aux_ckbp),
    .sigFromSrams_bore_4_ram_mcp_hold(sigFromSrams_bore_4_ram_mcp_hold),
    .sigFromSrams_bore_4_cgen(sigFromSrams_bore_4_cgen),
    .sigFromSrams_bore_5_ram_hold(sigFromSrams_bore_5_ram_hold),
    .sigFromSrams_bore_5_ram_bypass(sigFromSrams_bore_5_ram_bypass),
    .sigFromSrams_bore_5_ram_bp_clken(sigFromSrams_bore_5_ram_bp_clken),
    .sigFromSrams_bore_5_ram_aux_clk(sigFromSrams_bore_5_ram_aux_clk),
    .sigFromSrams_bore_5_ram_aux_ckbp(sigFromSrams_bore_5_ram_aux_ckbp),
    .sigFromSrams_bore_5_ram_mcp_hold(sigFromSrams_bore_5_ram_mcp_hold),
    .sigFromSrams_bore_5_cgen(sigFromSrams_bore_5_cgen),
    .sigFromSrams_bore_6_ram_hold(sigFromSrams_bore_6_ram_hold),
    .sigFromSrams_bore_6_ram_bypass(sigFromSrams_bore_6_ram_bypass),
    .sigFromSrams_bore_6_ram_bp_clken(sigFromSrams_bore_6_ram_bp_clken),
    .sigFromSrams_bore_6_ram_aux_clk(sigFromSrams_bore_6_ram_aux_clk),
    .sigFromSrams_bore_6_ram_aux_ckbp(sigFromSrams_bore_6_ram_aux_ckbp),
    .sigFromSrams_bore_6_ram_mcp_hold(sigFromSrams_bore_6_ram_mcp_hold),
    .sigFromSrams_bore_6_cgen(sigFromSrams_bore_6_cgen),
    .sigFromSrams_bore_7_ram_hold(sigFromSrams_bore_7_ram_hold),
    .sigFromSrams_bore_7_ram_bypass(sigFromSrams_bore_7_ram_bypass),
    .sigFromSrams_bore_7_ram_bp_clken(sigFromSrams_bore_7_ram_bp_clken),
    .sigFromSrams_bore_7_ram_aux_clk(sigFromSrams_bore_7_ram_aux_clk),
    .sigFromSrams_bore_7_ram_aux_ckbp(sigFromSrams_bore_7_ram_aux_ckbp),
    .sigFromSrams_bore_7_ram_mcp_hold(sigFromSrams_bore_7_ram_mcp_hold),
    .sigFromSrams_bore_7_cgen(sigFromSrams_bore_7_cgen),
    .sigFromSrams_bore_8_ram_hold(sigFromSrams_bore_8_ram_hold),
    .sigFromSrams_bore_8_ram_bypass(sigFromSrams_bore_8_ram_bypass),
    .sigFromSrams_bore_8_ram_bp_clken(sigFromSrams_bore_8_ram_bp_clken),
    .sigFromSrams_bore_8_ram_aux_clk(sigFromSrams_bore_8_ram_aux_clk),
    .sigFromSrams_bore_8_ram_aux_ckbp(sigFromSrams_bore_8_ram_aux_ckbp),
    .sigFromSrams_bore_8_ram_mcp_hold(sigFromSrams_bore_8_ram_mcp_hold),
    .sigFromSrams_bore_8_cgen(sigFromSrams_bore_8_cgen),
    .sigFromSrams_bore_9_ram_hold(sigFromSrams_bore_9_ram_hold),
    .sigFromSrams_bore_9_ram_bypass(sigFromSrams_bore_9_ram_bypass),
    .sigFromSrams_bore_9_ram_bp_clken(sigFromSrams_bore_9_ram_bp_clken),
    .sigFromSrams_bore_9_ram_aux_clk(sigFromSrams_bore_9_ram_aux_clk),
    .sigFromSrams_bore_9_ram_aux_ckbp(sigFromSrams_bore_9_ram_aux_ckbp),
    .sigFromSrams_bore_9_ram_mcp_hold(sigFromSrams_bore_9_ram_mcp_hold),
    .sigFromSrams_bore_9_cgen(sigFromSrams_bore_9_cgen),
    .sigFromSrams_bore_10_ram_hold(sigFromSrams_bore_10_ram_hold),
    .sigFromSrams_bore_10_ram_bypass(sigFromSrams_bore_10_ram_bypass),
    .sigFromSrams_bore_10_ram_bp_clken(sigFromSrams_bore_10_ram_bp_clken),
    .sigFromSrams_bore_10_ram_aux_clk(sigFromSrams_bore_10_ram_aux_clk),
    .sigFromSrams_bore_10_ram_aux_ckbp(sigFromSrams_bore_10_ram_aux_ckbp),
    .sigFromSrams_bore_10_ram_mcp_hold(sigFromSrams_bore_10_ram_mcp_hold),
    .sigFromSrams_bore_10_cgen(sigFromSrams_bore_10_cgen),
    .sigFromSrams_bore_11_ram_hold(sigFromSrams_bore_11_ram_hold),
    .sigFromSrams_bore_11_ram_bypass(sigFromSrams_bore_11_ram_bypass),
    .sigFromSrams_bore_11_ram_bp_clken(sigFromSrams_bore_11_ram_bp_clken),
    .sigFromSrams_bore_11_ram_aux_clk(sigFromSrams_bore_11_ram_aux_clk),
    .sigFromSrams_bore_11_ram_aux_ckbp(sigFromSrams_bore_11_ram_aux_ckbp),
    .sigFromSrams_bore_11_ram_mcp_hold(sigFromSrams_bore_11_ram_mcp_hold),
    .sigFromSrams_bore_11_cgen(sigFromSrams_bore_11_cgen),
    .sigFromSrams_bore_12_ram_hold(sigFromSrams_bore_12_ram_hold),
    .sigFromSrams_bore_12_ram_bypass(sigFromSrams_bore_12_ram_bypass),
    .sigFromSrams_bore_12_ram_bp_clken(sigFromSrams_bore_12_ram_bp_clken),
    .sigFromSrams_bore_12_ram_aux_clk(sigFromSrams_bore_12_ram_aux_clk),
    .sigFromSrams_bore_12_ram_aux_ckbp(sigFromSrams_bore_12_ram_aux_ckbp),
    .sigFromSrams_bore_12_ram_mcp_hold(sigFromSrams_bore_12_ram_mcp_hold),
    .sigFromSrams_bore_12_cgen(sigFromSrams_bore_12_cgen),
    .sigFromSrams_bore_13_ram_hold(sigFromSrams_bore_13_ram_hold),
    .sigFromSrams_bore_13_ram_bypass(sigFromSrams_bore_13_ram_bypass),
    .sigFromSrams_bore_13_ram_bp_clken(sigFromSrams_bore_13_ram_bp_clken),
    .sigFromSrams_bore_13_ram_aux_clk(sigFromSrams_bore_13_ram_aux_clk),
    .sigFromSrams_bore_13_ram_aux_ckbp(sigFromSrams_bore_13_ram_aux_ckbp),
    .sigFromSrams_bore_13_ram_mcp_hold(sigFromSrams_bore_13_ram_mcp_hold),
    .sigFromSrams_bore_13_cgen(sigFromSrams_bore_13_cgen),
    .sigFromSrams_bore_14_ram_hold(sigFromSrams_bore_14_ram_hold),
    .sigFromSrams_bore_14_ram_bypass(sigFromSrams_bore_14_ram_bypass),
    .sigFromSrams_bore_14_ram_bp_clken(sigFromSrams_bore_14_ram_bp_clken),
    .sigFromSrams_bore_14_ram_aux_clk(sigFromSrams_bore_14_ram_aux_clk),
    .sigFromSrams_bore_14_ram_aux_ckbp(sigFromSrams_bore_14_ram_aux_ckbp),
    .sigFromSrams_bore_14_ram_mcp_hold(sigFromSrams_bore_14_ram_mcp_hold),
    .sigFromSrams_bore_14_cgen(sigFromSrams_bore_14_cgen),
    .sigFromSrams_bore_15_ram_hold(sigFromSrams_bore_15_ram_hold),
    .sigFromSrams_bore_15_ram_bypass(sigFromSrams_bore_15_ram_bypass),
    .sigFromSrams_bore_15_ram_bp_clken(sigFromSrams_bore_15_ram_bp_clken),
    .sigFromSrams_bore_15_ram_aux_clk(sigFromSrams_bore_15_ram_aux_clk),
    .sigFromSrams_bore_15_ram_aux_ckbp(sigFromSrams_bore_15_ram_aux_ckbp),
    .sigFromSrams_bore_15_ram_mcp_hold(sigFromSrams_bore_15_ram_mcp_hold),
    .sigFromSrams_bore_15_cgen(sigFromSrams_bore_15_cgen),
    .sigFromSrams_bore_16_ram_hold(sigFromSrams_bore_16_ram_hold),
    .sigFromSrams_bore_16_ram_bypass(sigFromSrams_bore_16_ram_bypass),
    .sigFromSrams_bore_16_ram_bp_clken(sigFromSrams_bore_16_ram_bp_clken),
    .sigFromSrams_bore_16_ram_aux_clk(sigFromSrams_bore_16_ram_aux_clk),
    .sigFromSrams_bore_16_ram_aux_ckbp(sigFromSrams_bore_16_ram_aux_ckbp),
    .sigFromSrams_bore_16_ram_mcp_hold(sigFromSrams_bore_16_ram_mcp_hold),
    .sigFromSrams_bore_16_cgen(sigFromSrams_bore_16_cgen),
    .sigFromSrams_bore_17_ram_hold(sigFromSrams_bore_17_ram_hold),
    .sigFromSrams_bore_17_ram_bypass(sigFromSrams_bore_17_ram_bypass),
    .sigFromSrams_bore_17_ram_bp_clken(sigFromSrams_bore_17_ram_bp_clken),
    .sigFromSrams_bore_17_ram_aux_clk(sigFromSrams_bore_17_ram_aux_clk),
    .sigFromSrams_bore_17_ram_aux_ckbp(sigFromSrams_bore_17_ram_aux_ckbp),
    .sigFromSrams_bore_17_ram_mcp_hold(sigFromSrams_bore_17_ram_mcp_hold),
    .sigFromSrams_bore_17_cgen(sigFromSrams_bore_17_cgen),
    .sigFromSrams_bore_18_ram_hold(sigFromSrams_bore_18_ram_hold),
    .sigFromSrams_bore_18_ram_bypass(sigFromSrams_bore_18_ram_bypass),
    .sigFromSrams_bore_18_ram_bp_clken(sigFromSrams_bore_18_ram_bp_clken),
    .sigFromSrams_bore_18_ram_aux_clk(sigFromSrams_bore_18_ram_aux_clk),
    .sigFromSrams_bore_18_ram_aux_ckbp(sigFromSrams_bore_18_ram_aux_ckbp),
    .sigFromSrams_bore_18_ram_mcp_hold(sigFromSrams_bore_18_ram_mcp_hold),
    .sigFromSrams_bore_18_cgen(sigFromSrams_bore_18_cgen),
    .sigFromSrams_bore_19_ram_hold(sigFromSrams_bore_19_ram_hold),
    .sigFromSrams_bore_19_ram_bypass(sigFromSrams_bore_19_ram_bypass),
    .sigFromSrams_bore_19_ram_bp_clken(sigFromSrams_bore_19_ram_bp_clken),
    .sigFromSrams_bore_19_ram_aux_clk(sigFromSrams_bore_19_ram_aux_clk),
    .sigFromSrams_bore_19_ram_aux_ckbp(sigFromSrams_bore_19_ram_aux_ckbp),
    .sigFromSrams_bore_19_ram_mcp_hold(sigFromSrams_bore_19_ram_mcp_hold),
    .sigFromSrams_bore_19_cgen(sigFromSrams_bore_19_cgen),
    .sigFromSrams_bore_20_ram_hold(sigFromSrams_bore_20_ram_hold),
    .sigFromSrams_bore_20_ram_bypass(sigFromSrams_bore_20_ram_bypass),
    .sigFromSrams_bore_20_ram_bp_clken(sigFromSrams_bore_20_ram_bp_clken),
    .sigFromSrams_bore_20_ram_aux_clk(sigFromSrams_bore_20_ram_aux_clk),
    .sigFromSrams_bore_20_ram_aux_ckbp(sigFromSrams_bore_20_ram_aux_ckbp),
    .sigFromSrams_bore_20_ram_mcp_hold(sigFromSrams_bore_20_ram_mcp_hold),
    .sigFromSrams_bore_20_cgen(sigFromSrams_bore_20_cgen),
    .sigFromSrams_bore_21_ram_hold(sigFromSrams_bore_21_ram_hold),
    .sigFromSrams_bore_21_ram_bypass(sigFromSrams_bore_21_ram_bypass),
    .sigFromSrams_bore_21_ram_bp_clken(sigFromSrams_bore_21_ram_bp_clken),
    .sigFromSrams_bore_21_ram_aux_clk(sigFromSrams_bore_21_ram_aux_clk),
    .sigFromSrams_bore_21_ram_aux_ckbp(sigFromSrams_bore_21_ram_aux_ckbp),
    .sigFromSrams_bore_21_ram_mcp_hold(sigFromSrams_bore_21_ram_mcp_hold),
    .sigFromSrams_bore_21_cgen(sigFromSrams_bore_21_cgen),
    .sigFromSrams_bore_22_ram_hold(sigFromSrams_bore_22_ram_hold),
    .sigFromSrams_bore_22_ram_bypass(sigFromSrams_bore_22_ram_bypass),
    .sigFromSrams_bore_22_ram_bp_clken(sigFromSrams_bore_22_ram_bp_clken),
    .sigFromSrams_bore_22_ram_aux_clk(sigFromSrams_bore_22_ram_aux_clk),
    .sigFromSrams_bore_22_ram_aux_ckbp(sigFromSrams_bore_22_ram_aux_ckbp),
    .sigFromSrams_bore_22_ram_mcp_hold(sigFromSrams_bore_22_ram_mcp_hold),
    .sigFromSrams_bore_22_cgen(sigFromSrams_bore_22_cgen),
    .sigFromSrams_bore_23_ram_hold(sigFromSrams_bore_23_ram_hold),
    .sigFromSrams_bore_23_ram_bypass(sigFromSrams_bore_23_ram_bypass),
    .sigFromSrams_bore_23_ram_bp_clken(sigFromSrams_bore_23_ram_bp_clken),
    .sigFromSrams_bore_23_ram_aux_clk(sigFromSrams_bore_23_ram_aux_clk),
    .sigFromSrams_bore_23_ram_aux_ckbp(sigFromSrams_bore_23_ram_aux_ckbp),
    .sigFromSrams_bore_23_ram_mcp_hold(sigFromSrams_bore_23_ram_mcp_hold),
    .sigFromSrams_bore_23_cgen(sigFromSrams_bore_23_cgen),
    .sigFromSrams_bore_24_ram_hold(sigFromSrams_bore_24_ram_hold),
    .sigFromSrams_bore_24_ram_bypass(sigFromSrams_bore_24_ram_bypass),
    .sigFromSrams_bore_24_ram_bp_clken(sigFromSrams_bore_24_ram_bp_clken),
    .sigFromSrams_bore_24_ram_aux_clk(sigFromSrams_bore_24_ram_aux_clk),
    .sigFromSrams_bore_24_ram_aux_ckbp(sigFromSrams_bore_24_ram_aux_ckbp),
    .sigFromSrams_bore_24_ram_mcp_hold(sigFromSrams_bore_24_ram_mcp_hold),
    .sigFromSrams_bore_24_cgen(sigFromSrams_bore_24_cgen),
    .sigFromSrams_bore_25_ram_hold(sigFromSrams_bore_25_ram_hold),
    .sigFromSrams_bore_25_ram_bypass(sigFromSrams_bore_25_ram_bypass),
    .sigFromSrams_bore_25_ram_bp_clken(sigFromSrams_bore_25_ram_bp_clken),
    .sigFromSrams_bore_25_ram_aux_clk(sigFromSrams_bore_25_ram_aux_clk),
    .sigFromSrams_bore_25_ram_aux_ckbp(sigFromSrams_bore_25_ram_aux_ckbp),
    .sigFromSrams_bore_25_ram_mcp_hold(sigFromSrams_bore_25_ram_mcp_hold),
    .sigFromSrams_bore_25_cgen(sigFromSrams_bore_25_cgen),
    .sigFromSrams_bore_26_ram_hold(sigFromSrams_bore_26_ram_hold),
    .sigFromSrams_bore_26_ram_bypass(sigFromSrams_bore_26_ram_bypass),
    .sigFromSrams_bore_26_ram_bp_clken(sigFromSrams_bore_26_ram_bp_clken),
    .sigFromSrams_bore_26_ram_aux_clk(sigFromSrams_bore_26_ram_aux_clk),
    .sigFromSrams_bore_26_ram_aux_ckbp(sigFromSrams_bore_26_ram_aux_ckbp),
    .sigFromSrams_bore_26_ram_mcp_hold(sigFromSrams_bore_26_ram_mcp_hold),
    .sigFromSrams_bore_26_cgen(sigFromSrams_bore_26_cgen),
    .sigFromSrams_bore_27_ram_hold(sigFromSrams_bore_27_ram_hold),
    .sigFromSrams_bore_27_ram_bypass(sigFromSrams_bore_27_ram_bypass),
    .sigFromSrams_bore_27_ram_bp_clken(sigFromSrams_bore_27_ram_bp_clken),
    .sigFromSrams_bore_27_ram_aux_clk(sigFromSrams_bore_27_ram_aux_clk),
    .sigFromSrams_bore_27_ram_aux_ckbp(sigFromSrams_bore_27_ram_aux_ckbp),
    .sigFromSrams_bore_27_ram_mcp_hold(sigFromSrams_bore_27_ram_mcp_hold),
    .sigFromSrams_bore_27_cgen(sigFromSrams_bore_27_cgen),
    .sigFromSrams_bore_28_ram_hold(sigFromSrams_bore_28_ram_hold),
    .sigFromSrams_bore_28_ram_bypass(sigFromSrams_bore_28_ram_bypass),
    .sigFromSrams_bore_28_ram_bp_clken(sigFromSrams_bore_28_ram_bp_clken),
    .sigFromSrams_bore_28_ram_aux_clk(sigFromSrams_bore_28_ram_aux_clk),
    .sigFromSrams_bore_28_ram_aux_ckbp(sigFromSrams_bore_28_ram_aux_ckbp),
    .sigFromSrams_bore_28_ram_mcp_hold(sigFromSrams_bore_28_ram_mcp_hold),
    .sigFromSrams_bore_28_cgen(sigFromSrams_bore_28_cgen),
    .sigFromSrams_bore_29_ram_hold(sigFromSrams_bore_29_ram_hold),
    .sigFromSrams_bore_29_ram_bypass(sigFromSrams_bore_29_ram_bypass),
    .sigFromSrams_bore_29_ram_bp_clken(sigFromSrams_bore_29_ram_bp_clken),
    .sigFromSrams_bore_29_ram_aux_clk(sigFromSrams_bore_29_ram_aux_clk),
    .sigFromSrams_bore_29_ram_aux_ckbp(sigFromSrams_bore_29_ram_aux_ckbp),
    .sigFromSrams_bore_29_ram_mcp_hold(sigFromSrams_bore_29_ram_mcp_hold),
    .sigFromSrams_bore_29_cgen(sigFromSrams_bore_29_cgen),
    .sigFromSrams_bore_30_ram_hold(sigFromSrams_bore_30_ram_hold),
    .sigFromSrams_bore_30_ram_bypass(sigFromSrams_bore_30_ram_bypass),
    .sigFromSrams_bore_30_ram_bp_clken(sigFromSrams_bore_30_ram_bp_clken),
    .sigFromSrams_bore_30_ram_aux_clk(sigFromSrams_bore_30_ram_aux_clk),
    .sigFromSrams_bore_30_ram_aux_ckbp(sigFromSrams_bore_30_ram_aux_ckbp),
    .sigFromSrams_bore_30_ram_mcp_hold(sigFromSrams_bore_30_ram_mcp_hold),
    .sigFromSrams_bore_30_cgen(sigFromSrams_bore_30_cgen),
    .sigFromSrams_bore_31_ram_hold(sigFromSrams_bore_31_ram_hold),
    .sigFromSrams_bore_31_ram_bypass(sigFromSrams_bore_31_ram_bypass),
    .sigFromSrams_bore_31_ram_bp_clken(sigFromSrams_bore_31_ram_bp_clken),
    .sigFromSrams_bore_31_ram_aux_clk(sigFromSrams_bore_31_ram_aux_clk),
    .sigFromSrams_bore_31_ram_aux_ckbp(sigFromSrams_bore_31_ram_aux_ckbp),
    .sigFromSrams_bore_31_ram_mcp_hold(sigFromSrams_bore_31_ram_mcp_hold),
    .sigFromSrams_bore_31_cgen(sigFromSrams_bore_31_cgen),
    .sigFromSrams_bore_32_ram_hold(sigFromSrams_bore_32_ram_hold),
    .sigFromSrams_bore_32_ram_bypass(sigFromSrams_bore_32_ram_bypass),
    .sigFromSrams_bore_32_ram_bp_clken(sigFromSrams_bore_32_ram_bp_clken),
    .sigFromSrams_bore_32_ram_aux_clk(sigFromSrams_bore_32_ram_aux_clk),
    .sigFromSrams_bore_32_ram_aux_ckbp(sigFromSrams_bore_32_ram_aux_ckbp),
    .sigFromSrams_bore_32_ram_mcp_hold(sigFromSrams_bore_32_ram_mcp_hold),
    .sigFromSrams_bore_32_cgen(sigFromSrams_bore_32_cgen),
    .sigFromSrams_bore_33_ram_hold(sigFromSrams_bore_33_ram_hold),
    .sigFromSrams_bore_33_ram_bypass(sigFromSrams_bore_33_ram_bypass),
    .sigFromSrams_bore_33_ram_bp_clken(sigFromSrams_bore_33_ram_bp_clken),
    .sigFromSrams_bore_33_ram_aux_clk(sigFromSrams_bore_33_ram_aux_clk),
    .sigFromSrams_bore_33_ram_aux_ckbp(sigFromSrams_bore_33_ram_aux_ckbp),
    .sigFromSrams_bore_33_ram_mcp_hold(sigFromSrams_bore_33_ram_mcp_hold),
    .sigFromSrams_bore_33_cgen(sigFromSrams_bore_33_cgen),
    .sigFromSrams_bore_34_ram_hold(sigFromSrams_bore_34_ram_hold),
    .sigFromSrams_bore_34_ram_bypass(sigFromSrams_bore_34_ram_bypass),
    .sigFromSrams_bore_34_ram_bp_clken(sigFromSrams_bore_34_ram_bp_clken),
    .sigFromSrams_bore_34_ram_aux_clk(sigFromSrams_bore_34_ram_aux_clk),
    .sigFromSrams_bore_34_ram_aux_ckbp(sigFromSrams_bore_34_ram_aux_ckbp),
    .sigFromSrams_bore_34_ram_mcp_hold(sigFromSrams_bore_34_ram_mcp_hold),
    .sigFromSrams_bore_34_cgen(sigFromSrams_bore_34_cgen),
    .sigFromSrams_bore_35_ram_hold(sigFromSrams_bore_35_ram_hold),
    .sigFromSrams_bore_35_ram_bypass(sigFromSrams_bore_35_ram_bypass),
    .sigFromSrams_bore_35_ram_bp_clken(sigFromSrams_bore_35_ram_bp_clken),
    .sigFromSrams_bore_35_ram_aux_clk(sigFromSrams_bore_35_ram_aux_clk),
    .sigFromSrams_bore_35_ram_aux_ckbp(sigFromSrams_bore_35_ram_aux_ckbp),
    .sigFromSrams_bore_35_ram_mcp_hold(sigFromSrams_bore_35_ram_mcp_hold),
    .sigFromSrams_bore_35_cgen(sigFromSrams_bore_35_cgen)
  );
endmodule
