// Generated by scripts/gen_predchecker.py — do not hand-edit.
//
// xs_PredChecker_core — readable faithful (bug-for-bug) core for golden
// PredChecker (IFU F3 预测检查器: 预译码 vs 分支预测一致性检查 + 目标重算)。
//
// 结构(golden firtool 单模块, 0 子模块 0 mem, 唯一使能 io_in_fire_in, 无 reset):
//   S1(组合): 逐 lane 检查预译码出的必然跳转(jal/jalr/ret)是否被预测漏掉
//             (jalFaultVec/jalrFaultVec/retFaultVec), 取最低 fault lane 截断
//             instrRange(fixedRange), 并重算 fixedTaken;
//   REG:      S1 结果 + 重算目标(jumpTargets=pc+offset, seqTargets=pc+2/4)
//             在 fire_in 下打 1 拍(*_Next 寄存器组, 逐字保留 golden 名);
//   S2(组合): 由寄存器重算 targetFault(预测目标 != 重算目标)、fixedTarget、
//             fixedMissPred、faultType(1=jal,6=jalr,2=ret,3=target,4=notCFI,5=invalid)。
//
// RENAME 映射(golden → 本核, 其余 golden 具名 wire/reg 逐字保留):
//   _GEN/_GEN_1.._GEN_29(奇偶交错)     → (brTypeIn[i] == 2'h2) 内联 / predUnseenTaken[i]
//     _GEN_0/_GEN_2/..(lane 特化 (|bits), |bits[3:1], bits>4'h2, bits[3], &bits, ~valid)
//     都是 (ftqOffset_bits > i) & valid | ~valid 的常量折叠 → predUnseenTaken[i]
//   _remaskIdx_T_17/_21/_23/_31 优先级树 → remaskIdx(always_comb 低位优先编码, 缺省 4'hF)
//   _fixedRange_T_6                     → fixedRangeMask
//   _GEN_30/32/../60(instrRange&mask)   → inFixedRange[i]
//   _GEN_31/33/../59, &bits(lane15)     → predTakenAt[i] (ftqOffset_bits == i)
// 寄存器集与 next-state 表达式逐字保留(fixedRangeNext/instrValidNext_*/takenIdxNext/
// predTakenNext/predTargetNext/jumpTargetsNext_*/seqTargetsNext_*/pdsNext_*_brType/
// jal|jalr|retFaultVecNext_*/notCFITakenNext_*/invalidTakenNext_*)。
module xs_PredChecker_core(
  input          clock,
  input          io_in_ftqOffset_valid,
  input  [3:0]   io_in_ftqOffset_bits,
  input  [63:0]  io_in_jumpOffset_0,
  input  [63:0]  io_in_jumpOffset_1,
  input  [63:0]  io_in_jumpOffset_2,
  input  [63:0]  io_in_jumpOffset_3,
  input  [63:0]  io_in_jumpOffset_4,
  input  [63:0]  io_in_jumpOffset_5,
  input  [63:0]  io_in_jumpOffset_6,
  input  [63:0]  io_in_jumpOffset_7,
  input  [63:0]  io_in_jumpOffset_8,
  input  [63:0]  io_in_jumpOffset_9,
  input  [63:0]  io_in_jumpOffset_10,
  input  [63:0]  io_in_jumpOffset_11,
  input  [63:0]  io_in_jumpOffset_12,
  input  [63:0]  io_in_jumpOffset_13,
  input  [63:0]  io_in_jumpOffset_14,
  input  [63:0]  io_in_jumpOffset_15,
  input  [49:0]  io_in_target,
  input          io_in_instrRange_0,
  input          io_in_instrRange_1,
  input          io_in_instrRange_2,
  input          io_in_instrRange_3,
  input          io_in_instrRange_4,
  input          io_in_instrRange_5,
  input          io_in_instrRange_6,
  input          io_in_instrRange_7,
  input          io_in_instrRange_8,
  input          io_in_instrRange_9,
  input          io_in_instrRange_10,
  input          io_in_instrRange_11,
  input          io_in_instrRange_12,
  input          io_in_instrRange_13,
  input          io_in_instrRange_14,
  input          io_in_instrRange_15,
  input          io_in_instrValid_0,
  input          io_in_instrValid_1,
  input          io_in_instrValid_2,
  input          io_in_instrValid_3,
  input          io_in_instrValid_4,
  input          io_in_instrValid_5,
  input          io_in_instrValid_6,
  input          io_in_instrValid_7,
  input          io_in_instrValid_8,
  input          io_in_instrValid_9,
  input          io_in_instrValid_10,
  input          io_in_instrValid_11,
  input          io_in_instrValid_12,
  input          io_in_instrValid_13,
  input          io_in_instrValid_14,
  input          io_in_instrValid_15,
  input          io_in_pds_0_isRVC,
  input  [1:0]   io_in_pds_0_brType,
  input          io_in_pds_0_isRet,
  input          io_in_pds_1_isRVC,
  input  [1:0]   io_in_pds_1_brType,
  input          io_in_pds_1_isRet,
  input          io_in_pds_2_isRVC,
  input  [1:0]   io_in_pds_2_brType,
  input          io_in_pds_2_isRet,
  input          io_in_pds_3_isRVC,
  input  [1:0]   io_in_pds_3_brType,
  input          io_in_pds_3_isRet,
  input          io_in_pds_4_isRVC,
  input  [1:0]   io_in_pds_4_brType,
  input          io_in_pds_4_isRet,
  input          io_in_pds_5_isRVC,
  input  [1:0]   io_in_pds_5_brType,
  input          io_in_pds_5_isRet,
  input          io_in_pds_6_isRVC,
  input  [1:0]   io_in_pds_6_brType,
  input          io_in_pds_6_isRet,
  input          io_in_pds_7_isRVC,
  input  [1:0]   io_in_pds_7_brType,
  input          io_in_pds_7_isRet,
  input          io_in_pds_8_isRVC,
  input  [1:0]   io_in_pds_8_brType,
  input          io_in_pds_8_isRet,
  input          io_in_pds_9_isRVC,
  input  [1:0]   io_in_pds_9_brType,
  input          io_in_pds_9_isRet,
  input          io_in_pds_10_isRVC,
  input  [1:0]   io_in_pds_10_brType,
  input          io_in_pds_10_isRet,
  input          io_in_pds_11_isRVC,
  input  [1:0]   io_in_pds_11_brType,
  input          io_in_pds_11_isRet,
  input          io_in_pds_12_isRVC,
  input  [1:0]   io_in_pds_12_brType,
  input          io_in_pds_12_isRet,
  input          io_in_pds_13_isRVC,
  input  [1:0]   io_in_pds_13_brType,
  input          io_in_pds_13_isRet,
  input          io_in_pds_14_isRVC,
  input  [1:0]   io_in_pds_14_brType,
  input          io_in_pds_14_isRet,
  input          io_in_pds_15_isRVC,
  input  [1:0]   io_in_pds_15_brType,
  input          io_in_pds_15_isRet,
  input  [49:0]  io_in_pc_0,
  input  [49:0]  io_in_pc_1,
  input  [49:0]  io_in_pc_2,
  input  [49:0]  io_in_pc_3,
  input  [49:0]  io_in_pc_4,
  input  [49:0]  io_in_pc_5,
  input  [49:0]  io_in_pc_6,
  input  [49:0]  io_in_pc_7,
  input  [49:0]  io_in_pc_8,
  input  [49:0]  io_in_pc_9,
  input  [49:0]  io_in_pc_10,
  input  [49:0]  io_in_pc_11,
  input  [49:0]  io_in_pc_12,
  input  [49:0]  io_in_pc_13,
  input  [49:0]  io_in_pc_14,
  input  [49:0]  io_in_pc_15,
  input          io_in_fire_in,
  output         io_out_stage1Out_fixedRange_0,
  output         io_out_stage1Out_fixedRange_1,
  output         io_out_stage1Out_fixedRange_2,
  output         io_out_stage1Out_fixedRange_3,
  output         io_out_stage1Out_fixedRange_4,
  output         io_out_stage1Out_fixedRange_5,
  output         io_out_stage1Out_fixedRange_6,
  output         io_out_stage1Out_fixedRange_7,
  output         io_out_stage1Out_fixedRange_8,
  output         io_out_stage1Out_fixedRange_9,
  output         io_out_stage1Out_fixedRange_10,
  output         io_out_stage1Out_fixedRange_11,
  output         io_out_stage1Out_fixedRange_12,
  output         io_out_stage1Out_fixedRange_13,
  output         io_out_stage1Out_fixedRange_14,
  output         io_out_stage1Out_fixedRange_15,
  output         io_out_stage1Out_fixedTaken_0,
  output         io_out_stage1Out_fixedTaken_1,
  output         io_out_stage1Out_fixedTaken_2,
  output         io_out_stage1Out_fixedTaken_3,
  output         io_out_stage1Out_fixedTaken_4,
  output         io_out_stage1Out_fixedTaken_5,
  output         io_out_stage1Out_fixedTaken_6,
  output         io_out_stage1Out_fixedTaken_7,
  output         io_out_stage1Out_fixedTaken_8,
  output         io_out_stage1Out_fixedTaken_9,
  output         io_out_stage1Out_fixedTaken_10,
  output         io_out_stage1Out_fixedTaken_11,
  output         io_out_stage1Out_fixedTaken_12,
  output         io_out_stage1Out_fixedTaken_13,
  output         io_out_stage1Out_fixedTaken_14,
  output         io_out_stage1Out_fixedTaken_15,
  output [49:0]  io_out_stage2Out_fixedTarget_0,
  output [49:0]  io_out_stage2Out_fixedTarget_1,
  output [49:0]  io_out_stage2Out_fixedTarget_2,
  output [49:0]  io_out_stage2Out_fixedTarget_3,
  output [49:0]  io_out_stage2Out_fixedTarget_4,
  output [49:0]  io_out_stage2Out_fixedTarget_5,
  output [49:0]  io_out_stage2Out_fixedTarget_6,
  output [49:0]  io_out_stage2Out_fixedTarget_7,
  output [49:0]  io_out_stage2Out_fixedTarget_8,
  output [49:0]  io_out_stage2Out_fixedTarget_9,
  output [49:0]  io_out_stage2Out_fixedTarget_10,
  output [49:0]  io_out_stage2Out_fixedTarget_11,
  output [49:0]  io_out_stage2Out_fixedTarget_12,
  output [49:0]  io_out_stage2Out_fixedTarget_13,
  output [49:0]  io_out_stage2Out_fixedTarget_14,
  output [49:0]  io_out_stage2Out_fixedTarget_15,
  output [49:0]  io_out_stage2Out_jalTarget_0,
  output [49:0]  io_out_stage2Out_jalTarget_1,
  output [49:0]  io_out_stage2Out_jalTarget_2,
  output [49:0]  io_out_stage2Out_jalTarget_3,
  output [49:0]  io_out_stage2Out_jalTarget_4,
  output [49:0]  io_out_stage2Out_jalTarget_5,
  output [49:0]  io_out_stage2Out_jalTarget_6,
  output [49:0]  io_out_stage2Out_jalTarget_7,
  output [49:0]  io_out_stage2Out_jalTarget_8,
  output [49:0]  io_out_stage2Out_jalTarget_9,
  output [49:0]  io_out_stage2Out_jalTarget_10,
  output [49:0]  io_out_stage2Out_jalTarget_11,
  output [49:0]  io_out_stage2Out_jalTarget_12,
  output [49:0]  io_out_stage2Out_jalTarget_13,
  output [49:0]  io_out_stage2Out_jalTarget_14,
  output [49:0]  io_out_stage2Out_jalTarget_15,
  output         io_out_stage2Out_fixedMissPred_0,
  output         io_out_stage2Out_fixedMissPred_1,
  output         io_out_stage2Out_fixedMissPred_2,
  output         io_out_stage2Out_fixedMissPred_3,
  output         io_out_stage2Out_fixedMissPred_4,
  output         io_out_stage2Out_fixedMissPred_5,
  output         io_out_stage2Out_fixedMissPred_6,
  output         io_out_stage2Out_fixedMissPred_7,
  output         io_out_stage2Out_fixedMissPred_8,
  output         io_out_stage2Out_fixedMissPred_9,
  output         io_out_stage2Out_fixedMissPred_10,
  output         io_out_stage2Out_fixedMissPred_11,
  output         io_out_stage2Out_fixedMissPred_12,
  output         io_out_stage2Out_fixedMissPred_13,
  output         io_out_stage2Out_fixedMissPred_14,
  output         io_out_stage2Out_fixedMissPred_15,
  output [2:0]   io_out_stage2Out_faultType_0_value,
  output [2:0]   io_out_stage2Out_faultType_1_value,
  output [2:0]   io_out_stage2Out_faultType_2_value,
  output [2:0]   io_out_stage2Out_faultType_3_value,
  output [2:0]   io_out_stage2Out_faultType_4_value,
  output [2:0]   io_out_stage2Out_faultType_5_value,
  output [2:0]   io_out_stage2Out_faultType_6_value,
  output [2:0]   io_out_stage2Out_faultType_7_value,
  output [2:0]   io_out_stage2Out_faultType_8_value,
  output [2:0]   io_out_stage2Out_faultType_9_value,
  output [2:0]   io_out_stage2Out_faultType_10_value,
  output [2:0]   io_out_stage2Out_faultType_11_value,
  output [2:0]   io_out_stage2Out_faultType_12_value,
  output [2:0]   io_out_stage2Out_faultType_13_value,
  output [2:0]   io_out_stage2Out_faultType_14_value,
  output [2:0]   io_out_stage2Out_faultType_15_value
);

  localparam int PW = 16;   // PredictWidth

  // ---------------- 输入数组视图(机械 扁平->数组 打包) ----------------
  wire [PW-1:0] instrRange = {io_in_instrRange_15, io_in_instrRange_14, io_in_instrRange_13, io_in_instrRange_12, io_in_instrRange_11, io_in_instrRange_10, io_in_instrRange_9, io_in_instrRange_8, io_in_instrRange_7, io_in_instrRange_6, io_in_instrRange_5, io_in_instrRange_4, io_in_instrRange_3, io_in_instrRange_2, io_in_instrRange_1, io_in_instrRange_0};
  wire [PW-1:0] instrValid = {io_in_instrValid_15, io_in_instrValid_14, io_in_instrValid_13, io_in_instrValid_12, io_in_instrValid_11, io_in_instrValid_10, io_in_instrValid_9, io_in_instrValid_8, io_in_instrValid_7, io_in_instrValid_6, io_in_instrValid_5, io_in_instrValid_4, io_in_instrValid_3, io_in_instrValid_2, io_in_instrValid_1, io_in_instrValid_0};
  wire [PW-1:0] isRetIn    = {io_in_pds_15_isRet, io_in_pds_14_isRet, io_in_pds_13_isRet, io_in_pds_12_isRet, io_in_pds_11_isRet, io_in_pds_10_isRet, io_in_pds_9_isRet, io_in_pds_8_isRet, io_in_pds_7_isRet, io_in_pds_6_isRet, io_in_pds_5_isRet, io_in_pds_4_isRet, io_in_pds_3_isRet, io_in_pds_2_isRet, io_in_pds_1_isRet, io_in_pds_0_isRet};
  wire [1:0] brTypeIn [0:PW-1];
  assign brTypeIn[0] = io_in_pds_0_brType;
  assign brTypeIn[1] = io_in_pds_1_brType;
  assign brTypeIn[2] = io_in_pds_2_brType;
  assign brTypeIn[3] = io_in_pds_3_brType;
  assign brTypeIn[4] = io_in_pds_4_brType;
  assign brTypeIn[5] = io_in_pds_5_brType;
  assign brTypeIn[6] = io_in_pds_6_brType;
  assign brTypeIn[7] = io_in_pds_7_brType;
  assign brTypeIn[8] = io_in_pds_8_brType;
  assign brTypeIn[9] = io_in_pds_9_brType;
  assign brTypeIn[10] = io_in_pds_10_brType;
  assign brTypeIn[11] = io_in_pds_11_brType;
  assign brTypeIn[12] = io_in_pds_12_brType;
  assign brTypeIn[13] = io_in_pds_13_brType;
  assign brTypeIn[14] = io_in_pds_14_brType;
  assign brTypeIn[15] = io_in_pds_15_brType;

  // ---------------- S1: 预译码 vs 分支预测一致性检查(组合) ----------------
  // predUnseenTaken[i]: 预测 taken 点严格在 lane i 之后, 或本包无预测 taken。
  // 此时 lane i 的预译码必然跳转若存在, 即为预测漏报 fault。
  wire [PW-1:0] predUnseenTaken;
  wire [PW-1:0] jalFaultVec, jalrFaultVec, retFaultVec, remaskFault;
  genvar i;
  generate
    for (i = 0; i < PW; i = i + 1) begin : g_s1
      assign predUnseenTaken[i] =
        (io_in_ftqOffset_bits > i) & io_in_ftqOffset_valid | ~io_in_ftqOffset_valid;
      assign jalFaultVec[i] =
        (brTypeIn[i] == 2'h2) & instrRange[i] & instrValid[i] & predUnseenTaken[i];
      assign jalrFaultVec[i] =
        (brTypeIn[i] == 2'h3) & ~isRetIn[i] & instrRange[i] & instrValid[i]
        & predUnseenTaken[i];
      assign retFaultVec[i] =
        isRetIn[i] & instrRange[i] & instrValid[i] & predUnseenTaken[i];
      assign remaskFault[i] = jalFaultVec[i] | jalrFaultVec[i] | retFaultVec[i];
    end
  endgenerate

  // remaskIdx: 最低 fault lane 的优先编码(无 fault 时 4'hF, 与 golden 缺省一致;
  // golden 编码树只扫 lane0..14, lane15 fault 落缺省 4'hF —— 结果相同)。
  logic [3:0] remaskIdx;
  always_comb begin
    remaskIdx = 4'hF;
    for (int k = PW - 1; k >= 0; k = k - 1) begin
      if (remaskFault[k]) remaskIdx = 4'(k);
    end
  end
  // fixedRangeMask: 无 fault → 全 1; 有 fault → 只留 [remaskIdx:0]
  // (16'hFFFF >> ~idx = 16'hFFFF >> (15-idx))。
  wire [PW-1:0] fixedRangeMask = {PW{~(|remaskFault)}} | (16'hFFFF >> ~remaskIdx);
  wire [PW-1:0] fixedRange     = instrRange & fixedRangeMask;

  // fixedTaken(S1 组合输出): lane 有效且在修正范围内, 且预译码为必然跳转
  // (ret/jal/jalr), 或该 lane 恰是预测 taken 点且预译码确为 CFI(brType!=0)。
  wire [PW-1:0] inFixedRange;
  wire [PW-1:0] predTakenAt;
  wire [PW-1:0] fixedTaken;
  generate
    for (i = 0; i < PW; i = i + 1) begin : g_taken
      assign inFixedRange[i] = instrRange[i] & fixedRangeMask[i];
      assign predTakenAt[i]  = io_in_ftqOffset_bits == i;
      assign fixedTaken[i] =
        instrValid[i] & inFixedRange[i]
        & (isRetIn[i] | (brTypeIn[i] == 2'h2) | (brTypeIn[i] == 2'h3)
           | predTakenAt[i] & io_in_ftqOffset_valid & (brTypeIn[i] != 2'h0));
    end
  endgenerate

  // ---------------- 流水寄存器(golden 寄存器集逐字保留, fire_in 使能) --------
  reg  [15:0] fixedRangeNext;
  reg         instrValidNext_0;
  reg         instrValidNext_1;
  reg         instrValidNext_2;
  reg         instrValidNext_3;
  reg         instrValidNext_4;
  reg         instrValidNext_5;
  reg         instrValidNext_6;
  reg         instrValidNext_7;
  reg         instrValidNext_8;
  reg         instrValidNext_9;
  reg         instrValidNext_10;
  reg         instrValidNext_11;
  reg         instrValidNext_12;
  reg         instrValidNext_13;
  reg         instrValidNext_14;
  reg         instrValidNext_15;
  reg  [3:0]  takenIdxNext;
  reg         predTakenNext;
  reg  [49:0] predTargetNext;
  reg  [49:0] jumpTargetsNext_0;
  reg  [49:0] jumpTargetsNext_1;
  reg  [49:0] jumpTargetsNext_2;
  reg  [49:0] jumpTargetsNext_3;
  reg  [49:0] jumpTargetsNext_4;
  reg  [49:0] jumpTargetsNext_5;
  reg  [49:0] jumpTargetsNext_6;
  reg  [49:0] jumpTargetsNext_7;
  reg  [49:0] jumpTargetsNext_8;
  reg  [49:0] jumpTargetsNext_9;
  reg  [49:0] jumpTargetsNext_10;
  reg  [49:0] jumpTargetsNext_11;
  reg  [49:0] jumpTargetsNext_12;
  reg  [49:0] jumpTargetsNext_13;
  reg  [49:0] jumpTargetsNext_14;
  reg  [49:0] jumpTargetsNext_15;
  reg  [49:0] seqTargetsNext_0;
  reg  [49:0] seqTargetsNext_1;
  reg  [49:0] seqTargetsNext_2;
  reg  [49:0] seqTargetsNext_3;
  reg  [49:0] seqTargetsNext_4;
  reg  [49:0] seqTargetsNext_5;
  reg  [49:0] seqTargetsNext_6;
  reg  [49:0] seqTargetsNext_7;
  reg  [49:0] seqTargetsNext_8;
  reg  [49:0] seqTargetsNext_9;
  reg  [49:0] seqTargetsNext_10;
  reg  [49:0] seqTargetsNext_11;
  reg  [49:0] seqTargetsNext_12;
  reg  [49:0] seqTargetsNext_13;
  reg  [49:0] seqTargetsNext_14;
  reg  [49:0] seqTargetsNext_15;
  reg  [1:0]  pdsNext_0_brType;
  reg  [1:0]  pdsNext_1_brType;
  reg  [1:0]  pdsNext_2_brType;
  reg  [1:0]  pdsNext_3_brType;
  reg  [1:0]  pdsNext_4_brType;
  reg  [1:0]  pdsNext_5_brType;
  reg  [1:0]  pdsNext_6_brType;
  reg  [1:0]  pdsNext_7_brType;
  reg  [1:0]  pdsNext_8_brType;
  reg  [1:0]  pdsNext_9_brType;
  reg  [1:0]  pdsNext_10_brType;
  reg  [1:0]  pdsNext_11_brType;
  reg  [1:0]  pdsNext_12_brType;
  reg  [1:0]  pdsNext_13_brType;
  reg  [1:0]  pdsNext_14_brType;
  reg  [1:0]  pdsNext_15_brType;
  reg         jalFaultVecNext_0;
  reg         jalFaultVecNext_1;
  reg         jalFaultVecNext_2;
  reg         jalFaultVecNext_3;
  reg         jalFaultVecNext_4;
  reg         jalFaultVecNext_5;
  reg         jalFaultVecNext_6;
  reg         jalFaultVecNext_7;
  reg         jalFaultVecNext_8;
  reg         jalFaultVecNext_9;
  reg         jalFaultVecNext_10;
  reg         jalFaultVecNext_11;
  reg         jalFaultVecNext_12;
  reg         jalFaultVecNext_13;
  reg         jalFaultVecNext_14;
  reg         jalFaultVecNext_15;
  reg         jalrFaultVecNext_0;
  reg         jalrFaultVecNext_1;
  reg         jalrFaultVecNext_2;
  reg         jalrFaultVecNext_3;
  reg         jalrFaultVecNext_4;
  reg         jalrFaultVecNext_5;
  reg         jalrFaultVecNext_6;
  reg         jalrFaultVecNext_7;
  reg         jalrFaultVecNext_8;
  reg         jalrFaultVecNext_9;
  reg         jalrFaultVecNext_10;
  reg         jalrFaultVecNext_11;
  reg         jalrFaultVecNext_12;
  reg         jalrFaultVecNext_13;
  reg         jalrFaultVecNext_14;
  reg         jalrFaultVecNext_15;
  reg         retFaultVecNext_0;
  reg         retFaultVecNext_1;
  reg         retFaultVecNext_2;
  reg         retFaultVecNext_3;
  reg         retFaultVecNext_4;
  reg         retFaultVecNext_5;
  reg         retFaultVecNext_6;
  reg         retFaultVecNext_7;
  reg         retFaultVecNext_8;
  reg         retFaultVecNext_9;
  reg         retFaultVecNext_10;
  reg         retFaultVecNext_11;
  reg         retFaultVecNext_12;
  reg         retFaultVecNext_13;
  reg         retFaultVecNext_14;
  reg         retFaultVecNext_15;
  reg         notCFITakenNext_0;
  reg         notCFITakenNext_1;
  reg         notCFITakenNext_2;
  reg         notCFITakenNext_3;
  reg         notCFITakenNext_4;
  reg         notCFITakenNext_5;
  reg         notCFITakenNext_6;
  reg         notCFITakenNext_7;
  reg         notCFITakenNext_8;
  reg         notCFITakenNext_9;
  reg         notCFITakenNext_10;
  reg         notCFITakenNext_11;
  reg         notCFITakenNext_12;
  reg         notCFITakenNext_13;
  reg         notCFITakenNext_14;
  reg         notCFITakenNext_15;
  reg         invalidTakenNext_0;
  reg         invalidTakenNext_1;
  reg         invalidTakenNext_2;
  reg         invalidTakenNext_3;
  reg         invalidTakenNext_4;
  reg         invalidTakenNext_5;
  reg         invalidTakenNext_6;
  reg         invalidTakenNext_7;
  reg         invalidTakenNext_8;
  reg         invalidTakenNext_9;
  reg         invalidTakenNext_10;
  reg         invalidTakenNext_11;
  reg         invalidTakenNext_12;
  reg         invalidTakenNext_13;
  reg         invalidTakenNext_14;
  reg         invalidTakenNext_15;

  always @(posedge clock) begin
    if (io_in_fire_in) begin
      fixedRangeNext <= fixedRange;
      instrValidNext_0 <= io_in_instrValid_0;
      instrValidNext_1 <= io_in_instrValid_1;
      instrValidNext_2 <= io_in_instrValid_2;
      instrValidNext_3 <= io_in_instrValid_3;
      instrValidNext_4 <= io_in_instrValid_4;
      instrValidNext_5 <= io_in_instrValid_5;
      instrValidNext_6 <= io_in_instrValid_6;
      instrValidNext_7 <= io_in_instrValid_7;
      instrValidNext_8 <= io_in_instrValid_8;
      instrValidNext_9 <= io_in_instrValid_9;
      instrValidNext_10 <= io_in_instrValid_10;
      instrValidNext_11 <= io_in_instrValid_11;
      instrValidNext_12 <= io_in_instrValid_12;
      instrValidNext_13 <= io_in_instrValid_13;
      instrValidNext_14 <= io_in_instrValid_14;
      instrValidNext_15 <= io_in_instrValid_15;
      takenIdxNext <= io_in_ftqOffset_bits;
      predTakenNext <= io_in_ftqOffset_valid;
      predTargetNext <= io_in_target;
      jumpTargetsNext_0 <= 50'(io_in_pc_0 + io_in_jumpOffset_0[49:0]);
      jumpTargetsNext_1 <= 50'(io_in_pc_1 + io_in_jumpOffset_1[49:0]);
      jumpTargetsNext_2 <= 50'(io_in_pc_2 + io_in_jumpOffset_2[49:0]);
      jumpTargetsNext_3 <= 50'(io_in_pc_3 + io_in_jumpOffset_3[49:0]);
      jumpTargetsNext_4 <= 50'(io_in_pc_4 + io_in_jumpOffset_4[49:0]);
      jumpTargetsNext_5 <= 50'(io_in_pc_5 + io_in_jumpOffset_5[49:0]);
      jumpTargetsNext_6 <= 50'(io_in_pc_6 + io_in_jumpOffset_6[49:0]);
      jumpTargetsNext_7 <= 50'(io_in_pc_7 + io_in_jumpOffset_7[49:0]);
      jumpTargetsNext_8 <= 50'(io_in_pc_8 + io_in_jumpOffset_8[49:0]);
      jumpTargetsNext_9 <= 50'(io_in_pc_9 + io_in_jumpOffset_9[49:0]);
      jumpTargetsNext_10 <= 50'(io_in_pc_10 + io_in_jumpOffset_10[49:0]);
      jumpTargetsNext_11 <= 50'(io_in_pc_11 + io_in_jumpOffset_11[49:0]);
      jumpTargetsNext_12 <= 50'(io_in_pc_12 + io_in_jumpOffset_12[49:0]);
      jumpTargetsNext_13 <= 50'(io_in_pc_13 + io_in_jumpOffset_13[49:0]);
      jumpTargetsNext_14 <= 50'(io_in_pc_14 + io_in_jumpOffset_14[49:0]);
      jumpTargetsNext_15 <= 50'(io_in_pc_15 + io_in_jumpOffset_15[49:0]);
      seqTargetsNext_0 <=
        50'(io_in_pc_0 + {47'h0, io_in_pds_0_isRVC | ~io_in_instrValid_0 ? 3'h2 : 3'h4});
      seqTargetsNext_1 <=
        50'(io_in_pc_1 + {47'h0, io_in_pds_1_isRVC | ~io_in_instrValid_1 ? 3'h2 : 3'h4});
      seqTargetsNext_2 <=
        50'(io_in_pc_2 + {47'h0, io_in_pds_2_isRVC | ~io_in_instrValid_2 ? 3'h2 : 3'h4});
      seqTargetsNext_3 <=
        50'(io_in_pc_3 + {47'h0, io_in_pds_3_isRVC | ~io_in_instrValid_3 ? 3'h2 : 3'h4});
      seqTargetsNext_4 <=
        50'(io_in_pc_4 + {47'h0, io_in_pds_4_isRVC | ~io_in_instrValid_4 ? 3'h2 : 3'h4});
      seqTargetsNext_5 <=
        50'(io_in_pc_5 + {47'h0, io_in_pds_5_isRVC | ~io_in_instrValid_5 ? 3'h2 : 3'h4});
      seqTargetsNext_6 <=
        50'(io_in_pc_6 + {47'h0, io_in_pds_6_isRVC | ~io_in_instrValid_6 ? 3'h2 : 3'h4});
      seqTargetsNext_7 <=
        50'(io_in_pc_7 + {47'h0, io_in_pds_7_isRVC | ~io_in_instrValid_7 ? 3'h2 : 3'h4});
      seqTargetsNext_8 <=
        50'(io_in_pc_8 + {47'h0, io_in_pds_8_isRVC | ~io_in_instrValid_8 ? 3'h2 : 3'h4});
      seqTargetsNext_9 <=
        50'(io_in_pc_9 + {47'h0, io_in_pds_9_isRVC | ~io_in_instrValid_9 ? 3'h2 : 3'h4});
      seqTargetsNext_10 <=
        50'(io_in_pc_10 + {47'h0, io_in_pds_10_isRVC | ~io_in_instrValid_10 ? 3'h2 : 3'h4});
      seqTargetsNext_11 <=
        50'(io_in_pc_11 + {47'h0, io_in_pds_11_isRVC | ~io_in_instrValid_11 ? 3'h2 : 3'h4});
      seqTargetsNext_12 <=
        50'(io_in_pc_12 + {47'h0, io_in_pds_12_isRVC | ~io_in_instrValid_12 ? 3'h2 : 3'h4});
      seqTargetsNext_13 <=
        50'(io_in_pc_13 + {47'h0, io_in_pds_13_isRVC | ~io_in_instrValid_13 ? 3'h2 : 3'h4});
      seqTargetsNext_14 <=
        50'(io_in_pc_14 + {47'h0, io_in_pds_14_isRVC | ~io_in_instrValid_14 ? 3'h2 : 3'h4});
      seqTargetsNext_15 <=
        50'(io_in_pc_15 + {47'h0, io_in_pds_15_isRVC | ~io_in_instrValid_15 ? 3'h2 : 3'h4});
      pdsNext_0_brType <= io_in_pds_0_brType;
      pdsNext_1_brType <= io_in_pds_1_brType;
      pdsNext_2_brType <= io_in_pds_2_brType;
      pdsNext_3_brType <= io_in_pds_3_brType;
      pdsNext_4_brType <= io_in_pds_4_brType;
      pdsNext_5_brType <= io_in_pds_5_brType;
      pdsNext_6_brType <= io_in_pds_6_brType;
      pdsNext_7_brType <= io_in_pds_7_brType;
      pdsNext_8_brType <= io_in_pds_8_brType;
      pdsNext_9_brType <= io_in_pds_9_brType;
      pdsNext_10_brType <= io_in_pds_10_brType;
      pdsNext_11_brType <= io_in_pds_11_brType;
      pdsNext_12_brType <= io_in_pds_12_brType;
      pdsNext_13_brType <= io_in_pds_13_brType;
      pdsNext_14_brType <= io_in_pds_14_brType;
      pdsNext_15_brType <= io_in_pds_15_brType;
      jalFaultVecNext_0 <= jalFaultVec[0];
      jalFaultVecNext_1 <= jalFaultVec[1];
      jalFaultVecNext_2 <= jalFaultVec[2];
      jalFaultVecNext_3 <= jalFaultVec[3];
      jalFaultVecNext_4 <= jalFaultVec[4];
      jalFaultVecNext_5 <= jalFaultVec[5];
      jalFaultVecNext_6 <= jalFaultVec[6];
      jalFaultVecNext_7 <= jalFaultVec[7];
      jalFaultVecNext_8 <= jalFaultVec[8];
      jalFaultVecNext_9 <= jalFaultVec[9];
      jalFaultVecNext_10 <= jalFaultVec[10];
      jalFaultVecNext_11 <= jalFaultVec[11];
      jalFaultVecNext_12 <= jalFaultVec[12];
      jalFaultVecNext_13 <= jalFaultVec[13];
      jalFaultVecNext_14 <= jalFaultVec[14];
      jalFaultVecNext_15 <= jalFaultVec[15];
      jalrFaultVecNext_0 <= jalrFaultVec[0];
      jalrFaultVecNext_1 <= jalrFaultVec[1];
      jalrFaultVecNext_2 <= jalrFaultVec[2];
      jalrFaultVecNext_3 <= jalrFaultVec[3];
      jalrFaultVecNext_4 <= jalrFaultVec[4];
      jalrFaultVecNext_5 <= jalrFaultVec[5];
      jalrFaultVecNext_6 <= jalrFaultVec[6];
      jalrFaultVecNext_7 <= jalrFaultVec[7];
      jalrFaultVecNext_8 <= jalrFaultVec[8];
      jalrFaultVecNext_9 <= jalrFaultVec[9];
      jalrFaultVecNext_10 <= jalrFaultVec[10];
      jalrFaultVecNext_11 <= jalrFaultVec[11];
      jalrFaultVecNext_12 <= jalrFaultVec[12];
      jalrFaultVecNext_13 <= jalrFaultVec[13];
      jalrFaultVecNext_14 <= jalrFaultVec[14];
      jalrFaultVecNext_15 <= jalrFaultVec[15];
      retFaultVecNext_0 <= retFaultVec[0];
      retFaultVecNext_1 <= retFaultVec[1];
      retFaultVecNext_2 <= retFaultVec[2];
      retFaultVecNext_3 <= retFaultVec[3];
      retFaultVecNext_4 <= retFaultVec[4];
      retFaultVecNext_5 <= retFaultVec[5];
      retFaultVecNext_6 <= retFaultVec[6];
      retFaultVecNext_7 <= retFaultVec[7];
      retFaultVecNext_8 <= retFaultVec[8];
      retFaultVecNext_9 <= retFaultVec[9];
      retFaultVecNext_10 <= retFaultVec[10];
      retFaultVecNext_11 <= retFaultVec[11];
      retFaultVecNext_12 <= retFaultVec[12];
      retFaultVecNext_13 <= retFaultVec[13];
      retFaultVecNext_14 <= retFaultVec[14];
      retFaultVecNext_15 <= retFaultVec[15];
      notCFITakenNext_0 <=
        inFixedRange[0] & io_in_instrValid_0 & predTakenAt[0]
        & (io_in_pds_0_brType == 2'h0) & io_in_ftqOffset_valid;
      notCFITakenNext_1 <=
        inFixedRange[1] & io_in_instrValid_1 & predTakenAt[1]
        & (io_in_pds_1_brType == 2'h0) & io_in_ftqOffset_valid;
      notCFITakenNext_2 <=
        inFixedRange[2] & io_in_instrValid_2 & predTakenAt[2]
        & (io_in_pds_2_brType == 2'h0) & io_in_ftqOffset_valid;
      notCFITakenNext_3 <=
        inFixedRange[3] & io_in_instrValid_3 & predTakenAt[3]
        & (io_in_pds_3_brType == 2'h0) & io_in_ftqOffset_valid;
      notCFITakenNext_4 <=
        inFixedRange[4] & io_in_instrValid_4 & predTakenAt[4]
        & (io_in_pds_4_brType == 2'h0) & io_in_ftqOffset_valid;
      notCFITakenNext_5 <=
        inFixedRange[5] & io_in_instrValid_5 & predTakenAt[5]
        & (io_in_pds_5_brType == 2'h0) & io_in_ftqOffset_valid;
      notCFITakenNext_6 <=
        inFixedRange[6] & io_in_instrValid_6 & predTakenAt[6]
        & (io_in_pds_6_brType == 2'h0) & io_in_ftqOffset_valid;
      notCFITakenNext_7 <=
        inFixedRange[7] & io_in_instrValid_7 & predTakenAt[7]
        & (io_in_pds_7_brType == 2'h0) & io_in_ftqOffset_valid;
      notCFITakenNext_8 <=
        inFixedRange[8] & io_in_instrValid_8 & predTakenAt[8]
        & (io_in_pds_8_brType == 2'h0) & io_in_ftqOffset_valid;
      notCFITakenNext_9 <=
        inFixedRange[9] & io_in_instrValid_9 & predTakenAt[9]
        & (io_in_pds_9_brType == 2'h0) & io_in_ftqOffset_valid;
      notCFITakenNext_10 <=
        inFixedRange[10] & io_in_instrValid_10 & predTakenAt[10]
        & (io_in_pds_10_brType == 2'h0) & io_in_ftqOffset_valid;
      notCFITakenNext_11 <=
        inFixedRange[11] & io_in_instrValid_11 & predTakenAt[11]
        & (io_in_pds_11_brType == 2'h0) & io_in_ftqOffset_valid;
      notCFITakenNext_12 <=
        inFixedRange[12] & io_in_instrValid_12 & predTakenAt[12]
        & (io_in_pds_12_brType == 2'h0) & io_in_ftqOffset_valid;
      notCFITakenNext_13 <=
        inFixedRange[13] & io_in_instrValid_13 & predTakenAt[13]
        & (io_in_pds_13_brType == 2'h0) & io_in_ftqOffset_valid;
      notCFITakenNext_14 <=
        inFixedRange[14] & io_in_instrValid_14 & predTakenAt[14]
        & (io_in_pds_14_brType == 2'h0) & io_in_ftqOffset_valid;
      notCFITakenNext_15 <=
        inFixedRange[15] & io_in_instrValid_15 & predTakenAt[15]
        & (io_in_pds_15_brType == 2'h0) & io_in_ftqOffset_valid;
      invalidTakenNext_0 <=
        inFixedRange[0] & ~io_in_instrValid_0 & predTakenAt[0] & io_in_ftqOffset_valid;
      invalidTakenNext_1 <=
        inFixedRange[1] & ~io_in_instrValid_1 & predTakenAt[1] & io_in_ftqOffset_valid;
      invalidTakenNext_2 <=
        inFixedRange[2] & ~io_in_instrValid_2 & predTakenAt[2] & io_in_ftqOffset_valid;
      invalidTakenNext_3 <=
        inFixedRange[3] & ~io_in_instrValid_3 & predTakenAt[3] & io_in_ftqOffset_valid;
      invalidTakenNext_4 <=
        inFixedRange[4] & ~io_in_instrValid_4 & predTakenAt[4] & io_in_ftqOffset_valid;
      invalidTakenNext_5 <=
        inFixedRange[5] & ~io_in_instrValid_5 & predTakenAt[5] & io_in_ftqOffset_valid;
      invalidTakenNext_6 <=
        inFixedRange[6] & ~io_in_instrValid_6 & predTakenAt[6] & io_in_ftqOffset_valid;
      invalidTakenNext_7 <=
        inFixedRange[7] & ~io_in_instrValid_7 & predTakenAt[7] & io_in_ftqOffset_valid;
      invalidTakenNext_8 <=
        inFixedRange[8] & ~io_in_instrValid_8 & predTakenAt[8] & io_in_ftqOffset_valid;
      invalidTakenNext_9 <=
        inFixedRange[9] & ~io_in_instrValid_9 & predTakenAt[9] & io_in_ftqOffset_valid;
      invalidTakenNext_10 <=
        inFixedRange[10] & ~io_in_instrValid_10 & predTakenAt[10] & io_in_ftqOffset_valid;
      invalidTakenNext_11 <=
        inFixedRange[11] & ~io_in_instrValid_11 & predTakenAt[11] & io_in_ftqOffset_valid;
      invalidTakenNext_12 <=
        inFixedRange[12] & ~io_in_instrValid_12 & predTakenAt[12] & io_in_ftqOffset_valid;
      invalidTakenNext_13 <=
        inFixedRange[13] & ~io_in_instrValid_13 & predTakenAt[13] & io_in_ftqOffset_valid;
      invalidTakenNext_14 <=
        inFixedRange[14] & ~io_in_instrValid_14 & predTakenAt[14] & io_in_ftqOffset_valid;
      invalidTakenNext_15 <=
        inFixedRange[15] & ~io_in_instrValid_15 & predTakenAt[15] & io_in_ftqOffset_valid;
    end
  end

  // ---------------- S2: 由寄存器重算 targetFault(组合) --------------------
  // targetFault_i: 该 lane 是预测 taken 的条件分支/jal, 但预测目标与
  // 重算跳转目标不符。
  wire targetFault_0 =
    fixedRangeNext[0] & instrValidNext_0
    & ((pdsNext_0_brType == 2'h2) | (pdsNext_0_brType == 2'h1))
    & (takenIdxNext == 4'h0) & predTakenNext
    & (predTargetNext != jumpTargetsNext_0);
  wire targetFault_1 =
    fixedRangeNext[1] & instrValidNext_1
    & ((pdsNext_1_brType == 2'h2) | (pdsNext_1_brType == 2'h1))
    & (takenIdxNext == 4'h1) & predTakenNext
    & (predTargetNext != jumpTargetsNext_1);
  wire targetFault_2 =
    fixedRangeNext[2] & instrValidNext_2
    & ((pdsNext_2_brType == 2'h2) | (pdsNext_2_brType == 2'h1))
    & (takenIdxNext == 4'h2) & predTakenNext
    & (predTargetNext != jumpTargetsNext_2);
  wire targetFault_3 =
    fixedRangeNext[3] & instrValidNext_3
    & ((pdsNext_3_brType == 2'h2) | (pdsNext_3_brType == 2'h1))
    & (takenIdxNext == 4'h3) & predTakenNext
    & (predTargetNext != jumpTargetsNext_3);
  wire targetFault_4 =
    fixedRangeNext[4] & instrValidNext_4
    & ((pdsNext_4_brType == 2'h2) | (pdsNext_4_brType == 2'h1))
    & (takenIdxNext == 4'h4) & predTakenNext
    & (predTargetNext != jumpTargetsNext_4);
  wire targetFault_5 =
    fixedRangeNext[5] & instrValidNext_5
    & ((pdsNext_5_brType == 2'h2) | (pdsNext_5_brType == 2'h1))
    & (takenIdxNext == 4'h5) & predTakenNext
    & (predTargetNext != jumpTargetsNext_5);
  wire targetFault_6 =
    fixedRangeNext[6] & instrValidNext_6
    & ((pdsNext_6_brType == 2'h2) | (pdsNext_6_brType == 2'h1))
    & (takenIdxNext == 4'h6) & predTakenNext
    & (predTargetNext != jumpTargetsNext_6);
  wire targetFault_7 =
    fixedRangeNext[7] & instrValidNext_7
    & ((pdsNext_7_brType == 2'h2) | (pdsNext_7_brType == 2'h1))
    & (takenIdxNext == 4'h7) & predTakenNext
    & (predTargetNext != jumpTargetsNext_7);
  wire targetFault_8 =
    fixedRangeNext[8] & instrValidNext_8
    & ((pdsNext_8_brType == 2'h2) | (pdsNext_8_brType == 2'h1))
    & (takenIdxNext == 4'h8) & predTakenNext
    & (predTargetNext != jumpTargetsNext_8);
  wire targetFault_9 =
    fixedRangeNext[9] & instrValidNext_9
    & ((pdsNext_9_brType == 2'h2) | (pdsNext_9_brType == 2'h1))
    & (takenIdxNext == 4'h9) & predTakenNext
    & (predTargetNext != jumpTargetsNext_9);
  wire targetFault_10 =
    fixedRangeNext[10] & instrValidNext_10
    & ((pdsNext_10_brType == 2'h2) | (pdsNext_10_brType == 2'h1))
    & (takenIdxNext == 4'hA) & predTakenNext
    & (predTargetNext != jumpTargetsNext_10);
  wire targetFault_11 =
    fixedRangeNext[11] & instrValidNext_11
    & ((pdsNext_11_brType == 2'h2) | (pdsNext_11_brType == 2'h1))
    & (takenIdxNext == 4'hB) & predTakenNext
    & (predTargetNext != jumpTargetsNext_11);
  wire targetFault_12 =
    fixedRangeNext[12] & instrValidNext_12
    & ((pdsNext_12_brType == 2'h2) | (pdsNext_12_brType == 2'h1))
    & (takenIdxNext == 4'hC) & predTakenNext
    & (predTargetNext != jumpTargetsNext_12);
  wire targetFault_13 =
    fixedRangeNext[13] & instrValidNext_13
    & ((pdsNext_13_brType == 2'h2) | (pdsNext_13_brType == 2'h1))
    & (takenIdxNext == 4'hD) & predTakenNext
    & (predTargetNext != jumpTargetsNext_13);
  wire targetFault_14 =
    fixedRangeNext[14] & instrValidNext_14
    & ((pdsNext_14_brType == 2'h2) | (pdsNext_14_brType == 2'h1))
    & (takenIdxNext == 4'hE) & predTakenNext
    & (predTargetNext != jumpTargetsNext_14);
  wire targetFault_15 =
    fixedRangeNext[15] & instrValidNext_15
    & ((pdsNext_15_brType == 2'h2) | (pdsNext_15_brType == 2'h1))
    & (takenIdxNext == 4'hF) & predTakenNext
    & (predTargetNext != jumpTargetsNext_15);

  // ---------------- 输出 ----------------
  assign io_out_stage1Out_fixedRange_0 = fixedRange[0];
  assign io_out_stage1Out_fixedRange_1 = fixedRange[1];
  assign io_out_stage1Out_fixedRange_2 = fixedRange[2];
  assign io_out_stage1Out_fixedRange_3 = fixedRange[3];
  assign io_out_stage1Out_fixedRange_4 = fixedRange[4];
  assign io_out_stage1Out_fixedRange_5 = fixedRange[5];
  assign io_out_stage1Out_fixedRange_6 = fixedRange[6];
  assign io_out_stage1Out_fixedRange_7 = fixedRange[7];
  assign io_out_stage1Out_fixedRange_8 = fixedRange[8];
  assign io_out_stage1Out_fixedRange_9 = fixedRange[9];
  assign io_out_stage1Out_fixedRange_10 = fixedRange[10];
  assign io_out_stage1Out_fixedRange_11 = fixedRange[11];
  assign io_out_stage1Out_fixedRange_12 = fixedRange[12];
  assign io_out_stage1Out_fixedRange_13 = fixedRange[13];
  assign io_out_stage1Out_fixedRange_14 = fixedRange[14];
  assign io_out_stage1Out_fixedRange_15 = fixedRange[15];
  assign io_out_stage1Out_fixedTaken_0 = fixedTaken[0];
  assign io_out_stage1Out_fixedTaken_1 = fixedTaken[1];
  assign io_out_stage1Out_fixedTaken_2 = fixedTaken[2];
  assign io_out_stage1Out_fixedTaken_3 = fixedTaken[3];
  assign io_out_stage1Out_fixedTaken_4 = fixedTaken[4];
  assign io_out_stage1Out_fixedTaken_5 = fixedTaken[5];
  assign io_out_stage1Out_fixedTaken_6 = fixedTaken[6];
  assign io_out_stage1Out_fixedTaken_7 = fixedTaken[7];
  assign io_out_stage1Out_fixedTaken_8 = fixedTaken[8];
  assign io_out_stage1Out_fixedTaken_9 = fixedTaken[9];
  assign io_out_stage1Out_fixedTaken_10 = fixedTaken[10];
  assign io_out_stage1Out_fixedTaken_11 = fixedTaken[11];
  assign io_out_stage1Out_fixedTaken_12 = fixedTaken[12];
  assign io_out_stage1Out_fixedTaken_13 = fixedTaken[13];
  assign io_out_stage1Out_fixedTaken_14 = fixedTaken[14];
  assign io_out_stage1Out_fixedTaken_15 = fixedTaken[15];
  assign io_out_stage2Out_fixedTarget_0 =
    jalFaultVecNext_0 | targetFault_0 ? jumpTargetsNext_0 : seqTargetsNext_0;
  assign io_out_stage2Out_fixedTarget_1 =
    jalFaultVecNext_1 | targetFault_1 ? jumpTargetsNext_1 : seqTargetsNext_1;
  assign io_out_stage2Out_fixedTarget_2 =
    jalFaultVecNext_2 | targetFault_2 ? jumpTargetsNext_2 : seqTargetsNext_2;
  assign io_out_stage2Out_fixedTarget_3 =
    jalFaultVecNext_3 | targetFault_3 ? jumpTargetsNext_3 : seqTargetsNext_3;
  assign io_out_stage2Out_fixedTarget_4 =
    jalFaultVecNext_4 | targetFault_4 ? jumpTargetsNext_4 : seqTargetsNext_4;
  assign io_out_stage2Out_fixedTarget_5 =
    jalFaultVecNext_5 | targetFault_5 ? jumpTargetsNext_5 : seqTargetsNext_5;
  assign io_out_stage2Out_fixedTarget_6 =
    jalFaultVecNext_6 | targetFault_6 ? jumpTargetsNext_6 : seqTargetsNext_6;
  assign io_out_stage2Out_fixedTarget_7 =
    jalFaultVecNext_7 | targetFault_7 ? jumpTargetsNext_7 : seqTargetsNext_7;
  assign io_out_stage2Out_fixedTarget_8 =
    jalFaultVecNext_8 | targetFault_8 ? jumpTargetsNext_8 : seqTargetsNext_8;
  assign io_out_stage2Out_fixedTarget_9 =
    jalFaultVecNext_9 | targetFault_9 ? jumpTargetsNext_9 : seqTargetsNext_9;
  assign io_out_stage2Out_fixedTarget_10 =
    jalFaultVecNext_10 | targetFault_10 ? jumpTargetsNext_10 : seqTargetsNext_10;
  assign io_out_stage2Out_fixedTarget_11 =
    jalFaultVecNext_11 | targetFault_11 ? jumpTargetsNext_11 : seqTargetsNext_11;
  assign io_out_stage2Out_fixedTarget_12 =
    jalFaultVecNext_12 | targetFault_12 ? jumpTargetsNext_12 : seqTargetsNext_12;
  assign io_out_stage2Out_fixedTarget_13 =
    jalFaultVecNext_13 | targetFault_13 ? jumpTargetsNext_13 : seqTargetsNext_13;
  assign io_out_stage2Out_fixedTarget_14 =
    jalFaultVecNext_14 | targetFault_14 ? jumpTargetsNext_14 : seqTargetsNext_14;
  assign io_out_stage2Out_fixedTarget_15 =
    jalFaultVecNext_15 | targetFault_15 ? jumpTargetsNext_15 : seqTargetsNext_15;
  assign io_out_stage2Out_jalTarget_0 = jumpTargetsNext_0;
  assign io_out_stage2Out_jalTarget_1 = jumpTargetsNext_1;
  assign io_out_stage2Out_jalTarget_2 = jumpTargetsNext_2;
  assign io_out_stage2Out_jalTarget_3 = jumpTargetsNext_3;
  assign io_out_stage2Out_jalTarget_4 = jumpTargetsNext_4;
  assign io_out_stage2Out_jalTarget_5 = jumpTargetsNext_5;
  assign io_out_stage2Out_jalTarget_6 = jumpTargetsNext_6;
  assign io_out_stage2Out_jalTarget_7 = jumpTargetsNext_7;
  assign io_out_stage2Out_jalTarget_8 = jumpTargetsNext_8;
  assign io_out_stage2Out_jalTarget_9 = jumpTargetsNext_9;
  assign io_out_stage2Out_jalTarget_10 = jumpTargetsNext_10;
  assign io_out_stage2Out_jalTarget_11 = jumpTargetsNext_11;
  assign io_out_stage2Out_jalTarget_12 = jumpTargetsNext_12;
  assign io_out_stage2Out_jalTarget_13 = jumpTargetsNext_13;
  assign io_out_stage2Out_jalTarget_14 = jumpTargetsNext_14;
  assign io_out_stage2Out_jalTarget_15 = jumpTargetsNext_15;
  assign io_out_stage2Out_fixedMissPred_0 =
    jalFaultVecNext_0 | jalrFaultVecNext_0 | retFaultVecNext_0
    | notCFITakenNext_0 | invalidTakenNext_0 | targetFault_0;
  assign io_out_stage2Out_fixedMissPred_1 =
    jalFaultVecNext_1 | jalrFaultVecNext_1 | retFaultVecNext_1
    | notCFITakenNext_1 | invalidTakenNext_1 | targetFault_1;
  assign io_out_stage2Out_fixedMissPred_2 =
    jalFaultVecNext_2 | jalrFaultVecNext_2 | retFaultVecNext_2
    | notCFITakenNext_2 | invalidTakenNext_2 | targetFault_2;
  assign io_out_stage2Out_fixedMissPred_3 =
    jalFaultVecNext_3 | jalrFaultVecNext_3 | retFaultVecNext_3
    | notCFITakenNext_3 | invalidTakenNext_3 | targetFault_3;
  assign io_out_stage2Out_fixedMissPred_4 =
    jalFaultVecNext_4 | jalrFaultVecNext_4 | retFaultVecNext_4
    | notCFITakenNext_4 | invalidTakenNext_4 | targetFault_4;
  assign io_out_stage2Out_fixedMissPred_5 =
    jalFaultVecNext_5 | jalrFaultVecNext_5 | retFaultVecNext_5
    | notCFITakenNext_5 | invalidTakenNext_5 | targetFault_5;
  assign io_out_stage2Out_fixedMissPred_6 =
    jalFaultVecNext_6 | jalrFaultVecNext_6 | retFaultVecNext_6
    | notCFITakenNext_6 | invalidTakenNext_6 | targetFault_6;
  assign io_out_stage2Out_fixedMissPred_7 =
    jalFaultVecNext_7 | jalrFaultVecNext_7 | retFaultVecNext_7
    | notCFITakenNext_7 | invalidTakenNext_7 | targetFault_7;
  assign io_out_stage2Out_fixedMissPred_8 =
    jalFaultVecNext_8 | jalrFaultVecNext_8 | retFaultVecNext_8
    | notCFITakenNext_8 | invalidTakenNext_8 | targetFault_8;
  assign io_out_stage2Out_fixedMissPred_9 =
    jalFaultVecNext_9 | jalrFaultVecNext_9 | retFaultVecNext_9
    | notCFITakenNext_9 | invalidTakenNext_9 | targetFault_9;
  assign io_out_stage2Out_fixedMissPred_10 =
    jalFaultVecNext_10 | jalrFaultVecNext_10 | retFaultVecNext_10
    | notCFITakenNext_10 | invalidTakenNext_10 | targetFault_10;
  assign io_out_stage2Out_fixedMissPred_11 =
    jalFaultVecNext_11 | jalrFaultVecNext_11 | retFaultVecNext_11
    | notCFITakenNext_11 | invalidTakenNext_11 | targetFault_11;
  assign io_out_stage2Out_fixedMissPred_12 =
    jalFaultVecNext_12 | jalrFaultVecNext_12 | retFaultVecNext_12
    | notCFITakenNext_12 | invalidTakenNext_12 | targetFault_12;
  assign io_out_stage2Out_fixedMissPred_13 =
    jalFaultVecNext_13 | jalrFaultVecNext_13 | retFaultVecNext_13
    | notCFITakenNext_13 | invalidTakenNext_13 | targetFault_13;
  assign io_out_stage2Out_fixedMissPred_14 =
    jalFaultVecNext_14 | jalrFaultVecNext_14 | retFaultVecNext_14
    | notCFITakenNext_14 | invalidTakenNext_14 | targetFault_14;
  assign io_out_stage2Out_fixedMissPred_15 =
    jalFaultVecNext_15 | jalrFaultVecNext_15 | retFaultVecNext_15
    | notCFITakenNext_15 | invalidTakenNext_15 | targetFault_15;
  assign io_out_stage2Out_faultType_0_value =
    jalFaultVecNext_0 ? 3'h1
      : jalrFaultVecNext_0 ? 3'h6
      : retFaultVecNext_0 ? 3'h2
      : targetFault_0 ? 3'h3
      : notCFITakenNext_0 ? 3'h4 : invalidTakenNext_0 ? 3'h5 : 3'h0;
  assign io_out_stage2Out_faultType_1_value =
    jalFaultVecNext_1 ? 3'h1
      : jalrFaultVecNext_1 ? 3'h6
      : retFaultVecNext_1 ? 3'h2
      : targetFault_1 ? 3'h3
      : notCFITakenNext_1 ? 3'h4 : invalidTakenNext_1 ? 3'h5 : 3'h0;
  assign io_out_stage2Out_faultType_2_value =
    jalFaultVecNext_2 ? 3'h1
      : jalrFaultVecNext_2 ? 3'h6
      : retFaultVecNext_2 ? 3'h2
      : targetFault_2 ? 3'h3
      : notCFITakenNext_2 ? 3'h4 : invalidTakenNext_2 ? 3'h5 : 3'h0;
  assign io_out_stage2Out_faultType_3_value =
    jalFaultVecNext_3 ? 3'h1
      : jalrFaultVecNext_3 ? 3'h6
      : retFaultVecNext_3 ? 3'h2
      : targetFault_3 ? 3'h3
      : notCFITakenNext_3 ? 3'h4 : invalidTakenNext_3 ? 3'h5 : 3'h0;
  assign io_out_stage2Out_faultType_4_value =
    jalFaultVecNext_4 ? 3'h1
      : jalrFaultVecNext_4 ? 3'h6
      : retFaultVecNext_4 ? 3'h2
      : targetFault_4 ? 3'h3
      : notCFITakenNext_4 ? 3'h4 : invalidTakenNext_4 ? 3'h5 : 3'h0;
  assign io_out_stage2Out_faultType_5_value =
    jalFaultVecNext_5 ? 3'h1
      : jalrFaultVecNext_5 ? 3'h6
      : retFaultVecNext_5 ? 3'h2
      : targetFault_5 ? 3'h3
      : notCFITakenNext_5 ? 3'h4 : invalidTakenNext_5 ? 3'h5 : 3'h0;
  assign io_out_stage2Out_faultType_6_value =
    jalFaultVecNext_6 ? 3'h1
      : jalrFaultVecNext_6 ? 3'h6
      : retFaultVecNext_6 ? 3'h2
      : targetFault_6 ? 3'h3
      : notCFITakenNext_6 ? 3'h4 : invalidTakenNext_6 ? 3'h5 : 3'h0;
  assign io_out_stage2Out_faultType_7_value =
    jalFaultVecNext_7 ? 3'h1
      : jalrFaultVecNext_7 ? 3'h6
      : retFaultVecNext_7 ? 3'h2
      : targetFault_7 ? 3'h3
      : notCFITakenNext_7 ? 3'h4 : invalidTakenNext_7 ? 3'h5 : 3'h0;
  assign io_out_stage2Out_faultType_8_value =
    jalFaultVecNext_8 ? 3'h1
      : jalrFaultVecNext_8 ? 3'h6
      : retFaultVecNext_8 ? 3'h2
      : targetFault_8 ? 3'h3
      : notCFITakenNext_8 ? 3'h4 : invalidTakenNext_8 ? 3'h5 : 3'h0;
  assign io_out_stage2Out_faultType_9_value =
    jalFaultVecNext_9 ? 3'h1
      : jalrFaultVecNext_9 ? 3'h6
      : retFaultVecNext_9 ? 3'h2
      : targetFault_9 ? 3'h3
      : notCFITakenNext_9 ? 3'h4 : invalidTakenNext_9 ? 3'h5 : 3'h0;
  assign io_out_stage2Out_faultType_10_value =
    jalFaultVecNext_10 ? 3'h1
      : jalrFaultVecNext_10 ? 3'h6
      : retFaultVecNext_10 ? 3'h2
      : targetFault_10 ? 3'h3
      : notCFITakenNext_10 ? 3'h4 : invalidTakenNext_10 ? 3'h5 : 3'h0;
  assign io_out_stage2Out_faultType_11_value =
    jalFaultVecNext_11 ? 3'h1
      : jalrFaultVecNext_11 ? 3'h6
      : retFaultVecNext_11 ? 3'h2
      : targetFault_11 ? 3'h3
      : notCFITakenNext_11 ? 3'h4 : invalidTakenNext_11 ? 3'h5 : 3'h0;
  assign io_out_stage2Out_faultType_12_value =
    jalFaultVecNext_12 ? 3'h1
      : jalrFaultVecNext_12 ? 3'h6
      : retFaultVecNext_12 ? 3'h2
      : targetFault_12 ? 3'h3
      : notCFITakenNext_12 ? 3'h4 : invalidTakenNext_12 ? 3'h5 : 3'h0;
  assign io_out_stage2Out_faultType_13_value =
    jalFaultVecNext_13 ? 3'h1
      : jalrFaultVecNext_13 ? 3'h6
      : retFaultVecNext_13 ? 3'h2
      : targetFault_13 ? 3'h3
      : notCFITakenNext_13 ? 3'h4 : invalidTakenNext_13 ? 3'h5 : 3'h0;
  assign io_out_stage2Out_faultType_14_value =
    jalFaultVecNext_14 ? 3'h1
      : jalrFaultVecNext_14 ? 3'h6
      : retFaultVecNext_14 ? 3'h2
      : targetFault_14 ? 3'h3
      : notCFITakenNext_14 ? 3'h4 : invalidTakenNext_14 ? 3'h5 : 3'h0;
  assign io_out_stage2Out_faultType_15_value =
    jalFaultVecNext_15 ? 3'h1
      : jalrFaultVecNext_15 ? 3'h6
      : retFaultVecNext_15 ? 3'h2
      : targetFault_15 ? 3'h3
      : notCFITakenNext_15 ? 3'h4 : invalidTakenNext_15 ? 3'h5 : 3'h0;
endmodule
