// =============================================================================
// SCTable 变体包装层
//
// Chisel 把参数化的 SCTable 单态化成 4 个同名模块（SCTable / _1 / _2 / _3），差异仅在
// 读折叠历史长度与索引折叠方式。本文件用各 golden 同名模块名 + 完全一致的扁平端口，
// 例化参数化可读核 xs_SCTable_core（IDX_SCHEME / HIST_W / MBIST_ARRAY_ID 选变体），用于：
//   1) Formality 与 golden 同名顶层做等价比对；
//   2) 系统级验证时直接替换 build/rtl 下的同名生成文件。
// 包装层是机械的端口适配层（折叠历史/ghist 输入按变体接入或置 0）。
//
// 变体对照（V2R2 KunminghuV2Config，SC 4 张表）：
//   SCTable   : 无历史,           idx=pc[8:1],            MBIST array 0x42
//   SCTable_1 : 折叠历史 4-bit,   idx 仅异或低 4 位,       MBIST array 0x43
//   SCTable_2 : 折叠历史 8-bit,   histLen=11 折 8(含自异或),MBIST array 0x44
//   SCTable_3 : 折叠历史 8-bit,   histLen=16 折 8(两段异或),MBIST array 0x45
// =============================================================================

module SCTable(
  input         clock,
  input         reset,
  input         io_req_valid,
  input  [49:0] io_req_bits_pc,
  output [5:0]  io_resp_ctrs_0_0,
  output [5:0]  io_resp_ctrs_0_1,
  output [5:0]  io_resp_ctrs_1_0,
  output [5:0]  io_resp_ctrs_1_1,
  input  [49:0] io_update_pc,
  input         io_update_mask_0,
  input         io_update_mask_1,
  input  [5:0]  io_update_oldCtrs_0,
  input  [5:0]  io_update_oldCtrs_1,
  input         io_update_tagePreds_0,
  input         io_update_tagePreds_1,
  input         io_update_takens_0,
  input         io_update_takens_1,
  input  [6:0]  boreChildrenBd_bore_array,
  input         boreChildrenBd_bore_all,
  input         boreChildrenBd_bore_req,
  output        boreChildrenBd_bore_ack,
  input         boreChildrenBd_bore_writeen,
  input  [3:0]  boreChildrenBd_bore_be,
  input  [8:0]  boreChildrenBd_bore_addr,
  input  [23:0] boreChildrenBd_bore_indata,
  input         boreChildrenBd_bore_readen,
  input  [8:0]  boreChildrenBd_bore_addr_rd,
  output [23:0] boreChildrenBd_bore_outdata,
  input         sigFromSrams_bore_ram_hold,
  input         sigFromSrams_bore_ram_bypass,
  input         sigFromSrams_bore_ram_bp_clken,
  input         sigFromSrams_bore_ram_aux_clk,
  input         sigFromSrams_bore_ram_aux_ckbp,
  input         sigFromSrams_bore_ram_mcp_hold,
  input         sigFromSrams_bore_cgen
);
  xs_SCTable_core #(
    .IDX_SCHEME(0), .HIST_W(1), .MBIST_ARRAY_ID(7'h42)
  ) u_core (
    .clock(clock), .reset(reset),
    .io_req_valid(io_req_valid),
    .io_req_bits_pc(io_req_bits_pc),
    .io_req_folded_hist(1'b0),
    .io_resp_ctrs_0_0(io_resp_ctrs_0_0),
    .io_resp_ctrs_0_1(io_resp_ctrs_0_1),
    .io_resp_ctrs_1_0(io_resp_ctrs_1_0),
    .io_resp_ctrs_1_1(io_resp_ctrs_1_1),
    .io_update_pc(io_update_pc),
    .io_update_ghist(256'h0),
    .io_update_mask_0(io_update_mask_0),
    .io_update_mask_1(io_update_mask_1),
    .io_update_oldCtrs_0(io_update_oldCtrs_0),
    .io_update_oldCtrs_1(io_update_oldCtrs_1),
    .io_update_tagePreds_0(io_update_tagePreds_0),
    .io_update_tagePreds_1(io_update_tagePreds_1),
    .io_update_takens_0(io_update_takens_0),
    .io_update_takens_1(io_update_takens_1),
    .boreChildrenBd_bore_array(boreChildrenBd_bore_array),
    .boreChildrenBd_bore_all(boreChildrenBd_bore_all),
    .boreChildrenBd_bore_req(boreChildrenBd_bore_req),
    .boreChildrenBd_bore_ack(boreChildrenBd_bore_ack),
    .boreChildrenBd_bore_writeen(boreChildrenBd_bore_writeen),
    .boreChildrenBd_bore_be(boreChildrenBd_bore_be),
    .boreChildrenBd_bore_addr(boreChildrenBd_bore_addr),
    .boreChildrenBd_bore_indata(boreChildrenBd_bore_indata),
    .boreChildrenBd_bore_readen(boreChildrenBd_bore_readen),
    .boreChildrenBd_bore_addr_rd(boreChildrenBd_bore_addr_rd),
    .boreChildrenBd_bore_outdata(boreChildrenBd_bore_outdata),
    .sigFromSrams_bore_ram_hold(sigFromSrams_bore_ram_hold),
    .sigFromSrams_bore_ram_bypass(sigFromSrams_bore_ram_bypass),
    .sigFromSrams_bore_ram_bp_clken(sigFromSrams_bore_ram_bp_clken),
    .sigFromSrams_bore_ram_aux_clk(sigFromSrams_bore_ram_aux_clk),
    .sigFromSrams_bore_ram_aux_ckbp(sigFromSrams_bore_ram_aux_ckbp),
    .sigFromSrams_bore_ram_mcp_hold(sigFromSrams_bore_ram_mcp_hold),
    .sigFromSrams_bore_cgen(sigFromSrams_bore_cgen)
  );
endmodule

module SCTable_1(
  input         clock,
  input         reset,
  input         io_req_valid,
  input  [49:0] io_req_bits_pc,
  input  [3:0] io_req_bits_folded_hist_hist_12_folded_hist,
  output [5:0]  io_resp_ctrs_0_0,
  output [5:0]  io_resp_ctrs_0_1,
  output [5:0]  io_resp_ctrs_1_0,
  output [5:0]  io_resp_ctrs_1_1,
  input  [49:0] io_update_pc,
  input  [255:0] io_update_ghist,
  input         io_update_mask_0,
  input         io_update_mask_1,
  input  [5:0]  io_update_oldCtrs_0,
  input  [5:0]  io_update_oldCtrs_1,
  input         io_update_tagePreds_0,
  input         io_update_tagePreds_1,
  input         io_update_takens_0,
  input         io_update_takens_1,
  input  [6:0]  boreChildrenBd_bore_array,
  input         boreChildrenBd_bore_all,
  input         boreChildrenBd_bore_req,
  output        boreChildrenBd_bore_ack,
  input         boreChildrenBd_bore_writeen,
  input  [3:0]  boreChildrenBd_bore_be,
  input  [8:0]  boreChildrenBd_bore_addr,
  input  [23:0] boreChildrenBd_bore_indata,
  input         boreChildrenBd_bore_readen,
  input  [8:0]  boreChildrenBd_bore_addr_rd,
  output [23:0] boreChildrenBd_bore_outdata,
  input         sigFromSrams_bore_ram_hold,
  input         sigFromSrams_bore_ram_bypass,
  input         sigFromSrams_bore_ram_bp_clken,
  input         sigFromSrams_bore_ram_aux_clk,
  input         sigFromSrams_bore_ram_aux_ckbp,
  input         sigFromSrams_bore_ram_mcp_hold,
  input         sigFromSrams_bore_cgen
);
  xs_SCTable_core #(
    .IDX_SCHEME(1), .HIST_W(4), .MBIST_ARRAY_ID(7'h43)
  ) u_core (
    .clock(clock), .reset(reset),
    .io_req_valid(io_req_valid),
    .io_req_bits_pc(io_req_bits_pc),
    .io_req_folded_hist(io_req_bits_folded_hist_hist_12_folded_hist),
    .io_resp_ctrs_0_0(io_resp_ctrs_0_0),
    .io_resp_ctrs_0_1(io_resp_ctrs_0_1),
    .io_resp_ctrs_1_0(io_resp_ctrs_1_0),
    .io_resp_ctrs_1_1(io_resp_ctrs_1_1),
    .io_update_pc(io_update_pc),
    .io_update_ghist(io_update_ghist),
    .io_update_mask_0(io_update_mask_0),
    .io_update_mask_1(io_update_mask_1),
    .io_update_oldCtrs_0(io_update_oldCtrs_0),
    .io_update_oldCtrs_1(io_update_oldCtrs_1),
    .io_update_tagePreds_0(io_update_tagePreds_0),
    .io_update_tagePreds_1(io_update_tagePreds_1),
    .io_update_takens_0(io_update_takens_0),
    .io_update_takens_1(io_update_takens_1),
    .boreChildrenBd_bore_array(boreChildrenBd_bore_array),
    .boreChildrenBd_bore_all(boreChildrenBd_bore_all),
    .boreChildrenBd_bore_req(boreChildrenBd_bore_req),
    .boreChildrenBd_bore_ack(boreChildrenBd_bore_ack),
    .boreChildrenBd_bore_writeen(boreChildrenBd_bore_writeen),
    .boreChildrenBd_bore_be(boreChildrenBd_bore_be),
    .boreChildrenBd_bore_addr(boreChildrenBd_bore_addr),
    .boreChildrenBd_bore_indata(boreChildrenBd_bore_indata),
    .boreChildrenBd_bore_readen(boreChildrenBd_bore_readen),
    .boreChildrenBd_bore_addr_rd(boreChildrenBd_bore_addr_rd),
    .boreChildrenBd_bore_outdata(boreChildrenBd_bore_outdata),
    .sigFromSrams_bore_ram_hold(sigFromSrams_bore_ram_hold),
    .sigFromSrams_bore_ram_bypass(sigFromSrams_bore_ram_bypass),
    .sigFromSrams_bore_ram_bp_clken(sigFromSrams_bore_ram_bp_clken),
    .sigFromSrams_bore_ram_aux_clk(sigFromSrams_bore_ram_aux_clk),
    .sigFromSrams_bore_ram_aux_ckbp(sigFromSrams_bore_ram_aux_ckbp),
    .sigFromSrams_bore_ram_mcp_hold(sigFromSrams_bore_ram_mcp_hold),
    .sigFromSrams_bore_cgen(sigFromSrams_bore_cgen)
  );
endmodule

module SCTable_2(
  input         clock,
  input         reset,
  input         io_req_valid,
  input  [49:0] io_req_bits_pc,
  input  [7:0] io_req_bits_folded_hist_hist_11_folded_hist,
  output [5:0]  io_resp_ctrs_0_0,
  output [5:0]  io_resp_ctrs_0_1,
  output [5:0]  io_resp_ctrs_1_0,
  output [5:0]  io_resp_ctrs_1_1,
  input  [49:0] io_update_pc,
  input  [255:0] io_update_ghist,
  input         io_update_mask_0,
  input         io_update_mask_1,
  input  [5:0]  io_update_oldCtrs_0,
  input  [5:0]  io_update_oldCtrs_1,
  input         io_update_tagePreds_0,
  input         io_update_tagePreds_1,
  input         io_update_takens_0,
  input         io_update_takens_1,
  input  [6:0]  boreChildrenBd_bore_array,
  input         boreChildrenBd_bore_all,
  input         boreChildrenBd_bore_req,
  output        boreChildrenBd_bore_ack,
  input         boreChildrenBd_bore_writeen,
  input  [3:0]  boreChildrenBd_bore_be,
  input  [8:0]  boreChildrenBd_bore_addr,
  input  [23:0] boreChildrenBd_bore_indata,
  input         boreChildrenBd_bore_readen,
  input  [8:0]  boreChildrenBd_bore_addr_rd,
  output [23:0] boreChildrenBd_bore_outdata,
  input         sigFromSrams_bore_ram_hold,
  input         sigFromSrams_bore_ram_bypass,
  input         sigFromSrams_bore_ram_bp_clken,
  input         sigFromSrams_bore_ram_aux_clk,
  input         sigFromSrams_bore_ram_aux_ckbp,
  input         sigFromSrams_bore_ram_mcp_hold,
  input         sigFromSrams_bore_cgen
);
  xs_SCTable_core #(
    .IDX_SCHEME(2), .HIST_W(8), .MBIST_ARRAY_ID(7'h44)
  ) u_core (
    .clock(clock), .reset(reset),
    .io_req_valid(io_req_valid),
    .io_req_bits_pc(io_req_bits_pc),
    .io_req_folded_hist(io_req_bits_folded_hist_hist_11_folded_hist),
    .io_resp_ctrs_0_0(io_resp_ctrs_0_0),
    .io_resp_ctrs_0_1(io_resp_ctrs_0_1),
    .io_resp_ctrs_1_0(io_resp_ctrs_1_0),
    .io_resp_ctrs_1_1(io_resp_ctrs_1_1),
    .io_update_pc(io_update_pc),
    .io_update_ghist(io_update_ghist),
    .io_update_mask_0(io_update_mask_0),
    .io_update_mask_1(io_update_mask_1),
    .io_update_oldCtrs_0(io_update_oldCtrs_0),
    .io_update_oldCtrs_1(io_update_oldCtrs_1),
    .io_update_tagePreds_0(io_update_tagePreds_0),
    .io_update_tagePreds_1(io_update_tagePreds_1),
    .io_update_takens_0(io_update_takens_0),
    .io_update_takens_1(io_update_takens_1),
    .boreChildrenBd_bore_array(boreChildrenBd_bore_array),
    .boreChildrenBd_bore_all(boreChildrenBd_bore_all),
    .boreChildrenBd_bore_req(boreChildrenBd_bore_req),
    .boreChildrenBd_bore_ack(boreChildrenBd_bore_ack),
    .boreChildrenBd_bore_writeen(boreChildrenBd_bore_writeen),
    .boreChildrenBd_bore_be(boreChildrenBd_bore_be),
    .boreChildrenBd_bore_addr(boreChildrenBd_bore_addr),
    .boreChildrenBd_bore_indata(boreChildrenBd_bore_indata),
    .boreChildrenBd_bore_readen(boreChildrenBd_bore_readen),
    .boreChildrenBd_bore_addr_rd(boreChildrenBd_bore_addr_rd),
    .boreChildrenBd_bore_outdata(boreChildrenBd_bore_outdata),
    .sigFromSrams_bore_ram_hold(sigFromSrams_bore_ram_hold),
    .sigFromSrams_bore_ram_bypass(sigFromSrams_bore_ram_bypass),
    .sigFromSrams_bore_ram_bp_clken(sigFromSrams_bore_ram_bp_clken),
    .sigFromSrams_bore_ram_aux_clk(sigFromSrams_bore_ram_aux_clk),
    .sigFromSrams_bore_ram_aux_ckbp(sigFromSrams_bore_ram_aux_ckbp),
    .sigFromSrams_bore_ram_mcp_hold(sigFromSrams_bore_ram_mcp_hold),
    .sigFromSrams_bore_cgen(sigFromSrams_bore_cgen)
  );
endmodule

module SCTable_3(
  input         clock,
  input         reset,
  input         io_req_valid,
  input  [49:0] io_req_bits_pc,
  input  [7:0] io_req_bits_folded_hist_hist_2_folded_hist,
  output [5:0]  io_resp_ctrs_0_0,
  output [5:0]  io_resp_ctrs_0_1,
  output [5:0]  io_resp_ctrs_1_0,
  output [5:0]  io_resp_ctrs_1_1,
  input  [49:0] io_update_pc,
  input  [255:0] io_update_ghist,
  input         io_update_mask_0,
  input         io_update_mask_1,
  input  [5:0]  io_update_oldCtrs_0,
  input  [5:0]  io_update_oldCtrs_1,
  input         io_update_tagePreds_0,
  input         io_update_tagePreds_1,
  input         io_update_takens_0,
  input         io_update_takens_1,
  input  [6:0]  boreChildrenBd_bore_array,
  input         boreChildrenBd_bore_all,
  input         boreChildrenBd_bore_req,
  output        boreChildrenBd_bore_ack,
  input         boreChildrenBd_bore_writeen,
  input  [3:0]  boreChildrenBd_bore_be,
  input  [8:0]  boreChildrenBd_bore_addr,
  input  [23:0] boreChildrenBd_bore_indata,
  input         boreChildrenBd_bore_readen,
  input  [8:0]  boreChildrenBd_bore_addr_rd,
  output [23:0] boreChildrenBd_bore_outdata,
  input         sigFromSrams_bore_ram_hold,
  input         sigFromSrams_bore_ram_bypass,
  input         sigFromSrams_bore_ram_bp_clken,
  input         sigFromSrams_bore_ram_aux_clk,
  input         sigFromSrams_bore_ram_aux_ckbp,
  input         sigFromSrams_bore_ram_mcp_hold,
  input         sigFromSrams_bore_cgen
);
  xs_SCTable_core #(
    .IDX_SCHEME(3), .HIST_W(8), .MBIST_ARRAY_ID(7'h45)
  ) u_core (
    .clock(clock), .reset(reset),
    .io_req_valid(io_req_valid),
    .io_req_bits_pc(io_req_bits_pc),
    .io_req_folded_hist(io_req_bits_folded_hist_hist_2_folded_hist),
    .io_resp_ctrs_0_0(io_resp_ctrs_0_0),
    .io_resp_ctrs_0_1(io_resp_ctrs_0_1),
    .io_resp_ctrs_1_0(io_resp_ctrs_1_0),
    .io_resp_ctrs_1_1(io_resp_ctrs_1_1),
    .io_update_pc(io_update_pc),
    .io_update_ghist(io_update_ghist),
    .io_update_mask_0(io_update_mask_0),
    .io_update_mask_1(io_update_mask_1),
    .io_update_oldCtrs_0(io_update_oldCtrs_0),
    .io_update_oldCtrs_1(io_update_oldCtrs_1),
    .io_update_tagePreds_0(io_update_tagePreds_0),
    .io_update_tagePreds_1(io_update_tagePreds_1),
    .io_update_takens_0(io_update_takens_0),
    .io_update_takens_1(io_update_takens_1),
    .boreChildrenBd_bore_array(boreChildrenBd_bore_array),
    .boreChildrenBd_bore_all(boreChildrenBd_bore_all),
    .boreChildrenBd_bore_req(boreChildrenBd_bore_req),
    .boreChildrenBd_bore_ack(boreChildrenBd_bore_ack),
    .boreChildrenBd_bore_writeen(boreChildrenBd_bore_writeen),
    .boreChildrenBd_bore_be(boreChildrenBd_bore_be),
    .boreChildrenBd_bore_addr(boreChildrenBd_bore_addr),
    .boreChildrenBd_bore_indata(boreChildrenBd_bore_indata),
    .boreChildrenBd_bore_readen(boreChildrenBd_bore_readen),
    .boreChildrenBd_bore_addr_rd(boreChildrenBd_bore_addr_rd),
    .boreChildrenBd_bore_outdata(boreChildrenBd_bore_outdata),
    .sigFromSrams_bore_ram_hold(sigFromSrams_bore_ram_hold),
    .sigFromSrams_bore_ram_bypass(sigFromSrams_bore_ram_bypass),
    .sigFromSrams_bore_ram_bp_clken(sigFromSrams_bore_ram_bp_clken),
    .sigFromSrams_bore_ram_aux_clk(sigFromSrams_bore_ram_aux_clk),
    .sigFromSrams_bore_ram_aux_ckbp(sigFromSrams_bore_ram_aux_ckbp),
    .sigFromSrams_bore_ram_mcp_hold(sigFromSrams_bore_ram_mcp_hold),
    .sigFromSrams_bore_cgen(sigFromSrams_bore_cgen)
  );
endmodule

