// 自动生成：scripts/gen_fastarbiter.py —— 勿手改
module FastArbiter_27_xs(
  input clock,
  input reset,
  output io_in_0_ready,
  input io_in_0_valid,
  input [3:0] io_in_0_bits_qos,
  input [10:0] io_in_0_bits_tgtID,
  input [11:0] io_in_0_bits_txnID,
  input [4:0] io_in_0_bits_opcode,
  input [1:0] io_in_0_bits_respErr,
  input [2:0] io_in_0_bits_resp,
  input [2:0] io_in_0_bits_fwdState,
  input [2:0] io_in_0_bits_cBusy,
  input [11:0] io_in_0_bits_dbID,
  input [3:0] io_in_0_bits_pCrdType,
  input [1:0] io_in_0_bits_tagOp,
  input io_in_0_bits_traceTag,
  output io_in_1_ready,
  input io_in_1_valid,
  input [3:0] io_in_1_bits_qos,
  input [10:0] io_in_1_bits_tgtID,
  input [11:0] io_in_1_bits_txnID,
  input [4:0] io_in_1_bits_opcode,
  input [1:0] io_in_1_bits_respErr,
  input [2:0] io_in_1_bits_resp,
  input [2:0] io_in_1_bits_fwdState,
  input [2:0] io_in_1_bits_cBusy,
  input [11:0] io_in_1_bits_dbID,
  input [3:0] io_in_1_bits_pCrdType,
  input [1:0] io_in_1_bits_tagOp,
  input io_in_1_bits_traceTag,
  output io_in_2_ready,
  input io_in_2_valid,
  input [3:0] io_in_2_bits_qos,
  input [10:0] io_in_2_bits_tgtID,
  input [11:0] io_in_2_bits_txnID,
  input [4:0] io_in_2_bits_opcode,
  input [1:0] io_in_2_bits_respErr,
  input [2:0] io_in_2_bits_resp,
  input [2:0] io_in_2_bits_fwdState,
  input [2:0] io_in_2_bits_cBusy,
  input [11:0] io_in_2_bits_dbID,
  input [3:0] io_in_2_bits_pCrdType,
  input [1:0] io_in_2_bits_tagOp,
  input io_in_2_bits_traceTag,
  output io_in_3_ready,
  input io_in_3_valid,
  input [3:0] io_in_3_bits_qos,
  input [10:0] io_in_3_bits_tgtID,
  input [11:0] io_in_3_bits_txnID,
  input [4:0] io_in_3_bits_opcode,
  input [1:0] io_in_3_bits_respErr,
  input [2:0] io_in_3_bits_resp,
  input [2:0] io_in_3_bits_fwdState,
  input [2:0] io_in_3_bits_cBusy,
  input [11:0] io_in_3_bits_dbID,
  input [3:0] io_in_3_bits_pCrdType,
  input [1:0] io_in_3_bits_tagOp,
  input io_in_3_bits_traceTag,
  input io_out_ready,
  output io_out_valid,
  output [3:0] io_out_bits_qos,
  output [10:0] io_out_bits_tgtID,
  output [11:0] io_out_bits_txnID,
  output [4:0] io_out_bits_opcode,
  output [1:0] io_out_bits_respErr,
  output [2:0] io_out_bits_resp,
  output [2:0] io_out_bits_fwdState,
  output [2:0] io_out_bits_cBusy,
  output [11:0] io_out_bits_dbID,
  output [3:0] io_out_bits_pCrdType,
  output [1:0] io_out_bits_tagOp,
  output io_out_bits_traceTag,
  output [1:0] io_chosen
);
  xs_FastArbiter_27_core u_core (
    .clock(clock),
    .reset(reset),
    .io_in_0_ready(io_in_0_ready),
    .io_in_0_valid(io_in_0_valid),
    .io_in_0_bits_qos(io_in_0_bits_qos),
    .io_in_0_bits_tgtID(io_in_0_bits_tgtID),
    .io_in_0_bits_txnID(io_in_0_bits_txnID),
    .io_in_0_bits_opcode(io_in_0_bits_opcode),
    .io_in_0_bits_respErr(io_in_0_bits_respErr),
    .io_in_0_bits_resp(io_in_0_bits_resp),
    .io_in_0_bits_fwdState(io_in_0_bits_fwdState),
    .io_in_0_bits_cBusy(io_in_0_bits_cBusy),
    .io_in_0_bits_dbID(io_in_0_bits_dbID),
    .io_in_0_bits_pCrdType(io_in_0_bits_pCrdType),
    .io_in_0_bits_tagOp(io_in_0_bits_tagOp),
    .io_in_0_bits_traceTag(io_in_0_bits_traceTag),
    .io_in_1_ready(io_in_1_ready),
    .io_in_1_valid(io_in_1_valid),
    .io_in_1_bits_qos(io_in_1_bits_qos),
    .io_in_1_bits_tgtID(io_in_1_bits_tgtID),
    .io_in_1_bits_txnID(io_in_1_bits_txnID),
    .io_in_1_bits_opcode(io_in_1_bits_opcode),
    .io_in_1_bits_respErr(io_in_1_bits_respErr),
    .io_in_1_bits_resp(io_in_1_bits_resp),
    .io_in_1_bits_fwdState(io_in_1_bits_fwdState),
    .io_in_1_bits_cBusy(io_in_1_bits_cBusy),
    .io_in_1_bits_dbID(io_in_1_bits_dbID),
    .io_in_1_bits_pCrdType(io_in_1_bits_pCrdType),
    .io_in_1_bits_tagOp(io_in_1_bits_tagOp),
    .io_in_1_bits_traceTag(io_in_1_bits_traceTag),
    .io_in_2_ready(io_in_2_ready),
    .io_in_2_valid(io_in_2_valid),
    .io_in_2_bits_qos(io_in_2_bits_qos),
    .io_in_2_bits_tgtID(io_in_2_bits_tgtID),
    .io_in_2_bits_txnID(io_in_2_bits_txnID),
    .io_in_2_bits_opcode(io_in_2_bits_opcode),
    .io_in_2_bits_respErr(io_in_2_bits_respErr),
    .io_in_2_bits_resp(io_in_2_bits_resp),
    .io_in_2_bits_fwdState(io_in_2_bits_fwdState),
    .io_in_2_bits_cBusy(io_in_2_bits_cBusy),
    .io_in_2_bits_dbID(io_in_2_bits_dbID),
    .io_in_2_bits_pCrdType(io_in_2_bits_pCrdType),
    .io_in_2_bits_tagOp(io_in_2_bits_tagOp),
    .io_in_2_bits_traceTag(io_in_2_bits_traceTag),
    .io_in_3_ready(io_in_3_ready),
    .io_in_3_valid(io_in_3_valid),
    .io_in_3_bits_qos(io_in_3_bits_qos),
    .io_in_3_bits_tgtID(io_in_3_bits_tgtID),
    .io_in_3_bits_txnID(io_in_3_bits_txnID),
    .io_in_3_bits_opcode(io_in_3_bits_opcode),
    .io_in_3_bits_respErr(io_in_3_bits_respErr),
    .io_in_3_bits_resp(io_in_3_bits_resp),
    .io_in_3_bits_fwdState(io_in_3_bits_fwdState),
    .io_in_3_bits_cBusy(io_in_3_bits_cBusy),
    .io_in_3_bits_dbID(io_in_3_bits_dbID),
    .io_in_3_bits_pCrdType(io_in_3_bits_pCrdType),
    .io_in_3_bits_tagOp(io_in_3_bits_tagOp),
    .io_in_3_bits_traceTag(io_in_3_bits_traceTag),
    .io_out_ready(io_out_ready),
    .io_out_valid(io_out_valid),
    .io_out_bits_qos(io_out_bits_qos),
    .io_out_bits_tgtID(io_out_bits_tgtID),
    .io_out_bits_txnID(io_out_bits_txnID),
    .io_out_bits_opcode(io_out_bits_opcode),
    .io_out_bits_respErr(io_out_bits_respErr),
    .io_out_bits_resp(io_out_bits_resp),
    .io_out_bits_fwdState(io_out_bits_fwdState),
    .io_out_bits_cBusy(io_out_bits_cBusy),
    .io_out_bits_dbID(io_out_bits_dbID),
    .io_out_bits_pCrdType(io_out_bits_pCrdType),
    .io_out_bits_tagOp(io_out_bits_tagOp),
    .io_out_bits_traceTag(io_out_bits_traceTag),
    .io_chosen(io_chosen)
  );
endmodule
