// 自动生成 scripts/gen_chi_channel.py —— 勿手改
module TXREQ_4_xs(
  input io_req_ready,
  output io_req_valid,
  output [10:0] io_req_bits_tgtID,
  output [10:0] io_req_bits_srcID,
  output [11:0] io_req_bits_txnID,
  output [6:0] io_req_bits_opcode,
  output [2:0] io_req_bits_size,
  output [47:0] io_req_bits_addr,
  output io_req_bits_allowRetry,
  output [1:0] io_req_bits_order,
  output [3:0] io_req_bits_pCrdType,
  output io_req_bits_memAttr_allocate,
  output io_req_bits_memAttr_cacheable,
  output io_req_bits_memAttr_device,
  output io_req_bits_memAttr_ewa,
  output io_req_bits_snpAttr,
  output io_req_bits_expCompAck,
  output io_task_ready,
  input io_task_valid,
  input [11:0] io_task_bits_set,
  input [1:0] io_task_bits_bank,
  input [27:0] io_task_bits_tag,
  input [2:0] io_task_bits_size,
  input [10:0] io_task_bits_tgtID,
  input [10:0] io_task_bits_srcID,
  input [11:0] io_task_bits_txnID,
  input [6:0] io_task_bits_chiOpcode,
  input [3:0] io_task_bits_pCrdType,
  input io_task_bits_expCompAck,
  input io_task_bits_allowRetry,
  input [1:0] io_task_bits_order,
  input io_task_bits_memAttr_allocate,
  input io_task_bits_memAttr_cacheable,
  input io_task_bits_memAttr_device,
  input io_task_bits_memAttr_ewa,
  input io_task_bits_snpAttr
);
  xs_TXREQ_4_core u_core (
    .io_req_ready(io_req_ready),
    .io_req_valid(io_req_valid),
    .io_req_bits_tgtID(io_req_bits_tgtID),
    .io_req_bits_srcID(io_req_bits_srcID),
    .io_req_bits_txnID(io_req_bits_txnID),
    .io_req_bits_opcode(io_req_bits_opcode),
    .io_req_bits_size(io_req_bits_size),
    .io_req_bits_addr(io_req_bits_addr),
    .io_req_bits_allowRetry(io_req_bits_allowRetry),
    .io_req_bits_order(io_req_bits_order),
    .io_req_bits_pCrdType(io_req_bits_pCrdType),
    .io_req_bits_memAttr_allocate(io_req_bits_memAttr_allocate),
    .io_req_bits_memAttr_cacheable(io_req_bits_memAttr_cacheable),
    .io_req_bits_memAttr_device(io_req_bits_memAttr_device),
    .io_req_bits_memAttr_ewa(io_req_bits_memAttr_ewa),
    .io_req_bits_snpAttr(io_req_bits_snpAttr),
    .io_req_bits_expCompAck(io_req_bits_expCompAck),
    .io_task_ready(io_task_ready),
    .io_task_valid(io_task_valid),
    .io_task_bits_set(io_task_bits_set),
    .io_task_bits_bank(io_task_bits_bank),
    .io_task_bits_tag(io_task_bits_tag),
    .io_task_bits_size(io_task_bits_size),
    .io_task_bits_tgtID(io_task_bits_tgtID),
    .io_task_bits_srcID(io_task_bits_srcID),
    .io_task_bits_txnID(io_task_bits_txnID),
    .io_task_bits_chiOpcode(io_task_bits_chiOpcode),
    .io_task_bits_pCrdType(io_task_bits_pCrdType),
    .io_task_bits_expCompAck(io_task_bits_expCompAck),
    .io_task_bits_allowRetry(io_task_bits_allowRetry),
    .io_task_bits_order(io_task_bits_order),
    .io_task_bits_memAttr_allocate(io_task_bits_memAttr_allocate),
    .io_task_bits_memAttr_cacheable(io_task_bits_memAttr_cacheable),
    .io_task_bits_memAttr_device(io_task_bits_memAttr_device),
    .io_task_bits_memAttr_ewa(io_task_bits_memAttr_ewa),
    .io_task_bits_snpAttr(io_task_bits_snpAttr)
  );
endmodule
