// 自动生成 scripts/gen_chi_channel.py —— 勿手改
module LCredit2Decoupled_1_xs(
  input clock,
  input reset,
  input io_in_flitv,
  input [72:0] io_in_flit,
  output io_in_lcrdv,
  input io_out_ready,
  output io_out_valid,
  output [3:0] io_out_bits_qos,
  output [10:0] io_out_bits_tgtID,
  output [10:0] io_out_bits_srcID,
  output [11:0] io_out_bits_txnID,
  output [4:0] io_out_bits_opcode,
  output [1:0] io_out_bits_respErr,
  output [2:0] io_out_bits_resp,
  output [2:0] io_out_bits_fwdState,
  output [2:0] io_out_bits_cBusy,
  output [11:0] io_out_bits_dbID,
  output [3:0] io_out_bits_pCrdType,
  output [1:0] io_out_bits_tagOp,
  output io_out_bits_traceTag,
  input [1:0] io_state_state,
  output io_reclaimLCredit
);
  xs_LCredit2Decoupled_1_core u_core (
    .clock(clock),
    .reset(reset),
    .io_in_flitv(io_in_flitv),
    .io_in_flit(io_in_flit),
    .io_in_lcrdv(io_in_lcrdv),
    .io_out_ready(io_out_ready),
    .io_out_valid(io_out_valid),
    .io_out_bits_qos(io_out_bits_qos),
    .io_out_bits_tgtID(io_out_bits_tgtID),
    .io_out_bits_srcID(io_out_bits_srcID),
    .io_out_bits_txnID(io_out_bits_txnID),
    .io_out_bits_opcode(io_out_bits_opcode),
    .io_out_bits_respErr(io_out_bits_respErr),
    .io_out_bits_resp(io_out_bits_resp),
    .io_out_bits_fwdState(io_out_bits_fwdState),
    .io_out_bits_cBusy(io_out_bits_cBusy),
    .io_out_bits_dbID(io_out_bits_dbID),
    .io_out_bits_pCrdType(io_out_bits_pCrdType),
    .io_out_bits_tagOp(io_out_bits_tagOp),
    .io_out_bits_traceTag(io_out_bits_traceTag),
    .io_state_state(io_state_state),
    .io_reclaimLCredit(io_reclaimLCredit)
  );
endmodule
