// 自动生成：scripts/gen_ptwnewfilter.py —— 勿手改
module PTWNewFilter_xs (
  input  clock,
  input  reset,
  input  io_sfence_valid,
  input  [15:0] io_csr_satp_asid,
  input  io_csr_satp_changed,
  input  [15:0] io_csr_vsatp_asid,
  input  io_csr_vsatp_changed,
  input  [15:0] io_csr_hgatp_vmid,
  input  io_csr_priv_virt,
  input  io_tlb_req_0_valid,
  input  [37:0] io_tlb_req_0_bits_vpn,
  input  [1:0] io_tlb_req_0_bits_s2xlate,
  input  io_tlb_req_0_bits_getGpa,
  input  io_tlb_req_1_valid,
  input  [37:0] io_tlb_req_1_bits_vpn,
  input  [1:0] io_tlb_req_1_bits_s2xlate,
  input  io_tlb_req_1_bits_getGpa,
  input  io_tlb_req_2_valid,
  input  [37:0] io_tlb_req_2_bits_vpn,
  input  [1:0] io_tlb_req_2_bits_s2xlate,
  input  io_tlb_req_2_bits_getGpa,
  input  io_tlb_req_3_valid,
  input  [37:0] io_tlb_req_3_bits_vpn,
  input  [1:0] io_tlb_req_3_bits_s2xlate,
  input  io_tlb_req_3_bits_getGpa,
  input  io_tlb_req_4_valid,
  input  [37:0] io_tlb_req_4_bits_vpn,
  input  [1:0] io_tlb_req_4_bits_s2xlate,
  input  io_tlb_req_4_bits_getGpa,
  input  io_tlb_req_5_valid,
  input  [37:0] io_tlb_req_5_bits_vpn,
  input  [1:0] io_tlb_req_5_bits_s2xlate,
  input  io_tlb_req_5_bits_getGpa,
  input  io_tlb_req_6_valid,
  input  [37:0] io_tlb_req_6_bits_vpn,
  input  [1:0] io_tlb_req_6_bits_s2xlate,
  input  io_tlb_req_6_bits_getGpa,
  input  io_tlb_req_7_valid,
  input  [37:0] io_tlb_req_7_bits_vpn,
  input  [1:0] io_tlb_req_7_bits_s2xlate,
  input  io_tlb_req_7_bits_getGpa,
  output io_tlb_resp_valid,
  output [1:0] io_tlb_resp_bits_data_s2xlate,
  output [34:0] io_tlb_resp_bits_data_s1_entry_tag,
  output [15:0] io_tlb_resp_bits_data_s1_entry_asid,
  output [13:0] io_tlb_resp_bits_data_s1_entry_vmid,
  output io_tlb_resp_bits_data_s1_entry_n,
  output [1:0] io_tlb_resp_bits_data_s1_entry_pbmt,
  output io_tlb_resp_bits_data_s1_entry_perm_d,
  output io_tlb_resp_bits_data_s1_entry_perm_a,
  output io_tlb_resp_bits_data_s1_entry_perm_g,
  output io_tlb_resp_bits_data_s1_entry_perm_u,
  output io_tlb_resp_bits_data_s1_entry_perm_x,
  output io_tlb_resp_bits_data_s1_entry_perm_w,
  output io_tlb_resp_bits_data_s1_entry_perm_r,
  output [1:0] io_tlb_resp_bits_data_s1_entry_level,
  output io_tlb_resp_bits_data_s1_entry_v,
  output [40:0] io_tlb_resp_bits_data_s1_entry_ppn,
  output [2:0] io_tlb_resp_bits_data_s1_addr_low,
  output [2:0] io_tlb_resp_bits_data_s1_ppn_low_0,
  output [2:0] io_tlb_resp_bits_data_s1_ppn_low_1,
  output [2:0] io_tlb_resp_bits_data_s1_ppn_low_2,
  output [2:0] io_tlb_resp_bits_data_s1_ppn_low_3,
  output [2:0] io_tlb_resp_bits_data_s1_ppn_low_4,
  output [2:0] io_tlb_resp_bits_data_s1_ppn_low_5,
  output [2:0] io_tlb_resp_bits_data_s1_ppn_low_6,
  output [2:0] io_tlb_resp_bits_data_s1_ppn_low_7,
  output io_tlb_resp_bits_data_s1_valididx_0,
  output io_tlb_resp_bits_data_s1_valididx_1,
  output io_tlb_resp_bits_data_s1_valididx_2,
  output io_tlb_resp_bits_data_s1_valididx_3,
  output io_tlb_resp_bits_data_s1_valididx_4,
  output io_tlb_resp_bits_data_s1_valididx_5,
  output io_tlb_resp_bits_data_s1_valididx_6,
  output io_tlb_resp_bits_data_s1_valididx_7,
  output io_tlb_resp_bits_data_s1_pteidx_0,
  output io_tlb_resp_bits_data_s1_pteidx_1,
  output io_tlb_resp_bits_data_s1_pteidx_2,
  output io_tlb_resp_bits_data_s1_pteidx_3,
  output io_tlb_resp_bits_data_s1_pteidx_4,
  output io_tlb_resp_bits_data_s1_pteidx_5,
  output io_tlb_resp_bits_data_s1_pteidx_6,
  output io_tlb_resp_bits_data_s1_pteidx_7,
  output io_tlb_resp_bits_data_s1_pf,
  output io_tlb_resp_bits_data_s1_af,
  output [37:0] io_tlb_resp_bits_data_s2_entry_tag,
  output [13:0] io_tlb_resp_bits_data_s2_entry_vmid,
  output io_tlb_resp_bits_data_s2_entry_n,
  output [1:0] io_tlb_resp_bits_data_s2_entry_pbmt,
  output [37:0] io_tlb_resp_bits_data_s2_entry_ppn,
  output io_tlb_resp_bits_data_s2_entry_perm_d,
  output io_tlb_resp_bits_data_s2_entry_perm_a,
  output io_tlb_resp_bits_data_s2_entry_perm_g,
  output io_tlb_resp_bits_data_s2_entry_perm_u,
  output io_tlb_resp_bits_data_s2_entry_perm_x,
  output io_tlb_resp_bits_data_s2_entry_perm_w,
  output io_tlb_resp_bits_data_s2_entry_perm_r,
  output [1:0] io_tlb_resp_bits_data_s2_entry_level,
  output io_tlb_resp_bits_data_s2_gpf,
  output io_tlb_resp_bits_data_s2_gaf,
  output io_tlb_resp_bits_vector_0,
  output io_tlb_resp_bits_vector_4,
  output io_tlb_resp_bits_vector_6,
  output io_tlb_resp_bits_getGpa_0,
  output io_tlb_resp_bits_getGpa_4,
  output io_tlb_resp_bits_getGpa_6,
  input  io_ptw_req_0_ready,
  output io_ptw_req_0_valid,
  output [37:0] io_ptw_req_0_bits_vpn,
  output [1:0] io_ptw_req_0_bits_s2xlate,
  input  io_ptw_resp_valid,
  input  [1:0] io_ptw_resp_bits_s2xlate,
  input  [34:0] io_ptw_resp_bits_s1_entry_tag,
  input  [15:0] io_ptw_resp_bits_s1_entry_asid,
  input  [13:0] io_ptw_resp_bits_s1_entry_vmid,
  input  io_ptw_resp_bits_s1_entry_n,
  input  [1:0] io_ptw_resp_bits_s1_entry_pbmt,
  input  io_ptw_resp_bits_s1_entry_perm_d,
  input  io_ptw_resp_bits_s1_entry_perm_a,
  input  io_ptw_resp_bits_s1_entry_perm_g,
  input  io_ptw_resp_bits_s1_entry_perm_u,
  input  io_ptw_resp_bits_s1_entry_perm_x,
  input  io_ptw_resp_bits_s1_entry_perm_w,
  input  io_ptw_resp_bits_s1_entry_perm_r,
  input  [1:0] io_ptw_resp_bits_s1_entry_level,
  input  io_ptw_resp_bits_s1_entry_v,
  input  [40:0] io_ptw_resp_bits_s1_entry_ppn,
  input  [2:0] io_ptw_resp_bits_s1_addr_low,
  input  [2:0] io_ptw_resp_bits_s1_ppn_low_0,
  input  [2:0] io_ptw_resp_bits_s1_ppn_low_1,
  input  [2:0] io_ptw_resp_bits_s1_ppn_low_2,
  input  [2:0] io_ptw_resp_bits_s1_ppn_low_3,
  input  [2:0] io_ptw_resp_bits_s1_ppn_low_4,
  input  [2:0] io_ptw_resp_bits_s1_ppn_low_5,
  input  [2:0] io_ptw_resp_bits_s1_ppn_low_6,
  input  [2:0] io_ptw_resp_bits_s1_ppn_low_7,
  input  io_ptw_resp_bits_s1_valididx_0,
  input  io_ptw_resp_bits_s1_valididx_1,
  input  io_ptw_resp_bits_s1_valididx_2,
  input  io_ptw_resp_bits_s1_valididx_3,
  input  io_ptw_resp_bits_s1_valididx_4,
  input  io_ptw_resp_bits_s1_valididx_5,
  input  io_ptw_resp_bits_s1_valididx_6,
  input  io_ptw_resp_bits_s1_valididx_7,
  input  io_ptw_resp_bits_s1_pteidx_0,
  input  io_ptw_resp_bits_s1_pteidx_1,
  input  io_ptw_resp_bits_s1_pteidx_2,
  input  io_ptw_resp_bits_s1_pteidx_3,
  input  io_ptw_resp_bits_s1_pteidx_4,
  input  io_ptw_resp_bits_s1_pteidx_5,
  input  io_ptw_resp_bits_s1_pteidx_6,
  input  io_ptw_resp_bits_s1_pteidx_7,
  input  io_ptw_resp_bits_s1_pf,
  input  io_ptw_resp_bits_s1_af,
  input  [37:0] io_ptw_resp_bits_s2_entry_tag,
  input  [13:0] io_ptw_resp_bits_s2_entry_vmid,
  input  io_ptw_resp_bits_s2_entry_n,
  input  [1:0] io_ptw_resp_bits_s2_entry_pbmt,
  input  [37:0] io_ptw_resp_bits_s2_entry_ppn,
  input  io_ptw_resp_bits_s2_entry_perm_d,
  input  io_ptw_resp_bits_s2_entry_perm_a,
  input  io_ptw_resp_bits_s2_entry_perm_g,
  input  io_ptw_resp_bits_s2_entry_perm_u,
  input  io_ptw_resp_bits_s2_entry_perm_x,
  input  io_ptw_resp_bits_s2_entry_perm_w,
  input  io_ptw_resp_bits_s2_entry_perm_r,
  input  [1:0] io_ptw_resp_bits_s2_entry_level,
  input  io_ptw_resp_bits_s2_gpf,
  input  io_ptw_resp_bits_s2_gaf,
  output [3:0] io_hint_req_0_id,
  output io_hint_req_0_full,
  output [3:0] io_hint_req_1_id,
  output io_hint_req_1_full,
  output [3:0] io_hint_req_2_id,
  output io_hint_req_2_full,
  output io_hint_resp_valid,
  output [3:0] io_hint_resp_bits_id,
  output io_hint_resp_bits_replay_all,
  output io_rob_head_miss_in_tlb,
  input  io_debugTopDown_robHeadVaddr_valid,
  input  [49:0] io_debugTopDown_robHeadVaddr_bits
);

  // ---- flush（DelayN_1）----
  wire flush;
  DelayN_1 flush_delay (.clock(clock),
    .io_in(io_sfence_valid | io_csr_satp_changed | io_csr_priv_virt & io_csr_vsatp_changed),
    .io_out(flush));

  // ---- 核 ↔ filter 共用的锁存 ptwResp（核输出）----
  wire [1:0]  cr_s2xlate; wire [34:0] cr_s1_entry_tag; wire [15:0] cr_s1_entry_asid;
  wire [13:0] cr_s1_entry_vmid; wire cr_s1_entry_n, cr_s1_entry_perm_g;
  wire [1:0]  cr_s1_entry_level; wire [2:0] cr_s1_addr_low;
  wire cr_s1_valididx_0, cr_s1_valididx_1, cr_s1_valididx_2, cr_s1_valididx_3;
  wire cr_s1_valididx_4, cr_s1_valididx_5, cr_s1_valididx_6, cr_s1_valididx_7;
  wire [37:0] cr_s2_entry_tag; wire [13:0] cr_s2_entry_vmid; wire cr_s2_entry_n;
  wire [1:0]  cr_s2_entry_level;

  // 三组 ptw_resp_valid（延迟版, 核产生）
  wire lf_resp_last, sf_resp_last, pf_resp_last;

  // 三组 filter → arbiter 的 ptw req
  wire lf_ptw_valid; wire [37:0] lf_ptw_vpn; wire [1:0] lf_ptw_s2x;
  wire sf_ptw_valid; wire [37:0] sf_ptw_vpn; wire [1:0] sf_ptw_s2x;
  wire pf_ptw_valid; wire [37:0] pf_ptw_vpn; wire [1:0] pf_ptw_s2x;
  wire arb_in_0_ready, arb_in_1_ready, arb_in_2_ready;

  // 三组 refill / rob_head_miss
  wire lf_refill, sf_refill, pf_refill;
  wire lf_rob, sf_rob, pf_rob;

  // load 组 hint
  wire [3:0] lf_hint_req_0_id; wire lf_hint_req_0_full;
  wire [3:0] lf_hint_req_1_id; wire lf_hint_req_1_full;
  wire [3:0] lf_hint_req_2_id; wire lf_hint_req_2_full;
  wire lf_hint_resp_valid; wire [3:0] lf_hint_resp_bits_id; wire lf_hint_resp_bits_replay_all;

  PTWFilterEntry load_filter_load_entry (
    .clock(clock), .reset(reset),
    .io_csr_satp_asid(io_csr_satp_asid), .io_csr_vsatp_asid(io_csr_vsatp_asid),
    .io_csr_hgatp_vmid(io_csr_hgatp_vmid),
    .io_tlb_req_0_valid(io_tlb_req_0_valid),
    .io_tlb_req_0_bits_vpn(io_tlb_req_0_bits_vpn),
    .io_tlb_req_0_bits_s2xlate(io_tlb_req_0_bits_s2xlate),
    .io_tlb_req_0_bits_getGpa(io_tlb_req_0_bits_getGpa),
    .io_tlb_req_1_valid(io_tlb_req_1_valid),
    .io_tlb_req_1_bits_vpn(io_tlb_req_1_bits_vpn),
    .io_tlb_req_1_bits_s2xlate(io_tlb_req_1_bits_s2xlate),
    .io_tlb_req_1_bits_getGpa(io_tlb_req_1_bits_getGpa),
    .io_tlb_req_2_valid(io_tlb_req_2_valid),
    .io_tlb_req_2_bits_vpn(io_tlb_req_2_bits_vpn),
    .io_tlb_req_2_bits_s2xlate(io_tlb_req_2_bits_s2xlate),
    .io_tlb_req_2_bits_getGpa(io_tlb_req_2_bits_getGpa),
    .io_tlb_req_3_valid(io_tlb_req_3_valid),
    .io_tlb_req_3_bits_vpn(io_tlb_req_3_bits_vpn),
    .io_tlb_req_3_bits_s2xlate(io_tlb_req_3_bits_s2xlate),
    .io_tlb_req_3_bits_getGpa(io_tlb_req_3_bits_getGpa),
    .io_ptw_req_0_ready(arb_in_0_ready),
    .io_ptw_req_0_valid(lf_ptw_valid),
    .io_ptw_req_0_bits_vpn(lf_ptw_vpn),
    .io_ptw_req_0_bits_s2xlate(lf_ptw_s2x),
    .io_ptw_resp_valid(lf_resp_last),
    .io_ptw_resp_bits_s2xlate(cr_s2xlate),
    .io_ptw_resp_bits_s1_entry_tag(cr_s1_entry_tag),
    .io_ptw_resp_bits_s1_entry_asid(cr_s1_entry_asid),
    .io_ptw_resp_bits_s1_entry_vmid(cr_s1_entry_vmid),
    .io_ptw_resp_bits_s1_entry_n(cr_s1_entry_n),
    .io_ptw_resp_bits_s1_entry_perm_g(cr_s1_entry_perm_g),
    .io_ptw_resp_bits_s1_entry_level(cr_s1_entry_level),
    .io_ptw_resp_bits_s1_addr_low(cr_s1_addr_low),
    .io_ptw_resp_bits_s1_valididx_0(cr_s1_valididx_0),
    .io_ptw_resp_bits_s1_valididx_1(cr_s1_valididx_1),
    .io_ptw_resp_bits_s1_valididx_2(cr_s1_valididx_2),
    .io_ptw_resp_bits_s1_valididx_3(cr_s1_valididx_3),
    .io_ptw_resp_bits_s1_valididx_4(cr_s1_valididx_4),
    .io_ptw_resp_bits_s1_valididx_5(cr_s1_valididx_5),
    .io_ptw_resp_bits_s1_valididx_6(cr_s1_valididx_6),
    .io_ptw_resp_bits_s1_valididx_7(cr_s1_valididx_7),
    .io_ptw_resp_bits_s2_entry_tag(cr_s2_entry_tag),
    .io_ptw_resp_bits_s2_entry_vmid(cr_s2_entry_vmid),
    .io_ptw_resp_bits_s2_entry_n(cr_s2_entry_n),
    .io_ptw_resp_bits_s2_entry_level(cr_s2_entry_level),
    .io_hint_req_0_id(lf_hint_req_0_id), .io_hint_req_0_full(lf_hint_req_0_full),
    .io_hint_req_1_id(lf_hint_req_1_id), .io_hint_req_1_full(lf_hint_req_1_full),
    .io_hint_req_2_id(lf_hint_req_2_id), .io_hint_req_2_full(lf_hint_req_2_full),
    .io_hint_resp_valid(lf_hint_resp_valid), .io_hint_resp_bits_id(lf_hint_resp_bits_id),
    .io_hint_resp_bits_replay_all(lf_hint_resp_bits_replay_all),
    .io_rob_head_miss_in_tlb(lf_rob),
    .io_debugTopDown_robHeadVaddr_valid(io_debugTopDown_robHeadVaddr_valid),
    .io_debugTopDown_robHeadVaddr_bits(io_debugTopDown_robHeadVaddr_bits),
    .io_flush(flush),
    .io_refill(lf_refill),
    .io_getGpa(io_tlb_resp_bits_getGpa_0)
  );
  PTWFilterEntry_1 store_filter_store_entry (
    .clock(clock), .reset(reset),
    .io_csr_satp_asid(io_csr_satp_asid), .io_csr_vsatp_asid(io_csr_vsatp_asid),
    .io_csr_hgatp_vmid(io_csr_hgatp_vmid),
    .io_tlb_req_0_valid(io_tlb_req_4_valid),
    .io_tlb_req_0_bits_vpn(io_tlb_req_4_bits_vpn),
    .io_tlb_req_0_bits_s2xlate(io_tlb_req_4_bits_s2xlate),
    .io_tlb_req_0_bits_getGpa(io_tlb_req_4_bits_getGpa),
    .io_tlb_req_1_valid(io_tlb_req_5_valid),
    .io_tlb_req_1_bits_vpn(io_tlb_req_5_bits_vpn),
    .io_tlb_req_1_bits_s2xlate(io_tlb_req_5_bits_s2xlate),
    .io_tlb_req_1_bits_getGpa(io_tlb_req_5_bits_getGpa),
    .io_ptw_req_0_ready(arb_in_1_ready),
    .io_ptw_req_0_valid(sf_ptw_valid),
    .io_ptw_req_0_bits_vpn(sf_ptw_vpn),
    .io_ptw_req_0_bits_s2xlate(sf_ptw_s2x),
    .io_ptw_resp_valid(sf_resp_last),
    .io_ptw_resp_bits_s2xlate(cr_s2xlate),
    .io_ptw_resp_bits_s1_entry_tag(cr_s1_entry_tag),
    .io_ptw_resp_bits_s1_entry_asid(cr_s1_entry_asid),
    .io_ptw_resp_bits_s1_entry_vmid(cr_s1_entry_vmid),
    .io_ptw_resp_bits_s1_entry_n(cr_s1_entry_n),
    .io_ptw_resp_bits_s1_entry_perm_g(cr_s1_entry_perm_g),
    .io_ptw_resp_bits_s1_entry_level(cr_s1_entry_level),
    .io_ptw_resp_bits_s1_addr_low(cr_s1_addr_low),
    .io_ptw_resp_bits_s1_valididx_0(cr_s1_valididx_0),
    .io_ptw_resp_bits_s1_valididx_1(cr_s1_valididx_1),
    .io_ptw_resp_bits_s1_valididx_2(cr_s1_valididx_2),
    .io_ptw_resp_bits_s1_valididx_3(cr_s1_valididx_3),
    .io_ptw_resp_bits_s1_valididx_4(cr_s1_valididx_4),
    .io_ptw_resp_bits_s1_valididx_5(cr_s1_valididx_5),
    .io_ptw_resp_bits_s1_valididx_6(cr_s1_valididx_6),
    .io_ptw_resp_bits_s1_valididx_7(cr_s1_valididx_7),
    .io_ptw_resp_bits_s2_entry_tag(cr_s2_entry_tag),
    .io_ptw_resp_bits_s2_entry_vmid(cr_s2_entry_vmid),
    .io_ptw_resp_bits_s2_entry_n(cr_s2_entry_n),
    .io_ptw_resp_bits_s2_entry_level(cr_s2_entry_level),
    .io_rob_head_miss_in_tlb(sf_rob),
    .io_debugTopDown_robHeadVaddr_valid(io_debugTopDown_robHeadVaddr_valid),
    .io_debugTopDown_robHeadVaddr_bits(io_debugTopDown_robHeadVaddr_bits),
    .io_flush(flush),
    .io_refill(sf_refill),
    .io_getGpa(io_tlb_resp_bits_getGpa_4)
  );
  PTWFilterEntry_1 prefetch_filter_prefetch_entry (
    .clock(clock), .reset(reset),
    .io_csr_satp_asid(io_csr_satp_asid), .io_csr_vsatp_asid(io_csr_vsatp_asid),
    .io_csr_hgatp_vmid(io_csr_hgatp_vmid),
    .io_tlb_req_0_valid(io_tlb_req_6_valid),
    .io_tlb_req_0_bits_vpn(io_tlb_req_6_bits_vpn),
    .io_tlb_req_0_bits_s2xlate(io_tlb_req_6_bits_s2xlate),
    .io_tlb_req_0_bits_getGpa(io_tlb_req_6_bits_getGpa),
    .io_tlb_req_1_valid(io_tlb_req_7_valid),
    .io_tlb_req_1_bits_vpn(io_tlb_req_7_bits_vpn),
    .io_tlb_req_1_bits_s2xlate(io_tlb_req_7_bits_s2xlate),
    .io_tlb_req_1_bits_getGpa(io_tlb_req_7_bits_getGpa),
    .io_ptw_req_0_ready(arb_in_2_ready),
    .io_ptw_req_0_valid(pf_ptw_valid),
    .io_ptw_req_0_bits_vpn(pf_ptw_vpn),
    .io_ptw_req_0_bits_s2xlate(pf_ptw_s2x),
    .io_ptw_resp_valid(pf_resp_last),
    .io_ptw_resp_bits_s2xlate(cr_s2xlate),
    .io_ptw_resp_bits_s1_entry_tag(cr_s1_entry_tag),
    .io_ptw_resp_bits_s1_entry_asid(cr_s1_entry_asid),
    .io_ptw_resp_bits_s1_entry_vmid(cr_s1_entry_vmid),
    .io_ptw_resp_bits_s1_entry_n(cr_s1_entry_n),
    .io_ptw_resp_bits_s1_entry_perm_g(cr_s1_entry_perm_g),
    .io_ptw_resp_bits_s1_entry_level(cr_s1_entry_level),
    .io_ptw_resp_bits_s1_addr_low(cr_s1_addr_low),
    .io_ptw_resp_bits_s1_valididx_0(cr_s1_valididx_0),
    .io_ptw_resp_bits_s1_valididx_1(cr_s1_valididx_1),
    .io_ptw_resp_bits_s1_valididx_2(cr_s1_valididx_2),
    .io_ptw_resp_bits_s1_valididx_3(cr_s1_valididx_3),
    .io_ptw_resp_bits_s1_valididx_4(cr_s1_valididx_4),
    .io_ptw_resp_bits_s1_valididx_5(cr_s1_valididx_5),
    .io_ptw_resp_bits_s1_valididx_6(cr_s1_valididx_6),
    .io_ptw_resp_bits_s1_valididx_7(cr_s1_valididx_7),
    .io_ptw_resp_bits_s2_entry_tag(cr_s2_entry_tag),
    .io_ptw_resp_bits_s2_entry_vmid(cr_s2_entry_vmid),
    .io_ptw_resp_bits_s2_entry_n(cr_s2_entry_n),
    .io_ptw_resp_bits_s2_entry_level(cr_s2_entry_level),
    .io_rob_head_miss_in_tlb(pf_rob),
    .io_debugTopDown_robHeadVaddr_valid(io_debugTopDown_robHeadVaddr_valid),
    .io_debugTopDown_robHeadVaddr_bits(io_debugTopDown_robHeadVaddr_bits),
    .io_flush(flush),
    .io_refill(pf_refill),
    .io_getGpa(io_tlb_resp_bits_getGpa_6)
  );

  RRArbiterInit_10 ptw_arb (
    .clock(clock), .reset(reset),
    .io_in_0_ready(arb_in_0_ready), .io_in_0_valid(lf_ptw_valid),
    .io_in_0_bits_vpn(lf_ptw_vpn), .io_in_0_bits_s2xlate(lf_ptw_s2x),
    .io_in_1_ready(arb_in_1_ready), .io_in_1_valid(sf_ptw_valid),
    .io_in_1_bits_vpn(sf_ptw_vpn), .io_in_1_bits_s2xlate(sf_ptw_s2x),
    .io_in_2_ready(arb_in_2_ready), .io_in_2_valid(pf_ptw_valid),
    .io_in_2_bits_vpn(pf_ptw_vpn), .io_in_2_bits_s2xlate(pf_ptw_s2x),
    .io_out_ready(io_ptw_req_0_ready), .io_out_valid(io_ptw_req_0_valid),
    .io_out_bits_vpn(io_ptw_req_0_bits_vpn), .io_out_bits_s2xlate(io_ptw_req_0_bits_s2xlate)
  );

  xs_PTWNewFilter_core u_core (
    .clock(clock), .reset(reset), .io_flush(flush),
    .io_ptw_resp_valid(io_ptw_resp_valid), .io_ptw_resp_bits_s2xlate(io_ptw_resp_bits_s2xlate), .io_ptw_resp_bits_s1_entry_tag(io_ptw_resp_bits_s1_entry_tag), .io_ptw_resp_bits_s1_entry_asid(io_ptw_resp_bits_s1_entry_asid), .io_ptw_resp_bits_s1_entry_vmid(io_ptw_resp_bits_s1_entry_vmid), .io_ptw_resp_bits_s1_entry_n(io_ptw_resp_bits_s1_entry_n), .io_ptw_resp_bits_s1_entry_pbmt(io_ptw_resp_bits_s1_entry_pbmt), .io_ptw_resp_bits_s1_entry_perm_d(io_ptw_resp_bits_s1_entry_perm_d), .io_ptw_resp_bits_s1_entry_perm_a(io_ptw_resp_bits_s1_entry_perm_a), .io_ptw_resp_bits_s1_entry_perm_g(io_ptw_resp_bits_s1_entry_perm_g), .io_ptw_resp_bits_s1_entry_perm_u(io_ptw_resp_bits_s1_entry_perm_u), .io_ptw_resp_bits_s1_entry_perm_x(io_ptw_resp_bits_s1_entry_perm_x), .io_ptw_resp_bits_s1_entry_perm_w(io_ptw_resp_bits_s1_entry_perm_w), .io_ptw_resp_bits_s1_entry_perm_r(io_ptw_resp_bits_s1_entry_perm_r), .io_ptw_resp_bits_s1_entry_level(io_ptw_resp_bits_s1_entry_level), .io_ptw_resp_bits_s1_entry_v(io_ptw_resp_bits_s1_entry_v), .io_ptw_resp_bits_s1_entry_ppn(io_ptw_resp_bits_s1_entry_ppn), .io_ptw_resp_bits_s1_addr_low(io_ptw_resp_bits_s1_addr_low), .io_ptw_resp_bits_s1_ppn_low_0(io_ptw_resp_bits_s1_ppn_low_0), .io_ptw_resp_bits_s1_ppn_low_1(io_ptw_resp_bits_s1_ppn_low_1), .io_ptw_resp_bits_s1_ppn_low_2(io_ptw_resp_bits_s1_ppn_low_2), .io_ptw_resp_bits_s1_ppn_low_3(io_ptw_resp_bits_s1_ppn_low_3), .io_ptw_resp_bits_s1_ppn_low_4(io_ptw_resp_bits_s1_ppn_low_4), .io_ptw_resp_bits_s1_ppn_low_5(io_ptw_resp_bits_s1_ppn_low_5), .io_ptw_resp_bits_s1_ppn_low_6(io_ptw_resp_bits_s1_ppn_low_6), .io_ptw_resp_bits_s1_ppn_low_7(io_ptw_resp_bits_s1_ppn_low_7), .io_ptw_resp_bits_s1_valididx_0(io_ptw_resp_bits_s1_valididx_0), .io_ptw_resp_bits_s1_valididx_1(io_ptw_resp_bits_s1_valididx_1), .io_ptw_resp_bits_s1_valididx_2(io_ptw_resp_bits_s1_valididx_2), .io_ptw_resp_bits_s1_valididx_3(io_ptw_resp_bits_s1_valididx_3), .io_ptw_resp_bits_s1_valididx_4(io_ptw_resp_bits_s1_valididx_4), .io_ptw_resp_bits_s1_valididx_5(io_ptw_resp_bits_s1_valididx_5), .io_ptw_resp_bits_s1_valididx_6(io_ptw_resp_bits_s1_valididx_6), .io_ptw_resp_bits_s1_valididx_7(io_ptw_resp_bits_s1_valididx_7), .io_ptw_resp_bits_s1_pteidx_0(io_ptw_resp_bits_s1_pteidx_0), .io_ptw_resp_bits_s1_pteidx_1(io_ptw_resp_bits_s1_pteidx_1), .io_ptw_resp_bits_s1_pteidx_2(io_ptw_resp_bits_s1_pteidx_2), .io_ptw_resp_bits_s1_pteidx_3(io_ptw_resp_bits_s1_pteidx_3), .io_ptw_resp_bits_s1_pteidx_4(io_ptw_resp_bits_s1_pteidx_4), .io_ptw_resp_bits_s1_pteidx_5(io_ptw_resp_bits_s1_pteidx_5), .io_ptw_resp_bits_s1_pteidx_6(io_ptw_resp_bits_s1_pteidx_6), .io_ptw_resp_bits_s1_pteidx_7(io_ptw_resp_bits_s1_pteidx_7), .io_ptw_resp_bits_s1_pf(io_ptw_resp_bits_s1_pf), .io_ptw_resp_bits_s1_af(io_ptw_resp_bits_s1_af), .io_ptw_resp_bits_s2_entry_tag(io_ptw_resp_bits_s2_entry_tag), .io_ptw_resp_bits_s2_entry_vmid(io_ptw_resp_bits_s2_entry_vmid), .io_ptw_resp_bits_s2_entry_n(io_ptw_resp_bits_s2_entry_n), .io_ptw_resp_bits_s2_entry_pbmt(io_ptw_resp_bits_s2_entry_pbmt), .io_ptw_resp_bits_s2_entry_ppn(io_ptw_resp_bits_s2_entry_ppn), .io_ptw_resp_bits_s2_entry_perm_d(io_ptw_resp_bits_s2_entry_perm_d), .io_ptw_resp_bits_s2_entry_perm_a(io_ptw_resp_bits_s2_entry_perm_a), .io_ptw_resp_bits_s2_entry_perm_g(io_ptw_resp_bits_s2_entry_perm_g), .io_ptw_resp_bits_s2_entry_perm_u(io_ptw_resp_bits_s2_entry_perm_u), .io_ptw_resp_bits_s2_entry_perm_x(io_ptw_resp_bits_s2_entry_perm_x), .io_ptw_resp_bits_s2_entry_perm_w(io_ptw_resp_bits_s2_entry_perm_w), .io_ptw_resp_bits_s2_entry_perm_r(io_ptw_resp_bits_s2_entry_perm_r), .io_ptw_resp_bits_s2_entry_level(io_ptw_resp_bits_s2_entry_level), .io_ptw_resp_bits_s2_gpf(io_ptw_resp_bits_s2_gpf), .io_ptw_resp_bits_s2_gaf(io_ptw_resp_bits_s2_gaf),
    .o_load_ptw_resp_valid_last(lf_resp_last), .o_store_ptw_resp_valid_last(sf_resp_last),
    .o_prefetch_ptw_resp_valid_last(pf_resp_last),
    .o_ptwResp_s2xlate(cr_s2xlate),
    .o_ptwResp_s1_entry_tag(cr_s1_entry_tag),
    .o_ptwResp_s1_entry_asid(cr_s1_entry_asid),
    .o_ptwResp_s1_entry_vmid(cr_s1_entry_vmid),
    .o_ptwResp_s1_entry_n(cr_s1_entry_n),
    .o_ptwResp_s1_entry_perm_g(cr_s1_entry_perm_g),
    .o_ptwResp_s1_entry_level(cr_s1_entry_level),
    .o_ptwResp_s1_addr_low(cr_s1_addr_low),
    .o_ptwResp_s1_valididx_0(cr_s1_valididx_0),
    .o_ptwResp_s1_valididx_1(cr_s1_valididx_1),
    .o_ptwResp_s1_valididx_2(cr_s1_valididx_2),
    .o_ptwResp_s1_valididx_3(cr_s1_valididx_3),
    .o_ptwResp_s1_valididx_4(cr_s1_valididx_4),
    .o_ptwResp_s1_valididx_5(cr_s1_valididx_5),
    .o_ptwResp_s1_valididx_6(cr_s1_valididx_6),
    .o_ptwResp_s1_valididx_7(cr_s1_valididx_7),
    .o_ptwResp_s2_entry_tag(cr_s2_entry_tag),
    .o_ptwResp_s2_entry_vmid(cr_s2_entry_vmid),
    .o_ptwResp_s2_entry_n(cr_s2_entry_n),
    .o_ptwResp_s2_entry_level(cr_s2_entry_level),
    .i_load_refill(lf_refill), .i_store_refill(sf_refill), .i_prefetch_refill(pf_refill),
    .i_load_rob_head_miss(lf_rob), .i_store_rob_head_miss(sf_rob), .i_prefetch_rob_head_miss(pf_rob),
    .i_hint_req_0_id(lf_hint_req_0_id), .i_hint_req_0_full(lf_hint_req_0_full),
    .i_hint_req_1_id(lf_hint_req_1_id), .i_hint_req_1_full(lf_hint_req_1_full),
    .i_hint_req_2_id(lf_hint_req_2_id), .i_hint_req_2_full(lf_hint_req_2_full),
    .i_hint_resp_valid(lf_hint_resp_valid), .i_hint_resp_bits_id(lf_hint_resp_bits_id),
    .i_hint_resp_bits_replay_all(lf_hint_resp_bits_replay_all),
    .io_tlb_resp_valid(io_tlb_resp_valid), .io_tlb_resp_bits_data_s2xlate(io_tlb_resp_bits_data_s2xlate), .io_tlb_resp_bits_data_s1_entry_tag(io_tlb_resp_bits_data_s1_entry_tag), .io_tlb_resp_bits_data_s1_entry_asid(io_tlb_resp_bits_data_s1_entry_asid), .io_tlb_resp_bits_data_s1_entry_vmid(io_tlb_resp_bits_data_s1_entry_vmid), .io_tlb_resp_bits_data_s1_entry_n(io_tlb_resp_bits_data_s1_entry_n), .io_tlb_resp_bits_data_s1_entry_pbmt(io_tlb_resp_bits_data_s1_entry_pbmt), .io_tlb_resp_bits_data_s1_entry_perm_d(io_tlb_resp_bits_data_s1_entry_perm_d), .io_tlb_resp_bits_data_s1_entry_perm_a(io_tlb_resp_bits_data_s1_entry_perm_a), .io_tlb_resp_bits_data_s1_entry_perm_g(io_tlb_resp_bits_data_s1_entry_perm_g), .io_tlb_resp_bits_data_s1_entry_perm_u(io_tlb_resp_bits_data_s1_entry_perm_u), .io_tlb_resp_bits_data_s1_entry_perm_x(io_tlb_resp_bits_data_s1_entry_perm_x), .io_tlb_resp_bits_data_s1_entry_perm_w(io_tlb_resp_bits_data_s1_entry_perm_w), .io_tlb_resp_bits_data_s1_entry_perm_r(io_tlb_resp_bits_data_s1_entry_perm_r), .io_tlb_resp_bits_data_s1_entry_level(io_tlb_resp_bits_data_s1_entry_level), .io_tlb_resp_bits_data_s1_entry_v(io_tlb_resp_bits_data_s1_entry_v), .io_tlb_resp_bits_data_s1_entry_ppn(io_tlb_resp_bits_data_s1_entry_ppn), .io_tlb_resp_bits_data_s1_addr_low(io_tlb_resp_bits_data_s1_addr_low), .io_tlb_resp_bits_data_s1_ppn_low_0(io_tlb_resp_bits_data_s1_ppn_low_0), .io_tlb_resp_bits_data_s1_ppn_low_1(io_tlb_resp_bits_data_s1_ppn_low_1), .io_tlb_resp_bits_data_s1_ppn_low_2(io_tlb_resp_bits_data_s1_ppn_low_2), .io_tlb_resp_bits_data_s1_ppn_low_3(io_tlb_resp_bits_data_s1_ppn_low_3), .io_tlb_resp_bits_data_s1_ppn_low_4(io_tlb_resp_bits_data_s1_ppn_low_4), .io_tlb_resp_bits_data_s1_ppn_low_5(io_tlb_resp_bits_data_s1_ppn_low_5), .io_tlb_resp_bits_data_s1_ppn_low_6(io_tlb_resp_bits_data_s1_ppn_low_6), .io_tlb_resp_bits_data_s1_ppn_low_7(io_tlb_resp_bits_data_s1_ppn_low_7), .io_tlb_resp_bits_data_s1_valididx_0(io_tlb_resp_bits_data_s1_valididx_0), .io_tlb_resp_bits_data_s1_valididx_1(io_tlb_resp_bits_data_s1_valididx_1), .io_tlb_resp_bits_data_s1_valididx_2(io_tlb_resp_bits_data_s1_valididx_2), .io_tlb_resp_bits_data_s1_valididx_3(io_tlb_resp_bits_data_s1_valididx_3), .io_tlb_resp_bits_data_s1_valididx_4(io_tlb_resp_bits_data_s1_valididx_4), .io_tlb_resp_bits_data_s1_valididx_5(io_tlb_resp_bits_data_s1_valididx_5), .io_tlb_resp_bits_data_s1_valididx_6(io_tlb_resp_bits_data_s1_valididx_6), .io_tlb_resp_bits_data_s1_valididx_7(io_tlb_resp_bits_data_s1_valididx_7), .io_tlb_resp_bits_data_s1_pteidx_0(io_tlb_resp_bits_data_s1_pteidx_0), .io_tlb_resp_bits_data_s1_pteidx_1(io_tlb_resp_bits_data_s1_pteidx_1), .io_tlb_resp_bits_data_s1_pteidx_2(io_tlb_resp_bits_data_s1_pteidx_2), .io_tlb_resp_bits_data_s1_pteidx_3(io_tlb_resp_bits_data_s1_pteidx_3), .io_tlb_resp_bits_data_s1_pteidx_4(io_tlb_resp_bits_data_s1_pteidx_4), .io_tlb_resp_bits_data_s1_pteidx_5(io_tlb_resp_bits_data_s1_pteidx_5), .io_tlb_resp_bits_data_s1_pteidx_6(io_tlb_resp_bits_data_s1_pteidx_6), .io_tlb_resp_bits_data_s1_pteidx_7(io_tlb_resp_bits_data_s1_pteidx_7), .io_tlb_resp_bits_data_s1_pf(io_tlb_resp_bits_data_s1_pf), .io_tlb_resp_bits_data_s1_af(io_tlb_resp_bits_data_s1_af), .io_tlb_resp_bits_data_s2_entry_tag(io_tlb_resp_bits_data_s2_entry_tag), .io_tlb_resp_bits_data_s2_entry_vmid(io_tlb_resp_bits_data_s2_entry_vmid), .io_tlb_resp_bits_data_s2_entry_n(io_tlb_resp_bits_data_s2_entry_n), .io_tlb_resp_bits_data_s2_entry_pbmt(io_tlb_resp_bits_data_s2_entry_pbmt), .io_tlb_resp_bits_data_s2_entry_ppn(io_tlb_resp_bits_data_s2_entry_ppn), .io_tlb_resp_bits_data_s2_entry_perm_d(io_tlb_resp_bits_data_s2_entry_perm_d), .io_tlb_resp_bits_data_s2_entry_perm_a(io_tlb_resp_bits_data_s2_entry_perm_a), .io_tlb_resp_bits_data_s2_entry_perm_g(io_tlb_resp_bits_data_s2_entry_perm_g), .io_tlb_resp_bits_data_s2_entry_perm_u(io_tlb_resp_bits_data_s2_entry_perm_u), .io_tlb_resp_bits_data_s2_entry_perm_x(io_tlb_resp_bits_data_s2_entry_perm_x), .io_tlb_resp_bits_data_s2_entry_perm_w(io_tlb_resp_bits_data_s2_entry_perm_w), .io_tlb_resp_bits_data_s2_entry_perm_r(io_tlb_resp_bits_data_s2_entry_perm_r), .io_tlb_resp_bits_data_s2_entry_level(io_tlb_resp_bits_data_s2_entry_level), .io_tlb_resp_bits_data_s2_gpf(io_tlb_resp_bits_data_s2_gpf), .io_tlb_resp_bits_data_s2_gaf(io_tlb_resp_bits_data_s2_gaf), .io_tlb_resp_bits_vector_0(io_tlb_resp_bits_vector_0), .io_tlb_resp_bits_vector_4(io_tlb_resp_bits_vector_4), .io_tlb_resp_bits_vector_6(io_tlb_resp_bits_vector_6), .io_hint_req_0_id(io_hint_req_0_id), .io_hint_req_0_full(io_hint_req_0_full), .io_hint_req_1_id(io_hint_req_1_id), .io_hint_req_1_full(io_hint_req_1_full), .io_hint_req_2_id(io_hint_req_2_id), .io_hint_req_2_full(io_hint_req_2_full), .io_hint_resp_valid(io_hint_resp_valid), .io_hint_resp_bits_id(io_hint_resp_bits_id), .io_hint_resp_bits_replay_all(io_hint_resp_bits_replay_all), .io_rob_head_miss_in_tlb(io_rob_head_miss_in_tlb)
  );
endmodule
