// 自动生成：scripts/gen_snxbar.py —— 勿手改
module SNXbar_xs(
  input clock,
  input reset,
  output io_in_0_tx_req_ready,
  input io_in_0_tx_req_valid,
  input [10:0] io_in_0_tx_req_bits_tgtID,
  input [10:0] io_in_0_tx_req_bits_srcID,
  input [11:0] io_in_0_tx_req_bits_txnID,
  input [6:0] io_in_0_tx_req_bits_opcode,
  input [2:0] io_in_0_tx_req_bits_size,
  input [47:0] io_in_0_tx_req_bits_addr,
  input io_in_0_tx_req_bits_allowRetry,
  input [1:0] io_in_0_tx_req_bits_order,
  input [3:0] io_in_0_tx_req_bits_pCrdType,
  input io_in_0_tx_req_bits_memAttr_allocate,
  input io_in_0_tx_req_bits_memAttr_cacheable,
  input io_in_0_tx_req_bits_memAttr_device,
  input io_in_0_tx_req_bits_memAttr_ewa,
  input io_in_0_tx_req_bits_snpAttr,
  input io_in_0_tx_req_bits_expCompAck,
  output io_in_0_tx_dat_ready,
  input io_in_0_tx_dat_valid,
  input [10:0] io_in_0_tx_dat_bits_tgtID,
  input [10:0] io_in_0_tx_dat_bits_srcID,
  input [11:0] io_in_0_tx_dat_bits_txnID,
  input [10:0] io_in_0_tx_dat_bits_homeNID,
  input [3:0] io_in_0_tx_dat_bits_opcode,
  input [2:0] io_in_0_tx_dat_bits_resp,
  input [3:0] io_in_0_tx_dat_bits_dataSource,
  input [11:0] io_in_0_tx_dat_bits_dbID,
  input [1:0] io_in_0_tx_dat_bits_dataID,
  input [31:0] io_in_0_tx_dat_bits_be,
  input [255:0] io_in_0_tx_dat_bits_data,
  input [31:0] io_in_0_tx_dat_bits_dataCheck,
  output io_in_0_rx_rsp_valid,
  output [10:0] io_in_0_rx_rsp_bits_srcID,
  output [11:0] io_in_0_rx_rsp_bits_txnID,
  output [4:0] io_in_0_rx_rsp_bits_opcode,
  output [11:0] io_in_0_rx_rsp_bits_dbID,
  output io_in_0_rx_dat_valid,
  output [10:0] io_in_0_rx_dat_bits_srcID,
  output [11:0] io_in_0_rx_dat_bits_txnID,
  output [3:0] io_in_0_rx_dat_bits_opcode,
  output [2:0] io_in_0_rx_dat_bits_resp,
  output [1:0] io_in_0_rx_dat_bits_dataID,
  output [255:0] io_in_0_rx_dat_bits_data,
  output io_in_1_tx_req_ready,
  input io_in_1_tx_req_valid,
  input [10:0] io_in_1_tx_req_bits_tgtID,
  input [10:0] io_in_1_tx_req_bits_srcID,
  input [11:0] io_in_1_tx_req_bits_txnID,
  input [6:0] io_in_1_tx_req_bits_opcode,
  input [2:0] io_in_1_tx_req_bits_size,
  input [47:0] io_in_1_tx_req_bits_addr,
  input io_in_1_tx_req_bits_allowRetry,
  input [1:0] io_in_1_tx_req_bits_order,
  input [3:0] io_in_1_tx_req_bits_pCrdType,
  input io_in_1_tx_req_bits_memAttr_allocate,
  input io_in_1_tx_req_bits_memAttr_cacheable,
  input io_in_1_tx_req_bits_memAttr_device,
  input io_in_1_tx_req_bits_memAttr_ewa,
  input io_in_1_tx_req_bits_snpAttr,
  input io_in_1_tx_req_bits_expCompAck,
  output io_in_1_tx_dat_ready,
  input io_in_1_tx_dat_valid,
  input [10:0] io_in_1_tx_dat_bits_tgtID,
  input [10:0] io_in_1_tx_dat_bits_srcID,
  input [11:0] io_in_1_tx_dat_bits_txnID,
  input [10:0] io_in_1_tx_dat_bits_homeNID,
  input [3:0] io_in_1_tx_dat_bits_opcode,
  input [2:0] io_in_1_tx_dat_bits_resp,
  input [3:0] io_in_1_tx_dat_bits_dataSource,
  input [11:0] io_in_1_tx_dat_bits_dbID,
  input [1:0] io_in_1_tx_dat_bits_dataID,
  input [31:0] io_in_1_tx_dat_bits_be,
  input [255:0] io_in_1_tx_dat_bits_data,
  input [31:0] io_in_1_tx_dat_bits_dataCheck,
  output io_in_1_rx_rsp_valid,
  output [10:0] io_in_1_rx_rsp_bits_srcID,
  output [11:0] io_in_1_rx_rsp_bits_txnID,
  output [4:0] io_in_1_rx_rsp_bits_opcode,
  output [11:0] io_in_1_rx_rsp_bits_dbID,
  output io_in_1_rx_dat_valid,
  output [10:0] io_in_1_rx_dat_bits_srcID,
  output [11:0] io_in_1_rx_dat_bits_txnID,
  output [3:0] io_in_1_rx_dat_bits_opcode,
  output [2:0] io_in_1_rx_dat_bits_resp,
  output [1:0] io_in_1_rx_dat_bits_dataID,
  output [255:0] io_in_1_rx_dat_bits_data,
  output io_in_2_tx_req_ready,
  input io_in_2_tx_req_valid,
  input [10:0] io_in_2_tx_req_bits_tgtID,
  input [10:0] io_in_2_tx_req_bits_srcID,
  input [11:0] io_in_2_tx_req_bits_txnID,
  input [6:0] io_in_2_tx_req_bits_opcode,
  input [2:0] io_in_2_tx_req_bits_size,
  input [47:0] io_in_2_tx_req_bits_addr,
  input io_in_2_tx_req_bits_allowRetry,
  input [1:0] io_in_2_tx_req_bits_order,
  input [3:0] io_in_2_tx_req_bits_pCrdType,
  input io_in_2_tx_req_bits_memAttr_allocate,
  input io_in_2_tx_req_bits_memAttr_cacheable,
  input io_in_2_tx_req_bits_memAttr_device,
  input io_in_2_tx_req_bits_memAttr_ewa,
  input io_in_2_tx_req_bits_snpAttr,
  input io_in_2_tx_req_bits_expCompAck,
  output io_in_2_tx_dat_ready,
  input io_in_2_tx_dat_valid,
  input [10:0] io_in_2_tx_dat_bits_tgtID,
  input [10:0] io_in_2_tx_dat_bits_srcID,
  input [11:0] io_in_2_tx_dat_bits_txnID,
  input [10:0] io_in_2_tx_dat_bits_homeNID,
  input [3:0] io_in_2_tx_dat_bits_opcode,
  input [2:0] io_in_2_tx_dat_bits_resp,
  input [3:0] io_in_2_tx_dat_bits_dataSource,
  input [11:0] io_in_2_tx_dat_bits_dbID,
  input [1:0] io_in_2_tx_dat_bits_dataID,
  input [31:0] io_in_2_tx_dat_bits_be,
  input [255:0] io_in_2_tx_dat_bits_data,
  input [31:0] io_in_2_tx_dat_bits_dataCheck,
  output io_in_2_rx_rsp_valid,
  output [10:0] io_in_2_rx_rsp_bits_srcID,
  output [11:0] io_in_2_rx_rsp_bits_txnID,
  output [4:0] io_in_2_rx_rsp_bits_opcode,
  output [11:0] io_in_2_rx_rsp_bits_dbID,
  output io_in_2_rx_dat_valid,
  output [10:0] io_in_2_rx_dat_bits_srcID,
  output [11:0] io_in_2_rx_dat_bits_txnID,
  output [3:0] io_in_2_rx_dat_bits_opcode,
  output [2:0] io_in_2_rx_dat_bits_resp,
  output [1:0] io_in_2_rx_dat_bits_dataID,
  output [255:0] io_in_2_rx_dat_bits_data,
  output io_in_3_tx_req_ready,
  input io_in_3_tx_req_valid,
  input [10:0] io_in_3_tx_req_bits_tgtID,
  input [10:0] io_in_3_tx_req_bits_srcID,
  input [11:0] io_in_3_tx_req_bits_txnID,
  input [6:0] io_in_3_tx_req_bits_opcode,
  input [2:0] io_in_3_tx_req_bits_size,
  input [47:0] io_in_3_tx_req_bits_addr,
  input io_in_3_tx_req_bits_allowRetry,
  input [1:0] io_in_3_tx_req_bits_order,
  input [3:0] io_in_3_tx_req_bits_pCrdType,
  input io_in_3_tx_req_bits_memAttr_allocate,
  input io_in_3_tx_req_bits_memAttr_cacheable,
  input io_in_3_tx_req_bits_memAttr_device,
  input io_in_3_tx_req_bits_memAttr_ewa,
  input io_in_3_tx_req_bits_snpAttr,
  input io_in_3_tx_req_bits_expCompAck,
  output io_in_3_tx_dat_ready,
  input io_in_3_tx_dat_valid,
  input [10:0] io_in_3_tx_dat_bits_tgtID,
  input [10:0] io_in_3_tx_dat_bits_srcID,
  input [11:0] io_in_3_tx_dat_bits_txnID,
  input [10:0] io_in_3_tx_dat_bits_homeNID,
  input [3:0] io_in_3_tx_dat_bits_opcode,
  input [2:0] io_in_3_tx_dat_bits_resp,
  input [3:0] io_in_3_tx_dat_bits_dataSource,
  input [11:0] io_in_3_tx_dat_bits_dbID,
  input [1:0] io_in_3_tx_dat_bits_dataID,
  input [31:0] io_in_3_tx_dat_bits_be,
  input [255:0] io_in_3_tx_dat_bits_data,
  input [31:0] io_in_3_tx_dat_bits_dataCheck,
  output io_in_3_rx_rsp_valid,
  output [10:0] io_in_3_rx_rsp_bits_srcID,
  output [11:0] io_in_3_rx_rsp_bits_txnID,
  output [4:0] io_in_3_rx_rsp_bits_opcode,
  output [11:0] io_in_3_rx_rsp_bits_dbID,
  output io_in_3_rx_dat_valid,
  output [10:0] io_in_3_rx_dat_bits_srcID,
  output [11:0] io_in_3_rx_dat_bits_txnID,
  output [3:0] io_in_3_rx_dat_bits_opcode,
  output [2:0] io_in_3_rx_dat_bits_resp,
  output [1:0] io_in_3_rx_dat_bits_dataID,
  output [255:0] io_in_3_rx_dat_bits_data,
  input io_out_tx_req_ready,
  output io_out_tx_req_valid,
  output [10:0] io_out_tx_req_bits_tgtID,
  output [10:0] io_out_tx_req_bits_srcID,
  output [11:0] io_out_tx_req_bits_txnID,
  output [6:0] io_out_tx_req_bits_opcode,
  output [2:0] io_out_tx_req_bits_size,
  output [47:0] io_out_tx_req_bits_addr,
  output io_out_tx_req_bits_allowRetry,
  output [1:0] io_out_tx_req_bits_order,
  output [3:0] io_out_tx_req_bits_pCrdType,
  output io_out_tx_req_bits_memAttr_allocate,
  output io_out_tx_req_bits_memAttr_cacheable,
  output io_out_tx_req_bits_memAttr_device,
  output io_out_tx_req_bits_memAttr_ewa,
  output io_out_tx_req_bits_snpAttr,
  output io_out_tx_req_bits_expCompAck,
  input io_out_tx_dat_ready,
  output io_out_tx_dat_valid,
  output [10:0] io_out_tx_dat_bits_tgtID,
  output [10:0] io_out_tx_dat_bits_srcID,
  output [11:0] io_out_tx_dat_bits_txnID,
  output [10:0] io_out_tx_dat_bits_homeNID,
  output [3:0] io_out_tx_dat_bits_opcode,
  output [2:0] io_out_tx_dat_bits_resp,
  output [3:0] io_out_tx_dat_bits_dataSource,
  output [11:0] io_out_tx_dat_bits_dbID,
  output [1:0] io_out_tx_dat_bits_dataID,
  output [31:0] io_out_tx_dat_bits_be,
  output [255:0] io_out_tx_dat_bits_data,
  output [31:0] io_out_tx_dat_bits_dataCheck,
  output io_out_rx_rsp_ready,
  input io_out_rx_rsp_valid,
  input [10:0] io_out_rx_rsp_bits_srcID,
  input [11:0] io_out_rx_rsp_bits_txnID,
  input [4:0] io_out_rx_rsp_bits_opcode,
  input [11:0] io_out_rx_rsp_bits_dbID,
  output io_out_rx_dat_ready,
  input io_out_rx_dat_valid,
  input [10:0] io_out_rx_dat_bits_srcID,
  input [11:0] io_out_rx_dat_bits_txnID,
  input [3:0] io_out_rx_dat_bits_opcode,
  input [2:0] io_out_rx_dat_bits_resp,
  input [1:0] io_out_rx_dat_bits_dataID,
  input [255:0] io_out_rx_dat_bits_data
);
  xs_SNXbar_core u_core (
    .clock(clock),
    .reset(reset),
    .io_in_0_tx_req_ready(io_in_0_tx_req_ready),
    .io_in_0_tx_req_valid(io_in_0_tx_req_valid),
    .io_in_0_tx_req_bits_tgtID(io_in_0_tx_req_bits_tgtID),
    .io_in_0_tx_req_bits_srcID(io_in_0_tx_req_bits_srcID),
    .io_in_0_tx_req_bits_txnID(io_in_0_tx_req_bits_txnID),
    .io_in_0_tx_req_bits_opcode(io_in_0_tx_req_bits_opcode),
    .io_in_0_tx_req_bits_size(io_in_0_tx_req_bits_size),
    .io_in_0_tx_req_bits_addr(io_in_0_tx_req_bits_addr),
    .io_in_0_tx_req_bits_allowRetry(io_in_0_tx_req_bits_allowRetry),
    .io_in_0_tx_req_bits_order(io_in_0_tx_req_bits_order),
    .io_in_0_tx_req_bits_pCrdType(io_in_0_tx_req_bits_pCrdType),
    .io_in_0_tx_req_bits_memAttr_allocate(io_in_0_tx_req_bits_memAttr_allocate),
    .io_in_0_tx_req_bits_memAttr_cacheable(io_in_0_tx_req_bits_memAttr_cacheable),
    .io_in_0_tx_req_bits_memAttr_device(io_in_0_tx_req_bits_memAttr_device),
    .io_in_0_tx_req_bits_memAttr_ewa(io_in_0_tx_req_bits_memAttr_ewa),
    .io_in_0_tx_req_bits_snpAttr(io_in_0_tx_req_bits_snpAttr),
    .io_in_0_tx_req_bits_expCompAck(io_in_0_tx_req_bits_expCompAck),
    .io_in_0_tx_dat_ready(io_in_0_tx_dat_ready),
    .io_in_0_tx_dat_valid(io_in_0_tx_dat_valid),
    .io_in_0_tx_dat_bits_tgtID(io_in_0_tx_dat_bits_tgtID),
    .io_in_0_tx_dat_bits_srcID(io_in_0_tx_dat_bits_srcID),
    .io_in_0_tx_dat_bits_txnID(io_in_0_tx_dat_bits_txnID),
    .io_in_0_tx_dat_bits_homeNID(io_in_0_tx_dat_bits_homeNID),
    .io_in_0_tx_dat_bits_opcode(io_in_0_tx_dat_bits_opcode),
    .io_in_0_tx_dat_bits_resp(io_in_0_tx_dat_bits_resp),
    .io_in_0_tx_dat_bits_dataSource(io_in_0_tx_dat_bits_dataSource),
    .io_in_0_tx_dat_bits_dbID(io_in_0_tx_dat_bits_dbID),
    .io_in_0_tx_dat_bits_dataID(io_in_0_tx_dat_bits_dataID),
    .io_in_0_tx_dat_bits_be(io_in_0_tx_dat_bits_be),
    .io_in_0_tx_dat_bits_data(io_in_0_tx_dat_bits_data),
    .io_in_0_tx_dat_bits_dataCheck(io_in_0_tx_dat_bits_dataCheck),
    .io_in_0_rx_rsp_valid(io_in_0_rx_rsp_valid),
    .io_in_0_rx_rsp_bits_srcID(io_in_0_rx_rsp_bits_srcID),
    .io_in_0_rx_rsp_bits_txnID(io_in_0_rx_rsp_bits_txnID),
    .io_in_0_rx_rsp_bits_opcode(io_in_0_rx_rsp_bits_opcode),
    .io_in_0_rx_rsp_bits_dbID(io_in_0_rx_rsp_bits_dbID),
    .io_in_0_rx_dat_valid(io_in_0_rx_dat_valid),
    .io_in_0_rx_dat_bits_srcID(io_in_0_rx_dat_bits_srcID),
    .io_in_0_rx_dat_bits_txnID(io_in_0_rx_dat_bits_txnID),
    .io_in_0_rx_dat_bits_opcode(io_in_0_rx_dat_bits_opcode),
    .io_in_0_rx_dat_bits_resp(io_in_0_rx_dat_bits_resp),
    .io_in_0_rx_dat_bits_dataID(io_in_0_rx_dat_bits_dataID),
    .io_in_0_rx_dat_bits_data(io_in_0_rx_dat_bits_data),
    .io_in_1_tx_req_ready(io_in_1_tx_req_ready),
    .io_in_1_tx_req_valid(io_in_1_tx_req_valid),
    .io_in_1_tx_req_bits_tgtID(io_in_1_tx_req_bits_tgtID),
    .io_in_1_tx_req_bits_srcID(io_in_1_tx_req_bits_srcID),
    .io_in_1_tx_req_bits_txnID(io_in_1_tx_req_bits_txnID),
    .io_in_1_tx_req_bits_opcode(io_in_1_tx_req_bits_opcode),
    .io_in_1_tx_req_bits_size(io_in_1_tx_req_bits_size),
    .io_in_1_tx_req_bits_addr(io_in_1_tx_req_bits_addr),
    .io_in_1_tx_req_bits_allowRetry(io_in_1_tx_req_bits_allowRetry),
    .io_in_1_tx_req_bits_order(io_in_1_tx_req_bits_order),
    .io_in_1_tx_req_bits_pCrdType(io_in_1_tx_req_bits_pCrdType),
    .io_in_1_tx_req_bits_memAttr_allocate(io_in_1_tx_req_bits_memAttr_allocate),
    .io_in_1_tx_req_bits_memAttr_cacheable(io_in_1_tx_req_bits_memAttr_cacheable),
    .io_in_1_tx_req_bits_memAttr_device(io_in_1_tx_req_bits_memAttr_device),
    .io_in_1_tx_req_bits_memAttr_ewa(io_in_1_tx_req_bits_memAttr_ewa),
    .io_in_1_tx_req_bits_snpAttr(io_in_1_tx_req_bits_snpAttr),
    .io_in_1_tx_req_bits_expCompAck(io_in_1_tx_req_bits_expCompAck),
    .io_in_1_tx_dat_ready(io_in_1_tx_dat_ready),
    .io_in_1_tx_dat_valid(io_in_1_tx_dat_valid),
    .io_in_1_tx_dat_bits_tgtID(io_in_1_tx_dat_bits_tgtID),
    .io_in_1_tx_dat_bits_srcID(io_in_1_tx_dat_bits_srcID),
    .io_in_1_tx_dat_bits_txnID(io_in_1_tx_dat_bits_txnID),
    .io_in_1_tx_dat_bits_homeNID(io_in_1_tx_dat_bits_homeNID),
    .io_in_1_tx_dat_bits_opcode(io_in_1_tx_dat_bits_opcode),
    .io_in_1_tx_dat_bits_resp(io_in_1_tx_dat_bits_resp),
    .io_in_1_tx_dat_bits_dataSource(io_in_1_tx_dat_bits_dataSource),
    .io_in_1_tx_dat_bits_dbID(io_in_1_tx_dat_bits_dbID),
    .io_in_1_tx_dat_bits_dataID(io_in_1_tx_dat_bits_dataID),
    .io_in_1_tx_dat_bits_be(io_in_1_tx_dat_bits_be),
    .io_in_1_tx_dat_bits_data(io_in_1_tx_dat_bits_data),
    .io_in_1_tx_dat_bits_dataCheck(io_in_1_tx_dat_bits_dataCheck),
    .io_in_1_rx_rsp_valid(io_in_1_rx_rsp_valid),
    .io_in_1_rx_rsp_bits_srcID(io_in_1_rx_rsp_bits_srcID),
    .io_in_1_rx_rsp_bits_txnID(io_in_1_rx_rsp_bits_txnID),
    .io_in_1_rx_rsp_bits_opcode(io_in_1_rx_rsp_bits_opcode),
    .io_in_1_rx_rsp_bits_dbID(io_in_1_rx_rsp_bits_dbID),
    .io_in_1_rx_dat_valid(io_in_1_rx_dat_valid),
    .io_in_1_rx_dat_bits_srcID(io_in_1_rx_dat_bits_srcID),
    .io_in_1_rx_dat_bits_txnID(io_in_1_rx_dat_bits_txnID),
    .io_in_1_rx_dat_bits_opcode(io_in_1_rx_dat_bits_opcode),
    .io_in_1_rx_dat_bits_resp(io_in_1_rx_dat_bits_resp),
    .io_in_1_rx_dat_bits_dataID(io_in_1_rx_dat_bits_dataID),
    .io_in_1_rx_dat_bits_data(io_in_1_rx_dat_bits_data),
    .io_in_2_tx_req_ready(io_in_2_tx_req_ready),
    .io_in_2_tx_req_valid(io_in_2_tx_req_valid),
    .io_in_2_tx_req_bits_tgtID(io_in_2_tx_req_bits_tgtID),
    .io_in_2_tx_req_bits_srcID(io_in_2_tx_req_bits_srcID),
    .io_in_2_tx_req_bits_txnID(io_in_2_tx_req_bits_txnID),
    .io_in_2_tx_req_bits_opcode(io_in_2_tx_req_bits_opcode),
    .io_in_2_tx_req_bits_size(io_in_2_tx_req_bits_size),
    .io_in_2_tx_req_bits_addr(io_in_2_tx_req_bits_addr),
    .io_in_2_tx_req_bits_allowRetry(io_in_2_tx_req_bits_allowRetry),
    .io_in_2_tx_req_bits_order(io_in_2_tx_req_bits_order),
    .io_in_2_tx_req_bits_pCrdType(io_in_2_tx_req_bits_pCrdType),
    .io_in_2_tx_req_bits_memAttr_allocate(io_in_2_tx_req_bits_memAttr_allocate),
    .io_in_2_tx_req_bits_memAttr_cacheable(io_in_2_tx_req_bits_memAttr_cacheable),
    .io_in_2_tx_req_bits_memAttr_device(io_in_2_tx_req_bits_memAttr_device),
    .io_in_2_tx_req_bits_memAttr_ewa(io_in_2_tx_req_bits_memAttr_ewa),
    .io_in_2_tx_req_bits_snpAttr(io_in_2_tx_req_bits_snpAttr),
    .io_in_2_tx_req_bits_expCompAck(io_in_2_tx_req_bits_expCompAck),
    .io_in_2_tx_dat_ready(io_in_2_tx_dat_ready),
    .io_in_2_tx_dat_valid(io_in_2_tx_dat_valid),
    .io_in_2_tx_dat_bits_tgtID(io_in_2_tx_dat_bits_tgtID),
    .io_in_2_tx_dat_bits_srcID(io_in_2_tx_dat_bits_srcID),
    .io_in_2_tx_dat_bits_txnID(io_in_2_tx_dat_bits_txnID),
    .io_in_2_tx_dat_bits_homeNID(io_in_2_tx_dat_bits_homeNID),
    .io_in_2_tx_dat_bits_opcode(io_in_2_tx_dat_bits_opcode),
    .io_in_2_tx_dat_bits_resp(io_in_2_tx_dat_bits_resp),
    .io_in_2_tx_dat_bits_dataSource(io_in_2_tx_dat_bits_dataSource),
    .io_in_2_tx_dat_bits_dbID(io_in_2_tx_dat_bits_dbID),
    .io_in_2_tx_dat_bits_dataID(io_in_2_tx_dat_bits_dataID),
    .io_in_2_tx_dat_bits_be(io_in_2_tx_dat_bits_be),
    .io_in_2_tx_dat_bits_data(io_in_2_tx_dat_bits_data),
    .io_in_2_tx_dat_bits_dataCheck(io_in_2_tx_dat_bits_dataCheck),
    .io_in_2_rx_rsp_valid(io_in_2_rx_rsp_valid),
    .io_in_2_rx_rsp_bits_srcID(io_in_2_rx_rsp_bits_srcID),
    .io_in_2_rx_rsp_bits_txnID(io_in_2_rx_rsp_bits_txnID),
    .io_in_2_rx_rsp_bits_opcode(io_in_2_rx_rsp_bits_opcode),
    .io_in_2_rx_rsp_bits_dbID(io_in_2_rx_rsp_bits_dbID),
    .io_in_2_rx_dat_valid(io_in_2_rx_dat_valid),
    .io_in_2_rx_dat_bits_srcID(io_in_2_rx_dat_bits_srcID),
    .io_in_2_rx_dat_bits_txnID(io_in_2_rx_dat_bits_txnID),
    .io_in_2_rx_dat_bits_opcode(io_in_2_rx_dat_bits_opcode),
    .io_in_2_rx_dat_bits_resp(io_in_2_rx_dat_bits_resp),
    .io_in_2_rx_dat_bits_dataID(io_in_2_rx_dat_bits_dataID),
    .io_in_2_rx_dat_bits_data(io_in_2_rx_dat_bits_data),
    .io_in_3_tx_req_ready(io_in_3_tx_req_ready),
    .io_in_3_tx_req_valid(io_in_3_tx_req_valid),
    .io_in_3_tx_req_bits_tgtID(io_in_3_tx_req_bits_tgtID),
    .io_in_3_tx_req_bits_srcID(io_in_3_tx_req_bits_srcID),
    .io_in_3_tx_req_bits_txnID(io_in_3_tx_req_bits_txnID),
    .io_in_3_tx_req_bits_opcode(io_in_3_tx_req_bits_opcode),
    .io_in_3_tx_req_bits_size(io_in_3_tx_req_bits_size),
    .io_in_3_tx_req_bits_addr(io_in_3_tx_req_bits_addr),
    .io_in_3_tx_req_bits_allowRetry(io_in_3_tx_req_bits_allowRetry),
    .io_in_3_tx_req_bits_order(io_in_3_tx_req_bits_order),
    .io_in_3_tx_req_bits_pCrdType(io_in_3_tx_req_bits_pCrdType),
    .io_in_3_tx_req_bits_memAttr_allocate(io_in_3_tx_req_bits_memAttr_allocate),
    .io_in_3_tx_req_bits_memAttr_cacheable(io_in_3_tx_req_bits_memAttr_cacheable),
    .io_in_3_tx_req_bits_memAttr_device(io_in_3_tx_req_bits_memAttr_device),
    .io_in_3_tx_req_bits_memAttr_ewa(io_in_3_tx_req_bits_memAttr_ewa),
    .io_in_3_tx_req_bits_snpAttr(io_in_3_tx_req_bits_snpAttr),
    .io_in_3_tx_req_bits_expCompAck(io_in_3_tx_req_bits_expCompAck),
    .io_in_3_tx_dat_ready(io_in_3_tx_dat_ready),
    .io_in_3_tx_dat_valid(io_in_3_tx_dat_valid),
    .io_in_3_tx_dat_bits_tgtID(io_in_3_tx_dat_bits_tgtID),
    .io_in_3_tx_dat_bits_srcID(io_in_3_tx_dat_bits_srcID),
    .io_in_3_tx_dat_bits_txnID(io_in_3_tx_dat_bits_txnID),
    .io_in_3_tx_dat_bits_homeNID(io_in_3_tx_dat_bits_homeNID),
    .io_in_3_tx_dat_bits_opcode(io_in_3_tx_dat_bits_opcode),
    .io_in_3_tx_dat_bits_resp(io_in_3_tx_dat_bits_resp),
    .io_in_3_tx_dat_bits_dataSource(io_in_3_tx_dat_bits_dataSource),
    .io_in_3_tx_dat_bits_dbID(io_in_3_tx_dat_bits_dbID),
    .io_in_3_tx_dat_bits_dataID(io_in_3_tx_dat_bits_dataID),
    .io_in_3_tx_dat_bits_be(io_in_3_tx_dat_bits_be),
    .io_in_3_tx_dat_bits_data(io_in_3_tx_dat_bits_data),
    .io_in_3_tx_dat_bits_dataCheck(io_in_3_tx_dat_bits_dataCheck),
    .io_in_3_rx_rsp_valid(io_in_3_rx_rsp_valid),
    .io_in_3_rx_rsp_bits_srcID(io_in_3_rx_rsp_bits_srcID),
    .io_in_3_rx_rsp_bits_txnID(io_in_3_rx_rsp_bits_txnID),
    .io_in_3_rx_rsp_bits_opcode(io_in_3_rx_rsp_bits_opcode),
    .io_in_3_rx_rsp_bits_dbID(io_in_3_rx_rsp_bits_dbID),
    .io_in_3_rx_dat_valid(io_in_3_rx_dat_valid),
    .io_in_3_rx_dat_bits_srcID(io_in_3_rx_dat_bits_srcID),
    .io_in_3_rx_dat_bits_txnID(io_in_3_rx_dat_bits_txnID),
    .io_in_3_rx_dat_bits_opcode(io_in_3_rx_dat_bits_opcode),
    .io_in_3_rx_dat_bits_resp(io_in_3_rx_dat_bits_resp),
    .io_in_3_rx_dat_bits_dataID(io_in_3_rx_dat_bits_dataID),
    .io_in_3_rx_dat_bits_data(io_in_3_rx_dat_bits_data),
    .io_out_tx_req_ready(io_out_tx_req_ready),
    .io_out_tx_req_valid(io_out_tx_req_valid),
    .io_out_tx_req_bits_tgtID(io_out_tx_req_bits_tgtID),
    .io_out_tx_req_bits_srcID(io_out_tx_req_bits_srcID),
    .io_out_tx_req_bits_txnID(io_out_tx_req_bits_txnID),
    .io_out_tx_req_bits_opcode(io_out_tx_req_bits_opcode),
    .io_out_tx_req_bits_size(io_out_tx_req_bits_size),
    .io_out_tx_req_bits_addr(io_out_tx_req_bits_addr),
    .io_out_tx_req_bits_allowRetry(io_out_tx_req_bits_allowRetry),
    .io_out_tx_req_bits_order(io_out_tx_req_bits_order),
    .io_out_tx_req_bits_pCrdType(io_out_tx_req_bits_pCrdType),
    .io_out_tx_req_bits_memAttr_allocate(io_out_tx_req_bits_memAttr_allocate),
    .io_out_tx_req_bits_memAttr_cacheable(io_out_tx_req_bits_memAttr_cacheable),
    .io_out_tx_req_bits_memAttr_device(io_out_tx_req_bits_memAttr_device),
    .io_out_tx_req_bits_memAttr_ewa(io_out_tx_req_bits_memAttr_ewa),
    .io_out_tx_req_bits_snpAttr(io_out_tx_req_bits_snpAttr),
    .io_out_tx_req_bits_expCompAck(io_out_tx_req_bits_expCompAck),
    .io_out_tx_dat_ready(io_out_tx_dat_ready),
    .io_out_tx_dat_valid(io_out_tx_dat_valid),
    .io_out_tx_dat_bits_tgtID(io_out_tx_dat_bits_tgtID),
    .io_out_tx_dat_bits_srcID(io_out_tx_dat_bits_srcID),
    .io_out_tx_dat_bits_txnID(io_out_tx_dat_bits_txnID),
    .io_out_tx_dat_bits_homeNID(io_out_tx_dat_bits_homeNID),
    .io_out_tx_dat_bits_opcode(io_out_tx_dat_bits_opcode),
    .io_out_tx_dat_bits_resp(io_out_tx_dat_bits_resp),
    .io_out_tx_dat_bits_dataSource(io_out_tx_dat_bits_dataSource),
    .io_out_tx_dat_bits_dbID(io_out_tx_dat_bits_dbID),
    .io_out_tx_dat_bits_dataID(io_out_tx_dat_bits_dataID),
    .io_out_tx_dat_bits_be(io_out_tx_dat_bits_be),
    .io_out_tx_dat_bits_data(io_out_tx_dat_bits_data),
    .io_out_tx_dat_bits_dataCheck(io_out_tx_dat_bits_dataCheck),
    .io_out_rx_rsp_ready(io_out_rx_rsp_ready),
    .io_out_rx_rsp_valid(io_out_rx_rsp_valid),
    .io_out_rx_rsp_bits_srcID(io_out_rx_rsp_bits_srcID),
    .io_out_rx_rsp_bits_txnID(io_out_rx_rsp_bits_txnID),
    .io_out_rx_rsp_bits_opcode(io_out_rx_rsp_bits_opcode),
    .io_out_rx_rsp_bits_dbID(io_out_rx_rsp_bits_dbID),
    .io_out_rx_dat_ready(io_out_rx_dat_ready),
    .io_out_rx_dat_valid(io_out_rx_dat_valid),
    .io_out_rx_dat_bits_srcID(io_out_rx_dat_bits_srcID),
    .io_out_rx_dat_bits_txnID(io_out_rx_dat_bits_txnID),
    .io_out_rx_dat_bits_opcode(io_out_rx_dat_bits_opcode),
    .io_out_rx_dat_bits_resp(io_out_rx_dat_bits_resp),
    .io_out_rx_dat_bits_dataID(io_out_rx_dat_bits_dataID),
    .io_out_rx_dat_bits_data(io_out_rx_dat_bits_data)
  );
endmodule
