// ============================================================================
// AtomicsUnit_wrapper —— golden 同名顶层 `AtomicsUnit`(扁平端口 ↔ xs_AtomicsUnit_core)
// 端口与 golden/chisel-rtl/AtomicsUnit.sv 逐位一致。内部实例化可读手写核。
// 子模块 DummyDPICWrapper_50 由核实例化, 两侧 elaborate 同一 golden 定义。
// ============================================================================
module AtomicsUnit(
  input clock,
  input reset,
  input [5:0] io_hartId,
  output io_in_ready,
  input io_in_valid,
  input [8:0] io_in_bits_uop_fuOpType,
  input io_in_bits_uop_rfWen,
  input [7:0] io_in_bits_uop_pdest,
  input io_in_bits_uop_robIdx_flag,
  input [7:0] io_in_bits_uop_robIdx_value,
  input [63:0] io_in_bits_uop_debugInfo_enqRsTime,
  input [63:0] io_in_bits_uop_debugInfo_selectTime,
  input [63:0] io_in_bits_uop_debugInfo_issueTime,
  input io_in_bits_uop_sqIdx_flag,
  input [5:0] io_in_bits_uop_sqIdx_value,
  input [63:0] io_in_bits_src_0,
  input io_storeDataIn_0_valid,
  input [8:0] io_storeDataIn_0_bits_uop_fuOpType,
  input [63:0] io_storeDataIn_0_bits_data,
  input io_storeDataIn_1_valid,
  input [8:0] io_storeDataIn_1_bits_uop_fuOpType,
  input [63:0] io_storeDataIn_1_bits_data,
  output io_out_valid,
  output io_out_bits_uop_exceptionVec_3,
  output io_out_bits_uop_exceptionVec_4,
  output io_out_bits_uop_exceptionVec_5,
  output io_out_bits_uop_exceptionVec_6,
  output io_out_bits_uop_exceptionVec_7,
  output io_out_bits_uop_exceptionVec_13,
  output io_out_bits_uop_exceptionVec_15,
  output io_out_bits_uop_exceptionVec_21,
  output io_out_bits_uop_exceptionVec_23,
  output [3:0] io_out_bits_uop_trigger,
  output io_out_bits_uop_rfWen,
  output [7:0] io_out_bits_uop_pdest,
  output io_out_bits_uop_robIdx_flag,
  output [7:0] io_out_bits_uop_robIdx_value,
  output [63:0] io_out_bits_uop_debugInfo_enqRsTime,
  output [63:0] io_out_bits_uop_debugInfo_selectTime,
  output [63:0] io_out_bits_uop_debugInfo_issueTime,
  output [63:0] io_out_bits_data,
  output io_out_bits_debug_isMMIO,
  input io_dcache_req_ready,
  output io_dcache_req_valid,
  output [4:0] io_dcache_req_bits_cmd,
  output [49:0] io_dcache_req_bits_vaddr,
  output [47:0] io_dcache_req_bits_addr,
  output [2:0] io_dcache_req_bits_word_idx,
  output [127:0] io_dcache_req_bits_amo_data,
  output [15:0] io_dcache_req_bits_amo_mask,
  output [127:0] io_dcache_req_bits_amo_cmp,
  input io_dcache_resp_valid,
  input [127:0] io_dcache_resp_bits_data,
  input io_dcache_resp_bits_miss,
  input io_dcache_resp_bits_replay,
  input io_dcache_resp_bits_error,
  input [5:0] io_dcache_resp_bits_id,
  input io_dcache_block_lr,
  output io_dtlb_req_valid,
  output [49:0] io_dtlb_req_bits_vaddr,
  output [63:0] io_dtlb_req_bits_fullva,
  output [2:0] io_dtlb_req_bits_cmd,
  output io_dtlb_req_bits_debug_robIdx_flag,
  output [7:0] io_dtlb_req_bits_debug_robIdx_value,
  input io_dtlb_resp_valid,
  input [47:0] io_dtlb_resp_bits_paddr_0,
  input [63:0] io_dtlb_resp_bits_gpaddr_0,
  input [63:0] io_dtlb_resp_bits_fullva,
  input [1:0] io_dtlb_resp_bits_pbmt_0,
  input io_dtlb_resp_bits_miss,
  input io_dtlb_resp_bits_isForVSnonLeafPTE,
  input io_dtlb_resp_bits_excp_0_gpf_ld,
  input io_dtlb_resp_bits_excp_0_gpf_st,
  input io_dtlb_resp_bits_excp_0_pf_ld,
  input io_dtlb_resp_bits_excp_0_pf_st,
  input io_dtlb_resp_bits_excp_0_af_ld,
  input io_dtlb_resp_bits_excp_0_af_st,
  input io_pmpResp_ld,
  input io_pmpResp_st,
  input io_pmpResp_mmio,
  output io_flush_sbuffer_valid,
  input io_flush_sbuffer_empty,
  output io_feedbackSlow_valid,
  output io_feedbackSlow_bits_sqIdx_flag,
  output [5:0] io_feedbackSlow_bits_sqIdx_value,
  input io_redirect_valid,
  output io_exceptionInfo_valid,
  output [63:0] io_exceptionInfo_bits_vaddr,
  output [63:0] io_exceptionInfo_bits_gpaddr,
  output io_exceptionInfo_bits_isForVSnonLeafPTE,
  input io_csrCtrl_cache_error_enable,
  input io_csrCtrl_mem_trigger_tUpdate_valid,
  input [1:0] io_csrCtrl_mem_trigger_tUpdate_bits_addr,
  input [1:0] io_csrCtrl_mem_trigger_tUpdate_bits_tdata_matchType,
  input io_csrCtrl_mem_trigger_tUpdate_bits_tdata_select,
  input [3:0] io_csrCtrl_mem_trigger_tUpdate_bits_tdata_action,
  input io_csrCtrl_mem_trigger_tUpdate_bits_tdata_chain,
  input io_csrCtrl_mem_trigger_tUpdate_bits_tdata_store,
  input io_csrCtrl_mem_trigger_tUpdate_bits_tdata_load,
  input [63:0] io_csrCtrl_mem_trigger_tUpdate_bits_tdata_tdata2,
  input io_csrCtrl_mem_trigger_tEnableVec_0,
  input io_csrCtrl_mem_trigger_tEnableVec_1,
  input io_csrCtrl_mem_trigger_tEnableVec_2,
  input io_csrCtrl_mem_trigger_tEnableVec_3,
  input io_csrCtrl_mem_trigger_debugMode,
  input io_csrCtrl_mem_trigger_triggerCanRaiseBpExp
);
  xs_AtomicsUnit_core u_core (
    .clock(clock),
    .reset(reset),
    .io_hartId(io_hartId),
    .io_in_ready(io_in_ready),
    .io_in_valid(io_in_valid),
    .io_in_bits_uop_fuOpType(io_in_bits_uop_fuOpType),
    .io_in_bits_uop_rfWen(io_in_bits_uop_rfWen),
    .io_in_bits_uop_pdest(io_in_bits_uop_pdest),
    .io_in_bits_uop_robIdx_flag(io_in_bits_uop_robIdx_flag),
    .io_in_bits_uop_robIdx_value(io_in_bits_uop_robIdx_value),
    .io_in_bits_uop_debugInfo_enqRsTime(io_in_bits_uop_debugInfo_enqRsTime),
    .io_in_bits_uop_debugInfo_selectTime(io_in_bits_uop_debugInfo_selectTime),
    .io_in_bits_uop_debugInfo_issueTime(io_in_bits_uop_debugInfo_issueTime),
    .io_in_bits_uop_sqIdx_flag(io_in_bits_uop_sqIdx_flag),
    .io_in_bits_uop_sqIdx_value(io_in_bits_uop_sqIdx_value),
    .io_in_bits_src_0(io_in_bits_src_0),
    .io_storeDataIn_0_valid(io_storeDataIn_0_valid),
    .io_storeDataIn_0_bits_uop_fuOpType(io_storeDataIn_0_bits_uop_fuOpType),
    .io_storeDataIn_0_bits_data(io_storeDataIn_0_bits_data),
    .io_storeDataIn_1_valid(io_storeDataIn_1_valid),
    .io_storeDataIn_1_bits_uop_fuOpType(io_storeDataIn_1_bits_uop_fuOpType),
    .io_storeDataIn_1_bits_data(io_storeDataIn_1_bits_data),
    .io_out_valid(io_out_valid),
    .io_out_bits_uop_exceptionVec_3(io_out_bits_uop_exceptionVec_3),
    .io_out_bits_uop_exceptionVec_4(io_out_bits_uop_exceptionVec_4),
    .io_out_bits_uop_exceptionVec_5(io_out_bits_uop_exceptionVec_5),
    .io_out_bits_uop_exceptionVec_6(io_out_bits_uop_exceptionVec_6),
    .io_out_bits_uop_exceptionVec_7(io_out_bits_uop_exceptionVec_7),
    .io_out_bits_uop_exceptionVec_13(io_out_bits_uop_exceptionVec_13),
    .io_out_bits_uop_exceptionVec_15(io_out_bits_uop_exceptionVec_15),
    .io_out_bits_uop_exceptionVec_21(io_out_bits_uop_exceptionVec_21),
    .io_out_bits_uop_exceptionVec_23(io_out_bits_uop_exceptionVec_23),
    .io_out_bits_uop_trigger(io_out_bits_uop_trigger),
    .io_out_bits_uop_rfWen(io_out_bits_uop_rfWen),
    .io_out_bits_uop_pdest(io_out_bits_uop_pdest),
    .io_out_bits_uop_robIdx_flag(io_out_bits_uop_robIdx_flag),
    .io_out_bits_uop_robIdx_value(io_out_bits_uop_robIdx_value),
    .io_out_bits_uop_debugInfo_enqRsTime(io_out_bits_uop_debugInfo_enqRsTime),
    .io_out_bits_uop_debugInfo_selectTime(io_out_bits_uop_debugInfo_selectTime),
    .io_out_bits_uop_debugInfo_issueTime(io_out_bits_uop_debugInfo_issueTime),
    .io_out_bits_data(io_out_bits_data),
    .io_out_bits_debug_isMMIO(io_out_bits_debug_isMMIO),
    .io_dcache_req_ready(io_dcache_req_ready),
    .io_dcache_req_valid(io_dcache_req_valid),
    .io_dcache_req_bits_cmd(io_dcache_req_bits_cmd),
    .io_dcache_req_bits_vaddr(io_dcache_req_bits_vaddr),
    .io_dcache_req_bits_addr(io_dcache_req_bits_addr),
    .io_dcache_req_bits_word_idx(io_dcache_req_bits_word_idx),
    .io_dcache_req_bits_amo_data(io_dcache_req_bits_amo_data),
    .io_dcache_req_bits_amo_mask(io_dcache_req_bits_amo_mask),
    .io_dcache_req_bits_amo_cmp(io_dcache_req_bits_amo_cmp),
    .io_dcache_resp_valid(io_dcache_resp_valid),
    .io_dcache_resp_bits_data(io_dcache_resp_bits_data),
    .io_dcache_resp_bits_miss(io_dcache_resp_bits_miss),
    .io_dcache_resp_bits_replay(io_dcache_resp_bits_replay),
    .io_dcache_resp_bits_error(io_dcache_resp_bits_error),
    .io_dcache_resp_bits_id(io_dcache_resp_bits_id),
    .io_dcache_block_lr(io_dcache_block_lr),
    .io_dtlb_req_valid(io_dtlb_req_valid),
    .io_dtlb_req_bits_vaddr(io_dtlb_req_bits_vaddr),
    .io_dtlb_req_bits_fullva(io_dtlb_req_bits_fullva),
    .io_dtlb_req_bits_cmd(io_dtlb_req_bits_cmd),
    .io_dtlb_req_bits_debug_robIdx_flag(io_dtlb_req_bits_debug_robIdx_flag),
    .io_dtlb_req_bits_debug_robIdx_value(io_dtlb_req_bits_debug_robIdx_value),
    .io_dtlb_resp_valid(io_dtlb_resp_valid),
    .io_dtlb_resp_bits_paddr_0(io_dtlb_resp_bits_paddr_0),
    .io_dtlb_resp_bits_gpaddr_0(io_dtlb_resp_bits_gpaddr_0),
    .io_dtlb_resp_bits_fullva(io_dtlb_resp_bits_fullva),
    .io_dtlb_resp_bits_pbmt_0(io_dtlb_resp_bits_pbmt_0),
    .io_dtlb_resp_bits_miss(io_dtlb_resp_bits_miss),
    .io_dtlb_resp_bits_isForVSnonLeafPTE(io_dtlb_resp_bits_isForVSnonLeafPTE),
    .io_dtlb_resp_bits_excp_0_gpf_ld(io_dtlb_resp_bits_excp_0_gpf_ld),
    .io_dtlb_resp_bits_excp_0_gpf_st(io_dtlb_resp_bits_excp_0_gpf_st),
    .io_dtlb_resp_bits_excp_0_pf_ld(io_dtlb_resp_bits_excp_0_pf_ld),
    .io_dtlb_resp_bits_excp_0_pf_st(io_dtlb_resp_bits_excp_0_pf_st),
    .io_dtlb_resp_bits_excp_0_af_ld(io_dtlb_resp_bits_excp_0_af_ld),
    .io_dtlb_resp_bits_excp_0_af_st(io_dtlb_resp_bits_excp_0_af_st),
    .io_pmpResp_ld(io_pmpResp_ld),
    .io_pmpResp_st(io_pmpResp_st),
    .io_pmpResp_mmio(io_pmpResp_mmio),
    .io_flush_sbuffer_valid(io_flush_sbuffer_valid),
    .io_flush_sbuffer_empty(io_flush_sbuffer_empty),
    .io_feedbackSlow_valid(io_feedbackSlow_valid),
    .io_feedbackSlow_bits_sqIdx_flag(io_feedbackSlow_bits_sqIdx_flag),
    .io_feedbackSlow_bits_sqIdx_value(io_feedbackSlow_bits_sqIdx_value),
    .io_redirect_valid(io_redirect_valid),
    .io_exceptionInfo_valid(io_exceptionInfo_valid),
    .io_exceptionInfo_bits_vaddr(io_exceptionInfo_bits_vaddr),
    .io_exceptionInfo_bits_gpaddr(io_exceptionInfo_bits_gpaddr),
    .io_exceptionInfo_bits_isForVSnonLeafPTE(io_exceptionInfo_bits_isForVSnonLeafPTE),
    .io_csrCtrl_cache_error_enable(io_csrCtrl_cache_error_enable),
    .io_csrCtrl_mem_trigger_tUpdate_valid(io_csrCtrl_mem_trigger_tUpdate_valid),
    .io_csrCtrl_mem_trigger_tUpdate_bits_addr(io_csrCtrl_mem_trigger_tUpdate_bits_addr),
    .io_csrCtrl_mem_trigger_tUpdate_bits_tdata_matchType(io_csrCtrl_mem_trigger_tUpdate_bits_tdata_matchType),
    .io_csrCtrl_mem_trigger_tUpdate_bits_tdata_select(io_csrCtrl_mem_trigger_tUpdate_bits_tdata_select),
    .io_csrCtrl_mem_trigger_tUpdate_bits_tdata_action(io_csrCtrl_mem_trigger_tUpdate_bits_tdata_action),
    .io_csrCtrl_mem_trigger_tUpdate_bits_tdata_chain(io_csrCtrl_mem_trigger_tUpdate_bits_tdata_chain),
    .io_csrCtrl_mem_trigger_tUpdate_bits_tdata_store(io_csrCtrl_mem_trigger_tUpdate_bits_tdata_store),
    .io_csrCtrl_mem_trigger_tUpdate_bits_tdata_load(io_csrCtrl_mem_trigger_tUpdate_bits_tdata_load),
    .io_csrCtrl_mem_trigger_tUpdate_bits_tdata_tdata2(io_csrCtrl_mem_trigger_tUpdate_bits_tdata_tdata2),
    .io_csrCtrl_mem_trigger_tEnableVec_0(io_csrCtrl_mem_trigger_tEnableVec_0),
    .io_csrCtrl_mem_trigger_tEnableVec_1(io_csrCtrl_mem_trigger_tEnableVec_1),
    .io_csrCtrl_mem_trigger_tEnableVec_2(io_csrCtrl_mem_trigger_tEnableVec_2),
    .io_csrCtrl_mem_trigger_tEnableVec_3(io_csrCtrl_mem_trigger_tEnableVec_3),
    .io_csrCtrl_mem_trigger_debugMode(io_csrCtrl_mem_trigger_debugMode),
    .io_csrCtrl_mem_trigger_triggerCanRaiseBpExp(io_csrCtrl_mem_trigger_triggerCanRaiseBpExp)
  );
endmodule
