// 自动生成：scripts/gen_dcache.py —— 勿手改

// DCache 子模块黑盒 stub（UT/FM 两侧共用，统一黑盒边界）。

module CtrlUnit(

  input         clock,
  input         reset,
  output        auto_in_a_ready,
  input         auto_in_a_valid,
  input  [3:0]  auto_in_a_bits_opcode,
  input  [1:0]  auto_in_a_bits_size,
  input  [1:0]  auto_in_a_bits_source,
  input  [29:0] auto_in_a_bits_address,
  input  [7:0]  auto_in_a_bits_mask,
  input  [63:0] auto_in_a_bits_data,
  input         auto_in_d_ready,
  output        auto_in_d_valid,
  output [3:0]  auto_in_d_bits_opcode,
  output [1:0]  auto_in_d_bits_size,
  output [1:0]  auto_in_d_bits_source,
  output [63:0] auto_in_d_bits_data,
  input         io_pseudoError_0_ready,
  output        io_pseudoError_0_valid,
  output        io_pseudoError_0_bits_0_valid,
  output [63:0] io_pseudoError_0_bits_0_mask,
  input         io_pseudoError_1_ready,
  output        io_pseudoError_1_valid,
  output        io_pseudoError_1_bits_0_valid,
  output [63:0] io_pseudoError_1_bits_0_mask,
  output        io_pseudoError_1_bits_1_valid,
  output [63:0] io_pseudoError_1_bits_1_mask,
  output        io_pseudoError_1_bits_2_valid,
  output [63:0] io_pseudoError_1_bits_2_mask,
  output        io_pseudoError_1_bits_3_valid,
  output [63:0] io_pseudoError_1_bits_3_mask,
  output        io_pseudoError_1_bits_4_valid,
  output [63:0] io_pseudoError_1_bits_4_mask,
  output        io_pseudoError_1_bits_5_valid,
  output [63:0] io_pseudoError_1_bits_5_mask,
  output        io_pseudoError_1_bits_6_valid,
  output [63:0] io_pseudoError_1_bits_6_mask,
  output        io_pseudoError_1_bits_7_valid,
  output [63:0] io_pseudoError_1_bits_7_mask
);
endmodule

module BankedDataArray(

  input         clock,
  input         reset,
  output        io_read_0_ready,
  input         io_read_0_valid,
  input  [3:0]  io_read_0_bits_way_en,
  input  [47:0] io_read_0_bits_addr,
  input  [47:0] io_read_0_bits_addr_dup,
  input  [7:0]  io_read_0_bits_bankMask,
  input         io_read_0_bits_lqIdx_flag,
  input  [6:0]  io_read_0_bits_lqIdx_value,
  output        io_read_1_ready,
  input         io_read_1_valid,
  input  [3:0]  io_read_1_bits_way_en,
  input  [47:0] io_read_1_bits_addr,
  input  [47:0] io_read_1_bits_addr_dup,
  input  [7:0]  io_read_1_bits_bankMask,
  input         io_read_1_bits_lqIdx_flag,
  input  [6:0]  io_read_1_bits_lqIdx_value,
  output        io_read_2_ready,
  input         io_read_2_valid,
  input  [3:0]  io_read_2_bits_way_en,
  input  [47:0] io_read_2_bits_addr,
  input  [47:0] io_read_2_bits_addr_dup,
  input  [7:0]  io_read_2_bits_bankMask,
  input         io_read_2_bits_lqIdx_flag,
  input  [6:0]  io_read_2_bits_lqIdx_value,
  input         io_is128Req_0,
  input         io_is128Req_1,
  input         io_is128Req_2,
  input         io_readline_intend,
  output        io_readline_ready,
  input         io_readline_valid,
  input  [3:0]  io_readline_bits_way_en,
  input  [47:0] io_readline_bits_addr,
  input  [7:0]  io_readline_bits_rmask,
  input         io_readline_can_go,
  input         io_readline_stall,
  input         io_readline_can_resp,
  input         io_write_valid,
  input  [7:0]  io_write_bits_wmask,
  input  [63:0] io_write_bits_data_0,
  input  [63:0] io_write_bits_data_1,
  input  [63:0] io_write_bits_data_2,
  input  [63:0] io_write_bits_data_3,
  input  [63:0] io_write_bits_data_4,
  input  [63:0] io_write_bits_data_5,
  input  [63:0] io_write_bits_data_6,
  input  [63:0] io_write_bits_data_7,
  input         io_write_dup_0_valid,
  input  [3:0]  io_write_dup_0_bits_way_en,
  input  [47:0] io_write_dup_0_bits_addr,
  input         io_write_dup_1_valid,
  input  [3:0]  io_write_dup_1_bits_way_en,
  input  [47:0] io_write_dup_1_bits_addr,
  input         io_write_dup_2_valid,
  input  [3:0]  io_write_dup_2_bits_way_en,
  input  [47:0] io_write_dup_2_bits_addr,
  input         io_write_dup_3_valid,
  input  [3:0]  io_write_dup_3_bits_way_en,
  input  [47:0] io_write_dup_3_bits_addr,
  input         io_write_dup_4_valid,
  input  [3:0]  io_write_dup_4_bits_way_en,
  input  [47:0] io_write_dup_4_bits_addr,
  input         io_write_dup_5_valid,
  input  [3:0]  io_write_dup_5_bits_way_en,
  input  [47:0] io_write_dup_5_bits_addr,
  input         io_write_dup_6_valid,
  input  [3:0]  io_write_dup_6_bits_way_en,
  input  [47:0] io_write_dup_6_bits_addr,
  input         io_write_dup_7_valid,
  input  [3:0]  io_write_dup_7_bits_way_en,
  input  [47:0] io_write_dup_7_bits_addr,
  output [63:0] io_readline_resp_0_raw_data,
  output [63:0] io_readline_resp_1_raw_data,
  output [63:0] io_readline_resp_2_raw_data,
  output [63:0] io_readline_resp_3_raw_data,
  output [63:0] io_readline_resp_4_raw_data,
  output [63:0] io_readline_resp_5_raw_data,
  output [63:0] io_readline_resp_6_raw_data,
  output [63:0] io_readline_resp_7_raw_data,
  output        io_readline_error,
  output        io_readline_error_delayed,
  output [63:0] io_read_resp_0_0_raw_data,
  output [63:0] io_read_resp_0_1_raw_data,
  output [63:0] io_read_resp_1_0_raw_data,
  output [63:0] io_read_resp_1_1_raw_data,
  output [63:0] io_read_resp_2_0_raw_data,
  output [63:0] io_read_resp_2_1_raw_data,
  output        io_read_error_delayed_0_0,
  output        io_read_error_delayed_0_1,
  output        io_read_error_delayed_1_0,
  output        io_read_error_delayed_1_1,
  output        io_read_error_delayed_2_0,
  output        io_read_error_delayed_2_1,
  output        io_bank_conflict_slow_0,
  output        io_bank_conflict_slow_1,
  output        io_bank_conflict_slow_2,
  output        io_disable_ld_fast_wakeup_0,
  output        io_disable_ld_fast_wakeup_1,
  output        io_disable_ld_fast_wakeup_2,
  output        io_pseudo_error_ready,
  input         io_pseudo_error_valid,
  input         io_pseudo_error_bits_0_valid,
  input  [63:0] io_pseudo_error_bits_0_mask,
  input         io_pseudo_error_bits_1_valid,
  input  [63:0] io_pseudo_error_bits_1_mask,
  input         io_pseudo_error_bits_2_valid,
  input  [63:0] io_pseudo_error_bits_2_mask,
  input         io_pseudo_error_bits_3_valid,
  input  [63:0] io_pseudo_error_bits_3_mask,
  input         io_pseudo_error_bits_4_valid,
  input  [63:0] io_pseudo_error_bits_4_mask,
  input         io_pseudo_error_bits_5_valid,
  input  [63:0] io_pseudo_error_bits_5_mask,
  input         io_pseudo_error_bits_6_valid,
  input  [63:0] io_pseudo_error_bits_6_mask,
  input         io_pseudo_error_bits_7_valid,
  input  [63:0] io_pseudo_error_bits_7_mask,
  input  [4:0]  boreChildrenBd_bore_array,
  input         boreChildrenBd_bore_all,
  input         boreChildrenBd_bore_req,
  output        boreChildrenBd_bore_ack,
  input         boreChildrenBd_bore_writeen,
  input         boreChildrenBd_bore_be,
  input  [8:0]  boreChildrenBd_bore_addr,
  input  [71:0] boreChildrenBd_bore_indata,
  input         boreChildrenBd_bore_readen,
  input  [8:0]  boreChildrenBd_bore_addr_rd,
  output [71:0] boreChildrenBd_bore_outdata,
  input         sigFromSrams_bore_ram_hold,
  input         sigFromSrams_bore_ram_bypass,
  input         sigFromSrams_bore_ram_bp_clken,
  input         sigFromSrams_bore_ram_aux_clk,
  input         sigFromSrams_bore_ram_aux_ckbp,
  input         sigFromSrams_bore_ram_mcp_hold,
  input         sigFromSrams_bore_cgen,
  input         sigFromSrams_bore_1_ram_hold,
  input         sigFromSrams_bore_1_ram_bypass,
  input         sigFromSrams_bore_1_ram_bp_clken,
  input         sigFromSrams_bore_1_ram_aux_clk,
  input         sigFromSrams_bore_1_ram_aux_ckbp,
  input         sigFromSrams_bore_1_ram_mcp_hold,
  input         sigFromSrams_bore_1_cgen,
  input         sigFromSrams_bore_2_ram_hold,
  input         sigFromSrams_bore_2_ram_bypass,
  input         sigFromSrams_bore_2_ram_bp_clken,
  input         sigFromSrams_bore_2_ram_aux_clk,
  input         sigFromSrams_bore_2_ram_aux_ckbp,
  input         sigFromSrams_bore_2_ram_mcp_hold,
  input         sigFromSrams_bore_2_cgen,
  input         sigFromSrams_bore_3_ram_hold,
  input         sigFromSrams_bore_3_ram_bypass,
  input         sigFromSrams_bore_3_ram_bp_clken,
  input         sigFromSrams_bore_3_ram_aux_clk,
  input         sigFromSrams_bore_3_ram_aux_ckbp,
  input         sigFromSrams_bore_3_ram_mcp_hold,
  input         sigFromSrams_bore_3_cgen,
  input         sigFromSrams_bore_4_ram_hold,
  input         sigFromSrams_bore_4_ram_bypass,
  input         sigFromSrams_bore_4_ram_bp_clken,
  input         sigFromSrams_bore_4_ram_aux_clk,
  input         sigFromSrams_bore_4_ram_aux_ckbp,
  input         sigFromSrams_bore_4_ram_mcp_hold,
  input         sigFromSrams_bore_4_cgen,
  input         sigFromSrams_bore_5_ram_hold,
  input         sigFromSrams_bore_5_ram_bypass,
  input         sigFromSrams_bore_5_ram_bp_clken,
  input         sigFromSrams_bore_5_ram_aux_clk,
  input         sigFromSrams_bore_5_ram_aux_ckbp,
  input         sigFromSrams_bore_5_ram_mcp_hold,
  input         sigFromSrams_bore_5_cgen,
  input         sigFromSrams_bore_6_ram_hold,
  input         sigFromSrams_bore_6_ram_bypass,
  input         sigFromSrams_bore_6_ram_bp_clken,
  input         sigFromSrams_bore_6_ram_aux_clk,
  input         sigFromSrams_bore_6_ram_aux_ckbp,
  input         sigFromSrams_bore_6_ram_mcp_hold,
  input         sigFromSrams_bore_6_cgen,
  input         sigFromSrams_bore_7_ram_hold,
  input         sigFromSrams_bore_7_ram_bypass,
  input         sigFromSrams_bore_7_ram_bp_clken,
  input         sigFromSrams_bore_7_ram_aux_clk,
  input         sigFromSrams_bore_7_ram_aux_ckbp,
  input         sigFromSrams_bore_7_ram_mcp_hold,
  input         sigFromSrams_bore_7_cgen,
  input         sigFromSrams_bore_8_ram_hold,
  input         sigFromSrams_bore_8_ram_bypass,
  input         sigFromSrams_bore_8_ram_bp_clken,
  input         sigFromSrams_bore_8_ram_aux_clk,
  input         sigFromSrams_bore_8_ram_aux_ckbp,
  input         sigFromSrams_bore_8_ram_mcp_hold,
  input         sigFromSrams_bore_8_cgen,
  input         sigFromSrams_bore_9_ram_hold,
  input         sigFromSrams_bore_9_ram_bypass,
  input         sigFromSrams_bore_9_ram_bp_clken,
  input         sigFromSrams_bore_9_ram_aux_clk,
  input         sigFromSrams_bore_9_ram_aux_ckbp,
  input         sigFromSrams_bore_9_ram_mcp_hold,
  input         sigFromSrams_bore_9_cgen,
  input         sigFromSrams_bore_10_ram_hold,
  input         sigFromSrams_bore_10_ram_bypass,
  input         sigFromSrams_bore_10_ram_bp_clken,
  input         sigFromSrams_bore_10_ram_aux_clk,
  input         sigFromSrams_bore_10_ram_aux_ckbp,
  input         sigFromSrams_bore_10_ram_mcp_hold,
  input         sigFromSrams_bore_10_cgen,
  input         sigFromSrams_bore_11_ram_hold,
  input         sigFromSrams_bore_11_ram_bypass,
  input         sigFromSrams_bore_11_ram_bp_clken,
  input         sigFromSrams_bore_11_ram_aux_clk,
  input         sigFromSrams_bore_11_ram_aux_ckbp,
  input         sigFromSrams_bore_11_ram_mcp_hold,
  input         sigFromSrams_bore_11_cgen,
  input         sigFromSrams_bore_12_ram_hold,
  input         sigFromSrams_bore_12_ram_bypass,
  input         sigFromSrams_bore_12_ram_bp_clken,
  input         sigFromSrams_bore_12_ram_aux_clk,
  input         sigFromSrams_bore_12_ram_aux_ckbp,
  input         sigFromSrams_bore_12_ram_mcp_hold,
  input         sigFromSrams_bore_12_cgen,
  input         sigFromSrams_bore_13_ram_hold,
  input         sigFromSrams_bore_13_ram_bypass,
  input         sigFromSrams_bore_13_ram_bp_clken,
  input         sigFromSrams_bore_13_ram_aux_clk,
  input         sigFromSrams_bore_13_ram_aux_ckbp,
  input         sigFromSrams_bore_13_ram_mcp_hold,
  input         sigFromSrams_bore_13_cgen,
  input         sigFromSrams_bore_14_ram_hold,
  input         sigFromSrams_bore_14_ram_bypass,
  input         sigFromSrams_bore_14_ram_bp_clken,
  input         sigFromSrams_bore_14_ram_aux_clk,
  input         sigFromSrams_bore_14_ram_aux_ckbp,
  input         sigFromSrams_bore_14_ram_mcp_hold,
  input         sigFromSrams_bore_14_cgen,
  input         sigFromSrams_bore_15_ram_hold,
  input         sigFromSrams_bore_15_ram_bypass,
  input         sigFromSrams_bore_15_ram_bp_clken,
  input         sigFromSrams_bore_15_ram_aux_clk,
  input         sigFromSrams_bore_15_ram_aux_ckbp,
  input         sigFromSrams_bore_15_ram_mcp_hold,
  input         sigFromSrams_bore_15_cgen,
  input         sigFromSrams_bore_16_ram_hold,
  input         sigFromSrams_bore_16_ram_bypass,
  input         sigFromSrams_bore_16_ram_bp_clken,
  input         sigFromSrams_bore_16_ram_aux_clk,
  input         sigFromSrams_bore_16_ram_aux_ckbp,
  input         sigFromSrams_bore_16_ram_mcp_hold,
  input         sigFromSrams_bore_16_cgen,
  input         sigFromSrams_bore_17_ram_hold,
  input         sigFromSrams_bore_17_ram_bypass,
  input         sigFromSrams_bore_17_ram_bp_clken,
  input         sigFromSrams_bore_17_ram_aux_clk,
  input         sigFromSrams_bore_17_ram_aux_ckbp,
  input         sigFromSrams_bore_17_ram_mcp_hold,
  input         sigFromSrams_bore_17_cgen,
  input         sigFromSrams_bore_18_ram_hold,
  input         sigFromSrams_bore_18_ram_bypass,
  input         sigFromSrams_bore_18_ram_bp_clken,
  input         sigFromSrams_bore_18_ram_aux_clk,
  input         sigFromSrams_bore_18_ram_aux_ckbp,
  input         sigFromSrams_bore_18_ram_mcp_hold,
  input         sigFromSrams_bore_18_cgen,
  input         sigFromSrams_bore_19_ram_hold,
  input         sigFromSrams_bore_19_ram_bypass,
  input         sigFromSrams_bore_19_ram_bp_clken,
  input         sigFromSrams_bore_19_ram_aux_clk,
  input         sigFromSrams_bore_19_ram_aux_ckbp,
  input         sigFromSrams_bore_19_ram_mcp_hold,
  input         sigFromSrams_bore_19_cgen,
  input         sigFromSrams_bore_20_ram_hold,
  input         sigFromSrams_bore_20_ram_bypass,
  input         sigFromSrams_bore_20_ram_bp_clken,
  input         sigFromSrams_bore_20_ram_aux_clk,
  input         sigFromSrams_bore_20_ram_aux_ckbp,
  input         sigFromSrams_bore_20_ram_mcp_hold,
  input         sigFromSrams_bore_20_cgen,
  input         sigFromSrams_bore_21_ram_hold,
  input         sigFromSrams_bore_21_ram_bypass,
  input         sigFromSrams_bore_21_ram_bp_clken,
  input         sigFromSrams_bore_21_ram_aux_clk,
  input         sigFromSrams_bore_21_ram_aux_ckbp,
  input         sigFromSrams_bore_21_ram_mcp_hold,
  input         sigFromSrams_bore_21_cgen,
  input         sigFromSrams_bore_22_ram_hold,
  input         sigFromSrams_bore_22_ram_bypass,
  input         sigFromSrams_bore_22_ram_bp_clken,
  input         sigFromSrams_bore_22_ram_aux_clk,
  input         sigFromSrams_bore_22_ram_aux_ckbp,
  input         sigFromSrams_bore_22_ram_mcp_hold,
  input         sigFromSrams_bore_22_cgen,
  input         sigFromSrams_bore_23_ram_hold,
  input         sigFromSrams_bore_23_ram_bypass,
  input         sigFromSrams_bore_23_ram_bp_clken,
  input         sigFromSrams_bore_23_ram_aux_clk,
  input         sigFromSrams_bore_23_ram_aux_ckbp,
  input         sigFromSrams_bore_23_ram_mcp_hold,
  input         sigFromSrams_bore_23_cgen,
  input         sigFromSrams_bore_24_ram_hold,
  input         sigFromSrams_bore_24_ram_bypass,
  input         sigFromSrams_bore_24_ram_bp_clken,
  input         sigFromSrams_bore_24_ram_aux_clk,
  input         sigFromSrams_bore_24_ram_aux_ckbp,
  input         sigFromSrams_bore_24_ram_mcp_hold,
  input         sigFromSrams_bore_24_cgen,
  input         sigFromSrams_bore_25_ram_hold,
  input         sigFromSrams_bore_25_ram_bypass,
  input         sigFromSrams_bore_25_ram_bp_clken,
  input         sigFromSrams_bore_25_ram_aux_clk,
  input         sigFromSrams_bore_25_ram_aux_ckbp,
  input         sigFromSrams_bore_25_ram_mcp_hold,
  input         sigFromSrams_bore_25_cgen,
  input         sigFromSrams_bore_26_ram_hold,
  input         sigFromSrams_bore_26_ram_bypass,
  input         sigFromSrams_bore_26_ram_bp_clken,
  input         sigFromSrams_bore_26_ram_aux_clk,
  input         sigFromSrams_bore_26_ram_aux_ckbp,
  input         sigFromSrams_bore_26_ram_mcp_hold,
  input         sigFromSrams_bore_26_cgen,
  input         sigFromSrams_bore_27_ram_hold,
  input         sigFromSrams_bore_27_ram_bypass,
  input         sigFromSrams_bore_27_ram_bp_clken,
  input         sigFromSrams_bore_27_ram_aux_clk,
  input         sigFromSrams_bore_27_ram_aux_ckbp,
  input         sigFromSrams_bore_27_ram_mcp_hold,
  input         sigFromSrams_bore_27_cgen,
  input         sigFromSrams_bore_28_ram_hold,
  input         sigFromSrams_bore_28_ram_bypass,
  input         sigFromSrams_bore_28_ram_bp_clken,
  input         sigFromSrams_bore_28_ram_aux_clk,
  input         sigFromSrams_bore_28_ram_aux_ckbp,
  input         sigFromSrams_bore_28_ram_mcp_hold,
  input         sigFromSrams_bore_28_cgen,
  input         sigFromSrams_bore_29_ram_hold,
  input         sigFromSrams_bore_29_ram_bypass,
  input         sigFromSrams_bore_29_ram_bp_clken,
  input         sigFromSrams_bore_29_ram_aux_clk,
  input         sigFromSrams_bore_29_ram_aux_ckbp,
  input         sigFromSrams_bore_29_ram_mcp_hold,
  input         sigFromSrams_bore_29_cgen,
  input         sigFromSrams_bore_30_ram_hold,
  input         sigFromSrams_bore_30_ram_bypass,
  input         sigFromSrams_bore_30_ram_bp_clken,
  input         sigFromSrams_bore_30_ram_aux_clk,
  input         sigFromSrams_bore_30_ram_aux_ckbp,
  input         sigFromSrams_bore_30_ram_mcp_hold,
  input         sigFromSrams_bore_30_cgen,
  input         sigFromSrams_bore_31_ram_hold,
  input         sigFromSrams_bore_31_ram_bypass,
  input         sigFromSrams_bore_31_ram_bp_clken,
  input         sigFromSrams_bore_31_ram_aux_clk,
  input         sigFromSrams_bore_31_ram_aux_ckbp,
  input         sigFromSrams_bore_31_ram_mcp_hold,
  input         sigFromSrams_bore_31_cgen
);
endmodule

module L1CohMetaArray(

  input        clock,
  input        reset,
  input        io_read_0_valid,
  input  [7:0] io_read_0_bits_idx,
  input        io_read_1_valid,
  input  [7:0] io_read_1_bits_idx,
  input        io_read_2_valid,
  input  [7:0] io_read_2_bits_idx,
  input        io_read_3_valid,
  input  [7:0] io_read_3_bits_idx,
  output [1:0] io_resp_0_0_coh_state,
  output [1:0] io_resp_0_1_coh_state,
  output [1:0] io_resp_0_2_coh_state,
  output [1:0] io_resp_0_3_coh_state,
  output [1:0] io_resp_1_0_coh_state,
  output [1:0] io_resp_1_1_coh_state,
  output [1:0] io_resp_1_2_coh_state,
  output [1:0] io_resp_1_3_coh_state,
  output [1:0] io_resp_2_0_coh_state,
  output [1:0] io_resp_2_1_coh_state,
  output [1:0] io_resp_2_2_coh_state,
  output [1:0] io_resp_2_3_coh_state,
  output [1:0] io_resp_3_0_coh_state,
  output [1:0] io_resp_3_1_coh_state,
  output [1:0] io_resp_3_2_coh_state,
  output [1:0] io_resp_3_3_coh_state,
  input        io_write_0_valid,
  input  [7:0] io_write_0_bits_idx,
  input  [3:0] io_write_0_bits_way_en,
  input  [1:0] io_write_0_bits_meta_coh_state
);
endmodule

module L1FlagMetaArray(

  input        clock,
  input        reset,
  input        io_read_0_valid,
  input  [7:0] io_read_0_bits_idx,
  input        io_read_1_valid,
  input  [7:0] io_read_1_bits_idx,
  input        io_read_2_valid,
  input  [7:0] io_read_2_bits_idx,
  input        io_read_3_valid,
  input  [7:0] io_read_3_bits_idx,
  output       io_resp_0_0,
  output       io_resp_0_1,
  output       io_resp_0_2,
  output       io_resp_0_3,
  output       io_resp_1_0,
  output       io_resp_1_1,
  output       io_resp_1_2,
  output       io_resp_1_3,
  output       io_resp_2_0,
  output       io_resp_2_1,
  output       io_resp_2_2,
  output       io_resp_2_3,
  output       io_resp_3_0,
  output       io_resp_3_1,
  output       io_resp_3_2,
  output       io_resp_3_3,
  input        io_write_0_valid,
  input  [7:0] io_write_0_bits_idx,
  input  [3:0] io_write_0_bits_way_en,
  input        io_write_0_bits_flag
);
endmodule

module L1PrefetchSourceArray(

  input        clock,
  input        reset,
  input        io_read_0_valid,
  input  [7:0] io_read_0_bits_idx,
  input        io_read_1_valid,
  input  [7:0] io_read_1_bits_idx,
  input        io_read_2_valid,
  input  [7:0] io_read_2_bits_idx,
  input        io_read_3_valid,
  input  [7:0] io_read_3_bits_idx,
  input        io_read_4_valid,
  input  [7:0] io_read_4_bits_idx,
  output [2:0] io_resp_0_0,
  output [2:0] io_resp_0_1,
  output [2:0] io_resp_0_2,
  output [2:0] io_resp_0_3,
  output [2:0] io_resp_1_0,
  output [2:0] io_resp_1_1,
  output [2:0] io_resp_1_2,
  output [2:0] io_resp_1_3,
  output [2:0] io_resp_2_0,
  output [2:0] io_resp_2_1,
  output [2:0] io_resp_2_2,
  output [2:0] io_resp_2_3,
  output [2:0] io_resp_3_0,
  output [2:0] io_resp_3_1,
  output [2:0] io_resp_3_2,
  output [2:0] io_resp_3_3,
  output [2:0] io_resp_4_0,
  output [2:0] io_resp_4_1,
  output [2:0] io_resp_4_2,
  output [2:0] io_resp_4_3,
  input        io_write_0_valid,
  input  [7:0] io_write_0_bits_idx,
  input  [3:0] io_write_0_bits_way_en,
  input        io_write_1_valid,
  input  [7:0] io_write_1_bits_idx,
  input  [3:0] io_write_1_bits_way_en,
  input        io_write_2_valid,
  input  [7:0] io_write_2_bits_idx,
  input  [3:0] io_write_2_bits_way_en,
  input        io_write_3_valid,
  input  [7:0] io_write_3_bits_idx,
  input  [3:0] io_write_3_bits_way_en,
  input  [2:0] io_write_3_bits_source
);
endmodule

module L1FlagMetaArray_1(

  input        clock,
  input        reset,
  input        io_read_0_valid,
  input  [7:0] io_read_0_bits_idx,
  input        io_read_1_valid,
  input  [7:0] io_read_1_bits_idx,
  input        io_read_2_valid,
  input  [7:0] io_read_2_bits_idx,
  input        io_read_3_valid,
  input  [7:0] io_read_3_bits_idx,
  input        io_read_4_valid,
  input  [7:0] io_read_4_bits_idx,
  output       io_resp_0_0,
  output       io_resp_0_1,
  output       io_resp_0_2,
  output       io_resp_0_3,
  output       io_resp_1_0,
  output       io_resp_1_1,
  output       io_resp_1_2,
  output       io_resp_1_3,
  output       io_resp_2_0,
  output       io_resp_2_1,
  output       io_resp_2_2,
  output       io_resp_2_3,
  output       io_resp_3_0,
  output       io_resp_3_1,
  output       io_resp_3_2,
  output       io_resp_3_3,
  output       io_resp_4_0,
  output       io_resp_4_1,
  output       io_resp_4_2,
  output       io_resp_4_3,
  input        io_write_0_valid,
  input  [7:0] io_write_0_bits_idx,
  input  [3:0] io_write_0_bits_way_en,
  input        io_write_1_valid,
  input  [7:0] io_write_1_bits_idx,
  input  [3:0] io_write_1_bits_way_en,
  input        io_write_2_valid,
  input  [7:0] io_write_2_bits_idx,
  input  [3:0] io_write_2_bits_way_en,
  input        io_write_3_valid,
  input  [7:0] io_write_3_bits_idx,
  input  [3:0] io_write_3_bits_way_en,
  input        io_write_3_bits_flag
);
endmodule

module DuplicatedTagArray(

  input         clock,
  input         reset,
  input         io_read_0_valid,
  input  [7:0]  io_read_0_bits_idx,
  input         io_read_1_valid,
  input  [7:0]  io_read_1_bits_idx,
  input         io_read_2_valid,
  input  [7:0]  io_read_2_bits_idx,
  output        io_read_3_ready,
  input         io_read_3_valid,
  input  [7:0]  io_read_3_bits_idx,
  output [42:0] io_resp_0_0,
  output [42:0] io_resp_0_1,
  output [42:0] io_resp_0_2,
  output [42:0] io_resp_0_3,
  output [42:0] io_resp_1_0,
  output [42:0] io_resp_1_1,
  output [42:0] io_resp_1_2,
  output [42:0] io_resp_1_3,
  output [42:0] io_resp_2_0,
  output [42:0] io_resp_2_1,
  output [42:0] io_resp_2_2,
  output [42:0] io_resp_2_3,
  output [42:0] io_resp_3_0,
  output [42:0] io_resp_3_1,
  output [42:0] io_resp_3_2,
  output [42:0] io_resp_3_3,
  input         io_write_valid,
  input  [7:0]  io_write_bits_idx,
  input  [3:0]  io_write_bits_way_en,
  input  [35:0] io_write_bits_tag,
  input  [5:0]  boreChildrenBd_bore_array,
  input         boreChildrenBd_bore_all,
  input         boreChildrenBd_bore_req,
  output        boreChildrenBd_bore_ack,
  input         boreChildrenBd_bore_writeen,
  input  [1:0]  boreChildrenBd_bore_be,
  input  [8:0]  boreChildrenBd_bore_addr,
  input  [85:0] boreChildrenBd_bore_indata,
  input         boreChildrenBd_bore_readen,
  input  [8:0]  boreChildrenBd_bore_addr_rd,
  output [85:0] boreChildrenBd_bore_outdata,
  input         sigFromSrams_bore_ram_hold,
  input         sigFromSrams_bore_ram_bypass,
  input         sigFromSrams_bore_ram_bp_clken,
  input         sigFromSrams_bore_ram_aux_clk,
  input         sigFromSrams_bore_ram_aux_ckbp,
  input         sigFromSrams_bore_ram_mcp_hold,
  input         sigFromSrams_bore_cgen,
  input         sigFromSrams_bore_1_ram_hold,
  input         sigFromSrams_bore_1_ram_bypass,
  input         sigFromSrams_bore_1_ram_bp_clken,
  input         sigFromSrams_bore_1_ram_aux_clk,
  input         sigFromSrams_bore_1_ram_aux_ckbp,
  input         sigFromSrams_bore_1_ram_mcp_hold,
  input         sigFromSrams_bore_1_cgen,
  input         sigFromSrams_bore_2_ram_hold,
  input         sigFromSrams_bore_2_ram_bypass,
  input         sigFromSrams_bore_2_ram_bp_clken,
  input         sigFromSrams_bore_2_ram_aux_clk,
  input         sigFromSrams_bore_2_ram_aux_ckbp,
  input         sigFromSrams_bore_2_ram_mcp_hold,
  input         sigFromSrams_bore_2_cgen,
  input         sigFromSrams_bore_3_ram_hold,
  input         sigFromSrams_bore_3_ram_bypass,
  input         sigFromSrams_bore_3_ram_bp_clken,
  input         sigFromSrams_bore_3_ram_aux_clk,
  input         sigFromSrams_bore_3_ram_aux_ckbp,
  input         sigFromSrams_bore_3_ram_mcp_hold,
  input         sigFromSrams_bore_3_cgen,
  input         sigFromSrams_bore_4_ram_hold,
  input         sigFromSrams_bore_4_ram_bypass,
  input         sigFromSrams_bore_4_ram_bp_clken,
  input         sigFromSrams_bore_4_ram_aux_clk,
  input         sigFromSrams_bore_4_ram_aux_ckbp,
  input         sigFromSrams_bore_4_ram_mcp_hold,
  input         sigFromSrams_bore_4_cgen,
  input         sigFromSrams_bore_5_ram_hold,
  input         sigFromSrams_bore_5_ram_bypass,
  input         sigFromSrams_bore_5_ram_bp_clken,
  input         sigFromSrams_bore_5_ram_aux_clk,
  input         sigFromSrams_bore_5_ram_aux_ckbp,
  input         sigFromSrams_bore_5_ram_mcp_hold,
  input         sigFromSrams_bore_5_cgen,
  input         sigFromSrams_bore_6_ram_hold,
  input         sigFromSrams_bore_6_ram_bypass,
  input         sigFromSrams_bore_6_ram_bp_clken,
  input         sigFromSrams_bore_6_ram_aux_clk,
  input         sigFromSrams_bore_6_ram_aux_ckbp,
  input         sigFromSrams_bore_6_ram_mcp_hold,
  input         sigFromSrams_bore_6_cgen,
  input         sigFromSrams_bore_7_ram_hold,
  input         sigFromSrams_bore_7_ram_bypass,
  input         sigFromSrams_bore_7_ram_bp_clken,
  input         sigFromSrams_bore_7_ram_aux_clk,
  input         sigFromSrams_bore_7_ram_aux_ckbp,
  input         sigFromSrams_bore_7_ram_mcp_hold,
  input         sigFromSrams_bore_7_cgen
);
endmodule

module PrefetcherMonitor(

  input  clock,
  input  reset,
  input  io_timely_total_prefetch,
  input  io_timely_late_hit_prefetch,
  input  io_timely_late_miss_prefetch,
  input  io_validity_good_prefetch,
  input  io_validity_bad_prefetch,
  output io_pf_ctrl_enable,
  output io_pf_ctrl_confidence
);
endmodule

module FDPrefetcherMonitor(

  input io_accuracy_useful_prefetch_0,
  input io_accuracy_useful_prefetch_1,
  input io_accuracy_useful_prefetch_2,
  input io_timely_late_prefetch,
  input io_pollution_demand_miss_0,
  input io_pollution_demand_miss_1,
  input io_pollution_demand_miss_2,
  input io_pollution_cache_pollution_0,
  input io_pollution_cache_pollution_1,
  input io_pollution_cache_pollution_2
);
endmodule

module BloomFilter(

  input         clock,
  input         reset,
  input         io_set_valid,
  input  [11:0] io_set_bits_addr,
  input         io_clr_valid,
  input  [11:0] io_clr_bits_addr,
  input         io_query_0_valid,
  input  [11:0] io_query_0_bits_addr,
  input         io_query_1_valid,
  input  [11:0] io_query_1_bits_addr,
  input         io_query_2_valid,
  input  [11:0] io_query_2_bits_addr,
  output        io_resp_0_valid,
  output        io_resp_0_bits_res,
  output        io_resp_1_valid,
  output        io_resp_1_bits_res,
  output        io_resp_2_valid,
  output        io_resp_2_bits_res
);
endmodule

module CounterFilter(

  input        clock,
  input        reset,
  input        io_ld_in_0_valid,
  input  [7:0] io_ld_in_0_bits_idx,
  input  [1:0] io_ld_in_0_bits_way,
  input        io_ld_in_1_valid,
  input  [7:0] io_ld_in_1_bits_idx,
  input  [1:0] io_ld_in_1_bits_way,
  input        io_ld_in_2_valid,
  input  [7:0] io_ld_in_2_bits_idx,
  input  [1:0] io_ld_in_2_bits_way,
  input        io_query_0_req_valid,
  input  [7:0] io_query_0_req_bits_idx,
  input  [1:0] io_query_0_req_bits_way,
  output       io_query_0_resp,
  input        io_query_1_req_valid,
  input  [7:0] io_query_1_req_bits_idx,
  input  [1:0] io_query_1_req_bits_way,
  output       io_query_1_resp,
  input        io_query_2_req_valid,
  input  [7:0] io_query_2_req_bits_idx,
  input  [1:0] io_query_2_req_bits_way,
  output       io_query_2_resp
);
endmodule

module LoadPipe(

  input          clock,
  input          reset,
  output         io_lsu_req_ready,
  input          io_lsu_req_valid,
  input  [4:0]   io_lsu_req_bits_cmd,
  input  [49:0]  io_lsu_req_bits_vaddr,
  input  [49:0]  io_lsu_req_bits_vaddr_dup,
  input  [3:0]   io_lsu_req_bits_instrtype,
  input          io_lsu_req_bits_isFirstIssue,
  input          io_lsu_req_bits_lqIdx_flag,
  input  [6:0]   io_lsu_req_bits_lqIdx_value,
  output         io_lsu_resp_valid,
  output [127:0] io_lsu_resp_bits_data,
  output [127:0] io_lsu_resp_bits_data_delayed,
  output         io_lsu_resp_bits_miss,
  output [3:0]   io_lsu_resp_bits_mshr_id,
  output [2:0]   io_lsu_resp_bits_meta_prefetch,
  output         io_lsu_resp_bits_handled,
  output         io_lsu_resp_bits_error_delayed,
  input          io_lsu_s1_kill,
  input          io_lsu_s2_kill,
  input  [2:0]   io_lsu_pf_source,
  input  [47:0]  io_lsu_s1_paddr_dup_lsu,
  input  [47:0]  io_lsu_s1_paddr_dup_dcache,
  output         io_lsu_s2_bank_conflict,
  output         io_lsu_s2_mq_nack,
  input          io_load128Req,
  output         io_meta_read_valid,
  output [7:0]   io_meta_read_bits_idx,
  input  [1:0]   io_meta_resp_0_coh_state,
  input  [1:0]   io_meta_resp_1_coh_state,
  input  [1:0]   io_meta_resp_2_coh_state,
  input  [1:0]   io_meta_resp_3_coh_state,
  input          io_extra_meta_resp_0_error,
  input  [2:0]   io_extra_meta_resp_0_prefetch,
  input          io_extra_meta_resp_0_access,
  input          io_extra_meta_resp_1_error,
  input  [2:0]   io_extra_meta_resp_1_prefetch,
  input          io_extra_meta_resp_1_access,
  input          io_extra_meta_resp_2_error,
  input  [2:0]   io_extra_meta_resp_2_prefetch,
  input          io_extra_meta_resp_2_access,
  input          io_extra_meta_resp_3_error,
  input  [2:0]   io_extra_meta_resp_3_prefetch,
  input          io_extra_meta_resp_3_access,
  input          io_tag_read_ready,
  output         io_tag_read_valid,
  output [7:0]   io_tag_read_bits_idx,
  input  [42:0]  io_tag_resp_0,
  input  [42:0]  io_tag_resp_1,
  input  [42:0]  io_tag_resp_2,
  input  [42:0]  io_tag_resp_3,
  input          io_banked_data_read_ready,
  output         io_banked_data_read_valid,
  output [3:0]   io_banked_data_read_bits_way_en,
  output [47:0]  io_banked_data_read_bits_addr,
  output [47:0]  io_banked_data_read_bits_addr_dup,
  output [7:0]   io_banked_data_read_bits_bankMask,
  output         io_banked_data_read_bits_lqIdx_flag,
  output [6:0]   io_banked_data_read_bits_lqIdx_value,
  output         io_is128Req,
  input  [63:0]  io_banked_data_resp_0_raw_data,
  input  [63:0]  io_banked_data_resp_1_raw_data,
  input          io_read_error_delayed_0,
  input          io_read_error_delayed_1,
  output         io_access_flag_write_valid,
  output [7:0]   io_access_flag_write_bits_idx,
  output [3:0]   io_access_flag_write_bits_way_en,
  output         io_prefetch_flag_write_valid,
  output [7:0]   io_prefetch_flag_write_bits_idx,
  output [3:0]   io_prefetch_flag_write_bits_way_en,
  input          io_bank_conflict_slow,
  input          io_miss_req_ready,
  output         io_miss_req_valid,
  output [3:0]   io_miss_req_bits_source,
  output [2:0]   io_miss_req_bits_pf_source,
  output [4:0]   io_miss_req_bits_cmd,
  output [47:0]  io_miss_req_bits_addr,
  output [49:0]  io_miss_req_bits_vaddr,
  output [1:0]   io_miss_req_bits_req_coh_state,
  output         io_miss_req_bits_isBtoT,
  output [3:0]   io_miss_req_bits_occupy_way,
  output         io_miss_req_bits_cancel,
  input  [3:0]   io_miss_resp_id,
  input          io_miss_resp_handled,
  input          io_miss_resp_merged,
  output         io_wbq_conflict_check_valid,
  output [47:0]  io_wbq_conflict_check_bits,
  input          io_wbq_block_miss_req,
  output         io_replace_access_valid,
  output [7:0]   io_replace_access_bits_set,
  output [1:0]   io_replace_access_bits_way,
  output [7:0]   io_occupy_set,
  input          io_occupy_fail,
  input          io_disable_ld_fast_wakeup,
  output         io_error_valid,
  output [47:0]  io_error_bits_paddr,
  output         io_error_bits_report_to_beu,
  input          io_pseudo_error_valid,
  input          io_pseudo_error_bits_0_valid,
  input  [63:0]  io_pseudo_error_bits_0_mask,
  output         io_pseudo_tag_error_inj_done,
  output         io_pseudo_data_error_inj_done,
  output         io_prefetch_info_naive_total_prefetch,
  output         io_prefetch_info_naive_late_hit_prefetch,
  output         io_prefetch_info_naive_late_prefetch_hit,
  output         io_prefetch_info_naive_late_load_hit,
  output         io_prefetch_info_naive_useful_prefetch,
  output         io_prefetch_info_naive_prefetch_hit,
  output         io_prefetch_info_fdp_useful_prefetch,
  output         io_prefetch_info_fdp_demand_miss,
  output         io_prefetch_info_fdp_pollution,
  output         io_bloom_filter_query_query_valid,
  output [11:0]  io_bloom_filter_query_query_bits_addr,
  input          io_bloom_filter_query_resp_valid,
  input          io_bloom_filter_query_resp_bits_res,
  output         io_counter_filter_query_req_valid,
  output [7:0]   io_counter_filter_query_req_bits_idx,
  output [1:0]   io_counter_filter_query_req_bits_way,
  input          io_counter_filter_query_resp,
  output         io_counter_filter_enq_valid,
  output [7:0]   io_counter_filter_enq_bits_idx,
  output [1:0]   io_counter_filter_enq_bits_way,
  output [5:0]   io_perf_0_value,
  output [5:0]   io_perf_1_value,
  output [5:0]   io_perf_2_value,
  output [5:0]   io_perf_3_value,
  output [5:0]   io_perf_4_value
);
endmodule

module StorePipe(

  input io_lsu_req_valid
);
endmodule

module MainPipe(

  input          clock,
  input          reset,
  output         io_probe_req_ready,
  input          io_probe_req_valid,
  input  [1:0]   io_probe_req_bits_probe_param,
  input          io_probe_req_bits_probe_need_data,
  input  [49:0]  io_probe_req_bits_vaddr,
  input  [47:0]  io_probe_req_bits_addr,
  input  [5:0]   io_probe_req_bits_id,
  input          io_miss_req_ready,
  output         io_miss_req_valid,
  output [3:0]   io_miss_req_bits_source,
  output [4:0]   io_miss_req_bits_cmd,
  output [47:0]  io_miss_req_bits_addr,
  output [49:0]  io_miss_req_bits_vaddr,
  output         io_miss_req_bits_full_overwrite,
  output [2:0]   io_miss_req_bits_word_idx,
  output [127:0] io_miss_req_bits_amo_data,
  output [15:0]  io_miss_req_bits_amo_mask,
  output [127:0] io_miss_req_bits_amo_cmp,
  output [1:0]   io_miss_req_bits_req_coh_state,
  output [5:0]   io_miss_req_bits_id,
  output         io_miss_req_bits_isBtoT,
  output [3:0]   io_miss_req_bits_occupy_way,
  output         io_miss_req_bits_cancel,
  output [511:0] io_miss_req_bits_store_data,
  output [63:0]  io_miss_req_bits_store_mask,
  output         io_refill_req_ready,
  input          io_refill_req_valid,
  input          io_refill_req_bits_miss,
  input  [3:0]   io_refill_req_bits_miss_id,
  input  [3:0]   io_refill_req_bits_occupy_way,
  input          io_refill_req_bits_miss_fail_cause_evict_btot,
  input  [3:0]   io_refill_req_bits_source,
  input  [4:0]   io_refill_req_bits_cmd,
  input  [49:0]  io_refill_req_bits_vaddr,
  input  [47:0]  io_refill_req_bits_addr,
  input  [2:0]   io_refill_req_bits_word_idx,
  input  [127:0] io_refill_req_bits_amo_data,
  input  [15:0]  io_refill_req_bits_amo_mask,
  input  [127:0] io_refill_req_bits_amo_cmp,
  input  [2:0]   io_refill_req_bits_pf_source,
  input          io_refill_req_bits_access,
  input  [5:0]   io_refill_req_bits_id,
  output         io_wbq_conflict_check_valid,
  output [47:0]  io_wbq_conflict_check_bits,
  input          io_wbq_block_miss_req,
  output         io_store_req_ready,
  input          io_store_req_valid,
  input  [49:0]  io_store_req_bits_vaddr,
  input  [47:0]  io_store_req_bits_addr,
  input  [511:0] io_store_req_bits_data,
  input  [63:0]  io_store_req_bits_mask,
  input  [5:0]   io_store_req_bits_id,
  output         io_store_replay_resp_valid,
  output [5:0]   io_store_replay_resp_bits_id,
  output         io_store_hit_resp_valid,
  output [5:0]   io_store_hit_resp_bits_id,
  output         io_atomic_req_ready,
  input          io_atomic_req_valid,
  input  [4:0]   io_atomic_req_bits_cmd,
  input  [49:0]  io_atomic_req_bits_vaddr,
  input  [47:0]  io_atomic_req_bits_addr,
  input  [2:0]   io_atomic_req_bits_word_idx,
  input  [127:0] io_atomic_req_bits_amo_data,
  input  [15:0]  io_atomic_req_bits_amo_mask,
  input  [127:0] io_atomic_req_bits_amo_cmp,
  output         io_atomic_resp_valid,
  output [3:0]   io_atomic_resp_bits_source,
  output [127:0] io_atomic_resp_bits_data,
  output         io_atomic_resp_bits_miss,
  output [3:0]   io_atomic_resp_bits_miss_id,
  output         io_atomic_resp_bits_replay,
  output         io_atomic_resp_bits_error,
  output         io_atomic_resp_bits_ack_miss_queue,
  output [5:0]   io_atomic_resp_bits_id,
  output         io_mainpipe_info_s2_valid,
  output [3:0]   io_mainpipe_info_s2_miss_id,
  output         io_mainpipe_info_s2_replay_to_mq,
  output         io_mainpipe_info_s2_evict_BtoT_way,
  output [3:0]   io_mainpipe_info_s2_next_evict_way,
  output         io_mainpipe_info_s3_valid,
  output [3:0]   io_mainpipe_info_s3_miss_id,
  output         io_mainpipe_info_s3_refill_resp,
  input          io_refill_info_valid,
  input  [511:0] io_refill_info_bits_store_data,
  input  [63:0]  io_refill_info_bits_store_mask,
  input  [1:0]   io_refill_info_bits_miss_param,
  input          io_refill_info_bits_error,
  input          io_wb_ready,
  output         io_wb_valid,
  output [2:0]   io_wb_bits_param,
  output         io_wb_bits_voluntary,
  output         io_wb_bits_hasData,
  output         io_wb_bits_corrupt,
  output         io_wb_bits_dirty,
  output [47:0]  io_wb_bits_addr,
  output [511:0] io_wb_bits_data,
  output         io_data_read_intend,
  input          io_data_readline_ready,
  output         io_data_readline_valid,
  output [3:0]   io_data_readline_bits_way_en,
  output [47:0]  io_data_readline_bits_addr,
  output [7:0]   io_data_readline_bits_rmask,
  output         io_data_readline_can_go,
  output         io_data_readline_stall,
  output         io_data_readline_can_resp,
  input  [63:0]  io_data_resp_0_raw_data,
  input  [63:0]  io_data_resp_1_raw_data,
  input  [63:0]  io_data_resp_2_raw_data,
  input  [63:0]  io_data_resp_3_raw_data,
  input  [63:0]  io_data_resp_4_raw_data,
  input  [63:0]  io_data_resp_5_raw_data,
  input  [63:0]  io_data_resp_6_raw_data,
  input  [63:0]  io_data_resp_7_raw_data,
  input          io_readline_error,
  input          io_readline_error_delayed,
  output         io_data_write_valid,
  output [7:0]   io_data_write_bits_wmask,
  output [63:0]  io_data_write_bits_data_0,
  output [63:0]  io_data_write_bits_data_1,
  output [63:0]  io_data_write_bits_data_2,
  output [63:0]  io_data_write_bits_data_3,
  output [63:0]  io_data_write_bits_data_4,
  output [63:0]  io_data_write_bits_data_5,
  output [63:0]  io_data_write_bits_data_6,
  output [63:0]  io_data_write_bits_data_7,
  output         io_data_write_dup_0_valid,
  output [3:0]   io_data_write_dup_0_bits_way_en,
  output [47:0]  io_data_write_dup_0_bits_addr,
  output         io_data_write_dup_1_valid,
  output [3:0]   io_data_write_dup_1_bits_way_en,
  output [47:0]  io_data_write_dup_1_bits_addr,
  output         io_data_write_dup_2_valid,
  output [3:0]   io_data_write_dup_2_bits_way_en,
  output [47:0]  io_data_write_dup_2_bits_addr,
  output         io_data_write_dup_3_valid,
  output [3:0]   io_data_write_dup_3_bits_way_en,
  output [47:0]  io_data_write_dup_3_bits_addr,
  output         io_data_write_dup_4_valid,
  output [3:0]   io_data_write_dup_4_bits_way_en,
  output [47:0]  io_data_write_dup_4_bits_addr,
  output         io_data_write_dup_5_valid,
  output [3:0]   io_data_write_dup_5_bits_way_en,
  output [47:0]  io_data_write_dup_5_bits_addr,
  output         io_data_write_dup_6_valid,
  output [3:0]   io_data_write_dup_6_bits_way_en,
  output [47:0]  io_data_write_dup_6_bits_addr,
  output         io_data_write_dup_7_valid,
  output [3:0]   io_data_write_dup_7_bits_way_en,
  output [47:0]  io_data_write_dup_7_bits_addr,
  output         io_meta_read_valid,
  output [7:0]   io_meta_read_bits_idx,
  input  [1:0]   io_meta_resp_0_coh_state,
  input  [1:0]   io_meta_resp_1_coh_state,
  input  [1:0]   io_meta_resp_2_coh_state,
  input  [1:0]   io_meta_resp_3_coh_state,
  output         io_meta_write_valid,
  output [7:0]   io_meta_write_bits_idx,
  output [3:0]   io_meta_write_bits_way_en,
  output [1:0]   io_meta_write_bits_meta_coh_state,
  input          io_extra_meta_resp_0_error,
  input  [2:0]   io_extra_meta_resp_0_prefetch,
  input          io_extra_meta_resp_0_access,
  input          io_extra_meta_resp_1_error,
  input  [2:0]   io_extra_meta_resp_1_prefetch,
  input          io_extra_meta_resp_1_access,
  input          io_extra_meta_resp_2_error,
  input  [2:0]   io_extra_meta_resp_2_prefetch,
  input          io_extra_meta_resp_2_access,
  input          io_extra_meta_resp_3_error,
  input  [2:0]   io_extra_meta_resp_3_prefetch,
  input          io_extra_meta_resp_3_access,
  output         io_error_flag_write_valid,
  output [7:0]   io_error_flag_write_bits_idx,
  output [3:0]   io_error_flag_write_bits_way_en,
  output         io_error_flag_write_bits_flag,
  output         io_prefetch_flag_write_valid,
  output [7:0]   io_prefetch_flag_write_bits_idx,
  output [3:0]   io_prefetch_flag_write_bits_way_en,
  output [2:0]   io_prefetch_flag_write_bits_source,
  output         io_access_flag_write_valid,
  output [7:0]   io_access_flag_write_bits_idx,
  output [3:0]   io_access_flag_write_bits_way_en,
  output         io_access_flag_write_bits_flag,
  input          io_tag_read_ready,
  output         io_tag_read_valid,
  output [7:0]   io_tag_read_bits_idx,
  input  [42:0]  io_tag_resp_0,
  input  [42:0]  io_tag_resp_1,
  input  [42:0]  io_tag_resp_2,
  input  [42:0]  io_tag_resp_3,
  output         io_tag_write_valid,
  output [7:0]   io_tag_write_bits_idx,
  output [3:0]   io_tag_write_bits_way_en,
  output [35:0]  io_tag_write_bits_tag,
  output         io_tag_write_intend,
  output         io_replace_access_valid,
  output [7:0]   io_replace_access_bits_set,
  output [1:0]   io_replace_access_bits_way,
  output [7:0]   io_replace_way_set_bits,
  input  [1:0]   io_replace_way_way,
  output [7:0]   io_evict_set,
  input  [3:0]   io_btot_ways_for_set,
  output [47:0]  io_replace_req_bits_addr,
  output [49:0]  io_replace_req_bits_vaddr,
  input          io_replace_block,
  output         io_sms_agt_evict_req_valid,
  output [49:0]  io_sms_agt_evict_req_bits_vaddr,
  output         io_status_dup_0_s1_valid,
  output [7:0]   io_status_dup_0_s1_bits_set,
  output [3:0]   io_status_dup_0_s1_bits_way_en,
  output         io_status_dup_0_s2_valid,
  output [7:0]   io_status_dup_0_s2_bits_set,
  output [3:0]   io_status_dup_0_s2_bits_way_en,
  output         io_status_dup_0_s3_valid,
  output [7:0]   io_status_dup_0_s3_bits_set,
  output [3:0]   io_status_dup_0_s3_bits_way_en,
  output         io_status_dup_1_s1_valid,
  output [7:0]   io_status_dup_1_s1_bits_set,
  output [3:0]   io_status_dup_1_s1_bits_way_en,
  output         io_status_dup_1_s2_valid,
  output [7:0]   io_status_dup_1_s2_bits_set,
  output [3:0]   io_status_dup_1_s2_bits_way_en,
  output         io_status_dup_1_s3_valid,
  output [7:0]   io_status_dup_1_s3_bits_set,
  output [3:0]   io_status_dup_1_s3_bits_way_en,
  output         io_status_dup_2_s1_valid,
  output [7:0]   io_status_dup_2_s1_bits_set,
  output [3:0]   io_status_dup_2_s1_bits_way_en,
  output         io_status_dup_2_s2_valid,
  output [7:0]   io_status_dup_2_s2_bits_set,
  output [3:0]   io_status_dup_2_s2_bits_way_en,
  output         io_status_dup_2_s3_valid,
  output [7:0]   io_status_dup_2_s3_bits_set,
  output [3:0]   io_status_dup_2_s3_bits_way_en,
  output         io_status_dup_3_s1_valid,
  output [7:0]   io_status_dup_3_s1_bits_set,
  output [3:0]   io_status_dup_3_s1_bits_way_en,
  output         io_status_dup_3_s2_valid,
  output [7:0]   io_status_dup_3_s2_bits_set,
  output [3:0]   io_status_dup_3_s2_bits_way_en,
  output         io_status_dup_3_s3_valid,
  output [7:0]   io_status_dup_3_s3_bits_set,
  output [3:0]   io_status_dup_3_s3_bits_way_en,
  output         io_status_dup_4_s1_valid,
  output [7:0]   io_status_dup_4_s1_bits_set,
  output [3:0]   io_status_dup_4_s1_bits_way_en,
  output         io_status_dup_4_s2_valid,
  output [7:0]   io_status_dup_4_s2_bits_set,
  output [3:0]   io_status_dup_4_s2_bits_way_en,
  output         io_status_dup_4_s3_valid,
  output [7:0]   io_status_dup_4_s3_bits_set,
  output [3:0]   io_status_dup_4_s3_bits_way_en,
  output         io_status_dup_5_s1_valid,
  output [7:0]   io_status_dup_5_s1_bits_set,
  output [3:0]   io_status_dup_5_s1_bits_way_en,
  output         io_status_dup_5_s2_valid,
  output [7:0]   io_status_dup_5_s2_bits_set,
  output [3:0]   io_status_dup_5_s2_bits_way_en,
  output         io_status_dup_5_s3_valid,
  output [7:0]   io_status_dup_5_s3_bits_set,
  output [3:0]   io_status_dup_5_s3_bits_way_en,
  output         io_status_dup_6_s1_valid,
  output [7:0]   io_status_dup_6_s1_bits_set,
  output [3:0]   io_status_dup_6_s1_bits_way_en,
  output         io_status_dup_6_s2_valid,
  output [7:0]   io_status_dup_6_s2_bits_set,
  output [3:0]   io_status_dup_6_s2_bits_way_en,
  output         io_status_dup_6_s3_valid,
  output [7:0]   io_status_dup_6_s3_bits_set,
  output [3:0]   io_status_dup_6_s3_bits_way_en,
  output         io_status_dup_7_s1_valid,
  output [7:0]   io_status_dup_7_s1_bits_set,
  output [3:0]   io_status_dup_7_s1_bits_way_en,
  output         io_status_dup_7_s2_valid,
  output [7:0]   io_status_dup_7_s2_bits_set,
  output [3:0]   io_status_dup_7_s2_bits_way_en,
  output         io_status_dup_7_s3_valid,
  output [7:0]   io_status_dup_7_s3_bits_set,
  output [3:0]   io_status_dup_7_s3_bits_way_en,
  output         io_status_dup_8_s1_valid,
  output [7:0]   io_status_dup_8_s1_bits_set,
  output [3:0]   io_status_dup_8_s1_bits_way_en,
  output         io_status_dup_8_s2_valid,
  output [7:0]   io_status_dup_8_s2_bits_set,
  output [3:0]   io_status_dup_8_s2_bits_way_en,
  output         io_status_dup_8_s3_valid,
  output [7:0]   io_status_dup_8_s3_bits_set,
  output [3:0]   io_status_dup_8_s3_bits_way_en,
  output         io_status_dup_9_s1_valid,
  output [7:0]   io_status_dup_9_s1_bits_set,
  output [3:0]   io_status_dup_9_s1_bits_way_en,
  output         io_status_dup_9_s2_valid,
  output [7:0]   io_status_dup_9_s2_bits_set,
  output [3:0]   io_status_dup_9_s2_bits_way_en,
  output         io_status_dup_9_s3_valid,
  output [7:0]   io_status_dup_9_s3_bits_set,
  output [3:0]   io_status_dup_9_s3_bits_way_en,
  output         io_status_dup_10_s1_valid,
  output [7:0]   io_status_dup_10_s1_bits_set,
  output [3:0]   io_status_dup_10_s1_bits_way_en,
  output         io_status_dup_10_s2_valid,
  output [7:0]   io_status_dup_10_s2_bits_set,
  output [3:0]   io_status_dup_10_s2_bits_way_en,
  output         io_status_dup_10_s3_valid,
  output [7:0]   io_status_dup_10_s3_bits_set,
  output [3:0]   io_status_dup_10_s3_bits_way_en,
  output         io_status_dup_11_s1_valid,
  output [7:0]   io_status_dup_11_s1_bits_set,
  output [3:0]   io_status_dup_11_s1_bits_way_en,
  output         io_status_dup_11_s2_valid,
  output [7:0]   io_status_dup_11_s2_bits_set,
  output [3:0]   io_status_dup_11_s2_bits_way_en,
  output         io_status_dup_11_s3_valid,
  output [7:0]   io_status_dup_11_s3_bits_set,
  output [3:0]   io_status_dup_11_s3_bits_way_en,
  output         io_status_dup_12_s1_valid,
  output [7:0]   io_status_dup_12_s1_bits_set,
  output [3:0]   io_status_dup_12_s1_bits_way_en,
  output         io_status_dup_12_s2_valid,
  output [7:0]   io_status_dup_12_s2_bits_set,
  output [3:0]   io_status_dup_12_s2_bits_way_en,
  output         io_status_dup_12_s3_valid,
  output [7:0]   io_status_dup_12_s3_bits_set,
  output [3:0]   io_status_dup_12_s3_bits_way_en,
  output         io_status_dup_13_s1_valid,
  output [7:0]   io_status_dup_13_s1_bits_set,
  output [3:0]   io_status_dup_13_s1_bits_way_en,
  output         io_status_dup_13_s2_valid,
  output [7:0]   io_status_dup_13_s2_bits_set,
  output [3:0]   io_status_dup_13_s2_bits_way_en,
  output         io_status_dup_13_s3_valid,
  output [7:0]   io_status_dup_13_s3_bits_set,
  output [3:0]   io_status_dup_13_s3_bits_way_en,
  output         io_status_dup_14_s1_valid,
  output [7:0]   io_status_dup_14_s1_bits_set,
  output [3:0]   io_status_dup_14_s1_bits_way_en,
  output         io_status_dup_14_s2_valid,
  output [7:0]   io_status_dup_14_s2_bits_set,
  output [3:0]   io_status_dup_14_s2_bits_way_en,
  output         io_status_dup_14_s3_valid,
  output [7:0]   io_status_dup_14_s3_bits_set,
  output [3:0]   io_status_dup_14_s3_bits_way_en,
  output         io_status_dup_15_s1_valid,
  output [7:0]   io_status_dup_15_s1_bits_set,
  output [3:0]   io_status_dup_15_s1_bits_way_en,
  output         io_status_dup_15_s2_valid,
  output [7:0]   io_status_dup_15_s2_bits_set,
  output [3:0]   io_status_dup_15_s2_bits_way_en,
  output         io_status_dup_15_s3_valid,
  output [7:0]   io_status_dup_15_s3_bits_set,
  output [3:0]   io_status_dup_15_s3_bits_way_en,
  output         io_status_dup_16_s1_valid,
  output [7:0]   io_status_dup_16_s1_bits_set,
  output [3:0]   io_status_dup_16_s1_bits_way_en,
  output         io_status_dup_16_s2_valid,
  output [7:0]   io_status_dup_16_s2_bits_set,
  output [3:0]   io_status_dup_16_s2_bits_way_en,
  output         io_status_dup_16_s3_valid,
  output [7:0]   io_status_dup_16_s3_bits_set,
  output [3:0]   io_status_dup_16_s3_bits_way_en,
  output         io_status_dup_17_s1_valid,
  output [7:0]   io_status_dup_17_s1_bits_set,
  output [3:0]   io_status_dup_17_s1_bits_way_en,
  output         io_status_dup_17_s2_valid,
  output [7:0]   io_status_dup_17_s2_bits_set,
  output [3:0]   io_status_dup_17_s2_bits_way_en,
  output         io_status_dup_17_s3_valid,
  output [7:0]   io_status_dup_17_s3_bits_set,
  output [3:0]   io_status_dup_17_s3_bits_way_en,
  output         io_status_dup_18_s1_valid,
  output [7:0]   io_status_dup_18_s1_bits_set,
  output [3:0]   io_status_dup_18_s1_bits_way_en,
  output         io_status_dup_18_s2_valid,
  output [7:0]   io_status_dup_18_s2_bits_set,
  output [3:0]   io_status_dup_18_s2_bits_way_en,
  output         io_status_dup_18_s3_valid,
  output [7:0]   io_status_dup_18_s3_bits_set,
  output [3:0]   io_status_dup_18_s3_bits_way_en,
  output         io_status_dup_19_s1_valid,
  output [7:0]   io_status_dup_19_s1_bits_set,
  output [3:0]   io_status_dup_19_s1_bits_way_en,
  output         io_status_dup_19_s2_valid,
  output [7:0]   io_status_dup_19_s2_bits_set,
  output [3:0]   io_status_dup_19_s2_bits_way_en,
  output         io_status_dup_19_s3_valid,
  output [7:0]   io_status_dup_19_s3_bits_set,
  output [3:0]   io_status_dup_19_s3_bits_way_en,
  output         io_status_dup_20_s1_valid,
  output [7:0]   io_status_dup_20_s1_bits_set,
  output [3:0]   io_status_dup_20_s1_bits_way_en,
  output         io_status_dup_20_s2_valid,
  output [7:0]   io_status_dup_20_s2_bits_set,
  output [3:0]   io_status_dup_20_s2_bits_way_en,
  output         io_status_dup_20_s3_valid,
  output [7:0]   io_status_dup_20_s3_bits_set,
  output [3:0]   io_status_dup_20_s3_bits_way_en,
  output         io_status_dup_21_s1_valid,
  output [7:0]   io_status_dup_21_s1_bits_set,
  output [3:0]   io_status_dup_21_s1_bits_way_en,
  output         io_status_dup_21_s2_valid,
  output [7:0]   io_status_dup_21_s2_bits_set,
  output [3:0]   io_status_dup_21_s2_bits_way_en,
  output         io_status_dup_21_s3_valid,
  output [7:0]   io_status_dup_21_s3_bits_set,
  output [3:0]   io_status_dup_21_s3_bits_way_en,
  output         io_status_dup_22_s1_valid,
  output [7:0]   io_status_dup_22_s1_bits_set,
  output [3:0]   io_status_dup_22_s1_bits_way_en,
  output         io_status_dup_22_s2_valid,
  output [7:0]   io_status_dup_22_s2_bits_set,
  output [3:0]   io_status_dup_22_s2_bits_way_en,
  output         io_status_dup_22_s3_valid,
  output [7:0]   io_status_dup_22_s3_bits_set,
  output [3:0]   io_status_dup_22_s3_bits_way_en,
  output         io_status_dup_23_s1_valid,
  output [7:0]   io_status_dup_23_s1_bits_set,
  output [3:0]   io_status_dup_23_s1_bits_way_en,
  output         io_status_dup_23_s2_valid,
  output [7:0]   io_status_dup_23_s2_bits_set,
  output [3:0]   io_status_dup_23_s2_bits_way_en,
  output         io_status_dup_23_s3_valid,
  output [7:0]   io_status_dup_23_s3_bits_set,
  output [3:0]   io_status_dup_23_s3_bits_way_en,
  output         io_lrsc_locked_block_valid,
  output [47:0]  io_lrsc_locked_block_bits,
  input          io_invalid_resv_set,
  output         io_update_resv_set,
  output         io_block_lr,
  output         io_error_valid,
  output [47:0]  io_error_bits_paddr,
  output         io_error_bits_report_to_beu,
  input          io_pseudo_error_valid,
  input          io_pseudo_error_bits_0_valid,
  input  [63:0]  io_pseudo_error_bits_0_mask,
  output         io_pseudo_tag_error_inj_done,
  output         io_pseudo_data_error_inj_done,
  output         io_bloom_filter_query_set_valid,
  output [11:0]  io_bloom_filter_query_set_bits_addr,
  output         io_bloom_filter_query_clr_valid,
  output [11:0]  io_bloom_filter_query_clr_bits_addr,
  output [5:0]   io_perf_0_value,
  output [5:0]   io_perf_1_value
);
endmodule

module MissQueue(

  input          clock,
  input          reset,
  output         io_req_ready,
  input          io_req_valid,
  input  [3:0]   io_req_bits_source,
  input  [2:0]   io_req_bits_pf_source,
  input  [4:0]   io_req_bits_cmd,
  input  [47:0]  io_req_bits_addr,
  input  [49:0]  io_req_bits_vaddr,
  input          io_req_bits_full_overwrite,
  input  [2:0]   io_req_bits_word_idx,
  input  [127:0] io_req_bits_amo_data,
  input  [15:0]  io_req_bits_amo_mask,
  input  [127:0] io_req_bits_amo_cmp,
  input  [1:0]   io_req_bits_req_coh_state,
  input  [5:0]   io_req_bits_id,
  input          io_req_bits_isBtoT,
  input  [3:0]   io_req_bits_occupy_way,
  input          io_req_bits_cancel,
  input  [511:0] io_req_bits_store_data,
  input  [63:0]  io_req_bits_store_mask,
  output [3:0]   io_resp_id,
  output         io_resp_handled,
  output         io_resp_merged,
  output         io_cmo_req_ready,
  input          io_cmo_req_valid,
  input  [2:0]   io_cmo_req_bits_opcode,
  input  [63:0]  io_cmo_req_bits_address,
  input          io_cmo_resp_ready,
  output         io_cmo_resp_valid,
  output         io_cmo_resp_bits_nderr,
  input  [3:0]   io_queryMQ_0_req_bits_source,
  input  [47:0]  io_queryMQ_0_req_bits_addr,
  input  [49:0]  io_queryMQ_0_req_bits_vaddr,
  output         io_queryMQ_0_ready,
  input  [3:0]   io_queryMQ_1_req_bits_source,
  input  [47:0]  io_queryMQ_1_req_bits_addr,
  input  [49:0]  io_queryMQ_1_req_bits_vaddr,
  output         io_queryMQ_1_ready,
  input  [3:0]   io_queryMQ_2_req_bits_source,
  input  [47:0]  io_queryMQ_2_req_bits_addr,
  input  [49:0]  io_queryMQ_2_req_bits_vaddr,
  output         io_queryMQ_2_ready,
  input  [3:0]   io_queryMQ_3_req_bits_source,
  input  [47:0]  io_queryMQ_3_req_bits_addr,
  input  [49:0]  io_queryMQ_3_req_bits_vaddr,
  output         io_queryMQ_3_ready,
  input          io_mem_acquire_ready,
  output         io_mem_acquire_valid,
  output [3:0]   io_mem_acquire_bits_opcode,
  output [2:0]   io_mem_acquire_bits_param,
  output [2:0]   io_mem_acquire_bits_size,
  output [5:0]   io_mem_acquire_bits_source,
  output [47:0]  io_mem_acquire_bits_address,
  output [1:0]   io_mem_acquire_bits_user_alias,
  output [43:0]  io_mem_acquire_bits_user_vaddr,
  output [4:0]   io_mem_acquire_bits_user_reqSource,
  output         io_mem_acquire_bits_user_needHint,
  output         io_mem_acquire_bits_echo_isKeyword,
  output [31:0]  io_mem_acquire_bits_mask,
  output         io_mem_grant_ready,
  input          io_mem_grant_valid,
  input  [3:0]   io_mem_grant_bits_opcode,
  input  [1:0]   io_mem_grant_bits_param,
  input  [2:0]   io_mem_grant_bits_size,
  input  [5:0]   io_mem_grant_bits_source,
  input  [9:0]   io_mem_grant_bits_sink,
  input          io_mem_grant_bits_denied,
  input  [255:0] io_mem_grant_bits_data,
  input          io_mem_grant_bits_corrupt,
  input          io_mem_finish_ready,
  output         io_mem_finish_valid,
  output [9:0]   io_mem_finish_bits_sink,
  input          io_l2_hint_valid,
  input  [3:0]   io_l2_hint_bits_sourceId,
  input          io_main_pipe_req_ready,
  output         io_main_pipe_req_valid,
  output         io_main_pipe_req_bits_miss,
  output [3:0]   io_main_pipe_req_bits_miss_id,
  output [3:0]   io_main_pipe_req_bits_occupy_way,
  output         io_main_pipe_req_bits_miss_fail_cause_evict_btot,
  output [3:0]   io_main_pipe_req_bits_source,
  output [4:0]   io_main_pipe_req_bits_cmd,
  output [49:0]  io_main_pipe_req_bits_vaddr,
  output [47:0]  io_main_pipe_req_bits_addr,
  output [2:0]   io_main_pipe_req_bits_word_idx,
  output [127:0] io_main_pipe_req_bits_amo_data,
  output [15:0]  io_main_pipe_req_bits_amo_mask,
  output [127:0] io_main_pipe_req_bits_amo_cmp,
  output [2:0]   io_main_pipe_req_bits_pf_source,
  output         io_main_pipe_req_bits_access,
  output [5:0]   io_main_pipe_req_bits_id,
  input          io_main_pipe_resp_valid,
  input  [3:0]   io_main_pipe_resp_bits_miss_id,
  input          io_main_pipe_resp_bits_ack_miss_queue,
  input          io_mainpipe_info_s2_valid,
  input  [3:0]   io_mainpipe_info_s2_miss_id,
  input          io_mainpipe_info_s2_replay_to_mq,
  input          io_mainpipe_info_s2_evict_BtoT_way,
  input  [3:0]   io_mainpipe_info_s2_next_evict_way,
  input          io_mainpipe_info_s3_valid,
  input  [3:0]   io_mainpipe_info_s3_miss_id,
  input          io_mainpipe_info_s3_refill_resp,
  output         io_refill_info_valid,
  output [511:0] io_refill_info_bits_store_data,
  output [63:0]  io_refill_info_bits_store_mask,
  output [1:0]   io_refill_info_bits_miss_param,
  output         io_refill_info_bits_error,
  input  [47:0]  io_probe_req_bits_addr,
  input  [49:0]  io_probe_req_bits_vaddr,
  output         io_probe_block,
  input  [47:0]  io_replace_req_bits_addr,
  input  [49:0]  io_replace_req_bits_vaddr,
  output         io_replace_block,
  input  [7:0]   io_evict_set,
  output [3:0]   io_btot_ways_for_set,
  input  [7:0]   io_occupy_set_0,
  input  [7:0]   io_occupy_set_1,
  input  [7:0]   io_occupy_set_2,
  output         io_occupy_fail_0,
  output         io_occupy_fail_1,
  output         io_occupy_fail_2,
  input          io_wbq_block_miss_req,
  input          io_forward_0_valid,
  input  [3:0]   io_forward_0_mshrid,
  input  [47:0]  io_forward_0_paddr,
  output         io_forward_0_forward_mshr,
  output [7:0]   io_forward_0_forwardData_0,
  output [7:0]   io_forward_0_forwardData_1,
  output [7:0]   io_forward_0_forwardData_2,
  output [7:0]   io_forward_0_forwardData_3,
  output [7:0]   io_forward_0_forwardData_4,
  output [7:0]   io_forward_0_forwardData_5,
  output [7:0]   io_forward_0_forwardData_6,
  output [7:0]   io_forward_0_forwardData_7,
  output [7:0]   io_forward_0_forwardData_8,
  output [7:0]   io_forward_0_forwardData_9,
  output [7:0]   io_forward_0_forwardData_10,
  output [7:0]   io_forward_0_forwardData_11,
  output [7:0]   io_forward_0_forwardData_12,
  output [7:0]   io_forward_0_forwardData_13,
  output [7:0]   io_forward_0_forwardData_14,
  output [7:0]   io_forward_0_forwardData_15,
  output         io_forward_0_forward_result_valid,
  output         io_forward_0_corrupt,
  input          io_forward_1_valid,
  input  [3:0]   io_forward_1_mshrid,
  input  [47:0]  io_forward_1_paddr,
  output         io_forward_1_forward_mshr,
  output [7:0]   io_forward_1_forwardData_0,
  output [7:0]   io_forward_1_forwardData_1,
  output [7:0]   io_forward_1_forwardData_2,
  output [7:0]   io_forward_1_forwardData_3,
  output [7:0]   io_forward_1_forwardData_4,
  output [7:0]   io_forward_1_forwardData_5,
  output [7:0]   io_forward_1_forwardData_6,
  output [7:0]   io_forward_1_forwardData_7,
  output [7:0]   io_forward_1_forwardData_8,
  output [7:0]   io_forward_1_forwardData_9,
  output [7:0]   io_forward_1_forwardData_10,
  output [7:0]   io_forward_1_forwardData_11,
  output [7:0]   io_forward_1_forwardData_12,
  output [7:0]   io_forward_1_forwardData_13,
  output [7:0]   io_forward_1_forwardData_14,
  output [7:0]   io_forward_1_forwardData_15,
  output         io_forward_1_forward_result_valid,
  output         io_forward_1_corrupt,
  input          io_forward_2_valid,
  input  [3:0]   io_forward_2_mshrid,
  input  [47:0]  io_forward_2_paddr,
  output         io_forward_2_forward_mshr,
  output [7:0]   io_forward_2_forwardData_0,
  output [7:0]   io_forward_2_forwardData_1,
  output [7:0]   io_forward_2_forwardData_2,
  output [7:0]   io_forward_2_forwardData_3,
  output [7:0]   io_forward_2_forwardData_4,
  output [7:0]   io_forward_2_forwardData_5,
  output [7:0]   io_forward_2_forwardData_6,
  output [7:0]   io_forward_2_forwardData_7,
  output [7:0]   io_forward_2_forwardData_8,
  output [7:0]   io_forward_2_forwardData_9,
  output [7:0]   io_forward_2_forwardData_10,
  output [7:0]   io_forward_2_forwardData_11,
  output [7:0]   io_forward_2_forwardData_12,
  output [7:0]   io_forward_2_forwardData_13,
  output [7:0]   io_forward_2_forwardData_14,
  output [7:0]   io_forward_2_forwardData_15,
  output         io_forward_2_forward_result_valid,
  output         io_forward_2_corrupt,
  input          io_l2_pf_store_only,
  input          io_lqEmpty,
  output         io_prefetch_info_naive_late_miss_prefetch,
  output         io_prefetch_info_fdp_late_miss_prefetch,
  output         io_prefetch_info_fdp_prefetch_monitor_cnt,
  output         io_prefetch_info_fdp_total_prefetch,
  input          io_wfi_wfiReq,
  output         io_wfi_wfiSafe,
  input          io_debugTopDown_robHeadVaddr_valid,
  input  [49:0]  io_debugTopDown_robHeadVaddr_bits,
  output         io_debugTopDown_robHeadMissInDCache,
  output         io_l1Miss,
  output [5:0]   io_perf_0_value,
  output [5:0]   io_perf_1_value,
  output [5:0]   io_perf_2_value,
  output [5:0]   io_perf_3_value,
  output [5:0]   io_perf_4_value
);
endmodule

module ProbeQueue(

  input          clock,
  input          reset,
  output         io_mem_probe_ready,
  input          io_mem_probe_valid,
  input  [2:0]   io_mem_probe_bits_opcode,
  input  [1:0]   io_mem_probe_bits_param,
  input  [47:0]  io_mem_probe_bits_address,
  input  [255:0] io_mem_probe_bits_data,
  input          io_pipe_req_ready,
  output         io_pipe_req_valid,
  output [1:0]   io_pipe_req_bits_probe_param,
  output         io_pipe_req_bits_probe_need_data,
  output [49:0]  io_pipe_req_bits_vaddr,
  output [47:0]  io_pipe_req_bits_addr,
  output [5:0]   io_pipe_req_bits_id,
  input          io_lrsc_locked_block_valid,
  input  [47:0]  io_lrsc_locked_block_bits,
  input          io_update_resv_set,
  output [5:0]   io_perf_0_value,
  output [5:0]   io_perf_1_value,
  output [5:0]   io_perf_2_value,
  output [5:0]   io_perf_3_value,
  output [5:0]   io_perf_4_value
);
endmodule

module WritebackQueue(

  input          clock,
  input          reset,
  output         io_req_ready,
  input          io_req_valid,
  input  [2:0]   io_req_bits_param,
  input          io_req_bits_voluntary,
  input          io_req_bits_hasData,
  input          io_req_bits_corrupt,
  input          io_req_bits_dirty,
  input  [47:0]  io_req_bits_addr,
  input  [511:0] io_req_bits_data,
  input          io_mem_release_ready,
  output         io_mem_release_valid,
  output [2:0]   io_mem_release_bits_opcode,
  output [2:0]   io_mem_release_bits_param,
  output [2:0]   io_mem_release_bits_size,
  output [5:0]   io_mem_release_bits_source,
  output [47:0]  io_mem_release_bits_address,
  output [255:0] io_mem_release_bits_data,
  output         io_mem_release_bits_corrupt,
  input          io_mem_grant_valid,
  input  [5:0]   io_mem_grant_bits_source,
  input          io_miss_req_conflict_check_0_valid,
  input  [47:0]  io_miss_req_conflict_check_0_bits,
  input          io_miss_req_conflict_check_1_valid,
  input  [47:0]  io_miss_req_conflict_check_1_bits,
  input          io_miss_req_conflict_check_2_valid,
  input  [47:0]  io_miss_req_conflict_check_2_bits,
  input          io_miss_req_conflict_check_3_valid,
  input  [47:0]  io_miss_req_conflict_check_3_bits,
  input          io_miss_req_conflict_check_4_valid,
  input  [47:0]  io_miss_req_conflict_check_4_bits,
  output         io_block_miss_req_0,
  output         io_block_miss_req_1,
  output         io_block_miss_req_2,
  output         io_block_miss_req_3,
  output         io_block_miss_req_4,
  output [5:0]   io_perf_0_value,
  output [5:0]   io_perf_1_value,
  output [5:0]   io_perf_2_value,
  output [5:0]   io_perf_3_value,
  output [5:0]   io_perf_4_value
);
endmodule

module Arbiter1_TagWriteReq(

  input         io_in_0_valid,
  input  [7:0]  io_in_0_bits_idx,
  input  [3:0]  io_in_0_bits_way_en,
  input  [35:0] io_in_0_bits_tag,
  output        io_out_valid,
  output [7:0]  io_out_bits_idx,
  output [3:0]  io_out_bits_way_en,
  output [35:0] io_out_bits_tag
);
endmodule

module Arbiter1_L1BankedDataWriteReq(

  input         io_in_0_valid,
  input  [7:0]  io_in_0_bits_wmask,
  input  [63:0] io_in_0_bits_data_0,
  input  [63:0] io_in_0_bits_data_1,
  input  [63:0] io_in_0_bits_data_2,
  input  [63:0] io_in_0_bits_data_3,
  input  [63:0] io_in_0_bits_data_4,
  input  [63:0] io_in_0_bits_data_5,
  input  [63:0] io_in_0_bits_data_6,
  input  [63:0] io_in_0_bits_data_7,
  output        io_out_valid,
  output [7:0]  io_out_bits_wmask,
  output [63:0] io_out_bits_data_0,
  output [63:0] io_out_bits_data_1,
  output [63:0] io_out_bits_data_2,
  output [63:0] io_out_bits_data_3,
  output [63:0] io_out_bits_data_4,
  output [63:0] io_out_bits_data_5,
  output [63:0] io_out_bits_data_6,
  output [63:0] io_out_bits_data_7
);
endmodule

module Arbiter1_L1BankedDataWriteReqCtrl(

  input         io_in_0_valid,
  input  [3:0]  io_in_0_bits_way_en,
  input  [47:0] io_in_0_bits_addr,
  output        io_out_valid,
  output [3:0]  io_out_bits_way_en,
  output [47:0] io_out_bits_addr
);
endmodule

module TreeArbiter(

  output         io_in_0_ready,
  input          io_in_0_valid,
  input  [3:0]   io_in_0_bits_source,
  input  [4:0]   io_in_0_bits_cmd,
  input  [47:0]  io_in_0_bits_addr,
  input  [49:0]  io_in_0_bits_vaddr,
  input          io_in_0_bits_full_overwrite,
  input  [2:0]   io_in_0_bits_word_idx,
  input  [127:0] io_in_0_bits_amo_data,
  input  [15:0]  io_in_0_bits_amo_mask,
  input  [127:0] io_in_0_bits_amo_cmp,
  input  [1:0]   io_in_0_bits_req_coh_state,
  input  [5:0]   io_in_0_bits_id,
  input          io_in_0_bits_isBtoT,
  input  [3:0]   io_in_0_bits_occupy_way,
  input          io_in_0_bits_cancel,
  input  [511:0] io_in_0_bits_store_data,
  input  [63:0]  io_in_0_bits_store_mask,
  output         io_in_1_ready,
  input          io_in_1_valid,
  input  [3:0]   io_in_1_bits_source,
  input  [2:0]   io_in_1_bits_pf_source,
  input  [4:0]   io_in_1_bits_cmd,
  input  [47:0]  io_in_1_bits_addr,
  input  [49:0]  io_in_1_bits_vaddr,
  input  [1:0]   io_in_1_bits_req_coh_state,
  input          io_in_1_bits_isBtoT,
  input  [3:0]   io_in_1_bits_occupy_way,
  input          io_in_1_bits_cancel,
  output         io_in_2_ready,
  input          io_in_2_valid,
  input  [3:0]   io_in_2_bits_source,
  input  [2:0]   io_in_2_bits_pf_source,
  input  [4:0]   io_in_2_bits_cmd,
  input  [47:0]  io_in_2_bits_addr,
  input  [49:0]  io_in_2_bits_vaddr,
  input  [1:0]   io_in_2_bits_req_coh_state,
  input          io_in_2_bits_isBtoT,
  input  [3:0]   io_in_2_bits_occupy_way,
  input          io_in_2_bits_cancel,
  output         io_in_3_ready,
  input          io_in_3_valid,
  input  [3:0]   io_in_3_bits_source,
  input  [2:0]   io_in_3_bits_pf_source,
  input  [4:0]   io_in_3_bits_cmd,
  input  [47:0]  io_in_3_bits_addr,
  input  [49:0]  io_in_3_bits_vaddr,
  input  [1:0]   io_in_3_bits_req_coh_state,
  input          io_in_3_bits_isBtoT,
  input  [3:0]   io_in_3_bits_occupy_way,
  input          io_in_3_bits_cancel,
  input          io_out_ready,
  output         io_out_valid,
  output [3:0]   io_out_bits_source,
  output [2:0]   io_out_bits_pf_source,
  output [4:0]   io_out_bits_cmd,
  output [47:0]  io_out_bits_addr,
  output [49:0]  io_out_bits_vaddr,
  output         io_out_bits_full_overwrite,
  output [2:0]   io_out_bits_word_idx,
  output [127:0] io_out_bits_amo_data,
  output [15:0]  io_out_bits_amo_mask,
  output [127:0] io_out_bits_amo_cmp,
  output [1:0]   io_out_bits_req_coh_state,
  output [5:0]   io_out_bits_id,
  output         io_out_bits_isBtoT,
  output [3:0]   io_out_bits_occupy_way,
  output         io_out_bits_cancel,
  output [511:0] io_out_bits_store_data,
  output [63:0]  io_out_bits_store_mask
);
endmodule

module MissReadyGen(

  output        io_in_0_ready,
  input         io_in_0_valid,
  input  [3:0]  io_in_0_bits_source,
  input  [47:0] io_in_0_bits_addr,
  input  [49:0] io_in_0_bits_vaddr,
  output        io_in_1_ready,
  input         io_in_1_valid,
  input  [3:0]  io_in_1_bits_source,
  input  [47:0] io_in_1_bits_addr,
  input  [49:0] io_in_1_bits_vaddr,
  output        io_in_2_ready,
  input         io_in_2_valid,
  input  [3:0]  io_in_2_bits_source,
  input  [47:0] io_in_2_bits_addr,
  input  [49:0] io_in_2_bits_vaddr,
  output        io_in_3_ready,
  input  [3:0]  io_in_3_bits_source,
  input  [47:0] io_in_3_bits_addr,
  input  [49:0] io_in_3_bits_vaddr,
  output [3:0]  io_queryMQ_0_req_bits_source,
  output [47:0] io_queryMQ_0_req_bits_addr,
  output [49:0] io_queryMQ_0_req_bits_vaddr,
  input         io_queryMQ_0_ready,
  output [3:0]  io_queryMQ_1_req_bits_source,
  output [47:0] io_queryMQ_1_req_bits_addr,
  output [49:0] io_queryMQ_1_req_bits_vaddr,
  input         io_queryMQ_1_ready,
  output [3:0]  io_queryMQ_2_req_bits_source,
  output [47:0] io_queryMQ_2_req_bits_addr,
  output [49:0] io_queryMQ_2_req_bits_vaddr,
  input         io_queryMQ_2_ready,
  output [3:0]  io_queryMQ_3_req_bits_source,
  output [47:0] io_queryMQ_3_req_bits_addr,
  output [49:0] io_queryMQ_3_req_bits_vaddr,
  input         io_queryMQ_3_ready
);
endmodule
