// 自动生成：scripts/gen_loadqueue.py —— 勿手改
// 可读核 xs_LoadQueue_core 的端口列表（与 golden LoadQueue 同名扁平端口）。
  input  clock,
  input  reset,
  input  io_redirect_valid,
  input  io_redirect_bits_robIdx_flag,
  input  [7:0] io_redirect_bits_robIdx_value,
  input  io_redirect_bits_level,
  input  io_vecFeedback_0_valid,
  input  io_vecFeedback_0_bits_robidx_flag,
  input  [7:0] io_vecFeedback_0_bits_robidx_value,
  input  [6:0] io_vecFeedback_0_bits_uopidx,
  input  [63:0] io_vecFeedback_0_bits_vaddr,
  input  io_vecFeedback_0_bits_vaNeedExt,
  input  [49:0] io_vecFeedback_0_bits_gpaddr,
  input  io_vecFeedback_0_bits_feedback_0,
  input  io_vecFeedback_0_bits_feedback_1,
  input  io_vecFeedback_0_bits_exceptionVec_3,
  input  io_vecFeedback_0_bits_exceptionVec_4,
  input  io_vecFeedback_0_bits_exceptionVec_5,
  input  io_vecFeedback_0_bits_exceptionVec_13,
  input  io_vecFeedback_0_bits_exceptionVec_19,
  input  io_vecFeedback_0_bits_exceptionVec_21,
  input  io_vecFeedback_1_valid,
  input  io_vecFeedback_1_bits_robidx_flag,
  input  [7:0] io_vecFeedback_1_bits_robidx_value,
  input  [6:0] io_vecFeedback_1_bits_uopidx,
  input  [63:0] io_vecFeedback_1_bits_vaddr,
  input  io_vecFeedback_1_bits_vaNeedExt,
  input  [49:0] io_vecFeedback_1_bits_gpaddr,
  input  io_vecFeedback_1_bits_feedback_0,
  input  io_vecFeedback_1_bits_feedback_1,
  input  io_vecFeedback_1_bits_exceptionVec_3,
  input  io_vecFeedback_1_bits_exceptionVec_4,
  input  io_vecFeedback_1_bits_exceptionVec_5,
  input  io_vecFeedback_1_bits_exceptionVec_13,
  input  io_vecFeedback_1_bits_exceptionVec_19,
  input  io_vecFeedback_1_bits_exceptionVec_21,
  output io_enq_canAccept,
  input  io_enq_sqCanAccept,
  input  io_enq_needAlloc_0,
  input  io_enq_needAlloc_1,
  input  io_enq_needAlloc_2,
  input  io_enq_needAlloc_3,
  input  io_enq_needAlloc_4,
  input  io_enq_req_0_valid,
  input  [34:0] io_enq_req_0_bits_fuType,
  input  [6:0] io_enq_req_0_bits_uopIdx,
  input  io_enq_req_0_bits_robIdx_flag,
  input  [7:0] io_enq_req_0_bits_robIdx_value,
  input  io_enq_req_0_bits_lqIdx_flag,
  input  [6:0] io_enq_req_0_bits_lqIdx_value,
  input  [4:0] io_enq_req_0_bits_numLsElem,
  input  io_enq_req_1_valid,
  input  [34:0] io_enq_req_1_bits_fuType,
  input  [6:0] io_enq_req_1_bits_uopIdx,
  input  io_enq_req_1_bits_robIdx_flag,
  input  [7:0] io_enq_req_1_bits_robIdx_value,
  input  io_enq_req_1_bits_lqIdx_flag,
  input  [6:0] io_enq_req_1_bits_lqIdx_value,
  input  [4:0] io_enq_req_1_bits_numLsElem,
  input  io_enq_req_2_valid,
  input  [34:0] io_enq_req_2_bits_fuType,
  input  [6:0] io_enq_req_2_bits_uopIdx,
  input  io_enq_req_2_bits_robIdx_flag,
  input  [7:0] io_enq_req_2_bits_robIdx_value,
  input  io_enq_req_2_bits_lqIdx_flag,
  input  [6:0] io_enq_req_2_bits_lqIdx_value,
  input  [4:0] io_enq_req_2_bits_numLsElem,
  input  io_enq_req_3_valid,
  input  [34:0] io_enq_req_3_bits_fuType,
  input  [6:0] io_enq_req_3_bits_uopIdx,
  input  io_enq_req_3_bits_robIdx_flag,
  input  [7:0] io_enq_req_3_bits_robIdx_value,
  input  io_enq_req_3_bits_lqIdx_flag,
  input  [6:0] io_enq_req_3_bits_lqIdx_value,
  input  [4:0] io_enq_req_3_bits_numLsElem,
  input  io_enq_req_4_valid,
  input  [34:0] io_enq_req_4_bits_fuType,
  input  [6:0] io_enq_req_4_bits_uopIdx,
  input  io_enq_req_4_bits_robIdx_flag,
  input  [7:0] io_enq_req_4_bits_robIdx_value,
  input  io_enq_req_4_bits_lqIdx_flag,
  input  [6:0] io_enq_req_4_bits_lqIdx_value,
  input  [4:0] io_enq_req_4_bits_numLsElem,
  input  io_enq_req_5_valid,
  input  [34:0] io_enq_req_5_bits_fuType,
  input  [6:0] io_enq_req_5_bits_uopIdx,
  input  io_enq_req_5_bits_robIdx_flag,
  input  [7:0] io_enq_req_5_bits_robIdx_value,
  input  io_enq_req_5_bits_lqIdx_flag,
  input  [6:0] io_enq_req_5_bits_lqIdx_value,
  input  [4:0] io_enq_req_5_bits_numLsElem,
  output io_ldu_stld_nuke_query_0_req_ready,
  input  io_ldu_stld_nuke_query_0_req_valid,
  input  io_ldu_stld_nuke_query_0_req_bits_uop_preDecodeInfo_isRVC,
  input  io_ldu_stld_nuke_query_0_req_bits_uop_ftqPtr_flag,
  input  [5:0] io_ldu_stld_nuke_query_0_req_bits_uop_ftqPtr_value,
  input  [3:0] io_ldu_stld_nuke_query_0_req_bits_uop_ftqOffset,
  input  io_ldu_stld_nuke_query_0_req_bits_uop_robIdx_flag,
  input  [7:0] io_ldu_stld_nuke_query_0_req_bits_uop_robIdx_value,
  input  io_ldu_stld_nuke_query_0_req_bits_uop_sqIdx_flag,
  input  [5:0] io_ldu_stld_nuke_query_0_req_bits_uop_sqIdx_value,
  input  [15:0] io_ldu_stld_nuke_query_0_req_bits_mask,
  input  [47:0] io_ldu_stld_nuke_query_0_req_bits_paddr,
  input  io_ldu_stld_nuke_query_0_req_bits_data_valid,
  input  io_ldu_stld_nuke_query_0_revoke,
  output io_ldu_stld_nuke_query_1_req_ready,
  input  io_ldu_stld_nuke_query_1_req_valid,
  input  io_ldu_stld_nuke_query_1_req_bits_uop_preDecodeInfo_isRVC,
  input  io_ldu_stld_nuke_query_1_req_bits_uop_ftqPtr_flag,
  input  [5:0] io_ldu_stld_nuke_query_1_req_bits_uop_ftqPtr_value,
  input  [3:0] io_ldu_stld_nuke_query_1_req_bits_uop_ftqOffset,
  input  io_ldu_stld_nuke_query_1_req_bits_uop_robIdx_flag,
  input  [7:0] io_ldu_stld_nuke_query_1_req_bits_uop_robIdx_value,
  input  io_ldu_stld_nuke_query_1_req_bits_uop_sqIdx_flag,
  input  [5:0] io_ldu_stld_nuke_query_1_req_bits_uop_sqIdx_value,
  input  [15:0] io_ldu_stld_nuke_query_1_req_bits_mask,
  input  [47:0] io_ldu_stld_nuke_query_1_req_bits_paddr,
  input  io_ldu_stld_nuke_query_1_req_bits_data_valid,
  input  io_ldu_stld_nuke_query_1_revoke,
  output io_ldu_stld_nuke_query_2_req_ready,
  input  io_ldu_stld_nuke_query_2_req_valid,
  input  io_ldu_stld_nuke_query_2_req_bits_uop_preDecodeInfo_isRVC,
  input  io_ldu_stld_nuke_query_2_req_bits_uop_ftqPtr_flag,
  input  [5:0] io_ldu_stld_nuke_query_2_req_bits_uop_ftqPtr_value,
  input  [3:0] io_ldu_stld_nuke_query_2_req_bits_uop_ftqOffset,
  input  io_ldu_stld_nuke_query_2_req_bits_uop_robIdx_flag,
  input  [7:0] io_ldu_stld_nuke_query_2_req_bits_uop_robIdx_value,
  input  io_ldu_stld_nuke_query_2_req_bits_uop_sqIdx_flag,
  input  [5:0] io_ldu_stld_nuke_query_2_req_bits_uop_sqIdx_value,
  input  [15:0] io_ldu_stld_nuke_query_2_req_bits_mask,
  input  [47:0] io_ldu_stld_nuke_query_2_req_bits_paddr,
  input  io_ldu_stld_nuke_query_2_req_bits_data_valid,
  input  io_ldu_stld_nuke_query_2_revoke,
  output io_ldu_ldld_nuke_query_0_req_ready,
  input  io_ldu_ldld_nuke_query_0_req_valid,
  input  io_ldu_ldld_nuke_query_0_req_bits_uop_robIdx_flag,
  input  [7:0] io_ldu_ldld_nuke_query_0_req_bits_uop_robIdx_value,
  input  io_ldu_ldld_nuke_query_0_req_bits_uop_lqIdx_flag,
  input  [6:0] io_ldu_ldld_nuke_query_0_req_bits_uop_lqIdx_value,
  input  [47:0] io_ldu_ldld_nuke_query_0_req_bits_paddr,
  input  io_ldu_ldld_nuke_query_0_req_bits_data_valid,
  input  io_ldu_ldld_nuke_query_0_req_bits_is_nc,
  output io_ldu_ldld_nuke_query_0_resp_valid,
  output io_ldu_ldld_nuke_query_0_resp_bits_rep_frm_fetch,
  input  io_ldu_ldld_nuke_query_0_revoke,
  output io_ldu_ldld_nuke_query_1_req_ready,
  input  io_ldu_ldld_nuke_query_1_req_valid,
  input  io_ldu_ldld_nuke_query_1_req_bits_uop_robIdx_flag,
  input  [7:0] io_ldu_ldld_nuke_query_1_req_bits_uop_robIdx_value,
  input  io_ldu_ldld_nuke_query_1_req_bits_uop_lqIdx_flag,
  input  [6:0] io_ldu_ldld_nuke_query_1_req_bits_uop_lqIdx_value,
  input  [47:0] io_ldu_ldld_nuke_query_1_req_bits_paddr,
  input  io_ldu_ldld_nuke_query_1_req_bits_data_valid,
  input  io_ldu_ldld_nuke_query_1_req_bits_is_nc,
  output io_ldu_ldld_nuke_query_1_resp_valid,
  output io_ldu_ldld_nuke_query_1_resp_bits_rep_frm_fetch,
  input  io_ldu_ldld_nuke_query_1_revoke,
  output io_ldu_ldld_nuke_query_2_req_ready,
  input  io_ldu_ldld_nuke_query_2_req_valid,
  input  io_ldu_ldld_nuke_query_2_req_bits_uop_robIdx_flag,
  input  [7:0] io_ldu_ldld_nuke_query_2_req_bits_uop_robIdx_value,
  input  io_ldu_ldld_nuke_query_2_req_bits_uop_lqIdx_flag,
  input  [6:0] io_ldu_ldld_nuke_query_2_req_bits_uop_lqIdx_value,
  input  [47:0] io_ldu_ldld_nuke_query_2_req_bits_paddr,
  input  io_ldu_ldld_nuke_query_2_req_bits_data_valid,
  input  io_ldu_ldld_nuke_query_2_req_bits_is_nc,
  output io_ldu_ldld_nuke_query_2_resp_valid,
  output io_ldu_ldld_nuke_query_2_resp_bits_rep_frm_fetch,
  input  io_ldu_ldld_nuke_query_2_revoke,
  input  io_ldu_ldin_0_valid,
  input  io_ldu_ldin_0_bits_uop_exceptionVec_0,
  input  io_ldu_ldin_0_bits_uop_exceptionVec_1,
  input  io_ldu_ldin_0_bits_uop_exceptionVec_2,
  input  io_ldu_ldin_0_bits_uop_exceptionVec_3,
  input  io_ldu_ldin_0_bits_uop_exceptionVec_4,
  input  io_ldu_ldin_0_bits_uop_exceptionVec_5,
  input  io_ldu_ldin_0_bits_uop_exceptionVec_6,
  input  io_ldu_ldin_0_bits_uop_exceptionVec_7,
  input  io_ldu_ldin_0_bits_uop_exceptionVec_8,
  input  io_ldu_ldin_0_bits_uop_exceptionVec_9,
  input  io_ldu_ldin_0_bits_uop_exceptionVec_10,
  input  io_ldu_ldin_0_bits_uop_exceptionVec_11,
  input  io_ldu_ldin_0_bits_uop_exceptionVec_12,
  input  io_ldu_ldin_0_bits_uop_exceptionVec_13,
  input  io_ldu_ldin_0_bits_uop_exceptionVec_14,
  input  io_ldu_ldin_0_bits_uop_exceptionVec_15,
  input  io_ldu_ldin_0_bits_uop_exceptionVec_16,
  input  io_ldu_ldin_0_bits_uop_exceptionVec_17,
  input  io_ldu_ldin_0_bits_uop_exceptionVec_18,
  input  io_ldu_ldin_0_bits_uop_exceptionVec_19,
  input  io_ldu_ldin_0_bits_uop_exceptionVec_20,
  input  io_ldu_ldin_0_bits_uop_exceptionVec_21,
  input  io_ldu_ldin_0_bits_uop_exceptionVec_22,
  input  io_ldu_ldin_0_bits_uop_exceptionVec_23,
  input  [3:0] io_ldu_ldin_0_bits_uop_trigger,
  input  io_ldu_ldin_0_bits_uop_preDecodeInfo_isRVC,
  input  io_ldu_ldin_0_bits_uop_ftqPtr_flag,
  input  [5:0] io_ldu_ldin_0_bits_uop_ftqPtr_value,
  input  [3:0] io_ldu_ldin_0_bits_uop_ftqOffset,
  input  [8:0] io_ldu_ldin_0_bits_uop_fuOpType,
  input  io_ldu_ldin_0_bits_uop_rfWen,
  input  io_ldu_ldin_0_bits_uop_fpWen,
  input  [7:0] io_ldu_ldin_0_bits_uop_vpu_vstart,
  input  [1:0] io_ldu_ldin_0_bits_uop_vpu_veew,
  input  [6:0] io_ldu_ldin_0_bits_uop_uopIdx,
  input  [7:0] io_ldu_ldin_0_bits_uop_pdest,
  input  io_ldu_ldin_0_bits_uop_robIdx_flag,
  input  [7:0] io_ldu_ldin_0_bits_uop_robIdx_value,
  input  [63:0] io_ldu_ldin_0_bits_uop_debugInfo_enqRsTime,
  input  [63:0] io_ldu_ldin_0_bits_uop_debugInfo_selectTime,
  input  [63:0] io_ldu_ldin_0_bits_uop_debugInfo_issueTime,
  input  io_ldu_ldin_0_bits_uop_storeSetHit,
  input  io_ldu_ldin_0_bits_uop_waitForRobIdx_flag,
  input  [7:0] io_ldu_ldin_0_bits_uop_waitForRobIdx_value,
  input  io_ldu_ldin_0_bits_uop_loadWaitBit,
  input  io_ldu_ldin_0_bits_uop_loadWaitStrict,
  input  io_ldu_ldin_0_bits_uop_lqIdx_flag,
  input  [6:0] io_ldu_ldin_0_bits_uop_lqIdx_value,
  input  io_ldu_ldin_0_bits_uop_sqIdx_flag,
  input  [5:0] io_ldu_ldin_0_bits_uop_sqIdx_value,
  input  [49:0] io_ldu_ldin_0_bits_vaddr,
  input  [63:0] io_ldu_ldin_0_bits_fullva,
  input  io_ldu_ldin_0_bits_vaNeedExt,
  input  [47:0] io_ldu_ldin_0_bits_paddr,
  input  [63:0] io_ldu_ldin_0_bits_gpaddr,
  input  [15:0] io_ldu_ldin_0_bits_mask,
  input  io_ldu_ldin_0_bits_tlbMiss,
  input  io_ldu_ldin_0_bits_nc,
  input  io_ldu_ldin_0_bits_mmio,
  input  io_ldu_ldin_0_bits_memBackTypeMM,
  input  io_ldu_ldin_0_bits_isHyper,
  input  io_ldu_ldin_0_bits_isForVSnonLeafPTE,
  input  io_ldu_ldin_0_bits_isvec,
  input  io_ldu_ldin_0_bits_is128bit,
  input  [7:0] io_ldu_ldin_0_bits_elemIdx,
  input  [2:0] io_ldu_ldin_0_bits_alignedType,
  input  [3:0] io_ldu_ldin_0_bits_mbIndex,
  input  [3:0] io_ldu_ldin_0_bits_reg_offset,
  input  [7:0] io_ldu_ldin_0_bits_elemIdxInsideVd,
  input  io_ldu_ldin_0_bits_vecActive,
  input  io_ldu_ldin_0_bits_isLoadReplay,
  input  io_ldu_ldin_0_bits_handledByMSHR,
  input  [6:0] io_ldu_ldin_0_bits_schedIndex,
  input  io_ldu_ldin_0_bits_updateAddrValid,
  input  [3:0] io_ldu_ldin_0_bits_rep_info_mshr_id,
  input  io_ldu_ldin_0_bits_rep_info_full_fwd,
  input  io_ldu_ldin_0_bits_rep_info_data_inv_sq_idx_flag,
  input  [5:0] io_ldu_ldin_0_bits_rep_info_data_inv_sq_idx_value,
  input  io_ldu_ldin_0_bits_rep_info_addr_inv_sq_idx_flag,
  input  [5:0] io_ldu_ldin_0_bits_rep_info_addr_inv_sq_idx_value,
  input  io_ldu_ldin_0_bits_rep_info_last_beat,
  input  io_ldu_ldin_0_bits_rep_info_cause_0,
  input  io_ldu_ldin_0_bits_rep_info_cause_1,
  input  io_ldu_ldin_0_bits_rep_info_cause_2,
  input  io_ldu_ldin_0_bits_rep_info_cause_3,
  input  io_ldu_ldin_0_bits_rep_info_cause_4,
  input  io_ldu_ldin_0_bits_rep_info_cause_5,
  input  io_ldu_ldin_0_bits_rep_info_cause_6,
  input  io_ldu_ldin_0_bits_rep_info_cause_7,
  input  io_ldu_ldin_0_bits_rep_info_cause_8,
  input  io_ldu_ldin_0_bits_rep_info_cause_9,
  input  io_ldu_ldin_0_bits_rep_info_cause_10,
  input  [3:0] io_ldu_ldin_0_bits_rep_info_tlb_id,
  input  io_ldu_ldin_0_bits_rep_info_tlb_full,
  input  io_ldu_ldin_0_bits_nc_with_data,
  input  io_ldu_ldin_1_valid,
  input  io_ldu_ldin_1_bits_uop_exceptionVec_0,
  input  io_ldu_ldin_1_bits_uop_exceptionVec_1,
  input  io_ldu_ldin_1_bits_uop_exceptionVec_2,
  input  io_ldu_ldin_1_bits_uop_exceptionVec_3,
  input  io_ldu_ldin_1_bits_uop_exceptionVec_4,
  input  io_ldu_ldin_1_bits_uop_exceptionVec_5,
  input  io_ldu_ldin_1_bits_uop_exceptionVec_6,
  input  io_ldu_ldin_1_bits_uop_exceptionVec_7,
  input  io_ldu_ldin_1_bits_uop_exceptionVec_8,
  input  io_ldu_ldin_1_bits_uop_exceptionVec_9,
  input  io_ldu_ldin_1_bits_uop_exceptionVec_10,
  input  io_ldu_ldin_1_bits_uop_exceptionVec_11,
  input  io_ldu_ldin_1_bits_uop_exceptionVec_12,
  input  io_ldu_ldin_1_bits_uop_exceptionVec_13,
  input  io_ldu_ldin_1_bits_uop_exceptionVec_14,
  input  io_ldu_ldin_1_bits_uop_exceptionVec_15,
  input  io_ldu_ldin_1_bits_uop_exceptionVec_16,
  input  io_ldu_ldin_1_bits_uop_exceptionVec_17,
  input  io_ldu_ldin_1_bits_uop_exceptionVec_18,
  input  io_ldu_ldin_1_bits_uop_exceptionVec_19,
  input  io_ldu_ldin_1_bits_uop_exceptionVec_20,
  input  io_ldu_ldin_1_bits_uop_exceptionVec_21,
  input  io_ldu_ldin_1_bits_uop_exceptionVec_22,
  input  io_ldu_ldin_1_bits_uop_exceptionVec_23,
  input  [3:0] io_ldu_ldin_1_bits_uop_trigger,
  input  io_ldu_ldin_1_bits_uop_preDecodeInfo_isRVC,
  input  io_ldu_ldin_1_bits_uop_ftqPtr_flag,
  input  [5:0] io_ldu_ldin_1_bits_uop_ftqPtr_value,
  input  [3:0] io_ldu_ldin_1_bits_uop_ftqOffset,
  input  [8:0] io_ldu_ldin_1_bits_uop_fuOpType,
  input  io_ldu_ldin_1_bits_uop_rfWen,
  input  io_ldu_ldin_1_bits_uop_fpWen,
  input  [7:0] io_ldu_ldin_1_bits_uop_vpu_vstart,
  input  [1:0] io_ldu_ldin_1_bits_uop_vpu_veew,
  input  [6:0] io_ldu_ldin_1_bits_uop_uopIdx,
  input  [7:0] io_ldu_ldin_1_bits_uop_pdest,
  input  io_ldu_ldin_1_bits_uop_robIdx_flag,
  input  [7:0] io_ldu_ldin_1_bits_uop_robIdx_value,
  input  [63:0] io_ldu_ldin_1_bits_uop_debugInfo_enqRsTime,
  input  [63:0] io_ldu_ldin_1_bits_uop_debugInfo_selectTime,
  input  [63:0] io_ldu_ldin_1_bits_uop_debugInfo_issueTime,
  input  io_ldu_ldin_1_bits_uop_storeSetHit,
  input  io_ldu_ldin_1_bits_uop_waitForRobIdx_flag,
  input  [7:0] io_ldu_ldin_1_bits_uop_waitForRobIdx_value,
  input  io_ldu_ldin_1_bits_uop_loadWaitBit,
  input  io_ldu_ldin_1_bits_uop_loadWaitStrict,
  input  io_ldu_ldin_1_bits_uop_lqIdx_flag,
  input  [6:0] io_ldu_ldin_1_bits_uop_lqIdx_value,
  input  io_ldu_ldin_1_bits_uop_sqIdx_flag,
  input  [5:0] io_ldu_ldin_1_bits_uop_sqIdx_value,
  input  [49:0] io_ldu_ldin_1_bits_vaddr,
  input  [63:0] io_ldu_ldin_1_bits_fullva,
  input  io_ldu_ldin_1_bits_vaNeedExt,
  input  [47:0] io_ldu_ldin_1_bits_paddr,
  input  [63:0] io_ldu_ldin_1_bits_gpaddr,
  input  [15:0] io_ldu_ldin_1_bits_mask,
  input  io_ldu_ldin_1_bits_tlbMiss,
  input  io_ldu_ldin_1_bits_nc,
  input  io_ldu_ldin_1_bits_mmio,
  input  io_ldu_ldin_1_bits_memBackTypeMM,
  input  io_ldu_ldin_1_bits_isHyper,
  input  io_ldu_ldin_1_bits_isForVSnonLeafPTE,
  input  io_ldu_ldin_1_bits_isvec,
  input  io_ldu_ldin_1_bits_is128bit,
  input  [7:0] io_ldu_ldin_1_bits_elemIdx,
  input  [2:0] io_ldu_ldin_1_bits_alignedType,
  input  [3:0] io_ldu_ldin_1_bits_mbIndex,
  input  [3:0] io_ldu_ldin_1_bits_reg_offset,
  input  [7:0] io_ldu_ldin_1_bits_elemIdxInsideVd,
  input  io_ldu_ldin_1_bits_vecActive,
  input  io_ldu_ldin_1_bits_isLoadReplay,
  input  io_ldu_ldin_1_bits_handledByMSHR,
  input  [6:0] io_ldu_ldin_1_bits_schedIndex,
  input  io_ldu_ldin_1_bits_updateAddrValid,
  input  [3:0] io_ldu_ldin_1_bits_rep_info_mshr_id,
  input  io_ldu_ldin_1_bits_rep_info_full_fwd,
  input  io_ldu_ldin_1_bits_rep_info_data_inv_sq_idx_flag,
  input  [5:0] io_ldu_ldin_1_bits_rep_info_data_inv_sq_idx_value,
  input  io_ldu_ldin_1_bits_rep_info_addr_inv_sq_idx_flag,
  input  [5:0] io_ldu_ldin_1_bits_rep_info_addr_inv_sq_idx_value,
  input  io_ldu_ldin_1_bits_rep_info_last_beat,
  input  io_ldu_ldin_1_bits_rep_info_cause_0,
  input  io_ldu_ldin_1_bits_rep_info_cause_1,
  input  io_ldu_ldin_1_bits_rep_info_cause_2,
  input  io_ldu_ldin_1_bits_rep_info_cause_3,
  input  io_ldu_ldin_1_bits_rep_info_cause_4,
  input  io_ldu_ldin_1_bits_rep_info_cause_5,
  input  io_ldu_ldin_1_bits_rep_info_cause_6,
  input  io_ldu_ldin_1_bits_rep_info_cause_7,
  input  io_ldu_ldin_1_bits_rep_info_cause_8,
  input  io_ldu_ldin_1_bits_rep_info_cause_9,
  input  io_ldu_ldin_1_bits_rep_info_cause_10,
  input  [3:0] io_ldu_ldin_1_bits_rep_info_tlb_id,
  input  io_ldu_ldin_1_bits_rep_info_tlb_full,
  input  io_ldu_ldin_1_bits_nc_with_data,
  input  io_ldu_ldin_2_valid,
  input  io_ldu_ldin_2_bits_uop_exceptionVec_0,
  input  io_ldu_ldin_2_bits_uop_exceptionVec_1,
  input  io_ldu_ldin_2_bits_uop_exceptionVec_2,
  input  io_ldu_ldin_2_bits_uop_exceptionVec_3,
  input  io_ldu_ldin_2_bits_uop_exceptionVec_4,
  input  io_ldu_ldin_2_bits_uop_exceptionVec_5,
  input  io_ldu_ldin_2_bits_uop_exceptionVec_6,
  input  io_ldu_ldin_2_bits_uop_exceptionVec_7,
  input  io_ldu_ldin_2_bits_uop_exceptionVec_8,
  input  io_ldu_ldin_2_bits_uop_exceptionVec_9,
  input  io_ldu_ldin_2_bits_uop_exceptionVec_10,
  input  io_ldu_ldin_2_bits_uop_exceptionVec_11,
  input  io_ldu_ldin_2_bits_uop_exceptionVec_12,
  input  io_ldu_ldin_2_bits_uop_exceptionVec_13,
  input  io_ldu_ldin_2_bits_uop_exceptionVec_14,
  input  io_ldu_ldin_2_bits_uop_exceptionVec_15,
  input  io_ldu_ldin_2_bits_uop_exceptionVec_16,
  input  io_ldu_ldin_2_bits_uop_exceptionVec_17,
  input  io_ldu_ldin_2_bits_uop_exceptionVec_18,
  input  io_ldu_ldin_2_bits_uop_exceptionVec_19,
  input  io_ldu_ldin_2_bits_uop_exceptionVec_20,
  input  io_ldu_ldin_2_bits_uop_exceptionVec_21,
  input  io_ldu_ldin_2_bits_uop_exceptionVec_22,
  input  io_ldu_ldin_2_bits_uop_exceptionVec_23,
  input  [3:0] io_ldu_ldin_2_bits_uop_trigger,
  input  io_ldu_ldin_2_bits_uop_preDecodeInfo_isRVC,
  input  io_ldu_ldin_2_bits_uop_ftqPtr_flag,
  input  [5:0] io_ldu_ldin_2_bits_uop_ftqPtr_value,
  input  [3:0] io_ldu_ldin_2_bits_uop_ftqOffset,
  input  [8:0] io_ldu_ldin_2_bits_uop_fuOpType,
  input  io_ldu_ldin_2_bits_uop_rfWen,
  input  io_ldu_ldin_2_bits_uop_fpWen,
  input  [7:0] io_ldu_ldin_2_bits_uop_vpu_vstart,
  input  [1:0] io_ldu_ldin_2_bits_uop_vpu_veew,
  input  [6:0] io_ldu_ldin_2_bits_uop_uopIdx,
  input  [7:0] io_ldu_ldin_2_bits_uop_pdest,
  input  io_ldu_ldin_2_bits_uop_robIdx_flag,
  input  [7:0] io_ldu_ldin_2_bits_uop_robIdx_value,
  input  [63:0] io_ldu_ldin_2_bits_uop_debugInfo_enqRsTime,
  input  [63:0] io_ldu_ldin_2_bits_uop_debugInfo_selectTime,
  input  [63:0] io_ldu_ldin_2_bits_uop_debugInfo_issueTime,
  input  io_ldu_ldin_2_bits_uop_storeSetHit,
  input  io_ldu_ldin_2_bits_uop_waitForRobIdx_flag,
  input  [7:0] io_ldu_ldin_2_bits_uop_waitForRobIdx_value,
  input  io_ldu_ldin_2_bits_uop_loadWaitBit,
  input  io_ldu_ldin_2_bits_uop_loadWaitStrict,
  input  io_ldu_ldin_2_bits_uop_lqIdx_flag,
  input  [6:0] io_ldu_ldin_2_bits_uop_lqIdx_value,
  input  io_ldu_ldin_2_bits_uop_sqIdx_flag,
  input  [5:0] io_ldu_ldin_2_bits_uop_sqIdx_value,
  input  [49:0] io_ldu_ldin_2_bits_vaddr,
  input  [63:0] io_ldu_ldin_2_bits_fullva,
  input  io_ldu_ldin_2_bits_vaNeedExt,
  input  [47:0] io_ldu_ldin_2_bits_paddr,
  input  [63:0] io_ldu_ldin_2_bits_gpaddr,
  input  [15:0] io_ldu_ldin_2_bits_mask,
  input  io_ldu_ldin_2_bits_tlbMiss,
  input  io_ldu_ldin_2_bits_nc,
  input  io_ldu_ldin_2_bits_mmio,
  input  io_ldu_ldin_2_bits_memBackTypeMM,
  input  io_ldu_ldin_2_bits_isHyper,
  input  io_ldu_ldin_2_bits_isForVSnonLeafPTE,
  input  io_ldu_ldin_2_bits_isvec,
  input  io_ldu_ldin_2_bits_is128bit,
  input  [7:0] io_ldu_ldin_2_bits_elemIdx,
  input  [2:0] io_ldu_ldin_2_bits_alignedType,
  input  [3:0] io_ldu_ldin_2_bits_mbIndex,
  input  [3:0] io_ldu_ldin_2_bits_reg_offset,
  input  [7:0] io_ldu_ldin_2_bits_elemIdxInsideVd,
  input  io_ldu_ldin_2_bits_vecActive,
  input  io_ldu_ldin_2_bits_isLoadReplay,
  input  io_ldu_ldin_2_bits_handledByMSHR,
  input  [6:0] io_ldu_ldin_2_bits_schedIndex,
  input  io_ldu_ldin_2_bits_updateAddrValid,
  input  [3:0] io_ldu_ldin_2_bits_rep_info_mshr_id,
  input  io_ldu_ldin_2_bits_rep_info_full_fwd,
  input  io_ldu_ldin_2_bits_rep_info_data_inv_sq_idx_flag,
  input  [5:0] io_ldu_ldin_2_bits_rep_info_data_inv_sq_idx_value,
  input  io_ldu_ldin_2_bits_rep_info_addr_inv_sq_idx_flag,
  input  [5:0] io_ldu_ldin_2_bits_rep_info_addr_inv_sq_idx_value,
  input  io_ldu_ldin_2_bits_rep_info_last_beat,
  input  io_ldu_ldin_2_bits_rep_info_cause_0,
  input  io_ldu_ldin_2_bits_rep_info_cause_1,
  input  io_ldu_ldin_2_bits_rep_info_cause_2,
  input  io_ldu_ldin_2_bits_rep_info_cause_3,
  input  io_ldu_ldin_2_bits_rep_info_cause_4,
  input  io_ldu_ldin_2_bits_rep_info_cause_5,
  input  io_ldu_ldin_2_bits_rep_info_cause_6,
  input  io_ldu_ldin_2_bits_rep_info_cause_7,
  input  io_ldu_ldin_2_bits_rep_info_cause_8,
  input  io_ldu_ldin_2_bits_rep_info_cause_9,
  input  io_ldu_ldin_2_bits_rep_info_cause_10,
  input  [3:0] io_ldu_ldin_2_bits_rep_info_tlb_id,
  input  io_ldu_ldin_2_bits_rep_info_tlb_full,
  input  io_ldu_ldin_2_bits_nc_with_data,
  input  io_sta_storeAddrIn_0_valid,
  input  [5:0] io_sta_storeAddrIn_0_bits_uop_ftqPtr_value,
  input  [3:0] io_sta_storeAddrIn_0_bits_uop_ftqOffset,
  input  io_sta_storeAddrIn_0_bits_uop_robIdx_flag,
  input  [7:0] io_sta_storeAddrIn_0_bits_uop_robIdx_value,
  input  io_sta_storeAddrIn_0_bits_uop_sqIdx_flag,
  input  [5:0] io_sta_storeAddrIn_0_bits_uop_sqIdx_value,
  input  [47:0] io_sta_storeAddrIn_0_bits_paddr,
  input  [15:0] io_sta_storeAddrIn_0_bits_mask,
  input  io_sta_storeAddrIn_0_bits_wlineflag,
  input  io_sta_storeAddrIn_0_bits_miss,
  input  io_sta_storeAddrIn_1_valid,
  input  [5:0] io_sta_storeAddrIn_1_bits_uop_ftqPtr_value,
  input  [3:0] io_sta_storeAddrIn_1_bits_uop_ftqOffset,
  input  io_sta_storeAddrIn_1_bits_uop_robIdx_flag,
  input  [7:0] io_sta_storeAddrIn_1_bits_uop_robIdx_value,
  input  io_sta_storeAddrIn_1_bits_uop_sqIdx_flag,
  input  [5:0] io_sta_storeAddrIn_1_bits_uop_sqIdx_value,
  input  [47:0] io_sta_storeAddrIn_1_bits_paddr,
  input  [15:0] io_sta_storeAddrIn_1_bits_mask,
  input  io_sta_storeAddrIn_1_bits_wlineflag,
  input  io_sta_storeAddrIn_1_bits_miss,
  input  io_std_storeDataIn_0_valid,
  input  io_std_storeDataIn_0_bits_uop_sqIdx_flag,
  input  [5:0] io_std_storeDataIn_0_bits_uop_sqIdx_value,
  input  io_std_storeDataIn_1_valid,
  input  io_std_storeDataIn_1_bits_uop_sqIdx_flag,
  input  [5:0] io_std_storeDataIn_1_bits_uop_sqIdx_value,
  input  io_sq_stAddrReadySqPtr_flag,
  input  [5:0] io_sq_stAddrReadySqPtr_value,
  input  io_sq_stAddrReadyVec_0,
  input  io_sq_stAddrReadyVec_1,
  input  io_sq_stAddrReadyVec_2,
  input  io_sq_stAddrReadyVec_3,
  input  io_sq_stAddrReadyVec_4,
  input  io_sq_stAddrReadyVec_5,
  input  io_sq_stAddrReadyVec_6,
  input  io_sq_stAddrReadyVec_7,
  input  io_sq_stAddrReadyVec_8,
  input  io_sq_stAddrReadyVec_9,
  input  io_sq_stAddrReadyVec_10,
  input  io_sq_stAddrReadyVec_11,
  input  io_sq_stAddrReadyVec_12,
  input  io_sq_stAddrReadyVec_13,
  input  io_sq_stAddrReadyVec_14,
  input  io_sq_stAddrReadyVec_15,
  input  io_sq_stAddrReadyVec_16,
  input  io_sq_stAddrReadyVec_17,
  input  io_sq_stAddrReadyVec_18,
  input  io_sq_stAddrReadyVec_19,
  input  io_sq_stAddrReadyVec_20,
  input  io_sq_stAddrReadyVec_21,
  input  io_sq_stAddrReadyVec_22,
  input  io_sq_stAddrReadyVec_23,
  input  io_sq_stAddrReadyVec_24,
  input  io_sq_stAddrReadyVec_25,
  input  io_sq_stAddrReadyVec_26,
  input  io_sq_stAddrReadyVec_27,
  input  io_sq_stAddrReadyVec_28,
  input  io_sq_stAddrReadyVec_29,
  input  io_sq_stAddrReadyVec_30,
  input  io_sq_stAddrReadyVec_31,
  input  io_sq_stAddrReadyVec_32,
  input  io_sq_stAddrReadyVec_33,
  input  io_sq_stAddrReadyVec_34,
  input  io_sq_stAddrReadyVec_35,
  input  io_sq_stAddrReadyVec_36,
  input  io_sq_stAddrReadyVec_37,
  input  io_sq_stAddrReadyVec_38,
  input  io_sq_stAddrReadyVec_39,
  input  io_sq_stAddrReadyVec_40,
  input  io_sq_stAddrReadyVec_41,
  input  io_sq_stAddrReadyVec_42,
  input  io_sq_stAddrReadyVec_43,
  input  io_sq_stAddrReadyVec_44,
  input  io_sq_stAddrReadyVec_45,
  input  io_sq_stAddrReadyVec_46,
  input  io_sq_stAddrReadyVec_47,
  input  io_sq_stAddrReadyVec_48,
  input  io_sq_stAddrReadyVec_49,
  input  io_sq_stAddrReadyVec_50,
  input  io_sq_stAddrReadyVec_51,
  input  io_sq_stAddrReadyVec_52,
  input  io_sq_stAddrReadyVec_53,
  input  io_sq_stAddrReadyVec_54,
  input  io_sq_stAddrReadyVec_55,
  input  io_sq_stDataReadySqPtr_flag,
  input  [5:0] io_sq_stDataReadySqPtr_value,
  input  io_sq_stDataReadyVec_0,
  input  io_sq_stDataReadyVec_1,
  input  io_sq_stDataReadyVec_2,
  input  io_sq_stDataReadyVec_3,
  input  io_sq_stDataReadyVec_4,
  input  io_sq_stDataReadyVec_5,
  input  io_sq_stDataReadyVec_6,
  input  io_sq_stDataReadyVec_7,
  input  io_sq_stDataReadyVec_8,
  input  io_sq_stDataReadyVec_9,
  input  io_sq_stDataReadyVec_10,
  input  io_sq_stDataReadyVec_11,
  input  io_sq_stDataReadyVec_12,
  input  io_sq_stDataReadyVec_13,
  input  io_sq_stDataReadyVec_14,
  input  io_sq_stDataReadyVec_15,
  input  io_sq_stDataReadyVec_16,
  input  io_sq_stDataReadyVec_17,
  input  io_sq_stDataReadyVec_18,
  input  io_sq_stDataReadyVec_19,
  input  io_sq_stDataReadyVec_20,
  input  io_sq_stDataReadyVec_21,
  input  io_sq_stDataReadyVec_22,
  input  io_sq_stDataReadyVec_23,
  input  io_sq_stDataReadyVec_24,
  input  io_sq_stDataReadyVec_25,
  input  io_sq_stDataReadyVec_26,
  input  io_sq_stDataReadyVec_27,
  input  io_sq_stDataReadyVec_28,
  input  io_sq_stDataReadyVec_29,
  input  io_sq_stDataReadyVec_30,
  input  io_sq_stDataReadyVec_31,
  input  io_sq_stDataReadyVec_32,
  input  io_sq_stDataReadyVec_33,
  input  io_sq_stDataReadyVec_34,
  input  io_sq_stDataReadyVec_35,
  input  io_sq_stDataReadyVec_36,
  input  io_sq_stDataReadyVec_37,
  input  io_sq_stDataReadyVec_38,
  input  io_sq_stDataReadyVec_39,
  input  io_sq_stDataReadyVec_40,
  input  io_sq_stDataReadyVec_41,
  input  io_sq_stDataReadyVec_42,
  input  io_sq_stDataReadyVec_43,
  input  io_sq_stDataReadyVec_44,
  input  io_sq_stDataReadyVec_45,
  input  io_sq_stDataReadyVec_46,
  input  io_sq_stDataReadyVec_47,
  input  io_sq_stDataReadyVec_48,
  input  io_sq_stDataReadyVec_49,
  input  io_sq_stDataReadyVec_50,
  input  io_sq_stDataReadyVec_51,
  input  io_sq_stDataReadyVec_52,
  input  io_sq_stDataReadyVec_53,
  input  io_sq_stDataReadyVec_54,
  input  io_sq_stDataReadyVec_55,
  input  io_sq_stIssuePtr_flag,
  input  [5:0] io_sq_stIssuePtr_value,
  input  io_sq_sqEmpty,
  input  io_ldout_2_ready,
  output io_ldout_2_valid,
  output io_ldout_2_bits_uop_exceptionVec_0,
  output io_ldout_2_bits_uop_exceptionVec_1,
  output io_ldout_2_bits_uop_exceptionVec_2,
  output io_ldout_2_bits_uop_exceptionVec_3,
  output io_ldout_2_bits_uop_exceptionVec_4,
  output io_ldout_2_bits_uop_exceptionVec_5,
  output io_ldout_2_bits_uop_exceptionVec_6,
  output io_ldout_2_bits_uop_exceptionVec_7,
  output io_ldout_2_bits_uop_exceptionVec_8,
  output io_ldout_2_bits_uop_exceptionVec_9,
  output io_ldout_2_bits_uop_exceptionVec_10,
  output io_ldout_2_bits_uop_exceptionVec_11,
  output io_ldout_2_bits_uop_exceptionVec_12,
  output io_ldout_2_bits_uop_exceptionVec_13,
  output io_ldout_2_bits_uop_exceptionVec_14,
  output io_ldout_2_bits_uop_exceptionVec_15,
  output io_ldout_2_bits_uop_exceptionVec_16,
  output io_ldout_2_bits_uop_exceptionVec_17,
  output io_ldout_2_bits_uop_exceptionVec_18,
  output io_ldout_2_bits_uop_exceptionVec_19,
  output io_ldout_2_bits_uop_exceptionVec_20,
  output io_ldout_2_bits_uop_exceptionVec_21,
  output io_ldout_2_bits_uop_exceptionVec_22,
  output io_ldout_2_bits_uop_exceptionVec_23,
  output [3:0] io_ldout_2_bits_uop_trigger,
  output io_ldout_2_bits_uop_preDecodeInfo_isRVC,
  output io_ldout_2_bits_uop_ftqPtr_flag,
  output [5:0] io_ldout_2_bits_uop_ftqPtr_value,
  output [3:0] io_ldout_2_bits_uop_ftqOffset,
  output [8:0] io_ldout_2_bits_uop_fuOpType,
  output io_ldout_2_bits_uop_rfWen,
  output io_ldout_2_bits_uop_fpWen,
  output io_ldout_2_bits_uop_flushPipe,
  output [7:0] io_ldout_2_bits_uop_vpu_vstart,
  output [1:0] io_ldout_2_bits_uop_vpu_veew,
  output [6:0] io_ldout_2_bits_uop_uopIdx,
  output [7:0] io_ldout_2_bits_uop_pdest,
  output io_ldout_2_bits_uop_robIdx_flag,
  output [7:0] io_ldout_2_bits_uop_robIdx_value,
  output [63:0] io_ldout_2_bits_uop_debugInfo_enqRsTime,
  output [63:0] io_ldout_2_bits_uop_debugInfo_selectTime,
  output [63:0] io_ldout_2_bits_uop_debugInfo_issueTime,
  output io_ldout_2_bits_uop_storeSetHit,
  output io_ldout_2_bits_uop_waitForRobIdx_flag,
  output [7:0] io_ldout_2_bits_uop_waitForRobIdx_value,
  output io_ldout_2_bits_uop_loadWaitBit,
  output io_ldout_2_bits_uop_loadWaitStrict,
  output io_ldout_2_bits_uop_lqIdx_flag,
  output [6:0] io_ldout_2_bits_uop_lqIdx_value,
  output io_ldout_2_bits_uop_sqIdx_flag,
  output [5:0] io_ldout_2_bits_uop_sqIdx_value,
  output io_ldout_2_bits_uop_replayInst,
  output [63:0] io_ld_raw_data_2_lqData,
  output [8:0] io_ld_raw_data_2_uop_fuOpType,
  output io_ld_raw_data_2_uop_fpWen,
  output [2:0] io_ld_raw_data_2_addrOffset,
  input  io_ncOut_0_ready,
  output io_ncOut_0_valid,
  output io_ncOut_0_bits_uop_exceptionVec_0,
  output io_ncOut_0_bits_uop_exceptionVec_1,
  output io_ncOut_0_bits_uop_exceptionVec_2,
  output io_ncOut_0_bits_uop_exceptionVec_4,
  output io_ncOut_0_bits_uop_exceptionVec_6,
  output io_ncOut_0_bits_uop_exceptionVec_7,
  output io_ncOut_0_bits_uop_exceptionVec_8,
  output io_ncOut_0_bits_uop_exceptionVec_9,
  output io_ncOut_0_bits_uop_exceptionVec_10,
  output io_ncOut_0_bits_uop_exceptionVec_11,
  output io_ncOut_0_bits_uop_exceptionVec_12,
  output io_ncOut_0_bits_uop_exceptionVec_14,
  output io_ncOut_0_bits_uop_exceptionVec_15,
  output io_ncOut_0_bits_uop_exceptionVec_16,
  output io_ncOut_0_bits_uop_exceptionVec_17,
  output io_ncOut_0_bits_uop_exceptionVec_18,
  output io_ncOut_0_bits_uop_exceptionVec_19,
  output io_ncOut_0_bits_uop_exceptionVec_20,
  output io_ncOut_0_bits_uop_exceptionVec_22,
  output io_ncOut_0_bits_uop_exceptionVec_23,
  output io_ncOut_0_bits_uop_preDecodeInfo_isRVC,
  output io_ncOut_0_bits_uop_ftqPtr_flag,
  output [5:0] io_ncOut_0_bits_uop_ftqPtr_value,
  output [3:0] io_ncOut_0_bits_uop_ftqOffset,
  output [8:0] io_ncOut_0_bits_uop_fuOpType,
  output io_ncOut_0_bits_uop_rfWen,
  output io_ncOut_0_bits_uop_fpWen,
  output [7:0] io_ncOut_0_bits_uop_vpu_vstart,
  output [1:0] io_ncOut_0_bits_uop_vpu_veew,
  output [6:0] io_ncOut_0_bits_uop_uopIdx,
  output [7:0] io_ncOut_0_bits_uop_pdest,
  output io_ncOut_0_bits_uop_robIdx_flag,
  output [7:0] io_ncOut_0_bits_uop_robIdx_value,
  output [63:0] io_ncOut_0_bits_uop_debugInfo_enqRsTime,
  output [63:0] io_ncOut_0_bits_uop_debugInfo_selectTime,
  output [63:0] io_ncOut_0_bits_uop_debugInfo_issueTime,
  output io_ncOut_0_bits_uop_storeSetHit,
  output io_ncOut_0_bits_uop_waitForRobIdx_flag,
  output [7:0] io_ncOut_0_bits_uop_waitForRobIdx_value,
  output io_ncOut_0_bits_uop_loadWaitBit,
  output io_ncOut_0_bits_uop_loadWaitStrict,
  output io_ncOut_0_bits_uop_lqIdx_flag,
  output [6:0] io_ncOut_0_bits_uop_lqIdx_value,
  output io_ncOut_0_bits_uop_sqIdx_flag,
  output [5:0] io_ncOut_0_bits_uop_sqIdx_value,
  output [49:0] io_ncOut_0_bits_vaddr,
  output [47:0] io_ncOut_0_bits_paddr,
  output [128:0] io_ncOut_0_bits_data,
  output io_ncOut_0_bits_isvec,
  output io_ncOut_0_bits_is128bit,
  output io_ncOut_0_bits_vecActive,
  output [6:0] io_ncOut_0_bits_schedIndex,
  input  io_ncOut_1_ready,
  output io_ncOut_1_valid,
  output io_ncOut_1_bits_uop_exceptionVec_0,
  output io_ncOut_1_bits_uop_exceptionVec_1,
  output io_ncOut_1_bits_uop_exceptionVec_2,
  output io_ncOut_1_bits_uop_exceptionVec_4,
  output io_ncOut_1_bits_uop_exceptionVec_6,
  output io_ncOut_1_bits_uop_exceptionVec_7,
  output io_ncOut_1_bits_uop_exceptionVec_8,
  output io_ncOut_1_bits_uop_exceptionVec_9,
  output io_ncOut_1_bits_uop_exceptionVec_10,
  output io_ncOut_1_bits_uop_exceptionVec_11,
  output io_ncOut_1_bits_uop_exceptionVec_12,
  output io_ncOut_1_bits_uop_exceptionVec_14,
  output io_ncOut_1_bits_uop_exceptionVec_15,
  output io_ncOut_1_bits_uop_exceptionVec_16,
  output io_ncOut_1_bits_uop_exceptionVec_17,
  output io_ncOut_1_bits_uop_exceptionVec_18,
  output io_ncOut_1_bits_uop_exceptionVec_19,
  output io_ncOut_1_bits_uop_exceptionVec_20,
  output io_ncOut_1_bits_uop_exceptionVec_22,
  output io_ncOut_1_bits_uop_exceptionVec_23,
  output io_ncOut_1_bits_uop_preDecodeInfo_isRVC,
  output io_ncOut_1_bits_uop_ftqPtr_flag,
  output [5:0] io_ncOut_1_bits_uop_ftqPtr_value,
  output [3:0] io_ncOut_1_bits_uop_ftqOffset,
  output [8:0] io_ncOut_1_bits_uop_fuOpType,
  output io_ncOut_1_bits_uop_rfWen,
  output io_ncOut_1_bits_uop_fpWen,
  output [7:0] io_ncOut_1_bits_uop_vpu_vstart,
  output [1:0] io_ncOut_1_bits_uop_vpu_veew,
  output [6:0] io_ncOut_1_bits_uop_uopIdx,
  output [7:0] io_ncOut_1_bits_uop_pdest,
  output io_ncOut_1_bits_uop_robIdx_flag,
  output [7:0] io_ncOut_1_bits_uop_robIdx_value,
  output [63:0] io_ncOut_1_bits_uop_debugInfo_enqRsTime,
  output [63:0] io_ncOut_1_bits_uop_debugInfo_selectTime,
  output [63:0] io_ncOut_1_bits_uop_debugInfo_issueTime,
  output io_ncOut_1_bits_uop_storeSetHit,
  output io_ncOut_1_bits_uop_waitForRobIdx_flag,
  output [7:0] io_ncOut_1_bits_uop_waitForRobIdx_value,
  output io_ncOut_1_bits_uop_loadWaitBit,
  output io_ncOut_1_bits_uop_loadWaitStrict,
  output io_ncOut_1_bits_uop_lqIdx_flag,
  output [6:0] io_ncOut_1_bits_uop_lqIdx_value,
  output io_ncOut_1_bits_uop_sqIdx_flag,
  output [5:0] io_ncOut_1_bits_uop_sqIdx_value,
  output [49:0] io_ncOut_1_bits_vaddr,
  output [47:0] io_ncOut_1_bits_paddr,
  output [128:0] io_ncOut_1_bits_data,
  output io_ncOut_1_bits_isvec,
  output io_ncOut_1_bits_is128bit,
  output io_ncOut_1_bits_vecActive,
  output [6:0] io_ncOut_1_bits_schedIndex,
  input  io_ncOut_2_ready,
  output io_ncOut_2_valid,
  output io_ncOut_2_bits_uop_exceptionVec_0,
  output io_ncOut_2_bits_uop_exceptionVec_1,
  output io_ncOut_2_bits_uop_exceptionVec_2,
  output io_ncOut_2_bits_uop_exceptionVec_4,
  output io_ncOut_2_bits_uop_exceptionVec_6,
  output io_ncOut_2_bits_uop_exceptionVec_7,
  output io_ncOut_2_bits_uop_exceptionVec_8,
  output io_ncOut_2_bits_uop_exceptionVec_9,
  output io_ncOut_2_bits_uop_exceptionVec_10,
  output io_ncOut_2_bits_uop_exceptionVec_11,
  output io_ncOut_2_bits_uop_exceptionVec_12,
  output io_ncOut_2_bits_uop_exceptionVec_14,
  output io_ncOut_2_bits_uop_exceptionVec_15,
  output io_ncOut_2_bits_uop_exceptionVec_16,
  output io_ncOut_2_bits_uop_exceptionVec_17,
  output io_ncOut_2_bits_uop_exceptionVec_18,
  output io_ncOut_2_bits_uop_exceptionVec_19,
  output io_ncOut_2_bits_uop_exceptionVec_20,
  output io_ncOut_2_bits_uop_exceptionVec_22,
  output io_ncOut_2_bits_uop_exceptionVec_23,
  output io_ncOut_2_bits_uop_preDecodeInfo_isRVC,
  output io_ncOut_2_bits_uop_ftqPtr_flag,
  output [5:0] io_ncOut_2_bits_uop_ftqPtr_value,
  output [3:0] io_ncOut_2_bits_uop_ftqOffset,
  output [8:0] io_ncOut_2_bits_uop_fuOpType,
  output io_ncOut_2_bits_uop_rfWen,
  output io_ncOut_2_bits_uop_fpWen,
  output [7:0] io_ncOut_2_bits_uop_vpu_vstart,
  output [1:0] io_ncOut_2_bits_uop_vpu_veew,
  output [6:0] io_ncOut_2_bits_uop_uopIdx,
  output [7:0] io_ncOut_2_bits_uop_pdest,
  output io_ncOut_2_bits_uop_robIdx_flag,
  output [7:0] io_ncOut_2_bits_uop_robIdx_value,
  output [63:0] io_ncOut_2_bits_uop_debugInfo_enqRsTime,
  output [63:0] io_ncOut_2_bits_uop_debugInfo_selectTime,
  output [63:0] io_ncOut_2_bits_uop_debugInfo_issueTime,
  output io_ncOut_2_bits_uop_storeSetHit,
  output io_ncOut_2_bits_uop_waitForRobIdx_flag,
  output [7:0] io_ncOut_2_bits_uop_waitForRobIdx_value,
  output io_ncOut_2_bits_uop_loadWaitBit,
  output io_ncOut_2_bits_uop_loadWaitStrict,
  output io_ncOut_2_bits_uop_lqIdx_flag,
  output [6:0] io_ncOut_2_bits_uop_lqIdx_value,
  output io_ncOut_2_bits_uop_sqIdx_flag,
  output [5:0] io_ncOut_2_bits_uop_sqIdx_value,
  output [49:0] io_ncOut_2_bits_vaddr,
  output [47:0] io_ncOut_2_bits_paddr,
  output [128:0] io_ncOut_2_bits_data,
  output io_ncOut_2_bits_isvec,
  output io_ncOut_2_bits_is128bit,
  output io_ncOut_2_bits_vecActive,
  output [6:0] io_ncOut_2_bits_schedIndex,
  input  io_replay_0_ready,
  output io_replay_0_valid,
  output io_replay_0_bits_uop_exceptionVec_0,
  output io_replay_0_bits_uop_exceptionVec_1,
  output io_replay_0_bits_uop_exceptionVec_2,
  output io_replay_0_bits_uop_exceptionVec_6,
  output io_replay_0_bits_uop_exceptionVec_7,
  output io_replay_0_bits_uop_exceptionVec_8,
  output io_replay_0_bits_uop_exceptionVec_9,
  output io_replay_0_bits_uop_exceptionVec_10,
  output io_replay_0_bits_uop_exceptionVec_11,
  output io_replay_0_bits_uop_exceptionVec_12,
  output io_replay_0_bits_uop_exceptionVec_14,
  output io_replay_0_bits_uop_exceptionVec_15,
  output io_replay_0_bits_uop_exceptionVec_16,
  output io_replay_0_bits_uop_exceptionVec_17,
  output io_replay_0_bits_uop_exceptionVec_18,
  output io_replay_0_bits_uop_exceptionVec_19,
  output io_replay_0_bits_uop_exceptionVec_20,
  output io_replay_0_bits_uop_exceptionVec_22,
  output io_replay_0_bits_uop_exceptionVec_23,
  output io_replay_0_bits_uop_preDecodeInfo_isRVC,
  output io_replay_0_bits_uop_ftqPtr_flag,
  output [5:0] io_replay_0_bits_uop_ftqPtr_value,
  output [3:0] io_replay_0_bits_uop_ftqOffset,
  output [8:0] io_replay_0_bits_uop_fuOpType,
  output io_replay_0_bits_uop_rfWen,
  output io_replay_0_bits_uop_fpWen,
  output [7:0] io_replay_0_bits_uop_vpu_vstart,
  output [1:0] io_replay_0_bits_uop_vpu_veew,
  output [6:0] io_replay_0_bits_uop_uopIdx,
  output [7:0] io_replay_0_bits_uop_pdest,
  output io_replay_0_bits_uop_robIdx_flag,
  output [7:0] io_replay_0_bits_uop_robIdx_value,
  output [63:0] io_replay_0_bits_uop_debugInfo_enqRsTime,
  output [63:0] io_replay_0_bits_uop_debugInfo_selectTime,
  output [63:0] io_replay_0_bits_uop_debugInfo_issueTime,
  output io_replay_0_bits_uop_storeSetHit,
  output io_replay_0_bits_uop_waitForRobIdx_flag,
  output [7:0] io_replay_0_bits_uop_waitForRobIdx_value,
  output io_replay_0_bits_uop_loadWaitBit,
  output io_replay_0_bits_uop_lqIdx_flag,
  output [6:0] io_replay_0_bits_uop_lqIdx_value,
  output io_replay_0_bits_uop_sqIdx_flag,
  output [5:0] io_replay_0_bits_uop_sqIdx_value,
  output [49:0] io_replay_0_bits_vaddr,
  output [15:0] io_replay_0_bits_mask,
  output io_replay_0_bits_isvec,
  output io_replay_0_bits_is128bit,
  output [7:0] io_replay_0_bits_elemIdx,
  output [2:0] io_replay_0_bits_alignedType,
  output [3:0] io_replay_0_bits_mbIndex,
  output [3:0] io_replay_0_bits_reg_offset,
  output [7:0] io_replay_0_bits_elemIdxInsideVd,
  output io_replay_0_bits_vecActive,
  output [3:0] io_replay_0_bits_mshrid,
  output io_replay_0_bits_forward_tlDchannel,
  output [6:0] io_replay_0_bits_schedIndex,
  input  io_replay_1_ready,
  output io_replay_1_valid,
  output io_replay_1_bits_uop_exceptionVec_0,
  output io_replay_1_bits_uop_exceptionVec_1,
  output io_replay_1_bits_uop_exceptionVec_2,
  output io_replay_1_bits_uop_exceptionVec_6,
  output io_replay_1_bits_uop_exceptionVec_7,
  output io_replay_1_bits_uop_exceptionVec_8,
  output io_replay_1_bits_uop_exceptionVec_9,
  output io_replay_1_bits_uop_exceptionVec_10,
  output io_replay_1_bits_uop_exceptionVec_11,
  output io_replay_1_bits_uop_exceptionVec_12,
  output io_replay_1_bits_uop_exceptionVec_14,
  output io_replay_1_bits_uop_exceptionVec_15,
  output io_replay_1_bits_uop_exceptionVec_16,
  output io_replay_1_bits_uop_exceptionVec_17,
  output io_replay_1_bits_uop_exceptionVec_18,
  output io_replay_1_bits_uop_exceptionVec_19,
  output io_replay_1_bits_uop_exceptionVec_20,
  output io_replay_1_bits_uop_exceptionVec_22,
  output io_replay_1_bits_uop_exceptionVec_23,
  output io_replay_1_bits_uop_preDecodeInfo_isRVC,
  output io_replay_1_bits_uop_ftqPtr_flag,
  output [5:0] io_replay_1_bits_uop_ftqPtr_value,
  output [3:0] io_replay_1_bits_uop_ftqOffset,
  output [8:0] io_replay_1_bits_uop_fuOpType,
  output io_replay_1_bits_uop_rfWen,
  output io_replay_1_bits_uop_fpWen,
  output [7:0] io_replay_1_bits_uop_vpu_vstart,
  output [1:0] io_replay_1_bits_uop_vpu_veew,
  output [6:0] io_replay_1_bits_uop_uopIdx,
  output [7:0] io_replay_1_bits_uop_pdest,
  output io_replay_1_bits_uop_robIdx_flag,
  output [7:0] io_replay_1_bits_uop_robIdx_value,
  output [63:0] io_replay_1_bits_uop_debugInfo_enqRsTime,
  output [63:0] io_replay_1_bits_uop_debugInfo_selectTime,
  output [63:0] io_replay_1_bits_uop_debugInfo_issueTime,
  output io_replay_1_bits_uop_storeSetHit,
  output io_replay_1_bits_uop_waitForRobIdx_flag,
  output [7:0] io_replay_1_bits_uop_waitForRobIdx_value,
  output io_replay_1_bits_uop_loadWaitBit,
  output io_replay_1_bits_uop_lqIdx_flag,
  output [6:0] io_replay_1_bits_uop_lqIdx_value,
  output io_replay_1_bits_uop_sqIdx_flag,
  output [5:0] io_replay_1_bits_uop_sqIdx_value,
  output [49:0] io_replay_1_bits_vaddr,
  output [15:0] io_replay_1_bits_mask,
  output io_replay_1_bits_isvec,
  output io_replay_1_bits_is128bit,
  output [7:0] io_replay_1_bits_elemIdx,
  output [2:0] io_replay_1_bits_alignedType,
  output [3:0] io_replay_1_bits_mbIndex,
  output [3:0] io_replay_1_bits_reg_offset,
  output [7:0] io_replay_1_bits_elemIdxInsideVd,
  output io_replay_1_bits_vecActive,
  output [3:0] io_replay_1_bits_mshrid,
  output io_replay_1_bits_forward_tlDchannel,
  output [6:0] io_replay_1_bits_schedIndex,
  input  io_replay_2_ready,
  output io_replay_2_valid,
  output io_replay_2_bits_uop_exceptionVec_0,
  output io_replay_2_bits_uop_exceptionVec_1,
  output io_replay_2_bits_uop_exceptionVec_2,
  output io_replay_2_bits_uop_exceptionVec_6,
  output io_replay_2_bits_uop_exceptionVec_7,
  output io_replay_2_bits_uop_exceptionVec_8,
  output io_replay_2_bits_uop_exceptionVec_9,
  output io_replay_2_bits_uop_exceptionVec_10,
  output io_replay_2_bits_uop_exceptionVec_11,
  output io_replay_2_bits_uop_exceptionVec_12,
  output io_replay_2_bits_uop_exceptionVec_14,
  output io_replay_2_bits_uop_exceptionVec_15,
  output io_replay_2_bits_uop_exceptionVec_16,
  output io_replay_2_bits_uop_exceptionVec_17,
  output io_replay_2_bits_uop_exceptionVec_18,
  output io_replay_2_bits_uop_exceptionVec_19,
  output io_replay_2_bits_uop_exceptionVec_20,
  output io_replay_2_bits_uop_exceptionVec_22,
  output io_replay_2_bits_uop_exceptionVec_23,
  output io_replay_2_bits_uop_preDecodeInfo_isRVC,
  output io_replay_2_bits_uop_ftqPtr_flag,
  output [5:0] io_replay_2_bits_uop_ftqPtr_value,
  output [3:0] io_replay_2_bits_uop_ftqOffset,
  output [8:0] io_replay_2_bits_uop_fuOpType,
  output io_replay_2_bits_uop_rfWen,
  output io_replay_2_bits_uop_fpWen,
  output [7:0] io_replay_2_bits_uop_vpu_vstart,
  output [1:0] io_replay_2_bits_uop_vpu_veew,
  output [6:0] io_replay_2_bits_uop_uopIdx,
  output [7:0] io_replay_2_bits_uop_pdest,
  output io_replay_2_bits_uop_robIdx_flag,
  output [7:0] io_replay_2_bits_uop_robIdx_value,
  output [63:0] io_replay_2_bits_uop_debugInfo_enqRsTime,
  output [63:0] io_replay_2_bits_uop_debugInfo_selectTime,
  output [63:0] io_replay_2_bits_uop_debugInfo_issueTime,
  output io_replay_2_bits_uop_storeSetHit,
  output io_replay_2_bits_uop_waitForRobIdx_flag,
  output [7:0] io_replay_2_bits_uop_waitForRobIdx_value,
  output io_replay_2_bits_uop_loadWaitBit,
  output io_replay_2_bits_uop_lqIdx_flag,
  output [6:0] io_replay_2_bits_uop_lqIdx_value,
  output io_replay_2_bits_uop_sqIdx_flag,
  output [5:0] io_replay_2_bits_uop_sqIdx_value,
  output [49:0] io_replay_2_bits_vaddr,
  output [15:0] io_replay_2_bits_mask,
  output io_replay_2_bits_isvec,
  output io_replay_2_bits_is128bit,
  output [7:0] io_replay_2_bits_elemIdx,
  output [2:0] io_replay_2_bits_alignedType,
  output [3:0] io_replay_2_bits_mbIndex,
  output [3:0] io_replay_2_bits_reg_offset,
  output [7:0] io_replay_2_bits_elemIdxInsideVd,
  output io_replay_2_bits_vecActive,
  output [3:0] io_replay_2_bits_mshrid,
  output io_replay_2_bits_forward_tlDchannel,
  output [6:0] io_replay_2_bits_schedIndex,
  input  io_tl_d_channel_valid,
  input  [3:0] io_tl_d_channel_mshrid,
  input  io_release_valid,
  input  [47:0] io_release_bits_paddr,
  output io_nuke_rollback_0_valid,
  output io_nuke_rollback_0_bits_isRVC,
  output io_nuke_rollback_0_bits_robIdx_flag,
  output [7:0] io_nuke_rollback_0_bits_robIdx_value,
  output io_nuke_rollback_0_bits_ftqIdx_flag,
  output [5:0] io_nuke_rollback_0_bits_ftqIdx_value,
  output [3:0] io_nuke_rollback_0_bits_ftqOffset,
  output [5:0] io_nuke_rollback_0_bits_stFtqIdx_value,
  output [3:0] io_nuke_rollback_0_bits_stFtqOffset,
  output io_nuke_rollback_1_valid,
  output io_nuke_rollback_1_bits_isRVC,
  output io_nuke_rollback_1_bits_robIdx_flag,
  output [7:0] io_nuke_rollback_1_bits_robIdx_value,
  output io_nuke_rollback_1_bits_ftqIdx_flag,
  output [5:0] io_nuke_rollback_1_bits_ftqIdx_value,
  output [3:0] io_nuke_rollback_1_bits_ftqOffset,
  output [5:0] io_nuke_rollback_1_bits_stFtqIdx_value,
  output [3:0] io_nuke_rollback_1_bits_stFtqOffset,
  output io_nack_rollback_0_valid,
  output io_nack_rollback_0_bits_isRVC,
  output io_nack_rollback_0_bits_robIdx_flag,
  output [7:0] io_nack_rollback_0_bits_robIdx_value,
  output io_nack_rollback_0_bits_ftqIdx_flag,
  output [5:0] io_nack_rollback_0_bits_ftqIdx_value,
  output [3:0] io_nack_rollback_0_bits_ftqOffset,
  output io_nack_rollback_0_bits_level,
  input  io_rob_pendingMMIOld,
  input  io_rob_pendingPtr_flag,
  input  [7:0] io_rob_pendingPtr_value,
  output io_rob_mmio_0,
  output io_rob_mmio_1,
  output io_rob_mmio_2,
  output [7:0] io_rob_uop_0_robIdx_value,
  output [7:0] io_rob_uop_1_robIdx_value,
  output [7:0] io_rob_uop_2_robIdx_value,
  input  io_uncache_req_ready,
  output io_uncache_req_valid,
  output io_uncache_req_bits_robIdx_flag,
  output [7:0] io_uncache_req_bits_robIdx_value,
  output [4:0] io_uncache_req_bits_cmd,
  output [47:0] io_uncache_req_bits_addr,
  output [49:0] io_uncache_req_bits_vaddr,
  output [63:0] io_uncache_req_bits_data,
  output [7:0] io_uncache_req_bits_mask,
  output [6:0] io_uncache_req_bits_id,
  output io_uncache_req_bits_nc,
  output io_uncache_req_bits_memBackTypeMM,
  input  io_uncache_idResp_valid,
  input  [6:0] io_uncache_idResp_bits_mid,
  input  [1:0] io_uncache_idResp_bits_sid,
  input  io_uncache_resp_valid,
  input  [63:0] io_uncache_resp_bits_data,
  input  [1:0] io_uncache_resp_bits_id,
  input  io_uncache_resp_bits_nderr,
  output [63:0] io_exceptionAddr_vaddr,
  output io_exceptionAddr_vaNeedExt,
  output io_exceptionAddr_isHyper,
  output [63:0] io_exceptionAddr_gpaddr,
  output io_exceptionAddr_isForVSnonLeafPTE,
  input  io_loadMisalignFull,
  input  io_misalignAllowSpec,
  output [3:0] io_lqDeq,
  output [6:0] io_lqCancelCnt,
  input  io_l2_hint_valid,
  input  [3:0] io_l2_hint_bits_sourceId,
  input  io_l2_hint_bits_isKeyword,
  input  io_tlb_hint_resp_valid,
  input  [3:0] io_tlb_hint_resp_bits_id,
  input  io_tlb_hint_resp_bits_replay_all,
  output io_lqEmpty,
  output io_lqDeqPtr_flag,
  output [6:0] io_lqDeqPtr_value,
  output [6:0] io_rarValidCount,
  input  io_debugTopDown_robHeadVaddr_valid,
  input  [49:0] io_debugTopDown_robHeadVaddr_bits,
  output io_debugTopDown_robHeadTlbReplay,
  output io_debugTopDown_robHeadTlbMiss,
  output io_debugTopDown_robHeadLoadVio,
  output io_debugTopDown_robHeadLoadMSHR,
  input  io_debugTopDown_robHeadMissInDTlb,
  input  io_noUopsIssed,
  output [5:0] io_perf_0_value,
  output [5:0] io_perf_1_value,
  output [5:0] io_perf_2_value,
  output [5:0] io_perf_3_value,
  output [5:0] io_perf_4_value,
  output [5:0] io_perf_5_value,
  output [5:0] io_perf_6_value,
  output [5:0] io_perf_7_value,
  output [5:0] io_perf_8_value,
  output [5:0] io_perf_9_value,
  output [5:0] io_perf_10_value,
  output [5:0] io_perf_11_value,
  output [5:0] io_perf_12_value,
  output [5:0] io_perf_13_value,
  output [5:0] io_perf_14_value,
  output [5:0] io_perf_15_value,
  output [5:0] io_perf_16_value,
  output [5:0] io_perf_17_value,
  output [5:0] io_perf_18_value,
  output [5:0] io_perf_19_value,
  output [5:0] io_perf_20_value,
  output [5:0] io_perf_21_value,
  output [5:0] io_perf_22_value,
  output [5:0] io_perf_23_value,
  output [5:0] io_perf_24_value,
  output [5:0] io_perf_25_value,
  output [5:0] io_perf_26_value,
  output [5:0] io_perf_27_value
