// =============================================================================
//  missqueue_entry_inst.svh —— 16 条 MissEntry 黑盒例化（被 xs_MissQueue_core 内联）
// -----------------------------------------------------------------------------
//  用 genvar 统一例化 N_ENTRY 条 MissEntry（golden 黑盒）。每条 entry：
//    · io_id = i；primary_valid = req.valid & !merge & !reject & primary_ready[i]
//              & !former_primary_ready[i]（最低空闲下标分配）；
//    · pipe_reg 注入：mqpr 仅在 (mqpr_reg_valid & mqpr_mshr_id==i) 时灌入，其余拉 0；
//    · mem_grant 按 source==i 路由（opcode!=CBOAck 时）；
//    · mem_acquire/mem_finish 的 ready 由 F/G 节仲裁结果回灌（单 beat：被选中且通道 ready）；
//    · l2_hint 按 sourceId==i；mainpipe resp/replay/evict/refill 按各自 miss_id==i 匹配。
//  端口名与 golden MissEntry 完全一致；连接到 A 节聚合数组的第 i 元。
// =============================================================================
for (genvar i = 0; i < N_ENTRY; i++) begin : g_entry
  // 本 entry 是否被 pipe_reg 选中注入
  wire inject = mqpr_reg_valid & (mqpr_mshr_id == ENTRY_IDX_W'(i));
  // primary_valid（最低空闲分配）
  wire pv = io_req_valid & ~merge & ~reject & ~former_primary_ready[i] & e_primary_ready[i];
  // mem_grant 路由到 entry：source==i（不看 opcode；CBO 路由只影响 mem_grant.ready 的选择）
  wire grant_v = grant_hit_entry[i] & io_mem_grant_valid;
  // mem_acquire.ready（TLArbiter allowed 语义）：无更高优先级阻挡 且通道 ready（与本源 valid 无关）
  wire acq_rdy = io_mem_acquire_ready & acq_grant[2+i];   // golden in.ready = out.ready & (beatsLeft?state:readys)
  // mem_finish.ready（同上）
  wire fin_rdy = io_mem_finish_ready & fin_grant[i];      // 同上（E 通道）

  MissEntry u_entry (
    .clock                                            (clock),
    .reset                                            (reset),
    .io_id                                            (ENTRY_IDX_W'(i)),
    .io_req_valid                                     (io_req_valid),
    .io_req_bits_source                               (io_req_bits_source),
    .io_req_bits_addr                                 (io_req_bits_addr),
    .io_req_bits_vaddr                                (io_req_bits_vaddr),
    .io_req_bits_cancel                               (io_req_bits_cancel),
    .io_wbq_block_miss_req                            (io_wbq_block_miss_req),
    .io_miss_req_pipe_reg_req_source                  (mqpr.source),
    .io_miss_req_pipe_reg_req_pf_source               (mqpr.pf_source),
    .io_miss_req_pipe_reg_req_cmd                     (mqpr.cmd),
    .io_miss_req_pipe_reg_req_addr                    ({mqpr.addr, 6'h0}),  // 低 6 位钉 0(golden MissEntry 内部亦掩 0)
    .io_miss_req_pipe_reg_req_vaddr                   (mqpr.vaddr),
    .io_miss_req_pipe_reg_req_full_overwrite          (mqpr.full_overwrite),
    .io_miss_req_pipe_reg_req_word_idx                (mqpr.word_idx),
    .io_miss_req_pipe_reg_req_amo_data                (mqpr.amo_data),
    .io_miss_req_pipe_reg_req_amo_mask                (mqpr.amo_mask),
    .io_miss_req_pipe_reg_req_amo_cmp                 (mqpr.amo_cmp),
    .io_miss_req_pipe_reg_req_req_coh_state           (mqpr.req_coh_state),
    .io_miss_req_pipe_reg_req_id                      (mqpr.id),
    .io_miss_req_pipe_reg_req_isBtoT                  (mqpr.isBtoT),
    .io_miss_req_pipe_reg_req_occupy_way              (mqpr.occupy_way),
    .io_miss_req_pipe_reg_req_store_data              (mqpr.store_data),
    .io_miss_req_pipe_reg_req_store_mask              (mqpr.store_mask),
    .io_miss_req_pipe_reg_merge                       (inject & mqpr_merge),
    .io_miss_req_pipe_reg_alloc                       (inject & mqpr_alloc),
    .io_miss_req_pipe_reg_cancel                      (mqpr_cancel),
    .io_primary_valid                                 (pv),
    .io_primary_ready                                 (e_primary_ready[i]),
    .io_secondary_ready                               (e_secondary_ready[i]),
    .io_secondary_reject                              (e_secondary_reject[i]),
    .io_mem_acquire_ready                             (acq_rdy),
    .io_mem_acquire_valid                             (e_acq_valid[i]),
    .io_mem_acquire_bits_opcode                       (e_acq_opcode[i]),
    .io_mem_acquire_bits_param                        (e_acq_param[i]),
    .io_mem_acquire_bits_source                       (e_acq_source[i]),
    .io_mem_acquire_bits_address                      (e_acq_address[i]),
    .io_mem_acquire_bits_user_alias                   (e_acq_alias[i]),
    .io_mem_acquire_bits_user_vaddr                   (e_acq_vaddr[i]),
    .io_mem_acquire_bits_user_reqSource               (e_acq_reqsrc[i]),
    .io_mem_acquire_bits_user_needHint                (e_acq_needhint[i]),
    .io_mem_acquire_bits_echo_isKeyword               (e_acq_iskeyword[i]),
    .io_mem_grant_valid                               (grant_v),
    .io_mem_grant_bits_opcode                         (io_mem_grant_bits_opcode),
    .io_mem_grant_bits_param                          (io_mem_grant_bits_param),
    .io_mem_grant_bits_size                           (io_mem_grant_bits_size),
    .io_mem_grant_bits_sink                           (io_mem_grant_bits_sink),
    .io_mem_grant_bits_denied                         (io_mem_grant_bits_denied),
    .io_mem_grant_bits_data                           (io_mem_grant_bits_data),
    .io_mem_grant_bits_corrupt                        (io_mem_grant_bits_corrupt),
    .io_mem_finish_ready                              (fin_rdy),
    .io_mem_finish_valid                              (e_fin_valid[i]),
    .io_mem_finish_bits_sink                          (e_fin_sink[i]),
    .io_queryME_0_req_bits_source                     (io_queryMQ_0_req_bits_source),
    .io_queryME_0_req_bits_addr                       (io_queryMQ_0_req_bits_addr),
    .io_queryME_0_req_bits_vaddr                      (io_queryMQ_0_req_bits_vaddr),
    .io_queryME_0_primary_ready                       (qme_primary_ready[0][i]),
    .io_queryME_0_secondary_ready                     (qme_secondary_ready[0][i]),
    .io_queryME_0_secondary_reject                    (qme_secondary_reject[0][i]),
    .io_queryME_1_req_bits_source                     (io_queryMQ_1_req_bits_source),
    .io_queryME_1_req_bits_addr                       (io_queryMQ_1_req_bits_addr),
    .io_queryME_1_req_bits_vaddr                      (io_queryMQ_1_req_bits_vaddr),
    .io_queryME_1_primary_ready                       (qme_primary_ready[1][i]),
    .io_queryME_1_secondary_ready                     (qme_secondary_ready[1][i]),
    .io_queryME_1_secondary_reject                    (qme_secondary_reject[1][i]),
    .io_queryME_2_req_bits_source                     (io_queryMQ_2_req_bits_source),
    .io_queryME_2_req_bits_addr                       (io_queryMQ_2_req_bits_addr),
    .io_queryME_2_req_bits_vaddr                      (io_queryMQ_2_req_bits_vaddr),
    .io_queryME_2_primary_ready                       (qme_primary_ready[2][i]),
    .io_queryME_2_secondary_ready                     (qme_secondary_ready[2][i]),
    .io_queryME_2_secondary_reject                    (qme_secondary_reject[2][i]),
    .io_queryME_3_req_bits_source                     (io_queryMQ_3_req_bits_source),
    .io_queryME_3_req_bits_addr                       (io_queryMQ_3_req_bits_addr),
    .io_queryME_3_req_bits_vaddr                      (io_queryMQ_3_req_bits_vaddr),
    .io_queryME_3_primary_ready                       (qme_primary_ready[3][i]),
    .io_queryME_3_secondary_ready                     (qme_secondary_ready[3][i]),
    .io_queryME_3_secondary_reject                    (qme_secondary_reject[3][i]),
    .io_l2_hint_valid                                 ((io_l2_hint_bits_sourceId == ENTRY_IDX_W'(i)) & io_l2_hint_valid),
    .io_main_pipe_req_ready                           (e_mpr_ready[i]),
    .io_main_pipe_req_valid                           (e_mpr_valid[i]),
    .io_main_pipe_req_bits_miss_id                    (e_mpr_miss_id[i]),
    .io_main_pipe_req_bits_occupy_way                 (e_mpr_occupy_way[i]),
    .io_main_pipe_req_bits_miss_fail_cause_evict_btot (e_mpr_evict_btot[i]),
    .io_main_pipe_req_bits_source                     (e_mpr_source[i]),
    .io_main_pipe_req_bits_cmd                        (e_mpr_cmd[i]),
    .io_main_pipe_req_bits_vaddr                      (e_mpr_vaddr[i]),
    .io_main_pipe_req_bits_addr                       (e_mpr_addr[i]),
    .io_main_pipe_req_bits_word_idx                   (e_mpr_word_idx[i]),
    .io_main_pipe_req_bits_amo_data                   (e_mpr_amo_data[i]),
    .io_main_pipe_req_bits_amo_mask                   (e_mpr_amo_mask[i]),
    .io_main_pipe_req_bits_amo_cmp                    (e_mpr_amo_cmp[i]),
    .io_main_pipe_req_bits_pf_source                  (e_mpr_pf_source[i]),
    .io_main_pipe_req_bits_access                     (e_mpr_access[i]),
    .io_main_pipe_req_bits_id                         (e_mpr_id[i]),
    .io_main_pipe_resp                                (mp_resp_hit   & (io_main_pipe_resp_bits_miss_id == ENTRY_IDX_W'(i))),
    .io_main_pipe_refill_resp                         (mp_refill_hit & (io_mainpipe_info_s3_miss_id   == ENTRY_IDX_W'(i))),
    .io_main_pipe_replay                              (mp_replay_hit & (io_mainpipe_info_s2_miss_id   == ENTRY_IDX_W'(i))),
    .io_main_pipe_evict_BtoT_way                      (mp_evict_hit  & (io_mainpipe_info_s2_miss_id   == ENTRY_IDX_W'(i))),
    .io_main_pipe_next_evict_way                      (io_mainpipe_info_s2_next_evict_way),
    .io_refill_info_valid                             (e_refill_valid[i]),
    .io_refill_info_bits_store_data                   (e_refill_data[i]),
    .io_refill_info_bits_miss_param                   (e_refill_param[i]),
    .io_refill_info_bits_error                        (e_refill_error[i]),
    .io_occupy_way                                    (e_occupy_way[i]),
    .io_probe_req_bits_addr                           (io_probe_req_bits_addr),
    .io_probe_req_bits_vaddr                          (io_probe_req_bits_vaddr),
    .io_probe_block                                   (e_probe_block[i]),
    .io_replace_req_bits_addr                         (io_replace_req_bits_addr),
    .io_replace_req_bits_vaddr                        (io_replace_req_bits_vaddr),
    .io_replace_block                                 (e_replace_block[i]),
    .io_req_vaddr_valid                               (e_req_vaddr_valid[i]),
    .io_req_vaddr_bits                                (e_req_vaddr[i]),
    .io_req_isBtoT                                    (e_req_isBtoT[i]),
    .io_req_handled_by_this_entry                     (e_req_handled[i]),
    .io_forwardInfo_inflight                          (e_fwd_inflight[i]),
    .io_forwardInfo_paddr                             (e_fwd_paddr[i]),
    .io_forwardInfo_raw_data_0                        (e_fwd_raw[i][0]),
    .io_forwardInfo_raw_data_1                        (e_fwd_raw[i][1]),
    .io_forwardInfo_raw_data_2                        (e_fwd_raw[i][2]),
    .io_forwardInfo_raw_data_3                        (e_fwd_raw[i][3]),
    .io_forwardInfo_raw_data_4                        (e_fwd_raw[i][4]),
    .io_forwardInfo_raw_data_5                        (e_fwd_raw[i][5]),
    .io_forwardInfo_raw_data_6                        (e_fwd_raw[i][6]),
    .io_forwardInfo_raw_data_7                        (e_fwd_raw[i][7]),
    .io_forwardInfo_firstbeat_valid                   (e_fwd_firstbeat[i]),
    .io_forwardInfo_lastbeat_valid                    (e_fwd_lastbeat[i]),
    .io_forwardInfo_corrupt                           (e_fwd_corrupt[i]),
    .io_l2_pf_store_only                              (io_l2_pf_store_only),
    .io_acquire_fired_by_pipe_reg                     (acquire_pipereg_fired),
    .io_memSetPattenDetected                          (memset_detected_q),
    .io_perf_pending_prefetch                         (e_perf_pending_prefetch[i]),
    .io_perf_pending_normal                           (e_perf_pending_normal[i]),
    .io_rob_head_query_vaddr                          (io_debugTopDown_robHeadVaddr_bits),
    .io_rob_head_query_query_valid                    (io_debugTopDown_robHeadVaddr_valid),
    .io_rob_head_query_resp                           (e_rob_head_resp[i]),
    .io_latency_monitor_load_miss_refilling           (e_lat_load[i]),
    .io_latency_monitor_store_miss_refilling          (e_lat_store[i]),
    .io_latency_monitor_amo_miss_refilling            (e_lat_amo[i]),
    .io_latency_monitor_pf_miss_refilling             (e_lat_pf[i]),
    .io_prefetch_info_late_prefetch                   (e_late_prefetch[i]),
    .io_matched                                       (e_matched[i]),
    .io_l1Miss                                        (e_l1Miss[i]),
    .io_wfi_wfiReq                                    (io_wfi_wfiReq),
    .io_wfi_wfiSafe                                   (e_wfi_safe[i])
  );
end
