// =============================================================================
//  missqueue_subinst.svh —— CMOUnit / FastArbiter 黑盒例化（被 xs_MissQueue_core 内联）
// -----------------------------------------------------------------------------
//  CMOUnit：处理 CMO（cache block 维护操作 CBO）。它在 A 通道以最高优先(idx0)发 CBO 请求，
//    收 D 通道 CBOAck（grant opcode==8）后回 LSQ。req_chanA.ready = mem_acquire_ready & 被选中
//    (acq_winner[0])；resp_chanD.valid = grant_is_cbo & io_mem_grant_valid。
//  FastArbiter：把 16 条 entry 的 amo main_pipe_req 仲裁成单口 io_main_pipe_req（黑盒，内部
//    含其轮转/锁定逻辑）。各 entry 的 main_pipe_req.ready 由它回灌（e_mpr_ready[i]）。
// =============================================================================

// ---- CMOUnit ----
CMOUnit cmo_unit (
  .clock                      (clock),
  .reset                      (reset),
  .io_req_ready               (io_cmo_req_ready),
  .io_req_valid               (io_cmo_req_valid),
  .io_req_bits_opcode         (io_cmo_req_bits_opcode),
  .io_req_bits_address        (io_cmo_req_bits_address),
  .io_req_chanA_ready         (io_mem_acquire_ready & acq_grant[0]),
  .io_req_chanA_valid         (cmo_acq_valid),
  .io_req_chanA_bits_opcode   (cmo_acq_opcode),
  .io_req_chanA_bits_address  (cmo_acq_address),
  .io_resp_chanD_ready        (cmo_respD_ready),
  .io_resp_chanD_valid        (grant_is_cbo & io_mem_grant_valid),
  .io_resp_chanD_bits_denied  (io_mem_grant_bits_denied),
  .io_resp_chanD_bits_corrupt (io_mem_grant_bits_corrupt),
  .io_resp_to_lsq_ready       (io_cmo_resp_ready),
  .io_resp_to_lsq_valid       (io_cmo_resp_valid),
  .io_resp_to_lsq_bits_nderr  (io_cmo_resp_bits_nderr),
  .io_wfi_wfiReq              (io_wfi_wfiReq),
  .io_wfi_wfiSafe             (cmo_wfi_safe)
);

// ---- FastArbiter（16 路 amo main_pipe_req → 单口）----
FastArbiter main_pipe_req_arb (
  .clock                                    (clock),
  .reset                                    (reset),
  .io_in_0_ready  (e_mpr_ready[0]),   .io_in_0_valid (e_mpr_valid[0]),
  .io_in_0_bits_miss_id (e_mpr_miss_id[0]), .io_in_0_bits_occupy_way (e_mpr_occupy_way[0]),
  .io_in_0_bits_miss_fail_cause_evict_btot (e_mpr_evict_btot[0]),
  .io_in_0_bits_source (e_mpr_source[0]), .io_in_0_bits_cmd (e_mpr_cmd[0]),
  .io_in_0_bits_vaddr (e_mpr_vaddr[0]), .io_in_0_bits_addr (e_mpr_addr[0]),
  .io_in_0_bits_word_idx (e_mpr_word_idx[0]), .io_in_0_bits_amo_data (e_mpr_amo_data[0]),
  .io_in_0_bits_amo_mask (e_mpr_amo_mask[0]), .io_in_0_bits_amo_cmp (e_mpr_amo_cmp[0]),
  .io_in_0_bits_pf_source (e_mpr_pf_source[0]), .io_in_0_bits_access (e_mpr_access[0]),
  .io_in_0_bits_id (e_mpr_id[0]),
  .io_in_1_ready  (e_mpr_ready[1]),   .io_in_1_valid (e_mpr_valid[1]),
  .io_in_1_bits_miss_id (e_mpr_miss_id[1]), .io_in_1_bits_occupy_way (e_mpr_occupy_way[1]),
  .io_in_1_bits_miss_fail_cause_evict_btot (e_mpr_evict_btot[1]),
  .io_in_1_bits_source (e_mpr_source[1]), .io_in_1_bits_cmd (e_mpr_cmd[1]),
  .io_in_1_bits_vaddr (e_mpr_vaddr[1]), .io_in_1_bits_addr (e_mpr_addr[1]),
  .io_in_1_bits_word_idx (e_mpr_word_idx[1]), .io_in_1_bits_amo_data (e_mpr_amo_data[1]),
  .io_in_1_bits_amo_mask (e_mpr_amo_mask[1]), .io_in_1_bits_amo_cmp (e_mpr_amo_cmp[1]),
  .io_in_1_bits_pf_source (e_mpr_pf_source[1]), .io_in_1_bits_access (e_mpr_access[1]),
  .io_in_1_bits_id (e_mpr_id[1]),
  .io_in_2_ready  (e_mpr_ready[2]),   .io_in_2_valid (e_mpr_valid[2]),
  .io_in_2_bits_miss_id (e_mpr_miss_id[2]), .io_in_2_bits_occupy_way (e_mpr_occupy_way[2]),
  .io_in_2_bits_miss_fail_cause_evict_btot (e_mpr_evict_btot[2]),
  .io_in_2_bits_source (e_mpr_source[2]), .io_in_2_bits_cmd (e_mpr_cmd[2]),
  .io_in_2_bits_vaddr (e_mpr_vaddr[2]), .io_in_2_bits_addr (e_mpr_addr[2]),
  .io_in_2_bits_word_idx (e_mpr_word_idx[2]), .io_in_2_bits_amo_data (e_mpr_amo_data[2]),
  .io_in_2_bits_amo_mask (e_mpr_amo_mask[2]), .io_in_2_bits_amo_cmp (e_mpr_amo_cmp[2]),
  .io_in_2_bits_pf_source (e_mpr_pf_source[2]), .io_in_2_bits_access (e_mpr_access[2]),
  .io_in_2_bits_id (e_mpr_id[2]),
  .io_in_3_ready  (e_mpr_ready[3]),   .io_in_3_valid (e_mpr_valid[3]),
  .io_in_3_bits_miss_id (e_mpr_miss_id[3]), .io_in_3_bits_occupy_way (e_mpr_occupy_way[3]),
  .io_in_3_bits_miss_fail_cause_evict_btot (e_mpr_evict_btot[3]),
  .io_in_3_bits_source (e_mpr_source[3]), .io_in_3_bits_cmd (e_mpr_cmd[3]),
  .io_in_3_bits_vaddr (e_mpr_vaddr[3]), .io_in_3_bits_addr (e_mpr_addr[3]),
  .io_in_3_bits_word_idx (e_mpr_word_idx[3]), .io_in_3_bits_amo_data (e_mpr_amo_data[3]),
  .io_in_3_bits_amo_mask (e_mpr_amo_mask[3]), .io_in_3_bits_amo_cmp (e_mpr_amo_cmp[3]),
  .io_in_3_bits_pf_source (e_mpr_pf_source[3]), .io_in_3_bits_access (e_mpr_access[3]),
  .io_in_3_bits_id (e_mpr_id[3]),
  .io_in_4_ready  (e_mpr_ready[4]),   .io_in_4_valid (e_mpr_valid[4]),
  .io_in_4_bits_miss_id (e_mpr_miss_id[4]), .io_in_4_bits_occupy_way (e_mpr_occupy_way[4]),
  .io_in_4_bits_miss_fail_cause_evict_btot (e_mpr_evict_btot[4]),
  .io_in_4_bits_source (e_mpr_source[4]), .io_in_4_bits_cmd (e_mpr_cmd[4]),
  .io_in_4_bits_vaddr (e_mpr_vaddr[4]), .io_in_4_bits_addr (e_mpr_addr[4]),
  .io_in_4_bits_word_idx (e_mpr_word_idx[4]), .io_in_4_bits_amo_data (e_mpr_amo_data[4]),
  .io_in_4_bits_amo_mask (e_mpr_amo_mask[4]), .io_in_4_bits_amo_cmp (e_mpr_amo_cmp[4]),
  .io_in_4_bits_pf_source (e_mpr_pf_source[4]), .io_in_4_bits_access (e_mpr_access[4]),
  .io_in_4_bits_id (e_mpr_id[4]),
  .io_in_5_ready  (e_mpr_ready[5]),   .io_in_5_valid (e_mpr_valid[5]),
  .io_in_5_bits_miss_id (e_mpr_miss_id[5]), .io_in_5_bits_occupy_way (e_mpr_occupy_way[5]),
  .io_in_5_bits_miss_fail_cause_evict_btot (e_mpr_evict_btot[5]),
  .io_in_5_bits_source (e_mpr_source[5]), .io_in_5_bits_cmd (e_mpr_cmd[5]),
  .io_in_5_bits_vaddr (e_mpr_vaddr[5]), .io_in_5_bits_addr (e_mpr_addr[5]),
  .io_in_5_bits_word_idx (e_mpr_word_idx[5]), .io_in_5_bits_amo_data (e_mpr_amo_data[5]),
  .io_in_5_bits_amo_mask (e_mpr_amo_mask[5]), .io_in_5_bits_amo_cmp (e_mpr_amo_cmp[5]),
  .io_in_5_bits_pf_source (e_mpr_pf_source[5]), .io_in_5_bits_access (e_mpr_access[5]),
  .io_in_5_bits_id (e_mpr_id[5]),
  .io_in_6_ready  (e_mpr_ready[6]),   .io_in_6_valid (e_mpr_valid[6]),
  .io_in_6_bits_miss_id (e_mpr_miss_id[6]), .io_in_6_bits_occupy_way (e_mpr_occupy_way[6]),
  .io_in_6_bits_miss_fail_cause_evict_btot (e_mpr_evict_btot[6]),
  .io_in_6_bits_source (e_mpr_source[6]), .io_in_6_bits_cmd (e_mpr_cmd[6]),
  .io_in_6_bits_vaddr (e_mpr_vaddr[6]), .io_in_6_bits_addr (e_mpr_addr[6]),
  .io_in_6_bits_word_idx (e_mpr_word_idx[6]), .io_in_6_bits_amo_data (e_mpr_amo_data[6]),
  .io_in_6_bits_amo_mask (e_mpr_amo_mask[6]), .io_in_6_bits_amo_cmp (e_mpr_amo_cmp[6]),
  .io_in_6_bits_pf_source (e_mpr_pf_source[6]), .io_in_6_bits_access (e_mpr_access[6]),
  .io_in_6_bits_id (e_mpr_id[6]),
  .io_in_7_ready  (e_mpr_ready[7]),   .io_in_7_valid (e_mpr_valid[7]),
  .io_in_7_bits_miss_id (e_mpr_miss_id[7]), .io_in_7_bits_occupy_way (e_mpr_occupy_way[7]),
  .io_in_7_bits_miss_fail_cause_evict_btot (e_mpr_evict_btot[7]),
  .io_in_7_bits_source (e_mpr_source[7]), .io_in_7_bits_cmd (e_mpr_cmd[7]),
  .io_in_7_bits_vaddr (e_mpr_vaddr[7]), .io_in_7_bits_addr (e_mpr_addr[7]),
  .io_in_7_bits_word_idx (e_mpr_word_idx[7]), .io_in_7_bits_amo_data (e_mpr_amo_data[7]),
  .io_in_7_bits_amo_mask (e_mpr_amo_mask[7]), .io_in_7_bits_amo_cmp (e_mpr_amo_cmp[7]),
  .io_in_7_bits_pf_source (e_mpr_pf_source[7]), .io_in_7_bits_access (e_mpr_access[7]),
  .io_in_7_bits_id (e_mpr_id[7]),
  .io_in_8_ready  (e_mpr_ready[8]),   .io_in_8_valid (e_mpr_valid[8]),
  .io_in_8_bits_miss_id (e_mpr_miss_id[8]), .io_in_8_bits_occupy_way (e_mpr_occupy_way[8]),
  .io_in_8_bits_miss_fail_cause_evict_btot (e_mpr_evict_btot[8]),
  .io_in_8_bits_source (e_mpr_source[8]), .io_in_8_bits_cmd (e_mpr_cmd[8]),
  .io_in_8_bits_vaddr (e_mpr_vaddr[8]), .io_in_8_bits_addr (e_mpr_addr[8]),
  .io_in_8_bits_word_idx (e_mpr_word_idx[8]), .io_in_8_bits_amo_data (e_mpr_amo_data[8]),
  .io_in_8_bits_amo_mask (e_mpr_amo_mask[8]), .io_in_8_bits_amo_cmp (e_mpr_amo_cmp[8]),
  .io_in_8_bits_pf_source (e_mpr_pf_source[8]), .io_in_8_bits_access (e_mpr_access[8]),
  .io_in_8_bits_id (e_mpr_id[8]),
  .io_in_9_ready  (e_mpr_ready[9]),   .io_in_9_valid (e_mpr_valid[9]),
  .io_in_9_bits_miss_id (e_mpr_miss_id[9]), .io_in_9_bits_occupy_way (e_mpr_occupy_way[9]),
  .io_in_9_bits_miss_fail_cause_evict_btot (e_mpr_evict_btot[9]),
  .io_in_9_bits_source (e_mpr_source[9]), .io_in_9_bits_cmd (e_mpr_cmd[9]),
  .io_in_9_bits_vaddr (e_mpr_vaddr[9]), .io_in_9_bits_addr (e_mpr_addr[9]),
  .io_in_9_bits_word_idx (e_mpr_word_idx[9]), .io_in_9_bits_amo_data (e_mpr_amo_data[9]),
  .io_in_9_bits_amo_mask (e_mpr_amo_mask[9]), .io_in_9_bits_amo_cmp (e_mpr_amo_cmp[9]),
  .io_in_9_bits_pf_source (e_mpr_pf_source[9]), .io_in_9_bits_access (e_mpr_access[9]),
  .io_in_9_bits_id (e_mpr_id[9]),
  .io_in_10_ready (e_mpr_ready[10]),  .io_in_10_valid (e_mpr_valid[10]),
  .io_in_10_bits_miss_id (e_mpr_miss_id[10]), .io_in_10_bits_occupy_way (e_mpr_occupy_way[10]),
  .io_in_10_bits_miss_fail_cause_evict_btot (e_mpr_evict_btot[10]),
  .io_in_10_bits_source (e_mpr_source[10]), .io_in_10_bits_cmd (e_mpr_cmd[10]),
  .io_in_10_bits_vaddr (e_mpr_vaddr[10]), .io_in_10_bits_addr (e_mpr_addr[10]),
  .io_in_10_bits_word_idx (e_mpr_word_idx[10]), .io_in_10_bits_amo_data (e_mpr_amo_data[10]),
  .io_in_10_bits_amo_mask (e_mpr_amo_mask[10]), .io_in_10_bits_amo_cmp (e_mpr_amo_cmp[10]),
  .io_in_10_bits_pf_source (e_mpr_pf_source[10]), .io_in_10_bits_access (e_mpr_access[10]),
  .io_in_10_bits_id (e_mpr_id[10]),
  .io_in_11_ready (e_mpr_ready[11]),  .io_in_11_valid (e_mpr_valid[11]),
  .io_in_11_bits_miss_id (e_mpr_miss_id[11]), .io_in_11_bits_occupy_way (e_mpr_occupy_way[11]),
  .io_in_11_bits_miss_fail_cause_evict_btot (e_mpr_evict_btot[11]),
  .io_in_11_bits_source (e_mpr_source[11]), .io_in_11_bits_cmd (e_mpr_cmd[11]),
  .io_in_11_bits_vaddr (e_mpr_vaddr[11]), .io_in_11_bits_addr (e_mpr_addr[11]),
  .io_in_11_bits_word_idx (e_mpr_word_idx[11]), .io_in_11_bits_amo_data (e_mpr_amo_data[11]),
  .io_in_11_bits_amo_mask (e_mpr_amo_mask[11]), .io_in_11_bits_amo_cmp (e_mpr_amo_cmp[11]),
  .io_in_11_bits_pf_source (e_mpr_pf_source[11]), .io_in_11_bits_access (e_mpr_access[11]),
  .io_in_11_bits_id (e_mpr_id[11]),
  .io_in_12_ready (e_mpr_ready[12]),  .io_in_12_valid (e_mpr_valid[12]),
  .io_in_12_bits_miss_id (e_mpr_miss_id[12]), .io_in_12_bits_occupy_way (e_mpr_occupy_way[12]),
  .io_in_12_bits_miss_fail_cause_evict_btot (e_mpr_evict_btot[12]),
  .io_in_12_bits_source (e_mpr_source[12]), .io_in_12_bits_cmd (e_mpr_cmd[12]),
  .io_in_12_bits_vaddr (e_mpr_vaddr[12]), .io_in_12_bits_addr (e_mpr_addr[12]),
  .io_in_12_bits_word_idx (e_mpr_word_idx[12]), .io_in_12_bits_amo_data (e_mpr_amo_data[12]),
  .io_in_12_bits_amo_mask (e_mpr_amo_mask[12]), .io_in_12_bits_amo_cmp (e_mpr_amo_cmp[12]),
  .io_in_12_bits_pf_source (e_mpr_pf_source[12]), .io_in_12_bits_access (e_mpr_access[12]),
  .io_in_12_bits_id (e_mpr_id[12]),
  .io_in_13_ready (e_mpr_ready[13]),  .io_in_13_valid (e_mpr_valid[13]),
  .io_in_13_bits_miss_id (e_mpr_miss_id[13]), .io_in_13_bits_occupy_way (e_mpr_occupy_way[13]),
  .io_in_13_bits_miss_fail_cause_evict_btot (e_mpr_evict_btot[13]),
  .io_in_13_bits_source (e_mpr_source[13]), .io_in_13_bits_cmd (e_mpr_cmd[13]),
  .io_in_13_bits_vaddr (e_mpr_vaddr[13]), .io_in_13_bits_addr (e_mpr_addr[13]),
  .io_in_13_bits_word_idx (e_mpr_word_idx[13]), .io_in_13_bits_amo_data (e_mpr_amo_data[13]),
  .io_in_13_bits_amo_mask (e_mpr_amo_mask[13]), .io_in_13_bits_amo_cmp (e_mpr_amo_cmp[13]),
  .io_in_13_bits_pf_source (e_mpr_pf_source[13]), .io_in_13_bits_access (e_mpr_access[13]),
  .io_in_13_bits_id (e_mpr_id[13]),
  .io_in_14_ready (e_mpr_ready[14]),  .io_in_14_valid (e_mpr_valid[14]),
  .io_in_14_bits_miss_id (e_mpr_miss_id[14]), .io_in_14_bits_occupy_way (e_mpr_occupy_way[14]),
  .io_in_14_bits_miss_fail_cause_evict_btot (e_mpr_evict_btot[14]),
  .io_in_14_bits_source (e_mpr_source[14]), .io_in_14_bits_cmd (e_mpr_cmd[14]),
  .io_in_14_bits_vaddr (e_mpr_vaddr[14]), .io_in_14_bits_addr (e_mpr_addr[14]),
  .io_in_14_bits_word_idx (e_mpr_word_idx[14]), .io_in_14_bits_amo_data (e_mpr_amo_data[14]),
  .io_in_14_bits_amo_mask (e_mpr_amo_mask[14]), .io_in_14_bits_amo_cmp (e_mpr_amo_cmp[14]),
  .io_in_14_bits_pf_source (e_mpr_pf_source[14]), .io_in_14_bits_access (e_mpr_access[14]),
  .io_in_14_bits_id (e_mpr_id[14]),
  .io_in_15_ready (e_mpr_ready[15]),  .io_in_15_valid (e_mpr_valid[15]),
  .io_in_15_bits_miss_id (e_mpr_miss_id[15]), .io_in_15_bits_occupy_way (e_mpr_occupy_way[15]),
  .io_in_15_bits_miss_fail_cause_evict_btot (e_mpr_evict_btot[15]),
  .io_in_15_bits_source (e_mpr_source[15]), .io_in_15_bits_cmd (e_mpr_cmd[15]),
  .io_in_15_bits_vaddr (e_mpr_vaddr[15]), .io_in_15_bits_addr (e_mpr_addr[15]),
  .io_in_15_bits_word_idx (e_mpr_word_idx[15]), .io_in_15_bits_amo_data (e_mpr_amo_data[15]),
  .io_in_15_bits_amo_mask (e_mpr_amo_mask[15]), .io_in_15_bits_amo_cmp (e_mpr_amo_cmp[15]),
  .io_in_15_bits_pf_source (e_mpr_pf_source[15]), .io_in_15_bits_access (e_mpr_access[15]),
  .io_in_15_bits_id (e_mpr_id[15]),
  .io_out_ready                             (io_main_pipe_req_ready),
  .io_out_valid                             (io_main_pipe_req_valid),
  .io_out_bits_miss                         (io_main_pipe_req_bits_miss),
  .io_out_bits_miss_id                      (io_main_pipe_req_bits_miss_id),
  .io_out_bits_occupy_way                   (io_main_pipe_req_bits_occupy_way),
  .io_out_bits_miss_fail_cause_evict_btot   (io_main_pipe_req_bits_miss_fail_cause_evict_btot),
  .io_out_bits_source                       (io_main_pipe_req_bits_source),
  .io_out_bits_cmd                          (io_main_pipe_req_bits_cmd),
  .io_out_bits_vaddr                        (io_main_pipe_req_bits_vaddr),
  .io_out_bits_addr                         (io_main_pipe_req_bits_addr),
  .io_out_bits_word_idx                     (io_main_pipe_req_bits_word_idx),
  .io_out_bits_amo_data                     (io_main_pipe_req_bits_amo_data),
  .io_out_bits_amo_mask                     (io_main_pipe_req_bits_amo_mask),
  .io_out_bits_amo_cmp                      (io_main_pipe_req_bits_amo_cmp),
  .io_out_bits_pf_source                    (io_main_pipe_req_bits_pf_source),
  .io_out_bits_access                       (io_main_pipe_req_bits_access),
  .io_out_bits_id                           (io_main_pipe_req_bits_id)
);
