// 自动生成片段（端口与 golden MissQueue 完全一致；clock/reset 在模块头显式声明，故本片段不带前导逗号——直接续在 reset, 之后）
  output logic io_req_ready,
  input  logic io_req_valid,
  input  logic [3:0] io_req_bits_source,
  input  logic [2:0] io_req_bits_pf_source,
  input  logic [4:0] io_req_bits_cmd,
  input  logic [47:0] io_req_bits_addr,
  input  logic [49:0] io_req_bits_vaddr,
  input  logic io_req_bits_full_overwrite,
  input  logic [2:0] io_req_bits_word_idx,
  input  logic [127:0] io_req_bits_amo_data,
  input  logic [15:0] io_req_bits_amo_mask,
  input  logic [127:0] io_req_bits_amo_cmp,
  input  logic [1:0] io_req_bits_req_coh_state,
  input  logic [5:0] io_req_bits_id,
  input  logic io_req_bits_isBtoT,
  input  logic [3:0] io_req_bits_occupy_way,
  input  logic io_req_bits_cancel,
  input  logic [511:0] io_req_bits_store_data,
  input  logic [63:0] io_req_bits_store_mask,
  output logic [3:0] io_resp_id,
  output logic io_resp_handled,
  output logic io_resp_merged,
  output logic io_cmo_req_ready,
  input  logic io_cmo_req_valid,
  input  logic [2:0] io_cmo_req_bits_opcode,
  input  logic [63:0] io_cmo_req_bits_address,
  input  logic io_cmo_resp_ready,
  output logic io_cmo_resp_valid,
  output logic io_cmo_resp_bits_nderr,
  input  logic [3:0] io_queryMQ_0_req_bits_source,
  input  logic [47:0] io_queryMQ_0_req_bits_addr,
  input  logic [49:0] io_queryMQ_0_req_bits_vaddr,
  output logic io_queryMQ_0_ready,
  input  logic [3:0] io_queryMQ_1_req_bits_source,
  input  logic [47:0] io_queryMQ_1_req_bits_addr,
  input  logic [49:0] io_queryMQ_1_req_bits_vaddr,
  output logic io_queryMQ_1_ready,
  input  logic [3:0] io_queryMQ_2_req_bits_source,
  input  logic [47:0] io_queryMQ_2_req_bits_addr,
  input  logic [49:0] io_queryMQ_2_req_bits_vaddr,
  output logic io_queryMQ_2_ready,
  input  logic [3:0] io_queryMQ_3_req_bits_source,
  input  logic [47:0] io_queryMQ_3_req_bits_addr,
  input  logic [49:0] io_queryMQ_3_req_bits_vaddr,
  output logic io_queryMQ_3_ready,
  input  logic io_mem_acquire_ready,
  output logic io_mem_acquire_valid,
  output logic [3:0] io_mem_acquire_bits_opcode,
  output logic [2:0] io_mem_acquire_bits_param,
  output logic [2:0] io_mem_acquire_bits_size,
  output logic [5:0] io_mem_acquire_bits_source,
  output logic [47:0] io_mem_acquire_bits_address,
  output logic [1:0] io_mem_acquire_bits_user_alias,
  output logic [43:0] io_mem_acquire_bits_user_vaddr,
  output logic [4:0] io_mem_acquire_bits_user_reqSource,
  output logic io_mem_acquire_bits_user_needHint,
  output logic io_mem_acquire_bits_echo_isKeyword,
  output logic [31:0] io_mem_acquire_bits_mask,
  output logic io_mem_grant_ready,
  input  logic io_mem_grant_valid,
  input  logic [3:0] io_mem_grant_bits_opcode,
  input  logic [1:0] io_mem_grant_bits_param,
  input  logic [2:0] io_mem_grant_bits_size,
  input  logic [5:0] io_mem_grant_bits_source,
  input  logic [9:0] io_mem_grant_bits_sink,
  input  logic io_mem_grant_bits_denied,
  input  logic [255:0] io_mem_grant_bits_data,
  input  logic io_mem_grant_bits_corrupt,
  input  logic io_mem_finish_ready,
  output logic io_mem_finish_valid,
  output logic [9:0] io_mem_finish_bits_sink,
  input  logic io_l2_hint_valid,
  input  logic [3:0] io_l2_hint_bits_sourceId,
  input  logic io_main_pipe_req_ready,
  output logic io_main_pipe_req_valid,
  output logic io_main_pipe_req_bits_miss,
  output logic [3:0] io_main_pipe_req_bits_miss_id,
  output logic [3:0] io_main_pipe_req_bits_occupy_way,
  output logic io_main_pipe_req_bits_miss_fail_cause_evict_btot,
  output logic [3:0] io_main_pipe_req_bits_source,
  output logic [4:0] io_main_pipe_req_bits_cmd,
  output logic [49:0] io_main_pipe_req_bits_vaddr,
  output logic [47:0] io_main_pipe_req_bits_addr,
  output logic [2:0] io_main_pipe_req_bits_word_idx,
  output logic [127:0] io_main_pipe_req_bits_amo_data,
  output logic [15:0] io_main_pipe_req_bits_amo_mask,
  output logic [127:0] io_main_pipe_req_bits_amo_cmp,
  output logic [2:0] io_main_pipe_req_bits_pf_source,
  output logic io_main_pipe_req_bits_access,
  output logic [5:0] io_main_pipe_req_bits_id,
  input  logic io_main_pipe_resp_valid,
  input  logic [3:0] io_main_pipe_resp_bits_miss_id,
  input  logic io_main_pipe_resp_bits_ack_miss_queue,
  input  logic io_mainpipe_info_s2_valid,
  input  logic [3:0] io_mainpipe_info_s2_miss_id,
  input  logic io_mainpipe_info_s2_replay_to_mq,
  input  logic io_mainpipe_info_s2_evict_BtoT_way,
  input  logic [3:0] io_mainpipe_info_s2_next_evict_way,
  input  logic io_mainpipe_info_s3_valid,
  input  logic [3:0] io_mainpipe_info_s3_miss_id,
  input  logic io_mainpipe_info_s3_refill_resp,
  output logic io_refill_info_valid,
  output logic [511:0] io_refill_info_bits_store_data,
  output logic [63:0] io_refill_info_bits_store_mask,
  output logic [1:0] io_refill_info_bits_miss_param,
  output logic io_refill_info_bits_error,
  input  logic [47:0] io_probe_req_bits_addr,
  input  logic [49:0] io_probe_req_bits_vaddr,
  output logic io_probe_block,
  input  logic [47:0] io_replace_req_bits_addr,
  input  logic [49:0] io_replace_req_bits_vaddr,
  output logic io_replace_block,
  input  logic [7:0] io_evict_set,
  output logic [3:0] io_btot_ways_for_set,
  input  logic [7:0] io_occupy_set_0,
  input  logic [7:0] io_occupy_set_1,
  input  logic [7:0] io_occupy_set_2,
  output logic io_occupy_fail_0,
  output logic io_occupy_fail_1,
  output logic io_occupy_fail_2,
  input  logic io_wbq_block_miss_req,
  input  logic io_forward_0_valid,
  input  logic [3:0] io_forward_0_mshrid,
  input  logic [47:0] io_forward_0_paddr,
  output logic io_forward_0_forward_mshr,
  output logic [7:0] io_forward_0_forwardData_0,
  output logic [7:0] io_forward_0_forwardData_1,
  output logic [7:0] io_forward_0_forwardData_2,
  output logic [7:0] io_forward_0_forwardData_3,
  output logic [7:0] io_forward_0_forwardData_4,
  output logic [7:0] io_forward_0_forwardData_5,
  output logic [7:0] io_forward_0_forwardData_6,
  output logic [7:0] io_forward_0_forwardData_7,
  output logic [7:0] io_forward_0_forwardData_8,
  output logic [7:0] io_forward_0_forwardData_9,
  output logic [7:0] io_forward_0_forwardData_10,
  output logic [7:0] io_forward_0_forwardData_11,
  output logic [7:0] io_forward_0_forwardData_12,
  output logic [7:0] io_forward_0_forwardData_13,
  output logic [7:0] io_forward_0_forwardData_14,
  output logic [7:0] io_forward_0_forwardData_15,
  output logic io_forward_0_forward_result_valid,
  output logic io_forward_0_corrupt,
  input  logic io_forward_1_valid,
  input  logic [3:0] io_forward_1_mshrid,
  input  logic [47:0] io_forward_1_paddr,
  output logic io_forward_1_forward_mshr,
  output logic [7:0] io_forward_1_forwardData_0,
  output logic [7:0] io_forward_1_forwardData_1,
  output logic [7:0] io_forward_1_forwardData_2,
  output logic [7:0] io_forward_1_forwardData_3,
  output logic [7:0] io_forward_1_forwardData_4,
  output logic [7:0] io_forward_1_forwardData_5,
  output logic [7:0] io_forward_1_forwardData_6,
  output logic [7:0] io_forward_1_forwardData_7,
  output logic [7:0] io_forward_1_forwardData_8,
  output logic [7:0] io_forward_1_forwardData_9,
  output logic [7:0] io_forward_1_forwardData_10,
  output logic [7:0] io_forward_1_forwardData_11,
  output logic [7:0] io_forward_1_forwardData_12,
  output logic [7:0] io_forward_1_forwardData_13,
  output logic [7:0] io_forward_1_forwardData_14,
  output logic [7:0] io_forward_1_forwardData_15,
  output logic io_forward_1_forward_result_valid,
  output logic io_forward_1_corrupt,
  input  logic io_forward_2_valid,
  input  logic [3:0] io_forward_2_mshrid,
  input  logic [47:0] io_forward_2_paddr,
  output logic io_forward_2_forward_mshr,
  output logic [7:0] io_forward_2_forwardData_0,
  output logic [7:0] io_forward_2_forwardData_1,
  output logic [7:0] io_forward_2_forwardData_2,
  output logic [7:0] io_forward_2_forwardData_3,
  output logic [7:0] io_forward_2_forwardData_4,
  output logic [7:0] io_forward_2_forwardData_5,
  output logic [7:0] io_forward_2_forwardData_6,
  output logic [7:0] io_forward_2_forwardData_7,
  output logic [7:0] io_forward_2_forwardData_8,
  output logic [7:0] io_forward_2_forwardData_9,
  output logic [7:0] io_forward_2_forwardData_10,
  output logic [7:0] io_forward_2_forwardData_11,
  output logic [7:0] io_forward_2_forwardData_12,
  output logic [7:0] io_forward_2_forwardData_13,
  output logic [7:0] io_forward_2_forwardData_14,
  output logic [7:0] io_forward_2_forwardData_15,
  output logic io_forward_2_forward_result_valid,
  output logic io_forward_2_corrupt,
  input  logic io_l2_pf_store_only,
  input  logic io_lqEmpty,
  output logic io_prefetch_info_naive_late_miss_prefetch,
  output logic io_prefetch_info_fdp_late_miss_prefetch,
  output logic io_prefetch_info_fdp_prefetch_monitor_cnt,
  output logic io_prefetch_info_fdp_total_prefetch,
  input  logic io_wfi_wfiReq,
  output logic io_wfi_wfiSafe,
  input  logic io_debugTopDown_robHeadVaddr_valid,
  input  logic [49:0] io_debugTopDown_robHeadVaddr_bits,
  output logic io_debugTopDown_robHeadMissInDCache,
  output logic io_l1Miss,
  output logic [5:0] io_perf_0_value,
  output logic [5:0] io_perf_1_value,
  output logic [5:0] io_perf_2_value,
  output logic [5:0] io_perf_3_value,
  output logic [5:0] io_perf_4_value
