// 自动生成：scripts/gen_storequeue.py —— 勿手改
// 5 个数据存储子模块黑盒 stub：仅供 FM 单独跑（hdlin_unresolved_modules=black_box）。
// UT 双例化两侧共用真实 golden 子模块文件，不用这里的空壳。

module SQDataModule(
  input  clock,
  input  reset,
  input  [5:0] io_raddr_0,
  input  [5:0] io_raddr_1,
  output [15:0] io_rdata_0_mask,
  output [127:0] io_rdata_0_data,
  output [15:0] io_rdata_1_mask,
  output [127:0] io_rdata_1_data,
  input  io_data_wen_0,
  input  io_data_wen_1,
  input  [5:0] io_data_waddr_0,
  input  [5:0] io_data_waddr_1,
  input  [127:0] io_data_wdata_0,
  input  [127:0] io_data_wdata_1,
  input  io_mask_wen_0,
  input  io_mask_wen_1,
  input  [5:0] io_mask_waddr_0,
  input  [5:0] io_mask_waddr_1,
  input  [15:0] io_mask_wdata_0,
  input  [15:0] io_mask_wdata_1,
  input  [55:0] io_needForward_0_0,
  input  [55:0] io_needForward_0_1,
  input  [55:0] io_needForward_1_0,
  input  [55:0] io_needForward_1_1,
  input  [55:0] io_needForward_2_0,
  input  [55:0] io_needForward_2_1,
  output io_forwardMask_0_0,
  output io_forwardMask_0_1,
  output io_forwardMask_0_2,
  output io_forwardMask_0_3,
  output io_forwardMask_0_4,
  output io_forwardMask_0_5,
  output io_forwardMask_0_6,
  output io_forwardMask_0_7,
  output io_forwardMask_0_8,
  output io_forwardMask_0_9,
  output io_forwardMask_0_10,
  output io_forwardMask_0_11,
  output io_forwardMask_0_12,
  output io_forwardMask_0_13,
  output io_forwardMask_0_14,
  output io_forwardMask_0_15,
  output io_forwardMask_1_0,
  output io_forwardMask_1_1,
  output io_forwardMask_1_2,
  output io_forwardMask_1_3,
  output io_forwardMask_1_4,
  output io_forwardMask_1_5,
  output io_forwardMask_1_6,
  output io_forwardMask_1_7,
  output io_forwardMask_1_8,
  output io_forwardMask_1_9,
  output io_forwardMask_1_10,
  output io_forwardMask_1_11,
  output io_forwardMask_1_12,
  output io_forwardMask_1_13,
  output io_forwardMask_1_14,
  output io_forwardMask_1_15,
  output io_forwardMask_2_0,
  output io_forwardMask_2_1,
  output io_forwardMask_2_2,
  output io_forwardMask_2_3,
  output io_forwardMask_2_4,
  output io_forwardMask_2_5,
  output io_forwardMask_2_6,
  output io_forwardMask_2_7,
  output io_forwardMask_2_8,
  output io_forwardMask_2_9,
  output io_forwardMask_2_10,
  output io_forwardMask_2_11,
  output io_forwardMask_2_12,
  output io_forwardMask_2_13,
  output io_forwardMask_2_14,
  output io_forwardMask_2_15,
  output [7:0] io_forwardData_0_0,
  output [7:0] io_forwardData_0_1,
  output [7:0] io_forwardData_0_2,
  output [7:0] io_forwardData_0_3,
  output [7:0] io_forwardData_0_4,
  output [7:0] io_forwardData_0_5,
  output [7:0] io_forwardData_0_6,
  output [7:0] io_forwardData_0_7,
  output [7:0] io_forwardData_0_8,
  output [7:0] io_forwardData_0_9,
  output [7:0] io_forwardData_0_10,
  output [7:0] io_forwardData_0_11,
  output [7:0] io_forwardData_0_12,
  output [7:0] io_forwardData_0_13,
  output [7:0] io_forwardData_0_14,
  output [7:0] io_forwardData_0_15,
  output [7:0] io_forwardData_1_0,
  output [7:0] io_forwardData_1_1,
  output [7:0] io_forwardData_1_2,
  output [7:0] io_forwardData_1_3,
  output [7:0] io_forwardData_1_4,
  output [7:0] io_forwardData_1_5,
  output [7:0] io_forwardData_1_6,
  output [7:0] io_forwardData_1_7,
  output [7:0] io_forwardData_1_8,
  output [7:0] io_forwardData_1_9,
  output [7:0] io_forwardData_1_10,
  output [7:0] io_forwardData_1_11,
  output [7:0] io_forwardData_1_12,
  output [7:0] io_forwardData_1_13,
  output [7:0] io_forwardData_1_14,
  output [7:0] io_forwardData_1_15,
  output [7:0] io_forwardData_2_0,
  output [7:0] io_forwardData_2_1,
  output [7:0] io_forwardData_2_2,
  output [7:0] io_forwardData_2_3,
  output [7:0] io_forwardData_2_4,
  output [7:0] io_forwardData_2_5,
  output [7:0] io_forwardData_2_6,
  output [7:0] io_forwardData_2_7,
  output [7:0] io_forwardData_2_8,
  output [7:0] io_forwardData_2_9,
  output [7:0] io_forwardData_2_10,
  output [7:0] io_forwardData_2_11,
  output [7:0] io_forwardData_2_12,
  output [7:0] io_forwardData_2_13,
  output [7:0] io_forwardData_2_14,
  output [7:0] io_forwardData_2_15
);
endmodule

module SQAddrModule(
  input  clock,
  input  reset,
  input  [5:0] io_raddr_0,
  input  [5:0] io_raddr_1,
  output [47:0] io_rdata_0,
  output [47:0] io_rdata_1,
  output io_rlineflag_0,
  output io_rlineflag_1,
  input  io_wen_0,
  input  io_wen_1,
  input  [5:0] io_waddr_0,
  input  [5:0] io_waddr_1,
  input  [47:0] io_wdata_0,
  input  [47:0] io_wdata_1,
  input  [15:0] io_wmask_0,
  input  [15:0] io_wmask_1,
  input  io_wlineflag_0,
  input  io_wlineflag_1,
  input  [47:0] io_forwardMdata_0,
  input  [47:0] io_forwardMdata_1,
  input  [47:0] io_forwardMdata_2,
  input  [15:0] io_forwardDataMask_0,
  input  [15:0] io_forwardDataMask_1,
  input  [15:0] io_forwardDataMask_2,
  output io_forwardMmask_0_0,
  output io_forwardMmask_0_1,
  output io_forwardMmask_0_2,
  output io_forwardMmask_0_3,
  output io_forwardMmask_0_4,
  output io_forwardMmask_0_5,
  output io_forwardMmask_0_6,
  output io_forwardMmask_0_7,
  output io_forwardMmask_0_8,
  output io_forwardMmask_0_9,
  output io_forwardMmask_0_10,
  output io_forwardMmask_0_11,
  output io_forwardMmask_0_12,
  output io_forwardMmask_0_13,
  output io_forwardMmask_0_14,
  output io_forwardMmask_0_15,
  output io_forwardMmask_0_16,
  output io_forwardMmask_0_17,
  output io_forwardMmask_0_18,
  output io_forwardMmask_0_19,
  output io_forwardMmask_0_20,
  output io_forwardMmask_0_21,
  output io_forwardMmask_0_22,
  output io_forwardMmask_0_23,
  output io_forwardMmask_0_24,
  output io_forwardMmask_0_25,
  output io_forwardMmask_0_26,
  output io_forwardMmask_0_27,
  output io_forwardMmask_0_28,
  output io_forwardMmask_0_29,
  output io_forwardMmask_0_30,
  output io_forwardMmask_0_31,
  output io_forwardMmask_0_32,
  output io_forwardMmask_0_33,
  output io_forwardMmask_0_34,
  output io_forwardMmask_0_35,
  output io_forwardMmask_0_36,
  output io_forwardMmask_0_37,
  output io_forwardMmask_0_38,
  output io_forwardMmask_0_39,
  output io_forwardMmask_0_40,
  output io_forwardMmask_0_41,
  output io_forwardMmask_0_42,
  output io_forwardMmask_0_43,
  output io_forwardMmask_0_44,
  output io_forwardMmask_0_45,
  output io_forwardMmask_0_46,
  output io_forwardMmask_0_47,
  output io_forwardMmask_0_48,
  output io_forwardMmask_0_49,
  output io_forwardMmask_0_50,
  output io_forwardMmask_0_51,
  output io_forwardMmask_0_52,
  output io_forwardMmask_0_53,
  output io_forwardMmask_0_54,
  output io_forwardMmask_0_55,
  output io_forwardMmask_1_0,
  output io_forwardMmask_1_1,
  output io_forwardMmask_1_2,
  output io_forwardMmask_1_3,
  output io_forwardMmask_1_4,
  output io_forwardMmask_1_5,
  output io_forwardMmask_1_6,
  output io_forwardMmask_1_7,
  output io_forwardMmask_1_8,
  output io_forwardMmask_1_9,
  output io_forwardMmask_1_10,
  output io_forwardMmask_1_11,
  output io_forwardMmask_1_12,
  output io_forwardMmask_1_13,
  output io_forwardMmask_1_14,
  output io_forwardMmask_1_15,
  output io_forwardMmask_1_16,
  output io_forwardMmask_1_17,
  output io_forwardMmask_1_18,
  output io_forwardMmask_1_19,
  output io_forwardMmask_1_20,
  output io_forwardMmask_1_21,
  output io_forwardMmask_1_22,
  output io_forwardMmask_1_23,
  output io_forwardMmask_1_24,
  output io_forwardMmask_1_25,
  output io_forwardMmask_1_26,
  output io_forwardMmask_1_27,
  output io_forwardMmask_1_28,
  output io_forwardMmask_1_29,
  output io_forwardMmask_1_30,
  output io_forwardMmask_1_31,
  output io_forwardMmask_1_32,
  output io_forwardMmask_1_33,
  output io_forwardMmask_1_34,
  output io_forwardMmask_1_35,
  output io_forwardMmask_1_36,
  output io_forwardMmask_1_37,
  output io_forwardMmask_1_38,
  output io_forwardMmask_1_39,
  output io_forwardMmask_1_40,
  output io_forwardMmask_1_41,
  output io_forwardMmask_1_42,
  output io_forwardMmask_1_43,
  output io_forwardMmask_1_44,
  output io_forwardMmask_1_45,
  output io_forwardMmask_1_46,
  output io_forwardMmask_1_47,
  output io_forwardMmask_1_48,
  output io_forwardMmask_1_49,
  output io_forwardMmask_1_50,
  output io_forwardMmask_1_51,
  output io_forwardMmask_1_52,
  output io_forwardMmask_1_53,
  output io_forwardMmask_1_54,
  output io_forwardMmask_1_55,
  output io_forwardMmask_2_0,
  output io_forwardMmask_2_1,
  output io_forwardMmask_2_2,
  output io_forwardMmask_2_3,
  output io_forwardMmask_2_4,
  output io_forwardMmask_2_5,
  output io_forwardMmask_2_6,
  output io_forwardMmask_2_7,
  output io_forwardMmask_2_8,
  output io_forwardMmask_2_9,
  output io_forwardMmask_2_10,
  output io_forwardMmask_2_11,
  output io_forwardMmask_2_12,
  output io_forwardMmask_2_13,
  output io_forwardMmask_2_14,
  output io_forwardMmask_2_15,
  output io_forwardMmask_2_16,
  output io_forwardMmask_2_17,
  output io_forwardMmask_2_18,
  output io_forwardMmask_2_19,
  output io_forwardMmask_2_20,
  output io_forwardMmask_2_21,
  output io_forwardMmask_2_22,
  output io_forwardMmask_2_23,
  output io_forwardMmask_2_24,
  output io_forwardMmask_2_25,
  output io_forwardMmask_2_26,
  output io_forwardMmask_2_27,
  output io_forwardMmask_2_28,
  output io_forwardMmask_2_29,
  output io_forwardMmask_2_30,
  output io_forwardMmask_2_31,
  output io_forwardMmask_2_32,
  output io_forwardMmask_2_33,
  output io_forwardMmask_2_34,
  output io_forwardMmask_2_35,
  output io_forwardMmask_2_36,
  output io_forwardMmask_2_37,
  output io_forwardMmask_2_38,
  output io_forwardMmask_2_39,
  output io_forwardMmask_2_40,
  output io_forwardMmask_2_41,
  output io_forwardMmask_2_42,
  output io_forwardMmask_2_43,
  output io_forwardMmask_2_44,
  output io_forwardMmask_2_45,
  output io_forwardMmask_2_46,
  output io_forwardMmask_2_47,
  output io_forwardMmask_2_48,
  output io_forwardMmask_2_49,
  output io_forwardMmask_2_50,
  output io_forwardMmask_2_51,
  output io_forwardMmask_2_52,
  output io_forwardMmask_2_53,
  output io_forwardMmask_2_54,
  output io_forwardMmask_2_55
);
endmodule

module SQAddrModule_1(
  input  clock,
  input  reset,
  input  [5:0] io_raddr_0,
  input  [5:0] io_raddr_1,
  output [49:0] io_rdata_0,
  output [49:0] io_rdata_1,
  input  io_wen_0,
  input  io_wen_1,
  input  [5:0] io_waddr_0,
  input  [5:0] io_waddr_1,
  input  [49:0] io_wdata_0,
  input  [49:0] io_wdata_1,
  input  [15:0] io_wmask_0,
  input  [15:0] io_wmask_1,
  input  io_wlineflag_0,
  input  io_wlineflag_1,
  input  [49:0] io_forwardMdata_0,
  input  [49:0] io_forwardMdata_1,
  input  [49:0] io_forwardMdata_2,
  input  [15:0] io_forwardDataMask_0,
  input  [15:0] io_forwardDataMask_1,
  input  [15:0] io_forwardDataMask_2,
  output io_forwardMmask_0_0,
  output io_forwardMmask_0_1,
  output io_forwardMmask_0_2,
  output io_forwardMmask_0_3,
  output io_forwardMmask_0_4,
  output io_forwardMmask_0_5,
  output io_forwardMmask_0_6,
  output io_forwardMmask_0_7,
  output io_forwardMmask_0_8,
  output io_forwardMmask_0_9,
  output io_forwardMmask_0_10,
  output io_forwardMmask_0_11,
  output io_forwardMmask_0_12,
  output io_forwardMmask_0_13,
  output io_forwardMmask_0_14,
  output io_forwardMmask_0_15,
  output io_forwardMmask_0_16,
  output io_forwardMmask_0_17,
  output io_forwardMmask_0_18,
  output io_forwardMmask_0_19,
  output io_forwardMmask_0_20,
  output io_forwardMmask_0_21,
  output io_forwardMmask_0_22,
  output io_forwardMmask_0_23,
  output io_forwardMmask_0_24,
  output io_forwardMmask_0_25,
  output io_forwardMmask_0_26,
  output io_forwardMmask_0_27,
  output io_forwardMmask_0_28,
  output io_forwardMmask_0_29,
  output io_forwardMmask_0_30,
  output io_forwardMmask_0_31,
  output io_forwardMmask_0_32,
  output io_forwardMmask_0_33,
  output io_forwardMmask_0_34,
  output io_forwardMmask_0_35,
  output io_forwardMmask_0_36,
  output io_forwardMmask_0_37,
  output io_forwardMmask_0_38,
  output io_forwardMmask_0_39,
  output io_forwardMmask_0_40,
  output io_forwardMmask_0_41,
  output io_forwardMmask_0_42,
  output io_forwardMmask_0_43,
  output io_forwardMmask_0_44,
  output io_forwardMmask_0_45,
  output io_forwardMmask_0_46,
  output io_forwardMmask_0_47,
  output io_forwardMmask_0_48,
  output io_forwardMmask_0_49,
  output io_forwardMmask_0_50,
  output io_forwardMmask_0_51,
  output io_forwardMmask_0_52,
  output io_forwardMmask_0_53,
  output io_forwardMmask_0_54,
  output io_forwardMmask_0_55,
  output io_forwardMmask_1_0,
  output io_forwardMmask_1_1,
  output io_forwardMmask_1_2,
  output io_forwardMmask_1_3,
  output io_forwardMmask_1_4,
  output io_forwardMmask_1_5,
  output io_forwardMmask_1_6,
  output io_forwardMmask_1_7,
  output io_forwardMmask_1_8,
  output io_forwardMmask_1_9,
  output io_forwardMmask_1_10,
  output io_forwardMmask_1_11,
  output io_forwardMmask_1_12,
  output io_forwardMmask_1_13,
  output io_forwardMmask_1_14,
  output io_forwardMmask_1_15,
  output io_forwardMmask_1_16,
  output io_forwardMmask_1_17,
  output io_forwardMmask_1_18,
  output io_forwardMmask_1_19,
  output io_forwardMmask_1_20,
  output io_forwardMmask_1_21,
  output io_forwardMmask_1_22,
  output io_forwardMmask_1_23,
  output io_forwardMmask_1_24,
  output io_forwardMmask_1_25,
  output io_forwardMmask_1_26,
  output io_forwardMmask_1_27,
  output io_forwardMmask_1_28,
  output io_forwardMmask_1_29,
  output io_forwardMmask_1_30,
  output io_forwardMmask_1_31,
  output io_forwardMmask_1_32,
  output io_forwardMmask_1_33,
  output io_forwardMmask_1_34,
  output io_forwardMmask_1_35,
  output io_forwardMmask_1_36,
  output io_forwardMmask_1_37,
  output io_forwardMmask_1_38,
  output io_forwardMmask_1_39,
  output io_forwardMmask_1_40,
  output io_forwardMmask_1_41,
  output io_forwardMmask_1_42,
  output io_forwardMmask_1_43,
  output io_forwardMmask_1_44,
  output io_forwardMmask_1_45,
  output io_forwardMmask_1_46,
  output io_forwardMmask_1_47,
  output io_forwardMmask_1_48,
  output io_forwardMmask_1_49,
  output io_forwardMmask_1_50,
  output io_forwardMmask_1_51,
  output io_forwardMmask_1_52,
  output io_forwardMmask_1_53,
  output io_forwardMmask_1_54,
  output io_forwardMmask_1_55,
  output io_forwardMmask_2_0,
  output io_forwardMmask_2_1,
  output io_forwardMmask_2_2,
  output io_forwardMmask_2_3,
  output io_forwardMmask_2_4,
  output io_forwardMmask_2_5,
  output io_forwardMmask_2_6,
  output io_forwardMmask_2_7,
  output io_forwardMmask_2_8,
  output io_forwardMmask_2_9,
  output io_forwardMmask_2_10,
  output io_forwardMmask_2_11,
  output io_forwardMmask_2_12,
  output io_forwardMmask_2_13,
  output io_forwardMmask_2_14,
  output io_forwardMmask_2_15,
  output io_forwardMmask_2_16,
  output io_forwardMmask_2_17,
  output io_forwardMmask_2_18,
  output io_forwardMmask_2_19,
  output io_forwardMmask_2_20,
  output io_forwardMmask_2_21,
  output io_forwardMmask_2_22,
  output io_forwardMmask_2_23,
  output io_forwardMmask_2_24,
  output io_forwardMmask_2_25,
  output io_forwardMmask_2_26,
  output io_forwardMmask_2_27,
  output io_forwardMmask_2_28,
  output io_forwardMmask_2_29,
  output io_forwardMmask_2_30,
  output io_forwardMmask_2_31,
  output io_forwardMmask_2_32,
  output io_forwardMmask_2_33,
  output io_forwardMmask_2_34,
  output io_forwardMmask_2_35,
  output io_forwardMmask_2_36,
  output io_forwardMmask_2_37,
  output io_forwardMmask_2_38,
  output io_forwardMmask_2_39,
  output io_forwardMmask_2_40,
  output io_forwardMmask_2_41,
  output io_forwardMmask_2_42,
  output io_forwardMmask_2_43,
  output io_forwardMmask_2_44,
  output io_forwardMmask_2_45,
  output io_forwardMmask_2_46,
  output io_forwardMmask_2_47,
  output io_forwardMmask_2_48,
  output io_forwardMmask_2_49,
  output io_forwardMmask_2_50,
  output io_forwardMmask_2_51,
  output io_forwardMmask_2_52,
  output io_forwardMmask_2_53,
  output io_forwardMmask_2_54,
  output io_forwardMmask_2_55
);
endmodule

module DatamoduleResultBuffer(
  input  clock,
  input  reset,
  output io_enq_0_ready,
  input  io_enq_0_valid,
  input  [47:0] io_enq_0_bits_addr,
  input  [49:0] io_enq_0_bits_vaddr,
  input  [127:0] io_enq_0_bits_data,
  input  [15:0] io_enq_0_bits_mask,
  input  io_enq_0_bits_wline,
  input  [5:0] io_enq_0_bits_sqPtr_value,
  input  io_enq_0_bits_vecValid,
  output io_enq_1_ready,
  input  io_enq_1_valid,
  input  [47:0] io_enq_1_bits_addr,
  input  [49:0] io_enq_1_bits_vaddr,
  input  [127:0] io_enq_1_bits_data,
  input  [15:0] io_enq_1_bits_mask,
  input  io_enq_1_bits_wline,
  input  [5:0] io_enq_1_bits_sqPtr_value,
  input  io_enq_1_bits_vecValid,
  input  io_enq_1_bits_sqNeedDeq,
  input  io_deq_0_ready,
  output io_deq_0_valid,
  output [47:0] io_deq_0_bits_addr,
  output [49:0] io_deq_0_bits_vaddr,
  output [127:0] io_deq_0_bits_data,
  output [15:0] io_deq_0_bits_mask,
  output io_deq_0_bits_wline,
  output [5:0] io_deq_0_bits_sqPtr_value,
  output io_deq_0_bits_vecValid,
  output io_deq_0_bits_sqNeedDeq,
  input  io_deq_1_ready,
  output io_deq_1_valid,
  output [47:0] io_deq_1_bits_addr,
  output [49:0] io_deq_1_bits_vaddr,
  output [127:0] io_deq_1_bits_data,
  output [15:0] io_deq_1_bits_mask,
  output io_deq_1_bits_wline,
  output [5:0] io_deq_1_bits_sqPtr_value,
  output io_deq_1_bits_vecValid,
  output io_deq_1_bits_sqNeedDeq
);
endmodule

module StoreExceptionBuffer(
  input  clock,
  input  reset,
  input  io_redirect_valid,
  input  io_redirect_bits_robIdx_flag,
  input  [7:0] io_redirect_bits_robIdx_value,
  input  io_redirect_bits_level,
  input  io_storeAddrIn_0_valid,
  input  io_storeAddrIn_0_bits_uop_exceptionVec_3,
  input  io_storeAddrIn_0_bits_uop_exceptionVec_6,
  input  io_storeAddrIn_0_bits_uop_exceptionVec_7,
  input  io_storeAddrIn_0_bits_uop_exceptionVec_15,
  input  io_storeAddrIn_0_bits_uop_exceptionVec_19,
  input  io_storeAddrIn_0_bits_uop_exceptionVec_23,
  input  [6:0] io_storeAddrIn_0_bits_uop_uopIdx,
  input  io_storeAddrIn_0_bits_uop_robIdx_flag,
  input  [7:0] io_storeAddrIn_0_bits_uop_robIdx_value,
  input  [63:0] io_storeAddrIn_0_bits_fullva,
  input  io_storeAddrIn_0_bits_vaNeedExt,
  input  [63:0] io_storeAddrIn_0_bits_gpaddr,
  input  io_storeAddrIn_0_bits_isHyper,
  input  io_storeAddrIn_0_bits_isForVSnonLeafPTE,
  input  io_storeAddrIn_1_valid,
  input  io_storeAddrIn_1_bits_uop_exceptionVec_3,
  input  io_storeAddrIn_1_bits_uop_exceptionVec_6,
  input  io_storeAddrIn_1_bits_uop_exceptionVec_7,
  input  io_storeAddrIn_1_bits_uop_exceptionVec_15,
  input  io_storeAddrIn_1_bits_uop_exceptionVec_19,
  input  io_storeAddrIn_1_bits_uop_exceptionVec_23,
  input  [6:0] io_storeAddrIn_1_bits_uop_uopIdx,
  input  io_storeAddrIn_1_bits_uop_robIdx_flag,
  input  [7:0] io_storeAddrIn_1_bits_uop_robIdx_value,
  input  [63:0] io_storeAddrIn_1_bits_fullva,
  input  io_storeAddrIn_1_bits_vaNeedExt,
  input  [63:0] io_storeAddrIn_1_bits_gpaddr,
  input  io_storeAddrIn_1_bits_isHyper,
  input  io_storeAddrIn_1_bits_isForVSnonLeafPTE,
  input  io_storeAddrIn_2_valid,
  input  io_storeAddrIn_2_bits_uop_exceptionVec_3,
  input  io_storeAddrIn_2_bits_uop_exceptionVec_6,
  input  io_storeAddrIn_2_bits_uop_exceptionVec_7,
  input  io_storeAddrIn_2_bits_uop_exceptionVec_15,
  input  io_storeAddrIn_2_bits_uop_exceptionVec_19,
  input  io_storeAddrIn_2_bits_uop_exceptionVec_23,
  input  [6:0] io_storeAddrIn_2_bits_uop_uopIdx,
  input  io_storeAddrIn_2_bits_uop_robIdx_flag,
  input  [7:0] io_storeAddrIn_2_bits_uop_robIdx_value,
  input  [63:0] io_storeAddrIn_2_bits_fullva,
  input  io_storeAddrIn_2_bits_vaNeedExt,
  input  [63:0] io_storeAddrIn_2_bits_gpaddr,
  input  io_storeAddrIn_2_bits_isHyper,
  input  io_storeAddrIn_2_bits_isForVSnonLeafPTE,
  input  io_storeAddrIn_3_valid,
  input  io_storeAddrIn_3_bits_uop_exceptionVec_3,
  input  io_storeAddrIn_3_bits_uop_exceptionVec_6,
  input  io_storeAddrIn_3_bits_uop_exceptionVec_7,
  input  io_storeAddrIn_3_bits_uop_exceptionVec_15,
  input  io_storeAddrIn_3_bits_uop_exceptionVec_19,
  input  io_storeAddrIn_3_bits_uop_exceptionVec_23,
  input  [6:0] io_storeAddrIn_3_bits_uop_uopIdx,
  input  io_storeAddrIn_3_bits_uop_robIdx_flag,
  input  [7:0] io_storeAddrIn_3_bits_uop_robIdx_value,
  input  [63:0] io_storeAddrIn_3_bits_fullva,
  input  io_storeAddrIn_3_bits_vaNeedExt,
  input  [63:0] io_storeAddrIn_3_bits_gpaddr,
  input  io_storeAddrIn_3_bits_isHyper,
  input  io_storeAddrIn_3_bits_isForVSnonLeafPTE,
  input  io_storeAddrIn_4_valid,
  input  io_storeAddrIn_4_bits_uop_exceptionVec_3,
  input  io_storeAddrIn_4_bits_uop_exceptionVec_6,
  input  io_storeAddrIn_4_bits_uop_exceptionVec_7,
  input  io_storeAddrIn_4_bits_uop_exceptionVec_15,
  input  io_storeAddrIn_4_bits_uop_exceptionVec_19,
  input  io_storeAddrIn_4_bits_uop_exceptionVec_23,
  input  [6:0] io_storeAddrIn_4_bits_uop_uopIdx,
  input  io_storeAddrIn_4_bits_uop_robIdx_flag,
  input  [7:0] io_storeAddrIn_4_bits_uop_robIdx_value,
  input  [63:0] io_storeAddrIn_4_bits_fullva,
  input  io_storeAddrIn_4_bits_vaNeedExt,
  input  [63:0] io_storeAddrIn_4_bits_gpaddr,
  input  io_storeAddrIn_4_bits_isForVSnonLeafPTE,
  input  io_storeAddrIn_5_valid,
  input  io_storeAddrIn_5_bits_uop_exceptionVec_3,
  input  io_storeAddrIn_5_bits_uop_exceptionVec_6,
  input  io_storeAddrIn_5_bits_uop_exceptionVec_7,
  input  io_storeAddrIn_5_bits_uop_exceptionVec_15,
  input  io_storeAddrIn_5_bits_uop_exceptionVec_19,
  input  io_storeAddrIn_5_bits_uop_exceptionVec_23,
  input  [6:0] io_storeAddrIn_5_bits_uop_uopIdx,
  input  io_storeAddrIn_5_bits_uop_robIdx_flag,
  input  [7:0] io_storeAddrIn_5_bits_uop_robIdx_value,
  input  [63:0] io_storeAddrIn_5_bits_fullva,
  input  io_storeAddrIn_5_bits_vaNeedExt,
  input  [63:0] io_storeAddrIn_5_bits_gpaddr,
  input  io_storeAddrIn_5_bits_isForVSnonLeafPTE,
  input  io_storeAddrIn_6_valid,
  input  io_storeAddrIn_6_bits_uop_exceptionVec_19,
  input  [6:0] io_storeAddrIn_6_bits_uop_uopIdx,
  input  io_storeAddrIn_6_bits_uop_robIdx_flag,
  input  [7:0] io_storeAddrIn_6_bits_uop_robIdx_value,
  input  [63:0] io_storeAddrIn_6_bits_fullva,
  output [63:0] io_exceptionAddr_vaddr,
  output io_exceptionAddr_vaNeedExt,
  output io_exceptionAddr_isHyper,
  output [63:0] io_exceptionAddr_gpaddr,
  output io_exceptionAddr_isForVSnonLeafPTE
);
endmodule
