// 自动生成：scripts/gen_storemisalignbuffer.py —— 勿手改
module StoreMisalignBuffer(
  input  clock,
  input  reset,
  input  io_redirect_valid,
  input  io_redirect_bits_robIdx_flag,
  input  [7:0] io_redirect_bits_robIdx_value,
  input  io_redirect_bits_level,
  output io_enq_0_req_ready,
  input  io_enq_0_req_valid,
  input  io_enq_0_req_bits_uop_exceptionVec_0,
  input  io_enq_0_req_bits_uop_exceptionVec_1,
  input  io_enq_0_req_bits_uop_exceptionVec_2,
  input  io_enq_0_req_bits_uop_exceptionVec_4,
  input  io_enq_0_req_bits_uop_exceptionVec_5,
  input  io_enq_0_req_bits_uop_exceptionVec_8,
  input  io_enq_0_req_bits_uop_exceptionVec_9,
  input  io_enq_0_req_bits_uop_exceptionVec_10,
  input  io_enq_0_req_bits_uop_exceptionVec_11,
  input  io_enq_0_req_bits_uop_exceptionVec_12,
  input  io_enq_0_req_bits_uop_exceptionVec_13,
  input  io_enq_0_req_bits_uop_exceptionVec_14,
  input  io_enq_0_req_bits_uop_exceptionVec_16,
  input  io_enq_0_req_bits_uop_exceptionVec_17,
  input  io_enq_0_req_bits_uop_exceptionVec_18,
  input  io_enq_0_req_bits_uop_exceptionVec_19,
  input  io_enq_0_req_bits_uop_exceptionVec_20,
  input  io_enq_0_req_bits_uop_exceptionVec_21,
  input  io_enq_0_req_bits_uop_exceptionVec_22,
  input  [3:0] io_enq_0_req_bits_uop_trigger,
  input  [5:0] io_enq_0_req_bits_uop_ftqPtr_value,
  input  [3:0] io_enq_0_req_bits_uop_ftqOffset,
  input  [8:0] io_enq_0_req_bits_uop_fuOpType,
  input  [7:0] io_enq_0_req_bits_uop_vpu_vstart,
  input  [1:0] io_enq_0_req_bits_uop_vpu_veew,
  input  [6:0] io_enq_0_req_bits_uop_uopIdx,
  input  io_enq_0_req_bits_uop_robIdx_flag,
  input  [7:0] io_enq_0_req_bits_uop_robIdx_value,
  input  [63:0] io_enq_0_req_bits_uop_debugInfo_enqRsTime,
  input  [63:0] io_enq_0_req_bits_uop_debugInfo_selectTime,
  input  [63:0] io_enq_0_req_bits_uop_debugInfo_issueTime,
  input  io_enq_0_req_bits_uop_sqIdx_flag,
  input  [5:0] io_enq_0_req_bits_uop_sqIdx_value,
  input  [49:0] io_enq_0_req_bits_vaddr,
  input  [15:0] io_enq_0_req_bits_mask,
  input  io_enq_0_req_bits_isvec,
  input  [7:0] io_enq_0_req_bits_elemIdx,
  input  [2:0] io_enq_0_req_bits_alignedType,
  input  [3:0] io_enq_0_req_bits_mbIndex,
  input  io_enq_0_revoke,
  output io_enq_1_req_ready,
  input  io_enq_1_req_valid,
  input  io_enq_1_req_bits_uop_exceptionVec_0,
  input  io_enq_1_req_bits_uop_exceptionVec_1,
  input  io_enq_1_req_bits_uop_exceptionVec_2,
  input  io_enq_1_req_bits_uop_exceptionVec_4,
  input  io_enq_1_req_bits_uop_exceptionVec_5,
  input  io_enq_1_req_bits_uop_exceptionVec_8,
  input  io_enq_1_req_bits_uop_exceptionVec_9,
  input  io_enq_1_req_bits_uop_exceptionVec_10,
  input  io_enq_1_req_bits_uop_exceptionVec_11,
  input  io_enq_1_req_bits_uop_exceptionVec_12,
  input  io_enq_1_req_bits_uop_exceptionVec_13,
  input  io_enq_1_req_bits_uop_exceptionVec_14,
  input  io_enq_1_req_bits_uop_exceptionVec_16,
  input  io_enq_1_req_bits_uop_exceptionVec_17,
  input  io_enq_1_req_bits_uop_exceptionVec_18,
  input  io_enq_1_req_bits_uop_exceptionVec_19,
  input  io_enq_1_req_bits_uop_exceptionVec_20,
  input  io_enq_1_req_bits_uop_exceptionVec_21,
  input  io_enq_1_req_bits_uop_exceptionVec_22,
  input  [3:0] io_enq_1_req_bits_uop_trigger,
  input  [5:0] io_enq_1_req_bits_uop_ftqPtr_value,
  input  [3:0] io_enq_1_req_bits_uop_ftqOffset,
  input  [8:0] io_enq_1_req_bits_uop_fuOpType,
  input  [7:0] io_enq_1_req_bits_uop_vpu_vstart,
  input  [1:0] io_enq_1_req_bits_uop_vpu_veew,
  input  [6:0] io_enq_1_req_bits_uop_uopIdx,
  input  io_enq_1_req_bits_uop_robIdx_flag,
  input  [7:0] io_enq_1_req_bits_uop_robIdx_value,
  input  [63:0] io_enq_1_req_bits_uop_debugInfo_enqRsTime,
  input  [63:0] io_enq_1_req_bits_uop_debugInfo_selectTime,
  input  [63:0] io_enq_1_req_bits_uop_debugInfo_issueTime,
  input  io_enq_1_req_bits_uop_sqIdx_flag,
  input  [5:0] io_enq_1_req_bits_uop_sqIdx_value,
  input  [49:0] io_enq_1_req_bits_vaddr,
  input  [15:0] io_enq_1_req_bits_mask,
  input  io_enq_1_req_bits_isvec,
  input  [7:0] io_enq_1_req_bits_elemIdx,
  input  [2:0] io_enq_1_req_bits_alignedType,
  input  [3:0] io_enq_1_req_bits_mbIndex,
  input  io_enq_1_revoke,
  input  io_rob_pendingst,
  input  io_rob_pendingPtr_flag,
  input  [7:0] io_rob_pendingPtr_value,
  input  io_splitStoreReq_ready,
  output io_splitStoreReq_valid,
  output io_splitStoreReq_bits_uop_exceptionVec_0,
  output io_splitStoreReq_bits_uop_exceptionVec_1,
  output io_splitStoreReq_bits_uop_exceptionVec_2,
  output io_splitStoreReq_bits_uop_exceptionVec_4,
  output io_splitStoreReq_bits_uop_exceptionVec_5,
  output io_splitStoreReq_bits_uop_exceptionVec_8,
  output io_splitStoreReq_bits_uop_exceptionVec_9,
  output io_splitStoreReq_bits_uop_exceptionVec_10,
  output io_splitStoreReq_bits_uop_exceptionVec_11,
  output io_splitStoreReq_bits_uop_exceptionVec_12,
  output io_splitStoreReq_bits_uop_exceptionVec_13,
  output io_splitStoreReq_bits_uop_exceptionVec_14,
  output io_splitStoreReq_bits_uop_exceptionVec_16,
  output io_splitStoreReq_bits_uop_exceptionVec_17,
  output io_splitStoreReq_bits_uop_exceptionVec_18,
  output io_splitStoreReq_bits_uop_exceptionVec_19,
  output io_splitStoreReq_bits_uop_exceptionVec_20,
  output io_splitStoreReq_bits_uop_exceptionVec_21,
  output io_splitStoreReq_bits_uop_exceptionVec_22,
  output [3:0] io_splitStoreReq_bits_uop_trigger,
  output [5:0] io_splitStoreReq_bits_uop_ftqPtr_value,
  output [3:0] io_splitStoreReq_bits_uop_ftqOffset,
  output [8:0] io_splitStoreReq_bits_uop_fuOpType,
  output [7:0] io_splitStoreReq_bits_uop_vpu_vstart,
  output [1:0] io_splitStoreReq_bits_uop_vpu_veew,
  output [6:0] io_splitStoreReq_bits_uop_uopIdx,
  output io_splitStoreReq_bits_uop_robIdx_flag,
  output [7:0] io_splitStoreReq_bits_uop_robIdx_value,
  output [63:0] io_splitStoreReq_bits_uop_debugInfo_enqRsTime,
  output [63:0] io_splitStoreReq_bits_uop_debugInfo_selectTime,
  output [63:0] io_splitStoreReq_bits_uop_debugInfo_issueTime,
  output io_splitStoreReq_bits_uop_sqIdx_flag,
  output [5:0] io_splitStoreReq_bits_uop_sqIdx_value,
  output [49:0] io_splitStoreReq_bits_vaddr,
  output [15:0] io_splitStoreReq_bits_mask,
  output io_splitStoreReq_bits_isvec,
  output io_splitStoreReq_bits_is128bit,
  output io_splitStoreReq_bits_isFinalSplit,
  input  io_splitStoreResp_valid,
  input  io_splitStoreResp_bits_uop_exceptionVec_3,
  input  io_splitStoreResp_bits_uop_exceptionVec_6,
  input  io_splitStoreResp_bits_uop_exceptionVec_7,
  input  io_splitStoreResp_bits_uop_exceptionVec_15,
  input  io_splitStoreResp_bits_uop_exceptionVec_19,
  input  io_splitStoreResp_bits_uop_exceptionVec_23,
  input  [3:0] io_splitStoreResp_bits_uop_trigger,
  input  [47:0] io_splitStoreResp_bits_paddr,
  input  io_splitStoreResp_bits_nc,
  input  io_splitStoreResp_bits_mmio,
  input  io_splitStoreResp_bits_memBackTypeMM,
  input  io_splitStoreResp_bits_vecActive,
  input  io_splitStoreResp_bits_need_rep,
  input  io_writeBack_ready,
  output io_writeBack_valid,
  output io_writeBack_bits_uop_exceptionVec_3,
  output io_writeBack_bits_uop_exceptionVec_6,
  output io_writeBack_bits_uop_exceptionVec_7,
  output io_writeBack_bits_uop_exceptionVec_15,
  output io_writeBack_bits_uop_exceptionVec_19,
  output io_writeBack_bits_uop_exceptionVec_23,
  output [3:0] io_writeBack_bits_uop_trigger,
  output io_writeBack_bits_uop_flushPipe,
  output io_writeBack_bits_uop_robIdx_flag,
  output [7:0] io_writeBack_bits_uop_robIdx_value,
  output [63:0] io_writeBack_bits_uop_debugInfo_enqRsTime,
  output [63:0] io_writeBack_bits_uop_debugInfo_selectTime,
  output [63:0] io_writeBack_bits_uop_debugInfo_issueTime,
  output io_writeBack_bits_debug_isMMIO,
  output io_writeBack_bits_debug_isNCIO,
  output io_vecWriteBack_0_valid,
  output [3:0] io_vecWriteBack_0_bits_mBIndex,
  output io_vecWriteBack_0_bits_exceptionVec_3,
  output io_vecWriteBack_0_bits_exceptionVec_6,
  output io_vecWriteBack_0_bits_exceptionVec_7,
  output io_vecWriteBack_0_bits_exceptionVec_15,
  output io_vecWriteBack_0_bits_exceptionVec_19,
  output io_vecWriteBack_0_bits_exceptionVec_23,
  output io_vecWriteBack_0_bits_hasException,
  output [63:0] io_vecWriteBack_0_bits_vaddr,
  output io_vecWriteBack_0_bits_vaNeedExt,
  output [63:0] io_vecWriteBack_0_bits_gpaddr,
  output io_vecWriteBack_0_bits_isForVSnonLeafPTE,
  output [7:0] io_vecWriteBack_0_bits_vstart,
  output [7:0] io_vecWriteBack_0_bits_elemIdx,
  output [15:0] io_vecWriteBack_0_bits_mask,
  output io_vecWriteBack_1_valid,
  output [3:0] io_vecWriteBack_1_bits_mBIndex,
  output io_vecWriteBack_1_bits_exceptionVec_3,
  output io_vecWriteBack_1_bits_exceptionVec_6,
  output io_vecWriteBack_1_bits_exceptionVec_7,
  output io_vecWriteBack_1_bits_exceptionVec_15,
  output io_vecWriteBack_1_bits_exceptionVec_19,
  output io_vecWriteBack_1_bits_exceptionVec_23,
  output io_vecWriteBack_1_bits_hasException,
  output [63:0] io_vecWriteBack_1_bits_vaddr,
  output io_vecWriteBack_1_bits_vaNeedExt,
  output [63:0] io_vecWriteBack_1_bits_gpaddr,
  output io_vecWriteBack_1_bits_isForVSnonLeafPTE,
  output [7:0] io_vecWriteBack_1_bits_vstart,
  output [7:0] io_vecWriteBack_1_bits_elemIdx,
  output [15:0] io_vecWriteBack_1_bits_mask,
  input  io_storeOutValid,
  input  io_storeVecOutValid,
  output io_sqControl_toStoreQueue_crossPageWithHit,
  output io_sqControl_toStoreQueue_crossPageCanDeq,
  output [47:0] io_sqControl_toStoreQueue_paddr,
  output io_sqControl_toStoreQueue_withSameUop,
  input  io_sqControl_toStoreMisalignBuffer_sqPtr_flag,
  input  [5:0] io_sqControl_toStoreMisalignBuffer_sqPtr_value,
  input  io_sqControl_toStoreMisalignBuffer_doDeq,
  input  [6:0] io_sqControl_toStoreMisalignBuffer_uop_uopIdx,
  input  io_sqControl_toStoreMisalignBuffer_uop_robIdx_flag,
  input  [7:0] io_sqControl_toStoreMisalignBuffer_uop_robIdx_value,
  output [3:0] io_toVecStoreMergeBuffer_0_mbIndex,
  output io_toVecStoreMergeBuffer_0_flush,
  output [3:0] io_toVecStoreMergeBuffer_1_mbIndex,
  output io_toVecStoreMergeBuffer_1_flush,
  output io_full
);
  xs_StoreMisalignBuffer_core u_core (
    .clock(clock),
    .reset(reset),
    .io_redirect_valid(io_redirect_valid),
    .io_redirect_bits_robIdx_flag(io_redirect_bits_robIdx_flag),
    .io_redirect_bits_robIdx_value(io_redirect_bits_robIdx_value),
    .io_redirect_bits_level(io_redirect_bits_level),
    .io_enq_0_req_ready(io_enq_0_req_ready),
    .io_enq_0_req_valid(io_enq_0_req_valid),
    .io_enq_0_req_bits_uop_exceptionVec_0(io_enq_0_req_bits_uop_exceptionVec_0),
    .io_enq_0_req_bits_uop_exceptionVec_1(io_enq_0_req_bits_uop_exceptionVec_1),
    .io_enq_0_req_bits_uop_exceptionVec_2(io_enq_0_req_bits_uop_exceptionVec_2),
    .io_enq_0_req_bits_uop_exceptionVec_4(io_enq_0_req_bits_uop_exceptionVec_4),
    .io_enq_0_req_bits_uop_exceptionVec_5(io_enq_0_req_bits_uop_exceptionVec_5),
    .io_enq_0_req_bits_uop_exceptionVec_8(io_enq_0_req_bits_uop_exceptionVec_8),
    .io_enq_0_req_bits_uop_exceptionVec_9(io_enq_0_req_bits_uop_exceptionVec_9),
    .io_enq_0_req_bits_uop_exceptionVec_10(io_enq_0_req_bits_uop_exceptionVec_10),
    .io_enq_0_req_bits_uop_exceptionVec_11(io_enq_0_req_bits_uop_exceptionVec_11),
    .io_enq_0_req_bits_uop_exceptionVec_12(io_enq_0_req_bits_uop_exceptionVec_12),
    .io_enq_0_req_bits_uop_exceptionVec_13(io_enq_0_req_bits_uop_exceptionVec_13),
    .io_enq_0_req_bits_uop_exceptionVec_14(io_enq_0_req_bits_uop_exceptionVec_14),
    .io_enq_0_req_bits_uop_exceptionVec_16(io_enq_0_req_bits_uop_exceptionVec_16),
    .io_enq_0_req_bits_uop_exceptionVec_17(io_enq_0_req_bits_uop_exceptionVec_17),
    .io_enq_0_req_bits_uop_exceptionVec_18(io_enq_0_req_bits_uop_exceptionVec_18),
    .io_enq_0_req_bits_uop_exceptionVec_19(io_enq_0_req_bits_uop_exceptionVec_19),
    .io_enq_0_req_bits_uop_exceptionVec_20(io_enq_0_req_bits_uop_exceptionVec_20),
    .io_enq_0_req_bits_uop_exceptionVec_21(io_enq_0_req_bits_uop_exceptionVec_21),
    .io_enq_0_req_bits_uop_exceptionVec_22(io_enq_0_req_bits_uop_exceptionVec_22),
    .io_enq_0_req_bits_uop_trigger(io_enq_0_req_bits_uop_trigger),
    .io_enq_0_req_bits_uop_ftqPtr_value(io_enq_0_req_bits_uop_ftqPtr_value),
    .io_enq_0_req_bits_uop_ftqOffset(io_enq_0_req_bits_uop_ftqOffset),
    .io_enq_0_req_bits_uop_fuOpType(io_enq_0_req_bits_uop_fuOpType),
    .io_enq_0_req_bits_uop_vpu_vstart(io_enq_0_req_bits_uop_vpu_vstart),
    .io_enq_0_req_bits_uop_vpu_veew(io_enq_0_req_bits_uop_vpu_veew),
    .io_enq_0_req_bits_uop_uopIdx(io_enq_0_req_bits_uop_uopIdx),
    .io_enq_0_req_bits_uop_robIdx_flag(io_enq_0_req_bits_uop_robIdx_flag),
    .io_enq_0_req_bits_uop_robIdx_value(io_enq_0_req_bits_uop_robIdx_value),
    .io_enq_0_req_bits_uop_debugInfo_enqRsTime(io_enq_0_req_bits_uop_debugInfo_enqRsTime),
    .io_enq_0_req_bits_uop_debugInfo_selectTime(io_enq_0_req_bits_uop_debugInfo_selectTime),
    .io_enq_0_req_bits_uop_debugInfo_issueTime(io_enq_0_req_bits_uop_debugInfo_issueTime),
    .io_enq_0_req_bits_uop_sqIdx_flag(io_enq_0_req_bits_uop_sqIdx_flag),
    .io_enq_0_req_bits_uop_sqIdx_value(io_enq_0_req_bits_uop_sqIdx_value),
    .io_enq_0_req_bits_vaddr(io_enq_0_req_bits_vaddr),
    .io_enq_0_req_bits_mask(io_enq_0_req_bits_mask),
    .io_enq_0_req_bits_isvec(io_enq_0_req_bits_isvec),
    .io_enq_0_req_bits_elemIdx(io_enq_0_req_bits_elemIdx),
    .io_enq_0_req_bits_alignedType(io_enq_0_req_bits_alignedType),
    .io_enq_0_req_bits_mbIndex(io_enq_0_req_bits_mbIndex),
    .io_enq_0_revoke(io_enq_0_revoke),
    .io_enq_1_req_ready(io_enq_1_req_ready),
    .io_enq_1_req_valid(io_enq_1_req_valid),
    .io_enq_1_req_bits_uop_exceptionVec_0(io_enq_1_req_bits_uop_exceptionVec_0),
    .io_enq_1_req_bits_uop_exceptionVec_1(io_enq_1_req_bits_uop_exceptionVec_1),
    .io_enq_1_req_bits_uop_exceptionVec_2(io_enq_1_req_bits_uop_exceptionVec_2),
    .io_enq_1_req_bits_uop_exceptionVec_4(io_enq_1_req_bits_uop_exceptionVec_4),
    .io_enq_1_req_bits_uop_exceptionVec_5(io_enq_1_req_bits_uop_exceptionVec_5),
    .io_enq_1_req_bits_uop_exceptionVec_8(io_enq_1_req_bits_uop_exceptionVec_8),
    .io_enq_1_req_bits_uop_exceptionVec_9(io_enq_1_req_bits_uop_exceptionVec_9),
    .io_enq_1_req_bits_uop_exceptionVec_10(io_enq_1_req_bits_uop_exceptionVec_10),
    .io_enq_1_req_bits_uop_exceptionVec_11(io_enq_1_req_bits_uop_exceptionVec_11),
    .io_enq_1_req_bits_uop_exceptionVec_12(io_enq_1_req_bits_uop_exceptionVec_12),
    .io_enq_1_req_bits_uop_exceptionVec_13(io_enq_1_req_bits_uop_exceptionVec_13),
    .io_enq_1_req_bits_uop_exceptionVec_14(io_enq_1_req_bits_uop_exceptionVec_14),
    .io_enq_1_req_bits_uop_exceptionVec_16(io_enq_1_req_bits_uop_exceptionVec_16),
    .io_enq_1_req_bits_uop_exceptionVec_17(io_enq_1_req_bits_uop_exceptionVec_17),
    .io_enq_1_req_bits_uop_exceptionVec_18(io_enq_1_req_bits_uop_exceptionVec_18),
    .io_enq_1_req_bits_uop_exceptionVec_19(io_enq_1_req_bits_uop_exceptionVec_19),
    .io_enq_1_req_bits_uop_exceptionVec_20(io_enq_1_req_bits_uop_exceptionVec_20),
    .io_enq_1_req_bits_uop_exceptionVec_21(io_enq_1_req_bits_uop_exceptionVec_21),
    .io_enq_1_req_bits_uop_exceptionVec_22(io_enq_1_req_bits_uop_exceptionVec_22),
    .io_enq_1_req_bits_uop_trigger(io_enq_1_req_bits_uop_trigger),
    .io_enq_1_req_bits_uop_ftqPtr_value(io_enq_1_req_bits_uop_ftqPtr_value),
    .io_enq_1_req_bits_uop_ftqOffset(io_enq_1_req_bits_uop_ftqOffset),
    .io_enq_1_req_bits_uop_fuOpType(io_enq_1_req_bits_uop_fuOpType),
    .io_enq_1_req_bits_uop_vpu_vstart(io_enq_1_req_bits_uop_vpu_vstart),
    .io_enq_1_req_bits_uop_vpu_veew(io_enq_1_req_bits_uop_vpu_veew),
    .io_enq_1_req_bits_uop_uopIdx(io_enq_1_req_bits_uop_uopIdx),
    .io_enq_1_req_bits_uop_robIdx_flag(io_enq_1_req_bits_uop_robIdx_flag),
    .io_enq_1_req_bits_uop_robIdx_value(io_enq_1_req_bits_uop_robIdx_value),
    .io_enq_1_req_bits_uop_debugInfo_enqRsTime(io_enq_1_req_bits_uop_debugInfo_enqRsTime),
    .io_enq_1_req_bits_uop_debugInfo_selectTime(io_enq_1_req_bits_uop_debugInfo_selectTime),
    .io_enq_1_req_bits_uop_debugInfo_issueTime(io_enq_1_req_bits_uop_debugInfo_issueTime),
    .io_enq_1_req_bits_uop_sqIdx_flag(io_enq_1_req_bits_uop_sqIdx_flag),
    .io_enq_1_req_bits_uop_sqIdx_value(io_enq_1_req_bits_uop_sqIdx_value),
    .io_enq_1_req_bits_vaddr(io_enq_1_req_bits_vaddr),
    .io_enq_1_req_bits_mask(io_enq_1_req_bits_mask),
    .io_enq_1_req_bits_isvec(io_enq_1_req_bits_isvec),
    .io_enq_1_req_bits_elemIdx(io_enq_1_req_bits_elemIdx),
    .io_enq_1_req_bits_alignedType(io_enq_1_req_bits_alignedType),
    .io_enq_1_req_bits_mbIndex(io_enq_1_req_bits_mbIndex),
    .io_enq_1_revoke(io_enq_1_revoke),
    .io_rob_pendingst(io_rob_pendingst),
    .io_rob_pendingPtr_flag(io_rob_pendingPtr_flag),
    .io_rob_pendingPtr_value(io_rob_pendingPtr_value),
    .io_splitStoreReq_ready(io_splitStoreReq_ready),
    .io_splitStoreReq_valid(io_splitStoreReq_valid),
    .io_splitStoreReq_bits_uop_exceptionVec_0(io_splitStoreReq_bits_uop_exceptionVec_0),
    .io_splitStoreReq_bits_uop_exceptionVec_1(io_splitStoreReq_bits_uop_exceptionVec_1),
    .io_splitStoreReq_bits_uop_exceptionVec_2(io_splitStoreReq_bits_uop_exceptionVec_2),
    .io_splitStoreReq_bits_uop_exceptionVec_4(io_splitStoreReq_bits_uop_exceptionVec_4),
    .io_splitStoreReq_bits_uop_exceptionVec_5(io_splitStoreReq_bits_uop_exceptionVec_5),
    .io_splitStoreReq_bits_uop_exceptionVec_8(io_splitStoreReq_bits_uop_exceptionVec_8),
    .io_splitStoreReq_bits_uop_exceptionVec_9(io_splitStoreReq_bits_uop_exceptionVec_9),
    .io_splitStoreReq_bits_uop_exceptionVec_10(io_splitStoreReq_bits_uop_exceptionVec_10),
    .io_splitStoreReq_bits_uop_exceptionVec_11(io_splitStoreReq_bits_uop_exceptionVec_11),
    .io_splitStoreReq_bits_uop_exceptionVec_12(io_splitStoreReq_bits_uop_exceptionVec_12),
    .io_splitStoreReq_bits_uop_exceptionVec_13(io_splitStoreReq_bits_uop_exceptionVec_13),
    .io_splitStoreReq_bits_uop_exceptionVec_14(io_splitStoreReq_bits_uop_exceptionVec_14),
    .io_splitStoreReq_bits_uop_exceptionVec_16(io_splitStoreReq_bits_uop_exceptionVec_16),
    .io_splitStoreReq_bits_uop_exceptionVec_17(io_splitStoreReq_bits_uop_exceptionVec_17),
    .io_splitStoreReq_bits_uop_exceptionVec_18(io_splitStoreReq_bits_uop_exceptionVec_18),
    .io_splitStoreReq_bits_uop_exceptionVec_19(io_splitStoreReq_bits_uop_exceptionVec_19),
    .io_splitStoreReq_bits_uop_exceptionVec_20(io_splitStoreReq_bits_uop_exceptionVec_20),
    .io_splitStoreReq_bits_uop_exceptionVec_21(io_splitStoreReq_bits_uop_exceptionVec_21),
    .io_splitStoreReq_bits_uop_exceptionVec_22(io_splitStoreReq_bits_uop_exceptionVec_22),
    .io_splitStoreReq_bits_uop_trigger(io_splitStoreReq_bits_uop_trigger),
    .io_splitStoreReq_bits_uop_ftqPtr_value(io_splitStoreReq_bits_uop_ftqPtr_value),
    .io_splitStoreReq_bits_uop_ftqOffset(io_splitStoreReq_bits_uop_ftqOffset),
    .io_splitStoreReq_bits_uop_fuOpType(io_splitStoreReq_bits_uop_fuOpType),
    .io_splitStoreReq_bits_uop_vpu_vstart(io_splitStoreReq_bits_uop_vpu_vstart),
    .io_splitStoreReq_bits_uop_vpu_veew(io_splitStoreReq_bits_uop_vpu_veew),
    .io_splitStoreReq_bits_uop_uopIdx(io_splitStoreReq_bits_uop_uopIdx),
    .io_splitStoreReq_bits_uop_robIdx_flag(io_splitStoreReq_bits_uop_robIdx_flag),
    .io_splitStoreReq_bits_uop_robIdx_value(io_splitStoreReq_bits_uop_robIdx_value),
    .io_splitStoreReq_bits_uop_debugInfo_enqRsTime(io_splitStoreReq_bits_uop_debugInfo_enqRsTime),
    .io_splitStoreReq_bits_uop_debugInfo_selectTime(io_splitStoreReq_bits_uop_debugInfo_selectTime),
    .io_splitStoreReq_bits_uop_debugInfo_issueTime(io_splitStoreReq_bits_uop_debugInfo_issueTime),
    .io_splitStoreReq_bits_uop_sqIdx_flag(io_splitStoreReq_bits_uop_sqIdx_flag),
    .io_splitStoreReq_bits_uop_sqIdx_value(io_splitStoreReq_bits_uop_sqIdx_value),
    .io_splitStoreReq_bits_vaddr(io_splitStoreReq_bits_vaddr),
    .io_splitStoreReq_bits_mask(io_splitStoreReq_bits_mask),
    .io_splitStoreReq_bits_isvec(io_splitStoreReq_bits_isvec),
    .io_splitStoreReq_bits_is128bit(io_splitStoreReq_bits_is128bit),
    .io_splitStoreReq_bits_isFinalSplit(io_splitStoreReq_bits_isFinalSplit),
    .io_splitStoreResp_valid(io_splitStoreResp_valid),
    .io_splitStoreResp_bits_uop_exceptionVec_3(io_splitStoreResp_bits_uop_exceptionVec_3),
    .io_splitStoreResp_bits_uop_exceptionVec_6(io_splitStoreResp_bits_uop_exceptionVec_6),
    .io_splitStoreResp_bits_uop_exceptionVec_7(io_splitStoreResp_bits_uop_exceptionVec_7),
    .io_splitStoreResp_bits_uop_exceptionVec_15(io_splitStoreResp_bits_uop_exceptionVec_15),
    .io_splitStoreResp_bits_uop_exceptionVec_19(io_splitStoreResp_bits_uop_exceptionVec_19),
    .io_splitStoreResp_bits_uop_exceptionVec_23(io_splitStoreResp_bits_uop_exceptionVec_23),
    .io_splitStoreResp_bits_uop_trigger(io_splitStoreResp_bits_uop_trigger),
    .io_splitStoreResp_bits_paddr(io_splitStoreResp_bits_paddr),
    .io_splitStoreResp_bits_nc(io_splitStoreResp_bits_nc),
    .io_splitStoreResp_bits_mmio(io_splitStoreResp_bits_mmio),
    .io_splitStoreResp_bits_memBackTypeMM(io_splitStoreResp_bits_memBackTypeMM),
    .io_splitStoreResp_bits_vecActive(io_splitStoreResp_bits_vecActive),
    .io_splitStoreResp_bits_need_rep(io_splitStoreResp_bits_need_rep),
    .io_writeBack_ready(io_writeBack_ready),
    .io_writeBack_valid(io_writeBack_valid),
    .io_writeBack_bits_uop_exceptionVec_3(io_writeBack_bits_uop_exceptionVec_3),
    .io_writeBack_bits_uop_exceptionVec_6(io_writeBack_bits_uop_exceptionVec_6),
    .io_writeBack_bits_uop_exceptionVec_7(io_writeBack_bits_uop_exceptionVec_7),
    .io_writeBack_bits_uop_exceptionVec_15(io_writeBack_bits_uop_exceptionVec_15),
    .io_writeBack_bits_uop_exceptionVec_19(io_writeBack_bits_uop_exceptionVec_19),
    .io_writeBack_bits_uop_exceptionVec_23(io_writeBack_bits_uop_exceptionVec_23),
    .io_writeBack_bits_uop_trigger(io_writeBack_bits_uop_trigger),
    .io_writeBack_bits_uop_flushPipe(io_writeBack_bits_uop_flushPipe),
    .io_writeBack_bits_uop_robIdx_flag(io_writeBack_bits_uop_robIdx_flag),
    .io_writeBack_bits_uop_robIdx_value(io_writeBack_bits_uop_robIdx_value),
    .io_writeBack_bits_uop_debugInfo_enqRsTime(io_writeBack_bits_uop_debugInfo_enqRsTime),
    .io_writeBack_bits_uop_debugInfo_selectTime(io_writeBack_bits_uop_debugInfo_selectTime),
    .io_writeBack_bits_uop_debugInfo_issueTime(io_writeBack_bits_uop_debugInfo_issueTime),
    .io_writeBack_bits_debug_isMMIO(io_writeBack_bits_debug_isMMIO),
    .io_writeBack_bits_debug_isNCIO(io_writeBack_bits_debug_isNCIO),
    .io_vecWriteBack_0_valid(io_vecWriteBack_0_valid),
    .io_vecWriteBack_0_bits_mBIndex(io_vecWriteBack_0_bits_mBIndex),
    .io_vecWriteBack_0_bits_exceptionVec_3(io_vecWriteBack_0_bits_exceptionVec_3),
    .io_vecWriteBack_0_bits_exceptionVec_6(io_vecWriteBack_0_bits_exceptionVec_6),
    .io_vecWriteBack_0_bits_exceptionVec_7(io_vecWriteBack_0_bits_exceptionVec_7),
    .io_vecWriteBack_0_bits_exceptionVec_15(io_vecWriteBack_0_bits_exceptionVec_15),
    .io_vecWriteBack_0_bits_exceptionVec_19(io_vecWriteBack_0_bits_exceptionVec_19),
    .io_vecWriteBack_0_bits_exceptionVec_23(io_vecWriteBack_0_bits_exceptionVec_23),
    .io_vecWriteBack_0_bits_hasException(io_vecWriteBack_0_bits_hasException),
    .io_vecWriteBack_0_bits_vaddr(io_vecWriteBack_0_bits_vaddr),
    .io_vecWriteBack_0_bits_vaNeedExt(io_vecWriteBack_0_bits_vaNeedExt),
    .io_vecWriteBack_0_bits_gpaddr(io_vecWriteBack_0_bits_gpaddr),
    .io_vecWriteBack_0_bits_isForVSnonLeafPTE(io_vecWriteBack_0_bits_isForVSnonLeafPTE),
    .io_vecWriteBack_0_bits_vstart(io_vecWriteBack_0_bits_vstart),
    .io_vecWriteBack_0_bits_elemIdx(io_vecWriteBack_0_bits_elemIdx),
    .io_vecWriteBack_0_bits_mask(io_vecWriteBack_0_bits_mask),
    .io_vecWriteBack_1_valid(io_vecWriteBack_1_valid),
    .io_vecWriteBack_1_bits_mBIndex(io_vecWriteBack_1_bits_mBIndex),
    .io_vecWriteBack_1_bits_exceptionVec_3(io_vecWriteBack_1_bits_exceptionVec_3),
    .io_vecWriteBack_1_bits_exceptionVec_6(io_vecWriteBack_1_bits_exceptionVec_6),
    .io_vecWriteBack_1_bits_exceptionVec_7(io_vecWriteBack_1_bits_exceptionVec_7),
    .io_vecWriteBack_1_bits_exceptionVec_15(io_vecWriteBack_1_bits_exceptionVec_15),
    .io_vecWriteBack_1_bits_exceptionVec_19(io_vecWriteBack_1_bits_exceptionVec_19),
    .io_vecWriteBack_1_bits_exceptionVec_23(io_vecWriteBack_1_bits_exceptionVec_23),
    .io_vecWriteBack_1_bits_hasException(io_vecWriteBack_1_bits_hasException),
    .io_vecWriteBack_1_bits_vaddr(io_vecWriteBack_1_bits_vaddr),
    .io_vecWriteBack_1_bits_vaNeedExt(io_vecWriteBack_1_bits_vaNeedExt),
    .io_vecWriteBack_1_bits_gpaddr(io_vecWriteBack_1_bits_gpaddr),
    .io_vecWriteBack_1_bits_isForVSnonLeafPTE(io_vecWriteBack_1_bits_isForVSnonLeafPTE),
    .io_vecWriteBack_1_bits_vstart(io_vecWriteBack_1_bits_vstart),
    .io_vecWriteBack_1_bits_elemIdx(io_vecWriteBack_1_bits_elemIdx),
    .io_vecWriteBack_1_bits_mask(io_vecWriteBack_1_bits_mask),
    .io_storeOutValid(io_storeOutValid),
    .io_storeVecOutValid(io_storeVecOutValid),
    .io_sqControl_toStoreQueue_crossPageWithHit(io_sqControl_toStoreQueue_crossPageWithHit),
    .io_sqControl_toStoreQueue_crossPageCanDeq(io_sqControl_toStoreQueue_crossPageCanDeq),
    .io_sqControl_toStoreQueue_paddr(io_sqControl_toStoreQueue_paddr),
    .io_sqControl_toStoreQueue_withSameUop(io_sqControl_toStoreQueue_withSameUop),
    .io_sqControl_toStoreMisalignBuffer_sqPtr_flag(io_sqControl_toStoreMisalignBuffer_sqPtr_flag),
    .io_sqControl_toStoreMisalignBuffer_sqPtr_value(io_sqControl_toStoreMisalignBuffer_sqPtr_value),
    .io_sqControl_toStoreMisalignBuffer_doDeq(io_sqControl_toStoreMisalignBuffer_doDeq),
    .io_sqControl_toStoreMisalignBuffer_uop_uopIdx(io_sqControl_toStoreMisalignBuffer_uop_uopIdx),
    .io_sqControl_toStoreMisalignBuffer_uop_robIdx_flag(io_sqControl_toStoreMisalignBuffer_uop_robIdx_flag),
    .io_sqControl_toStoreMisalignBuffer_uop_robIdx_value(io_sqControl_toStoreMisalignBuffer_uop_robIdx_value),
    .io_toVecStoreMergeBuffer_0_mbIndex(io_toVecStoreMergeBuffer_0_mbIndex),
    .io_toVecStoreMergeBuffer_0_flush(io_toVecStoreMergeBuffer_0_flush),
    .io_toVecStoreMergeBuffer_1_mbIndex(io_toVecStoreMergeBuffer_1_mbIndex),
    .io_toVecStoreMergeBuffer_1_flush(io_toVecStoreMergeBuffer_1_flush),
    .io_full(io_full)
  );
endmodule
