// 自动生成：scripts/gen_storequeue.py —— 勿手改
// exceptionBuffer 7 个输入口的核内 readable 网声明（被 §14 vec 驱动、subinst 引用）。
  logic eb_in_0_valid;
  logic eb_in_0_bits_uop_exceptionVec_3;
  logic eb_in_0_bits_uop_exceptionVec_6;
  logic eb_in_0_bits_uop_exceptionVec_7;
  logic eb_in_0_bits_uop_exceptionVec_15;
  logic eb_in_0_bits_uop_exceptionVec_19;
  logic eb_in_0_bits_uop_exceptionVec_23;
  logic [6:0] eb_in_0_bits_uop_uopIdx;
  logic eb_in_0_bits_uop_robIdx_flag;
  logic [7:0] eb_in_0_bits_uop_robIdx_value;
  logic [63:0] eb_in_0_bits_fullva;
  logic eb_in_0_bits_vaNeedExt;
  logic [63:0] eb_in_0_bits_gpaddr;
  logic eb_in_0_bits_isHyper;
  logic eb_in_0_bits_isForVSnonLeafPTE;
  logic eb_in_1_valid;
  logic eb_in_1_bits_uop_exceptionVec_3;
  logic eb_in_1_bits_uop_exceptionVec_6;
  logic eb_in_1_bits_uop_exceptionVec_7;
  logic eb_in_1_bits_uop_exceptionVec_15;
  logic eb_in_1_bits_uop_exceptionVec_19;
  logic eb_in_1_bits_uop_exceptionVec_23;
  logic [6:0] eb_in_1_bits_uop_uopIdx;
  logic eb_in_1_bits_uop_robIdx_flag;
  logic [7:0] eb_in_1_bits_uop_robIdx_value;
  logic [63:0] eb_in_1_bits_fullva;
  logic eb_in_1_bits_vaNeedExt;
  logic [63:0] eb_in_1_bits_gpaddr;
  logic eb_in_1_bits_isHyper;
  logic eb_in_1_bits_isForVSnonLeafPTE;
  logic eb_in_2_valid;
  logic eb_in_2_bits_uop_exceptionVec_3;
  logic eb_in_2_bits_uop_exceptionVec_6;
  logic eb_in_2_bits_uop_exceptionVec_7;
  logic eb_in_2_bits_uop_exceptionVec_15;
  logic eb_in_2_bits_uop_exceptionVec_19;
  logic eb_in_2_bits_uop_exceptionVec_23;
  logic [6:0] eb_in_2_bits_uop_uopIdx;
  logic eb_in_2_bits_uop_robIdx_flag;
  logic [7:0] eb_in_2_bits_uop_robIdx_value;
  logic [63:0] eb_in_2_bits_fullva;
  logic eb_in_2_bits_vaNeedExt;
  logic [63:0] eb_in_2_bits_gpaddr;
  logic eb_in_2_bits_isHyper;
  logic eb_in_2_bits_isForVSnonLeafPTE;
  logic eb_in_3_valid;
  logic eb_in_3_bits_uop_exceptionVec_3;
  logic eb_in_3_bits_uop_exceptionVec_6;
  logic eb_in_3_bits_uop_exceptionVec_7;
  logic eb_in_3_bits_uop_exceptionVec_15;
  logic eb_in_3_bits_uop_exceptionVec_19;
  logic eb_in_3_bits_uop_exceptionVec_23;
  logic [6:0] eb_in_3_bits_uop_uopIdx;
  logic eb_in_3_bits_uop_robIdx_flag;
  logic [7:0] eb_in_3_bits_uop_robIdx_value;
  logic [63:0] eb_in_3_bits_fullva;
  logic eb_in_3_bits_vaNeedExt;
  logic [63:0] eb_in_3_bits_gpaddr;
  logic eb_in_3_bits_isHyper;
  logic eb_in_3_bits_isForVSnonLeafPTE;
  logic eb_in_4_valid;
  logic eb_in_4_bits_uop_exceptionVec_3;
  logic eb_in_4_bits_uop_exceptionVec_6;
  logic eb_in_4_bits_uop_exceptionVec_7;
  logic eb_in_4_bits_uop_exceptionVec_15;
  logic eb_in_4_bits_uop_exceptionVec_19;
  logic eb_in_4_bits_uop_exceptionVec_23;
  logic [6:0] eb_in_4_bits_uop_uopIdx;
  logic eb_in_4_bits_uop_robIdx_flag;
  logic [7:0] eb_in_4_bits_uop_robIdx_value;
  logic [63:0] eb_in_4_bits_fullva;
  logic eb_in_4_bits_vaNeedExt;
  logic [63:0] eb_in_4_bits_gpaddr;
  logic eb_in_4_bits_isForVSnonLeafPTE;
  logic eb_in_5_valid;
  logic eb_in_5_bits_uop_exceptionVec_3;
  logic eb_in_5_bits_uop_exceptionVec_6;
  logic eb_in_5_bits_uop_exceptionVec_7;
  logic eb_in_5_bits_uop_exceptionVec_15;
  logic eb_in_5_bits_uop_exceptionVec_19;
  logic eb_in_5_bits_uop_exceptionVec_23;
  logic [6:0] eb_in_5_bits_uop_uopIdx;
  logic eb_in_5_bits_uop_robIdx_flag;
  logic [7:0] eb_in_5_bits_uop_robIdx_value;
  logic [63:0] eb_in_5_bits_fullva;
  logic eb_in_5_bits_vaNeedExt;
  logic [63:0] eb_in_5_bits_gpaddr;
  logic eb_in_5_bits_isForVSnonLeafPTE;
  logic eb_in_6_valid;
  logic eb_in_6_bits_uop_exceptionVec_19;
  logic [6:0] eb_in_6_bits_uop_uopIdx;
  logic eb_in_6_bits_uop_robIdx_flag;
  logic [7:0] eb_in_6_bits_uop_robIdx_value;
  logic [63:0] eb_in_6_bits_fullva;
