// 自动生成：scripts/gen_tlbuffer22.py —— 勿手改
module TLBuffer_22(
  input clock,
  input reset,
  output auto_in_a_ready,
  input auto_in_a_valid,
  input [3:0] auto_in_a_bits_opcode,
  input [2:0] auto_in_a_bits_param,
  input [1:0] auto_in_a_bits_size,
  input [2:0] auto_in_a_bits_source,
  input [47:0] auto_in_a_bits_address,
  input auto_in_a_bits_user_memBackType_MM,
  input auto_in_a_bits_user_memPageType_NC,
  input [7:0] auto_in_a_bits_mask,
  input [63:0] auto_in_a_bits_data,
  input auto_in_a_bits_corrupt,
  input auto_in_d_ready,
  output auto_in_d_valid,
  output [3:0] auto_in_d_bits_opcode,
  output [1:0] auto_in_d_bits_param,
  output [1:0] auto_in_d_bits_size,
  output [2:0] auto_in_d_bits_source,
  output auto_in_d_bits_sink,
  output auto_in_d_bits_denied,
  output [63:0] auto_in_d_bits_data,
  output auto_in_d_bits_corrupt,
  input auto_out_a_ready,
  output auto_out_a_valid,
  output [3:0] auto_out_a_bits_opcode,
  output [2:0] auto_out_a_bits_param,
  output [1:0] auto_out_a_bits_size,
  output [2:0] auto_out_a_bits_source,
  output [47:0] auto_out_a_bits_address,
  output auto_out_a_bits_user_memBackType_MM,
  output auto_out_a_bits_user_memPageType_NC,
  output [7:0] auto_out_a_bits_mask,
  output [63:0] auto_out_a_bits_data,
  output auto_out_a_bits_corrupt,
  output auto_out_d_ready,
  input auto_out_d_valid,
  input [3:0] auto_out_d_bits_opcode,
  input [1:0] auto_out_d_bits_param,
  input [1:0] auto_out_d_bits_size,
  input [2:0] auto_out_d_bits_source,
  input auto_out_d_bits_sink,
  input auto_out_d_bits_denied,
  input [63:0] auto_out_d_bits_data,
  input auto_out_d_bits_corrupt
);
  xs_TLBuffer_22_core u_core (
    .clock(clock),
    .reset(reset),
    .auto_in_a_ready(auto_in_a_ready),
    .auto_in_a_valid(auto_in_a_valid),
    .auto_in_a_bits_opcode(auto_in_a_bits_opcode),
    .auto_in_a_bits_param(auto_in_a_bits_param),
    .auto_in_a_bits_size(auto_in_a_bits_size),
    .auto_in_a_bits_source(auto_in_a_bits_source),
    .auto_in_a_bits_address(auto_in_a_bits_address),
    .auto_in_a_bits_user_memBackType_MM(auto_in_a_bits_user_memBackType_MM),
    .auto_in_a_bits_user_memPageType_NC(auto_in_a_bits_user_memPageType_NC),
    .auto_in_a_bits_mask(auto_in_a_bits_mask),
    .auto_in_a_bits_data(auto_in_a_bits_data),
    .auto_in_a_bits_corrupt(auto_in_a_bits_corrupt),
    .auto_in_d_ready(auto_in_d_ready),
    .auto_in_d_valid(auto_in_d_valid),
    .auto_in_d_bits_opcode(auto_in_d_bits_opcode),
    .auto_in_d_bits_param(auto_in_d_bits_param),
    .auto_in_d_bits_size(auto_in_d_bits_size),
    .auto_in_d_bits_source(auto_in_d_bits_source),
    .auto_in_d_bits_sink(auto_in_d_bits_sink),
    .auto_in_d_bits_denied(auto_in_d_bits_denied),
    .auto_in_d_bits_data(auto_in_d_bits_data),
    .auto_in_d_bits_corrupt(auto_in_d_bits_corrupt),
    .auto_out_a_ready(auto_out_a_ready),
    .auto_out_a_valid(auto_out_a_valid),
    .auto_out_a_bits_opcode(auto_out_a_bits_opcode),
    .auto_out_a_bits_param(auto_out_a_bits_param),
    .auto_out_a_bits_size(auto_out_a_bits_size),
    .auto_out_a_bits_source(auto_out_a_bits_source),
    .auto_out_a_bits_address(auto_out_a_bits_address),
    .auto_out_a_bits_user_memBackType_MM(auto_out_a_bits_user_memBackType_MM),
    .auto_out_a_bits_user_memPageType_NC(auto_out_a_bits_user_memPageType_NC),
    .auto_out_a_bits_mask(auto_out_a_bits_mask),
    .auto_out_a_bits_data(auto_out_a_bits_data),
    .auto_out_a_bits_corrupt(auto_out_a_bits_corrupt),
    .auto_out_d_ready(auto_out_d_ready),
    .auto_out_d_valid(auto_out_d_valid),
    .auto_out_d_bits_opcode(auto_out_d_bits_opcode),
    .auto_out_d_bits_param(auto_out_d_bits_param),
    .auto_out_d_bits_size(auto_out_d_bits_size),
    .auto_out_d_bits_source(auto_out_d_bits_source),
    .auto_out_d_bits_sink(auto_out_d_bits_sink),
    .auto_out_d_bits_denied(auto_out_d_bits_denied),
    .auto_out_d_bits_data(auto_out_d_bits_data),
    .auto_out_d_bits_corrupt(auto_out_d_bits_corrupt)
  );
endmodule
