// VfofBuffer —— 扁平端口包装(FM impl 顶层), 例化 xs_VfofBuffer_core。
// 机械生成 by gen_vfofbuffer.py, 勿手改。
module VfofBuffer
  import xs_vfofbuffer_pkg::*;
(
  input           clock,
  input           reset,
  input           io_redirect_valid,
  input           io_redirect_bits_robIdx_flag,
  input [7:0]     io_redirect_bits_robIdx_value,
  input           io_redirect_bits_level,
  input           io_in_0_valid,
  input [8:0]     io_in_0_bits_uop_fuOpType,
  input           io_in_0_bits_uop_vecWen,
  input           io_in_0_bits_uop_v0Wen,
  input           io_in_0_bits_uop_vlWen,
  input           io_in_0_bits_uop_vpu_vma,
  input           io_in_0_bits_uop_vpu_vta,
  input [1:0]     io_in_0_bits_uop_vpu_vsew,
  input [2:0]     io_in_0_bits_uop_vpu_vlmul,
  input           io_in_0_bits_uop_vpu_vm,
  input [7:0]     io_in_0_bits_uop_vpu_vstart,
  input [6:0]     io_in_0_bits_uop_vpu_vuopIdx,
  input           io_in_0_bits_uop_vpu_lastUop,
  input [2:0]     io_in_0_bits_uop_vpu_nf,
  input [1:0]     io_in_0_bits_uop_vpu_veew,
  input           io_in_0_bits_uop_vpu_isVleff,
  input [7:0]     io_in_0_bits_uop_pdest,
  input           io_in_0_bits_uop_robIdx_flag,
  input [7:0]     io_in_0_bits_uop_robIdx_value,
  input [63:0]    io_in_0_bits_uop_debugInfo_enqRsTime,
  input [63:0]    io_in_0_bits_uop_debugInfo_selectTime,
  input [63:0]    io_in_0_bits_uop_debugInfo_issueTime,
  input [127:0]   io_in_0_bits_src_4,
  input           io_in_1_valid,
  input [8:0]     io_in_1_bits_uop_fuOpType,
  input           io_in_1_bits_uop_vecWen,
  input           io_in_1_bits_uop_v0Wen,
  input           io_in_1_bits_uop_vlWen,
  input           io_in_1_bits_uop_vpu_vma,
  input           io_in_1_bits_uop_vpu_vta,
  input [1:0]     io_in_1_bits_uop_vpu_vsew,
  input [2:0]     io_in_1_bits_uop_vpu_vlmul,
  input           io_in_1_bits_uop_vpu_vm,
  input [7:0]     io_in_1_bits_uop_vpu_vstart,
  input [6:0]     io_in_1_bits_uop_vpu_vuopIdx,
  input           io_in_1_bits_uop_vpu_lastUop,
  input [2:0]     io_in_1_bits_uop_vpu_nf,
  input [1:0]     io_in_1_bits_uop_vpu_veew,
  input           io_in_1_bits_uop_vpu_isVleff,
  input [7:0]     io_in_1_bits_uop_pdest,
  input           io_in_1_bits_uop_robIdx_flag,
  input [7:0]     io_in_1_bits_uop_robIdx_value,
  input [63:0]    io_in_1_bits_uop_debugInfo_enqRsTime,
  input [63:0]    io_in_1_bits_uop_debugInfo_selectTime,
  input [63:0]    io_in_1_bits_uop_debugInfo_issueTime,
  input [127:0]   io_in_1_bits_src_4,
  input           io_mergeUopWriteback_0_valid,
  input           io_mergeUopWriteback_0_bits_uop_exceptionVec_3,
  input           io_mergeUopWriteback_0_bits_uop_exceptionVec_4,
  input           io_mergeUopWriteback_0_bits_uop_exceptionVec_5,
  input           io_mergeUopWriteback_0_bits_uop_exceptionVec_13,
  input           io_mergeUopWriteback_0_bits_uop_exceptionVec_19,
  input           io_mergeUopWriteback_0_bits_uop_exceptionVec_21,
  input [7:0]     io_mergeUopWriteback_0_bits_uop_vpu_vl,
  input           io_mergeUopWriteback_0_bits_uop_robIdx_flag,
  input [7:0]     io_mergeUopWriteback_0_bits_uop_robIdx_value,
  input           io_mergeUopWriteback_1_valid,
  input           io_mergeUopWriteback_1_bits_uop_exceptionVec_3,
  input           io_mergeUopWriteback_1_bits_uop_exceptionVec_4,
  input           io_mergeUopWriteback_1_bits_uop_exceptionVec_5,
  input           io_mergeUopWriteback_1_bits_uop_exceptionVec_13,
  input           io_mergeUopWriteback_1_bits_uop_exceptionVec_19,
  input           io_mergeUopWriteback_1_bits_uop_exceptionVec_21,
  input [7:0]     io_mergeUopWriteback_1_bits_uop_vpu_vl,
  input           io_mergeUopWriteback_1_bits_uop_robIdx_flag,
  input [7:0]     io_mergeUopWriteback_1_bits_uop_robIdx_value,
  output           io_uopWriteback_valid,
  output [8:0]     io_uopWriteback_bits_uop_fuOpType,
  output           io_uopWriteback_bits_uop_vecWen,
  output           io_uopWriteback_bits_uop_v0Wen,
  output           io_uopWriteback_bits_uop_vlWen,
  output           io_uopWriteback_bits_uop_vpu_vma,
  output           io_uopWriteback_bits_uop_vpu_vta,
  output [1:0]     io_uopWriteback_bits_uop_vpu_vsew,
  output [2:0]     io_uopWriteback_bits_uop_vpu_vlmul,
  output           io_uopWriteback_bits_uop_vpu_vm,
  output [7:0]     io_uopWriteback_bits_uop_vpu_vstart,
  output [6:0]     io_uopWriteback_bits_uop_vpu_vuopIdx,
  output [7:0]     io_uopWriteback_bits_uop_vpu_vl,
  output [2:0]     io_uopWriteback_bits_uop_vpu_nf,
  output [1:0]     io_uopWriteback_bits_uop_vpu_veew,
  output [7:0]     io_uopWriteback_bits_uop_pdest,
  output           io_uopWriteback_bits_uop_robIdx_flag,
  output [7:0]     io_uopWriteback_bits_uop_robIdx_value,
  output [63:0]    io_uopWriteback_bits_uop_debugInfo_enqRsTime,
  output [63:0]    io_uopWriteback_bits_uop_debugInfo_selectTime,
  output [63:0]    io_uopWriteback_bits_uop_debugInfo_issueTime,
  output [127:0]   io_uopWriteback_bits_data
);

  xs_VfofBuffer_core u_core (
    .clock                                       (clock),
    .reset                                       (reset),
    .io_redirect_valid                           (io_redirect_valid),
    .io_redirect_bits_robIdx_flag                (io_redirect_bits_robIdx_flag),
    .io_redirect_bits_robIdx_value               (io_redirect_bits_robIdx_value),
    .io_redirect_bits_level                      (io_redirect_bits_level),
    .io_in_0_valid                               (io_in_0_valid),
    .io_in_0_bits_uop_fuOpType                   (io_in_0_bits_uop_fuOpType),
    .io_in_0_bits_uop_vecWen                     (io_in_0_bits_uop_vecWen),
    .io_in_0_bits_uop_v0Wen                      (io_in_0_bits_uop_v0Wen),
    .io_in_0_bits_uop_vlWen                      (io_in_0_bits_uop_vlWen),
    .io_in_0_bits_uop_vpu_vma                    (io_in_0_bits_uop_vpu_vma),
    .io_in_0_bits_uop_vpu_vta                    (io_in_0_bits_uop_vpu_vta),
    .io_in_0_bits_uop_vpu_vsew                   (io_in_0_bits_uop_vpu_vsew),
    .io_in_0_bits_uop_vpu_vlmul                  (io_in_0_bits_uop_vpu_vlmul),
    .io_in_0_bits_uop_vpu_vm                     (io_in_0_bits_uop_vpu_vm),
    .io_in_0_bits_uop_vpu_vstart                 (io_in_0_bits_uop_vpu_vstart),
    .io_in_0_bits_uop_vpu_vuopIdx                (io_in_0_bits_uop_vpu_vuopIdx),
    .io_in_0_bits_uop_vpu_lastUop                (io_in_0_bits_uop_vpu_lastUop),
    .io_in_0_bits_uop_vpu_nf                     (io_in_0_bits_uop_vpu_nf),
    .io_in_0_bits_uop_vpu_veew                   (io_in_0_bits_uop_vpu_veew),
    .io_in_0_bits_uop_vpu_isVleff                (io_in_0_bits_uop_vpu_isVleff),
    .io_in_0_bits_uop_pdest                      (io_in_0_bits_uop_pdest),
    .io_in_0_bits_uop_robIdx_flag                (io_in_0_bits_uop_robIdx_flag),
    .io_in_0_bits_uop_robIdx_value               (io_in_0_bits_uop_robIdx_value),
    .io_in_0_bits_uop_debugInfo_enqRsTime        (io_in_0_bits_uop_debugInfo_enqRsTime),
    .io_in_0_bits_uop_debugInfo_selectTime       (io_in_0_bits_uop_debugInfo_selectTime),
    .io_in_0_bits_uop_debugInfo_issueTime        (io_in_0_bits_uop_debugInfo_issueTime),
    .io_in_0_bits_src_4                          (io_in_0_bits_src_4),
    .io_in_1_valid                               (io_in_1_valid),
    .io_in_1_bits_uop_fuOpType                   (io_in_1_bits_uop_fuOpType),
    .io_in_1_bits_uop_vecWen                     (io_in_1_bits_uop_vecWen),
    .io_in_1_bits_uop_v0Wen                      (io_in_1_bits_uop_v0Wen),
    .io_in_1_bits_uop_vlWen                      (io_in_1_bits_uop_vlWen),
    .io_in_1_bits_uop_vpu_vma                    (io_in_1_bits_uop_vpu_vma),
    .io_in_1_bits_uop_vpu_vta                    (io_in_1_bits_uop_vpu_vta),
    .io_in_1_bits_uop_vpu_vsew                   (io_in_1_bits_uop_vpu_vsew),
    .io_in_1_bits_uop_vpu_vlmul                  (io_in_1_bits_uop_vpu_vlmul),
    .io_in_1_bits_uop_vpu_vm                     (io_in_1_bits_uop_vpu_vm),
    .io_in_1_bits_uop_vpu_vstart                 (io_in_1_bits_uop_vpu_vstart),
    .io_in_1_bits_uop_vpu_vuopIdx                (io_in_1_bits_uop_vpu_vuopIdx),
    .io_in_1_bits_uop_vpu_lastUop                (io_in_1_bits_uop_vpu_lastUop),
    .io_in_1_bits_uop_vpu_nf                     (io_in_1_bits_uop_vpu_nf),
    .io_in_1_bits_uop_vpu_veew                   (io_in_1_bits_uop_vpu_veew),
    .io_in_1_bits_uop_vpu_isVleff                (io_in_1_bits_uop_vpu_isVleff),
    .io_in_1_bits_uop_pdest                      (io_in_1_bits_uop_pdest),
    .io_in_1_bits_uop_robIdx_flag                (io_in_1_bits_uop_robIdx_flag),
    .io_in_1_bits_uop_robIdx_value               (io_in_1_bits_uop_robIdx_value),
    .io_in_1_bits_uop_debugInfo_enqRsTime        (io_in_1_bits_uop_debugInfo_enqRsTime),
    .io_in_1_bits_uop_debugInfo_selectTime       (io_in_1_bits_uop_debugInfo_selectTime),
    .io_in_1_bits_uop_debugInfo_issueTime        (io_in_1_bits_uop_debugInfo_issueTime),
    .io_in_1_bits_src_4                          (io_in_1_bits_src_4),
    .io_mergeUopWriteback_0_valid                (io_mergeUopWriteback_0_valid),
    .io_mergeUopWriteback_0_bits_uop_exceptionVec_3(io_mergeUopWriteback_0_bits_uop_exceptionVec_3),
    .io_mergeUopWriteback_0_bits_uop_exceptionVec_4(io_mergeUopWriteback_0_bits_uop_exceptionVec_4),
    .io_mergeUopWriteback_0_bits_uop_exceptionVec_5(io_mergeUopWriteback_0_bits_uop_exceptionVec_5),
    .io_mergeUopWriteback_0_bits_uop_exceptionVec_13(io_mergeUopWriteback_0_bits_uop_exceptionVec_13),
    .io_mergeUopWriteback_0_bits_uop_exceptionVec_19(io_mergeUopWriteback_0_bits_uop_exceptionVec_19),
    .io_mergeUopWriteback_0_bits_uop_exceptionVec_21(io_mergeUopWriteback_0_bits_uop_exceptionVec_21),
    .io_mergeUopWriteback_0_bits_uop_vpu_vl      (io_mergeUopWriteback_0_bits_uop_vpu_vl),
    .io_mergeUopWriteback_0_bits_uop_robIdx_flag (io_mergeUopWriteback_0_bits_uop_robIdx_flag),
    .io_mergeUopWriteback_0_bits_uop_robIdx_value(io_mergeUopWriteback_0_bits_uop_robIdx_value),
    .io_mergeUopWriteback_1_valid                (io_mergeUopWriteback_1_valid),
    .io_mergeUopWriteback_1_bits_uop_exceptionVec_3(io_mergeUopWriteback_1_bits_uop_exceptionVec_3),
    .io_mergeUopWriteback_1_bits_uop_exceptionVec_4(io_mergeUopWriteback_1_bits_uop_exceptionVec_4),
    .io_mergeUopWriteback_1_bits_uop_exceptionVec_5(io_mergeUopWriteback_1_bits_uop_exceptionVec_5),
    .io_mergeUopWriteback_1_bits_uop_exceptionVec_13(io_mergeUopWriteback_1_bits_uop_exceptionVec_13),
    .io_mergeUopWriteback_1_bits_uop_exceptionVec_19(io_mergeUopWriteback_1_bits_uop_exceptionVec_19),
    .io_mergeUopWriteback_1_bits_uop_exceptionVec_21(io_mergeUopWriteback_1_bits_uop_exceptionVec_21),
    .io_mergeUopWriteback_1_bits_uop_vpu_vl      (io_mergeUopWriteback_1_bits_uop_vpu_vl),
    .io_mergeUopWriteback_1_bits_uop_robIdx_flag (io_mergeUopWriteback_1_bits_uop_robIdx_flag),
    .io_mergeUopWriteback_1_bits_uop_robIdx_value(io_mergeUopWriteback_1_bits_uop_robIdx_value),
    .io_uopWriteback_valid                       (io_uopWriteback_valid),
    .io_uopWriteback_bits_uop_fuOpType           (io_uopWriteback_bits_uop_fuOpType),
    .io_uopWriteback_bits_uop_vecWen             (io_uopWriteback_bits_uop_vecWen),
    .io_uopWriteback_bits_uop_v0Wen              (io_uopWriteback_bits_uop_v0Wen),
    .io_uopWriteback_bits_uop_vlWen              (io_uopWriteback_bits_uop_vlWen),
    .io_uopWriteback_bits_uop_vpu_vma            (io_uopWriteback_bits_uop_vpu_vma),
    .io_uopWriteback_bits_uop_vpu_vta            (io_uopWriteback_bits_uop_vpu_vta),
    .io_uopWriteback_bits_uop_vpu_vsew           (io_uopWriteback_bits_uop_vpu_vsew),
    .io_uopWriteback_bits_uop_vpu_vlmul          (io_uopWriteback_bits_uop_vpu_vlmul),
    .io_uopWriteback_bits_uop_vpu_vm             (io_uopWriteback_bits_uop_vpu_vm),
    .io_uopWriteback_bits_uop_vpu_vstart         (io_uopWriteback_bits_uop_vpu_vstart),
    .io_uopWriteback_bits_uop_vpu_vuopIdx        (io_uopWriteback_bits_uop_vpu_vuopIdx),
    .io_uopWriteback_bits_uop_vpu_vl             (io_uopWriteback_bits_uop_vpu_vl),
    .io_uopWriteback_bits_uop_vpu_nf             (io_uopWriteback_bits_uop_vpu_nf),
    .io_uopWriteback_bits_uop_vpu_veew           (io_uopWriteback_bits_uop_vpu_veew),
    .io_uopWriteback_bits_uop_pdest              (io_uopWriteback_bits_uop_pdest),
    .io_uopWriteback_bits_uop_robIdx_flag        (io_uopWriteback_bits_uop_robIdx_flag),
    .io_uopWriteback_bits_uop_robIdx_value       (io_uopWriteback_bits_uop_robIdx_value),
    .io_uopWriteback_bits_uop_debugInfo_enqRsTime(io_uopWriteback_bits_uop_debugInfo_enqRsTime),
    .io_uopWriteback_bits_uop_debugInfo_selectTime(io_uopWriteback_bits_uop_debugInfo_selectTime),
    .io_uopWriteback_bits_uop_debugInfo_issueTime(io_uopWriteback_bits_uop_debugInfo_issueTime),
    .io_uopWriteback_bits_data                   (io_uopWriteback_bits_data)
  );

endmodule
