// VSMergeBufferImp —— 扁平端口包装(FM impl 顶层), 例化 xs_VSMergeBufferImp_core
// + FreeList_1 + NewPipelineConnectPipe_27(两侧同 elaborate 的 golden 子模块)。
// 机械生成 by gen_vsmerge.py, 勿手改。
module VSMergeBufferImp
  import xs_vsmergebuffer_pkg::*;
(
  input           clock,
  input           reset,
  input           io_redirect_valid,
  input           io_redirect_bits_robIdx_flag,
  input [7:0]     io_redirect_bits_robIdx_value,
  input           io_redirect_bits_level,
  input           io_fromPipeline_0_valid,
  input [3:0]     io_fromPipeline_0_bits_mBIndex,
  input           io_fromPipeline_0_bits_hit,
  input [3:0]     io_fromPipeline_0_bits_trigger,
  input           io_fromPipeline_0_bits_exceptionVec_3,
  input           io_fromPipeline_0_bits_exceptionVec_6,
  input           io_fromPipeline_0_bits_exceptionVec_7,
  input           io_fromPipeline_0_bits_exceptionVec_15,
  input           io_fromPipeline_0_bits_exceptionVec_19,
  input           io_fromPipeline_0_bits_exceptionVec_23,
  input           io_fromPipeline_0_bits_hasException,
  input [63:0]    io_fromPipeline_0_bits_vaddr,
  input           io_fromPipeline_0_bits_vaNeedExt,
  input [63:0]    io_fromPipeline_0_bits_gpaddr,
  input           io_fromPipeline_0_bits_isForVSnonLeafPTE,
  input [7:0]     io_fromPipeline_0_bits_vstart,
  input [7:0]     io_fromPipeline_0_bits_elemIdx,
  input [15:0]    io_fromPipeline_0_bits_mask,
  output           io_fromSplit_0_req_ready,
  input           io_fromSplit_0_req_valid,
  input [15:0]    io_fromSplit_0_req_bits_mask,
  input [49:0]    io_fromSplit_0_req_bits_vaddr,
  input [4:0]     io_fromSplit_0_req_bits_flowNum,
  input [8:0]     io_fromSplit_0_req_bits_uop_fuOpType,
  input           io_fromSplit_0_req_bits_uop_vecWen,
  input           io_fromSplit_0_req_bits_uop_v0Wen,
  input           io_fromSplit_0_req_bits_uop_vlWen,
  input           io_fromSplit_0_req_bits_uop_vpu_vma,
  input           io_fromSplit_0_req_bits_uop_vpu_vta,
  input [1:0]     io_fromSplit_0_req_bits_uop_vpu_vsew,
  input [2:0]     io_fromSplit_0_req_bits_uop_vpu_vlmul,
  input           io_fromSplit_0_req_bits_uop_vpu_vm,
  input [6:0]     io_fromSplit_0_req_bits_uop_vpu_vuopIdx,
  input [127:0]   io_fromSplit_0_req_bits_uop_vpu_vmask,
  input [7:0]     io_fromSplit_0_req_bits_uop_vpu_vl,
  input [2:0]     io_fromSplit_0_req_bits_uop_vpu_nf,
  input [1:0]     io_fromSplit_0_req_bits_uop_vpu_veew,
  input [6:0]     io_fromSplit_0_req_bits_uop_uopIdx,
  input [7:0]     io_fromSplit_0_req_bits_uop_pdest,
  input           io_fromSplit_0_req_bits_uop_robIdx_flag,
  input [7:0]     io_fromSplit_0_req_bits_uop_robIdx_value,
  input [63:0]    io_fromSplit_0_req_bits_uop_debugInfo_enqRsTime,
  input [63:0]    io_fromSplit_0_req_bits_uop_debugInfo_selectTime,
  input [63:0]    io_fromSplit_0_req_bits_uop_debugInfo_issueTime,
  input           io_fromSplit_0_req_bits_uop_lqIdx_flag,
  input [6:0]     io_fromSplit_0_req_bits_uop_lqIdx_value,
  input           io_fromSplit_0_req_bits_uop_sqIdx_flag,
  input [5:0]     io_fromSplit_0_req_bits_uop_sqIdx_value,
  input [7:0]     io_fromSplit_0_req_bits_vlmax,
  output           io_fromSplit_0_resp_valid,
  output [3:0]     io_fromSplit_0_resp_bits_mBIndex,
  input           io_uopWriteback_0_ready,
  output           io_uopWriteback_0_valid,
  output           io_uopWriteback_0_bits_uop_exceptionVec_3,
  output           io_uopWriteback_0_bits_uop_exceptionVec_6,
  output           io_uopWriteback_0_bits_uop_exceptionVec_7,
  output           io_uopWriteback_0_bits_uop_exceptionVec_15,
  output           io_uopWriteback_0_bits_uop_exceptionVec_19,
  output           io_uopWriteback_0_bits_uop_exceptionVec_23,
  output [3:0]     io_uopWriteback_0_bits_uop_trigger,
  output [8:0]     io_uopWriteback_0_bits_uop_fuOpType,
  output           io_uopWriteback_0_bits_uop_vecWen,
  output           io_uopWriteback_0_bits_uop_v0Wen,
  output           io_uopWriteback_0_bits_uop_vlWen,
  output           io_uopWriteback_0_bits_uop_flushPipe,
  output           io_uopWriteback_0_bits_uop_vpu_vma,
  output           io_uopWriteback_0_bits_uop_vpu_vta,
  output [1:0]     io_uopWriteback_0_bits_uop_vpu_vsew,
  output [2:0]     io_uopWriteback_0_bits_uop_vpu_vlmul,
  output           io_uopWriteback_0_bits_uop_vpu_vm,
  output [7:0]     io_uopWriteback_0_bits_uop_vpu_vstart,
  output [6:0]     io_uopWriteback_0_bits_uop_vpu_vuopIdx,
  output [127:0]   io_uopWriteback_0_bits_uop_vpu_vmask,
  output [7:0]     io_uopWriteback_0_bits_uop_vpu_vl,
  output [2:0]     io_uopWriteback_0_bits_uop_vpu_nf,
  output [1:0]     io_uopWriteback_0_bits_uop_vpu_veew,
  output [7:0]     io_uopWriteback_0_bits_uop_pdest,
  output           io_uopWriteback_0_bits_uop_robIdx_flag,
  output [7:0]     io_uopWriteback_0_bits_uop_robIdx_value,
  output [63:0]    io_uopWriteback_0_bits_uop_debugInfo_enqRsTime,
  output [63:0]    io_uopWriteback_0_bits_uop_debugInfo_selectTime,
  output [63:0]    io_uopWriteback_0_bits_uop_debugInfo_issueTime,
  output           io_uopWriteback_0_bits_uop_replayInst,
  output [127:0]   io_uopWriteback_0_bits_data,
  output [2:0]     io_uopWriteback_0_bits_vdIdx,
  output [2:0]     io_uopWriteback_0_bits_vdIdxInField,
  output           io_toLsq_0_valid,
  output           io_toLsq_0_bits_robidx_flag,
  output [7:0]     io_toLsq_0_bits_robidx_value,
  output [6:0]     io_toLsq_0_bits_uopidx,
  output [63:0]    io_toLsq_0_bits_vaddr,
  output           io_toLsq_0_bits_vaNeedExt,
  output [49:0]    io_toLsq_0_bits_gpaddr,
  output           io_toLsq_0_bits_isForVSnonLeafPTE,
  output           io_toLsq_0_bits_feedback_0,
  output           io_toLsq_0_bits_feedback_1,
  output           io_toLsq_0_bits_exceptionVec_3,
  output           io_toLsq_0_bits_exceptionVec_6,
  output           io_toLsq_0_bits_exceptionVec_7,
  output           io_toLsq_0_bits_exceptionVec_15,
  output           io_toLsq_0_bits_exceptionVec_19,
  output           io_toLsq_0_bits_exceptionVec_23,
  output           io_feedback_0_valid,
  output           io_feedback_0_bits_hit,
  output           io_feedback_0_bits_sqIdx_flag,
  output [5:0]     io_feedback_0_bits_sqIdx_value,
  output           io_feedback_0_bits_lqIdx_flag,
  output [6:0]     io_feedback_0_bits_lqIdx_value,
  input [3:0]     io_fromMisalignBuffer_mbIndex,
  input           io_fromMisalignBuffer_flush
);

  // 子模块 glue 网
  wire [3:0]   allocateSlot;
  wire         doAllocate;
  wire [15:0]  freeMaskVec;
  wire [4:0]   validCount;
  wire         pc_in_valid;
  wire         pc_in_ready;
  wire         pc_isFlush;
  wire pc_in_uop_exceptionVec_3;
  wire pc_in_uop_exceptionVec_6;
  wire pc_in_uop_exceptionVec_7;
  wire pc_in_uop_exceptionVec_15;
  wire pc_in_uop_exceptionVec_19;
  wire pc_in_uop_exceptionVec_23;
  wire [3:0] pc_in_uop_trigger;
  wire [8:0] pc_in_uop_fuOpType;
  wire pc_in_uop_vecWen;
  wire pc_in_uop_v0Wen;
  wire pc_in_uop_vlWen;
  wire pc_in_uop_flushPipe;
  wire pc_in_uop_vpu_vma;
  wire pc_in_uop_vpu_vta;
  wire [1:0] pc_in_uop_vpu_vsew;
  wire [2:0] pc_in_uop_vpu_vlmul;
  wire pc_in_uop_vpu_vm;
  wire [7:0] pc_in_uop_vpu_vstart;
  wire [6:0] pc_in_uop_vpu_vuopIdx;
  wire [127:0] pc_in_uop_vpu_vmask;
  wire [7:0] pc_in_uop_vpu_vl;
  wire [2:0] pc_in_uop_vpu_nf;
  wire [1:0] pc_in_uop_vpu_veew;
  wire [7:0] pc_in_uop_pdest;
  wire pc_in_uop_robIdx_flag;
  wire [7:0] pc_in_uop_robIdx_value;
  wire [63:0] pc_in_uop_debugInfo_enqRsTime;
  wire [63:0] pc_in_uop_debugInfo_selectTime;
  wire [63:0] pc_in_uop_debugInfo_issueTime;
  wire pc_in_uop_replayInst;

  xs_VSMergeBufferImp_core u_core (
    .clock(clock), .reset(reset),
    .io_redirect_valid(io_redirect_valid),
    .io_redirect_bits_robIdx_flag(io_redirect_bits_robIdx_flag),
    .io_redirect_bits_robIdx_value(io_redirect_bits_robIdx_value),
    .io_redirect_bits_level(io_redirect_bits_level),
    .io_fromPipeline_0_valid(io_fromPipeline_0_valid),
    .io_fromPipeline_0_bits_mBIndex(io_fromPipeline_0_bits_mBIndex),
    .io_fromPipeline_0_bits_hit(io_fromPipeline_0_bits_hit),
    .io_fromPipeline_0_bits_trigger(io_fromPipeline_0_bits_trigger),
    .io_fromPipeline_0_bits_exceptionVec_3(io_fromPipeline_0_bits_exceptionVec_3),
    .io_fromPipeline_0_bits_exceptionVec_6(io_fromPipeline_0_bits_exceptionVec_6),
    .io_fromPipeline_0_bits_exceptionVec_7(io_fromPipeline_0_bits_exceptionVec_7),
    .io_fromPipeline_0_bits_exceptionVec_15(io_fromPipeline_0_bits_exceptionVec_15),
    .io_fromPipeline_0_bits_exceptionVec_19(io_fromPipeline_0_bits_exceptionVec_19),
    .io_fromPipeline_0_bits_exceptionVec_23(io_fromPipeline_0_bits_exceptionVec_23),
    .io_fromPipeline_0_bits_hasException(io_fromPipeline_0_bits_hasException),
    .io_fromPipeline_0_bits_vaddr(io_fromPipeline_0_bits_vaddr),
    .io_fromPipeline_0_bits_vaNeedExt(io_fromPipeline_0_bits_vaNeedExt),
    .io_fromPipeline_0_bits_gpaddr(io_fromPipeline_0_bits_gpaddr),
    .io_fromPipeline_0_bits_isForVSnonLeafPTE(io_fromPipeline_0_bits_isForVSnonLeafPTE),
    .io_fromPipeline_0_bits_vstart(io_fromPipeline_0_bits_vstart),
    .io_fromPipeline_0_bits_elemIdx(io_fromPipeline_0_bits_elemIdx),
    .io_fromPipeline_0_bits_mask(io_fromPipeline_0_bits_mask),
    .io_fromSplit_0_req_ready(io_fromSplit_0_req_ready),
    .io_fromSplit_0_req_valid(io_fromSplit_0_req_valid),
    .io_fromSplit_0_req_bits_mask(io_fromSplit_0_req_bits_mask),
    .io_fromSplit_0_req_bits_vaddr(io_fromSplit_0_req_bits_vaddr),
    .io_fromSplit_0_req_bits_flowNum(io_fromSplit_0_req_bits_flowNum),
    .io_fromSplit_0_req_bits_uop_fuOpType(io_fromSplit_0_req_bits_uop_fuOpType),
    .io_fromSplit_0_req_bits_uop_vecWen(io_fromSplit_0_req_bits_uop_vecWen),
    .io_fromSplit_0_req_bits_uop_v0Wen(io_fromSplit_0_req_bits_uop_v0Wen),
    .io_fromSplit_0_req_bits_uop_vlWen(io_fromSplit_0_req_bits_uop_vlWen),
    .io_fromSplit_0_req_bits_uop_vpu_vma(io_fromSplit_0_req_bits_uop_vpu_vma),
    .io_fromSplit_0_req_bits_uop_vpu_vta(io_fromSplit_0_req_bits_uop_vpu_vta),
    .io_fromSplit_0_req_bits_uop_vpu_vsew(io_fromSplit_0_req_bits_uop_vpu_vsew),
    .io_fromSplit_0_req_bits_uop_vpu_vlmul(io_fromSplit_0_req_bits_uop_vpu_vlmul),
    .io_fromSplit_0_req_bits_uop_vpu_vm(io_fromSplit_0_req_bits_uop_vpu_vm),
    .io_fromSplit_0_req_bits_uop_vpu_vuopIdx(io_fromSplit_0_req_bits_uop_vpu_vuopIdx),
    .io_fromSplit_0_req_bits_uop_vpu_vmask(io_fromSplit_0_req_bits_uop_vpu_vmask),
    .io_fromSplit_0_req_bits_uop_vpu_vl(io_fromSplit_0_req_bits_uop_vpu_vl),
    .io_fromSplit_0_req_bits_uop_vpu_nf(io_fromSplit_0_req_bits_uop_vpu_nf),
    .io_fromSplit_0_req_bits_uop_vpu_veew(io_fromSplit_0_req_bits_uop_vpu_veew),
    .io_fromSplit_0_req_bits_uop_uopIdx(io_fromSplit_0_req_bits_uop_uopIdx),
    .io_fromSplit_0_req_bits_uop_pdest(io_fromSplit_0_req_bits_uop_pdest),
    .io_fromSplit_0_req_bits_uop_robIdx_flag(io_fromSplit_0_req_bits_uop_robIdx_flag),
    .io_fromSplit_0_req_bits_uop_robIdx_value(io_fromSplit_0_req_bits_uop_robIdx_value),
    .io_fromSplit_0_req_bits_uop_debugInfo_enqRsTime(io_fromSplit_0_req_bits_uop_debugInfo_enqRsTime),
    .io_fromSplit_0_req_bits_uop_debugInfo_selectTime(io_fromSplit_0_req_bits_uop_debugInfo_selectTime),
    .io_fromSplit_0_req_bits_uop_debugInfo_issueTime(io_fromSplit_0_req_bits_uop_debugInfo_issueTime),
    .io_fromSplit_0_req_bits_uop_lqIdx_flag(io_fromSplit_0_req_bits_uop_lqIdx_flag),
    .io_fromSplit_0_req_bits_uop_lqIdx_value(io_fromSplit_0_req_bits_uop_lqIdx_value),
    .io_fromSplit_0_req_bits_uop_sqIdx_flag(io_fromSplit_0_req_bits_uop_sqIdx_flag),
    .io_fromSplit_0_req_bits_uop_sqIdx_value(io_fromSplit_0_req_bits_uop_sqIdx_value),
    .io_fromSplit_0_req_bits_vlmax(io_fromSplit_0_req_bits_vlmax),
    .io_fromSplit_0_resp_valid(io_fromSplit_0_resp_valid),
    .io_fromSplit_0_resp_bits_mBIndex(io_fromSplit_0_resp_bits_mBIndex),
    .io_toLsq_0_valid(io_toLsq_0_valid),
    .io_toLsq_0_bits_robidx_flag(io_toLsq_0_bits_robidx_flag),
    .io_toLsq_0_bits_robidx_value(io_toLsq_0_bits_robidx_value),
    .io_toLsq_0_bits_uopidx(io_toLsq_0_bits_uopidx),
    .io_toLsq_0_bits_vaddr(io_toLsq_0_bits_vaddr),
    .io_toLsq_0_bits_vaNeedExt(io_toLsq_0_bits_vaNeedExt),
    .io_toLsq_0_bits_gpaddr(io_toLsq_0_bits_gpaddr),
    .io_toLsq_0_bits_isForVSnonLeafPTE(io_toLsq_0_bits_isForVSnonLeafPTE),
    .io_toLsq_0_bits_feedback_0(io_toLsq_0_bits_feedback_0),
    .io_toLsq_0_bits_feedback_1(io_toLsq_0_bits_feedback_1),
    .io_toLsq_0_bits_exceptionVec_3(io_toLsq_0_bits_exceptionVec_3),
    .io_toLsq_0_bits_exceptionVec_6(io_toLsq_0_bits_exceptionVec_6),
    .io_toLsq_0_bits_exceptionVec_7(io_toLsq_0_bits_exceptionVec_7),
    .io_toLsq_0_bits_exceptionVec_15(io_toLsq_0_bits_exceptionVec_15),
    .io_toLsq_0_bits_exceptionVec_19(io_toLsq_0_bits_exceptionVec_19),
    .io_toLsq_0_bits_exceptionVec_23(io_toLsq_0_bits_exceptionVec_23),
    .io_feedback_0_valid(io_feedback_0_valid),
    .io_feedback_0_bits_hit(io_feedback_0_bits_hit),
    .io_feedback_0_bits_sqIdx_flag(io_feedback_0_bits_sqIdx_flag),
    .io_feedback_0_bits_sqIdx_value(io_feedback_0_bits_sqIdx_value),
    .io_feedback_0_bits_lqIdx_flag(io_feedback_0_bits_lqIdx_flag),
    .io_feedback_0_bits_lqIdx_value(io_feedback_0_bits_lqIdx_value),
    .io_fromMisalignBuffer_mbIndex(io_fromMisalignBuffer_mbIndex),
    .io_fromMisalignBuffer_flush(io_fromMisalignBuffer_flush),
    .allocateSlot(allocateSlot),
    .doAllocate(doAllocate),
    .freeMaskVec(freeMaskVec),
    .validCount(validCount),
    .pc_in_valid(pc_in_valid),
    .pc_in_ready(pc_in_ready),
    .pc_isFlush(pc_isFlush),
    .pc_out_robIdx_flag(io_uopWriteback_0_bits_uop_robIdx_flag),
    .pc_out_robIdx_value(io_uopWriteback_0_bits_uop_robIdx_value),
    .pc_in_uop_exceptionVec_3(pc_in_uop_exceptionVec_3),
    .pc_in_uop_exceptionVec_6(pc_in_uop_exceptionVec_6),
    .pc_in_uop_exceptionVec_7(pc_in_uop_exceptionVec_7),
    .pc_in_uop_exceptionVec_15(pc_in_uop_exceptionVec_15),
    .pc_in_uop_exceptionVec_19(pc_in_uop_exceptionVec_19),
    .pc_in_uop_exceptionVec_23(pc_in_uop_exceptionVec_23),
    .pc_in_uop_trigger(pc_in_uop_trigger),
    .pc_in_uop_fuOpType(pc_in_uop_fuOpType),
    .pc_in_uop_vecWen(pc_in_uop_vecWen),
    .pc_in_uop_v0Wen(pc_in_uop_v0Wen),
    .pc_in_uop_vlWen(pc_in_uop_vlWen),
    .pc_in_uop_flushPipe(pc_in_uop_flushPipe),
    .pc_in_uop_vpu_vma(pc_in_uop_vpu_vma),
    .pc_in_uop_vpu_vta(pc_in_uop_vpu_vta),
    .pc_in_uop_vpu_vsew(pc_in_uop_vpu_vsew),
    .pc_in_uop_vpu_vlmul(pc_in_uop_vpu_vlmul),
    .pc_in_uop_vpu_vm(pc_in_uop_vpu_vm),
    .pc_in_uop_vpu_vstart(pc_in_uop_vpu_vstart),
    .pc_in_uop_vpu_vuopIdx(pc_in_uop_vpu_vuopIdx),
    .pc_in_uop_vpu_vmask(pc_in_uop_vpu_vmask),
    .pc_in_uop_vpu_vl(pc_in_uop_vpu_vl),
    .pc_in_uop_vpu_nf(pc_in_uop_vpu_nf),
    .pc_in_uop_vpu_veew(pc_in_uop_vpu_veew),
    .pc_in_uop_pdest(pc_in_uop_pdest),
    .pc_in_uop_robIdx_flag(pc_in_uop_robIdx_flag),
    .pc_in_uop_robIdx_value(pc_in_uop_robIdx_value),
    .pc_in_uop_debugInfo_enqRsTime(pc_in_uop_debugInfo_enqRsTime),
    .pc_in_uop_debugInfo_selectTime(pc_in_uop_debugInfo_selectTime),
    .pc_in_uop_debugInfo_issueTime(pc_in_uop_debugInfo_issueTime),
    .pc_in_uop_replayInst(pc_in_uop_replayInst)
  );

  FreeList_1 freeCount_freeList (
    .clock             (clock),
    .reset             (reset),
    .io_allocateSlot_0 (allocateSlot),
    .io_doAllocate_0   (doAllocate),
    .io_free           (freeMaskVec),
    .io_validCount     (validCount),
    .io_empty          (/* unused */)
  );

  NewPipelineConnectPipe_27 VMergebufferPipelineConnect0 (
    .clock                                (clock),
    .reset                                (reset),
    .io_in_ready                          (pc_in_ready),
    .io_in_valid                          (pc_in_valid),
    .io_in_bits_uop_exceptionVec_3        (pc_in_uop_exceptionVec_3),
    .io_in_bits_uop_exceptionVec_4        (1'h0),
    .io_in_bits_uop_exceptionVec_5        (1'h0),
    .io_in_bits_uop_exceptionVec_6        (pc_in_uop_exceptionVec_6),
    .io_in_bits_uop_exceptionVec_7        (pc_in_uop_exceptionVec_7),
    .io_in_bits_uop_exceptionVec_13       (1'h0),
    .io_in_bits_uop_exceptionVec_15       (pc_in_uop_exceptionVec_15),
    .io_in_bits_uop_exceptionVec_19       (pc_in_uop_exceptionVec_19),
    .io_in_bits_uop_exceptionVec_21       (1'h0),
    .io_in_bits_uop_exceptionVec_23       (pc_in_uop_exceptionVec_23),
    .io_in_bits_uop_trigger               (pc_in_uop_trigger),
    .io_in_bits_uop_fuOpType              (pc_in_uop_fuOpType),
    .io_in_bits_uop_vecWen                (pc_in_uop_vecWen),
    .io_in_bits_uop_v0Wen                 (pc_in_uop_v0Wen),
    .io_in_bits_uop_vlWen                 (pc_in_uop_vlWen),
    .io_in_bits_uop_flushPipe             (pc_in_uop_flushPipe),
    .io_in_bits_uop_vpu_vma               (pc_in_uop_vpu_vma),
    .io_in_bits_uop_vpu_vta               (pc_in_uop_vpu_vta),
    .io_in_bits_uop_vpu_vsew              (pc_in_uop_vpu_vsew),
    .io_in_bits_uop_vpu_vlmul             (pc_in_uop_vpu_vlmul),
    .io_in_bits_uop_vpu_vm                (pc_in_uop_vpu_vm),
    .io_in_bits_uop_vpu_vstart            (pc_in_uop_vpu_vstart),
    .io_in_bits_uop_vpu_vuopIdx           (pc_in_uop_vpu_vuopIdx),
    .io_in_bits_uop_vpu_vmask             (pc_in_uop_vpu_vmask),
    .io_in_bits_uop_vpu_vl                (pc_in_uop_vpu_vl),
    .io_in_bits_uop_vpu_nf                (pc_in_uop_vpu_nf),
    .io_in_bits_uop_vpu_veew              (pc_in_uop_vpu_veew),
    .io_in_bits_uop_pdest                 (pc_in_uop_pdest),
    .io_in_bits_uop_robIdx_flag           (pc_in_uop_robIdx_flag),
    .io_in_bits_uop_robIdx_value          (pc_in_uop_robIdx_value),
    .io_in_bits_uop_debugInfo_enqRsTime   (pc_in_uop_debugInfo_enqRsTime),
    .io_in_bits_uop_debugInfo_selectTime  (pc_in_uop_debugInfo_selectTime),
    .io_in_bits_uop_debugInfo_issueTime   (pc_in_uop_debugInfo_issueTime),
    .io_in_bits_uop_replayInst            (pc_in_uop_replayInst),
    .io_in_bits_data                      (128'h0),
    .io_in_bits_vdIdx                     (3'h0),
    .io_in_bits_vdIdxInField              (3'h0),
    .io_out_ready                         (io_uopWriteback_0_ready),
    .io_out_valid                         (io_uopWriteback_0_valid),
    .io_out_bits_uop_exceptionVec_3       (io_uopWriteback_0_bits_uop_exceptionVec_3),
    .io_out_bits_uop_exceptionVec_4       (/* unused */),
    .io_out_bits_uop_exceptionVec_5       (/* unused */),
    .io_out_bits_uop_exceptionVec_6       (io_uopWriteback_0_bits_uop_exceptionVec_6),
    .io_out_bits_uop_exceptionVec_7       (io_uopWriteback_0_bits_uop_exceptionVec_7),
    .io_out_bits_uop_exceptionVec_13      (/* unused */),
    .io_out_bits_uop_exceptionVec_15      (io_uopWriteback_0_bits_uop_exceptionVec_15),
    .io_out_bits_uop_exceptionVec_19      (io_uopWriteback_0_bits_uop_exceptionVec_19),
    .io_out_bits_uop_exceptionVec_21      (/* unused */),
    .io_out_bits_uop_exceptionVec_23      (io_uopWriteback_0_bits_uop_exceptionVec_23),
    .io_out_bits_uop_trigger              (io_uopWriteback_0_bits_uop_trigger),
    .io_out_bits_uop_fuOpType             (io_uopWriteback_0_bits_uop_fuOpType),
    .io_out_bits_uop_vecWen               (io_uopWriteback_0_bits_uop_vecWen),
    .io_out_bits_uop_v0Wen                (io_uopWriteback_0_bits_uop_v0Wen),
    .io_out_bits_uop_vlWen                (io_uopWriteback_0_bits_uop_vlWen),
    .io_out_bits_uop_flushPipe            (io_uopWriteback_0_bits_uop_flushPipe),
    .io_out_bits_uop_vpu_vma              (io_uopWriteback_0_bits_uop_vpu_vma),
    .io_out_bits_uop_vpu_vta              (io_uopWriteback_0_bits_uop_vpu_vta),
    .io_out_bits_uop_vpu_vsew             (io_uopWriteback_0_bits_uop_vpu_vsew),
    .io_out_bits_uop_vpu_vlmul            (io_uopWriteback_0_bits_uop_vpu_vlmul),
    .io_out_bits_uop_vpu_vm               (io_uopWriteback_0_bits_uop_vpu_vm),
    .io_out_bits_uop_vpu_vstart           (io_uopWriteback_0_bits_uop_vpu_vstart),
    .io_out_bits_uop_vpu_vuopIdx          (io_uopWriteback_0_bits_uop_vpu_vuopIdx),
    .io_out_bits_uop_vpu_vmask            (io_uopWriteback_0_bits_uop_vpu_vmask),
    .io_out_bits_uop_vpu_vl               (io_uopWriteback_0_bits_uop_vpu_vl),
    .io_out_bits_uop_vpu_nf               (io_uopWriteback_0_bits_uop_vpu_nf),
    .io_out_bits_uop_vpu_veew             (io_uopWriteback_0_bits_uop_vpu_veew),
    .io_out_bits_uop_pdest                (io_uopWriteback_0_bits_uop_pdest),
    .io_out_bits_uop_robIdx_flag          (io_uopWriteback_0_bits_uop_robIdx_flag),
    .io_out_bits_uop_robIdx_value         (io_uopWriteback_0_bits_uop_robIdx_value),
    .io_out_bits_uop_debugInfo_enqRsTime  (io_uopWriteback_0_bits_uop_debugInfo_enqRsTime),
    .io_out_bits_uop_debugInfo_selectTime (io_uopWriteback_0_bits_uop_debugInfo_selectTime),
    .io_out_bits_uop_debugInfo_issueTime  (io_uopWriteback_0_bits_uop_debugInfo_issueTime),
    .io_out_bits_uop_replayInst           (io_uopWriteback_0_bits_uop_replayInst),
    .io_out_bits_data                     (io_uopWriteback_0_bits_data),
    .io_out_bits_vdIdx                    (io_uopWriteback_0_bits_vdIdx),
    .io_out_bits_vdIdxInField             (io_uopWriteback_0_bits_vdIdxInField),
    .io_rightOutFire                      (io_uopWriteback_0_ready & io_uopWriteback_0_valid),
    .io_isFlush                           (pc_isFlush)
  );

endmodule
