// 自动生成：scripts/gen_writebackqueue.py —— 勿手改
module WritebackQueue(
  input  clock,
  input  reset,
  output io_req_ready,
  input  io_req_valid,
  input  [2:0] io_req_bits_param,
  input  io_req_bits_voluntary,
  input  io_req_bits_hasData,
  input  io_req_bits_corrupt,
  input  io_req_bits_dirty,
  input  [47:0] io_req_bits_addr,
  input  [511:0] io_req_bits_data,
  input  io_mem_release_ready,
  output io_mem_release_valid,
  output [2:0] io_mem_release_bits_opcode,
  output [2:0] io_mem_release_bits_param,
  output [2:0] io_mem_release_bits_size,
  output [5:0] io_mem_release_bits_source,
  output [47:0] io_mem_release_bits_address,
  output [255:0] io_mem_release_bits_data,
  output io_mem_release_bits_corrupt,
  input  io_mem_grant_valid,
  input  [5:0] io_mem_grant_bits_source,
  input  io_miss_req_conflict_check_0_valid,
  input  [47:0] io_miss_req_conflict_check_0_bits,
  input  io_miss_req_conflict_check_1_valid,
  input  [47:0] io_miss_req_conflict_check_1_bits,
  input  io_miss_req_conflict_check_2_valid,
  input  [47:0] io_miss_req_conflict_check_2_bits,
  input  io_miss_req_conflict_check_3_valid,
  input  [47:0] io_miss_req_conflict_check_3_bits,
  input  io_miss_req_conflict_check_4_valid,
  input  [47:0] io_miss_req_conflict_check_4_bits,
  output io_block_miss_req_0,
  output io_block_miss_req_1,
  output io_block_miss_req_2,
  output io_block_miss_req_3,
  output io_block_miss_req_4,
  output [5:0] io_perf_0_value,
  output [5:0] io_perf_1_value,
  output [5:0] io_perf_2_value,
  output [5:0] io_perf_3_value,
  output [5:0] io_perf_4_value
);
  xs_WritebackQueue_core u_core (
    .clock(clock),
    .reset(reset),
    .io_req_ready(io_req_ready),
    .io_req_valid(io_req_valid),
    .io_req_bits_param(io_req_bits_param),
    .io_req_bits_voluntary(io_req_bits_voluntary),
    .io_req_bits_hasData(io_req_bits_hasData),
    .io_req_bits_corrupt(io_req_bits_corrupt),
    .io_req_bits_dirty(io_req_bits_dirty),
    .io_req_bits_addr(io_req_bits_addr),
    .io_req_bits_data(io_req_bits_data),
    .io_mem_release_ready(io_mem_release_ready),
    .io_mem_release_valid(io_mem_release_valid),
    .io_mem_release_bits_opcode(io_mem_release_bits_opcode),
    .io_mem_release_bits_param(io_mem_release_bits_param),
    .io_mem_release_bits_size(io_mem_release_bits_size),
    .io_mem_release_bits_source(io_mem_release_bits_source),
    .io_mem_release_bits_address(io_mem_release_bits_address),
    .io_mem_release_bits_data(io_mem_release_bits_data),
    .io_mem_release_bits_corrupt(io_mem_release_bits_corrupt),
    .io_mem_grant_valid(io_mem_grant_valid),
    .io_mem_grant_bits_source(io_mem_grant_bits_source),
    .io_miss_req_conflict_check_0_valid(io_miss_req_conflict_check_0_valid),
    .io_miss_req_conflict_check_0_bits(io_miss_req_conflict_check_0_bits),
    .io_miss_req_conflict_check_1_valid(io_miss_req_conflict_check_1_valid),
    .io_miss_req_conflict_check_1_bits(io_miss_req_conflict_check_1_bits),
    .io_miss_req_conflict_check_2_valid(io_miss_req_conflict_check_2_valid),
    .io_miss_req_conflict_check_2_bits(io_miss_req_conflict_check_2_bits),
    .io_miss_req_conflict_check_3_valid(io_miss_req_conflict_check_3_valid),
    .io_miss_req_conflict_check_3_bits(io_miss_req_conflict_check_3_bits),
    .io_miss_req_conflict_check_4_valid(io_miss_req_conflict_check_4_valid),
    .io_miss_req_conflict_check_4_bits(io_miss_req_conflict_check_4_bits),
    .io_block_miss_req_0(io_block_miss_req_0),
    .io_block_miss_req_1(io_block_miss_req_1),
    .io_block_miss_req_2(io_block_miss_req_2),
    .io_block_miss_req_3(io_block_miss_req_3),
    .io_block_miss_req_4(io_block_miss_req_4),
    .io_perf_0_value(io_perf_0_value),
    .io_perf_1_value(io_perf_1_value),
    .io_perf_2_value(io_perf_2_value),
    .io_perf_3_value(io_perf_3_value),
    .io_perf_4_value(io_perf_4_value)
  );
endmodule
