// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module StorePipe(
  input          clock,
  input          reset,
  input  [47:0]  io_lsu_s1_paddr,
  input          io_lsu_s1_kill,
  input          io_lsu_s2_kill,
  input  [49:0]  io_lsu_s2_pc,
  output         io_lsu_req_ready,
  input          io_lsu_req_valid,
  input  [4:0]   io_lsu_req_bits_cmd,
  input  [49:0]  io_lsu_req_bits_vaddr,
  input  [3:0]   io_lsu_req_bits_instrtype,
  input          io_lsu_resp_ready,
  output         io_lsu_resp_valid,
  output         io_lsu_resp_bits_miss,
  output         io_lsu_resp_bits_replay,
  output         io_lsu_resp_bits_tag_error,
  input          io_meta_read_ready,
  output         io_meta_read_valid,
  output [7:0]   io_meta_read_bits_idx,
  output [3:0]   io_meta_read_bits_way_en,
  input  [1:0]   io_meta_resp_0_coh_state,
  input  [1:0]   io_meta_resp_1_coh_state,
  input  [1:0]   io_meta_resp_2_coh_state,
  input  [1:0]   io_meta_resp_3_coh_state,
  input          io_tag_read_ready,
  output         io_tag_read_valid,
  output [7:0]   io_tag_read_bits_idx,
  output [3:0]   io_tag_read_bits_way_en,
  input  [42:0]  io_tag_resp_0,
  input  [42:0]  io_tag_resp_1,
  input  [42:0]  io_tag_resp_2,
  input  [42:0]  io_tag_resp_3,
  input          io_miss_req_ready,
  output         io_miss_req_valid,
  output [3:0]   io_miss_req_bits_source,
  output [2:0]   io_miss_req_bits_pf_source,
  output [4:0]   io_miss_req_bits_cmd,
  output [47:0]  io_miss_req_bits_addr,
  output [49:0]  io_miss_req_bits_vaddr,
  output [49:0]  io_miss_req_bits_pc,
  output         io_miss_req_bits_lqIdx_flag,
  output [6:0]   io_miss_req_bits_lqIdx_value,
  output         io_miss_req_bits_full_overwrite,
  output [2:0]   io_miss_req_bits_word_idx,
  output [127:0] io_miss_req_bits_amo_data,
  output [15:0]  io_miss_req_bits_amo_mask,
  output [127:0] io_miss_req_bits_amo_cmp,
  output [1:0]   io_miss_req_bits_req_coh_state,
  output [5:0]   io_miss_req_bits_id,
  output         io_miss_req_bits_isBtoT,
  output [3:0]   io_miss_req_bits_occupy_way,
  output         io_miss_req_bits_cancel,
  output [511:0] io_miss_req_bits_store_data,
  output [63:0]  io_miss_req_bits_store_mask,
  output         io_replace_access_valid,
  output [7:0]   io_replace_access_bits_set,
  output [1:0]   io_replace_access_bits_way,
  output         io_replace_way_set_valid,
  output [7:0]   io_replace_way_set_bits,
  output [1:0]   io_replace_way_dmWay,
  input  [1:0]   io_replace_way_way,
  output         io_error_valid,
  output         io_error_bits_source_tag,
  output         io_error_bits_source_data,
  output         io_error_bits_source_l2,
  output         io_error_bits_opType_fetch,
  output         io_error_bits_opType_load,
  output         io_error_bits_opType_store,
  output         io_error_bits_opType_probe,
  output         io_error_bits_opType_release,
  output         io_error_bits_opType_atom,
  output [47:0]  io_error_bits_paddr,
  output         io_error_bits_report_to_beu
);

  wire             io_lsu_req_ready_0 = io_meta_read_ready & io_tag_read_ready;
  wire             _GEN = io_lsu_req_valid & ~io_lsu_req_ready_0;
  reg              s1_valid;
  reg  [4:0]       s1_req_cmd;
  reg  [49:0]      s1_req_vaddr;
  reg  [3:0]       s1_req_instrtype;
  reg              s2_valid_REG;
  reg              s2_valid_REG_1;
  wire             s2_valid = s2_valid_REG & s2_valid_REG_1;
  reg  [49:0]      s2_req_vaddr;
  reg              s2_hit;
  reg  [47:0]      s2_paddr;
  reg  [1:0]       s2_hit_coh_state;
  reg              s2_is_prefetch;
  wire             io_miss_req_valid_0 = s2_valid & ~s2_hit & s2_is_prefetch;
  wire             _GEN_0 = s2_valid & ~io_lsu_s2_kill;
  wire             _GEN_1 = s2_valid & s2_hit & ~io_lsu_s2_kill;
  wire             _GEN_2 = s2_valid & ~s2_hit & ~io_lsu_s2_kill;
  wire             _GEN_3 = io_miss_req_ready & io_miss_req_valid_0 & ~io_lsu_s2_kill;
  wire             _GEN_4 = io_miss_req_valid_0 & ~io_miss_req_ready & ~io_lsu_s2_kill;
  wire             _s1_tag_match_T_3 =
    io_tag_resp_0[35:0] == io_lsu_s1_paddr[47:12] & (|io_meta_resp_0_coh_state);
  wire             _s1_tag_match_T_7 =
    io_tag_resp_1[35:0] == io_lsu_s1_paddr[47:12] & (|io_meta_resp_1_coh_state);
  wire             _s1_tag_match_T_11 =
    io_tag_resp_2[35:0] == io_lsu_s1_paddr[47:12] & (|io_meta_resp_2_coh_state);
  wire             _s1_tag_match_T_15 =
    io_tag_resp_3[35:0] == io_lsu_s1_paddr[47:12] & (|io_meta_resp_3_coh_state);
  wire [3:0]       s1_tag_match =
    {_s1_tag_match_T_15, _s1_tag_match_T_11, _s1_tag_match_T_7, _s1_tag_match_T_3};
  wire [1:0]       s1_hit_meta_coh_state =
    (|s1_tag_match)
      ? (_s1_tag_match_T_3 ? io_meta_resp_0_coh_state : 2'h0)
        | (_s1_tag_match_T_7 ? io_meta_resp_1_coh_state : 2'h0)
        | (_s1_tag_match_T_11 ? io_meta_resp_2_coh_state : 2'h0)
        | (_s1_tag_match_T_15 ? io_meta_resp_3_coh_state : 2'h0)
      : 2'h0;
  wire             _r_c_cat_T_29 = s1_req_cmd == 5'h1;
  wire             _r_c_cat_T_30 = s1_req_cmd == 5'h11;
  wire             _r_c_cat_T_32 = s1_req_cmd == 5'h7;
  wire             _r_c_cat_T_34 = s1_req_cmd == 5'h4;
  wire             _r_c_cat_T_35 = s1_req_cmd == 5'h9;
  wire             _r_c_cat_T_36 = s1_req_cmd == 5'hA;
  wire             _r_c_cat_T_37 = s1_req_cmd == 5'hB;
  wire             _r_c_cat_T_41 = s1_req_cmd == 5'h8;
  wire             _r_c_cat_T_42 = s1_req_cmd == 5'hC;
  wire             _r_c_cat_T_43 = s1_req_cmd == 5'hD;
  wire             _r_c_cat_T_44 = s1_req_cmd == 5'hE;
  wire             _r_c_cat_T_45 = s1_req_cmd == 5'hF;
  wire             _r_c_cat_T_51 = s1_req_cmd == 5'h1A;
  wire             _r_c_cat_T_52 = s1_req_cmd == 5'h1B;
  wire             _r_c_cat_T_54 = s1_req_cmd == 5'h18;
  wire [3:0]       _r_T =
    {_r_c_cat_T_29 | _r_c_cat_T_30 | _r_c_cat_T_32 | _r_c_cat_T_34 | _r_c_cat_T_35
       | _r_c_cat_T_36 | _r_c_cat_T_37 | _r_c_cat_T_41 | _r_c_cat_T_42 | _r_c_cat_T_43
       | _r_c_cat_T_44 | _r_c_cat_T_45 | _r_c_cat_T_51 | _r_c_cat_T_52 | _r_c_cat_T_54,
     _r_c_cat_T_29 | _r_c_cat_T_30 | _r_c_cat_T_32 | _r_c_cat_T_34 | _r_c_cat_T_35
       | _r_c_cat_T_36 | _r_c_cat_T_37 | _r_c_cat_T_41 | _r_c_cat_T_42 | _r_c_cat_T_43
       | _r_c_cat_T_44 | _r_c_cat_T_45 | _r_c_cat_T_51 | _r_c_cat_T_52 | _r_c_cat_T_54
       | s1_req_cmd == 5'h3 | s1_req_cmd == 5'h6,
     s1_hit_meta_coh_state};
  wire [1:0]       _r_T_27 = {1'h0, _r_T == 4'hC};
  wire [15:0][1:0] _GEN_5 =
    {{2'h3},
     {2'h3},
     {2'h2},
     {_r_T_27},
     {_r_T_27},
     {_r_T_27},
     {_r_T_27},
     {_r_T_27},
     {2'h3},
     {2'h2},
     {2'h2},
     {2'h1},
     {2'h3},
     {2'h2},
     {2'h1},
     {2'h0}};
  wire             s0_fire = io_lsu_req_ready_0 & io_lsu_req_valid;
  always @(posedge clock) begin
    s1_valid <= s0_fire;
    if (s0_fire) begin
      s1_req_cmd <= io_lsu_req_bits_cmd;
      s1_req_vaddr <= io_lsu_req_bits_vaddr;
      s1_req_instrtype <= io_lsu_req_bits_instrtype;
    end
    s2_valid_REG <= s1_valid;
    s2_valid_REG_1 <= ~io_lsu_s1_kill;
    if (s1_valid) begin
      s2_req_vaddr <= s1_req_vaddr;
      s2_hit <=
        (_r_T == 4'h3 | _r_T == 4'h2 | _r_T == 4'h1 | _r_T == 4'h7 | _r_T == 4'h6
         | (&_r_T) | _r_T == 4'hE) & _GEN_5[_r_T] == s1_hit_meta_coh_state
        & (|s1_tag_match);
      s2_paddr <= io_lsu_s1_paddr;
      s2_hit_coh_state <= s1_hit_meta_coh_state;
      s2_is_prefetch <= s1_req_instrtype == 4'h3;
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:5];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [2:0] i = 3'h0; i < 3'h6; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        s1_valid = _RANDOM[3'h0][0];
        s1_req_cmd = _RANDOM[3'h0][5:1];
        s1_req_vaddr = {_RANDOM[3'h0][31:6], _RANDOM[3'h1][23:0]};
        s1_req_instrtype = _RANDOM[3'h1][27:24];
        s2_valid_REG = _RANDOM[3'h1][28];
        s2_valid_REG_1 = _RANDOM[3'h1][29];
        s2_req_vaddr = {_RANDOM[3'h2][31:3], _RANDOM[3'h3][20:0]};
        s2_hit = _RANDOM[3'h3][25];
        s2_paddr = {_RANDOM[3'h3][31:26], _RANDOM[3'h4], _RANDOM[3'h5][9:0]};
        s2_hit_coh_state = _RANDOM[3'h5][11:10];
        s2_is_prefetch = _RANDOM[3'h5][12];
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_lsu_req_ready = io_lsu_req_ready_0;
  assign io_lsu_resp_valid = s2_valid;
  assign io_lsu_resp_bits_miss = ~s2_hit;
  assign io_lsu_resp_bits_replay = 1'h0;
  assign io_lsu_resp_bits_tag_error = 1'h0;
  assign io_meta_read_valid = io_lsu_req_valid;
  assign io_meta_read_bits_idx = io_lsu_req_bits_vaddr[13:6];
  assign io_meta_read_bits_way_en = 4'hF;
  assign io_tag_read_valid = io_lsu_req_valid;
  assign io_tag_read_bits_idx = io_lsu_req_bits_vaddr[13:6];
  assign io_tag_read_bits_way_en = 4'hF;
  assign io_miss_req_valid = io_miss_req_valid_0;
  assign io_miss_req_bits_source = 4'h3;
  assign io_miss_req_bits_pf_source = 3'h4;
  assign io_miss_req_bits_cmd = 5'h3;
  assign io_miss_req_bits_addr = {s2_paddr[47:6], 6'h0};
  assign io_miss_req_bits_vaddr = s2_req_vaddr;
  assign io_miss_req_bits_pc = io_lsu_s2_pc;
  assign io_miss_req_bits_lqIdx_flag = 1'h0;
  assign io_miss_req_bits_lqIdx_value = 7'h0;
  assign io_miss_req_bits_full_overwrite = 1'h0;
  assign io_miss_req_bits_word_idx = 3'h0;
  assign io_miss_req_bits_amo_data = 128'h0;
  assign io_miss_req_bits_amo_mask = 16'h0;
  assign io_miss_req_bits_amo_cmp = 128'h0;
  assign io_miss_req_bits_req_coh_state = s2_hit_coh_state;
  assign io_miss_req_bits_id = 6'h0;
  assign io_miss_req_bits_isBtoT = 1'h0;
  assign io_miss_req_bits_occupy_way = 4'h0;
  assign io_miss_req_bits_cancel = io_lsu_s2_kill;
  assign io_miss_req_bits_store_data = 512'h0;
  assign io_miss_req_bits_store_mask = 64'h0;
  assign io_replace_access_valid = 1'h0;
  assign io_replace_access_bits_set = 8'h0;
  assign io_replace_access_bits_way = 2'h0;
  assign io_replace_way_set_valid = 1'h0;
  assign io_replace_way_set_bits = s1_req_vaddr[13:6];
  assign io_replace_way_dmWay = s1_req_vaddr[15:14];
  assign io_error_valid = 1'h0;
  assign io_error_bits_source_tag = 1'h0;
  assign io_error_bits_source_data = 1'h0;
  assign io_error_bits_source_l2 = 1'h0;
  assign io_error_bits_opType_fetch = 1'h0;
  assign io_error_bits_opType_load = 1'h0;
  assign io_error_bits_opType_store = 1'h0;
  assign io_error_bits_opType_probe = 1'h0;
  assign io_error_bits_opType_release = 1'h0;
  assign io_error_bits_opType_atom = 1'h0;
  assign io_error_bits_paddr = 48'h0;
  assign io_error_bits_report_to_beu = 1'h0;
endmodule

