// predictor_stubs.sv —— Composer FM 接口桩(端口空模块, 两侧同读)
// 自动生成: gen_composer_stubs.py, 端口逐字取自 canonical G0 golden-rtl/<M>.sv
// provenance=G0, 不含 implementation RTL; 修改请改生成器并重跑, 勿手改。
//
//   FTB: 323 ports
//   FauFTB: 143 ports
//   Tage_SC: 309 ports
//   ITTage: 492 ports

module FTB(
  input          clock,
  input          reset,
  input  [47:0]  io_reset_vector,
  input  [49:0]  io_in_bits_s0_pc_0,
  input  [49:0]  io_in_bits_s0_pc_1,
  input  [49:0]  io_in_bits_s0_pc_2,
  input  [49:0]  io_in_bits_s0_pc_3,
  input          io_in_bits_resp_in_0_s2_full_pred_0_br_taken_mask_0,
  input          io_in_bits_resp_in_0_s2_full_pred_0_br_taken_mask_1,
  input          io_in_bits_resp_in_0_s2_full_pred_1_br_taken_mask_0,
  input          io_in_bits_resp_in_0_s2_full_pred_1_br_taken_mask_1,
  input          io_in_bits_resp_in_0_s2_full_pred_2_br_taken_mask_0,
  input          io_in_bits_resp_in_0_s2_full_pred_2_br_taken_mask_1,
  input          io_in_bits_resp_in_0_s2_full_pred_3_br_taken_mask_0,
  input          io_in_bits_resp_in_0_s2_full_pred_3_br_taken_mask_1,
  input          io_in_bits_resp_in_0_s3_full_pred_0_br_taken_mask_0,
  input          io_in_bits_resp_in_0_s3_full_pred_0_br_taken_mask_1,
  input          io_in_bits_resp_in_0_s3_full_pred_1_br_taken_mask_0,
  input          io_in_bits_resp_in_0_s3_full_pred_1_br_taken_mask_1,
  input          io_in_bits_resp_in_0_s3_full_pred_2_br_taken_mask_0,
  input          io_in_bits_resp_in_0_s3_full_pred_2_br_taken_mask_1,
  input          io_in_bits_resp_in_0_s3_full_pred_3_br_taken_mask_0,
  input          io_in_bits_resp_in_0_s3_full_pred_3_br_taken_mask_1,
  input          io_in_bits_resp_in_0_last_stage_spec_info_sc_disagree_0,
  input          io_in_bits_resp_in_0_last_stage_spec_info_sc_disagree_1,
  output         io_out_s2_full_pred_0_br_taken_mask_0,
  output         io_out_s2_full_pred_0_br_taken_mask_1,
  output         io_out_s2_full_pred_0_slot_valids_0,
  output         io_out_s2_full_pred_0_slot_valids_1,
  output [49:0]  io_out_s2_full_pred_0_targets_0,
  output [49:0]  io_out_s2_full_pred_0_targets_1,
  output [49:0]  io_out_s2_full_pred_0_jalr_target,
  output [3:0]   io_out_s2_full_pred_0_offsets_0,
  output [3:0]   io_out_s2_full_pred_0_offsets_1,
  output [49:0]  io_out_s2_full_pred_0_fallThroughAddr,
  output         io_out_s2_full_pred_0_fallThroughErr,
  output         io_out_s2_full_pred_0_is_jal,
  output         io_out_s2_full_pred_0_is_jalr,
  output         io_out_s2_full_pred_0_is_call,
  output         io_out_s2_full_pred_0_is_ret,
  output         io_out_s2_full_pred_0_last_may_be_rvi_call,
  output         io_out_s2_full_pred_0_is_br_sharing,
  output         io_out_s2_full_pred_0_hit,
  output         io_out_s2_full_pred_1_br_taken_mask_0,
  output         io_out_s2_full_pred_1_br_taken_mask_1,
  output         io_out_s2_full_pred_1_slot_valids_0,
  output         io_out_s2_full_pred_1_slot_valids_1,
  output [49:0]  io_out_s2_full_pred_1_targets_0,
  output [49:0]  io_out_s2_full_pred_1_targets_1,
  output [49:0]  io_out_s2_full_pred_1_jalr_target,
  output [3:0]   io_out_s2_full_pred_1_offsets_0,
  output [3:0]   io_out_s2_full_pred_1_offsets_1,
  output [49:0]  io_out_s2_full_pred_1_fallThroughAddr,
  output         io_out_s2_full_pred_1_fallThroughErr,
  output         io_out_s2_full_pred_1_is_jal,
  output         io_out_s2_full_pred_1_is_jalr,
  output         io_out_s2_full_pred_1_is_call,
  output         io_out_s2_full_pred_1_is_ret,
  output         io_out_s2_full_pred_1_last_may_be_rvi_call,
  output         io_out_s2_full_pred_1_is_br_sharing,
  output         io_out_s2_full_pred_1_hit,
  output         io_out_s2_full_pred_2_br_taken_mask_0,
  output         io_out_s2_full_pred_2_br_taken_mask_1,
  output         io_out_s2_full_pred_2_slot_valids_0,
  output         io_out_s2_full_pred_2_slot_valids_1,
  output [49:0]  io_out_s2_full_pred_2_targets_0,
  output [49:0]  io_out_s2_full_pred_2_targets_1,
  output [49:0]  io_out_s2_full_pred_2_jalr_target,
  output [3:0]   io_out_s2_full_pred_2_offsets_0,
  output [3:0]   io_out_s2_full_pred_2_offsets_1,
  output [49:0]  io_out_s2_full_pred_2_fallThroughAddr,
  output         io_out_s2_full_pred_2_fallThroughErr,
  output         io_out_s2_full_pred_2_is_jal,
  output         io_out_s2_full_pred_2_is_jalr,
  output         io_out_s2_full_pred_2_is_call,
  output         io_out_s2_full_pred_2_is_ret,
  output         io_out_s2_full_pred_2_last_may_be_rvi_call,
  output         io_out_s2_full_pred_2_is_br_sharing,
  output         io_out_s2_full_pred_2_hit,
  output         io_out_s2_full_pred_3_br_taken_mask_0,
  output         io_out_s2_full_pred_3_br_taken_mask_1,
  output         io_out_s2_full_pred_3_slot_valids_0,
  output         io_out_s2_full_pred_3_slot_valids_1,
  output [49:0]  io_out_s2_full_pred_3_targets_0,
  output [49:0]  io_out_s2_full_pred_3_targets_1,
  output [49:0]  io_out_s2_full_pred_3_jalr_target,
  output [3:0]   io_out_s2_full_pred_3_offsets_0,
  output [3:0]   io_out_s2_full_pred_3_offsets_1,
  output [49:0]  io_out_s2_full_pred_3_fallThroughAddr,
  output         io_out_s2_full_pred_3_fallThroughErr,
  output         io_out_s2_full_pred_3_is_jal,
  output         io_out_s2_full_pred_3_is_jalr,
  output         io_out_s2_full_pred_3_is_call,
  output         io_out_s2_full_pred_3_is_ret,
  output         io_out_s2_full_pred_3_last_may_be_rvi_call,
  output         io_out_s2_full_pred_3_is_br_sharing,
  output         io_out_s2_full_pred_3_hit,
  output         io_out_s3_full_pred_0_br_taken_mask_0,
  output         io_out_s3_full_pred_0_br_taken_mask_1,
  output         io_out_s3_full_pred_0_slot_valids_0,
  output         io_out_s3_full_pred_0_slot_valids_1,
  output [49:0]  io_out_s3_full_pred_0_targets_0,
  output [49:0]  io_out_s3_full_pred_0_targets_1,
  output [3:0]   io_out_s3_full_pred_0_offsets_0,
  output [3:0]   io_out_s3_full_pred_0_offsets_1,
  output [49:0]  io_out_s3_full_pred_0_fallThroughAddr,
  output         io_out_s3_full_pred_0_fallThroughErr,
  output         io_out_s3_full_pred_0_multiHit,
  output         io_out_s3_full_pred_0_is_jal,
  output         io_out_s3_full_pred_0_is_jalr,
  output         io_out_s3_full_pred_0_is_call,
  output         io_out_s3_full_pred_0_is_ret,
  output         io_out_s3_full_pred_0_last_may_be_rvi_call,
  output         io_out_s3_full_pred_0_is_br_sharing,
  output         io_out_s3_full_pred_0_hit,
  output         io_out_s3_full_pred_1_br_taken_mask_0,
  output         io_out_s3_full_pred_1_br_taken_mask_1,
  output         io_out_s3_full_pred_1_slot_valids_0,
  output         io_out_s3_full_pred_1_slot_valids_1,
  output [49:0]  io_out_s3_full_pred_1_targets_0,
  output [49:0]  io_out_s3_full_pred_1_targets_1,
  output [3:0]   io_out_s3_full_pred_1_offsets_0,
  output [3:0]   io_out_s3_full_pred_1_offsets_1,
  output [49:0]  io_out_s3_full_pred_1_fallThroughAddr,
  output         io_out_s3_full_pred_1_fallThroughErr,
  output         io_out_s3_full_pred_1_multiHit,
  output         io_out_s3_full_pred_1_is_jal,
  output         io_out_s3_full_pred_1_is_jalr,
  output         io_out_s3_full_pred_1_is_call,
  output         io_out_s3_full_pred_1_is_ret,
  output         io_out_s3_full_pred_1_last_may_be_rvi_call,
  output         io_out_s3_full_pred_1_is_br_sharing,
  output         io_out_s3_full_pred_1_hit,
  output         io_out_s3_full_pred_2_br_taken_mask_0,
  output         io_out_s3_full_pred_2_br_taken_mask_1,
  output         io_out_s3_full_pred_2_slot_valids_0,
  output         io_out_s3_full_pred_2_slot_valids_1,
  output [49:0]  io_out_s3_full_pred_2_targets_0,
  output [49:0]  io_out_s3_full_pred_2_targets_1,
  output [3:0]   io_out_s3_full_pred_2_offsets_0,
  output [3:0]   io_out_s3_full_pred_2_offsets_1,
  output [49:0]  io_out_s3_full_pred_2_fallThroughAddr,
  output         io_out_s3_full_pred_2_fallThroughErr,
  output         io_out_s3_full_pred_2_multiHit,
  output         io_out_s3_full_pred_2_is_jal,
  output         io_out_s3_full_pred_2_is_jalr,
  output         io_out_s3_full_pred_2_is_call,
  output         io_out_s3_full_pred_2_is_ret,
  output         io_out_s3_full_pred_2_last_may_be_rvi_call,
  output         io_out_s3_full_pred_2_is_br_sharing,
  output         io_out_s3_full_pred_2_hit,
  output         io_out_s3_full_pred_3_br_taken_mask_0,
  output         io_out_s3_full_pred_3_br_taken_mask_1,
  output         io_out_s3_full_pred_3_slot_valids_0,
  output         io_out_s3_full_pred_3_slot_valids_1,
  output [49:0]  io_out_s3_full_pred_3_targets_0,
  output [49:0]  io_out_s3_full_pred_3_targets_1,
  output [3:0]   io_out_s3_full_pred_3_offsets_0,
  output [3:0]   io_out_s3_full_pred_3_offsets_1,
  output [49:0]  io_out_s3_full_pred_3_fallThroughAddr,
  output         io_out_s3_full_pred_3_fallThroughErr,
  output         io_out_s3_full_pred_3_multiHit,
  output         io_out_s3_full_pred_3_is_jal,
  output         io_out_s3_full_pred_3_is_jalr,
  output         io_out_s3_full_pred_3_is_call,
  output         io_out_s3_full_pred_3_is_ret,
  output         io_out_s3_full_pred_3_last_may_be_rvi_call,
  output         io_out_s3_full_pred_3_is_br_sharing,
  output         io_out_s3_full_pred_3_hit,
  output         io_out_s1_uftbHit,
  output         io_out_s1_uftbHasIndirect,
  output         io_out_s1_ftbCloseReq,
  output [515:0] io_out_last_stage_meta,
  output         io_out_last_stage_spec_info_sc_disagree_0,
  output         io_out_last_stage_spec_info_sc_disagree_1,
  output         io_out_last_stage_ftb_entry_isCall,
  output         io_out_last_stage_ftb_entry_isRet,
  output         io_out_last_stage_ftb_entry_isJalr,
  output         io_out_last_stage_ftb_entry_valid,
  output [3:0]   io_out_last_stage_ftb_entry_brSlots_0_offset,
  output         io_out_last_stage_ftb_entry_brSlots_0_sharing,
  output         io_out_last_stage_ftb_entry_brSlots_0_valid,
  output [11:0]  io_out_last_stage_ftb_entry_brSlots_0_lower,
  output [1:0]   io_out_last_stage_ftb_entry_brSlots_0_tarStat,
  output [3:0]   io_out_last_stage_ftb_entry_tailSlot_offset,
  output         io_out_last_stage_ftb_entry_tailSlot_sharing,
  output         io_out_last_stage_ftb_entry_tailSlot_valid,
  output [19:0]  io_out_last_stage_ftb_entry_tailSlot_lower,
  output [1:0]   io_out_last_stage_ftb_entry_tailSlot_tarStat,
  output [3:0]   io_out_last_stage_ftb_entry_pftAddr,
  output         io_out_last_stage_ftb_entry_carry,
  output         io_out_last_stage_ftb_entry_last_may_be_rvi_call,
  output         io_out_last_stage_ftb_entry_strong_bias_0,
  output         io_out_last_stage_ftb_entry_strong_bias_1,
  input          io_fauftb_entry_in_isCall,
  input          io_fauftb_entry_in_isRet,
  input          io_fauftb_entry_in_isJalr,
  input          io_fauftb_entry_in_valid,
  input  [3:0]   io_fauftb_entry_in_brSlots_0_offset,
  input          io_fauftb_entry_in_brSlots_0_sharing,
  input          io_fauftb_entry_in_brSlots_0_valid,
  input  [11:0]  io_fauftb_entry_in_brSlots_0_lower,
  input  [1:0]   io_fauftb_entry_in_brSlots_0_tarStat,
  input  [3:0]   io_fauftb_entry_in_tailSlot_offset,
  input          io_fauftb_entry_in_tailSlot_sharing,
  input          io_fauftb_entry_in_tailSlot_valid,
  input  [19:0]  io_fauftb_entry_in_tailSlot_lower,
  input  [1:0]   io_fauftb_entry_in_tailSlot_tarStat,
  input  [3:0]   io_fauftb_entry_in_pftAddr,
  input          io_fauftb_entry_in_carry,
  input          io_fauftb_entry_in_last_may_be_rvi_call,
  input          io_fauftb_entry_in_strong_bias_0,
  input          io_fauftb_entry_in_strong_bias_1,
  input          io_fauftb_entry_hit_in,
  input          io_ctrl_btb_enable,
  input          io_s0_fire_0,
  input          io_s0_fire_1,
  input          io_s0_fire_2,
  input          io_s0_fire_3,
  input          io_s1_fire_0,
  input          io_s1_fire_1,
  input          io_s1_fire_2,
  input          io_s1_fire_3,
  input          io_s2_fire_0,
  input          io_s2_fire_1,
  input          io_s2_fire_2,
  input          io_s2_fire_3,
  input          io_s3_fire_0,
  output         io_s1_ready,
  input          io_update_valid,
  input  [49:0]  io_update_bits_pc,
  input          io_update_bits_ftb_entry_isCall,
  input          io_update_bits_ftb_entry_isRet,
  input          io_update_bits_ftb_entry_isJalr,
  input          io_update_bits_ftb_entry_valid,
  input  [3:0]   io_update_bits_ftb_entry_brSlots_0_offset,
  input          io_update_bits_ftb_entry_brSlots_0_sharing,
  input          io_update_bits_ftb_entry_brSlots_0_valid,
  input  [11:0]  io_update_bits_ftb_entry_brSlots_0_lower,
  input  [1:0]   io_update_bits_ftb_entry_brSlots_0_tarStat,
  input  [3:0]   io_update_bits_ftb_entry_tailSlot_offset,
  input          io_update_bits_ftb_entry_tailSlot_sharing,
  input          io_update_bits_ftb_entry_tailSlot_valid,
  input  [19:0]  io_update_bits_ftb_entry_tailSlot_lower,
  input  [1:0]   io_update_bits_ftb_entry_tailSlot_tarStat,
  input  [3:0]   io_update_bits_ftb_entry_pftAddr,
  input          io_update_bits_ftb_entry_carry,
  input          io_update_bits_ftb_entry_last_may_be_rvi_call,
  input          io_update_bits_ftb_entry_strong_bias_0,
  input          io_update_bits_ftb_entry_strong_bias_1,
  input          io_update_bits_false_hit,
  input          io_update_bits_old_entry,
  input  [515:0] io_update_bits_meta,
  input          io_redirectFromIFU,
  output [5:0]   io_perf_0_value,
  output [5:0]   io_perf_1_value,
  input  [5:0]   boreChildrenBd_bore_array,
  input          boreChildrenBd_bore_all,
  input          boreChildrenBd_bore_req,
  output         boreChildrenBd_bore_ack,
  input          boreChildrenBd_bore_writeen,
  input  [3:0]   boreChildrenBd_bore_be,
  input  [9:0]   boreChildrenBd_bore_addr,
  input  [39:0]  boreChildrenBd_bore_indata,
  input          boreChildrenBd_bore_readen,
  input  [9:0]   boreChildrenBd_bore_addr_rd,
  output [39:0]  boreChildrenBd_bore_outdata,
  input          sigFromSrams_bore_ram_hold,
  input          sigFromSrams_bore_ram_bypass,
  input          sigFromSrams_bore_ram_bp_clken,
  input          sigFromSrams_bore_ram_aux_clk,
  input          sigFromSrams_bore_ram_aux_ckbp,
  input          sigFromSrams_bore_ram_mcp_hold,
  input          sigFromSrams_bore_cgen,
  input          sigFromSrams_bore_1_ram_hold,
  input          sigFromSrams_bore_1_ram_bypass,
  input          sigFromSrams_bore_1_ram_bp_clken,
  input          sigFromSrams_bore_1_ram_aux_clk,
  input          sigFromSrams_bore_1_ram_aux_ckbp,
  input          sigFromSrams_bore_1_ram_mcp_hold,
  input          sigFromSrams_bore_1_cgen,
  input          sigFromSrams_bore_2_ram_hold,
  input          sigFromSrams_bore_2_ram_bypass,
  input          sigFromSrams_bore_2_ram_bp_clken,
  input          sigFromSrams_bore_2_ram_aux_clk,
  input          sigFromSrams_bore_2_ram_aux_ckbp,
  input          sigFromSrams_bore_2_ram_mcp_hold,
  input          sigFromSrams_bore_2_cgen,
  input          sigFromSrams_bore_3_ram_hold,
  input          sigFromSrams_bore_3_ram_bypass,
  input          sigFromSrams_bore_3_ram_bp_clken,
  input          sigFromSrams_bore_3_ram_aux_clk,
  input          sigFromSrams_bore_3_ram_aux_ckbp,
  input          sigFromSrams_bore_3_ram_mcp_hold,
  input          sigFromSrams_bore_3_cgen,
  input          sigFromSrams_bore_4_ram_hold,
  input          sigFromSrams_bore_4_ram_bypass,
  input          sigFromSrams_bore_4_ram_bp_clken,
  input          sigFromSrams_bore_4_ram_aux_clk,
  input          sigFromSrams_bore_4_ram_aux_ckbp,
  input          sigFromSrams_bore_4_ram_mcp_hold,
  input          sigFromSrams_bore_4_cgen,
  input          sigFromSrams_bore_5_ram_hold,
  input          sigFromSrams_bore_5_ram_bypass,
  input          sigFromSrams_bore_5_ram_bp_clken,
  input          sigFromSrams_bore_5_ram_aux_clk,
  input          sigFromSrams_bore_5_ram_aux_ckbp,
  input          sigFromSrams_bore_5_ram_mcp_hold,
  input          sigFromSrams_bore_5_cgen,
  input          sigFromSrams_bore_6_ram_hold,
  input          sigFromSrams_bore_6_ram_bypass,
  input          sigFromSrams_bore_6_ram_bp_clken,
  input          sigFromSrams_bore_6_ram_aux_clk,
  input          sigFromSrams_bore_6_ram_aux_ckbp,
  input          sigFromSrams_bore_6_ram_mcp_hold,
  input          sigFromSrams_bore_6_cgen,
  input          sigFromSrams_bore_7_ram_hold,
  input          sigFromSrams_bore_7_ram_bypass,
  input          sigFromSrams_bore_7_ram_bp_clken,
  input          sigFromSrams_bore_7_ram_aux_clk,
  input          sigFromSrams_bore_7_ram_aux_ckbp,
  input          sigFromSrams_bore_7_ram_mcp_hold,
  input          sigFromSrams_bore_7_cgen
);
endmodule

module FauFTB(
  input          clock,
  input          reset,
  input  [47:0]  io_reset_vector,
  input  [49:0]  io_in_bits_s0_pc_0,
  input  [49:0]  io_in_bits_s0_pc_1,
  input  [49:0]  io_in_bits_s0_pc_2,
  input  [49:0]  io_in_bits_s0_pc_3,
  output [49:0]  io_out_s1_pc_0,
  output [49:0]  io_out_s1_pc_1,
  output [49:0]  io_out_s1_pc_2,
  output [49:0]  io_out_s1_pc_3,
  output         io_out_s1_full_pred_0_br_taken_mask_0,
  output         io_out_s1_full_pred_0_br_taken_mask_1,
  output         io_out_s1_full_pred_0_slot_valids_0,
  output         io_out_s1_full_pred_0_slot_valids_1,
  output [49:0]  io_out_s1_full_pred_0_targets_0,
  output [49:0]  io_out_s1_full_pred_0_targets_1,
  output [49:0]  io_out_s1_full_pred_0_jalr_target,
  output [3:0]   io_out_s1_full_pred_0_offsets_0,
  output [3:0]   io_out_s1_full_pred_0_offsets_1,
  output [49:0]  io_out_s1_full_pred_0_fallThroughAddr,
  output         io_out_s1_full_pred_0_fallThroughErr,
  output         io_out_s1_full_pred_0_is_jal,
  output         io_out_s1_full_pred_0_is_jalr,
  output         io_out_s1_full_pred_0_is_call,
  output         io_out_s1_full_pred_0_is_ret,
  output         io_out_s1_full_pred_0_last_may_be_rvi_call,
  output         io_out_s1_full_pred_0_is_br_sharing,
  output         io_out_s1_full_pred_0_hit,
  output         io_out_s1_full_pred_1_br_taken_mask_0,
  output         io_out_s1_full_pred_1_br_taken_mask_1,
  output         io_out_s1_full_pred_1_slot_valids_0,
  output         io_out_s1_full_pred_1_slot_valids_1,
  output [49:0]  io_out_s1_full_pred_1_targets_0,
  output [49:0]  io_out_s1_full_pred_1_targets_1,
  output [49:0]  io_out_s1_full_pred_1_jalr_target,
  output [3:0]   io_out_s1_full_pred_1_offsets_0,
  output [3:0]   io_out_s1_full_pred_1_offsets_1,
  output [49:0]  io_out_s1_full_pred_1_fallThroughAddr,
  output         io_out_s1_full_pred_1_fallThroughErr,
  output         io_out_s1_full_pred_1_is_jal,
  output         io_out_s1_full_pred_1_is_jalr,
  output         io_out_s1_full_pred_1_is_call,
  output         io_out_s1_full_pred_1_is_ret,
  output         io_out_s1_full_pred_1_last_may_be_rvi_call,
  output         io_out_s1_full_pred_1_is_br_sharing,
  output         io_out_s1_full_pred_1_hit,
  output         io_out_s1_full_pred_2_br_taken_mask_0,
  output         io_out_s1_full_pred_2_br_taken_mask_1,
  output         io_out_s1_full_pred_2_slot_valids_0,
  output         io_out_s1_full_pred_2_slot_valids_1,
  output [49:0]  io_out_s1_full_pred_2_targets_0,
  output [49:0]  io_out_s1_full_pred_2_targets_1,
  output [49:0]  io_out_s1_full_pred_2_jalr_target,
  output [3:0]   io_out_s1_full_pred_2_offsets_0,
  output [3:0]   io_out_s1_full_pred_2_offsets_1,
  output [49:0]  io_out_s1_full_pred_2_fallThroughAddr,
  output         io_out_s1_full_pred_2_fallThroughErr,
  output         io_out_s1_full_pred_2_is_jal,
  output         io_out_s1_full_pred_2_is_jalr,
  output         io_out_s1_full_pred_2_is_call,
  output         io_out_s1_full_pred_2_is_ret,
  output         io_out_s1_full_pred_2_last_may_be_rvi_call,
  output         io_out_s1_full_pred_2_is_br_sharing,
  output         io_out_s1_full_pred_2_hit,
  output         io_out_s1_full_pred_3_br_taken_mask_0,
  output         io_out_s1_full_pred_3_br_taken_mask_1,
  output         io_out_s1_full_pred_3_slot_valids_0,
  output         io_out_s1_full_pred_3_slot_valids_1,
  output [49:0]  io_out_s1_full_pred_3_targets_0,
  output [49:0]  io_out_s1_full_pred_3_targets_1,
  output [49:0]  io_out_s1_full_pred_3_jalr_target,
  output [3:0]   io_out_s1_full_pred_3_offsets_0,
  output [3:0]   io_out_s1_full_pred_3_offsets_1,
  output [49:0]  io_out_s1_full_pred_3_fallThroughAddr,
  output         io_out_s1_full_pred_3_fallThroughErr,
  output         io_out_s1_full_pred_3_is_jal,
  output         io_out_s1_full_pred_3_is_jalr,
  output         io_out_s1_full_pred_3_is_call,
  output         io_out_s1_full_pred_3_is_ret,
  output         io_out_s1_full_pred_3_last_may_be_rvi_call,
  output         io_out_s1_full_pred_3_is_br_sharing,
  output         io_out_s1_full_pred_3_hit,
  output [515:0] io_out_last_stage_meta,
  output         io_fauftb_entry_out_isCall,
  output         io_fauftb_entry_out_isRet,
  output         io_fauftb_entry_out_isJalr,
  output         io_fauftb_entry_out_valid,
  output [3:0]   io_fauftb_entry_out_brSlots_0_offset,
  output         io_fauftb_entry_out_brSlots_0_sharing,
  output         io_fauftb_entry_out_brSlots_0_valid,
  output [11:0]  io_fauftb_entry_out_brSlots_0_lower,
  output [1:0]   io_fauftb_entry_out_brSlots_0_tarStat,
  output [3:0]   io_fauftb_entry_out_tailSlot_offset,
  output         io_fauftb_entry_out_tailSlot_sharing,
  output         io_fauftb_entry_out_tailSlot_valid,
  output [19:0]  io_fauftb_entry_out_tailSlot_lower,
  output [1:0]   io_fauftb_entry_out_tailSlot_tarStat,
  output [3:0]   io_fauftb_entry_out_pftAddr,
  output         io_fauftb_entry_out_carry,
  output         io_fauftb_entry_out_last_may_be_rvi_call,
  output         io_fauftb_entry_out_strong_bias_0,
  output         io_fauftb_entry_out_strong_bias_1,
  output         io_fauftb_entry_hit_out,
  input          io_ctrl_ubtb_enable,
  input          io_s0_fire_0,
  input          io_s0_fire_1,
  input          io_s0_fire_2,
  input          io_s0_fire_3,
  input          io_s1_fire_0,
  input          io_s1_fire_1,
  input          io_s1_fire_2,
  input          io_s1_fire_3,
  input          io_s2_fire_0,
  input          io_s2_fire_1,
  input          io_s2_fire_2,
  input          io_s2_fire_3,
  input          io_update_valid,
  input  [49:0]  io_update_bits_pc,
  input          io_update_bits_ftb_entry_isCall,
  input          io_update_bits_ftb_entry_isRet,
  input          io_update_bits_ftb_entry_isJalr,
  input          io_update_bits_ftb_entry_valid,
  input  [3:0]   io_update_bits_ftb_entry_brSlots_0_offset,
  input          io_update_bits_ftb_entry_brSlots_0_sharing,
  input          io_update_bits_ftb_entry_brSlots_0_valid,
  input  [11:0]  io_update_bits_ftb_entry_brSlots_0_lower,
  input  [1:0]   io_update_bits_ftb_entry_brSlots_0_tarStat,
  input  [3:0]   io_update_bits_ftb_entry_tailSlot_offset,
  input          io_update_bits_ftb_entry_tailSlot_sharing,
  input          io_update_bits_ftb_entry_tailSlot_valid,
  input  [19:0]  io_update_bits_ftb_entry_tailSlot_lower,
  input  [1:0]   io_update_bits_ftb_entry_tailSlot_tarStat,
  input  [3:0]   io_update_bits_ftb_entry_pftAddr,
  input          io_update_bits_ftb_entry_carry,
  input          io_update_bits_ftb_entry_last_may_be_rvi_call,
  input          io_update_bits_ftb_entry_strong_bias_0,
  input          io_update_bits_ftb_entry_strong_bias_1,
  input          io_update_bits_br_taken_mask_0,
  input          io_update_bits_br_taken_mask_1,
  input  [515:0] io_update_bits_meta,
  output [5:0]   io_perf_0_value,
  output [5:0]   io_perf_1_value
);
endmodule

module Tage_SC(
  input          clock,
  input          reset,
  input  [47:0]  io_reset_vector,
  input  [49:0]  io_in_bits_s0_pc_0,
  input  [49:0]  io_in_bits_s0_pc_1,
  input  [49:0]  io_in_bits_s0_pc_2,
  input  [49:0]  io_in_bits_s0_pc_3,
  input  [10:0]  io_in_bits_folded_hist_1_hist_17_folded_hist,
  input  [10:0]  io_in_bits_folded_hist_1_hist_16_folded_hist,
  input  [6:0]   io_in_bits_folded_hist_1_hist_15_folded_hist,
  input  [7:0]   io_in_bits_folded_hist_1_hist_14_folded_hist,
  input  [6:0]   io_in_bits_folded_hist_1_hist_9_folded_hist,
  input  [7:0]   io_in_bits_folded_hist_1_hist_8_folded_hist,
  input  [6:0]   io_in_bits_folded_hist_1_hist_7_folded_hist,
  input  [6:0]   io_in_bits_folded_hist_1_hist_5_folded_hist,
  input  [7:0]   io_in_bits_folded_hist_1_hist_4_folded_hist,
  input  [7:0]   io_in_bits_folded_hist_1_hist_3_folded_hist,
  input  [10:0]  io_in_bits_folded_hist_1_hist_1_folded_hist,
  input  [3:0]   io_in_bits_folded_hist_3_hist_12_folded_hist,
  input  [7:0]   io_in_bits_folded_hist_3_hist_11_folded_hist,
  input  [7:0]   io_in_bits_folded_hist_3_hist_2_folded_hist,
  input  [255:0] io_in_bits_ghist,
  output         io_out_s2_full_pred_0_br_taken_mask_0,
  output         io_out_s2_full_pred_0_br_taken_mask_1,
  output         io_out_s2_full_pred_1_br_taken_mask_0,
  output         io_out_s2_full_pred_1_br_taken_mask_1,
  output         io_out_s2_full_pred_2_br_taken_mask_0,
  output         io_out_s2_full_pred_2_br_taken_mask_1,
  output         io_out_s2_full_pred_3_br_taken_mask_0,
  output         io_out_s2_full_pred_3_br_taken_mask_1,
  output         io_out_s3_full_pred_0_br_taken_mask_0,
  output         io_out_s3_full_pred_0_br_taken_mask_1,
  output         io_out_s3_full_pred_1_br_taken_mask_0,
  output         io_out_s3_full_pred_1_br_taken_mask_1,
  output         io_out_s3_full_pred_2_br_taken_mask_0,
  output         io_out_s3_full_pred_2_br_taken_mask_1,
  output         io_out_s3_full_pred_3_br_taken_mask_0,
  output         io_out_s3_full_pred_3_br_taken_mask_1,
  output [515:0] io_out_last_stage_meta,
  output         io_out_last_stage_spec_info_sc_disagree_0,
  output         io_out_last_stage_spec_info_sc_disagree_1,
  input          io_ctrl_tage_enable,
  input          io_ctrl_sc_enable,
  input          io_s0_fire_0,
  input          io_s0_fire_1,
  input          io_s0_fire_2,
  input          io_s0_fire_3,
  input          io_s1_fire_0,
  input          io_s1_fire_1,
  input          io_s1_fire_2,
  input          io_s1_fire_3,
  input          io_s2_fire_0,
  input          io_s2_fire_1,
  input          io_s2_fire_2,
  input          io_s2_fire_3,
  output         io_s1_ready,
  input          io_update_valid,
  input  [49:0]  io_update_bits_pc,
  input          io_update_bits_ftb_entry_brSlots_0_valid,
  input          io_update_bits_ftb_entry_tailSlot_sharing,
  input          io_update_bits_ftb_entry_tailSlot_valid,
  input          io_update_bits_ftb_entry_strong_bias_0,
  input          io_update_bits_ftb_entry_strong_bias_1,
  input          io_update_bits_br_taken_mask_0,
  input          io_update_bits_br_taken_mask_1,
  input          io_update_bits_mispred_mask_0,
  input          io_update_bits_mispred_mask_1,
  input  [515:0] io_update_bits_meta,
  input  [255:0] io_update_bits_ghist,
  output [5:0]   io_perf_0_value,
  output [5:0]   io_perf_1_value,
  output [5:0]   io_perf_2_value,
  input  [6:0]   boreChildrenBd_bore_array,
  input          boreChildrenBd_bore_all,
  input          boreChildrenBd_bore_req,
  output         boreChildrenBd_bore_ack,
  input          boreChildrenBd_bore_writeen,
  input  [15:0]  boreChildrenBd_bore_be,
  input  [9:0]   boreChildrenBd_bore_addr,
  input  [23:0]  boreChildrenBd_bore_indata,
  input          boreChildrenBd_bore_readen,
  input  [9:0]   boreChildrenBd_bore_addr_rd,
  output [23:0]  boreChildrenBd_bore_outdata,
  input  [6:0]   boreChildrenBd_bore_1_array,
  input          boreChildrenBd_bore_1_all,
  input          boreChildrenBd_bore_1_req,
  output         boreChildrenBd_bore_1_ack,
  input          boreChildrenBd_bore_1_writeen,
  input  [3:0]   boreChildrenBd_bore_1_be,
  input  [8:0]   boreChildrenBd_bore_1_addr,
  input  [23:0]  boreChildrenBd_bore_1_indata,
  input          boreChildrenBd_bore_1_readen,
  input  [8:0]   boreChildrenBd_bore_1_addr_rd,
  output [23:0]  boreChildrenBd_bore_1_outdata,
  input  [6:0]   boreChildrenBd_bore_2_array,
  input          boreChildrenBd_bore_2_all,
  input          boreChildrenBd_bore_2_req,
  output         boreChildrenBd_bore_2_ack,
  input          boreChildrenBd_bore_2_writeen,
  input  [3:0]   boreChildrenBd_bore_2_be,
  input  [8:0]   boreChildrenBd_bore_2_addr,
  input  [23:0]  boreChildrenBd_bore_2_indata,
  input          boreChildrenBd_bore_2_readen,
  input  [8:0]   boreChildrenBd_bore_2_addr_rd,
  output [23:0]  boreChildrenBd_bore_2_outdata,
  input  [6:0]   boreChildrenBd_bore_3_array,
  input          boreChildrenBd_bore_3_all,
  input          boreChildrenBd_bore_3_req,
  output         boreChildrenBd_bore_3_ack,
  input          boreChildrenBd_bore_3_writeen,
  input  [3:0]   boreChildrenBd_bore_3_be,
  input  [8:0]   boreChildrenBd_bore_3_addr,
  input  [23:0]  boreChildrenBd_bore_3_indata,
  input          boreChildrenBd_bore_3_readen,
  input  [8:0]   boreChildrenBd_bore_3_addr_rd,
  output [23:0]  boreChildrenBd_bore_3_outdata,
  input  [6:0]   boreChildrenBd_bore_4_array,
  input          boreChildrenBd_bore_4_all,
  input          boreChildrenBd_bore_4_req,
  output         boreChildrenBd_bore_4_ack,
  input          boreChildrenBd_bore_4_writeen,
  input  [3:0]   boreChildrenBd_bore_4_be,
  input  [8:0]   boreChildrenBd_bore_4_addr,
  input  [23:0]  boreChildrenBd_bore_4_indata,
  input          boreChildrenBd_bore_4_readen,
  input  [8:0]   boreChildrenBd_bore_4_addr_rd,
  output [23:0]  boreChildrenBd_bore_4_outdata,
  input          sigFromSrams_bore_ram_hold,
  input          sigFromSrams_bore_ram_bypass,
  input          sigFromSrams_bore_ram_bp_clken,
  input          sigFromSrams_bore_ram_aux_clk,
  input          sigFromSrams_bore_ram_aux_ckbp,
  input          sigFromSrams_bore_ram_mcp_hold,
  input          sigFromSrams_bore_cgen,
  input          sigFromSrams_bore_1_ram_hold,
  input          sigFromSrams_bore_1_ram_bypass,
  input          sigFromSrams_bore_1_ram_bp_clken,
  input          sigFromSrams_bore_1_ram_aux_clk,
  input          sigFromSrams_bore_1_ram_aux_ckbp,
  input          sigFromSrams_bore_1_ram_mcp_hold,
  input          sigFromSrams_bore_1_cgen,
  input          sigFromSrams_bore_2_ram_hold,
  input          sigFromSrams_bore_2_ram_bypass,
  input          sigFromSrams_bore_2_ram_bp_clken,
  input          sigFromSrams_bore_2_ram_aux_clk,
  input          sigFromSrams_bore_2_ram_aux_ckbp,
  input          sigFromSrams_bore_2_ram_mcp_hold,
  input          sigFromSrams_bore_2_cgen,
  input          sigFromSrams_bore_3_ram_hold,
  input          sigFromSrams_bore_3_ram_bypass,
  input          sigFromSrams_bore_3_ram_bp_clken,
  input          sigFromSrams_bore_3_ram_aux_clk,
  input          sigFromSrams_bore_3_ram_aux_ckbp,
  input          sigFromSrams_bore_3_ram_mcp_hold,
  input          sigFromSrams_bore_3_cgen,
  input          sigFromSrams_bore_4_ram_hold,
  input          sigFromSrams_bore_4_ram_bypass,
  input          sigFromSrams_bore_4_ram_bp_clken,
  input          sigFromSrams_bore_4_ram_aux_clk,
  input          sigFromSrams_bore_4_ram_aux_ckbp,
  input          sigFromSrams_bore_4_ram_mcp_hold,
  input          sigFromSrams_bore_4_cgen,
  input          sigFromSrams_bore_5_ram_hold,
  input          sigFromSrams_bore_5_ram_bypass,
  input          sigFromSrams_bore_5_ram_bp_clken,
  input          sigFromSrams_bore_5_ram_aux_clk,
  input          sigFromSrams_bore_5_ram_aux_ckbp,
  input          sigFromSrams_bore_5_ram_mcp_hold,
  input          sigFromSrams_bore_5_cgen,
  input          sigFromSrams_bore_6_ram_hold,
  input          sigFromSrams_bore_6_ram_bypass,
  input          sigFromSrams_bore_6_ram_bp_clken,
  input          sigFromSrams_bore_6_ram_aux_clk,
  input          sigFromSrams_bore_6_ram_aux_ckbp,
  input          sigFromSrams_bore_6_ram_mcp_hold,
  input          sigFromSrams_bore_6_cgen,
  input          sigFromSrams_bore_7_ram_hold,
  input          sigFromSrams_bore_7_ram_bypass,
  input          sigFromSrams_bore_7_ram_bp_clken,
  input          sigFromSrams_bore_7_ram_aux_clk,
  input          sigFromSrams_bore_7_ram_aux_ckbp,
  input          sigFromSrams_bore_7_ram_mcp_hold,
  input          sigFromSrams_bore_7_cgen,
  input          sigFromSrams_bore_8_ram_hold,
  input          sigFromSrams_bore_8_ram_bypass,
  input          sigFromSrams_bore_8_ram_bp_clken,
  input          sigFromSrams_bore_8_ram_aux_clk,
  input          sigFromSrams_bore_8_ram_aux_ckbp,
  input          sigFromSrams_bore_8_ram_mcp_hold,
  input          sigFromSrams_bore_8_cgen,
  input          sigFromSrams_bore_9_ram_hold,
  input          sigFromSrams_bore_9_ram_bypass,
  input          sigFromSrams_bore_9_ram_bp_clken,
  input          sigFromSrams_bore_9_ram_aux_clk,
  input          sigFromSrams_bore_9_ram_aux_ckbp,
  input          sigFromSrams_bore_9_ram_mcp_hold,
  input          sigFromSrams_bore_9_cgen,
  input          sigFromSrams_bore_10_ram_hold,
  input          sigFromSrams_bore_10_ram_bypass,
  input          sigFromSrams_bore_10_ram_bp_clken,
  input          sigFromSrams_bore_10_ram_aux_clk,
  input          sigFromSrams_bore_10_ram_aux_ckbp,
  input          sigFromSrams_bore_10_ram_mcp_hold,
  input          sigFromSrams_bore_10_cgen,
  input          sigFromSrams_bore_11_ram_hold,
  input          sigFromSrams_bore_11_ram_bypass,
  input          sigFromSrams_bore_11_ram_bp_clken,
  input          sigFromSrams_bore_11_ram_aux_clk,
  input          sigFromSrams_bore_11_ram_aux_ckbp,
  input          sigFromSrams_bore_11_ram_mcp_hold,
  input          sigFromSrams_bore_11_cgen,
  input          sigFromSrams_bore_12_ram_hold,
  input          sigFromSrams_bore_12_ram_bypass,
  input          sigFromSrams_bore_12_ram_bp_clken,
  input          sigFromSrams_bore_12_ram_aux_clk,
  input          sigFromSrams_bore_12_ram_aux_ckbp,
  input          sigFromSrams_bore_12_ram_mcp_hold,
  input          sigFromSrams_bore_12_cgen,
  input          sigFromSrams_bore_13_ram_hold,
  input          sigFromSrams_bore_13_ram_bypass,
  input          sigFromSrams_bore_13_ram_bp_clken,
  input          sigFromSrams_bore_13_ram_aux_clk,
  input          sigFromSrams_bore_13_ram_aux_ckbp,
  input          sigFromSrams_bore_13_ram_mcp_hold,
  input          sigFromSrams_bore_13_cgen,
  input          sigFromSrams_bore_14_ram_hold,
  input          sigFromSrams_bore_14_ram_bypass,
  input          sigFromSrams_bore_14_ram_bp_clken,
  input          sigFromSrams_bore_14_ram_aux_clk,
  input          sigFromSrams_bore_14_ram_aux_ckbp,
  input          sigFromSrams_bore_14_ram_mcp_hold,
  input          sigFromSrams_bore_14_cgen,
  input          sigFromSrams_bore_15_ram_hold,
  input          sigFromSrams_bore_15_ram_bypass,
  input          sigFromSrams_bore_15_ram_bp_clken,
  input          sigFromSrams_bore_15_ram_aux_clk,
  input          sigFromSrams_bore_15_ram_aux_ckbp,
  input          sigFromSrams_bore_15_ram_mcp_hold,
  input          sigFromSrams_bore_15_cgen,
  input          sigFromSrams_bore_16_ram_hold,
  input          sigFromSrams_bore_16_ram_bypass,
  input          sigFromSrams_bore_16_ram_bp_clken,
  input          sigFromSrams_bore_16_ram_aux_clk,
  input          sigFromSrams_bore_16_ram_aux_ckbp,
  input          sigFromSrams_bore_16_ram_mcp_hold,
  input          sigFromSrams_bore_16_cgen,
  input          sigFromSrams_bore_17_ram_hold,
  input          sigFromSrams_bore_17_ram_bypass,
  input          sigFromSrams_bore_17_ram_bp_clken,
  input          sigFromSrams_bore_17_ram_aux_clk,
  input          sigFromSrams_bore_17_ram_aux_ckbp,
  input          sigFromSrams_bore_17_ram_mcp_hold,
  input          sigFromSrams_bore_17_cgen,
  input          sigFromSrams_bore_18_ram_hold,
  input          sigFromSrams_bore_18_ram_bypass,
  input          sigFromSrams_bore_18_ram_bp_clken,
  input          sigFromSrams_bore_18_ram_aux_clk,
  input          sigFromSrams_bore_18_ram_aux_ckbp,
  input          sigFromSrams_bore_18_ram_mcp_hold,
  input          sigFromSrams_bore_18_cgen,
  input          sigFromSrams_bore_19_ram_hold,
  input          sigFromSrams_bore_19_ram_bypass,
  input          sigFromSrams_bore_19_ram_bp_clken,
  input          sigFromSrams_bore_19_ram_aux_clk,
  input          sigFromSrams_bore_19_ram_aux_ckbp,
  input          sigFromSrams_bore_19_ram_mcp_hold,
  input          sigFromSrams_bore_19_cgen,
  input          sigFromSrams_bore_20_ram_hold,
  input          sigFromSrams_bore_20_ram_bypass,
  input          sigFromSrams_bore_20_ram_bp_clken,
  input          sigFromSrams_bore_20_ram_aux_clk,
  input          sigFromSrams_bore_20_ram_aux_ckbp,
  input          sigFromSrams_bore_20_ram_mcp_hold,
  input          sigFromSrams_bore_20_cgen,
  input          sigFromSrams_bore_21_ram_hold,
  input          sigFromSrams_bore_21_ram_bypass,
  input          sigFromSrams_bore_21_ram_bp_clken,
  input          sigFromSrams_bore_21_ram_aux_clk,
  input          sigFromSrams_bore_21_ram_aux_ckbp,
  input          sigFromSrams_bore_21_ram_mcp_hold,
  input          sigFromSrams_bore_21_cgen,
  input          sigFromSrams_bore_22_ram_hold,
  input          sigFromSrams_bore_22_ram_bypass,
  input          sigFromSrams_bore_22_ram_bp_clken,
  input          sigFromSrams_bore_22_ram_aux_clk,
  input          sigFromSrams_bore_22_ram_aux_ckbp,
  input          sigFromSrams_bore_22_ram_mcp_hold,
  input          sigFromSrams_bore_22_cgen,
  input          sigFromSrams_bore_23_ram_hold,
  input          sigFromSrams_bore_23_ram_bypass,
  input          sigFromSrams_bore_23_ram_bp_clken,
  input          sigFromSrams_bore_23_ram_aux_clk,
  input          sigFromSrams_bore_23_ram_aux_ckbp,
  input          sigFromSrams_bore_23_ram_mcp_hold,
  input          sigFromSrams_bore_23_cgen,
  input          sigFromSrams_bore_24_ram_hold,
  input          sigFromSrams_bore_24_ram_bypass,
  input          sigFromSrams_bore_24_ram_bp_clken,
  input          sigFromSrams_bore_24_ram_aux_clk,
  input          sigFromSrams_bore_24_ram_aux_ckbp,
  input          sigFromSrams_bore_24_ram_mcp_hold,
  input          sigFromSrams_bore_24_cgen,
  input          sigFromSrams_bore_25_ram_hold,
  input          sigFromSrams_bore_25_ram_bypass,
  input          sigFromSrams_bore_25_ram_bp_clken,
  input          sigFromSrams_bore_25_ram_aux_clk,
  input          sigFromSrams_bore_25_ram_aux_ckbp,
  input          sigFromSrams_bore_25_ram_mcp_hold,
  input          sigFromSrams_bore_25_cgen
);
endmodule

module ITTage(
  input          clock,
  input          reset,
  input  [47:0]  io_reset_vector,
  input  [49:0]  io_in_bits_s0_pc_0,
  input  [49:0]  io_in_bits_s0_pc_1,
  input  [49:0]  io_in_bits_s0_pc_2,
  input  [49:0]  io_in_bits_s0_pc_3,
  input  [7:0]   io_in_bits_s1_folded_hist_3_hist_14_folded_hist,
  input  [8:0]   io_in_bits_s1_folded_hist_3_hist_13_folded_hist,
  input  [3:0]   io_in_bits_s1_folded_hist_3_hist_12_folded_hist,
  input  [8:0]   io_in_bits_s1_folded_hist_3_hist_10_folded_hist,
  input  [8:0]   io_in_bits_s1_folded_hist_3_hist_6_folded_hist,
  input  [7:0]   io_in_bits_s1_folded_hist_3_hist_4_folded_hist,
  input  [7:0]   io_in_bits_s1_folded_hist_3_hist_3_folded_hist,
  input  [7:0]   io_in_bits_s1_folded_hist_3_hist_2_folded_hist,
  input          io_in_bits_resp_in_0_s2_full_pred_0_br_taken_mask_0,
  input          io_in_bits_resp_in_0_s2_full_pred_0_br_taken_mask_1,
  input          io_in_bits_resp_in_0_s2_full_pred_0_slot_valids_0,
  input          io_in_bits_resp_in_0_s2_full_pred_0_slot_valids_1,
  input  [49:0]  io_in_bits_resp_in_0_s2_full_pred_0_targets_0,
  input  [49:0]  io_in_bits_resp_in_0_s2_full_pred_0_targets_1,
  input  [49:0]  io_in_bits_resp_in_0_s2_full_pred_0_jalr_target,
  input  [3:0]   io_in_bits_resp_in_0_s2_full_pred_0_offsets_0,
  input  [3:0]   io_in_bits_resp_in_0_s2_full_pred_0_offsets_1,
  input  [49:0]  io_in_bits_resp_in_0_s2_full_pred_0_fallThroughAddr,
  input          io_in_bits_resp_in_0_s2_full_pred_0_fallThroughErr,
  input          io_in_bits_resp_in_0_s2_full_pred_0_is_jal,
  input          io_in_bits_resp_in_0_s2_full_pred_0_is_jalr,
  input          io_in_bits_resp_in_0_s2_full_pred_0_is_call,
  input          io_in_bits_resp_in_0_s2_full_pred_0_is_ret,
  input          io_in_bits_resp_in_0_s2_full_pred_0_last_may_be_rvi_call,
  input          io_in_bits_resp_in_0_s2_full_pred_0_is_br_sharing,
  input          io_in_bits_resp_in_0_s2_full_pred_0_hit,
  input          io_in_bits_resp_in_0_s2_full_pred_1_br_taken_mask_0,
  input          io_in_bits_resp_in_0_s2_full_pred_1_br_taken_mask_1,
  input          io_in_bits_resp_in_0_s2_full_pred_1_slot_valids_0,
  input          io_in_bits_resp_in_0_s2_full_pred_1_slot_valids_1,
  input  [49:0]  io_in_bits_resp_in_0_s2_full_pred_1_targets_0,
  input  [49:0]  io_in_bits_resp_in_0_s2_full_pred_1_targets_1,
  input  [49:0]  io_in_bits_resp_in_0_s2_full_pred_1_jalr_target,
  input  [3:0]   io_in_bits_resp_in_0_s2_full_pred_1_offsets_0,
  input  [3:0]   io_in_bits_resp_in_0_s2_full_pred_1_offsets_1,
  input  [49:0]  io_in_bits_resp_in_0_s2_full_pred_1_fallThroughAddr,
  input          io_in_bits_resp_in_0_s2_full_pred_1_fallThroughErr,
  input          io_in_bits_resp_in_0_s2_full_pred_1_is_jal,
  input          io_in_bits_resp_in_0_s2_full_pred_1_is_jalr,
  input          io_in_bits_resp_in_0_s2_full_pred_1_is_call,
  input          io_in_bits_resp_in_0_s2_full_pred_1_is_ret,
  input          io_in_bits_resp_in_0_s2_full_pred_1_last_may_be_rvi_call,
  input          io_in_bits_resp_in_0_s2_full_pred_1_is_br_sharing,
  input          io_in_bits_resp_in_0_s2_full_pred_1_hit,
  input          io_in_bits_resp_in_0_s2_full_pred_2_br_taken_mask_0,
  input          io_in_bits_resp_in_0_s2_full_pred_2_br_taken_mask_1,
  input          io_in_bits_resp_in_0_s2_full_pred_2_slot_valids_0,
  input          io_in_bits_resp_in_0_s2_full_pred_2_slot_valids_1,
  input  [49:0]  io_in_bits_resp_in_0_s2_full_pred_2_targets_0,
  input  [49:0]  io_in_bits_resp_in_0_s2_full_pred_2_targets_1,
  input  [49:0]  io_in_bits_resp_in_0_s2_full_pred_2_jalr_target,
  input  [3:0]   io_in_bits_resp_in_0_s2_full_pred_2_offsets_0,
  input  [3:0]   io_in_bits_resp_in_0_s2_full_pred_2_offsets_1,
  input  [49:0]  io_in_bits_resp_in_0_s2_full_pred_2_fallThroughAddr,
  input          io_in_bits_resp_in_0_s2_full_pred_2_fallThroughErr,
  input          io_in_bits_resp_in_0_s2_full_pred_2_is_jal,
  input          io_in_bits_resp_in_0_s2_full_pred_2_is_jalr,
  input          io_in_bits_resp_in_0_s2_full_pred_2_is_call,
  input          io_in_bits_resp_in_0_s2_full_pred_2_is_ret,
  input          io_in_bits_resp_in_0_s2_full_pred_2_last_may_be_rvi_call,
  input          io_in_bits_resp_in_0_s2_full_pred_2_is_br_sharing,
  input          io_in_bits_resp_in_0_s2_full_pred_2_hit,
  input          io_in_bits_resp_in_0_s2_full_pred_3_br_taken_mask_0,
  input          io_in_bits_resp_in_0_s2_full_pred_3_br_taken_mask_1,
  input          io_in_bits_resp_in_0_s2_full_pred_3_slot_valids_0,
  input          io_in_bits_resp_in_0_s2_full_pred_3_slot_valids_1,
  input  [49:0]  io_in_bits_resp_in_0_s2_full_pred_3_targets_0,
  input  [49:0]  io_in_bits_resp_in_0_s2_full_pred_3_targets_1,
  input  [49:0]  io_in_bits_resp_in_0_s2_full_pred_3_jalr_target,
  input  [3:0]   io_in_bits_resp_in_0_s2_full_pred_3_offsets_0,
  input  [3:0]   io_in_bits_resp_in_0_s2_full_pred_3_offsets_1,
  input  [49:0]  io_in_bits_resp_in_0_s2_full_pred_3_fallThroughAddr,
  input          io_in_bits_resp_in_0_s2_full_pred_3_fallThroughErr,
  input          io_in_bits_resp_in_0_s2_full_pred_3_is_jal,
  input          io_in_bits_resp_in_0_s2_full_pred_3_is_jalr,
  input          io_in_bits_resp_in_0_s2_full_pred_3_is_call,
  input          io_in_bits_resp_in_0_s2_full_pred_3_is_ret,
  input          io_in_bits_resp_in_0_s2_full_pred_3_last_may_be_rvi_call,
  input          io_in_bits_resp_in_0_s2_full_pred_3_is_br_sharing,
  input          io_in_bits_resp_in_0_s2_full_pred_3_hit,
  input          io_in_bits_resp_in_0_s3_full_pred_0_br_taken_mask_0,
  input          io_in_bits_resp_in_0_s3_full_pred_0_br_taken_mask_1,
  input          io_in_bits_resp_in_0_s3_full_pred_0_slot_valids_0,
  input          io_in_bits_resp_in_0_s3_full_pred_0_slot_valids_1,
  input  [49:0]  io_in_bits_resp_in_0_s3_full_pred_0_targets_0,
  input  [49:0]  io_in_bits_resp_in_0_s3_full_pred_0_targets_1,
  input  [3:0]   io_in_bits_resp_in_0_s3_full_pred_0_offsets_0,
  input  [3:0]   io_in_bits_resp_in_0_s3_full_pred_0_offsets_1,
  input  [49:0]  io_in_bits_resp_in_0_s3_full_pred_0_fallThroughAddr,
  input          io_in_bits_resp_in_0_s3_full_pred_0_fallThroughErr,
  input          io_in_bits_resp_in_0_s3_full_pred_0_multiHit,
  input          io_in_bits_resp_in_0_s3_full_pred_0_is_jal,
  input          io_in_bits_resp_in_0_s3_full_pred_0_is_jalr,
  input          io_in_bits_resp_in_0_s3_full_pred_0_is_call,
  input          io_in_bits_resp_in_0_s3_full_pred_0_is_ret,
  input          io_in_bits_resp_in_0_s3_full_pred_0_last_may_be_rvi_call,
  input          io_in_bits_resp_in_0_s3_full_pred_0_is_br_sharing,
  input          io_in_bits_resp_in_0_s3_full_pred_0_hit,
  input          io_in_bits_resp_in_0_s3_full_pred_1_br_taken_mask_0,
  input          io_in_bits_resp_in_0_s3_full_pred_1_br_taken_mask_1,
  input          io_in_bits_resp_in_0_s3_full_pred_1_slot_valids_0,
  input          io_in_bits_resp_in_0_s3_full_pred_1_slot_valids_1,
  input  [49:0]  io_in_bits_resp_in_0_s3_full_pred_1_targets_0,
  input  [49:0]  io_in_bits_resp_in_0_s3_full_pred_1_targets_1,
  input  [3:0]   io_in_bits_resp_in_0_s3_full_pred_1_offsets_0,
  input  [3:0]   io_in_bits_resp_in_0_s3_full_pred_1_offsets_1,
  input  [49:0]  io_in_bits_resp_in_0_s3_full_pred_1_fallThroughAddr,
  input          io_in_bits_resp_in_0_s3_full_pred_1_fallThroughErr,
  input          io_in_bits_resp_in_0_s3_full_pred_1_multiHit,
  input          io_in_bits_resp_in_0_s3_full_pred_1_is_jal,
  input          io_in_bits_resp_in_0_s3_full_pred_1_is_jalr,
  input          io_in_bits_resp_in_0_s3_full_pred_1_is_call,
  input          io_in_bits_resp_in_0_s3_full_pred_1_is_ret,
  input          io_in_bits_resp_in_0_s3_full_pred_1_last_may_be_rvi_call,
  input          io_in_bits_resp_in_0_s3_full_pred_1_is_br_sharing,
  input          io_in_bits_resp_in_0_s3_full_pred_1_hit,
  input          io_in_bits_resp_in_0_s3_full_pred_2_br_taken_mask_0,
  input          io_in_bits_resp_in_0_s3_full_pred_2_br_taken_mask_1,
  input          io_in_bits_resp_in_0_s3_full_pred_2_slot_valids_0,
  input          io_in_bits_resp_in_0_s3_full_pred_2_slot_valids_1,
  input  [49:0]  io_in_bits_resp_in_0_s3_full_pred_2_targets_0,
  input  [49:0]  io_in_bits_resp_in_0_s3_full_pred_2_targets_1,
  input  [3:0]   io_in_bits_resp_in_0_s3_full_pred_2_offsets_0,
  input  [3:0]   io_in_bits_resp_in_0_s3_full_pred_2_offsets_1,
  input  [49:0]  io_in_bits_resp_in_0_s3_full_pred_2_fallThroughAddr,
  input          io_in_bits_resp_in_0_s3_full_pred_2_fallThroughErr,
  input          io_in_bits_resp_in_0_s3_full_pred_2_multiHit,
  input          io_in_bits_resp_in_0_s3_full_pred_2_is_jal,
  input          io_in_bits_resp_in_0_s3_full_pred_2_is_jalr,
  input          io_in_bits_resp_in_0_s3_full_pred_2_is_call,
  input          io_in_bits_resp_in_0_s3_full_pred_2_is_ret,
  input          io_in_bits_resp_in_0_s3_full_pred_2_last_may_be_rvi_call,
  input          io_in_bits_resp_in_0_s3_full_pred_2_is_br_sharing,
  input          io_in_bits_resp_in_0_s3_full_pred_2_hit,
  input          io_in_bits_resp_in_0_s3_full_pred_3_br_taken_mask_0,
  input          io_in_bits_resp_in_0_s3_full_pred_3_br_taken_mask_1,
  input          io_in_bits_resp_in_0_s3_full_pred_3_slot_valids_0,
  input          io_in_bits_resp_in_0_s3_full_pred_3_slot_valids_1,
  input  [49:0]  io_in_bits_resp_in_0_s3_full_pred_3_targets_0,
  input  [49:0]  io_in_bits_resp_in_0_s3_full_pred_3_targets_1,
  input  [3:0]   io_in_bits_resp_in_0_s3_full_pred_3_offsets_0,
  input  [3:0]   io_in_bits_resp_in_0_s3_full_pred_3_offsets_1,
  input  [49:0]  io_in_bits_resp_in_0_s3_full_pred_3_fallThroughAddr,
  input          io_in_bits_resp_in_0_s3_full_pred_3_fallThroughErr,
  input          io_in_bits_resp_in_0_s3_full_pred_3_multiHit,
  input          io_in_bits_resp_in_0_s3_full_pred_3_is_jal,
  input          io_in_bits_resp_in_0_s3_full_pred_3_is_jalr,
  input          io_in_bits_resp_in_0_s3_full_pred_3_is_call,
  input          io_in_bits_resp_in_0_s3_full_pred_3_is_ret,
  input          io_in_bits_resp_in_0_s3_full_pred_3_last_may_be_rvi_call,
  input          io_in_bits_resp_in_0_s3_full_pred_3_is_br_sharing,
  input          io_in_bits_resp_in_0_s3_full_pred_3_hit,
  input          io_in_bits_resp_in_0_s1_uftbHit,
  input          io_in_bits_resp_in_0_s1_uftbHasIndirect,
  input          io_in_bits_resp_in_0_s1_ftbCloseReq,
  input          io_in_bits_resp_in_0_last_stage_spec_info_sc_disagree_0,
  input          io_in_bits_resp_in_0_last_stage_spec_info_sc_disagree_1,
  input          io_in_bits_resp_in_0_last_stage_ftb_entry_isCall,
  input          io_in_bits_resp_in_0_last_stage_ftb_entry_isRet,
  input          io_in_bits_resp_in_0_last_stage_ftb_entry_isJalr,
  input          io_in_bits_resp_in_0_last_stage_ftb_entry_valid,
  input  [3:0]   io_in_bits_resp_in_0_last_stage_ftb_entry_brSlots_0_offset,
  input          io_in_bits_resp_in_0_last_stage_ftb_entry_brSlots_0_sharing,
  input          io_in_bits_resp_in_0_last_stage_ftb_entry_brSlots_0_valid,
  input  [11:0]  io_in_bits_resp_in_0_last_stage_ftb_entry_brSlots_0_lower,
  input  [1:0]   io_in_bits_resp_in_0_last_stage_ftb_entry_brSlots_0_tarStat,
  input  [3:0]   io_in_bits_resp_in_0_last_stage_ftb_entry_tailSlot_offset,
  input          io_in_bits_resp_in_0_last_stage_ftb_entry_tailSlot_sharing,
  input          io_in_bits_resp_in_0_last_stage_ftb_entry_tailSlot_valid,
  input  [19:0]  io_in_bits_resp_in_0_last_stage_ftb_entry_tailSlot_lower,
  input  [1:0]   io_in_bits_resp_in_0_last_stage_ftb_entry_tailSlot_tarStat,
  input  [3:0]   io_in_bits_resp_in_0_last_stage_ftb_entry_pftAddr,
  input          io_in_bits_resp_in_0_last_stage_ftb_entry_carry,
  input          io_in_bits_resp_in_0_last_stage_ftb_entry_last_may_be_rvi_call,
  input          io_in_bits_resp_in_0_last_stage_ftb_entry_strong_bias_0,
  input          io_in_bits_resp_in_0_last_stage_ftb_entry_strong_bias_1,
  output         io_out_s2_full_pred_0_br_taken_mask_0,
  output         io_out_s2_full_pred_0_br_taken_mask_1,
  output         io_out_s2_full_pred_0_slot_valids_0,
  output         io_out_s2_full_pred_0_slot_valids_1,
  output [49:0]  io_out_s2_full_pred_0_targets_0,
  output [49:0]  io_out_s2_full_pred_0_targets_1,
  output [49:0]  io_out_s2_full_pred_0_jalr_target,
  output [3:0]   io_out_s2_full_pred_0_offsets_0,
  output [3:0]   io_out_s2_full_pred_0_offsets_1,
  output [49:0]  io_out_s2_full_pred_0_fallThroughAddr,
  output         io_out_s2_full_pred_0_fallThroughErr,
  output         io_out_s2_full_pred_0_is_jal,
  output         io_out_s2_full_pred_0_is_jalr,
  output         io_out_s2_full_pred_0_is_call,
  output         io_out_s2_full_pred_0_is_ret,
  output         io_out_s2_full_pred_0_last_may_be_rvi_call,
  output         io_out_s2_full_pred_0_is_br_sharing,
  output         io_out_s2_full_pred_0_hit,
  output         io_out_s2_full_pred_1_br_taken_mask_0,
  output         io_out_s2_full_pred_1_br_taken_mask_1,
  output         io_out_s2_full_pred_1_slot_valids_0,
  output         io_out_s2_full_pred_1_slot_valids_1,
  output [49:0]  io_out_s2_full_pred_1_targets_0,
  output [49:0]  io_out_s2_full_pred_1_targets_1,
  output [49:0]  io_out_s2_full_pred_1_jalr_target,
  output [3:0]   io_out_s2_full_pred_1_offsets_0,
  output [3:0]   io_out_s2_full_pred_1_offsets_1,
  output [49:0]  io_out_s2_full_pred_1_fallThroughAddr,
  output         io_out_s2_full_pred_1_fallThroughErr,
  output         io_out_s2_full_pred_1_is_jal,
  output         io_out_s2_full_pred_1_is_jalr,
  output         io_out_s2_full_pred_1_is_call,
  output         io_out_s2_full_pred_1_is_ret,
  output         io_out_s2_full_pred_1_last_may_be_rvi_call,
  output         io_out_s2_full_pred_1_is_br_sharing,
  output         io_out_s2_full_pred_1_hit,
  output         io_out_s2_full_pred_2_br_taken_mask_0,
  output         io_out_s2_full_pred_2_br_taken_mask_1,
  output         io_out_s2_full_pred_2_slot_valids_0,
  output         io_out_s2_full_pred_2_slot_valids_1,
  output [49:0]  io_out_s2_full_pred_2_targets_0,
  output [49:0]  io_out_s2_full_pred_2_targets_1,
  output [49:0]  io_out_s2_full_pred_2_jalr_target,
  output [3:0]   io_out_s2_full_pred_2_offsets_0,
  output [3:0]   io_out_s2_full_pred_2_offsets_1,
  output [49:0]  io_out_s2_full_pred_2_fallThroughAddr,
  output         io_out_s2_full_pred_2_fallThroughErr,
  output         io_out_s2_full_pred_2_is_jal,
  output         io_out_s2_full_pred_2_is_jalr,
  output         io_out_s2_full_pred_2_is_call,
  output         io_out_s2_full_pred_2_is_ret,
  output         io_out_s2_full_pred_2_last_may_be_rvi_call,
  output         io_out_s2_full_pred_2_is_br_sharing,
  output         io_out_s2_full_pred_2_hit,
  output         io_out_s2_full_pred_3_br_taken_mask_0,
  output         io_out_s2_full_pred_3_br_taken_mask_1,
  output         io_out_s2_full_pred_3_slot_valids_0,
  output         io_out_s2_full_pred_3_slot_valids_1,
  output [49:0]  io_out_s2_full_pred_3_targets_0,
  output [49:0]  io_out_s2_full_pred_3_targets_1,
  output [49:0]  io_out_s2_full_pred_3_jalr_target,
  output [3:0]   io_out_s2_full_pred_3_offsets_0,
  output [3:0]   io_out_s2_full_pred_3_offsets_1,
  output [49:0]  io_out_s2_full_pred_3_fallThroughAddr,
  output         io_out_s2_full_pred_3_fallThroughErr,
  output         io_out_s2_full_pred_3_is_jal,
  output         io_out_s2_full_pred_3_is_jalr,
  output         io_out_s2_full_pred_3_is_call,
  output         io_out_s2_full_pred_3_is_ret,
  output         io_out_s2_full_pred_3_last_may_be_rvi_call,
  output         io_out_s2_full_pred_3_is_br_sharing,
  output         io_out_s2_full_pred_3_hit,
  output         io_out_s3_full_pred_0_br_taken_mask_0,
  output         io_out_s3_full_pred_0_br_taken_mask_1,
  output         io_out_s3_full_pred_0_slot_valids_0,
  output         io_out_s3_full_pred_0_slot_valids_1,
  output [49:0]  io_out_s3_full_pred_0_targets_0,
  output [49:0]  io_out_s3_full_pred_0_targets_1,
  output [49:0]  io_out_s3_full_pred_0_jalr_target,
  output [3:0]   io_out_s3_full_pred_0_offsets_0,
  output [3:0]   io_out_s3_full_pred_0_offsets_1,
  output [49:0]  io_out_s3_full_pred_0_fallThroughAddr,
  output         io_out_s3_full_pred_0_fallThroughErr,
  output         io_out_s3_full_pred_0_multiHit,
  output         io_out_s3_full_pred_0_is_jal,
  output         io_out_s3_full_pred_0_is_jalr,
  output         io_out_s3_full_pred_0_is_call,
  output         io_out_s3_full_pred_0_is_ret,
  output         io_out_s3_full_pred_0_last_may_be_rvi_call,
  output         io_out_s3_full_pred_0_is_br_sharing,
  output         io_out_s3_full_pred_0_hit,
  output         io_out_s3_full_pred_1_br_taken_mask_0,
  output         io_out_s3_full_pred_1_br_taken_mask_1,
  output         io_out_s3_full_pred_1_slot_valids_0,
  output         io_out_s3_full_pred_1_slot_valids_1,
  output [49:0]  io_out_s3_full_pred_1_targets_0,
  output [49:0]  io_out_s3_full_pred_1_targets_1,
  output [49:0]  io_out_s3_full_pred_1_jalr_target,
  output [3:0]   io_out_s3_full_pred_1_offsets_0,
  output [3:0]   io_out_s3_full_pred_1_offsets_1,
  output [49:0]  io_out_s3_full_pred_1_fallThroughAddr,
  output         io_out_s3_full_pred_1_fallThroughErr,
  output         io_out_s3_full_pred_1_multiHit,
  output         io_out_s3_full_pred_1_is_jal,
  output         io_out_s3_full_pred_1_is_jalr,
  output         io_out_s3_full_pred_1_is_call,
  output         io_out_s3_full_pred_1_is_ret,
  output         io_out_s3_full_pred_1_last_may_be_rvi_call,
  output         io_out_s3_full_pred_1_is_br_sharing,
  output         io_out_s3_full_pred_1_hit,
  output         io_out_s3_full_pred_2_br_taken_mask_0,
  output         io_out_s3_full_pred_2_br_taken_mask_1,
  output         io_out_s3_full_pred_2_slot_valids_0,
  output         io_out_s3_full_pred_2_slot_valids_1,
  output [49:0]  io_out_s3_full_pred_2_targets_0,
  output [49:0]  io_out_s3_full_pred_2_targets_1,
  output [49:0]  io_out_s3_full_pred_2_jalr_target,
  output [3:0]   io_out_s3_full_pred_2_offsets_0,
  output [3:0]   io_out_s3_full_pred_2_offsets_1,
  output [49:0]  io_out_s3_full_pred_2_fallThroughAddr,
  output         io_out_s3_full_pred_2_fallThroughErr,
  output         io_out_s3_full_pred_2_multiHit,
  output         io_out_s3_full_pred_2_is_jal,
  output         io_out_s3_full_pred_2_is_jalr,
  output         io_out_s3_full_pred_2_is_call,
  output         io_out_s3_full_pred_2_is_ret,
  output         io_out_s3_full_pred_2_last_may_be_rvi_call,
  output         io_out_s3_full_pred_2_is_br_sharing,
  output         io_out_s3_full_pred_2_hit,
  output         io_out_s3_full_pred_3_br_taken_mask_0,
  output         io_out_s3_full_pred_3_br_taken_mask_1,
  output         io_out_s3_full_pred_3_slot_valids_0,
  output         io_out_s3_full_pred_3_slot_valids_1,
  output [49:0]  io_out_s3_full_pred_3_targets_0,
  output [49:0]  io_out_s3_full_pred_3_targets_1,
  output [49:0]  io_out_s3_full_pred_3_jalr_target,
  output [3:0]   io_out_s3_full_pred_3_offsets_0,
  output [3:0]   io_out_s3_full_pred_3_offsets_1,
  output [49:0]  io_out_s3_full_pred_3_fallThroughAddr,
  output         io_out_s3_full_pred_3_fallThroughErr,
  output         io_out_s3_full_pred_3_multiHit,
  output         io_out_s3_full_pred_3_is_jal,
  output         io_out_s3_full_pred_3_is_jalr,
  output         io_out_s3_full_pred_3_is_call,
  output         io_out_s3_full_pred_3_is_ret,
  output         io_out_s3_full_pred_3_last_may_be_rvi_call,
  output         io_out_s3_full_pred_3_is_br_sharing,
  output         io_out_s3_full_pred_3_hit,
  output [515:0] io_out_last_stage_meta,
  output         io_out_last_stage_spec_info_sc_disagree_0,
  output         io_out_last_stage_spec_info_sc_disagree_1,
  output         io_out_last_stage_ftb_entry_isCall,
  output         io_out_last_stage_ftb_entry_isRet,
  output         io_out_last_stage_ftb_entry_isJalr,
  output         io_out_last_stage_ftb_entry_valid,
  output [3:0]   io_out_last_stage_ftb_entry_brSlots_0_offset,
  output         io_out_last_stage_ftb_entry_brSlots_0_sharing,
  output         io_out_last_stage_ftb_entry_brSlots_0_valid,
  output [11:0]  io_out_last_stage_ftb_entry_brSlots_0_lower,
  output [1:0]   io_out_last_stage_ftb_entry_brSlots_0_tarStat,
  output [3:0]   io_out_last_stage_ftb_entry_tailSlot_offset,
  output         io_out_last_stage_ftb_entry_tailSlot_sharing,
  output         io_out_last_stage_ftb_entry_tailSlot_valid,
  output [19:0]  io_out_last_stage_ftb_entry_tailSlot_lower,
  output [1:0]   io_out_last_stage_ftb_entry_tailSlot_tarStat,
  output [3:0]   io_out_last_stage_ftb_entry_pftAddr,
  output         io_out_last_stage_ftb_entry_carry,
  output         io_out_last_stage_ftb_entry_last_may_be_rvi_call,
  output         io_out_last_stage_ftb_entry_strong_bias_0,
  output         io_out_last_stage_ftb_entry_strong_bias_1,
  input          io_s0_fire_0,
  input          io_s0_fire_1,
  input          io_s0_fire_2,
  input          io_s0_fire_3,
  input          io_s1_fire_0,
  input          io_s1_fire_1,
  input          io_s1_fire_2,
  input          io_s1_fire_3,
  input          io_s2_fire_0,
  input          io_s2_fire_1,
  input          io_s2_fire_2,
  input          io_s2_fire_3,
  output         io_s1_ready,
  input          io_update_valid,
  input  [49:0]  io_update_bits_pc,
  input          io_update_bits_ftb_entry_isRet,
  input          io_update_bits_ftb_entry_isJalr,
  input  [3:0]   io_update_bits_ftb_entry_tailSlot_offset,
  input          io_update_bits_ftb_entry_tailSlot_sharing,
  input          io_update_bits_ftb_entry_tailSlot_valid,
  input          io_update_bits_ftb_entry_strong_bias_1,
  input          io_update_bits_cfi_idx_valid,
  input  [3:0]   io_update_bits_cfi_idx_bits,
  input          io_update_bits_jmp_taken,
  input          io_update_bits_mispred_mask_2,
  input  [515:0] io_update_bits_meta,
  input  [49:0]  io_update_bits_full_target,
  input  [255:0] io_update_bits_ghist,
  input  [6:0]   boreChildrenBd_bore_array,
  input          boreChildrenBd_bore_all,
  input          boreChildrenBd_bore_req,
  output         boreChildrenBd_bore_ack,
  input          boreChildrenBd_bore_writeen,
  input  [75:0]  boreChildrenBd_bore_be,
  input  [7:0]   boreChildrenBd_bore_addr,
  input  [75:0]  boreChildrenBd_bore_indata,
  input          boreChildrenBd_bore_readen,
  input  [7:0]   boreChildrenBd_bore_addr_rd,
  output [75:0]  boreChildrenBd_bore_outdata,
  input  [6:0]   boreChildrenBd_bore_1_array,
  input          boreChildrenBd_bore_1_all,
  input          boreChildrenBd_bore_1_req,
  output         boreChildrenBd_bore_1_ack,
  input          boreChildrenBd_bore_1_writeen,
  input  [75:0]  boreChildrenBd_bore_1_be,
  input  [7:0]   boreChildrenBd_bore_1_addr,
  input  [75:0]  boreChildrenBd_bore_1_indata,
  input          boreChildrenBd_bore_1_readen,
  input  [7:0]   boreChildrenBd_bore_1_addr_rd,
  output [75:0]  boreChildrenBd_bore_1_outdata,
  input  [6:0]   boreChildrenBd_bore_2_array,
  input          boreChildrenBd_bore_2_all,
  input          boreChildrenBd_bore_2_req,
  output         boreChildrenBd_bore_2_ack,
  input          boreChildrenBd_bore_2_writeen,
  input  [75:0]  boreChildrenBd_bore_2_be,
  input  [7:0]   boreChildrenBd_bore_2_addr,
  input  [75:0]  boreChildrenBd_bore_2_indata,
  input          boreChildrenBd_bore_2_readen,
  input  [7:0]   boreChildrenBd_bore_2_addr_rd,
  output [75:0]  boreChildrenBd_bore_2_outdata,
  input  [6:0]   boreChildrenBd_bore_3_array,
  input          boreChildrenBd_bore_3_all,
  input          boreChildrenBd_bore_3_req,
  output         boreChildrenBd_bore_3_ack,
  input          boreChildrenBd_bore_3_writeen,
  input  [75:0]  boreChildrenBd_bore_3_be,
  input  [7:0]   boreChildrenBd_bore_3_addr,
  input  [75:0]  boreChildrenBd_bore_3_indata,
  input          boreChildrenBd_bore_3_readen,
  input  [7:0]   boreChildrenBd_bore_3_addr_rd,
  output [75:0]  boreChildrenBd_bore_3_outdata,
  input  [6:0]   boreChildrenBd_bore_4_array,
  input          boreChildrenBd_bore_4_all,
  input          boreChildrenBd_bore_4_req,
  output         boreChildrenBd_bore_4_ack,
  input          boreChildrenBd_bore_4_writeen,
  input  [75:0]  boreChildrenBd_bore_4_be,
  input  [7:0]   boreChildrenBd_bore_4_addr,
  input  [75:0]  boreChildrenBd_bore_4_indata,
  input          boreChildrenBd_bore_4_readen,
  input  [7:0]   boreChildrenBd_bore_4_addr_rd,
  output [75:0]  boreChildrenBd_bore_4_outdata,
  input          sigFromSrams_bore_ram_hold,
  input          sigFromSrams_bore_ram_bypass,
  input          sigFromSrams_bore_ram_bp_clken,
  input          sigFromSrams_bore_ram_aux_clk,
  input          sigFromSrams_bore_ram_aux_ckbp,
  input          sigFromSrams_bore_ram_mcp_hold,
  input          sigFromSrams_bore_cgen,
  input          sigFromSrams_bore_1_ram_hold,
  input          sigFromSrams_bore_1_ram_bypass,
  input          sigFromSrams_bore_1_ram_bp_clken,
  input          sigFromSrams_bore_1_ram_aux_clk,
  input          sigFromSrams_bore_1_ram_aux_ckbp,
  input          sigFromSrams_bore_1_ram_mcp_hold,
  input          sigFromSrams_bore_1_cgen,
  input          sigFromSrams_bore_2_ram_hold,
  input          sigFromSrams_bore_2_ram_bypass,
  input          sigFromSrams_bore_2_ram_bp_clken,
  input          sigFromSrams_bore_2_ram_aux_clk,
  input          sigFromSrams_bore_2_ram_aux_ckbp,
  input          sigFromSrams_bore_2_ram_mcp_hold,
  input          sigFromSrams_bore_2_cgen,
  input          sigFromSrams_bore_3_ram_hold,
  input          sigFromSrams_bore_3_ram_bypass,
  input          sigFromSrams_bore_3_ram_bp_clken,
  input          sigFromSrams_bore_3_ram_aux_clk,
  input          sigFromSrams_bore_3_ram_aux_ckbp,
  input          sigFromSrams_bore_3_ram_mcp_hold,
  input          sigFromSrams_bore_3_cgen,
  input          sigFromSrams_bore_4_ram_hold,
  input          sigFromSrams_bore_4_ram_bypass,
  input          sigFromSrams_bore_4_ram_bp_clken,
  input          sigFromSrams_bore_4_ram_aux_clk,
  input          sigFromSrams_bore_4_ram_aux_ckbp,
  input          sigFromSrams_bore_4_ram_mcp_hold,
  input          sigFromSrams_bore_4_cgen,
  input          sigFromSrams_bore_5_ram_hold,
  input          sigFromSrams_bore_5_ram_bypass,
  input          sigFromSrams_bore_5_ram_bp_clken,
  input          sigFromSrams_bore_5_ram_aux_clk,
  input          sigFromSrams_bore_5_ram_aux_ckbp,
  input          sigFromSrams_bore_5_ram_mcp_hold,
  input          sigFromSrams_bore_5_cgen,
  input          sigFromSrams_bore_6_ram_hold,
  input          sigFromSrams_bore_6_ram_bypass,
  input          sigFromSrams_bore_6_ram_bp_clken,
  input          sigFromSrams_bore_6_ram_aux_clk,
  input          sigFromSrams_bore_6_ram_aux_ckbp,
  input          sigFromSrams_bore_6_ram_mcp_hold,
  input          sigFromSrams_bore_6_cgen,
  input          sigFromSrams_bore_7_ram_hold,
  input          sigFromSrams_bore_7_ram_bypass,
  input          sigFromSrams_bore_7_ram_bp_clken,
  input          sigFromSrams_bore_7_ram_aux_clk,
  input          sigFromSrams_bore_7_ram_aux_ckbp,
  input          sigFromSrams_bore_7_ram_mcp_hold,
  input          sigFromSrams_bore_7_cgen
);
endmodule

