MODULE = FauFTBWay

RTL_DIR = ../../../rtl
GOLDEN_RTL = ../../../golden/chisel-rtl

RTL_SRCS = $(RTL_DIR)/frontend/FauFTBWay.sv
WRAPPER_SRCS = $(RTL_DIR)/frontend/FauFTBWay_wrapper.sv
GOLDEN_SRCS = $(GOLDEN_RTL)/FauFTBWay.sv
TB_SRCS = variants_xs.sv tb.sv

FM_VARIANTS = FauFTBWay

include ../../../scripts/ut_common.mk
