// 自动生成：scripts/gen_ctrlblock.py —— 勿手改(逻辑部分为从 Scala 意图的可读重写)

// 入队装包:NewDispatch 黑盒输出 _dispatch_io_enqRob_req_<i>_* -> enqInValid[i]/enqInBits[i]。
// 这些 _dispatch_* 网由 ctrlblock_inst.svh 例化 NewDispatch 时绑定,这里先声明。
// snapshot 仅第 0 路有效;exceptionVec_<n> 按位填 23 位向量。

  // -- NewDispatch enqRob 输出网(黑盒,inst.svh 绑定)--
  logic _dispatch_io_enqRob_req_0_bits_blockBackward;
  logic [2:0] _dispatch_io_enqRob_req_0_bits_commitType;
  logic _dispatch_io_enqRob_req_0_bits_crossPageIPFFix;
  logic [63:0] _dispatch_io_enqRob_req_0_bits_debugInfo_renameTime;
  logic _dispatch_io_enqRob_req_0_bits_dirtyFs;
  logic _dispatch_io_enqRob_req_0_bits_dirtyVs;
  logic _dispatch_io_enqRob_req_0_bits_eliminatedMove;
  logic _dispatch_io_enqRob_req_0_bits_exceptionVec_0;
  logic _dispatch_io_enqRob_req_0_bits_exceptionVec_1;
  logic _dispatch_io_enqRob_req_0_bits_exceptionVec_12;
  logic _dispatch_io_enqRob_req_0_bits_exceptionVec_2;
  logic _dispatch_io_enqRob_req_0_bits_exceptionVec_20;
  logic _dispatch_io_enqRob_req_0_bits_exceptionVec_22;
  logic _dispatch_io_enqRob_req_0_bits_exceptionVec_3;
  logic _dispatch_io_enqRob_req_0_bits_firstUop;
  logic _dispatch_io_enqRob_req_0_bits_flushPipe;
  logic _dispatch_io_enqRob_req_0_bits_fpWen;
  logic [3:0] _dispatch_io_enqRob_req_0_bits_ftqOffset;
  logic _dispatch_io_enqRob_req_0_bits_ftqPtr_flag;
  logic [5:0] _dispatch_io_enqRob_req_0_bits_ftqPtr_value;
  logic [8:0] _dispatch_io_enqRob_req_0_bits_fuOpType;
  logic [34:0] _dispatch_io_enqRob_req_0_bits_fuType;
  logic _dispatch_io_enqRob_req_0_bits_hasException;
  logic [31:0] _dispatch_io_enqRob_req_0_bits_instr;
  logic [2:0] _dispatch_io_enqRob_req_0_bits_instrSize;
  logic _dispatch_io_enqRob_req_0_bits_isFetchMalAddr;
  logic _dispatch_io_enqRob_req_0_bits_isMove;
  logic _dispatch_io_enqRob_req_0_bits_isVset;
  logic _dispatch_io_enqRob_req_0_bits_isXSTrap;
  logic _dispatch_io_enqRob_req_0_bits_lastUop;
  logic [5:0] _dispatch_io_enqRob_req_0_bits_ldest;
  logic [6:0] _dispatch_io_enqRob_req_0_bits_numWB;
  logic [7:0] _dispatch_io_enqRob_req_0_bits_pdest;
  logic _dispatch_io_enqRob_req_0_bits_preDecodeInfo_isRVC;
  logic _dispatch_io_enqRob_req_0_bits_rfWen;
  logic _dispatch_io_enqRob_req_0_bits_robIdx_flag;
  logic [7:0] _dispatch_io_enqRob_req_0_bits_robIdx_value;
  logic _dispatch_io_enqRob_req_0_bits_singleStep;
  logic _dispatch_io_enqRob_req_0_bits_snapshot;
  logic _dispatch_io_enqRob_req_0_bits_traceBlockInPipe_ilastsize;
  logic [3:0] _dispatch_io_enqRob_req_0_bits_traceBlockInPipe_iretire;
  logic [3:0] _dispatch_io_enqRob_req_0_bits_traceBlockInPipe_itype;
  logic [3:0] _dispatch_io_enqRob_req_0_bits_trigger;
  logic _dispatch_io_enqRob_req_0_bits_v0Wen;
  logic _dispatch_io_enqRob_req_0_bits_vecWen;
  logic _dispatch_io_enqRob_req_0_bits_vlWen;
  logic _dispatch_io_enqRob_req_0_bits_vlsInstr;
  logic _dispatch_io_enqRob_req_0_bits_vpu_specVill;
  logic [2:0] _dispatch_io_enqRob_req_0_bits_vpu_specVlmul;
  logic _dispatch_io_enqRob_req_0_bits_vpu_specVma;
  logic [1:0] _dispatch_io_enqRob_req_0_bits_vpu_specVsew;
  logic _dispatch_io_enqRob_req_0_bits_vpu_specVta;
  logic _dispatch_io_enqRob_req_0_bits_vpu_vill;
  logic [2:0] _dispatch_io_enqRob_req_0_bits_vpu_vlmul;
  logic _dispatch_io_enqRob_req_0_bits_vpu_vma;
  logic [1:0] _dispatch_io_enqRob_req_0_bits_vpu_vsew;
  logic _dispatch_io_enqRob_req_0_bits_vpu_vta;
  logic _dispatch_io_enqRob_req_0_bits_waitForward;
  logic _dispatch_io_enqRob_req_0_bits_wfflags;
  logic _dispatch_io_enqRob_req_0_valid;
  logic _dispatch_io_enqRob_req_1_bits_blockBackward;
  logic [2:0] _dispatch_io_enqRob_req_1_bits_commitType;
  logic _dispatch_io_enqRob_req_1_bits_crossPageIPFFix;
  logic [63:0] _dispatch_io_enqRob_req_1_bits_debugInfo_renameTime;
  logic _dispatch_io_enqRob_req_1_bits_dirtyFs;
  logic _dispatch_io_enqRob_req_1_bits_dirtyVs;
  logic _dispatch_io_enqRob_req_1_bits_eliminatedMove;
  logic _dispatch_io_enqRob_req_1_bits_exceptionVec_0;
  logic _dispatch_io_enqRob_req_1_bits_exceptionVec_1;
  logic _dispatch_io_enqRob_req_1_bits_exceptionVec_12;
  logic _dispatch_io_enqRob_req_1_bits_exceptionVec_2;
  logic _dispatch_io_enqRob_req_1_bits_exceptionVec_20;
  logic _dispatch_io_enqRob_req_1_bits_exceptionVec_22;
  logic _dispatch_io_enqRob_req_1_bits_exceptionVec_3;
  logic _dispatch_io_enqRob_req_1_bits_firstUop;
  logic _dispatch_io_enqRob_req_1_bits_flushPipe;
  logic _dispatch_io_enqRob_req_1_bits_fpWen;
  logic [3:0] _dispatch_io_enqRob_req_1_bits_ftqOffset;
  logic _dispatch_io_enqRob_req_1_bits_ftqPtr_flag;
  logic [5:0] _dispatch_io_enqRob_req_1_bits_ftqPtr_value;
  logic [8:0] _dispatch_io_enqRob_req_1_bits_fuOpType;
  logic [34:0] _dispatch_io_enqRob_req_1_bits_fuType;
  logic _dispatch_io_enqRob_req_1_bits_hasException;
  logic [31:0] _dispatch_io_enqRob_req_1_bits_instr;
  logic [2:0] _dispatch_io_enqRob_req_1_bits_instrSize;
  logic _dispatch_io_enqRob_req_1_bits_isFetchMalAddr;
  logic _dispatch_io_enqRob_req_1_bits_isMove;
  logic _dispatch_io_enqRob_req_1_bits_isVset;
  logic _dispatch_io_enqRob_req_1_bits_isXSTrap;
  logic _dispatch_io_enqRob_req_1_bits_lastUop;
  logic [5:0] _dispatch_io_enqRob_req_1_bits_ldest;
  logic [6:0] _dispatch_io_enqRob_req_1_bits_numWB;
  logic [7:0] _dispatch_io_enqRob_req_1_bits_pdest;
  logic _dispatch_io_enqRob_req_1_bits_preDecodeInfo_isRVC;
  logic _dispatch_io_enqRob_req_1_bits_rfWen;
  logic _dispatch_io_enqRob_req_1_bits_robIdx_flag;
  logic [7:0] _dispatch_io_enqRob_req_1_bits_robIdx_value;
  logic _dispatch_io_enqRob_req_1_bits_singleStep;
  logic _dispatch_io_enqRob_req_1_bits_traceBlockInPipe_ilastsize;
  logic [3:0] _dispatch_io_enqRob_req_1_bits_traceBlockInPipe_iretire;
  logic [3:0] _dispatch_io_enqRob_req_1_bits_traceBlockInPipe_itype;
  logic [3:0] _dispatch_io_enqRob_req_1_bits_trigger;
  logic _dispatch_io_enqRob_req_1_bits_v0Wen;
  logic _dispatch_io_enqRob_req_1_bits_vecWen;
  logic _dispatch_io_enqRob_req_1_bits_vlWen;
  logic _dispatch_io_enqRob_req_1_bits_vlsInstr;
  logic _dispatch_io_enqRob_req_1_bits_vpu_specVill;
  logic [2:0] _dispatch_io_enqRob_req_1_bits_vpu_specVlmul;
  logic _dispatch_io_enqRob_req_1_bits_vpu_specVma;
  logic [1:0] _dispatch_io_enqRob_req_1_bits_vpu_specVsew;
  logic _dispatch_io_enqRob_req_1_bits_vpu_specVta;
  logic _dispatch_io_enqRob_req_1_bits_vpu_vill;
  logic [2:0] _dispatch_io_enqRob_req_1_bits_vpu_vlmul;
  logic _dispatch_io_enqRob_req_1_bits_vpu_vma;
  logic [1:0] _dispatch_io_enqRob_req_1_bits_vpu_vsew;
  logic _dispatch_io_enqRob_req_1_bits_vpu_vta;
  logic _dispatch_io_enqRob_req_1_bits_waitForward;
  logic _dispatch_io_enqRob_req_1_bits_wfflags;
  logic _dispatch_io_enqRob_req_1_valid;
  logic _dispatch_io_enqRob_req_2_bits_blockBackward;
  logic [2:0] _dispatch_io_enqRob_req_2_bits_commitType;
  logic _dispatch_io_enqRob_req_2_bits_crossPageIPFFix;
  logic [63:0] _dispatch_io_enqRob_req_2_bits_debugInfo_renameTime;
  logic _dispatch_io_enqRob_req_2_bits_dirtyFs;
  logic _dispatch_io_enqRob_req_2_bits_dirtyVs;
  logic _dispatch_io_enqRob_req_2_bits_eliminatedMove;
  logic _dispatch_io_enqRob_req_2_bits_exceptionVec_0;
  logic _dispatch_io_enqRob_req_2_bits_exceptionVec_1;
  logic _dispatch_io_enqRob_req_2_bits_exceptionVec_12;
  logic _dispatch_io_enqRob_req_2_bits_exceptionVec_2;
  logic _dispatch_io_enqRob_req_2_bits_exceptionVec_20;
  logic _dispatch_io_enqRob_req_2_bits_exceptionVec_22;
  logic _dispatch_io_enqRob_req_2_bits_exceptionVec_3;
  logic _dispatch_io_enqRob_req_2_bits_firstUop;
  logic _dispatch_io_enqRob_req_2_bits_flushPipe;
  logic _dispatch_io_enqRob_req_2_bits_fpWen;
  logic [3:0] _dispatch_io_enqRob_req_2_bits_ftqOffset;
  logic _dispatch_io_enqRob_req_2_bits_ftqPtr_flag;
  logic [5:0] _dispatch_io_enqRob_req_2_bits_ftqPtr_value;
  logic [8:0] _dispatch_io_enqRob_req_2_bits_fuOpType;
  logic [34:0] _dispatch_io_enqRob_req_2_bits_fuType;
  logic _dispatch_io_enqRob_req_2_bits_hasException;
  logic [31:0] _dispatch_io_enqRob_req_2_bits_instr;
  logic [2:0] _dispatch_io_enqRob_req_2_bits_instrSize;
  logic _dispatch_io_enqRob_req_2_bits_isFetchMalAddr;
  logic _dispatch_io_enqRob_req_2_bits_isMove;
  logic _dispatch_io_enqRob_req_2_bits_isVset;
  logic _dispatch_io_enqRob_req_2_bits_isXSTrap;
  logic _dispatch_io_enqRob_req_2_bits_lastUop;
  logic [5:0] _dispatch_io_enqRob_req_2_bits_ldest;
  logic [6:0] _dispatch_io_enqRob_req_2_bits_numWB;
  logic [7:0] _dispatch_io_enqRob_req_2_bits_pdest;
  logic _dispatch_io_enqRob_req_2_bits_preDecodeInfo_isRVC;
  logic _dispatch_io_enqRob_req_2_bits_rfWen;
  logic _dispatch_io_enqRob_req_2_bits_robIdx_flag;
  logic [7:0] _dispatch_io_enqRob_req_2_bits_robIdx_value;
  logic _dispatch_io_enqRob_req_2_bits_singleStep;
  logic _dispatch_io_enqRob_req_2_bits_traceBlockInPipe_ilastsize;
  logic [3:0] _dispatch_io_enqRob_req_2_bits_traceBlockInPipe_iretire;
  logic [3:0] _dispatch_io_enqRob_req_2_bits_traceBlockInPipe_itype;
  logic [3:0] _dispatch_io_enqRob_req_2_bits_trigger;
  logic _dispatch_io_enqRob_req_2_bits_v0Wen;
  logic _dispatch_io_enqRob_req_2_bits_vecWen;
  logic _dispatch_io_enqRob_req_2_bits_vlWen;
  logic _dispatch_io_enqRob_req_2_bits_vlsInstr;
  logic _dispatch_io_enqRob_req_2_bits_vpu_specVill;
  logic [2:0] _dispatch_io_enqRob_req_2_bits_vpu_specVlmul;
  logic _dispatch_io_enqRob_req_2_bits_vpu_specVma;
  logic [1:0] _dispatch_io_enqRob_req_2_bits_vpu_specVsew;
  logic _dispatch_io_enqRob_req_2_bits_vpu_specVta;
  logic _dispatch_io_enqRob_req_2_bits_vpu_vill;
  logic [2:0] _dispatch_io_enqRob_req_2_bits_vpu_vlmul;
  logic _dispatch_io_enqRob_req_2_bits_vpu_vma;
  logic [1:0] _dispatch_io_enqRob_req_2_bits_vpu_vsew;
  logic _dispatch_io_enqRob_req_2_bits_vpu_vta;
  logic _dispatch_io_enqRob_req_2_bits_waitForward;
  logic _dispatch_io_enqRob_req_2_bits_wfflags;
  logic _dispatch_io_enqRob_req_2_valid;
  logic _dispatch_io_enqRob_req_3_bits_blockBackward;
  logic [2:0] _dispatch_io_enqRob_req_3_bits_commitType;
  logic _dispatch_io_enqRob_req_3_bits_crossPageIPFFix;
  logic [63:0] _dispatch_io_enqRob_req_3_bits_debugInfo_renameTime;
  logic _dispatch_io_enqRob_req_3_bits_dirtyFs;
  logic _dispatch_io_enqRob_req_3_bits_dirtyVs;
  logic _dispatch_io_enqRob_req_3_bits_eliminatedMove;
  logic _dispatch_io_enqRob_req_3_bits_exceptionVec_0;
  logic _dispatch_io_enqRob_req_3_bits_exceptionVec_1;
  logic _dispatch_io_enqRob_req_3_bits_exceptionVec_12;
  logic _dispatch_io_enqRob_req_3_bits_exceptionVec_2;
  logic _dispatch_io_enqRob_req_3_bits_exceptionVec_20;
  logic _dispatch_io_enqRob_req_3_bits_exceptionVec_22;
  logic _dispatch_io_enqRob_req_3_bits_exceptionVec_3;
  logic _dispatch_io_enqRob_req_3_bits_firstUop;
  logic _dispatch_io_enqRob_req_3_bits_flushPipe;
  logic _dispatch_io_enqRob_req_3_bits_fpWen;
  logic [3:0] _dispatch_io_enqRob_req_3_bits_ftqOffset;
  logic _dispatch_io_enqRob_req_3_bits_ftqPtr_flag;
  logic [5:0] _dispatch_io_enqRob_req_3_bits_ftqPtr_value;
  logic [8:0] _dispatch_io_enqRob_req_3_bits_fuOpType;
  logic [34:0] _dispatch_io_enqRob_req_3_bits_fuType;
  logic _dispatch_io_enqRob_req_3_bits_hasException;
  logic [31:0] _dispatch_io_enqRob_req_3_bits_instr;
  logic [2:0] _dispatch_io_enqRob_req_3_bits_instrSize;
  logic _dispatch_io_enqRob_req_3_bits_isFetchMalAddr;
  logic _dispatch_io_enqRob_req_3_bits_isMove;
  logic _dispatch_io_enqRob_req_3_bits_isVset;
  logic _dispatch_io_enqRob_req_3_bits_isXSTrap;
  logic _dispatch_io_enqRob_req_3_bits_lastUop;
  logic [5:0] _dispatch_io_enqRob_req_3_bits_ldest;
  logic [6:0] _dispatch_io_enqRob_req_3_bits_numWB;
  logic [7:0] _dispatch_io_enqRob_req_3_bits_pdest;
  logic _dispatch_io_enqRob_req_3_bits_preDecodeInfo_isRVC;
  logic _dispatch_io_enqRob_req_3_bits_rfWen;
  logic _dispatch_io_enqRob_req_3_bits_robIdx_flag;
  logic [7:0] _dispatch_io_enqRob_req_3_bits_robIdx_value;
  logic _dispatch_io_enqRob_req_3_bits_singleStep;
  logic _dispatch_io_enqRob_req_3_bits_traceBlockInPipe_ilastsize;
  logic [3:0] _dispatch_io_enqRob_req_3_bits_traceBlockInPipe_iretire;
  logic [3:0] _dispatch_io_enqRob_req_3_bits_traceBlockInPipe_itype;
  logic [3:0] _dispatch_io_enqRob_req_3_bits_trigger;
  logic _dispatch_io_enqRob_req_3_bits_v0Wen;
  logic _dispatch_io_enqRob_req_3_bits_vecWen;
  logic _dispatch_io_enqRob_req_3_bits_vlWen;
  logic _dispatch_io_enqRob_req_3_bits_vlsInstr;
  logic _dispatch_io_enqRob_req_3_bits_vpu_specVill;
  logic [2:0] _dispatch_io_enqRob_req_3_bits_vpu_specVlmul;
  logic _dispatch_io_enqRob_req_3_bits_vpu_specVma;
  logic [1:0] _dispatch_io_enqRob_req_3_bits_vpu_specVsew;
  logic _dispatch_io_enqRob_req_3_bits_vpu_specVta;
  logic _dispatch_io_enqRob_req_3_bits_vpu_vill;
  logic [2:0] _dispatch_io_enqRob_req_3_bits_vpu_vlmul;
  logic _dispatch_io_enqRob_req_3_bits_vpu_vma;
  logic [1:0] _dispatch_io_enqRob_req_3_bits_vpu_vsew;
  logic _dispatch_io_enqRob_req_3_bits_vpu_vta;
  logic _dispatch_io_enqRob_req_3_bits_waitForward;
  logic _dispatch_io_enqRob_req_3_bits_wfflags;
  logic _dispatch_io_enqRob_req_3_valid;
  logic _dispatch_io_enqRob_req_4_bits_blockBackward;
  logic [2:0] _dispatch_io_enqRob_req_4_bits_commitType;
  logic _dispatch_io_enqRob_req_4_bits_crossPageIPFFix;
  logic [63:0] _dispatch_io_enqRob_req_4_bits_debugInfo_renameTime;
  logic _dispatch_io_enqRob_req_4_bits_dirtyFs;
  logic _dispatch_io_enqRob_req_4_bits_dirtyVs;
  logic _dispatch_io_enqRob_req_4_bits_eliminatedMove;
  logic _dispatch_io_enqRob_req_4_bits_exceptionVec_0;
  logic _dispatch_io_enqRob_req_4_bits_exceptionVec_1;
  logic _dispatch_io_enqRob_req_4_bits_exceptionVec_12;
  logic _dispatch_io_enqRob_req_4_bits_exceptionVec_2;
  logic _dispatch_io_enqRob_req_4_bits_exceptionVec_20;
  logic _dispatch_io_enqRob_req_4_bits_exceptionVec_22;
  logic _dispatch_io_enqRob_req_4_bits_exceptionVec_3;
  logic _dispatch_io_enqRob_req_4_bits_firstUop;
  logic _dispatch_io_enqRob_req_4_bits_flushPipe;
  logic _dispatch_io_enqRob_req_4_bits_fpWen;
  logic [3:0] _dispatch_io_enqRob_req_4_bits_ftqOffset;
  logic _dispatch_io_enqRob_req_4_bits_ftqPtr_flag;
  logic [5:0] _dispatch_io_enqRob_req_4_bits_ftqPtr_value;
  logic [8:0] _dispatch_io_enqRob_req_4_bits_fuOpType;
  logic [34:0] _dispatch_io_enqRob_req_4_bits_fuType;
  logic _dispatch_io_enqRob_req_4_bits_hasException;
  logic [31:0] _dispatch_io_enqRob_req_4_bits_instr;
  logic [2:0] _dispatch_io_enqRob_req_4_bits_instrSize;
  logic _dispatch_io_enqRob_req_4_bits_isFetchMalAddr;
  logic _dispatch_io_enqRob_req_4_bits_isMove;
  logic _dispatch_io_enqRob_req_4_bits_isVset;
  logic _dispatch_io_enqRob_req_4_bits_isXSTrap;
  logic _dispatch_io_enqRob_req_4_bits_lastUop;
  logic [5:0] _dispatch_io_enqRob_req_4_bits_ldest;
  logic [6:0] _dispatch_io_enqRob_req_4_bits_numWB;
  logic [7:0] _dispatch_io_enqRob_req_4_bits_pdest;
  logic _dispatch_io_enqRob_req_4_bits_preDecodeInfo_isRVC;
  logic _dispatch_io_enqRob_req_4_bits_rfWen;
  logic _dispatch_io_enqRob_req_4_bits_robIdx_flag;
  logic [7:0] _dispatch_io_enqRob_req_4_bits_robIdx_value;
  logic _dispatch_io_enqRob_req_4_bits_singleStep;
  logic _dispatch_io_enqRob_req_4_bits_traceBlockInPipe_ilastsize;
  logic [3:0] _dispatch_io_enqRob_req_4_bits_traceBlockInPipe_iretire;
  logic [3:0] _dispatch_io_enqRob_req_4_bits_traceBlockInPipe_itype;
  logic [3:0] _dispatch_io_enqRob_req_4_bits_trigger;
  logic _dispatch_io_enqRob_req_4_bits_v0Wen;
  logic _dispatch_io_enqRob_req_4_bits_vecWen;
  logic _dispatch_io_enqRob_req_4_bits_vlWen;
  logic _dispatch_io_enqRob_req_4_bits_vlsInstr;
  logic _dispatch_io_enqRob_req_4_bits_vpu_specVill;
  logic [2:0] _dispatch_io_enqRob_req_4_bits_vpu_specVlmul;
  logic _dispatch_io_enqRob_req_4_bits_vpu_specVma;
  logic [1:0] _dispatch_io_enqRob_req_4_bits_vpu_specVsew;
  logic _dispatch_io_enqRob_req_4_bits_vpu_specVta;
  logic _dispatch_io_enqRob_req_4_bits_vpu_vill;
  logic [2:0] _dispatch_io_enqRob_req_4_bits_vpu_vlmul;
  logic _dispatch_io_enqRob_req_4_bits_vpu_vma;
  logic [1:0] _dispatch_io_enqRob_req_4_bits_vpu_vsew;
  logic _dispatch_io_enqRob_req_4_bits_vpu_vta;
  logic _dispatch_io_enqRob_req_4_bits_waitForward;
  logic _dispatch_io_enqRob_req_4_bits_wfflags;
  logic _dispatch_io_enqRob_req_4_valid;
  logic _dispatch_io_enqRob_req_5_bits_blockBackward;
  logic [2:0] _dispatch_io_enqRob_req_5_bits_commitType;
  logic _dispatch_io_enqRob_req_5_bits_crossPageIPFFix;
  logic [63:0] _dispatch_io_enqRob_req_5_bits_debugInfo_renameTime;
  logic _dispatch_io_enqRob_req_5_bits_dirtyFs;
  logic _dispatch_io_enqRob_req_5_bits_dirtyVs;
  logic _dispatch_io_enqRob_req_5_bits_eliminatedMove;
  logic _dispatch_io_enqRob_req_5_bits_exceptionVec_0;
  logic _dispatch_io_enqRob_req_5_bits_exceptionVec_1;
  logic _dispatch_io_enqRob_req_5_bits_exceptionVec_12;
  logic _dispatch_io_enqRob_req_5_bits_exceptionVec_2;
  logic _dispatch_io_enqRob_req_5_bits_exceptionVec_20;
  logic _dispatch_io_enqRob_req_5_bits_exceptionVec_22;
  logic _dispatch_io_enqRob_req_5_bits_exceptionVec_3;
  logic _dispatch_io_enqRob_req_5_bits_firstUop;
  logic _dispatch_io_enqRob_req_5_bits_flushPipe;
  logic _dispatch_io_enqRob_req_5_bits_fpWen;
  logic [3:0] _dispatch_io_enqRob_req_5_bits_ftqOffset;
  logic _dispatch_io_enqRob_req_5_bits_ftqPtr_flag;
  logic [5:0] _dispatch_io_enqRob_req_5_bits_ftqPtr_value;
  logic [8:0] _dispatch_io_enqRob_req_5_bits_fuOpType;
  logic [34:0] _dispatch_io_enqRob_req_5_bits_fuType;
  logic _dispatch_io_enqRob_req_5_bits_hasException;
  logic [31:0] _dispatch_io_enqRob_req_5_bits_instr;
  logic [2:0] _dispatch_io_enqRob_req_5_bits_instrSize;
  logic _dispatch_io_enqRob_req_5_bits_isFetchMalAddr;
  logic _dispatch_io_enqRob_req_5_bits_isMove;
  logic _dispatch_io_enqRob_req_5_bits_isVset;
  logic _dispatch_io_enqRob_req_5_bits_isXSTrap;
  logic _dispatch_io_enqRob_req_5_bits_lastUop;
  logic [5:0] _dispatch_io_enqRob_req_5_bits_ldest;
  logic [6:0] _dispatch_io_enqRob_req_5_bits_numWB;
  logic [7:0] _dispatch_io_enqRob_req_5_bits_pdest;
  logic _dispatch_io_enqRob_req_5_bits_preDecodeInfo_isRVC;
  logic _dispatch_io_enqRob_req_5_bits_rfWen;
  logic _dispatch_io_enqRob_req_5_bits_robIdx_flag;
  logic [7:0] _dispatch_io_enqRob_req_5_bits_robIdx_value;
  logic _dispatch_io_enqRob_req_5_bits_singleStep;
  logic _dispatch_io_enqRob_req_5_bits_traceBlockInPipe_ilastsize;
  logic [3:0] _dispatch_io_enqRob_req_5_bits_traceBlockInPipe_iretire;
  logic [3:0] _dispatch_io_enqRob_req_5_bits_traceBlockInPipe_itype;
  logic [3:0] _dispatch_io_enqRob_req_5_bits_trigger;
  logic _dispatch_io_enqRob_req_5_bits_v0Wen;
  logic _dispatch_io_enqRob_req_5_bits_vecWen;
  logic _dispatch_io_enqRob_req_5_bits_vlWen;
  logic _dispatch_io_enqRob_req_5_bits_vlsInstr;
  logic _dispatch_io_enqRob_req_5_bits_vpu_specVill;
  logic [2:0] _dispatch_io_enqRob_req_5_bits_vpu_specVlmul;
  logic _dispatch_io_enqRob_req_5_bits_vpu_specVma;
  logic [1:0] _dispatch_io_enqRob_req_5_bits_vpu_specVsew;
  logic _dispatch_io_enqRob_req_5_bits_vpu_specVta;
  logic _dispatch_io_enqRob_req_5_bits_vpu_vill;
  logic [2:0] _dispatch_io_enqRob_req_5_bits_vpu_vlmul;
  logic _dispatch_io_enqRob_req_5_bits_vpu_vma;
  logic [1:0] _dispatch_io_enqRob_req_5_bits_vpu_vsew;
  logic _dispatch_io_enqRob_req_5_bits_vpu_vta;
  logic _dispatch_io_enqRob_req_5_bits_waitForward;
  logic _dispatch_io_enqRob_req_5_bits_wfflags;
  logic _dispatch_io_enqRob_req_5_valid;

  assign enqInValid[0] = _dispatch_io_enqRob_req_0_valid;
  assign enqInValid[1] = _dispatch_io_enqRob_req_1_valid;
  assign enqInValid[2] = _dispatch_io_enqRob_req_2_valid;
  assign enqInValid[3] = _dispatch_io_enqRob_req_3_valid;
  assign enqInValid[4] = _dispatch_io_enqRob_req_4_valid;
  assign enqInValid[5] = _dispatch_io_enqRob_req_5_valid;
  always_comb begin
    enqInBits[0] = '{default:'0};
    enqInBits[1] = '{default:'0};
    enqInBits[2] = '{default:'0};
    enqInBits[3] = '{default:'0};
    enqInBits[4] = '{default:'0};
    enqInBits[5] = '{default:'0};
    // ---- enqRob.req[0] ----
    enqInBits[0].blockBackward = _dispatch_io_enqRob_req_0_bits_blockBackward;
    enqInBits[0].commitType = _dispatch_io_enqRob_req_0_bits_commitType;
    enqInBits[0].crossPageIPFFix = _dispatch_io_enqRob_req_0_bits_crossPageIPFFix;
    enqInBits[0].debugInfo_renameTime = _dispatch_io_enqRob_req_0_bits_debugInfo_renameTime;
    enqInBits[0].dirtyFs = _dispatch_io_enqRob_req_0_bits_dirtyFs;
    enqInBits[0].dirtyVs = _dispatch_io_enqRob_req_0_bits_dirtyVs;
    enqInBits[0].eliminatedMove = _dispatch_io_enqRob_req_0_bits_eliminatedMove;
    enqInBits[0].exceptionVec[0] = _dispatch_io_enqRob_req_0_bits_exceptionVec_0;
    enqInBits[0].exceptionVec[1] = _dispatch_io_enqRob_req_0_bits_exceptionVec_1;
    enqInBits[0].exceptionVec[12] = _dispatch_io_enqRob_req_0_bits_exceptionVec_12;
    enqInBits[0].exceptionVec[2] = _dispatch_io_enqRob_req_0_bits_exceptionVec_2;
    enqInBits[0].exceptionVec[20] = _dispatch_io_enqRob_req_0_bits_exceptionVec_20;
    enqInBits[0].exceptionVec[22] = _dispatch_io_enqRob_req_0_bits_exceptionVec_22;
    enqInBits[0].exceptionVec[3] = _dispatch_io_enqRob_req_0_bits_exceptionVec_3;
    enqInBits[0].firstUop = _dispatch_io_enqRob_req_0_bits_firstUop;
    enqInBits[0].flushPipe = _dispatch_io_enqRob_req_0_bits_flushPipe;
    enqInBits[0].fpWen = _dispatch_io_enqRob_req_0_bits_fpWen;
    enqInBits[0].ftqOffset = _dispatch_io_enqRob_req_0_bits_ftqOffset;
    enqInBits[0].ftqPtr_flag = _dispatch_io_enqRob_req_0_bits_ftqPtr_flag;
    enqInBits[0].ftqPtr_value = _dispatch_io_enqRob_req_0_bits_ftqPtr_value;
    enqInBits[0].fuOpType = _dispatch_io_enqRob_req_0_bits_fuOpType;
    enqInBits[0].fuType = _dispatch_io_enqRob_req_0_bits_fuType;
    enqInBits[0].hasException = _dispatch_io_enqRob_req_0_bits_hasException;
    enqInBits[0].instr = _dispatch_io_enqRob_req_0_bits_instr;
    enqInBits[0].instrSize = _dispatch_io_enqRob_req_0_bits_instrSize;
    enqInBits[0].isFetchMalAddr = _dispatch_io_enqRob_req_0_bits_isFetchMalAddr;
    enqInBits[0].isMove = _dispatch_io_enqRob_req_0_bits_isMove;
    enqInBits[0].isVset = _dispatch_io_enqRob_req_0_bits_isVset;
    enqInBits[0].isXSTrap = _dispatch_io_enqRob_req_0_bits_isXSTrap;
    enqInBits[0].lastUop = _dispatch_io_enqRob_req_0_bits_lastUop;
    enqInBits[0].ldest = _dispatch_io_enqRob_req_0_bits_ldest;
    enqInBits[0].numWB = _dispatch_io_enqRob_req_0_bits_numWB;
    enqInBits[0].pdest = _dispatch_io_enqRob_req_0_bits_pdest;
    enqInBits[0].preDecodeInfo_isRVC = _dispatch_io_enqRob_req_0_bits_preDecodeInfo_isRVC;
    enqInBits[0].rfWen = _dispatch_io_enqRob_req_0_bits_rfWen;
    enqInBits[0].robIdx_flag = _dispatch_io_enqRob_req_0_bits_robIdx_flag;
    enqInBits[0].robIdx_value = _dispatch_io_enqRob_req_0_bits_robIdx_value;
    enqInBits[0].singleStep = _dispatch_io_enqRob_req_0_bits_singleStep;
    enqInBits[0].snapshot = _dispatch_io_enqRob_req_0_bits_snapshot;
    enqInBits[0].traceBlockInPipe_ilastsize = _dispatch_io_enqRob_req_0_bits_traceBlockInPipe_ilastsize;
    enqInBits[0].traceBlockInPipe_iretire = _dispatch_io_enqRob_req_0_bits_traceBlockInPipe_iretire;
    enqInBits[0].traceBlockInPipe_itype = _dispatch_io_enqRob_req_0_bits_traceBlockInPipe_itype;
    enqInBits[0].trigger = _dispatch_io_enqRob_req_0_bits_trigger;
    enqInBits[0].v0Wen = _dispatch_io_enqRob_req_0_bits_v0Wen;
    enqInBits[0].vecWen = _dispatch_io_enqRob_req_0_bits_vecWen;
    enqInBits[0].vlWen = _dispatch_io_enqRob_req_0_bits_vlWen;
    enqInBits[0].vlsInstr = _dispatch_io_enqRob_req_0_bits_vlsInstr;
    enqInBits[0].vpu_specVill = _dispatch_io_enqRob_req_0_bits_vpu_specVill;
    enqInBits[0].vpu_specVlmul = _dispatch_io_enqRob_req_0_bits_vpu_specVlmul;
    enqInBits[0].vpu_specVma = _dispatch_io_enqRob_req_0_bits_vpu_specVma;
    enqInBits[0].vpu_specVsew = _dispatch_io_enqRob_req_0_bits_vpu_specVsew;
    enqInBits[0].vpu_specVta = _dispatch_io_enqRob_req_0_bits_vpu_specVta;
    enqInBits[0].vpu_vill = _dispatch_io_enqRob_req_0_bits_vpu_vill;
    enqInBits[0].vpu_vlmul = _dispatch_io_enqRob_req_0_bits_vpu_vlmul;
    enqInBits[0].vpu_vma = _dispatch_io_enqRob_req_0_bits_vpu_vma;
    enqInBits[0].vpu_vsew = _dispatch_io_enqRob_req_0_bits_vpu_vsew;
    enqInBits[0].vpu_vta = _dispatch_io_enqRob_req_0_bits_vpu_vta;
    enqInBits[0].waitForward = _dispatch_io_enqRob_req_0_bits_waitForward;
    enqInBits[0].wfflags = _dispatch_io_enqRob_req_0_bits_wfflags;
    // ---- enqRob.req[1] ----
    enqInBits[1].blockBackward = _dispatch_io_enqRob_req_1_bits_blockBackward;
    enqInBits[1].commitType = _dispatch_io_enqRob_req_1_bits_commitType;
    enqInBits[1].crossPageIPFFix = _dispatch_io_enqRob_req_1_bits_crossPageIPFFix;
    enqInBits[1].debugInfo_renameTime = _dispatch_io_enqRob_req_1_bits_debugInfo_renameTime;
    enqInBits[1].dirtyFs = _dispatch_io_enqRob_req_1_bits_dirtyFs;
    enqInBits[1].dirtyVs = _dispatch_io_enqRob_req_1_bits_dirtyVs;
    enqInBits[1].eliminatedMove = _dispatch_io_enqRob_req_1_bits_eliminatedMove;
    enqInBits[1].exceptionVec[0] = _dispatch_io_enqRob_req_1_bits_exceptionVec_0;
    enqInBits[1].exceptionVec[1] = _dispatch_io_enqRob_req_1_bits_exceptionVec_1;
    enqInBits[1].exceptionVec[12] = _dispatch_io_enqRob_req_1_bits_exceptionVec_12;
    enqInBits[1].exceptionVec[2] = _dispatch_io_enqRob_req_1_bits_exceptionVec_2;
    enqInBits[1].exceptionVec[20] = _dispatch_io_enqRob_req_1_bits_exceptionVec_20;
    enqInBits[1].exceptionVec[22] = _dispatch_io_enqRob_req_1_bits_exceptionVec_22;
    enqInBits[1].exceptionVec[3] = _dispatch_io_enqRob_req_1_bits_exceptionVec_3;
    enqInBits[1].firstUop = _dispatch_io_enqRob_req_1_bits_firstUop;
    enqInBits[1].flushPipe = _dispatch_io_enqRob_req_1_bits_flushPipe;
    enqInBits[1].fpWen = _dispatch_io_enqRob_req_1_bits_fpWen;
    enqInBits[1].ftqOffset = _dispatch_io_enqRob_req_1_bits_ftqOffset;
    enqInBits[1].ftqPtr_flag = _dispatch_io_enqRob_req_1_bits_ftqPtr_flag;
    enqInBits[1].ftqPtr_value = _dispatch_io_enqRob_req_1_bits_ftqPtr_value;
    enqInBits[1].fuOpType = _dispatch_io_enqRob_req_1_bits_fuOpType;
    enqInBits[1].fuType = _dispatch_io_enqRob_req_1_bits_fuType;
    enqInBits[1].hasException = _dispatch_io_enqRob_req_1_bits_hasException;
    enqInBits[1].instr = _dispatch_io_enqRob_req_1_bits_instr;
    enqInBits[1].instrSize = _dispatch_io_enqRob_req_1_bits_instrSize;
    enqInBits[1].isFetchMalAddr = _dispatch_io_enqRob_req_1_bits_isFetchMalAddr;
    enqInBits[1].isMove = _dispatch_io_enqRob_req_1_bits_isMove;
    enqInBits[1].isVset = _dispatch_io_enqRob_req_1_bits_isVset;
    enqInBits[1].isXSTrap = _dispatch_io_enqRob_req_1_bits_isXSTrap;
    enqInBits[1].lastUop = _dispatch_io_enqRob_req_1_bits_lastUop;
    enqInBits[1].ldest = _dispatch_io_enqRob_req_1_bits_ldest;
    enqInBits[1].numWB = _dispatch_io_enqRob_req_1_bits_numWB;
    enqInBits[1].pdest = _dispatch_io_enqRob_req_1_bits_pdest;
    enqInBits[1].preDecodeInfo_isRVC = _dispatch_io_enqRob_req_1_bits_preDecodeInfo_isRVC;
    enqInBits[1].rfWen = _dispatch_io_enqRob_req_1_bits_rfWen;
    enqInBits[1].robIdx_flag = _dispatch_io_enqRob_req_1_bits_robIdx_flag;
    enqInBits[1].robIdx_value = _dispatch_io_enqRob_req_1_bits_robIdx_value;
    enqInBits[1].singleStep = _dispatch_io_enqRob_req_1_bits_singleStep;
    enqInBits[1].traceBlockInPipe_ilastsize = _dispatch_io_enqRob_req_1_bits_traceBlockInPipe_ilastsize;
    enqInBits[1].traceBlockInPipe_iretire = _dispatch_io_enqRob_req_1_bits_traceBlockInPipe_iretire;
    enqInBits[1].traceBlockInPipe_itype = _dispatch_io_enqRob_req_1_bits_traceBlockInPipe_itype;
    enqInBits[1].trigger = _dispatch_io_enqRob_req_1_bits_trigger;
    enqInBits[1].v0Wen = _dispatch_io_enqRob_req_1_bits_v0Wen;
    enqInBits[1].vecWen = _dispatch_io_enqRob_req_1_bits_vecWen;
    enqInBits[1].vlWen = _dispatch_io_enqRob_req_1_bits_vlWen;
    enqInBits[1].vlsInstr = _dispatch_io_enqRob_req_1_bits_vlsInstr;
    enqInBits[1].vpu_specVill = _dispatch_io_enqRob_req_1_bits_vpu_specVill;
    enqInBits[1].vpu_specVlmul = _dispatch_io_enqRob_req_1_bits_vpu_specVlmul;
    enqInBits[1].vpu_specVma = _dispatch_io_enqRob_req_1_bits_vpu_specVma;
    enqInBits[1].vpu_specVsew = _dispatch_io_enqRob_req_1_bits_vpu_specVsew;
    enqInBits[1].vpu_specVta = _dispatch_io_enqRob_req_1_bits_vpu_specVta;
    enqInBits[1].vpu_vill = _dispatch_io_enqRob_req_1_bits_vpu_vill;
    enqInBits[1].vpu_vlmul = _dispatch_io_enqRob_req_1_bits_vpu_vlmul;
    enqInBits[1].vpu_vma = _dispatch_io_enqRob_req_1_bits_vpu_vma;
    enqInBits[1].vpu_vsew = _dispatch_io_enqRob_req_1_bits_vpu_vsew;
    enqInBits[1].vpu_vta = _dispatch_io_enqRob_req_1_bits_vpu_vta;
    enqInBits[1].waitForward = _dispatch_io_enqRob_req_1_bits_waitForward;
    enqInBits[1].wfflags = _dispatch_io_enqRob_req_1_bits_wfflags;
    // ---- enqRob.req[2] ----
    enqInBits[2].blockBackward = _dispatch_io_enqRob_req_2_bits_blockBackward;
    enqInBits[2].commitType = _dispatch_io_enqRob_req_2_bits_commitType;
    enqInBits[2].crossPageIPFFix = _dispatch_io_enqRob_req_2_bits_crossPageIPFFix;
    enqInBits[2].debugInfo_renameTime = _dispatch_io_enqRob_req_2_bits_debugInfo_renameTime;
    enqInBits[2].dirtyFs = _dispatch_io_enqRob_req_2_bits_dirtyFs;
    enqInBits[2].dirtyVs = _dispatch_io_enqRob_req_2_bits_dirtyVs;
    enqInBits[2].eliminatedMove = _dispatch_io_enqRob_req_2_bits_eliminatedMove;
    enqInBits[2].exceptionVec[0] = _dispatch_io_enqRob_req_2_bits_exceptionVec_0;
    enqInBits[2].exceptionVec[1] = _dispatch_io_enqRob_req_2_bits_exceptionVec_1;
    enqInBits[2].exceptionVec[12] = _dispatch_io_enqRob_req_2_bits_exceptionVec_12;
    enqInBits[2].exceptionVec[2] = _dispatch_io_enqRob_req_2_bits_exceptionVec_2;
    enqInBits[2].exceptionVec[20] = _dispatch_io_enqRob_req_2_bits_exceptionVec_20;
    enqInBits[2].exceptionVec[22] = _dispatch_io_enqRob_req_2_bits_exceptionVec_22;
    enqInBits[2].exceptionVec[3] = _dispatch_io_enqRob_req_2_bits_exceptionVec_3;
    enqInBits[2].firstUop = _dispatch_io_enqRob_req_2_bits_firstUop;
    enqInBits[2].flushPipe = _dispatch_io_enqRob_req_2_bits_flushPipe;
    enqInBits[2].fpWen = _dispatch_io_enqRob_req_2_bits_fpWen;
    enqInBits[2].ftqOffset = _dispatch_io_enqRob_req_2_bits_ftqOffset;
    enqInBits[2].ftqPtr_flag = _dispatch_io_enqRob_req_2_bits_ftqPtr_flag;
    enqInBits[2].ftqPtr_value = _dispatch_io_enqRob_req_2_bits_ftqPtr_value;
    enqInBits[2].fuOpType = _dispatch_io_enqRob_req_2_bits_fuOpType;
    enqInBits[2].fuType = _dispatch_io_enqRob_req_2_bits_fuType;
    enqInBits[2].hasException = _dispatch_io_enqRob_req_2_bits_hasException;
    enqInBits[2].instr = _dispatch_io_enqRob_req_2_bits_instr;
    enqInBits[2].instrSize = _dispatch_io_enqRob_req_2_bits_instrSize;
    enqInBits[2].isFetchMalAddr = _dispatch_io_enqRob_req_2_bits_isFetchMalAddr;
    enqInBits[2].isMove = _dispatch_io_enqRob_req_2_bits_isMove;
    enqInBits[2].isVset = _dispatch_io_enqRob_req_2_bits_isVset;
    enqInBits[2].isXSTrap = _dispatch_io_enqRob_req_2_bits_isXSTrap;
    enqInBits[2].lastUop = _dispatch_io_enqRob_req_2_bits_lastUop;
    enqInBits[2].ldest = _dispatch_io_enqRob_req_2_bits_ldest;
    enqInBits[2].numWB = _dispatch_io_enqRob_req_2_bits_numWB;
    enqInBits[2].pdest = _dispatch_io_enqRob_req_2_bits_pdest;
    enqInBits[2].preDecodeInfo_isRVC = _dispatch_io_enqRob_req_2_bits_preDecodeInfo_isRVC;
    enqInBits[2].rfWen = _dispatch_io_enqRob_req_2_bits_rfWen;
    enqInBits[2].robIdx_flag = _dispatch_io_enqRob_req_2_bits_robIdx_flag;
    enqInBits[2].robIdx_value = _dispatch_io_enqRob_req_2_bits_robIdx_value;
    enqInBits[2].singleStep = _dispatch_io_enqRob_req_2_bits_singleStep;
    enqInBits[2].traceBlockInPipe_ilastsize = _dispatch_io_enqRob_req_2_bits_traceBlockInPipe_ilastsize;
    enqInBits[2].traceBlockInPipe_iretire = _dispatch_io_enqRob_req_2_bits_traceBlockInPipe_iretire;
    enqInBits[2].traceBlockInPipe_itype = _dispatch_io_enqRob_req_2_bits_traceBlockInPipe_itype;
    enqInBits[2].trigger = _dispatch_io_enqRob_req_2_bits_trigger;
    enqInBits[2].v0Wen = _dispatch_io_enqRob_req_2_bits_v0Wen;
    enqInBits[2].vecWen = _dispatch_io_enqRob_req_2_bits_vecWen;
    enqInBits[2].vlWen = _dispatch_io_enqRob_req_2_bits_vlWen;
    enqInBits[2].vlsInstr = _dispatch_io_enqRob_req_2_bits_vlsInstr;
    enqInBits[2].vpu_specVill = _dispatch_io_enqRob_req_2_bits_vpu_specVill;
    enqInBits[2].vpu_specVlmul = _dispatch_io_enqRob_req_2_bits_vpu_specVlmul;
    enqInBits[2].vpu_specVma = _dispatch_io_enqRob_req_2_bits_vpu_specVma;
    enqInBits[2].vpu_specVsew = _dispatch_io_enqRob_req_2_bits_vpu_specVsew;
    enqInBits[2].vpu_specVta = _dispatch_io_enqRob_req_2_bits_vpu_specVta;
    enqInBits[2].vpu_vill = _dispatch_io_enqRob_req_2_bits_vpu_vill;
    enqInBits[2].vpu_vlmul = _dispatch_io_enqRob_req_2_bits_vpu_vlmul;
    enqInBits[2].vpu_vma = _dispatch_io_enqRob_req_2_bits_vpu_vma;
    enqInBits[2].vpu_vsew = _dispatch_io_enqRob_req_2_bits_vpu_vsew;
    enqInBits[2].vpu_vta = _dispatch_io_enqRob_req_2_bits_vpu_vta;
    enqInBits[2].waitForward = _dispatch_io_enqRob_req_2_bits_waitForward;
    enqInBits[2].wfflags = _dispatch_io_enqRob_req_2_bits_wfflags;
    // ---- enqRob.req[3] ----
    enqInBits[3].blockBackward = _dispatch_io_enqRob_req_3_bits_blockBackward;
    enqInBits[3].commitType = _dispatch_io_enqRob_req_3_bits_commitType;
    enqInBits[3].crossPageIPFFix = _dispatch_io_enqRob_req_3_bits_crossPageIPFFix;
    enqInBits[3].debugInfo_renameTime = _dispatch_io_enqRob_req_3_bits_debugInfo_renameTime;
    enqInBits[3].dirtyFs = _dispatch_io_enqRob_req_3_bits_dirtyFs;
    enqInBits[3].dirtyVs = _dispatch_io_enqRob_req_3_bits_dirtyVs;
    enqInBits[3].eliminatedMove = _dispatch_io_enqRob_req_3_bits_eliminatedMove;
    enqInBits[3].exceptionVec[0] = _dispatch_io_enqRob_req_3_bits_exceptionVec_0;
    enqInBits[3].exceptionVec[1] = _dispatch_io_enqRob_req_3_bits_exceptionVec_1;
    enqInBits[3].exceptionVec[12] = _dispatch_io_enqRob_req_3_bits_exceptionVec_12;
    enqInBits[3].exceptionVec[2] = _dispatch_io_enqRob_req_3_bits_exceptionVec_2;
    enqInBits[3].exceptionVec[20] = _dispatch_io_enqRob_req_3_bits_exceptionVec_20;
    enqInBits[3].exceptionVec[22] = _dispatch_io_enqRob_req_3_bits_exceptionVec_22;
    enqInBits[3].exceptionVec[3] = _dispatch_io_enqRob_req_3_bits_exceptionVec_3;
    enqInBits[3].firstUop = _dispatch_io_enqRob_req_3_bits_firstUop;
    enqInBits[3].flushPipe = _dispatch_io_enqRob_req_3_bits_flushPipe;
    enqInBits[3].fpWen = _dispatch_io_enqRob_req_3_bits_fpWen;
    enqInBits[3].ftqOffset = _dispatch_io_enqRob_req_3_bits_ftqOffset;
    enqInBits[3].ftqPtr_flag = _dispatch_io_enqRob_req_3_bits_ftqPtr_flag;
    enqInBits[3].ftqPtr_value = _dispatch_io_enqRob_req_3_bits_ftqPtr_value;
    enqInBits[3].fuOpType = _dispatch_io_enqRob_req_3_bits_fuOpType;
    enqInBits[3].fuType = _dispatch_io_enqRob_req_3_bits_fuType;
    enqInBits[3].hasException = _dispatch_io_enqRob_req_3_bits_hasException;
    enqInBits[3].instr = _dispatch_io_enqRob_req_3_bits_instr;
    enqInBits[3].instrSize = _dispatch_io_enqRob_req_3_bits_instrSize;
    enqInBits[3].isFetchMalAddr = _dispatch_io_enqRob_req_3_bits_isFetchMalAddr;
    enqInBits[3].isMove = _dispatch_io_enqRob_req_3_bits_isMove;
    enqInBits[3].isVset = _dispatch_io_enqRob_req_3_bits_isVset;
    enqInBits[3].isXSTrap = _dispatch_io_enqRob_req_3_bits_isXSTrap;
    enqInBits[3].lastUop = _dispatch_io_enqRob_req_3_bits_lastUop;
    enqInBits[3].ldest = _dispatch_io_enqRob_req_3_bits_ldest;
    enqInBits[3].numWB = _dispatch_io_enqRob_req_3_bits_numWB;
    enqInBits[3].pdest = _dispatch_io_enqRob_req_3_bits_pdest;
    enqInBits[3].preDecodeInfo_isRVC = _dispatch_io_enqRob_req_3_bits_preDecodeInfo_isRVC;
    enqInBits[3].rfWen = _dispatch_io_enqRob_req_3_bits_rfWen;
    enqInBits[3].robIdx_flag = _dispatch_io_enqRob_req_3_bits_robIdx_flag;
    enqInBits[3].robIdx_value = _dispatch_io_enqRob_req_3_bits_robIdx_value;
    enqInBits[3].singleStep = _dispatch_io_enqRob_req_3_bits_singleStep;
    enqInBits[3].traceBlockInPipe_ilastsize = _dispatch_io_enqRob_req_3_bits_traceBlockInPipe_ilastsize;
    enqInBits[3].traceBlockInPipe_iretire = _dispatch_io_enqRob_req_3_bits_traceBlockInPipe_iretire;
    enqInBits[3].traceBlockInPipe_itype = _dispatch_io_enqRob_req_3_bits_traceBlockInPipe_itype;
    enqInBits[3].trigger = _dispatch_io_enqRob_req_3_bits_trigger;
    enqInBits[3].v0Wen = _dispatch_io_enqRob_req_3_bits_v0Wen;
    enqInBits[3].vecWen = _dispatch_io_enqRob_req_3_bits_vecWen;
    enqInBits[3].vlWen = _dispatch_io_enqRob_req_3_bits_vlWen;
    enqInBits[3].vlsInstr = _dispatch_io_enqRob_req_3_bits_vlsInstr;
    enqInBits[3].vpu_specVill = _dispatch_io_enqRob_req_3_bits_vpu_specVill;
    enqInBits[3].vpu_specVlmul = _dispatch_io_enqRob_req_3_bits_vpu_specVlmul;
    enqInBits[3].vpu_specVma = _dispatch_io_enqRob_req_3_bits_vpu_specVma;
    enqInBits[3].vpu_specVsew = _dispatch_io_enqRob_req_3_bits_vpu_specVsew;
    enqInBits[3].vpu_specVta = _dispatch_io_enqRob_req_3_bits_vpu_specVta;
    enqInBits[3].vpu_vill = _dispatch_io_enqRob_req_3_bits_vpu_vill;
    enqInBits[3].vpu_vlmul = _dispatch_io_enqRob_req_3_bits_vpu_vlmul;
    enqInBits[3].vpu_vma = _dispatch_io_enqRob_req_3_bits_vpu_vma;
    enqInBits[3].vpu_vsew = _dispatch_io_enqRob_req_3_bits_vpu_vsew;
    enqInBits[3].vpu_vta = _dispatch_io_enqRob_req_3_bits_vpu_vta;
    enqInBits[3].waitForward = _dispatch_io_enqRob_req_3_bits_waitForward;
    enqInBits[3].wfflags = _dispatch_io_enqRob_req_3_bits_wfflags;
    // ---- enqRob.req[4] ----
    enqInBits[4].blockBackward = _dispatch_io_enqRob_req_4_bits_blockBackward;
    enqInBits[4].commitType = _dispatch_io_enqRob_req_4_bits_commitType;
    enqInBits[4].crossPageIPFFix = _dispatch_io_enqRob_req_4_bits_crossPageIPFFix;
    enqInBits[4].debugInfo_renameTime = _dispatch_io_enqRob_req_4_bits_debugInfo_renameTime;
    enqInBits[4].dirtyFs = _dispatch_io_enqRob_req_4_bits_dirtyFs;
    enqInBits[4].dirtyVs = _dispatch_io_enqRob_req_4_bits_dirtyVs;
    enqInBits[4].eliminatedMove = _dispatch_io_enqRob_req_4_bits_eliminatedMove;
    enqInBits[4].exceptionVec[0] = _dispatch_io_enqRob_req_4_bits_exceptionVec_0;
    enqInBits[4].exceptionVec[1] = _dispatch_io_enqRob_req_4_bits_exceptionVec_1;
    enqInBits[4].exceptionVec[12] = _dispatch_io_enqRob_req_4_bits_exceptionVec_12;
    enqInBits[4].exceptionVec[2] = _dispatch_io_enqRob_req_4_bits_exceptionVec_2;
    enqInBits[4].exceptionVec[20] = _dispatch_io_enqRob_req_4_bits_exceptionVec_20;
    enqInBits[4].exceptionVec[22] = _dispatch_io_enqRob_req_4_bits_exceptionVec_22;
    enqInBits[4].exceptionVec[3] = _dispatch_io_enqRob_req_4_bits_exceptionVec_3;
    enqInBits[4].firstUop = _dispatch_io_enqRob_req_4_bits_firstUop;
    enqInBits[4].flushPipe = _dispatch_io_enqRob_req_4_bits_flushPipe;
    enqInBits[4].fpWen = _dispatch_io_enqRob_req_4_bits_fpWen;
    enqInBits[4].ftqOffset = _dispatch_io_enqRob_req_4_bits_ftqOffset;
    enqInBits[4].ftqPtr_flag = _dispatch_io_enqRob_req_4_bits_ftqPtr_flag;
    enqInBits[4].ftqPtr_value = _dispatch_io_enqRob_req_4_bits_ftqPtr_value;
    enqInBits[4].fuOpType = _dispatch_io_enqRob_req_4_bits_fuOpType;
    enqInBits[4].fuType = _dispatch_io_enqRob_req_4_bits_fuType;
    enqInBits[4].hasException = _dispatch_io_enqRob_req_4_bits_hasException;
    enqInBits[4].instr = _dispatch_io_enqRob_req_4_bits_instr;
    enqInBits[4].instrSize = _dispatch_io_enqRob_req_4_bits_instrSize;
    enqInBits[4].isFetchMalAddr = _dispatch_io_enqRob_req_4_bits_isFetchMalAddr;
    enqInBits[4].isMove = _dispatch_io_enqRob_req_4_bits_isMove;
    enqInBits[4].isVset = _dispatch_io_enqRob_req_4_bits_isVset;
    enqInBits[4].isXSTrap = _dispatch_io_enqRob_req_4_bits_isXSTrap;
    enqInBits[4].lastUop = _dispatch_io_enqRob_req_4_bits_lastUop;
    enqInBits[4].ldest = _dispatch_io_enqRob_req_4_bits_ldest;
    enqInBits[4].numWB = _dispatch_io_enqRob_req_4_bits_numWB;
    enqInBits[4].pdest = _dispatch_io_enqRob_req_4_bits_pdest;
    enqInBits[4].preDecodeInfo_isRVC = _dispatch_io_enqRob_req_4_bits_preDecodeInfo_isRVC;
    enqInBits[4].rfWen = _dispatch_io_enqRob_req_4_bits_rfWen;
    enqInBits[4].robIdx_flag = _dispatch_io_enqRob_req_4_bits_robIdx_flag;
    enqInBits[4].robIdx_value = _dispatch_io_enqRob_req_4_bits_robIdx_value;
    enqInBits[4].singleStep = _dispatch_io_enqRob_req_4_bits_singleStep;
    enqInBits[4].traceBlockInPipe_ilastsize = _dispatch_io_enqRob_req_4_bits_traceBlockInPipe_ilastsize;
    enqInBits[4].traceBlockInPipe_iretire = _dispatch_io_enqRob_req_4_bits_traceBlockInPipe_iretire;
    enqInBits[4].traceBlockInPipe_itype = _dispatch_io_enqRob_req_4_bits_traceBlockInPipe_itype;
    enqInBits[4].trigger = _dispatch_io_enqRob_req_4_bits_trigger;
    enqInBits[4].v0Wen = _dispatch_io_enqRob_req_4_bits_v0Wen;
    enqInBits[4].vecWen = _dispatch_io_enqRob_req_4_bits_vecWen;
    enqInBits[4].vlWen = _dispatch_io_enqRob_req_4_bits_vlWen;
    enqInBits[4].vlsInstr = _dispatch_io_enqRob_req_4_bits_vlsInstr;
    enqInBits[4].vpu_specVill = _dispatch_io_enqRob_req_4_bits_vpu_specVill;
    enqInBits[4].vpu_specVlmul = _dispatch_io_enqRob_req_4_bits_vpu_specVlmul;
    enqInBits[4].vpu_specVma = _dispatch_io_enqRob_req_4_bits_vpu_specVma;
    enqInBits[4].vpu_specVsew = _dispatch_io_enqRob_req_4_bits_vpu_specVsew;
    enqInBits[4].vpu_specVta = _dispatch_io_enqRob_req_4_bits_vpu_specVta;
    enqInBits[4].vpu_vill = _dispatch_io_enqRob_req_4_bits_vpu_vill;
    enqInBits[4].vpu_vlmul = _dispatch_io_enqRob_req_4_bits_vpu_vlmul;
    enqInBits[4].vpu_vma = _dispatch_io_enqRob_req_4_bits_vpu_vma;
    enqInBits[4].vpu_vsew = _dispatch_io_enqRob_req_4_bits_vpu_vsew;
    enqInBits[4].vpu_vta = _dispatch_io_enqRob_req_4_bits_vpu_vta;
    enqInBits[4].waitForward = _dispatch_io_enqRob_req_4_bits_waitForward;
    enqInBits[4].wfflags = _dispatch_io_enqRob_req_4_bits_wfflags;
    // ---- enqRob.req[5] ----
    enqInBits[5].blockBackward = _dispatch_io_enqRob_req_5_bits_blockBackward;
    enqInBits[5].commitType = _dispatch_io_enqRob_req_5_bits_commitType;
    enqInBits[5].crossPageIPFFix = _dispatch_io_enqRob_req_5_bits_crossPageIPFFix;
    enqInBits[5].debugInfo_renameTime = _dispatch_io_enqRob_req_5_bits_debugInfo_renameTime;
    enqInBits[5].dirtyFs = _dispatch_io_enqRob_req_5_bits_dirtyFs;
    enqInBits[5].dirtyVs = _dispatch_io_enqRob_req_5_bits_dirtyVs;
    enqInBits[5].eliminatedMove = _dispatch_io_enqRob_req_5_bits_eliminatedMove;
    enqInBits[5].exceptionVec[0] = _dispatch_io_enqRob_req_5_bits_exceptionVec_0;
    enqInBits[5].exceptionVec[1] = _dispatch_io_enqRob_req_5_bits_exceptionVec_1;
    enqInBits[5].exceptionVec[12] = _dispatch_io_enqRob_req_5_bits_exceptionVec_12;
    enqInBits[5].exceptionVec[2] = _dispatch_io_enqRob_req_5_bits_exceptionVec_2;
    enqInBits[5].exceptionVec[20] = _dispatch_io_enqRob_req_5_bits_exceptionVec_20;
    enqInBits[5].exceptionVec[22] = _dispatch_io_enqRob_req_5_bits_exceptionVec_22;
    enqInBits[5].exceptionVec[3] = _dispatch_io_enqRob_req_5_bits_exceptionVec_3;
    enqInBits[5].firstUop = _dispatch_io_enqRob_req_5_bits_firstUop;
    enqInBits[5].flushPipe = _dispatch_io_enqRob_req_5_bits_flushPipe;
    enqInBits[5].fpWen = _dispatch_io_enqRob_req_5_bits_fpWen;
    enqInBits[5].ftqOffset = _dispatch_io_enqRob_req_5_bits_ftqOffset;
    enqInBits[5].ftqPtr_flag = _dispatch_io_enqRob_req_5_bits_ftqPtr_flag;
    enqInBits[5].ftqPtr_value = _dispatch_io_enqRob_req_5_bits_ftqPtr_value;
    enqInBits[5].fuOpType = _dispatch_io_enqRob_req_5_bits_fuOpType;
    enqInBits[5].fuType = _dispatch_io_enqRob_req_5_bits_fuType;
    enqInBits[5].hasException = _dispatch_io_enqRob_req_5_bits_hasException;
    enqInBits[5].instr = _dispatch_io_enqRob_req_5_bits_instr;
    enqInBits[5].instrSize = _dispatch_io_enqRob_req_5_bits_instrSize;
    enqInBits[5].isFetchMalAddr = _dispatch_io_enqRob_req_5_bits_isFetchMalAddr;
    enqInBits[5].isMove = _dispatch_io_enqRob_req_5_bits_isMove;
    enqInBits[5].isVset = _dispatch_io_enqRob_req_5_bits_isVset;
    enqInBits[5].isXSTrap = _dispatch_io_enqRob_req_5_bits_isXSTrap;
    enqInBits[5].lastUop = _dispatch_io_enqRob_req_5_bits_lastUop;
    enqInBits[5].ldest = _dispatch_io_enqRob_req_5_bits_ldest;
    enqInBits[5].numWB = _dispatch_io_enqRob_req_5_bits_numWB;
    enqInBits[5].pdest = _dispatch_io_enqRob_req_5_bits_pdest;
    enqInBits[5].preDecodeInfo_isRVC = _dispatch_io_enqRob_req_5_bits_preDecodeInfo_isRVC;
    enqInBits[5].rfWen = _dispatch_io_enqRob_req_5_bits_rfWen;
    enqInBits[5].robIdx_flag = _dispatch_io_enqRob_req_5_bits_robIdx_flag;
    enqInBits[5].robIdx_value = _dispatch_io_enqRob_req_5_bits_robIdx_value;
    enqInBits[5].singleStep = _dispatch_io_enqRob_req_5_bits_singleStep;
    enqInBits[5].traceBlockInPipe_ilastsize = _dispatch_io_enqRob_req_5_bits_traceBlockInPipe_ilastsize;
    enqInBits[5].traceBlockInPipe_iretire = _dispatch_io_enqRob_req_5_bits_traceBlockInPipe_iretire;
    enqInBits[5].traceBlockInPipe_itype = _dispatch_io_enqRob_req_5_bits_traceBlockInPipe_itype;
    enqInBits[5].trigger = _dispatch_io_enqRob_req_5_bits_trigger;
    enqInBits[5].v0Wen = _dispatch_io_enqRob_req_5_bits_v0Wen;
    enqInBits[5].vecWen = _dispatch_io_enqRob_req_5_bits_vecWen;
    enqInBits[5].vlWen = _dispatch_io_enqRob_req_5_bits_vlWen;
    enqInBits[5].vlsInstr = _dispatch_io_enqRob_req_5_bits_vlsInstr;
    enqInBits[5].vpu_specVill = _dispatch_io_enqRob_req_5_bits_vpu_specVill;
    enqInBits[5].vpu_specVlmul = _dispatch_io_enqRob_req_5_bits_vpu_specVlmul;
    enqInBits[5].vpu_specVma = _dispatch_io_enqRob_req_5_bits_vpu_specVma;
    enqInBits[5].vpu_specVsew = _dispatch_io_enqRob_req_5_bits_vpu_specVsew;
    enqInBits[5].vpu_specVta = _dispatch_io_enqRob_req_5_bits_vpu_specVta;
    enqInBits[5].vpu_vill = _dispatch_io_enqRob_req_5_bits_vpu_vill;
    enqInBits[5].vpu_vlmul = _dispatch_io_enqRob_req_5_bits_vpu_vlmul;
    enqInBits[5].vpu_vma = _dispatch_io_enqRob_req_5_bits_vpu_vma;
    enqInBits[5].vpu_vsew = _dispatch_io_enqRob_req_5_bits_vpu_vsew;
    enqInBits[5].vpu_vta = _dispatch_io_enqRob_req_5_bits_vpu_vta;
    enqInBits[5].waitForward = _dispatch_io_enqRob_req_5_bits_waitForward;
    enqInBits[5].wfflags = _dispatch_io_enqRob_req_5_bits_wfflags;
  end
