// 自动生成:scripts/gen_datapath.py —— 勿手改(逻辑为从设计意图的可读重写)

// =====================================================================
// s0->s1 控制流水寄存器(打拍部分)。ctrl 字段从 fromIQ.common 寄存(RegEnable
// on s0.valid);loadDependency 老化为 {ld[0],1'b0};srcType 寄存(RegEnable on fire)
// 供 STD 端口 int|fp Mux1H;flush 寄存(RegNext)供 s1_flush 判定。
// =====================================================================

  // ---- 当拍 flush 与打一拍 flush(RegNext)聚成 flush_info_t,供 s1_flush 判定 ----
  datapath_pkg::flush_info_t flush_now, flush_q;
  assign flush_now = '{valid: io_flush_valid, level: io_flush_bits_level,
                       robIdx_flag: io_flush_bits_robIdx_flag,
                       robIdx_value: io_flush_bits_robIdx_value};
  always_ff @(posedge clock) begin
    if (reset) flush_q.valid <= 1'b0;
    else       flush_q.valid <= io_flush_valid;
    flush_q.level        <= io_flush_bits_level;
    flush_q.robIdx_flag  <= io_flush_bits_robIdx_flag;
    flush_q.robIdx_value <= io_flush_bits_robIdx_value;
  end

  // EXU g0.0 ctrl 流水寄存器
  logic [34:0] s1_ctrl_0_0_fuType;
  logic [8:0] s1_ctrl_0_0_fuOpType;
  logic s1_ctrl_0_0_robIdx_flag;
  logic [7:0] s1_ctrl_0_0_robIdx_value;
  logic [7:0] s1_ctrl_0_0_pdest;
  logic s1_ctrl_0_0_rfWen;
  logic [3:0] s1_ctrl_0_0_dataSources_0_value;
  logic [3:0] s1_ctrl_0_0_dataSources_1_value;
  logic [2:0] s1_ctrl_0_0_exuSources_0_value;
  logic [2:0] s1_ctrl_0_0_exuSources_1_value;
  logic [1:0] s1_ctrl_0_0_loadDependency_0;
  logic [1:0] s1_ctrl_0_0_loadDependency_1;
  logic [1:0] s1_ctrl_0_0_loadDependency_2;
  always_ff @(posedge clock) if (io_fromIntIQ_0_0_valid) begin
    s1_ctrl_0_0_fuType <= io_fromIntIQ_0_0_bits_common_fuType;
    s1_ctrl_0_0_fuOpType <= io_fromIntIQ_0_0_bits_common_fuOpType;
    s1_ctrl_0_0_robIdx_flag <= io_fromIntIQ_0_0_bits_common_robIdx_flag;
    s1_ctrl_0_0_robIdx_value <= io_fromIntIQ_0_0_bits_common_robIdx_value;
    s1_ctrl_0_0_pdest <= io_fromIntIQ_0_0_bits_common_pdest;
    s1_ctrl_0_0_rfWen <= io_fromIntIQ_0_0_bits_common_rfWen;
    s1_ctrl_0_0_dataSources_0_value <= io_fromIntIQ_0_0_bits_common_dataSources_0_value;
    s1_ctrl_0_0_dataSources_1_value <= io_fromIntIQ_0_0_bits_common_dataSources_1_value;
    s1_ctrl_0_0_exuSources_0_value <= io_fromIntIQ_0_0_bits_common_exuSources_0_value;
    s1_ctrl_0_0_exuSources_1_value <= io_fromIntIQ_0_0_bits_common_exuSources_1_value;
    s1_ctrl_0_0_loadDependency_0 <= {io_fromIntIQ_0_0_bits_common_loadDependency_0[0], 1'b0};
    s1_ctrl_0_0_loadDependency_1 <= {io_fromIntIQ_0_0_bits_common_loadDependency_1[0], 1'b0};
    s1_ctrl_0_0_loadDependency_2 <= {io_fromIntIQ_0_0_bits_common_loadDependency_2[0], 1'b0};
  end
  // EXU g0.1 ctrl 流水寄存器
  logic [34:0] s1_ctrl_0_1_fuType;
  logic [8:0] s1_ctrl_0_1_fuOpType;
  logic s1_ctrl_0_1_robIdx_flag;
  logic [7:0] s1_ctrl_0_1_robIdx_value;
  logic [7:0] s1_ctrl_0_1_pdest;
  logic s1_ctrl_0_1_rfWen;
  logic s1_ctrl_0_1_preDecode_isRVC;
  logic s1_ctrl_0_1_ftqIdx_flag;
  logic [5:0] s1_ctrl_0_1_ftqIdx_value;
  logic [3:0] s1_ctrl_0_1_ftqOffset;
  logic s1_ctrl_0_1_predictInfo_taken;
  logic [3:0] s1_ctrl_0_1_dataSources_0_value;
  logic [3:0] s1_ctrl_0_1_dataSources_1_value;
  logic [2:0] s1_ctrl_0_1_exuSources_0_value;
  logic [2:0] s1_ctrl_0_1_exuSources_1_value;
  logic [1:0] s1_ctrl_0_1_loadDependency_0;
  logic [1:0] s1_ctrl_0_1_loadDependency_1;
  logic [1:0] s1_ctrl_0_1_loadDependency_2;
  always_ff @(posedge clock) if (io_fromIntIQ_0_1_valid) begin
    s1_ctrl_0_1_fuType <= io_fromIntIQ_0_1_bits_common_fuType;
    s1_ctrl_0_1_fuOpType <= io_fromIntIQ_0_1_bits_common_fuOpType;
    s1_ctrl_0_1_robIdx_flag <= io_fromIntIQ_0_1_bits_common_robIdx_flag;
    s1_ctrl_0_1_robIdx_value <= io_fromIntIQ_0_1_bits_common_robIdx_value;
    s1_ctrl_0_1_pdest <= io_fromIntIQ_0_1_bits_common_pdest;
    s1_ctrl_0_1_rfWen <= io_fromIntIQ_0_1_bits_common_rfWen;
    s1_ctrl_0_1_preDecode_isRVC <= io_fromIntIQ_0_1_bits_common_preDecode_isRVC;
    s1_ctrl_0_1_ftqIdx_flag <= io_fromIntIQ_0_1_bits_common_ftqIdx_flag;
    s1_ctrl_0_1_ftqIdx_value <= io_fromIntIQ_0_1_bits_common_ftqIdx_value;
    s1_ctrl_0_1_ftqOffset <= io_fromIntIQ_0_1_bits_common_ftqOffset;
    s1_ctrl_0_1_predictInfo_taken <= io_fromIntIQ_0_1_bits_common_predictInfo_taken;
    s1_ctrl_0_1_dataSources_0_value <= io_fromIntIQ_0_1_bits_common_dataSources_0_value;
    s1_ctrl_0_1_dataSources_1_value <= io_fromIntIQ_0_1_bits_common_dataSources_1_value;
    s1_ctrl_0_1_exuSources_0_value <= io_fromIntIQ_0_1_bits_common_exuSources_0_value;
    s1_ctrl_0_1_exuSources_1_value <= io_fromIntIQ_0_1_bits_common_exuSources_1_value;
    s1_ctrl_0_1_loadDependency_0 <= {io_fromIntIQ_0_1_bits_common_loadDependency_0[0], 1'b0};
    s1_ctrl_0_1_loadDependency_1 <= {io_fromIntIQ_0_1_bits_common_loadDependency_1[0], 1'b0};
    s1_ctrl_0_1_loadDependency_2 <= {io_fromIntIQ_0_1_bits_common_loadDependency_2[0], 1'b0};
  end
  // EXU g1.0 ctrl 流水寄存器
  logic [34:0] s1_ctrl_1_0_fuType;
  logic [8:0] s1_ctrl_1_0_fuOpType;
  logic s1_ctrl_1_0_robIdx_flag;
  logic [7:0] s1_ctrl_1_0_robIdx_value;
  logic [7:0] s1_ctrl_1_0_pdest;
  logic s1_ctrl_1_0_rfWen;
  logic [3:0] s1_ctrl_1_0_dataSources_0_value;
  logic [3:0] s1_ctrl_1_0_dataSources_1_value;
  logic [2:0] s1_ctrl_1_0_exuSources_0_value;
  logic [2:0] s1_ctrl_1_0_exuSources_1_value;
  logic [1:0] s1_ctrl_1_0_loadDependency_0;
  logic [1:0] s1_ctrl_1_0_loadDependency_1;
  logic [1:0] s1_ctrl_1_0_loadDependency_2;
  always_ff @(posedge clock) if (io_fromIntIQ_1_0_valid) begin
    s1_ctrl_1_0_fuType <= io_fromIntIQ_1_0_bits_common_fuType;
    s1_ctrl_1_0_fuOpType <= io_fromIntIQ_1_0_bits_common_fuOpType;
    s1_ctrl_1_0_robIdx_flag <= io_fromIntIQ_1_0_bits_common_robIdx_flag;
    s1_ctrl_1_0_robIdx_value <= io_fromIntIQ_1_0_bits_common_robIdx_value;
    s1_ctrl_1_0_pdest <= io_fromIntIQ_1_0_bits_common_pdest;
    s1_ctrl_1_0_rfWen <= io_fromIntIQ_1_0_bits_common_rfWen;
    s1_ctrl_1_0_dataSources_0_value <= io_fromIntIQ_1_0_bits_common_dataSources_0_value;
    s1_ctrl_1_0_dataSources_1_value <= io_fromIntIQ_1_0_bits_common_dataSources_1_value;
    s1_ctrl_1_0_exuSources_0_value <= io_fromIntIQ_1_0_bits_common_exuSources_0_value;
    s1_ctrl_1_0_exuSources_1_value <= io_fromIntIQ_1_0_bits_common_exuSources_1_value;
    s1_ctrl_1_0_loadDependency_0 <= {io_fromIntIQ_1_0_bits_common_loadDependency_0[0], 1'b0};
    s1_ctrl_1_0_loadDependency_1 <= {io_fromIntIQ_1_0_bits_common_loadDependency_1[0], 1'b0};
    s1_ctrl_1_0_loadDependency_2 <= {io_fromIntIQ_1_0_bits_common_loadDependency_2[0], 1'b0};
  end
  // EXU g1.1 ctrl 流水寄存器
  logic [34:0] s1_ctrl_1_1_fuType;
  logic [8:0] s1_ctrl_1_1_fuOpType;
  logic s1_ctrl_1_1_robIdx_flag;
  logic [7:0] s1_ctrl_1_1_robIdx_value;
  logic [7:0] s1_ctrl_1_1_pdest;
  logic s1_ctrl_1_1_rfWen;
  logic s1_ctrl_1_1_preDecode_isRVC;
  logic s1_ctrl_1_1_ftqIdx_flag;
  logic [5:0] s1_ctrl_1_1_ftqIdx_value;
  logic [3:0] s1_ctrl_1_1_ftqOffset;
  logic s1_ctrl_1_1_predictInfo_taken;
  logic [3:0] s1_ctrl_1_1_dataSources_0_value;
  logic [3:0] s1_ctrl_1_1_dataSources_1_value;
  logic [2:0] s1_ctrl_1_1_exuSources_0_value;
  logic [2:0] s1_ctrl_1_1_exuSources_1_value;
  logic [1:0] s1_ctrl_1_1_loadDependency_0;
  logic [1:0] s1_ctrl_1_1_loadDependency_1;
  logic [1:0] s1_ctrl_1_1_loadDependency_2;
  always_ff @(posedge clock) if (io_fromIntIQ_1_1_valid) begin
    s1_ctrl_1_1_fuType <= io_fromIntIQ_1_1_bits_common_fuType;
    s1_ctrl_1_1_fuOpType <= io_fromIntIQ_1_1_bits_common_fuOpType;
    s1_ctrl_1_1_robIdx_flag <= io_fromIntIQ_1_1_bits_common_robIdx_flag;
    s1_ctrl_1_1_robIdx_value <= io_fromIntIQ_1_1_bits_common_robIdx_value;
    s1_ctrl_1_1_pdest <= io_fromIntIQ_1_1_bits_common_pdest;
    s1_ctrl_1_1_rfWen <= io_fromIntIQ_1_1_bits_common_rfWen;
    s1_ctrl_1_1_preDecode_isRVC <= io_fromIntIQ_1_1_bits_common_preDecode_isRVC;
    s1_ctrl_1_1_ftqIdx_flag <= io_fromIntIQ_1_1_bits_common_ftqIdx_flag;
    s1_ctrl_1_1_ftqIdx_value <= io_fromIntIQ_1_1_bits_common_ftqIdx_value;
    s1_ctrl_1_1_ftqOffset <= io_fromIntIQ_1_1_bits_common_ftqOffset;
    s1_ctrl_1_1_predictInfo_taken <= io_fromIntIQ_1_1_bits_common_predictInfo_taken;
    s1_ctrl_1_1_dataSources_0_value <= io_fromIntIQ_1_1_bits_common_dataSources_0_value;
    s1_ctrl_1_1_dataSources_1_value <= io_fromIntIQ_1_1_bits_common_dataSources_1_value;
    s1_ctrl_1_1_exuSources_0_value <= io_fromIntIQ_1_1_bits_common_exuSources_0_value;
    s1_ctrl_1_1_exuSources_1_value <= io_fromIntIQ_1_1_bits_common_exuSources_1_value;
    s1_ctrl_1_1_loadDependency_0 <= {io_fromIntIQ_1_1_bits_common_loadDependency_0[0], 1'b0};
    s1_ctrl_1_1_loadDependency_1 <= {io_fromIntIQ_1_1_bits_common_loadDependency_1[0], 1'b0};
    s1_ctrl_1_1_loadDependency_2 <= {io_fromIntIQ_1_1_bits_common_loadDependency_2[0], 1'b0};
  end
  // EXU g2.0 ctrl 流水寄存器
  logic [34:0] s1_ctrl_2_0_fuType;
  logic [8:0] s1_ctrl_2_0_fuOpType;
  logic s1_ctrl_2_0_robIdx_flag;
  logic [7:0] s1_ctrl_2_0_robIdx_value;
  logic [7:0] s1_ctrl_2_0_pdest;
  logic s1_ctrl_2_0_rfWen;
  logic [3:0] s1_ctrl_2_0_dataSources_0_value;
  logic [3:0] s1_ctrl_2_0_dataSources_1_value;
  logic [2:0] s1_ctrl_2_0_exuSources_0_value;
  logic [2:0] s1_ctrl_2_0_exuSources_1_value;
  logic [1:0] s1_ctrl_2_0_loadDependency_0;
  logic [1:0] s1_ctrl_2_0_loadDependency_1;
  logic [1:0] s1_ctrl_2_0_loadDependency_2;
  always_ff @(posedge clock) if (io_fromIntIQ_2_0_valid) begin
    s1_ctrl_2_0_fuType <= io_fromIntIQ_2_0_bits_common_fuType;
    s1_ctrl_2_0_fuOpType <= io_fromIntIQ_2_0_bits_common_fuOpType;
    s1_ctrl_2_0_robIdx_flag <= io_fromIntIQ_2_0_bits_common_robIdx_flag;
    s1_ctrl_2_0_robIdx_value <= io_fromIntIQ_2_0_bits_common_robIdx_value;
    s1_ctrl_2_0_pdest <= io_fromIntIQ_2_0_bits_common_pdest;
    s1_ctrl_2_0_rfWen <= io_fromIntIQ_2_0_bits_common_rfWen;
    s1_ctrl_2_0_dataSources_0_value <= io_fromIntIQ_2_0_bits_common_dataSources_0_value;
    s1_ctrl_2_0_dataSources_1_value <= io_fromIntIQ_2_0_bits_common_dataSources_1_value;
    s1_ctrl_2_0_exuSources_0_value <= io_fromIntIQ_2_0_bits_common_exuSources_0_value;
    s1_ctrl_2_0_exuSources_1_value <= io_fromIntIQ_2_0_bits_common_exuSources_1_value;
    s1_ctrl_2_0_loadDependency_0 <= {io_fromIntIQ_2_0_bits_common_loadDependency_0[0], 1'b0};
    s1_ctrl_2_0_loadDependency_1 <= {io_fromIntIQ_2_0_bits_common_loadDependency_1[0], 1'b0};
    s1_ctrl_2_0_loadDependency_2 <= {io_fromIntIQ_2_0_bits_common_loadDependency_2[0], 1'b0};
  end
  // EXU g2.1 ctrl 流水寄存器
  logic [34:0] s1_ctrl_2_1_fuType;
  logic [8:0] s1_ctrl_2_1_fuOpType;
  logic s1_ctrl_2_1_robIdx_flag;
  logic [7:0] s1_ctrl_2_1_robIdx_value;
  logic [7:0] s1_ctrl_2_1_pdest;
  logic s1_ctrl_2_1_rfWen;
  logic s1_ctrl_2_1_fpWen;
  logic s1_ctrl_2_1_vecWen;
  logic s1_ctrl_2_1_v0Wen;
  logic s1_ctrl_2_1_vlWen;
  logic [1:0] s1_ctrl_2_1_fpu_typeTagOut;
  logic s1_ctrl_2_1_fpu_wflags;
  logic [1:0] s1_ctrl_2_1_fpu_typ;
  logic [2:0] s1_ctrl_2_1_fpu_rm;
  logic s1_ctrl_2_1_preDecode_isRVC;
  logic s1_ctrl_2_1_ftqIdx_flag;
  logic [5:0] s1_ctrl_2_1_ftqIdx_value;
  logic [3:0] s1_ctrl_2_1_ftqOffset;
  logic s1_ctrl_2_1_predictInfo_taken;
  logic [3:0] s1_ctrl_2_1_dataSources_0_value;
  logic [3:0] s1_ctrl_2_1_dataSources_1_value;
  logic [2:0] s1_ctrl_2_1_exuSources_0_value;
  logic [2:0] s1_ctrl_2_1_exuSources_1_value;
  logic [1:0] s1_ctrl_2_1_loadDependency_0;
  logic [1:0] s1_ctrl_2_1_loadDependency_1;
  logic [1:0] s1_ctrl_2_1_loadDependency_2;
  always_ff @(posedge clock) if (io_fromIntIQ_2_1_valid) begin
    s1_ctrl_2_1_fuType <= io_fromIntIQ_2_1_bits_common_fuType;
    s1_ctrl_2_1_fuOpType <= io_fromIntIQ_2_1_bits_common_fuOpType;
    s1_ctrl_2_1_robIdx_flag <= io_fromIntIQ_2_1_bits_common_robIdx_flag;
    s1_ctrl_2_1_robIdx_value <= io_fromIntIQ_2_1_bits_common_robIdx_value;
    s1_ctrl_2_1_pdest <= io_fromIntIQ_2_1_bits_common_pdest;
    s1_ctrl_2_1_rfWen <= io_fromIntIQ_2_1_bits_common_rfWen;
    s1_ctrl_2_1_fpWen <= io_fromIntIQ_2_1_bits_common_fpWen;
    s1_ctrl_2_1_vecWen <= io_fromIntIQ_2_1_bits_common_vecWen;
    s1_ctrl_2_1_v0Wen <= io_fromIntIQ_2_1_bits_common_v0Wen;
    s1_ctrl_2_1_vlWen <= io_fromIntIQ_2_1_bits_common_vlWen;
    s1_ctrl_2_1_fpu_typeTagOut <= io_fromIntIQ_2_1_bits_common_fpu_typeTagOut;
    s1_ctrl_2_1_fpu_wflags <= io_fromIntIQ_2_1_bits_common_fpu_wflags;
    s1_ctrl_2_1_fpu_typ <= io_fromIntIQ_2_1_bits_common_fpu_typ;
    s1_ctrl_2_1_fpu_rm <= io_fromIntIQ_2_1_bits_common_fpu_rm;
    s1_ctrl_2_1_preDecode_isRVC <= io_fromIntIQ_2_1_bits_common_preDecode_isRVC;
    s1_ctrl_2_1_ftqIdx_flag <= io_fromIntIQ_2_1_bits_common_ftqIdx_flag;
    s1_ctrl_2_1_ftqIdx_value <= io_fromIntIQ_2_1_bits_common_ftqIdx_value;
    s1_ctrl_2_1_ftqOffset <= io_fromIntIQ_2_1_bits_common_ftqOffset;
    s1_ctrl_2_1_predictInfo_taken <= io_fromIntIQ_2_1_bits_common_predictInfo_taken;
    s1_ctrl_2_1_dataSources_0_value <= io_fromIntIQ_2_1_bits_common_dataSources_0_value;
    s1_ctrl_2_1_dataSources_1_value <= io_fromIntIQ_2_1_bits_common_dataSources_1_value;
    s1_ctrl_2_1_exuSources_0_value <= io_fromIntIQ_2_1_bits_common_exuSources_0_value;
    s1_ctrl_2_1_exuSources_1_value <= io_fromIntIQ_2_1_bits_common_exuSources_1_value;
    s1_ctrl_2_1_loadDependency_0 <= {io_fromIntIQ_2_1_bits_common_loadDependency_0[0], 1'b0};
    s1_ctrl_2_1_loadDependency_1 <= {io_fromIntIQ_2_1_bits_common_loadDependency_1[0], 1'b0};
    s1_ctrl_2_1_loadDependency_2 <= {io_fromIntIQ_2_1_bits_common_loadDependency_2[0], 1'b0};
  end
  // EXU g3.0 ctrl 流水寄存器
  logic [34:0] s1_ctrl_3_0_fuType;
  logic [8:0] s1_ctrl_3_0_fuOpType;
  logic s1_ctrl_3_0_robIdx_flag;
  logic [7:0] s1_ctrl_3_0_robIdx_value;
  logic [7:0] s1_ctrl_3_0_pdest;
  logic s1_ctrl_3_0_rfWen;
  logic [3:0] s1_ctrl_3_0_dataSources_0_value;
  logic [3:0] s1_ctrl_3_0_dataSources_1_value;
  logic [2:0] s1_ctrl_3_0_exuSources_0_value;
  logic [2:0] s1_ctrl_3_0_exuSources_1_value;
  logic [1:0] s1_ctrl_3_0_loadDependency_0;
  logic [1:0] s1_ctrl_3_0_loadDependency_1;
  logic [1:0] s1_ctrl_3_0_loadDependency_2;
  always_ff @(posedge clock) if (io_fromIntIQ_3_0_valid) begin
    s1_ctrl_3_0_fuType <= io_fromIntIQ_3_0_bits_common_fuType;
    s1_ctrl_3_0_fuOpType <= io_fromIntIQ_3_0_bits_common_fuOpType;
    s1_ctrl_3_0_robIdx_flag <= io_fromIntIQ_3_0_bits_common_robIdx_flag;
    s1_ctrl_3_0_robIdx_value <= io_fromIntIQ_3_0_bits_common_robIdx_value;
    s1_ctrl_3_0_pdest <= io_fromIntIQ_3_0_bits_common_pdest;
    s1_ctrl_3_0_rfWen <= io_fromIntIQ_3_0_bits_common_rfWen;
    s1_ctrl_3_0_dataSources_0_value <= io_fromIntIQ_3_0_bits_common_dataSources_0_value;
    s1_ctrl_3_0_dataSources_1_value <= io_fromIntIQ_3_0_bits_common_dataSources_1_value;
    s1_ctrl_3_0_exuSources_0_value <= io_fromIntIQ_3_0_bits_common_exuSources_0_value;
    s1_ctrl_3_0_exuSources_1_value <= io_fromIntIQ_3_0_bits_common_exuSources_1_value;
    s1_ctrl_3_0_loadDependency_0 <= {io_fromIntIQ_3_0_bits_common_loadDependency_0[0], 1'b0};
    s1_ctrl_3_0_loadDependency_1 <= {io_fromIntIQ_3_0_bits_common_loadDependency_1[0], 1'b0};
    s1_ctrl_3_0_loadDependency_2 <= {io_fromIntIQ_3_0_bits_common_loadDependency_2[0], 1'b0};
  end
  // EXU g3.1 ctrl 流水寄存器
  logic [34:0] s1_ctrl_3_1_fuType;
  logic [8:0] s1_ctrl_3_1_fuOpType;
  logic [63:0] s1_ctrl_3_1_imm;
  logic s1_ctrl_3_1_robIdx_flag;
  logic [7:0] s1_ctrl_3_1_robIdx_value;
  logic [7:0] s1_ctrl_3_1_pdest;
  logic s1_ctrl_3_1_rfWen;
  logic s1_ctrl_3_1_flushPipe;
  logic s1_ctrl_3_1_ftqIdx_flag;
  logic [5:0] s1_ctrl_3_1_ftqIdx_value;
  logic [3:0] s1_ctrl_3_1_ftqOffset;
  logic [3:0] s1_ctrl_3_1_dataSources_0_value;
  logic [3:0] s1_ctrl_3_1_dataSources_1_value;
  logic [2:0] s1_ctrl_3_1_exuSources_0_value;
  logic [2:0] s1_ctrl_3_1_exuSources_1_value;
  logic [1:0] s1_ctrl_3_1_loadDependency_0;
  logic [1:0] s1_ctrl_3_1_loadDependency_1;
  logic [1:0] s1_ctrl_3_1_loadDependency_2;
  always_ff @(posedge clock) if (io_fromIntIQ_3_1_valid) begin
    s1_ctrl_3_1_fuType <= io_fromIntIQ_3_1_bits_common_fuType;
    s1_ctrl_3_1_fuOpType <= io_fromIntIQ_3_1_bits_common_fuOpType;
    s1_ctrl_3_1_imm <= io_fromIntIQ_3_1_bits_common_imm;
    s1_ctrl_3_1_robIdx_flag <= io_fromIntIQ_3_1_bits_common_robIdx_flag;
    s1_ctrl_3_1_robIdx_value <= io_fromIntIQ_3_1_bits_common_robIdx_value;
    s1_ctrl_3_1_pdest <= io_fromIntIQ_3_1_bits_common_pdest;
    s1_ctrl_3_1_rfWen <= io_fromIntIQ_3_1_bits_common_rfWen;
    s1_ctrl_3_1_flushPipe <= io_fromIntIQ_3_1_bits_common_flushPipe;
    s1_ctrl_3_1_ftqIdx_flag <= io_fromIntIQ_3_1_bits_common_ftqIdx_flag;
    s1_ctrl_3_1_ftqIdx_value <= io_fromIntIQ_3_1_bits_common_ftqIdx_value;
    s1_ctrl_3_1_ftqOffset <= io_fromIntIQ_3_1_bits_common_ftqOffset;
    s1_ctrl_3_1_dataSources_0_value <= io_fromIntIQ_3_1_bits_common_dataSources_0_value;
    s1_ctrl_3_1_dataSources_1_value <= io_fromIntIQ_3_1_bits_common_dataSources_1_value;
    s1_ctrl_3_1_exuSources_0_value <= io_fromIntIQ_3_1_bits_common_exuSources_0_value;
    s1_ctrl_3_1_exuSources_1_value <= io_fromIntIQ_3_1_bits_common_exuSources_1_value;
    s1_ctrl_3_1_loadDependency_0 <= {io_fromIntIQ_3_1_bits_common_loadDependency_0[0], 1'b0};
    s1_ctrl_3_1_loadDependency_1 <= {io_fromIntIQ_3_1_bits_common_loadDependency_1[0], 1'b0};
    s1_ctrl_3_1_loadDependency_2 <= {io_fromIntIQ_3_1_bits_common_loadDependency_2[0], 1'b0};
  end
  // EXU g4.0 ctrl 流水寄存器
  logic [34:0] s1_ctrl_4_0_fuType;
  logic [8:0] s1_ctrl_4_0_fuOpType;
  logic s1_ctrl_4_0_robIdx_flag;
  logic [7:0] s1_ctrl_4_0_robIdx_value;
  logic [7:0] s1_ctrl_4_0_pdest;
  logic s1_ctrl_4_0_rfWen;
  logic s1_ctrl_4_0_fpWen;
  logic s1_ctrl_4_0_vecWen;
  logic s1_ctrl_4_0_v0Wen;
  logic s1_ctrl_4_0_fpu_wflags;
  logic [1:0] s1_ctrl_4_0_fpu_fmt;
  logic [2:0] s1_ctrl_4_0_fpu_rm;
  logic [3:0] s1_ctrl_4_0_dataSources_0_value;
  logic [3:0] s1_ctrl_4_0_dataSources_1_value;
  logic [3:0] s1_ctrl_4_0_dataSources_2_value;
  logic [1:0] s1_ctrl_4_0_exuSources_0_value;
  logic [1:0] s1_ctrl_4_0_exuSources_1_value;
  logic [1:0] s1_ctrl_4_0_exuSources_2_value;
  always_ff @(posedge clock) if (io_fromFpIQ_0_0_valid) begin
    s1_ctrl_4_0_fuType <= io_fromFpIQ_0_0_bits_common_fuType;
    s1_ctrl_4_0_fuOpType <= io_fromFpIQ_0_0_bits_common_fuOpType;
    s1_ctrl_4_0_robIdx_flag <= io_fromFpIQ_0_0_bits_common_robIdx_flag;
    s1_ctrl_4_0_robIdx_value <= io_fromFpIQ_0_0_bits_common_robIdx_value;
    s1_ctrl_4_0_pdest <= io_fromFpIQ_0_0_bits_common_pdest;
    s1_ctrl_4_0_rfWen <= io_fromFpIQ_0_0_bits_common_rfWen;
    s1_ctrl_4_0_fpWen <= io_fromFpIQ_0_0_bits_common_fpWen;
    s1_ctrl_4_0_vecWen <= io_fromFpIQ_0_0_bits_common_vecWen;
    s1_ctrl_4_0_v0Wen <= io_fromFpIQ_0_0_bits_common_v0Wen;
    s1_ctrl_4_0_fpu_wflags <= io_fromFpIQ_0_0_bits_common_fpu_wflags;
    s1_ctrl_4_0_fpu_fmt <= io_fromFpIQ_0_0_bits_common_fpu_fmt;
    s1_ctrl_4_0_fpu_rm <= io_fromFpIQ_0_0_bits_common_fpu_rm;
    s1_ctrl_4_0_dataSources_0_value <= io_fromFpIQ_0_0_bits_common_dataSources_0_value;
    s1_ctrl_4_0_dataSources_1_value <= io_fromFpIQ_0_0_bits_common_dataSources_1_value;
    s1_ctrl_4_0_dataSources_2_value <= io_fromFpIQ_0_0_bits_common_dataSources_2_value;
    s1_ctrl_4_0_exuSources_0_value <= io_fromFpIQ_0_0_bits_common_exuSources_0_value;
    s1_ctrl_4_0_exuSources_1_value <= io_fromFpIQ_0_0_bits_common_exuSources_1_value;
    s1_ctrl_4_0_exuSources_2_value <= io_fromFpIQ_0_0_bits_common_exuSources_2_value;
  end
  // EXU g4.1 ctrl 流水寄存器
  logic [34:0] s1_ctrl_4_1_fuType;
  logic [8:0] s1_ctrl_4_1_fuOpType;
  logic s1_ctrl_4_1_robIdx_flag;
  logic [7:0] s1_ctrl_4_1_robIdx_value;
  logic [7:0] s1_ctrl_4_1_pdest;
  logic s1_ctrl_4_1_fpWen;
  logic s1_ctrl_4_1_fpu_wflags;
  logic [1:0] s1_ctrl_4_1_fpu_fmt;
  logic [2:0] s1_ctrl_4_1_fpu_rm;
  logic [3:0] s1_ctrl_4_1_dataSources_0_value;
  logic [3:0] s1_ctrl_4_1_dataSources_1_value;
  logic [1:0] s1_ctrl_4_1_exuSources_0_value;
  logic [1:0] s1_ctrl_4_1_exuSources_1_value;
  always_ff @(posedge clock) if (io_fromFpIQ_0_1_valid) begin
    s1_ctrl_4_1_fuType <= io_fromFpIQ_0_1_bits_common_fuType;
    s1_ctrl_4_1_fuOpType <= io_fromFpIQ_0_1_bits_common_fuOpType;
    s1_ctrl_4_1_robIdx_flag <= io_fromFpIQ_0_1_bits_common_robIdx_flag;
    s1_ctrl_4_1_robIdx_value <= io_fromFpIQ_0_1_bits_common_robIdx_value;
    s1_ctrl_4_1_pdest <= io_fromFpIQ_0_1_bits_common_pdest;
    s1_ctrl_4_1_fpWen <= io_fromFpIQ_0_1_bits_common_fpWen;
    s1_ctrl_4_1_fpu_wflags <= io_fromFpIQ_0_1_bits_common_fpu_wflags;
    s1_ctrl_4_1_fpu_fmt <= io_fromFpIQ_0_1_bits_common_fpu_fmt;
    s1_ctrl_4_1_fpu_rm <= io_fromFpIQ_0_1_bits_common_fpu_rm;
    s1_ctrl_4_1_dataSources_0_value <= io_fromFpIQ_0_1_bits_common_dataSources_0_value;
    s1_ctrl_4_1_dataSources_1_value <= io_fromFpIQ_0_1_bits_common_dataSources_1_value;
    s1_ctrl_4_1_exuSources_0_value <= io_fromFpIQ_0_1_bits_common_exuSources_0_value;
    s1_ctrl_4_1_exuSources_1_value <= io_fromFpIQ_0_1_bits_common_exuSources_1_value;
  end
  // EXU g5.0 ctrl 流水寄存器
  logic [34:0] s1_ctrl_5_0_fuType;
  logic [8:0] s1_ctrl_5_0_fuOpType;
  logic s1_ctrl_5_0_robIdx_flag;
  logic [7:0] s1_ctrl_5_0_robIdx_value;
  logic [7:0] s1_ctrl_5_0_pdest;
  logic s1_ctrl_5_0_rfWen;
  logic s1_ctrl_5_0_fpWen;
  logic s1_ctrl_5_0_fpu_wflags;
  logic [1:0] s1_ctrl_5_0_fpu_fmt;
  logic [2:0] s1_ctrl_5_0_fpu_rm;
  logic [3:0] s1_ctrl_5_0_dataSources_0_value;
  logic [3:0] s1_ctrl_5_0_dataSources_1_value;
  logic [3:0] s1_ctrl_5_0_dataSources_2_value;
  logic [1:0] s1_ctrl_5_0_exuSources_0_value;
  logic [1:0] s1_ctrl_5_0_exuSources_1_value;
  logic [1:0] s1_ctrl_5_0_exuSources_2_value;
  always_ff @(posedge clock) if (io_fromFpIQ_1_0_valid) begin
    s1_ctrl_5_0_fuType <= io_fromFpIQ_1_0_bits_common_fuType;
    s1_ctrl_5_0_fuOpType <= io_fromFpIQ_1_0_bits_common_fuOpType;
    s1_ctrl_5_0_robIdx_flag <= io_fromFpIQ_1_0_bits_common_robIdx_flag;
    s1_ctrl_5_0_robIdx_value <= io_fromFpIQ_1_0_bits_common_robIdx_value;
    s1_ctrl_5_0_pdest <= io_fromFpIQ_1_0_bits_common_pdest;
    s1_ctrl_5_0_rfWen <= io_fromFpIQ_1_0_bits_common_rfWen;
    s1_ctrl_5_0_fpWen <= io_fromFpIQ_1_0_bits_common_fpWen;
    s1_ctrl_5_0_fpu_wflags <= io_fromFpIQ_1_0_bits_common_fpu_wflags;
    s1_ctrl_5_0_fpu_fmt <= io_fromFpIQ_1_0_bits_common_fpu_fmt;
    s1_ctrl_5_0_fpu_rm <= io_fromFpIQ_1_0_bits_common_fpu_rm;
    s1_ctrl_5_0_dataSources_0_value <= io_fromFpIQ_1_0_bits_common_dataSources_0_value;
    s1_ctrl_5_0_dataSources_1_value <= io_fromFpIQ_1_0_bits_common_dataSources_1_value;
    s1_ctrl_5_0_dataSources_2_value <= io_fromFpIQ_1_0_bits_common_dataSources_2_value;
    s1_ctrl_5_0_exuSources_0_value <= io_fromFpIQ_1_0_bits_common_exuSources_0_value;
    s1_ctrl_5_0_exuSources_1_value <= io_fromFpIQ_1_0_bits_common_exuSources_1_value;
    s1_ctrl_5_0_exuSources_2_value <= io_fromFpIQ_1_0_bits_common_exuSources_2_value;
  end
  // EXU g5.1 ctrl 流水寄存器
  logic [34:0] s1_ctrl_5_1_fuType;
  logic [8:0] s1_ctrl_5_1_fuOpType;
  logic s1_ctrl_5_1_robIdx_flag;
  logic [7:0] s1_ctrl_5_1_robIdx_value;
  logic [7:0] s1_ctrl_5_1_pdest;
  logic s1_ctrl_5_1_fpWen;
  logic s1_ctrl_5_1_fpu_wflags;
  logic [1:0] s1_ctrl_5_1_fpu_fmt;
  logic [2:0] s1_ctrl_5_1_fpu_rm;
  logic [3:0] s1_ctrl_5_1_dataSources_0_value;
  logic [3:0] s1_ctrl_5_1_dataSources_1_value;
  logic [1:0] s1_ctrl_5_1_exuSources_0_value;
  logic [1:0] s1_ctrl_5_1_exuSources_1_value;
  always_ff @(posedge clock) if (io_fromFpIQ_1_1_valid) begin
    s1_ctrl_5_1_fuType <= io_fromFpIQ_1_1_bits_common_fuType;
    s1_ctrl_5_1_fuOpType <= io_fromFpIQ_1_1_bits_common_fuOpType;
    s1_ctrl_5_1_robIdx_flag <= io_fromFpIQ_1_1_bits_common_robIdx_flag;
    s1_ctrl_5_1_robIdx_value <= io_fromFpIQ_1_1_bits_common_robIdx_value;
    s1_ctrl_5_1_pdest <= io_fromFpIQ_1_1_bits_common_pdest;
    s1_ctrl_5_1_fpWen <= io_fromFpIQ_1_1_bits_common_fpWen;
    s1_ctrl_5_1_fpu_wflags <= io_fromFpIQ_1_1_bits_common_fpu_wflags;
    s1_ctrl_5_1_fpu_fmt <= io_fromFpIQ_1_1_bits_common_fpu_fmt;
    s1_ctrl_5_1_fpu_rm <= io_fromFpIQ_1_1_bits_common_fpu_rm;
    s1_ctrl_5_1_dataSources_0_value <= io_fromFpIQ_1_1_bits_common_dataSources_0_value;
    s1_ctrl_5_1_dataSources_1_value <= io_fromFpIQ_1_1_bits_common_dataSources_1_value;
    s1_ctrl_5_1_exuSources_0_value <= io_fromFpIQ_1_1_bits_common_exuSources_0_value;
    s1_ctrl_5_1_exuSources_1_value <= io_fromFpIQ_1_1_bits_common_exuSources_1_value;
  end
  // EXU g6.0 ctrl 流水寄存器
  logic [34:0] s1_ctrl_6_0_fuType;
  logic [8:0] s1_ctrl_6_0_fuOpType;
  logic s1_ctrl_6_0_robIdx_flag;
  logic [7:0] s1_ctrl_6_0_robIdx_value;
  logic [7:0] s1_ctrl_6_0_pdest;
  logic s1_ctrl_6_0_rfWen;
  logic s1_ctrl_6_0_fpWen;
  logic s1_ctrl_6_0_fpu_wflags;
  logic [1:0] s1_ctrl_6_0_fpu_fmt;
  logic [2:0] s1_ctrl_6_0_fpu_rm;
  logic [3:0] s1_ctrl_6_0_dataSources_0_value;
  logic [3:0] s1_ctrl_6_0_dataSources_1_value;
  logic [3:0] s1_ctrl_6_0_dataSources_2_value;
  logic [1:0] s1_ctrl_6_0_exuSources_0_value;
  logic [1:0] s1_ctrl_6_0_exuSources_1_value;
  logic [1:0] s1_ctrl_6_0_exuSources_2_value;
  always_ff @(posedge clock) if (io_fromFpIQ_2_0_valid) begin
    s1_ctrl_6_0_fuType <= io_fromFpIQ_2_0_bits_common_fuType;
    s1_ctrl_6_0_fuOpType <= io_fromFpIQ_2_0_bits_common_fuOpType;
    s1_ctrl_6_0_robIdx_flag <= io_fromFpIQ_2_0_bits_common_robIdx_flag;
    s1_ctrl_6_0_robIdx_value <= io_fromFpIQ_2_0_bits_common_robIdx_value;
    s1_ctrl_6_0_pdest <= io_fromFpIQ_2_0_bits_common_pdest;
    s1_ctrl_6_0_rfWen <= io_fromFpIQ_2_0_bits_common_rfWen;
    s1_ctrl_6_0_fpWen <= io_fromFpIQ_2_0_bits_common_fpWen;
    s1_ctrl_6_0_fpu_wflags <= io_fromFpIQ_2_0_bits_common_fpu_wflags;
    s1_ctrl_6_0_fpu_fmt <= io_fromFpIQ_2_0_bits_common_fpu_fmt;
    s1_ctrl_6_0_fpu_rm <= io_fromFpIQ_2_0_bits_common_fpu_rm;
    s1_ctrl_6_0_dataSources_0_value <= io_fromFpIQ_2_0_bits_common_dataSources_0_value;
    s1_ctrl_6_0_dataSources_1_value <= io_fromFpIQ_2_0_bits_common_dataSources_1_value;
    s1_ctrl_6_0_dataSources_2_value <= io_fromFpIQ_2_0_bits_common_dataSources_2_value;
    s1_ctrl_6_0_exuSources_0_value <= io_fromFpIQ_2_0_bits_common_exuSources_0_value;
    s1_ctrl_6_0_exuSources_1_value <= io_fromFpIQ_2_0_bits_common_exuSources_1_value;
    s1_ctrl_6_0_exuSources_2_value <= io_fromFpIQ_2_0_bits_common_exuSources_2_value;
  end
  // EXU g7.0 ctrl 流水寄存器
  logic [34:0] s1_ctrl_7_0_fuType;
  logic [8:0] s1_ctrl_7_0_fuOpType;
  logic s1_ctrl_7_0_robIdx_flag;
  logic [7:0] s1_ctrl_7_0_robIdx_value;
  logic [6:0] s1_ctrl_7_0_pdest;
  logic s1_ctrl_7_0_vecWen;
  logic s1_ctrl_7_0_v0Wen;
  logic s1_ctrl_7_0_fpu_wflags;
  logic s1_ctrl_7_0_vpu_vma;
  logic s1_ctrl_7_0_vpu_vta;
  logic [1:0] s1_ctrl_7_0_vpu_vsew;
  logic [2:0] s1_ctrl_7_0_vpu_vlmul;
  logic s1_ctrl_7_0_vpu_vm;
  logic [7:0] s1_ctrl_7_0_vpu_vstart;
  logic [6:0] s1_ctrl_7_0_vpu_vuopIdx;
  logic s1_ctrl_7_0_vpu_isExt;
  logic s1_ctrl_7_0_vpu_isNarrow;
  logic s1_ctrl_7_0_vpu_isDstMask;
  logic s1_ctrl_7_0_vpu_isOpMask;
  logic [3:0] s1_ctrl_7_0_dataSources_0_value;
  logic [3:0] s1_ctrl_7_0_dataSources_1_value;
  logic [3:0] s1_ctrl_7_0_dataSources_2_value;
  logic [3:0] s1_ctrl_7_0_dataSources_3_value;
  logic [3:0] s1_ctrl_7_0_dataSources_4_value;
  always_ff @(posedge clock) if (io_fromVfIQ_0_0_valid) begin
    s1_ctrl_7_0_fuType <= io_fromVfIQ_0_0_bits_common_fuType;
    s1_ctrl_7_0_fuOpType <= io_fromVfIQ_0_0_bits_common_fuOpType;
    s1_ctrl_7_0_robIdx_flag <= io_fromVfIQ_0_0_bits_common_robIdx_flag;
    s1_ctrl_7_0_robIdx_value <= io_fromVfIQ_0_0_bits_common_robIdx_value;
    s1_ctrl_7_0_pdest <= io_fromVfIQ_0_0_bits_common_pdest;
    s1_ctrl_7_0_vecWen <= io_fromVfIQ_0_0_bits_common_vecWen;
    s1_ctrl_7_0_v0Wen <= io_fromVfIQ_0_0_bits_common_v0Wen;
    s1_ctrl_7_0_fpu_wflags <= io_fromVfIQ_0_0_bits_common_fpu_wflags;
    s1_ctrl_7_0_vpu_vma <= io_fromVfIQ_0_0_bits_common_vpu_vma;
    s1_ctrl_7_0_vpu_vta <= io_fromVfIQ_0_0_bits_common_vpu_vta;
    s1_ctrl_7_0_vpu_vsew <= io_fromVfIQ_0_0_bits_common_vpu_vsew;
    s1_ctrl_7_0_vpu_vlmul <= io_fromVfIQ_0_0_bits_common_vpu_vlmul;
    s1_ctrl_7_0_vpu_vm <= io_fromVfIQ_0_0_bits_common_vpu_vm;
    s1_ctrl_7_0_vpu_vstart <= io_fromVfIQ_0_0_bits_common_vpu_vstart;
    s1_ctrl_7_0_vpu_vuopIdx <= io_fromVfIQ_0_0_bits_common_vpu_vuopIdx;
    s1_ctrl_7_0_vpu_isExt <= io_fromVfIQ_0_0_bits_common_vpu_isExt;
    s1_ctrl_7_0_vpu_isNarrow <= io_fromVfIQ_0_0_bits_common_vpu_isNarrow;
    s1_ctrl_7_0_vpu_isDstMask <= io_fromVfIQ_0_0_bits_common_vpu_isDstMask;
    s1_ctrl_7_0_vpu_isOpMask <= io_fromVfIQ_0_0_bits_common_vpu_isOpMask;
    s1_ctrl_7_0_dataSources_0_value <= io_fromVfIQ_0_0_bits_common_dataSources_0_value;
    s1_ctrl_7_0_dataSources_1_value <= io_fromVfIQ_0_0_bits_common_dataSources_1_value;
    s1_ctrl_7_0_dataSources_2_value <= io_fromVfIQ_0_0_bits_common_dataSources_2_value;
    s1_ctrl_7_0_dataSources_3_value <= io_fromVfIQ_0_0_bits_common_dataSources_3_value;
    s1_ctrl_7_0_dataSources_4_value <= io_fromVfIQ_0_0_bits_common_dataSources_4_value;
  end
  // EXU g7.1 ctrl 流水寄存器
  logic [34:0] s1_ctrl_7_1_fuType;
  logic [8:0] s1_ctrl_7_1_fuOpType;
  logic s1_ctrl_7_1_robIdx_flag;
  logic [7:0] s1_ctrl_7_1_robIdx_value;
  logic [7:0] s1_ctrl_7_1_pdest;
  logic s1_ctrl_7_1_rfWen;
  logic s1_ctrl_7_1_fpWen;
  logic s1_ctrl_7_1_vecWen;
  logic s1_ctrl_7_1_v0Wen;
  logic s1_ctrl_7_1_vlWen;
  logic s1_ctrl_7_1_fpu_wflags;
  logic s1_ctrl_7_1_vpu_vma;
  logic s1_ctrl_7_1_vpu_vta;
  logic [1:0] s1_ctrl_7_1_vpu_vsew;
  logic [2:0] s1_ctrl_7_1_vpu_vlmul;
  logic s1_ctrl_7_1_vpu_vm;
  logic [7:0] s1_ctrl_7_1_vpu_vstart;
  logic s1_ctrl_7_1_vpu_fpu_isFoldTo1_2;
  logic s1_ctrl_7_1_vpu_fpu_isFoldTo1_4;
  logic s1_ctrl_7_1_vpu_fpu_isFoldTo1_8;
  logic [6:0] s1_ctrl_7_1_vpu_vuopIdx;
  logic s1_ctrl_7_1_vpu_lastUop;
  logic s1_ctrl_7_1_vpu_isNarrow;
  logic s1_ctrl_7_1_vpu_isDstMask;
  logic [3:0] s1_ctrl_7_1_dataSources_0_value;
  logic [3:0] s1_ctrl_7_1_dataSources_1_value;
  logic [3:0] s1_ctrl_7_1_dataSources_2_value;
  logic [3:0] s1_ctrl_7_1_dataSources_3_value;
  logic [3:0] s1_ctrl_7_1_dataSources_4_value;
  always_ff @(posedge clock) if (io_fromVfIQ_0_1_valid) begin
    s1_ctrl_7_1_fuType <= io_fromVfIQ_0_1_bits_common_fuType;
    s1_ctrl_7_1_fuOpType <= io_fromVfIQ_0_1_bits_common_fuOpType;
    s1_ctrl_7_1_robIdx_flag <= io_fromVfIQ_0_1_bits_common_robIdx_flag;
    s1_ctrl_7_1_robIdx_value <= io_fromVfIQ_0_1_bits_common_robIdx_value;
    s1_ctrl_7_1_pdest <= io_fromVfIQ_0_1_bits_common_pdest;
    s1_ctrl_7_1_rfWen <= io_fromVfIQ_0_1_bits_common_rfWen;
    s1_ctrl_7_1_fpWen <= io_fromVfIQ_0_1_bits_common_fpWen;
    s1_ctrl_7_1_vecWen <= io_fromVfIQ_0_1_bits_common_vecWen;
    s1_ctrl_7_1_v0Wen <= io_fromVfIQ_0_1_bits_common_v0Wen;
    s1_ctrl_7_1_vlWen <= io_fromVfIQ_0_1_bits_common_vlWen;
    s1_ctrl_7_1_fpu_wflags <= io_fromVfIQ_0_1_bits_common_fpu_wflags;
    s1_ctrl_7_1_vpu_vma <= io_fromVfIQ_0_1_bits_common_vpu_vma;
    s1_ctrl_7_1_vpu_vta <= io_fromVfIQ_0_1_bits_common_vpu_vta;
    s1_ctrl_7_1_vpu_vsew <= io_fromVfIQ_0_1_bits_common_vpu_vsew;
    s1_ctrl_7_1_vpu_vlmul <= io_fromVfIQ_0_1_bits_common_vpu_vlmul;
    s1_ctrl_7_1_vpu_vm <= io_fromVfIQ_0_1_bits_common_vpu_vm;
    s1_ctrl_7_1_vpu_vstart <= io_fromVfIQ_0_1_bits_common_vpu_vstart;
    s1_ctrl_7_1_vpu_fpu_isFoldTo1_2 <= io_fromVfIQ_0_1_bits_common_vpu_fpu_isFoldTo1_2;
    s1_ctrl_7_1_vpu_fpu_isFoldTo1_4 <= io_fromVfIQ_0_1_bits_common_vpu_fpu_isFoldTo1_4;
    s1_ctrl_7_1_vpu_fpu_isFoldTo1_8 <= io_fromVfIQ_0_1_bits_common_vpu_fpu_isFoldTo1_8;
    s1_ctrl_7_1_vpu_vuopIdx <= io_fromVfIQ_0_1_bits_common_vpu_vuopIdx;
    s1_ctrl_7_1_vpu_lastUop <= io_fromVfIQ_0_1_bits_common_vpu_lastUop;
    s1_ctrl_7_1_vpu_isNarrow <= io_fromVfIQ_0_1_bits_common_vpu_isNarrow;
    s1_ctrl_7_1_vpu_isDstMask <= io_fromVfIQ_0_1_bits_common_vpu_isDstMask;
    s1_ctrl_7_1_dataSources_0_value <= io_fromVfIQ_0_1_bits_common_dataSources_0_value;
    s1_ctrl_7_1_dataSources_1_value <= io_fromVfIQ_0_1_bits_common_dataSources_1_value;
    s1_ctrl_7_1_dataSources_2_value <= io_fromVfIQ_0_1_bits_common_dataSources_2_value;
    s1_ctrl_7_1_dataSources_3_value <= io_fromVfIQ_0_1_bits_common_dataSources_3_value;
    s1_ctrl_7_1_dataSources_4_value <= io_fromVfIQ_0_1_bits_common_dataSources_4_value;
  end
  // EXU g8.0 ctrl 流水寄存器
  logic [34:0] s1_ctrl_8_0_fuType;
  logic [8:0] s1_ctrl_8_0_fuOpType;
  logic s1_ctrl_8_0_robIdx_flag;
  logic [7:0] s1_ctrl_8_0_robIdx_value;
  logic [6:0] s1_ctrl_8_0_pdest;
  logic s1_ctrl_8_0_vecWen;
  logic s1_ctrl_8_0_v0Wen;
  logic s1_ctrl_8_0_fpu_wflags;
  logic s1_ctrl_8_0_vpu_vma;
  logic s1_ctrl_8_0_vpu_vta;
  logic [1:0] s1_ctrl_8_0_vpu_vsew;
  logic [2:0] s1_ctrl_8_0_vpu_vlmul;
  logic s1_ctrl_8_0_vpu_vm;
  logic [7:0] s1_ctrl_8_0_vpu_vstart;
  logic [6:0] s1_ctrl_8_0_vpu_vuopIdx;
  logic s1_ctrl_8_0_vpu_isExt;
  logic s1_ctrl_8_0_vpu_isNarrow;
  logic s1_ctrl_8_0_vpu_isDstMask;
  logic s1_ctrl_8_0_vpu_isOpMask;
  logic [3:0] s1_ctrl_8_0_dataSources_0_value;
  logic [3:0] s1_ctrl_8_0_dataSources_1_value;
  logic [3:0] s1_ctrl_8_0_dataSources_2_value;
  logic [3:0] s1_ctrl_8_0_dataSources_3_value;
  logic [3:0] s1_ctrl_8_0_dataSources_4_value;
  always_ff @(posedge clock) if (io_fromVfIQ_1_0_valid) begin
    s1_ctrl_8_0_fuType <= io_fromVfIQ_1_0_bits_common_fuType;
    s1_ctrl_8_0_fuOpType <= io_fromVfIQ_1_0_bits_common_fuOpType;
    s1_ctrl_8_0_robIdx_flag <= io_fromVfIQ_1_0_bits_common_robIdx_flag;
    s1_ctrl_8_0_robIdx_value <= io_fromVfIQ_1_0_bits_common_robIdx_value;
    s1_ctrl_8_0_pdest <= io_fromVfIQ_1_0_bits_common_pdest;
    s1_ctrl_8_0_vecWen <= io_fromVfIQ_1_0_bits_common_vecWen;
    s1_ctrl_8_0_v0Wen <= io_fromVfIQ_1_0_bits_common_v0Wen;
    s1_ctrl_8_0_fpu_wflags <= io_fromVfIQ_1_0_bits_common_fpu_wflags;
    s1_ctrl_8_0_vpu_vma <= io_fromVfIQ_1_0_bits_common_vpu_vma;
    s1_ctrl_8_0_vpu_vta <= io_fromVfIQ_1_0_bits_common_vpu_vta;
    s1_ctrl_8_0_vpu_vsew <= io_fromVfIQ_1_0_bits_common_vpu_vsew;
    s1_ctrl_8_0_vpu_vlmul <= io_fromVfIQ_1_0_bits_common_vpu_vlmul;
    s1_ctrl_8_0_vpu_vm <= io_fromVfIQ_1_0_bits_common_vpu_vm;
    s1_ctrl_8_0_vpu_vstart <= io_fromVfIQ_1_0_bits_common_vpu_vstart;
    s1_ctrl_8_0_vpu_vuopIdx <= io_fromVfIQ_1_0_bits_common_vpu_vuopIdx;
    s1_ctrl_8_0_vpu_isExt <= io_fromVfIQ_1_0_bits_common_vpu_isExt;
    s1_ctrl_8_0_vpu_isNarrow <= io_fromVfIQ_1_0_bits_common_vpu_isNarrow;
    s1_ctrl_8_0_vpu_isDstMask <= io_fromVfIQ_1_0_bits_common_vpu_isDstMask;
    s1_ctrl_8_0_vpu_isOpMask <= io_fromVfIQ_1_0_bits_common_vpu_isOpMask;
    s1_ctrl_8_0_dataSources_0_value <= io_fromVfIQ_1_0_bits_common_dataSources_0_value;
    s1_ctrl_8_0_dataSources_1_value <= io_fromVfIQ_1_0_bits_common_dataSources_1_value;
    s1_ctrl_8_0_dataSources_2_value <= io_fromVfIQ_1_0_bits_common_dataSources_2_value;
    s1_ctrl_8_0_dataSources_3_value <= io_fromVfIQ_1_0_bits_common_dataSources_3_value;
    s1_ctrl_8_0_dataSources_4_value <= io_fromVfIQ_1_0_bits_common_dataSources_4_value;
  end
  // EXU g8.1 ctrl 流水寄存器
  logic [34:0] s1_ctrl_8_1_fuType;
  logic [8:0] s1_ctrl_8_1_fuOpType;
  logic s1_ctrl_8_1_robIdx_flag;
  logic [7:0] s1_ctrl_8_1_robIdx_value;
  logic [7:0] s1_ctrl_8_1_pdest;
  logic s1_ctrl_8_1_fpWen;
  logic s1_ctrl_8_1_vecWen;
  logic s1_ctrl_8_1_v0Wen;
  logic s1_ctrl_8_1_fpu_wflags;
  logic s1_ctrl_8_1_vpu_vma;
  logic s1_ctrl_8_1_vpu_vta;
  logic [1:0] s1_ctrl_8_1_vpu_vsew;
  logic [2:0] s1_ctrl_8_1_vpu_vlmul;
  logic s1_ctrl_8_1_vpu_vm;
  logic [7:0] s1_ctrl_8_1_vpu_vstart;
  logic s1_ctrl_8_1_vpu_fpu_isFoldTo1_2;
  logic s1_ctrl_8_1_vpu_fpu_isFoldTo1_4;
  logic s1_ctrl_8_1_vpu_fpu_isFoldTo1_8;
  logic [6:0] s1_ctrl_8_1_vpu_vuopIdx;
  logic s1_ctrl_8_1_vpu_lastUop;
  logic s1_ctrl_8_1_vpu_isNarrow;
  logic s1_ctrl_8_1_vpu_isDstMask;
  logic [3:0] s1_ctrl_8_1_dataSources_0_value;
  logic [3:0] s1_ctrl_8_1_dataSources_1_value;
  logic [3:0] s1_ctrl_8_1_dataSources_2_value;
  logic [3:0] s1_ctrl_8_1_dataSources_3_value;
  logic [3:0] s1_ctrl_8_1_dataSources_4_value;
  always_ff @(posedge clock) if (io_fromVfIQ_1_1_valid) begin
    s1_ctrl_8_1_fuType <= io_fromVfIQ_1_1_bits_common_fuType;
    s1_ctrl_8_1_fuOpType <= io_fromVfIQ_1_1_bits_common_fuOpType;
    s1_ctrl_8_1_robIdx_flag <= io_fromVfIQ_1_1_bits_common_robIdx_flag;
    s1_ctrl_8_1_robIdx_value <= io_fromVfIQ_1_1_bits_common_robIdx_value;
    s1_ctrl_8_1_pdest <= io_fromVfIQ_1_1_bits_common_pdest;
    s1_ctrl_8_1_fpWen <= io_fromVfIQ_1_1_bits_common_fpWen;
    s1_ctrl_8_1_vecWen <= io_fromVfIQ_1_1_bits_common_vecWen;
    s1_ctrl_8_1_v0Wen <= io_fromVfIQ_1_1_bits_common_v0Wen;
    s1_ctrl_8_1_fpu_wflags <= io_fromVfIQ_1_1_bits_common_fpu_wflags;
    s1_ctrl_8_1_vpu_vma <= io_fromVfIQ_1_1_bits_common_vpu_vma;
    s1_ctrl_8_1_vpu_vta <= io_fromVfIQ_1_1_bits_common_vpu_vta;
    s1_ctrl_8_1_vpu_vsew <= io_fromVfIQ_1_1_bits_common_vpu_vsew;
    s1_ctrl_8_1_vpu_vlmul <= io_fromVfIQ_1_1_bits_common_vpu_vlmul;
    s1_ctrl_8_1_vpu_vm <= io_fromVfIQ_1_1_bits_common_vpu_vm;
    s1_ctrl_8_1_vpu_vstart <= io_fromVfIQ_1_1_bits_common_vpu_vstart;
    s1_ctrl_8_1_vpu_fpu_isFoldTo1_2 <= io_fromVfIQ_1_1_bits_common_vpu_fpu_isFoldTo1_2;
    s1_ctrl_8_1_vpu_fpu_isFoldTo1_4 <= io_fromVfIQ_1_1_bits_common_vpu_fpu_isFoldTo1_4;
    s1_ctrl_8_1_vpu_fpu_isFoldTo1_8 <= io_fromVfIQ_1_1_bits_common_vpu_fpu_isFoldTo1_8;
    s1_ctrl_8_1_vpu_vuopIdx <= io_fromVfIQ_1_1_bits_common_vpu_vuopIdx;
    s1_ctrl_8_1_vpu_lastUop <= io_fromVfIQ_1_1_bits_common_vpu_lastUop;
    s1_ctrl_8_1_vpu_isNarrow <= io_fromVfIQ_1_1_bits_common_vpu_isNarrow;
    s1_ctrl_8_1_vpu_isDstMask <= io_fromVfIQ_1_1_bits_common_vpu_isDstMask;
    s1_ctrl_8_1_dataSources_0_value <= io_fromVfIQ_1_1_bits_common_dataSources_0_value;
    s1_ctrl_8_1_dataSources_1_value <= io_fromVfIQ_1_1_bits_common_dataSources_1_value;
    s1_ctrl_8_1_dataSources_2_value <= io_fromVfIQ_1_1_bits_common_dataSources_2_value;
    s1_ctrl_8_1_dataSources_3_value <= io_fromVfIQ_1_1_bits_common_dataSources_3_value;
    s1_ctrl_8_1_dataSources_4_value <= io_fromVfIQ_1_1_bits_common_dataSources_4_value;
  end
  // EXU g9.0 ctrl 流水寄存器
  logic [34:0] s1_ctrl_9_0_fuType;
  logic [8:0] s1_ctrl_9_0_fuOpType;
  logic s1_ctrl_9_0_robIdx_flag;
  logic [7:0] s1_ctrl_9_0_robIdx_value;
  logic [6:0] s1_ctrl_9_0_pdest;
  logic s1_ctrl_9_0_vecWen;
  logic s1_ctrl_9_0_v0Wen;
  logic s1_ctrl_9_0_fpu_wflags;
  logic s1_ctrl_9_0_vpu_vma;
  logic s1_ctrl_9_0_vpu_vta;
  logic [1:0] s1_ctrl_9_0_vpu_vsew;
  logic [2:0] s1_ctrl_9_0_vpu_vlmul;
  logic s1_ctrl_9_0_vpu_vm;
  logic [7:0] s1_ctrl_9_0_vpu_vstart;
  logic [6:0] s1_ctrl_9_0_vpu_vuopIdx;
  logic s1_ctrl_9_0_vpu_isExt;
  logic s1_ctrl_9_0_vpu_isNarrow;
  logic s1_ctrl_9_0_vpu_isDstMask;
  logic s1_ctrl_9_0_vpu_isOpMask;
  logic [3:0] s1_ctrl_9_0_dataSources_0_value;
  logic [3:0] s1_ctrl_9_0_dataSources_1_value;
  logic [3:0] s1_ctrl_9_0_dataSources_2_value;
  logic [3:0] s1_ctrl_9_0_dataSources_3_value;
  logic [3:0] s1_ctrl_9_0_dataSources_4_value;
  always_ff @(posedge clock) if (io_fromVfIQ_2_0_valid) begin
    s1_ctrl_9_0_fuType <= io_fromVfIQ_2_0_bits_common_fuType;
    s1_ctrl_9_0_fuOpType <= io_fromVfIQ_2_0_bits_common_fuOpType;
    s1_ctrl_9_0_robIdx_flag <= io_fromVfIQ_2_0_bits_common_robIdx_flag;
    s1_ctrl_9_0_robIdx_value <= io_fromVfIQ_2_0_bits_common_robIdx_value;
    s1_ctrl_9_0_pdest <= io_fromVfIQ_2_0_bits_common_pdest;
    s1_ctrl_9_0_vecWen <= io_fromVfIQ_2_0_bits_common_vecWen;
    s1_ctrl_9_0_v0Wen <= io_fromVfIQ_2_0_bits_common_v0Wen;
    s1_ctrl_9_0_fpu_wflags <= io_fromVfIQ_2_0_bits_common_fpu_wflags;
    s1_ctrl_9_0_vpu_vma <= io_fromVfIQ_2_0_bits_common_vpu_vma;
    s1_ctrl_9_0_vpu_vta <= io_fromVfIQ_2_0_bits_common_vpu_vta;
    s1_ctrl_9_0_vpu_vsew <= io_fromVfIQ_2_0_bits_common_vpu_vsew;
    s1_ctrl_9_0_vpu_vlmul <= io_fromVfIQ_2_0_bits_common_vpu_vlmul;
    s1_ctrl_9_0_vpu_vm <= io_fromVfIQ_2_0_bits_common_vpu_vm;
    s1_ctrl_9_0_vpu_vstart <= io_fromVfIQ_2_0_bits_common_vpu_vstart;
    s1_ctrl_9_0_vpu_vuopIdx <= io_fromVfIQ_2_0_bits_common_vpu_vuopIdx;
    s1_ctrl_9_0_vpu_isExt <= io_fromVfIQ_2_0_bits_common_vpu_isExt;
    s1_ctrl_9_0_vpu_isNarrow <= io_fromVfIQ_2_0_bits_common_vpu_isNarrow;
    s1_ctrl_9_0_vpu_isDstMask <= io_fromVfIQ_2_0_bits_common_vpu_isDstMask;
    s1_ctrl_9_0_vpu_isOpMask <= io_fromVfIQ_2_0_bits_common_vpu_isOpMask;
    s1_ctrl_9_0_dataSources_0_value <= io_fromVfIQ_2_0_bits_common_dataSources_0_value;
    s1_ctrl_9_0_dataSources_1_value <= io_fromVfIQ_2_0_bits_common_dataSources_1_value;
    s1_ctrl_9_0_dataSources_2_value <= io_fromVfIQ_2_0_bits_common_dataSources_2_value;
    s1_ctrl_9_0_dataSources_3_value <= io_fromVfIQ_2_0_bits_common_dataSources_3_value;
    s1_ctrl_9_0_dataSources_4_value <= io_fromVfIQ_2_0_bits_common_dataSources_4_value;
  end
  // EXU g10.0 ctrl 流水寄存器
  logic [34:0] s1_ctrl_10_0_fuType;
  logic [8:0] s1_ctrl_10_0_fuOpType;
  logic [63:0] s1_ctrl_10_0_imm;
  logic s1_ctrl_10_0_robIdx_flag;
  logic [7:0] s1_ctrl_10_0_robIdx_value;
  logic s1_ctrl_10_0_isFirstIssue;
  logic [7:0] s1_ctrl_10_0_pdest;
  logic s1_ctrl_10_0_rfWen;
  logic [5:0] s1_ctrl_10_0_ftqIdx_value;
  logic [3:0] s1_ctrl_10_0_ftqOffset;
  logic s1_ctrl_10_0_sqIdx_flag;
  logic [5:0] s1_ctrl_10_0_sqIdx_value;
  logic [3:0] s1_ctrl_10_0_dataSources_0_value;
  logic [2:0] s1_ctrl_10_0_exuSources_0_value;
  logic [1:0] s1_ctrl_10_0_loadDependency_0;
  logic [1:0] s1_ctrl_10_0_loadDependency_1;
  logic [1:0] s1_ctrl_10_0_loadDependency_2;
  always_ff @(posedge clock) if (io_fromMemIQ_0_0_valid) begin
    s1_ctrl_10_0_fuType <= io_fromMemIQ_0_0_bits_common_fuType;
    s1_ctrl_10_0_fuOpType <= io_fromMemIQ_0_0_bits_common_fuOpType;
    s1_ctrl_10_0_imm <= io_fromMemIQ_0_0_bits_common_imm;
    s1_ctrl_10_0_robIdx_flag <= io_fromMemIQ_0_0_bits_common_robIdx_flag;
    s1_ctrl_10_0_robIdx_value <= io_fromMemIQ_0_0_bits_common_robIdx_value;
    s1_ctrl_10_0_isFirstIssue <= io_fromMemIQ_0_0_bits_common_isFirstIssue;
    s1_ctrl_10_0_pdest <= io_fromMemIQ_0_0_bits_common_pdest;
    s1_ctrl_10_0_rfWen <= io_fromMemIQ_0_0_bits_common_rfWen;
    s1_ctrl_10_0_ftqIdx_value <= io_fromMemIQ_0_0_bits_common_ftqIdx_value;
    s1_ctrl_10_0_ftqOffset <= io_fromMemIQ_0_0_bits_common_ftqOffset;
    s1_ctrl_10_0_sqIdx_flag <= io_fromMemIQ_0_0_bits_common_sqIdx_flag;
    s1_ctrl_10_0_sqIdx_value <= io_fromMemIQ_0_0_bits_common_sqIdx_value;
    s1_ctrl_10_0_dataSources_0_value <= io_fromMemIQ_0_0_bits_common_dataSources_0_value;
    s1_ctrl_10_0_exuSources_0_value <= io_fromMemIQ_0_0_bits_common_exuSources_0_value;
    s1_ctrl_10_0_loadDependency_0 <= {io_fromMemIQ_0_0_bits_common_loadDependency_0[0], 1'b0};
    s1_ctrl_10_0_loadDependency_1 <= {io_fromMemIQ_0_0_bits_common_loadDependency_1[0], 1'b0};
    s1_ctrl_10_0_loadDependency_2 <= {io_fromMemIQ_0_0_bits_common_loadDependency_2[0], 1'b0};
  end
  // EXU g11.0 ctrl 流水寄存器
  logic [34:0] s1_ctrl_11_0_fuType;
  logic [8:0] s1_ctrl_11_0_fuOpType;
  logic [63:0] s1_ctrl_11_0_imm;
  logic s1_ctrl_11_0_robIdx_flag;
  logic [7:0] s1_ctrl_11_0_robIdx_value;
  logic s1_ctrl_11_0_isFirstIssue;
  logic [7:0] s1_ctrl_11_0_pdest;
  logic s1_ctrl_11_0_rfWen;
  logic [5:0] s1_ctrl_11_0_ftqIdx_value;
  logic [3:0] s1_ctrl_11_0_ftqOffset;
  logic s1_ctrl_11_0_sqIdx_flag;
  logic [5:0] s1_ctrl_11_0_sqIdx_value;
  logic [3:0] s1_ctrl_11_0_dataSources_0_value;
  logic [2:0] s1_ctrl_11_0_exuSources_0_value;
  logic [1:0] s1_ctrl_11_0_loadDependency_0;
  logic [1:0] s1_ctrl_11_0_loadDependency_1;
  logic [1:0] s1_ctrl_11_0_loadDependency_2;
  always_ff @(posedge clock) if (io_fromMemIQ_1_0_valid) begin
    s1_ctrl_11_0_fuType <= io_fromMemIQ_1_0_bits_common_fuType;
    s1_ctrl_11_0_fuOpType <= io_fromMemIQ_1_0_bits_common_fuOpType;
    s1_ctrl_11_0_imm <= io_fromMemIQ_1_0_bits_common_imm;
    s1_ctrl_11_0_robIdx_flag <= io_fromMemIQ_1_0_bits_common_robIdx_flag;
    s1_ctrl_11_0_robIdx_value <= io_fromMemIQ_1_0_bits_common_robIdx_value;
    s1_ctrl_11_0_isFirstIssue <= io_fromMemIQ_1_0_bits_common_isFirstIssue;
    s1_ctrl_11_0_pdest <= io_fromMemIQ_1_0_bits_common_pdest;
    s1_ctrl_11_0_rfWen <= io_fromMemIQ_1_0_bits_common_rfWen;
    s1_ctrl_11_0_ftqIdx_value <= io_fromMemIQ_1_0_bits_common_ftqIdx_value;
    s1_ctrl_11_0_ftqOffset <= io_fromMemIQ_1_0_bits_common_ftqOffset;
    s1_ctrl_11_0_sqIdx_flag <= io_fromMemIQ_1_0_bits_common_sqIdx_flag;
    s1_ctrl_11_0_sqIdx_value <= io_fromMemIQ_1_0_bits_common_sqIdx_value;
    s1_ctrl_11_0_dataSources_0_value <= io_fromMemIQ_1_0_bits_common_dataSources_0_value;
    s1_ctrl_11_0_exuSources_0_value <= io_fromMemIQ_1_0_bits_common_exuSources_0_value;
    s1_ctrl_11_0_loadDependency_0 <= {io_fromMemIQ_1_0_bits_common_loadDependency_0[0], 1'b0};
    s1_ctrl_11_0_loadDependency_1 <= {io_fromMemIQ_1_0_bits_common_loadDependency_1[0], 1'b0};
    s1_ctrl_11_0_loadDependency_2 <= {io_fromMemIQ_1_0_bits_common_loadDependency_2[0], 1'b0};
  end
  // EXU g12.0 ctrl 流水寄存器
  logic [34:0] s1_ctrl_12_0_fuType;
  logic [8:0] s1_ctrl_12_0_fuOpType;
  logic [63:0] s1_ctrl_12_0_imm;
  logic s1_ctrl_12_0_robIdx_flag;
  logic [7:0] s1_ctrl_12_0_robIdx_value;
  logic [7:0] s1_ctrl_12_0_pdest;
  logic s1_ctrl_12_0_rfWen;
  logic s1_ctrl_12_0_fpWen;
  logic s1_ctrl_12_0_preDecode_isRVC;
  logic s1_ctrl_12_0_ftqIdx_flag;
  logic [5:0] s1_ctrl_12_0_ftqIdx_value;
  logic [3:0] s1_ctrl_12_0_ftqOffset;
  logic s1_ctrl_12_0_loadWaitBit;
  logic s1_ctrl_12_0_waitForRobIdx_flag;
  logic [7:0] s1_ctrl_12_0_waitForRobIdx_value;
  logic s1_ctrl_12_0_storeSetHit;
  logic s1_ctrl_12_0_loadWaitStrict;
  logic s1_ctrl_12_0_sqIdx_flag;
  logic [5:0] s1_ctrl_12_0_sqIdx_value;
  logic s1_ctrl_12_0_lqIdx_flag;
  logic [6:0] s1_ctrl_12_0_lqIdx_value;
  logic [3:0] s1_ctrl_12_0_dataSources_0_value;
  logic [2:0] s1_ctrl_12_0_exuSources_0_value;
  logic [1:0] s1_ctrl_12_0_loadDependency_0;
  logic [1:0] s1_ctrl_12_0_loadDependency_1;
  logic [1:0] s1_ctrl_12_0_loadDependency_2;
  always_ff @(posedge clock) if (io_fromMemIQ_2_0_valid) begin
    s1_ctrl_12_0_fuType <= io_fromMemIQ_2_0_bits_common_fuType;
    s1_ctrl_12_0_fuOpType <= io_fromMemIQ_2_0_bits_common_fuOpType;
    s1_ctrl_12_0_imm <= io_fromMemIQ_2_0_bits_common_imm;
    s1_ctrl_12_0_robIdx_flag <= io_fromMemIQ_2_0_bits_common_robIdx_flag;
    s1_ctrl_12_0_robIdx_value <= io_fromMemIQ_2_0_bits_common_robIdx_value;
    s1_ctrl_12_0_pdest <= io_fromMemIQ_2_0_bits_common_pdest;
    s1_ctrl_12_0_rfWen <= io_fromMemIQ_2_0_bits_common_rfWen;
    s1_ctrl_12_0_fpWen <= io_fromMemIQ_2_0_bits_common_fpWen;
    s1_ctrl_12_0_preDecode_isRVC <= io_fromMemIQ_2_0_bits_common_preDecode_isRVC;
    s1_ctrl_12_0_ftqIdx_flag <= io_fromMemIQ_2_0_bits_common_ftqIdx_flag;
    s1_ctrl_12_0_ftqIdx_value <= io_fromMemIQ_2_0_bits_common_ftqIdx_value;
    s1_ctrl_12_0_ftqOffset <= io_fromMemIQ_2_0_bits_common_ftqOffset;
    s1_ctrl_12_0_loadWaitBit <= io_fromMemIQ_2_0_bits_common_loadWaitBit;
    s1_ctrl_12_0_waitForRobIdx_flag <= io_fromMemIQ_2_0_bits_common_waitForRobIdx_flag;
    s1_ctrl_12_0_waitForRobIdx_value <= io_fromMemIQ_2_0_bits_common_waitForRobIdx_value;
    s1_ctrl_12_0_storeSetHit <= io_fromMemIQ_2_0_bits_common_storeSetHit;
    s1_ctrl_12_0_loadWaitStrict <= io_fromMemIQ_2_0_bits_common_loadWaitStrict;
    s1_ctrl_12_0_sqIdx_flag <= io_fromMemIQ_2_0_bits_common_sqIdx_flag;
    s1_ctrl_12_0_sqIdx_value <= io_fromMemIQ_2_0_bits_common_sqIdx_value;
    s1_ctrl_12_0_lqIdx_flag <= io_fromMemIQ_2_0_bits_common_lqIdx_flag;
    s1_ctrl_12_0_lqIdx_value <= io_fromMemIQ_2_0_bits_common_lqIdx_value;
    s1_ctrl_12_0_dataSources_0_value <= io_fromMemIQ_2_0_bits_common_dataSources_0_value;
    s1_ctrl_12_0_exuSources_0_value <= io_fromMemIQ_2_0_bits_common_exuSources_0_value;
    s1_ctrl_12_0_loadDependency_0 <= {io_fromMemIQ_2_0_bits_common_loadDependency_0[0], 1'b0};
    s1_ctrl_12_0_loadDependency_1 <= {io_fromMemIQ_2_0_bits_common_loadDependency_1[0], 1'b0};
    s1_ctrl_12_0_loadDependency_2 <= {io_fromMemIQ_2_0_bits_common_loadDependency_2[0], 1'b0};
  end
  // EXU g13.0 ctrl 流水寄存器
  logic [34:0] s1_ctrl_13_0_fuType;
  logic [8:0] s1_ctrl_13_0_fuOpType;
  logic [63:0] s1_ctrl_13_0_imm;
  logic s1_ctrl_13_0_robIdx_flag;
  logic [7:0] s1_ctrl_13_0_robIdx_value;
  logic [7:0] s1_ctrl_13_0_pdest;
  logic s1_ctrl_13_0_rfWen;
  logic s1_ctrl_13_0_fpWen;
  logic s1_ctrl_13_0_preDecode_isRVC;
  logic s1_ctrl_13_0_ftqIdx_flag;
  logic [5:0] s1_ctrl_13_0_ftqIdx_value;
  logic [3:0] s1_ctrl_13_0_ftqOffset;
  logic s1_ctrl_13_0_loadWaitBit;
  logic s1_ctrl_13_0_waitForRobIdx_flag;
  logic [7:0] s1_ctrl_13_0_waitForRobIdx_value;
  logic s1_ctrl_13_0_storeSetHit;
  logic s1_ctrl_13_0_loadWaitStrict;
  logic s1_ctrl_13_0_sqIdx_flag;
  logic [5:0] s1_ctrl_13_0_sqIdx_value;
  logic s1_ctrl_13_0_lqIdx_flag;
  logic [6:0] s1_ctrl_13_0_lqIdx_value;
  logic [3:0] s1_ctrl_13_0_dataSources_0_value;
  logic [2:0] s1_ctrl_13_0_exuSources_0_value;
  logic [1:0] s1_ctrl_13_0_loadDependency_0;
  logic [1:0] s1_ctrl_13_0_loadDependency_1;
  logic [1:0] s1_ctrl_13_0_loadDependency_2;
  always_ff @(posedge clock) if (io_fromMemIQ_3_0_valid) begin
    s1_ctrl_13_0_fuType <= io_fromMemIQ_3_0_bits_common_fuType;
    s1_ctrl_13_0_fuOpType <= io_fromMemIQ_3_0_bits_common_fuOpType;
    s1_ctrl_13_0_imm <= io_fromMemIQ_3_0_bits_common_imm;
    s1_ctrl_13_0_robIdx_flag <= io_fromMemIQ_3_0_bits_common_robIdx_flag;
    s1_ctrl_13_0_robIdx_value <= io_fromMemIQ_3_0_bits_common_robIdx_value;
    s1_ctrl_13_0_pdest <= io_fromMemIQ_3_0_bits_common_pdest;
    s1_ctrl_13_0_rfWen <= io_fromMemIQ_3_0_bits_common_rfWen;
    s1_ctrl_13_0_fpWen <= io_fromMemIQ_3_0_bits_common_fpWen;
    s1_ctrl_13_0_preDecode_isRVC <= io_fromMemIQ_3_0_bits_common_preDecode_isRVC;
    s1_ctrl_13_0_ftqIdx_flag <= io_fromMemIQ_3_0_bits_common_ftqIdx_flag;
    s1_ctrl_13_0_ftqIdx_value <= io_fromMemIQ_3_0_bits_common_ftqIdx_value;
    s1_ctrl_13_0_ftqOffset <= io_fromMemIQ_3_0_bits_common_ftqOffset;
    s1_ctrl_13_0_loadWaitBit <= io_fromMemIQ_3_0_bits_common_loadWaitBit;
    s1_ctrl_13_0_waitForRobIdx_flag <= io_fromMemIQ_3_0_bits_common_waitForRobIdx_flag;
    s1_ctrl_13_0_waitForRobIdx_value <= io_fromMemIQ_3_0_bits_common_waitForRobIdx_value;
    s1_ctrl_13_0_storeSetHit <= io_fromMemIQ_3_0_bits_common_storeSetHit;
    s1_ctrl_13_0_loadWaitStrict <= io_fromMemIQ_3_0_bits_common_loadWaitStrict;
    s1_ctrl_13_0_sqIdx_flag <= io_fromMemIQ_3_0_bits_common_sqIdx_flag;
    s1_ctrl_13_0_sqIdx_value <= io_fromMemIQ_3_0_bits_common_sqIdx_value;
    s1_ctrl_13_0_lqIdx_flag <= io_fromMemIQ_3_0_bits_common_lqIdx_flag;
    s1_ctrl_13_0_lqIdx_value <= io_fromMemIQ_3_0_bits_common_lqIdx_value;
    s1_ctrl_13_0_dataSources_0_value <= io_fromMemIQ_3_0_bits_common_dataSources_0_value;
    s1_ctrl_13_0_exuSources_0_value <= io_fromMemIQ_3_0_bits_common_exuSources_0_value;
    s1_ctrl_13_0_loadDependency_0 <= {io_fromMemIQ_3_0_bits_common_loadDependency_0[0], 1'b0};
    s1_ctrl_13_0_loadDependency_1 <= {io_fromMemIQ_3_0_bits_common_loadDependency_1[0], 1'b0};
    s1_ctrl_13_0_loadDependency_2 <= {io_fromMemIQ_3_0_bits_common_loadDependency_2[0], 1'b0};
  end
  // EXU g14.0 ctrl 流水寄存器
  logic [34:0] s1_ctrl_14_0_fuType;
  logic [8:0] s1_ctrl_14_0_fuOpType;
  logic [63:0] s1_ctrl_14_0_imm;
  logic s1_ctrl_14_0_robIdx_flag;
  logic [7:0] s1_ctrl_14_0_robIdx_value;
  logic [7:0] s1_ctrl_14_0_pdest;
  logic s1_ctrl_14_0_rfWen;
  logic s1_ctrl_14_0_fpWen;
  logic s1_ctrl_14_0_preDecode_isRVC;
  logic s1_ctrl_14_0_ftqIdx_flag;
  logic [5:0] s1_ctrl_14_0_ftqIdx_value;
  logic [3:0] s1_ctrl_14_0_ftqOffset;
  logic s1_ctrl_14_0_loadWaitBit;
  logic s1_ctrl_14_0_waitForRobIdx_flag;
  logic [7:0] s1_ctrl_14_0_waitForRobIdx_value;
  logic s1_ctrl_14_0_storeSetHit;
  logic s1_ctrl_14_0_loadWaitStrict;
  logic s1_ctrl_14_0_sqIdx_flag;
  logic [5:0] s1_ctrl_14_0_sqIdx_value;
  logic s1_ctrl_14_0_lqIdx_flag;
  logic [6:0] s1_ctrl_14_0_lqIdx_value;
  logic [3:0] s1_ctrl_14_0_dataSources_0_value;
  logic [2:0] s1_ctrl_14_0_exuSources_0_value;
  logic [1:0] s1_ctrl_14_0_loadDependency_0;
  logic [1:0] s1_ctrl_14_0_loadDependency_1;
  logic [1:0] s1_ctrl_14_0_loadDependency_2;
  always_ff @(posedge clock) if (io_fromMemIQ_4_0_valid) begin
    s1_ctrl_14_0_fuType <= io_fromMemIQ_4_0_bits_common_fuType;
    s1_ctrl_14_0_fuOpType <= io_fromMemIQ_4_0_bits_common_fuOpType;
    s1_ctrl_14_0_imm <= io_fromMemIQ_4_0_bits_common_imm;
    s1_ctrl_14_0_robIdx_flag <= io_fromMemIQ_4_0_bits_common_robIdx_flag;
    s1_ctrl_14_0_robIdx_value <= io_fromMemIQ_4_0_bits_common_robIdx_value;
    s1_ctrl_14_0_pdest <= io_fromMemIQ_4_0_bits_common_pdest;
    s1_ctrl_14_0_rfWen <= io_fromMemIQ_4_0_bits_common_rfWen;
    s1_ctrl_14_0_fpWen <= io_fromMemIQ_4_0_bits_common_fpWen;
    s1_ctrl_14_0_preDecode_isRVC <= io_fromMemIQ_4_0_bits_common_preDecode_isRVC;
    s1_ctrl_14_0_ftqIdx_flag <= io_fromMemIQ_4_0_bits_common_ftqIdx_flag;
    s1_ctrl_14_0_ftqIdx_value <= io_fromMemIQ_4_0_bits_common_ftqIdx_value;
    s1_ctrl_14_0_ftqOffset <= io_fromMemIQ_4_0_bits_common_ftqOffset;
    s1_ctrl_14_0_loadWaitBit <= io_fromMemIQ_4_0_bits_common_loadWaitBit;
    s1_ctrl_14_0_waitForRobIdx_flag <= io_fromMemIQ_4_0_bits_common_waitForRobIdx_flag;
    s1_ctrl_14_0_waitForRobIdx_value <= io_fromMemIQ_4_0_bits_common_waitForRobIdx_value;
    s1_ctrl_14_0_storeSetHit <= io_fromMemIQ_4_0_bits_common_storeSetHit;
    s1_ctrl_14_0_loadWaitStrict <= io_fromMemIQ_4_0_bits_common_loadWaitStrict;
    s1_ctrl_14_0_sqIdx_flag <= io_fromMemIQ_4_0_bits_common_sqIdx_flag;
    s1_ctrl_14_0_sqIdx_value <= io_fromMemIQ_4_0_bits_common_sqIdx_value;
    s1_ctrl_14_0_lqIdx_flag <= io_fromMemIQ_4_0_bits_common_lqIdx_flag;
    s1_ctrl_14_0_lqIdx_value <= io_fromMemIQ_4_0_bits_common_lqIdx_value;
    s1_ctrl_14_0_dataSources_0_value <= io_fromMemIQ_4_0_bits_common_dataSources_0_value;
    s1_ctrl_14_0_exuSources_0_value <= io_fromMemIQ_4_0_bits_common_exuSources_0_value;
    s1_ctrl_14_0_loadDependency_0 <= {io_fromMemIQ_4_0_bits_common_loadDependency_0[0], 1'b0};
    s1_ctrl_14_0_loadDependency_1 <= {io_fromMemIQ_4_0_bits_common_loadDependency_1[0], 1'b0};
    s1_ctrl_14_0_loadDependency_2 <= {io_fromMemIQ_4_0_bits_common_loadDependency_2[0], 1'b0};
  end
  // EXU g15.0 ctrl 流水寄存器
  logic [34:0] s1_ctrl_15_0_fuType;
  logic [8:0] s1_ctrl_15_0_fuOpType;
  logic s1_ctrl_15_0_robIdx_flag;
  logic [7:0] s1_ctrl_15_0_robIdx_value;
  logic [6:0] s1_ctrl_15_0_pdest;
  logic s1_ctrl_15_0_vecWen;
  logic s1_ctrl_15_0_v0Wen;
  logic s1_ctrl_15_0_vlWen;
  logic s1_ctrl_15_0_vpu_vma;
  logic s1_ctrl_15_0_vpu_vta;
  logic [1:0] s1_ctrl_15_0_vpu_vsew;
  logic [2:0] s1_ctrl_15_0_vpu_vlmul;
  logic s1_ctrl_15_0_vpu_vm;
  logic [7:0] s1_ctrl_15_0_vpu_vstart;
  logic [6:0] s1_ctrl_15_0_vpu_vuopIdx;
  logic s1_ctrl_15_0_vpu_lastUop;
  logic [127:0] s1_ctrl_15_0_vpu_vmask;
  logic [2:0] s1_ctrl_15_0_vpu_nf;
  logic [1:0] s1_ctrl_15_0_vpu_veew;
  logic s1_ctrl_15_0_vpu_isVleff;
  logic s1_ctrl_15_0_ftqIdx_flag;
  logic [5:0] s1_ctrl_15_0_ftqIdx_value;
  logic [3:0] s1_ctrl_15_0_ftqOffset;
  logic [4:0] s1_ctrl_15_0_numLsElem;
  logic s1_ctrl_15_0_sqIdx_flag;
  logic [5:0] s1_ctrl_15_0_sqIdx_value;
  logic s1_ctrl_15_0_lqIdx_flag;
  logic [6:0] s1_ctrl_15_0_lqIdx_value;
  logic [3:0] s1_ctrl_15_0_dataSources_0_value;
  logic [3:0] s1_ctrl_15_0_dataSources_1_value;
  logic [3:0] s1_ctrl_15_0_dataSources_2_value;
  logic [3:0] s1_ctrl_15_0_dataSources_3_value;
  logic [3:0] s1_ctrl_15_0_dataSources_4_value;
  always_ff @(posedge clock) if (io_fromMemIQ_5_0_valid) begin
    s1_ctrl_15_0_fuType <= io_fromMemIQ_5_0_bits_common_fuType;
    s1_ctrl_15_0_fuOpType <= io_fromMemIQ_5_0_bits_common_fuOpType;
    s1_ctrl_15_0_robIdx_flag <= io_fromMemIQ_5_0_bits_common_robIdx_flag;
    s1_ctrl_15_0_robIdx_value <= io_fromMemIQ_5_0_bits_common_robIdx_value;
    s1_ctrl_15_0_pdest <= io_fromMemIQ_5_0_bits_common_pdest;
    s1_ctrl_15_0_vecWen <= io_fromMemIQ_5_0_bits_common_vecWen;
    s1_ctrl_15_0_v0Wen <= io_fromMemIQ_5_0_bits_common_v0Wen;
    s1_ctrl_15_0_vlWen <= io_fromMemIQ_5_0_bits_common_vlWen;
    s1_ctrl_15_0_vpu_vma <= io_fromMemIQ_5_0_bits_common_vpu_vma;
    s1_ctrl_15_0_vpu_vta <= io_fromMemIQ_5_0_bits_common_vpu_vta;
    s1_ctrl_15_0_vpu_vsew <= io_fromMemIQ_5_0_bits_common_vpu_vsew;
    s1_ctrl_15_0_vpu_vlmul <= io_fromMemIQ_5_0_bits_common_vpu_vlmul;
    s1_ctrl_15_0_vpu_vm <= io_fromMemIQ_5_0_bits_common_vpu_vm;
    s1_ctrl_15_0_vpu_vstart <= io_fromMemIQ_5_0_bits_common_vpu_vstart;
    s1_ctrl_15_0_vpu_vuopIdx <= io_fromMemIQ_5_0_bits_common_vpu_vuopIdx;
    s1_ctrl_15_0_vpu_lastUop <= io_fromMemIQ_5_0_bits_common_vpu_lastUop;
    s1_ctrl_15_0_vpu_vmask <= io_fromMemIQ_5_0_bits_common_vpu_vmask;
    s1_ctrl_15_0_vpu_nf <= io_fromMemIQ_5_0_bits_common_vpu_nf;
    s1_ctrl_15_0_vpu_veew <= io_fromMemIQ_5_0_bits_common_vpu_veew;
    s1_ctrl_15_0_vpu_isVleff <= io_fromMemIQ_5_0_bits_common_vpu_isVleff;
    s1_ctrl_15_0_ftqIdx_flag <= io_fromMemIQ_5_0_bits_common_ftqIdx_flag;
    s1_ctrl_15_0_ftqIdx_value <= io_fromMemIQ_5_0_bits_common_ftqIdx_value;
    s1_ctrl_15_0_ftqOffset <= io_fromMemIQ_5_0_bits_common_ftqOffset;
    s1_ctrl_15_0_numLsElem <= io_fromMemIQ_5_0_bits_common_numLsElem;
    s1_ctrl_15_0_sqIdx_flag <= io_fromMemIQ_5_0_bits_common_sqIdx_flag;
    s1_ctrl_15_0_sqIdx_value <= io_fromMemIQ_5_0_bits_common_sqIdx_value;
    s1_ctrl_15_0_lqIdx_flag <= io_fromMemIQ_5_0_bits_common_lqIdx_flag;
    s1_ctrl_15_0_lqIdx_value <= io_fromMemIQ_5_0_bits_common_lqIdx_value;
    s1_ctrl_15_0_dataSources_0_value <= io_fromMemIQ_5_0_bits_common_dataSources_0_value;
    s1_ctrl_15_0_dataSources_1_value <= io_fromMemIQ_5_0_bits_common_dataSources_1_value;
    s1_ctrl_15_0_dataSources_2_value <= io_fromMemIQ_5_0_bits_common_dataSources_2_value;
    s1_ctrl_15_0_dataSources_3_value <= io_fromMemIQ_5_0_bits_common_dataSources_3_value;
    s1_ctrl_15_0_dataSources_4_value <= io_fromMemIQ_5_0_bits_common_dataSources_4_value;
  end
  // EXU g16.0 ctrl 流水寄存器
  logic [34:0] s1_ctrl_16_0_fuType;
  logic [8:0] s1_ctrl_16_0_fuOpType;
  logic s1_ctrl_16_0_robIdx_flag;
  logic [7:0] s1_ctrl_16_0_robIdx_value;
  logic [6:0] s1_ctrl_16_0_pdest;
  logic s1_ctrl_16_0_vecWen;
  logic s1_ctrl_16_0_v0Wen;
  logic s1_ctrl_16_0_vlWen;
  logic s1_ctrl_16_0_vpu_vma;
  logic s1_ctrl_16_0_vpu_vta;
  logic [1:0] s1_ctrl_16_0_vpu_vsew;
  logic [2:0] s1_ctrl_16_0_vpu_vlmul;
  logic s1_ctrl_16_0_vpu_vm;
  logic [7:0] s1_ctrl_16_0_vpu_vstart;
  logic [6:0] s1_ctrl_16_0_vpu_vuopIdx;
  logic s1_ctrl_16_0_vpu_lastUop;
  logic [127:0] s1_ctrl_16_0_vpu_vmask;
  logic [2:0] s1_ctrl_16_0_vpu_nf;
  logic [1:0] s1_ctrl_16_0_vpu_veew;
  logic s1_ctrl_16_0_vpu_isVleff;
  logic s1_ctrl_16_0_ftqIdx_flag;
  logic [5:0] s1_ctrl_16_0_ftqIdx_value;
  logic [3:0] s1_ctrl_16_0_ftqOffset;
  logic [4:0] s1_ctrl_16_0_numLsElem;
  logic s1_ctrl_16_0_sqIdx_flag;
  logic [5:0] s1_ctrl_16_0_sqIdx_value;
  logic s1_ctrl_16_0_lqIdx_flag;
  logic [6:0] s1_ctrl_16_0_lqIdx_value;
  logic [3:0] s1_ctrl_16_0_dataSources_0_value;
  logic [3:0] s1_ctrl_16_0_dataSources_1_value;
  logic [3:0] s1_ctrl_16_0_dataSources_2_value;
  logic [3:0] s1_ctrl_16_0_dataSources_3_value;
  logic [3:0] s1_ctrl_16_0_dataSources_4_value;
  always_ff @(posedge clock) if (io_fromMemIQ_6_0_valid) begin
    s1_ctrl_16_0_fuType <= io_fromMemIQ_6_0_bits_common_fuType;
    s1_ctrl_16_0_fuOpType <= io_fromMemIQ_6_0_bits_common_fuOpType;
    s1_ctrl_16_0_robIdx_flag <= io_fromMemIQ_6_0_bits_common_robIdx_flag;
    s1_ctrl_16_0_robIdx_value <= io_fromMemIQ_6_0_bits_common_robIdx_value;
    s1_ctrl_16_0_pdest <= io_fromMemIQ_6_0_bits_common_pdest;
    s1_ctrl_16_0_vecWen <= io_fromMemIQ_6_0_bits_common_vecWen;
    s1_ctrl_16_0_v0Wen <= io_fromMemIQ_6_0_bits_common_v0Wen;
    s1_ctrl_16_0_vlWen <= io_fromMemIQ_6_0_bits_common_vlWen;
    s1_ctrl_16_0_vpu_vma <= io_fromMemIQ_6_0_bits_common_vpu_vma;
    s1_ctrl_16_0_vpu_vta <= io_fromMemIQ_6_0_bits_common_vpu_vta;
    s1_ctrl_16_0_vpu_vsew <= io_fromMemIQ_6_0_bits_common_vpu_vsew;
    s1_ctrl_16_0_vpu_vlmul <= io_fromMemIQ_6_0_bits_common_vpu_vlmul;
    s1_ctrl_16_0_vpu_vm <= io_fromMemIQ_6_0_bits_common_vpu_vm;
    s1_ctrl_16_0_vpu_vstart <= io_fromMemIQ_6_0_bits_common_vpu_vstart;
    s1_ctrl_16_0_vpu_vuopIdx <= io_fromMemIQ_6_0_bits_common_vpu_vuopIdx;
    s1_ctrl_16_0_vpu_lastUop <= io_fromMemIQ_6_0_bits_common_vpu_lastUop;
    s1_ctrl_16_0_vpu_vmask <= io_fromMemIQ_6_0_bits_common_vpu_vmask;
    s1_ctrl_16_0_vpu_nf <= io_fromMemIQ_6_0_bits_common_vpu_nf;
    s1_ctrl_16_0_vpu_veew <= io_fromMemIQ_6_0_bits_common_vpu_veew;
    s1_ctrl_16_0_vpu_isVleff <= io_fromMemIQ_6_0_bits_common_vpu_isVleff;
    s1_ctrl_16_0_ftqIdx_flag <= io_fromMemIQ_6_0_bits_common_ftqIdx_flag;
    s1_ctrl_16_0_ftqIdx_value <= io_fromMemIQ_6_0_bits_common_ftqIdx_value;
    s1_ctrl_16_0_ftqOffset <= io_fromMemIQ_6_0_bits_common_ftqOffset;
    s1_ctrl_16_0_numLsElem <= io_fromMemIQ_6_0_bits_common_numLsElem;
    s1_ctrl_16_0_sqIdx_flag <= io_fromMemIQ_6_0_bits_common_sqIdx_flag;
    s1_ctrl_16_0_sqIdx_value <= io_fromMemIQ_6_0_bits_common_sqIdx_value;
    s1_ctrl_16_0_lqIdx_flag <= io_fromMemIQ_6_0_bits_common_lqIdx_flag;
    s1_ctrl_16_0_lqIdx_value <= io_fromMemIQ_6_0_bits_common_lqIdx_value;
    s1_ctrl_16_0_dataSources_0_value <= io_fromMemIQ_6_0_bits_common_dataSources_0_value;
    s1_ctrl_16_0_dataSources_1_value <= io_fromMemIQ_6_0_bits_common_dataSources_1_value;
    s1_ctrl_16_0_dataSources_2_value <= io_fromMemIQ_6_0_bits_common_dataSources_2_value;
    s1_ctrl_16_0_dataSources_3_value <= io_fromMemIQ_6_0_bits_common_dataSources_3_value;
    s1_ctrl_16_0_dataSources_4_value <= io_fromMemIQ_6_0_bits_common_dataSources_4_value;
  end
  // EXU g17.0 ctrl 流水寄存器
  logic [34:0] s1_ctrl_17_0_fuType;
  logic [8:0] s1_ctrl_17_0_fuOpType;
  logic s1_ctrl_17_0_robIdx_flag;
  logic [7:0] s1_ctrl_17_0_robIdx_value;
  logic s1_ctrl_17_0_sqIdx_flag;
  logic [5:0] s1_ctrl_17_0_sqIdx_value;
  logic [3:0] s1_ctrl_17_0_dataSources_0_value;
  logic [2:0] s1_ctrl_17_0_exuSources_0_value;
  logic [1:0] s1_ctrl_17_0_loadDependency_0;
  logic [1:0] s1_ctrl_17_0_loadDependency_1;
  logic [1:0] s1_ctrl_17_0_loadDependency_2;
  always_ff @(posedge clock) if (io_fromMemIQ_7_0_valid) begin
    s1_ctrl_17_0_fuType <= io_fromMemIQ_7_0_bits_common_fuType;
    s1_ctrl_17_0_fuOpType <= io_fromMemIQ_7_0_bits_common_fuOpType;
    s1_ctrl_17_0_robIdx_flag <= io_fromMemIQ_7_0_bits_common_robIdx_flag;
    s1_ctrl_17_0_robIdx_value <= io_fromMemIQ_7_0_bits_common_robIdx_value;
    s1_ctrl_17_0_sqIdx_flag <= io_fromMemIQ_7_0_bits_common_sqIdx_flag;
    s1_ctrl_17_0_sqIdx_value <= io_fromMemIQ_7_0_bits_common_sqIdx_value;
    s1_ctrl_17_0_dataSources_0_value <= io_fromMemIQ_7_0_bits_common_dataSources_0_value;
    s1_ctrl_17_0_exuSources_0_value <= io_fromMemIQ_7_0_bits_common_exuSources_0_value;
    s1_ctrl_17_0_loadDependency_0 <= {io_fromMemIQ_7_0_bits_common_loadDependency_0[0], 1'b0};
    s1_ctrl_17_0_loadDependency_1 <= {io_fromMemIQ_7_0_bits_common_loadDependency_1[0], 1'b0};
    s1_ctrl_17_0_loadDependency_2 <= {io_fromMemIQ_7_0_bits_common_loadDependency_2[0], 1'b0};
  end
  // EXU g18.0 ctrl 流水寄存器
  logic [34:0] s1_ctrl_18_0_fuType;
  logic [8:0] s1_ctrl_18_0_fuOpType;
  logic s1_ctrl_18_0_robIdx_flag;
  logic [7:0] s1_ctrl_18_0_robIdx_value;
  logic s1_ctrl_18_0_sqIdx_flag;
  logic [5:0] s1_ctrl_18_0_sqIdx_value;
  logic [3:0] s1_ctrl_18_0_dataSources_0_value;
  logic [2:0] s1_ctrl_18_0_exuSources_0_value;
  logic [1:0] s1_ctrl_18_0_loadDependency_0;
  logic [1:0] s1_ctrl_18_0_loadDependency_1;
  logic [1:0] s1_ctrl_18_0_loadDependency_2;
  always_ff @(posedge clock) if (io_fromMemIQ_8_0_valid) begin
    s1_ctrl_18_0_fuType <= io_fromMemIQ_8_0_bits_common_fuType;
    s1_ctrl_18_0_fuOpType <= io_fromMemIQ_8_0_bits_common_fuOpType;
    s1_ctrl_18_0_robIdx_flag <= io_fromMemIQ_8_0_bits_common_robIdx_flag;
    s1_ctrl_18_0_robIdx_value <= io_fromMemIQ_8_0_bits_common_robIdx_value;
    s1_ctrl_18_0_sqIdx_flag <= io_fromMemIQ_8_0_bits_common_sqIdx_flag;
    s1_ctrl_18_0_sqIdx_value <= io_fromMemIQ_8_0_bits_common_sqIdx_value;
    s1_ctrl_18_0_dataSources_0_value <= io_fromMemIQ_8_0_bits_common_dataSources_0_value;
    s1_ctrl_18_0_exuSources_0_value <= io_fromMemIQ_8_0_bits_common_exuSources_0_value;
    s1_ctrl_18_0_loadDependency_0 <= {io_fromMemIQ_8_0_bits_common_loadDependency_0[0], 1'b0};
    s1_ctrl_18_0_loadDependency_1 <= {io_fromMemIQ_8_0_bits_common_loadDependency_1[0], 1'b0};
    s1_ctrl_18_0_loadDependency_2 <= {io_fromMemIQ_8_0_bits_common_loadDependency_2[0], 1'b0};
  end

  // ---- srcType 寄存(RegEnable on fire),供 STD 端口 int|fp Mux1H ----
  logic [3:0] s1_srctype_17_0_0;
  always_ff @(posedge clock) if (fromIQ_fire_17_0) s1_srctype_17_0_0 <= io_fromMemIQ_7_0_bits_srcType_0;
  logic [3:0] s1_srctype_18_0_0;
  always_ff @(posedge clock) if (fromIQ_fire_18_0) s1_srctype_18_0_0 <= io_fromMemIQ_8_0_bits_srcType_0;

