// 由 scripts/gen_decodestage.py 生成：DecodeStage 顶层 wrapper（golden 同名）。
// 机械适配层：扁平端口原样转接给可读核 xs_DecodeStage_core，供 FM/ST 对接。
`include "decodestage_pkg.sv"

module DecodeStage(
  input       clock,
  input       reset,
  input       io_redirect,
  output       io_in_0_ready,
  input       io_in_0_valid,
  input [31:0] io_in_0_bits_instr,
  input [9:0] io_in_0_bits_foldpc,
  input       io_in_0_bits_exceptionVec_0,
  input       io_in_0_bits_exceptionVec_1,
  input       io_in_0_bits_exceptionVec_2,
  input       io_in_0_bits_exceptionVec_4,
  input       io_in_0_bits_exceptionVec_5,
  input       io_in_0_bits_exceptionVec_6,
  input       io_in_0_bits_exceptionVec_7,
  input       io_in_0_bits_exceptionVec_8,
  input       io_in_0_bits_exceptionVec_9,
  input       io_in_0_bits_exceptionVec_10,
  input       io_in_0_bits_exceptionVec_11,
  input       io_in_0_bits_exceptionVec_12,
  input       io_in_0_bits_exceptionVec_13,
  input       io_in_0_bits_exceptionVec_14,
  input       io_in_0_bits_exceptionVec_15,
  input       io_in_0_bits_exceptionVec_16,
  input       io_in_0_bits_exceptionVec_17,
  input       io_in_0_bits_exceptionVec_18,
  input       io_in_0_bits_exceptionVec_19,
  input       io_in_0_bits_exceptionVec_20,
  input       io_in_0_bits_exceptionVec_21,
  input       io_in_0_bits_exceptionVec_23,
  input       io_in_0_bits_isFetchMalAddr,
  input [3:0] io_in_0_bits_trigger,
  input       io_in_0_bits_preDecodeInfo_isRVC,
  input [1:0] io_in_0_bits_preDecodeInfo_brType,
  input       io_in_0_bits_pred_taken,
  input       io_in_0_bits_crossPageIPFFix,
  input       io_in_0_bits_ftqPtr_flag,
  input [5:0] io_in_0_bits_ftqPtr_value,
  input [3:0] io_in_0_bits_ftqOffset,
  input       io_in_0_bits_isLastInFtqEntry,
  output       io_in_1_ready,
  input       io_in_1_valid,
  input [31:0] io_in_1_bits_instr,
  input [9:0] io_in_1_bits_foldpc,
  input       io_in_1_bits_exceptionVec_0,
  input       io_in_1_bits_exceptionVec_1,
  input       io_in_1_bits_exceptionVec_2,
  input       io_in_1_bits_exceptionVec_4,
  input       io_in_1_bits_exceptionVec_5,
  input       io_in_1_bits_exceptionVec_6,
  input       io_in_1_bits_exceptionVec_7,
  input       io_in_1_bits_exceptionVec_8,
  input       io_in_1_bits_exceptionVec_9,
  input       io_in_1_bits_exceptionVec_10,
  input       io_in_1_bits_exceptionVec_11,
  input       io_in_1_bits_exceptionVec_12,
  input       io_in_1_bits_exceptionVec_13,
  input       io_in_1_bits_exceptionVec_14,
  input       io_in_1_bits_exceptionVec_15,
  input       io_in_1_bits_exceptionVec_16,
  input       io_in_1_bits_exceptionVec_17,
  input       io_in_1_bits_exceptionVec_18,
  input       io_in_1_bits_exceptionVec_19,
  input       io_in_1_bits_exceptionVec_20,
  input       io_in_1_bits_exceptionVec_21,
  input       io_in_1_bits_exceptionVec_23,
  input       io_in_1_bits_isFetchMalAddr,
  input [3:0] io_in_1_bits_trigger,
  input       io_in_1_bits_preDecodeInfo_isRVC,
  input [1:0] io_in_1_bits_preDecodeInfo_brType,
  input       io_in_1_bits_pred_taken,
  input       io_in_1_bits_crossPageIPFFix,
  input       io_in_1_bits_ftqPtr_flag,
  input [5:0] io_in_1_bits_ftqPtr_value,
  input [3:0] io_in_1_bits_ftqOffset,
  input       io_in_1_bits_isLastInFtqEntry,
  output       io_in_2_ready,
  input       io_in_2_valid,
  input [31:0] io_in_2_bits_instr,
  input [9:0] io_in_2_bits_foldpc,
  input       io_in_2_bits_exceptionVec_0,
  input       io_in_2_bits_exceptionVec_1,
  input       io_in_2_bits_exceptionVec_2,
  input       io_in_2_bits_exceptionVec_4,
  input       io_in_2_bits_exceptionVec_5,
  input       io_in_2_bits_exceptionVec_6,
  input       io_in_2_bits_exceptionVec_7,
  input       io_in_2_bits_exceptionVec_8,
  input       io_in_2_bits_exceptionVec_9,
  input       io_in_2_bits_exceptionVec_10,
  input       io_in_2_bits_exceptionVec_11,
  input       io_in_2_bits_exceptionVec_12,
  input       io_in_2_bits_exceptionVec_13,
  input       io_in_2_bits_exceptionVec_14,
  input       io_in_2_bits_exceptionVec_15,
  input       io_in_2_bits_exceptionVec_16,
  input       io_in_2_bits_exceptionVec_17,
  input       io_in_2_bits_exceptionVec_18,
  input       io_in_2_bits_exceptionVec_19,
  input       io_in_2_bits_exceptionVec_20,
  input       io_in_2_bits_exceptionVec_21,
  input       io_in_2_bits_exceptionVec_23,
  input       io_in_2_bits_isFetchMalAddr,
  input [3:0] io_in_2_bits_trigger,
  input       io_in_2_bits_preDecodeInfo_isRVC,
  input [1:0] io_in_2_bits_preDecodeInfo_brType,
  input       io_in_2_bits_pred_taken,
  input       io_in_2_bits_crossPageIPFFix,
  input       io_in_2_bits_ftqPtr_flag,
  input [5:0] io_in_2_bits_ftqPtr_value,
  input [3:0] io_in_2_bits_ftqOffset,
  input       io_in_2_bits_isLastInFtqEntry,
  output       io_in_3_ready,
  input       io_in_3_valid,
  input [31:0] io_in_3_bits_instr,
  input [9:0] io_in_3_bits_foldpc,
  input       io_in_3_bits_exceptionVec_0,
  input       io_in_3_bits_exceptionVec_1,
  input       io_in_3_bits_exceptionVec_2,
  input       io_in_3_bits_exceptionVec_4,
  input       io_in_3_bits_exceptionVec_5,
  input       io_in_3_bits_exceptionVec_6,
  input       io_in_3_bits_exceptionVec_7,
  input       io_in_3_bits_exceptionVec_8,
  input       io_in_3_bits_exceptionVec_9,
  input       io_in_3_bits_exceptionVec_10,
  input       io_in_3_bits_exceptionVec_11,
  input       io_in_3_bits_exceptionVec_12,
  input       io_in_3_bits_exceptionVec_13,
  input       io_in_3_bits_exceptionVec_14,
  input       io_in_3_bits_exceptionVec_15,
  input       io_in_3_bits_exceptionVec_16,
  input       io_in_3_bits_exceptionVec_17,
  input       io_in_3_bits_exceptionVec_18,
  input       io_in_3_bits_exceptionVec_19,
  input       io_in_3_bits_exceptionVec_20,
  input       io_in_3_bits_exceptionVec_21,
  input       io_in_3_bits_exceptionVec_23,
  input       io_in_3_bits_isFetchMalAddr,
  input [3:0] io_in_3_bits_trigger,
  input       io_in_3_bits_preDecodeInfo_isRVC,
  input [1:0] io_in_3_bits_preDecodeInfo_brType,
  input       io_in_3_bits_pred_taken,
  input       io_in_3_bits_crossPageIPFFix,
  input       io_in_3_bits_ftqPtr_flag,
  input [5:0] io_in_3_bits_ftqPtr_value,
  input [3:0] io_in_3_bits_ftqOffset,
  input       io_in_3_bits_isLastInFtqEntry,
  output       io_in_4_ready,
  input       io_in_4_valid,
  input [31:0] io_in_4_bits_instr,
  input [9:0] io_in_4_bits_foldpc,
  input       io_in_4_bits_exceptionVec_0,
  input       io_in_4_bits_exceptionVec_1,
  input       io_in_4_bits_exceptionVec_2,
  input       io_in_4_bits_exceptionVec_4,
  input       io_in_4_bits_exceptionVec_5,
  input       io_in_4_bits_exceptionVec_6,
  input       io_in_4_bits_exceptionVec_7,
  input       io_in_4_bits_exceptionVec_8,
  input       io_in_4_bits_exceptionVec_9,
  input       io_in_4_bits_exceptionVec_10,
  input       io_in_4_bits_exceptionVec_11,
  input       io_in_4_bits_exceptionVec_12,
  input       io_in_4_bits_exceptionVec_13,
  input       io_in_4_bits_exceptionVec_14,
  input       io_in_4_bits_exceptionVec_15,
  input       io_in_4_bits_exceptionVec_16,
  input       io_in_4_bits_exceptionVec_17,
  input       io_in_4_bits_exceptionVec_18,
  input       io_in_4_bits_exceptionVec_19,
  input       io_in_4_bits_exceptionVec_20,
  input       io_in_4_bits_exceptionVec_21,
  input       io_in_4_bits_exceptionVec_23,
  input       io_in_4_bits_isFetchMalAddr,
  input [3:0] io_in_4_bits_trigger,
  input       io_in_4_bits_preDecodeInfo_isRVC,
  input [1:0] io_in_4_bits_preDecodeInfo_brType,
  input       io_in_4_bits_pred_taken,
  input       io_in_4_bits_crossPageIPFFix,
  input       io_in_4_bits_ftqPtr_flag,
  input [5:0] io_in_4_bits_ftqPtr_value,
  input [3:0] io_in_4_bits_ftqOffset,
  input       io_in_4_bits_isLastInFtqEntry,
  output       io_in_5_ready,
  input       io_in_5_valid,
  input [31:0] io_in_5_bits_instr,
  input [9:0] io_in_5_bits_foldpc,
  input       io_in_5_bits_exceptionVec_0,
  input       io_in_5_bits_exceptionVec_1,
  input       io_in_5_bits_exceptionVec_2,
  input       io_in_5_bits_exceptionVec_4,
  input       io_in_5_bits_exceptionVec_5,
  input       io_in_5_bits_exceptionVec_6,
  input       io_in_5_bits_exceptionVec_7,
  input       io_in_5_bits_exceptionVec_8,
  input       io_in_5_bits_exceptionVec_9,
  input       io_in_5_bits_exceptionVec_10,
  input       io_in_5_bits_exceptionVec_11,
  input       io_in_5_bits_exceptionVec_12,
  input       io_in_5_bits_exceptionVec_13,
  input       io_in_5_bits_exceptionVec_14,
  input       io_in_5_bits_exceptionVec_15,
  input       io_in_5_bits_exceptionVec_16,
  input       io_in_5_bits_exceptionVec_17,
  input       io_in_5_bits_exceptionVec_18,
  input       io_in_5_bits_exceptionVec_19,
  input       io_in_5_bits_exceptionVec_20,
  input       io_in_5_bits_exceptionVec_21,
  input       io_in_5_bits_exceptionVec_23,
  input       io_in_5_bits_isFetchMalAddr,
  input [3:0] io_in_5_bits_trigger,
  input       io_in_5_bits_preDecodeInfo_isRVC,
  input [1:0] io_in_5_bits_preDecodeInfo_brType,
  input       io_in_5_bits_pred_taken,
  input       io_in_5_bits_crossPageIPFFix,
  input       io_in_5_bits_ftqPtr_flag,
  input [5:0] io_in_5_bits_ftqPtr_value,
  input [3:0] io_in_5_bits_ftqOffset,
  input       io_in_5_bits_isLastInFtqEntry,
  input       io_out_0_ready,
  output       io_out_0_valid,
  output [31:0] io_out_0_bits_instr,
  output [9:0] io_out_0_bits_foldpc,
  output       io_out_0_bits_exceptionVec_0,
  output       io_out_0_bits_exceptionVec_1,
  output       io_out_0_bits_exceptionVec_2,
  output       io_out_0_bits_exceptionVec_3,
  output       io_out_0_bits_exceptionVec_4,
  output       io_out_0_bits_exceptionVec_5,
  output       io_out_0_bits_exceptionVec_6,
  output       io_out_0_bits_exceptionVec_7,
  output       io_out_0_bits_exceptionVec_8,
  output       io_out_0_bits_exceptionVec_9,
  output       io_out_0_bits_exceptionVec_10,
  output       io_out_0_bits_exceptionVec_11,
  output       io_out_0_bits_exceptionVec_12,
  output       io_out_0_bits_exceptionVec_13,
  output       io_out_0_bits_exceptionVec_14,
  output       io_out_0_bits_exceptionVec_15,
  output       io_out_0_bits_exceptionVec_16,
  output       io_out_0_bits_exceptionVec_17,
  output       io_out_0_bits_exceptionVec_18,
  output       io_out_0_bits_exceptionVec_19,
  output       io_out_0_bits_exceptionVec_20,
  output       io_out_0_bits_exceptionVec_21,
  output       io_out_0_bits_exceptionVec_22,
  output       io_out_0_bits_exceptionVec_23,
  output       io_out_0_bits_isFetchMalAddr,
  output [3:0] io_out_0_bits_trigger,
  output       io_out_0_bits_preDecodeInfo_isRVC,
  output [1:0] io_out_0_bits_preDecodeInfo_brType,
  output       io_out_0_bits_pred_taken,
  output       io_out_0_bits_crossPageIPFFix,
  output       io_out_0_bits_ftqPtr_flag,
  output [5:0] io_out_0_bits_ftqPtr_value,
  output [3:0] io_out_0_bits_ftqOffset,
  output [3:0] io_out_0_bits_srcType_0,
  output [3:0] io_out_0_bits_srcType_1,
  output [3:0] io_out_0_bits_srcType_2,
  output [3:0] io_out_0_bits_srcType_3,
  output [3:0] io_out_0_bits_srcType_4,
  output [5:0] io_out_0_bits_lsrc_0,
  output [5:0] io_out_0_bits_lsrc_1,
  output [5:0] io_out_0_bits_lsrc_2,
  output [5:0] io_out_0_bits_ldest,
  output [34:0] io_out_0_bits_fuType,
  output [8:0] io_out_0_bits_fuOpType,
  output       io_out_0_bits_rfWen,
  output       io_out_0_bits_fpWen,
  output       io_out_0_bits_vecWen,
  output       io_out_0_bits_v0Wen,
  output       io_out_0_bits_vlWen,
  output       io_out_0_bits_isXSTrap,
  output       io_out_0_bits_waitForward,
  output       io_out_0_bits_blockBackward,
  output       io_out_0_bits_flushPipe,
  output       io_out_0_bits_canRobCompress,
  output [3:0] io_out_0_bits_selImm,
  output [21:0] io_out_0_bits_imm,
  output [1:0] io_out_0_bits_fpu_typeTagOut,
  output       io_out_0_bits_fpu_wflags,
  output [1:0] io_out_0_bits_fpu_typ,
  output [1:0] io_out_0_bits_fpu_fmt,
  output [2:0] io_out_0_bits_fpu_rm,
  output       io_out_0_bits_vpu_vill,
  output       io_out_0_bits_vpu_vma,
  output       io_out_0_bits_vpu_vta,
  output [1:0] io_out_0_bits_vpu_vsew,
  output [2:0] io_out_0_bits_vpu_vlmul,
  output       io_out_0_bits_vpu_specVill,
  output       io_out_0_bits_vpu_specVma,
  output       io_out_0_bits_vpu_specVta,
  output [1:0] io_out_0_bits_vpu_specVsew,
  output [2:0] io_out_0_bits_vpu_specVlmul,
  output       io_out_0_bits_vpu_vm,
  output [7:0] io_out_0_bits_vpu_vstart,
  output       io_out_0_bits_vpu_fpu_isFoldTo1_2,
  output       io_out_0_bits_vpu_fpu_isFoldTo1_4,
  output       io_out_0_bits_vpu_fpu_isFoldTo1_8,
  output [2:0] io_out_0_bits_vpu_nf,
  output [1:0] io_out_0_bits_vpu_veew,
  output       io_out_0_bits_vpu_isExt,
  output       io_out_0_bits_vpu_isNarrow,
  output       io_out_0_bits_vpu_isDstMask,
  output       io_out_0_bits_vpu_isOpMask,
  output       io_out_0_bits_vpu_isDependOldVd,
  output       io_out_0_bits_vpu_isWritePartVd,
  output       io_out_0_bits_vpu_isVleff,
  output       io_out_0_bits_vlsInstr,
  output       io_out_0_bits_wfflags,
  output       io_out_0_bits_isMove,
  output [6:0] io_out_0_bits_uopIdx,
  output [5:0] io_out_0_bits_uopSplitType,
  output       io_out_0_bits_isVset,
  output       io_out_0_bits_firstUop,
  output       io_out_0_bits_lastUop,
  output [6:0] io_out_0_bits_numWB,
  output [2:0] io_out_0_bits_commitType,
  input       io_out_1_ready,
  output       io_out_1_valid,
  output [31:0] io_out_1_bits_instr,
  output [9:0] io_out_1_bits_foldpc,
  output       io_out_1_bits_exceptionVec_0,
  output       io_out_1_bits_exceptionVec_1,
  output       io_out_1_bits_exceptionVec_2,
  output       io_out_1_bits_exceptionVec_3,
  output       io_out_1_bits_exceptionVec_4,
  output       io_out_1_bits_exceptionVec_5,
  output       io_out_1_bits_exceptionVec_6,
  output       io_out_1_bits_exceptionVec_7,
  output       io_out_1_bits_exceptionVec_8,
  output       io_out_1_bits_exceptionVec_9,
  output       io_out_1_bits_exceptionVec_10,
  output       io_out_1_bits_exceptionVec_11,
  output       io_out_1_bits_exceptionVec_12,
  output       io_out_1_bits_exceptionVec_13,
  output       io_out_1_bits_exceptionVec_14,
  output       io_out_1_bits_exceptionVec_15,
  output       io_out_1_bits_exceptionVec_16,
  output       io_out_1_bits_exceptionVec_17,
  output       io_out_1_bits_exceptionVec_18,
  output       io_out_1_bits_exceptionVec_19,
  output       io_out_1_bits_exceptionVec_20,
  output       io_out_1_bits_exceptionVec_21,
  output       io_out_1_bits_exceptionVec_22,
  output       io_out_1_bits_exceptionVec_23,
  output       io_out_1_bits_isFetchMalAddr,
  output [3:0] io_out_1_bits_trigger,
  output       io_out_1_bits_preDecodeInfo_isRVC,
  output [1:0] io_out_1_bits_preDecodeInfo_brType,
  output       io_out_1_bits_pred_taken,
  output       io_out_1_bits_crossPageIPFFix,
  output       io_out_1_bits_ftqPtr_flag,
  output [5:0] io_out_1_bits_ftqPtr_value,
  output [3:0] io_out_1_bits_ftqOffset,
  output [3:0] io_out_1_bits_srcType_0,
  output [3:0] io_out_1_bits_srcType_1,
  output [3:0] io_out_1_bits_srcType_2,
  output [3:0] io_out_1_bits_srcType_3,
  output [3:0] io_out_1_bits_srcType_4,
  output [5:0] io_out_1_bits_lsrc_0,
  output [5:0] io_out_1_bits_lsrc_1,
  output [5:0] io_out_1_bits_lsrc_2,
  output [5:0] io_out_1_bits_ldest,
  output [34:0] io_out_1_bits_fuType,
  output [8:0] io_out_1_bits_fuOpType,
  output       io_out_1_bits_rfWen,
  output       io_out_1_bits_fpWen,
  output       io_out_1_bits_vecWen,
  output       io_out_1_bits_v0Wen,
  output       io_out_1_bits_vlWen,
  output       io_out_1_bits_isXSTrap,
  output       io_out_1_bits_waitForward,
  output       io_out_1_bits_blockBackward,
  output       io_out_1_bits_flushPipe,
  output       io_out_1_bits_canRobCompress,
  output [3:0] io_out_1_bits_selImm,
  output [21:0] io_out_1_bits_imm,
  output [1:0] io_out_1_bits_fpu_typeTagOut,
  output       io_out_1_bits_fpu_wflags,
  output [1:0] io_out_1_bits_fpu_typ,
  output [1:0] io_out_1_bits_fpu_fmt,
  output [2:0] io_out_1_bits_fpu_rm,
  output       io_out_1_bits_vpu_vill,
  output       io_out_1_bits_vpu_vma,
  output       io_out_1_bits_vpu_vta,
  output [1:0] io_out_1_bits_vpu_vsew,
  output [2:0] io_out_1_bits_vpu_vlmul,
  output       io_out_1_bits_vpu_specVill,
  output       io_out_1_bits_vpu_specVma,
  output       io_out_1_bits_vpu_specVta,
  output [1:0] io_out_1_bits_vpu_specVsew,
  output [2:0] io_out_1_bits_vpu_specVlmul,
  output       io_out_1_bits_vpu_vm,
  output [7:0] io_out_1_bits_vpu_vstart,
  output       io_out_1_bits_vpu_fpu_isFoldTo1_2,
  output       io_out_1_bits_vpu_fpu_isFoldTo1_4,
  output       io_out_1_bits_vpu_fpu_isFoldTo1_8,
  output [2:0] io_out_1_bits_vpu_nf,
  output [1:0] io_out_1_bits_vpu_veew,
  output       io_out_1_bits_vpu_isExt,
  output       io_out_1_bits_vpu_isNarrow,
  output       io_out_1_bits_vpu_isDstMask,
  output       io_out_1_bits_vpu_isOpMask,
  output       io_out_1_bits_vpu_isDependOldVd,
  output       io_out_1_bits_vpu_isWritePartVd,
  output       io_out_1_bits_vpu_isVleff,
  output       io_out_1_bits_vlsInstr,
  output       io_out_1_bits_wfflags,
  output       io_out_1_bits_isMove,
  output [6:0] io_out_1_bits_uopIdx,
  output [5:0] io_out_1_bits_uopSplitType,
  output       io_out_1_bits_isVset,
  output       io_out_1_bits_firstUop,
  output       io_out_1_bits_lastUop,
  output [6:0] io_out_1_bits_numWB,
  output [2:0] io_out_1_bits_commitType,
  input       io_out_2_ready,
  output       io_out_2_valid,
  output [31:0] io_out_2_bits_instr,
  output [9:0] io_out_2_bits_foldpc,
  output       io_out_2_bits_exceptionVec_0,
  output       io_out_2_bits_exceptionVec_1,
  output       io_out_2_bits_exceptionVec_2,
  output       io_out_2_bits_exceptionVec_3,
  output       io_out_2_bits_exceptionVec_4,
  output       io_out_2_bits_exceptionVec_5,
  output       io_out_2_bits_exceptionVec_6,
  output       io_out_2_bits_exceptionVec_7,
  output       io_out_2_bits_exceptionVec_8,
  output       io_out_2_bits_exceptionVec_9,
  output       io_out_2_bits_exceptionVec_10,
  output       io_out_2_bits_exceptionVec_11,
  output       io_out_2_bits_exceptionVec_12,
  output       io_out_2_bits_exceptionVec_13,
  output       io_out_2_bits_exceptionVec_14,
  output       io_out_2_bits_exceptionVec_15,
  output       io_out_2_bits_exceptionVec_16,
  output       io_out_2_bits_exceptionVec_17,
  output       io_out_2_bits_exceptionVec_18,
  output       io_out_2_bits_exceptionVec_19,
  output       io_out_2_bits_exceptionVec_20,
  output       io_out_2_bits_exceptionVec_21,
  output       io_out_2_bits_exceptionVec_22,
  output       io_out_2_bits_exceptionVec_23,
  output       io_out_2_bits_isFetchMalAddr,
  output [3:0] io_out_2_bits_trigger,
  output       io_out_2_bits_preDecodeInfo_isRVC,
  output [1:0] io_out_2_bits_preDecodeInfo_brType,
  output       io_out_2_bits_pred_taken,
  output       io_out_2_bits_crossPageIPFFix,
  output       io_out_2_bits_ftqPtr_flag,
  output [5:0] io_out_2_bits_ftqPtr_value,
  output [3:0] io_out_2_bits_ftqOffset,
  output [3:0] io_out_2_bits_srcType_0,
  output [3:0] io_out_2_bits_srcType_1,
  output [3:0] io_out_2_bits_srcType_2,
  output [3:0] io_out_2_bits_srcType_3,
  output [3:0] io_out_2_bits_srcType_4,
  output [5:0] io_out_2_bits_lsrc_0,
  output [5:0] io_out_2_bits_lsrc_1,
  output [5:0] io_out_2_bits_lsrc_2,
  output [5:0] io_out_2_bits_ldest,
  output [34:0] io_out_2_bits_fuType,
  output [8:0] io_out_2_bits_fuOpType,
  output       io_out_2_bits_rfWen,
  output       io_out_2_bits_fpWen,
  output       io_out_2_bits_vecWen,
  output       io_out_2_bits_v0Wen,
  output       io_out_2_bits_vlWen,
  output       io_out_2_bits_isXSTrap,
  output       io_out_2_bits_waitForward,
  output       io_out_2_bits_blockBackward,
  output       io_out_2_bits_flushPipe,
  output       io_out_2_bits_canRobCompress,
  output [3:0] io_out_2_bits_selImm,
  output [21:0] io_out_2_bits_imm,
  output [1:0] io_out_2_bits_fpu_typeTagOut,
  output       io_out_2_bits_fpu_wflags,
  output [1:0] io_out_2_bits_fpu_typ,
  output [1:0] io_out_2_bits_fpu_fmt,
  output [2:0] io_out_2_bits_fpu_rm,
  output       io_out_2_bits_vpu_vill,
  output       io_out_2_bits_vpu_vma,
  output       io_out_2_bits_vpu_vta,
  output [1:0] io_out_2_bits_vpu_vsew,
  output [2:0] io_out_2_bits_vpu_vlmul,
  output       io_out_2_bits_vpu_specVill,
  output       io_out_2_bits_vpu_specVma,
  output       io_out_2_bits_vpu_specVta,
  output [1:0] io_out_2_bits_vpu_specVsew,
  output [2:0] io_out_2_bits_vpu_specVlmul,
  output       io_out_2_bits_vpu_vm,
  output [7:0] io_out_2_bits_vpu_vstart,
  output       io_out_2_bits_vpu_fpu_isFoldTo1_2,
  output       io_out_2_bits_vpu_fpu_isFoldTo1_4,
  output       io_out_2_bits_vpu_fpu_isFoldTo1_8,
  output [2:0] io_out_2_bits_vpu_nf,
  output [1:0] io_out_2_bits_vpu_veew,
  output       io_out_2_bits_vpu_isExt,
  output       io_out_2_bits_vpu_isNarrow,
  output       io_out_2_bits_vpu_isDstMask,
  output       io_out_2_bits_vpu_isOpMask,
  output       io_out_2_bits_vpu_isDependOldVd,
  output       io_out_2_bits_vpu_isWritePartVd,
  output       io_out_2_bits_vpu_isVleff,
  output       io_out_2_bits_vlsInstr,
  output       io_out_2_bits_wfflags,
  output       io_out_2_bits_isMove,
  output [6:0] io_out_2_bits_uopIdx,
  output [5:0] io_out_2_bits_uopSplitType,
  output       io_out_2_bits_isVset,
  output       io_out_2_bits_firstUop,
  output       io_out_2_bits_lastUop,
  output [6:0] io_out_2_bits_numWB,
  output [2:0] io_out_2_bits_commitType,
  input       io_out_3_ready,
  output       io_out_3_valid,
  output [31:0] io_out_3_bits_instr,
  output [9:0] io_out_3_bits_foldpc,
  output       io_out_3_bits_exceptionVec_0,
  output       io_out_3_bits_exceptionVec_1,
  output       io_out_3_bits_exceptionVec_2,
  output       io_out_3_bits_exceptionVec_3,
  output       io_out_3_bits_exceptionVec_4,
  output       io_out_3_bits_exceptionVec_5,
  output       io_out_3_bits_exceptionVec_6,
  output       io_out_3_bits_exceptionVec_7,
  output       io_out_3_bits_exceptionVec_8,
  output       io_out_3_bits_exceptionVec_9,
  output       io_out_3_bits_exceptionVec_10,
  output       io_out_3_bits_exceptionVec_11,
  output       io_out_3_bits_exceptionVec_12,
  output       io_out_3_bits_exceptionVec_13,
  output       io_out_3_bits_exceptionVec_14,
  output       io_out_3_bits_exceptionVec_15,
  output       io_out_3_bits_exceptionVec_16,
  output       io_out_3_bits_exceptionVec_17,
  output       io_out_3_bits_exceptionVec_18,
  output       io_out_3_bits_exceptionVec_19,
  output       io_out_3_bits_exceptionVec_20,
  output       io_out_3_bits_exceptionVec_21,
  output       io_out_3_bits_exceptionVec_22,
  output       io_out_3_bits_exceptionVec_23,
  output       io_out_3_bits_isFetchMalAddr,
  output [3:0] io_out_3_bits_trigger,
  output       io_out_3_bits_preDecodeInfo_isRVC,
  output [1:0] io_out_3_bits_preDecodeInfo_brType,
  output       io_out_3_bits_pred_taken,
  output       io_out_3_bits_crossPageIPFFix,
  output       io_out_3_bits_ftqPtr_flag,
  output [5:0] io_out_3_bits_ftqPtr_value,
  output [3:0] io_out_3_bits_ftqOffset,
  output [3:0] io_out_3_bits_srcType_0,
  output [3:0] io_out_3_bits_srcType_1,
  output [3:0] io_out_3_bits_srcType_2,
  output [3:0] io_out_3_bits_srcType_3,
  output [3:0] io_out_3_bits_srcType_4,
  output [5:0] io_out_3_bits_lsrc_0,
  output [5:0] io_out_3_bits_lsrc_1,
  output [5:0] io_out_3_bits_lsrc_2,
  output [5:0] io_out_3_bits_ldest,
  output [34:0] io_out_3_bits_fuType,
  output [8:0] io_out_3_bits_fuOpType,
  output       io_out_3_bits_rfWen,
  output       io_out_3_bits_fpWen,
  output       io_out_3_bits_vecWen,
  output       io_out_3_bits_v0Wen,
  output       io_out_3_bits_vlWen,
  output       io_out_3_bits_isXSTrap,
  output       io_out_3_bits_waitForward,
  output       io_out_3_bits_blockBackward,
  output       io_out_3_bits_flushPipe,
  output       io_out_3_bits_canRobCompress,
  output [3:0] io_out_3_bits_selImm,
  output [21:0] io_out_3_bits_imm,
  output [1:0] io_out_3_bits_fpu_typeTagOut,
  output       io_out_3_bits_fpu_wflags,
  output [1:0] io_out_3_bits_fpu_typ,
  output [1:0] io_out_3_bits_fpu_fmt,
  output [2:0] io_out_3_bits_fpu_rm,
  output       io_out_3_bits_vpu_vill,
  output       io_out_3_bits_vpu_vma,
  output       io_out_3_bits_vpu_vta,
  output [1:0] io_out_3_bits_vpu_vsew,
  output [2:0] io_out_3_bits_vpu_vlmul,
  output       io_out_3_bits_vpu_specVill,
  output       io_out_3_bits_vpu_specVma,
  output       io_out_3_bits_vpu_specVta,
  output [1:0] io_out_3_bits_vpu_specVsew,
  output [2:0] io_out_3_bits_vpu_specVlmul,
  output       io_out_3_bits_vpu_vm,
  output [7:0] io_out_3_bits_vpu_vstart,
  output       io_out_3_bits_vpu_fpu_isFoldTo1_2,
  output       io_out_3_bits_vpu_fpu_isFoldTo1_4,
  output       io_out_3_bits_vpu_fpu_isFoldTo1_8,
  output [2:0] io_out_3_bits_vpu_nf,
  output [1:0] io_out_3_bits_vpu_veew,
  output       io_out_3_bits_vpu_isExt,
  output       io_out_3_bits_vpu_isNarrow,
  output       io_out_3_bits_vpu_isDstMask,
  output       io_out_3_bits_vpu_isOpMask,
  output       io_out_3_bits_vpu_isDependOldVd,
  output       io_out_3_bits_vpu_isWritePartVd,
  output       io_out_3_bits_vpu_isVleff,
  output       io_out_3_bits_vlsInstr,
  output       io_out_3_bits_wfflags,
  output       io_out_3_bits_isMove,
  output [6:0] io_out_3_bits_uopIdx,
  output [5:0] io_out_3_bits_uopSplitType,
  output       io_out_3_bits_isVset,
  output       io_out_3_bits_firstUop,
  output       io_out_3_bits_lastUop,
  output [6:0] io_out_3_bits_numWB,
  output [2:0] io_out_3_bits_commitType,
  input       io_out_4_ready,
  output       io_out_4_valid,
  output [31:0] io_out_4_bits_instr,
  output [9:0] io_out_4_bits_foldpc,
  output       io_out_4_bits_exceptionVec_0,
  output       io_out_4_bits_exceptionVec_1,
  output       io_out_4_bits_exceptionVec_2,
  output       io_out_4_bits_exceptionVec_3,
  output       io_out_4_bits_exceptionVec_4,
  output       io_out_4_bits_exceptionVec_5,
  output       io_out_4_bits_exceptionVec_6,
  output       io_out_4_bits_exceptionVec_7,
  output       io_out_4_bits_exceptionVec_8,
  output       io_out_4_bits_exceptionVec_9,
  output       io_out_4_bits_exceptionVec_10,
  output       io_out_4_bits_exceptionVec_11,
  output       io_out_4_bits_exceptionVec_12,
  output       io_out_4_bits_exceptionVec_13,
  output       io_out_4_bits_exceptionVec_14,
  output       io_out_4_bits_exceptionVec_15,
  output       io_out_4_bits_exceptionVec_16,
  output       io_out_4_bits_exceptionVec_17,
  output       io_out_4_bits_exceptionVec_18,
  output       io_out_4_bits_exceptionVec_19,
  output       io_out_4_bits_exceptionVec_20,
  output       io_out_4_bits_exceptionVec_21,
  output       io_out_4_bits_exceptionVec_22,
  output       io_out_4_bits_exceptionVec_23,
  output       io_out_4_bits_isFetchMalAddr,
  output [3:0] io_out_4_bits_trigger,
  output       io_out_4_bits_preDecodeInfo_isRVC,
  output [1:0] io_out_4_bits_preDecodeInfo_brType,
  output       io_out_4_bits_pred_taken,
  output       io_out_4_bits_crossPageIPFFix,
  output       io_out_4_bits_ftqPtr_flag,
  output [5:0] io_out_4_bits_ftqPtr_value,
  output [3:0] io_out_4_bits_ftqOffset,
  output [3:0] io_out_4_bits_srcType_0,
  output [3:0] io_out_4_bits_srcType_1,
  output [3:0] io_out_4_bits_srcType_2,
  output [3:0] io_out_4_bits_srcType_3,
  output [3:0] io_out_4_bits_srcType_4,
  output [5:0] io_out_4_bits_lsrc_0,
  output [5:0] io_out_4_bits_lsrc_1,
  output [5:0] io_out_4_bits_lsrc_2,
  output [5:0] io_out_4_bits_ldest,
  output [34:0] io_out_4_bits_fuType,
  output [8:0] io_out_4_bits_fuOpType,
  output       io_out_4_bits_rfWen,
  output       io_out_4_bits_fpWen,
  output       io_out_4_bits_vecWen,
  output       io_out_4_bits_v0Wen,
  output       io_out_4_bits_vlWen,
  output       io_out_4_bits_isXSTrap,
  output       io_out_4_bits_waitForward,
  output       io_out_4_bits_blockBackward,
  output       io_out_4_bits_flushPipe,
  output       io_out_4_bits_canRobCompress,
  output [3:0] io_out_4_bits_selImm,
  output [21:0] io_out_4_bits_imm,
  output [1:0] io_out_4_bits_fpu_typeTagOut,
  output       io_out_4_bits_fpu_wflags,
  output [1:0] io_out_4_bits_fpu_typ,
  output [1:0] io_out_4_bits_fpu_fmt,
  output [2:0] io_out_4_bits_fpu_rm,
  output       io_out_4_bits_vpu_vill,
  output       io_out_4_bits_vpu_vma,
  output       io_out_4_bits_vpu_vta,
  output [1:0] io_out_4_bits_vpu_vsew,
  output [2:0] io_out_4_bits_vpu_vlmul,
  output       io_out_4_bits_vpu_specVill,
  output       io_out_4_bits_vpu_specVma,
  output       io_out_4_bits_vpu_specVta,
  output [1:0] io_out_4_bits_vpu_specVsew,
  output [2:0] io_out_4_bits_vpu_specVlmul,
  output       io_out_4_bits_vpu_vm,
  output [7:0] io_out_4_bits_vpu_vstart,
  output       io_out_4_bits_vpu_fpu_isFoldTo1_2,
  output       io_out_4_bits_vpu_fpu_isFoldTo1_4,
  output       io_out_4_bits_vpu_fpu_isFoldTo1_8,
  output [2:0] io_out_4_bits_vpu_nf,
  output [1:0] io_out_4_bits_vpu_veew,
  output       io_out_4_bits_vpu_isExt,
  output       io_out_4_bits_vpu_isNarrow,
  output       io_out_4_bits_vpu_isDstMask,
  output       io_out_4_bits_vpu_isOpMask,
  output       io_out_4_bits_vpu_isDependOldVd,
  output       io_out_4_bits_vpu_isWritePartVd,
  output       io_out_4_bits_vpu_isVleff,
  output       io_out_4_bits_vlsInstr,
  output       io_out_4_bits_wfflags,
  output       io_out_4_bits_isMove,
  output [6:0] io_out_4_bits_uopIdx,
  output [5:0] io_out_4_bits_uopSplitType,
  output       io_out_4_bits_isVset,
  output       io_out_4_bits_firstUop,
  output       io_out_4_bits_lastUop,
  output [6:0] io_out_4_bits_numWB,
  output [2:0] io_out_4_bits_commitType,
  input       io_out_5_ready,
  output       io_out_5_valid,
  output [31:0] io_out_5_bits_instr,
  output [9:0] io_out_5_bits_foldpc,
  output       io_out_5_bits_exceptionVec_0,
  output       io_out_5_bits_exceptionVec_1,
  output       io_out_5_bits_exceptionVec_2,
  output       io_out_5_bits_exceptionVec_3,
  output       io_out_5_bits_exceptionVec_4,
  output       io_out_5_bits_exceptionVec_5,
  output       io_out_5_bits_exceptionVec_6,
  output       io_out_5_bits_exceptionVec_7,
  output       io_out_5_bits_exceptionVec_8,
  output       io_out_5_bits_exceptionVec_9,
  output       io_out_5_bits_exceptionVec_10,
  output       io_out_5_bits_exceptionVec_11,
  output       io_out_5_bits_exceptionVec_12,
  output       io_out_5_bits_exceptionVec_13,
  output       io_out_5_bits_exceptionVec_14,
  output       io_out_5_bits_exceptionVec_15,
  output       io_out_5_bits_exceptionVec_16,
  output       io_out_5_bits_exceptionVec_17,
  output       io_out_5_bits_exceptionVec_18,
  output       io_out_5_bits_exceptionVec_19,
  output       io_out_5_bits_exceptionVec_20,
  output       io_out_5_bits_exceptionVec_21,
  output       io_out_5_bits_exceptionVec_22,
  output       io_out_5_bits_exceptionVec_23,
  output       io_out_5_bits_isFetchMalAddr,
  output [3:0] io_out_5_bits_trigger,
  output       io_out_5_bits_preDecodeInfo_isRVC,
  output [1:0] io_out_5_bits_preDecodeInfo_brType,
  output       io_out_5_bits_pred_taken,
  output       io_out_5_bits_crossPageIPFFix,
  output       io_out_5_bits_ftqPtr_flag,
  output [5:0] io_out_5_bits_ftqPtr_value,
  output [3:0] io_out_5_bits_ftqOffset,
  output [3:0] io_out_5_bits_srcType_0,
  output [3:0] io_out_5_bits_srcType_1,
  output [3:0] io_out_5_bits_srcType_2,
  output [3:0] io_out_5_bits_srcType_3,
  output [3:0] io_out_5_bits_srcType_4,
  output [5:0] io_out_5_bits_lsrc_0,
  output [5:0] io_out_5_bits_lsrc_1,
  output [5:0] io_out_5_bits_lsrc_2,
  output [5:0] io_out_5_bits_ldest,
  output [34:0] io_out_5_bits_fuType,
  output [8:0] io_out_5_bits_fuOpType,
  output       io_out_5_bits_rfWen,
  output       io_out_5_bits_fpWen,
  output       io_out_5_bits_vecWen,
  output       io_out_5_bits_v0Wen,
  output       io_out_5_bits_vlWen,
  output       io_out_5_bits_isXSTrap,
  output       io_out_5_bits_waitForward,
  output       io_out_5_bits_blockBackward,
  output       io_out_5_bits_flushPipe,
  output       io_out_5_bits_canRobCompress,
  output [3:0] io_out_5_bits_selImm,
  output [21:0] io_out_5_bits_imm,
  output [1:0] io_out_5_bits_fpu_typeTagOut,
  output       io_out_5_bits_fpu_wflags,
  output [1:0] io_out_5_bits_fpu_typ,
  output [1:0] io_out_5_bits_fpu_fmt,
  output [2:0] io_out_5_bits_fpu_rm,
  output       io_out_5_bits_vpu_vill,
  output       io_out_5_bits_vpu_vma,
  output       io_out_5_bits_vpu_vta,
  output [1:0] io_out_5_bits_vpu_vsew,
  output [2:0] io_out_5_bits_vpu_vlmul,
  output       io_out_5_bits_vpu_specVill,
  output       io_out_5_bits_vpu_specVma,
  output       io_out_5_bits_vpu_specVta,
  output [1:0] io_out_5_bits_vpu_specVsew,
  output [2:0] io_out_5_bits_vpu_specVlmul,
  output       io_out_5_bits_vpu_vm,
  output [7:0] io_out_5_bits_vpu_vstart,
  output       io_out_5_bits_vpu_fpu_isFoldTo1_2,
  output       io_out_5_bits_vpu_fpu_isFoldTo1_4,
  output       io_out_5_bits_vpu_fpu_isFoldTo1_8,
  output [2:0] io_out_5_bits_vpu_nf,
  output [1:0] io_out_5_bits_vpu_veew,
  output       io_out_5_bits_vpu_isExt,
  output       io_out_5_bits_vpu_isNarrow,
  output       io_out_5_bits_vpu_isDstMask,
  output       io_out_5_bits_vpu_isOpMask,
  output       io_out_5_bits_vpu_isDependOldVd,
  output       io_out_5_bits_vpu_isWritePartVd,
  output       io_out_5_bits_vpu_isVleff,
  output       io_out_5_bits_vlsInstr,
  output       io_out_5_bits_wfflags,
  output       io_out_5_bits_isMove,
  output [6:0] io_out_5_bits_uopIdx,
  output [5:0] io_out_5_bits_uopSplitType,
  output       io_out_5_bits_isVset,
  output       io_out_5_bits_firstUop,
  output       io_out_5_bits_lastUop,
  output [6:0] io_out_5_bits_numWB,
  output [2:0] io_out_5_bits_commitType,
  output       io_intRat_0_0_hold,
  output [31:0] io_intRat_0_0_addr,
  output       io_intRat_0_1_hold,
  output [31:0] io_intRat_0_1_addr,
  output       io_intRat_1_0_hold,
  output [31:0] io_intRat_1_0_addr,
  output       io_intRat_1_1_hold,
  output [31:0] io_intRat_1_1_addr,
  output       io_intRat_2_0_hold,
  output [31:0] io_intRat_2_0_addr,
  output       io_intRat_2_1_hold,
  output [31:0] io_intRat_2_1_addr,
  output       io_intRat_3_0_hold,
  output [31:0] io_intRat_3_0_addr,
  output       io_intRat_3_1_hold,
  output [31:0] io_intRat_3_1_addr,
  output       io_intRat_4_0_hold,
  output [31:0] io_intRat_4_0_addr,
  output       io_intRat_4_1_hold,
  output [31:0] io_intRat_4_1_addr,
  output       io_intRat_5_0_hold,
  output [31:0] io_intRat_5_0_addr,
  output       io_intRat_5_1_hold,
  output [31:0] io_intRat_5_1_addr,
  output       io_fpRat_0_0_hold,
  output [33:0] io_fpRat_0_0_addr,
  output       io_fpRat_0_1_hold,
  output [33:0] io_fpRat_0_1_addr,
  output       io_fpRat_0_2_hold,
  output [33:0] io_fpRat_0_2_addr,
  output       io_fpRat_1_0_hold,
  output [33:0] io_fpRat_1_0_addr,
  output       io_fpRat_1_1_hold,
  output [33:0] io_fpRat_1_1_addr,
  output       io_fpRat_1_2_hold,
  output [33:0] io_fpRat_1_2_addr,
  output       io_fpRat_2_0_hold,
  output [33:0] io_fpRat_2_0_addr,
  output       io_fpRat_2_1_hold,
  output [33:0] io_fpRat_2_1_addr,
  output       io_fpRat_2_2_hold,
  output [33:0] io_fpRat_2_2_addr,
  output       io_fpRat_3_0_hold,
  output [33:0] io_fpRat_3_0_addr,
  output       io_fpRat_3_1_hold,
  output [33:0] io_fpRat_3_1_addr,
  output       io_fpRat_3_2_hold,
  output [33:0] io_fpRat_3_2_addr,
  output       io_fpRat_4_0_hold,
  output [33:0] io_fpRat_4_0_addr,
  output       io_fpRat_4_1_hold,
  output [33:0] io_fpRat_4_1_addr,
  output       io_fpRat_4_2_hold,
  output [33:0] io_fpRat_4_2_addr,
  output       io_fpRat_5_0_hold,
  output [33:0] io_fpRat_5_0_addr,
  output       io_fpRat_5_1_hold,
  output [33:0] io_fpRat_5_1_addr,
  output       io_fpRat_5_2_hold,
  output [33:0] io_fpRat_5_2_addr,
  output       io_vecRat_0_0_hold,
  output [46:0] io_vecRat_0_0_addr,
  output       io_vecRat_0_1_hold,
  output [46:0] io_vecRat_0_1_addr,
  output       io_vecRat_0_2_hold,
  output [46:0] io_vecRat_0_2_addr,
  output       io_vecRat_1_0_hold,
  output [46:0] io_vecRat_1_0_addr,
  output       io_vecRat_1_1_hold,
  output [46:0] io_vecRat_1_1_addr,
  output       io_vecRat_1_2_hold,
  output [46:0] io_vecRat_1_2_addr,
  output       io_vecRat_2_0_hold,
  output [46:0] io_vecRat_2_0_addr,
  output       io_vecRat_2_1_hold,
  output [46:0] io_vecRat_2_1_addr,
  output       io_vecRat_2_2_hold,
  output [46:0] io_vecRat_2_2_addr,
  output       io_vecRat_3_0_hold,
  output [46:0] io_vecRat_3_0_addr,
  output       io_vecRat_3_1_hold,
  output [46:0] io_vecRat_3_1_addr,
  output       io_vecRat_3_2_hold,
  output [46:0] io_vecRat_3_2_addr,
  output       io_vecRat_4_0_hold,
  output [46:0] io_vecRat_4_0_addr,
  output       io_vecRat_4_1_hold,
  output [46:0] io_vecRat_4_1_addr,
  output       io_vecRat_4_2_hold,
  output [46:0] io_vecRat_4_2_addr,
  output       io_vecRat_5_0_hold,
  output [46:0] io_vecRat_5_0_addr,
  output       io_vecRat_5_1_hold,
  output [46:0] io_vecRat_5_1_addr,
  output       io_vecRat_5_2_hold,
  output [46:0] io_vecRat_5_2_addr,
  input       io_csrCtrl_singlestep,
  input       io_fromCSR_illegalInst_sfenceVMA,
  input       io_fromCSR_illegalInst_sfencePart,
  input       io_fromCSR_illegalInst_hfenceGVMA,
  input       io_fromCSR_illegalInst_hfenceVVMA,
  input       io_fromCSR_illegalInst_hlsv,
  input       io_fromCSR_illegalInst_fsIsOff,
  input       io_fromCSR_illegalInst_vsIsOff,
  input       io_fromCSR_illegalInst_wfi,
  input       io_fromCSR_illegalInst_wrs_nto,
  input       io_fromCSR_illegalInst_frm,
  input       io_fromCSR_illegalInst_cboZ,
  input       io_fromCSR_illegalInst_cboCF,
  input       io_fromCSR_illegalInst_cboI,
  input       io_fromCSR_virtualInst_sfenceVMA,
  input       io_fromCSR_virtualInst_sfencePart,
  input       io_fromCSR_virtualInst_hfence,
  input       io_fromCSR_virtualInst_hlsv,
  input       io_fromCSR_virtualInst_wfi,
  input       io_fromCSR_virtualInst_wrs_nto,
  input       io_fromCSR_virtualInst_cboZ,
  input       io_fromCSR_virtualInst_cboCF,
  input       io_fromCSR_virtualInst_cboI,
  input       io_fromCSR_special_cboI2F,
  input       io_fusion_0,
  input       io_fusion_1,
  input       io_fusion_2,
  input       io_fusion_3,
  input       io_fusion_4,
  input       io_fromRob_isResumeVType,
  input       io_fromRob_walkToArchVType,
  input       io_fromRob_commitVType_vtype_valid,
  input       io_fromRob_commitVType_vtype_bits_illegal,
  input       io_fromRob_commitVType_vtype_bits_vma,
  input       io_fromRob_commitVType_vtype_bits_vta,
  input [1:0] io_fromRob_commitVType_vtype_bits_vsew,
  input [2:0] io_fromRob_commitVType_vtype_bits_vlmul,
  input       io_fromRob_commitVType_hasVsetvl,
  input       io_fromRob_walkVType_valid,
  input       io_fromRob_walkVType_bits_illegal,
  input       io_fromRob_walkVType_bits_vma,
  input       io_fromRob_walkVType_bits_vta,
  input [1:0] io_fromRob_walkVType_bits_vsew,
  input [2:0] io_fromRob_walkVType_bits_vlmul,
  input [5:0] io_stallReason_in_reason_0,
  input [5:0] io_stallReason_in_reason_1,
  input [5:0] io_stallReason_in_reason_2,
  input [5:0] io_stallReason_in_reason_3,
  input [5:0] io_stallReason_in_reason_4,
  input [5:0] io_stallReason_in_reason_5,
  output       io_stallReason_in_backReason_valid,
  output [5:0] io_stallReason_in_backReason_bits,
  output [5:0] io_stallReason_out_reason_0,
  output [5:0] io_stallReason_out_reason_1,
  output [5:0] io_stallReason_out_reason_2,
  output [5:0] io_stallReason_out_reason_3,
  output [5:0] io_stallReason_out_reason_4,
  output [5:0] io_stallReason_out_reason_5,
  input       io_stallReason_out_backReason_valid,
  input [5:0] io_stallReason_out_backReason_bits,
  input       io_vsetvlVType_illegal,
  input       io_vsetvlVType_vma,
  input       io_vsetvlVType_vta,
  input [1:0] io_vsetvlVType_vsew,
  input [2:0] io_vsetvlVType_vlmul,
  input [7:0] io_vstart,
  output       io_toCSR_trapInstInfo_valid,
  output [31:0] io_toCSR_trapInstInfo_bits_instr,
  output       io_toCSR_trapInstInfo_bits_ftqPtr_flag,
  output [5:0] io_toCSR_trapInstInfo_bits_ftqPtr_value,
  output [3:0] io_toCSR_trapInstInfo_bits_ftqOffset,
  output [5:0] io_perf_0_value,
  output [5:0] io_perf_1_value,
  output [5:0] io_perf_2_value,
  output [5:0] io_perf_3_value,
  output [5:0] io_perf_4_value,
  output [5:0] io_perf_5_value
);
  xs_DecodeStage_core u_core (
    .clock(clock),
    .reset(reset),
    .io_redirect(io_redirect),
    .io_in_0_ready(io_in_0_ready),
    .io_in_0_valid(io_in_0_valid),
    .io_in_0_bits_instr(io_in_0_bits_instr),
    .io_in_0_bits_foldpc(io_in_0_bits_foldpc),
    .io_in_0_bits_exceptionVec_0(io_in_0_bits_exceptionVec_0),
    .io_in_0_bits_exceptionVec_1(io_in_0_bits_exceptionVec_1),
    .io_in_0_bits_exceptionVec_2(io_in_0_bits_exceptionVec_2),
    .io_in_0_bits_exceptionVec_4(io_in_0_bits_exceptionVec_4),
    .io_in_0_bits_exceptionVec_5(io_in_0_bits_exceptionVec_5),
    .io_in_0_bits_exceptionVec_6(io_in_0_bits_exceptionVec_6),
    .io_in_0_bits_exceptionVec_7(io_in_0_bits_exceptionVec_7),
    .io_in_0_bits_exceptionVec_8(io_in_0_bits_exceptionVec_8),
    .io_in_0_bits_exceptionVec_9(io_in_0_bits_exceptionVec_9),
    .io_in_0_bits_exceptionVec_10(io_in_0_bits_exceptionVec_10),
    .io_in_0_bits_exceptionVec_11(io_in_0_bits_exceptionVec_11),
    .io_in_0_bits_exceptionVec_12(io_in_0_bits_exceptionVec_12),
    .io_in_0_bits_exceptionVec_13(io_in_0_bits_exceptionVec_13),
    .io_in_0_bits_exceptionVec_14(io_in_0_bits_exceptionVec_14),
    .io_in_0_bits_exceptionVec_15(io_in_0_bits_exceptionVec_15),
    .io_in_0_bits_exceptionVec_16(io_in_0_bits_exceptionVec_16),
    .io_in_0_bits_exceptionVec_17(io_in_0_bits_exceptionVec_17),
    .io_in_0_bits_exceptionVec_18(io_in_0_bits_exceptionVec_18),
    .io_in_0_bits_exceptionVec_19(io_in_0_bits_exceptionVec_19),
    .io_in_0_bits_exceptionVec_20(io_in_0_bits_exceptionVec_20),
    .io_in_0_bits_exceptionVec_21(io_in_0_bits_exceptionVec_21),
    .io_in_0_bits_exceptionVec_23(io_in_0_bits_exceptionVec_23),
    .io_in_0_bits_isFetchMalAddr(io_in_0_bits_isFetchMalAddr),
    .io_in_0_bits_trigger(io_in_0_bits_trigger),
    .io_in_0_bits_preDecodeInfo_isRVC(io_in_0_bits_preDecodeInfo_isRVC),
    .io_in_0_bits_preDecodeInfo_brType(io_in_0_bits_preDecodeInfo_brType),
    .io_in_0_bits_pred_taken(io_in_0_bits_pred_taken),
    .io_in_0_bits_crossPageIPFFix(io_in_0_bits_crossPageIPFFix),
    .io_in_0_bits_ftqPtr_flag(io_in_0_bits_ftqPtr_flag),
    .io_in_0_bits_ftqPtr_value(io_in_0_bits_ftqPtr_value),
    .io_in_0_bits_ftqOffset(io_in_0_bits_ftqOffset),
    .io_in_0_bits_isLastInFtqEntry(io_in_0_bits_isLastInFtqEntry),
    .io_in_1_ready(io_in_1_ready),
    .io_in_1_valid(io_in_1_valid),
    .io_in_1_bits_instr(io_in_1_bits_instr),
    .io_in_1_bits_foldpc(io_in_1_bits_foldpc),
    .io_in_1_bits_exceptionVec_0(io_in_1_bits_exceptionVec_0),
    .io_in_1_bits_exceptionVec_1(io_in_1_bits_exceptionVec_1),
    .io_in_1_bits_exceptionVec_2(io_in_1_bits_exceptionVec_2),
    .io_in_1_bits_exceptionVec_4(io_in_1_bits_exceptionVec_4),
    .io_in_1_bits_exceptionVec_5(io_in_1_bits_exceptionVec_5),
    .io_in_1_bits_exceptionVec_6(io_in_1_bits_exceptionVec_6),
    .io_in_1_bits_exceptionVec_7(io_in_1_bits_exceptionVec_7),
    .io_in_1_bits_exceptionVec_8(io_in_1_bits_exceptionVec_8),
    .io_in_1_bits_exceptionVec_9(io_in_1_bits_exceptionVec_9),
    .io_in_1_bits_exceptionVec_10(io_in_1_bits_exceptionVec_10),
    .io_in_1_bits_exceptionVec_11(io_in_1_bits_exceptionVec_11),
    .io_in_1_bits_exceptionVec_12(io_in_1_bits_exceptionVec_12),
    .io_in_1_bits_exceptionVec_13(io_in_1_bits_exceptionVec_13),
    .io_in_1_bits_exceptionVec_14(io_in_1_bits_exceptionVec_14),
    .io_in_1_bits_exceptionVec_15(io_in_1_bits_exceptionVec_15),
    .io_in_1_bits_exceptionVec_16(io_in_1_bits_exceptionVec_16),
    .io_in_1_bits_exceptionVec_17(io_in_1_bits_exceptionVec_17),
    .io_in_1_bits_exceptionVec_18(io_in_1_bits_exceptionVec_18),
    .io_in_1_bits_exceptionVec_19(io_in_1_bits_exceptionVec_19),
    .io_in_1_bits_exceptionVec_20(io_in_1_bits_exceptionVec_20),
    .io_in_1_bits_exceptionVec_21(io_in_1_bits_exceptionVec_21),
    .io_in_1_bits_exceptionVec_23(io_in_1_bits_exceptionVec_23),
    .io_in_1_bits_isFetchMalAddr(io_in_1_bits_isFetchMalAddr),
    .io_in_1_bits_trigger(io_in_1_bits_trigger),
    .io_in_1_bits_preDecodeInfo_isRVC(io_in_1_bits_preDecodeInfo_isRVC),
    .io_in_1_bits_preDecodeInfo_brType(io_in_1_bits_preDecodeInfo_brType),
    .io_in_1_bits_pred_taken(io_in_1_bits_pred_taken),
    .io_in_1_bits_crossPageIPFFix(io_in_1_bits_crossPageIPFFix),
    .io_in_1_bits_ftqPtr_flag(io_in_1_bits_ftqPtr_flag),
    .io_in_1_bits_ftqPtr_value(io_in_1_bits_ftqPtr_value),
    .io_in_1_bits_ftqOffset(io_in_1_bits_ftqOffset),
    .io_in_1_bits_isLastInFtqEntry(io_in_1_bits_isLastInFtqEntry),
    .io_in_2_ready(io_in_2_ready),
    .io_in_2_valid(io_in_2_valid),
    .io_in_2_bits_instr(io_in_2_bits_instr),
    .io_in_2_bits_foldpc(io_in_2_bits_foldpc),
    .io_in_2_bits_exceptionVec_0(io_in_2_bits_exceptionVec_0),
    .io_in_2_bits_exceptionVec_1(io_in_2_bits_exceptionVec_1),
    .io_in_2_bits_exceptionVec_2(io_in_2_bits_exceptionVec_2),
    .io_in_2_bits_exceptionVec_4(io_in_2_bits_exceptionVec_4),
    .io_in_2_bits_exceptionVec_5(io_in_2_bits_exceptionVec_5),
    .io_in_2_bits_exceptionVec_6(io_in_2_bits_exceptionVec_6),
    .io_in_2_bits_exceptionVec_7(io_in_2_bits_exceptionVec_7),
    .io_in_2_bits_exceptionVec_8(io_in_2_bits_exceptionVec_8),
    .io_in_2_bits_exceptionVec_9(io_in_2_bits_exceptionVec_9),
    .io_in_2_bits_exceptionVec_10(io_in_2_bits_exceptionVec_10),
    .io_in_2_bits_exceptionVec_11(io_in_2_bits_exceptionVec_11),
    .io_in_2_bits_exceptionVec_12(io_in_2_bits_exceptionVec_12),
    .io_in_2_bits_exceptionVec_13(io_in_2_bits_exceptionVec_13),
    .io_in_2_bits_exceptionVec_14(io_in_2_bits_exceptionVec_14),
    .io_in_2_bits_exceptionVec_15(io_in_2_bits_exceptionVec_15),
    .io_in_2_bits_exceptionVec_16(io_in_2_bits_exceptionVec_16),
    .io_in_2_bits_exceptionVec_17(io_in_2_bits_exceptionVec_17),
    .io_in_2_bits_exceptionVec_18(io_in_2_bits_exceptionVec_18),
    .io_in_2_bits_exceptionVec_19(io_in_2_bits_exceptionVec_19),
    .io_in_2_bits_exceptionVec_20(io_in_2_bits_exceptionVec_20),
    .io_in_2_bits_exceptionVec_21(io_in_2_bits_exceptionVec_21),
    .io_in_2_bits_exceptionVec_23(io_in_2_bits_exceptionVec_23),
    .io_in_2_bits_isFetchMalAddr(io_in_2_bits_isFetchMalAddr),
    .io_in_2_bits_trigger(io_in_2_bits_trigger),
    .io_in_2_bits_preDecodeInfo_isRVC(io_in_2_bits_preDecodeInfo_isRVC),
    .io_in_2_bits_preDecodeInfo_brType(io_in_2_bits_preDecodeInfo_brType),
    .io_in_2_bits_pred_taken(io_in_2_bits_pred_taken),
    .io_in_2_bits_crossPageIPFFix(io_in_2_bits_crossPageIPFFix),
    .io_in_2_bits_ftqPtr_flag(io_in_2_bits_ftqPtr_flag),
    .io_in_2_bits_ftqPtr_value(io_in_2_bits_ftqPtr_value),
    .io_in_2_bits_ftqOffset(io_in_2_bits_ftqOffset),
    .io_in_2_bits_isLastInFtqEntry(io_in_2_bits_isLastInFtqEntry),
    .io_in_3_ready(io_in_3_ready),
    .io_in_3_valid(io_in_3_valid),
    .io_in_3_bits_instr(io_in_3_bits_instr),
    .io_in_3_bits_foldpc(io_in_3_bits_foldpc),
    .io_in_3_bits_exceptionVec_0(io_in_3_bits_exceptionVec_0),
    .io_in_3_bits_exceptionVec_1(io_in_3_bits_exceptionVec_1),
    .io_in_3_bits_exceptionVec_2(io_in_3_bits_exceptionVec_2),
    .io_in_3_bits_exceptionVec_4(io_in_3_bits_exceptionVec_4),
    .io_in_3_bits_exceptionVec_5(io_in_3_bits_exceptionVec_5),
    .io_in_3_bits_exceptionVec_6(io_in_3_bits_exceptionVec_6),
    .io_in_3_bits_exceptionVec_7(io_in_3_bits_exceptionVec_7),
    .io_in_3_bits_exceptionVec_8(io_in_3_bits_exceptionVec_8),
    .io_in_3_bits_exceptionVec_9(io_in_3_bits_exceptionVec_9),
    .io_in_3_bits_exceptionVec_10(io_in_3_bits_exceptionVec_10),
    .io_in_3_bits_exceptionVec_11(io_in_3_bits_exceptionVec_11),
    .io_in_3_bits_exceptionVec_12(io_in_3_bits_exceptionVec_12),
    .io_in_3_bits_exceptionVec_13(io_in_3_bits_exceptionVec_13),
    .io_in_3_bits_exceptionVec_14(io_in_3_bits_exceptionVec_14),
    .io_in_3_bits_exceptionVec_15(io_in_3_bits_exceptionVec_15),
    .io_in_3_bits_exceptionVec_16(io_in_3_bits_exceptionVec_16),
    .io_in_3_bits_exceptionVec_17(io_in_3_bits_exceptionVec_17),
    .io_in_3_bits_exceptionVec_18(io_in_3_bits_exceptionVec_18),
    .io_in_3_bits_exceptionVec_19(io_in_3_bits_exceptionVec_19),
    .io_in_3_bits_exceptionVec_20(io_in_3_bits_exceptionVec_20),
    .io_in_3_bits_exceptionVec_21(io_in_3_bits_exceptionVec_21),
    .io_in_3_bits_exceptionVec_23(io_in_3_bits_exceptionVec_23),
    .io_in_3_bits_isFetchMalAddr(io_in_3_bits_isFetchMalAddr),
    .io_in_3_bits_trigger(io_in_3_bits_trigger),
    .io_in_3_bits_preDecodeInfo_isRVC(io_in_3_bits_preDecodeInfo_isRVC),
    .io_in_3_bits_preDecodeInfo_brType(io_in_3_bits_preDecodeInfo_brType),
    .io_in_3_bits_pred_taken(io_in_3_bits_pred_taken),
    .io_in_3_bits_crossPageIPFFix(io_in_3_bits_crossPageIPFFix),
    .io_in_3_bits_ftqPtr_flag(io_in_3_bits_ftqPtr_flag),
    .io_in_3_bits_ftqPtr_value(io_in_3_bits_ftqPtr_value),
    .io_in_3_bits_ftqOffset(io_in_3_bits_ftqOffset),
    .io_in_3_bits_isLastInFtqEntry(io_in_3_bits_isLastInFtqEntry),
    .io_in_4_ready(io_in_4_ready),
    .io_in_4_valid(io_in_4_valid),
    .io_in_4_bits_instr(io_in_4_bits_instr),
    .io_in_4_bits_foldpc(io_in_4_bits_foldpc),
    .io_in_4_bits_exceptionVec_0(io_in_4_bits_exceptionVec_0),
    .io_in_4_bits_exceptionVec_1(io_in_4_bits_exceptionVec_1),
    .io_in_4_bits_exceptionVec_2(io_in_4_bits_exceptionVec_2),
    .io_in_4_bits_exceptionVec_4(io_in_4_bits_exceptionVec_4),
    .io_in_4_bits_exceptionVec_5(io_in_4_bits_exceptionVec_5),
    .io_in_4_bits_exceptionVec_6(io_in_4_bits_exceptionVec_6),
    .io_in_4_bits_exceptionVec_7(io_in_4_bits_exceptionVec_7),
    .io_in_4_bits_exceptionVec_8(io_in_4_bits_exceptionVec_8),
    .io_in_4_bits_exceptionVec_9(io_in_4_bits_exceptionVec_9),
    .io_in_4_bits_exceptionVec_10(io_in_4_bits_exceptionVec_10),
    .io_in_4_bits_exceptionVec_11(io_in_4_bits_exceptionVec_11),
    .io_in_4_bits_exceptionVec_12(io_in_4_bits_exceptionVec_12),
    .io_in_4_bits_exceptionVec_13(io_in_4_bits_exceptionVec_13),
    .io_in_4_bits_exceptionVec_14(io_in_4_bits_exceptionVec_14),
    .io_in_4_bits_exceptionVec_15(io_in_4_bits_exceptionVec_15),
    .io_in_4_bits_exceptionVec_16(io_in_4_bits_exceptionVec_16),
    .io_in_4_bits_exceptionVec_17(io_in_4_bits_exceptionVec_17),
    .io_in_4_bits_exceptionVec_18(io_in_4_bits_exceptionVec_18),
    .io_in_4_bits_exceptionVec_19(io_in_4_bits_exceptionVec_19),
    .io_in_4_bits_exceptionVec_20(io_in_4_bits_exceptionVec_20),
    .io_in_4_bits_exceptionVec_21(io_in_4_bits_exceptionVec_21),
    .io_in_4_bits_exceptionVec_23(io_in_4_bits_exceptionVec_23),
    .io_in_4_bits_isFetchMalAddr(io_in_4_bits_isFetchMalAddr),
    .io_in_4_bits_trigger(io_in_4_bits_trigger),
    .io_in_4_bits_preDecodeInfo_isRVC(io_in_4_bits_preDecodeInfo_isRVC),
    .io_in_4_bits_preDecodeInfo_brType(io_in_4_bits_preDecodeInfo_brType),
    .io_in_4_bits_pred_taken(io_in_4_bits_pred_taken),
    .io_in_4_bits_crossPageIPFFix(io_in_4_bits_crossPageIPFFix),
    .io_in_4_bits_ftqPtr_flag(io_in_4_bits_ftqPtr_flag),
    .io_in_4_bits_ftqPtr_value(io_in_4_bits_ftqPtr_value),
    .io_in_4_bits_ftqOffset(io_in_4_bits_ftqOffset),
    .io_in_4_bits_isLastInFtqEntry(io_in_4_bits_isLastInFtqEntry),
    .io_in_5_ready(io_in_5_ready),
    .io_in_5_valid(io_in_5_valid),
    .io_in_5_bits_instr(io_in_5_bits_instr),
    .io_in_5_bits_foldpc(io_in_5_bits_foldpc),
    .io_in_5_bits_exceptionVec_0(io_in_5_bits_exceptionVec_0),
    .io_in_5_bits_exceptionVec_1(io_in_5_bits_exceptionVec_1),
    .io_in_5_bits_exceptionVec_2(io_in_5_bits_exceptionVec_2),
    .io_in_5_bits_exceptionVec_4(io_in_5_bits_exceptionVec_4),
    .io_in_5_bits_exceptionVec_5(io_in_5_bits_exceptionVec_5),
    .io_in_5_bits_exceptionVec_6(io_in_5_bits_exceptionVec_6),
    .io_in_5_bits_exceptionVec_7(io_in_5_bits_exceptionVec_7),
    .io_in_5_bits_exceptionVec_8(io_in_5_bits_exceptionVec_8),
    .io_in_5_bits_exceptionVec_9(io_in_5_bits_exceptionVec_9),
    .io_in_5_bits_exceptionVec_10(io_in_5_bits_exceptionVec_10),
    .io_in_5_bits_exceptionVec_11(io_in_5_bits_exceptionVec_11),
    .io_in_5_bits_exceptionVec_12(io_in_5_bits_exceptionVec_12),
    .io_in_5_bits_exceptionVec_13(io_in_5_bits_exceptionVec_13),
    .io_in_5_bits_exceptionVec_14(io_in_5_bits_exceptionVec_14),
    .io_in_5_bits_exceptionVec_15(io_in_5_bits_exceptionVec_15),
    .io_in_5_bits_exceptionVec_16(io_in_5_bits_exceptionVec_16),
    .io_in_5_bits_exceptionVec_17(io_in_5_bits_exceptionVec_17),
    .io_in_5_bits_exceptionVec_18(io_in_5_bits_exceptionVec_18),
    .io_in_5_bits_exceptionVec_19(io_in_5_bits_exceptionVec_19),
    .io_in_5_bits_exceptionVec_20(io_in_5_bits_exceptionVec_20),
    .io_in_5_bits_exceptionVec_21(io_in_5_bits_exceptionVec_21),
    .io_in_5_bits_exceptionVec_23(io_in_5_bits_exceptionVec_23),
    .io_in_5_bits_isFetchMalAddr(io_in_5_bits_isFetchMalAddr),
    .io_in_5_bits_trigger(io_in_5_bits_trigger),
    .io_in_5_bits_preDecodeInfo_isRVC(io_in_5_bits_preDecodeInfo_isRVC),
    .io_in_5_bits_preDecodeInfo_brType(io_in_5_bits_preDecodeInfo_brType),
    .io_in_5_bits_pred_taken(io_in_5_bits_pred_taken),
    .io_in_5_bits_crossPageIPFFix(io_in_5_bits_crossPageIPFFix),
    .io_in_5_bits_ftqPtr_flag(io_in_5_bits_ftqPtr_flag),
    .io_in_5_bits_ftqPtr_value(io_in_5_bits_ftqPtr_value),
    .io_in_5_bits_ftqOffset(io_in_5_bits_ftqOffset),
    .io_in_5_bits_isLastInFtqEntry(io_in_5_bits_isLastInFtqEntry),
    .io_out_0_ready(io_out_0_ready),
    .io_out_0_valid(io_out_0_valid),
    .io_out_0_bits_instr(io_out_0_bits_instr),
    .io_out_0_bits_foldpc(io_out_0_bits_foldpc),
    .io_out_0_bits_exceptionVec_0(io_out_0_bits_exceptionVec_0),
    .io_out_0_bits_exceptionVec_1(io_out_0_bits_exceptionVec_1),
    .io_out_0_bits_exceptionVec_2(io_out_0_bits_exceptionVec_2),
    .io_out_0_bits_exceptionVec_3(io_out_0_bits_exceptionVec_3),
    .io_out_0_bits_exceptionVec_4(io_out_0_bits_exceptionVec_4),
    .io_out_0_bits_exceptionVec_5(io_out_0_bits_exceptionVec_5),
    .io_out_0_bits_exceptionVec_6(io_out_0_bits_exceptionVec_6),
    .io_out_0_bits_exceptionVec_7(io_out_0_bits_exceptionVec_7),
    .io_out_0_bits_exceptionVec_8(io_out_0_bits_exceptionVec_8),
    .io_out_0_bits_exceptionVec_9(io_out_0_bits_exceptionVec_9),
    .io_out_0_bits_exceptionVec_10(io_out_0_bits_exceptionVec_10),
    .io_out_0_bits_exceptionVec_11(io_out_0_bits_exceptionVec_11),
    .io_out_0_bits_exceptionVec_12(io_out_0_bits_exceptionVec_12),
    .io_out_0_bits_exceptionVec_13(io_out_0_bits_exceptionVec_13),
    .io_out_0_bits_exceptionVec_14(io_out_0_bits_exceptionVec_14),
    .io_out_0_bits_exceptionVec_15(io_out_0_bits_exceptionVec_15),
    .io_out_0_bits_exceptionVec_16(io_out_0_bits_exceptionVec_16),
    .io_out_0_bits_exceptionVec_17(io_out_0_bits_exceptionVec_17),
    .io_out_0_bits_exceptionVec_18(io_out_0_bits_exceptionVec_18),
    .io_out_0_bits_exceptionVec_19(io_out_0_bits_exceptionVec_19),
    .io_out_0_bits_exceptionVec_20(io_out_0_bits_exceptionVec_20),
    .io_out_0_bits_exceptionVec_21(io_out_0_bits_exceptionVec_21),
    .io_out_0_bits_exceptionVec_22(io_out_0_bits_exceptionVec_22),
    .io_out_0_bits_exceptionVec_23(io_out_0_bits_exceptionVec_23),
    .io_out_0_bits_isFetchMalAddr(io_out_0_bits_isFetchMalAddr),
    .io_out_0_bits_trigger(io_out_0_bits_trigger),
    .io_out_0_bits_preDecodeInfo_isRVC(io_out_0_bits_preDecodeInfo_isRVC),
    .io_out_0_bits_preDecodeInfo_brType(io_out_0_bits_preDecodeInfo_brType),
    .io_out_0_bits_pred_taken(io_out_0_bits_pred_taken),
    .io_out_0_bits_crossPageIPFFix(io_out_0_bits_crossPageIPFFix),
    .io_out_0_bits_ftqPtr_flag(io_out_0_bits_ftqPtr_flag),
    .io_out_0_bits_ftqPtr_value(io_out_0_bits_ftqPtr_value),
    .io_out_0_bits_ftqOffset(io_out_0_bits_ftqOffset),
    .io_out_0_bits_srcType_0(io_out_0_bits_srcType_0),
    .io_out_0_bits_srcType_1(io_out_0_bits_srcType_1),
    .io_out_0_bits_srcType_2(io_out_0_bits_srcType_2),
    .io_out_0_bits_srcType_3(io_out_0_bits_srcType_3),
    .io_out_0_bits_srcType_4(io_out_0_bits_srcType_4),
    .io_out_0_bits_lsrc_0(io_out_0_bits_lsrc_0),
    .io_out_0_bits_lsrc_1(io_out_0_bits_lsrc_1),
    .io_out_0_bits_lsrc_2(io_out_0_bits_lsrc_2),
    .io_out_0_bits_ldest(io_out_0_bits_ldest),
    .io_out_0_bits_fuType(io_out_0_bits_fuType),
    .io_out_0_bits_fuOpType(io_out_0_bits_fuOpType),
    .io_out_0_bits_rfWen(io_out_0_bits_rfWen),
    .io_out_0_bits_fpWen(io_out_0_bits_fpWen),
    .io_out_0_bits_vecWen(io_out_0_bits_vecWen),
    .io_out_0_bits_v0Wen(io_out_0_bits_v0Wen),
    .io_out_0_bits_vlWen(io_out_0_bits_vlWen),
    .io_out_0_bits_isXSTrap(io_out_0_bits_isXSTrap),
    .io_out_0_bits_waitForward(io_out_0_bits_waitForward),
    .io_out_0_bits_blockBackward(io_out_0_bits_blockBackward),
    .io_out_0_bits_flushPipe(io_out_0_bits_flushPipe),
    .io_out_0_bits_canRobCompress(io_out_0_bits_canRobCompress),
    .io_out_0_bits_selImm(io_out_0_bits_selImm),
    .io_out_0_bits_imm(io_out_0_bits_imm),
    .io_out_0_bits_fpu_typeTagOut(io_out_0_bits_fpu_typeTagOut),
    .io_out_0_bits_fpu_wflags(io_out_0_bits_fpu_wflags),
    .io_out_0_bits_fpu_typ(io_out_0_bits_fpu_typ),
    .io_out_0_bits_fpu_fmt(io_out_0_bits_fpu_fmt),
    .io_out_0_bits_fpu_rm(io_out_0_bits_fpu_rm),
    .io_out_0_bits_vpu_vill(io_out_0_bits_vpu_vill),
    .io_out_0_bits_vpu_vma(io_out_0_bits_vpu_vma),
    .io_out_0_bits_vpu_vta(io_out_0_bits_vpu_vta),
    .io_out_0_bits_vpu_vsew(io_out_0_bits_vpu_vsew),
    .io_out_0_bits_vpu_vlmul(io_out_0_bits_vpu_vlmul),
    .io_out_0_bits_vpu_specVill(io_out_0_bits_vpu_specVill),
    .io_out_0_bits_vpu_specVma(io_out_0_bits_vpu_specVma),
    .io_out_0_bits_vpu_specVta(io_out_0_bits_vpu_specVta),
    .io_out_0_bits_vpu_specVsew(io_out_0_bits_vpu_specVsew),
    .io_out_0_bits_vpu_specVlmul(io_out_0_bits_vpu_specVlmul),
    .io_out_0_bits_vpu_vm(io_out_0_bits_vpu_vm),
    .io_out_0_bits_vpu_vstart(io_out_0_bits_vpu_vstart),
    .io_out_0_bits_vpu_fpu_isFoldTo1_2(io_out_0_bits_vpu_fpu_isFoldTo1_2),
    .io_out_0_bits_vpu_fpu_isFoldTo1_4(io_out_0_bits_vpu_fpu_isFoldTo1_4),
    .io_out_0_bits_vpu_fpu_isFoldTo1_8(io_out_0_bits_vpu_fpu_isFoldTo1_8),
    .io_out_0_bits_vpu_nf(io_out_0_bits_vpu_nf),
    .io_out_0_bits_vpu_veew(io_out_0_bits_vpu_veew),
    .io_out_0_bits_vpu_isExt(io_out_0_bits_vpu_isExt),
    .io_out_0_bits_vpu_isNarrow(io_out_0_bits_vpu_isNarrow),
    .io_out_0_bits_vpu_isDstMask(io_out_0_bits_vpu_isDstMask),
    .io_out_0_bits_vpu_isOpMask(io_out_0_bits_vpu_isOpMask),
    .io_out_0_bits_vpu_isDependOldVd(io_out_0_bits_vpu_isDependOldVd),
    .io_out_0_bits_vpu_isWritePartVd(io_out_0_bits_vpu_isWritePartVd),
    .io_out_0_bits_vpu_isVleff(io_out_0_bits_vpu_isVleff),
    .io_out_0_bits_vlsInstr(io_out_0_bits_vlsInstr),
    .io_out_0_bits_wfflags(io_out_0_bits_wfflags),
    .io_out_0_bits_isMove(io_out_0_bits_isMove),
    .io_out_0_bits_uopIdx(io_out_0_bits_uopIdx),
    .io_out_0_bits_uopSplitType(io_out_0_bits_uopSplitType),
    .io_out_0_bits_isVset(io_out_0_bits_isVset),
    .io_out_0_bits_firstUop(io_out_0_bits_firstUop),
    .io_out_0_bits_lastUop(io_out_0_bits_lastUop),
    .io_out_0_bits_numWB(io_out_0_bits_numWB),
    .io_out_0_bits_commitType(io_out_0_bits_commitType),
    .io_out_1_ready(io_out_1_ready),
    .io_out_1_valid(io_out_1_valid),
    .io_out_1_bits_instr(io_out_1_bits_instr),
    .io_out_1_bits_foldpc(io_out_1_bits_foldpc),
    .io_out_1_bits_exceptionVec_0(io_out_1_bits_exceptionVec_0),
    .io_out_1_bits_exceptionVec_1(io_out_1_bits_exceptionVec_1),
    .io_out_1_bits_exceptionVec_2(io_out_1_bits_exceptionVec_2),
    .io_out_1_bits_exceptionVec_3(io_out_1_bits_exceptionVec_3),
    .io_out_1_bits_exceptionVec_4(io_out_1_bits_exceptionVec_4),
    .io_out_1_bits_exceptionVec_5(io_out_1_bits_exceptionVec_5),
    .io_out_1_bits_exceptionVec_6(io_out_1_bits_exceptionVec_6),
    .io_out_1_bits_exceptionVec_7(io_out_1_bits_exceptionVec_7),
    .io_out_1_bits_exceptionVec_8(io_out_1_bits_exceptionVec_8),
    .io_out_1_bits_exceptionVec_9(io_out_1_bits_exceptionVec_9),
    .io_out_1_bits_exceptionVec_10(io_out_1_bits_exceptionVec_10),
    .io_out_1_bits_exceptionVec_11(io_out_1_bits_exceptionVec_11),
    .io_out_1_bits_exceptionVec_12(io_out_1_bits_exceptionVec_12),
    .io_out_1_bits_exceptionVec_13(io_out_1_bits_exceptionVec_13),
    .io_out_1_bits_exceptionVec_14(io_out_1_bits_exceptionVec_14),
    .io_out_1_bits_exceptionVec_15(io_out_1_bits_exceptionVec_15),
    .io_out_1_bits_exceptionVec_16(io_out_1_bits_exceptionVec_16),
    .io_out_1_bits_exceptionVec_17(io_out_1_bits_exceptionVec_17),
    .io_out_1_bits_exceptionVec_18(io_out_1_bits_exceptionVec_18),
    .io_out_1_bits_exceptionVec_19(io_out_1_bits_exceptionVec_19),
    .io_out_1_bits_exceptionVec_20(io_out_1_bits_exceptionVec_20),
    .io_out_1_bits_exceptionVec_21(io_out_1_bits_exceptionVec_21),
    .io_out_1_bits_exceptionVec_22(io_out_1_bits_exceptionVec_22),
    .io_out_1_bits_exceptionVec_23(io_out_1_bits_exceptionVec_23),
    .io_out_1_bits_isFetchMalAddr(io_out_1_bits_isFetchMalAddr),
    .io_out_1_bits_trigger(io_out_1_bits_trigger),
    .io_out_1_bits_preDecodeInfo_isRVC(io_out_1_bits_preDecodeInfo_isRVC),
    .io_out_1_bits_preDecodeInfo_brType(io_out_1_bits_preDecodeInfo_brType),
    .io_out_1_bits_pred_taken(io_out_1_bits_pred_taken),
    .io_out_1_bits_crossPageIPFFix(io_out_1_bits_crossPageIPFFix),
    .io_out_1_bits_ftqPtr_flag(io_out_1_bits_ftqPtr_flag),
    .io_out_1_bits_ftqPtr_value(io_out_1_bits_ftqPtr_value),
    .io_out_1_bits_ftqOffset(io_out_1_bits_ftqOffset),
    .io_out_1_bits_srcType_0(io_out_1_bits_srcType_0),
    .io_out_1_bits_srcType_1(io_out_1_bits_srcType_1),
    .io_out_1_bits_srcType_2(io_out_1_bits_srcType_2),
    .io_out_1_bits_srcType_3(io_out_1_bits_srcType_3),
    .io_out_1_bits_srcType_4(io_out_1_bits_srcType_4),
    .io_out_1_bits_lsrc_0(io_out_1_bits_lsrc_0),
    .io_out_1_bits_lsrc_1(io_out_1_bits_lsrc_1),
    .io_out_1_bits_lsrc_2(io_out_1_bits_lsrc_2),
    .io_out_1_bits_ldest(io_out_1_bits_ldest),
    .io_out_1_bits_fuType(io_out_1_bits_fuType),
    .io_out_1_bits_fuOpType(io_out_1_bits_fuOpType),
    .io_out_1_bits_rfWen(io_out_1_bits_rfWen),
    .io_out_1_bits_fpWen(io_out_1_bits_fpWen),
    .io_out_1_bits_vecWen(io_out_1_bits_vecWen),
    .io_out_1_bits_v0Wen(io_out_1_bits_v0Wen),
    .io_out_1_bits_vlWen(io_out_1_bits_vlWen),
    .io_out_1_bits_isXSTrap(io_out_1_bits_isXSTrap),
    .io_out_1_bits_waitForward(io_out_1_bits_waitForward),
    .io_out_1_bits_blockBackward(io_out_1_bits_blockBackward),
    .io_out_1_bits_flushPipe(io_out_1_bits_flushPipe),
    .io_out_1_bits_canRobCompress(io_out_1_bits_canRobCompress),
    .io_out_1_bits_selImm(io_out_1_bits_selImm),
    .io_out_1_bits_imm(io_out_1_bits_imm),
    .io_out_1_bits_fpu_typeTagOut(io_out_1_bits_fpu_typeTagOut),
    .io_out_1_bits_fpu_wflags(io_out_1_bits_fpu_wflags),
    .io_out_1_bits_fpu_typ(io_out_1_bits_fpu_typ),
    .io_out_1_bits_fpu_fmt(io_out_1_bits_fpu_fmt),
    .io_out_1_bits_fpu_rm(io_out_1_bits_fpu_rm),
    .io_out_1_bits_vpu_vill(io_out_1_bits_vpu_vill),
    .io_out_1_bits_vpu_vma(io_out_1_bits_vpu_vma),
    .io_out_1_bits_vpu_vta(io_out_1_bits_vpu_vta),
    .io_out_1_bits_vpu_vsew(io_out_1_bits_vpu_vsew),
    .io_out_1_bits_vpu_vlmul(io_out_1_bits_vpu_vlmul),
    .io_out_1_bits_vpu_specVill(io_out_1_bits_vpu_specVill),
    .io_out_1_bits_vpu_specVma(io_out_1_bits_vpu_specVma),
    .io_out_1_bits_vpu_specVta(io_out_1_bits_vpu_specVta),
    .io_out_1_bits_vpu_specVsew(io_out_1_bits_vpu_specVsew),
    .io_out_1_bits_vpu_specVlmul(io_out_1_bits_vpu_specVlmul),
    .io_out_1_bits_vpu_vm(io_out_1_bits_vpu_vm),
    .io_out_1_bits_vpu_vstart(io_out_1_bits_vpu_vstart),
    .io_out_1_bits_vpu_fpu_isFoldTo1_2(io_out_1_bits_vpu_fpu_isFoldTo1_2),
    .io_out_1_bits_vpu_fpu_isFoldTo1_4(io_out_1_bits_vpu_fpu_isFoldTo1_4),
    .io_out_1_bits_vpu_fpu_isFoldTo1_8(io_out_1_bits_vpu_fpu_isFoldTo1_8),
    .io_out_1_bits_vpu_nf(io_out_1_bits_vpu_nf),
    .io_out_1_bits_vpu_veew(io_out_1_bits_vpu_veew),
    .io_out_1_bits_vpu_isExt(io_out_1_bits_vpu_isExt),
    .io_out_1_bits_vpu_isNarrow(io_out_1_bits_vpu_isNarrow),
    .io_out_1_bits_vpu_isDstMask(io_out_1_bits_vpu_isDstMask),
    .io_out_1_bits_vpu_isOpMask(io_out_1_bits_vpu_isOpMask),
    .io_out_1_bits_vpu_isDependOldVd(io_out_1_bits_vpu_isDependOldVd),
    .io_out_1_bits_vpu_isWritePartVd(io_out_1_bits_vpu_isWritePartVd),
    .io_out_1_bits_vpu_isVleff(io_out_1_bits_vpu_isVleff),
    .io_out_1_bits_vlsInstr(io_out_1_bits_vlsInstr),
    .io_out_1_bits_wfflags(io_out_1_bits_wfflags),
    .io_out_1_bits_isMove(io_out_1_bits_isMove),
    .io_out_1_bits_uopIdx(io_out_1_bits_uopIdx),
    .io_out_1_bits_uopSplitType(io_out_1_bits_uopSplitType),
    .io_out_1_bits_isVset(io_out_1_bits_isVset),
    .io_out_1_bits_firstUop(io_out_1_bits_firstUop),
    .io_out_1_bits_lastUop(io_out_1_bits_lastUop),
    .io_out_1_bits_numWB(io_out_1_bits_numWB),
    .io_out_1_bits_commitType(io_out_1_bits_commitType),
    .io_out_2_ready(io_out_2_ready),
    .io_out_2_valid(io_out_2_valid),
    .io_out_2_bits_instr(io_out_2_bits_instr),
    .io_out_2_bits_foldpc(io_out_2_bits_foldpc),
    .io_out_2_bits_exceptionVec_0(io_out_2_bits_exceptionVec_0),
    .io_out_2_bits_exceptionVec_1(io_out_2_bits_exceptionVec_1),
    .io_out_2_bits_exceptionVec_2(io_out_2_bits_exceptionVec_2),
    .io_out_2_bits_exceptionVec_3(io_out_2_bits_exceptionVec_3),
    .io_out_2_bits_exceptionVec_4(io_out_2_bits_exceptionVec_4),
    .io_out_2_bits_exceptionVec_5(io_out_2_bits_exceptionVec_5),
    .io_out_2_bits_exceptionVec_6(io_out_2_bits_exceptionVec_6),
    .io_out_2_bits_exceptionVec_7(io_out_2_bits_exceptionVec_7),
    .io_out_2_bits_exceptionVec_8(io_out_2_bits_exceptionVec_8),
    .io_out_2_bits_exceptionVec_9(io_out_2_bits_exceptionVec_9),
    .io_out_2_bits_exceptionVec_10(io_out_2_bits_exceptionVec_10),
    .io_out_2_bits_exceptionVec_11(io_out_2_bits_exceptionVec_11),
    .io_out_2_bits_exceptionVec_12(io_out_2_bits_exceptionVec_12),
    .io_out_2_bits_exceptionVec_13(io_out_2_bits_exceptionVec_13),
    .io_out_2_bits_exceptionVec_14(io_out_2_bits_exceptionVec_14),
    .io_out_2_bits_exceptionVec_15(io_out_2_bits_exceptionVec_15),
    .io_out_2_bits_exceptionVec_16(io_out_2_bits_exceptionVec_16),
    .io_out_2_bits_exceptionVec_17(io_out_2_bits_exceptionVec_17),
    .io_out_2_bits_exceptionVec_18(io_out_2_bits_exceptionVec_18),
    .io_out_2_bits_exceptionVec_19(io_out_2_bits_exceptionVec_19),
    .io_out_2_bits_exceptionVec_20(io_out_2_bits_exceptionVec_20),
    .io_out_2_bits_exceptionVec_21(io_out_2_bits_exceptionVec_21),
    .io_out_2_bits_exceptionVec_22(io_out_2_bits_exceptionVec_22),
    .io_out_2_bits_exceptionVec_23(io_out_2_bits_exceptionVec_23),
    .io_out_2_bits_isFetchMalAddr(io_out_2_bits_isFetchMalAddr),
    .io_out_2_bits_trigger(io_out_2_bits_trigger),
    .io_out_2_bits_preDecodeInfo_isRVC(io_out_2_bits_preDecodeInfo_isRVC),
    .io_out_2_bits_preDecodeInfo_brType(io_out_2_bits_preDecodeInfo_brType),
    .io_out_2_bits_pred_taken(io_out_2_bits_pred_taken),
    .io_out_2_bits_crossPageIPFFix(io_out_2_bits_crossPageIPFFix),
    .io_out_2_bits_ftqPtr_flag(io_out_2_bits_ftqPtr_flag),
    .io_out_2_bits_ftqPtr_value(io_out_2_bits_ftqPtr_value),
    .io_out_2_bits_ftqOffset(io_out_2_bits_ftqOffset),
    .io_out_2_bits_srcType_0(io_out_2_bits_srcType_0),
    .io_out_2_bits_srcType_1(io_out_2_bits_srcType_1),
    .io_out_2_bits_srcType_2(io_out_2_bits_srcType_2),
    .io_out_2_bits_srcType_3(io_out_2_bits_srcType_3),
    .io_out_2_bits_srcType_4(io_out_2_bits_srcType_4),
    .io_out_2_bits_lsrc_0(io_out_2_bits_lsrc_0),
    .io_out_2_bits_lsrc_1(io_out_2_bits_lsrc_1),
    .io_out_2_bits_lsrc_2(io_out_2_bits_lsrc_2),
    .io_out_2_bits_ldest(io_out_2_bits_ldest),
    .io_out_2_bits_fuType(io_out_2_bits_fuType),
    .io_out_2_bits_fuOpType(io_out_2_bits_fuOpType),
    .io_out_2_bits_rfWen(io_out_2_bits_rfWen),
    .io_out_2_bits_fpWen(io_out_2_bits_fpWen),
    .io_out_2_bits_vecWen(io_out_2_bits_vecWen),
    .io_out_2_bits_v0Wen(io_out_2_bits_v0Wen),
    .io_out_2_bits_vlWen(io_out_2_bits_vlWen),
    .io_out_2_bits_isXSTrap(io_out_2_bits_isXSTrap),
    .io_out_2_bits_waitForward(io_out_2_bits_waitForward),
    .io_out_2_bits_blockBackward(io_out_2_bits_blockBackward),
    .io_out_2_bits_flushPipe(io_out_2_bits_flushPipe),
    .io_out_2_bits_canRobCompress(io_out_2_bits_canRobCompress),
    .io_out_2_bits_selImm(io_out_2_bits_selImm),
    .io_out_2_bits_imm(io_out_2_bits_imm),
    .io_out_2_bits_fpu_typeTagOut(io_out_2_bits_fpu_typeTagOut),
    .io_out_2_bits_fpu_wflags(io_out_2_bits_fpu_wflags),
    .io_out_2_bits_fpu_typ(io_out_2_bits_fpu_typ),
    .io_out_2_bits_fpu_fmt(io_out_2_bits_fpu_fmt),
    .io_out_2_bits_fpu_rm(io_out_2_bits_fpu_rm),
    .io_out_2_bits_vpu_vill(io_out_2_bits_vpu_vill),
    .io_out_2_bits_vpu_vma(io_out_2_bits_vpu_vma),
    .io_out_2_bits_vpu_vta(io_out_2_bits_vpu_vta),
    .io_out_2_bits_vpu_vsew(io_out_2_bits_vpu_vsew),
    .io_out_2_bits_vpu_vlmul(io_out_2_bits_vpu_vlmul),
    .io_out_2_bits_vpu_specVill(io_out_2_bits_vpu_specVill),
    .io_out_2_bits_vpu_specVma(io_out_2_bits_vpu_specVma),
    .io_out_2_bits_vpu_specVta(io_out_2_bits_vpu_specVta),
    .io_out_2_bits_vpu_specVsew(io_out_2_bits_vpu_specVsew),
    .io_out_2_bits_vpu_specVlmul(io_out_2_bits_vpu_specVlmul),
    .io_out_2_bits_vpu_vm(io_out_2_bits_vpu_vm),
    .io_out_2_bits_vpu_vstart(io_out_2_bits_vpu_vstart),
    .io_out_2_bits_vpu_fpu_isFoldTo1_2(io_out_2_bits_vpu_fpu_isFoldTo1_2),
    .io_out_2_bits_vpu_fpu_isFoldTo1_4(io_out_2_bits_vpu_fpu_isFoldTo1_4),
    .io_out_2_bits_vpu_fpu_isFoldTo1_8(io_out_2_bits_vpu_fpu_isFoldTo1_8),
    .io_out_2_bits_vpu_nf(io_out_2_bits_vpu_nf),
    .io_out_2_bits_vpu_veew(io_out_2_bits_vpu_veew),
    .io_out_2_bits_vpu_isExt(io_out_2_bits_vpu_isExt),
    .io_out_2_bits_vpu_isNarrow(io_out_2_bits_vpu_isNarrow),
    .io_out_2_bits_vpu_isDstMask(io_out_2_bits_vpu_isDstMask),
    .io_out_2_bits_vpu_isOpMask(io_out_2_bits_vpu_isOpMask),
    .io_out_2_bits_vpu_isDependOldVd(io_out_2_bits_vpu_isDependOldVd),
    .io_out_2_bits_vpu_isWritePartVd(io_out_2_bits_vpu_isWritePartVd),
    .io_out_2_bits_vpu_isVleff(io_out_2_bits_vpu_isVleff),
    .io_out_2_bits_vlsInstr(io_out_2_bits_vlsInstr),
    .io_out_2_bits_wfflags(io_out_2_bits_wfflags),
    .io_out_2_bits_isMove(io_out_2_bits_isMove),
    .io_out_2_bits_uopIdx(io_out_2_bits_uopIdx),
    .io_out_2_bits_uopSplitType(io_out_2_bits_uopSplitType),
    .io_out_2_bits_isVset(io_out_2_bits_isVset),
    .io_out_2_bits_firstUop(io_out_2_bits_firstUop),
    .io_out_2_bits_lastUop(io_out_2_bits_lastUop),
    .io_out_2_bits_numWB(io_out_2_bits_numWB),
    .io_out_2_bits_commitType(io_out_2_bits_commitType),
    .io_out_3_ready(io_out_3_ready),
    .io_out_3_valid(io_out_3_valid),
    .io_out_3_bits_instr(io_out_3_bits_instr),
    .io_out_3_bits_foldpc(io_out_3_bits_foldpc),
    .io_out_3_bits_exceptionVec_0(io_out_3_bits_exceptionVec_0),
    .io_out_3_bits_exceptionVec_1(io_out_3_bits_exceptionVec_1),
    .io_out_3_bits_exceptionVec_2(io_out_3_bits_exceptionVec_2),
    .io_out_3_bits_exceptionVec_3(io_out_3_bits_exceptionVec_3),
    .io_out_3_bits_exceptionVec_4(io_out_3_bits_exceptionVec_4),
    .io_out_3_bits_exceptionVec_5(io_out_3_bits_exceptionVec_5),
    .io_out_3_bits_exceptionVec_6(io_out_3_bits_exceptionVec_6),
    .io_out_3_bits_exceptionVec_7(io_out_3_bits_exceptionVec_7),
    .io_out_3_bits_exceptionVec_8(io_out_3_bits_exceptionVec_8),
    .io_out_3_bits_exceptionVec_9(io_out_3_bits_exceptionVec_9),
    .io_out_3_bits_exceptionVec_10(io_out_3_bits_exceptionVec_10),
    .io_out_3_bits_exceptionVec_11(io_out_3_bits_exceptionVec_11),
    .io_out_3_bits_exceptionVec_12(io_out_3_bits_exceptionVec_12),
    .io_out_3_bits_exceptionVec_13(io_out_3_bits_exceptionVec_13),
    .io_out_3_bits_exceptionVec_14(io_out_3_bits_exceptionVec_14),
    .io_out_3_bits_exceptionVec_15(io_out_3_bits_exceptionVec_15),
    .io_out_3_bits_exceptionVec_16(io_out_3_bits_exceptionVec_16),
    .io_out_3_bits_exceptionVec_17(io_out_3_bits_exceptionVec_17),
    .io_out_3_bits_exceptionVec_18(io_out_3_bits_exceptionVec_18),
    .io_out_3_bits_exceptionVec_19(io_out_3_bits_exceptionVec_19),
    .io_out_3_bits_exceptionVec_20(io_out_3_bits_exceptionVec_20),
    .io_out_3_bits_exceptionVec_21(io_out_3_bits_exceptionVec_21),
    .io_out_3_bits_exceptionVec_22(io_out_3_bits_exceptionVec_22),
    .io_out_3_bits_exceptionVec_23(io_out_3_bits_exceptionVec_23),
    .io_out_3_bits_isFetchMalAddr(io_out_3_bits_isFetchMalAddr),
    .io_out_3_bits_trigger(io_out_3_bits_trigger),
    .io_out_3_bits_preDecodeInfo_isRVC(io_out_3_bits_preDecodeInfo_isRVC),
    .io_out_3_bits_preDecodeInfo_brType(io_out_3_bits_preDecodeInfo_brType),
    .io_out_3_bits_pred_taken(io_out_3_bits_pred_taken),
    .io_out_3_bits_crossPageIPFFix(io_out_3_bits_crossPageIPFFix),
    .io_out_3_bits_ftqPtr_flag(io_out_3_bits_ftqPtr_flag),
    .io_out_3_bits_ftqPtr_value(io_out_3_bits_ftqPtr_value),
    .io_out_3_bits_ftqOffset(io_out_3_bits_ftqOffset),
    .io_out_3_bits_srcType_0(io_out_3_bits_srcType_0),
    .io_out_3_bits_srcType_1(io_out_3_bits_srcType_1),
    .io_out_3_bits_srcType_2(io_out_3_bits_srcType_2),
    .io_out_3_bits_srcType_3(io_out_3_bits_srcType_3),
    .io_out_3_bits_srcType_4(io_out_3_bits_srcType_4),
    .io_out_3_bits_lsrc_0(io_out_3_bits_lsrc_0),
    .io_out_3_bits_lsrc_1(io_out_3_bits_lsrc_1),
    .io_out_3_bits_lsrc_2(io_out_3_bits_lsrc_2),
    .io_out_3_bits_ldest(io_out_3_bits_ldest),
    .io_out_3_bits_fuType(io_out_3_bits_fuType),
    .io_out_3_bits_fuOpType(io_out_3_bits_fuOpType),
    .io_out_3_bits_rfWen(io_out_3_bits_rfWen),
    .io_out_3_bits_fpWen(io_out_3_bits_fpWen),
    .io_out_3_bits_vecWen(io_out_3_bits_vecWen),
    .io_out_3_bits_v0Wen(io_out_3_bits_v0Wen),
    .io_out_3_bits_vlWen(io_out_3_bits_vlWen),
    .io_out_3_bits_isXSTrap(io_out_3_bits_isXSTrap),
    .io_out_3_bits_waitForward(io_out_3_bits_waitForward),
    .io_out_3_bits_blockBackward(io_out_3_bits_blockBackward),
    .io_out_3_bits_flushPipe(io_out_3_bits_flushPipe),
    .io_out_3_bits_canRobCompress(io_out_3_bits_canRobCompress),
    .io_out_3_bits_selImm(io_out_3_bits_selImm),
    .io_out_3_bits_imm(io_out_3_bits_imm),
    .io_out_3_bits_fpu_typeTagOut(io_out_3_bits_fpu_typeTagOut),
    .io_out_3_bits_fpu_wflags(io_out_3_bits_fpu_wflags),
    .io_out_3_bits_fpu_typ(io_out_3_bits_fpu_typ),
    .io_out_3_bits_fpu_fmt(io_out_3_bits_fpu_fmt),
    .io_out_3_bits_fpu_rm(io_out_3_bits_fpu_rm),
    .io_out_3_bits_vpu_vill(io_out_3_bits_vpu_vill),
    .io_out_3_bits_vpu_vma(io_out_3_bits_vpu_vma),
    .io_out_3_bits_vpu_vta(io_out_3_bits_vpu_vta),
    .io_out_3_bits_vpu_vsew(io_out_3_bits_vpu_vsew),
    .io_out_3_bits_vpu_vlmul(io_out_3_bits_vpu_vlmul),
    .io_out_3_bits_vpu_specVill(io_out_3_bits_vpu_specVill),
    .io_out_3_bits_vpu_specVma(io_out_3_bits_vpu_specVma),
    .io_out_3_bits_vpu_specVta(io_out_3_bits_vpu_specVta),
    .io_out_3_bits_vpu_specVsew(io_out_3_bits_vpu_specVsew),
    .io_out_3_bits_vpu_specVlmul(io_out_3_bits_vpu_specVlmul),
    .io_out_3_bits_vpu_vm(io_out_3_bits_vpu_vm),
    .io_out_3_bits_vpu_vstart(io_out_3_bits_vpu_vstart),
    .io_out_3_bits_vpu_fpu_isFoldTo1_2(io_out_3_bits_vpu_fpu_isFoldTo1_2),
    .io_out_3_bits_vpu_fpu_isFoldTo1_4(io_out_3_bits_vpu_fpu_isFoldTo1_4),
    .io_out_3_bits_vpu_fpu_isFoldTo1_8(io_out_3_bits_vpu_fpu_isFoldTo1_8),
    .io_out_3_bits_vpu_nf(io_out_3_bits_vpu_nf),
    .io_out_3_bits_vpu_veew(io_out_3_bits_vpu_veew),
    .io_out_3_bits_vpu_isExt(io_out_3_bits_vpu_isExt),
    .io_out_3_bits_vpu_isNarrow(io_out_3_bits_vpu_isNarrow),
    .io_out_3_bits_vpu_isDstMask(io_out_3_bits_vpu_isDstMask),
    .io_out_3_bits_vpu_isOpMask(io_out_3_bits_vpu_isOpMask),
    .io_out_3_bits_vpu_isDependOldVd(io_out_3_bits_vpu_isDependOldVd),
    .io_out_3_bits_vpu_isWritePartVd(io_out_3_bits_vpu_isWritePartVd),
    .io_out_3_bits_vpu_isVleff(io_out_3_bits_vpu_isVleff),
    .io_out_3_bits_vlsInstr(io_out_3_bits_vlsInstr),
    .io_out_3_bits_wfflags(io_out_3_bits_wfflags),
    .io_out_3_bits_isMove(io_out_3_bits_isMove),
    .io_out_3_bits_uopIdx(io_out_3_bits_uopIdx),
    .io_out_3_bits_uopSplitType(io_out_3_bits_uopSplitType),
    .io_out_3_bits_isVset(io_out_3_bits_isVset),
    .io_out_3_bits_firstUop(io_out_3_bits_firstUop),
    .io_out_3_bits_lastUop(io_out_3_bits_lastUop),
    .io_out_3_bits_numWB(io_out_3_bits_numWB),
    .io_out_3_bits_commitType(io_out_3_bits_commitType),
    .io_out_4_ready(io_out_4_ready),
    .io_out_4_valid(io_out_4_valid),
    .io_out_4_bits_instr(io_out_4_bits_instr),
    .io_out_4_bits_foldpc(io_out_4_bits_foldpc),
    .io_out_4_bits_exceptionVec_0(io_out_4_bits_exceptionVec_0),
    .io_out_4_bits_exceptionVec_1(io_out_4_bits_exceptionVec_1),
    .io_out_4_bits_exceptionVec_2(io_out_4_bits_exceptionVec_2),
    .io_out_4_bits_exceptionVec_3(io_out_4_bits_exceptionVec_3),
    .io_out_4_bits_exceptionVec_4(io_out_4_bits_exceptionVec_4),
    .io_out_4_bits_exceptionVec_5(io_out_4_bits_exceptionVec_5),
    .io_out_4_bits_exceptionVec_6(io_out_4_bits_exceptionVec_6),
    .io_out_4_bits_exceptionVec_7(io_out_4_bits_exceptionVec_7),
    .io_out_4_bits_exceptionVec_8(io_out_4_bits_exceptionVec_8),
    .io_out_4_bits_exceptionVec_9(io_out_4_bits_exceptionVec_9),
    .io_out_4_bits_exceptionVec_10(io_out_4_bits_exceptionVec_10),
    .io_out_4_bits_exceptionVec_11(io_out_4_bits_exceptionVec_11),
    .io_out_4_bits_exceptionVec_12(io_out_4_bits_exceptionVec_12),
    .io_out_4_bits_exceptionVec_13(io_out_4_bits_exceptionVec_13),
    .io_out_4_bits_exceptionVec_14(io_out_4_bits_exceptionVec_14),
    .io_out_4_bits_exceptionVec_15(io_out_4_bits_exceptionVec_15),
    .io_out_4_bits_exceptionVec_16(io_out_4_bits_exceptionVec_16),
    .io_out_4_bits_exceptionVec_17(io_out_4_bits_exceptionVec_17),
    .io_out_4_bits_exceptionVec_18(io_out_4_bits_exceptionVec_18),
    .io_out_4_bits_exceptionVec_19(io_out_4_bits_exceptionVec_19),
    .io_out_4_bits_exceptionVec_20(io_out_4_bits_exceptionVec_20),
    .io_out_4_bits_exceptionVec_21(io_out_4_bits_exceptionVec_21),
    .io_out_4_bits_exceptionVec_22(io_out_4_bits_exceptionVec_22),
    .io_out_4_bits_exceptionVec_23(io_out_4_bits_exceptionVec_23),
    .io_out_4_bits_isFetchMalAddr(io_out_4_bits_isFetchMalAddr),
    .io_out_4_bits_trigger(io_out_4_bits_trigger),
    .io_out_4_bits_preDecodeInfo_isRVC(io_out_4_bits_preDecodeInfo_isRVC),
    .io_out_4_bits_preDecodeInfo_brType(io_out_4_bits_preDecodeInfo_brType),
    .io_out_4_bits_pred_taken(io_out_4_bits_pred_taken),
    .io_out_4_bits_crossPageIPFFix(io_out_4_bits_crossPageIPFFix),
    .io_out_4_bits_ftqPtr_flag(io_out_4_bits_ftqPtr_flag),
    .io_out_4_bits_ftqPtr_value(io_out_4_bits_ftqPtr_value),
    .io_out_4_bits_ftqOffset(io_out_4_bits_ftqOffset),
    .io_out_4_bits_srcType_0(io_out_4_bits_srcType_0),
    .io_out_4_bits_srcType_1(io_out_4_bits_srcType_1),
    .io_out_4_bits_srcType_2(io_out_4_bits_srcType_2),
    .io_out_4_bits_srcType_3(io_out_4_bits_srcType_3),
    .io_out_4_bits_srcType_4(io_out_4_bits_srcType_4),
    .io_out_4_bits_lsrc_0(io_out_4_bits_lsrc_0),
    .io_out_4_bits_lsrc_1(io_out_4_bits_lsrc_1),
    .io_out_4_bits_lsrc_2(io_out_4_bits_lsrc_2),
    .io_out_4_bits_ldest(io_out_4_bits_ldest),
    .io_out_4_bits_fuType(io_out_4_bits_fuType),
    .io_out_4_bits_fuOpType(io_out_4_bits_fuOpType),
    .io_out_4_bits_rfWen(io_out_4_bits_rfWen),
    .io_out_4_bits_fpWen(io_out_4_bits_fpWen),
    .io_out_4_bits_vecWen(io_out_4_bits_vecWen),
    .io_out_4_bits_v0Wen(io_out_4_bits_v0Wen),
    .io_out_4_bits_vlWen(io_out_4_bits_vlWen),
    .io_out_4_bits_isXSTrap(io_out_4_bits_isXSTrap),
    .io_out_4_bits_waitForward(io_out_4_bits_waitForward),
    .io_out_4_bits_blockBackward(io_out_4_bits_blockBackward),
    .io_out_4_bits_flushPipe(io_out_4_bits_flushPipe),
    .io_out_4_bits_canRobCompress(io_out_4_bits_canRobCompress),
    .io_out_4_bits_selImm(io_out_4_bits_selImm),
    .io_out_4_bits_imm(io_out_4_bits_imm),
    .io_out_4_bits_fpu_typeTagOut(io_out_4_bits_fpu_typeTagOut),
    .io_out_4_bits_fpu_wflags(io_out_4_bits_fpu_wflags),
    .io_out_4_bits_fpu_typ(io_out_4_bits_fpu_typ),
    .io_out_4_bits_fpu_fmt(io_out_4_bits_fpu_fmt),
    .io_out_4_bits_fpu_rm(io_out_4_bits_fpu_rm),
    .io_out_4_bits_vpu_vill(io_out_4_bits_vpu_vill),
    .io_out_4_bits_vpu_vma(io_out_4_bits_vpu_vma),
    .io_out_4_bits_vpu_vta(io_out_4_bits_vpu_vta),
    .io_out_4_bits_vpu_vsew(io_out_4_bits_vpu_vsew),
    .io_out_4_bits_vpu_vlmul(io_out_4_bits_vpu_vlmul),
    .io_out_4_bits_vpu_specVill(io_out_4_bits_vpu_specVill),
    .io_out_4_bits_vpu_specVma(io_out_4_bits_vpu_specVma),
    .io_out_4_bits_vpu_specVta(io_out_4_bits_vpu_specVta),
    .io_out_4_bits_vpu_specVsew(io_out_4_bits_vpu_specVsew),
    .io_out_4_bits_vpu_specVlmul(io_out_4_bits_vpu_specVlmul),
    .io_out_4_bits_vpu_vm(io_out_4_bits_vpu_vm),
    .io_out_4_bits_vpu_vstart(io_out_4_bits_vpu_vstart),
    .io_out_4_bits_vpu_fpu_isFoldTo1_2(io_out_4_bits_vpu_fpu_isFoldTo1_2),
    .io_out_4_bits_vpu_fpu_isFoldTo1_4(io_out_4_bits_vpu_fpu_isFoldTo1_4),
    .io_out_4_bits_vpu_fpu_isFoldTo1_8(io_out_4_bits_vpu_fpu_isFoldTo1_8),
    .io_out_4_bits_vpu_nf(io_out_4_bits_vpu_nf),
    .io_out_4_bits_vpu_veew(io_out_4_bits_vpu_veew),
    .io_out_4_bits_vpu_isExt(io_out_4_bits_vpu_isExt),
    .io_out_4_bits_vpu_isNarrow(io_out_4_bits_vpu_isNarrow),
    .io_out_4_bits_vpu_isDstMask(io_out_4_bits_vpu_isDstMask),
    .io_out_4_bits_vpu_isOpMask(io_out_4_bits_vpu_isOpMask),
    .io_out_4_bits_vpu_isDependOldVd(io_out_4_bits_vpu_isDependOldVd),
    .io_out_4_bits_vpu_isWritePartVd(io_out_4_bits_vpu_isWritePartVd),
    .io_out_4_bits_vpu_isVleff(io_out_4_bits_vpu_isVleff),
    .io_out_4_bits_vlsInstr(io_out_4_bits_vlsInstr),
    .io_out_4_bits_wfflags(io_out_4_bits_wfflags),
    .io_out_4_bits_isMove(io_out_4_bits_isMove),
    .io_out_4_bits_uopIdx(io_out_4_bits_uopIdx),
    .io_out_4_bits_uopSplitType(io_out_4_bits_uopSplitType),
    .io_out_4_bits_isVset(io_out_4_bits_isVset),
    .io_out_4_bits_firstUop(io_out_4_bits_firstUop),
    .io_out_4_bits_lastUop(io_out_4_bits_lastUop),
    .io_out_4_bits_numWB(io_out_4_bits_numWB),
    .io_out_4_bits_commitType(io_out_4_bits_commitType),
    .io_out_5_ready(io_out_5_ready),
    .io_out_5_valid(io_out_5_valid),
    .io_out_5_bits_instr(io_out_5_bits_instr),
    .io_out_5_bits_foldpc(io_out_5_bits_foldpc),
    .io_out_5_bits_exceptionVec_0(io_out_5_bits_exceptionVec_0),
    .io_out_5_bits_exceptionVec_1(io_out_5_bits_exceptionVec_1),
    .io_out_5_bits_exceptionVec_2(io_out_5_bits_exceptionVec_2),
    .io_out_5_bits_exceptionVec_3(io_out_5_bits_exceptionVec_3),
    .io_out_5_bits_exceptionVec_4(io_out_5_bits_exceptionVec_4),
    .io_out_5_bits_exceptionVec_5(io_out_5_bits_exceptionVec_5),
    .io_out_5_bits_exceptionVec_6(io_out_5_bits_exceptionVec_6),
    .io_out_5_bits_exceptionVec_7(io_out_5_bits_exceptionVec_7),
    .io_out_5_bits_exceptionVec_8(io_out_5_bits_exceptionVec_8),
    .io_out_5_bits_exceptionVec_9(io_out_5_bits_exceptionVec_9),
    .io_out_5_bits_exceptionVec_10(io_out_5_bits_exceptionVec_10),
    .io_out_5_bits_exceptionVec_11(io_out_5_bits_exceptionVec_11),
    .io_out_5_bits_exceptionVec_12(io_out_5_bits_exceptionVec_12),
    .io_out_5_bits_exceptionVec_13(io_out_5_bits_exceptionVec_13),
    .io_out_5_bits_exceptionVec_14(io_out_5_bits_exceptionVec_14),
    .io_out_5_bits_exceptionVec_15(io_out_5_bits_exceptionVec_15),
    .io_out_5_bits_exceptionVec_16(io_out_5_bits_exceptionVec_16),
    .io_out_5_bits_exceptionVec_17(io_out_5_bits_exceptionVec_17),
    .io_out_5_bits_exceptionVec_18(io_out_5_bits_exceptionVec_18),
    .io_out_5_bits_exceptionVec_19(io_out_5_bits_exceptionVec_19),
    .io_out_5_bits_exceptionVec_20(io_out_5_bits_exceptionVec_20),
    .io_out_5_bits_exceptionVec_21(io_out_5_bits_exceptionVec_21),
    .io_out_5_bits_exceptionVec_22(io_out_5_bits_exceptionVec_22),
    .io_out_5_bits_exceptionVec_23(io_out_5_bits_exceptionVec_23),
    .io_out_5_bits_isFetchMalAddr(io_out_5_bits_isFetchMalAddr),
    .io_out_5_bits_trigger(io_out_5_bits_trigger),
    .io_out_5_bits_preDecodeInfo_isRVC(io_out_5_bits_preDecodeInfo_isRVC),
    .io_out_5_bits_preDecodeInfo_brType(io_out_5_bits_preDecodeInfo_brType),
    .io_out_5_bits_pred_taken(io_out_5_bits_pred_taken),
    .io_out_5_bits_crossPageIPFFix(io_out_5_bits_crossPageIPFFix),
    .io_out_5_bits_ftqPtr_flag(io_out_5_bits_ftqPtr_flag),
    .io_out_5_bits_ftqPtr_value(io_out_5_bits_ftqPtr_value),
    .io_out_5_bits_ftqOffset(io_out_5_bits_ftqOffset),
    .io_out_5_bits_srcType_0(io_out_5_bits_srcType_0),
    .io_out_5_bits_srcType_1(io_out_5_bits_srcType_1),
    .io_out_5_bits_srcType_2(io_out_5_bits_srcType_2),
    .io_out_5_bits_srcType_3(io_out_5_bits_srcType_3),
    .io_out_5_bits_srcType_4(io_out_5_bits_srcType_4),
    .io_out_5_bits_lsrc_0(io_out_5_bits_lsrc_0),
    .io_out_5_bits_lsrc_1(io_out_5_bits_lsrc_1),
    .io_out_5_bits_lsrc_2(io_out_5_bits_lsrc_2),
    .io_out_5_bits_ldest(io_out_5_bits_ldest),
    .io_out_5_bits_fuType(io_out_5_bits_fuType),
    .io_out_5_bits_fuOpType(io_out_5_bits_fuOpType),
    .io_out_5_bits_rfWen(io_out_5_bits_rfWen),
    .io_out_5_bits_fpWen(io_out_5_bits_fpWen),
    .io_out_5_bits_vecWen(io_out_5_bits_vecWen),
    .io_out_5_bits_v0Wen(io_out_5_bits_v0Wen),
    .io_out_5_bits_vlWen(io_out_5_bits_vlWen),
    .io_out_5_bits_isXSTrap(io_out_5_bits_isXSTrap),
    .io_out_5_bits_waitForward(io_out_5_bits_waitForward),
    .io_out_5_bits_blockBackward(io_out_5_bits_blockBackward),
    .io_out_5_bits_flushPipe(io_out_5_bits_flushPipe),
    .io_out_5_bits_canRobCompress(io_out_5_bits_canRobCompress),
    .io_out_5_bits_selImm(io_out_5_bits_selImm),
    .io_out_5_bits_imm(io_out_5_bits_imm),
    .io_out_5_bits_fpu_typeTagOut(io_out_5_bits_fpu_typeTagOut),
    .io_out_5_bits_fpu_wflags(io_out_5_bits_fpu_wflags),
    .io_out_5_bits_fpu_typ(io_out_5_bits_fpu_typ),
    .io_out_5_bits_fpu_fmt(io_out_5_bits_fpu_fmt),
    .io_out_5_bits_fpu_rm(io_out_5_bits_fpu_rm),
    .io_out_5_bits_vpu_vill(io_out_5_bits_vpu_vill),
    .io_out_5_bits_vpu_vma(io_out_5_bits_vpu_vma),
    .io_out_5_bits_vpu_vta(io_out_5_bits_vpu_vta),
    .io_out_5_bits_vpu_vsew(io_out_5_bits_vpu_vsew),
    .io_out_5_bits_vpu_vlmul(io_out_5_bits_vpu_vlmul),
    .io_out_5_bits_vpu_specVill(io_out_5_bits_vpu_specVill),
    .io_out_5_bits_vpu_specVma(io_out_5_bits_vpu_specVma),
    .io_out_5_bits_vpu_specVta(io_out_5_bits_vpu_specVta),
    .io_out_5_bits_vpu_specVsew(io_out_5_bits_vpu_specVsew),
    .io_out_5_bits_vpu_specVlmul(io_out_5_bits_vpu_specVlmul),
    .io_out_5_bits_vpu_vm(io_out_5_bits_vpu_vm),
    .io_out_5_bits_vpu_vstart(io_out_5_bits_vpu_vstart),
    .io_out_5_bits_vpu_fpu_isFoldTo1_2(io_out_5_bits_vpu_fpu_isFoldTo1_2),
    .io_out_5_bits_vpu_fpu_isFoldTo1_4(io_out_5_bits_vpu_fpu_isFoldTo1_4),
    .io_out_5_bits_vpu_fpu_isFoldTo1_8(io_out_5_bits_vpu_fpu_isFoldTo1_8),
    .io_out_5_bits_vpu_nf(io_out_5_bits_vpu_nf),
    .io_out_5_bits_vpu_veew(io_out_5_bits_vpu_veew),
    .io_out_5_bits_vpu_isExt(io_out_5_bits_vpu_isExt),
    .io_out_5_bits_vpu_isNarrow(io_out_5_bits_vpu_isNarrow),
    .io_out_5_bits_vpu_isDstMask(io_out_5_bits_vpu_isDstMask),
    .io_out_5_bits_vpu_isOpMask(io_out_5_bits_vpu_isOpMask),
    .io_out_5_bits_vpu_isDependOldVd(io_out_5_bits_vpu_isDependOldVd),
    .io_out_5_bits_vpu_isWritePartVd(io_out_5_bits_vpu_isWritePartVd),
    .io_out_5_bits_vpu_isVleff(io_out_5_bits_vpu_isVleff),
    .io_out_5_bits_vlsInstr(io_out_5_bits_vlsInstr),
    .io_out_5_bits_wfflags(io_out_5_bits_wfflags),
    .io_out_5_bits_isMove(io_out_5_bits_isMove),
    .io_out_5_bits_uopIdx(io_out_5_bits_uopIdx),
    .io_out_5_bits_uopSplitType(io_out_5_bits_uopSplitType),
    .io_out_5_bits_isVset(io_out_5_bits_isVset),
    .io_out_5_bits_firstUop(io_out_5_bits_firstUop),
    .io_out_5_bits_lastUop(io_out_5_bits_lastUop),
    .io_out_5_bits_numWB(io_out_5_bits_numWB),
    .io_out_5_bits_commitType(io_out_5_bits_commitType),
    .io_intRat_0_0_hold(io_intRat_0_0_hold),
    .io_intRat_0_0_addr(io_intRat_0_0_addr),
    .io_intRat_0_1_hold(io_intRat_0_1_hold),
    .io_intRat_0_1_addr(io_intRat_0_1_addr),
    .io_intRat_1_0_hold(io_intRat_1_0_hold),
    .io_intRat_1_0_addr(io_intRat_1_0_addr),
    .io_intRat_1_1_hold(io_intRat_1_1_hold),
    .io_intRat_1_1_addr(io_intRat_1_1_addr),
    .io_intRat_2_0_hold(io_intRat_2_0_hold),
    .io_intRat_2_0_addr(io_intRat_2_0_addr),
    .io_intRat_2_1_hold(io_intRat_2_1_hold),
    .io_intRat_2_1_addr(io_intRat_2_1_addr),
    .io_intRat_3_0_hold(io_intRat_3_0_hold),
    .io_intRat_3_0_addr(io_intRat_3_0_addr),
    .io_intRat_3_1_hold(io_intRat_3_1_hold),
    .io_intRat_3_1_addr(io_intRat_3_1_addr),
    .io_intRat_4_0_hold(io_intRat_4_0_hold),
    .io_intRat_4_0_addr(io_intRat_4_0_addr),
    .io_intRat_4_1_hold(io_intRat_4_1_hold),
    .io_intRat_4_1_addr(io_intRat_4_1_addr),
    .io_intRat_5_0_hold(io_intRat_5_0_hold),
    .io_intRat_5_0_addr(io_intRat_5_0_addr),
    .io_intRat_5_1_hold(io_intRat_5_1_hold),
    .io_intRat_5_1_addr(io_intRat_5_1_addr),
    .io_fpRat_0_0_hold(io_fpRat_0_0_hold),
    .io_fpRat_0_0_addr(io_fpRat_0_0_addr),
    .io_fpRat_0_1_hold(io_fpRat_0_1_hold),
    .io_fpRat_0_1_addr(io_fpRat_0_1_addr),
    .io_fpRat_0_2_hold(io_fpRat_0_2_hold),
    .io_fpRat_0_2_addr(io_fpRat_0_2_addr),
    .io_fpRat_1_0_hold(io_fpRat_1_0_hold),
    .io_fpRat_1_0_addr(io_fpRat_1_0_addr),
    .io_fpRat_1_1_hold(io_fpRat_1_1_hold),
    .io_fpRat_1_1_addr(io_fpRat_1_1_addr),
    .io_fpRat_1_2_hold(io_fpRat_1_2_hold),
    .io_fpRat_1_2_addr(io_fpRat_1_2_addr),
    .io_fpRat_2_0_hold(io_fpRat_2_0_hold),
    .io_fpRat_2_0_addr(io_fpRat_2_0_addr),
    .io_fpRat_2_1_hold(io_fpRat_2_1_hold),
    .io_fpRat_2_1_addr(io_fpRat_2_1_addr),
    .io_fpRat_2_2_hold(io_fpRat_2_2_hold),
    .io_fpRat_2_2_addr(io_fpRat_2_2_addr),
    .io_fpRat_3_0_hold(io_fpRat_3_0_hold),
    .io_fpRat_3_0_addr(io_fpRat_3_0_addr),
    .io_fpRat_3_1_hold(io_fpRat_3_1_hold),
    .io_fpRat_3_1_addr(io_fpRat_3_1_addr),
    .io_fpRat_3_2_hold(io_fpRat_3_2_hold),
    .io_fpRat_3_2_addr(io_fpRat_3_2_addr),
    .io_fpRat_4_0_hold(io_fpRat_4_0_hold),
    .io_fpRat_4_0_addr(io_fpRat_4_0_addr),
    .io_fpRat_4_1_hold(io_fpRat_4_1_hold),
    .io_fpRat_4_1_addr(io_fpRat_4_1_addr),
    .io_fpRat_4_2_hold(io_fpRat_4_2_hold),
    .io_fpRat_4_2_addr(io_fpRat_4_2_addr),
    .io_fpRat_5_0_hold(io_fpRat_5_0_hold),
    .io_fpRat_5_0_addr(io_fpRat_5_0_addr),
    .io_fpRat_5_1_hold(io_fpRat_5_1_hold),
    .io_fpRat_5_1_addr(io_fpRat_5_1_addr),
    .io_fpRat_5_2_hold(io_fpRat_5_2_hold),
    .io_fpRat_5_2_addr(io_fpRat_5_2_addr),
    .io_vecRat_0_0_hold(io_vecRat_0_0_hold),
    .io_vecRat_0_0_addr(io_vecRat_0_0_addr),
    .io_vecRat_0_1_hold(io_vecRat_0_1_hold),
    .io_vecRat_0_1_addr(io_vecRat_0_1_addr),
    .io_vecRat_0_2_hold(io_vecRat_0_2_hold),
    .io_vecRat_0_2_addr(io_vecRat_0_2_addr),
    .io_vecRat_1_0_hold(io_vecRat_1_0_hold),
    .io_vecRat_1_0_addr(io_vecRat_1_0_addr),
    .io_vecRat_1_1_hold(io_vecRat_1_1_hold),
    .io_vecRat_1_1_addr(io_vecRat_1_1_addr),
    .io_vecRat_1_2_hold(io_vecRat_1_2_hold),
    .io_vecRat_1_2_addr(io_vecRat_1_2_addr),
    .io_vecRat_2_0_hold(io_vecRat_2_0_hold),
    .io_vecRat_2_0_addr(io_vecRat_2_0_addr),
    .io_vecRat_2_1_hold(io_vecRat_2_1_hold),
    .io_vecRat_2_1_addr(io_vecRat_2_1_addr),
    .io_vecRat_2_2_hold(io_vecRat_2_2_hold),
    .io_vecRat_2_2_addr(io_vecRat_2_2_addr),
    .io_vecRat_3_0_hold(io_vecRat_3_0_hold),
    .io_vecRat_3_0_addr(io_vecRat_3_0_addr),
    .io_vecRat_3_1_hold(io_vecRat_3_1_hold),
    .io_vecRat_3_1_addr(io_vecRat_3_1_addr),
    .io_vecRat_3_2_hold(io_vecRat_3_2_hold),
    .io_vecRat_3_2_addr(io_vecRat_3_2_addr),
    .io_vecRat_4_0_hold(io_vecRat_4_0_hold),
    .io_vecRat_4_0_addr(io_vecRat_4_0_addr),
    .io_vecRat_4_1_hold(io_vecRat_4_1_hold),
    .io_vecRat_4_1_addr(io_vecRat_4_1_addr),
    .io_vecRat_4_2_hold(io_vecRat_4_2_hold),
    .io_vecRat_4_2_addr(io_vecRat_4_2_addr),
    .io_vecRat_5_0_hold(io_vecRat_5_0_hold),
    .io_vecRat_5_0_addr(io_vecRat_5_0_addr),
    .io_vecRat_5_1_hold(io_vecRat_5_1_hold),
    .io_vecRat_5_1_addr(io_vecRat_5_1_addr),
    .io_vecRat_5_2_hold(io_vecRat_5_2_hold),
    .io_vecRat_5_2_addr(io_vecRat_5_2_addr),
    .io_csrCtrl_singlestep(io_csrCtrl_singlestep),
    .io_fromCSR_illegalInst_sfenceVMA(io_fromCSR_illegalInst_sfenceVMA),
    .io_fromCSR_illegalInst_sfencePart(io_fromCSR_illegalInst_sfencePart),
    .io_fromCSR_illegalInst_hfenceGVMA(io_fromCSR_illegalInst_hfenceGVMA),
    .io_fromCSR_illegalInst_hfenceVVMA(io_fromCSR_illegalInst_hfenceVVMA),
    .io_fromCSR_illegalInst_hlsv(io_fromCSR_illegalInst_hlsv),
    .io_fromCSR_illegalInst_fsIsOff(io_fromCSR_illegalInst_fsIsOff),
    .io_fromCSR_illegalInst_vsIsOff(io_fromCSR_illegalInst_vsIsOff),
    .io_fromCSR_illegalInst_wfi(io_fromCSR_illegalInst_wfi),
    .io_fromCSR_illegalInst_wrs_nto(io_fromCSR_illegalInst_wrs_nto),
    .io_fromCSR_illegalInst_frm(io_fromCSR_illegalInst_frm),
    .io_fromCSR_illegalInst_cboZ(io_fromCSR_illegalInst_cboZ),
    .io_fromCSR_illegalInst_cboCF(io_fromCSR_illegalInst_cboCF),
    .io_fromCSR_illegalInst_cboI(io_fromCSR_illegalInst_cboI),
    .io_fromCSR_virtualInst_sfenceVMA(io_fromCSR_virtualInst_sfenceVMA),
    .io_fromCSR_virtualInst_sfencePart(io_fromCSR_virtualInst_sfencePart),
    .io_fromCSR_virtualInst_hfence(io_fromCSR_virtualInst_hfence),
    .io_fromCSR_virtualInst_hlsv(io_fromCSR_virtualInst_hlsv),
    .io_fromCSR_virtualInst_wfi(io_fromCSR_virtualInst_wfi),
    .io_fromCSR_virtualInst_wrs_nto(io_fromCSR_virtualInst_wrs_nto),
    .io_fromCSR_virtualInst_cboZ(io_fromCSR_virtualInst_cboZ),
    .io_fromCSR_virtualInst_cboCF(io_fromCSR_virtualInst_cboCF),
    .io_fromCSR_virtualInst_cboI(io_fromCSR_virtualInst_cboI),
    .io_fromCSR_special_cboI2F(io_fromCSR_special_cboI2F),
    .io_fusion_0(io_fusion_0),
    .io_fusion_1(io_fusion_1),
    .io_fusion_2(io_fusion_2),
    .io_fusion_3(io_fusion_3),
    .io_fusion_4(io_fusion_4),
    .io_fromRob_isResumeVType(io_fromRob_isResumeVType),
    .io_fromRob_walkToArchVType(io_fromRob_walkToArchVType),
    .io_fromRob_commitVType_vtype_valid(io_fromRob_commitVType_vtype_valid),
    .io_fromRob_commitVType_vtype_bits_illegal(io_fromRob_commitVType_vtype_bits_illegal),
    .io_fromRob_commitVType_vtype_bits_vma(io_fromRob_commitVType_vtype_bits_vma),
    .io_fromRob_commitVType_vtype_bits_vta(io_fromRob_commitVType_vtype_bits_vta),
    .io_fromRob_commitVType_vtype_bits_vsew(io_fromRob_commitVType_vtype_bits_vsew),
    .io_fromRob_commitVType_vtype_bits_vlmul(io_fromRob_commitVType_vtype_bits_vlmul),
    .io_fromRob_commitVType_hasVsetvl(io_fromRob_commitVType_hasVsetvl),
    .io_fromRob_walkVType_valid(io_fromRob_walkVType_valid),
    .io_fromRob_walkVType_bits_illegal(io_fromRob_walkVType_bits_illegal),
    .io_fromRob_walkVType_bits_vma(io_fromRob_walkVType_bits_vma),
    .io_fromRob_walkVType_bits_vta(io_fromRob_walkVType_bits_vta),
    .io_fromRob_walkVType_bits_vsew(io_fromRob_walkVType_bits_vsew),
    .io_fromRob_walkVType_bits_vlmul(io_fromRob_walkVType_bits_vlmul),
    .io_stallReason_in_reason_0(io_stallReason_in_reason_0),
    .io_stallReason_in_reason_1(io_stallReason_in_reason_1),
    .io_stallReason_in_reason_2(io_stallReason_in_reason_2),
    .io_stallReason_in_reason_3(io_stallReason_in_reason_3),
    .io_stallReason_in_reason_4(io_stallReason_in_reason_4),
    .io_stallReason_in_reason_5(io_stallReason_in_reason_5),
    .io_stallReason_in_backReason_valid(io_stallReason_in_backReason_valid),
    .io_stallReason_in_backReason_bits(io_stallReason_in_backReason_bits),
    .io_stallReason_out_reason_0(io_stallReason_out_reason_0),
    .io_stallReason_out_reason_1(io_stallReason_out_reason_1),
    .io_stallReason_out_reason_2(io_stallReason_out_reason_2),
    .io_stallReason_out_reason_3(io_stallReason_out_reason_3),
    .io_stallReason_out_reason_4(io_stallReason_out_reason_4),
    .io_stallReason_out_reason_5(io_stallReason_out_reason_5),
    .io_stallReason_out_backReason_valid(io_stallReason_out_backReason_valid),
    .io_stallReason_out_backReason_bits(io_stallReason_out_backReason_bits),
    .io_vsetvlVType_illegal(io_vsetvlVType_illegal),
    .io_vsetvlVType_vma(io_vsetvlVType_vma),
    .io_vsetvlVType_vta(io_vsetvlVType_vta),
    .io_vsetvlVType_vsew(io_vsetvlVType_vsew),
    .io_vsetvlVType_vlmul(io_vsetvlVType_vlmul),
    .io_vstart(io_vstart),
    .io_toCSR_trapInstInfo_valid(io_toCSR_trapInstInfo_valid),
    .io_toCSR_trapInstInfo_bits_instr(io_toCSR_trapInstInfo_bits_instr),
    .io_toCSR_trapInstInfo_bits_ftqPtr_flag(io_toCSR_trapInstInfo_bits_ftqPtr_flag),
    .io_toCSR_trapInstInfo_bits_ftqPtr_value(io_toCSR_trapInstInfo_bits_ftqPtr_value),
    .io_toCSR_trapInstInfo_bits_ftqOffset(io_toCSR_trapInstInfo_bits_ftqOffset),
    .io_perf_0_value(io_perf_0_value),
    .io_perf_1_value(io_perf_1_value),
    .io_perf_2_value(io_perf_2_value),
    .io_perf_3_value(io_perf_3_value),
    .io_perf_4_value(io_perf_4_value),
    .io_perf_5_value(io_perf_5_value)
  );
endmodule
