// xs_ExceptionGen_core — readable faithful (bug-for-bug) core for golden
// ExceptionGen (Rob exception aggregation pipeline). Generated by
// scripts/gen_exceptiongen.py from G0 golden ExceptionGen.sv.
//
// Golden is a firtool single-module pipeline (0 submodules, 0 memory):
//   s0: per-writeback-group oldest-select into 5 s0_out slots
//   s1: oldest-of-5 tree-reduce into s1_out; enq path in parallel
//   current: the held oldest exception state (io_state output)
// This core keeps golden's exact register set and exact next-state
// expressions; only the cryptic firtool intermediate wire names
// (_GEN*/_T_*) are renamed to descriptive identifiers (see gen script).
// Do not hand-edit; regenerate via gen_exceptiongen.py.
module xs_ExceptionGen_core(
  input  clock,
  input  reset,
  input  io_redirect_valid,
  input  io_redirect_bits_robIdx_flag,
  input  [7:0] io_redirect_bits_robIdx_value,
  input  io_redirect_bits_level,
  input  io_flush,
  input  io_enq_0_valid,
  input  io_enq_0_bits_robIdx_flag,
  input  [7:0] io_enq_0_bits_robIdx_value,
  input  [5:0] io_enq_0_bits_ftqPtr_value,
  input  [3:0] io_enq_0_bits_ftqOffset,
  input  io_enq_0_bits_hasException,
  input  io_enq_0_bits_exceptionVec_0,
  input  io_enq_0_bits_exceptionVec_1,
  input  io_enq_0_bits_exceptionVec_2,
  input  io_enq_0_bits_exceptionVec_3,
  input  io_enq_0_bits_exceptionVec_12,
  input  io_enq_0_bits_exceptionVec_20,
  input  io_enq_0_bits_exceptionVec_22,
  input  io_enq_0_bits_isFetchMalAddr,
  input  io_enq_0_bits_flushPipe,
  input  io_enq_0_bits_isVset,
  input  io_enq_0_bits_singleStep,
  input  io_enq_0_bits_crossPageIPFFix,
  input  [3:0] io_enq_0_bits_trigger,
  input  io_enq_1_valid,
  input  io_enq_1_bits_robIdx_flag,
  input  [7:0] io_enq_1_bits_robIdx_value,
  input  [5:0] io_enq_1_bits_ftqPtr_value,
  input  [3:0] io_enq_1_bits_ftqOffset,
  input  io_enq_1_bits_hasException,
  input  io_enq_1_bits_exceptionVec_0,
  input  io_enq_1_bits_exceptionVec_1,
  input  io_enq_1_bits_exceptionVec_2,
  input  io_enq_1_bits_exceptionVec_3,
  input  io_enq_1_bits_exceptionVec_12,
  input  io_enq_1_bits_exceptionVec_20,
  input  io_enq_1_bits_exceptionVec_22,
  input  io_enq_1_bits_isFetchMalAddr,
  input  io_enq_1_bits_flushPipe,
  input  io_enq_1_bits_isVset,
  input  io_enq_1_bits_singleStep,
  input  io_enq_1_bits_crossPageIPFFix,
  input  [3:0] io_enq_1_bits_trigger,
  input  io_enq_2_valid,
  input  io_enq_2_bits_robIdx_flag,
  input  [7:0] io_enq_2_bits_robIdx_value,
  input  [5:0] io_enq_2_bits_ftqPtr_value,
  input  [3:0] io_enq_2_bits_ftqOffset,
  input  io_enq_2_bits_hasException,
  input  io_enq_2_bits_exceptionVec_0,
  input  io_enq_2_bits_exceptionVec_1,
  input  io_enq_2_bits_exceptionVec_2,
  input  io_enq_2_bits_exceptionVec_3,
  input  io_enq_2_bits_exceptionVec_12,
  input  io_enq_2_bits_exceptionVec_20,
  input  io_enq_2_bits_exceptionVec_22,
  input  io_enq_2_bits_isFetchMalAddr,
  input  io_enq_2_bits_flushPipe,
  input  io_enq_2_bits_isVset,
  input  io_enq_2_bits_singleStep,
  input  io_enq_2_bits_crossPageIPFFix,
  input  [3:0] io_enq_2_bits_trigger,
  input  io_enq_3_valid,
  input  io_enq_3_bits_robIdx_flag,
  input  [7:0] io_enq_3_bits_robIdx_value,
  input  [5:0] io_enq_3_bits_ftqPtr_value,
  input  [3:0] io_enq_3_bits_ftqOffset,
  input  io_enq_3_bits_hasException,
  input  io_enq_3_bits_exceptionVec_0,
  input  io_enq_3_bits_exceptionVec_1,
  input  io_enq_3_bits_exceptionVec_2,
  input  io_enq_3_bits_exceptionVec_3,
  input  io_enq_3_bits_exceptionVec_12,
  input  io_enq_3_bits_exceptionVec_20,
  input  io_enq_3_bits_exceptionVec_22,
  input  io_enq_3_bits_isFetchMalAddr,
  input  io_enq_3_bits_flushPipe,
  input  io_enq_3_bits_isVset,
  input  io_enq_3_bits_singleStep,
  input  io_enq_3_bits_crossPageIPFFix,
  input  [3:0] io_enq_3_bits_trigger,
  input  io_enq_4_valid,
  input  io_enq_4_bits_robIdx_flag,
  input  [7:0] io_enq_4_bits_robIdx_value,
  input  [5:0] io_enq_4_bits_ftqPtr_value,
  input  [3:0] io_enq_4_bits_ftqOffset,
  input  io_enq_4_bits_hasException,
  input  io_enq_4_bits_exceptionVec_0,
  input  io_enq_4_bits_exceptionVec_1,
  input  io_enq_4_bits_exceptionVec_2,
  input  io_enq_4_bits_exceptionVec_3,
  input  io_enq_4_bits_exceptionVec_12,
  input  io_enq_4_bits_exceptionVec_20,
  input  io_enq_4_bits_exceptionVec_22,
  input  io_enq_4_bits_isFetchMalAddr,
  input  io_enq_4_bits_flushPipe,
  input  io_enq_4_bits_isVset,
  input  io_enq_4_bits_singleStep,
  input  io_enq_4_bits_crossPageIPFFix,
  input  [3:0] io_enq_4_bits_trigger,
  input  io_enq_5_valid,
  input  io_enq_5_bits_robIdx_flag,
  input  [7:0] io_enq_5_bits_robIdx_value,
  input  [5:0] io_enq_5_bits_ftqPtr_value,
  input  [3:0] io_enq_5_bits_ftqOffset,
  input  io_enq_5_bits_hasException,
  input  io_enq_5_bits_exceptionVec_0,
  input  io_enq_5_bits_exceptionVec_1,
  input  io_enq_5_bits_exceptionVec_2,
  input  io_enq_5_bits_exceptionVec_3,
  input  io_enq_5_bits_exceptionVec_12,
  input  io_enq_5_bits_exceptionVec_20,
  input  io_enq_5_bits_exceptionVec_22,
  input  io_enq_5_bits_isFetchMalAddr,
  input  io_enq_5_bits_flushPipe,
  input  io_enq_5_bits_isVset,
  input  io_enq_5_bits_singleStep,
  input  io_enq_5_bits_crossPageIPFFix,
  input  [3:0] io_enq_5_bits_trigger,
  input  io_wb_0_valid,
  input  io_wb_0_bits_robIdx_flag,
  input  [7:0] io_wb_0_bits_robIdx_value,
  input  io_wb_0_bits_hasException,
  input  io_wb_0_bits_exceptionVec_2,
  input  io_wb_0_bits_exceptionVec_3,
  input  io_wb_0_bits_exceptionVec_8,
  input  io_wb_0_bits_exceptionVec_9,
  input  io_wb_0_bits_exceptionVec_10,
  input  io_wb_0_bits_exceptionVec_11,
  input  io_wb_0_bits_exceptionVec_22,
  input  io_wb_0_bits_flushPipe,
  input  io_wb_1_valid,
  input  io_wb_1_bits_robIdx_flag,
  input  [7:0] io_wb_1_bits_robIdx_value,
  input  io_wb_1_bits_hasException,
  input  io_wb_1_bits_exceptionVec_2,
  input  io_wb_2_valid,
  input  io_wb_2_bits_robIdx_flag,
  input  [7:0] io_wb_2_bits_robIdx_value,
  input  io_wb_2_bits_hasException,
  input  io_wb_2_bits_exceptionVec_2,
  input  io_wb_3_bits_robIdx_flag,
  input  [7:0] io_wb_3_bits_robIdx_value,
  input  io_wb_4_bits_robIdx_flag,
  input  [7:0] io_wb_4_bits_robIdx_value,
  input  io_wb_5_bits_robIdx_flag,
  input  [7:0] io_wb_5_bits_robIdx_value,
  input  io_wb_6_valid,
  input  io_wb_6_bits_robIdx_flag,
  input  [7:0] io_wb_6_bits_robIdx_value,
  input  io_wb_6_bits_hasException,
  input  io_wb_6_bits_exceptionVec_0,
  input  io_wb_6_bits_exceptionVec_1,
  input  io_wb_6_bits_exceptionVec_2,
  input  io_wb_6_bits_exceptionVec_3,
  input  io_wb_6_bits_exceptionVec_4,
  input  io_wb_6_bits_exceptionVec_5,
  input  io_wb_6_bits_exceptionVec_6,
  input  io_wb_6_bits_exceptionVec_7,
  input  io_wb_6_bits_exceptionVec_8,
  input  io_wb_6_bits_exceptionVec_9,
  input  io_wb_6_bits_exceptionVec_10,
  input  io_wb_6_bits_exceptionVec_11,
  input  io_wb_6_bits_exceptionVec_12,
  input  io_wb_6_bits_exceptionVec_13,
  input  io_wb_6_bits_exceptionVec_14,
  input  io_wb_6_bits_exceptionVec_15,
  input  io_wb_6_bits_exceptionVec_16,
  input  io_wb_6_bits_exceptionVec_17,
  input  io_wb_6_bits_exceptionVec_18,
  input  io_wb_6_bits_exceptionVec_19,
  input  io_wb_6_bits_exceptionVec_20,
  input  io_wb_6_bits_exceptionVec_21,
  input  io_wb_6_bits_exceptionVec_22,
  input  io_wb_6_bits_exceptionVec_23,
  input  io_wb_6_bits_flushPipe,
  input  [3:0] io_wb_6_bits_trigger,
  input  io_wb_7_valid,
  input  io_wb_7_bits_robIdx_flag,
  input  [7:0] io_wb_7_bits_robIdx_value,
  input  io_wb_7_bits_hasException,
  input  io_wb_7_bits_exceptionVec_3,
  input  io_wb_7_bits_exceptionVec_6,
  input  io_wb_7_bits_exceptionVec_7,
  input  io_wb_7_bits_exceptionVec_15,
  input  io_wb_7_bits_exceptionVec_19,
  input  io_wb_7_bits_exceptionVec_23,
  input  [3:0] io_wb_7_bits_trigger,
  input  io_wb_8_valid,
  input  io_wb_8_bits_robIdx_flag,
  input  [7:0] io_wb_8_bits_robIdx_value,
  input  io_wb_8_bits_hasException,
  input  io_wb_8_bits_exceptionVec_0,
  input  io_wb_8_bits_exceptionVec_1,
  input  io_wb_8_bits_exceptionVec_2,
  input  io_wb_8_bits_exceptionVec_3,
  input  io_wb_8_bits_exceptionVec_4,
  input  io_wb_8_bits_exceptionVec_5,
  input  io_wb_8_bits_exceptionVec_6,
  input  io_wb_8_bits_exceptionVec_7,
  input  io_wb_8_bits_exceptionVec_8,
  input  io_wb_8_bits_exceptionVec_9,
  input  io_wb_8_bits_exceptionVec_10,
  input  io_wb_8_bits_exceptionVec_11,
  input  io_wb_8_bits_exceptionVec_12,
  input  io_wb_8_bits_exceptionVec_13,
  input  io_wb_8_bits_exceptionVec_14,
  input  io_wb_8_bits_exceptionVec_15,
  input  io_wb_8_bits_exceptionVec_16,
  input  io_wb_8_bits_exceptionVec_17,
  input  io_wb_8_bits_exceptionVec_18,
  input  io_wb_8_bits_exceptionVec_19,
  input  io_wb_8_bits_exceptionVec_20,
  input  io_wb_8_bits_exceptionVec_21,
  input  io_wb_8_bits_exceptionVec_22,
  input  io_wb_8_bits_exceptionVec_23,
  input  io_wb_8_bits_flushPipe,
  input  io_wb_8_bits_replayInst,
  input  [3:0] io_wb_8_bits_trigger,
  input  io_wb_9_valid,
  input  io_wb_9_bits_robIdx_flag,
  input  [7:0] io_wb_9_bits_robIdx_value,
  input  io_wb_9_bits_hasException,
  input  io_wb_9_bits_exceptionVec_3,
  input  io_wb_9_bits_exceptionVec_4,
  input  io_wb_9_bits_exceptionVec_5,
  input  io_wb_9_bits_exceptionVec_13,
  input  io_wb_9_bits_exceptionVec_19,
  input  io_wb_9_bits_exceptionVec_21,
  input  io_wb_9_bits_flushPipe,
  input  io_wb_9_bits_replayInst,
  input  [3:0] io_wb_9_bits_trigger,
  input  io_wb_10_valid,
  input  io_wb_10_bits_robIdx_flag,
  input  [7:0] io_wb_10_bits_robIdx_value,
  input  io_wb_10_bits_hasException,
  input  io_wb_10_bits_exceptionVec_3,
  input  io_wb_10_bits_exceptionVec_4,
  input  io_wb_10_bits_exceptionVec_5,
  input  io_wb_10_bits_exceptionVec_13,
  input  io_wb_10_bits_exceptionVec_19,
  input  io_wb_10_bits_exceptionVec_21,
  input  io_wb_10_bits_flushPipe,
  input  io_wb_10_bits_replayInst,
  input  [3:0] io_wb_10_bits_trigger,
  input  io_wb_11_valid,
  input  io_wb_11_bits_robIdx_flag,
  input  [7:0] io_wb_11_bits_robIdx_value,
  input  io_wb_11_bits_hasException,
  input  io_wb_11_bits_exceptionVec_0,
  input  io_wb_11_bits_exceptionVec_1,
  input  io_wb_11_bits_exceptionVec_2,
  input  io_wb_11_bits_exceptionVec_3,
  input  io_wb_11_bits_exceptionVec_4,
  input  io_wb_11_bits_exceptionVec_5,
  input  io_wb_11_bits_exceptionVec_6,
  input  io_wb_11_bits_exceptionVec_7,
  input  io_wb_11_bits_exceptionVec_8,
  input  io_wb_11_bits_exceptionVec_9,
  input  io_wb_11_bits_exceptionVec_10,
  input  io_wb_11_bits_exceptionVec_11,
  input  io_wb_11_bits_exceptionVec_12,
  input  io_wb_11_bits_exceptionVec_13,
  input  io_wb_11_bits_exceptionVec_14,
  input  io_wb_11_bits_exceptionVec_15,
  input  io_wb_11_bits_exceptionVec_16,
  input  io_wb_11_bits_exceptionVec_17,
  input  io_wb_11_bits_exceptionVec_18,
  input  io_wb_11_bits_exceptionVec_19,
  input  io_wb_11_bits_exceptionVec_20,
  input  io_wb_11_bits_exceptionVec_21,
  input  io_wb_11_bits_exceptionVec_22,
  input  io_wb_11_bits_exceptionVec_23,
  input  io_wb_11_bits_flushPipe,
  input  io_wb_11_bits_replayInst,
  input  [3:0] io_wb_11_bits_trigger,
  input  io_wb_11_bits_vstartEn,
  input  [63:0] io_wb_11_bits_vstart,
  input  [6:0] io_wb_11_bits_vuopIdx,
  input  io_wb_11_bits_isVecLoad,
  input  io_wb_11_bits_isVlm,
  input  io_wb_11_bits_isStrided,
  input  io_wb_11_bits_isIndexed,
  input  io_wb_11_bits_isWhole,
  input  [2:0] io_wb_11_bits_nf,
  input  [1:0] io_wb_11_bits_vsew,
  input  [1:0] io_wb_11_bits_veew,
  input  [2:0] io_wb_11_bits_vlmul,
  input  io_wb_12_valid,
  input  io_wb_12_bits_robIdx_flag,
  input  [7:0] io_wb_12_bits_robIdx_value,
  input  io_wb_12_bits_hasException,
  input  io_wb_12_bits_exceptionVec_3,
  input  io_wb_12_bits_exceptionVec_4,
  input  io_wb_12_bits_exceptionVec_5,
  input  io_wb_12_bits_exceptionVec_6,
  input  io_wb_12_bits_exceptionVec_7,
  input  io_wb_12_bits_exceptionVec_13,
  input  io_wb_12_bits_exceptionVec_15,
  input  io_wb_12_bits_exceptionVec_19,
  input  io_wb_12_bits_exceptionVec_21,
  input  io_wb_12_bits_exceptionVec_23,
  input  io_wb_12_bits_flushPipe,
  input  io_wb_12_bits_replayInst,
  input  [3:0] io_wb_12_bits_trigger,
  input  io_wb_12_bits_vstartEn,
  input  [63:0] io_wb_12_bits_vstart,
  input  [6:0] io_wb_12_bits_vuopIdx,
  input  io_wb_12_bits_isVecLoad,
  input  io_wb_12_bits_isVlm,
  input  io_wb_12_bits_isStrided,
  input  io_wb_12_bits_isIndexed,
  input  io_wb_12_bits_isWhole,
  input  [2:0] io_wb_12_bits_nf,
  input  [1:0] io_wb_12_bits_vsew,
  input  [1:0] io_wb_12_bits_veew,
  input  [2:0] io_wb_12_bits_vlmul,
  output io_state_valid,
  output io_state_bits_robIdx_flag,
  output [7:0] io_state_bits_robIdx_value,
  output [5:0] io_state_bits_ftqPtr_value,
  output [3:0] io_state_bits_ftqOffset,
  output io_state_bits_hasException,
  output io_state_bits_isEnqExcp,
  output io_state_bits_exceptionVec_0,
  output io_state_bits_exceptionVec_1,
  output io_state_bits_exceptionVec_2,
  output io_state_bits_exceptionVec_3,
  output io_state_bits_exceptionVec_4,
  output io_state_bits_exceptionVec_5,
  output io_state_bits_exceptionVec_6,
  output io_state_bits_exceptionVec_7,
  output io_state_bits_exceptionVec_8,
  output io_state_bits_exceptionVec_9,
  output io_state_bits_exceptionVec_10,
  output io_state_bits_exceptionVec_11,
  output io_state_bits_exceptionVec_12,
  output io_state_bits_exceptionVec_13,
  output io_state_bits_exceptionVec_14,
  output io_state_bits_exceptionVec_15,
  output io_state_bits_exceptionVec_16,
  output io_state_bits_exceptionVec_17,
  output io_state_bits_exceptionVec_18,
  output io_state_bits_exceptionVec_19,
  output io_state_bits_exceptionVec_20,
  output io_state_bits_exceptionVec_21,
  output io_state_bits_exceptionVec_22,
  output io_state_bits_exceptionVec_23,
  output io_state_bits_isFetchMalAddr,
  output io_state_bits_flushPipe,
  output io_state_bits_isVset,
  output io_state_bits_replayInst,
  output io_state_bits_singleStep,
  output io_state_bits_crossPageIPFFix,
  output [3:0] io_state_bits_trigger,
  output io_state_bits_vstartEn,
  output [63:0] io_state_bits_vstart,
  output io_state_bits_isVecLoad,
  output io_state_bits_isVlm,
  output io_state_bits_isStrided,
  output io_state_bits_isIndexed,
  output io_state_bits_isWhole,
  output [2:0] io_state_bits_nf,
  output [1:0] io_state_bits_vsew,
  output [1:0] io_state_bits_veew,
  output [2:0] io_state_bits_vlmul
);

  reg         currentValid;
  reg         current_robIdx_flag;
  reg  [7:0]  current_robIdx_value;
  reg  [5:0]  current_ftqPtr_value;
  reg  [3:0]  current_ftqOffset;
  reg         current_hasException;
  reg         current_isEnqExcp;
  reg         current_exceptionVec_0;
  reg         current_exceptionVec_1;
  reg         current_exceptionVec_2;
  reg         current_exceptionVec_3;
  reg         current_exceptionVec_4;
  reg         current_exceptionVec_5;
  reg         current_exceptionVec_6;
  reg         current_exceptionVec_7;
  reg         current_exceptionVec_8;
  reg         current_exceptionVec_9;
  reg         current_exceptionVec_10;
  reg         current_exceptionVec_11;
  reg         current_exceptionVec_12;
  reg         current_exceptionVec_13;
  reg         current_exceptionVec_14;
  reg         current_exceptionVec_15;
  reg         current_exceptionVec_16;
  reg         current_exceptionVec_17;
  reg         current_exceptionVec_18;
  reg         current_exceptionVec_19;
  reg         current_exceptionVec_20;
  reg         current_exceptionVec_21;
  reg         current_exceptionVec_22;
  reg         current_exceptionVec_23;
  reg         current_isFetchMalAddr;
  reg         current_flushPipe;
  reg         current_isVset;
  reg         current_replayInst;
  reg         current_singleStep;
  reg         current_crossPageIPFFix;
  reg  [3:0]  current_trigger;
  reg         current_vstartEn;
  reg  [63:0] current_vstart;
  reg         current_isVecLoad;
  reg         current_isVlm;
  reg         current_isStrided;
  reg         current_isIndexed;
  reg         current_isWhole;
  reg  [2:0]  current_nf;
  reg  [1:0]  current_vsew;
  reg  [1:0]  current_veew;
  reg  [2:0]  current_vlmul;
  reg         lastCycleFlush;
  wire [8:0]  redirect_robIdx_cat =
    {io_redirect_bits_robIdx_flag, io_redirect_bits_robIdx_value};
  reg         s0_out_valid_0;
  reg         s0_out_valid_1;
  reg         s0_out_valid_2;
  reg         s0_out_valid_3;
  reg         s0_out_valid_4;
  reg         s0_out_bits_0_robIdx_flag;
  reg  [7:0]  s0_out_bits_0_robIdx_value;
  reg         s0_out_bits_0_hasException;
  reg         s0_out_bits_0_exceptionVec_0;
  reg         s0_out_bits_0_exceptionVec_1;
  reg         s0_out_bits_0_exceptionVec_2;
  reg         s0_out_bits_0_exceptionVec_3;
  reg         s0_out_bits_0_exceptionVec_4;
  reg         s0_out_bits_0_exceptionVec_5;
  reg         s0_out_bits_0_exceptionVec_6;
  reg         s0_out_bits_0_exceptionVec_7;
  reg         s0_out_bits_0_exceptionVec_8;
  reg         s0_out_bits_0_exceptionVec_9;
  reg         s0_out_bits_0_exceptionVec_10;
  reg         s0_out_bits_0_exceptionVec_11;
  reg         s0_out_bits_0_exceptionVec_12;
  reg         s0_out_bits_0_exceptionVec_13;
  reg         s0_out_bits_0_exceptionVec_14;
  reg         s0_out_bits_0_exceptionVec_15;
  reg         s0_out_bits_0_exceptionVec_16;
  reg         s0_out_bits_0_exceptionVec_17;
  reg         s0_out_bits_0_exceptionVec_18;
  reg         s0_out_bits_0_exceptionVec_19;
  reg         s0_out_bits_0_exceptionVec_20;
  reg         s0_out_bits_0_exceptionVec_21;
  reg         s0_out_bits_0_exceptionVec_22;
  reg         s0_out_bits_0_exceptionVec_23;
  reg         s0_out_bits_0_flushPipe;
  reg         s0_out_bits_1_robIdx_flag;
  reg  [7:0]  s0_out_bits_1_robIdx_value;
  reg         s0_out_bits_1_hasException;
  reg         s0_out_bits_1_exceptionVec_0;
  reg         s0_out_bits_1_exceptionVec_1;
  reg         s0_out_bits_1_exceptionVec_2;
  reg         s0_out_bits_1_exceptionVec_3;
  reg         s0_out_bits_1_exceptionVec_4;
  reg         s0_out_bits_1_exceptionVec_5;
  reg         s0_out_bits_1_exceptionVec_6;
  reg         s0_out_bits_1_exceptionVec_7;
  reg         s0_out_bits_1_exceptionVec_8;
  reg         s0_out_bits_1_exceptionVec_9;
  reg         s0_out_bits_1_exceptionVec_10;
  reg         s0_out_bits_1_exceptionVec_11;
  reg         s0_out_bits_1_exceptionVec_12;
  reg         s0_out_bits_1_exceptionVec_13;
  reg         s0_out_bits_1_exceptionVec_14;
  reg         s0_out_bits_1_exceptionVec_15;
  reg         s0_out_bits_1_exceptionVec_16;
  reg         s0_out_bits_1_exceptionVec_17;
  reg         s0_out_bits_1_exceptionVec_18;
  reg         s0_out_bits_1_exceptionVec_19;
  reg         s0_out_bits_1_exceptionVec_20;
  reg         s0_out_bits_1_exceptionVec_21;
  reg         s0_out_bits_1_exceptionVec_22;
  reg         s0_out_bits_1_exceptionVec_23;
  reg         s0_out_bits_1_flushPipe;
  reg         s0_out_bits_1_replayInst;
  reg  [3:0]  s0_out_bits_1_trigger;
  reg         s0_out_bits_2_robIdx_flag;
  reg  [7:0]  s0_out_bits_2_robIdx_value;
  reg         s0_out_bits_2_hasException;
  reg         s0_out_bits_2_exceptionVec_0;
  reg         s0_out_bits_2_exceptionVec_1;
  reg         s0_out_bits_2_exceptionVec_2;
  reg         s0_out_bits_2_exceptionVec_3;
  reg         s0_out_bits_2_exceptionVec_4;
  reg         s0_out_bits_2_exceptionVec_5;
  reg         s0_out_bits_2_exceptionVec_6;
  reg         s0_out_bits_2_exceptionVec_7;
  reg         s0_out_bits_2_exceptionVec_8;
  reg         s0_out_bits_2_exceptionVec_9;
  reg         s0_out_bits_2_exceptionVec_10;
  reg         s0_out_bits_2_exceptionVec_11;
  reg         s0_out_bits_2_exceptionVec_12;
  reg         s0_out_bits_2_exceptionVec_13;
  reg         s0_out_bits_2_exceptionVec_14;
  reg         s0_out_bits_2_exceptionVec_15;
  reg         s0_out_bits_2_exceptionVec_16;
  reg         s0_out_bits_2_exceptionVec_17;
  reg         s0_out_bits_2_exceptionVec_18;
  reg         s0_out_bits_2_exceptionVec_19;
  reg         s0_out_bits_2_exceptionVec_20;
  reg         s0_out_bits_2_exceptionVec_21;
  reg         s0_out_bits_2_exceptionVec_22;
  reg         s0_out_bits_2_exceptionVec_23;
  reg         s0_out_bits_2_flushPipe;
  reg  [3:0]  s0_out_bits_2_trigger;
  reg         s0_out_bits_3_robIdx_flag;
  reg  [7:0]  s0_out_bits_3_robIdx_value;
  reg         s0_out_bits_3_hasException;
  reg         s0_out_bits_3_exceptionVec_0;
  reg         s0_out_bits_3_exceptionVec_1;
  reg         s0_out_bits_3_exceptionVec_2;
  reg         s0_out_bits_3_exceptionVec_3;
  reg         s0_out_bits_3_exceptionVec_4;
  reg         s0_out_bits_3_exceptionVec_5;
  reg         s0_out_bits_3_exceptionVec_6;
  reg         s0_out_bits_3_exceptionVec_7;
  reg         s0_out_bits_3_exceptionVec_8;
  reg         s0_out_bits_3_exceptionVec_9;
  reg         s0_out_bits_3_exceptionVec_10;
  reg         s0_out_bits_3_exceptionVec_11;
  reg         s0_out_bits_3_exceptionVec_12;
  reg         s0_out_bits_3_exceptionVec_13;
  reg         s0_out_bits_3_exceptionVec_14;
  reg         s0_out_bits_3_exceptionVec_15;
  reg         s0_out_bits_3_exceptionVec_16;
  reg         s0_out_bits_3_exceptionVec_17;
  reg         s0_out_bits_3_exceptionVec_18;
  reg         s0_out_bits_3_exceptionVec_19;
  reg         s0_out_bits_3_exceptionVec_20;
  reg         s0_out_bits_3_exceptionVec_21;
  reg         s0_out_bits_3_exceptionVec_22;
  reg         s0_out_bits_3_exceptionVec_23;
  reg         s0_out_bits_4_robIdx_flag;
  reg  [7:0]  s0_out_bits_4_robIdx_value;
  reg         s0_out_bits_4_hasException;
  reg         s0_out_bits_4_exceptionVec_0;
  reg         s0_out_bits_4_exceptionVec_1;
  reg         s0_out_bits_4_exceptionVec_2;
  reg         s0_out_bits_4_exceptionVec_3;
  reg         s0_out_bits_4_exceptionVec_4;
  reg         s0_out_bits_4_exceptionVec_5;
  reg         s0_out_bits_4_exceptionVec_6;
  reg         s0_out_bits_4_exceptionVec_7;
  reg         s0_out_bits_4_exceptionVec_8;
  reg         s0_out_bits_4_exceptionVec_9;
  reg         s0_out_bits_4_exceptionVec_10;
  reg         s0_out_bits_4_exceptionVec_11;
  reg         s0_out_bits_4_exceptionVec_12;
  reg         s0_out_bits_4_exceptionVec_13;
  reg         s0_out_bits_4_exceptionVec_14;
  reg         s0_out_bits_4_exceptionVec_15;
  reg         s0_out_bits_4_exceptionVec_16;
  reg         s0_out_bits_4_exceptionVec_17;
  reg         s0_out_bits_4_exceptionVec_18;
  reg         s0_out_bits_4_exceptionVec_19;
  reg         s0_out_bits_4_exceptionVec_20;
  reg         s0_out_bits_4_exceptionVec_21;
  reg         s0_out_bits_4_exceptionVec_22;
  reg         s0_out_bits_4_exceptionVec_23;
  reg         s0_out_bits_4_flushPipe;
  reg         s0_out_bits_4_replayInst;
  reg  [3:0]  s0_out_bits_4_trigger;
  reg         s0_out_bits_4_vstartEn;
  reg  [63:0] s0_out_bits_4_vstart;
  reg  [6:0]  s0_out_bits_4_vuopIdx;
  reg         s0_out_bits_4_isVecLoad;
  reg         s0_out_bits_4_isVlm;
  reg         s0_out_bits_4_isStrided;
  reg         s0_out_bits_4_isIndexed;
  reg         s0_out_bits_4_isWhole;
  reg  [2:0]  s0_out_bits_4_nf;
  reg  [1:0]  s0_out_bits_4_vsew;
  reg  [1:0]  s0_out_bits_4_veew;
  reg  [2:0]  s0_out_bits_4_vlmul;
  reg         s1_out_bits_robIdx_flag;
  reg  [7:0]  s1_out_bits_robIdx_value;
  reg         s1_out_bits_hasException;
  reg         s1_out_bits_exceptionVec_0;
  reg         s1_out_bits_exceptionVec_1;
  reg         s1_out_bits_exceptionVec_2;
  reg         s1_out_bits_exceptionVec_3;
  reg         s1_out_bits_exceptionVec_4;
  reg         s1_out_bits_exceptionVec_5;
  reg         s1_out_bits_exceptionVec_6;
  reg         s1_out_bits_exceptionVec_7;
  reg         s1_out_bits_exceptionVec_8;
  reg         s1_out_bits_exceptionVec_9;
  reg         s1_out_bits_exceptionVec_10;
  reg         s1_out_bits_exceptionVec_11;
  reg         s1_out_bits_exceptionVec_12;
  reg         s1_out_bits_exceptionVec_13;
  reg         s1_out_bits_exceptionVec_14;
  reg         s1_out_bits_exceptionVec_15;
  reg         s1_out_bits_exceptionVec_16;
  reg         s1_out_bits_exceptionVec_17;
  reg         s1_out_bits_exceptionVec_18;
  reg         s1_out_bits_exceptionVec_19;
  reg         s1_out_bits_exceptionVec_20;
  reg         s1_out_bits_exceptionVec_21;
  reg         s1_out_bits_exceptionVec_22;
  reg         s1_out_bits_exceptionVec_23;
  reg         s1_out_bits_flushPipe;
  reg         s1_out_bits_replayInst;
  reg  [3:0]  s1_out_bits_trigger;
  reg         s1_out_bits_vstartEn;
  reg  [63:0] s1_out_bits_vstart;
  reg         s1_out_bits_isVecLoad;
  reg         s1_out_bits_isVlm;
  reg         s1_out_bits_isStrided;
  reg         s1_out_bits_isIndexed;
  reg         s1_out_bits_isWhole;
  reg  [2:0]  s1_out_bits_nf;
  reg  [1:0]  s1_out_bits_vsew;
  reg  [1:0]  s1_out_bits_veew;
  reg  [2:0]  s1_out_bits_vlmul;
  reg         s1_out_valid;
  reg         enq_s1_valid;
  reg         enq_s1_bits_robIdx_flag;
  reg  [7:0]  enq_s1_bits_robIdx_value;
  reg  [5:0]  enq_s1_bits_ftqPtr_value;
  reg  [3:0]  enq_s1_bits_ftqOffset;
  reg         enq_s1_bits_hasException;
  reg         enq_s1_bits_exceptionVec_0;
  reg         enq_s1_bits_exceptionVec_1;
  reg         enq_s1_bits_exceptionVec_2;
  reg         enq_s1_bits_exceptionVec_3;
  reg         enq_s1_bits_exceptionVec_12;
  reg         enq_s1_bits_exceptionVec_20;
  reg         enq_s1_bits_exceptionVec_22;
  reg         enq_s1_bits_isFetchMalAddr;
  reg         enq_s1_bits_flushPipe;
  reg         enq_s1_bits_isVset;
  reg         enq_s1_bits_singleStep;
  reg         enq_s1_bits_crossPageIPFFix;
  reg  [3:0]  enq_s1_bits_trigger;
  wire [8:0]  current_robIdx_cat =
    {current_robIdx_flag, current_robIdx_value};
  wire [8:0]  s1_robIdx_cat =
    {s1_out_bits_robIdx_flag, s1_out_bits_robIdx_value};
  wire        s1_flush =
    io_redirect_valid
    & (io_redirect_bits_level & s1_robIdx_cat == redirect_robIdx_cat
       | s1_out_bits_robIdx_flag ^ io_redirect_bits_robIdx_flag
       ^ s1_out_bits_robIdx_value > io_redirect_bits_robIdx_value) | io_flush;
  wire        s1Accept = s1_out_valid & ~s1_flush;
  wire        enqAccept = enq_s1_valid & ~(io_redirect_valid | io_flush);
  always @(posedge clock or posedge reset) begin
    if (reset)
      currentValid <= 1'h0;
    else if (currentValid) begin
      if (io_redirect_valid
          & (io_redirect_bits_level
             & current_robIdx_cat == redirect_robIdx_cat
             | current_robIdx_flag ^ io_redirect_bits_robIdx_flag
             ^ current_robIdx_value > io_redirect_bits_robIdx_value) | io_flush)
        currentValid <= ~s1_flush & s1_out_valid;
    end
    else
      currentValid <= s1Accept | enqAccept | currentValid;
  end // always @(posedge, posedge)
  wire        s1NewerThanCurrent =
    current_robIdx_flag ^ s1_out_bits_robIdx_flag
    ^ current_robIdx_value > s1_out_bits_robIdx_value;
  wire        s1ReplacePtr = s1Accept & s1NewerThanCurrent;
  wire        s1SameRobAsCurrent = current_robIdx_cat == s1_robIdx_cat;
  wire        s1_left_pick0 =
    ~s0_out_valid_1 | s0_out_valid_0
    & (s0_out_bits_1_robIdx_flag ^ s0_out_bits_0_robIdx_flag
       ^ s0_out_bits_1_robIdx_value > s0_out_bits_0_robIdx_value);
  wire        s1_out_bits_res_0_bits_robIdx_flag =
    s1_left_pick0 ? s0_out_bits_0_robIdx_flag : s0_out_bits_1_robIdx_flag;
  wire [7:0]  s1_out_bits_res_0_bits_robIdx_value =
    s1_left_pick0
      ? s0_out_bits_0_robIdx_value
      : s0_out_bits_1_robIdx_value;
  wire        enq_s0_valid_0 =
    io_enq_0_valid
    & (io_enq_0_bits_hasException | io_enq_0_bits_flushPipe | io_enq_0_bits_singleStep
       | io_enq_0_bits_trigger == 4'h1) & ~lastCycleFlush;
  wire        enq_s0_valid_1 =
    io_enq_1_valid
    & (io_enq_1_bits_hasException | io_enq_1_bits_flushPipe | io_enq_1_bits_singleStep
       | io_enq_1_bits_trigger == 4'h1) & ~lastCycleFlush;
  wire        enq_s0_valid_2 =
    io_enq_2_valid
    & (io_enq_2_bits_hasException | io_enq_2_bits_flushPipe | io_enq_2_bits_singleStep
       | io_enq_2_bits_trigger == 4'h1) & ~lastCycleFlush;
  wire        enq_s0_valid_3 =
    io_enq_3_valid
    & (io_enq_3_bits_hasException | io_enq_3_bits_flushPipe | io_enq_3_bits_singleStep
       | io_enq_3_bits_trigger == 4'h1) & ~lastCycleFlush;
  wire        enq_s0_valid_4 =
    io_enq_4_valid
    & (io_enq_4_bits_hasException | io_enq_4_bits_flushPipe | io_enq_4_bits_singleStep
       | io_enq_4_bits_trigger == 4'h1) & ~lastCycleFlush;
  wire        enq_s0_valid_5 =
    io_enq_5_valid
    & (io_enq_5_bits_hasException | io_enq_5_bits_flushPipe | io_enq_5_bits_singleStep
       | io_enq_5_bits_trigger == 4'h1) & ~lastCycleFlush;
  wire        in_wb_valids_1_0 =
    io_wb_8_valid
    & (io_wb_8_bits_hasException | io_wb_8_bits_flushPipe | io_wb_8_bits_replayInst
       | io_wb_8_bits_trigger == 4'h1) & ~lastCycleFlush;
  wire        in_wb_valids_1_1 =
    io_wb_9_valid
    & (io_wb_9_bits_hasException | io_wb_9_bits_flushPipe | io_wb_9_bits_replayInst
       | io_wb_9_bits_trigger == 4'h1) & ~lastCycleFlush;
  wire        in_wb_valids_1_2 =
    io_wb_10_valid
    & (io_wb_10_bits_hasException | io_wb_10_bits_flushPipe | io_wb_10_bits_replayInst
       | io_wb_10_bits_trigger == 4'h1) & ~lastCycleFlush;
  wire        in_wb_valids_2_0 =
    io_wb_6_valid
    & (io_wb_6_bits_hasException | io_wb_6_bits_flushPipe | io_wb_6_bits_trigger == 4'h1)
    & ~lastCycleFlush;
  wire        in_wb_valids_2_1 =
    io_wb_7_valid & (io_wb_7_bits_hasException | io_wb_7_bits_trigger == 4'h1)
    & ~lastCycleFlush;
  wire        in_wb_valids_3_0 =
    io_wb_1_valid & io_wb_1_bits_hasException & ~lastCycleFlush;
  wire        in_wb_valids_3_1 =
    io_wb_2_valid & io_wb_2_bits_hasException & ~lastCycleFlush;
  wire        in_wb_valids_4_0 =
    io_wb_11_valid
    & (io_wb_11_bits_hasException | io_wb_11_bits_flushPipe | io_wb_11_bits_replayInst
       | io_wb_11_bits_trigger == 4'h1) & ~lastCycleFlush;
  wire        in_wb_valids_4_1 =
    io_wb_12_valid
    & (io_wb_12_bits_hasException | io_wb_12_bits_flushPipe | io_wb_12_bits_replayInst
       | io_wb_12_bits_trigger == 4'h1) & ~lastCycleFlush;
  wire        wb_valid_0 =
    io_wb_0_valid & (io_wb_0_bits_hasException | io_wb_0_bits_flushPipe) & ~lastCycleFlush
    & ~(io_redirect_valid
        & (io_redirect_bits_level
           & {io_wb_0_bits_robIdx_flag,
              io_wb_0_bits_robIdx_value} == redirect_robIdx_cat
           | io_wb_0_bits_robIdx_flag ^ io_redirect_bits_robIdx_flag
           ^ io_wb_0_bits_robIdx_value > io_redirect_bits_robIdx_value) | io_flush);
  wire        wb_valid_1 =
    in_wb_valids_1_0
    & ~(io_redirect_valid
        & (io_redirect_bits_level
           & {io_wb_8_bits_robIdx_flag,
              io_wb_8_bits_robIdx_value} == redirect_robIdx_cat
           | io_wb_8_bits_robIdx_flag ^ io_redirect_bits_robIdx_flag
           ^ io_wb_8_bits_robIdx_value > io_redirect_bits_robIdx_value) | io_flush)
    | in_wb_valids_1_1
    & ~(io_redirect_valid
        & (io_redirect_bits_level
           & {io_wb_9_bits_robIdx_flag,
              io_wb_9_bits_robIdx_value} == redirect_robIdx_cat
           | io_wb_9_bits_robIdx_flag ^ io_redirect_bits_robIdx_flag
           ^ io_wb_9_bits_robIdx_value > io_redirect_bits_robIdx_value) | io_flush)
    | in_wb_valids_1_2
    & ~(io_redirect_valid
        & (io_redirect_bits_level
           & {io_wb_10_bits_robIdx_flag,
              io_wb_10_bits_robIdx_value} == redirect_robIdx_cat
           | io_wb_10_bits_robIdx_flag ^ io_redirect_bits_robIdx_flag
           ^ io_wb_10_bits_robIdx_value > io_redirect_bits_robIdx_value) | io_flush);
  wire        wb_valid_2 =
    in_wb_valids_2_0
    & ~(io_redirect_valid
        & (io_redirect_bits_level
           & {io_wb_6_bits_robIdx_flag,
              io_wb_6_bits_robIdx_value} == redirect_robIdx_cat
           | io_wb_6_bits_robIdx_flag ^ io_redirect_bits_robIdx_flag
           ^ io_wb_6_bits_robIdx_value > io_redirect_bits_robIdx_value) | io_flush)
    | in_wb_valids_2_1
    & ~(io_redirect_valid
        & (io_redirect_bits_level
           & {io_wb_7_bits_robIdx_flag,
              io_wb_7_bits_robIdx_value} == redirect_robIdx_cat
           | io_wb_7_bits_robIdx_flag ^ io_redirect_bits_robIdx_flag
           ^ io_wb_7_bits_robIdx_value > io_redirect_bits_robIdx_value) | io_flush);
  wire        wb_valid_3 =
    in_wb_valids_3_0
    & ~(io_redirect_valid
        & (io_redirect_bits_level
           & {io_wb_1_bits_robIdx_flag,
              io_wb_1_bits_robIdx_value} == redirect_robIdx_cat
           | io_wb_1_bits_robIdx_flag ^ io_redirect_bits_robIdx_flag
           ^ io_wb_1_bits_robIdx_value > io_redirect_bits_robIdx_value) | io_flush)
    | in_wb_valids_3_1
    & ~(io_redirect_valid
        & (io_redirect_bits_level
           & {io_wb_2_bits_robIdx_flag,
              io_wb_2_bits_robIdx_value} == redirect_robIdx_cat
           | io_wb_2_bits_robIdx_flag ^ io_redirect_bits_robIdx_flag
           ^ io_wb_2_bits_robIdx_value > io_redirect_bits_robIdx_value) | io_flush);
  wire [8:0]  wb11_robIdx_cat =
    {io_wb_11_bits_robIdx_flag, io_wb_11_bits_robIdx_value};
  wire [8:0]  wb12_robIdx_cat =
    {io_wb_12_bits_robIdx_flag, io_wb_12_bits_robIdx_value};
  wire        wb_valid_4 =
    in_wb_valids_4_0
    & ~(io_redirect_valid
        & (io_redirect_bits_level & wb11_robIdx_cat == redirect_robIdx_cat
           | io_wb_11_bits_robIdx_flag ^ io_redirect_bits_robIdx_flag
           ^ io_wb_11_bits_robIdx_value > io_redirect_bits_robIdx_value) | io_flush)
    | in_wb_valids_4_1
    & ~(io_redirect_valid
        & (io_redirect_bits_level & wb12_robIdx_cat == redirect_robIdx_cat
           | io_wb_12_bits_robIdx_flag ^ io_redirect_bits_robIdx_flag
           ^ io_wb_12_bits_robIdx_value > io_redirect_bits_robIdx_value) | io_flush);
  wire        s1_valid_0 =
    s0_out_valid_0
    & ~(io_redirect_valid
        & (io_redirect_bits_level
           & {s0_out_bits_0_robIdx_flag,
              s0_out_bits_0_robIdx_value} == redirect_robIdx_cat
           | s0_out_bits_0_robIdx_flag ^ io_redirect_bits_robIdx_flag
           ^ s0_out_bits_0_robIdx_value > io_redirect_bits_robIdx_value) | io_flush);
  wire        s1_valid_1 =
    s0_out_valid_1
    & ~(io_redirect_valid
        & (io_redirect_bits_level
           & {s0_out_bits_1_robIdx_flag,
              s0_out_bits_1_robIdx_value} == redirect_robIdx_cat
           | s0_out_bits_1_robIdx_flag ^ io_redirect_bits_robIdx_flag
           ^ s0_out_bits_1_robIdx_value > io_redirect_bits_robIdx_value) | io_flush);
  wire [8:0]  s0_2_robIdx_cat =
    {s0_out_bits_2_robIdx_flag, s0_out_bits_2_robIdx_value};
  wire        s1_valid_2 =
    s0_out_valid_2
    & ~(io_redirect_valid
        & (io_redirect_bits_level
           & s0_2_robIdx_cat == redirect_robIdx_cat
           | s0_out_bits_2_robIdx_flag ^ io_redirect_bits_robIdx_flag
           ^ s0_out_bits_2_robIdx_value > io_redirect_bits_robIdx_value) | io_flush);
  wire [8:0]  s0_3_robIdx_cat =
    {s0_out_bits_3_robIdx_flag, s0_out_bits_3_robIdx_value};
  wire        s1_valid_3 =
    s0_out_valid_3
    & ~(io_redirect_valid
        & (io_redirect_bits_level
           & s0_3_robIdx_cat == redirect_robIdx_cat
           | s0_out_bits_3_robIdx_flag ^ io_redirect_bits_robIdx_flag
           ^ s0_out_bits_3_robIdx_value > io_redirect_bits_robIdx_value) | io_flush);
  wire [8:0]  s0_4_robIdx_cat =
    {s0_out_bits_4_robIdx_flag, s0_out_bits_4_robIdx_value};
  wire        s1_valid_4 =
    s0_out_valid_4
    & ~(io_redirect_valid
        & (io_redirect_bits_level
           & s0_4_robIdx_cat == redirect_robIdx_cat
           | s0_out_bits_4_robIdx_flag ^ io_redirect_bits_robIdx_flag
           ^ s0_out_bits_4_robIdx_value > io_redirect_bits_robIdx_value) | io_flush);
  wire        wb1_right_pick9 =
    ~in_wb_valids_1_2 | in_wb_valids_1_1
    & (io_wb_10_bits_robIdx_flag ^ io_wb_9_bits_robIdx_flag
       ^ io_wb_10_bits_robIdx_value > io_wb_9_bits_robIdx_value);
  wire        wb_bits_res_1_bits_robIdx_flag =
    wb1_right_pick9 ? io_wb_9_bits_robIdx_flag : io_wb_10_bits_robIdx_flag;
  wire [7:0]  wb_bits_res_1_bits_robIdx_value =
    wb1_right_pick9 ? io_wb_9_bits_robIdx_value : io_wb_10_bits_robIdx_value;
  wire        wb1_pick8 =
    ~(wb1_right_pick9 ? in_wb_valids_1_1 : in_wb_valids_1_2) | in_wb_valids_1_0
    & (wb_bits_res_1_bits_robIdx_flag ^ io_wb_8_bits_robIdx_flag
       ^ wb_bits_res_1_bits_robIdx_value > io_wb_8_bits_robIdx_value);
  wire        wb2_pick6 =
    ~in_wb_valids_2_1 | in_wb_valids_2_0
    & (io_wb_7_bits_robIdx_flag ^ io_wb_6_bits_robIdx_flag
       ^ io_wb_7_bits_robIdx_value > io_wb_6_bits_robIdx_value);
  wire        wb_left_pick1 =
    ~in_wb_valids_3_1 | in_wb_valids_3_0
    & (io_wb_2_bits_robIdx_flag ^ io_wb_1_bits_robIdx_flag
       ^ io_wb_2_bits_robIdx_value > io_wb_1_bits_robIdx_value);
  wire        wb4_pick11 =
    ~in_wb_valids_4_1 | in_wb_valids_4_0
    & (io_wb_12_bits_robIdx_flag ^ io_wb_11_bits_robIdx_flag
       ^ io_wb_12_bits_robIdx_value > io_wb_11_bits_robIdx_value
       | wb12_robIdx_cat == wb11_robIdx_cat
       & io_wb_12_bits_vuopIdx > io_wb_11_bits_vuopIdx);
  wire        s1_rr_pick3 =
    ~s0_out_valid_4 | s0_out_valid_3
    & (s0_out_bits_4_robIdx_flag ^ s0_out_bits_3_robIdx_flag
       ^ s0_out_bits_4_robIdx_value > s0_out_bits_3_robIdx_value
       | s0_4_robIdx_cat == s0_3_robIdx_cat
       & (|s0_out_bits_4_vuopIdx));
  wire        s1_out_bits_right_res_1_valid =
    s1_rr_pick3 ? s0_out_valid_3 : s0_out_valid_4;
  wire        s1_out_bits_right_res_1_bits_robIdx_flag =
    s1_rr_pick3
      ? s0_out_bits_3_robIdx_flag
      : s0_out_bits_4_robIdx_flag;
  wire [7:0]  s1_out_bits_right_res_1_bits_robIdx_value =
    s1_rr_pick3
      ? s0_out_bits_3_robIdx_value
      : s0_out_bits_4_robIdx_value;
  wire        s1_right_pick2 =
    ~s1_out_bits_right_res_1_valid | s0_out_valid_2
    & (s1_out_bits_right_res_1_bits_robIdx_flag ^ s0_out_bits_2_robIdx_flag
       ^ s1_out_bits_right_res_1_bits_robIdx_value > s0_out_bits_2_robIdx_value
       | {s1_out_bits_right_res_1_bits_robIdx_flag,
          s1_out_bits_right_res_1_bits_robIdx_value} == s0_2_robIdx_cat
       & (|(s1_rr_pick3 ? 7'h0 : s0_out_bits_4_vuopIdx)));
  wire        s1_out_bits_res_1_bits_robIdx_flag =
    s1_right_pick2
      ? s0_out_bits_2_robIdx_flag
      : s1_out_bits_right_res_1_bits_robIdx_flag;
  wire [7:0]  s1_out_bits_res_1_bits_robIdx_value =
    s1_right_pick2
      ? s0_out_bits_2_robIdx_value
      : s1_out_bits_right_res_1_bits_robIdx_value;
  wire        s1_top_pickLeft =
    ~(s1_right_pick2 ? s0_out_valid_2 : s1_out_bits_right_res_1_valid)
    | (s1_left_pick0 ? s0_out_valid_0 : s0_out_valid_1)
    & (s1_out_bits_res_1_bits_robIdx_flag ^ s1_out_bits_res_0_bits_robIdx_flag
       ^ s1_out_bits_res_1_bits_robIdx_value > s1_out_bits_res_0_bits_robIdx_value
       | {s1_out_bits_res_1_bits_robIdx_flag,
          s1_out_bits_res_1_bits_robIdx_value} == {s1_out_bits_res_0_bits_robIdx_flag,
                                                   s1_out_bits_res_0_bits_robIdx_value}
       & (|(s1_right_pick2 | s1_rr_pick3
              ? 7'h0
              : s0_out_bits_4_vuopIdx)));
  wire        s1NoValidPick =
    s1_top_pickLeft | s1_right_pick2
    | s1_rr_pick3;
  wire        enq_pick_left = enq_s0_valid_0 | enq_s0_valid_1 | enq_s0_valid_2;
  always @(posedge clock) begin
    if (currentValid) begin
      if (s1ReplacePtr) begin
        current_robIdx_flag <= s1_out_bits_robIdx_flag;
        current_robIdx_value <= s1_out_bits_robIdx_value;
        current_ftqPtr_value <= 6'h0;
        current_ftqOffset <= 4'h0;
      end
      if (s1Accept
          & (s1NewerThanCurrent | s1SameRobAsCurrent
             & (s1_out_bits_vstart < current_vstart | ~current_vstartEn))) begin
        current_hasException <= s1_out_bits_hasException;
        current_exceptionVec_0 <= s1_out_bits_exceptionVec_0;
        current_exceptionVec_1 <= s1_out_bits_exceptionVec_1;
        current_exceptionVec_2 <= s1_out_bits_exceptionVec_2;
        current_exceptionVec_3 <= s1_out_bits_exceptionVec_3;
        current_exceptionVec_4 <= s1_out_bits_exceptionVec_4;
        current_exceptionVec_5 <= s1_out_bits_exceptionVec_5;
        current_exceptionVec_6 <= s1_out_bits_exceptionVec_6;
        current_exceptionVec_7 <= s1_out_bits_exceptionVec_7;
        current_exceptionVec_8 <= s1_out_bits_exceptionVec_8;
        current_exceptionVec_9 <= s1_out_bits_exceptionVec_9;
        current_exceptionVec_10 <= s1_out_bits_exceptionVec_10;
        current_exceptionVec_11 <= s1_out_bits_exceptionVec_11;
        current_exceptionVec_12 <= s1_out_bits_exceptionVec_12;
        current_exceptionVec_13 <= s1_out_bits_exceptionVec_13;
        current_exceptionVec_14 <= s1_out_bits_exceptionVec_14;
        current_exceptionVec_15 <= s1_out_bits_exceptionVec_15;
        current_exceptionVec_16 <= s1_out_bits_exceptionVec_16;
        current_exceptionVec_17 <= s1_out_bits_exceptionVec_17;
        current_exceptionVec_18 <= s1_out_bits_exceptionVec_18;
        current_exceptionVec_19 <= s1_out_bits_exceptionVec_19;
        current_exceptionVec_20 <= s1_out_bits_exceptionVec_20;
        current_exceptionVec_21 <= s1_out_bits_exceptionVec_21;
        current_exceptionVec_22 <= s1_out_bits_exceptionVec_22;
        current_exceptionVec_23 <= s1_out_bits_exceptionVec_23;
        current_trigger <= s1_out_bits_trigger;
        current_vstartEn <= s1_out_bits_vstartEn;
        current_vstart <= s1_out_bits_vstart;
        current_isVecLoad <= s1_out_bits_isVecLoad;
        current_isVlm <= s1_out_bits_isVlm;
        current_isStrided <= s1_out_bits_isStrided;
        current_isIndexed <= s1_out_bits_isIndexed;
        current_isWhole <= s1_out_bits_isWhole;
        current_nf <= s1_out_bits_nf;
        current_vsew <= s1_out_bits_vsew;
        current_veew <= s1_out_bits_veew;
        current_vlmul <= s1_out_bits_vlmul;
      end
      current_isEnqExcp <= ~(s1Accept & (s1NewerThanCurrent | s1SameRobAsCurrent)) & current_isEnqExcp;
      current_isFetchMalAddr <= ~s1ReplacePtr & current_isFetchMalAddr;
      if (s1Accept) begin
        if (s1NewerThanCurrent) begin
          current_flushPipe <= s1_out_bits_flushPipe;
          current_replayInst <= s1_out_bits_replayInst;
        end
        else begin
          if (s1SameRobAsCurrent)
            current_flushPipe <=
              (s1_out_bits_flushPipe | current_flushPipe)
              & {s1_out_bits_exceptionVec_23,
                 s1_out_bits_exceptionVec_22,
                 s1_out_bits_exceptionVec_21,
                 s1_out_bits_exceptionVec_20,
                 s1_out_bits_exceptionVec_19,
                 s1_out_bits_exceptionVec_18,
                 s1_out_bits_exceptionVec_17,
                 s1_out_bits_exceptionVec_16,
                 s1_out_bits_exceptionVec_15,
                 s1_out_bits_exceptionVec_14,
                 s1_out_bits_exceptionVec_13,
                 s1_out_bits_exceptionVec_12,
                 s1_out_bits_exceptionVec_11,
                 s1_out_bits_exceptionVec_10,
                 s1_out_bits_exceptionVec_9,
                 s1_out_bits_exceptionVec_8,
                 s1_out_bits_exceptionVec_7,
                 s1_out_bits_exceptionVec_6,
                 s1_out_bits_exceptionVec_5,
                 s1_out_bits_exceptionVec_4,
                 s1_out_bits_exceptionVec_3,
                 s1_out_bits_exceptionVec_2,
                 s1_out_bits_exceptionVec_1,
                 s1_out_bits_exceptionVec_0} == 24'h0;
          current_replayInst <= s1SameRobAsCurrent & s1_out_bits_replayInst | current_replayInst;
        end
      end
      current_isVset <= ~s1ReplacePtr & current_isVset;
      current_singleStep <= ~s1ReplacePtr & current_singleStep;
      current_crossPageIPFFix <= ~s1ReplacePtr & current_crossPageIPFFix;
    end
    else begin
      if (s1Accept) begin
        current_robIdx_flag <= s1_out_bits_robIdx_flag;
        current_robIdx_value <= s1_out_bits_robIdx_value;
        current_ftqPtr_value <= 6'h0;
        current_ftqOffset <= 4'h0;
        current_hasException <= s1_out_bits_hasException;
        current_exceptionVec_0 <= s1_out_bits_exceptionVec_0;
        current_exceptionVec_1 <= s1_out_bits_exceptionVec_1;
        current_exceptionVec_2 <= s1_out_bits_exceptionVec_2;
        current_exceptionVec_3 <= s1_out_bits_exceptionVec_3;
        current_exceptionVec_4 <= s1_out_bits_exceptionVec_4;
        current_exceptionVec_5 <= s1_out_bits_exceptionVec_5;
        current_exceptionVec_6 <= s1_out_bits_exceptionVec_6;
        current_exceptionVec_7 <= s1_out_bits_exceptionVec_7;
        current_exceptionVec_8 <= s1_out_bits_exceptionVec_8;
        current_exceptionVec_9 <= s1_out_bits_exceptionVec_9;
        current_exceptionVec_10 <= s1_out_bits_exceptionVec_10;
        current_exceptionVec_11 <= s1_out_bits_exceptionVec_11;
        current_exceptionVec_12 <= s1_out_bits_exceptionVec_12;
        current_exceptionVec_13 <= s1_out_bits_exceptionVec_13;
        current_exceptionVec_14 <= s1_out_bits_exceptionVec_14;
        current_exceptionVec_15 <= s1_out_bits_exceptionVec_15;
        current_exceptionVec_16 <= s1_out_bits_exceptionVec_16;
        current_exceptionVec_17 <= s1_out_bits_exceptionVec_17;
        current_exceptionVec_18 <= s1_out_bits_exceptionVec_18;
        current_exceptionVec_19 <= s1_out_bits_exceptionVec_19;
        current_exceptionVec_20 <= s1_out_bits_exceptionVec_20;
        current_exceptionVec_21 <= s1_out_bits_exceptionVec_21;
        current_exceptionVec_22 <= s1_out_bits_exceptionVec_22;
        current_exceptionVec_23 <= s1_out_bits_exceptionVec_23;
        current_flushPipe <= s1_out_bits_flushPipe;
        current_replayInst <= s1_out_bits_replayInst;
        current_trigger <= s1_out_bits_trigger;
        current_vstartEn <= s1_out_bits_vstartEn;
        current_vstart <= s1_out_bits_vstart;
        current_isVecLoad <= s1_out_bits_isVecLoad;
        current_isVlm <= s1_out_bits_isVlm;
        current_isStrided <= s1_out_bits_isStrided;
        current_isIndexed <= s1_out_bits_isIndexed;
        current_isWhole <= s1_out_bits_isWhole;
        current_nf <= s1_out_bits_nf;
        current_vsew <= s1_out_bits_vsew;
        current_veew <= s1_out_bits_veew;
        current_vlmul <= s1_out_bits_vlmul;
      end
      else begin
        if (enqAccept) begin
          current_robIdx_flag <= enq_s1_bits_robIdx_flag;
          current_robIdx_value <= enq_s1_bits_robIdx_value;
          current_ftqPtr_value <= enq_s1_bits_ftqPtr_value;
          current_ftqOffset <= enq_s1_bits_ftqOffset;
          current_hasException <= enq_s1_bits_hasException;
          current_exceptionVec_0 <= enq_s1_bits_exceptionVec_0;
          current_exceptionVec_1 <= enq_s1_bits_exceptionVec_1;
          current_exceptionVec_2 <= enq_s1_bits_exceptionVec_2;
          current_exceptionVec_3 <= enq_s1_bits_exceptionVec_3;
          current_exceptionVec_12 <= enq_s1_bits_exceptionVec_12;
          current_exceptionVec_20 <= enq_s1_bits_exceptionVec_20;
          current_exceptionVec_22 <= enq_s1_bits_exceptionVec_22;
          current_flushPipe <= enq_s1_bits_flushPipe;
          current_trigger <= enq_s1_bits_trigger;
          current_vstart <= 64'h0;
          current_nf <= 3'h0;
          current_vsew <= 2'h0;
          current_veew <= 2'h0;
          current_vlmul <= 3'h0;
        end
        current_exceptionVec_4 <= ~enqAccept & current_exceptionVec_4;
        current_exceptionVec_5 <= ~enqAccept & current_exceptionVec_5;
        current_exceptionVec_6 <= ~enqAccept & current_exceptionVec_6;
        current_exceptionVec_7 <= ~enqAccept & current_exceptionVec_7;
        current_exceptionVec_8 <= ~enqAccept & current_exceptionVec_8;
        current_exceptionVec_9 <= ~enqAccept & current_exceptionVec_9;
        current_exceptionVec_10 <= ~enqAccept & current_exceptionVec_10;
        current_exceptionVec_11 <= ~enqAccept & current_exceptionVec_11;
        current_exceptionVec_13 <= ~enqAccept & current_exceptionVec_13;
        current_exceptionVec_14 <= ~enqAccept & current_exceptionVec_14;
        current_exceptionVec_15 <= ~enqAccept & current_exceptionVec_15;
        current_exceptionVec_16 <= ~enqAccept & current_exceptionVec_16;
        current_exceptionVec_17 <= ~enqAccept & current_exceptionVec_17;
        current_exceptionVec_18 <= ~enqAccept & current_exceptionVec_18;
        current_exceptionVec_19 <= ~enqAccept & current_exceptionVec_19;
        current_exceptionVec_21 <= ~enqAccept & current_exceptionVec_21;
        current_exceptionVec_23 <= ~enqAccept & current_exceptionVec_23;
        current_replayInst <= ~enqAccept & current_replayInst;
        current_vstartEn <= ~enqAccept & current_vstartEn;
        current_isVecLoad <= ~enqAccept & current_isVecLoad;
        current_isVlm <= ~enqAccept & current_isVlm;
        current_isStrided <= ~enqAccept & current_isStrided;
        current_isIndexed <= ~enqAccept & current_isIndexed;
        current_isWhole <= ~enqAccept & current_isWhole;
      end
      current_isEnqExcp <= ~s1Accept & (enqAccept | current_isEnqExcp);
      current_isFetchMalAddr <=
        ~s1Accept & (enqAccept ? enq_s1_bits_isFetchMalAddr : current_isFetchMalAddr);
      current_isVset <= ~s1Accept & (enqAccept ? enq_s1_bits_isVset : current_isVset);
      current_singleStep <=
        ~s1Accept & (enqAccept ? enq_s1_bits_singleStep : current_singleStep);
      current_crossPageIPFFix <=
        ~s1Accept & (enqAccept ? enq_s1_bits_crossPageIPFFix : current_crossPageIPFFix);
    end
    lastCycleFlush <= io_flush;
    s0_out_valid_0 <= wb_valid_0;
    s0_out_valid_1 <= wb_valid_1;
    s0_out_valid_2 <= wb_valid_2;
    s0_out_valid_3 <= wb_valid_3;
    s0_out_valid_4 <= wb_valid_4;
    if (wb_valid_0) begin
      s0_out_bits_0_robIdx_flag <= io_wb_0_bits_robIdx_flag;
      s0_out_bits_0_robIdx_value <= io_wb_0_bits_robIdx_value;
      s0_out_bits_0_hasException <= io_wb_0_bits_hasException;
      s0_out_bits_0_exceptionVec_2 <= io_wb_0_bits_exceptionVec_2;
      s0_out_bits_0_exceptionVec_3 <= io_wb_0_bits_exceptionVec_3;
      s0_out_bits_0_exceptionVec_8 <= io_wb_0_bits_exceptionVec_8;
      s0_out_bits_0_exceptionVec_9 <= io_wb_0_bits_exceptionVec_9;
      s0_out_bits_0_exceptionVec_10 <= io_wb_0_bits_exceptionVec_10;
      s0_out_bits_0_exceptionVec_11 <= io_wb_0_bits_exceptionVec_11;
      s0_out_bits_0_exceptionVec_22 <= io_wb_0_bits_exceptionVec_22;
      s0_out_bits_0_flushPipe <= io_wb_0_bits_flushPipe;
    end
    s0_out_bits_0_exceptionVec_0 <= ~wb_valid_0 & s0_out_bits_0_exceptionVec_0;
    s0_out_bits_0_exceptionVec_1 <= ~wb_valid_0 & s0_out_bits_0_exceptionVec_1;
    s0_out_bits_0_exceptionVec_4 <= ~wb_valid_0 & s0_out_bits_0_exceptionVec_4;
    s0_out_bits_0_exceptionVec_5 <= ~wb_valid_0 & s0_out_bits_0_exceptionVec_5;
    s0_out_bits_0_exceptionVec_6 <= ~wb_valid_0 & s0_out_bits_0_exceptionVec_6;
    s0_out_bits_0_exceptionVec_7 <= ~wb_valid_0 & s0_out_bits_0_exceptionVec_7;
    s0_out_bits_0_exceptionVec_12 <= ~wb_valid_0 & s0_out_bits_0_exceptionVec_12;
    s0_out_bits_0_exceptionVec_13 <= ~wb_valid_0 & s0_out_bits_0_exceptionVec_13;
    s0_out_bits_0_exceptionVec_14 <= ~wb_valid_0 & s0_out_bits_0_exceptionVec_14;
    s0_out_bits_0_exceptionVec_15 <= ~wb_valid_0 & s0_out_bits_0_exceptionVec_15;
    s0_out_bits_0_exceptionVec_16 <= ~wb_valid_0 & s0_out_bits_0_exceptionVec_16;
    s0_out_bits_0_exceptionVec_17 <= ~wb_valid_0 & s0_out_bits_0_exceptionVec_17;
    s0_out_bits_0_exceptionVec_18 <= ~wb_valid_0 & s0_out_bits_0_exceptionVec_18;
    s0_out_bits_0_exceptionVec_19 <= ~wb_valid_0 & s0_out_bits_0_exceptionVec_19;
    s0_out_bits_0_exceptionVec_20 <= ~wb_valid_0 & s0_out_bits_0_exceptionVec_20;
    s0_out_bits_0_exceptionVec_21 <= ~wb_valid_0 & s0_out_bits_0_exceptionVec_21;
    s0_out_bits_0_exceptionVec_23 <= ~wb_valid_0 & s0_out_bits_0_exceptionVec_23;
    if (wb_valid_1) begin
      s0_out_bits_1_robIdx_flag <=
        wb1_pick8 ? io_wb_8_bits_robIdx_flag : wb_bits_res_1_bits_robIdx_flag;
      s0_out_bits_1_robIdx_value <=
        wb1_pick8 ? io_wb_8_bits_robIdx_value : wb_bits_res_1_bits_robIdx_value;
      s0_out_bits_1_hasException <=
        wb1_pick8
          ? io_wb_8_bits_hasException
          : wb1_right_pick9
              ? io_wb_9_bits_hasException
              : io_wb_10_bits_hasException;
      s0_out_bits_1_exceptionVec_0 <= wb1_pick8 & io_wb_8_bits_exceptionVec_0;
      s0_out_bits_1_exceptionVec_1 <= wb1_pick8 & io_wb_8_bits_exceptionVec_1;
      s0_out_bits_1_exceptionVec_2 <= wb1_pick8 & io_wb_8_bits_exceptionVec_2;
      s0_out_bits_1_exceptionVec_3 <=
        wb1_pick8
          ? io_wb_8_bits_exceptionVec_3
          : wb1_right_pick9
              ? io_wb_9_bits_exceptionVec_3
              : io_wb_10_bits_exceptionVec_3;
      s0_out_bits_1_exceptionVec_4 <=
        wb1_pick8
          ? io_wb_8_bits_exceptionVec_4
          : wb1_right_pick9
              ? io_wb_9_bits_exceptionVec_4
              : io_wb_10_bits_exceptionVec_4;
      s0_out_bits_1_exceptionVec_5 <=
        wb1_pick8
          ? io_wb_8_bits_exceptionVec_5
          : wb1_right_pick9
              ? io_wb_9_bits_exceptionVec_5
              : io_wb_10_bits_exceptionVec_5;
      s0_out_bits_1_exceptionVec_6 <= wb1_pick8 & io_wb_8_bits_exceptionVec_6;
      s0_out_bits_1_exceptionVec_7 <= wb1_pick8 & io_wb_8_bits_exceptionVec_7;
      s0_out_bits_1_exceptionVec_8 <= wb1_pick8 & io_wb_8_bits_exceptionVec_8;
      s0_out_bits_1_exceptionVec_9 <= wb1_pick8 & io_wb_8_bits_exceptionVec_9;
      s0_out_bits_1_exceptionVec_10 <= wb1_pick8 & io_wb_8_bits_exceptionVec_10;
      s0_out_bits_1_exceptionVec_11 <= wb1_pick8 & io_wb_8_bits_exceptionVec_11;
      s0_out_bits_1_exceptionVec_12 <= wb1_pick8 & io_wb_8_bits_exceptionVec_12;
      s0_out_bits_1_exceptionVec_13 <=
        wb1_pick8
          ? io_wb_8_bits_exceptionVec_13
          : wb1_right_pick9
              ? io_wb_9_bits_exceptionVec_13
              : io_wb_10_bits_exceptionVec_13;
      s0_out_bits_1_exceptionVec_14 <= wb1_pick8 & io_wb_8_bits_exceptionVec_14;
      s0_out_bits_1_exceptionVec_15 <= wb1_pick8 & io_wb_8_bits_exceptionVec_15;
      s0_out_bits_1_exceptionVec_16 <= wb1_pick8 & io_wb_8_bits_exceptionVec_16;
      s0_out_bits_1_exceptionVec_17 <= wb1_pick8 & io_wb_8_bits_exceptionVec_17;
      s0_out_bits_1_exceptionVec_18 <= wb1_pick8 & io_wb_8_bits_exceptionVec_18;
      s0_out_bits_1_exceptionVec_19 <=
        wb1_pick8
          ? io_wb_8_bits_exceptionVec_19
          : wb1_right_pick9
              ? io_wb_9_bits_exceptionVec_19
              : io_wb_10_bits_exceptionVec_19;
      s0_out_bits_1_exceptionVec_20 <= wb1_pick8 & io_wb_8_bits_exceptionVec_20;
      s0_out_bits_1_exceptionVec_21 <=
        wb1_pick8
          ? io_wb_8_bits_exceptionVec_21
          : wb1_right_pick9
              ? io_wb_9_bits_exceptionVec_21
              : io_wb_10_bits_exceptionVec_21;
      s0_out_bits_1_exceptionVec_22 <= wb1_pick8 & io_wb_8_bits_exceptionVec_22;
      s0_out_bits_1_exceptionVec_23 <= wb1_pick8 & io_wb_8_bits_exceptionVec_23;
      s0_out_bits_1_flushPipe <=
        wb1_pick8
          ? io_wb_8_bits_flushPipe
          : wb1_right_pick9 ? io_wb_9_bits_flushPipe : io_wb_10_bits_flushPipe;
      s0_out_bits_1_replayInst <=
        wb1_pick8
          ? io_wb_8_bits_replayInst
          : wb1_right_pick9
              ? io_wb_9_bits_replayInst
              : io_wb_10_bits_replayInst;
      s0_out_bits_1_trigger <=
        wb1_pick8
          ? io_wb_8_bits_trigger
          : wb1_right_pick9 ? io_wb_9_bits_trigger : io_wb_10_bits_trigger;
    end
    if (wb_valid_2) begin
      s0_out_bits_2_robIdx_flag <=
        wb2_pick6 ? io_wb_6_bits_robIdx_flag : io_wb_7_bits_robIdx_flag;
      s0_out_bits_2_robIdx_value <=
        wb2_pick6 ? io_wb_6_bits_robIdx_value : io_wb_7_bits_robIdx_value;
      s0_out_bits_2_hasException <=
        wb2_pick6 ? io_wb_6_bits_hasException : io_wb_7_bits_hasException;
      s0_out_bits_2_exceptionVec_0 <= wb2_pick6 & io_wb_6_bits_exceptionVec_0;
      s0_out_bits_2_exceptionVec_1 <= wb2_pick6 & io_wb_6_bits_exceptionVec_1;
      s0_out_bits_2_exceptionVec_2 <= wb2_pick6 & io_wb_6_bits_exceptionVec_2;
      s0_out_bits_2_exceptionVec_3 <=
        wb2_pick6 ? io_wb_6_bits_exceptionVec_3 : io_wb_7_bits_exceptionVec_3;
      s0_out_bits_2_exceptionVec_4 <= wb2_pick6 & io_wb_6_bits_exceptionVec_4;
      s0_out_bits_2_exceptionVec_5 <= wb2_pick6 & io_wb_6_bits_exceptionVec_5;
      s0_out_bits_2_exceptionVec_6 <=
        wb2_pick6 ? io_wb_6_bits_exceptionVec_6 : io_wb_7_bits_exceptionVec_6;
      s0_out_bits_2_exceptionVec_7 <=
        wb2_pick6 ? io_wb_6_bits_exceptionVec_7 : io_wb_7_bits_exceptionVec_7;
      s0_out_bits_2_exceptionVec_8 <= wb2_pick6 & io_wb_6_bits_exceptionVec_8;
      s0_out_bits_2_exceptionVec_9 <= wb2_pick6 & io_wb_6_bits_exceptionVec_9;
      s0_out_bits_2_exceptionVec_10 <=
        wb2_pick6 & io_wb_6_bits_exceptionVec_10;
      s0_out_bits_2_exceptionVec_11 <=
        wb2_pick6 & io_wb_6_bits_exceptionVec_11;
      s0_out_bits_2_exceptionVec_12 <=
        wb2_pick6 & io_wb_6_bits_exceptionVec_12;
      s0_out_bits_2_exceptionVec_13 <=
        wb2_pick6 & io_wb_6_bits_exceptionVec_13;
      s0_out_bits_2_exceptionVec_14 <=
        wb2_pick6 & io_wb_6_bits_exceptionVec_14;
      s0_out_bits_2_exceptionVec_15 <=
        wb2_pick6
          ? io_wb_6_bits_exceptionVec_15
          : io_wb_7_bits_exceptionVec_15;
      s0_out_bits_2_exceptionVec_16 <=
        wb2_pick6 & io_wb_6_bits_exceptionVec_16;
      s0_out_bits_2_exceptionVec_17 <=
        wb2_pick6 & io_wb_6_bits_exceptionVec_17;
      s0_out_bits_2_exceptionVec_18 <=
        wb2_pick6 & io_wb_6_bits_exceptionVec_18;
      s0_out_bits_2_exceptionVec_19 <=
        wb2_pick6
          ? io_wb_6_bits_exceptionVec_19
          : io_wb_7_bits_exceptionVec_19;
      s0_out_bits_2_exceptionVec_20 <=
        wb2_pick6 & io_wb_6_bits_exceptionVec_20;
      s0_out_bits_2_exceptionVec_21 <=
        wb2_pick6 & io_wb_6_bits_exceptionVec_21;
      s0_out_bits_2_exceptionVec_22 <=
        wb2_pick6 & io_wb_6_bits_exceptionVec_22;
      s0_out_bits_2_exceptionVec_23 <=
        wb2_pick6
          ? io_wb_6_bits_exceptionVec_23
          : io_wb_7_bits_exceptionVec_23;
      s0_out_bits_2_flushPipe <= wb2_pick6 & io_wb_6_bits_flushPipe;
      s0_out_bits_2_trigger <=
        wb2_pick6 ? io_wb_6_bits_trigger : io_wb_7_bits_trigger;
    end
    if (wb_valid_3) begin
      s0_out_bits_3_robIdx_flag <=
        wb_left_pick1 ? io_wb_1_bits_robIdx_flag : io_wb_2_bits_robIdx_flag;
      s0_out_bits_3_robIdx_value <=
        wb_left_pick1 ? io_wb_1_bits_robIdx_value : io_wb_2_bits_robIdx_value;
      s0_out_bits_3_hasException <=
        wb_left_pick1 ? io_wb_1_bits_hasException : io_wb_2_bits_hasException;
      s0_out_bits_3_exceptionVec_2 <=
        wb_left_pick1
          ? io_wb_1_bits_exceptionVec_2
          : io_wb_2_bits_exceptionVec_2;
    end
    s0_out_bits_3_exceptionVec_0 <= ~wb_valid_3 & s0_out_bits_3_exceptionVec_0;
    s0_out_bits_3_exceptionVec_1 <= ~wb_valid_3 & s0_out_bits_3_exceptionVec_1;
    s0_out_bits_3_exceptionVec_3 <= ~wb_valid_3 & s0_out_bits_3_exceptionVec_3;
    s0_out_bits_3_exceptionVec_4 <= ~wb_valid_3 & s0_out_bits_3_exceptionVec_4;
    s0_out_bits_3_exceptionVec_5 <= ~wb_valid_3 & s0_out_bits_3_exceptionVec_5;
    s0_out_bits_3_exceptionVec_6 <= ~wb_valid_3 & s0_out_bits_3_exceptionVec_6;
    s0_out_bits_3_exceptionVec_7 <= ~wb_valid_3 & s0_out_bits_3_exceptionVec_7;
    s0_out_bits_3_exceptionVec_8 <= ~wb_valid_3 & s0_out_bits_3_exceptionVec_8;
    s0_out_bits_3_exceptionVec_9 <= ~wb_valid_3 & s0_out_bits_3_exceptionVec_9;
    s0_out_bits_3_exceptionVec_10 <= ~wb_valid_3 & s0_out_bits_3_exceptionVec_10;
    s0_out_bits_3_exceptionVec_11 <= ~wb_valid_3 & s0_out_bits_3_exceptionVec_11;
    s0_out_bits_3_exceptionVec_12 <= ~wb_valid_3 & s0_out_bits_3_exceptionVec_12;
    s0_out_bits_3_exceptionVec_13 <= ~wb_valid_3 & s0_out_bits_3_exceptionVec_13;
    s0_out_bits_3_exceptionVec_14 <= ~wb_valid_3 & s0_out_bits_3_exceptionVec_14;
    s0_out_bits_3_exceptionVec_15 <= ~wb_valid_3 & s0_out_bits_3_exceptionVec_15;
    s0_out_bits_3_exceptionVec_16 <= ~wb_valid_3 & s0_out_bits_3_exceptionVec_16;
    s0_out_bits_3_exceptionVec_17 <= ~wb_valid_3 & s0_out_bits_3_exceptionVec_17;
    s0_out_bits_3_exceptionVec_18 <= ~wb_valid_3 & s0_out_bits_3_exceptionVec_18;
    s0_out_bits_3_exceptionVec_19 <= ~wb_valid_3 & s0_out_bits_3_exceptionVec_19;
    s0_out_bits_3_exceptionVec_20 <= ~wb_valid_3 & s0_out_bits_3_exceptionVec_20;
    s0_out_bits_3_exceptionVec_21 <= ~wb_valid_3 & s0_out_bits_3_exceptionVec_21;
    s0_out_bits_3_exceptionVec_22 <= ~wb_valid_3 & s0_out_bits_3_exceptionVec_22;
    s0_out_bits_3_exceptionVec_23 <= ~wb_valid_3 & s0_out_bits_3_exceptionVec_23;
    if (wb_valid_4) begin
      s0_out_bits_4_robIdx_flag <=
        wb4_pick11 ? io_wb_11_bits_robIdx_flag : io_wb_12_bits_robIdx_flag;
      s0_out_bits_4_robIdx_value <=
        wb4_pick11 ? io_wb_11_bits_robIdx_value : io_wb_12_bits_robIdx_value;
      s0_out_bits_4_hasException <=
        wb4_pick11 ? io_wb_11_bits_hasException : io_wb_12_bits_hasException;
      s0_out_bits_4_exceptionVec_0 <= wb4_pick11 & io_wb_11_bits_exceptionVec_0;
      s0_out_bits_4_exceptionVec_1 <= wb4_pick11 & io_wb_11_bits_exceptionVec_1;
      s0_out_bits_4_exceptionVec_2 <= wb4_pick11 & io_wb_11_bits_exceptionVec_2;
      s0_out_bits_4_exceptionVec_3 <=
        wb4_pick11
          ? io_wb_11_bits_exceptionVec_3
          : io_wb_12_bits_exceptionVec_3;
      s0_out_bits_4_exceptionVec_4 <=
        wb4_pick11
          ? io_wb_11_bits_exceptionVec_4
          : io_wb_12_bits_exceptionVec_4;
      s0_out_bits_4_exceptionVec_5 <=
        wb4_pick11
          ? io_wb_11_bits_exceptionVec_5
          : io_wb_12_bits_exceptionVec_5;
      s0_out_bits_4_exceptionVec_6 <=
        wb4_pick11
          ? io_wb_11_bits_exceptionVec_6
          : io_wb_12_bits_exceptionVec_6;
      s0_out_bits_4_exceptionVec_7 <=
        wb4_pick11
          ? io_wb_11_bits_exceptionVec_7
          : io_wb_12_bits_exceptionVec_7;
      s0_out_bits_4_exceptionVec_8 <= wb4_pick11 & io_wb_11_bits_exceptionVec_8;
      s0_out_bits_4_exceptionVec_9 <= wb4_pick11 & io_wb_11_bits_exceptionVec_9;
      s0_out_bits_4_exceptionVec_10 <=
        wb4_pick11 & io_wb_11_bits_exceptionVec_10;
      s0_out_bits_4_exceptionVec_11 <=
        wb4_pick11 & io_wb_11_bits_exceptionVec_11;
      s0_out_bits_4_exceptionVec_12 <=
        wb4_pick11 & io_wb_11_bits_exceptionVec_12;
      s0_out_bits_4_exceptionVec_13 <=
        wb4_pick11
          ? io_wb_11_bits_exceptionVec_13
          : io_wb_12_bits_exceptionVec_13;
      s0_out_bits_4_exceptionVec_14 <=
        wb4_pick11 & io_wb_11_bits_exceptionVec_14;
      s0_out_bits_4_exceptionVec_15 <=
        wb4_pick11
          ? io_wb_11_bits_exceptionVec_15
          : io_wb_12_bits_exceptionVec_15;
      s0_out_bits_4_exceptionVec_16 <=
        wb4_pick11 & io_wb_11_bits_exceptionVec_16;
      s0_out_bits_4_exceptionVec_17 <=
        wb4_pick11 & io_wb_11_bits_exceptionVec_17;
      s0_out_bits_4_exceptionVec_18 <=
        wb4_pick11 & io_wb_11_bits_exceptionVec_18;
      s0_out_bits_4_exceptionVec_19 <=
        wb4_pick11
          ? io_wb_11_bits_exceptionVec_19
          : io_wb_12_bits_exceptionVec_19;
      s0_out_bits_4_exceptionVec_20 <=
        wb4_pick11 & io_wb_11_bits_exceptionVec_20;
      s0_out_bits_4_exceptionVec_21 <=
        wb4_pick11
          ? io_wb_11_bits_exceptionVec_21
          : io_wb_12_bits_exceptionVec_21;
      s0_out_bits_4_exceptionVec_22 <=
        wb4_pick11 & io_wb_11_bits_exceptionVec_22;
      s0_out_bits_4_exceptionVec_23 <=
        wb4_pick11
          ? io_wb_11_bits_exceptionVec_23
          : io_wb_12_bits_exceptionVec_23;
      s0_out_bits_4_flushPipe <=
        wb4_pick11 ? io_wb_11_bits_flushPipe : io_wb_12_bits_flushPipe;
      s0_out_bits_4_replayInst <=
        wb4_pick11 ? io_wb_11_bits_replayInst : io_wb_12_bits_replayInst;
      s0_out_bits_4_trigger <=
        wb4_pick11 ? io_wb_11_bits_trigger : io_wb_12_bits_trigger;
      s0_out_bits_4_vstartEn <=
        wb4_pick11 ? io_wb_11_bits_vstartEn : io_wb_12_bits_vstartEn;
      s0_out_bits_4_vstart <=
        wb4_pick11 ? io_wb_11_bits_vstart : io_wb_12_bits_vstart;
      s0_out_bits_4_vuopIdx <=
        wb4_pick11 ? io_wb_11_bits_vuopIdx : io_wb_12_bits_vuopIdx;
      s0_out_bits_4_isVecLoad <=
        wb4_pick11 ? io_wb_11_bits_isVecLoad : io_wb_12_bits_isVecLoad;
      s0_out_bits_4_isVlm <=
        wb4_pick11 ? io_wb_11_bits_isVlm : io_wb_12_bits_isVlm;
      s0_out_bits_4_isStrided <=
        wb4_pick11 ? io_wb_11_bits_isStrided : io_wb_12_bits_isStrided;
      s0_out_bits_4_isIndexed <=
        wb4_pick11 ? io_wb_11_bits_isIndexed : io_wb_12_bits_isIndexed;
      s0_out_bits_4_isWhole <=
        wb4_pick11 ? io_wb_11_bits_isWhole : io_wb_12_bits_isWhole;
      s0_out_bits_4_nf <= wb4_pick11 ? io_wb_11_bits_nf : io_wb_12_bits_nf;
      s0_out_bits_4_vsew <=
        wb4_pick11 ? io_wb_11_bits_vsew : io_wb_12_bits_vsew;
      s0_out_bits_4_veew <=
        wb4_pick11 ? io_wb_11_bits_veew : io_wb_12_bits_veew;
      s0_out_bits_4_vlmul <=
        wb4_pick11 ? io_wb_11_bits_vlmul : io_wb_12_bits_vlmul;
    end
    if (|{s1_valid_4, s1_valid_3, s1_valid_2, s1_valid_1, s1_valid_0}) begin
      s1_out_bits_robIdx_flag <=
        s1_top_pickLeft
          ? s1_out_bits_res_0_bits_robIdx_flag
          : s1_out_bits_res_1_bits_robIdx_flag;
      s1_out_bits_robIdx_value <=
        s1_top_pickLeft
          ? s1_out_bits_res_0_bits_robIdx_value
          : s1_out_bits_res_1_bits_robIdx_value;
      s1_out_bits_hasException <=
        s1_top_pickLeft
          ? (s1_left_pick0
               ? s0_out_bits_0_hasException
               : s0_out_bits_1_hasException)
          : s1_right_pick2
              ? s0_out_bits_2_hasException
              : s1_rr_pick3
                  ? s0_out_bits_3_hasException
                  : s0_out_bits_4_hasException;
      s1_out_bits_exceptionVec_0 <=
        s1_top_pickLeft
          ? (s1_left_pick0
               ? s0_out_bits_0_exceptionVec_0
               : s0_out_bits_1_exceptionVec_0)
          : s1_right_pick2
              ? s0_out_bits_2_exceptionVec_0
              : s1_rr_pick3
                  ? s0_out_bits_3_exceptionVec_0
                  : s0_out_bits_4_exceptionVec_0;
      s1_out_bits_exceptionVec_1 <=
        s1_top_pickLeft
          ? (s1_left_pick0
               ? s0_out_bits_0_exceptionVec_1
               : s0_out_bits_1_exceptionVec_1)
          : s1_right_pick2
              ? s0_out_bits_2_exceptionVec_1
              : s1_rr_pick3
                  ? s0_out_bits_3_exceptionVec_1
                  : s0_out_bits_4_exceptionVec_1;
      s1_out_bits_exceptionVec_2 <=
        s1_top_pickLeft
          ? (s1_left_pick0
               ? s0_out_bits_0_exceptionVec_2
               : s0_out_bits_1_exceptionVec_2)
          : s1_right_pick2
              ? s0_out_bits_2_exceptionVec_2
              : s1_rr_pick3
                  ? s0_out_bits_3_exceptionVec_2
                  : s0_out_bits_4_exceptionVec_2;
      s1_out_bits_exceptionVec_3 <=
        s1_top_pickLeft
          ? (s1_left_pick0
               ? s0_out_bits_0_exceptionVec_3
               : s0_out_bits_1_exceptionVec_3)
          : s1_right_pick2
              ? s0_out_bits_2_exceptionVec_3
              : s1_rr_pick3
                  ? s0_out_bits_3_exceptionVec_3
                  : s0_out_bits_4_exceptionVec_3;
      s1_out_bits_exceptionVec_4 <=
        s1_top_pickLeft
          ? (s1_left_pick0
               ? s0_out_bits_0_exceptionVec_4
               : s0_out_bits_1_exceptionVec_4)
          : s1_right_pick2
              ? s0_out_bits_2_exceptionVec_4
              : s1_rr_pick3
                  ? s0_out_bits_3_exceptionVec_4
                  : s0_out_bits_4_exceptionVec_4;
      s1_out_bits_exceptionVec_5 <=
        s1_top_pickLeft
          ? (s1_left_pick0
               ? s0_out_bits_0_exceptionVec_5
               : s0_out_bits_1_exceptionVec_5)
          : s1_right_pick2
              ? s0_out_bits_2_exceptionVec_5
              : s1_rr_pick3
                  ? s0_out_bits_3_exceptionVec_5
                  : s0_out_bits_4_exceptionVec_5;
      s1_out_bits_exceptionVec_6 <=
        s1_top_pickLeft
          ? (s1_left_pick0
               ? s0_out_bits_0_exceptionVec_6
               : s0_out_bits_1_exceptionVec_6)
          : s1_right_pick2
              ? s0_out_bits_2_exceptionVec_6
              : s1_rr_pick3
                  ? s0_out_bits_3_exceptionVec_6
                  : s0_out_bits_4_exceptionVec_6;
      s1_out_bits_exceptionVec_7 <=
        s1_top_pickLeft
          ? (s1_left_pick0
               ? s0_out_bits_0_exceptionVec_7
               : s0_out_bits_1_exceptionVec_7)
          : s1_right_pick2
              ? s0_out_bits_2_exceptionVec_7
              : s1_rr_pick3
                  ? s0_out_bits_3_exceptionVec_7
                  : s0_out_bits_4_exceptionVec_7;
      s1_out_bits_exceptionVec_8 <=
        s1_top_pickLeft
          ? (s1_left_pick0
               ? s0_out_bits_0_exceptionVec_8
               : s0_out_bits_1_exceptionVec_8)
          : s1_right_pick2
              ? s0_out_bits_2_exceptionVec_8
              : s1_rr_pick3
                  ? s0_out_bits_3_exceptionVec_8
                  : s0_out_bits_4_exceptionVec_8;
      s1_out_bits_exceptionVec_9 <=
        s1_top_pickLeft
          ? (s1_left_pick0
               ? s0_out_bits_0_exceptionVec_9
               : s0_out_bits_1_exceptionVec_9)
          : s1_right_pick2
              ? s0_out_bits_2_exceptionVec_9
              : s1_rr_pick3
                  ? s0_out_bits_3_exceptionVec_9
                  : s0_out_bits_4_exceptionVec_9;
      s1_out_bits_exceptionVec_10 <=
        s1_top_pickLeft
          ? (s1_left_pick0
               ? s0_out_bits_0_exceptionVec_10
               : s0_out_bits_1_exceptionVec_10)
          : s1_right_pick2
              ? s0_out_bits_2_exceptionVec_10
              : s1_rr_pick3
                  ? s0_out_bits_3_exceptionVec_10
                  : s0_out_bits_4_exceptionVec_10;
      s1_out_bits_exceptionVec_11 <=
        s1_top_pickLeft
          ? (s1_left_pick0
               ? s0_out_bits_0_exceptionVec_11
               : s0_out_bits_1_exceptionVec_11)
          : s1_right_pick2
              ? s0_out_bits_2_exceptionVec_11
              : s1_rr_pick3
                  ? s0_out_bits_3_exceptionVec_11
                  : s0_out_bits_4_exceptionVec_11;
      s1_out_bits_exceptionVec_12 <=
        s1_top_pickLeft
          ? (s1_left_pick0
               ? s0_out_bits_0_exceptionVec_12
               : s0_out_bits_1_exceptionVec_12)
          : s1_right_pick2
              ? s0_out_bits_2_exceptionVec_12
              : s1_rr_pick3
                  ? s0_out_bits_3_exceptionVec_12
                  : s0_out_bits_4_exceptionVec_12;
      s1_out_bits_exceptionVec_13 <=
        s1_top_pickLeft
          ? (s1_left_pick0
               ? s0_out_bits_0_exceptionVec_13
               : s0_out_bits_1_exceptionVec_13)
          : s1_right_pick2
              ? s0_out_bits_2_exceptionVec_13
              : s1_rr_pick3
                  ? s0_out_bits_3_exceptionVec_13
                  : s0_out_bits_4_exceptionVec_13;
      s1_out_bits_exceptionVec_14 <=
        s1_top_pickLeft
          ? (s1_left_pick0
               ? s0_out_bits_0_exceptionVec_14
               : s0_out_bits_1_exceptionVec_14)
          : s1_right_pick2
              ? s0_out_bits_2_exceptionVec_14
              : s1_rr_pick3
                  ? s0_out_bits_3_exceptionVec_14
                  : s0_out_bits_4_exceptionVec_14;
      s1_out_bits_exceptionVec_15 <=
        s1_top_pickLeft
          ? (s1_left_pick0
               ? s0_out_bits_0_exceptionVec_15
               : s0_out_bits_1_exceptionVec_15)
          : s1_right_pick2
              ? s0_out_bits_2_exceptionVec_15
              : s1_rr_pick3
                  ? s0_out_bits_3_exceptionVec_15
                  : s0_out_bits_4_exceptionVec_15;
      s1_out_bits_exceptionVec_16 <=
        s1_top_pickLeft
          ? (s1_left_pick0
               ? s0_out_bits_0_exceptionVec_16
               : s0_out_bits_1_exceptionVec_16)
          : s1_right_pick2
              ? s0_out_bits_2_exceptionVec_16
              : s1_rr_pick3
                  ? s0_out_bits_3_exceptionVec_16
                  : s0_out_bits_4_exceptionVec_16;
      s1_out_bits_exceptionVec_17 <=
        s1_top_pickLeft
          ? (s1_left_pick0
               ? s0_out_bits_0_exceptionVec_17
               : s0_out_bits_1_exceptionVec_17)
          : s1_right_pick2
              ? s0_out_bits_2_exceptionVec_17
              : s1_rr_pick3
                  ? s0_out_bits_3_exceptionVec_17
                  : s0_out_bits_4_exceptionVec_17;
      s1_out_bits_exceptionVec_18 <=
        s1_top_pickLeft
          ? (s1_left_pick0
               ? s0_out_bits_0_exceptionVec_18
               : s0_out_bits_1_exceptionVec_18)
          : s1_right_pick2
              ? s0_out_bits_2_exceptionVec_18
              : s1_rr_pick3
                  ? s0_out_bits_3_exceptionVec_18
                  : s0_out_bits_4_exceptionVec_18;
      s1_out_bits_exceptionVec_19 <=
        s1_top_pickLeft
          ? (s1_left_pick0
               ? s0_out_bits_0_exceptionVec_19
               : s0_out_bits_1_exceptionVec_19)
          : s1_right_pick2
              ? s0_out_bits_2_exceptionVec_19
              : s1_rr_pick3
                  ? s0_out_bits_3_exceptionVec_19
                  : s0_out_bits_4_exceptionVec_19;
      s1_out_bits_exceptionVec_20 <=
        s1_top_pickLeft
          ? (s1_left_pick0
               ? s0_out_bits_0_exceptionVec_20
               : s0_out_bits_1_exceptionVec_20)
          : s1_right_pick2
              ? s0_out_bits_2_exceptionVec_20
              : s1_rr_pick3
                  ? s0_out_bits_3_exceptionVec_20
                  : s0_out_bits_4_exceptionVec_20;
      s1_out_bits_exceptionVec_21 <=
        s1_top_pickLeft
          ? (s1_left_pick0
               ? s0_out_bits_0_exceptionVec_21
               : s0_out_bits_1_exceptionVec_21)
          : s1_right_pick2
              ? s0_out_bits_2_exceptionVec_21
              : s1_rr_pick3
                  ? s0_out_bits_3_exceptionVec_21
                  : s0_out_bits_4_exceptionVec_21;
      s1_out_bits_exceptionVec_22 <=
        s1_top_pickLeft
          ? (s1_left_pick0
               ? s0_out_bits_0_exceptionVec_22
               : s0_out_bits_1_exceptionVec_22)
          : s1_right_pick2
              ? s0_out_bits_2_exceptionVec_22
              : s1_rr_pick3
                  ? s0_out_bits_3_exceptionVec_22
                  : s0_out_bits_4_exceptionVec_22;
      s1_out_bits_exceptionVec_23 <=
        s1_top_pickLeft
          ? (s1_left_pick0
               ? s0_out_bits_0_exceptionVec_23
               : s0_out_bits_1_exceptionVec_23)
          : s1_right_pick2
              ? s0_out_bits_2_exceptionVec_23
              : s1_rr_pick3
                  ? s0_out_bits_3_exceptionVec_23
                  : s0_out_bits_4_exceptionVec_23;
      s1_out_bits_flushPipe <=
        s1_top_pickLeft
          ? (s1_left_pick0
               ? s0_out_bits_0_flushPipe
               : s0_out_bits_1_flushPipe)
          : s1_right_pick2
              ? s0_out_bits_2_flushPipe
              : ~s1_rr_pick3 & s0_out_bits_4_flushPipe;
      s1_out_bits_replayInst <=
        s1_top_pickLeft
          ? ~s1_left_pick0 & s0_out_bits_1_replayInst
          : ~s1_right_pick2 & ~s1_rr_pick3
            & s0_out_bits_4_replayInst;
      s1_out_bits_trigger <=
        s1_top_pickLeft
          ? (s1_left_pick0 ? 4'hF : s0_out_bits_1_trigger)
          : s1_right_pick2
              ? s0_out_bits_2_trigger
              : s1_rr_pick3 ? 4'hF : s0_out_bits_4_trigger;
      s1_out_bits_vstartEn <=
        ~s1_top_pickLeft & ~s1_right_pick2
        & ~s1_rr_pick3 & s0_out_bits_4_vstartEn;
      s1_out_bits_vstart <= s1NoValidPick ? 64'h0 : s0_out_bits_4_vstart;
      s1_out_bits_isVecLoad <=
        ~s1_top_pickLeft & ~s1_right_pick2
        & ~s1_rr_pick3 & s0_out_bits_4_isVecLoad;
      s1_out_bits_isVlm <=
        ~s1_top_pickLeft & ~s1_right_pick2
        & ~s1_rr_pick3 & s0_out_bits_4_isVlm;
      s1_out_bits_isStrided <=
        ~s1_top_pickLeft & ~s1_right_pick2
        & ~s1_rr_pick3 & s0_out_bits_4_isStrided;
      s1_out_bits_isIndexed <=
        ~s1_top_pickLeft & ~s1_right_pick2
        & ~s1_rr_pick3 & s0_out_bits_4_isIndexed;
      s1_out_bits_isWhole <=
        ~s1_top_pickLeft & ~s1_right_pick2
        & ~s1_rr_pick3 & s0_out_bits_4_isWhole;
      s1_out_bits_nf <= s1NoValidPick ? 3'h0 : s0_out_bits_4_nf;
      s1_out_bits_vsew <= s1NoValidPick ? 2'h0 : s0_out_bits_4_vsew;
      s1_out_bits_veew <= s1NoValidPick ? 2'h0 : s0_out_bits_4_veew;
      s1_out_bits_vlmul <= s1NoValidPick ? 3'h0 : s0_out_bits_4_vlmul;
    end
    s1_out_valid <= |{s1_valid_4, s1_valid_3, s1_valid_2, s1_valid_1, s1_valid_0};
    enq_s1_valid <=
      (|{enq_s0_valid_5,
         enq_s0_valid_4,
         enq_s0_valid_3,
         enq_s0_valid_2,
         enq_s0_valid_1,
         enq_s0_valid_0}) & ~io_redirect_valid & ~io_flush;
    if ((|{enq_s0_valid_5,
           enq_s0_valid_4,
           enq_s0_valid_3,
           enq_s0_valid_2,
           enq_s0_valid_1,
           enq_s0_valid_0}) & ~io_redirect_valid & ~io_flush) begin
      enq_s1_bits_robIdx_flag <=
        enq_pick_left
          ? (enq_s0_valid_0
               ? io_enq_0_bits_robIdx_flag
               : enq_s0_valid_1 ? io_enq_1_bits_robIdx_flag : io_enq_2_bits_robIdx_flag)
          : enq_s0_valid_3
              ? io_enq_3_bits_robIdx_flag
              : enq_s0_valid_4 ? io_enq_4_bits_robIdx_flag : io_enq_5_bits_robIdx_flag;
      enq_s1_bits_robIdx_value <=
        enq_pick_left
          ? (enq_s0_valid_0
               ? io_enq_0_bits_robIdx_value
               : enq_s0_valid_1 ? io_enq_1_bits_robIdx_value : io_enq_2_bits_robIdx_value)
          : enq_s0_valid_3
              ? io_enq_3_bits_robIdx_value
              : enq_s0_valid_4 ? io_enq_4_bits_robIdx_value : io_enq_5_bits_robIdx_value;
      enq_s1_bits_ftqPtr_value <=
        enq_pick_left
          ? (enq_s0_valid_0
               ? io_enq_0_bits_ftqPtr_value
               : enq_s0_valid_1 ? io_enq_1_bits_ftqPtr_value : io_enq_2_bits_ftqPtr_value)
          : enq_s0_valid_3
              ? io_enq_3_bits_ftqPtr_value
              : enq_s0_valid_4 ? io_enq_4_bits_ftqPtr_value : io_enq_5_bits_ftqPtr_value;
      enq_s1_bits_ftqOffset <=
        enq_pick_left
          ? (enq_s0_valid_0
               ? io_enq_0_bits_ftqOffset
               : enq_s0_valid_1 ? io_enq_1_bits_ftqOffset : io_enq_2_bits_ftqOffset)
          : enq_s0_valid_3
              ? io_enq_3_bits_ftqOffset
              : enq_s0_valid_4 ? io_enq_4_bits_ftqOffset : io_enq_5_bits_ftqOffset;
      enq_s1_bits_hasException <=
        enq_pick_left
          ? (enq_s0_valid_0
               ? io_enq_0_bits_hasException
               : enq_s0_valid_1 ? io_enq_1_bits_hasException : io_enq_2_bits_hasException)
          : enq_s0_valid_3
              ? io_enq_3_bits_hasException
              : enq_s0_valid_4 ? io_enq_4_bits_hasException : io_enq_5_bits_hasException;
      enq_s1_bits_exceptionVec_0 <=
        enq_pick_left
          ? (enq_s0_valid_0
               ? io_enq_0_bits_exceptionVec_0
               : enq_s0_valid_1
                   ? io_enq_1_bits_exceptionVec_0
                   : io_enq_2_bits_exceptionVec_0)
          : enq_s0_valid_3
              ? io_enq_3_bits_exceptionVec_0
              : enq_s0_valid_4
                  ? io_enq_4_bits_exceptionVec_0
                  : io_enq_5_bits_exceptionVec_0;
      enq_s1_bits_exceptionVec_1 <=
        enq_pick_left
          ? (enq_s0_valid_0
               ? io_enq_0_bits_exceptionVec_1
               : enq_s0_valid_1
                   ? io_enq_1_bits_exceptionVec_1
                   : io_enq_2_bits_exceptionVec_1)
          : enq_s0_valid_3
              ? io_enq_3_bits_exceptionVec_1
              : enq_s0_valid_4
                  ? io_enq_4_bits_exceptionVec_1
                  : io_enq_5_bits_exceptionVec_1;
      enq_s1_bits_exceptionVec_2 <=
        enq_pick_left
          ? (enq_s0_valid_0
               ? io_enq_0_bits_exceptionVec_2
               : enq_s0_valid_1
                   ? io_enq_1_bits_exceptionVec_2
                   : io_enq_2_bits_exceptionVec_2)
          : enq_s0_valid_3
              ? io_enq_3_bits_exceptionVec_2
              : enq_s0_valid_4
                  ? io_enq_4_bits_exceptionVec_2
                  : io_enq_5_bits_exceptionVec_2;
      enq_s1_bits_exceptionVec_3 <=
        enq_pick_left
          ? (enq_s0_valid_0
               ? io_enq_0_bits_exceptionVec_3
               : enq_s0_valid_1
                   ? io_enq_1_bits_exceptionVec_3
                   : io_enq_2_bits_exceptionVec_3)
          : enq_s0_valid_3
              ? io_enq_3_bits_exceptionVec_3
              : enq_s0_valid_4
                  ? io_enq_4_bits_exceptionVec_3
                  : io_enq_5_bits_exceptionVec_3;
      enq_s1_bits_exceptionVec_12 <=
        enq_pick_left
          ? (enq_s0_valid_0
               ? io_enq_0_bits_exceptionVec_12
               : enq_s0_valid_1
                   ? io_enq_1_bits_exceptionVec_12
                   : io_enq_2_bits_exceptionVec_12)
          : enq_s0_valid_3
              ? io_enq_3_bits_exceptionVec_12
              : enq_s0_valid_4
                  ? io_enq_4_bits_exceptionVec_12
                  : io_enq_5_bits_exceptionVec_12;
      enq_s1_bits_exceptionVec_20 <=
        enq_pick_left
          ? (enq_s0_valid_0
               ? io_enq_0_bits_exceptionVec_20
               : enq_s0_valid_1
                   ? io_enq_1_bits_exceptionVec_20
                   : io_enq_2_bits_exceptionVec_20)
          : enq_s0_valid_3
              ? io_enq_3_bits_exceptionVec_20
              : enq_s0_valid_4
                  ? io_enq_4_bits_exceptionVec_20
                  : io_enq_5_bits_exceptionVec_20;
      enq_s1_bits_exceptionVec_22 <=
        enq_pick_left
          ? (enq_s0_valid_0
               ? io_enq_0_bits_exceptionVec_22
               : enq_s0_valid_1
                   ? io_enq_1_bits_exceptionVec_22
                   : io_enq_2_bits_exceptionVec_22)
          : enq_s0_valid_3
              ? io_enq_3_bits_exceptionVec_22
              : enq_s0_valid_4
                  ? io_enq_4_bits_exceptionVec_22
                  : io_enq_5_bits_exceptionVec_22;
      enq_s1_bits_isFetchMalAddr <=
        enq_pick_left
          ? (enq_s0_valid_0
               ? io_enq_0_bits_isFetchMalAddr
               : enq_s0_valid_1
                   ? io_enq_1_bits_isFetchMalAddr
                   : io_enq_2_bits_isFetchMalAddr)
          : enq_s0_valid_3
              ? io_enq_3_bits_isFetchMalAddr
              : enq_s0_valid_4
                  ? io_enq_4_bits_isFetchMalAddr
                  : io_enq_5_bits_isFetchMalAddr;
      enq_s1_bits_flushPipe <=
        enq_pick_left
          ? (enq_s0_valid_0
               ? io_enq_0_bits_flushPipe & ~io_enq_0_bits_hasException
               : enq_s0_valid_1
                   ? io_enq_1_bits_flushPipe & ~io_enq_1_bits_hasException
                   : io_enq_2_bits_flushPipe & ~io_enq_2_bits_hasException)
          : enq_s0_valid_3
              ? io_enq_3_bits_flushPipe & ~io_enq_3_bits_hasException
              : enq_s0_valid_4
                  ? io_enq_4_bits_flushPipe & ~io_enq_4_bits_hasException
                  : io_enq_5_bits_flushPipe & ~io_enq_5_bits_hasException;
      enq_s1_bits_isVset <=
        enq_pick_left
          ? (enq_s0_valid_0
               ? io_enq_0_bits_isVset
               : enq_s0_valid_1 ? io_enq_1_bits_isVset : io_enq_2_bits_isVset)
          : enq_s0_valid_3
              ? io_enq_3_bits_isVset
              : enq_s0_valid_4 ? io_enq_4_bits_isVset : io_enq_5_bits_isVset;
      enq_s1_bits_singleStep <=
        enq_pick_left
          ? (enq_s0_valid_0
               ? io_enq_0_bits_singleStep
               : enq_s0_valid_1 ? io_enq_1_bits_singleStep : io_enq_2_bits_singleStep)
          : enq_s0_valid_3
              ? io_enq_3_bits_singleStep
              : enq_s0_valid_4 ? io_enq_4_bits_singleStep : io_enq_5_bits_singleStep;
      enq_s1_bits_crossPageIPFFix <=
        enq_pick_left
          ? (enq_s0_valid_0
               ? io_enq_0_bits_crossPageIPFFix
               : enq_s0_valid_1
                   ? io_enq_1_bits_crossPageIPFFix
                   : io_enq_2_bits_crossPageIPFFix)
          : enq_s0_valid_3
              ? io_enq_3_bits_crossPageIPFFix
              : enq_s0_valid_4
                  ? io_enq_4_bits_crossPageIPFFix
                  : io_enq_5_bits_crossPageIPFFix;
      enq_s1_bits_trigger <=
        enq_pick_left
          ? (enq_s0_valid_0
               ? io_enq_0_bits_trigger
               : enq_s0_valid_1 ? io_enq_1_bits_trigger : io_enq_2_bits_trigger)
          : enq_s0_valid_3
              ? io_enq_3_bits_trigger
              : enq_s0_valid_4 ? io_enq_4_bits_trigger : io_enq_5_bits_trigger;
    end
  end // always @(posedge)
  assign io_state_valid = currentValid;
  assign io_state_bits_robIdx_flag = current_robIdx_flag;
  assign io_state_bits_robIdx_value = current_robIdx_value;
  assign io_state_bits_ftqPtr_value = current_ftqPtr_value;
  assign io_state_bits_ftqOffset = current_ftqOffset;
  assign io_state_bits_hasException = current_hasException;
  assign io_state_bits_isEnqExcp = current_isEnqExcp;
  assign io_state_bits_exceptionVec_0 = current_exceptionVec_0;
  assign io_state_bits_exceptionVec_1 = current_exceptionVec_1;
  assign io_state_bits_exceptionVec_2 = current_exceptionVec_2;
  assign io_state_bits_exceptionVec_3 = current_exceptionVec_3;
  assign io_state_bits_exceptionVec_4 = current_exceptionVec_4;
  assign io_state_bits_exceptionVec_5 = current_exceptionVec_5;
  assign io_state_bits_exceptionVec_6 = current_exceptionVec_6;
  assign io_state_bits_exceptionVec_7 = current_exceptionVec_7;
  assign io_state_bits_exceptionVec_8 = current_exceptionVec_8;
  assign io_state_bits_exceptionVec_9 = current_exceptionVec_9;
  assign io_state_bits_exceptionVec_10 = current_exceptionVec_10;
  assign io_state_bits_exceptionVec_11 = current_exceptionVec_11;
  assign io_state_bits_exceptionVec_12 = current_exceptionVec_12;
  assign io_state_bits_exceptionVec_13 = current_exceptionVec_13;
  assign io_state_bits_exceptionVec_14 = current_exceptionVec_14;
  assign io_state_bits_exceptionVec_15 = current_exceptionVec_15;
  assign io_state_bits_exceptionVec_16 = current_exceptionVec_16;
  assign io_state_bits_exceptionVec_17 = current_exceptionVec_17;
  assign io_state_bits_exceptionVec_18 = current_exceptionVec_18;
  assign io_state_bits_exceptionVec_19 = current_exceptionVec_19;
  assign io_state_bits_exceptionVec_20 = current_exceptionVec_20;
  assign io_state_bits_exceptionVec_21 = current_exceptionVec_21;
  assign io_state_bits_exceptionVec_22 = current_exceptionVec_22;
  assign io_state_bits_exceptionVec_23 = current_exceptionVec_23;
  assign io_state_bits_isFetchMalAddr = current_isFetchMalAddr;
  assign io_state_bits_flushPipe = current_flushPipe;
  assign io_state_bits_isVset = current_isVset;
  assign io_state_bits_replayInst = current_replayInst;
  assign io_state_bits_singleStep = current_singleStep;
  assign io_state_bits_crossPageIPFFix = current_crossPageIPFFix;
  assign io_state_bits_trigger = current_trigger;
  assign io_state_bits_vstartEn = current_vstartEn;
  assign io_state_bits_vstart = current_vstart;
  assign io_state_bits_isVecLoad = current_isVecLoad;
  assign io_state_bits_isVlm = current_isVlm;
  assign io_state_bits_isStrided = current_isStrided;
  assign io_state_bits_isIndexed = current_isIndexed;
  assign io_state_bits_isWhole = current_isWhole;
  assign io_state_bits_nf = current_nf;
  assign io_state_bits_vsew = current_vsew;
  assign io_state_bits_veew = current_veew;
  assign io_state_bits_vlmul = current_vlmul;
endmodule
