// 自动生成:scripts/gen_exeunit.py（ExeUnit_8）—— 勿手改(逻辑为从设计意图的可读重写)
// golden 同名扁平 wrapper(FM/ST 用):例化可读核。
module ExeUnit_8(
  input  clock,
  input  reset,
  input  io_flush_valid,
  input  io_flush_bits_robIdx_flag,
  input  [7:0] io_flush_bits_robIdx_value,
  input  io_flush_bits_level,
  input  io_in_valid,
  input  [34:0] io_in_bits_fuType,
  input  [8:0] io_in_bits_fuOpType,
  input  [63:0] io_in_bits_src_0,
  input  [63:0] io_in_bits_src_1,
  input  [63:0] io_in_bits_src_2,
  input  io_in_bits_robIdx_flag,
  input  [7:0] io_in_bits_robIdx_value,
  input  [7:0] io_in_bits_pdest,
  input  io_in_bits_rfWen,
  input  io_in_bits_fpWen,
  input  io_in_bits_vecWen,
  input  io_in_bits_v0Wen,
  input  io_in_bits_fpu_wflags,
  input  [1:0] io_in_bits_fpu_fmt,
  input  [2:0] io_in_bits_fpu_rm,
  input  [63:0] io_in_bits_perfDebugInfo_enqRsTime,
  input  [63:0] io_in_bits_perfDebugInfo_selectTime,
  input  [63:0] io_in_bits_perfDebugInfo_issueTime,
  output io_out_valid,
  output [127:0] io_out_bits_data_0,
  output [127:0] io_out_bits_data_1,
  output [127:0] io_out_bits_data_2,
  output [127:0] io_out_bits_data_3,
  output [127:0] io_out_bits_data_4,
  output [7:0] io_out_bits_pdest,
  output io_out_bits_robIdx_flag,
  output [7:0] io_out_bits_robIdx_value,
  output io_out_bits_intWen,
  output io_out_bits_fpWen,
  output io_out_bits_vecWen,
  output io_out_bits_v0Wen,
  output [4:0] io_out_bits_fflags,
  output io_out_bits_wflags,
  output [63:0] io_out_bits_debugInfo_enqRsTime,
  output [63:0] io_out_bits_debugInfo_selectTime,
  output [63:0] io_out_bits_debugInfo_issueTime,
  input  [2:0] io_frm,
  input  cg_bore_cgen,
  input  cg_bore_1_cgen,
  input  cg_bore_2_cgen
);
  xs_ExeUnit_8_core u_core (
    .clock(clock),
    .reset(reset),
    .io_flush_valid(io_flush_valid),
    .io_flush_bits_robIdx_flag(io_flush_bits_robIdx_flag),
    .io_flush_bits_robIdx_value(io_flush_bits_robIdx_value),
    .io_flush_bits_level(io_flush_bits_level),
    .io_in_valid(io_in_valid),
    .io_in_bits_fuType(io_in_bits_fuType),
    .io_in_bits_fuOpType(io_in_bits_fuOpType),
    .io_in_bits_src_0(io_in_bits_src_0),
    .io_in_bits_src_1(io_in_bits_src_1),
    .io_in_bits_src_2(io_in_bits_src_2),
    .io_in_bits_robIdx_flag(io_in_bits_robIdx_flag),
    .io_in_bits_robIdx_value(io_in_bits_robIdx_value),
    .io_in_bits_pdest(io_in_bits_pdest),
    .io_in_bits_rfWen(io_in_bits_rfWen),
    .io_in_bits_fpWen(io_in_bits_fpWen),
    .io_in_bits_vecWen(io_in_bits_vecWen),
    .io_in_bits_v0Wen(io_in_bits_v0Wen),
    .io_in_bits_fpu_wflags(io_in_bits_fpu_wflags),
    .io_in_bits_fpu_fmt(io_in_bits_fpu_fmt),
    .io_in_bits_fpu_rm(io_in_bits_fpu_rm),
    .io_in_bits_perfDebugInfo_enqRsTime(io_in_bits_perfDebugInfo_enqRsTime),
    .io_in_bits_perfDebugInfo_selectTime(io_in_bits_perfDebugInfo_selectTime),
    .io_in_bits_perfDebugInfo_issueTime(io_in_bits_perfDebugInfo_issueTime),
    .io_out_valid(io_out_valid),
    .io_out_bits_data_0(io_out_bits_data_0),
    .io_out_bits_data_1(io_out_bits_data_1),
    .io_out_bits_data_2(io_out_bits_data_2),
    .io_out_bits_data_3(io_out_bits_data_3),
    .io_out_bits_data_4(io_out_bits_data_4),
    .io_out_bits_pdest(io_out_bits_pdest),
    .io_out_bits_robIdx_flag(io_out_bits_robIdx_flag),
    .io_out_bits_robIdx_value(io_out_bits_robIdx_value),
    .io_out_bits_intWen(io_out_bits_intWen),
    .io_out_bits_fpWen(io_out_bits_fpWen),
    .io_out_bits_vecWen(io_out_bits_vecWen),
    .io_out_bits_v0Wen(io_out_bits_v0Wen),
    .io_out_bits_fflags(io_out_bits_fflags),
    .io_out_bits_wflags(io_out_bits_wflags),
    .io_out_bits_debugInfo_enqRsTime(io_out_bits_debugInfo_enqRsTime),
    .io_out_bits_debugInfo_selectTime(io_out_bits_debugInfo_selectTime),
    .io_out_bits_debugInfo_issueTime(io_out_bits_debugInfo_issueTime),
    .io_frm(io_frm),
    .cg_bore_cgen(cg_bore_cgen),
    .cg_bore_1_cgen(cg_bore_1_cgen),
    .cg_bore_2_cgen(cg_bore_2_cgen)
  );
endmodule
