// 自动生成:scripts/gen_exublock.py（ExuBlock）—— 勿手改(逻辑为从设计意图的可读重写)
// 可读核 xs_ExuBlock_core 端口表(golden 同名扁平端口,无 clock/reset)。
  input         io_flush_valid,
  input         io_flush_bits_robIdx_flag,
  input         [7:0] io_flush_bits_robIdx_value,
  input         io_flush_bits_ftqIdx_flag,
  input         [5:0] io_flush_bits_ftqIdx_value,
  input         [3:0] io_flush_bits_ftqOffset,
  input         io_flush_bits_level,
  input         io_flush_bits_cfiUpdate_backendIGPF,
  input         io_flush_bits_cfiUpdate_backendIPF,
  input         io_flush_bits_cfiUpdate_backendIAF,
  input         [63:0] io_flush_bits_fullTarget,
  output logic  io_in_3_1_ready,
  input         io_in_3_1_valid,
  input         [34:0] io_in_3_1_bits_fuType,
  input         [8:0] io_in_3_1_bits_fuOpType,
  input         [63:0] io_in_3_1_bits_src_0,
  input         [63:0] io_in_3_1_bits_src_1,
  input         [63:0] io_in_3_1_bits_imm,
  input         io_in_3_1_bits_robIdx_flag,
  input         [7:0] io_in_3_1_bits_robIdx_value,
  input         [7:0] io_in_3_1_bits_pdest,
  input         io_in_3_1_bits_rfWen,
  input         io_in_3_1_bits_flushPipe,
  input         io_in_3_1_bits_ftqIdx_flag,
  input         [5:0] io_in_3_1_bits_ftqIdx_value,
  input         [3:0] io_in_3_1_bits_ftqOffset,
  input         [63:0] io_in_3_1_bits_perfDebugInfo_enqRsTime,
  input         [63:0] io_in_3_1_bits_perfDebugInfo_selectTime,
  input         [63:0] io_in_3_1_bits_perfDebugInfo_issueTime,
  input         io_in_3_0_valid,
  input         [34:0] io_in_3_0_bits_fuType,
  input         [8:0] io_in_3_0_bits_fuOpType,
  input         [63:0] io_in_3_0_bits_src_0,
  input         [63:0] io_in_3_0_bits_src_1,
  input         io_in_3_0_bits_robIdx_flag,
  input         [7:0] io_in_3_0_bits_robIdx_value,
  input         [7:0] io_in_3_0_bits_pdest,
  input         io_in_3_0_bits_rfWen,
  input         [63:0] io_in_3_0_bits_perfDebugInfo_enqRsTime,
  input         [63:0] io_in_3_0_bits_perfDebugInfo_selectTime,
  input         [63:0] io_in_3_0_bits_perfDebugInfo_issueTime,
  input         io_in_2_1_valid,
  input         [34:0] io_in_2_1_bits_fuType,
  input         [8:0] io_in_2_1_bits_fuOpType,
  input         [63:0] io_in_2_1_bits_src_0,
  input         [63:0] io_in_2_1_bits_src_1,
  input         [63:0] io_in_2_1_bits_imm,
  input         [4:0] io_in_2_1_bits_nextPcOffset,
  input         io_in_2_1_bits_robIdx_flag,
  input         [7:0] io_in_2_1_bits_robIdx_value,
  input         [7:0] io_in_2_1_bits_pdest,
  input         io_in_2_1_bits_rfWen,
  input         io_in_2_1_bits_fpWen,
  input         io_in_2_1_bits_vecWen,
  input         io_in_2_1_bits_v0Wen,
  input         io_in_2_1_bits_vlWen,
  input         [1:0] io_in_2_1_bits_fpu_typeTagOut,
  input         io_in_2_1_bits_fpu_wflags,
  input         [1:0] io_in_2_1_bits_fpu_typ,
  input         [2:0] io_in_2_1_bits_fpu_rm,
  input         [49:0] io_in_2_1_bits_pc,
  input         io_in_2_1_bits_ftqIdx_flag,
  input         [5:0] io_in_2_1_bits_ftqIdx_value,
  input         [3:0] io_in_2_1_bits_ftqOffset,
  input         [49:0] io_in_2_1_bits_predictInfo_target,
  input         io_in_2_1_bits_predictInfo_taken,
  input         [63:0] io_in_2_1_bits_perfDebugInfo_enqRsTime,
  input         [63:0] io_in_2_1_bits_perfDebugInfo_selectTime,
  input         [63:0] io_in_2_1_bits_perfDebugInfo_issueTime,
  input         io_in_2_0_valid,
  input         [34:0] io_in_2_0_bits_fuType,
  input         [8:0] io_in_2_0_bits_fuOpType,
  input         [63:0] io_in_2_0_bits_src_0,
  input         [63:0] io_in_2_0_bits_src_1,
  input         io_in_2_0_bits_robIdx_flag,
  input         [7:0] io_in_2_0_bits_robIdx_value,
  input         [7:0] io_in_2_0_bits_pdest,
  input         io_in_2_0_bits_rfWen,
  input         [63:0] io_in_2_0_bits_perfDebugInfo_enqRsTime,
  input         [63:0] io_in_2_0_bits_perfDebugInfo_selectTime,
  input         [63:0] io_in_2_0_bits_perfDebugInfo_issueTime,
  input         io_in_1_1_valid,
  input         [34:0] io_in_1_1_bits_fuType,
  input         [8:0] io_in_1_1_bits_fuOpType,
  input         [63:0] io_in_1_1_bits_src_0,
  input         [63:0] io_in_1_1_bits_src_1,
  input         [63:0] io_in_1_1_bits_imm,
  input         [4:0] io_in_1_1_bits_nextPcOffset,
  input         io_in_1_1_bits_robIdx_flag,
  input         [7:0] io_in_1_1_bits_robIdx_value,
  input         [7:0] io_in_1_1_bits_pdest,
  input         io_in_1_1_bits_rfWen,
  input         [49:0] io_in_1_1_bits_pc,
  input         io_in_1_1_bits_ftqIdx_flag,
  input         [5:0] io_in_1_1_bits_ftqIdx_value,
  input         [3:0] io_in_1_1_bits_ftqOffset,
  input         [49:0] io_in_1_1_bits_predictInfo_target,
  input         io_in_1_1_bits_predictInfo_taken,
  input         [63:0] io_in_1_1_bits_perfDebugInfo_enqRsTime,
  input         [63:0] io_in_1_1_bits_perfDebugInfo_selectTime,
  input         [63:0] io_in_1_1_bits_perfDebugInfo_issueTime,
  input         io_in_1_0_valid,
  input         [34:0] io_in_1_0_bits_fuType,
  input         [8:0] io_in_1_0_bits_fuOpType,
  input         [63:0] io_in_1_0_bits_src_0,
  input         [63:0] io_in_1_0_bits_src_1,
  input         io_in_1_0_bits_robIdx_flag,
  input         [7:0] io_in_1_0_bits_robIdx_value,
  input         [7:0] io_in_1_0_bits_pdest,
  input         io_in_1_0_bits_rfWen,
  input         [63:0] io_in_1_0_bits_perfDebugInfo_enqRsTime,
  input         [63:0] io_in_1_0_bits_perfDebugInfo_selectTime,
  input         [63:0] io_in_1_0_bits_perfDebugInfo_issueTime,
  input         io_in_0_1_valid,
  input         [34:0] io_in_0_1_bits_fuType,
  input         [8:0] io_in_0_1_bits_fuOpType,
  input         [63:0] io_in_0_1_bits_src_0,
  input         [63:0] io_in_0_1_bits_src_1,
  input         [63:0] io_in_0_1_bits_imm,
  input         [4:0] io_in_0_1_bits_nextPcOffset,
  input         io_in_0_1_bits_robIdx_flag,
  input         [7:0] io_in_0_1_bits_robIdx_value,
  input         [7:0] io_in_0_1_bits_pdest,
  input         io_in_0_1_bits_rfWen,
  input         [49:0] io_in_0_1_bits_pc,
  input         io_in_0_1_bits_ftqIdx_flag,
  input         [5:0] io_in_0_1_bits_ftqIdx_value,
  input         [3:0] io_in_0_1_bits_ftqOffset,
  input         [49:0] io_in_0_1_bits_predictInfo_target,
  input         io_in_0_1_bits_predictInfo_taken,
  input         [63:0] io_in_0_1_bits_perfDebugInfo_enqRsTime,
  input         [63:0] io_in_0_1_bits_perfDebugInfo_selectTime,
  input         [63:0] io_in_0_1_bits_perfDebugInfo_issueTime,
  input         io_in_0_0_valid,
  input         [34:0] io_in_0_0_bits_fuType,
  input         [8:0] io_in_0_0_bits_fuOpType,
  input         [63:0] io_in_0_0_bits_src_0,
  input         [63:0] io_in_0_0_bits_src_1,
  input         io_in_0_0_bits_robIdx_flag,
  input         [7:0] io_in_0_0_bits_robIdx_value,
  input         [7:0] io_in_0_0_bits_pdest,
  input         io_in_0_0_bits_rfWen,
  input         [63:0] io_in_0_0_bits_perfDebugInfo_enqRsTime,
  input         [63:0] io_in_0_0_bits_perfDebugInfo_selectTime,
  input         [63:0] io_in_0_0_bits_perfDebugInfo_issueTime,
  input         io_out_3_1_ready,
  output logic  io_out_3_1_valid,
  output logic  [63:0] io_out_3_1_bits_data_1,
  output logic  [7:0] io_out_3_1_bits_pdest,
  output logic  io_out_3_1_bits_robIdx_flag,
  output logic  [7:0] io_out_3_1_bits_robIdx_value,
  output logic  io_out_3_1_bits_intWen,
  output logic  io_out_3_1_bits_redirect_valid,
  output logic  io_out_3_1_bits_redirect_bits_robIdx_flag,
  output logic  [7:0] io_out_3_1_bits_redirect_bits_robIdx_value,
  output logic  io_out_3_1_bits_redirect_bits_ftqIdx_flag,
  output logic  [5:0] io_out_3_1_bits_redirect_bits_ftqIdx_value,
  output logic  [3:0] io_out_3_1_bits_redirect_bits_ftqOffset,
  output logic  io_out_3_1_bits_redirect_bits_level,
  output logic  [49:0] io_out_3_1_bits_redirect_bits_cfiUpdate_pc,
  output logic  [49:0] io_out_3_1_bits_redirect_bits_cfiUpdate_target,
  output logic  io_out_3_1_bits_redirect_bits_cfiUpdate_taken,
  output logic  io_out_3_1_bits_redirect_bits_cfiUpdate_isMisPred,
  output logic  io_out_3_1_bits_redirect_bits_cfiUpdate_backendIGPF,
  output logic  io_out_3_1_bits_redirect_bits_cfiUpdate_backendIPF,
  output logic  io_out_3_1_bits_redirect_bits_cfiUpdate_backendIAF,
  output logic  [63:0] io_out_3_1_bits_redirect_bits_fullTarget,
  output logic  io_out_3_1_bits_exceptionVec_2,
  output logic  io_out_3_1_bits_exceptionVec_3,
  output logic  io_out_3_1_bits_exceptionVec_8,
  output logic  io_out_3_1_bits_exceptionVec_9,
  output logic  io_out_3_1_bits_exceptionVec_10,
  output logic  io_out_3_1_bits_exceptionVec_11,
  output logic  io_out_3_1_bits_exceptionVec_22,
  output logic  io_out_3_1_bits_flushPipe,
  output logic  io_out_3_1_bits_debug_isPerfCnt,
  output logic  [63:0] io_out_3_1_bits_debugInfo_enqRsTime,
  output logic  [63:0] io_out_3_1_bits_debugInfo_selectTime,
  output logic  [63:0] io_out_3_1_bits_debugInfo_issueTime,
  output logic  io_out_3_0_valid,
  output logic  [63:0] io_out_3_0_bits_data_0,
  output logic  [63:0] io_out_3_0_bits_data_1,
  output logic  [7:0] io_out_3_0_bits_pdest,
  output logic  io_out_3_0_bits_robIdx_flag,
  output logic  [7:0] io_out_3_0_bits_robIdx_value,
  output logic  io_out_3_0_bits_intWen,
  output logic  [63:0] io_out_3_0_bits_debugInfo_enqRsTime,
  output logic  [63:0] io_out_3_0_bits_debugInfo_selectTime,
  output logic  [63:0] io_out_3_0_bits_debugInfo_issueTime,
  output logic  io_out_2_1_valid,
  output logic  [127:0] io_out_2_1_bits_data_1,
  output logic  [127:0] io_out_2_1_bits_data_2,
  output logic  [127:0] io_out_2_1_bits_data_3,
  output logic  [127:0] io_out_2_1_bits_data_4,
  output logic  [127:0] io_out_2_1_bits_data_5,
  output logic  [7:0] io_out_2_1_bits_pdest,
  output logic  io_out_2_1_bits_robIdx_flag,
  output logic  [7:0] io_out_2_1_bits_robIdx_value,
  output logic  io_out_2_1_bits_intWen,
  output logic  io_out_2_1_bits_fpWen,
  output logic  io_out_2_1_bits_vecWen,
  output logic  io_out_2_1_bits_v0Wen,
  output logic  io_out_2_1_bits_vlWen,
  output logic  io_out_2_1_bits_redirect_valid,
  output logic  io_out_2_1_bits_redirect_bits_robIdx_flag,
  output logic  [7:0] io_out_2_1_bits_redirect_bits_robIdx_value,
  output logic  io_out_2_1_bits_redirect_bits_ftqIdx_flag,
  output logic  [5:0] io_out_2_1_bits_redirect_bits_ftqIdx_value,
  output logic  [3:0] io_out_2_1_bits_redirect_bits_ftqOffset,
  output logic  io_out_2_1_bits_redirect_bits_level,
  output logic  [49:0] io_out_2_1_bits_redirect_bits_cfiUpdate_pc,
  output logic  [49:0] io_out_2_1_bits_redirect_bits_cfiUpdate_target,
  output logic  io_out_2_1_bits_redirect_bits_cfiUpdate_taken,
  output logic  io_out_2_1_bits_redirect_bits_cfiUpdate_isMisPred,
  output logic  io_out_2_1_bits_redirect_bits_cfiUpdate_backendIGPF,
  output logic  io_out_2_1_bits_redirect_bits_cfiUpdate_backendIPF,
  output logic  io_out_2_1_bits_redirect_bits_cfiUpdate_backendIAF,
  output logic  [63:0] io_out_2_1_bits_redirect_bits_fullTarget,
  output logic  [4:0] io_out_2_1_bits_fflags,
  output logic  io_out_2_1_bits_wflags,
  output logic  [63:0] io_out_2_1_bits_debugInfo_enqRsTime,
  output logic  [63:0] io_out_2_1_bits_debugInfo_selectTime,
  output logic  [63:0] io_out_2_1_bits_debugInfo_issueTime,
  output logic  io_out_2_0_valid,
  output logic  [63:0] io_out_2_0_bits_data_0,
  output logic  [63:0] io_out_2_0_bits_data_1,
  output logic  [7:0] io_out_2_0_bits_pdest,
  output logic  io_out_2_0_bits_robIdx_flag,
  output logic  [7:0] io_out_2_0_bits_robIdx_value,
  output logic  io_out_2_0_bits_intWen,
  output logic  [63:0] io_out_2_0_bits_debugInfo_enqRsTime,
  output logic  [63:0] io_out_2_0_bits_debugInfo_selectTime,
  output logic  [63:0] io_out_2_0_bits_debugInfo_issueTime,
  output logic  io_out_1_1_valid,
  output logic  [63:0] io_out_1_1_bits_data_1,
  output logic  [7:0] io_out_1_1_bits_pdest,
  output logic  io_out_1_1_bits_robIdx_flag,
  output logic  [7:0] io_out_1_1_bits_robIdx_value,
  output logic  io_out_1_1_bits_intWen,
  output logic  io_out_1_1_bits_redirect_valid,
  output logic  io_out_1_1_bits_redirect_bits_robIdx_flag,
  output logic  [7:0] io_out_1_1_bits_redirect_bits_robIdx_value,
  output logic  io_out_1_1_bits_redirect_bits_ftqIdx_flag,
  output logic  [5:0] io_out_1_1_bits_redirect_bits_ftqIdx_value,
  output logic  [3:0] io_out_1_1_bits_redirect_bits_ftqOffset,
  output logic  io_out_1_1_bits_redirect_bits_level,
  output logic  [49:0] io_out_1_1_bits_redirect_bits_cfiUpdate_pc,
  output logic  [49:0] io_out_1_1_bits_redirect_bits_cfiUpdate_target,
  output logic  io_out_1_1_bits_redirect_bits_cfiUpdate_taken,
  output logic  io_out_1_1_bits_redirect_bits_cfiUpdate_isMisPred,
  output logic  io_out_1_1_bits_redirect_bits_cfiUpdate_backendIGPF,
  output logic  io_out_1_1_bits_redirect_bits_cfiUpdate_backendIPF,
  output logic  io_out_1_1_bits_redirect_bits_cfiUpdate_backendIAF,
  output logic  [63:0] io_out_1_1_bits_redirect_bits_fullTarget,
  output logic  [63:0] io_out_1_1_bits_debugInfo_enqRsTime,
  output logic  [63:0] io_out_1_1_bits_debugInfo_selectTime,
  output logic  [63:0] io_out_1_1_bits_debugInfo_issueTime,
  output logic  io_out_1_0_valid,
  output logic  [63:0] io_out_1_0_bits_data_0,
  output logic  [63:0] io_out_1_0_bits_data_1,
  output logic  [7:0] io_out_1_0_bits_pdest,
  output logic  io_out_1_0_bits_robIdx_flag,
  output logic  [7:0] io_out_1_0_bits_robIdx_value,
  output logic  io_out_1_0_bits_intWen,
  output logic  [63:0] io_out_1_0_bits_debugInfo_enqRsTime,
  output logic  [63:0] io_out_1_0_bits_debugInfo_selectTime,
  output logic  [63:0] io_out_1_0_bits_debugInfo_issueTime,
  output logic  io_out_0_1_valid,
  output logic  [63:0] io_out_0_1_bits_data_1,
  output logic  [7:0] io_out_0_1_bits_pdest,
  output logic  io_out_0_1_bits_robIdx_flag,
  output logic  [7:0] io_out_0_1_bits_robIdx_value,
  output logic  io_out_0_1_bits_intWen,
  output logic  io_out_0_1_bits_redirect_valid,
  output logic  io_out_0_1_bits_redirect_bits_robIdx_flag,
  output logic  [7:0] io_out_0_1_bits_redirect_bits_robIdx_value,
  output logic  io_out_0_1_bits_redirect_bits_ftqIdx_flag,
  output logic  [5:0] io_out_0_1_bits_redirect_bits_ftqIdx_value,
  output logic  [3:0] io_out_0_1_bits_redirect_bits_ftqOffset,
  output logic  io_out_0_1_bits_redirect_bits_level,
  output logic  [49:0] io_out_0_1_bits_redirect_bits_cfiUpdate_pc,
  output logic  [49:0] io_out_0_1_bits_redirect_bits_cfiUpdate_target,
  output logic  io_out_0_1_bits_redirect_bits_cfiUpdate_taken,
  output logic  io_out_0_1_bits_redirect_bits_cfiUpdate_isMisPred,
  output logic  io_out_0_1_bits_redirect_bits_cfiUpdate_backendIGPF,
  output logic  io_out_0_1_bits_redirect_bits_cfiUpdate_backendIPF,
  output logic  io_out_0_1_bits_redirect_bits_cfiUpdate_backendIAF,
  output logic  [63:0] io_out_0_1_bits_redirect_bits_fullTarget,
  output logic  [63:0] io_out_0_1_bits_debugInfo_enqRsTime,
  output logic  [63:0] io_out_0_1_bits_debugInfo_selectTime,
  output logic  [63:0] io_out_0_1_bits_debugInfo_issueTime,
  output logic  io_out_0_0_valid,
  output logic  [63:0] io_out_0_0_bits_data_0,
  output logic  [63:0] io_out_0_0_bits_data_1,
  output logic  [7:0] io_out_0_0_bits_pdest,
  output logic  io_out_0_0_bits_robIdx_flag,
  output logic  [7:0] io_out_0_0_bits_robIdx_value,
  output logic  io_out_0_0_bits_intWen,
  output logic  [63:0] io_out_0_0_bits_debugInfo_enqRsTime,
  output logic  [63:0] io_out_0_0_bits_debugInfo_selectTime,
  output logic  [63:0] io_out_0_0_bits_debugInfo_issueTime,
  input         [5:0] io_csrio_perf_perfEventsFrontend_0_value,
  input         [5:0] io_csrio_perf_perfEventsFrontend_1_value,
  input         [5:0] io_csrio_perf_perfEventsFrontend_2_value,
  input         [5:0] io_csrio_perf_perfEventsFrontend_3_value,
  input         [5:0] io_csrio_perf_perfEventsFrontend_4_value,
  input         [5:0] io_csrio_perf_perfEventsFrontend_5_value,
  input         [5:0] io_csrio_perf_perfEventsFrontend_6_value,
  input         [5:0] io_csrio_perf_perfEventsFrontend_7_value,
  input         [5:0] io_csrio_perf_perfEventsBackend_0_value,
  input         [5:0] io_csrio_perf_perfEventsBackend_1_value,
  input         [5:0] io_csrio_perf_perfEventsBackend_2_value,
  input         [5:0] io_csrio_perf_perfEventsBackend_3_value,
  input         [5:0] io_csrio_perf_perfEventsBackend_4_value,
  input         [5:0] io_csrio_perf_perfEventsBackend_5_value,
  input         [5:0] io_csrio_perf_perfEventsBackend_6_value,
  input         [5:0] io_csrio_perf_perfEventsBackend_7_value,
  input         [5:0] io_csrio_perf_perfEventsLsu_0_value,
  input         [5:0] io_csrio_perf_perfEventsLsu_1_value,
  input         [5:0] io_csrio_perf_perfEventsLsu_2_value,
  input         [5:0] io_csrio_perf_perfEventsLsu_3_value,
  input         [5:0] io_csrio_perf_perfEventsLsu_4_value,
  input         [5:0] io_csrio_perf_perfEventsLsu_5_value,
  input         [5:0] io_csrio_perf_perfEventsLsu_6_value,
  input         [5:0] io_csrio_perf_perfEventsLsu_7_value,
  input         [5:0] io_csrio_perf_perfEventsHc_0_value,
  input         [5:0] io_csrio_perf_perfEventsHc_1_value,
  input         [5:0] io_csrio_perf_perfEventsHc_2_value,
  input         [5:0] io_csrio_perf_perfEventsHc_3_value,
  input         [5:0] io_csrio_perf_perfEventsHc_4_value,
  input         [5:0] io_csrio_perf_perfEventsHc_5_value,
  input         [5:0] io_csrio_perf_perfEventsHc_6_value,
  input         [5:0] io_csrio_perf_perfEventsHc_7_value,
  input         [5:0] io_csrio_perf_perfEventsHc_8_value,
  input         [5:0] io_csrio_perf_perfEventsHc_9_value,
  input         [5:0] io_csrio_perf_perfEventsHc_10_value,
  input         [5:0] io_csrio_perf_perfEventsHc_11_value,
  input         [5:0] io_csrio_perf_perfEventsHc_12_value,
  input         [5:0] io_csrio_perf_perfEventsHc_13_value,
  input         [5:0] io_csrio_perf_perfEventsHc_14_value,
  input         [5:0] io_csrio_perf_perfEventsHc_15_value,
  input         [5:0] io_csrio_perf_perfEventsHc_16_value,
  input         [5:0] io_csrio_perf_perfEventsHc_17_value,
  input         [5:0] io_csrio_perf_perfEventsHc_18_value,
  input         [5:0] io_csrio_perf_perfEventsHc_19_value,
  input         [5:0] io_csrio_perf_perfEventsHc_20_value,
  input         [5:0] io_csrio_perf_perfEventsHc_21_value,
  input         [5:0] io_csrio_perf_perfEventsHc_22_value,
  input         [5:0] io_csrio_perf_perfEventsHc_23_value,
  input         [5:0] io_csrio_perf_perfEventsHc_24_value,
  input         [5:0] io_csrio_perf_perfEventsHc_25_value,
  input         [5:0] io_csrio_perf_perfEventsHc_26_value,
  input         [5:0] io_csrio_perf_perfEventsHc_27_value,
  input         [5:0] io_csrio_perf_perfEventsHc_28_value,
  input         [5:0] io_csrio_perf_perfEventsHc_29_value,
  input         [5:0] io_csrio_perf_perfEventsHc_30_value,
  input         [5:0] io_csrio_perf_perfEventsHc_31_value,
  input         [5:0] io_csrio_perf_perfEventsHc_32_value,
  input         [5:0] io_csrio_perf_perfEventsHc_33_value,
  input         [5:0] io_csrio_perf_perfEventsHc_34_value,
  input         [5:0] io_csrio_perf_perfEventsHc_35_value,
  input         [5:0] io_csrio_perf_perfEventsHc_36_value,
  input         [5:0] io_csrio_perf_perfEventsHc_37_value,
  input         [5:0] io_csrio_perf_perfEventsHc_38_value,
  input         [5:0] io_csrio_perf_perfEventsHc_39_value,
  input         [5:0] io_csrio_perf_perfEventsHc_40_value,
  input         [5:0] io_csrio_perf_perfEventsHc_41_value,
  input         [5:0] io_csrio_perf_perfEventsHc_42_value,
  input         [5:0] io_csrio_perf_perfEventsHc_43_value,
  input         [5:0] io_csrio_perf_perfEventsHc_44_value,
  input         [5:0] io_csrio_perf_perfEventsHc_45_value,
  input         [5:0] io_csrio_perf_perfEventsHc_46_value,
  input         [5:0] io_csrio_perf_perfEventsHc_47_value,
  input         [6:0] io_csrio_perf_retiredInstr,
  output logic  io_csrio_criticalErrorState,
  input         io_csrio_fpu_fflags_valid,
  input         [4:0] io_csrio_fpu_fflags_bits,
  input         io_csrio_fpu_dirty_fs,
  output logic  [2:0] io_csrio_fpu_frm,
  output logic  [63:0] io_csrio_vpu_vstart,
  output logic  [1:0] io_csrio_vpu_vxrm,
  input         [63:0] io_csrio_vpu_vl,
  input         io_csrio_vpu_set_vstart_valid,
  input         [63:0] io_csrio_vpu_set_vstart_bits,
  input         io_csrio_vpu_set_vtype_valid,
  input         [63:0] io_csrio_vpu_set_vtype_bits,
  input         io_csrio_vpu_set_vxsat_valid,
  input         io_csrio_vpu_set_vxsat_bits,
  input         io_csrio_vpu_dirty_vs,
  input         io_csrio_exception_valid,
  input         [49:0] io_csrio_exception_bits_pc,
  input         io_csrio_exception_bits_exceptionVec_0,
  input         io_csrio_exception_bits_exceptionVec_1,
  input         io_csrio_exception_bits_exceptionVec_2,
  input         io_csrio_exception_bits_exceptionVec_3,
  input         io_csrio_exception_bits_exceptionVec_4,
  input         io_csrio_exception_bits_exceptionVec_5,
  input         io_csrio_exception_bits_exceptionVec_6,
  input         io_csrio_exception_bits_exceptionVec_7,
  input         io_csrio_exception_bits_exceptionVec_8,
  input         io_csrio_exception_bits_exceptionVec_9,
  input         io_csrio_exception_bits_exceptionVec_10,
  input         io_csrio_exception_bits_exceptionVec_11,
  input         io_csrio_exception_bits_exceptionVec_12,
  input         io_csrio_exception_bits_exceptionVec_13,
  input         io_csrio_exception_bits_exceptionVec_14,
  input         io_csrio_exception_bits_exceptionVec_15,
  input         io_csrio_exception_bits_exceptionVec_16,
  input         io_csrio_exception_bits_exceptionVec_17,
  input         io_csrio_exception_bits_exceptionVec_18,
  input         io_csrio_exception_bits_exceptionVec_19,
  input         io_csrio_exception_bits_exceptionVec_20,
  input         io_csrio_exception_bits_exceptionVec_21,
  input         io_csrio_exception_bits_exceptionVec_22,
  input         io_csrio_exception_bits_exceptionVec_23,
  input         io_csrio_exception_bits_isPcBkpt,
  input         io_csrio_exception_bits_isFetchMalAddr,
  input         [63:0] io_csrio_exception_bits_gpaddr,
  input         io_csrio_exception_bits_singleStep,
  input         io_csrio_exception_bits_crossPageIPFFix,
  input         io_csrio_exception_bits_isInterrupt,
  input         io_csrio_exception_bits_isHls,
  input         [3:0] io_csrio_exception_bits_trigger,
  input         io_csrio_exception_bits_isForVSnonLeafPTE,
  input         io_csrio_robDeqPtr_flag,
  input         [7:0] io_csrio_robDeqPtr_value,
  output logic  [63:0] io_csrio_trapTarget_pc,
  output logic  io_csrio_trapTarget_raiseIPF,
  output logic  io_csrio_trapTarget_raiseIAF,
  output logic  io_csrio_trapTarget_raiseIGPF,
  output logic  io_csrio_interrupt,
  output logic  io_csrio_wfi_event,
  output logic  [63:0] io_csrio_traceCSR_cause,
  output logic  [49:0] io_csrio_traceCSR_tval,
  output logic  [2:0] io_csrio_traceCSR_lastPriv,
  output logic  [2:0] io_csrio_traceCSR_currentPriv,
  input         [63:0] io_csrio_memExceptionVAddr,
  input         [63:0] io_csrio_memExceptionGPAddr,
  input         io_csrio_memExceptionIsForVSnonLeafPTE,
  input         io_csrio_externalInterrupt_mtip,
  input         io_csrio_externalInterrupt_msip,
  input         io_csrio_externalInterrupt_meip,
  input         io_csrio_externalInterrupt_seip,
  input         io_csrio_externalInterrupt_debug,
  input         io_csrio_externalInterrupt_nmi_nmi_31,
  input         io_csrio_externalInterrupt_nmi_nmi_43,
  output logic  [3:0] io_csrio_tlb_satp_mode,
  output logic  [15:0] io_csrio_tlb_satp_asid,
  output logic  [43:0] io_csrio_tlb_satp_ppn,
  output logic  io_csrio_tlb_satp_changed,
  output logic  [3:0] io_csrio_tlb_vsatp_mode,
  output logic  [15:0] io_csrio_tlb_vsatp_asid,
  output logic  [43:0] io_csrio_tlb_vsatp_ppn,
  output logic  io_csrio_tlb_vsatp_changed,
  output logic  [3:0] io_csrio_tlb_hgatp_mode,
  output logic  [15:0] io_csrio_tlb_hgatp_vmid,
  output logic  [43:0] io_csrio_tlb_hgatp_ppn,
  output logic  io_csrio_tlb_hgatp_changed,
  output logic  io_csrio_tlb_priv_mxr,
  output logic  io_csrio_tlb_priv_sum,
  output logic  io_csrio_tlb_priv_vmxr,
  output logic  io_csrio_tlb_priv_vsum,
  output logic  io_csrio_tlb_priv_virt,
  output logic  io_csrio_tlb_priv_spvp,
  output logic  [1:0] io_csrio_tlb_priv_imode,
  output logic  [1:0] io_csrio_tlb_priv_dmode,
  output logic  io_csrio_tlb_mPBMTE,
  output logic  io_csrio_tlb_hPBMTE,
  output logic  [1:0] io_csrio_tlb_pmm_mseccfg,
  output logic  [1:0] io_csrio_tlb_pmm_menvcfg,
  output logic  [1:0] io_csrio_tlb_pmm_henvcfg,
  output logic  [1:0] io_csrio_tlb_pmm_hstatus,
  output logic  [1:0] io_csrio_tlb_pmm_senvcfg,
  output logic  io_csrio_customCtrl_pf_ctrl_l1I_pf_enable,
  output logic  io_csrio_customCtrl_pf_ctrl_l2_pf_enable,
  output logic  io_csrio_customCtrl_pf_ctrl_l1D_pf_enable,
  output logic  io_csrio_customCtrl_pf_ctrl_l1D_pf_train_on_hit,
  output logic  io_csrio_customCtrl_pf_ctrl_l1D_pf_enable_agt,
  output logic  io_csrio_customCtrl_pf_ctrl_l1D_pf_enable_pht,
  output logic  [3:0] io_csrio_customCtrl_pf_ctrl_l1D_pf_active_threshold,
  output logic  [5:0] io_csrio_customCtrl_pf_ctrl_l1D_pf_active_stride,
  output logic  io_csrio_customCtrl_pf_ctrl_l1D_pf_enable_stride,
  output logic  io_csrio_customCtrl_pf_ctrl_l2_pf_store_only,
  output logic  io_csrio_customCtrl_pf_ctrl_l2_pf_recv_enable,
  output logic  io_csrio_customCtrl_pf_ctrl_l2_pf_pbop_enable,
  output logic  io_csrio_customCtrl_pf_ctrl_l2_pf_vbop_enable,
  output logic  [4:0] io_csrio_customCtrl_lvpred_timeout,
  output logic  io_csrio_customCtrl_bp_ctrl_ubtb_enable,
  output logic  io_csrio_customCtrl_bp_ctrl_btb_enable,
  output logic  io_csrio_customCtrl_bp_ctrl_tage_enable,
  output logic  io_csrio_customCtrl_bp_ctrl_sc_enable,
  output logic  io_csrio_customCtrl_bp_ctrl_ras_enable,
  output logic  io_csrio_customCtrl_ldld_vio_check_enable,
  output logic  io_csrio_customCtrl_cache_error_enable,
  output logic  io_csrio_customCtrl_uncache_write_outstanding_enable,
  output logic  io_csrio_customCtrl_hd_misalign_st_enable,
  output logic  io_csrio_customCtrl_hd_misalign_ld_enable,
  output logic  io_csrio_customCtrl_power_down_enable,
  output logic  io_csrio_customCtrl_flush_l2_enable,
  output logic  io_csrio_customCtrl_fusion_enable,
  output logic  io_csrio_customCtrl_wfi_enable,
  output logic  io_csrio_customCtrl_distribute_csr_w_valid,
  output logic  [11:0] io_csrio_customCtrl_distribute_csr_w_bits_addr,
  output logic  [63:0] io_csrio_customCtrl_distribute_csr_w_bits_data,
  output logic  io_csrio_customCtrl_singlestep,
  output logic  io_csrio_customCtrl_frontend_trigger_tUpdate_valid,
  output logic  [1:0] io_csrio_customCtrl_frontend_trigger_tUpdate_bits_addr,
  output logic  [1:0] io_csrio_customCtrl_frontend_trigger_tUpdate_bits_tdata_matchType,
  output logic  io_csrio_customCtrl_frontend_trigger_tUpdate_bits_tdata_select,
  output logic  [3:0] io_csrio_customCtrl_frontend_trigger_tUpdate_bits_tdata_action,
  output logic  io_csrio_customCtrl_frontend_trigger_tUpdate_bits_tdata_chain,
  output logic  [63:0] io_csrio_customCtrl_frontend_trigger_tUpdate_bits_tdata_tdata2,
  output logic  io_csrio_customCtrl_frontend_trigger_tEnableVec_0,
  output logic  io_csrio_customCtrl_frontend_trigger_tEnableVec_1,
  output logic  io_csrio_customCtrl_frontend_trigger_tEnableVec_2,
  output logic  io_csrio_customCtrl_frontend_trigger_tEnableVec_3,
  output logic  io_csrio_customCtrl_frontend_trigger_debugMode,
  output logic  io_csrio_customCtrl_frontend_trigger_triggerCanRaiseBpExp,
  output logic  io_csrio_customCtrl_mem_trigger_tUpdate_valid,
  output logic  [1:0] io_csrio_customCtrl_mem_trigger_tUpdate_bits_addr,
  output logic  [1:0] io_csrio_customCtrl_mem_trigger_tUpdate_bits_tdata_matchType,
  output logic  io_csrio_customCtrl_mem_trigger_tUpdate_bits_tdata_select,
  output logic  [3:0] io_csrio_customCtrl_mem_trigger_tUpdate_bits_tdata_action,
  output logic  io_csrio_customCtrl_mem_trigger_tUpdate_bits_tdata_chain,
  output logic  io_csrio_customCtrl_mem_trigger_tUpdate_bits_tdata_store,
  output logic  io_csrio_customCtrl_mem_trigger_tUpdate_bits_tdata_load,
  output logic  [63:0] io_csrio_customCtrl_mem_trigger_tUpdate_bits_tdata_tdata2,
  output logic  io_csrio_customCtrl_mem_trigger_tEnableVec_0,
  output logic  io_csrio_customCtrl_mem_trigger_tEnableVec_1,
  output logic  io_csrio_customCtrl_mem_trigger_tEnableVec_2,
  output logic  io_csrio_customCtrl_mem_trigger_tEnableVec_3,
  output logic  io_csrio_customCtrl_mem_trigger_debugMode,
  output logic  io_csrio_customCtrl_mem_trigger_triggerCanRaiseBpExp,
  output logic  io_csrio_customCtrl_fsIsOff,
  output logic  io_csrio_instrAddrTransType_bare,
  output logic  io_csrio_instrAddrTransType_sv39,
  output logic  io_csrio_instrAddrTransType_sv39x4,
  output logic  io_csrio_instrAddrTransType_sv48,
  output logic  io_csrio_instrAddrTransType_sv48x4,
  input         [7:0] io_csrin_hartId,
  input         io_csrin_msiInfo_valid,
  input         [10:0] io_csrin_msiInfo_bits,
  input         io_csrin_criticalErrorState,
  input         io_csrin_clintTime_valid,
  input         [63:0] io_csrin_clintTime_bits,
  input         io_csrin_l2FlushDone,
  input         io_csrin_trapInstInfo_valid,
  input         [31:0] io_csrin_trapInstInfo_bits_instr,
  input         io_csrin_trapInstInfo_bits_ftqPtr_flag,
  input         [5:0] io_csrin_trapInstInfo_bits_ftqPtr_value,
  input         [3:0] io_csrin_trapInstInfo_bits_ftqOffset,
  input         io_csrin_fromVecExcpMod_busy,
  output logic  io_csrToDecode_illegalInst_sfenceVMA,
  output logic  io_csrToDecode_illegalInst_sfencePart,
  output logic  io_csrToDecode_illegalInst_hfenceGVMA,
  output logic  io_csrToDecode_illegalInst_hfenceVVMA,
  output logic  io_csrToDecode_illegalInst_hlsv,
  output logic  io_csrToDecode_illegalInst_fsIsOff,
  output logic  io_csrToDecode_illegalInst_vsIsOff,
  output logic  io_csrToDecode_illegalInst_wfi,
  output logic  io_csrToDecode_illegalInst_wrs_nto,
  output logic  io_csrToDecode_illegalInst_frm,
  output logic  io_csrToDecode_illegalInst_cboZ,
  output logic  io_csrToDecode_illegalInst_cboCF,
  output logic  io_csrToDecode_illegalInst_cboI,
  output logic  io_csrToDecode_virtualInst_sfenceVMA,
  output logic  io_csrToDecode_virtualInst_sfencePart,
  output logic  io_csrToDecode_virtualInst_hfence,
  output logic  io_csrToDecode_virtualInst_hlsv,
  output logic  io_csrToDecode_virtualInst_wfi,
  output logic  io_csrToDecode_virtualInst_wrs_nto,
  output logic  io_csrToDecode_virtualInst_cboZ,
  output logic  io_csrToDecode_virtualInst_cboCF,
  output logic  io_csrToDecode_virtualInst_cboI,
  output logic  io_csrToDecode_special_cboI2F,
  output logic  io_fenceio_sfence_valid,
  output logic  io_fenceio_sfence_bits_rs1,
  output logic  io_fenceio_sfence_bits_rs2,
  output logic  [49:0] io_fenceio_sfence_bits_addr,
  output logic  [15:0] io_fenceio_sfence_bits_id,
  output logic  io_fenceio_sfence_bits_flushPipe,
  output logic  io_fenceio_sfence_bits_hv,
  output logic  io_fenceio_sfence_bits_hg,
  output logic  io_fenceio_fencei,
  output logic  io_fenceio_sbuffer_flushSb,
  input         io_fenceio_sbuffer_sbIsEmpty,
  input         [2:0] io_frm,
  output logic  io_vtype_valid,
  output logic  io_vtype_bits_illegal,
  output logic  io_vtype_bits_vma,
  output logic  io_vtype_bits_vta,
  output logic  [1:0] io_vtype_bits_vsew,
  output logic  [2:0] io_vtype_bits_vlmul,
  output logic  io_vlIsZero,
  output logic  io_vlIsVlmax,
  output logic  io_error_0,
  input         cg_bore_cgen,
  input         cg_bore_1_cgen,
  input         cg_bore_2_cgen,
  input         cg_bore_3_cgen,
  input         cg_bore_4_cgen,
  input         cg_bore_5_cgen,
  input         cg_bore_6_cgen,
  input         cg_bore_7_cgen
