// 自动生成:scripts/gen_exublock.py（ExuBlock_2）—— 勿手改(逻辑为从设计意图的可读重写)
// 可读核 xs_ExuBlock_2_core 端口表(golden 同名扁平端口,无 clock/reset)。
  input         io_flush_valid,
  input         io_flush_bits_robIdx_flag,
  input         [7:0] io_flush_bits_robIdx_value,
  input         io_flush_bits_level,
  output logic  io_in_2_0_ready,
  input         io_in_2_0_valid,
  input         [34:0] io_in_2_0_bits_fuType,
  input         [8:0] io_in_2_0_bits_fuOpType,
  input         [127:0] io_in_2_0_bits_src_0,
  input         [127:0] io_in_2_0_bits_src_1,
  input         [127:0] io_in_2_0_bits_src_2,
  input         [127:0] io_in_2_0_bits_src_3,
  input         [127:0] io_in_2_0_bits_src_4,
  input         io_in_2_0_bits_robIdx_flag,
  input         [7:0] io_in_2_0_bits_robIdx_value,
  input         [6:0] io_in_2_0_bits_pdest,
  input         io_in_2_0_bits_vecWen,
  input         io_in_2_0_bits_v0Wen,
  input         io_in_2_0_bits_fpu_wflags,
  input         io_in_2_0_bits_vpu_vma,
  input         io_in_2_0_bits_vpu_vta,
  input         [1:0] io_in_2_0_bits_vpu_vsew,
  input         [2:0] io_in_2_0_bits_vpu_vlmul,
  input         io_in_2_0_bits_vpu_vm,
  input         [7:0] io_in_2_0_bits_vpu_vstart,
  input         [6:0] io_in_2_0_bits_vpu_vuopIdx,
  input         io_in_2_0_bits_vpu_isNarrow,
  input         io_in_2_0_bits_vpu_isDstMask,
  input         [63:0] io_in_2_0_bits_perfDebugInfo_enqRsTime,
  input         [63:0] io_in_2_0_bits_perfDebugInfo_selectTime,
  input         [63:0] io_in_2_0_bits_perfDebugInfo_issueTime,
  input         io_in_1_1_valid,
  input         [34:0] io_in_1_1_bits_fuType,
  input         [8:0] io_in_1_1_bits_fuOpType,
  input         [127:0] io_in_1_1_bits_src_0,
  input         [127:0] io_in_1_1_bits_src_1,
  input         [127:0] io_in_1_1_bits_src_2,
  input         [127:0] io_in_1_1_bits_src_3,
  input         [127:0] io_in_1_1_bits_src_4,
  input         io_in_1_1_bits_robIdx_flag,
  input         [7:0] io_in_1_1_bits_robIdx_value,
  input         [7:0] io_in_1_1_bits_pdest,
  input         io_in_1_1_bits_fpWen,
  input         io_in_1_1_bits_vecWen,
  input         io_in_1_1_bits_v0Wen,
  input         io_in_1_1_bits_fpu_wflags,
  input         io_in_1_1_bits_vpu_vma,
  input         io_in_1_1_bits_vpu_vta,
  input         [1:0] io_in_1_1_bits_vpu_vsew,
  input         [2:0] io_in_1_1_bits_vpu_vlmul,
  input         io_in_1_1_bits_vpu_vm,
  input         [7:0] io_in_1_1_bits_vpu_vstart,
  input         io_in_1_1_bits_vpu_fpu_isFoldTo1_2,
  input         io_in_1_1_bits_vpu_fpu_isFoldTo1_4,
  input         io_in_1_1_bits_vpu_fpu_isFoldTo1_8,
  input         [6:0] io_in_1_1_bits_vpu_vuopIdx,
  input         io_in_1_1_bits_vpu_lastUop,
  input         io_in_1_1_bits_vpu_isNarrow,
  input         io_in_1_1_bits_vpu_isDstMask,
  input         [63:0] io_in_1_1_bits_perfDebugInfo_enqRsTime,
  input         [63:0] io_in_1_1_bits_perfDebugInfo_selectTime,
  input         [63:0] io_in_1_1_bits_perfDebugInfo_issueTime,
  input         io_in_1_0_valid,
  input         [34:0] io_in_1_0_bits_fuType,
  input         [8:0] io_in_1_0_bits_fuOpType,
  input         [127:0] io_in_1_0_bits_src_0,
  input         [127:0] io_in_1_0_bits_src_1,
  input         [127:0] io_in_1_0_bits_src_2,
  input         [127:0] io_in_1_0_bits_src_3,
  input         [127:0] io_in_1_0_bits_src_4,
  input         io_in_1_0_bits_robIdx_flag,
  input         [7:0] io_in_1_0_bits_robIdx_value,
  input         [6:0] io_in_1_0_bits_pdest,
  input         io_in_1_0_bits_vecWen,
  input         io_in_1_0_bits_v0Wen,
  input         io_in_1_0_bits_fpu_wflags,
  input         io_in_1_0_bits_vpu_vma,
  input         io_in_1_0_bits_vpu_vta,
  input         [1:0] io_in_1_0_bits_vpu_vsew,
  input         [2:0] io_in_1_0_bits_vpu_vlmul,
  input         io_in_1_0_bits_vpu_vm,
  input         [7:0] io_in_1_0_bits_vpu_vstart,
  input         [6:0] io_in_1_0_bits_vpu_vuopIdx,
  input         io_in_1_0_bits_vpu_isExt,
  input         io_in_1_0_bits_vpu_isNarrow,
  input         io_in_1_0_bits_vpu_isDstMask,
  input         io_in_1_0_bits_vpu_isOpMask,
  input         [63:0] io_in_1_0_bits_perfDebugInfo_enqRsTime,
  input         [63:0] io_in_1_0_bits_perfDebugInfo_selectTime,
  input         [63:0] io_in_1_0_bits_perfDebugInfo_issueTime,
  input         io_in_0_1_valid,
  input         [34:0] io_in_0_1_bits_fuType,
  input         [8:0] io_in_0_1_bits_fuOpType,
  input         [127:0] io_in_0_1_bits_src_0,
  input         [127:0] io_in_0_1_bits_src_1,
  input         [127:0] io_in_0_1_bits_src_2,
  input         [127:0] io_in_0_1_bits_src_3,
  input         [127:0] io_in_0_1_bits_src_4,
  input         io_in_0_1_bits_robIdx_flag,
  input         [7:0] io_in_0_1_bits_robIdx_value,
  input         [7:0] io_in_0_1_bits_pdest,
  input         io_in_0_1_bits_rfWen,
  input         io_in_0_1_bits_fpWen,
  input         io_in_0_1_bits_vecWen,
  input         io_in_0_1_bits_v0Wen,
  input         io_in_0_1_bits_vlWen,
  input         io_in_0_1_bits_fpu_wflags,
  input         io_in_0_1_bits_vpu_vma,
  input         io_in_0_1_bits_vpu_vta,
  input         [1:0] io_in_0_1_bits_vpu_vsew,
  input         [2:0] io_in_0_1_bits_vpu_vlmul,
  input         io_in_0_1_bits_vpu_vm,
  input         [7:0] io_in_0_1_bits_vpu_vstart,
  input         io_in_0_1_bits_vpu_fpu_isFoldTo1_2,
  input         io_in_0_1_bits_vpu_fpu_isFoldTo1_4,
  input         io_in_0_1_bits_vpu_fpu_isFoldTo1_8,
  input         [6:0] io_in_0_1_bits_vpu_vuopIdx,
  input         io_in_0_1_bits_vpu_lastUop,
  input         io_in_0_1_bits_vpu_isNarrow,
  input         io_in_0_1_bits_vpu_isDstMask,
  input         [63:0] io_in_0_1_bits_perfDebugInfo_enqRsTime,
  input         [63:0] io_in_0_1_bits_perfDebugInfo_selectTime,
  input         [63:0] io_in_0_1_bits_perfDebugInfo_issueTime,
  input         io_in_0_0_valid,
  input         [34:0] io_in_0_0_bits_fuType,
  input         [8:0] io_in_0_0_bits_fuOpType,
  input         [127:0] io_in_0_0_bits_src_0,
  input         [127:0] io_in_0_0_bits_src_1,
  input         [127:0] io_in_0_0_bits_src_2,
  input         [127:0] io_in_0_0_bits_src_3,
  input         [127:0] io_in_0_0_bits_src_4,
  input         io_in_0_0_bits_robIdx_flag,
  input         [7:0] io_in_0_0_bits_robIdx_value,
  input         [6:0] io_in_0_0_bits_pdest,
  input         io_in_0_0_bits_vecWen,
  input         io_in_0_0_bits_v0Wen,
  input         io_in_0_0_bits_fpu_wflags,
  input         io_in_0_0_bits_vpu_vma,
  input         io_in_0_0_bits_vpu_vta,
  input         [1:0] io_in_0_0_bits_vpu_vsew,
  input         [2:0] io_in_0_0_bits_vpu_vlmul,
  input         io_in_0_0_bits_vpu_vm,
  input         [7:0] io_in_0_0_bits_vpu_vstart,
  input         [6:0] io_in_0_0_bits_vpu_vuopIdx,
  input         io_in_0_0_bits_vpu_isExt,
  input         io_in_0_0_bits_vpu_isNarrow,
  input         io_in_0_0_bits_vpu_isDstMask,
  input         io_in_0_0_bits_vpu_isOpMask,
  input         [63:0] io_in_0_0_bits_perfDebugInfo_enqRsTime,
  input         [63:0] io_in_0_0_bits_perfDebugInfo_selectTime,
  input         [63:0] io_in_0_0_bits_perfDebugInfo_issueTime,
  input         io_out_2_0_ready,
  output logic  io_out_2_0_valid,
  output logic  [127:0] io_out_2_0_bits_data_1,
  output logic  [127:0] io_out_2_0_bits_data_2,
  output logic  [6:0] io_out_2_0_bits_pdest,
  output logic  io_out_2_0_bits_robIdx_flag,
  output logic  [7:0] io_out_2_0_bits_robIdx_value,
  output logic  io_out_2_0_bits_vecWen,
  output logic  io_out_2_0_bits_v0Wen,
  output logic  [4:0] io_out_2_0_bits_fflags,
  output logic  io_out_2_0_bits_wflags,
  output logic  [63:0] io_out_2_0_bits_debugInfo_enqRsTime,
  output logic  [63:0] io_out_2_0_bits_debugInfo_selectTime,
  output logic  [63:0] io_out_2_0_bits_debugInfo_issueTime,
  output logic  io_out_1_1_valid,
  output logic  [127:0] io_out_1_1_bits_data_1,
  output logic  [127:0] io_out_1_1_bits_data_2,
  output logic  [127:0] io_out_1_1_bits_data_3,
  output logic  [7:0] io_out_1_1_bits_pdest,
  output logic  io_out_1_1_bits_robIdx_flag,
  output logic  [7:0] io_out_1_1_bits_robIdx_value,
  output logic  io_out_1_1_bits_fpWen,
  output logic  io_out_1_1_bits_vecWen,
  output logic  io_out_1_1_bits_v0Wen,
  output logic  [4:0] io_out_1_1_bits_fflags,
  output logic  io_out_1_1_bits_wflags,
  output logic  [63:0] io_out_1_1_bits_debugInfo_enqRsTime,
  output logic  [63:0] io_out_1_1_bits_debugInfo_selectTime,
  output logic  [63:0] io_out_1_1_bits_debugInfo_issueTime,
  output logic  io_out_1_0_valid,
  output logic  [127:0] io_out_1_0_bits_data_1,
  output logic  [127:0] io_out_1_0_bits_data_2,
  output logic  [6:0] io_out_1_0_bits_pdest,
  output logic  io_out_1_0_bits_robIdx_flag,
  output logic  [7:0] io_out_1_0_bits_robIdx_value,
  output logic  io_out_1_0_bits_vecWen,
  output logic  io_out_1_0_bits_v0Wen,
  output logic  [4:0] io_out_1_0_bits_fflags,
  output logic  io_out_1_0_bits_wflags,
  output logic  io_out_1_0_bits_vxsat,
  output logic  [63:0] io_out_1_0_bits_debugInfo_enqRsTime,
  output logic  [63:0] io_out_1_0_bits_debugInfo_selectTime,
  output logic  [63:0] io_out_1_0_bits_debugInfo_issueTime,
  output logic  io_out_0_1_valid,
  output logic  [127:0] io_out_0_1_bits_data_1,
  output logic  [127:0] io_out_0_1_bits_data_2,
  output logic  [127:0] io_out_0_1_bits_data_3,
  output logic  [127:0] io_out_0_1_bits_data_4,
  output logic  [127:0] io_out_0_1_bits_data_5,
  output logic  [7:0] io_out_0_1_bits_pdest,
  output logic  io_out_0_1_bits_robIdx_flag,
  output logic  [7:0] io_out_0_1_bits_robIdx_value,
  output logic  io_out_0_1_bits_intWen,
  output logic  io_out_0_1_bits_fpWen,
  output logic  io_out_0_1_bits_vecWen,
  output logic  io_out_0_1_bits_v0Wen,
  output logic  io_out_0_1_bits_vlWen,
  output logic  [4:0] io_out_0_1_bits_fflags,
  output logic  io_out_0_1_bits_wflags,
  output logic  io_out_0_1_bits_exceptionVec_2,
  output logic  [63:0] io_out_0_1_bits_debugInfo_enqRsTime,
  output logic  [63:0] io_out_0_1_bits_debugInfo_selectTime,
  output logic  [63:0] io_out_0_1_bits_debugInfo_issueTime,
  output logic  io_out_0_0_valid,
  output logic  [127:0] io_out_0_0_bits_data_1,
  output logic  [127:0] io_out_0_0_bits_data_2,
  output logic  [6:0] io_out_0_0_bits_pdest,
  output logic  io_out_0_0_bits_robIdx_flag,
  output logic  [7:0] io_out_0_0_bits_robIdx_value,
  output logic  io_out_0_0_bits_vecWen,
  output logic  io_out_0_0_bits_v0Wen,
  output logic  [4:0] io_out_0_0_bits_fflags,
  output logic  io_out_0_0_bits_wflags,
  output logic  io_out_0_0_bits_vxsat,
  output logic  io_out_0_0_bits_exceptionVec_2,
  output logic  [63:0] io_out_0_0_bits_debugInfo_enqRsTime,
  output logic  [63:0] io_out_0_0_bits_debugInfo_selectTime,
  output logic  [63:0] io_out_0_0_bits_debugInfo_issueTime,
  input         [2:0] io_frm,
  input         [1:0] io_vxrm,
  output logic  io_vtype_valid,
  output logic  io_vtype_bits_illegal,
  output logic  io_vtype_bits_vma,
  output logic  io_vtype_bits_vta,
  output logic  [1:0] io_vtype_bits_vsew,
  output logic  [2:0] io_vtype_bits_vlmul,
  output logic  io_vlIsZero,
  output logic  io_vlIsVlmax,
  input         cg_bore_cgen,
  input         cg_bore_1_cgen,
  input         cg_bore_2_cgen,
  input         cg_bore_3_cgen,
  input         cg_bore_4_cgen,
  input         cg_bore_5_cgen,
  input         cg_bore_6_cgen,
  input         cg_bore_7_cgen,
  input         cg_bore_8_cgen,
  input         cg_bore_9_cgen,
  input         cg_bore_10_cgen,
  input         cg_bore_11_cgen
