// NewCSR Iprio AUX wrapper (Iprio2Module_1). Single-module copy from newcsr_iprio_wrappers.sv
// (generated by scripts/gen_newcsr_iprio.py). Thin wrapper over readable
// primitive xs_iprio_ext / xs_iprio6 (rtl/backend/newcsr_iprio.sv).
// FM-verified against golden Iprio2Module_1.sv in signoff-strict mode.
// Wrapper file committed per pilot铁律 — required for independent AUX FM.
module Iprio2Module_1(
  input         clock,
  input         reset,
  input         w_wen,
  input  [63:0] w_wdata,
  output [63:0] rdata,
  input         sie_SSIE,
  input         sie_STIE,
  input         sie_SEIE,
  input         sie_LCOFIE,
  input         sie_LC14IE,
  input         sie_LC15IE,
  input         sie_LC16IE,
  input         sie_LC17IE,
  input         sie_LC18IE,
  input         sie_LC19IE,
  input         sie_LC20IE,
  input         sie_LC21IE,
  input         sie_LC22IE,
  input         sie_LC23IE,
  input         sie_LC24IE,
  input         sie_LC25IE,
  input         sie_LC26IE,
  input         sie_LC27IE,
  input         sie_LC28IE,
  input         sie_LC29IE,
  input         sie_LC30IE,
  input         sie_LC31IE,
  input         sie_LC32IE,
  input         sie_LC33IE,
  input         sie_LC34IE,
  input         sie_LPRASEIE,
  input         sie_LC36IE,
  input         sie_LC37IE,
  input         sie_LC38IE,
  input         sie_LC39IE,
  input         sie_LC40IE,
  input         sie_LC41IE,
  input         sie_LC42IE,
  input         sie_HPRASEIE,
  input         sie_LC44IE,
  input         sie_LC45IE,
  input         sie_LC46IE,
  input         sie_LC47IE,
  input         sie_LC48IE,
  input         sie_LC49IE,
  input         sie_LC50IE,
  input         sie_LC51IE,
  input         sie_LC52IE,
  input         sie_LC53IE,
  input         sie_LC54IE,
  input         sie_LC55IE,
  input         sie_LC56IE,
  input         sie_LC57IE,
  input         sie_LC58IE,
  input         sie_LC59IE,
  input         sie_LC60IE,
  input         sie_LC61IE,
  input         sie_LC62IE,
  input         sie_LC63IE
);
  wire [7:0] r0, r1, r2, r3, r4, r5; // VSEI MEI SGEI LCOFI Prio14 Prio15
  xs_iprio6 #(
    .WOFF0(16),
    .WOFF1(24),
    .WOFF2(32),
    .WOFF3(40),
    .WOFF4(48),
    .WOFF5(56)
  ) u_core (
    .clock (clock),
    .reset (reset),
    .w_wen (w_wen),
    .w_wdata (w_wdata),
    .reg0 (r0), .reg1 (r1), .reg2 (r2),
    .reg3 (r3), .reg4 (r4), .reg5 (r5)
  );
  wire [7:0] g_LCOFI  = r3 & {8{sie_LCOFIE}};
  wire [7:0] g_Prio14 = r4 & {8{sie_LC14IE}};
  wire [7:0] g_Prio15 = r5 & {8{sie_LC15IE}};
  assign rdata = {g_Prio15, g_Prio14, g_LCOFI, 40'h0};
endmodule
