// NewCSR Iprio AUX wrapper (Iprio0Module). Single-module copy from newcsr_iprio_wrappers.sv
// (generated by scripts/gen_newcsr_iprio.py). Thin wrapper over readable
// primitive xs_iprio_ext / xs_iprio6 (rtl/backend/newcsr_iprio.sv).
// FM-verified against golden Iprio0Module.sv in signoff-strict mode.
// Wrapper file committed per pilot铁律 — required for independent AUX FM.
module Iprio0Module(
  input         clock,
  input         reset,
  input         w_wen,
  input  [63:0] w_wdata,
  output [63:0] rdata,
  input         mie_SSIE,
  input         mie_VSSIE,
  input         mie_MSIE,
  input         mie_STIE,
  input         mie_VSTIE,
  input         mie_MTIE,
  input         mie_SEIE,
  input         mie_VSEIE,
  input         mie_MEIE,
  input         mie_SGEIE,
  input         mie_LCOFIE
);
  wire [7:0] r0, r1, r2, r3, r4, r5; // SSI VSSI MSI STI VSTI MTI
  xs_iprio6 #(
    .WOFF0(8),
    .WOFF1(16),
    .WOFF2(24),
    .WOFF3(40),
    .WOFF4(48),
    .WOFF5(56)
  ) u_core (
    .clock (clock),
    .reset (reset),
    .w_wen (w_wen),
    .w_wdata (w_wdata),
    .reg0 (r0), .reg1 (r1), .reg2 (r2),
    .reg3 (r3), .reg4 (r4), .reg5 (r5)
  );
  wire [7:0] g_SSI  = r0 & {8{mie_SSIE}};
  wire [7:0] g_VSSI = r1 & {8{mie_VSSIE}};
  wire [7:0] g_MSI  = r2 & {8{mie_MSIE}};
  wire [7:0] g_STI  = r3 & {8{mie_STIE}};
  wire [7:0] g_VSTI = r4 & {8{mie_VSTIE}};
  wire [7:0] g_MTI  = r5 & {8{mie_MTIE}};
  assign rdata = {g_MTI, g_VSTI, g_STI, 8'h0, g_MSI, g_VSSI, g_SSI, 8'h0};
endmodule
