// NewCSR PMA family AUX wrappers (34 golden modules).
// GENERATED by scripts/gen_newcsr_pma.py. Thin wrappers over the readable
// primitives in rtl/backend/newcsr_pma.sv, binding golden per-instance ports.
// FM-verified per module in signoff-strict mode (no blackbox / no dont_verify).

// ===== Pmacfg{0,2}Module: 64-bit read slice of packed 128-bit PMA cfg bus =====
module Pmacfg0Module(
  output [63:0]  rdata,
  input  [127:0] cfgRData
);
  xs_pmacfg_slice #(.HI(1'b0)) u_core (.rdata(rdata), .cfgRData(cfgRData));
endmodule

// ===== Pmacfg{0,2}Module: 64-bit read slice of packed 128-bit PMA cfg bus =====
module Pmacfg2Module(
  output [63:0]  rdata,
  input  [127:0] cfgRData
);
  xs_pmacfg_slice #(.HI(1'b1)) u_core (.rdata(rdata), .cfgRData(cfgRData));
endmodule

// ===== Pmaaddr{0..15}Module: pass-through per-entry addr read =====
module Pmaaddr0Module(
  output [63:0] rdata,
  input  [63:0] addrRData_0
);
  xs_pmaaddr u_core (.rdata(rdata), .addr_rdata(addrRData_0));
endmodule

module Pmaaddr1Module(
  output [63:0] rdata,
  input  [63:0] addrRData_1
);
  xs_pmaaddr u_core (.rdata(rdata), .addr_rdata(addrRData_1));
endmodule

module Pmaaddr2Module(
  output [63:0] rdata,
  input  [63:0] addrRData_2
);
  xs_pmaaddr u_core (.rdata(rdata), .addr_rdata(addrRData_2));
endmodule

module Pmaaddr3Module(
  output [63:0] rdata,
  input  [63:0] addrRData_3
);
  xs_pmaaddr u_core (.rdata(rdata), .addr_rdata(addrRData_3));
endmodule

module Pmaaddr4Module(
  output [63:0] rdata,
  input  [63:0] addrRData_4
);
  xs_pmaaddr u_core (.rdata(rdata), .addr_rdata(addrRData_4));
endmodule

module Pmaaddr5Module(
  output [63:0] rdata,
  input  [63:0] addrRData_5
);
  xs_pmaaddr u_core (.rdata(rdata), .addr_rdata(addrRData_5));
endmodule

module Pmaaddr6Module(
  output [63:0] rdata,
  input  [63:0] addrRData_6
);
  xs_pmaaddr u_core (.rdata(rdata), .addr_rdata(addrRData_6));
endmodule

module Pmaaddr7Module(
  output [63:0] rdata,
  input  [63:0] addrRData_7
);
  xs_pmaaddr u_core (.rdata(rdata), .addr_rdata(addrRData_7));
endmodule

module Pmaaddr8Module(
  output [63:0] rdata,
  input  [63:0] addrRData_8
);
  xs_pmaaddr u_core (.rdata(rdata), .addr_rdata(addrRData_8));
endmodule

module Pmaaddr9Module(
  output [63:0] rdata,
  input  [63:0] addrRData_9
);
  xs_pmaaddr u_core (.rdata(rdata), .addr_rdata(addrRData_9));
endmodule

module Pmaaddr10Module(
  output [63:0] rdata,
  input  [63:0] addrRData_10
);
  xs_pmaaddr u_core (.rdata(rdata), .addr_rdata(addrRData_10));
endmodule

module Pmaaddr11Module(
  output [63:0] rdata,
  input  [63:0] addrRData_11
);
  xs_pmaaddr u_core (.rdata(rdata), .addr_rdata(addrRData_11));
endmodule

module Pmaaddr12Module(
  output [63:0] rdata,
  input  [63:0] addrRData_12
);
  xs_pmaaddr u_core (.rdata(rdata), .addr_rdata(addrRData_12));
endmodule

module Pmaaddr13Module(
  output [63:0] rdata,
  input  [63:0] addrRData_13
);
  xs_pmaaddr u_core (.rdata(rdata), .addr_rdata(addrRData_13));
endmodule

module Pmaaddr14Module(
  output [63:0] rdata,
  input  [63:0] addrRData_14
);
  xs_pmaaddr u_core (.rdata(rdata), .addr_rdata(addrRData_14));
endmodule

module Pmaaddr15Module(
  output [63:0] rdata,
  input  [63:0] addrRData_15
);
  xs_pmaaddr u_core (.rdata(rdata), .addr_rdata(addrRData_15));
endmodule

// ===== Pma{0..15}cfgModule: config-entry register (per-index reset) =====
module Pma0cfgModule(
  input         clock,
  input         reset,
  input         w_wen,
  input  [63:0] w_wdata,
  output [7:0]  rdata,
  output        regOut_R,
  output        regOut_W,
  output        regOut_X,
  output [1:0]  regOut_A,
  output        regOut_ATOMIC,
  output        regOut_C,
  output        regOut_L
);
  xs_pmacfg_entry #(.RESET_VAL(8'h00)) u_core (
    .clock(clock), .reset(reset), .w_wen(w_wen), .w_wdata(w_wdata),
    .rdata(rdata), .regOut_R(regOut_R), .regOut_W(regOut_W), .regOut_X(regOut_X),
    .regOut_A(regOut_A), .regOut_ATOMIC(regOut_ATOMIC), .regOut_C(regOut_C),
    .regOut_L(regOut_L));
endmodule

module Pma1cfgModule(
  input         clock,
  input         reset,
  input         w_wen,
  input  [63:0] w_wdata,
  output [7:0]  rdata,
  output        regOut_R,
  output        regOut_W,
  output        regOut_X,
  output [1:0]  regOut_A,
  output        regOut_ATOMIC,
  output        regOut_C,
  output        regOut_L
);
  xs_pmacfg_entry #(.RESET_VAL(8'h00)) u_core (
    .clock(clock), .reset(reset), .w_wen(w_wen), .w_wdata(w_wdata),
    .rdata(rdata), .regOut_R(regOut_R), .regOut_W(regOut_W), .regOut_X(regOut_X),
    .regOut_A(regOut_A), .regOut_ATOMIC(regOut_ATOMIC), .regOut_C(regOut_C),
    .regOut_L(regOut_L));
endmodule

module Pma2cfgModule(
  input         clock,
  input         reset,
  input         w_wen,
  input  [63:0] w_wdata,
  output [7:0]  rdata,
  output        regOut_R,
  output        regOut_W,
  output        regOut_X,
  output [1:0]  regOut_A,
  output        regOut_ATOMIC,
  output        regOut_C,
  output        regOut_L
);
  xs_pmacfg_entry #(.RESET_VAL(8'h00)) u_core (
    .clock(clock), .reset(reset), .w_wen(w_wen), .w_wdata(w_wdata),
    .rdata(rdata), .regOut_R(regOut_R), .regOut_W(regOut_W), .regOut_X(regOut_X),
    .regOut_A(regOut_A), .regOut_ATOMIC(regOut_ATOMIC), .regOut_C(regOut_C),
    .regOut_L(regOut_L));
endmodule

module Pma3cfgModule(
  input         clock,
  input         reset,
  input         w_wen,
  input  [63:0] w_wdata,
  output [7:0]  rdata,
  output        regOut_R,
  output        regOut_W,
  output        regOut_X,
  output [1:0]  regOut_A,
  output        regOut_ATOMIC,
  output        regOut_C,
  output        regOut_L
);
  xs_pmacfg_entry #(.RESET_VAL(8'h0B)) u_core (
    .clock(clock), .reset(reset), .w_wen(w_wen), .w_wdata(w_wdata),
    .rdata(rdata), .regOut_R(regOut_R), .regOut_W(regOut_W), .regOut_X(regOut_X),
    .regOut_A(regOut_A), .regOut_ATOMIC(regOut_ATOMIC), .regOut_C(regOut_C),
    .regOut_L(regOut_L));
endmodule

module Pma4cfgModule(
  input         clock,
  input         reset,
  input         w_wen,
  input  [63:0] w_wdata,
  output [7:0]  rdata,
  output        regOut_R,
  output        regOut_W,
  output        regOut_X,
  output [1:0]  regOut_A,
  output        regOut_ATOMIC,
  output        regOut_C,
  output        regOut_L
);
  xs_pmacfg_entry #(.RESET_VAL(8'h0F)) u_core (
    .clock(clock), .reset(reset), .w_wen(w_wen), .w_wdata(w_wdata),
    .rdata(rdata), .regOut_R(regOut_R), .regOut_W(regOut_W), .regOut_X(regOut_X),
    .regOut_A(regOut_A), .regOut_ATOMIC(regOut_ATOMIC), .regOut_C(regOut_C),
    .regOut_L(regOut_L));
endmodule

module Pma5cfgModule(
  input         clock,
  input         reset,
  input         w_wen,
  input  [63:0] w_wdata,
  output [7:0]  rdata,
  output        regOut_R,
  output        regOut_W,
  output        regOut_X,
  output [1:0]  regOut_A,
  output        regOut_ATOMIC,
  output        regOut_C,
  output        regOut_L
);
  xs_pmacfg_entry #(.RESET_VAL(8'h0B)) u_core (
    .clock(clock), .reset(reset), .w_wen(w_wen), .w_wdata(w_wdata),
    .rdata(rdata), .regOut_R(regOut_R), .regOut_W(regOut_W), .regOut_X(regOut_X),
    .regOut_A(regOut_A), .regOut_ATOMIC(regOut_ATOMIC), .regOut_C(regOut_C),
    .regOut_L(regOut_L));
endmodule

module Pma6cfgModule(
  input         clock,
  input         reset,
  input         w_wen,
  input  [63:0] w_wdata,
  output [7:0]  rdata,
  output        regOut_R,
  output        regOut_W,
  output        regOut_X,
  output [1:0]  regOut_A,
  output        regOut_ATOMIC,
  output        regOut_C,
  output        regOut_L
);
  xs_pmacfg_entry #(.RESET_VAL(8'h0B)) u_core (
    .clock(clock), .reset(reset), .w_wen(w_wen), .w_wdata(w_wdata),
    .rdata(rdata), .regOut_R(regOut_R), .regOut_W(regOut_W), .regOut_X(regOut_X),
    .regOut_A(regOut_A), .regOut_ATOMIC(regOut_ATOMIC), .regOut_C(regOut_C),
    .regOut_L(regOut_L));
endmodule

module Pma7cfgModule(
  input         clock,
  input         reset,
  input         w_wen,
  input  [63:0] w_wdata,
  output [7:0]  rdata,
  output        regOut_R,
  output        regOut_W,
  output        regOut_X,
  output [1:0]  regOut_A,
  output        regOut_ATOMIC,
  output        regOut_C,
  output        regOut_L
);
  xs_pmacfg_entry #(.RESET_VAL(8'h0B)) u_core (
    .clock(clock), .reset(reset), .w_wen(w_wen), .w_wdata(w_wdata),
    .rdata(rdata), .regOut_R(regOut_R), .regOut_W(regOut_W), .regOut_X(regOut_X),
    .regOut_A(regOut_A), .regOut_ATOMIC(regOut_ATOMIC), .regOut_C(regOut_C),
    .regOut_L(regOut_L));
endmodule

module Pma8cfgModule(
  input         clock,
  input         reset,
  input         w_wen,
  input  [63:0] w_wdata,
  output [7:0]  rdata,
  output        regOut_R,
  output        regOut_W,
  output        regOut_X,
  output [1:0]  regOut_A,
  output        regOut_ATOMIC,
  output        regOut_C,
  output        regOut_L
);
  xs_pmacfg_entry #(.RESET_VAL(8'h0F)) u_core (
    .clock(clock), .reset(reset), .w_wen(w_wen), .w_wdata(w_wdata),
    .rdata(rdata), .regOut_R(regOut_R), .regOut_W(regOut_W), .regOut_X(regOut_X),
    .regOut_A(regOut_A), .regOut_ATOMIC(regOut_ATOMIC), .regOut_C(regOut_C),
    .regOut_L(regOut_L));
endmodule

module Pma9cfgModule(
  input         clock,
  input         reset,
  input         w_wen,
  input  [63:0] w_wdata,
  output [7:0]  rdata,
  output        regOut_R,
  output        regOut_W,
  output        regOut_X,
  output [1:0]  regOut_A,
  output        regOut_ATOMIC,
  output        regOut_C,
  output        regOut_L
);
  xs_pmacfg_entry #(.RESET_VAL(8'h0B)) u_core (
    .clock(clock), .reset(reset), .w_wen(w_wen), .w_wdata(w_wdata),
    .rdata(rdata), .regOut_R(regOut_R), .regOut_W(regOut_W), .regOut_X(regOut_X),
    .regOut_A(regOut_A), .regOut_ATOMIC(regOut_ATOMIC), .regOut_C(regOut_C),
    .regOut_L(regOut_L));
endmodule

module Pma10cfgModule(
  input         clock,
  input         reset,
  input         w_wen,
  input  [63:0] w_wdata,
  output [7:0]  rdata,
  output        regOut_R,
  output        regOut_W,
  output        regOut_X,
  output [1:0]  regOut_A,
  output        regOut_ATOMIC,
  output        regOut_C,
  output        regOut_L
);
  xs_pmacfg_entry #(.RESET_VAL(8'h0B)) u_core (
    .clock(clock), .reset(reset), .w_wen(w_wen), .w_wdata(w_wdata),
    .rdata(rdata), .regOut_R(regOut_R), .regOut_W(regOut_W), .regOut_X(regOut_X),
    .regOut_A(regOut_A), .regOut_ATOMIC(regOut_ATOMIC), .regOut_C(regOut_C),
    .regOut_L(regOut_L));
endmodule

module Pma11cfgModule(
  input         clock,
  input         reset,
  input         w_wen,
  input  [63:0] w_wdata,
  output [7:0]  rdata,
  output        regOut_R,
  output        regOut_W,
  output        regOut_X,
  output [1:0]  regOut_A,
  output        regOut_ATOMIC,
  output        regOut_C,
  output        regOut_L
);
  xs_pmacfg_entry #(.RESET_VAL(8'h0B)) u_core (
    .clock(clock), .reset(reset), .w_wen(w_wen), .w_wdata(w_wdata),
    .rdata(rdata), .regOut_R(regOut_R), .regOut_W(regOut_W), .regOut_X(regOut_X),
    .regOut_A(regOut_A), .regOut_ATOMIC(regOut_ATOMIC), .regOut_C(regOut_C),
    .regOut_L(regOut_L));
endmodule

module Pma12cfgModule(
  input         clock,
  input         reset,
  input         w_wen,
  input  [63:0] w_wdata,
  output [7:0]  rdata,
  output        regOut_R,
  output        regOut_W,
  output        regOut_X,
  output [1:0]  regOut_A,
  output        regOut_ATOMIC,
  output        regOut_C,
  output        regOut_L
);
  xs_pmacfg_entry #(.RESET_VAL(8'h08)) u_core (
    .clock(clock), .reset(reset), .w_wen(w_wen), .w_wdata(w_wdata),
    .rdata(rdata), .regOut_R(regOut_R), .regOut_W(regOut_W), .regOut_X(regOut_X),
    .regOut_A(regOut_A), .regOut_ATOMIC(regOut_ATOMIC), .regOut_C(regOut_C),
    .regOut_L(regOut_L));
endmodule

module Pma13cfgModule(
  input         clock,
  input         reset,
  input         w_wen,
  input  [63:0] w_wdata,
  output [7:0]  rdata,
  output        regOut_R,
  output        regOut_W,
  output        regOut_X,
  output [1:0]  regOut_A,
  output        regOut_ATOMIC,
  output        regOut_C,
  output        regOut_L
);
  xs_pmacfg_entry #(.RESET_VAL(8'h0B)) u_core (
    .clock(clock), .reset(reset), .w_wen(w_wen), .w_wdata(w_wdata),
    .rdata(rdata), .regOut_R(regOut_R), .regOut_W(regOut_W), .regOut_X(regOut_X),
    .regOut_A(regOut_A), .regOut_ATOMIC(regOut_ATOMIC), .regOut_C(regOut_C),
    .regOut_L(regOut_L));
endmodule

module Pma14cfgModule(
  input         clock,
  input         reset,
  input         w_wen,
  input  [63:0] w_wdata,
  output [7:0]  rdata,
  output        regOut_R,
  output        regOut_W,
  output        regOut_X,
  output [1:0]  regOut_A,
  output        regOut_ATOMIC,
  output        regOut_C,
  output        regOut_L
);
  xs_pmacfg_entry #(.RESET_VAL(8'h6F)) u_core (
    .clock(clock), .reset(reset), .w_wen(w_wen), .w_wdata(w_wdata),
    .rdata(rdata), .regOut_R(regOut_R), .regOut_W(regOut_W), .regOut_X(regOut_X),
    .regOut_A(regOut_A), .regOut_ATOMIC(regOut_ATOMIC), .regOut_C(regOut_C),
    .regOut_L(regOut_L));
endmodule

module Pma15cfgModule(
  input         clock,
  input         reset,
  input         w_wen,
  input  [63:0] w_wdata,
  output [7:0]  rdata,
  output        regOut_R,
  output        regOut_W,
  output        regOut_X,
  output [1:0]  regOut_A,
  output        regOut_ATOMIC,
  output        regOut_C,
  output        regOut_L
);
  xs_pmacfg_entry #(.RESET_VAL(8'h18)) u_core (
    .clock(clock), .reset(reset), .w_wen(w_wen), .w_wdata(w_wdata),
    .rdata(rdata), .regOut_R(regOut_R), .regOut_W(regOut_W), .regOut_X(regOut_X),
    .regOut_A(regOut_A), .regOut_ATOMIC(regOut_ATOMIC), .regOut_C(regOut_C),
    .regOut_L(regOut_L));
endmodule

