// NewCSR MipModule AUX wrapper (bespoke). Thin wrapper over the readable
// primitive xs_mip (rtl/backend/newcsr_mip.sv). FM-verified strict.
module MipModule(
  input         clock,
  input         reset,
  input         w_wen,
  input  [63:0] w_wdata,
  output [63:0] rdata,
  output        regOut_SSIP,
  output        regOut_VSSIP,
  output        regOut_MSIP,
  output        regOut_STIP,
  output        regOut_VSTIP,
  output        regOut_MTIP,
  output        regOut_SEIP,
  output        regOut_VSEIP,
  output        regOut_MEIP,
  output        regOut_SGEIP,
  output        regOut_LCOFIP,
  output        rdataFields_SSIP,
  output        rdataFields_VSSIP,
  output        rdataFields_MSIP,
  output        rdataFields_STIP,
  output        rdataFields_VSTIP,
  output        rdataFields_MTIP,
  output        rdataFields_SEIP,
  output        rdataFields_VSEIP,
  output        rdataFields_MEIP,
  output        rdataFields_SGEIP,
  output        rdataFields_LCOFIP,
  input         mvip_SEIP,
  input         mvien_SEIE,
  input         hvip_VSSIP,
  input         hvip_VSTIP,
  input         hvip_VSEIP,
  input  [4:0]  hgeip_ip,
  input  [4:0]  hgeie_ie,
  input  [5:0]  hstatusVGEIN,
  input         platformIRP_MEIP,
  input         platformIRP_MTIP,
  input         platformIRP_MSIP,
  input         platformIRP_SEIP,
  input         platformIRP_STIP,
  input         platformIRP_VSTIP,
  input         menvcfg_STCE,
  input         lcofiReq,
  input         aiaToCSR_meip,
  input         aiaToCSR_seip,
  input         fromMvip_SSIP_valid,
  input         fromMvip_SSIP_bits,
  input         fromMvip_STIP_valid,
  input         fromMvip_STIP_bits,
  input         fromSip_SSIP_valid,
  input         fromSip_SSIP_bits,
  input         fromSip_LCOFIP_valid,
  input         fromSip_LCOFIP_bits,
  input         fromVSip_LCOFIP_valid,
  input         fromVSip_LCOFIP_bits,
  output        toMvip_SEIP_valid,
  output        toMvip_SEIP_bits,
  output        toHvip_VSSIP_valid,
  output        toHvip_VSSIP_bits
);
  xs_mip u_core (
    .clock(clock), .reset(reset), .w_wen(w_wen), .w_wdata(w_wdata), .rdata(rdata),
    .regOut_SSIP(regOut_SSIP), .regOut_VSSIP(regOut_VSSIP), .regOut_MSIP(regOut_MSIP),
    .regOut_STIP(regOut_STIP), .regOut_VSTIP(regOut_VSTIP), .regOut_MTIP(regOut_MTIP),
    .regOut_SEIP(regOut_SEIP), .regOut_VSEIP(regOut_VSEIP), .regOut_MEIP(regOut_MEIP),
    .regOut_SGEIP(regOut_SGEIP), .regOut_LCOFIP(regOut_LCOFIP),
    .rdataFields_SSIP(rdataFields_SSIP), .rdataFields_VSSIP(rdataFields_VSSIP),
    .rdataFields_MSIP(rdataFields_MSIP), .rdataFields_STIP(rdataFields_STIP),
    .rdataFields_VSTIP(rdataFields_VSTIP), .rdataFields_MTIP(rdataFields_MTIP),
    .rdataFields_SEIP(rdataFields_SEIP), .rdataFields_VSEIP(rdataFields_VSEIP),
    .rdataFields_MEIP(rdataFields_MEIP), .rdataFields_SGEIP(rdataFields_SGEIP),
    .rdataFields_LCOFIP(rdataFields_LCOFIP),
    .mvip_SEIP(mvip_SEIP), .mvien_SEIE(mvien_SEIE), .hvip_VSSIP(hvip_VSSIP),
    .hvip_VSTIP(hvip_VSTIP), .hvip_VSEIP(hvip_VSEIP), .hgeip_ip(hgeip_ip),
    .hgeie_ie(hgeie_ie), .hstatusVGEIN(hstatusVGEIN),
    .platformIRP_MEIP(platformIRP_MEIP), .platformIRP_MTIP(platformIRP_MTIP),
    .platformIRP_MSIP(platformIRP_MSIP), .platformIRP_SEIP(platformIRP_SEIP),
    .platformIRP_STIP(platformIRP_STIP), .platformIRP_VSTIP(platformIRP_VSTIP),
    .menvcfg_STCE(menvcfg_STCE), .lcofiReq(lcofiReq),
    .aiaToCSR_meip(aiaToCSR_meip), .aiaToCSR_seip(aiaToCSR_seip),
    .fromMvip_SSIP_valid(fromMvip_SSIP_valid), .fromMvip_SSIP_bits(fromMvip_SSIP_bits),
    .fromMvip_STIP_valid(fromMvip_STIP_valid), .fromMvip_STIP_bits(fromMvip_STIP_bits),
    .fromSip_SSIP_valid(fromSip_SSIP_valid), .fromSip_SSIP_bits(fromSip_SSIP_bits),
    .fromSip_LCOFIP_valid(fromSip_LCOFIP_valid), .fromSip_LCOFIP_bits(fromSip_LCOFIP_bits),
    .fromVSip_LCOFIP_valid(fromVSip_LCOFIP_valid), .fromVSip_LCOFIP_bits(fromVSip_LCOFIP_bits),
    .toMvip_SEIP_valid(toMvip_SEIP_valid), .toMvip_SEIP_bits(toMvip_SEIP_bits),
    .toHvip_VSSIP_valid(toHvip_VSSIP_valid), .toHvip_VSSIP_bits(toHvip_VSSIP_bits));
endmodule
