// 本文件由 scripts/gen_regcache.py 生成:RegCache 两半区的黑盒子模块例化。
// 黑盒:RegCacheDataModule(_1)/RegCacheAgeTimer(_1)/RegCacheAgeDetector(_1)。
// 三角 ageInfo 在核内用一维数组 age_int[120]/age_mem[66] 表达,这里映射到扁平端口。

  RegCacheDataModule IntRegCache (
    .clock(clock), .reset(reset),
    .io_readPorts_0_ren (IntRegCache_rd_ren[0]),
    .io_readPorts_0_addr(IntRegCache_rd_addr[0]),
    .io_readPorts_0_data(IntRegCache_rd_data[0]),
    .io_readPorts_1_ren (IntRegCache_rd_ren[1]),
    .io_readPorts_1_addr(IntRegCache_rd_addr[1]),
    .io_readPorts_1_data(IntRegCache_rd_data[1]),
    .io_readPorts_2_ren (IntRegCache_rd_ren[2]),
    .io_readPorts_2_addr(IntRegCache_rd_addr[2]),
    .io_readPorts_2_data(IntRegCache_rd_data[2]),
    .io_readPorts_3_ren (IntRegCache_rd_ren[3]),
    .io_readPorts_3_addr(IntRegCache_rd_addr[3]),
    .io_readPorts_3_data(IntRegCache_rd_data[3]),
    .io_readPorts_4_ren (IntRegCache_rd_ren[4]),
    .io_readPorts_4_addr(IntRegCache_rd_addr[4]),
    .io_readPorts_4_data(IntRegCache_rd_data[4]),
    .io_readPorts_5_ren (IntRegCache_rd_ren[5]),
    .io_readPorts_5_addr(IntRegCache_rd_addr[5]),
    .io_readPorts_5_data(IntRegCache_rd_data[5]),
    .io_readPorts_6_ren (IntRegCache_rd_ren[6]),
    .io_readPorts_6_addr(IntRegCache_rd_addr[6]),
    .io_readPorts_6_data(IntRegCache_rd_data[6]),
    .io_readPorts_7_ren (IntRegCache_rd_ren[7]),
    .io_readPorts_7_addr(IntRegCache_rd_addr[7]),
    .io_readPorts_7_data(IntRegCache_rd_data[7]),
    .io_readPorts_8_ren (IntRegCache_rd_ren[8]),
    .io_readPorts_8_addr(IntRegCache_rd_addr[8]),
    .io_readPorts_8_data(IntRegCache_rd_data[8]),
    .io_readPorts_9_ren (IntRegCache_rd_ren[9]),
    .io_readPorts_9_addr(IntRegCache_rd_addr[9]),
    .io_readPorts_9_data(IntRegCache_rd_data[9]),
    .io_readPorts_10_ren (IntRegCache_rd_ren[10]),
    .io_readPorts_10_addr(IntRegCache_rd_addr[10]),
    .io_readPorts_10_data(IntRegCache_rd_data[10]),
    .io_readPorts_11_ren (IntRegCache_rd_ren[11]),
    .io_readPorts_11_addr(IntRegCache_rd_addr[11]),
    .io_readPorts_11_data(IntRegCache_rd_data[11]),
    .io_readPorts_12_ren (IntRegCache_rd_ren[12]),
    .io_readPorts_12_addr(IntRegCache_rd_addr[12]),
    .io_readPorts_12_data(IntRegCache_rd_data[12]),
    .io_readPorts_13_ren (IntRegCache_rd_ren[13]),
    .io_readPorts_13_addr(IntRegCache_rd_addr[13]),
    .io_readPorts_13_data(IntRegCache_rd_data[13]),
    .io_readPorts_14_ren (IntRegCache_rd_ren[14]),
    .io_readPorts_14_addr(IntRegCache_rd_addr[14]),
    .io_readPorts_14_data(IntRegCache_rd_data[14]),
    .io_readPorts_15_ren (IntRegCache_rd_ren[15]),
    .io_readPorts_15_addr(IntRegCache_rd_addr[15]),
    .io_readPorts_15_data(IntRegCache_rd_data[15]),
    .io_readPorts_16_ren (IntRegCache_rd_ren[16]),
    .io_readPorts_16_addr(IntRegCache_rd_addr[16]),
    .io_readPorts_16_data(IntRegCache_rd_data[16]),
    .io_readPorts_17_ren (IntRegCache_rd_ren[17]),
    .io_readPorts_17_addr(IntRegCache_rd_addr[17]),
    .io_readPorts_17_data(IntRegCache_rd_data[17]),
    .io_readPorts_18_ren (IntRegCache_rd_ren[18]),
    .io_readPorts_18_addr(IntRegCache_rd_addr[18]),
    .io_readPorts_18_data(IntRegCache_rd_data[18]),
    .io_readPorts_19_ren (IntRegCache_rd_ren[19]),
    .io_readPorts_19_addr(IntRegCache_rd_addr[19]),
    .io_readPorts_19_data(IntRegCache_rd_data[19]),
    .io_readPorts_20_ren (IntRegCache_rd_ren[20]),
    .io_readPorts_20_addr(IntRegCache_rd_addr[20]),
    .io_readPorts_20_data(IntRegCache_rd_data[20]),
    .io_readPorts_21_ren (IntRegCache_rd_ren[21]),
    .io_readPorts_21_addr(IntRegCache_rd_addr[21]),
    .io_readPorts_21_data(IntRegCache_rd_data[21]),
    .io_readPorts_22_ren (IntRegCache_rd_ren[22]),
    .io_readPorts_22_addr(IntRegCache_rd_addr[22]),
    .io_readPorts_22_data(IntRegCache_rd_data[22]),
    .io_writePorts_0_wen (IntRegCache_wr_wen[0]),
    .io_writePorts_0_addr(IntRegCache_wr_addr[0]),
    .io_writePorts_0_data(IntRegCache_wr_data[0]),
    .io_writePorts_1_wen (IntRegCache_wr_wen[1]),
    .io_writePorts_1_addr(IntRegCache_wr_addr[1]),
    .io_writePorts_1_data(IntRegCache_wr_data[1]),
    .io_writePorts_2_wen (IntRegCache_wr_wen[2]),
    .io_writePorts_2_addr(IntRegCache_wr_addr[2]),
    .io_writePorts_2_data(IntRegCache_wr_data[2]),
    .io_writePorts_3_wen (IntRegCache_wr_wen[3]),
    .io_writePorts_3_addr(IntRegCache_wr_addr[3]),
    .io_writePorts_3_data(IntRegCache_wr_data[3]),
    .io_validInfo_0(IntRegCache_valid[0]), .io_validInfo_1(IntRegCache_valid[1]), .io_validInfo_2(IntRegCache_valid[2]), .io_validInfo_3(IntRegCache_valid[3]), .io_validInfo_4(IntRegCache_valid[4]), .io_validInfo_5(IntRegCache_valid[5]), .io_validInfo_6(IntRegCache_valid[6]), .io_validInfo_7(IntRegCache_valid[7]), .io_validInfo_8(IntRegCache_valid[8]), .io_validInfo_9(IntRegCache_valid[9]), .io_validInfo_10(IntRegCache_valid[10]), .io_validInfo_11(IntRegCache_valid[11]), .io_validInfo_12(IntRegCache_valid[12]), .io_validInfo_13(IntRegCache_valid[13]), .io_validInfo_14(IntRegCache_valid[14]), .io_validInfo_15(IntRegCache_valid[15])
  );

  RegCacheAgeTimer IntRegCache_age_timer (
    .clock(clock), .reset(reset),
    .io_readPorts_0_ren (IntRegCache_rd_ren[0]),
    .io_readPorts_0_addr(IntRegCache_rd_addr[0]),
    .io_readPorts_1_ren (IntRegCache_rd_ren[1]),
    .io_readPorts_1_addr(IntRegCache_rd_addr[1]),
    .io_readPorts_2_ren (IntRegCache_rd_ren[2]),
    .io_readPorts_2_addr(IntRegCache_rd_addr[2]),
    .io_readPorts_3_ren (IntRegCache_rd_ren[3]),
    .io_readPorts_3_addr(IntRegCache_rd_addr[3]),
    .io_readPorts_4_ren (IntRegCache_rd_ren[4]),
    .io_readPorts_4_addr(IntRegCache_rd_addr[4]),
    .io_readPorts_5_ren (IntRegCache_rd_ren[5]),
    .io_readPorts_5_addr(IntRegCache_rd_addr[5]),
    .io_readPorts_6_ren (IntRegCache_rd_ren[6]),
    .io_readPorts_6_addr(IntRegCache_rd_addr[6]),
    .io_readPorts_7_ren (IntRegCache_rd_ren[7]),
    .io_readPorts_7_addr(IntRegCache_rd_addr[7]),
    .io_readPorts_8_ren (IntRegCache_rd_ren[8]),
    .io_readPorts_8_addr(IntRegCache_rd_addr[8]),
    .io_readPorts_9_ren (IntRegCache_rd_ren[9]),
    .io_readPorts_9_addr(IntRegCache_rd_addr[9]),
    .io_readPorts_10_ren (IntRegCache_rd_ren[10]),
    .io_readPorts_10_addr(IntRegCache_rd_addr[10]),
    .io_readPorts_11_ren (IntRegCache_rd_ren[11]),
    .io_readPorts_11_addr(IntRegCache_rd_addr[11]),
    .io_readPorts_12_ren (IntRegCache_rd_ren[12]),
    .io_readPorts_12_addr(IntRegCache_rd_addr[12]),
    .io_readPorts_13_ren (IntRegCache_rd_ren[13]),
    .io_readPorts_13_addr(IntRegCache_rd_addr[13]),
    .io_readPorts_14_ren (IntRegCache_rd_ren[14]),
    .io_readPorts_14_addr(IntRegCache_rd_addr[14]),
    .io_readPorts_15_ren (IntRegCache_rd_ren[15]),
    .io_readPorts_15_addr(IntRegCache_rd_addr[15]),
    .io_readPorts_16_ren (IntRegCache_rd_ren[16]),
    .io_readPorts_16_addr(IntRegCache_rd_addr[16]),
    .io_readPorts_17_ren (IntRegCache_rd_ren[17]),
    .io_readPorts_17_addr(IntRegCache_rd_addr[17]),
    .io_readPorts_18_ren (IntRegCache_rd_ren[18]),
    .io_readPorts_18_addr(IntRegCache_rd_addr[18]),
    .io_readPorts_19_ren (IntRegCache_rd_ren[19]),
    .io_readPorts_19_addr(IntRegCache_rd_addr[19]),
    .io_readPorts_20_ren (IntRegCache_rd_ren[20]),
    .io_readPorts_20_addr(IntRegCache_rd_addr[20]),
    .io_readPorts_21_ren (IntRegCache_rd_ren[21]),
    .io_readPorts_21_addr(IntRegCache_rd_addr[21]),
    .io_readPorts_22_ren (IntRegCache_rd_ren[22]),
    .io_readPorts_22_addr(IntRegCache_rd_addr[22]),
    .io_writePorts_0_wen (IntRegCache_wr_wen[0]),
    .io_writePorts_0_addr(IntRegCache_wr_addr[0]),
    .io_writePorts_1_wen (IntRegCache_wr_wen[1]),
    .io_writePorts_1_addr(IntRegCache_wr_addr[1]),
    .io_writePorts_2_wen (IntRegCache_wr_wen[2]),
    .io_writePorts_2_addr(IntRegCache_wr_addr[2]),
    .io_writePorts_3_wen (IntRegCache_wr_wen[3]),
    .io_writePorts_3_addr(IntRegCache_wr_addr[3]),
    .io_validInfo_0(IntRegCache_valid[0]),
    .io_validInfo_1(IntRegCache_valid[1]),
    .io_validInfo_2(IntRegCache_valid[2]),
    .io_validInfo_3(IntRegCache_valid[3]),
    .io_validInfo_4(IntRegCache_valid[4]),
    .io_validInfo_5(IntRegCache_valid[5]),
    .io_validInfo_6(IntRegCache_valid[6]),
    .io_validInfo_7(IntRegCache_valid[7]),
    .io_validInfo_8(IntRegCache_valid[8]),
    .io_validInfo_9(IntRegCache_valid[9]),
    .io_validInfo_10(IntRegCache_valid[10]),
    .io_validInfo_11(IntRegCache_valid[11]),
    .io_validInfo_12(IntRegCache_valid[12]),
    .io_validInfo_13(IntRegCache_valid[13]),
    .io_validInfo_14(IntRegCache_valid[14]),
    .io_validInfo_15(IntRegCache_valid[15]),
    .io_ageInfo_0_1(age_int[0]), .io_ageInfo_0_2(age_int[1]), .io_ageInfo_0_3(age_int[2]), .io_ageInfo_0_4(age_int[3]), .io_ageInfo_0_5(age_int[4]), .io_ageInfo_0_6(age_int[5]), .io_ageInfo_0_7(age_int[6]), .io_ageInfo_0_8(age_int[7]), .io_ageInfo_0_9(age_int[8]), .io_ageInfo_0_10(age_int[9]), .io_ageInfo_0_11(age_int[10]), .io_ageInfo_0_12(age_int[11]), .io_ageInfo_0_13(age_int[12]), .io_ageInfo_0_14(age_int[13]), .io_ageInfo_0_15(age_int[14]), .io_ageInfo_1_2(age_int[15]), .io_ageInfo_1_3(age_int[16]), .io_ageInfo_1_4(age_int[17]), .io_ageInfo_1_5(age_int[18]), .io_ageInfo_1_6(age_int[19]), .io_ageInfo_1_7(age_int[20]), .io_ageInfo_1_8(age_int[21]), .io_ageInfo_1_9(age_int[22]), .io_ageInfo_1_10(age_int[23]), .io_ageInfo_1_11(age_int[24]), .io_ageInfo_1_12(age_int[25]), .io_ageInfo_1_13(age_int[26]), .io_ageInfo_1_14(age_int[27]), .io_ageInfo_1_15(age_int[28]), .io_ageInfo_2_3(age_int[29]), .io_ageInfo_2_4(age_int[30]), .io_ageInfo_2_5(age_int[31]), .io_ageInfo_2_6(age_int[32]), .io_ageInfo_2_7(age_int[33]), .io_ageInfo_2_8(age_int[34]), .io_ageInfo_2_9(age_int[35]), .io_ageInfo_2_10(age_int[36]), .io_ageInfo_2_11(age_int[37]), .io_ageInfo_2_12(age_int[38]), .io_ageInfo_2_13(age_int[39]), .io_ageInfo_2_14(age_int[40]), .io_ageInfo_2_15(age_int[41]), .io_ageInfo_3_4(age_int[42]), .io_ageInfo_3_5(age_int[43]), .io_ageInfo_3_6(age_int[44]), .io_ageInfo_3_7(age_int[45]), .io_ageInfo_3_8(age_int[46]), .io_ageInfo_3_9(age_int[47]), .io_ageInfo_3_10(age_int[48]), .io_ageInfo_3_11(age_int[49]), .io_ageInfo_3_12(age_int[50]), .io_ageInfo_3_13(age_int[51]), .io_ageInfo_3_14(age_int[52]), .io_ageInfo_3_15(age_int[53]), .io_ageInfo_4_5(age_int[54]), .io_ageInfo_4_6(age_int[55]), .io_ageInfo_4_7(age_int[56]), .io_ageInfo_4_8(age_int[57]), .io_ageInfo_4_9(age_int[58]), .io_ageInfo_4_10(age_int[59]), .io_ageInfo_4_11(age_int[60]), .io_ageInfo_4_12(age_int[61]), .io_ageInfo_4_13(age_int[62]), .io_ageInfo_4_14(age_int[63]), .io_ageInfo_4_15(age_int[64]), .io_ageInfo_5_6(age_int[65]), .io_ageInfo_5_7(age_int[66]), .io_ageInfo_5_8(age_int[67]), .io_ageInfo_5_9(age_int[68]), .io_ageInfo_5_10(age_int[69]), .io_ageInfo_5_11(age_int[70]), .io_ageInfo_5_12(age_int[71]), .io_ageInfo_5_13(age_int[72]), .io_ageInfo_5_14(age_int[73]), .io_ageInfo_5_15(age_int[74]), .io_ageInfo_6_7(age_int[75]), .io_ageInfo_6_8(age_int[76]), .io_ageInfo_6_9(age_int[77]), .io_ageInfo_6_10(age_int[78]), .io_ageInfo_6_11(age_int[79]), .io_ageInfo_6_12(age_int[80]), .io_ageInfo_6_13(age_int[81]), .io_ageInfo_6_14(age_int[82]), .io_ageInfo_6_15(age_int[83]), .io_ageInfo_7_8(age_int[84]), .io_ageInfo_7_9(age_int[85]), .io_ageInfo_7_10(age_int[86]), .io_ageInfo_7_11(age_int[87]), .io_ageInfo_7_12(age_int[88]), .io_ageInfo_7_13(age_int[89]), .io_ageInfo_7_14(age_int[90]), .io_ageInfo_7_15(age_int[91]), .io_ageInfo_8_9(age_int[92]), .io_ageInfo_8_10(age_int[93]), .io_ageInfo_8_11(age_int[94]), .io_ageInfo_8_12(age_int[95]), .io_ageInfo_8_13(age_int[96]), .io_ageInfo_8_14(age_int[97]), .io_ageInfo_8_15(age_int[98]), .io_ageInfo_9_10(age_int[99]), .io_ageInfo_9_11(age_int[100]), .io_ageInfo_9_12(age_int[101]), .io_ageInfo_9_13(age_int[102]), .io_ageInfo_9_14(age_int[103]), .io_ageInfo_9_15(age_int[104]), .io_ageInfo_10_11(age_int[105]), .io_ageInfo_10_12(age_int[106]), .io_ageInfo_10_13(age_int[107]), .io_ageInfo_10_14(age_int[108]), .io_ageInfo_10_15(age_int[109]), .io_ageInfo_11_12(age_int[110]), .io_ageInfo_11_13(age_int[111]), .io_ageInfo_11_14(age_int[112]), .io_ageInfo_11_15(age_int[113]), .io_ageInfo_12_13(age_int[114]), .io_ageInfo_12_14(age_int[115]), .io_ageInfo_12_15(age_int[116]), .io_ageInfo_13_14(age_int[117]), .io_ageInfo_13_15(age_int[118]), .io_ageInfo_14_15(age_int[119])
  );

  RegCacheAgeDetector IntRegCache_rep (
    .clock(clock), .reset(reset),
    .io_ageInfo_0_1(age_int[0]), .io_ageInfo_0_2(age_int[1]), .io_ageInfo_0_3(age_int[2]), .io_ageInfo_0_4(age_int[3]), .io_ageInfo_0_5(age_int[4]), .io_ageInfo_0_6(age_int[5]), .io_ageInfo_0_7(age_int[6]), .io_ageInfo_0_8(age_int[7]), .io_ageInfo_0_9(age_int[8]), .io_ageInfo_0_10(age_int[9]), .io_ageInfo_0_11(age_int[10]), .io_ageInfo_0_12(age_int[11]), .io_ageInfo_0_13(age_int[12]), .io_ageInfo_0_14(age_int[13]), .io_ageInfo_0_15(age_int[14]), .io_ageInfo_1_2(age_int[15]), .io_ageInfo_1_3(age_int[16]), .io_ageInfo_1_4(age_int[17]), .io_ageInfo_1_5(age_int[18]), .io_ageInfo_1_6(age_int[19]), .io_ageInfo_1_7(age_int[20]), .io_ageInfo_1_8(age_int[21]), .io_ageInfo_1_9(age_int[22]), .io_ageInfo_1_10(age_int[23]), .io_ageInfo_1_11(age_int[24]), .io_ageInfo_1_12(age_int[25]), .io_ageInfo_1_13(age_int[26]), .io_ageInfo_1_14(age_int[27]), .io_ageInfo_1_15(age_int[28]), .io_ageInfo_2_3(age_int[29]), .io_ageInfo_2_4(age_int[30]), .io_ageInfo_2_5(age_int[31]), .io_ageInfo_2_6(age_int[32]), .io_ageInfo_2_7(age_int[33]), .io_ageInfo_2_8(age_int[34]), .io_ageInfo_2_9(age_int[35]), .io_ageInfo_2_10(age_int[36]), .io_ageInfo_2_11(age_int[37]), .io_ageInfo_2_12(age_int[38]), .io_ageInfo_2_13(age_int[39]), .io_ageInfo_2_14(age_int[40]), .io_ageInfo_2_15(age_int[41]), .io_ageInfo_3_4(age_int[42]), .io_ageInfo_3_5(age_int[43]), .io_ageInfo_3_6(age_int[44]), .io_ageInfo_3_7(age_int[45]), .io_ageInfo_3_8(age_int[46]), .io_ageInfo_3_9(age_int[47]), .io_ageInfo_3_10(age_int[48]), .io_ageInfo_3_11(age_int[49]), .io_ageInfo_3_12(age_int[50]), .io_ageInfo_3_13(age_int[51]), .io_ageInfo_3_14(age_int[52]), .io_ageInfo_3_15(age_int[53]), .io_ageInfo_4_5(age_int[54]), .io_ageInfo_4_6(age_int[55]), .io_ageInfo_4_7(age_int[56]), .io_ageInfo_4_8(age_int[57]), .io_ageInfo_4_9(age_int[58]), .io_ageInfo_4_10(age_int[59]), .io_ageInfo_4_11(age_int[60]), .io_ageInfo_4_12(age_int[61]), .io_ageInfo_4_13(age_int[62]), .io_ageInfo_4_14(age_int[63]), .io_ageInfo_4_15(age_int[64]), .io_ageInfo_5_6(age_int[65]), .io_ageInfo_5_7(age_int[66]), .io_ageInfo_5_8(age_int[67]), .io_ageInfo_5_9(age_int[68]), .io_ageInfo_5_10(age_int[69]), .io_ageInfo_5_11(age_int[70]), .io_ageInfo_5_12(age_int[71]), .io_ageInfo_5_13(age_int[72]), .io_ageInfo_5_14(age_int[73]), .io_ageInfo_5_15(age_int[74]), .io_ageInfo_6_7(age_int[75]), .io_ageInfo_6_8(age_int[76]), .io_ageInfo_6_9(age_int[77]), .io_ageInfo_6_10(age_int[78]), .io_ageInfo_6_11(age_int[79]), .io_ageInfo_6_12(age_int[80]), .io_ageInfo_6_13(age_int[81]), .io_ageInfo_6_14(age_int[82]), .io_ageInfo_6_15(age_int[83]), .io_ageInfo_7_8(age_int[84]), .io_ageInfo_7_9(age_int[85]), .io_ageInfo_7_10(age_int[86]), .io_ageInfo_7_11(age_int[87]), .io_ageInfo_7_12(age_int[88]), .io_ageInfo_7_13(age_int[89]), .io_ageInfo_7_14(age_int[90]), .io_ageInfo_7_15(age_int[91]), .io_ageInfo_8_9(age_int[92]), .io_ageInfo_8_10(age_int[93]), .io_ageInfo_8_11(age_int[94]), .io_ageInfo_8_12(age_int[95]), .io_ageInfo_8_13(age_int[96]), .io_ageInfo_8_14(age_int[97]), .io_ageInfo_8_15(age_int[98]), .io_ageInfo_9_10(age_int[99]), .io_ageInfo_9_11(age_int[100]), .io_ageInfo_9_12(age_int[101]), .io_ageInfo_9_13(age_int[102]), .io_ageInfo_9_14(age_int[103]), .io_ageInfo_9_15(age_int[104]), .io_ageInfo_10_11(age_int[105]), .io_ageInfo_10_12(age_int[106]), .io_ageInfo_10_13(age_int[107]), .io_ageInfo_10_14(age_int[108]), .io_ageInfo_10_15(age_int[109]), .io_ageInfo_11_12(age_int[110]), .io_ageInfo_11_13(age_int[111]), .io_ageInfo_11_14(age_int[112]), .io_ageInfo_11_15(age_int[113]), .io_ageInfo_12_13(age_int[114]), .io_ageInfo_12_14(age_int[115]), .io_ageInfo_12_15(age_int[116]), .io_ageInfo_13_14(age_int[117]), .io_ageInfo_13_15(age_int[118]), .io_ageInfo_14_15(age_int[119]),
    .io_out_0(rep_int[0]), .io_out_1(rep_int[1]), .io_out_2(rep_int[2]), .io_out_3(rep_int[3])
  );

  RegCacheDataModule_1 MemRegCache (
    .clock(clock), .reset(reset),
    .io_readPorts_0_ren (MemRegCache_rd_ren[0]),
    .io_readPorts_0_addr(MemRegCache_rd_addr[0]),
    .io_readPorts_0_data(MemRegCache_rd_data[0]),
    .io_readPorts_1_ren (MemRegCache_rd_ren[1]),
    .io_readPorts_1_addr(MemRegCache_rd_addr[1]),
    .io_readPorts_1_data(MemRegCache_rd_data[1]),
    .io_readPorts_2_ren (MemRegCache_rd_ren[2]),
    .io_readPorts_2_addr(MemRegCache_rd_addr[2]),
    .io_readPorts_2_data(MemRegCache_rd_data[2]),
    .io_readPorts_3_ren (MemRegCache_rd_ren[3]),
    .io_readPorts_3_addr(MemRegCache_rd_addr[3]),
    .io_readPorts_3_data(MemRegCache_rd_data[3]),
    .io_readPorts_4_ren (MemRegCache_rd_ren[4]),
    .io_readPorts_4_addr(MemRegCache_rd_addr[4]),
    .io_readPorts_4_data(MemRegCache_rd_data[4]),
    .io_readPorts_5_ren (MemRegCache_rd_ren[5]),
    .io_readPorts_5_addr(MemRegCache_rd_addr[5]),
    .io_readPorts_5_data(MemRegCache_rd_data[5]),
    .io_readPorts_6_ren (MemRegCache_rd_ren[6]),
    .io_readPorts_6_addr(MemRegCache_rd_addr[6]),
    .io_readPorts_6_data(MemRegCache_rd_data[6]),
    .io_readPorts_7_ren (MemRegCache_rd_ren[7]),
    .io_readPorts_7_addr(MemRegCache_rd_addr[7]),
    .io_readPorts_7_data(MemRegCache_rd_data[7]),
    .io_readPorts_8_ren (MemRegCache_rd_ren[8]),
    .io_readPorts_8_addr(MemRegCache_rd_addr[8]),
    .io_readPorts_8_data(MemRegCache_rd_data[8]),
    .io_readPorts_9_ren (MemRegCache_rd_ren[9]),
    .io_readPorts_9_addr(MemRegCache_rd_addr[9]),
    .io_readPorts_9_data(MemRegCache_rd_data[9]),
    .io_readPorts_10_ren (MemRegCache_rd_ren[10]),
    .io_readPorts_10_addr(MemRegCache_rd_addr[10]),
    .io_readPorts_10_data(MemRegCache_rd_data[10]),
    .io_readPorts_11_ren (MemRegCache_rd_ren[11]),
    .io_readPorts_11_addr(MemRegCache_rd_addr[11]),
    .io_readPorts_11_data(MemRegCache_rd_data[11]),
    .io_readPorts_12_ren (MemRegCache_rd_ren[12]),
    .io_readPorts_12_addr(MemRegCache_rd_addr[12]),
    .io_readPorts_12_data(MemRegCache_rd_data[12]),
    .io_readPorts_13_ren (MemRegCache_rd_ren[13]),
    .io_readPorts_13_addr(MemRegCache_rd_addr[13]),
    .io_readPorts_13_data(MemRegCache_rd_data[13]),
    .io_readPorts_14_ren (MemRegCache_rd_ren[14]),
    .io_readPorts_14_addr(MemRegCache_rd_addr[14]),
    .io_readPorts_14_data(MemRegCache_rd_data[14]),
    .io_readPorts_15_ren (MemRegCache_rd_ren[15]),
    .io_readPorts_15_addr(MemRegCache_rd_addr[15]),
    .io_readPorts_15_data(MemRegCache_rd_data[15]),
    .io_readPorts_16_ren (MemRegCache_rd_ren[16]),
    .io_readPorts_16_addr(MemRegCache_rd_addr[16]),
    .io_readPorts_16_data(MemRegCache_rd_data[16]),
    .io_readPorts_17_ren (MemRegCache_rd_ren[17]),
    .io_readPorts_17_addr(MemRegCache_rd_addr[17]),
    .io_readPorts_17_data(MemRegCache_rd_data[17]),
    .io_readPorts_18_ren (MemRegCache_rd_ren[18]),
    .io_readPorts_18_addr(MemRegCache_rd_addr[18]),
    .io_readPorts_18_data(MemRegCache_rd_data[18]),
    .io_readPorts_19_ren (MemRegCache_rd_ren[19]),
    .io_readPorts_19_addr(MemRegCache_rd_addr[19]),
    .io_readPorts_19_data(MemRegCache_rd_data[19]),
    .io_readPorts_20_ren (MemRegCache_rd_ren[20]),
    .io_readPorts_20_addr(MemRegCache_rd_addr[20]),
    .io_readPorts_20_data(MemRegCache_rd_data[20]),
    .io_readPorts_21_ren (MemRegCache_rd_ren[21]),
    .io_readPorts_21_addr(MemRegCache_rd_addr[21]),
    .io_readPorts_21_data(MemRegCache_rd_data[21]),
    .io_readPorts_22_ren (MemRegCache_rd_ren[22]),
    .io_readPorts_22_addr(MemRegCache_rd_addr[22]),
    .io_readPorts_22_data(MemRegCache_rd_data[22]),
    .io_writePorts_0_wen (MemRegCache_wr_wen[0]),
    .io_writePorts_0_addr(MemRegCache_wr_addr[0]),
    .io_writePorts_0_data(MemRegCache_wr_data[0]),
    .io_writePorts_1_wen (MemRegCache_wr_wen[1]),
    .io_writePorts_1_addr(MemRegCache_wr_addr[1]),
    .io_writePorts_1_data(MemRegCache_wr_data[1]),
    .io_writePorts_2_wen (MemRegCache_wr_wen[2]),
    .io_writePorts_2_addr(MemRegCache_wr_addr[2]),
    .io_writePorts_2_data(MemRegCache_wr_data[2]),
    .io_validInfo_0(MemRegCache_valid[0]), .io_validInfo_1(MemRegCache_valid[1]), .io_validInfo_2(MemRegCache_valid[2]), .io_validInfo_3(MemRegCache_valid[3]), .io_validInfo_4(MemRegCache_valid[4]), .io_validInfo_5(MemRegCache_valid[5]), .io_validInfo_6(MemRegCache_valid[6]), .io_validInfo_7(MemRegCache_valid[7]), .io_validInfo_8(MemRegCache_valid[8]), .io_validInfo_9(MemRegCache_valid[9]), .io_validInfo_10(MemRegCache_valid[10]), .io_validInfo_11(MemRegCache_valid[11])
  );

  RegCacheAgeTimer_1 MemRegCache_age_timer (
    .clock(clock), .reset(reset),
    .io_readPorts_0_ren (MemRegCache_rd_ren[0]),
    .io_readPorts_0_addr(MemRegCache_rd_addr[0]),
    .io_readPorts_1_ren (MemRegCache_rd_ren[1]),
    .io_readPorts_1_addr(MemRegCache_rd_addr[1]),
    .io_readPorts_2_ren (MemRegCache_rd_ren[2]),
    .io_readPorts_2_addr(MemRegCache_rd_addr[2]),
    .io_readPorts_3_ren (MemRegCache_rd_ren[3]),
    .io_readPorts_3_addr(MemRegCache_rd_addr[3]),
    .io_readPorts_4_ren (MemRegCache_rd_ren[4]),
    .io_readPorts_4_addr(MemRegCache_rd_addr[4]),
    .io_readPorts_5_ren (MemRegCache_rd_ren[5]),
    .io_readPorts_5_addr(MemRegCache_rd_addr[5]),
    .io_readPorts_6_ren (MemRegCache_rd_ren[6]),
    .io_readPorts_6_addr(MemRegCache_rd_addr[6]),
    .io_readPorts_7_ren (MemRegCache_rd_ren[7]),
    .io_readPorts_7_addr(MemRegCache_rd_addr[7]),
    .io_readPorts_8_ren (MemRegCache_rd_ren[8]),
    .io_readPorts_8_addr(MemRegCache_rd_addr[8]),
    .io_readPorts_9_ren (MemRegCache_rd_ren[9]),
    .io_readPorts_9_addr(MemRegCache_rd_addr[9]),
    .io_readPorts_10_ren (MemRegCache_rd_ren[10]),
    .io_readPorts_10_addr(MemRegCache_rd_addr[10]),
    .io_readPorts_11_ren (MemRegCache_rd_ren[11]),
    .io_readPorts_11_addr(MemRegCache_rd_addr[11]),
    .io_readPorts_12_ren (MemRegCache_rd_ren[12]),
    .io_readPorts_12_addr(MemRegCache_rd_addr[12]),
    .io_readPorts_13_ren (MemRegCache_rd_ren[13]),
    .io_readPorts_13_addr(MemRegCache_rd_addr[13]),
    .io_readPorts_14_ren (MemRegCache_rd_ren[14]),
    .io_readPorts_14_addr(MemRegCache_rd_addr[14]),
    .io_readPorts_15_ren (MemRegCache_rd_ren[15]),
    .io_readPorts_15_addr(MemRegCache_rd_addr[15]),
    .io_readPorts_16_ren (MemRegCache_rd_ren[16]),
    .io_readPorts_16_addr(MemRegCache_rd_addr[16]),
    .io_readPorts_17_ren (MemRegCache_rd_ren[17]),
    .io_readPorts_17_addr(MemRegCache_rd_addr[17]),
    .io_readPorts_18_ren (MemRegCache_rd_ren[18]),
    .io_readPorts_18_addr(MemRegCache_rd_addr[18]),
    .io_readPorts_19_ren (MemRegCache_rd_ren[19]),
    .io_readPorts_19_addr(MemRegCache_rd_addr[19]),
    .io_readPorts_20_ren (MemRegCache_rd_ren[20]),
    .io_readPorts_20_addr(MemRegCache_rd_addr[20]),
    .io_readPorts_21_ren (MemRegCache_rd_ren[21]),
    .io_readPorts_21_addr(MemRegCache_rd_addr[21]),
    .io_readPorts_22_ren (MemRegCache_rd_ren[22]),
    .io_readPorts_22_addr(MemRegCache_rd_addr[22]),
    .io_writePorts_0_wen (MemRegCache_wr_wen[0]),
    .io_writePorts_0_addr(MemRegCache_wr_addr[0]),
    .io_writePorts_1_wen (MemRegCache_wr_wen[1]),
    .io_writePorts_1_addr(MemRegCache_wr_addr[1]),
    .io_writePorts_2_wen (MemRegCache_wr_wen[2]),
    .io_writePorts_2_addr(MemRegCache_wr_addr[2]),
    .io_validInfo_0(MemRegCache_valid[0]),
    .io_validInfo_1(MemRegCache_valid[1]),
    .io_validInfo_2(MemRegCache_valid[2]),
    .io_validInfo_3(MemRegCache_valid[3]),
    .io_validInfo_4(MemRegCache_valid[4]),
    .io_validInfo_5(MemRegCache_valid[5]),
    .io_validInfo_6(MemRegCache_valid[6]),
    .io_validInfo_7(MemRegCache_valid[7]),
    .io_validInfo_8(MemRegCache_valid[8]),
    .io_validInfo_9(MemRegCache_valid[9]),
    .io_validInfo_10(MemRegCache_valid[10]),
    .io_validInfo_11(MemRegCache_valid[11]),
    .io_ageInfo_0_1(age_mem[0]), .io_ageInfo_0_2(age_mem[1]), .io_ageInfo_0_3(age_mem[2]), .io_ageInfo_0_4(age_mem[3]), .io_ageInfo_0_5(age_mem[4]), .io_ageInfo_0_6(age_mem[5]), .io_ageInfo_0_7(age_mem[6]), .io_ageInfo_0_8(age_mem[7]), .io_ageInfo_0_9(age_mem[8]), .io_ageInfo_0_10(age_mem[9]), .io_ageInfo_0_11(age_mem[10]), .io_ageInfo_1_2(age_mem[11]), .io_ageInfo_1_3(age_mem[12]), .io_ageInfo_1_4(age_mem[13]), .io_ageInfo_1_5(age_mem[14]), .io_ageInfo_1_6(age_mem[15]), .io_ageInfo_1_7(age_mem[16]), .io_ageInfo_1_8(age_mem[17]), .io_ageInfo_1_9(age_mem[18]), .io_ageInfo_1_10(age_mem[19]), .io_ageInfo_1_11(age_mem[20]), .io_ageInfo_2_3(age_mem[21]), .io_ageInfo_2_4(age_mem[22]), .io_ageInfo_2_5(age_mem[23]), .io_ageInfo_2_6(age_mem[24]), .io_ageInfo_2_7(age_mem[25]), .io_ageInfo_2_8(age_mem[26]), .io_ageInfo_2_9(age_mem[27]), .io_ageInfo_2_10(age_mem[28]), .io_ageInfo_2_11(age_mem[29]), .io_ageInfo_3_4(age_mem[30]), .io_ageInfo_3_5(age_mem[31]), .io_ageInfo_3_6(age_mem[32]), .io_ageInfo_3_7(age_mem[33]), .io_ageInfo_3_8(age_mem[34]), .io_ageInfo_3_9(age_mem[35]), .io_ageInfo_3_10(age_mem[36]), .io_ageInfo_3_11(age_mem[37]), .io_ageInfo_4_5(age_mem[38]), .io_ageInfo_4_6(age_mem[39]), .io_ageInfo_4_7(age_mem[40]), .io_ageInfo_4_8(age_mem[41]), .io_ageInfo_4_9(age_mem[42]), .io_ageInfo_4_10(age_mem[43]), .io_ageInfo_4_11(age_mem[44]), .io_ageInfo_5_6(age_mem[45]), .io_ageInfo_5_7(age_mem[46]), .io_ageInfo_5_8(age_mem[47]), .io_ageInfo_5_9(age_mem[48]), .io_ageInfo_5_10(age_mem[49]), .io_ageInfo_5_11(age_mem[50]), .io_ageInfo_6_7(age_mem[51]), .io_ageInfo_6_8(age_mem[52]), .io_ageInfo_6_9(age_mem[53]), .io_ageInfo_6_10(age_mem[54]), .io_ageInfo_6_11(age_mem[55]), .io_ageInfo_7_8(age_mem[56]), .io_ageInfo_7_9(age_mem[57]), .io_ageInfo_7_10(age_mem[58]), .io_ageInfo_7_11(age_mem[59]), .io_ageInfo_8_9(age_mem[60]), .io_ageInfo_8_10(age_mem[61]), .io_ageInfo_8_11(age_mem[62]), .io_ageInfo_9_10(age_mem[63]), .io_ageInfo_9_11(age_mem[64]), .io_ageInfo_10_11(age_mem[65])
  );

  RegCacheAgeDetector_1 MemRegCache_rep (
    .clock(clock), .reset(reset),
    .io_ageInfo_0_1(age_mem[0]), .io_ageInfo_0_2(age_mem[1]), .io_ageInfo_0_3(age_mem[2]), .io_ageInfo_0_4(age_mem[3]), .io_ageInfo_0_5(age_mem[4]), .io_ageInfo_0_6(age_mem[5]), .io_ageInfo_0_7(age_mem[6]), .io_ageInfo_0_8(age_mem[7]), .io_ageInfo_0_9(age_mem[8]), .io_ageInfo_0_10(age_mem[9]), .io_ageInfo_0_11(age_mem[10]), .io_ageInfo_1_2(age_mem[11]), .io_ageInfo_1_3(age_mem[12]), .io_ageInfo_1_4(age_mem[13]), .io_ageInfo_1_5(age_mem[14]), .io_ageInfo_1_6(age_mem[15]), .io_ageInfo_1_7(age_mem[16]), .io_ageInfo_1_8(age_mem[17]), .io_ageInfo_1_9(age_mem[18]), .io_ageInfo_1_10(age_mem[19]), .io_ageInfo_1_11(age_mem[20]), .io_ageInfo_2_3(age_mem[21]), .io_ageInfo_2_4(age_mem[22]), .io_ageInfo_2_5(age_mem[23]), .io_ageInfo_2_6(age_mem[24]), .io_ageInfo_2_7(age_mem[25]), .io_ageInfo_2_8(age_mem[26]), .io_ageInfo_2_9(age_mem[27]), .io_ageInfo_2_10(age_mem[28]), .io_ageInfo_2_11(age_mem[29]), .io_ageInfo_3_4(age_mem[30]), .io_ageInfo_3_5(age_mem[31]), .io_ageInfo_3_6(age_mem[32]), .io_ageInfo_3_7(age_mem[33]), .io_ageInfo_3_8(age_mem[34]), .io_ageInfo_3_9(age_mem[35]), .io_ageInfo_3_10(age_mem[36]), .io_ageInfo_3_11(age_mem[37]), .io_ageInfo_4_5(age_mem[38]), .io_ageInfo_4_6(age_mem[39]), .io_ageInfo_4_7(age_mem[40]), .io_ageInfo_4_8(age_mem[41]), .io_ageInfo_4_9(age_mem[42]), .io_ageInfo_4_10(age_mem[43]), .io_ageInfo_4_11(age_mem[44]), .io_ageInfo_5_6(age_mem[45]), .io_ageInfo_5_7(age_mem[46]), .io_ageInfo_5_8(age_mem[47]), .io_ageInfo_5_9(age_mem[48]), .io_ageInfo_5_10(age_mem[49]), .io_ageInfo_5_11(age_mem[50]), .io_ageInfo_6_7(age_mem[51]), .io_ageInfo_6_8(age_mem[52]), .io_ageInfo_6_9(age_mem[53]), .io_ageInfo_6_10(age_mem[54]), .io_ageInfo_6_11(age_mem[55]), .io_ageInfo_7_8(age_mem[56]), .io_ageInfo_7_9(age_mem[57]), .io_ageInfo_7_10(age_mem[58]), .io_ageInfo_7_11(age_mem[59]), .io_ageInfo_8_9(age_mem[60]), .io_ageInfo_8_10(age_mem[61]), .io_ageInfo_8_11(age_mem[62]), .io_ageInfo_9_10(age_mem[63]), .io_ageInfo_9_11(age_mem[64]), .io_ageInfo_10_11(age_mem[65]),
    .io_out_0(rep_mem[0]), .io_out_1(rep_mem[1]), .io_out_2(rep_mem[2])
  );

