// 自动生成:scripts/gen_scheduler_variants.py —— 勿手改
// =============================================================================
// Scheduler_3 —— 香山 V2R2 Mem Scheduler 可读核(golden 同名顶层)
// 设计源:src/main/scala/xiangshan/backend/issue/Scheduler.scala
//        golden:Scheduler_3.sv
//
// 见 scripts/gen_scheduler_variants.py 头部「设计意图 / 重写方式」。
// 本核做四件可读的事:
//   A) 例化 9 个 IssueQueue 并互联(唤醒网络/响应/cancel,机械连线在 .svh);
//   B) dispatch-ready 透传:把各 IQ 的 enq0.ready 回送给 fromDispatch.uops.ready;
//   C) deqDelay 输出扇出:各 IQ 的 deqDelay_0_valid 引到对应 toDataPathAfterDelay;
//   D) 发射 perf 统计:enq_fire popcount + 各 IQ full 位,两级 RegNext 后输出。
// =============================================================================
module Scheduler_3 import scheduler_mem_pkg::*; (
  input         clock,
  input         reset,
  output [4:0] io_IQValidNumVec_0,
  output [4:0] io_IQValidNumVec_1,
  output [4:0] io_IQValidNumVec_2,
  output [4:0] io_IQValidNumVec_3,
  output [4:0] io_IQValidNumVec_4,
  output [4:0] io_IQValidNumVec_5,
  output [4:0] io_IQValidNumVec_6,
  input  io_fromCtrlBlock_flush_valid,
  input  io_fromCtrlBlock_flush_bits_robIdx_flag,
  input  [7:0] io_fromCtrlBlock_flush_bits_robIdx_value,
  input  io_fromCtrlBlock_flush_bits_level,
  output io_fromDispatch_uops_0_ready,
  input  io_fromDispatch_uops_0_valid,
  input  [5:0] io_fromDispatch_uops_0_bits_ftqPtr_value,
  input  [3:0] io_fromDispatch_uops_0_bits_ftqOffset,
  input  [3:0] io_fromDispatch_uops_0_bits_srcType_0,
  input  [3:0] io_fromDispatch_uops_0_bits_srcType_1,
  input  [34:0] io_fromDispatch_uops_0_bits_fuType,
  input  [8:0] io_fromDispatch_uops_0_bits_fuOpType,
  input  io_fromDispatch_uops_0_bits_rfWen,
  input  [3:0] io_fromDispatch_uops_0_bits_selImm,
  input  [31:0] io_fromDispatch_uops_0_bits_imm,
  input  io_fromDispatch_uops_0_bits_isDropAmocasSta,
  input  io_fromDispatch_uops_0_bits_srcState_0,
  input  io_fromDispatch_uops_0_bits_srcState_1,
  input  [1:0] io_fromDispatch_uops_0_bits_srcLoadDependency_0_0,
  input  [1:0] io_fromDispatch_uops_0_bits_srcLoadDependency_0_1,
  input  [1:0] io_fromDispatch_uops_0_bits_srcLoadDependency_0_2,
  input  [1:0] io_fromDispatch_uops_0_bits_srcLoadDependency_1_0,
  input  [1:0] io_fromDispatch_uops_0_bits_srcLoadDependency_1_1,
  input  [1:0] io_fromDispatch_uops_0_bits_srcLoadDependency_1_2,
  input  [7:0] io_fromDispatch_uops_0_bits_psrc_0,
  input  [7:0] io_fromDispatch_uops_0_bits_psrc_1,
  input  [7:0] io_fromDispatch_uops_0_bits_pdest,
  input  io_fromDispatch_uops_0_bits_useRegCache_0,
  input  io_fromDispatch_uops_0_bits_useRegCache_1,
  input  [4:0] io_fromDispatch_uops_0_bits_regCacheIdx_0,
  input  [4:0] io_fromDispatch_uops_0_bits_regCacheIdx_1,
  input  io_fromDispatch_uops_0_bits_robIdx_flag,
  input  [7:0] io_fromDispatch_uops_0_bits_robIdx_value,
  input  io_fromDispatch_uops_0_bits_sqIdx_flag,
  input  [5:0] io_fromDispatch_uops_0_bits_sqIdx_value,
  input  io_fromDispatch_uops_1_valid,
  input  [5:0] io_fromDispatch_uops_1_bits_ftqPtr_value,
  input  [3:0] io_fromDispatch_uops_1_bits_ftqOffset,
  input  [3:0] io_fromDispatch_uops_1_bits_srcType_0,
  input  [3:0] io_fromDispatch_uops_1_bits_srcType_1,
  input  [34:0] io_fromDispatch_uops_1_bits_fuType,
  input  [8:0] io_fromDispatch_uops_1_bits_fuOpType,
  input  io_fromDispatch_uops_1_bits_rfWen,
  input  [3:0] io_fromDispatch_uops_1_bits_selImm,
  input  [31:0] io_fromDispatch_uops_1_bits_imm,
  input  io_fromDispatch_uops_1_bits_isDropAmocasSta,
  input  io_fromDispatch_uops_1_bits_srcState_0,
  input  io_fromDispatch_uops_1_bits_srcState_1,
  input  [1:0] io_fromDispatch_uops_1_bits_srcLoadDependency_0_0,
  input  [1:0] io_fromDispatch_uops_1_bits_srcLoadDependency_0_1,
  input  [1:0] io_fromDispatch_uops_1_bits_srcLoadDependency_0_2,
  input  [1:0] io_fromDispatch_uops_1_bits_srcLoadDependency_1_0,
  input  [1:0] io_fromDispatch_uops_1_bits_srcLoadDependency_1_1,
  input  [1:0] io_fromDispatch_uops_1_bits_srcLoadDependency_1_2,
  input  [7:0] io_fromDispatch_uops_1_bits_psrc_0,
  input  [7:0] io_fromDispatch_uops_1_bits_psrc_1,
  input  [7:0] io_fromDispatch_uops_1_bits_pdest,
  input  io_fromDispatch_uops_1_bits_useRegCache_0,
  input  io_fromDispatch_uops_1_bits_useRegCache_1,
  input  [4:0] io_fromDispatch_uops_1_bits_regCacheIdx_0,
  input  [4:0] io_fromDispatch_uops_1_bits_regCacheIdx_1,
  input  io_fromDispatch_uops_1_bits_robIdx_flag,
  input  [7:0] io_fromDispatch_uops_1_bits_robIdx_value,
  input  io_fromDispatch_uops_1_bits_sqIdx_flag,
  input  [5:0] io_fromDispatch_uops_1_bits_sqIdx_value,
  output io_fromDispatch_uops_2_ready,
  input  io_fromDispatch_uops_2_valid,
  input  [5:0] io_fromDispatch_uops_2_bits_ftqPtr_value,
  input  [3:0] io_fromDispatch_uops_2_bits_ftqOffset,
  input  [3:0] io_fromDispatch_uops_2_bits_srcType_0,
  input  [3:0] io_fromDispatch_uops_2_bits_srcType_1,
  input  [34:0] io_fromDispatch_uops_2_bits_fuType,
  input  [8:0] io_fromDispatch_uops_2_bits_fuOpType,
  input  io_fromDispatch_uops_2_bits_rfWen,
  input  [3:0] io_fromDispatch_uops_2_bits_selImm,
  input  [31:0] io_fromDispatch_uops_2_bits_imm,
  input  io_fromDispatch_uops_2_bits_isDropAmocasSta,
  input  io_fromDispatch_uops_2_bits_srcState_0,
  input  io_fromDispatch_uops_2_bits_srcState_1,
  input  [1:0] io_fromDispatch_uops_2_bits_srcLoadDependency_0_0,
  input  [1:0] io_fromDispatch_uops_2_bits_srcLoadDependency_0_1,
  input  [1:0] io_fromDispatch_uops_2_bits_srcLoadDependency_0_2,
  input  [1:0] io_fromDispatch_uops_2_bits_srcLoadDependency_1_0,
  input  [1:0] io_fromDispatch_uops_2_bits_srcLoadDependency_1_1,
  input  [1:0] io_fromDispatch_uops_2_bits_srcLoadDependency_1_2,
  input  [7:0] io_fromDispatch_uops_2_bits_psrc_0,
  input  [7:0] io_fromDispatch_uops_2_bits_psrc_1,
  input  [7:0] io_fromDispatch_uops_2_bits_pdest,
  input  io_fromDispatch_uops_2_bits_useRegCache_0,
  input  io_fromDispatch_uops_2_bits_useRegCache_1,
  input  [4:0] io_fromDispatch_uops_2_bits_regCacheIdx_0,
  input  [4:0] io_fromDispatch_uops_2_bits_regCacheIdx_1,
  input  io_fromDispatch_uops_2_bits_robIdx_flag,
  input  [7:0] io_fromDispatch_uops_2_bits_robIdx_value,
  input  io_fromDispatch_uops_2_bits_sqIdx_flag,
  input  [5:0] io_fromDispatch_uops_2_bits_sqIdx_value,
  input  io_fromDispatch_uops_3_valid,
  input  [5:0] io_fromDispatch_uops_3_bits_ftqPtr_value,
  input  [3:0] io_fromDispatch_uops_3_bits_ftqOffset,
  input  [3:0] io_fromDispatch_uops_3_bits_srcType_0,
  input  [3:0] io_fromDispatch_uops_3_bits_srcType_1,
  input  [34:0] io_fromDispatch_uops_3_bits_fuType,
  input  [8:0] io_fromDispatch_uops_3_bits_fuOpType,
  input  io_fromDispatch_uops_3_bits_rfWen,
  input  [3:0] io_fromDispatch_uops_3_bits_selImm,
  input  [31:0] io_fromDispatch_uops_3_bits_imm,
  input  io_fromDispatch_uops_3_bits_isDropAmocasSta,
  input  io_fromDispatch_uops_3_bits_srcState_0,
  input  io_fromDispatch_uops_3_bits_srcState_1,
  input  [1:0] io_fromDispatch_uops_3_bits_srcLoadDependency_0_0,
  input  [1:0] io_fromDispatch_uops_3_bits_srcLoadDependency_0_1,
  input  [1:0] io_fromDispatch_uops_3_bits_srcLoadDependency_0_2,
  input  [1:0] io_fromDispatch_uops_3_bits_srcLoadDependency_1_0,
  input  [1:0] io_fromDispatch_uops_3_bits_srcLoadDependency_1_1,
  input  [1:0] io_fromDispatch_uops_3_bits_srcLoadDependency_1_2,
  input  [7:0] io_fromDispatch_uops_3_bits_psrc_0,
  input  [7:0] io_fromDispatch_uops_3_bits_psrc_1,
  input  [7:0] io_fromDispatch_uops_3_bits_pdest,
  input  io_fromDispatch_uops_3_bits_useRegCache_0,
  input  io_fromDispatch_uops_3_bits_useRegCache_1,
  input  [4:0] io_fromDispatch_uops_3_bits_regCacheIdx_0,
  input  [4:0] io_fromDispatch_uops_3_bits_regCacheIdx_1,
  input  io_fromDispatch_uops_3_bits_robIdx_flag,
  input  [7:0] io_fromDispatch_uops_3_bits_robIdx_value,
  input  io_fromDispatch_uops_3_bits_sqIdx_flag,
  input  [5:0] io_fromDispatch_uops_3_bits_sqIdx_value,
  output io_fromDispatch_uops_4_ready,
  input  io_fromDispatch_uops_4_valid,
  input  io_fromDispatch_uops_4_bits_preDecodeInfo_isRVC,
  input  io_fromDispatch_uops_4_bits_ftqPtr_flag,
  input  [5:0] io_fromDispatch_uops_4_bits_ftqPtr_value,
  input  [3:0] io_fromDispatch_uops_4_bits_ftqOffset,
  input  [3:0] io_fromDispatch_uops_4_bits_srcType_0,
  input  [34:0] io_fromDispatch_uops_4_bits_fuType,
  input  [8:0] io_fromDispatch_uops_4_bits_fuOpType,
  input  io_fromDispatch_uops_4_bits_rfWen,
  input  io_fromDispatch_uops_4_bits_fpWen,
  input  [31:0] io_fromDispatch_uops_4_bits_imm,
  input  io_fromDispatch_uops_4_bits_srcState_0,
  input  [1:0] io_fromDispatch_uops_4_bits_srcLoadDependency_0_0,
  input  [1:0] io_fromDispatch_uops_4_bits_srcLoadDependency_0_1,
  input  [1:0] io_fromDispatch_uops_4_bits_srcLoadDependency_0_2,
  input  [7:0] io_fromDispatch_uops_4_bits_psrc_0,
  input  [7:0] io_fromDispatch_uops_4_bits_pdest,
  input  io_fromDispatch_uops_4_bits_useRegCache_0,
  input  [4:0] io_fromDispatch_uops_4_bits_regCacheIdx_0,
  input  io_fromDispatch_uops_4_bits_robIdx_flag,
  input  [7:0] io_fromDispatch_uops_4_bits_robIdx_value,
  input  io_fromDispatch_uops_4_bits_lqIdx_flag,
  input  [6:0] io_fromDispatch_uops_4_bits_lqIdx_value,
  input  io_fromDispatch_uops_4_bits_sqIdx_flag,
  input  [5:0] io_fromDispatch_uops_4_bits_sqIdx_value,
  input  io_fromDispatch_uops_5_valid,
  input  io_fromDispatch_uops_5_bits_preDecodeInfo_isRVC,
  input  io_fromDispatch_uops_5_bits_ftqPtr_flag,
  input  [5:0] io_fromDispatch_uops_5_bits_ftqPtr_value,
  input  [3:0] io_fromDispatch_uops_5_bits_ftqOffset,
  input  [3:0] io_fromDispatch_uops_5_bits_srcType_0,
  input  [34:0] io_fromDispatch_uops_5_bits_fuType,
  input  [8:0] io_fromDispatch_uops_5_bits_fuOpType,
  input  io_fromDispatch_uops_5_bits_rfWen,
  input  io_fromDispatch_uops_5_bits_fpWen,
  input  [31:0] io_fromDispatch_uops_5_bits_imm,
  input  io_fromDispatch_uops_5_bits_srcState_0,
  input  [1:0] io_fromDispatch_uops_5_bits_srcLoadDependency_0_0,
  input  [1:0] io_fromDispatch_uops_5_bits_srcLoadDependency_0_1,
  input  [1:0] io_fromDispatch_uops_5_bits_srcLoadDependency_0_2,
  input  [7:0] io_fromDispatch_uops_5_bits_psrc_0,
  input  [7:0] io_fromDispatch_uops_5_bits_pdest,
  input  io_fromDispatch_uops_5_bits_useRegCache_0,
  input  [4:0] io_fromDispatch_uops_5_bits_regCacheIdx_0,
  input  io_fromDispatch_uops_5_bits_robIdx_flag,
  input  [7:0] io_fromDispatch_uops_5_bits_robIdx_value,
  input  io_fromDispatch_uops_5_bits_lqIdx_flag,
  input  [6:0] io_fromDispatch_uops_5_bits_lqIdx_value,
  input  io_fromDispatch_uops_5_bits_sqIdx_flag,
  input  [5:0] io_fromDispatch_uops_5_bits_sqIdx_value,
  output io_fromDispatch_uops_6_ready,
  input  io_fromDispatch_uops_6_valid,
  input  io_fromDispatch_uops_6_bits_preDecodeInfo_isRVC,
  input  io_fromDispatch_uops_6_bits_ftqPtr_flag,
  input  [5:0] io_fromDispatch_uops_6_bits_ftqPtr_value,
  input  [3:0] io_fromDispatch_uops_6_bits_ftqOffset,
  input  [3:0] io_fromDispatch_uops_6_bits_srcType_0,
  input  [34:0] io_fromDispatch_uops_6_bits_fuType,
  input  [8:0] io_fromDispatch_uops_6_bits_fuOpType,
  input  io_fromDispatch_uops_6_bits_rfWen,
  input  io_fromDispatch_uops_6_bits_fpWen,
  input  [31:0] io_fromDispatch_uops_6_bits_imm,
  input  io_fromDispatch_uops_6_bits_srcState_0,
  input  [1:0] io_fromDispatch_uops_6_bits_srcLoadDependency_0_0,
  input  [1:0] io_fromDispatch_uops_6_bits_srcLoadDependency_0_1,
  input  [1:0] io_fromDispatch_uops_6_bits_srcLoadDependency_0_2,
  input  [7:0] io_fromDispatch_uops_6_bits_psrc_0,
  input  [7:0] io_fromDispatch_uops_6_bits_pdest,
  input  io_fromDispatch_uops_6_bits_useRegCache_0,
  input  [4:0] io_fromDispatch_uops_6_bits_regCacheIdx_0,
  input  io_fromDispatch_uops_6_bits_robIdx_flag,
  input  [7:0] io_fromDispatch_uops_6_bits_robIdx_value,
  input  io_fromDispatch_uops_6_bits_lqIdx_flag,
  input  [6:0] io_fromDispatch_uops_6_bits_lqIdx_value,
  input  io_fromDispatch_uops_6_bits_sqIdx_flag,
  input  [5:0] io_fromDispatch_uops_6_bits_sqIdx_value,
  input  io_fromDispatch_uops_7_valid,
  input  io_fromDispatch_uops_7_bits_preDecodeInfo_isRVC,
  input  io_fromDispatch_uops_7_bits_ftqPtr_flag,
  input  [5:0] io_fromDispatch_uops_7_bits_ftqPtr_value,
  input  [3:0] io_fromDispatch_uops_7_bits_ftqOffset,
  input  [3:0] io_fromDispatch_uops_7_bits_srcType_0,
  input  [34:0] io_fromDispatch_uops_7_bits_fuType,
  input  [8:0] io_fromDispatch_uops_7_bits_fuOpType,
  input  io_fromDispatch_uops_7_bits_rfWen,
  input  io_fromDispatch_uops_7_bits_fpWen,
  input  [31:0] io_fromDispatch_uops_7_bits_imm,
  input  io_fromDispatch_uops_7_bits_srcState_0,
  input  [1:0] io_fromDispatch_uops_7_bits_srcLoadDependency_0_0,
  input  [1:0] io_fromDispatch_uops_7_bits_srcLoadDependency_0_1,
  input  [1:0] io_fromDispatch_uops_7_bits_srcLoadDependency_0_2,
  input  [7:0] io_fromDispatch_uops_7_bits_psrc_0,
  input  [7:0] io_fromDispatch_uops_7_bits_pdest,
  input  io_fromDispatch_uops_7_bits_useRegCache_0,
  input  [4:0] io_fromDispatch_uops_7_bits_regCacheIdx_0,
  input  io_fromDispatch_uops_7_bits_robIdx_flag,
  input  [7:0] io_fromDispatch_uops_7_bits_robIdx_value,
  input  io_fromDispatch_uops_7_bits_lqIdx_flag,
  input  [6:0] io_fromDispatch_uops_7_bits_lqIdx_value,
  input  io_fromDispatch_uops_7_bits_sqIdx_flag,
  input  [5:0] io_fromDispatch_uops_7_bits_sqIdx_value,
  output io_fromDispatch_uops_8_ready,
  input  io_fromDispatch_uops_8_valid,
  input  io_fromDispatch_uops_8_bits_preDecodeInfo_isRVC,
  input  io_fromDispatch_uops_8_bits_ftqPtr_flag,
  input  [5:0] io_fromDispatch_uops_8_bits_ftqPtr_value,
  input  [3:0] io_fromDispatch_uops_8_bits_ftqOffset,
  input  [3:0] io_fromDispatch_uops_8_bits_srcType_0,
  input  [34:0] io_fromDispatch_uops_8_bits_fuType,
  input  [8:0] io_fromDispatch_uops_8_bits_fuOpType,
  input  io_fromDispatch_uops_8_bits_rfWen,
  input  io_fromDispatch_uops_8_bits_fpWen,
  input  [31:0] io_fromDispatch_uops_8_bits_imm,
  input  io_fromDispatch_uops_8_bits_srcState_0,
  input  [1:0] io_fromDispatch_uops_8_bits_srcLoadDependency_0_0,
  input  [1:0] io_fromDispatch_uops_8_bits_srcLoadDependency_0_1,
  input  [1:0] io_fromDispatch_uops_8_bits_srcLoadDependency_0_2,
  input  [7:0] io_fromDispatch_uops_8_bits_psrc_0,
  input  [7:0] io_fromDispatch_uops_8_bits_pdest,
  input  io_fromDispatch_uops_8_bits_useRegCache_0,
  input  [4:0] io_fromDispatch_uops_8_bits_regCacheIdx_0,
  input  io_fromDispatch_uops_8_bits_robIdx_flag,
  input  [7:0] io_fromDispatch_uops_8_bits_robIdx_value,
  input  io_fromDispatch_uops_8_bits_lqIdx_flag,
  input  [6:0] io_fromDispatch_uops_8_bits_lqIdx_value,
  input  io_fromDispatch_uops_8_bits_sqIdx_flag,
  input  [5:0] io_fromDispatch_uops_8_bits_sqIdx_value,
  input  io_fromDispatch_uops_9_valid,
  input  io_fromDispatch_uops_9_bits_preDecodeInfo_isRVC,
  input  io_fromDispatch_uops_9_bits_ftqPtr_flag,
  input  [5:0] io_fromDispatch_uops_9_bits_ftqPtr_value,
  input  [3:0] io_fromDispatch_uops_9_bits_ftqOffset,
  input  [3:0] io_fromDispatch_uops_9_bits_srcType_0,
  input  [34:0] io_fromDispatch_uops_9_bits_fuType,
  input  [8:0] io_fromDispatch_uops_9_bits_fuOpType,
  input  io_fromDispatch_uops_9_bits_rfWen,
  input  io_fromDispatch_uops_9_bits_fpWen,
  input  [31:0] io_fromDispatch_uops_9_bits_imm,
  input  io_fromDispatch_uops_9_bits_srcState_0,
  input  [1:0] io_fromDispatch_uops_9_bits_srcLoadDependency_0_0,
  input  [1:0] io_fromDispatch_uops_9_bits_srcLoadDependency_0_1,
  input  [1:0] io_fromDispatch_uops_9_bits_srcLoadDependency_0_2,
  input  [7:0] io_fromDispatch_uops_9_bits_psrc_0,
  input  [7:0] io_fromDispatch_uops_9_bits_pdest,
  input  io_fromDispatch_uops_9_bits_useRegCache_0,
  input  [4:0] io_fromDispatch_uops_9_bits_regCacheIdx_0,
  input  io_fromDispatch_uops_9_bits_robIdx_flag,
  input  [7:0] io_fromDispatch_uops_9_bits_robIdx_value,
  input  io_fromDispatch_uops_9_bits_lqIdx_flag,
  input  [6:0] io_fromDispatch_uops_9_bits_lqIdx_value,
  input  io_fromDispatch_uops_9_bits_sqIdx_flag,
  input  [5:0] io_fromDispatch_uops_9_bits_sqIdx_value,
  output io_fromDispatch_uops_10_ready,
  input  io_fromDispatch_uops_10_valid,
  input  io_fromDispatch_uops_10_bits_ftqPtr_flag,
  input  [5:0] io_fromDispatch_uops_10_bits_ftqPtr_value,
  input  [3:0] io_fromDispatch_uops_10_bits_ftqOffset,
  input  [3:0] io_fromDispatch_uops_10_bits_srcType_0,
  input  [3:0] io_fromDispatch_uops_10_bits_srcType_1,
  input  [3:0] io_fromDispatch_uops_10_bits_srcType_2,
  input  [3:0] io_fromDispatch_uops_10_bits_srcType_3,
  input  [3:0] io_fromDispatch_uops_10_bits_srcType_4,
  input  [34:0] io_fromDispatch_uops_10_bits_fuType,
  input  [8:0] io_fromDispatch_uops_10_bits_fuOpType,
  input  io_fromDispatch_uops_10_bits_vecWen,
  input  io_fromDispatch_uops_10_bits_v0Wen,
  input  io_fromDispatch_uops_10_bits_vlWen,
  input  io_fromDispatch_uops_10_bits_vpu_vma,
  input  io_fromDispatch_uops_10_bits_vpu_vta,
  input  [1:0] io_fromDispatch_uops_10_bits_vpu_vsew,
  input  [2:0] io_fromDispatch_uops_10_bits_vpu_vlmul,
  input  io_fromDispatch_uops_10_bits_vpu_vm,
  input  [7:0] io_fromDispatch_uops_10_bits_vpu_vstart,
  input  [127:0] io_fromDispatch_uops_10_bits_vpu_vmask,
  input  [2:0] io_fromDispatch_uops_10_bits_vpu_nf,
  input  [1:0] io_fromDispatch_uops_10_bits_vpu_veew,
  input  io_fromDispatch_uops_10_bits_vpu_isDependOldVd,
  input  io_fromDispatch_uops_10_bits_vpu_isWritePartVd,
  input  io_fromDispatch_uops_10_bits_vpu_isVleff,
  input  [6:0] io_fromDispatch_uops_10_bits_uopIdx,
  input  io_fromDispatch_uops_10_bits_lastUop,
  input  io_fromDispatch_uops_10_bits_srcState_0,
  input  io_fromDispatch_uops_10_bits_srcState_1,
  input  io_fromDispatch_uops_10_bits_srcState_2,
  input  io_fromDispatch_uops_10_bits_srcState_3,
  input  io_fromDispatch_uops_10_bits_srcState_4,
  input  [7:0] io_fromDispatch_uops_10_bits_psrc_0,
  input  [7:0] io_fromDispatch_uops_10_bits_psrc_1,
  input  [7:0] io_fromDispatch_uops_10_bits_psrc_2,
  input  [7:0] io_fromDispatch_uops_10_bits_psrc_3,
  input  [7:0] io_fromDispatch_uops_10_bits_psrc_4,
  input  [7:0] io_fromDispatch_uops_10_bits_pdest,
  input  io_fromDispatch_uops_10_bits_robIdx_flag,
  input  [7:0] io_fromDispatch_uops_10_bits_robIdx_value,
  input  io_fromDispatch_uops_10_bits_lqIdx_flag,
  input  [6:0] io_fromDispatch_uops_10_bits_lqIdx_value,
  input  io_fromDispatch_uops_10_bits_sqIdx_flag,
  input  [5:0] io_fromDispatch_uops_10_bits_sqIdx_value,
  input  [4:0] io_fromDispatch_uops_10_bits_numLsElem,
  input  io_fromDispatch_uops_11_valid,
  input  io_fromDispatch_uops_11_bits_ftqPtr_flag,
  input  [5:0] io_fromDispatch_uops_11_bits_ftqPtr_value,
  input  [3:0] io_fromDispatch_uops_11_bits_ftqOffset,
  input  [3:0] io_fromDispatch_uops_11_bits_srcType_0,
  input  [3:0] io_fromDispatch_uops_11_bits_srcType_1,
  input  [3:0] io_fromDispatch_uops_11_bits_srcType_2,
  input  [3:0] io_fromDispatch_uops_11_bits_srcType_3,
  input  [3:0] io_fromDispatch_uops_11_bits_srcType_4,
  input  [34:0] io_fromDispatch_uops_11_bits_fuType,
  input  [8:0] io_fromDispatch_uops_11_bits_fuOpType,
  input  io_fromDispatch_uops_11_bits_vecWen,
  input  io_fromDispatch_uops_11_bits_v0Wen,
  input  io_fromDispatch_uops_11_bits_vlWen,
  input  io_fromDispatch_uops_11_bits_vpu_vma,
  input  io_fromDispatch_uops_11_bits_vpu_vta,
  input  [1:0] io_fromDispatch_uops_11_bits_vpu_vsew,
  input  [2:0] io_fromDispatch_uops_11_bits_vpu_vlmul,
  input  io_fromDispatch_uops_11_bits_vpu_vm,
  input  [7:0] io_fromDispatch_uops_11_bits_vpu_vstart,
  input  [127:0] io_fromDispatch_uops_11_bits_vpu_vmask,
  input  [2:0] io_fromDispatch_uops_11_bits_vpu_nf,
  input  [1:0] io_fromDispatch_uops_11_bits_vpu_veew,
  input  io_fromDispatch_uops_11_bits_vpu_isDependOldVd,
  input  io_fromDispatch_uops_11_bits_vpu_isWritePartVd,
  input  io_fromDispatch_uops_11_bits_vpu_isVleff,
  input  [6:0] io_fromDispatch_uops_11_bits_uopIdx,
  input  io_fromDispatch_uops_11_bits_lastUop,
  input  io_fromDispatch_uops_11_bits_srcState_0,
  input  io_fromDispatch_uops_11_bits_srcState_1,
  input  io_fromDispatch_uops_11_bits_srcState_2,
  input  io_fromDispatch_uops_11_bits_srcState_3,
  input  io_fromDispatch_uops_11_bits_srcState_4,
  input  [7:0] io_fromDispatch_uops_11_bits_psrc_0,
  input  [7:0] io_fromDispatch_uops_11_bits_psrc_1,
  input  [7:0] io_fromDispatch_uops_11_bits_psrc_2,
  input  [7:0] io_fromDispatch_uops_11_bits_psrc_3,
  input  [7:0] io_fromDispatch_uops_11_bits_psrc_4,
  input  [7:0] io_fromDispatch_uops_11_bits_pdest,
  input  io_fromDispatch_uops_11_bits_robIdx_flag,
  input  [7:0] io_fromDispatch_uops_11_bits_robIdx_value,
  input  io_fromDispatch_uops_11_bits_lqIdx_flag,
  input  [6:0] io_fromDispatch_uops_11_bits_lqIdx_value,
  input  io_fromDispatch_uops_11_bits_sqIdx_flag,
  input  [5:0] io_fromDispatch_uops_11_bits_sqIdx_value,
  input  [4:0] io_fromDispatch_uops_11_bits_numLsElem,
  output io_fromDispatch_uops_12_ready,
  input  io_fromDispatch_uops_12_valid,
  input  io_fromDispatch_uops_12_bits_ftqPtr_flag,
  input  [5:0] io_fromDispatch_uops_12_bits_ftqPtr_value,
  input  [3:0] io_fromDispatch_uops_12_bits_ftqOffset,
  input  [3:0] io_fromDispatch_uops_12_bits_srcType_0,
  input  [3:0] io_fromDispatch_uops_12_bits_srcType_1,
  input  [3:0] io_fromDispatch_uops_12_bits_srcType_2,
  input  [3:0] io_fromDispatch_uops_12_bits_srcType_3,
  input  [3:0] io_fromDispatch_uops_12_bits_srcType_4,
  input  [34:0] io_fromDispatch_uops_12_bits_fuType,
  input  [8:0] io_fromDispatch_uops_12_bits_fuOpType,
  input  io_fromDispatch_uops_12_bits_vecWen,
  input  io_fromDispatch_uops_12_bits_v0Wen,
  input  io_fromDispatch_uops_12_bits_vlWen,
  input  io_fromDispatch_uops_12_bits_vpu_vma,
  input  io_fromDispatch_uops_12_bits_vpu_vta,
  input  [1:0] io_fromDispatch_uops_12_bits_vpu_vsew,
  input  [2:0] io_fromDispatch_uops_12_bits_vpu_vlmul,
  input  io_fromDispatch_uops_12_bits_vpu_vm,
  input  [7:0] io_fromDispatch_uops_12_bits_vpu_vstart,
  input  [127:0] io_fromDispatch_uops_12_bits_vpu_vmask,
  input  [2:0] io_fromDispatch_uops_12_bits_vpu_nf,
  input  [1:0] io_fromDispatch_uops_12_bits_vpu_veew,
  input  io_fromDispatch_uops_12_bits_vpu_isDependOldVd,
  input  io_fromDispatch_uops_12_bits_vpu_isWritePartVd,
  input  io_fromDispatch_uops_12_bits_vpu_isVleff,
  input  [6:0] io_fromDispatch_uops_12_bits_uopIdx,
  input  io_fromDispatch_uops_12_bits_lastUop,
  input  io_fromDispatch_uops_12_bits_srcState_0,
  input  io_fromDispatch_uops_12_bits_srcState_1,
  input  io_fromDispatch_uops_12_bits_srcState_2,
  input  io_fromDispatch_uops_12_bits_srcState_3,
  input  io_fromDispatch_uops_12_bits_srcState_4,
  input  [7:0] io_fromDispatch_uops_12_bits_psrc_0,
  input  [7:0] io_fromDispatch_uops_12_bits_psrc_1,
  input  [7:0] io_fromDispatch_uops_12_bits_psrc_2,
  input  [7:0] io_fromDispatch_uops_12_bits_psrc_3,
  input  [7:0] io_fromDispatch_uops_12_bits_psrc_4,
  input  [7:0] io_fromDispatch_uops_12_bits_pdest,
  input  io_fromDispatch_uops_12_bits_robIdx_flag,
  input  [7:0] io_fromDispatch_uops_12_bits_robIdx_value,
  input  io_fromDispatch_uops_12_bits_lqIdx_flag,
  input  [6:0] io_fromDispatch_uops_12_bits_lqIdx_value,
  input  io_fromDispatch_uops_12_bits_sqIdx_flag,
  input  [5:0] io_fromDispatch_uops_12_bits_sqIdx_value,
  input  [4:0] io_fromDispatch_uops_12_bits_numLsElem,
  input  io_fromDispatch_uops_13_valid,
  input  io_fromDispatch_uops_13_bits_ftqPtr_flag,
  input  [5:0] io_fromDispatch_uops_13_bits_ftqPtr_value,
  input  [3:0] io_fromDispatch_uops_13_bits_ftqOffset,
  input  [3:0] io_fromDispatch_uops_13_bits_srcType_0,
  input  [3:0] io_fromDispatch_uops_13_bits_srcType_1,
  input  [3:0] io_fromDispatch_uops_13_bits_srcType_2,
  input  [3:0] io_fromDispatch_uops_13_bits_srcType_3,
  input  [3:0] io_fromDispatch_uops_13_bits_srcType_4,
  input  [34:0] io_fromDispatch_uops_13_bits_fuType,
  input  [8:0] io_fromDispatch_uops_13_bits_fuOpType,
  input  io_fromDispatch_uops_13_bits_vecWen,
  input  io_fromDispatch_uops_13_bits_v0Wen,
  input  io_fromDispatch_uops_13_bits_vlWen,
  input  io_fromDispatch_uops_13_bits_vpu_vma,
  input  io_fromDispatch_uops_13_bits_vpu_vta,
  input  [1:0] io_fromDispatch_uops_13_bits_vpu_vsew,
  input  [2:0] io_fromDispatch_uops_13_bits_vpu_vlmul,
  input  io_fromDispatch_uops_13_bits_vpu_vm,
  input  [7:0] io_fromDispatch_uops_13_bits_vpu_vstart,
  input  [127:0] io_fromDispatch_uops_13_bits_vpu_vmask,
  input  [2:0] io_fromDispatch_uops_13_bits_vpu_nf,
  input  [1:0] io_fromDispatch_uops_13_bits_vpu_veew,
  input  io_fromDispatch_uops_13_bits_vpu_isDependOldVd,
  input  io_fromDispatch_uops_13_bits_vpu_isWritePartVd,
  input  io_fromDispatch_uops_13_bits_vpu_isVleff,
  input  [6:0] io_fromDispatch_uops_13_bits_uopIdx,
  input  io_fromDispatch_uops_13_bits_lastUop,
  input  io_fromDispatch_uops_13_bits_srcState_0,
  input  io_fromDispatch_uops_13_bits_srcState_1,
  input  io_fromDispatch_uops_13_bits_srcState_2,
  input  io_fromDispatch_uops_13_bits_srcState_3,
  input  io_fromDispatch_uops_13_bits_srcState_4,
  input  [7:0] io_fromDispatch_uops_13_bits_psrc_0,
  input  [7:0] io_fromDispatch_uops_13_bits_psrc_1,
  input  [7:0] io_fromDispatch_uops_13_bits_psrc_2,
  input  [7:0] io_fromDispatch_uops_13_bits_psrc_3,
  input  [7:0] io_fromDispatch_uops_13_bits_psrc_4,
  input  [7:0] io_fromDispatch_uops_13_bits_pdest,
  input  io_fromDispatch_uops_13_bits_robIdx_flag,
  input  [7:0] io_fromDispatch_uops_13_bits_robIdx_value,
  input  io_fromDispatch_uops_13_bits_lqIdx_flag,
  input  [6:0] io_fromDispatch_uops_13_bits_lqIdx_value,
  input  io_fromDispatch_uops_13_bits_sqIdx_flag,
  input  [5:0] io_fromDispatch_uops_13_bits_sqIdx_value,
  input  [4:0] io_fromDispatch_uops_13_bits_numLsElem,
  input  io_intWriteBack_4_wen,
  input  [7:0] io_intWriteBack_4_addr,
  input  io_intWriteBack_4_intWen,
  input  io_intWriteBack_2_wen,
  input  [7:0] io_intWriteBack_2_addr,
  input  io_intWriteBack_2_intWen,
  input  io_intWriteBack_1_wen,
  input  [7:0] io_intWriteBack_1_addr,
  input  io_intWriteBack_1_intWen,
  input  io_intWriteBack_0_wen,
  input  [7:0] io_intWriteBack_0_addr,
  input  io_intWriteBack_0_intWen,
  input  io_fpWriteBack_5_wen,
  input  [7:0] io_fpWriteBack_5_addr,
  input  io_fpWriteBack_5_fpWen,
  input  io_fpWriteBack_4_wen,
  input  [7:0] io_fpWriteBack_4_addr,
  input  io_fpWriteBack_4_fpWen,
  input  io_fpWriteBack_3_wen,
  input  [7:0] io_fpWriteBack_3_addr,
  input  io_fpWriteBack_3_fpWen,
  input  io_fpWriteBack_2_wen,
  input  [7:0] io_fpWriteBack_2_addr,
  input  io_fpWriteBack_2_fpWen,
  input  io_fpWriteBack_1_wen,
  input  [7:0] io_fpWriteBack_1_addr,
  input  io_fpWriteBack_1_fpWen,
  input  io_fpWriteBack_0_wen,
  input  [7:0] io_fpWriteBack_0_addr,
  input  io_fpWriteBack_0_fpWen,
  input  io_vfWriteBack_5_wen,
  input  [6:0] io_vfWriteBack_5_addr,
  input  io_vfWriteBack_5_vecWen,
  input  io_vfWriteBack_4_wen,
  input  [6:0] io_vfWriteBack_4_addr,
  input  io_vfWriteBack_4_vecWen,
  input  io_vfWriteBack_3_wen,
  input  [6:0] io_vfWriteBack_3_addr,
  input  io_vfWriteBack_3_vecWen,
  input  io_vfWriteBack_2_wen,
  input  [6:0] io_vfWriteBack_2_addr,
  input  io_vfWriteBack_2_vecWen,
  input  io_vfWriteBack_1_wen,
  input  [6:0] io_vfWriteBack_1_addr,
  input  io_vfWriteBack_1_vecWen,
  input  io_vfWriteBack_0_wen,
  input  [6:0] io_vfWriteBack_0_addr,
  input  io_vfWriteBack_0_vecWen,
  input  io_v0WriteBack_5_wen,
  input  [4:0] io_v0WriteBack_5_addr,
  input  io_v0WriteBack_5_v0Wen,
  input  io_v0WriteBack_4_wen,
  input  [4:0] io_v0WriteBack_4_addr,
  input  io_v0WriteBack_4_v0Wen,
  input  io_v0WriteBack_3_wen,
  input  [4:0] io_v0WriteBack_3_addr,
  input  io_v0WriteBack_3_v0Wen,
  input  io_v0WriteBack_2_wen,
  input  [4:0] io_v0WriteBack_2_addr,
  input  io_v0WriteBack_2_v0Wen,
  input  io_v0WriteBack_1_wen,
  input  [4:0] io_v0WriteBack_1_addr,
  input  io_v0WriteBack_1_v0Wen,
  input  io_v0WriteBack_0_wen,
  input  [4:0] io_v0WriteBack_0_addr,
  input  io_v0WriteBack_0_v0Wen,
  input  io_vlWriteBack_3_wen,
  input  [4:0] io_vlWriteBack_3_addr,
  input  io_vlWriteBack_3_vlWen,
  input  io_vlWriteBack_2_wen,
  input  [4:0] io_vlWriteBack_2_addr,
  input  io_vlWriteBack_2_vlWen,
  input  io_vlWriteBack_1_wen,
  input  [4:0] io_vlWriteBack_1_addr,
  input  io_vlWriteBack_1_vlWen,
  input  io_vlWriteBack_0_wen,
  input  [4:0] io_vlWriteBack_0_addr,
  input  io_vlWriteBack_0_vlWen,
  input  io_intWriteBackDelayed_4_wen,
  input  [7:0] io_intWriteBackDelayed_4_addr,
  input  io_intWriteBackDelayed_4_intWen,
  input  io_intWriteBackDelayed_2_wen,
  input  [7:0] io_intWriteBackDelayed_2_addr,
  input  io_intWriteBackDelayed_2_intWen,
  input  io_intWriteBackDelayed_1_wen,
  input  [7:0] io_intWriteBackDelayed_1_addr,
  input  io_intWriteBackDelayed_1_intWen,
  input  io_intWriteBackDelayed_0_wen,
  input  [7:0] io_intWriteBackDelayed_0_addr,
  input  io_intWriteBackDelayed_0_intWen,
  input  io_fpWriteBackDelayed_5_wen,
  input  [7:0] io_fpWriteBackDelayed_5_addr,
  input  io_fpWriteBackDelayed_5_fpWen,
  input  io_fpWriteBackDelayed_4_wen,
  input  [7:0] io_fpWriteBackDelayed_4_addr,
  input  io_fpWriteBackDelayed_4_fpWen,
  input  io_fpWriteBackDelayed_3_wen,
  input  [7:0] io_fpWriteBackDelayed_3_addr,
  input  io_fpWriteBackDelayed_3_fpWen,
  input  io_fpWriteBackDelayed_2_wen,
  input  [7:0] io_fpWriteBackDelayed_2_addr,
  input  io_fpWriteBackDelayed_2_fpWen,
  input  io_fpWriteBackDelayed_1_wen,
  input  [7:0] io_fpWriteBackDelayed_1_addr,
  input  io_fpWriteBackDelayed_1_fpWen,
  input  io_fpWriteBackDelayed_0_wen,
  input  [7:0] io_fpWriteBackDelayed_0_addr,
  input  io_fpWriteBackDelayed_0_fpWen,
  input  io_vfWriteBackDelayed_5_wen,
  input  [6:0] io_vfWriteBackDelayed_5_addr,
  input  io_vfWriteBackDelayed_5_vecWen,
  input  io_vfWriteBackDelayed_4_wen,
  input  [6:0] io_vfWriteBackDelayed_4_addr,
  input  io_vfWriteBackDelayed_4_vecWen,
  input  io_vfWriteBackDelayed_3_wen,
  input  [6:0] io_vfWriteBackDelayed_3_addr,
  input  io_vfWriteBackDelayed_3_vecWen,
  input  io_vfWriteBackDelayed_2_wen,
  input  [6:0] io_vfWriteBackDelayed_2_addr,
  input  io_vfWriteBackDelayed_2_vecWen,
  input  io_vfWriteBackDelayed_1_wen,
  input  [6:0] io_vfWriteBackDelayed_1_addr,
  input  io_vfWriteBackDelayed_1_vecWen,
  input  io_vfWriteBackDelayed_0_wen,
  input  [6:0] io_vfWriteBackDelayed_0_addr,
  input  io_vfWriteBackDelayed_0_vecWen,
  input  io_v0WriteBackDelayed_5_wen,
  input  [4:0] io_v0WriteBackDelayed_5_addr,
  input  io_v0WriteBackDelayed_5_v0Wen,
  input  io_v0WriteBackDelayed_4_wen,
  input  [4:0] io_v0WriteBackDelayed_4_addr,
  input  io_v0WriteBackDelayed_4_v0Wen,
  input  io_v0WriteBackDelayed_3_wen,
  input  [4:0] io_v0WriteBackDelayed_3_addr,
  input  io_v0WriteBackDelayed_3_v0Wen,
  input  io_v0WriteBackDelayed_2_wen,
  input  [4:0] io_v0WriteBackDelayed_2_addr,
  input  io_v0WriteBackDelayed_2_v0Wen,
  input  io_v0WriteBackDelayed_1_wen,
  input  [4:0] io_v0WriteBackDelayed_1_addr,
  input  io_v0WriteBackDelayed_1_v0Wen,
  input  io_v0WriteBackDelayed_0_wen,
  input  [4:0] io_v0WriteBackDelayed_0_addr,
  input  io_v0WriteBackDelayed_0_v0Wen,
  input  io_vlWriteBackDelayed_3_wen,
  input  [4:0] io_vlWriteBackDelayed_3_addr,
  input  io_vlWriteBackDelayed_3_vlWen,
  input  io_vlWriteBackDelayed_2_wen,
  input  [4:0] io_vlWriteBackDelayed_2_addr,
  input  io_vlWriteBackDelayed_2_vlWen,
  input  io_vlWriteBackDelayed_1_wen,
  input  [4:0] io_vlWriteBackDelayed_1_addr,
  input  io_vlWriteBackDelayed_1_vlWen,
  input  io_vlWriteBackDelayed_0_wen,
  input  [4:0] io_vlWriteBackDelayed_0_addr,
  input  io_vlWriteBackDelayed_0_vlWen,
  input  io_toDataPathAfterDelay_8_0_ready,
  output io_toDataPathAfterDelay_8_0_valid,
  output [7:0] io_toDataPathAfterDelay_8_0_bits_rf_0_0_addr,
  output [3:0] io_toDataPathAfterDelay_8_0_bits_srcType_0,
  output [4:0] io_toDataPathAfterDelay_8_0_bits_rcIdx_0,
  output [34:0] io_toDataPathAfterDelay_8_0_bits_common_fuType,
  output [8:0] io_toDataPathAfterDelay_8_0_bits_common_fuOpType,
  output io_toDataPathAfterDelay_8_0_bits_common_robIdx_flag,
  output [7:0] io_toDataPathAfterDelay_8_0_bits_common_robIdx_value,
  output io_toDataPathAfterDelay_8_0_bits_common_sqIdx_flag,
  output [5:0] io_toDataPathAfterDelay_8_0_bits_common_sqIdx_value,
  output [3:0] io_toDataPathAfterDelay_8_0_bits_common_dataSources_0_value,
  output [2:0] io_toDataPathAfterDelay_8_0_bits_common_exuSources_0_value,
  output [1:0] io_toDataPathAfterDelay_8_0_bits_common_loadDependency_0,
  output [1:0] io_toDataPathAfterDelay_8_0_bits_common_loadDependency_1,
  output [1:0] io_toDataPathAfterDelay_8_0_bits_common_loadDependency_2,
  input  io_toDataPathAfterDelay_7_0_ready,
  output io_toDataPathAfterDelay_7_0_valid,
  output [7:0] io_toDataPathAfterDelay_7_0_bits_rf_0_0_addr,
  output [3:0] io_toDataPathAfterDelay_7_0_bits_srcType_0,
  output [4:0] io_toDataPathAfterDelay_7_0_bits_rcIdx_0,
  output [34:0] io_toDataPathAfterDelay_7_0_bits_common_fuType,
  output [8:0] io_toDataPathAfterDelay_7_0_bits_common_fuOpType,
  output io_toDataPathAfterDelay_7_0_bits_common_robIdx_flag,
  output [7:0] io_toDataPathAfterDelay_7_0_bits_common_robIdx_value,
  output io_toDataPathAfterDelay_7_0_bits_common_sqIdx_flag,
  output [5:0] io_toDataPathAfterDelay_7_0_bits_common_sqIdx_value,
  output [3:0] io_toDataPathAfterDelay_7_0_bits_common_dataSources_0_value,
  output [2:0] io_toDataPathAfterDelay_7_0_bits_common_exuSources_0_value,
  output [1:0] io_toDataPathAfterDelay_7_0_bits_common_loadDependency_0,
  output [1:0] io_toDataPathAfterDelay_7_0_bits_common_loadDependency_1,
  output [1:0] io_toDataPathAfterDelay_7_0_bits_common_loadDependency_2,
  input  io_toDataPathAfterDelay_6_0_ready,
  output io_toDataPathAfterDelay_6_0_valid,
  output [6:0] io_toDataPathAfterDelay_6_0_bits_rf_4_0_addr,
  output [6:0] io_toDataPathAfterDelay_6_0_bits_rf_3_0_addr,
  output [6:0] io_toDataPathAfterDelay_6_0_bits_rf_2_0_addr,
  output [6:0] io_toDataPathAfterDelay_6_0_bits_rf_1_0_addr,
  output [6:0] io_toDataPathAfterDelay_6_0_bits_rf_0_0_addr,
  output [34:0] io_toDataPathAfterDelay_6_0_bits_common_fuType,
  output [8:0] io_toDataPathAfterDelay_6_0_bits_common_fuOpType,
  output io_toDataPathAfterDelay_6_0_bits_common_robIdx_flag,
  output [7:0] io_toDataPathAfterDelay_6_0_bits_common_robIdx_value,
  output [6:0] io_toDataPathAfterDelay_6_0_bits_common_pdest,
  output io_toDataPathAfterDelay_6_0_bits_common_vecWen,
  output io_toDataPathAfterDelay_6_0_bits_common_v0Wen,
  output io_toDataPathAfterDelay_6_0_bits_common_vlWen,
  output io_toDataPathAfterDelay_6_0_bits_common_vpu_vma,
  output io_toDataPathAfterDelay_6_0_bits_common_vpu_vta,
  output [1:0] io_toDataPathAfterDelay_6_0_bits_common_vpu_vsew,
  output [2:0] io_toDataPathAfterDelay_6_0_bits_common_vpu_vlmul,
  output io_toDataPathAfterDelay_6_0_bits_common_vpu_vm,
  output [7:0] io_toDataPathAfterDelay_6_0_bits_common_vpu_vstart,
  output [6:0] io_toDataPathAfterDelay_6_0_bits_common_vpu_vuopIdx,
  output io_toDataPathAfterDelay_6_0_bits_common_vpu_lastUop,
  output [127:0] io_toDataPathAfterDelay_6_0_bits_common_vpu_vmask,
  output [2:0] io_toDataPathAfterDelay_6_0_bits_common_vpu_nf,
  output [1:0] io_toDataPathAfterDelay_6_0_bits_common_vpu_veew,
  output io_toDataPathAfterDelay_6_0_bits_common_vpu_isVleff,
  output io_toDataPathAfterDelay_6_0_bits_common_ftqIdx_flag,
  output [5:0] io_toDataPathAfterDelay_6_0_bits_common_ftqIdx_value,
  output [3:0] io_toDataPathAfterDelay_6_0_bits_common_ftqOffset,
  output [4:0] io_toDataPathAfterDelay_6_0_bits_common_numLsElem,
  output io_toDataPathAfterDelay_6_0_bits_common_sqIdx_flag,
  output [5:0] io_toDataPathAfterDelay_6_0_bits_common_sqIdx_value,
  output io_toDataPathAfterDelay_6_0_bits_common_lqIdx_flag,
  output [6:0] io_toDataPathAfterDelay_6_0_bits_common_lqIdx_value,
  output [3:0] io_toDataPathAfterDelay_6_0_bits_common_dataSources_0_value,
  output [3:0] io_toDataPathAfterDelay_6_0_bits_common_dataSources_1_value,
  output [3:0] io_toDataPathAfterDelay_6_0_bits_common_dataSources_2_value,
  output [3:0] io_toDataPathAfterDelay_6_0_bits_common_dataSources_3_value,
  output [3:0] io_toDataPathAfterDelay_6_0_bits_common_dataSources_4_value,
  input  io_toDataPathAfterDelay_5_0_ready,
  output io_toDataPathAfterDelay_5_0_valid,
  output [6:0] io_toDataPathAfterDelay_5_0_bits_rf_4_0_addr,
  output [6:0] io_toDataPathAfterDelay_5_0_bits_rf_3_0_addr,
  output [6:0] io_toDataPathAfterDelay_5_0_bits_rf_2_0_addr,
  output [6:0] io_toDataPathAfterDelay_5_0_bits_rf_1_0_addr,
  output [6:0] io_toDataPathAfterDelay_5_0_bits_rf_0_0_addr,
  output [34:0] io_toDataPathAfterDelay_5_0_bits_common_fuType,
  output [8:0] io_toDataPathAfterDelay_5_0_bits_common_fuOpType,
  output io_toDataPathAfterDelay_5_0_bits_common_robIdx_flag,
  output [7:0] io_toDataPathAfterDelay_5_0_bits_common_robIdx_value,
  output [6:0] io_toDataPathAfterDelay_5_0_bits_common_pdest,
  output io_toDataPathAfterDelay_5_0_bits_common_vecWen,
  output io_toDataPathAfterDelay_5_0_bits_common_v0Wen,
  output io_toDataPathAfterDelay_5_0_bits_common_vlWen,
  output io_toDataPathAfterDelay_5_0_bits_common_vpu_vma,
  output io_toDataPathAfterDelay_5_0_bits_common_vpu_vta,
  output [1:0] io_toDataPathAfterDelay_5_0_bits_common_vpu_vsew,
  output [2:0] io_toDataPathAfterDelay_5_0_bits_common_vpu_vlmul,
  output io_toDataPathAfterDelay_5_0_bits_common_vpu_vm,
  output [7:0] io_toDataPathAfterDelay_5_0_bits_common_vpu_vstart,
  output [6:0] io_toDataPathAfterDelay_5_0_bits_common_vpu_vuopIdx,
  output io_toDataPathAfterDelay_5_0_bits_common_vpu_lastUop,
  output [127:0] io_toDataPathAfterDelay_5_0_bits_common_vpu_vmask,
  output [2:0] io_toDataPathAfterDelay_5_0_bits_common_vpu_nf,
  output [1:0] io_toDataPathAfterDelay_5_0_bits_common_vpu_veew,
  output io_toDataPathAfterDelay_5_0_bits_common_vpu_isVleff,
  output io_toDataPathAfterDelay_5_0_bits_common_ftqIdx_flag,
  output [5:0] io_toDataPathAfterDelay_5_0_bits_common_ftqIdx_value,
  output [3:0] io_toDataPathAfterDelay_5_0_bits_common_ftqOffset,
  output [4:0] io_toDataPathAfterDelay_5_0_bits_common_numLsElem,
  output io_toDataPathAfterDelay_5_0_bits_common_sqIdx_flag,
  output [5:0] io_toDataPathAfterDelay_5_0_bits_common_sqIdx_value,
  output io_toDataPathAfterDelay_5_0_bits_common_lqIdx_flag,
  output [6:0] io_toDataPathAfterDelay_5_0_bits_common_lqIdx_value,
  output [3:0] io_toDataPathAfterDelay_5_0_bits_common_dataSources_0_value,
  output [3:0] io_toDataPathAfterDelay_5_0_bits_common_dataSources_1_value,
  output [3:0] io_toDataPathAfterDelay_5_0_bits_common_dataSources_2_value,
  output [3:0] io_toDataPathAfterDelay_5_0_bits_common_dataSources_3_value,
  output [3:0] io_toDataPathAfterDelay_5_0_bits_common_dataSources_4_value,
  input  io_toDataPathAfterDelay_4_0_ready,
  output io_toDataPathAfterDelay_4_0_valid,
  output [7:0] io_toDataPathAfterDelay_4_0_bits_rf_0_0_addr,
  output [4:0] io_toDataPathAfterDelay_4_0_bits_rcIdx_0,
  output [34:0] io_toDataPathAfterDelay_4_0_bits_common_fuType,
  output [8:0] io_toDataPathAfterDelay_4_0_bits_common_fuOpType,
  output [63:0] io_toDataPathAfterDelay_4_0_bits_common_imm,
  output io_toDataPathAfterDelay_4_0_bits_common_robIdx_flag,
  output [7:0] io_toDataPathAfterDelay_4_0_bits_common_robIdx_value,
  output [7:0] io_toDataPathAfterDelay_4_0_bits_common_pdest,
  output io_toDataPathAfterDelay_4_0_bits_common_rfWen,
  output io_toDataPathAfterDelay_4_0_bits_common_fpWen,
  output io_toDataPathAfterDelay_4_0_bits_common_preDecode_isRVC,
  output io_toDataPathAfterDelay_4_0_bits_common_ftqIdx_flag,
  output [5:0] io_toDataPathAfterDelay_4_0_bits_common_ftqIdx_value,
  output [3:0] io_toDataPathAfterDelay_4_0_bits_common_ftqOffset,
  output io_toDataPathAfterDelay_4_0_bits_common_loadWaitBit,
  output io_toDataPathAfterDelay_4_0_bits_common_waitForRobIdx_flag,
  output [7:0] io_toDataPathAfterDelay_4_0_bits_common_waitForRobIdx_value,
  output io_toDataPathAfterDelay_4_0_bits_common_storeSetHit,
  output io_toDataPathAfterDelay_4_0_bits_common_loadWaitStrict,
  output io_toDataPathAfterDelay_4_0_bits_common_sqIdx_flag,
  output [5:0] io_toDataPathAfterDelay_4_0_bits_common_sqIdx_value,
  output io_toDataPathAfterDelay_4_0_bits_common_lqIdx_flag,
  output [6:0] io_toDataPathAfterDelay_4_0_bits_common_lqIdx_value,
  output [3:0] io_toDataPathAfterDelay_4_0_bits_common_dataSources_0_value,
  output [2:0] io_toDataPathAfterDelay_4_0_bits_common_exuSources_0_value,
  output [1:0] io_toDataPathAfterDelay_4_0_bits_common_loadDependency_0,
  output [1:0] io_toDataPathAfterDelay_4_0_bits_common_loadDependency_1,
  output [1:0] io_toDataPathAfterDelay_4_0_bits_common_loadDependency_2,
  input  io_toDataPathAfterDelay_3_0_ready,
  output io_toDataPathAfterDelay_3_0_valid,
  output [7:0] io_toDataPathAfterDelay_3_0_bits_rf_0_0_addr,
  output [4:0] io_toDataPathAfterDelay_3_0_bits_rcIdx_0,
  output [34:0] io_toDataPathAfterDelay_3_0_bits_common_fuType,
  output [8:0] io_toDataPathAfterDelay_3_0_bits_common_fuOpType,
  output [63:0] io_toDataPathAfterDelay_3_0_bits_common_imm,
  output io_toDataPathAfterDelay_3_0_bits_common_robIdx_flag,
  output [7:0] io_toDataPathAfterDelay_3_0_bits_common_robIdx_value,
  output [7:0] io_toDataPathAfterDelay_3_0_bits_common_pdest,
  output io_toDataPathAfterDelay_3_0_bits_common_rfWen,
  output io_toDataPathAfterDelay_3_0_bits_common_fpWen,
  output io_toDataPathAfterDelay_3_0_bits_common_preDecode_isRVC,
  output io_toDataPathAfterDelay_3_0_bits_common_ftqIdx_flag,
  output [5:0] io_toDataPathAfterDelay_3_0_bits_common_ftqIdx_value,
  output [3:0] io_toDataPathAfterDelay_3_0_bits_common_ftqOffset,
  output io_toDataPathAfterDelay_3_0_bits_common_loadWaitBit,
  output io_toDataPathAfterDelay_3_0_bits_common_waitForRobIdx_flag,
  output [7:0] io_toDataPathAfterDelay_3_0_bits_common_waitForRobIdx_value,
  output io_toDataPathAfterDelay_3_0_bits_common_storeSetHit,
  output io_toDataPathAfterDelay_3_0_bits_common_loadWaitStrict,
  output io_toDataPathAfterDelay_3_0_bits_common_sqIdx_flag,
  output [5:0] io_toDataPathAfterDelay_3_0_bits_common_sqIdx_value,
  output io_toDataPathAfterDelay_3_0_bits_common_lqIdx_flag,
  output [6:0] io_toDataPathAfterDelay_3_0_bits_common_lqIdx_value,
  output [3:0] io_toDataPathAfterDelay_3_0_bits_common_dataSources_0_value,
  output [2:0] io_toDataPathAfterDelay_3_0_bits_common_exuSources_0_value,
  output [1:0] io_toDataPathAfterDelay_3_0_bits_common_loadDependency_0,
  output [1:0] io_toDataPathAfterDelay_3_0_bits_common_loadDependency_1,
  output [1:0] io_toDataPathAfterDelay_3_0_bits_common_loadDependency_2,
  input  io_toDataPathAfterDelay_2_0_ready,
  output io_toDataPathAfterDelay_2_0_valid,
  output [7:0] io_toDataPathAfterDelay_2_0_bits_rf_0_0_addr,
  output [4:0] io_toDataPathAfterDelay_2_0_bits_rcIdx_0,
  output [34:0] io_toDataPathAfterDelay_2_0_bits_common_fuType,
  output [8:0] io_toDataPathAfterDelay_2_0_bits_common_fuOpType,
  output [63:0] io_toDataPathAfterDelay_2_0_bits_common_imm,
  output io_toDataPathAfterDelay_2_0_bits_common_robIdx_flag,
  output [7:0] io_toDataPathAfterDelay_2_0_bits_common_robIdx_value,
  output [7:0] io_toDataPathAfterDelay_2_0_bits_common_pdest,
  output io_toDataPathAfterDelay_2_0_bits_common_rfWen,
  output io_toDataPathAfterDelay_2_0_bits_common_fpWen,
  output io_toDataPathAfterDelay_2_0_bits_common_preDecode_isRVC,
  output io_toDataPathAfterDelay_2_0_bits_common_ftqIdx_flag,
  output [5:0] io_toDataPathAfterDelay_2_0_bits_common_ftqIdx_value,
  output [3:0] io_toDataPathAfterDelay_2_0_bits_common_ftqOffset,
  output io_toDataPathAfterDelay_2_0_bits_common_loadWaitBit,
  output io_toDataPathAfterDelay_2_0_bits_common_waitForRobIdx_flag,
  output [7:0] io_toDataPathAfterDelay_2_0_bits_common_waitForRobIdx_value,
  output io_toDataPathAfterDelay_2_0_bits_common_storeSetHit,
  output io_toDataPathAfterDelay_2_0_bits_common_loadWaitStrict,
  output io_toDataPathAfterDelay_2_0_bits_common_sqIdx_flag,
  output [5:0] io_toDataPathAfterDelay_2_0_bits_common_sqIdx_value,
  output io_toDataPathAfterDelay_2_0_bits_common_lqIdx_flag,
  output [6:0] io_toDataPathAfterDelay_2_0_bits_common_lqIdx_value,
  output [3:0] io_toDataPathAfterDelay_2_0_bits_common_dataSources_0_value,
  output [2:0] io_toDataPathAfterDelay_2_0_bits_common_exuSources_0_value,
  output [1:0] io_toDataPathAfterDelay_2_0_bits_common_loadDependency_0,
  output [1:0] io_toDataPathAfterDelay_2_0_bits_common_loadDependency_1,
  output [1:0] io_toDataPathAfterDelay_2_0_bits_common_loadDependency_2,
  input  io_toDataPathAfterDelay_1_0_ready,
  output io_toDataPathAfterDelay_1_0_valid,
  output [7:0] io_toDataPathAfterDelay_1_0_bits_rf_0_0_addr,
  output [4:0] io_toDataPathAfterDelay_1_0_bits_rcIdx_0,
  output [3:0] io_toDataPathAfterDelay_1_0_bits_immType,
  output [34:0] io_toDataPathAfterDelay_1_0_bits_common_fuType,
  output [8:0] io_toDataPathAfterDelay_1_0_bits_common_fuOpType,
  output [63:0] io_toDataPathAfterDelay_1_0_bits_common_imm,
  output io_toDataPathAfterDelay_1_0_bits_common_robIdx_flag,
  output [7:0] io_toDataPathAfterDelay_1_0_bits_common_robIdx_value,
  output io_toDataPathAfterDelay_1_0_bits_common_isFirstIssue,
  output [7:0] io_toDataPathAfterDelay_1_0_bits_common_pdest,
  output io_toDataPathAfterDelay_1_0_bits_common_rfWen,
  output [5:0] io_toDataPathAfterDelay_1_0_bits_common_ftqIdx_value,
  output [3:0] io_toDataPathAfterDelay_1_0_bits_common_ftqOffset,
  output io_toDataPathAfterDelay_1_0_bits_common_sqIdx_flag,
  output [5:0] io_toDataPathAfterDelay_1_0_bits_common_sqIdx_value,
  output [3:0] io_toDataPathAfterDelay_1_0_bits_common_dataSources_0_value,
  output [2:0] io_toDataPathAfterDelay_1_0_bits_common_exuSources_0_value,
  output [1:0] io_toDataPathAfterDelay_1_0_bits_common_loadDependency_0,
  output [1:0] io_toDataPathAfterDelay_1_0_bits_common_loadDependency_1,
  output [1:0] io_toDataPathAfterDelay_1_0_bits_common_loadDependency_2,
  input  io_toDataPathAfterDelay_0_0_ready,
  output io_toDataPathAfterDelay_0_0_valid,
  output [7:0] io_toDataPathAfterDelay_0_0_bits_rf_0_0_addr,
  output [4:0] io_toDataPathAfterDelay_0_0_bits_rcIdx_0,
  output [3:0] io_toDataPathAfterDelay_0_0_bits_immType,
  output [34:0] io_toDataPathAfterDelay_0_0_bits_common_fuType,
  output [8:0] io_toDataPathAfterDelay_0_0_bits_common_fuOpType,
  output [63:0] io_toDataPathAfterDelay_0_0_bits_common_imm,
  output io_toDataPathAfterDelay_0_0_bits_common_robIdx_flag,
  output [7:0] io_toDataPathAfterDelay_0_0_bits_common_robIdx_value,
  output io_toDataPathAfterDelay_0_0_bits_common_isFirstIssue,
  output [7:0] io_toDataPathAfterDelay_0_0_bits_common_pdest,
  output io_toDataPathAfterDelay_0_0_bits_common_rfWen,
  output [5:0] io_toDataPathAfterDelay_0_0_bits_common_ftqIdx_value,
  output [3:0] io_toDataPathAfterDelay_0_0_bits_common_ftqOffset,
  output io_toDataPathAfterDelay_0_0_bits_common_sqIdx_flag,
  output [5:0] io_toDataPathAfterDelay_0_0_bits_common_sqIdx_value,
  output [3:0] io_toDataPathAfterDelay_0_0_bits_common_dataSources_0_value,
  output [2:0] io_toDataPathAfterDelay_0_0_bits_common_exuSources_0_value,
  output [1:0] io_toDataPathAfterDelay_0_0_bits_common_loadDependency_0,
  output [1:0] io_toDataPathAfterDelay_0_0_bits_common_loadDependency_1,
  output [1:0] io_toDataPathAfterDelay_0_0_bits_common_loadDependency_2,
  input  io_vlWriteBackInfo_vlFromIntIsZero,
  input  io_vlWriteBackInfo_vlFromIntIsVlmax,
  input  io_vlWriteBackInfo_vlFromVfIsZero,
  input  io_vlWriteBackInfo_vlFromVfIsVlmax,
  input  [4:0] io_fromSchedulers_wakeupVec_6_bits_rcDest,
  input  [7:0] io_fromSchedulers_wakeupVec_6_bits_pdestCopy_2,
  input  [7:0] io_fromSchedulers_wakeupVec_6_bits_pdestCopy_3,
  input  [7:0] io_fromSchedulers_wakeupVec_6_bits_pdestCopy_4,
  input  [7:0] io_fromSchedulers_wakeupVec_6_bits_pdestCopy_5,
  input  io_fromSchedulers_wakeupVec_6_bits_rfWenCopy_2,
  input  io_fromSchedulers_wakeupVec_6_bits_rfWenCopy_3,
  input  io_fromSchedulers_wakeupVec_6_bits_rfWenCopy_4,
  input  io_fromSchedulers_wakeupVec_6_bits_rfWenCopy_5,
  input  [4:0] io_fromSchedulers_wakeupVec_5_bits_rcDest,
  input  [7:0] io_fromSchedulers_wakeupVec_5_bits_pdestCopy_2,
  input  [7:0] io_fromSchedulers_wakeupVec_5_bits_pdestCopy_3,
  input  [7:0] io_fromSchedulers_wakeupVec_5_bits_pdestCopy_4,
  input  [7:0] io_fromSchedulers_wakeupVec_5_bits_pdestCopy_5,
  input  io_fromSchedulers_wakeupVec_5_bits_rfWenCopy_2,
  input  io_fromSchedulers_wakeupVec_5_bits_rfWenCopy_3,
  input  io_fromSchedulers_wakeupVec_5_bits_rfWenCopy_4,
  input  io_fromSchedulers_wakeupVec_5_bits_rfWenCopy_5,
  input  [4:0] io_fromSchedulers_wakeupVec_4_bits_rcDest,
  input  [7:0] io_fromSchedulers_wakeupVec_4_bits_pdestCopy_2,
  input  [7:0] io_fromSchedulers_wakeupVec_4_bits_pdestCopy_3,
  input  [7:0] io_fromSchedulers_wakeupVec_4_bits_pdestCopy_4,
  input  [7:0] io_fromSchedulers_wakeupVec_4_bits_pdestCopy_5,
  input  io_fromSchedulers_wakeupVec_4_bits_rfWenCopy_2,
  input  io_fromSchedulers_wakeupVec_4_bits_rfWenCopy_3,
  input  io_fromSchedulers_wakeupVec_4_bits_rfWenCopy_4,
  input  io_fromSchedulers_wakeupVec_4_bits_rfWenCopy_5,
  input  [4:0] io_fromSchedulers_wakeupVec_3_bits_rcDest,
  input  [7:0] io_fromSchedulers_wakeupVec_3_bits_pdestCopy_2,
  input  [7:0] io_fromSchedulers_wakeupVec_3_bits_pdestCopy_3,
  input  [7:0] io_fromSchedulers_wakeupVec_3_bits_pdestCopy_4,
  input  [7:0] io_fromSchedulers_wakeupVec_3_bits_pdestCopy_5,
  input  io_fromSchedulers_wakeupVec_3_bits_rfWenCopy_2,
  input  io_fromSchedulers_wakeupVec_3_bits_rfWenCopy_3,
  input  io_fromSchedulers_wakeupVec_3_bits_rfWenCopy_4,
  input  io_fromSchedulers_wakeupVec_3_bits_rfWenCopy_5,
  input  [1:0] io_fromSchedulers_wakeupVec_3_bits_loadDependencyCopy_2_0,
  input  [1:0] io_fromSchedulers_wakeupVec_3_bits_loadDependencyCopy_2_1,
  input  [1:0] io_fromSchedulers_wakeupVec_3_bits_loadDependencyCopy_2_2,
  input  [1:0] io_fromSchedulers_wakeupVec_3_bits_loadDependencyCopy_3_0,
  input  [1:0] io_fromSchedulers_wakeupVec_3_bits_loadDependencyCopy_3_1,
  input  [1:0] io_fromSchedulers_wakeupVec_3_bits_loadDependencyCopy_3_2,
  input  [1:0] io_fromSchedulers_wakeupVec_3_bits_loadDependencyCopy_4_0,
  input  [1:0] io_fromSchedulers_wakeupVec_3_bits_loadDependencyCopy_4_1,
  input  [1:0] io_fromSchedulers_wakeupVec_3_bits_loadDependencyCopy_4_2,
  input  [1:0] io_fromSchedulers_wakeupVec_3_bits_loadDependencyCopy_5_0,
  input  [1:0] io_fromSchedulers_wakeupVec_3_bits_loadDependencyCopy_5_1,
  input  [1:0] io_fromSchedulers_wakeupVec_3_bits_loadDependencyCopy_5_2,
  input  [4:0] io_fromSchedulers_wakeupVec_2_bits_rcDest,
  input  [7:0] io_fromSchedulers_wakeupVec_2_bits_pdestCopy_2,
  input  [7:0] io_fromSchedulers_wakeupVec_2_bits_pdestCopy_3,
  input  [7:0] io_fromSchedulers_wakeupVec_2_bits_pdestCopy_4,
  input  [7:0] io_fromSchedulers_wakeupVec_2_bits_pdestCopy_5,
  input  io_fromSchedulers_wakeupVec_2_bits_rfWenCopy_2,
  input  io_fromSchedulers_wakeupVec_2_bits_rfWenCopy_3,
  input  io_fromSchedulers_wakeupVec_2_bits_rfWenCopy_4,
  input  io_fromSchedulers_wakeupVec_2_bits_rfWenCopy_5,
  input  [1:0] io_fromSchedulers_wakeupVec_2_bits_loadDependencyCopy_2_0,
  input  [1:0] io_fromSchedulers_wakeupVec_2_bits_loadDependencyCopy_2_1,
  input  [1:0] io_fromSchedulers_wakeupVec_2_bits_loadDependencyCopy_2_2,
  input  [1:0] io_fromSchedulers_wakeupVec_2_bits_loadDependencyCopy_3_0,
  input  [1:0] io_fromSchedulers_wakeupVec_2_bits_loadDependencyCopy_3_1,
  input  [1:0] io_fromSchedulers_wakeupVec_2_bits_loadDependencyCopy_3_2,
  input  [1:0] io_fromSchedulers_wakeupVec_2_bits_loadDependencyCopy_4_0,
  input  [1:0] io_fromSchedulers_wakeupVec_2_bits_loadDependencyCopy_4_1,
  input  [1:0] io_fromSchedulers_wakeupVec_2_bits_loadDependencyCopy_4_2,
  input  [1:0] io_fromSchedulers_wakeupVec_2_bits_loadDependencyCopy_5_0,
  input  [1:0] io_fromSchedulers_wakeupVec_2_bits_loadDependencyCopy_5_1,
  input  [1:0] io_fromSchedulers_wakeupVec_2_bits_loadDependencyCopy_5_2,
  input  io_fromSchedulers_wakeupVec_1_bits_is0Lat,
  input  [4:0] io_fromSchedulers_wakeupVec_1_bits_rcDest,
  input  [7:0] io_fromSchedulers_wakeupVec_1_bits_pdestCopy_2,
  input  [7:0] io_fromSchedulers_wakeupVec_1_bits_pdestCopy_3,
  input  [7:0] io_fromSchedulers_wakeupVec_1_bits_pdestCopy_4,
  input  [7:0] io_fromSchedulers_wakeupVec_1_bits_pdestCopy_5,
  input  io_fromSchedulers_wakeupVec_1_bits_rfWenCopy_2,
  input  io_fromSchedulers_wakeupVec_1_bits_rfWenCopy_3,
  input  io_fromSchedulers_wakeupVec_1_bits_rfWenCopy_4,
  input  io_fromSchedulers_wakeupVec_1_bits_rfWenCopy_5,
  input  [1:0] io_fromSchedulers_wakeupVec_1_bits_loadDependencyCopy_2_0,
  input  [1:0] io_fromSchedulers_wakeupVec_1_bits_loadDependencyCopy_2_1,
  input  [1:0] io_fromSchedulers_wakeupVec_1_bits_loadDependencyCopy_2_2,
  input  [1:0] io_fromSchedulers_wakeupVec_1_bits_loadDependencyCopy_3_0,
  input  [1:0] io_fromSchedulers_wakeupVec_1_bits_loadDependencyCopy_3_1,
  input  [1:0] io_fromSchedulers_wakeupVec_1_bits_loadDependencyCopy_3_2,
  input  [1:0] io_fromSchedulers_wakeupVec_1_bits_loadDependencyCopy_4_0,
  input  [1:0] io_fromSchedulers_wakeupVec_1_bits_loadDependencyCopy_4_1,
  input  [1:0] io_fromSchedulers_wakeupVec_1_bits_loadDependencyCopy_4_2,
  input  [1:0] io_fromSchedulers_wakeupVec_1_bits_loadDependencyCopy_5_0,
  input  [1:0] io_fromSchedulers_wakeupVec_1_bits_loadDependencyCopy_5_1,
  input  [1:0] io_fromSchedulers_wakeupVec_1_bits_loadDependencyCopy_5_2,
  input  io_fromSchedulers_wakeupVec_0_bits_is0Lat,
  input  [4:0] io_fromSchedulers_wakeupVec_0_bits_rcDest,
  input  [7:0] io_fromSchedulers_wakeupVec_0_bits_pdestCopy_2,
  input  [7:0] io_fromSchedulers_wakeupVec_0_bits_pdestCopy_3,
  input  [7:0] io_fromSchedulers_wakeupVec_0_bits_pdestCopy_4,
  input  [7:0] io_fromSchedulers_wakeupVec_0_bits_pdestCopy_5,
  input  io_fromSchedulers_wakeupVec_0_bits_rfWenCopy_2,
  input  io_fromSchedulers_wakeupVec_0_bits_rfWenCopy_3,
  input  io_fromSchedulers_wakeupVec_0_bits_rfWenCopy_4,
  input  io_fromSchedulers_wakeupVec_0_bits_rfWenCopy_5,
  input  [1:0] io_fromSchedulers_wakeupVec_0_bits_loadDependencyCopy_2_0,
  input  [1:0] io_fromSchedulers_wakeupVec_0_bits_loadDependencyCopy_2_1,
  input  [1:0] io_fromSchedulers_wakeupVec_0_bits_loadDependencyCopy_2_2,
  input  [1:0] io_fromSchedulers_wakeupVec_0_bits_loadDependencyCopy_3_0,
  input  [1:0] io_fromSchedulers_wakeupVec_0_bits_loadDependencyCopy_3_1,
  input  [1:0] io_fromSchedulers_wakeupVec_0_bits_loadDependencyCopy_3_2,
  input  [1:0] io_fromSchedulers_wakeupVec_0_bits_loadDependencyCopy_4_0,
  input  [1:0] io_fromSchedulers_wakeupVec_0_bits_loadDependencyCopy_4_1,
  input  [1:0] io_fromSchedulers_wakeupVec_0_bits_loadDependencyCopy_4_2,
  input  [1:0] io_fromSchedulers_wakeupVec_0_bits_loadDependencyCopy_5_0,
  input  [1:0] io_fromSchedulers_wakeupVec_0_bits_loadDependencyCopy_5_1,
  input  [1:0] io_fromSchedulers_wakeupVec_0_bits_loadDependencyCopy_5_2,
  input  io_fromSchedulers_wakeupVecDelayed_6_bits_rfWen,
  input  io_fromSchedulers_wakeupVecDelayed_6_bits_fpWen,
  input  [7:0] io_fromSchedulers_wakeupVecDelayed_6_bits_pdest,
  input  [4:0] io_fromSchedulers_wakeupVecDelayed_6_bits_rcDest,
  input  io_fromSchedulers_wakeupVecDelayed_5_bits_rfWen,
  input  io_fromSchedulers_wakeupVecDelayed_5_bits_fpWen,
  input  [7:0] io_fromSchedulers_wakeupVecDelayed_5_bits_pdest,
  input  [4:0] io_fromSchedulers_wakeupVecDelayed_5_bits_rcDest,
  input  io_fromSchedulers_wakeupVecDelayed_4_bits_rfWen,
  input  io_fromSchedulers_wakeupVecDelayed_4_bits_fpWen,
  input  [7:0] io_fromSchedulers_wakeupVecDelayed_4_bits_pdest,
  input  [4:0] io_fromSchedulers_wakeupVecDelayed_4_bits_rcDest,
  input  io_fromSchedulers_wakeupVecDelayed_3_bits_rfWen,
  input  [7:0] io_fromSchedulers_wakeupVecDelayed_3_bits_pdest,
  input  [1:0] io_fromSchedulers_wakeupVecDelayed_3_bits_loadDependency_0,
  input  [1:0] io_fromSchedulers_wakeupVecDelayed_3_bits_loadDependency_1,
  input  [1:0] io_fromSchedulers_wakeupVecDelayed_3_bits_loadDependency_2,
  input  [4:0] io_fromSchedulers_wakeupVecDelayed_3_bits_rcDest,
  input  io_fromSchedulers_wakeupVecDelayed_2_bits_rfWen,
  input  [7:0] io_fromSchedulers_wakeupVecDelayed_2_bits_pdest,
  input  [1:0] io_fromSchedulers_wakeupVecDelayed_2_bits_loadDependency_0,
  input  [1:0] io_fromSchedulers_wakeupVecDelayed_2_bits_loadDependency_1,
  input  [1:0] io_fromSchedulers_wakeupVecDelayed_2_bits_loadDependency_2,
  input  [4:0] io_fromSchedulers_wakeupVecDelayed_2_bits_rcDest,
  input  io_fromSchedulers_wakeupVecDelayed_1_bits_rfWen,
  input  [7:0] io_fromSchedulers_wakeupVecDelayed_1_bits_pdest,
  input  [1:0] io_fromSchedulers_wakeupVecDelayed_1_bits_loadDependency_0,
  input  [1:0] io_fromSchedulers_wakeupVecDelayed_1_bits_loadDependency_1,
  input  [1:0] io_fromSchedulers_wakeupVecDelayed_1_bits_loadDependency_2,
  input  io_fromSchedulers_wakeupVecDelayed_1_bits_is0Lat,
  input  [4:0] io_fromSchedulers_wakeupVecDelayed_1_bits_rcDest,
  input  io_fromSchedulers_wakeupVecDelayed_0_bits_rfWen,
  input  [7:0] io_fromSchedulers_wakeupVecDelayed_0_bits_pdest,
  input  [1:0] io_fromSchedulers_wakeupVecDelayed_0_bits_loadDependency_0,
  input  [1:0] io_fromSchedulers_wakeupVecDelayed_0_bits_loadDependency_1,
  input  [1:0] io_fromSchedulers_wakeupVecDelayed_0_bits_loadDependency_2,
  input  io_fromSchedulers_wakeupVecDelayed_0_bits_is0Lat,
  input  [4:0] io_fromSchedulers_wakeupVecDelayed_0_bits_rcDest,
  output io_toSchedulers_wakeupVec_2_valid,
  output io_toSchedulers_wakeupVec_2_bits_rfWen,
  output io_toSchedulers_wakeupVec_2_bits_fpWen,
  output [7:0] io_toSchedulers_wakeupVec_2_bits_pdest,
  output [4:0] io_toSchedulers_wakeupVec_2_bits_rcDest,
  output [7:0] io_toSchedulers_wakeupVec_2_bits_pdestCopy_0,
  output [7:0] io_toSchedulers_wakeupVec_2_bits_pdestCopy_1,
  output [7:0] io_toSchedulers_wakeupVec_2_bits_pdestCopy_2,
  output [7:0] io_toSchedulers_wakeupVec_2_bits_pdestCopy_3,
  output [7:0] io_toSchedulers_wakeupVec_2_bits_pdestCopy_4,
  output [7:0] io_toSchedulers_wakeupVec_2_bits_pdestCopy_5,
  output io_toSchedulers_wakeupVec_2_bits_rfWenCopy_0,
  output io_toSchedulers_wakeupVec_2_bits_rfWenCopy_1,
  output io_toSchedulers_wakeupVec_2_bits_rfWenCopy_2,
  output io_toSchedulers_wakeupVec_2_bits_rfWenCopy_3,
  output io_toSchedulers_wakeupVec_2_bits_rfWenCopy_4,
  output io_toSchedulers_wakeupVec_2_bits_rfWenCopy_5,
  output io_toSchedulers_wakeupVec_1_valid,
  output io_toSchedulers_wakeupVec_1_bits_rfWen,
  output io_toSchedulers_wakeupVec_1_bits_fpWen,
  output [7:0] io_toSchedulers_wakeupVec_1_bits_pdest,
  output [4:0] io_toSchedulers_wakeupVec_1_bits_rcDest,
  output [7:0] io_toSchedulers_wakeupVec_1_bits_pdestCopy_0,
  output [7:0] io_toSchedulers_wakeupVec_1_bits_pdestCopy_1,
  output [7:0] io_toSchedulers_wakeupVec_1_bits_pdestCopy_2,
  output [7:0] io_toSchedulers_wakeupVec_1_bits_pdestCopy_3,
  output [7:0] io_toSchedulers_wakeupVec_1_bits_pdestCopy_4,
  output [7:0] io_toSchedulers_wakeupVec_1_bits_pdestCopy_5,
  output io_toSchedulers_wakeupVec_1_bits_rfWenCopy_0,
  output io_toSchedulers_wakeupVec_1_bits_rfWenCopy_1,
  output io_toSchedulers_wakeupVec_1_bits_rfWenCopy_2,
  output io_toSchedulers_wakeupVec_1_bits_rfWenCopy_3,
  output io_toSchedulers_wakeupVec_1_bits_rfWenCopy_4,
  output io_toSchedulers_wakeupVec_1_bits_rfWenCopy_5,
  output io_toSchedulers_wakeupVec_0_valid,
  output io_toSchedulers_wakeupVec_0_bits_rfWen,
  output io_toSchedulers_wakeupVec_0_bits_fpWen,
  output [7:0] io_toSchedulers_wakeupVec_0_bits_pdest,
  output [4:0] io_toSchedulers_wakeupVec_0_bits_rcDest,
  output [7:0] io_toSchedulers_wakeupVec_0_bits_pdestCopy_0,
  output [7:0] io_toSchedulers_wakeupVec_0_bits_pdestCopy_1,
  output [7:0] io_toSchedulers_wakeupVec_0_bits_pdestCopy_2,
  output [7:0] io_toSchedulers_wakeupVec_0_bits_pdestCopy_3,
  output [7:0] io_toSchedulers_wakeupVec_0_bits_pdestCopy_4,
  output [7:0] io_toSchedulers_wakeupVec_0_bits_pdestCopy_5,
  output io_toSchedulers_wakeupVec_0_bits_rfWenCopy_0,
  output io_toSchedulers_wakeupVec_0_bits_rfWenCopy_1,
  output io_toSchedulers_wakeupVec_0_bits_rfWenCopy_2,
  output io_toSchedulers_wakeupVec_0_bits_rfWenCopy_3,
  output io_toSchedulers_wakeupVec_0_bits_rfWenCopy_4,
  output io_toSchedulers_wakeupVec_0_bits_rfWenCopy_5,
  input  io_fromDataPath_resp_8_0_og0resp_valid,
  input  io_fromDataPath_resp_8_0_og1resp_valid,
  input  [1:0] io_fromDataPath_resp_8_0_og1resp_bits_resp,
  input  io_fromDataPath_resp_7_0_og0resp_valid,
  input  io_fromDataPath_resp_7_0_og1resp_valid,
  input  [1:0] io_fromDataPath_resp_7_0_og1resp_bits_resp,
  input  io_fromDataPath_resp_6_0_og0resp_valid,
  input  io_fromDataPath_resp_6_0_og1resp_valid,
  input  io_fromDataPath_resp_5_0_og0resp_valid,
  input  io_fromDataPath_resp_5_0_og1resp_valid,
  input  io_fromDataPath_resp_4_0_og0resp_valid,
  input  [34:0] io_fromDataPath_resp_4_0_og0resp_bits_fuType,
  input  io_fromDataPath_resp_4_0_og1resp_valid,
  input  [1:0] io_fromDataPath_resp_4_0_og1resp_bits_resp,
  input  [34:0] io_fromDataPath_resp_4_0_og1resp_bits_fuType,
  input  io_fromDataPath_resp_3_0_og0resp_valid,
  input  [34:0] io_fromDataPath_resp_3_0_og0resp_bits_fuType,
  input  io_fromDataPath_resp_3_0_og1resp_valid,
  input  [1:0] io_fromDataPath_resp_3_0_og1resp_bits_resp,
  input  [34:0] io_fromDataPath_resp_3_0_og1resp_bits_fuType,
  input  io_fromDataPath_resp_2_0_og0resp_valid,
  input  [34:0] io_fromDataPath_resp_2_0_og0resp_bits_fuType,
  input  io_fromDataPath_resp_2_0_og1resp_valid,
  input  [1:0] io_fromDataPath_resp_2_0_og1resp_bits_resp,
  input  [34:0] io_fromDataPath_resp_2_0_og1resp_bits_fuType,
  input  io_fromDataPath_resp_1_0_og0resp_valid,
  input  io_fromDataPath_resp_1_0_og1resp_valid,
  input  [1:0] io_fromDataPath_resp_1_0_og1resp_bits_resp,
  input  io_fromDataPath_resp_0_0_og0resp_valid,
  input  io_fromDataPath_resp_0_0_og1resp_valid,
  input  [1:0] io_fromDataPath_resp_0_0_og1resp_bits_resp,
  input  io_fromDataPath_og0Cancel_0,
  input  io_fromDataPath_og0Cancel_2,
  input  io_fromDataPath_og0Cancel_4,
  input  io_fromDataPath_og0Cancel_6,
  input  [4:0] io_fromDataPath_replaceRCIdx_0,
  input  [4:0] io_fromDataPath_replaceRCIdx_1,
  input  [4:0] io_fromDataPath_replaceRCIdx_2,
  input  io_loadFinalIssueResp_4_0_valid,
  input  io_loadFinalIssueResp_4_0_bits_lqIdx_flag,
  input  [6:0] io_loadFinalIssueResp_4_0_bits_lqIdx_value,
  input  io_loadFinalIssueResp_3_0_valid,
  input  io_loadFinalIssueResp_3_0_bits_lqIdx_flag,
  input  [6:0] io_loadFinalIssueResp_3_0_bits_lqIdx_value,
  input  io_loadFinalIssueResp_2_0_valid,
  input  io_loadFinalIssueResp_2_0_bits_lqIdx_flag,
  input  [6:0] io_loadFinalIssueResp_2_0_bits_lqIdx_value,
  input  io_vecLoadFinalIssueResp_6_0_valid,
  input  io_vecLoadFinalIssueResp_6_0_bits_robIdx_flag,
  input  [7:0] io_vecLoadFinalIssueResp_6_0_bits_robIdx_value,
  input  [34:0] io_vecLoadFinalIssueResp_6_0_bits_fuType,
  input  [6:0] io_vecLoadFinalIssueResp_6_0_bits_uopIdx,
  input  io_vecLoadFinalIssueResp_6_0_bits_sqIdx_flag,
  input  [5:0] io_vecLoadFinalIssueResp_6_0_bits_sqIdx_value,
  input  io_vecLoadFinalIssueResp_6_0_bits_lqIdx_flag,
  input  [6:0] io_vecLoadFinalIssueResp_6_0_bits_lqIdx_value,
  input  io_vecLoadFinalIssueResp_5_0_valid,
  input  io_vecLoadFinalIssueResp_5_0_bits_robIdx_flag,
  input  [7:0] io_vecLoadFinalIssueResp_5_0_bits_robIdx_value,
  input  [34:0] io_vecLoadFinalIssueResp_5_0_bits_fuType,
  input  [6:0] io_vecLoadFinalIssueResp_5_0_bits_uopIdx,
  input  io_vecLoadFinalIssueResp_5_0_bits_sqIdx_flag,
  input  [5:0] io_vecLoadFinalIssueResp_5_0_bits_sqIdx_value,
  input  io_vecLoadFinalIssueResp_5_0_bits_lqIdx_flag,
  input  [6:0] io_vecLoadFinalIssueResp_5_0_bits_lqIdx_value,
  input  io_memAddrIssueResp_4_0_valid,
  input  io_memAddrIssueResp_4_0_bits_lqIdx_flag,
  input  [6:0] io_memAddrIssueResp_4_0_bits_lqIdx_value,
  input  io_memAddrIssueResp_3_0_valid,
  input  io_memAddrIssueResp_3_0_bits_lqIdx_flag,
  input  [6:0] io_memAddrIssueResp_3_0_bits_lqIdx_value,
  input  io_memAddrIssueResp_2_0_valid,
  input  io_memAddrIssueResp_2_0_bits_lqIdx_flag,
  input  [6:0] io_memAddrIssueResp_2_0_bits_lqIdx_value,
  input  io_vecLoadIssueResp_6_0_valid,
  input  io_vecLoadIssueResp_6_0_bits_robIdx_flag,
  input  [7:0] io_vecLoadIssueResp_6_0_bits_robIdx_value,
  input  [34:0] io_vecLoadIssueResp_6_0_bits_fuType,
  input  [6:0] io_vecLoadIssueResp_6_0_bits_uopIdx,
  input  io_vecLoadIssueResp_6_0_bits_sqIdx_flag,
  input  [5:0] io_vecLoadIssueResp_6_0_bits_sqIdx_value,
  input  io_vecLoadIssueResp_6_0_bits_lqIdx_flag,
  input  [6:0] io_vecLoadIssueResp_6_0_bits_lqIdx_value,
  input  io_vecLoadIssueResp_5_0_valid,
  input  io_vecLoadIssueResp_5_0_bits_robIdx_flag,
  input  [7:0] io_vecLoadIssueResp_5_0_bits_robIdx_value,
  input  [34:0] io_vecLoadIssueResp_5_0_bits_fuType,
  input  [6:0] io_vecLoadIssueResp_5_0_bits_uopIdx,
  input  io_vecLoadIssueResp_5_0_bits_sqIdx_flag,
  input  [5:0] io_vecLoadIssueResp_5_0_bits_sqIdx_value,
  input  io_vecLoadIssueResp_5_0_bits_lqIdx_flag,
  input  [6:0] io_vecLoadIssueResp_5_0_bits_lqIdx_value,
  input  io_ldCancel_0_ld2Cancel,
  input  io_ldCancel_1_ld2Cancel,
  input  io_ldCancel_2_ld2Cancel,
  input  io_fromMem_staFeedback_0_feedbackSlow_valid,
  input  io_fromMem_staFeedback_0_feedbackSlow_bits_hit,
  input  io_fromMem_staFeedback_0_feedbackSlow_bits_sqIdx_flag,
  input  [5:0] io_fromMem_staFeedback_0_feedbackSlow_bits_sqIdx_value,
  input  io_fromMem_staFeedback_1_feedbackSlow_valid,
  input  io_fromMem_staFeedback_1_feedbackSlow_bits_hit,
  input  io_fromMem_staFeedback_1_feedbackSlow_bits_sqIdx_flag,
  input  [5:0] io_fromMem_staFeedback_1_feedbackSlow_bits_sqIdx_value,
  input  io_fromMem_vstuFeedback_0_feedbackSlow_valid,
  input  io_fromMem_vstuFeedback_0_feedbackSlow_bits_hit,
  input  io_fromMem_vstuFeedback_0_feedbackSlow_bits_sqIdx_flag,
  input  [5:0] io_fromMem_vstuFeedback_0_feedbackSlow_bits_sqIdx_value,
  input  io_fromMem_vstuFeedback_0_feedbackSlow_bits_lqIdx_flag,
  input  [6:0] io_fromMem_vstuFeedback_0_feedbackSlow_bits_lqIdx_value,
  input  io_fromMem_vstuFeedback_1_feedbackSlow_valid,
  input  io_fromMem_vstuFeedback_1_feedbackSlow_bits_hit,
  input  io_fromMem_vstuFeedback_1_feedbackSlow_bits_sqIdx_flag,
  input  [5:0] io_fromMem_vstuFeedback_1_feedbackSlow_bits_sqIdx_value,
  input  io_fromMem_vstuFeedback_1_feedbackSlow_bits_lqIdx_flag,
  input  [6:0] io_fromMem_vstuFeedback_1_feedbackSlow_bits_lqIdx_value,
  input  io_fromMem_wakeup_0_valid,
  input  io_fromMem_wakeup_0_bits_rfWen,
  input  io_fromMem_wakeup_0_bits_fpWen,
  input  [7:0] io_fromMem_wakeup_0_bits_pdest,
  input  io_fromMem_wakeup_1_valid,
  input  io_fromMem_wakeup_1_bits_rfWen,
  input  io_fromMem_wakeup_1_bits_fpWen,
  input  [7:0] io_fromMem_wakeup_1_bits_pdest,
  input  io_fromMem_wakeup_2_valid,
  input  io_fromMem_wakeup_2_bits_rfWen,
  input  io_fromMem_wakeup_2_bits_fpWen,
  input  [7:0] io_fromMem_wakeup_2_bits_pdest,
  input  io_fromMem_lqDeqPtr_flag,
  input  [6:0] io_fromMem_lqDeqPtr_value,
  input  io_fromOg2Resp_1_0_valid,
  input  [1:0] io_fromOg2Resp_1_0_bits_resp,
  input  io_fromOg2Resp_0_0_valid,
  input  [1:0] io_fromOg2Resp_0_0_bits_resp,
  output [5:0] io_perf_0_value,
  output [5:0] io_perf_1_value,
  output [5:0] io_perf_2_value,
  output [5:0] io_perf_3_value,
  output [5:0] io_perf_4_value,
  output [5:0] io_perf_5_value,
  output [5:0] io_perf_6_value,
  output [5:0] io_perf_7_value,
  output [5:0] io_perf_8_value,
  output [5:0] io_perf_9_value
);

  // ===== A) 例化 9 个 IssueQueue 并互联(唤醒网络/响应/cancel) =====
  `include "scheduler_mem_iq_connect.svh"

  // ===== B) dispatch-ready 透传 =====
  // 每个 dispatch 入端口的 ready 来自承接它的 IQ 的 enq0.ready。
  // 注:端口 0/2 由 Sta 与 Std 共享(存地址+存数据),须两个 IQ 都能收才 ready。
  assign io_fromDispatch_uops_0_ready = IssueQueueStaMou_enq_0_ready & IssueQueueStdMoud_enq_0_ready;
  assign io_fromDispatch_uops_2_ready = IssueQueueStaMou_1_enq_0_ready & IssueQueueStdMoud_1_enq_0_ready;
  assign io_fromDispatch_uops_4_ready = IssueQueueLdu_enq_0_ready;
  assign io_fromDispatch_uops_6_ready = IssueQueueLdu_1_enq_0_ready;
  assign io_fromDispatch_uops_8_ready = IssueQueueLdu_2_enq_0_ready;
  assign io_fromDispatch_uops_10_ready = IssueQueueVlduVstuVseglduVsegstu_enq_0_ready;
  assign io_fromDispatch_uops_12_ready = IssueQueueVlduVstu_enq_0_ready;

  // ===== C) deqDelay 发射有效 输出扇出 =====
  // 各 IQ 的 deqDelay_0_valid 在 .svh 里引到内部线,这里扇出到对应输出端口。
  assign io_toDataPathAfterDelay_0_0_valid = IssueQueueStaMou_deqDelay_0_valid;
  assign io_toDataPathAfterDelay_1_0_valid = IssueQueueStaMou_1_deqDelay_0_valid;
  assign io_toDataPathAfterDelay_2_0_valid = IssueQueueLdu_deqDelay_0_valid;
  assign io_toDataPathAfterDelay_3_0_valid = IssueQueueLdu_1_deqDelay_0_valid;
  assign io_toDataPathAfterDelay_4_0_valid = IssueQueueLdu_2_deqDelay_0_valid;
  assign io_toDataPathAfterDelay_5_0_valid = IssueQueueVlduVstuVseglduVsegstu_deqDelay_0_valid;
  assign io_toDataPathAfterDelay_6_0_valid = IssueQueueVlduVstu_deqDelay_0_valid;
  assign io_toDataPathAfterDelay_7_0_valid = IssueQueueStdMoud_deqDelay_0_valid;
  assign io_toDataPathAfterDelay_8_0_valid = IssueQueueStdMoud_1_deqDelay_0_valid;

  // ===== D) 发射 perf 统计 =====
  // enq_fire[i] = 第 i 个统计端口本拍 fire(IQ enq.ready & 对应 valid);
  // iq_full[k]  = 第 k 个 IQ 的 enq0.ready(队列是否还能收)。
  logic [NUM_ENQ_FIRE-1:0] enq_fire;
  logic [NUM_IQ-1:0]       iq_full;
  assign enq_fire[0] = IssueQueueStaMou_enq_0_ready & sta_enq_valid_uop0;
  assign enq_fire[1] = IssueQueueStaMou_enq_1_ready & sta_enq_valid_uop1;
  assign enq_fire[2] = IssueQueueStaMou_1_enq_0_ready & sta_enq_valid_uop2;
  assign enq_fire[3] = IssueQueueStaMou_1_enq_1_ready & sta_enq_valid_uop3;
  assign enq_fire[4] = IssueQueueLdu_enq_0_ready & io_fromDispatch_uops_4_valid;
  assign enq_fire[5] = IssueQueueLdu_enq_1_ready & io_fromDispatch_uops_5_valid;
  assign enq_fire[6] = IssueQueueLdu_1_enq_0_ready & io_fromDispatch_uops_6_valid;
  assign enq_fire[7] = IssueQueueLdu_1_enq_1_ready & io_fromDispatch_uops_7_valid;
  assign enq_fire[8] = IssueQueueLdu_2_enq_0_ready & io_fromDispatch_uops_8_valid;
  assign enq_fire[9] = IssueQueueLdu_2_enq_1_ready & io_fromDispatch_uops_9_valid;
  assign enq_fire[10] = IssueQueueVlduVstuVseglduVsegstu_enq_0_ready & io_fromDispatch_uops_10_valid;
  assign enq_fire[11] = IssueQueueVlduVstuVseglduVsegstu_enq_1_ready & io_fromDispatch_uops_11_valid;
  assign enq_fire[12] = IssueQueueVlduVstu_enq_0_ready & io_fromDispatch_uops_12_valid;
  assign enq_fire[13] = IssueQueueVlduVstu_enq_1_ready & io_fromDispatch_uops_13_valid;
  assign enq_fire[14] = IssueQueueStdMoud_enq_0_ready & io_fromDispatch_uops_0_valid;
  assign enq_fire[15] = IssueQueueStdMoud_enq_1_ready & io_fromDispatch_uops_1_valid;
  assign enq_fire[16] = IssueQueueStdMoud_1_enq_0_ready & io_fromDispatch_uops_2_valid;
  assign enq_fire[17] = IssueQueueStdMoud_1_enq_1_ready & io_fromDispatch_uops_3_valid;

  assign iq_full[IQ_STA_MOU_0] = IssueQueueStaMou_enq_0_ready;
  assign iq_full[IQ_STA_MOU_1] = IssueQueueStaMou_1_enq_0_ready;
  assign iq_full[IQ_LDU_0] = IssueQueueLdu_enq_0_ready;
  assign iq_full[IQ_LDU_1] = IssueQueueLdu_1_enq_0_ready;
  assign iq_full[IQ_LDU_2] = IssueQueueLdu_2_enq_0_ready;
  assign iq_full[IQ_VLDU_VSTU_SEG] = IssueQueueVlduVstuVseglduVsegstu_enq_0_ready;
  assign iq_full[IQ_VLDU_VSTU] = IssueQueueVlduVstu_enq_0_ready;
  assign iq_full[IQ_STD_MOU_0] = IssueQueueStdMoud_enq_0_ready;
  assign iq_full[IQ_STD_MOU_1] = IssueQueueStdMoud_1_enq_0_ready;

  // perf 三级流水(与 firtool 一致):
  //   stage0(last_cycle):先把本拍 enq_fire / iq_full 各打一拍;
  //   stage1(perf_s1)   :对 stage0 的 enq_fire 求 popcount;full 位直接打拍;
  //   stage2(perf_s2)   :再打一拍,作为对外 io_perf 输出。
  // popcount 作用在「已寄存」的 enq_fire 上(故计数比 fire 晚一拍),保留以逐拍等价。
  logic [NUM_ENQ_FIRE-1:0] last_cycle_enq_fire;
  logic [NUM_IQ-1:0]       last_cycle_iq_full;
  perf_sample_t perf_s1, perf_s2;
  always_ff @(posedge clock) begin
    last_cycle_enq_fire  <= enq_fire;
    last_cycle_iq_full   <= iq_full;
    perf_s1.enq_fire_cnt <= popcount(last_cycle_enq_fire);
    perf_s1.iq_full      <= last_cycle_iq_full;
    perf_s2              <= perf_s1;
  end

  // perf 输出:enq_fire_cnt 端口 6bit(高位补 1'h0);各 full 端口 6bit(高位补 5'h0)。
  assign io_perf_0_value = {1'h0, perf_s2.enq_fire_cnt};
  assign io_perf_1_value = {5'h0, perf_s2.iq_full[IQ_STA_MOU_0]};
  assign io_perf_2_value = {5'h0, perf_s2.iq_full[IQ_STA_MOU_1]};
  assign io_perf_3_value = {5'h0, perf_s2.iq_full[IQ_LDU_0]};
  assign io_perf_4_value = {5'h0, perf_s2.iq_full[IQ_LDU_1]};
  assign io_perf_5_value = {5'h0, perf_s2.iq_full[IQ_LDU_2]};
  assign io_perf_6_value = {5'h0, perf_s2.iq_full[IQ_VLDU_VSTU_SEG]};
  assign io_perf_7_value = {5'h0, perf_s2.iq_full[IQ_VLDU_VSTU]};
  assign io_perf_8_value = {5'h0, perf_s2.iq_full[IQ_STD_MOU_0]};
  assign io_perf_9_value = {5'h0, perf_s2.iq_full[IQ_STD_MOU_1]};

endmodule
