// =============================================================================
// WbFuBusyTable —— golden 同名 wrapper(机械端口适配层, 供 FM/ST 对接)
// -----------------------------------------------------------------------------
// 把可读核 xs_WbFuBusyTable_core 的语义化端口拆/接成 golden 的扁平端口。
// 端口名、位宽、连接关系与 golden WbFuBusyTable.sv 逐一对应。纯接线, 允许平铺。
// =============================================================================
module WbFuBusyTable(
  input  [2:0] io_in_intSchdBusyTable_2_1_fpWbBusyTable,
  input  [2:0] io_in_intSchdBusyTable_1_0_intWbBusyTable,
  input  [2:0] io_in_intSchdBusyTable_0_0_intWbBusyTable,
  input  [1:0] io_in_fpSchdBusyTable_2_0_intWbBusyTable,
  input  [3:0] io_in_fpSchdBusyTable_2_0_fpWbBusyTable,
  input  [1:0] io_in_fpSchdBusyTable_1_0_intWbBusyTable,
  input  [3:0] io_in_fpSchdBusyTable_1_0_fpWbBusyTable,
  input  [2:0] io_in_fpSchdBusyTable_0_0_intWbBusyTable,
  input  [3:0] io_in_fpSchdBusyTable_0_0_fpWbBusyTable,
  input  [2:0] io_in_vfSchdBusyTable_1_1_fpWbBusyTable,
  input  [2:0] io_in_vfSchdBusyTable_1_1_vfWbBusyTable,
  input  [2:0] io_in_vfSchdBusyTable_1_1_v0WbBusyTable,
  input  [4:0] io_in_vfSchdBusyTable_1_0_vfWbBusyTable,
  input  [4:0] io_in_vfSchdBusyTable_1_0_v0WbBusyTable,
  input  [4:0] io_in_vfSchdBusyTable_0_1_intWbBusyTable,
  input  [2:0] io_in_vfSchdBusyTable_0_1_fpWbBusyTable,
  input  [3:0] io_in_vfSchdBusyTable_0_1_vfWbBusyTable,
  input  [3:0] io_in_vfSchdBusyTable_0_1_v0WbBusyTable,
  input  [1:0] io_in_vfSchdBusyTable_0_1_vlWbBusyTable,
  input  [4:0] io_in_vfSchdBusyTable_0_0_vfWbBusyTable,
  input  [4:0] io_in_vfSchdBusyTable_0_0_v0WbBusyTable,
  output [2:0] io_out_intRespRead_2_1_fpWbBusyTable,
  output       io_out_intRespRead_2_1_vfWbBusyTable,
  output       io_out_intRespRead_2_1_v0WbBusyTable,
  output       io_out_intRespRead_2_0_intWbBusyTable,
  output       io_out_intRespRead_1_1_intWbBusyTable,
  output [2:0] io_out_intRespRead_1_0_intWbBusyTable,
  output       io_out_intRespRead_0_1_intWbBusyTable,
  output [2:0] io_out_intRespRead_0_0_intWbBusyTable,
  output [1:0] io_out_fpRespRead_2_0_intWbBusyTable,
  output [3:0] io_out_fpRespRead_2_0_fpWbBusyTable,
  output [1:0] io_out_fpRespRead_1_0_intWbBusyTable,
  output [3:0] io_out_fpRespRead_1_0_fpWbBusyTable,
  output [2:0] io_out_fpRespRead_0_0_intWbBusyTable,
  output [3:0] io_out_fpRespRead_0_0_fpWbBusyTable,
  output [2:0] io_out_vfRespRead_1_1_fpWbBusyTable,
  output [2:0] io_out_vfRespRead_1_1_vfWbBusyTable,
  output [2:0] io_out_vfRespRead_1_1_v0WbBusyTable,
  output [4:0] io_out_vfRespRead_1_0_vfWbBusyTable,
  output [4:0] io_out_vfRespRead_1_0_v0WbBusyTable,
  output [4:0] io_out_vfRespRead_0_1_intWbBusyTable,
  output [2:0] io_out_vfRespRead_0_1_fpWbBusyTable,
  output [3:0] io_out_vfRespRead_0_1_vfWbBusyTable,
  output [3:0] io_out_vfRespRead_0_1_v0WbBusyTable,
  output [1:0] io_out_vfRespRead_0_1_vlWbBusyTable,
  output [4:0] io_out_vfRespRead_0_0_vfWbBusyTable,
  output [4:0] io_out_vfRespRead_0_0_v0WbBusyTable
);

  xs_WbFuBusyTable_core u_core (
    .in_intSchd_0_0_intWb (io_in_intSchdBusyTable_0_0_intWbBusyTable),
    .in_intSchd_1_0_intWb (io_in_intSchdBusyTable_1_0_intWbBusyTable),
    .in_intSchd_2_1_fpWb  (io_in_intSchdBusyTable_2_1_fpWbBusyTable),
    .in_fpSchd_0_0_intWb  (io_in_fpSchdBusyTable_0_0_intWbBusyTable),
    .in_fpSchd_0_0_fpWb   (io_in_fpSchdBusyTable_0_0_fpWbBusyTable),
    .in_fpSchd_1_0_intWb  (io_in_fpSchdBusyTable_1_0_intWbBusyTable),
    .in_fpSchd_1_0_fpWb   (io_in_fpSchdBusyTable_1_0_fpWbBusyTable),
    .in_fpSchd_2_0_intWb  (io_in_fpSchdBusyTable_2_0_intWbBusyTable),
    .in_fpSchd_2_0_fpWb   (io_in_fpSchdBusyTable_2_0_fpWbBusyTable),
    .in_vfSchd_1_1_fpWb   (io_in_vfSchdBusyTable_1_1_fpWbBusyTable),
    .in_vfSchd_1_1_vfWb   (io_in_vfSchdBusyTable_1_1_vfWbBusyTable),
    .in_vfSchd_1_1_v0Wb   (io_in_vfSchdBusyTable_1_1_v0WbBusyTable),
    .in_vfSchd_1_0_vfWb   (io_in_vfSchdBusyTable_1_0_vfWbBusyTable),
    .in_vfSchd_1_0_v0Wb   (io_in_vfSchdBusyTable_1_0_v0WbBusyTable),
    .in_vfSchd_0_1_intWb  (io_in_vfSchdBusyTable_0_1_intWbBusyTable),
    .in_vfSchd_0_1_fpWb   (io_in_vfSchdBusyTable_0_1_fpWbBusyTable),
    .in_vfSchd_0_1_vfWb   (io_in_vfSchdBusyTable_0_1_vfWbBusyTable),
    .in_vfSchd_0_1_v0Wb   (io_in_vfSchdBusyTable_0_1_v0WbBusyTable),
    .in_vfSchd_0_1_vlWb   (io_in_vfSchdBusyTable_0_1_vlWbBusyTable),
    .in_vfSchd_0_0_vfWb   (io_in_vfSchdBusyTable_0_0_vfWbBusyTable),
    .in_vfSchd_0_0_v0Wb   (io_in_vfSchdBusyTable_0_0_v0WbBusyTable),

    .out_intResp_2_1_fpWb (io_out_intRespRead_2_1_fpWbBusyTable),
    .out_intResp_2_1_vfWb (io_out_intRespRead_2_1_vfWbBusyTable),
    .out_intResp_2_1_v0Wb (io_out_intRespRead_2_1_v0WbBusyTable),
    .out_intResp_2_0_intWb(io_out_intRespRead_2_0_intWbBusyTable),
    .out_intResp_1_1_intWb(io_out_intRespRead_1_1_intWbBusyTable),
    .out_intResp_1_0_intWb(io_out_intRespRead_1_0_intWbBusyTable),
    .out_intResp_0_1_intWb(io_out_intRespRead_0_1_intWbBusyTable),
    .out_intResp_0_0_intWb(io_out_intRespRead_0_0_intWbBusyTable),
    .out_fpResp_2_0_intWb (io_out_fpRespRead_2_0_intWbBusyTable),
    .out_fpResp_2_0_fpWb  (io_out_fpRespRead_2_0_fpWbBusyTable),
    .out_fpResp_1_0_intWb (io_out_fpRespRead_1_0_intWbBusyTable),
    .out_fpResp_1_0_fpWb  (io_out_fpRespRead_1_0_fpWbBusyTable),
    .out_fpResp_0_0_intWb (io_out_fpRespRead_0_0_intWbBusyTable),
    .out_fpResp_0_0_fpWb  (io_out_fpRespRead_0_0_fpWbBusyTable),
    .out_vfResp_1_1_fpWb  (io_out_vfRespRead_1_1_fpWbBusyTable),
    .out_vfResp_1_1_vfWb  (io_out_vfRespRead_1_1_vfWbBusyTable),
    .out_vfResp_1_1_v0Wb  (io_out_vfRespRead_1_1_v0WbBusyTable),
    .out_vfResp_1_0_vfWb  (io_out_vfRespRead_1_0_vfWbBusyTable),
    .out_vfResp_1_0_v0Wb  (io_out_vfRespRead_1_0_v0WbBusyTable),
    .out_vfResp_0_1_intWb (io_out_vfRespRead_0_1_intWbBusyTable),
    .out_vfResp_0_1_fpWb  (io_out_vfRespRead_0_1_fpWbBusyTable),
    .out_vfResp_0_1_vfWb  (io_out_vfRespRead_0_1_vfWbBusyTable),
    .out_vfResp_0_1_v0Wb  (io_out_vfRespRead_0_1_v0WbBusyTable),
    .out_vfResp_0_1_vlWb  (io_out_vfRespRead_0_1_vlWbBusyTable),
    .out_vfResp_0_0_vfWb  (io_out_vfRespRead_0_0_vfWbBusyTable),
    .out_vfResp_0_0_v0Wb  (io_out_vfRespRead_0_0_v0WbBusyTable)
  );

endmodule
