// Generated by scripts/gen_frontendtrigger.py — do not hand-edit.
// Double-instantiate golden FrontendTrigger vs FrontendTrigger_xs; 逐拍比对全部输出。
`timescale 1ns/1ps
module tb;
  int unsigned NCYCLES = 200000;
  int unsigned WARMUP  = 8;
  bit clk = 0;
  logic rst;
  int errors = 0, checks = 0, cyc = 0;
  int act_bp = 0, act_dbg = 0, act_any = 0;  // golden 触发活性审计
  always #5 clk = ~clk;

  logic io_frontendTrigger_tUpdate_valid;
  logic [1:0] io_frontendTrigger_tUpdate_bits_addr;
  logic [1:0] io_frontendTrigger_tUpdate_bits_tdata_matchType;
  logic io_frontendTrigger_tUpdate_bits_tdata_select;
  logic [3:0] io_frontendTrigger_tUpdate_bits_tdata_action;
  logic io_frontendTrigger_tUpdate_bits_tdata_chain;
  logic [63:0] io_frontendTrigger_tUpdate_bits_tdata_tdata2;
  logic io_frontendTrigger_tEnableVec_0;
  logic io_frontendTrigger_tEnableVec_1;
  logic io_frontendTrigger_tEnableVec_2;
  logic io_frontendTrigger_tEnableVec_3;
  logic io_frontendTrigger_debugMode;
  logic io_frontendTrigger_triggerCanRaiseBpExp;
  logic [49:0] io_pc_0;
  logic [49:0] io_pc_1;
  logic [49:0] io_pc_2;
  logic [49:0] io_pc_3;
  logic [49:0] io_pc_4;
  logic [49:0] io_pc_5;
  logic [49:0] io_pc_6;
  logic [49:0] io_pc_7;
  logic [49:0] io_pc_8;
  logic [49:0] io_pc_9;
  logic [49:0] io_pc_10;
  logic [49:0] io_pc_11;
  logic [49:0] io_pc_12;
  logic [49:0] io_pc_13;
  logic [49:0] io_pc_14;
  logic [49:0] io_pc_15;

  wire [3:0] g_io_triggered_0, i_io_triggered_0;
  wire [3:0] g_io_triggered_1, i_io_triggered_1;
  wire [3:0] g_io_triggered_2, i_io_triggered_2;
  wire [3:0] g_io_triggered_3, i_io_triggered_3;
  wire [3:0] g_io_triggered_4, i_io_triggered_4;
  wire [3:0] g_io_triggered_5, i_io_triggered_5;
  wire [3:0] g_io_triggered_6, i_io_triggered_6;
  wire [3:0] g_io_triggered_7, i_io_triggered_7;
  wire [3:0] g_io_triggered_8, i_io_triggered_8;
  wire [3:0] g_io_triggered_9, i_io_triggered_9;
  wire [3:0] g_io_triggered_10, i_io_triggered_10;
  wire [3:0] g_io_triggered_11, i_io_triggered_11;
  wire [3:0] g_io_triggered_12, i_io_triggered_12;
  wire [3:0] g_io_triggered_13, i_io_triggered_13;
  wire [3:0] g_io_triggered_14, i_io_triggered_14;
  wire [3:0] g_io_triggered_15, i_io_triggered_15;

  FrontendTrigger u_g(
    .clock(clk),
    .reset(rst),
    .io_frontendTrigger_tUpdate_valid(io_frontendTrigger_tUpdate_valid),
    .io_frontendTrigger_tUpdate_bits_addr(io_frontendTrigger_tUpdate_bits_addr),
    .io_frontendTrigger_tUpdate_bits_tdata_matchType(io_frontendTrigger_tUpdate_bits_tdata_matchType),
    .io_frontendTrigger_tUpdate_bits_tdata_select(io_frontendTrigger_tUpdate_bits_tdata_select),
    .io_frontendTrigger_tUpdate_bits_tdata_action(io_frontendTrigger_tUpdate_bits_tdata_action),
    .io_frontendTrigger_tUpdate_bits_tdata_chain(io_frontendTrigger_tUpdate_bits_tdata_chain),
    .io_frontendTrigger_tUpdate_bits_tdata_tdata2(io_frontendTrigger_tUpdate_bits_tdata_tdata2),
    .io_frontendTrigger_tEnableVec_0(io_frontendTrigger_tEnableVec_0),
    .io_frontendTrigger_tEnableVec_1(io_frontendTrigger_tEnableVec_1),
    .io_frontendTrigger_tEnableVec_2(io_frontendTrigger_tEnableVec_2),
    .io_frontendTrigger_tEnableVec_3(io_frontendTrigger_tEnableVec_3),
    .io_frontendTrigger_debugMode(io_frontendTrigger_debugMode),
    .io_frontendTrigger_triggerCanRaiseBpExp(io_frontendTrigger_triggerCanRaiseBpExp),
    .io_pc_0(io_pc_0),
    .io_pc_1(io_pc_1),
    .io_pc_2(io_pc_2),
    .io_pc_3(io_pc_3),
    .io_pc_4(io_pc_4),
    .io_pc_5(io_pc_5),
    .io_pc_6(io_pc_6),
    .io_pc_7(io_pc_7),
    .io_pc_8(io_pc_8),
    .io_pc_9(io_pc_9),
    .io_pc_10(io_pc_10),
    .io_pc_11(io_pc_11),
    .io_pc_12(io_pc_12),
    .io_pc_13(io_pc_13),
    .io_pc_14(io_pc_14),
    .io_pc_15(io_pc_15),
    .io_triggered_0(g_io_triggered_0),
    .io_triggered_1(g_io_triggered_1),
    .io_triggered_2(g_io_triggered_2),
    .io_triggered_3(g_io_triggered_3),
    .io_triggered_4(g_io_triggered_4),
    .io_triggered_5(g_io_triggered_5),
    .io_triggered_6(g_io_triggered_6),
    .io_triggered_7(g_io_triggered_7),
    .io_triggered_8(g_io_triggered_8),
    .io_triggered_9(g_io_triggered_9),
    .io_triggered_10(g_io_triggered_10),
    .io_triggered_11(g_io_triggered_11),
    .io_triggered_12(g_io_triggered_12),
    .io_triggered_13(g_io_triggered_13),
    .io_triggered_14(g_io_triggered_14),
    .io_triggered_15(g_io_triggered_15)
  );

  FrontendTrigger_xs u_i(
    .clock(clk),
    .reset(rst),
    .io_frontendTrigger_tUpdate_valid(io_frontendTrigger_tUpdate_valid),
    .io_frontendTrigger_tUpdate_bits_addr(io_frontendTrigger_tUpdate_bits_addr),
    .io_frontendTrigger_tUpdate_bits_tdata_matchType(io_frontendTrigger_tUpdate_bits_tdata_matchType),
    .io_frontendTrigger_tUpdate_bits_tdata_select(io_frontendTrigger_tUpdate_bits_tdata_select),
    .io_frontendTrigger_tUpdate_bits_tdata_action(io_frontendTrigger_tUpdate_bits_tdata_action),
    .io_frontendTrigger_tUpdate_bits_tdata_chain(io_frontendTrigger_tUpdate_bits_tdata_chain),
    .io_frontendTrigger_tUpdate_bits_tdata_tdata2(io_frontendTrigger_tUpdate_bits_tdata_tdata2),
    .io_frontendTrigger_tEnableVec_0(io_frontendTrigger_tEnableVec_0),
    .io_frontendTrigger_tEnableVec_1(io_frontendTrigger_tEnableVec_1),
    .io_frontendTrigger_tEnableVec_2(io_frontendTrigger_tEnableVec_2),
    .io_frontendTrigger_tEnableVec_3(io_frontendTrigger_tEnableVec_3),
    .io_frontendTrigger_debugMode(io_frontendTrigger_debugMode),
    .io_frontendTrigger_triggerCanRaiseBpExp(io_frontendTrigger_triggerCanRaiseBpExp),
    .io_pc_0(io_pc_0),
    .io_pc_1(io_pc_1),
    .io_pc_2(io_pc_2),
    .io_pc_3(io_pc_3),
    .io_pc_4(io_pc_4),
    .io_pc_5(io_pc_5),
    .io_pc_6(io_pc_6),
    .io_pc_7(io_pc_7),
    .io_pc_8(io_pc_8),
    .io_pc_9(io_pc_9),
    .io_pc_10(io_pc_10),
    .io_pc_11(io_pc_11),
    .io_pc_12(io_pc_12),
    .io_pc_13(io_pc_13),
    .io_pc_14(io_pc_14),
    .io_pc_15(io_pc_15),
    .io_triggered_0(i_io_triggered_0),
    .io_triggered_1(i_io_triggered_1),
    .io_triggered_2(i_io_triggered_2),
    .io_triggered_3(i_io_triggered_3),
    .io_triggered_4(i_io_triggered_4),
    .io_triggered_5(i_io_triggered_5),
    .io_triggered_6(i_io_triggered_6),
    .io_triggered_7(i_io_triggered_7),
    .io_triggered_8(i_io_triggered_8),
    .io_triggered_9(i_io_triggered_9),
    .io_triggered_10(i_io_triggered_10),
    .io_triggered_11(i_io_triggered_11),
    .io_triggered_12(i_io_triggered_12),
    .io_triggered_13(i_io_triggered_13),
    .io_triggered_14(i_io_triggered_14),
    .io_triggered_15(i_io_triggered_15)
  );

  // 与 pc 同一小块号空间, 保证 equal/greater/less 三路都非蒸汽
  localparam logic [44:0] BASE_HI = 45'h1234;

  function automatic logic [1:0] rmt();  // matchType: 0=equal 多数, 1=保留, 2=geq, 3=less
    int r;
    r = $urandom_range(9);
    return (r < 4) ? 2'h0 : (r < 6) ? 2'h1 : (r < 8) ? 2'h2 : 2'h3;
  endfunction

  function automatic logic [3:0] ract();  // action: 0(断点)/1(debug) 多数
    int r;
    r = $urandom_range(9);
    return (r < 4) ? 4'h0 : (r < 7) ? 4'h1 : 4'($urandom);
  endfunction

  task automatic drive_random();
    logic [44:0] hi;
    logic [49:0] pcbase;
    io_frontendTrigger_tUpdate_valid = ($urandom_range(9) < 4);
    io_frontendTrigger_tUpdate_bits_addr = 2'($urandom_range(3));
    io_frontendTrigger_tUpdate_bits_tdata_matchType = rmt();
    io_frontendTrigger_tUpdate_bits_tdata_select = ($urandom_range(9) == 0);
    io_frontendTrigger_tUpdate_bits_tdata_action = ract();
    io_frontendTrigger_tUpdate_bits_tdata_chain = ($urandom_range(9) < 3);
    hi = BASE_HI + 45'($urandom_range(3));
    io_frontendTrigger_tUpdate_bits_tdata_tdata2 = {14'($urandom), hi, 5'($urandom)};
    io_frontendTrigger_tEnableVec_0 = ($urandom_range(9) < 7);
    io_frontendTrigger_tEnableVec_1 = ($urandom_range(9) < 7);
    io_frontendTrigger_tEnableVec_2 = ($urandom_range(9) < 7);
    io_frontendTrigger_tEnableVec_3 = ($urandom_range(9) < 7);
    io_frontendTrigger_debugMode = ($urandom_range(19) == 0);
    io_frontendTrigger_triggerCanRaiseBpExp = 1'($urandom_range(1));
    // 顺序取指包; 5% 全随机 pc 打散
    if ($urandom_range(19) == 0) pcbase = {45'($urandom), 5'($urandom)};
    else pcbase = {BASE_HI + 45'($urandom_range(3)), 5'($urandom)};
    io_pc_0 = 50'(pcbase + 0);
    io_pc_1 = 50'(pcbase + 2);
    io_pc_2 = 50'(pcbase + 4);
    io_pc_3 = 50'(pcbase + 6);
    io_pc_4 = 50'(pcbase + 8);
    io_pc_5 = 50'(pcbase + 10);
    io_pc_6 = 50'(pcbase + 12);
    io_pc_7 = 50'(pcbase + 14);
    io_pc_8 = 50'(pcbase + 16);
    io_pc_9 = 50'(pcbase + 18);
    io_pc_10 = 50'(pcbase + 20);
    io_pc_11 = 50'(pcbase + 22);
    io_pc_12 = 50'(pcbase + 24);
    io_pc_13 = 50'(pcbase + 26);
    io_pc_14 = 50'(pcbase + 28);
    io_pc_15 = 50'(pcbase + 30);
  endtask

  initial begin
    rst = 1;
    io_frontendTrigger_tUpdate_valid = '0;
    io_frontendTrigger_tUpdate_bits_addr = '0;
    io_frontendTrigger_tUpdate_bits_tdata_matchType = '0;
    io_frontendTrigger_tUpdate_bits_tdata_select = '0;
    io_frontendTrigger_tUpdate_bits_tdata_action = '0;
    io_frontendTrigger_tUpdate_bits_tdata_chain = '0;
    io_frontendTrigger_tUpdate_bits_tdata_tdata2 = '0;
    io_frontendTrigger_tEnableVec_0 = '0;
    io_frontendTrigger_tEnableVec_1 = '0;
    io_frontendTrigger_tEnableVec_2 = '0;
    io_frontendTrigger_tEnableVec_3 = '0;
    io_frontendTrigger_debugMode = '0;
    io_frontendTrigger_triggerCanRaiseBpExp = '0;
    io_pc_0 = '0;
    io_pc_1 = '0;
    io_pc_2 = '0;
    io_pc_3 = '0;
    io_pc_4 = '0;
    io_pc_5 = '0;
    io_pc_6 = '0;
    io_pc_7 = '0;
    io_pc_8 = '0;
    io_pc_9 = '0;
    io_pc_10 = '0;
    io_pc_11 = '0;
    io_pc_12 = '0;
    io_pc_13 = '0;
    io_pc_14 = '0;
    io_pc_15 = '0;
    repeat (5) @(posedge clk);
    @(negedge clk);
    rst = 0;
    repeat (WARMUP) @(posedge clk);
    for (cyc = 0; cyc < NCYCLES; cyc++) begin
      @(negedge clk);
      if ($urandom_range(199) == 0) begin  // 偶发异步复位脉冲(两侧共享)
        rst = 1;
        @(negedge clk);
        rst = 0;
      end
      drive_random();
      #1;
      checks++;
      if (g_io_triggered_0 !== i_io_triggered_0) begin errors++; if (errors < 20) $display("MISMATCH io_triggered_0 @%0d g=%h i=%h", cyc, g_io_triggered_0, i_io_triggered_0); end
      if (g_io_triggered_1 !== i_io_triggered_1) begin errors++; if (errors < 20) $display("MISMATCH io_triggered_1 @%0d g=%h i=%h", cyc, g_io_triggered_1, i_io_triggered_1); end
      if (g_io_triggered_2 !== i_io_triggered_2) begin errors++; if (errors < 20) $display("MISMATCH io_triggered_2 @%0d g=%h i=%h", cyc, g_io_triggered_2, i_io_triggered_2); end
      if (g_io_triggered_3 !== i_io_triggered_3) begin errors++; if (errors < 20) $display("MISMATCH io_triggered_3 @%0d g=%h i=%h", cyc, g_io_triggered_3, i_io_triggered_3); end
      if (g_io_triggered_4 !== i_io_triggered_4) begin errors++; if (errors < 20) $display("MISMATCH io_triggered_4 @%0d g=%h i=%h", cyc, g_io_triggered_4, i_io_triggered_4); end
      if (g_io_triggered_5 !== i_io_triggered_5) begin errors++; if (errors < 20) $display("MISMATCH io_triggered_5 @%0d g=%h i=%h", cyc, g_io_triggered_5, i_io_triggered_5); end
      if (g_io_triggered_6 !== i_io_triggered_6) begin errors++; if (errors < 20) $display("MISMATCH io_triggered_6 @%0d g=%h i=%h", cyc, g_io_triggered_6, i_io_triggered_6); end
      if (g_io_triggered_7 !== i_io_triggered_7) begin errors++; if (errors < 20) $display("MISMATCH io_triggered_7 @%0d g=%h i=%h", cyc, g_io_triggered_7, i_io_triggered_7); end
      if (g_io_triggered_8 !== i_io_triggered_8) begin errors++; if (errors < 20) $display("MISMATCH io_triggered_8 @%0d g=%h i=%h", cyc, g_io_triggered_8, i_io_triggered_8); end
      if (g_io_triggered_9 !== i_io_triggered_9) begin errors++; if (errors < 20) $display("MISMATCH io_triggered_9 @%0d g=%h i=%h", cyc, g_io_triggered_9, i_io_triggered_9); end
      if (g_io_triggered_10 !== i_io_triggered_10) begin errors++; if (errors < 20) $display("MISMATCH io_triggered_10 @%0d g=%h i=%h", cyc, g_io_triggered_10, i_io_triggered_10); end
      if (g_io_triggered_11 !== i_io_triggered_11) begin errors++; if (errors < 20) $display("MISMATCH io_triggered_11 @%0d g=%h i=%h", cyc, g_io_triggered_11, i_io_triggered_11); end
      if (g_io_triggered_12 !== i_io_triggered_12) begin errors++; if (errors < 20) $display("MISMATCH io_triggered_12 @%0d g=%h i=%h", cyc, g_io_triggered_12, i_io_triggered_12); end
      if (g_io_triggered_13 !== i_io_triggered_13) begin errors++; if (errors < 20) $display("MISMATCH io_triggered_13 @%0d g=%h i=%h", cyc, g_io_triggered_13, i_io_triggered_13); end
      if (g_io_triggered_14 !== i_io_triggered_14) begin errors++; if (errors < 20) $display("MISMATCH io_triggered_14 @%0d g=%h i=%h", cyc, g_io_triggered_14, i_io_triggered_14); end
      if (g_io_triggered_15 !== i_io_triggered_15) begin errors++; if (errors < 20) $display("MISMATCH io_triggered_15 @%0d g=%h i=%h", cyc, g_io_triggered_15, i_io_triggered_15); end
      if (g_io_triggered_0 == 4'h0) act_bp++; else if (g_io_triggered_0 == 4'h1) act_dbg++;
      if (g_io_triggered_0 != 4'hF) act_any++;
      if (g_io_triggered_1 == 4'h0) act_bp++; else if (g_io_triggered_1 == 4'h1) act_dbg++;
      if (g_io_triggered_1 != 4'hF) act_any++;
      if (g_io_triggered_2 == 4'h0) act_bp++; else if (g_io_triggered_2 == 4'h1) act_dbg++;
      if (g_io_triggered_2 != 4'hF) act_any++;
      if (g_io_triggered_3 == 4'h0) act_bp++; else if (g_io_triggered_3 == 4'h1) act_dbg++;
      if (g_io_triggered_3 != 4'hF) act_any++;
      if (g_io_triggered_4 == 4'h0) act_bp++; else if (g_io_triggered_4 == 4'h1) act_dbg++;
      if (g_io_triggered_4 != 4'hF) act_any++;
      if (g_io_triggered_5 == 4'h0) act_bp++; else if (g_io_triggered_5 == 4'h1) act_dbg++;
      if (g_io_triggered_5 != 4'hF) act_any++;
      if (g_io_triggered_6 == 4'h0) act_bp++; else if (g_io_triggered_6 == 4'h1) act_dbg++;
      if (g_io_triggered_6 != 4'hF) act_any++;
      if (g_io_triggered_7 == 4'h0) act_bp++; else if (g_io_triggered_7 == 4'h1) act_dbg++;
      if (g_io_triggered_7 != 4'hF) act_any++;
      if (g_io_triggered_8 == 4'h0) act_bp++; else if (g_io_triggered_8 == 4'h1) act_dbg++;
      if (g_io_triggered_8 != 4'hF) act_any++;
      if (g_io_triggered_9 == 4'h0) act_bp++; else if (g_io_triggered_9 == 4'h1) act_dbg++;
      if (g_io_triggered_9 != 4'hF) act_any++;
      if (g_io_triggered_10 == 4'h0) act_bp++; else if (g_io_triggered_10 == 4'h1) act_dbg++;
      if (g_io_triggered_10 != 4'hF) act_any++;
      if (g_io_triggered_11 == 4'h0) act_bp++; else if (g_io_triggered_11 == 4'h1) act_dbg++;
      if (g_io_triggered_11 != 4'hF) act_any++;
      if (g_io_triggered_12 == 4'h0) act_bp++; else if (g_io_triggered_12 == 4'h1) act_dbg++;
      if (g_io_triggered_12 != 4'hF) act_any++;
      if (g_io_triggered_13 == 4'h0) act_bp++; else if (g_io_triggered_13 == 4'h1) act_dbg++;
      if (g_io_triggered_13 != 4'hF) act_any++;
      if (g_io_triggered_14 == 4'h0) act_bp++; else if (g_io_triggered_14 == 4'h1) act_dbg++;
      if (g_io_triggered_14 != 4'hF) act_any++;
      if (g_io_triggered_15 == 4'h0) act_bp++; else if (g_io_triggered_15 == 4'h1) act_dbg++;
      if (g_io_triggered_15 != 4'hF) act_any++;
    end
    $display("ACTIVITY triggered_any=%0d bp_exception=%0d debug_mode=%0d", act_any, act_bp, act_dbg);
    if (errors == 0) $display("TEST PASSED checks=%0d errors=0", checks);
    else             $display("TEST FAILED checks=%0d errors=%0d", checks, errors);
    $finish;
  end
endmodule
