// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module StorePipe(	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7
  input          clock,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7
                 reset,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7
  input  [47:0]  io_lsu_s1_paddr,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  input          io_lsu_s1_kill,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
                 io_lsu_s2_kill,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  input  [49:0]  io_lsu_s2_pc,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  output         io_lsu_req_ready,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  input          io_lsu_req_valid,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  input  [4:0]   io_lsu_req_bits_cmd,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  input  [49:0]  io_lsu_req_bits_vaddr,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  input  [3:0]   io_lsu_req_bits_instrtype,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  input          io_lsu_resp_ready,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  output         io_lsu_resp_valid,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
                 io_lsu_resp_bits_miss,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
                 io_lsu_resp_bits_replay,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
                 io_lsu_resp_bits_tag_error,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  input          io_meta_read_ready,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  output         io_meta_read_valid,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  output [7:0]   io_meta_read_bits_idx,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  output [3:0]   io_meta_read_bits_way_en,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  input  [1:0]   io_meta_resp_0_coh_state,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
                 io_meta_resp_1_coh_state,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
                 io_meta_resp_2_coh_state,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
                 io_meta_resp_3_coh_state,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  input          io_tag_read_ready,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  output         io_tag_read_valid,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  output [7:0]   io_tag_read_bits_idx,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  output [3:0]   io_tag_read_bits_way_en,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  input  [42:0]  io_tag_resp_0,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
                 io_tag_resp_1,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
                 io_tag_resp_2,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
                 io_tag_resp_3,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  input          io_miss_req_ready,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  output         io_miss_req_valid,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  output [3:0]   io_miss_req_bits_source,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  output [2:0]   io_miss_req_bits_pf_source,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  output [4:0]   io_miss_req_bits_cmd,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  output [47:0]  io_miss_req_bits_addr,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  output [49:0]  io_miss_req_bits_vaddr,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
                 io_miss_req_bits_pc,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  output         io_miss_req_bits_lqIdx_flag,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  output [6:0]   io_miss_req_bits_lqIdx_value,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  output         io_miss_req_bits_full_overwrite,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  output [2:0]   io_miss_req_bits_word_idx,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  output [127:0] io_miss_req_bits_amo_data,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  output [15:0]  io_miss_req_bits_amo_mask,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  output [127:0] io_miss_req_bits_amo_cmp,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  output [1:0]   io_miss_req_bits_req_coh_state,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  output [5:0]   io_miss_req_bits_id,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  output         io_miss_req_bits_isBtoT,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  output [3:0]   io_miss_req_bits_occupy_way,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  output         io_miss_req_bits_cancel,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  output [511:0] io_miss_req_bits_store_data,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  output [63:0]  io_miss_req_bits_store_mask,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  output         io_replace_access_valid,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  output [7:0]   io_replace_access_bits_set,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  output [1:0]   io_replace_access_bits_way,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  output         io_replace_way_set_valid,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  output [7:0]   io_replace_way_set_bits,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  output [1:0]   io_replace_way_dmWay,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  input  [1:0]   io_replace_way_way,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  output         io_error_valid,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
                 io_error_bits_source_tag,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
                 io_error_bits_source_data,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
                 io_error_bits_source_l2,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
                 io_error_bits_opType_fetch,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
                 io_error_bits_opType_load,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
                 io_error_bits_opType_store,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
                 io_error_bits_opType_probe,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
                 io_error_bits_opType_release,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
                 io_error_bits_opType_atom,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  output [47:0]  io_error_bits_paddr,	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
  output         io_error_bits_report_to_beu	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:60:14
);

  wire             io_lsu_req_ready_0 = io_meta_read_ready & io_tag_read_ready;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:103:42
  wire             _GEN = io_lsu_req_valid & ~io_lsu_req_ready_0;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:103:42, :106:{59,62}
  reg              s1_valid;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:115:25
  reg  [4:0]       s1_req_cmd;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:116:25
  reg  [49:0]      s1_req_vaddr;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:116:25
  reg  [3:0]       s1_req_instrtype;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:116:25
  reg              s2_valid_REG;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:149:25
  reg              s2_valid_REG_1;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:149:46
  wire             s2_valid = s2_valid_REG & s2_valid_REG_1;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:149:{25,36,46}
  reg  [49:0]      s2_req_vaddr;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:150:25
  reg              s2_hit;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:152:25
  reg  [47:0]      s2_paddr;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:153:27
  reg  [1:0]       s2_hit_coh_state;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:154:29
  reg              s2_is_prefetch;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:155:33
  wire             io_miss_req_valid_0 = s2_valid & ~s2_hit & s2_is_prefetch;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:149:36, :152:25, :155:33, :158:28, :172:46
  wire             _GEN_0 = s2_valid & ~io_lsu_s2_kill;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:149:36, :192:{43,46}
  wire             _GEN_1 = s2_valid & s2_hit & ~io_lsu_s2_kill;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:149:36, :152:25, :192:46, :193:52
  wire             _GEN_2 = s2_valid & ~s2_hit & ~io_lsu_s2_kill;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:149:36, :152:25, :158:28, :192:46, :194:52
  wire             _GEN_3 = io_miss_req_ready & io_miss_req_valid_0 & ~io_lsu_s2_kill;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:172:46, :192:46, :195:65
  wire             _GEN_4 = io_miss_req_valid_0 & ~io_miss_req_ready & ~io_lsu_s2_kill;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:172:46, :192:46, :196:{73,92}
  wire             _s1_tag_match_T_3 =
    io_tag_resp_0[35:0] == io_lsu_s1_paddr[47:12] & (|io_meta_resp_0_coh_state);	// home/eda/xs-env/xs-clean/rocket-chip/src/main/scala/tilelink/Metadata.scala:50:45, home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/L1Cache.scala:81:41, home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:119:48, :127:{62,84}
  wire             _s1_tag_match_T_7 =
    io_tag_resp_1[35:0] == io_lsu_s1_paddr[47:12] & (|io_meta_resp_1_coh_state);	// home/eda/xs-env/xs-clean/rocket-chip/src/main/scala/tilelink/Metadata.scala:50:45, home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/L1Cache.scala:81:41, home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:119:48, :127:{62,84}
  wire             _s1_tag_match_T_11 =
    io_tag_resp_2[35:0] == io_lsu_s1_paddr[47:12] & (|io_meta_resp_2_coh_state);	// home/eda/xs-env/xs-clean/rocket-chip/src/main/scala/tilelink/Metadata.scala:50:45, home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/L1Cache.scala:81:41, home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:119:48, :127:{62,84}
  wire             _s1_tag_match_T_15 =
    io_tag_resp_3[35:0] == io_lsu_s1_paddr[47:12] & (|io_meta_resp_3_coh_state);	// home/eda/xs-env/xs-clean/rocket-chip/src/main/scala/tilelink/Metadata.scala:50:45, home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/L1Cache.scala:81:41, home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:119:48, :127:{62,84}
  wire [3:0]       s1_tag_match =
    {_s1_tag_match_T_15, _s1_tag_match_T_11, _s1_tag_match_T_7, _s1_tag_match_T_3};	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:127:{84,123}
  wire [1:0]       s1_hit_meta_coh_state =
    (|s1_tag_match)
      ? (_s1_tag_match_T_3 ? io_meta_resp_0_coh_state : 2'h0)
        | (_s1_tag_match_T_7 ? io_meta_resp_1_coh_state : 2'h0)
        | (_s1_tag_match_T_11 ? io_meta_resp_2_coh_state : 2'h0)
        | (_s1_tag_match_T_15 ? io_meta_resp_3_coh_state : 2'h0)
      : 2'h0;	// home/eda/xs-env/xs-clean/rocket-chip/src/main/scala/tilelink/Metadata.scala:50:45, home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:127:{84,123}, :130:{24,38}, src/main/scala/chisel3/util/Mux.scala:30:73
  wire             _r_c_cat_T_29 = s1_req_cmd == 5'h1;	// home/eda/xs-env/xs-clean/rocket-chip/src/main/scala/rocket/Consts.scala:91:32, home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:116:25
  wire             _r_c_cat_T_30 = s1_req_cmd == 5'h11;	// home/eda/xs-env/xs-clean/rocket-chip/src/main/scala/rocket/Consts.scala:91:49, home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:116:25
  wire             _r_c_cat_T_32 = s1_req_cmd == 5'h7;	// home/eda/xs-env/xs-clean/rocket-chip/src/main/scala/rocket/Consts.scala:91:66, home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:116:25
  wire             _r_c_cat_T_34 = s1_req_cmd == 5'h4;	// home/eda/xs-env/xs-clean/rocket-chip/src/main/scala/util/package.scala:16:47, home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:116:25
  wire             _r_c_cat_T_35 = s1_req_cmd == 5'h9;	// home/eda/xs-env/xs-clean/rocket-chip/src/main/scala/util/package.scala:16:47, home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:116:25
  wire             _r_c_cat_T_36 = s1_req_cmd == 5'hA;	// home/eda/xs-env/xs-clean/rocket-chip/src/main/scala/util/package.scala:16:47, home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:116:25
  wire             _r_c_cat_T_37 = s1_req_cmd == 5'hB;	// home/eda/xs-env/xs-clean/rocket-chip/src/main/scala/util/package.scala:16:47, home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:116:25
  wire             _r_c_cat_T_41 = s1_req_cmd == 5'h8;	// home/eda/xs-env/xs-clean/rocket-chip/src/main/scala/util/package.scala:16:47, home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:116:25
  wire             _r_c_cat_T_42 = s1_req_cmd == 5'hC;	// home/eda/xs-env/xs-clean/rocket-chip/src/main/scala/util/package.scala:16:47, home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:116:25
  wire             _r_c_cat_T_43 = s1_req_cmd == 5'hD;	// home/eda/xs-env/xs-clean/rocket-chip/src/main/scala/util/package.scala:16:47, home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:116:25
  wire             _r_c_cat_T_44 = s1_req_cmd == 5'hE;	// home/eda/xs-env/xs-clean/rocket-chip/src/main/scala/util/package.scala:16:47, home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:116:25
  wire             _r_c_cat_T_45 = s1_req_cmd == 5'hF;	// home/eda/xs-env/xs-clean/rocket-chip/src/main/scala/util/package.scala:16:47, home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:116:25
  wire             _r_c_cat_T_51 = s1_req_cmd == 5'h1A;	// home/eda/xs-env/xs-clean/rocket-chip/src/main/scala/rocket/Consts.scala:86:33, home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:116:25
  wire             _r_c_cat_T_52 = s1_req_cmd == 5'h1B;	// home/eda/xs-env/xs-clean/rocket-chip/src/main/scala/rocket/Consts.scala:86:54, home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:116:25
  wire             _r_c_cat_T_54 = s1_req_cmd == 5'h18;	// home/eda/xs-env/xs-clean/rocket-chip/src/main/scala/rocket/Consts.scala:86:75, home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:116:25
  wire [3:0]       _r_T =
    {_r_c_cat_T_29 | _r_c_cat_T_30 | _r_c_cat_T_32 | _r_c_cat_T_34 | _r_c_cat_T_35
       | _r_c_cat_T_36 | _r_c_cat_T_37 | _r_c_cat_T_41 | _r_c_cat_T_42 | _r_c_cat_T_43
       | _r_c_cat_T_44 | _r_c_cat_T_45 | _r_c_cat_T_51 | _r_c_cat_T_52 | _r_c_cat_T_54,
     _r_c_cat_T_29 | _r_c_cat_T_30 | _r_c_cat_T_32 | _r_c_cat_T_34 | _r_c_cat_T_35
       | _r_c_cat_T_36 | _r_c_cat_T_37 | _r_c_cat_T_41 | _r_c_cat_T_42 | _r_c_cat_T_43
       | _r_c_cat_T_44 | _r_c_cat_T_45 | _r_c_cat_T_51 | _r_c_cat_T_52 | _r_c_cat_T_54
       | s1_req_cmd == 5'h3 | s1_req_cmd == 5'h6,
     s1_hit_meta_coh_state};	// home/eda/xs-env/xs-clean/rocket-chip/src/main/scala/rocket/Consts.scala:86:{33,54,75}, :91:{32,49,66,76}, :92:{54,64,71}, home/eda/xs-env/xs-clean/rocket-chip/src/main/scala/tilelink/Metadata.scala:58:19, home/eda/xs-env/xs-clean/rocket-chip/src/main/scala/util/package.scala:16:47, home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:116:25, :130:24, :178:24
  wire [1:0]       _r_T_27 = {1'h0, _r_T == 4'hC};	// home/eda/xs-env/xs-clean/rocket-chip/src/main/scala/tilelink/Metadata.scala:58:19, home/eda/xs-env/xs-clean/rocket-chip/src/main/scala/util/Misc.scala:35:36, :49:20, home/eda/xs-env/xs-clean/rocket-chip/src/main/scala/util/package.scala:16:47, home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:86:27
  wire [15:0][1:0] _GEN_5 =
    {{2'h3},
     {2'h3},
     {2'h2},
     {_r_T_27},
     {_r_T_27},
     {_r_T_27},
     {_r_T_27},
     {_r_T_27},
     {2'h3},
     {2'h2},
     {2'h2},
     {2'h1},
     {2'h3},
     {2'h2},
     {2'h1},
     {2'h0}};	// home/eda/xs-env/xs-clean/rocket-chip/src/main/scala/rocket/Consts.scala:92:54, home/eda/xs-env/xs-clean/rocket-chip/src/main/scala/tilelink/Metadata.scala:50:45, :61:10, :62:10, home/eda/xs-env/xs-clean/rocket-chip/src/main/scala/util/Misc.scala:35:36, :49:20
  wire             s0_fire = io_lsu_req_ready_0 & io_lsu_req_valid;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:103:42, src/main/scala/chisel3/util/Decoupled.scala:51:35
  always @(posedge clock) begin	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7
    s1_valid <= s0_fire;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:115:25, src/main/scala/chisel3/util/Decoupled.scala:51:35
    if (s0_fire) begin	// src/main/scala/chisel3/util/Decoupled.scala:51:35
      s1_req_cmd <= io_lsu_req_bits_cmd;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:116:25
      s1_req_vaddr <= io_lsu_req_bits_vaddr;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:116:25
      s1_req_instrtype <= io_lsu_req_bits_instrtype;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:116:25
    end
    s2_valid_REG <= s1_valid;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:115:25, :149:25
    s2_valid_REG_1 <= ~io_lsu_s1_kill;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:149:{46,47}
    if (s1_valid) begin	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:115:25
      s2_req_vaddr <= s1_req_vaddr;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:116:25, :150:25
      s2_hit <=
        (_r_T == 4'h3 | _r_T == 4'h2 | _r_T == 4'h1 | _r_T == 4'h7 | _r_T == 4'h6
         | (&_r_T) | _r_T == 4'hE) & _GEN_5[_r_T] == s1_hit_meta_coh_state
        & (|s1_tag_match);	// home/eda/xs-env/xs-clean/rocket-chip/src/main/scala/tilelink/Metadata.scala:46:46, :58:19, :60:10, :61:10, :62:10, :63:10, :64:10, home/eda/xs-env/xs-clean/rocket-chip/src/main/scala/util/Misc.scala:35:{9,36}, :49:20, home/eda/xs-env/xs-clean/rocket-chip/src/main/scala/util/package.scala:16:47, home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:127:123, :130:{24,38}, :134:67, :152:25
      s2_paddr <= io_lsu_s1_paddr;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:153:27
      s2_hit_coh_state <= s1_hit_meta_coh_state;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:130:24, :154:29
      s2_is_prefetch <= s1_req_instrtype == 4'h3;	// home/eda/xs-env/xs-clean/rocket-chip/src/main/scala/tilelink/Metadata.scala:60:10, home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:116:25, :155:{33,51}
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7
    `ifdef FIRRTL_BEFORE_INITIAL	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7
      `FIRRTL_BEFORE_INITIAL	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:5];	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7
    initial begin	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7
      `ifdef INIT_RANDOM_PROLOG_	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7
        `INIT_RANDOM_PROLOG_	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7
        for (logic [2:0] i = 3'h0; i < 3'h6; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7
        end	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7
        s1_valid = _RANDOM[3'h0][0];	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :115:25
        s1_req_cmd = _RANDOM[3'h0][5:1];	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :115:25, :116:25
        s1_req_vaddr = {_RANDOM[3'h0][31:6], _RANDOM[3'h1][23:0]};	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :115:25, :116:25
        s1_req_instrtype = _RANDOM[3'h1][27:24];	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :116:25
        s2_valid_REG = _RANDOM[3'h1][28];	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :116:25, :149:25
        s2_valid_REG_1 = _RANDOM[3'h1][29];	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :116:25, :149:46
        s2_req_vaddr = {_RANDOM[3'h2][31:3], _RANDOM[3'h3][20:0]};	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :150:25
        s2_hit = _RANDOM[3'h3][25];	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :150:25, :152:25
        s2_paddr = {_RANDOM[3'h3][31:26], _RANDOM[3'h4], _RANDOM[3'h5][9:0]};	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :150:25, :153:27
        s2_hit_coh_state = _RANDOM[3'h5][11:10];	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :153:27, :154:29
        s2_is_prefetch = _RANDOM[3'h5][12];	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :153:27, :155:33
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7
      `FIRRTL_AFTER_INITIAL	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_lsu_req_ready = io_lsu_req_ready_0;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :103:42
  assign io_lsu_resp_valid = s2_valid;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :149:36
  assign io_lsu_resp_bits_miss = ~s2_hit;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :152:25, :158:28
  assign io_lsu_resp_bits_replay = 1'h0;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :86:27
  assign io_lsu_resp_bits_tag_error = 1'h0;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :86:27
  assign io_meta_read_valid = io_lsu_req_valid;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7
  assign io_meta_read_bits_idx = io_lsu_req_bits_vaddr[13:6];	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/L1Cache.scala:84:33, home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7
  assign io_meta_read_bits_way_en = 4'hF;	// home/eda/xs-env/xs-clean/rocket-chip/src/main/scala/util/package.scala:16:47, home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7
  assign io_tag_read_valid = io_lsu_req_valid;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7
  assign io_tag_read_bits_idx = io_lsu_req_bits_vaddr[13:6];	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/L1Cache.scala:84:33, home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7
  assign io_tag_read_bits_way_en = 4'hF;	// home/eda/xs-env/xs-clean/rocket-chip/src/main/scala/util/package.scala:16:47, home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7
  assign io_miss_req_valid = io_miss_req_valid_0;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :172:46
  assign io_miss_req_bits_source = 4'h3;	// home/eda/xs-env/xs-clean/rocket-chip/src/main/scala/tilelink/Metadata.scala:60:10, home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7
  assign io_miss_req_bits_pf_source = 3'h4;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7
  assign io_miss_req_bits_cmd = 5'h3;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :178:24
  assign io_miss_req_bits_addr = {s2_paddr[47:6], 6'h0};	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/L1Cache.scala:87:{42,59}, home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :153:27, :174:20
  assign io_miss_req_bits_vaddr = s2_req_vaddr;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :150:25
  assign io_miss_req_bits_pc = io_lsu_s2_pc;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7
  assign io_miss_req_bits_lqIdx_flag = 1'h0;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :86:27
  assign io_miss_req_bits_lqIdx_value = 7'h0;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :174:20
  assign io_miss_req_bits_full_overwrite = 1'h0;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :86:27
  assign io_miss_req_bits_word_idx = 3'h0;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7
  assign io_miss_req_bits_amo_data = 128'h0;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :174:20
  assign io_miss_req_bits_amo_mask = 16'h0;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :174:20
  assign io_miss_req_bits_amo_cmp = 128'h0;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :174:20
  assign io_miss_req_bits_req_coh_state = s2_hit_coh_state;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :154:29
  assign io_miss_req_bits_id = 6'h0;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :174:20
  assign io_miss_req_bits_isBtoT = 1'h0;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :86:27
  assign io_miss_req_bits_occupy_way = 4'h0;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :97:32
  assign io_miss_req_bits_cancel = io_lsu_s2_kill;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7
  assign io_miss_req_bits_store_data = 512'h0;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :174:20
  assign io_miss_req_bits_store_mask = 64'h0;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :174:20
  assign io_replace_access_valid = 1'h0;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :86:27
  assign io_replace_access_bits_set = 8'h0;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :190:27
  assign io_replace_access_bits_way = 2'h0;	// home/eda/xs-env/xs-clean/rocket-chip/src/main/scala/tilelink/Metadata.scala:50:45, home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7
  assign io_replace_way_set_valid = 1'h0;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :86:27
  assign io_replace_way_set_bits = s1_req_vaddr[13:6];	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/L1Cache.scala:84:33, home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :116:25
  assign io_replace_way_dmWay = s1_req_vaddr[15:14];	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/DCacheWrapper.scala:265:9, home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :116:25
  assign io_error_valid = 1'h0;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :86:27
  assign io_error_bits_source_tag = 1'h0;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :86:27
  assign io_error_bits_source_data = 1'h0;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :86:27
  assign io_error_bits_source_l2 = 1'h0;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :86:27
  assign io_error_bits_opType_fetch = 1'h0;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :86:27
  assign io_error_bits_opType_load = 1'h0;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :86:27
  assign io_error_bits_opType_store = 1'h0;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :86:27
  assign io_error_bits_opType_probe = 1'h0;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :86:27
  assign io_error_bits_opType_release = 1'h0;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :86:27
  assign io_error_bits_opType_atom = 1'h0;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :86:27
  assign io_error_bits_paddr = 48'h0;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :86:27
  assign io_error_bits_report_to_beu = 1'h0;	// home/eda/xs-env/xs-clean/src/main/scala/xiangshan/cache/dcache/storepipe/StorePipe.scala:59:7, :86:27
endmodule


// ----- 8< ----- FILE "ref_StorePipe_StorePipe.sv" ----- 8< -----

// Generated by CIRCT firtool-1.62.1
`define ref_StorePipe_StorePipe_perfCnt_bore _GEN
`define ref_StorePipe_StorePipe_perfCnt_bore_1 _GEN_0
`define ref_StorePipe_StorePipe_perfCnt_bore_2 _GEN_1
`define ref_StorePipe_StorePipe_perfCnt_bore_3 _GEN_2
`define ref_StorePipe_StorePipe_perfCnt_bore_4 _GEN_3
`define ref_StorePipe_StorePipe_perfCnt_bore_5 _GEN_4
