// ====================================================================
// StorePipe_surface -- target-scoped semantic-surface wrapper
// derivative_id : G0-StorePipe-observable-v1
// GENERATED by derive_surface.py (FIRRTL last-connect-wins + derivative
// port widths).  DO NOT hand-edit: regenerate + re-hash in LEDGER.tsv.
//
// REF side: instantiates the canonical derivative StorePipe (hash-pinned).
// Surface = 59 inputs+defined-outputs re-exported; 14 UNSPECIFIED_BY_SOURCE
// (invalidate-only) output leaves are LEFT UNCONNECTED (off the compare
// surface).  Not dont_verify, not 0-fill, not a generic exclusion.
// ====================================================================
module StorePipe_surface (
  input   clock,
  input   reset,
  input   [47:0] io_lsu_s1_paddr,
  input   io_lsu_s1_kill,
  input   io_lsu_s2_kill,
  input   [49:0] io_lsu_s2_pc,
  output  io_lsu_req_ready,
  input   io_lsu_req_valid,
  input   [4:0] io_lsu_req_bits_cmd,
  input   [49:0] io_lsu_req_bits_vaddr,
  input   [3:0] io_lsu_req_bits_instrtype,
  input   io_lsu_resp_ready,
  output  io_lsu_resp_valid,
  output  io_lsu_resp_bits_miss,
  output  io_lsu_resp_bits_replay,
  output  io_lsu_resp_bits_tag_error,
  input   io_meta_read_ready,
  output  io_meta_read_valid,
  output  [7:0] io_meta_read_bits_idx,
  output  [3:0] io_meta_read_bits_way_en,
  input   [1:0] io_meta_resp_0_coh_state,
  input   [1:0] io_meta_resp_1_coh_state,
  input   [1:0] io_meta_resp_2_coh_state,
  input   [1:0] io_meta_resp_3_coh_state,
  input   io_tag_read_ready,
  output  io_tag_read_valid,
  output  [7:0] io_tag_read_bits_idx,
  output  [3:0] io_tag_read_bits_way_en,
  input   [42:0] io_tag_resp_0,
  input   [42:0] io_tag_resp_1,
  input   [42:0] io_tag_resp_2,
  input   [42:0] io_tag_resp_3,
  input   io_miss_req_ready,
  output  io_miss_req_valid,
  output  [3:0] io_miss_req_bits_source,
  output  [2:0] io_miss_req_bits_pf_source,
  output  [4:0] io_miss_req_bits_cmd,
  output  [47:0] io_miss_req_bits_addr,
  output  [49:0] io_miss_req_bits_vaddr,
  output  [49:0] io_miss_req_bits_pc,
  output  [1:0] io_miss_req_bits_req_coh_state,
  output  io_miss_req_bits_cancel,
  output  io_replace_access_valid,
  output  io_replace_way_set_valid,
  output  [7:0] io_replace_way_set_bits,
  output  [1:0] io_replace_way_dmWay,
  input   [1:0] io_replace_way_way,
  output  io_error_valid,
  output  io_error_bits_source_tag,
  output  io_error_bits_source_data,
  output  io_error_bits_source_l2,
  output  io_error_bits_opType_fetch,
  output  io_error_bits_opType_load,
  output  io_error_bits_opType_store,
  output  io_error_bits_opType_probe,
  output  io_error_bits_opType_release,
  output  io_error_bits_opType_atom,
  output  [47:0] io_error_bits_paddr,
  output  io_error_bits_report_to_beu
);

  wire io_miss_req_bits_lqIdx_flag; // UNSPECIFIED_BY_SOURCE: off surface
  wire [6:0] io_miss_req_bits_lqIdx_value; // UNSPECIFIED_BY_SOURCE: off surface
  wire io_miss_req_bits_full_overwrite; // UNSPECIFIED_BY_SOURCE: off surface
  wire [2:0] io_miss_req_bits_word_idx; // UNSPECIFIED_BY_SOURCE: off surface
  wire [127:0] io_miss_req_bits_amo_data; // UNSPECIFIED_BY_SOURCE: off surface
  wire [15:0] io_miss_req_bits_amo_mask; // UNSPECIFIED_BY_SOURCE: off surface
  wire [127:0] io_miss_req_bits_amo_cmp; // UNSPECIFIED_BY_SOURCE: off surface
  wire [5:0] io_miss_req_bits_id; // UNSPECIFIED_BY_SOURCE: off surface
  wire io_miss_req_bits_isBtoT; // UNSPECIFIED_BY_SOURCE: off surface
  wire [3:0] io_miss_req_bits_occupy_way; // UNSPECIFIED_BY_SOURCE: off surface
  wire [511:0] io_miss_req_bits_store_data; // UNSPECIFIED_BY_SOURCE: off surface
  wire [63:0] io_miss_req_bits_store_mask; // UNSPECIFIED_BY_SOURCE: off surface
  wire [7:0] io_replace_access_bits_set; // UNSPECIFIED_BY_SOURCE: off surface
  wire [1:0] io_replace_access_bits_way; // UNSPECIFIED_BY_SOURCE: off surface

  StorePipe u_dut (
    .clock(clock),
    .reset(reset),
    .io_lsu_s1_paddr(io_lsu_s1_paddr),
    .io_lsu_s1_kill(io_lsu_s1_kill),
    .io_lsu_s2_kill(io_lsu_s2_kill),
    .io_lsu_s2_pc(io_lsu_s2_pc),
    .io_lsu_req_ready(io_lsu_req_ready),
    .io_lsu_req_valid(io_lsu_req_valid),
    .io_lsu_req_bits_cmd(io_lsu_req_bits_cmd),
    .io_lsu_req_bits_vaddr(io_lsu_req_bits_vaddr),
    .io_lsu_req_bits_instrtype(io_lsu_req_bits_instrtype),
    .io_lsu_resp_ready(io_lsu_resp_ready),
    .io_lsu_resp_valid(io_lsu_resp_valid),
    .io_lsu_resp_bits_miss(io_lsu_resp_bits_miss),
    .io_lsu_resp_bits_replay(io_lsu_resp_bits_replay),
    .io_lsu_resp_bits_tag_error(io_lsu_resp_bits_tag_error),
    .io_meta_read_ready(io_meta_read_ready),
    .io_meta_read_valid(io_meta_read_valid),
    .io_meta_read_bits_idx(io_meta_read_bits_idx),
    .io_meta_read_bits_way_en(io_meta_read_bits_way_en),
    .io_meta_resp_0_coh_state(io_meta_resp_0_coh_state),
    .io_meta_resp_1_coh_state(io_meta_resp_1_coh_state),
    .io_meta_resp_2_coh_state(io_meta_resp_2_coh_state),
    .io_meta_resp_3_coh_state(io_meta_resp_3_coh_state),
    .io_tag_read_ready(io_tag_read_ready),
    .io_tag_read_valid(io_tag_read_valid),
    .io_tag_read_bits_idx(io_tag_read_bits_idx),
    .io_tag_read_bits_way_en(io_tag_read_bits_way_en),
    .io_tag_resp_0(io_tag_resp_0),
    .io_tag_resp_1(io_tag_resp_1),
    .io_tag_resp_2(io_tag_resp_2),
    .io_tag_resp_3(io_tag_resp_3),
    .io_miss_req_ready(io_miss_req_ready),
    .io_miss_req_valid(io_miss_req_valid),
    .io_miss_req_bits_source(io_miss_req_bits_source),
    .io_miss_req_bits_pf_source(io_miss_req_bits_pf_source),
    .io_miss_req_bits_cmd(io_miss_req_bits_cmd),
    .io_miss_req_bits_addr(io_miss_req_bits_addr),
    .io_miss_req_bits_vaddr(io_miss_req_bits_vaddr),
    .io_miss_req_bits_pc(io_miss_req_bits_pc),
    .io_miss_req_bits_lqIdx_flag(io_miss_req_bits_lqIdx_flag),
    .io_miss_req_bits_lqIdx_value(io_miss_req_bits_lqIdx_value),
    .io_miss_req_bits_full_overwrite(io_miss_req_bits_full_overwrite),
    .io_miss_req_bits_word_idx(io_miss_req_bits_word_idx),
    .io_miss_req_bits_amo_data(io_miss_req_bits_amo_data),
    .io_miss_req_bits_amo_mask(io_miss_req_bits_amo_mask),
    .io_miss_req_bits_amo_cmp(io_miss_req_bits_amo_cmp),
    .io_miss_req_bits_req_coh_state(io_miss_req_bits_req_coh_state),
    .io_miss_req_bits_id(io_miss_req_bits_id),
    .io_miss_req_bits_isBtoT(io_miss_req_bits_isBtoT),
    .io_miss_req_bits_occupy_way(io_miss_req_bits_occupy_way),
    .io_miss_req_bits_cancel(io_miss_req_bits_cancel),
    .io_miss_req_bits_store_data(io_miss_req_bits_store_data),
    .io_miss_req_bits_store_mask(io_miss_req_bits_store_mask),
    .io_replace_access_valid(io_replace_access_valid),
    .io_replace_access_bits_set(io_replace_access_bits_set),
    .io_replace_access_bits_way(io_replace_access_bits_way),
    .io_replace_way_set_valid(io_replace_way_set_valid),
    .io_replace_way_set_bits(io_replace_way_set_bits),
    .io_replace_way_dmWay(io_replace_way_dmWay),
    .io_replace_way_way(io_replace_way_way),
    .io_error_valid(io_error_valid),
    .io_error_bits_source_tag(io_error_bits_source_tag),
    .io_error_bits_source_data(io_error_bits_source_data),
    .io_error_bits_source_l2(io_error_bits_source_l2),
    .io_error_bits_opType_fetch(io_error_bits_opType_fetch),
    .io_error_bits_opType_load(io_error_bits_opType_load),
    .io_error_bits_opType_store(io_error_bits_opType_store),
    .io_error_bits_opType_probe(io_error_bits_opType_probe),
    .io_error_bits_opType_release(io_error_bits_opType_release),
    .io_error_bits_opType_atom(io_error_bits_opType_atom),
    .io_error_bits_paddr(io_error_bits_paddr),
    .io_error_bits_report_to_beu(io_error_bits_report_to_beu)
  );
endmodule
