// 自动生成：scripts/gen_loadmisalignbuffer.py —— 勿手改
module LoadMisalignBuffer_xs(
  input  clock,
  input  reset,
  input  io_redirect_valid,
  input  io_redirect_bits_robIdx_flag,
  input  [7:0] io_redirect_bits_robIdx_value,
  input  io_redirect_bits_level,
  output io_enq_0_req_ready,
  input  io_enq_0_req_valid,
  input  io_enq_0_req_bits_uop_exceptionVec_0,
  input  io_enq_0_req_bits_uop_exceptionVec_1,
  input  io_enq_0_req_bits_uop_exceptionVec_2,
  input  io_enq_0_req_bits_uop_exceptionVec_3,
  input  io_enq_0_req_bits_uop_exceptionVec_5,
  input  io_enq_0_req_bits_uop_exceptionVec_6,
  input  io_enq_0_req_bits_uop_exceptionVec_7,
  input  io_enq_0_req_bits_uop_exceptionVec_8,
  input  io_enq_0_req_bits_uop_exceptionVec_9,
  input  io_enq_0_req_bits_uop_exceptionVec_10,
  input  io_enq_0_req_bits_uop_exceptionVec_11,
  input  io_enq_0_req_bits_uop_exceptionVec_12,
  input  io_enq_0_req_bits_uop_exceptionVec_13,
  input  io_enq_0_req_bits_uop_exceptionVec_14,
  input  io_enq_0_req_bits_uop_exceptionVec_15,
  input  io_enq_0_req_bits_uop_exceptionVec_16,
  input  io_enq_0_req_bits_uop_exceptionVec_17,
  input  io_enq_0_req_bits_uop_exceptionVec_18,
  input  io_enq_0_req_bits_uop_exceptionVec_19,
  input  io_enq_0_req_bits_uop_exceptionVec_20,
  input  io_enq_0_req_bits_uop_exceptionVec_21,
  input  io_enq_0_req_bits_uop_exceptionVec_22,
  input  io_enq_0_req_bits_uop_exceptionVec_23,
  input  [3:0] io_enq_0_req_bits_uop_trigger,
  input  io_enq_0_req_bits_uop_preDecodeInfo_isRVC,
  input  io_enq_0_req_bits_uop_ftqPtr_flag,
  input  [5:0] io_enq_0_req_bits_uop_ftqPtr_value,
  input  [3:0] io_enq_0_req_bits_uop_ftqOffset,
  input  [8:0] io_enq_0_req_bits_uop_fuOpType,
  input  io_enq_0_req_bits_uop_rfWen,
  input  io_enq_0_req_bits_uop_fpWen,
  input  [7:0] io_enq_0_req_bits_uop_vpu_vstart,
  input  [1:0] io_enq_0_req_bits_uop_vpu_veew,
  input  [6:0] io_enq_0_req_bits_uop_uopIdx,
  input  [7:0] io_enq_0_req_bits_uop_pdest,
  input  io_enq_0_req_bits_uop_robIdx_flag,
  input  [7:0] io_enq_0_req_bits_uop_robIdx_value,
  input  [63:0] io_enq_0_req_bits_uop_debugInfo_enqRsTime,
  input  [63:0] io_enq_0_req_bits_uop_debugInfo_selectTime,
  input  [63:0] io_enq_0_req_bits_uop_debugInfo_issueTime,
  input  io_enq_0_req_bits_uop_storeSetHit,
  input  io_enq_0_req_bits_uop_waitForRobIdx_flag,
  input  [7:0] io_enq_0_req_bits_uop_waitForRobIdx_value,
  input  io_enq_0_req_bits_uop_loadWaitBit,
  input  io_enq_0_req_bits_uop_loadWaitStrict,
  input  io_enq_0_req_bits_uop_lqIdx_flag,
  input  [6:0] io_enq_0_req_bits_uop_lqIdx_value,
  input  io_enq_0_req_bits_uop_sqIdx_flag,
  input  [5:0] io_enq_0_req_bits_uop_sqIdx_value,
  input  [49:0] io_enq_0_req_bits_vaddr,
  input  [63:0] io_enq_0_req_bits_fullva,
  input  io_enq_0_req_bits_vaNeedExt,
  input  [63:0] io_enq_0_req_bits_gpaddr,
  input  [15:0] io_enq_0_req_bits_mask,
  input  io_enq_0_req_bits_isvec,
  input  [7:0] io_enq_0_req_bits_elemIdx,
  input  [2:0] io_enq_0_req_bits_alignedType,
  input  [3:0] io_enq_0_req_bits_mbIndex,
  input  [7:0] io_enq_0_req_bits_elemIdxInsideVd,
  input  [15:0] io_enq_0_req_bits_vecTriggerMask,
  output io_enq_1_req_ready,
  input  io_enq_1_req_valid,
  input  io_enq_1_req_bits_uop_exceptionVec_0,
  input  io_enq_1_req_bits_uop_exceptionVec_1,
  input  io_enq_1_req_bits_uop_exceptionVec_2,
  input  io_enq_1_req_bits_uop_exceptionVec_3,
  input  io_enq_1_req_bits_uop_exceptionVec_5,
  input  io_enq_1_req_bits_uop_exceptionVec_6,
  input  io_enq_1_req_bits_uop_exceptionVec_7,
  input  io_enq_1_req_bits_uop_exceptionVec_8,
  input  io_enq_1_req_bits_uop_exceptionVec_9,
  input  io_enq_1_req_bits_uop_exceptionVec_10,
  input  io_enq_1_req_bits_uop_exceptionVec_11,
  input  io_enq_1_req_bits_uop_exceptionVec_12,
  input  io_enq_1_req_bits_uop_exceptionVec_13,
  input  io_enq_1_req_bits_uop_exceptionVec_14,
  input  io_enq_1_req_bits_uop_exceptionVec_15,
  input  io_enq_1_req_bits_uop_exceptionVec_16,
  input  io_enq_1_req_bits_uop_exceptionVec_17,
  input  io_enq_1_req_bits_uop_exceptionVec_18,
  input  io_enq_1_req_bits_uop_exceptionVec_19,
  input  io_enq_1_req_bits_uop_exceptionVec_20,
  input  io_enq_1_req_bits_uop_exceptionVec_21,
  input  io_enq_1_req_bits_uop_exceptionVec_22,
  input  io_enq_1_req_bits_uop_exceptionVec_23,
  input  [3:0] io_enq_1_req_bits_uop_trigger,
  input  io_enq_1_req_bits_uop_preDecodeInfo_isRVC,
  input  io_enq_1_req_bits_uop_ftqPtr_flag,
  input  [5:0] io_enq_1_req_bits_uop_ftqPtr_value,
  input  [3:0] io_enq_1_req_bits_uop_ftqOffset,
  input  [8:0] io_enq_1_req_bits_uop_fuOpType,
  input  io_enq_1_req_bits_uop_rfWen,
  input  io_enq_1_req_bits_uop_fpWen,
  input  [7:0] io_enq_1_req_bits_uop_vpu_vstart,
  input  [1:0] io_enq_1_req_bits_uop_vpu_veew,
  input  [6:0] io_enq_1_req_bits_uop_uopIdx,
  input  [7:0] io_enq_1_req_bits_uop_pdest,
  input  io_enq_1_req_bits_uop_robIdx_flag,
  input  [7:0] io_enq_1_req_bits_uop_robIdx_value,
  input  [63:0] io_enq_1_req_bits_uop_debugInfo_enqRsTime,
  input  [63:0] io_enq_1_req_bits_uop_debugInfo_selectTime,
  input  [63:0] io_enq_1_req_bits_uop_debugInfo_issueTime,
  input  io_enq_1_req_bits_uop_storeSetHit,
  input  io_enq_1_req_bits_uop_waitForRobIdx_flag,
  input  [7:0] io_enq_1_req_bits_uop_waitForRobIdx_value,
  input  io_enq_1_req_bits_uop_loadWaitBit,
  input  io_enq_1_req_bits_uop_loadWaitStrict,
  input  io_enq_1_req_bits_uop_lqIdx_flag,
  input  [6:0] io_enq_1_req_bits_uop_lqIdx_value,
  input  io_enq_1_req_bits_uop_sqIdx_flag,
  input  [5:0] io_enq_1_req_bits_uop_sqIdx_value,
  input  [49:0] io_enq_1_req_bits_vaddr,
  input  [63:0] io_enq_1_req_bits_fullva,
  input  io_enq_1_req_bits_vaNeedExt,
  input  [63:0] io_enq_1_req_bits_gpaddr,
  input  [15:0] io_enq_1_req_bits_mask,
  input  io_enq_1_req_bits_isvec,
  input  [7:0] io_enq_1_req_bits_elemIdx,
  input  [2:0] io_enq_1_req_bits_alignedType,
  input  [3:0] io_enq_1_req_bits_mbIndex,
  input  [7:0] io_enq_1_req_bits_elemIdxInsideVd,
  input  [15:0] io_enq_1_req_bits_vecTriggerMask,
  output io_enq_2_req_ready,
  input  io_enq_2_req_valid,
  input  io_enq_2_req_bits_uop_exceptionVec_0,
  input  io_enq_2_req_bits_uop_exceptionVec_1,
  input  io_enq_2_req_bits_uop_exceptionVec_2,
  input  io_enq_2_req_bits_uop_exceptionVec_3,
  input  io_enq_2_req_bits_uop_exceptionVec_5,
  input  io_enq_2_req_bits_uop_exceptionVec_6,
  input  io_enq_2_req_bits_uop_exceptionVec_7,
  input  io_enq_2_req_bits_uop_exceptionVec_8,
  input  io_enq_2_req_bits_uop_exceptionVec_9,
  input  io_enq_2_req_bits_uop_exceptionVec_10,
  input  io_enq_2_req_bits_uop_exceptionVec_11,
  input  io_enq_2_req_bits_uop_exceptionVec_12,
  input  io_enq_2_req_bits_uop_exceptionVec_13,
  input  io_enq_2_req_bits_uop_exceptionVec_14,
  input  io_enq_2_req_bits_uop_exceptionVec_15,
  input  io_enq_2_req_bits_uop_exceptionVec_16,
  input  io_enq_2_req_bits_uop_exceptionVec_17,
  input  io_enq_2_req_bits_uop_exceptionVec_18,
  input  io_enq_2_req_bits_uop_exceptionVec_19,
  input  io_enq_2_req_bits_uop_exceptionVec_20,
  input  io_enq_2_req_bits_uop_exceptionVec_21,
  input  io_enq_2_req_bits_uop_exceptionVec_22,
  input  io_enq_2_req_bits_uop_exceptionVec_23,
  input  [3:0] io_enq_2_req_bits_uop_trigger,
  input  io_enq_2_req_bits_uop_preDecodeInfo_isRVC,
  input  io_enq_2_req_bits_uop_ftqPtr_flag,
  input  [5:0] io_enq_2_req_bits_uop_ftqPtr_value,
  input  [3:0] io_enq_2_req_bits_uop_ftqOffset,
  input  [8:0] io_enq_2_req_bits_uop_fuOpType,
  input  io_enq_2_req_bits_uop_rfWen,
  input  io_enq_2_req_bits_uop_fpWen,
  input  [7:0] io_enq_2_req_bits_uop_vpu_vstart,
  input  [1:0] io_enq_2_req_bits_uop_vpu_veew,
  input  [6:0] io_enq_2_req_bits_uop_uopIdx,
  input  [7:0] io_enq_2_req_bits_uop_pdest,
  input  io_enq_2_req_bits_uop_robIdx_flag,
  input  [7:0] io_enq_2_req_bits_uop_robIdx_value,
  input  [63:0] io_enq_2_req_bits_uop_debugInfo_enqRsTime,
  input  [63:0] io_enq_2_req_bits_uop_debugInfo_selectTime,
  input  [63:0] io_enq_2_req_bits_uop_debugInfo_issueTime,
  input  io_enq_2_req_bits_uop_storeSetHit,
  input  io_enq_2_req_bits_uop_waitForRobIdx_flag,
  input  [7:0] io_enq_2_req_bits_uop_waitForRobIdx_value,
  input  io_enq_2_req_bits_uop_loadWaitBit,
  input  io_enq_2_req_bits_uop_loadWaitStrict,
  input  io_enq_2_req_bits_uop_lqIdx_flag,
  input  [6:0] io_enq_2_req_bits_uop_lqIdx_value,
  input  io_enq_2_req_bits_uop_sqIdx_flag,
  input  [5:0] io_enq_2_req_bits_uop_sqIdx_value,
  input  [49:0] io_enq_2_req_bits_vaddr,
  input  [63:0] io_enq_2_req_bits_fullva,
  input  io_enq_2_req_bits_vaNeedExt,
  input  [63:0] io_enq_2_req_bits_gpaddr,
  input  [15:0] io_enq_2_req_bits_mask,
  input  io_enq_2_req_bits_isvec,
  input  [7:0] io_enq_2_req_bits_elemIdx,
  input  [2:0] io_enq_2_req_bits_alignedType,
  input  [3:0] io_enq_2_req_bits_mbIndex,
  input  [7:0] io_enq_2_req_bits_elemIdxInsideVd,
  input  [15:0] io_enq_2_req_bits_vecTriggerMask,
  input  io_splitLoadReq_ready,
  output io_splitLoadReq_valid,
  output io_splitLoadReq_bits_uop_exceptionVec_0,
  output io_splitLoadReq_bits_uop_exceptionVec_1,
  output io_splitLoadReq_bits_uop_exceptionVec_2,
  output io_splitLoadReq_bits_uop_exceptionVec_3,
  output io_splitLoadReq_bits_uop_exceptionVec_4,
  output io_splitLoadReq_bits_uop_exceptionVec_5,
  output io_splitLoadReq_bits_uop_exceptionVec_6,
  output io_splitLoadReq_bits_uop_exceptionVec_7,
  output io_splitLoadReq_bits_uop_exceptionVec_8,
  output io_splitLoadReq_bits_uop_exceptionVec_9,
  output io_splitLoadReq_bits_uop_exceptionVec_10,
  output io_splitLoadReq_bits_uop_exceptionVec_11,
  output io_splitLoadReq_bits_uop_exceptionVec_12,
  output io_splitLoadReq_bits_uop_exceptionVec_13,
  output io_splitLoadReq_bits_uop_exceptionVec_14,
  output io_splitLoadReq_bits_uop_exceptionVec_15,
  output io_splitLoadReq_bits_uop_exceptionVec_16,
  output io_splitLoadReq_bits_uop_exceptionVec_17,
  output io_splitLoadReq_bits_uop_exceptionVec_18,
  output io_splitLoadReq_bits_uop_exceptionVec_19,
  output io_splitLoadReq_bits_uop_exceptionVec_20,
  output io_splitLoadReq_bits_uop_exceptionVec_21,
  output io_splitLoadReq_bits_uop_exceptionVec_22,
  output io_splitLoadReq_bits_uop_exceptionVec_23,
  output [3:0] io_splitLoadReq_bits_uop_trigger,
  output io_splitLoadReq_bits_uop_preDecodeInfo_isRVC,
  output io_splitLoadReq_bits_uop_ftqPtr_flag,
  output [5:0] io_splitLoadReq_bits_uop_ftqPtr_value,
  output [3:0] io_splitLoadReq_bits_uop_ftqOffset,
  output [8:0] io_splitLoadReq_bits_uop_fuOpType,
  output io_splitLoadReq_bits_uop_rfWen,
  output io_splitLoadReq_bits_uop_fpWen,
  output [7:0] io_splitLoadReq_bits_uop_vpu_vstart,
  output [1:0] io_splitLoadReq_bits_uop_vpu_veew,
  output [6:0] io_splitLoadReq_bits_uop_uopIdx,
  output [7:0] io_splitLoadReq_bits_uop_pdest,
  output io_splitLoadReq_bits_uop_robIdx_flag,
  output [7:0] io_splitLoadReq_bits_uop_robIdx_value,
  output [63:0] io_splitLoadReq_bits_uop_debugInfo_enqRsTime,
  output [63:0] io_splitLoadReq_bits_uop_debugInfo_selectTime,
  output [63:0] io_splitLoadReq_bits_uop_debugInfo_issueTime,
  output io_splitLoadReq_bits_uop_storeSetHit,
  output io_splitLoadReq_bits_uop_waitForRobIdx_flag,
  output [7:0] io_splitLoadReq_bits_uop_waitForRobIdx_value,
  output io_splitLoadReq_bits_uop_loadWaitBit,
  output io_splitLoadReq_bits_uop_loadWaitStrict,
  output io_splitLoadReq_bits_uop_lqIdx_flag,
  output [6:0] io_splitLoadReq_bits_uop_lqIdx_value,
  output io_splitLoadReq_bits_uop_sqIdx_flag,
  output [5:0] io_splitLoadReq_bits_uop_sqIdx_value,
  output [49:0] io_splitLoadReq_bits_vaddr,
  output [63:0] io_splitLoadReq_bits_fullva,
  output [15:0] io_splitLoadReq_bits_mask,
  output io_splitLoadReq_bits_nc,
  output io_splitLoadReq_bits_mmio,
  output io_splitLoadReq_bits_memBackTypeMM,
  output io_splitLoadReq_bits_isvec,
  output io_splitLoadReq_bits_is128bit,
  output io_splitLoadReq_bits_vecActive,
  output [3:0] io_splitLoadReq_bits_mshrid,
  output [6:0] io_splitLoadReq_bits_schedIndex,
  output io_splitLoadReq_bits_isFinalSplit,
  output io_splitLoadReq_bits_misalignNeedWakeUp,
  input  io_splitLoadResp_valid,
  input  io_splitLoadResp_bits_uop_exceptionVec_3,
  input  io_splitLoadResp_bits_uop_exceptionVec_4,
  input  io_splitLoadResp_bits_uop_exceptionVec_5,
  input  io_splitLoadResp_bits_uop_exceptionVec_13,
  input  io_splitLoadResp_bits_uop_exceptionVec_19,
  input  io_splitLoadResp_bits_uop_exceptionVec_21,
  input  [3:0] io_splitLoadResp_bits_uop_trigger,
  input  [128:0] io_splitLoadResp_bits_data,
  input  io_splitLoadResp_bits_nc,
  input  io_splitLoadResp_bits_mmio,
  input  io_splitLoadResp_bits_memBackTypeMM,
  input  io_splitLoadResp_bits_vecActive,
  input  io_splitLoadResp_bits_misalignNeedWakeUp,
  input  io_splitLoadResp_bits_rep_info_cause_0,
  input  io_splitLoadResp_bits_rep_info_cause_1,
  input  io_splitLoadResp_bits_rep_info_cause_2,
  input  io_splitLoadResp_bits_rep_info_cause_3,
  input  io_splitLoadResp_bits_rep_info_cause_4,
  input  io_splitLoadResp_bits_rep_info_cause_5,
  input  io_splitLoadResp_bits_rep_info_cause_6,
  input  io_splitLoadResp_bits_rep_info_cause_7,
  input  io_splitLoadResp_bits_rep_info_cause_8,
  input  io_splitLoadResp_bits_rep_info_cause_9,
  input  io_splitLoadResp_bits_rep_info_cause_10,
  input  io_writeBack_ready,
  output io_writeBack_valid,
  output io_writeBack_bits_uop_exceptionVec_3,
  output io_writeBack_bits_uop_exceptionVec_4,
  output io_writeBack_bits_uop_exceptionVec_5,
  output io_writeBack_bits_uop_exceptionVec_13,
  output io_writeBack_bits_uop_exceptionVec_19,
  output io_writeBack_bits_uop_exceptionVec_21,
  output [3:0] io_writeBack_bits_uop_trigger,
  output io_writeBack_bits_uop_rfWen,
  output io_writeBack_bits_uop_fpWen,
  output [7:0] io_writeBack_bits_uop_pdest,
  output io_writeBack_bits_uop_robIdx_flag,
  output [7:0] io_writeBack_bits_uop_robIdx_value,
  output [63:0] io_writeBack_bits_uop_debugInfo_enqRsTime,
  output [63:0] io_writeBack_bits_uop_debugInfo_selectTime,
  output [63:0] io_writeBack_bits_uop_debugInfo_issueTime,
  output [63:0] io_writeBack_bits_data,
  output io_writeBack_bits_debug_isMMIO,
  output io_writeBack_bits_debug_isNCIO,
  output io_vecWriteBack_valid,
  output [3:0] io_vecWriteBack_bits_mBIndex,
  output io_vecWriteBack_bits_exceptionVec_3,
  output io_vecWriteBack_bits_exceptionVec_4,
  output io_vecWriteBack_bits_exceptionVec_5,
  output io_vecWriteBack_bits_exceptionVec_13,
  output io_vecWriteBack_bits_exceptionVec_19,
  output io_vecWriteBack_bits_exceptionVec_21,
  output io_vecWriteBack_bits_hasException,
  output [63:0] io_vecWriteBack_bits_vaddr,
  output io_vecWriteBack_bits_vaNeedExt,
  output [63:0] io_vecWriteBack_bits_gpaddr,
  output [7:0] io_vecWriteBack_bits_vstart,
  output [15:0] io_vecWriteBack_bits_vecTriggerMask,
  output [7:0] io_vecWriteBack_bits_elemIdx,
  output [15:0] io_vecWriteBack_bits_mask,
  output [2:0] io_vecWriteBack_bits_alignedType,
  output [7:0] io_vecWriteBack_bits_elemIdxInsideVd,
  output [127:0] io_vecWriteBack_bits_vecdata,
  input  io_loadOutValid,
  input  io_loadVecOutValid,
  output io_loadMisalignFull
);
  xs_LoadMisalignBuffer_core u_core (
    .clock(clock),
    .reset(reset),
    .io_redirect_valid(io_redirect_valid),
    .io_redirect_bits_robIdx_flag(io_redirect_bits_robIdx_flag),
    .io_redirect_bits_robIdx_value(io_redirect_bits_robIdx_value),
    .io_redirect_bits_level(io_redirect_bits_level),
    .io_enq_0_req_ready(io_enq_0_req_ready),
    .io_enq_0_req_valid(io_enq_0_req_valid),
    .io_enq_0_req_bits_uop_exceptionVec_0(io_enq_0_req_bits_uop_exceptionVec_0),
    .io_enq_0_req_bits_uop_exceptionVec_1(io_enq_0_req_bits_uop_exceptionVec_1),
    .io_enq_0_req_bits_uop_exceptionVec_2(io_enq_0_req_bits_uop_exceptionVec_2),
    .io_enq_0_req_bits_uop_exceptionVec_3(io_enq_0_req_bits_uop_exceptionVec_3),
    .io_enq_0_req_bits_uop_exceptionVec_5(io_enq_0_req_bits_uop_exceptionVec_5),
    .io_enq_0_req_bits_uop_exceptionVec_6(io_enq_0_req_bits_uop_exceptionVec_6),
    .io_enq_0_req_bits_uop_exceptionVec_7(io_enq_0_req_bits_uop_exceptionVec_7),
    .io_enq_0_req_bits_uop_exceptionVec_8(io_enq_0_req_bits_uop_exceptionVec_8),
    .io_enq_0_req_bits_uop_exceptionVec_9(io_enq_0_req_bits_uop_exceptionVec_9),
    .io_enq_0_req_bits_uop_exceptionVec_10(io_enq_0_req_bits_uop_exceptionVec_10),
    .io_enq_0_req_bits_uop_exceptionVec_11(io_enq_0_req_bits_uop_exceptionVec_11),
    .io_enq_0_req_bits_uop_exceptionVec_12(io_enq_0_req_bits_uop_exceptionVec_12),
    .io_enq_0_req_bits_uop_exceptionVec_13(io_enq_0_req_bits_uop_exceptionVec_13),
    .io_enq_0_req_bits_uop_exceptionVec_14(io_enq_0_req_bits_uop_exceptionVec_14),
    .io_enq_0_req_bits_uop_exceptionVec_15(io_enq_0_req_bits_uop_exceptionVec_15),
    .io_enq_0_req_bits_uop_exceptionVec_16(io_enq_0_req_bits_uop_exceptionVec_16),
    .io_enq_0_req_bits_uop_exceptionVec_17(io_enq_0_req_bits_uop_exceptionVec_17),
    .io_enq_0_req_bits_uop_exceptionVec_18(io_enq_0_req_bits_uop_exceptionVec_18),
    .io_enq_0_req_bits_uop_exceptionVec_19(io_enq_0_req_bits_uop_exceptionVec_19),
    .io_enq_0_req_bits_uop_exceptionVec_20(io_enq_0_req_bits_uop_exceptionVec_20),
    .io_enq_0_req_bits_uop_exceptionVec_21(io_enq_0_req_bits_uop_exceptionVec_21),
    .io_enq_0_req_bits_uop_exceptionVec_22(io_enq_0_req_bits_uop_exceptionVec_22),
    .io_enq_0_req_bits_uop_exceptionVec_23(io_enq_0_req_bits_uop_exceptionVec_23),
    .io_enq_0_req_bits_uop_trigger(io_enq_0_req_bits_uop_trigger),
    .io_enq_0_req_bits_uop_preDecodeInfo_isRVC(io_enq_0_req_bits_uop_preDecodeInfo_isRVC),
    .io_enq_0_req_bits_uop_ftqPtr_flag(io_enq_0_req_bits_uop_ftqPtr_flag),
    .io_enq_0_req_bits_uop_ftqPtr_value(io_enq_0_req_bits_uop_ftqPtr_value),
    .io_enq_0_req_bits_uop_ftqOffset(io_enq_0_req_bits_uop_ftqOffset),
    .io_enq_0_req_bits_uop_fuOpType(io_enq_0_req_bits_uop_fuOpType),
    .io_enq_0_req_bits_uop_rfWen(io_enq_0_req_bits_uop_rfWen),
    .io_enq_0_req_bits_uop_fpWen(io_enq_0_req_bits_uop_fpWen),
    .io_enq_0_req_bits_uop_vpu_vstart(io_enq_0_req_bits_uop_vpu_vstart),
    .io_enq_0_req_bits_uop_vpu_veew(io_enq_0_req_bits_uop_vpu_veew),
    .io_enq_0_req_bits_uop_uopIdx(io_enq_0_req_bits_uop_uopIdx),
    .io_enq_0_req_bits_uop_pdest(io_enq_0_req_bits_uop_pdest),
    .io_enq_0_req_bits_uop_robIdx_flag(io_enq_0_req_bits_uop_robIdx_flag),
    .io_enq_0_req_bits_uop_robIdx_value(io_enq_0_req_bits_uop_robIdx_value),
    .io_enq_0_req_bits_uop_debugInfo_enqRsTime(io_enq_0_req_bits_uop_debugInfo_enqRsTime),
    .io_enq_0_req_bits_uop_debugInfo_selectTime(io_enq_0_req_bits_uop_debugInfo_selectTime),
    .io_enq_0_req_bits_uop_debugInfo_issueTime(io_enq_0_req_bits_uop_debugInfo_issueTime),
    .io_enq_0_req_bits_uop_storeSetHit(io_enq_0_req_bits_uop_storeSetHit),
    .io_enq_0_req_bits_uop_waitForRobIdx_flag(io_enq_0_req_bits_uop_waitForRobIdx_flag),
    .io_enq_0_req_bits_uop_waitForRobIdx_value(io_enq_0_req_bits_uop_waitForRobIdx_value),
    .io_enq_0_req_bits_uop_loadWaitBit(io_enq_0_req_bits_uop_loadWaitBit),
    .io_enq_0_req_bits_uop_loadWaitStrict(io_enq_0_req_bits_uop_loadWaitStrict),
    .io_enq_0_req_bits_uop_lqIdx_flag(io_enq_0_req_bits_uop_lqIdx_flag),
    .io_enq_0_req_bits_uop_lqIdx_value(io_enq_0_req_bits_uop_lqIdx_value),
    .io_enq_0_req_bits_uop_sqIdx_flag(io_enq_0_req_bits_uop_sqIdx_flag),
    .io_enq_0_req_bits_uop_sqIdx_value(io_enq_0_req_bits_uop_sqIdx_value),
    .io_enq_0_req_bits_vaddr(io_enq_0_req_bits_vaddr),
    .io_enq_0_req_bits_fullva(io_enq_0_req_bits_fullva),
    .io_enq_0_req_bits_vaNeedExt(io_enq_0_req_bits_vaNeedExt),
    .io_enq_0_req_bits_gpaddr(io_enq_0_req_bits_gpaddr),
    .io_enq_0_req_bits_mask(io_enq_0_req_bits_mask),
    .io_enq_0_req_bits_isvec(io_enq_0_req_bits_isvec),
    .io_enq_0_req_bits_elemIdx(io_enq_0_req_bits_elemIdx),
    .io_enq_0_req_bits_alignedType(io_enq_0_req_bits_alignedType),
    .io_enq_0_req_bits_mbIndex(io_enq_0_req_bits_mbIndex),
    .io_enq_0_req_bits_elemIdxInsideVd(io_enq_0_req_bits_elemIdxInsideVd),
    .io_enq_0_req_bits_vecTriggerMask(io_enq_0_req_bits_vecTriggerMask),
    .io_enq_1_req_ready(io_enq_1_req_ready),
    .io_enq_1_req_valid(io_enq_1_req_valid),
    .io_enq_1_req_bits_uop_exceptionVec_0(io_enq_1_req_bits_uop_exceptionVec_0),
    .io_enq_1_req_bits_uop_exceptionVec_1(io_enq_1_req_bits_uop_exceptionVec_1),
    .io_enq_1_req_bits_uop_exceptionVec_2(io_enq_1_req_bits_uop_exceptionVec_2),
    .io_enq_1_req_bits_uop_exceptionVec_3(io_enq_1_req_bits_uop_exceptionVec_3),
    .io_enq_1_req_bits_uop_exceptionVec_5(io_enq_1_req_bits_uop_exceptionVec_5),
    .io_enq_1_req_bits_uop_exceptionVec_6(io_enq_1_req_bits_uop_exceptionVec_6),
    .io_enq_1_req_bits_uop_exceptionVec_7(io_enq_1_req_bits_uop_exceptionVec_7),
    .io_enq_1_req_bits_uop_exceptionVec_8(io_enq_1_req_bits_uop_exceptionVec_8),
    .io_enq_1_req_bits_uop_exceptionVec_9(io_enq_1_req_bits_uop_exceptionVec_9),
    .io_enq_1_req_bits_uop_exceptionVec_10(io_enq_1_req_bits_uop_exceptionVec_10),
    .io_enq_1_req_bits_uop_exceptionVec_11(io_enq_1_req_bits_uop_exceptionVec_11),
    .io_enq_1_req_bits_uop_exceptionVec_12(io_enq_1_req_bits_uop_exceptionVec_12),
    .io_enq_1_req_bits_uop_exceptionVec_13(io_enq_1_req_bits_uop_exceptionVec_13),
    .io_enq_1_req_bits_uop_exceptionVec_14(io_enq_1_req_bits_uop_exceptionVec_14),
    .io_enq_1_req_bits_uop_exceptionVec_15(io_enq_1_req_bits_uop_exceptionVec_15),
    .io_enq_1_req_bits_uop_exceptionVec_16(io_enq_1_req_bits_uop_exceptionVec_16),
    .io_enq_1_req_bits_uop_exceptionVec_17(io_enq_1_req_bits_uop_exceptionVec_17),
    .io_enq_1_req_bits_uop_exceptionVec_18(io_enq_1_req_bits_uop_exceptionVec_18),
    .io_enq_1_req_bits_uop_exceptionVec_19(io_enq_1_req_bits_uop_exceptionVec_19),
    .io_enq_1_req_bits_uop_exceptionVec_20(io_enq_1_req_bits_uop_exceptionVec_20),
    .io_enq_1_req_bits_uop_exceptionVec_21(io_enq_1_req_bits_uop_exceptionVec_21),
    .io_enq_1_req_bits_uop_exceptionVec_22(io_enq_1_req_bits_uop_exceptionVec_22),
    .io_enq_1_req_bits_uop_exceptionVec_23(io_enq_1_req_bits_uop_exceptionVec_23),
    .io_enq_1_req_bits_uop_trigger(io_enq_1_req_bits_uop_trigger),
    .io_enq_1_req_bits_uop_preDecodeInfo_isRVC(io_enq_1_req_bits_uop_preDecodeInfo_isRVC),
    .io_enq_1_req_bits_uop_ftqPtr_flag(io_enq_1_req_bits_uop_ftqPtr_flag),
    .io_enq_1_req_bits_uop_ftqPtr_value(io_enq_1_req_bits_uop_ftqPtr_value),
    .io_enq_1_req_bits_uop_ftqOffset(io_enq_1_req_bits_uop_ftqOffset),
    .io_enq_1_req_bits_uop_fuOpType(io_enq_1_req_bits_uop_fuOpType),
    .io_enq_1_req_bits_uop_rfWen(io_enq_1_req_bits_uop_rfWen),
    .io_enq_1_req_bits_uop_fpWen(io_enq_1_req_bits_uop_fpWen),
    .io_enq_1_req_bits_uop_vpu_vstart(io_enq_1_req_bits_uop_vpu_vstart),
    .io_enq_1_req_bits_uop_vpu_veew(io_enq_1_req_bits_uop_vpu_veew),
    .io_enq_1_req_bits_uop_uopIdx(io_enq_1_req_bits_uop_uopIdx),
    .io_enq_1_req_bits_uop_pdest(io_enq_1_req_bits_uop_pdest),
    .io_enq_1_req_bits_uop_robIdx_flag(io_enq_1_req_bits_uop_robIdx_flag),
    .io_enq_1_req_bits_uop_robIdx_value(io_enq_1_req_bits_uop_robIdx_value),
    .io_enq_1_req_bits_uop_debugInfo_enqRsTime(io_enq_1_req_bits_uop_debugInfo_enqRsTime),
    .io_enq_1_req_bits_uop_debugInfo_selectTime(io_enq_1_req_bits_uop_debugInfo_selectTime),
    .io_enq_1_req_bits_uop_debugInfo_issueTime(io_enq_1_req_bits_uop_debugInfo_issueTime),
    .io_enq_1_req_bits_uop_storeSetHit(io_enq_1_req_bits_uop_storeSetHit),
    .io_enq_1_req_bits_uop_waitForRobIdx_flag(io_enq_1_req_bits_uop_waitForRobIdx_flag),
    .io_enq_1_req_bits_uop_waitForRobIdx_value(io_enq_1_req_bits_uop_waitForRobIdx_value),
    .io_enq_1_req_bits_uop_loadWaitBit(io_enq_1_req_bits_uop_loadWaitBit),
    .io_enq_1_req_bits_uop_loadWaitStrict(io_enq_1_req_bits_uop_loadWaitStrict),
    .io_enq_1_req_bits_uop_lqIdx_flag(io_enq_1_req_bits_uop_lqIdx_flag),
    .io_enq_1_req_bits_uop_lqIdx_value(io_enq_1_req_bits_uop_lqIdx_value),
    .io_enq_1_req_bits_uop_sqIdx_flag(io_enq_1_req_bits_uop_sqIdx_flag),
    .io_enq_1_req_bits_uop_sqIdx_value(io_enq_1_req_bits_uop_sqIdx_value),
    .io_enq_1_req_bits_vaddr(io_enq_1_req_bits_vaddr),
    .io_enq_1_req_bits_fullva(io_enq_1_req_bits_fullva),
    .io_enq_1_req_bits_vaNeedExt(io_enq_1_req_bits_vaNeedExt),
    .io_enq_1_req_bits_gpaddr(io_enq_1_req_bits_gpaddr),
    .io_enq_1_req_bits_mask(io_enq_1_req_bits_mask),
    .io_enq_1_req_bits_isvec(io_enq_1_req_bits_isvec),
    .io_enq_1_req_bits_elemIdx(io_enq_1_req_bits_elemIdx),
    .io_enq_1_req_bits_alignedType(io_enq_1_req_bits_alignedType),
    .io_enq_1_req_bits_mbIndex(io_enq_1_req_bits_mbIndex),
    .io_enq_1_req_bits_elemIdxInsideVd(io_enq_1_req_bits_elemIdxInsideVd),
    .io_enq_1_req_bits_vecTriggerMask(io_enq_1_req_bits_vecTriggerMask),
    .io_enq_2_req_ready(io_enq_2_req_ready),
    .io_enq_2_req_valid(io_enq_2_req_valid),
    .io_enq_2_req_bits_uop_exceptionVec_0(io_enq_2_req_bits_uop_exceptionVec_0),
    .io_enq_2_req_bits_uop_exceptionVec_1(io_enq_2_req_bits_uop_exceptionVec_1),
    .io_enq_2_req_bits_uop_exceptionVec_2(io_enq_2_req_bits_uop_exceptionVec_2),
    .io_enq_2_req_bits_uop_exceptionVec_3(io_enq_2_req_bits_uop_exceptionVec_3),
    .io_enq_2_req_bits_uop_exceptionVec_5(io_enq_2_req_bits_uop_exceptionVec_5),
    .io_enq_2_req_bits_uop_exceptionVec_6(io_enq_2_req_bits_uop_exceptionVec_6),
    .io_enq_2_req_bits_uop_exceptionVec_7(io_enq_2_req_bits_uop_exceptionVec_7),
    .io_enq_2_req_bits_uop_exceptionVec_8(io_enq_2_req_bits_uop_exceptionVec_8),
    .io_enq_2_req_bits_uop_exceptionVec_9(io_enq_2_req_bits_uop_exceptionVec_9),
    .io_enq_2_req_bits_uop_exceptionVec_10(io_enq_2_req_bits_uop_exceptionVec_10),
    .io_enq_2_req_bits_uop_exceptionVec_11(io_enq_2_req_bits_uop_exceptionVec_11),
    .io_enq_2_req_bits_uop_exceptionVec_12(io_enq_2_req_bits_uop_exceptionVec_12),
    .io_enq_2_req_bits_uop_exceptionVec_13(io_enq_2_req_bits_uop_exceptionVec_13),
    .io_enq_2_req_bits_uop_exceptionVec_14(io_enq_2_req_bits_uop_exceptionVec_14),
    .io_enq_2_req_bits_uop_exceptionVec_15(io_enq_2_req_bits_uop_exceptionVec_15),
    .io_enq_2_req_bits_uop_exceptionVec_16(io_enq_2_req_bits_uop_exceptionVec_16),
    .io_enq_2_req_bits_uop_exceptionVec_17(io_enq_2_req_bits_uop_exceptionVec_17),
    .io_enq_2_req_bits_uop_exceptionVec_18(io_enq_2_req_bits_uop_exceptionVec_18),
    .io_enq_2_req_bits_uop_exceptionVec_19(io_enq_2_req_bits_uop_exceptionVec_19),
    .io_enq_2_req_bits_uop_exceptionVec_20(io_enq_2_req_bits_uop_exceptionVec_20),
    .io_enq_2_req_bits_uop_exceptionVec_21(io_enq_2_req_bits_uop_exceptionVec_21),
    .io_enq_2_req_bits_uop_exceptionVec_22(io_enq_2_req_bits_uop_exceptionVec_22),
    .io_enq_2_req_bits_uop_exceptionVec_23(io_enq_2_req_bits_uop_exceptionVec_23),
    .io_enq_2_req_bits_uop_trigger(io_enq_2_req_bits_uop_trigger),
    .io_enq_2_req_bits_uop_preDecodeInfo_isRVC(io_enq_2_req_bits_uop_preDecodeInfo_isRVC),
    .io_enq_2_req_bits_uop_ftqPtr_flag(io_enq_2_req_bits_uop_ftqPtr_flag),
    .io_enq_2_req_bits_uop_ftqPtr_value(io_enq_2_req_bits_uop_ftqPtr_value),
    .io_enq_2_req_bits_uop_ftqOffset(io_enq_2_req_bits_uop_ftqOffset),
    .io_enq_2_req_bits_uop_fuOpType(io_enq_2_req_bits_uop_fuOpType),
    .io_enq_2_req_bits_uop_rfWen(io_enq_2_req_bits_uop_rfWen),
    .io_enq_2_req_bits_uop_fpWen(io_enq_2_req_bits_uop_fpWen),
    .io_enq_2_req_bits_uop_vpu_vstart(io_enq_2_req_bits_uop_vpu_vstart),
    .io_enq_2_req_bits_uop_vpu_veew(io_enq_2_req_bits_uop_vpu_veew),
    .io_enq_2_req_bits_uop_uopIdx(io_enq_2_req_bits_uop_uopIdx),
    .io_enq_2_req_bits_uop_pdest(io_enq_2_req_bits_uop_pdest),
    .io_enq_2_req_bits_uop_robIdx_flag(io_enq_2_req_bits_uop_robIdx_flag),
    .io_enq_2_req_bits_uop_robIdx_value(io_enq_2_req_bits_uop_robIdx_value),
    .io_enq_2_req_bits_uop_debugInfo_enqRsTime(io_enq_2_req_bits_uop_debugInfo_enqRsTime),
    .io_enq_2_req_bits_uop_debugInfo_selectTime(io_enq_2_req_bits_uop_debugInfo_selectTime),
    .io_enq_2_req_bits_uop_debugInfo_issueTime(io_enq_2_req_bits_uop_debugInfo_issueTime),
    .io_enq_2_req_bits_uop_storeSetHit(io_enq_2_req_bits_uop_storeSetHit),
    .io_enq_2_req_bits_uop_waitForRobIdx_flag(io_enq_2_req_bits_uop_waitForRobIdx_flag),
    .io_enq_2_req_bits_uop_waitForRobIdx_value(io_enq_2_req_bits_uop_waitForRobIdx_value),
    .io_enq_2_req_bits_uop_loadWaitBit(io_enq_2_req_bits_uop_loadWaitBit),
    .io_enq_2_req_bits_uop_loadWaitStrict(io_enq_2_req_bits_uop_loadWaitStrict),
    .io_enq_2_req_bits_uop_lqIdx_flag(io_enq_2_req_bits_uop_lqIdx_flag),
    .io_enq_2_req_bits_uop_lqIdx_value(io_enq_2_req_bits_uop_lqIdx_value),
    .io_enq_2_req_bits_uop_sqIdx_flag(io_enq_2_req_bits_uop_sqIdx_flag),
    .io_enq_2_req_bits_uop_sqIdx_value(io_enq_2_req_bits_uop_sqIdx_value),
    .io_enq_2_req_bits_vaddr(io_enq_2_req_bits_vaddr),
    .io_enq_2_req_bits_fullva(io_enq_2_req_bits_fullva),
    .io_enq_2_req_bits_vaNeedExt(io_enq_2_req_bits_vaNeedExt),
    .io_enq_2_req_bits_gpaddr(io_enq_2_req_bits_gpaddr),
    .io_enq_2_req_bits_mask(io_enq_2_req_bits_mask),
    .io_enq_2_req_bits_isvec(io_enq_2_req_bits_isvec),
    .io_enq_2_req_bits_elemIdx(io_enq_2_req_bits_elemIdx),
    .io_enq_2_req_bits_alignedType(io_enq_2_req_bits_alignedType),
    .io_enq_2_req_bits_mbIndex(io_enq_2_req_bits_mbIndex),
    .io_enq_2_req_bits_elemIdxInsideVd(io_enq_2_req_bits_elemIdxInsideVd),
    .io_enq_2_req_bits_vecTriggerMask(io_enq_2_req_bits_vecTriggerMask),
    .io_splitLoadReq_ready(io_splitLoadReq_ready),
    .io_splitLoadReq_valid(io_splitLoadReq_valid),
    .io_splitLoadReq_bits_uop_exceptionVec_0(io_splitLoadReq_bits_uop_exceptionVec_0),
    .io_splitLoadReq_bits_uop_exceptionVec_1(io_splitLoadReq_bits_uop_exceptionVec_1),
    .io_splitLoadReq_bits_uop_exceptionVec_2(io_splitLoadReq_bits_uop_exceptionVec_2),
    .io_splitLoadReq_bits_uop_exceptionVec_3(io_splitLoadReq_bits_uop_exceptionVec_3),
    .io_splitLoadReq_bits_uop_exceptionVec_4(io_splitLoadReq_bits_uop_exceptionVec_4),
    .io_splitLoadReq_bits_uop_exceptionVec_5(io_splitLoadReq_bits_uop_exceptionVec_5),
    .io_splitLoadReq_bits_uop_exceptionVec_6(io_splitLoadReq_bits_uop_exceptionVec_6),
    .io_splitLoadReq_bits_uop_exceptionVec_7(io_splitLoadReq_bits_uop_exceptionVec_7),
    .io_splitLoadReq_bits_uop_exceptionVec_8(io_splitLoadReq_bits_uop_exceptionVec_8),
    .io_splitLoadReq_bits_uop_exceptionVec_9(io_splitLoadReq_bits_uop_exceptionVec_9),
    .io_splitLoadReq_bits_uop_exceptionVec_10(io_splitLoadReq_bits_uop_exceptionVec_10),
    .io_splitLoadReq_bits_uop_exceptionVec_11(io_splitLoadReq_bits_uop_exceptionVec_11),
    .io_splitLoadReq_bits_uop_exceptionVec_12(io_splitLoadReq_bits_uop_exceptionVec_12),
    .io_splitLoadReq_bits_uop_exceptionVec_13(io_splitLoadReq_bits_uop_exceptionVec_13),
    .io_splitLoadReq_bits_uop_exceptionVec_14(io_splitLoadReq_bits_uop_exceptionVec_14),
    .io_splitLoadReq_bits_uop_exceptionVec_15(io_splitLoadReq_bits_uop_exceptionVec_15),
    .io_splitLoadReq_bits_uop_exceptionVec_16(io_splitLoadReq_bits_uop_exceptionVec_16),
    .io_splitLoadReq_bits_uop_exceptionVec_17(io_splitLoadReq_bits_uop_exceptionVec_17),
    .io_splitLoadReq_bits_uop_exceptionVec_18(io_splitLoadReq_bits_uop_exceptionVec_18),
    .io_splitLoadReq_bits_uop_exceptionVec_19(io_splitLoadReq_bits_uop_exceptionVec_19),
    .io_splitLoadReq_bits_uop_exceptionVec_20(io_splitLoadReq_bits_uop_exceptionVec_20),
    .io_splitLoadReq_bits_uop_exceptionVec_21(io_splitLoadReq_bits_uop_exceptionVec_21),
    .io_splitLoadReq_bits_uop_exceptionVec_22(io_splitLoadReq_bits_uop_exceptionVec_22),
    .io_splitLoadReq_bits_uop_exceptionVec_23(io_splitLoadReq_bits_uop_exceptionVec_23),
    .io_splitLoadReq_bits_uop_trigger(io_splitLoadReq_bits_uop_trigger),
    .io_splitLoadReq_bits_uop_preDecodeInfo_isRVC(io_splitLoadReq_bits_uop_preDecodeInfo_isRVC),
    .io_splitLoadReq_bits_uop_ftqPtr_flag(io_splitLoadReq_bits_uop_ftqPtr_flag),
    .io_splitLoadReq_bits_uop_ftqPtr_value(io_splitLoadReq_bits_uop_ftqPtr_value),
    .io_splitLoadReq_bits_uop_ftqOffset(io_splitLoadReq_bits_uop_ftqOffset),
    .io_splitLoadReq_bits_uop_fuOpType(io_splitLoadReq_bits_uop_fuOpType),
    .io_splitLoadReq_bits_uop_rfWen(io_splitLoadReq_bits_uop_rfWen),
    .io_splitLoadReq_bits_uop_fpWen(io_splitLoadReq_bits_uop_fpWen),
    .io_splitLoadReq_bits_uop_vpu_vstart(io_splitLoadReq_bits_uop_vpu_vstart),
    .io_splitLoadReq_bits_uop_vpu_veew(io_splitLoadReq_bits_uop_vpu_veew),
    .io_splitLoadReq_bits_uop_uopIdx(io_splitLoadReq_bits_uop_uopIdx),
    .io_splitLoadReq_bits_uop_pdest(io_splitLoadReq_bits_uop_pdest),
    .io_splitLoadReq_bits_uop_robIdx_flag(io_splitLoadReq_bits_uop_robIdx_flag),
    .io_splitLoadReq_bits_uop_robIdx_value(io_splitLoadReq_bits_uop_robIdx_value),
    .io_splitLoadReq_bits_uop_debugInfo_enqRsTime(io_splitLoadReq_bits_uop_debugInfo_enqRsTime),
    .io_splitLoadReq_bits_uop_debugInfo_selectTime(io_splitLoadReq_bits_uop_debugInfo_selectTime),
    .io_splitLoadReq_bits_uop_debugInfo_issueTime(io_splitLoadReq_bits_uop_debugInfo_issueTime),
    .io_splitLoadReq_bits_uop_storeSetHit(io_splitLoadReq_bits_uop_storeSetHit),
    .io_splitLoadReq_bits_uop_waitForRobIdx_flag(io_splitLoadReq_bits_uop_waitForRobIdx_flag),
    .io_splitLoadReq_bits_uop_waitForRobIdx_value(io_splitLoadReq_bits_uop_waitForRobIdx_value),
    .io_splitLoadReq_bits_uop_loadWaitBit(io_splitLoadReq_bits_uop_loadWaitBit),
    .io_splitLoadReq_bits_uop_loadWaitStrict(io_splitLoadReq_bits_uop_loadWaitStrict),
    .io_splitLoadReq_bits_uop_lqIdx_flag(io_splitLoadReq_bits_uop_lqIdx_flag),
    .io_splitLoadReq_bits_uop_lqIdx_value(io_splitLoadReq_bits_uop_lqIdx_value),
    .io_splitLoadReq_bits_uop_sqIdx_flag(io_splitLoadReq_bits_uop_sqIdx_flag),
    .io_splitLoadReq_bits_uop_sqIdx_value(io_splitLoadReq_bits_uop_sqIdx_value),
    .io_splitLoadReq_bits_vaddr(io_splitLoadReq_bits_vaddr),
    .io_splitLoadReq_bits_fullva(io_splitLoadReq_bits_fullva),
    .io_splitLoadReq_bits_mask(io_splitLoadReq_bits_mask),
    .io_splitLoadReq_bits_nc(io_splitLoadReq_bits_nc),
    .io_splitLoadReq_bits_mmio(io_splitLoadReq_bits_mmio),
    .io_splitLoadReq_bits_memBackTypeMM(io_splitLoadReq_bits_memBackTypeMM),
    .io_splitLoadReq_bits_isvec(io_splitLoadReq_bits_isvec),
    .io_splitLoadReq_bits_is128bit(io_splitLoadReq_bits_is128bit),
    .io_splitLoadReq_bits_vecActive(io_splitLoadReq_bits_vecActive),
    .io_splitLoadReq_bits_mshrid(io_splitLoadReq_bits_mshrid),
    .io_splitLoadReq_bits_schedIndex(io_splitLoadReq_bits_schedIndex),
    .io_splitLoadReq_bits_isFinalSplit(io_splitLoadReq_bits_isFinalSplit),
    .io_splitLoadReq_bits_misalignNeedWakeUp(io_splitLoadReq_bits_misalignNeedWakeUp),
    .io_splitLoadResp_valid(io_splitLoadResp_valid),
    .io_splitLoadResp_bits_uop_exceptionVec_3(io_splitLoadResp_bits_uop_exceptionVec_3),
    .io_splitLoadResp_bits_uop_exceptionVec_4(io_splitLoadResp_bits_uop_exceptionVec_4),
    .io_splitLoadResp_bits_uop_exceptionVec_5(io_splitLoadResp_bits_uop_exceptionVec_5),
    .io_splitLoadResp_bits_uop_exceptionVec_13(io_splitLoadResp_bits_uop_exceptionVec_13),
    .io_splitLoadResp_bits_uop_exceptionVec_19(io_splitLoadResp_bits_uop_exceptionVec_19),
    .io_splitLoadResp_bits_uop_exceptionVec_21(io_splitLoadResp_bits_uop_exceptionVec_21),
    .io_splitLoadResp_bits_uop_trigger(io_splitLoadResp_bits_uop_trigger),
    .io_splitLoadResp_bits_data(io_splitLoadResp_bits_data),
    .io_splitLoadResp_bits_nc(io_splitLoadResp_bits_nc),
    .io_splitLoadResp_bits_mmio(io_splitLoadResp_bits_mmio),
    .io_splitLoadResp_bits_memBackTypeMM(io_splitLoadResp_bits_memBackTypeMM),
    .io_splitLoadResp_bits_vecActive(io_splitLoadResp_bits_vecActive),
    .io_splitLoadResp_bits_misalignNeedWakeUp(io_splitLoadResp_bits_misalignNeedWakeUp),
    .io_splitLoadResp_bits_rep_info_cause_0(io_splitLoadResp_bits_rep_info_cause_0),
    .io_splitLoadResp_bits_rep_info_cause_1(io_splitLoadResp_bits_rep_info_cause_1),
    .io_splitLoadResp_bits_rep_info_cause_2(io_splitLoadResp_bits_rep_info_cause_2),
    .io_splitLoadResp_bits_rep_info_cause_3(io_splitLoadResp_bits_rep_info_cause_3),
    .io_splitLoadResp_bits_rep_info_cause_4(io_splitLoadResp_bits_rep_info_cause_4),
    .io_splitLoadResp_bits_rep_info_cause_5(io_splitLoadResp_bits_rep_info_cause_5),
    .io_splitLoadResp_bits_rep_info_cause_6(io_splitLoadResp_bits_rep_info_cause_6),
    .io_splitLoadResp_bits_rep_info_cause_7(io_splitLoadResp_bits_rep_info_cause_7),
    .io_splitLoadResp_bits_rep_info_cause_8(io_splitLoadResp_bits_rep_info_cause_8),
    .io_splitLoadResp_bits_rep_info_cause_9(io_splitLoadResp_bits_rep_info_cause_9),
    .io_splitLoadResp_bits_rep_info_cause_10(io_splitLoadResp_bits_rep_info_cause_10),
    .io_writeBack_ready(io_writeBack_ready),
    .io_writeBack_valid(io_writeBack_valid),
    .io_writeBack_bits_uop_exceptionVec_3(io_writeBack_bits_uop_exceptionVec_3),
    .io_writeBack_bits_uop_exceptionVec_4(io_writeBack_bits_uop_exceptionVec_4),
    .io_writeBack_bits_uop_exceptionVec_5(io_writeBack_bits_uop_exceptionVec_5),
    .io_writeBack_bits_uop_exceptionVec_13(io_writeBack_bits_uop_exceptionVec_13),
    .io_writeBack_bits_uop_exceptionVec_19(io_writeBack_bits_uop_exceptionVec_19),
    .io_writeBack_bits_uop_exceptionVec_21(io_writeBack_bits_uop_exceptionVec_21),
    .io_writeBack_bits_uop_trigger(io_writeBack_bits_uop_trigger),
    .io_writeBack_bits_uop_rfWen(io_writeBack_bits_uop_rfWen),
    .io_writeBack_bits_uop_fpWen(io_writeBack_bits_uop_fpWen),
    .io_writeBack_bits_uop_pdest(io_writeBack_bits_uop_pdest),
    .io_writeBack_bits_uop_robIdx_flag(io_writeBack_bits_uop_robIdx_flag),
    .io_writeBack_bits_uop_robIdx_value(io_writeBack_bits_uop_robIdx_value),
    .io_writeBack_bits_uop_debugInfo_enqRsTime(io_writeBack_bits_uop_debugInfo_enqRsTime),
    .io_writeBack_bits_uop_debugInfo_selectTime(io_writeBack_bits_uop_debugInfo_selectTime),
    .io_writeBack_bits_uop_debugInfo_issueTime(io_writeBack_bits_uop_debugInfo_issueTime),
    .io_writeBack_bits_data(io_writeBack_bits_data),
    .io_writeBack_bits_debug_isMMIO(io_writeBack_bits_debug_isMMIO),
    .io_writeBack_bits_debug_isNCIO(io_writeBack_bits_debug_isNCIO),
    .io_vecWriteBack_valid(io_vecWriteBack_valid),
    .io_vecWriteBack_bits_mBIndex(io_vecWriteBack_bits_mBIndex),
    .io_vecWriteBack_bits_exceptionVec_3(io_vecWriteBack_bits_exceptionVec_3),
    .io_vecWriteBack_bits_exceptionVec_4(io_vecWriteBack_bits_exceptionVec_4),
    .io_vecWriteBack_bits_exceptionVec_5(io_vecWriteBack_bits_exceptionVec_5),
    .io_vecWriteBack_bits_exceptionVec_13(io_vecWriteBack_bits_exceptionVec_13),
    .io_vecWriteBack_bits_exceptionVec_19(io_vecWriteBack_bits_exceptionVec_19),
    .io_vecWriteBack_bits_exceptionVec_21(io_vecWriteBack_bits_exceptionVec_21),
    .io_vecWriteBack_bits_hasException(io_vecWriteBack_bits_hasException),
    .io_vecWriteBack_bits_vaddr(io_vecWriteBack_bits_vaddr),
    .io_vecWriteBack_bits_vaNeedExt(io_vecWriteBack_bits_vaNeedExt),
    .io_vecWriteBack_bits_gpaddr(io_vecWriteBack_bits_gpaddr),
    .io_vecWriteBack_bits_vstart(io_vecWriteBack_bits_vstart),
    .io_vecWriteBack_bits_vecTriggerMask(io_vecWriteBack_bits_vecTriggerMask),
    .io_vecWriteBack_bits_elemIdx(io_vecWriteBack_bits_elemIdx),
    .io_vecWriteBack_bits_mask(io_vecWriteBack_bits_mask),
    .io_vecWriteBack_bits_alignedType(io_vecWriteBack_bits_alignedType),
    .io_vecWriteBack_bits_elemIdxInsideVd(io_vecWriteBack_bits_elemIdxInsideVd),
    .io_vecWriteBack_bits_vecdata(io_vecWriteBack_bits_vecdata),
    .io_loadOutValid(io_loadOutValid),
    .io_loadVecOutValid(io_loadVecOutValid),
    .io_loadMisalignFull(io_loadMisalignFull)
  );
endmodule
