// 自动生成:scripts/gen_xstile.py —— 勿手改(顶层 glue 为从 Scala 意图的可读重写)

// golden 同名扁平 wrapper(FM/ST 用):例化可读核 xs_XSTile_core。
module XSTile(
  input  clock,
  input  reset,
  output  auto_l2top_inner_beu_int_out_0,
  input  auto_l2top_inner_nmi_int_in_0,
  input  auto_l2top_inner_nmi_int_in_1,
  input  auto_l2top_inner_plic_int_in_1_0,
  input  auto_l2top_inner_plic_int_in_0_0,
  input  auto_l2top_inner_debug_int_in_0,
  input  auto_l2top_inner_clint_int_in_0,
  input  auto_l2top_inner_clint_int_in_1,
  input  [5:0] io_hartId,
  input  io_msiInfo_valid,
  input  [10:0] io_msiInfo_bits,
  input  [47:0] io_reset_vector,
  output  io_cpu_halt,
  output  io_cpu_crtical_error,
  output  io_hartIsInReset,
  input  io_traceCoreInterface_fromEncoder_enable,
  input  io_traceCoreInterface_fromEncoder_stall,
  output  [2:0] io_traceCoreInterface_toEncoder_priv,
  output  [63:0] io_traceCoreInterface_toEncoder_trap_cause,
  output  [49:0] io_traceCoreInterface_toEncoder_trap_tval,
  output  [49:0] io_traceCoreInterface_toEncoder_groups_0_bits_iaddr,
  output  [3:0] io_traceCoreInterface_toEncoder_groups_0_bits_itype,
  output  [6:0] io_traceCoreInterface_toEncoder_groups_0_bits_iretire,
  output  io_traceCoreInterface_toEncoder_groups_0_bits_ilastsize,
  output  [49:0] io_traceCoreInterface_toEncoder_groups_1_bits_iaddr,
  output  [3:0] io_traceCoreInterface_toEncoder_groups_1_bits_itype,
  output  [6:0] io_traceCoreInterface_toEncoder_groups_1_bits_iretire,
  output  io_traceCoreInterface_toEncoder_groups_1_bits_ilastsize,
  output  [49:0] io_traceCoreInterface_toEncoder_groups_2_bits_iaddr,
  output  [3:0] io_traceCoreInterface_toEncoder_groups_2_bits_itype,
  output  [6:0] io_traceCoreInterface_toEncoder_groups_2_bits_iretire,
  output  io_traceCoreInterface_toEncoder_groups_2_bits_ilastsize,
  output  io_debugTopDown_robHeadPaddr_valid,
  output  [47:0] io_debugTopDown_robHeadPaddr_bits,
  input  io_debugTopDown_l3MissMatch,
  input  io_l3Miss,
  output  io_chi_txsactive,
  input  io_chi_rxsactive,
  output  io_chi_syscoreq,
  input  io_chi_syscoack,
  output  io_chi_tx_linkactivereq,
  input  io_chi_tx_linkactiveack,
  output  io_chi_tx_req_flitpend,
  output  io_chi_tx_req_flitv,
  output  [161:0] io_chi_tx_req_flit,
  input  io_chi_tx_req_lcrdv,
  output  io_chi_tx_rsp_flitpend,
  output  io_chi_tx_rsp_flitv,
  output  [72:0] io_chi_tx_rsp_flit,
  input  io_chi_tx_rsp_lcrdv,
  output  io_chi_tx_dat_flitpend,
  output  io_chi_tx_dat_flitv,
  output  [421:0] io_chi_tx_dat_flit,
  input  io_chi_tx_dat_lcrdv,
  input  io_chi_rx_linkactivereq,
  output  io_chi_rx_linkactiveack,
  input  io_chi_rx_rsp_flitpend,
  input  io_chi_rx_rsp_flitv,
  input  [72:0] io_chi_rx_rsp_flit,
  output  io_chi_rx_rsp_lcrdv,
  input  io_chi_rx_dat_flitpend,
  input  io_chi_rx_dat_flitv,
  input  [421:0] io_chi_rx_dat_flit,
  output  io_chi_rx_dat_lcrdv,
  input  io_chi_rx_snp_flitpend,
  input  io_chi_rx_snp_flitv,
  input  [114:0] io_chi_rx_snp_flit,
  output  io_chi_rx_snp_lcrdv,
  input  [10:0] io_nodeID,
  input  io_clintTime_valid,
  input  [63:0] io_clintTime_bits,
  input  io_dft_ram_hold,
  input  io_dft_ram_bypass,
  input  io_dft_ram_bp_clken,
  input  io_dft_ram_aux_clk,
  input  io_dft_ram_aux_ckbp,
  input  io_dft_ram_mcp_hold,
  input  [63:0] io_dft_ram_ctl,
  input  io_dft_cgen,
  input  io_dft_reset_lgc_rst_n,
  input  io_dft_reset_mode,
  input  io_dft_reset_scan_mode
);
  xs_XSTile_core u_core (
    .clock(clock),
    .reset(reset),
    .auto_l2top_inner_beu_int_out_0(auto_l2top_inner_beu_int_out_0),
    .auto_l2top_inner_nmi_int_in_0(auto_l2top_inner_nmi_int_in_0),
    .auto_l2top_inner_nmi_int_in_1(auto_l2top_inner_nmi_int_in_1),
    .auto_l2top_inner_plic_int_in_1_0(auto_l2top_inner_plic_int_in_1_0),
    .auto_l2top_inner_plic_int_in_0_0(auto_l2top_inner_plic_int_in_0_0),
    .auto_l2top_inner_debug_int_in_0(auto_l2top_inner_debug_int_in_0),
    .auto_l2top_inner_clint_int_in_0(auto_l2top_inner_clint_int_in_0),
    .auto_l2top_inner_clint_int_in_1(auto_l2top_inner_clint_int_in_1),
    .io_hartId(io_hartId),
    .io_msiInfo_valid(io_msiInfo_valid),
    .io_msiInfo_bits(io_msiInfo_bits),
    .io_reset_vector(io_reset_vector),
    .io_cpu_halt(io_cpu_halt),
    .io_cpu_crtical_error(io_cpu_crtical_error),
    .io_hartIsInReset(io_hartIsInReset),
    .io_traceCoreInterface_fromEncoder_enable(io_traceCoreInterface_fromEncoder_enable),
    .io_traceCoreInterface_fromEncoder_stall(io_traceCoreInterface_fromEncoder_stall),
    .io_traceCoreInterface_toEncoder_priv(io_traceCoreInterface_toEncoder_priv),
    .io_traceCoreInterface_toEncoder_trap_cause(io_traceCoreInterface_toEncoder_trap_cause),
    .io_traceCoreInterface_toEncoder_trap_tval(io_traceCoreInterface_toEncoder_trap_tval),
    .io_traceCoreInterface_toEncoder_groups_0_bits_iaddr(io_traceCoreInterface_toEncoder_groups_0_bits_iaddr),
    .io_traceCoreInterface_toEncoder_groups_0_bits_itype(io_traceCoreInterface_toEncoder_groups_0_bits_itype),
    .io_traceCoreInterface_toEncoder_groups_0_bits_iretire(io_traceCoreInterface_toEncoder_groups_0_bits_iretire),
    .io_traceCoreInterface_toEncoder_groups_0_bits_ilastsize(io_traceCoreInterface_toEncoder_groups_0_bits_ilastsize),
    .io_traceCoreInterface_toEncoder_groups_1_bits_iaddr(io_traceCoreInterface_toEncoder_groups_1_bits_iaddr),
    .io_traceCoreInterface_toEncoder_groups_1_bits_itype(io_traceCoreInterface_toEncoder_groups_1_bits_itype),
    .io_traceCoreInterface_toEncoder_groups_1_bits_iretire(io_traceCoreInterface_toEncoder_groups_1_bits_iretire),
    .io_traceCoreInterface_toEncoder_groups_1_bits_ilastsize(io_traceCoreInterface_toEncoder_groups_1_bits_ilastsize),
    .io_traceCoreInterface_toEncoder_groups_2_bits_iaddr(io_traceCoreInterface_toEncoder_groups_2_bits_iaddr),
    .io_traceCoreInterface_toEncoder_groups_2_bits_itype(io_traceCoreInterface_toEncoder_groups_2_bits_itype),
    .io_traceCoreInterface_toEncoder_groups_2_bits_iretire(io_traceCoreInterface_toEncoder_groups_2_bits_iretire),
    .io_traceCoreInterface_toEncoder_groups_2_bits_ilastsize(io_traceCoreInterface_toEncoder_groups_2_bits_ilastsize),
    .io_debugTopDown_robHeadPaddr_valid(io_debugTopDown_robHeadPaddr_valid),
    .io_debugTopDown_robHeadPaddr_bits(io_debugTopDown_robHeadPaddr_bits),
    .io_debugTopDown_l3MissMatch(io_debugTopDown_l3MissMatch),
    .io_l3Miss(io_l3Miss),
    .io_chi_txsactive(io_chi_txsactive),
    .io_chi_rxsactive(io_chi_rxsactive),
    .io_chi_syscoreq(io_chi_syscoreq),
    .io_chi_syscoack(io_chi_syscoack),
    .io_chi_tx_linkactivereq(io_chi_tx_linkactivereq),
    .io_chi_tx_linkactiveack(io_chi_tx_linkactiveack),
    .io_chi_tx_req_flitpend(io_chi_tx_req_flitpend),
    .io_chi_tx_req_flitv(io_chi_tx_req_flitv),
    .io_chi_tx_req_flit(io_chi_tx_req_flit),
    .io_chi_tx_req_lcrdv(io_chi_tx_req_lcrdv),
    .io_chi_tx_rsp_flitpend(io_chi_tx_rsp_flitpend),
    .io_chi_tx_rsp_flitv(io_chi_tx_rsp_flitv),
    .io_chi_tx_rsp_flit(io_chi_tx_rsp_flit),
    .io_chi_tx_rsp_lcrdv(io_chi_tx_rsp_lcrdv),
    .io_chi_tx_dat_flitpend(io_chi_tx_dat_flitpend),
    .io_chi_tx_dat_flitv(io_chi_tx_dat_flitv),
    .io_chi_tx_dat_flit(io_chi_tx_dat_flit),
    .io_chi_tx_dat_lcrdv(io_chi_tx_dat_lcrdv),
    .io_chi_rx_linkactivereq(io_chi_rx_linkactivereq),
    .io_chi_rx_linkactiveack(io_chi_rx_linkactiveack),
    .io_chi_rx_rsp_flitpend(io_chi_rx_rsp_flitpend),
    .io_chi_rx_rsp_flitv(io_chi_rx_rsp_flitv),
    .io_chi_rx_rsp_flit(io_chi_rx_rsp_flit),
    .io_chi_rx_rsp_lcrdv(io_chi_rx_rsp_lcrdv),
    .io_chi_rx_dat_flitpend(io_chi_rx_dat_flitpend),
    .io_chi_rx_dat_flitv(io_chi_rx_dat_flitv),
    .io_chi_rx_dat_flit(io_chi_rx_dat_flit),
    .io_chi_rx_dat_lcrdv(io_chi_rx_dat_lcrdv),
    .io_chi_rx_snp_flitpend(io_chi_rx_snp_flitpend),
    .io_chi_rx_snp_flitv(io_chi_rx_snp_flitv),
    .io_chi_rx_snp_flit(io_chi_rx_snp_flit),
    .io_chi_rx_snp_lcrdv(io_chi_rx_snp_lcrdv),
    .io_nodeID(io_nodeID),
    .io_clintTime_valid(io_clintTime_valid),
    .io_clintTime_bits(io_clintTime_bits),
    .io_dft_ram_hold(io_dft_ram_hold),
    .io_dft_ram_bypass(io_dft_ram_bypass),
    .io_dft_ram_bp_clken(io_dft_ram_bp_clken),
    .io_dft_ram_aux_clk(io_dft_ram_aux_clk),
    .io_dft_ram_aux_ckbp(io_dft_ram_aux_ckbp),
    .io_dft_ram_mcp_hold(io_dft_ram_mcp_hold),
    .io_dft_ram_ctl(io_dft_ram_ctl),
    .io_dft_cgen(io_dft_cgen),
    .io_dft_reset_lgc_rst_n(io_dft_reset_lgc_rst_n),
    .io_dft_reset_mode(io_dft_reset_mode),
    .io_dft_reset_scan_mode(io_dft_reset_scan_mode)
  );
endmodule
