// 自动生成:scripts/gen_xstile.py —— 勿手改(顶层 glue 为从 Scala 意图的可读重写)

// 可读核端口表(与 golden XSTile 同名扁平端口,供 FM/ST 对接)。
// clock/reset 在核声明处单列,这里只列功能端口。
  output auto_l2top_inner_beu_int_out_0,
  input auto_l2top_inner_nmi_int_in_0,
  input auto_l2top_inner_nmi_int_in_1,
  input auto_l2top_inner_plic_int_in_1_0,
  input auto_l2top_inner_plic_int_in_0_0,
  input auto_l2top_inner_debug_int_in_0,
  input auto_l2top_inner_clint_int_in_0,
  input auto_l2top_inner_clint_int_in_1,
  input [5:0] io_hartId,
  input io_msiInfo_valid,
  input [10:0] io_msiInfo_bits,
  input [47:0] io_reset_vector,
  output io_cpu_halt,
  output io_cpu_crtical_error,
  output io_hartIsInReset,
  input io_traceCoreInterface_fromEncoder_enable,
  input io_traceCoreInterface_fromEncoder_stall,
  output [2:0] io_traceCoreInterface_toEncoder_priv,
  output [63:0] io_traceCoreInterface_toEncoder_trap_cause,
  output [49:0] io_traceCoreInterface_toEncoder_trap_tval,
  output [49:0] io_traceCoreInterface_toEncoder_groups_0_bits_iaddr,
  output [3:0] io_traceCoreInterface_toEncoder_groups_0_bits_itype,
  output [6:0] io_traceCoreInterface_toEncoder_groups_0_bits_iretire,
  output io_traceCoreInterface_toEncoder_groups_0_bits_ilastsize,
  output [49:0] io_traceCoreInterface_toEncoder_groups_1_bits_iaddr,
  output [3:0] io_traceCoreInterface_toEncoder_groups_1_bits_itype,
  output [6:0] io_traceCoreInterface_toEncoder_groups_1_bits_iretire,
  output io_traceCoreInterface_toEncoder_groups_1_bits_ilastsize,
  output [49:0] io_traceCoreInterface_toEncoder_groups_2_bits_iaddr,
  output [3:0] io_traceCoreInterface_toEncoder_groups_2_bits_itype,
  output [6:0] io_traceCoreInterface_toEncoder_groups_2_bits_iretire,
  output io_traceCoreInterface_toEncoder_groups_2_bits_ilastsize,
  output io_debugTopDown_robHeadPaddr_valid,
  output [47:0] io_debugTopDown_robHeadPaddr_bits,
  input io_debugTopDown_l3MissMatch,
  input io_l3Miss,
  output io_chi_txsactive,
  input io_chi_rxsactive,
  output io_chi_syscoreq,
  input io_chi_syscoack,
  output io_chi_tx_linkactivereq,
  input io_chi_tx_linkactiveack,
  output io_chi_tx_req_flitpend,
  output io_chi_tx_req_flitv,
  output [161:0] io_chi_tx_req_flit,
  input io_chi_tx_req_lcrdv,
  output io_chi_tx_rsp_flitpend,
  output io_chi_tx_rsp_flitv,
  output [72:0] io_chi_tx_rsp_flit,
  input io_chi_tx_rsp_lcrdv,
  output io_chi_tx_dat_flitpend,
  output io_chi_tx_dat_flitv,
  output [421:0] io_chi_tx_dat_flit,
  input io_chi_tx_dat_lcrdv,
  input io_chi_rx_linkactivereq,
  output io_chi_rx_linkactiveack,
  input io_chi_rx_rsp_flitpend,
  input io_chi_rx_rsp_flitv,
  input [72:0] io_chi_rx_rsp_flit,
  output io_chi_rx_rsp_lcrdv,
  input io_chi_rx_dat_flitpend,
  input io_chi_rx_dat_flitv,
  input [421:0] io_chi_rx_dat_flit,
  output io_chi_rx_dat_lcrdv,
  input io_chi_rx_snp_flitpend,
  input io_chi_rx_snp_flitv,
  input [114:0] io_chi_rx_snp_flit,
  output io_chi_rx_snp_lcrdv,
  input [10:0] io_nodeID,
  input io_clintTime_valid,
  input [63:0] io_clintTime_bits,
  input io_dft_ram_hold,
  input io_dft_ram_bypass,
  input io_dft_ram_bp_clken,
  input io_dft_ram_aux_clk,
  input io_dft_ram_aux_ckbp,
  input io_dft_ram_mcp_hold,
  input [63:0] io_dft_ram_ctl,
  input io_dft_cgen,
  input io_dft_reset_lgc_rst_n,
  input io_dft_reset_mode,
  input io_dft_reset_scan_mode
