// 自动生成:scripts/gen_xstile.py —— 勿手改(顶层 glue 为从 Scala 意图的可读重写)

// 3 子模块(core/l2top/intBuffer,golden 黑盒)输出/互联网声明,
// 宽度从 golden wire 声明收割。由 xstile_inst.svh 绑定子模块输出引脚,
// 互联直连 / outassign 消费。

  logic [47:0] _core_auto_memBlock_inner_buffers_out_a_bits_address;
  logic _core_auto_memBlock_inner_buffers_out_a_bits_corrupt;
  logic [63:0] _core_auto_memBlock_inner_buffers_out_a_bits_data;
  logic [7:0] _core_auto_memBlock_inner_buffers_out_a_bits_mask;
  logic [3:0] _core_auto_memBlock_inner_buffers_out_a_bits_opcode;
  logic [2:0] _core_auto_memBlock_inner_buffers_out_a_bits_param;
  logic [1:0] _core_auto_memBlock_inner_buffers_out_a_bits_size;
  logic [1:0] _core_auto_memBlock_inner_buffers_out_a_bits_source;
  logic _core_auto_memBlock_inner_buffers_out_a_bits_user_memBackType_MM;
  logic _core_auto_memBlock_inner_buffers_out_a_bits_user_memPageType_NC;
  logic _core_auto_memBlock_inner_buffers_out_a_valid;
  logic _core_auto_memBlock_inner_buffers_out_d_ready;
  logic [47:0] _core_auto_memBlock_inner_dcache_client_out_a_bits_address;
  logic _core_auto_memBlock_inner_dcache_client_out_a_bits_corrupt;
  logic [255:0] _core_auto_memBlock_inner_dcache_client_out_a_bits_data;
  logic _core_auto_memBlock_inner_dcache_client_out_a_bits_echo_isKeyword;
  logic [31:0] _core_auto_memBlock_inner_dcache_client_out_a_bits_mask;
  logic [3:0] _core_auto_memBlock_inner_dcache_client_out_a_bits_opcode;
  logic [2:0] _core_auto_memBlock_inner_dcache_client_out_a_bits_param;
  logic [2:0] _core_auto_memBlock_inner_dcache_client_out_a_bits_size;
  logic [5:0] _core_auto_memBlock_inner_dcache_client_out_a_bits_source;
  logic [1:0] _core_auto_memBlock_inner_dcache_client_out_a_bits_user_alias;
  logic _core_auto_memBlock_inner_dcache_client_out_a_bits_user_needHint;
  logic [4:0] _core_auto_memBlock_inner_dcache_client_out_a_bits_user_reqSource;
  logic [43:0] _core_auto_memBlock_inner_dcache_client_out_a_bits_user_vaddr;
  logic _core_auto_memBlock_inner_dcache_client_out_a_valid;
  logic _core_auto_memBlock_inner_dcache_client_out_b_ready;
  logic [47:0] _core_auto_memBlock_inner_dcache_client_out_c_bits_address;
  logic _core_auto_memBlock_inner_dcache_client_out_c_bits_corrupt;
  logic [255:0] _core_auto_memBlock_inner_dcache_client_out_c_bits_data;
  logic _core_auto_memBlock_inner_dcache_client_out_c_bits_echo_isKeyword;
  logic [2:0] _core_auto_memBlock_inner_dcache_client_out_c_bits_opcode;
  logic [2:0] _core_auto_memBlock_inner_dcache_client_out_c_bits_param;
  logic [2:0] _core_auto_memBlock_inner_dcache_client_out_c_bits_size;
  logic [5:0] _core_auto_memBlock_inner_dcache_client_out_c_bits_source;
  logic [1:0] _core_auto_memBlock_inner_dcache_client_out_c_bits_user_alias;
  logic _core_auto_memBlock_inner_dcache_client_out_c_bits_user_needHint;
  logic [4:0] _core_auto_memBlock_inner_dcache_client_out_c_bits_user_reqSource;
  logic [43:0] _core_auto_memBlock_inner_dcache_client_out_c_bits_user_vaddr;
  logic _core_auto_memBlock_inner_dcache_client_out_c_valid;
  logic _core_auto_memBlock_inner_dcache_client_out_d_ready;
  logic [9:0] _core_auto_memBlock_inner_dcache_client_out_e_bits_sink;
  logic _core_auto_memBlock_inner_dcache_client_out_e_valid;
  logic [47:0] _core_auto_memBlock_inner_frontendBridge_icache_out_a_bits_address;
  logic _core_auto_memBlock_inner_frontendBridge_icache_out_a_bits_corrupt;
  logic [255:0] _core_auto_memBlock_inner_frontendBridge_icache_out_a_bits_data;
  logic [31:0] _core_auto_memBlock_inner_frontendBridge_icache_out_a_bits_mask;
  logic [3:0] _core_auto_memBlock_inner_frontendBridge_icache_out_a_bits_opcode;
  logic [2:0] _core_auto_memBlock_inner_frontendBridge_icache_out_a_bits_param;
  logic [2:0] _core_auto_memBlock_inner_frontendBridge_icache_out_a_bits_size;
  logic [3:0] _core_auto_memBlock_inner_frontendBridge_icache_out_a_bits_source;
  logic [1:0] _core_auto_memBlock_inner_frontendBridge_icache_out_a_bits_user_alias;
  logic _core_auto_memBlock_inner_frontendBridge_icache_out_a_bits_user_needHint;
  logic [4:0] _core_auto_memBlock_inner_frontendBridge_icache_out_a_bits_user_reqSource;
  logic _core_auto_memBlock_inner_frontendBridge_icache_out_a_valid;
  logic _core_auto_memBlock_inner_frontendBridge_icache_out_d_ready;
  logic _core_auto_memBlock_inner_frontendBridge_icachectrl_in_a_ready;
  logic _core_auto_memBlock_inner_frontendBridge_icachectrl_in_d_bits_corrupt;
  logic [63:0] _core_auto_memBlock_inner_frontendBridge_icachectrl_in_d_bits_data;
  logic _core_auto_memBlock_inner_frontendBridge_icachectrl_in_d_bits_denied;
  logic [3:0] _core_auto_memBlock_inner_frontendBridge_icachectrl_in_d_bits_opcode;
  logic [1:0] _core_auto_memBlock_inner_frontendBridge_icachectrl_in_d_bits_param;
  logic _core_auto_memBlock_inner_frontendBridge_icachectrl_in_d_bits_sink;
  logic [1:0] _core_auto_memBlock_inner_frontendBridge_icachectrl_in_d_bits_size;
  logic [2:0] _core_auto_memBlock_inner_frontendBridge_icachectrl_in_d_bits_source;
  logic _core_auto_memBlock_inner_frontendBridge_icachectrl_in_d_valid;
  logic [47:0] _core_auto_memBlock_inner_frontendBridge_instr_uncache_out_a_bits_address;
  logic _core_auto_memBlock_inner_frontendBridge_instr_uncache_out_a_bits_corrupt;
  logic [2:0] _core_auto_memBlock_inner_frontendBridge_instr_uncache_out_a_bits_param;
  logic _core_auto_memBlock_inner_frontendBridge_instr_uncache_out_a_valid;
  logic _core_auto_memBlock_inner_frontendBridge_instr_uncache_out_d_ready;
  logic [63:0] _core_auto_memBlock_inner_l2_pf_sender_out_addr;
  logic _core_auto_memBlock_inner_l2_pf_sender_out_addr_valid;
  logic [4:0] _core_auto_memBlock_inner_l2_pf_sender_out_pf_source;
  logic [47:0] _core_auto_memBlock_inner_ptw_to_l2_buffer_out_a_bits_address;
  logic _core_auto_memBlock_inner_ptw_to_l2_buffer_out_a_bits_corrupt;
  logic [255:0] _core_auto_memBlock_inner_ptw_to_l2_buffer_out_a_bits_data;
  logic [31:0] _core_auto_memBlock_inner_ptw_to_l2_buffer_out_a_bits_mask;
  logic [3:0] _core_auto_memBlock_inner_ptw_to_l2_buffer_out_a_bits_opcode;
  logic [2:0] _core_auto_memBlock_inner_ptw_to_l2_buffer_out_a_bits_param;
  logic [2:0] _core_auto_memBlock_inner_ptw_to_l2_buffer_out_a_bits_size;
  logic [2:0] _core_auto_memBlock_inner_ptw_to_l2_buffer_out_a_bits_source;
  logic [4:0] _core_auto_memBlock_inner_ptw_to_l2_buffer_out_a_bits_user_reqSource;
  logic _core_auto_memBlock_inner_ptw_to_l2_buffer_out_a_valid;
  logic _core_auto_memBlock_inner_ptw_to_l2_buffer_out_d_ready;
  logic [47:0] _core_io_beu_errors_dcache_ecc_error_bits;
  logic _core_io_beu_errors_dcache_ecc_error_valid;
  logic [47:0] _core_io_beu_errors_icache_ecc_error_bits;
  logic _core_io_beu_errors_icache_ecc_error_valid;
  logic [47:0] _core_io_beu_errors_uncache_ecc_error_bits;
  logic _core_io_beu_errors_uncache_ecc_error_valid;
  logic _core_io_cpu_critical_error;
  logic _core_io_cpu_halt;
  logic [47:0] _core_io_debugTopDown_robHeadPaddr_bits;
  logic _core_io_debugTopDown_robHeadPaddr_valid;
  logic _core_io_l2PfCtrl_l2_pbop_en;
  logic _core_io_l2PfCtrl_l2_pf_master_en;
  logic _core_io_l2PfCtrl_l2_pf_recv_en;
  logic _core_io_l2PfCtrl_l2_vbop_en;
  logic _core_io_l2_pmp_resp_ld;
  logic _core_io_l2_pmp_resp_mmio;
  logic _core_io_l2_tlb_req_resp_bits_excp_0_af_ld;
  logic _core_io_l2_tlb_req_resp_bits_excp_0_gpf_ld;
  logic _core_io_l2_tlb_req_resp_bits_excp_0_pf_ld;
  logic _core_io_l2_tlb_req_resp_bits_miss;
  logic [47:0] _core_io_l2_tlb_req_resp_bits_paddr_0;
  logic [1:0] _core_io_l2_tlb_req_resp_bits_pbmt_0;
  logic _core_io_l2_tlb_req_resp_valid;
  logic _core_io_resetInFrontend;
  logic [49:0] _core_io_traceCoreInterface_toEncoder_groups_0_bits_iaddr;
  logic _core_io_traceCoreInterface_toEncoder_groups_0_bits_ilastsize;
  logic [6:0] _core_io_traceCoreInterface_toEncoder_groups_0_bits_iretire;
  logic [3:0] _core_io_traceCoreInterface_toEncoder_groups_0_bits_itype;
  logic _core_io_traceCoreInterface_toEncoder_groups_0_valid;
  logic [49:0] _core_io_traceCoreInterface_toEncoder_groups_1_bits_iaddr;
  logic _core_io_traceCoreInterface_toEncoder_groups_1_bits_ilastsize;
  logic [6:0] _core_io_traceCoreInterface_toEncoder_groups_1_bits_iretire;
  logic [3:0] _core_io_traceCoreInterface_toEncoder_groups_1_bits_itype;
  logic _core_io_traceCoreInterface_toEncoder_groups_1_valid;
  logic [49:0] _core_io_traceCoreInterface_toEncoder_groups_2_bits_iaddr;
  logic _core_io_traceCoreInterface_toEncoder_groups_2_bits_ilastsize;
  logic [6:0] _core_io_traceCoreInterface_toEncoder_groups_2_bits_iretire;
  logic [3:0] _core_io_traceCoreInterface_toEncoder_groups_2_bits_itype;
  logic _core_io_traceCoreInterface_toEncoder_groups_2_valid;
  logic [2:0] _core_io_traceCoreInterface_toEncoder_priv;
  logic [63:0] _core_io_traceCoreInterface_toEncoder_trap_cause;
  logic [49:0] _core_io_traceCoreInterface_toEncoder_trap_tval;
  logic _intBuffer_auto_out_0;
  logic _l2top_auto_inner_beu_local_int_source_out_0;
  logic _l2top_auto_inner_buffers_in_a_ready;
  logic _l2top_auto_inner_buffers_in_d_bits_corrupt;
  logic [63:0] _l2top_auto_inner_buffers_in_d_bits_data;
  logic _l2top_auto_inner_buffers_in_d_bits_denied;
  logic [3:0] _l2top_auto_inner_buffers_in_d_bits_opcode;
  logic [1:0] _l2top_auto_inner_buffers_in_d_bits_param;
  logic _l2top_auto_inner_buffers_in_d_bits_sink;
  logic [1:0] _l2top_auto_inner_buffers_in_d_bits_size;
  logic [1:0] _l2top_auto_inner_buffers_in_d_bits_source;
  logic _l2top_auto_inner_buffers_in_d_valid;
  logic [29:0] _l2top_auto_inner_buffers_out_a_bits_address;
  logic _l2top_auto_inner_buffers_out_a_bits_corrupt;
  logic [63:0] _l2top_auto_inner_buffers_out_a_bits_data;
  logic [7:0] _l2top_auto_inner_buffers_out_a_bits_mask;
  logic [3:0] _l2top_auto_inner_buffers_out_a_bits_opcode;
  logic [2:0] _l2top_auto_inner_buffers_out_a_bits_param;
  logic [1:0] _l2top_auto_inner_buffers_out_a_bits_size;
  logic [2:0] _l2top_auto_inner_buffers_out_a_bits_source;
  logic _l2top_auto_inner_buffers_out_a_valid;
  logic _l2top_auto_inner_buffers_out_d_ready;
  logic _l2top_auto_inner_clint_int_out_0;
  logic _l2top_auto_inner_clint_int_out_1;
  logic _l2top_auto_inner_debug_int_out_0;
  logic _l2top_auto_inner_i_mmio_buffer_in_a_ready;
  logic _l2top_auto_inner_i_mmio_buffer_in_d_bits_corrupt;
  logic [63:0] _l2top_auto_inner_i_mmio_buffer_in_d_bits_data;
  logic _l2top_auto_inner_i_mmio_buffer_in_d_bits_denied;
  logic [3:0] _l2top_auto_inner_i_mmio_buffer_in_d_bits_opcode;
  logic [1:0] _l2top_auto_inner_i_mmio_buffer_in_d_bits_param;
  logic _l2top_auto_inner_i_mmio_buffer_in_d_bits_sink;
  logic [1:0] _l2top_auto_inner_i_mmio_buffer_in_d_bits_size;
  logic _l2top_auto_inner_i_mmio_buffer_in_d_bits_source;
  logic _l2top_auto_inner_i_mmio_buffer_in_d_valid;
  logic _l2top_auto_inner_logger_in_0_a_ready;
  logic [47:0] _l2top_auto_inner_logger_in_0_b_bits_address;
  logic _l2top_auto_inner_logger_in_0_b_bits_corrupt;
  logic [255:0] _l2top_auto_inner_logger_in_0_b_bits_data;
  logic [31:0] _l2top_auto_inner_logger_in_0_b_bits_mask;
  logic [2:0] _l2top_auto_inner_logger_in_0_b_bits_opcode;
  logic [1:0] _l2top_auto_inner_logger_in_0_b_bits_param;
  logic [2:0] _l2top_auto_inner_logger_in_0_b_bits_size;
  logic [5:0] _l2top_auto_inner_logger_in_0_b_bits_source;
  logic _l2top_auto_inner_logger_in_0_b_valid;
  logic _l2top_auto_inner_logger_in_0_c_ready;
  logic _l2top_auto_inner_logger_in_0_d_bits_corrupt;
  logic [255:0] _l2top_auto_inner_logger_in_0_d_bits_data;
  logic _l2top_auto_inner_logger_in_0_d_bits_denied;
  logic _l2top_auto_inner_logger_in_0_d_bits_echo_isKeyword;
  logic [3:0] _l2top_auto_inner_logger_in_0_d_bits_opcode;
  logic [1:0] _l2top_auto_inner_logger_in_0_d_bits_param;
  logic [9:0] _l2top_auto_inner_logger_in_0_d_bits_sink;
  logic [2:0] _l2top_auto_inner_logger_in_0_d_bits_size;
  logic [5:0] _l2top_auto_inner_logger_in_0_d_bits_source;
  logic _l2top_auto_inner_logger_in_0_d_valid;
  logic _l2top_auto_inner_logger_in_0_e_ready;
  logic _l2top_auto_inner_logger_in_1_a_ready;
  logic _l2top_auto_inner_logger_in_1_d_bits_corrupt;
  logic [255:0] _l2top_auto_inner_logger_in_1_d_bits_data;
  logic _l2top_auto_inner_logger_in_1_d_bits_denied;
  logic [3:0] _l2top_auto_inner_logger_in_1_d_bits_opcode;
  logic [1:0] _l2top_auto_inner_logger_in_1_d_bits_param;
  logic [9:0] _l2top_auto_inner_logger_in_1_d_bits_sink;
  logic [2:0] _l2top_auto_inner_logger_in_1_d_bits_size;
  logic [3:0] _l2top_auto_inner_logger_in_1_d_bits_source;
  logic _l2top_auto_inner_logger_in_1_d_valid;
  logic _l2top_auto_inner_nmi_int_out_0;
  logic _l2top_auto_inner_nmi_int_out_1;
  logic _l2top_auto_inner_plic_int_out_0_0;
  logic _l2top_auto_inner_plic_int_out_1_0;
  logic _l2top_auto_inner_ptw_to_l2_buffer_in_a_ready;
  logic _l2top_auto_inner_ptw_to_l2_buffer_in_d_bits_corrupt;
  logic [255:0] _l2top_auto_inner_ptw_to_l2_buffer_in_d_bits_data;
  logic _l2top_auto_inner_ptw_to_l2_buffer_in_d_bits_denied;
  logic [3:0] _l2top_auto_inner_ptw_to_l2_buffer_in_d_bits_opcode;
  logic [1:0] _l2top_auto_inner_ptw_to_l2_buffer_in_d_bits_param;
  logic [9:0] _l2top_auto_inner_ptw_to_l2_buffer_in_d_bits_sink;
  logic [2:0] _l2top_auto_inner_ptw_to_l2_buffer_in_d_bits_size;
  logic [2:0] _l2top_auto_inner_ptw_to_l2_buffer_in_d_bits_source;
  logic _l2top_auto_inner_ptw_to_l2_buffer_in_d_valid;
  logic [63:0] _l2top_io_clintTime_toCore_bits;
  logic _l2top_io_clintTime_toCore_valid;
  logic _l2top_io_debugTopDown_l2MissMatch;
  logic [63:0] _l2top_io_hartId_toCore;
  logic _l2top_io_l2Miss;
  logic _l2top_io_l2_hint_bits_isKeyword;
  logic [3:0] _l2top_io_l2_hint_bits_sourceId;
  logic _l2top_io_l2_hint_valid;
  logic [2:0] _l2top_io_l2_tlb_req_req_bits_cmd;
  logic _l2top_io_l2_tlb_req_req_bits_kill;
  logic _l2top_io_l2_tlb_req_req_bits_no_translate;
  logic [49:0] _l2top_io_l2_tlb_req_req_bits_vaddr;
  logic _l2top_io_l2_tlb_req_req_valid;
  logic _l2top_io_l3Miss_toCore;
  logic [10:0] _l2top_io_msiInfo_toCore_bits;
  logic _l2top_io_msiInfo_toCore_valid;
  logic [5:0] _l2top_io_perfEvents_10_value;
  logic [5:0] _l2top_io_perfEvents_11_value;
  logic [5:0] _l2top_io_perfEvents_12_value;
  logic [5:0] _l2top_io_perfEvents_13_value;
  logic [5:0] _l2top_io_perfEvents_14_value;
  logic [5:0] _l2top_io_perfEvents_15_value;
  logic [5:0] _l2top_io_perfEvents_16_value;
  logic [5:0] _l2top_io_perfEvents_17_value;
  logic [5:0] _l2top_io_perfEvents_18_value;
  logic [5:0] _l2top_io_perfEvents_19_value;
  logic [5:0] _l2top_io_perfEvents_1_value;
  logic [5:0] _l2top_io_perfEvents_20_value;
  logic [5:0] _l2top_io_perfEvents_21_value;
  logic [5:0] _l2top_io_perfEvents_22_value;
  logic [5:0] _l2top_io_perfEvents_23_value;
  logic [5:0] _l2top_io_perfEvents_24_value;
  logic [5:0] _l2top_io_perfEvents_25_value;
  logic [5:0] _l2top_io_perfEvents_26_value;
  logic [5:0] _l2top_io_perfEvents_27_value;
  logic [5:0] _l2top_io_perfEvents_28_value;
  logic [5:0] _l2top_io_perfEvents_29_value;
  logic [5:0] _l2top_io_perfEvents_2_value;
  logic [5:0] _l2top_io_perfEvents_30_value;
  logic [5:0] _l2top_io_perfEvents_31_value;
  logic [5:0] _l2top_io_perfEvents_32_value;
  logic [5:0] _l2top_io_perfEvents_33_value;
  logic [5:0] _l2top_io_perfEvents_34_value;
  logic [5:0] _l2top_io_perfEvents_35_value;
  logic [5:0] _l2top_io_perfEvents_36_value;
  logic [5:0] _l2top_io_perfEvents_37_value;
  logic [5:0] _l2top_io_perfEvents_38_value;
  logic [5:0] _l2top_io_perfEvents_39_value;
  logic [5:0] _l2top_io_perfEvents_3_value;
  logic [5:0] _l2top_io_perfEvents_40_value;
  logic [5:0] _l2top_io_perfEvents_41_value;
  logic [5:0] _l2top_io_perfEvents_42_value;
  logic [5:0] _l2top_io_perfEvents_43_value;
  logic [5:0] _l2top_io_perfEvents_44_value;
  logic [5:0] _l2top_io_perfEvents_45_value;
  logic [5:0] _l2top_io_perfEvents_46_value;
  logic [5:0] _l2top_io_perfEvents_47_value;
  logic [5:0] _l2top_io_perfEvents_48_value;
  logic [5:0] _l2top_io_perfEvents_4_value;
  logic [5:0] _l2top_io_perfEvents_5_value;
  logic [5:0] _l2top_io_perfEvents_6_value;
  logic [5:0] _l2top_io_perfEvents_7_value;
  logic [5:0] _l2top_io_perfEvents_8_value;
  logic [5:0] _l2top_io_perfEvents_9_value;
  logic [47:0] _l2top_io_reset_vector_toCore;
  logic _l2top_io_traceCoreInterface_fromCore_fromEncoder_enable;
  logic _l2top_io_traceCoreInterface_fromCore_fromEncoder_stall;
