// 自动生成: gen_mmio_ut.py —— MMIOBridge_xs (UT 变体, 例化 xs_MMIOBridge_core)
module MMIOBridge_xs(
  input clock,
  input reset,
  output auto_mmio_in_a_ready,
  input auto_mmio_in_a_valid,
  input [3:0] auto_mmio_in_a_bits_opcode,
  input [2:0] auto_mmio_in_a_bits_param,
  input [1:0] auto_mmio_in_a_bits_size,
  input [2:0] auto_mmio_in_a_bits_source,
  input [47:0] auto_mmio_in_a_bits_address,
  input auto_mmio_in_a_bits_user_memBackType_MM,
  input auto_mmio_in_a_bits_user_memPageType_NC,
  input [7:0] auto_mmio_in_a_bits_mask,
  input [63:0] auto_mmio_in_a_bits_data,
  input auto_mmio_in_a_bits_corrupt,
  input auto_mmio_in_d_ready,
  output auto_mmio_in_d_valid,
  output [3:0] auto_mmio_in_d_bits_opcode,
  output [1:0] auto_mmio_in_d_bits_param,
  output [1:0] auto_mmio_in_d_bits_size,
  output [2:0] auto_mmio_in_d_bits_source,
  output auto_mmio_in_d_bits_sink,
  output auto_mmio_in_d_bits_denied,
  output [63:0] auto_mmio_in_d_bits_data,
  output auto_mmio_in_d_bits_corrupt,
  input io_tx_req_ready,
  output io_tx_req_valid,
  output [3:0] io_tx_req_bits_qos,
  output [10:0] io_tx_req_bits_tgtID,
  output [10:0] io_tx_req_bits_srcID,
  output [11:0] io_tx_req_bits_txnID,
  output [10:0] io_tx_req_bits_returnNID,
  output io_tx_req_bits_stashNIDValid,
  output [11:0] io_tx_req_bits_returnTxnID,
  output [6:0] io_tx_req_bits_opcode,
  output [2:0] io_tx_req_bits_size,
  output [47:0] io_tx_req_bits_addr,
  output io_tx_req_bits_ns,
  output io_tx_req_bits_likelyshared,
  output io_tx_req_bits_allowRetry,
  output [1:0] io_tx_req_bits_order,
  output [3:0] io_tx_req_bits_pCrdType,
  output io_tx_req_bits_memAttr_allocate,
  output io_tx_req_bits_memAttr_cacheable,
  output io_tx_req_bits_memAttr_device,
  output io_tx_req_bits_memAttr_ewa,
  output io_tx_req_bits_snpAttr,
  output [7:0] io_tx_req_bits_lpIDWithPadding,
  output io_tx_req_bits_snoopMe,
  output io_tx_req_bits_expCompAck,
  output [1:0] io_tx_req_bits_tagOp,
  output io_tx_req_bits_traceTag,
  output io_tx_req_bits_mpam_perfMonGroup,
  output [8:0] io_tx_req_bits_mpam_partID,
  output io_tx_req_bits_mpam_mpamNS,
  output [3:0] io_tx_req_bits_rsvdc,
  input io_tx_dat_ready,
  output io_tx_dat_valid,
  output [3:0] io_tx_dat_bits_qos,
  output [10:0] io_tx_dat_bits_tgtID,
  output [10:0] io_tx_dat_bits_srcID,
  output [11:0] io_tx_dat_bits_txnID,
  output [10:0] io_tx_dat_bits_homeNID,
  output [3:0] io_tx_dat_bits_opcode,
  output [1:0] io_tx_dat_bits_respErr,
  output [2:0] io_tx_dat_bits_resp,
  output [3:0] io_tx_dat_bits_dataSource,
  output [2:0] io_tx_dat_bits_cBusy,
  output [11:0] io_tx_dat_bits_dbID,
  output [1:0] io_tx_dat_bits_ccID,
  output [1:0] io_tx_dat_bits_dataID,
  output [1:0] io_tx_dat_bits_tagOp,
  output [7:0] io_tx_dat_bits_tag,
  output [1:0] io_tx_dat_bits_tu,
  output io_tx_dat_bits_traceTag,
  output [3:0] io_tx_dat_bits_rsvdc,
  output [31:0] io_tx_dat_bits_be,
  output [255:0] io_tx_dat_bits_data,
  output [31:0] io_tx_dat_bits_dataCheck,
  output [3:0] io_tx_dat_bits_poison,
  output io_rx_rsp_ready,
  input io_rx_rsp_valid,
  input [3:0] io_rx_rsp_bits_qos,
  input [10:0] io_rx_rsp_bits_tgtID,
  input [10:0] io_rx_rsp_bits_srcID,
  input [11:0] io_rx_rsp_bits_txnID,
  input [4:0] io_rx_rsp_bits_opcode,
  input [1:0] io_rx_rsp_bits_respErr,
  input [2:0] io_rx_rsp_bits_resp,
  input [2:0] io_rx_rsp_bits_fwdState,
  input [2:0] io_rx_rsp_bits_cBusy,
  input [11:0] io_rx_rsp_bits_dbID,
  input [3:0] io_rx_rsp_bits_pCrdType,
  input [1:0] io_rx_rsp_bits_tagOp,
  input io_rx_rsp_bits_traceTag,
  output io_rx_dat_ready,
  input io_rx_dat_valid,
  input [3:0] io_rx_dat_bits_qos,
  input [10:0] io_rx_dat_bits_tgtID,
  input [10:0] io_rx_dat_bits_srcID,
  input [11:0] io_rx_dat_bits_txnID,
  input [10:0] io_rx_dat_bits_homeNID,
  input [3:0] io_rx_dat_bits_opcode,
  input [1:0] io_rx_dat_bits_respErr,
  input [2:0] io_rx_dat_bits_resp,
  input [3:0] io_rx_dat_bits_dataSource,
  input [2:0] io_rx_dat_bits_cBusy,
  input [11:0] io_rx_dat_bits_dbID,
  input [1:0] io_rx_dat_bits_ccID,
  input [1:0] io_rx_dat_bits_dataID,
  input [1:0] io_rx_dat_bits_tagOp,
  input [7:0] io_rx_dat_bits_tag,
  input [1:0] io_rx_dat_bits_tu,
  input io_rx_dat_bits_traceTag,
  input [3:0] io_rx_dat_bits_rsvdc,
  input [31:0] io_rx_dat_bits_be,
  input [255:0] io_rx_dat_bits_data,
  input [31:0] io_rx_dat_bits_dataCheck,
  input [3:0] io_rx_dat_bits_poison,
  output io_pCrd_0_query_valid,
  output [3:0] io_pCrd_0_query_bits_pCrdType,
  output [10:0] io_pCrd_0_query_bits_srcID,
  input io_pCrd_0_grant,
  output io_pCrd_1_query_valid,
  output [3:0] io_pCrd_1_query_bits_pCrdType,
  output [10:0] io_pCrd_1_query_bits_srcID,
  input io_pCrd_1_grant,
  output io_pCrd_2_query_valid,
  output [3:0] io_pCrd_2_query_bits_pCrdType,
  output [10:0] io_pCrd_2_query_bits_srcID,
  input io_pCrd_2_grant,
  output io_pCrd_3_query_valid,
  output [3:0] io_pCrd_3_query_bits_pCrdType,
  output [10:0] io_pCrd_3_query_bits_srcID,
  input io_pCrd_3_grant,
  output io_pCrd_4_query_valid,
  output [3:0] io_pCrd_4_query_bits_pCrdType,
  output [10:0] io_pCrd_4_query_bits_srcID,
  input io_pCrd_4_grant,
  output io_pCrd_5_query_valid,
  output [3:0] io_pCrd_5_query_bits_pCrdType,
  output [10:0] io_pCrd_5_query_bits_srcID,
  input io_pCrd_5_grant,
  output io_pCrd_6_query_valid,
  output [3:0] io_pCrd_6_query_bits_pCrdType,
  output [10:0] io_pCrd_6_query_bits_srcID,
  input io_pCrd_6_grant,
  output io_pCrd_7_query_valid,
  output [3:0] io_pCrd_7_query_bits_pCrdType,
  output [10:0] io_pCrd_7_query_bits_srcID,
  input io_pCrd_7_grant
);
  xs_MMIOBridge_core u_core (
    .clock(clock),
    .reset(reset),
    .auto_mmio_in_a_ready(auto_mmio_in_a_ready),
    .auto_mmio_in_a_valid(auto_mmio_in_a_valid),
    .auto_mmio_in_a_bits_opcode(auto_mmio_in_a_bits_opcode),
    .auto_mmio_in_a_bits_param(auto_mmio_in_a_bits_param),
    .auto_mmio_in_a_bits_size(auto_mmio_in_a_bits_size),
    .auto_mmio_in_a_bits_source(auto_mmio_in_a_bits_source),
    .auto_mmio_in_a_bits_address(auto_mmio_in_a_bits_address),
    .auto_mmio_in_a_bits_user_memBackType_MM(auto_mmio_in_a_bits_user_memBackType_MM),
    .auto_mmio_in_a_bits_user_memPageType_NC(auto_mmio_in_a_bits_user_memPageType_NC),
    .auto_mmio_in_a_bits_mask(auto_mmio_in_a_bits_mask),
    .auto_mmio_in_a_bits_data(auto_mmio_in_a_bits_data),
    .auto_mmio_in_a_bits_corrupt(auto_mmio_in_a_bits_corrupt),
    .auto_mmio_in_d_ready(auto_mmio_in_d_ready),
    .auto_mmio_in_d_valid(auto_mmio_in_d_valid),
    .auto_mmio_in_d_bits_opcode(auto_mmio_in_d_bits_opcode),
    .auto_mmio_in_d_bits_param(auto_mmio_in_d_bits_param),
    .auto_mmio_in_d_bits_size(auto_mmio_in_d_bits_size),
    .auto_mmio_in_d_bits_source(auto_mmio_in_d_bits_source),
    .auto_mmio_in_d_bits_sink(auto_mmio_in_d_bits_sink),
    .auto_mmio_in_d_bits_denied(auto_mmio_in_d_bits_denied),
    .auto_mmio_in_d_bits_data(auto_mmio_in_d_bits_data),
    .auto_mmio_in_d_bits_corrupt(auto_mmio_in_d_bits_corrupt),
    .io_tx_req_ready(io_tx_req_ready),
    .io_tx_req_valid(io_tx_req_valid),
    .io_tx_req_bits_qos(io_tx_req_bits_qos),
    .io_tx_req_bits_tgtID(io_tx_req_bits_tgtID),
    .io_tx_req_bits_srcID(io_tx_req_bits_srcID),
    .io_tx_req_bits_txnID(io_tx_req_bits_txnID),
    .io_tx_req_bits_returnNID(io_tx_req_bits_returnNID),
    .io_tx_req_bits_stashNIDValid(io_tx_req_bits_stashNIDValid),
    .io_tx_req_bits_returnTxnID(io_tx_req_bits_returnTxnID),
    .io_tx_req_bits_opcode(io_tx_req_bits_opcode),
    .io_tx_req_bits_size(io_tx_req_bits_size),
    .io_tx_req_bits_addr(io_tx_req_bits_addr),
    .io_tx_req_bits_ns(io_tx_req_bits_ns),
    .io_tx_req_bits_likelyshared(io_tx_req_bits_likelyshared),
    .io_tx_req_bits_allowRetry(io_tx_req_bits_allowRetry),
    .io_tx_req_bits_order(io_tx_req_bits_order),
    .io_tx_req_bits_pCrdType(io_tx_req_bits_pCrdType),
    .io_tx_req_bits_memAttr_allocate(io_tx_req_bits_memAttr_allocate),
    .io_tx_req_bits_memAttr_cacheable(io_tx_req_bits_memAttr_cacheable),
    .io_tx_req_bits_memAttr_device(io_tx_req_bits_memAttr_device),
    .io_tx_req_bits_memAttr_ewa(io_tx_req_bits_memAttr_ewa),
    .io_tx_req_bits_snpAttr(io_tx_req_bits_snpAttr),
    .io_tx_req_bits_lpIDWithPadding(io_tx_req_bits_lpIDWithPadding),
    .io_tx_req_bits_snoopMe(io_tx_req_bits_snoopMe),
    .io_tx_req_bits_expCompAck(io_tx_req_bits_expCompAck),
    .io_tx_req_bits_tagOp(io_tx_req_bits_tagOp),
    .io_tx_req_bits_traceTag(io_tx_req_bits_traceTag),
    .io_tx_req_bits_mpam_perfMonGroup(io_tx_req_bits_mpam_perfMonGroup),
    .io_tx_req_bits_mpam_partID(io_tx_req_bits_mpam_partID),
    .io_tx_req_bits_mpam_mpamNS(io_tx_req_bits_mpam_mpamNS),
    .io_tx_req_bits_rsvdc(io_tx_req_bits_rsvdc),
    .io_tx_dat_ready(io_tx_dat_ready),
    .io_tx_dat_valid(io_tx_dat_valid),
    .io_tx_dat_bits_qos(io_tx_dat_bits_qos),
    .io_tx_dat_bits_tgtID(io_tx_dat_bits_tgtID),
    .io_tx_dat_bits_srcID(io_tx_dat_bits_srcID),
    .io_tx_dat_bits_txnID(io_tx_dat_bits_txnID),
    .io_tx_dat_bits_homeNID(io_tx_dat_bits_homeNID),
    .io_tx_dat_bits_opcode(io_tx_dat_bits_opcode),
    .io_tx_dat_bits_respErr(io_tx_dat_bits_respErr),
    .io_tx_dat_bits_resp(io_tx_dat_bits_resp),
    .io_tx_dat_bits_dataSource(io_tx_dat_bits_dataSource),
    .io_tx_dat_bits_cBusy(io_tx_dat_bits_cBusy),
    .io_tx_dat_bits_dbID(io_tx_dat_bits_dbID),
    .io_tx_dat_bits_ccID(io_tx_dat_bits_ccID),
    .io_tx_dat_bits_dataID(io_tx_dat_bits_dataID),
    .io_tx_dat_bits_tagOp(io_tx_dat_bits_tagOp),
    .io_tx_dat_bits_tag(io_tx_dat_bits_tag),
    .io_tx_dat_bits_tu(io_tx_dat_bits_tu),
    .io_tx_dat_bits_traceTag(io_tx_dat_bits_traceTag),
    .io_tx_dat_bits_rsvdc(io_tx_dat_bits_rsvdc),
    .io_tx_dat_bits_be(io_tx_dat_bits_be),
    .io_tx_dat_bits_data(io_tx_dat_bits_data),
    .io_tx_dat_bits_dataCheck(io_tx_dat_bits_dataCheck),
    .io_tx_dat_bits_poison(io_tx_dat_bits_poison),
    .io_rx_rsp_ready(io_rx_rsp_ready),
    .io_rx_rsp_valid(io_rx_rsp_valid),
    .io_rx_rsp_bits_qos(io_rx_rsp_bits_qos),
    .io_rx_rsp_bits_tgtID(io_rx_rsp_bits_tgtID),
    .io_rx_rsp_bits_srcID(io_rx_rsp_bits_srcID),
    .io_rx_rsp_bits_txnID(io_rx_rsp_bits_txnID),
    .io_rx_rsp_bits_opcode(io_rx_rsp_bits_opcode),
    .io_rx_rsp_bits_respErr(io_rx_rsp_bits_respErr),
    .io_rx_rsp_bits_resp(io_rx_rsp_bits_resp),
    .io_rx_rsp_bits_fwdState(io_rx_rsp_bits_fwdState),
    .io_rx_rsp_bits_cBusy(io_rx_rsp_bits_cBusy),
    .io_rx_rsp_bits_dbID(io_rx_rsp_bits_dbID),
    .io_rx_rsp_bits_pCrdType(io_rx_rsp_bits_pCrdType),
    .io_rx_rsp_bits_tagOp(io_rx_rsp_bits_tagOp),
    .io_rx_rsp_bits_traceTag(io_rx_rsp_bits_traceTag),
    .io_rx_dat_ready(io_rx_dat_ready),
    .io_rx_dat_valid(io_rx_dat_valid),
    .io_rx_dat_bits_qos(io_rx_dat_bits_qos),
    .io_rx_dat_bits_tgtID(io_rx_dat_bits_tgtID),
    .io_rx_dat_bits_srcID(io_rx_dat_bits_srcID),
    .io_rx_dat_bits_txnID(io_rx_dat_bits_txnID),
    .io_rx_dat_bits_homeNID(io_rx_dat_bits_homeNID),
    .io_rx_dat_bits_opcode(io_rx_dat_bits_opcode),
    .io_rx_dat_bits_respErr(io_rx_dat_bits_respErr),
    .io_rx_dat_bits_resp(io_rx_dat_bits_resp),
    .io_rx_dat_bits_dataSource(io_rx_dat_bits_dataSource),
    .io_rx_dat_bits_cBusy(io_rx_dat_bits_cBusy),
    .io_rx_dat_bits_dbID(io_rx_dat_bits_dbID),
    .io_rx_dat_bits_ccID(io_rx_dat_bits_ccID),
    .io_rx_dat_bits_dataID(io_rx_dat_bits_dataID),
    .io_rx_dat_bits_tagOp(io_rx_dat_bits_tagOp),
    .io_rx_dat_bits_tag(io_rx_dat_bits_tag),
    .io_rx_dat_bits_tu(io_rx_dat_bits_tu),
    .io_rx_dat_bits_traceTag(io_rx_dat_bits_traceTag),
    .io_rx_dat_bits_rsvdc(io_rx_dat_bits_rsvdc),
    .io_rx_dat_bits_be(io_rx_dat_bits_be),
    .io_rx_dat_bits_data(io_rx_dat_bits_data),
    .io_rx_dat_bits_dataCheck(io_rx_dat_bits_dataCheck),
    .io_rx_dat_bits_poison(io_rx_dat_bits_poison),
    .io_pCrd_0_query_valid(io_pCrd_0_query_valid),
    .io_pCrd_0_query_bits_pCrdType(io_pCrd_0_query_bits_pCrdType),
    .io_pCrd_0_query_bits_srcID(io_pCrd_0_query_bits_srcID),
    .io_pCrd_0_grant(io_pCrd_0_grant),
    .io_pCrd_1_query_valid(io_pCrd_1_query_valid),
    .io_pCrd_1_query_bits_pCrdType(io_pCrd_1_query_bits_pCrdType),
    .io_pCrd_1_query_bits_srcID(io_pCrd_1_query_bits_srcID),
    .io_pCrd_1_grant(io_pCrd_1_grant),
    .io_pCrd_2_query_valid(io_pCrd_2_query_valid),
    .io_pCrd_2_query_bits_pCrdType(io_pCrd_2_query_bits_pCrdType),
    .io_pCrd_2_query_bits_srcID(io_pCrd_2_query_bits_srcID),
    .io_pCrd_2_grant(io_pCrd_2_grant),
    .io_pCrd_3_query_valid(io_pCrd_3_query_valid),
    .io_pCrd_3_query_bits_pCrdType(io_pCrd_3_query_bits_pCrdType),
    .io_pCrd_3_query_bits_srcID(io_pCrd_3_query_bits_srcID),
    .io_pCrd_3_grant(io_pCrd_3_grant),
    .io_pCrd_4_query_valid(io_pCrd_4_query_valid),
    .io_pCrd_4_query_bits_pCrdType(io_pCrd_4_query_bits_pCrdType),
    .io_pCrd_4_query_bits_srcID(io_pCrd_4_query_bits_srcID),
    .io_pCrd_4_grant(io_pCrd_4_grant),
    .io_pCrd_5_query_valid(io_pCrd_5_query_valid),
    .io_pCrd_5_query_bits_pCrdType(io_pCrd_5_query_bits_pCrdType),
    .io_pCrd_5_query_bits_srcID(io_pCrd_5_query_bits_srcID),
    .io_pCrd_5_grant(io_pCrd_5_grant),
    .io_pCrd_6_query_valid(io_pCrd_6_query_valid),
    .io_pCrd_6_query_bits_pCrdType(io_pCrd_6_query_bits_pCrdType),
    .io_pCrd_6_query_bits_srcID(io_pCrd_6_query_bits_srcID),
    .io_pCrd_6_grant(io_pCrd_6_grant),
    .io_pCrd_7_query_valid(io_pCrd_7_query_valid),
    .io_pCrd_7_query_bits_pCrdType(io_pCrd_7_query_bits_pCrdType),
    .io_pCrd_7_query_bits_srcID(io_pCrd_7_query_bits_srcID),
    .io_pCrd_7_grant(io_pCrd_7_grant)
  );
endmodule
