// 自动生成:scripts/gen_xstop.py —— 勿手改(顶层 glue 为从 Scala 意图的可读重写)

// 可读核端口表(与 golden XSTop 同名扁平端口,供 FM/ST 对接)。
// clock/reset 不在本层端口里:XSTop 用 io_clock/io_reset(功能端口),核里照列。
  input nmi_0_0,
  input nmi_0_1,
  input peripheral_awready,
  output peripheral_awvalid,
  output [1:0] peripheral_awid,
  output [30:0] peripheral_awaddr,
  output [7:0] peripheral_awlen,
  output [2:0] peripheral_awsize,
  output [1:0] peripheral_awburst,
  output peripheral_awlock,
  output [3:0] peripheral_awcache,
  output [2:0] peripheral_awprot,
  output [3:0] peripheral_awqos,
  input peripheral_wready,
  output peripheral_wvalid,
  output [63:0] peripheral_wdata,
  output [7:0] peripheral_wstrb,
  output peripheral_wlast,
  output peripheral_bready,
  input peripheral_bvalid,
  input [1:0] peripheral_bid,
  input [1:0] peripheral_bresp,
  input peripheral_arready,
  output peripheral_arvalid,
  output [1:0] peripheral_arid,
  output [30:0] peripheral_araddr,
  output [7:0] peripheral_arlen,
  output [2:0] peripheral_arsize,
  output [1:0] peripheral_arburst,
  output peripheral_arlock,
  output [3:0] peripheral_arcache,
  output [2:0] peripheral_arprot,
  output [3:0] peripheral_arqos,
  output peripheral_rready,
  input peripheral_rvalid,
  input [1:0] peripheral_rid,
  input [63:0] peripheral_rdata,
  input [1:0] peripheral_rresp,
  input peripheral_rlast,
  input memory_awready,
  output memory_awvalid,
  output [13:0] memory_awid,
  output [47:0] memory_awaddr,
  output [7:0] memory_awlen,
  output [2:0] memory_awsize,
  output [1:0] memory_awburst,
  output memory_awlock,
  output [3:0] memory_awcache,
  output [2:0] memory_awprot,
  output [3:0] memory_awqos,
  input memory_wready,
  output memory_wvalid,
  output [255:0] memory_wdata,
  output [31:0] memory_wstrb,
  output memory_wlast,
  output memory_bready,
  input memory_bvalid,
  input [13:0] memory_bid,
  input [1:0] memory_bresp,
  input memory_arready,
  output memory_arvalid,
  output [13:0] memory_arid,
  output [47:0] memory_araddr,
  output [7:0] memory_arlen,
  output [2:0] memory_arsize,
  output [1:0] memory_arburst,
  output memory_arlock,
  output [3:0] memory_arcache,
  output [2:0] memory_arprot,
  output [3:0] memory_arqos,
  output memory_rready,
  input memory_rvalid,
  input [13:0] memory_rid,
  input [255:0] memory_rdata,
  input [1:0] memory_rresp,
  input memory_rlast,
  input io_clock,
  input io_reset,
  input [15:0] io_sram_config,
  input [63:0] io_extIntrs,
  input io_pll0_lock,
  output [31:0] io_pll0_ctrl_0,
  output [31:0] io_pll0_ctrl_1,
  output [31:0] io_pll0_ctrl_2,
  output [31:0] io_pll0_ctrl_3,
  output [31:0] io_pll0_ctrl_4,
  output [31:0] io_pll0_ctrl_5,
  input io_systemjtag_jtag_TCK,
  input io_systemjtag_jtag_TMS,
  input io_systemjtag_jtag_TDI,
  output io_systemjtag_jtag_TDO_data,
  output io_systemjtag_jtag_TDO_driven,
  input io_systemjtag_reset,
  input [10:0] io_systemjtag_mfr_id,
  input [15:0] io_systemjtag_part_number,
  input [3:0] io_systemjtag_version,
  output io_debug_reset,
  input io_rtc_clock,
  input io_cacheable_check_req_0_valid,
  input [47:0] io_cacheable_check_req_0_bits_addr,
  input [1:0] io_cacheable_check_req_0_bits_size,
  input [2:0] io_cacheable_check_req_0_bits_cmd,
  input io_cacheable_check_req_1_valid,
  input [47:0] io_cacheable_check_req_1_bits_addr,
  input [1:0] io_cacheable_check_req_1_bits_size,
  input [2:0] io_cacheable_check_req_1_bits_cmd,
  output io_cacheable_check_resp_0_ld,
  output io_cacheable_check_resp_0_st,
  output io_cacheable_check_resp_0_instr,
  output io_cacheable_check_resp_0_mmio,
  output io_cacheable_check_resp_0_atomic,
  output io_cacheable_check_resp_1_ld,
  output io_cacheable_check_resp_1_st,
  output io_cacheable_check_resp_1_instr,
  output io_cacheable_check_resp_1_mmio,
  output io_cacheable_check_resp_1_atomic,
  output io_riscv_halt_0,
  output io_riscv_critical_error_0,
  input [47:0] io_riscv_rst_vec_0,
  input io_traceCoreInterface_0_fromEncoder_enable,
  input io_traceCoreInterface_0_fromEncoder_stall,
  output [63:0] io_traceCoreInterface_0_toEncoder_cause,
  output [49:0] io_traceCoreInterface_0_toEncoder_tval,
  output [2:0] io_traceCoreInterface_0_toEncoder_priv,
  output [149:0] io_traceCoreInterface_0_toEncoder_iaddr,
  output [11:0] io_traceCoreInterface_0_toEncoder_itype,
  output [20:0] io_traceCoreInterface_0_toEncoder_iretire,
  output [2:0] io_traceCoreInterface_0_toEncoder_ilastsize
