// 自动生成:scripts/gen_xstop.py —— 勿手改(顶层 glue 为从 Scala 意图的可读重写)

// 子模块(golden 黑盒)输出/互联网声明,宽度从 golden wire 声明收割。
// 由 xstop_inst.svh 绑定子模块输出引脚,互联直连 / glue / outassign 消费。
// (CHI 多 die 路由 glue 的具名 wire 单列在 xstop_glue.svh,不在此声明。)

  logic [48:0] _chi_llcBridge_opt_auto_axi4_out_ar_bits_addr;
  logic [1:0] _chi_llcBridge_opt_auto_axi4_out_ar_bits_burst;
  logic [5:0] _chi_llcBridge_opt_auto_axi4_out_ar_bits_id;
  logic [7:0] _chi_llcBridge_opt_auto_axi4_out_ar_bits_len;
  logic [3:0] _chi_llcBridge_opt_auto_axi4_out_ar_bits_qos;
  logic [2:0] _chi_llcBridge_opt_auto_axi4_out_ar_bits_size;
  logic _chi_llcBridge_opt_auto_axi4_out_ar_valid;
  logic [48:0] _chi_llcBridge_opt_auto_axi4_out_aw_bits_addr;
  logic [1:0] _chi_llcBridge_opt_auto_axi4_out_aw_bits_burst;
  logic [5:0] _chi_llcBridge_opt_auto_axi4_out_aw_bits_id;
  logic [7:0] _chi_llcBridge_opt_auto_axi4_out_aw_bits_len;
  logic [3:0] _chi_llcBridge_opt_auto_axi4_out_aw_bits_qos;
  logic [2:0] _chi_llcBridge_opt_auto_axi4_out_aw_bits_size;
  logic _chi_llcBridge_opt_auto_axi4_out_aw_valid;
  logic [255:0] _chi_llcBridge_opt_auto_axi4_out_w_bits_data;
  logic _chi_llcBridge_opt_auto_axi4_out_w_bits_last;
  logic [31:0] _chi_llcBridge_opt_auto_axi4_out_w_bits_strb;
  logic _chi_llcBridge_opt_auto_axi4_out_w_valid;
  logic [421:0] _chi_llcBridge_opt_io_chi_rx_dat_flit;
  logic _chi_llcBridge_opt_io_chi_rx_dat_flitpend;
  logic _chi_llcBridge_opt_io_chi_rx_dat_flitv;
  logic _chi_llcBridge_opt_io_chi_rx_linkactivereq;
  logic [72:0] _chi_llcBridge_opt_io_chi_rx_rsp_flit;
  logic _chi_llcBridge_opt_io_chi_rx_rsp_flitpend;
  logic _chi_llcBridge_opt_io_chi_rx_rsp_flitv;
  logic _chi_llcBridge_opt_io_chi_rxsactive;
  logic _chi_llcBridge_opt_io_chi_tx_dat_lcrdv;
  logic _chi_llcBridge_opt_io_chi_tx_linkactiveack;
  logic _chi_llcBridge_opt_io_chi_tx_req_lcrdv;
  logic [48:0] _chi_mmioBridge_opt_auto_axi4_out_ar_bits_addr;
  logic [1:0] _chi_mmioBridge_opt_auto_axi4_out_ar_bits_burst;
  logic [3:0] _chi_mmioBridge_opt_auto_axi4_out_ar_bits_cache;
  logic [4:0] _chi_mmioBridge_opt_auto_axi4_out_ar_bits_id;
  logic [7:0] _chi_mmioBridge_opt_auto_axi4_out_ar_bits_len;
  logic [3:0] _chi_mmioBridge_opt_auto_axi4_out_ar_bits_qos;
  logic [2:0] _chi_mmioBridge_opt_auto_axi4_out_ar_bits_size;
  logic _chi_mmioBridge_opt_auto_axi4_out_ar_valid;
  logic [48:0] _chi_mmioBridge_opt_auto_axi4_out_aw_bits_addr;
  logic [1:0] _chi_mmioBridge_opt_auto_axi4_out_aw_bits_burst;
  logic [3:0] _chi_mmioBridge_opt_auto_axi4_out_aw_bits_cache;
  logic [4:0] _chi_mmioBridge_opt_auto_axi4_out_aw_bits_id;
  logic [7:0] _chi_mmioBridge_opt_auto_axi4_out_aw_bits_len;
  logic [3:0] _chi_mmioBridge_opt_auto_axi4_out_aw_bits_qos;
  logic [2:0] _chi_mmioBridge_opt_auto_axi4_out_aw_bits_size;
  logic _chi_mmioBridge_opt_auto_axi4_out_aw_valid;
  logic [255:0] _chi_mmioBridge_opt_auto_axi4_out_w_bits_data;
  logic _chi_mmioBridge_opt_auto_axi4_out_w_bits_last;
  logic [31:0] _chi_mmioBridge_opt_auto_axi4_out_w_bits_strb;
  logic _chi_mmioBridge_opt_auto_axi4_out_w_valid;
  logic [421:0] _chi_mmioBridge_opt_io_chi_rx_dat_flit;
  logic _chi_mmioBridge_opt_io_chi_rx_dat_flitpend;
  logic _chi_mmioBridge_opt_io_chi_rx_dat_flitv;
  logic _chi_mmioBridge_opt_io_chi_rx_linkactivereq;
  logic [72:0] _chi_mmioBridge_opt_io_chi_rx_rsp_flit;
  logic _chi_mmioBridge_opt_io_chi_rx_rsp_flitpend;
  logic _chi_mmioBridge_opt_io_chi_rx_rsp_flitv;
  logic _chi_mmioBridge_opt_io_chi_rxsactive;
  logic _chi_mmioBridge_opt_io_chi_tx_dat_lcrdv;
  logic _chi_mmioBridge_opt_io_chi_tx_linkactiveack;
  logic _chi_mmioBridge_opt_io_chi_tx_req_lcrdv;
  logic _chi_openllc_opt_io_debugTopDown_addrMatch_0;
  logic _chi_openllc_opt_io_l3Miss;
  logic [421:0] _chi_openllc_opt_io_rn_0_rx_dat_flit;
  logic _chi_openllc_opt_io_rn_0_rx_dat_flitpend;
  logic _chi_openllc_opt_io_rn_0_rx_dat_flitv;
  logic _chi_openllc_opt_io_rn_0_rx_linkactivereq;
  logic [72:0] _chi_openllc_opt_io_rn_0_rx_rsp_flit;
  logic _chi_openllc_opt_io_rn_0_rx_rsp_flitpend;
  logic _chi_openllc_opt_io_rn_0_rx_rsp_flitv;
  logic [114:0] _chi_openllc_opt_io_rn_0_rx_snp_flit;
  logic _chi_openllc_opt_io_rn_0_rx_snp_flitpend;
  logic _chi_openllc_opt_io_rn_0_rx_snp_flitv;
  logic _chi_openllc_opt_io_rn_0_rxsactive;
  logic _chi_openllc_opt_io_rn_0_syscoack;
  logic _chi_openllc_opt_io_rn_0_tx_dat_lcrdv;
  logic _chi_openllc_opt_io_rn_0_tx_linkactiveack;
  logic _chi_openllc_opt_io_rn_0_tx_req_lcrdv;
  logic _chi_openllc_opt_io_rn_0_tx_rsp_lcrdv;
  logic _chi_openllc_opt_io_sn_rx_dat_lcrdv;
  logic _chi_openllc_opt_io_sn_rx_linkactiveack;
  logic _chi_openllc_opt_io_sn_rx_rsp_lcrdv;
  logic [421:0] _chi_openllc_opt_io_sn_tx_dat_flit;
  logic _chi_openllc_opt_io_sn_tx_dat_flitpend;
  logic _chi_openllc_opt_io_sn_tx_dat_flitv;
  logic _chi_openllc_opt_io_sn_tx_linkactivereq;
  logic [161:0] _chi_openllc_opt_io_sn_tx_req_flit;
  logic _chi_openllc_opt_io_sn_tx_req_flitpend;
  logic _chi_openllc_opt_io_sn_tx_req_flitv;
  logic _chi_openllc_opt_io_sn_txsactive;
  logic _core_with_l2_auto_l2top_inner_beu_int_out_0;
  logic _core_with_l2_io_chi_rx_dat_lcrdv;
  logic _core_with_l2_io_chi_rx_linkactiveack;
  logic _core_with_l2_io_chi_rx_rsp_lcrdv;
  logic _core_with_l2_io_chi_rx_snp_lcrdv;
  logic _core_with_l2_io_chi_syscoreq;
  logic [421:0] _core_with_l2_io_chi_tx_dat_flit;
  logic _core_with_l2_io_chi_tx_dat_flitpend;
  logic _core_with_l2_io_chi_tx_dat_flitv;
  logic _core_with_l2_io_chi_tx_linkactivereq;
  logic [161:0] _core_with_l2_io_chi_tx_req_flit;
  logic _core_with_l2_io_chi_tx_req_flitpend;
  logic _core_with_l2_io_chi_tx_req_flitv;
  logic [72:0] _core_with_l2_io_chi_tx_rsp_flit;
  logic _core_with_l2_io_chi_tx_rsp_flitpend;
  logic _core_with_l2_io_chi_tx_rsp_flitv;
  logic _core_with_l2_io_chi_txsactive;
  logic [47:0] _core_with_l2_io_debugTopDown_robHeadPaddr_bits;
  logic _core_with_l2_io_debugTopDown_robHeadPaddr_valid;
  logic _core_with_l2_io_hartIsInReset;
  logic [49:0] _core_with_l2_io_traceCoreInterface_toEncoder_groups_0_bits_iaddr;
  logic _core_with_l2_io_traceCoreInterface_toEncoder_groups_0_bits_ilastsize;
  logic [6:0] _core_with_l2_io_traceCoreInterface_toEncoder_groups_0_bits_iretire;
  logic [3:0] _core_with_l2_io_traceCoreInterface_toEncoder_groups_0_bits_itype;
  logic [49:0] _core_with_l2_io_traceCoreInterface_toEncoder_groups_1_bits_iaddr;
  logic _core_with_l2_io_traceCoreInterface_toEncoder_groups_1_bits_ilastsize;
  logic [6:0] _core_with_l2_io_traceCoreInterface_toEncoder_groups_1_bits_iretire;
  logic [3:0] _core_with_l2_io_traceCoreInterface_toEncoder_groups_1_bits_itype;
  logic [49:0] _core_with_l2_io_traceCoreInterface_toEncoder_groups_2_bits_iaddr;
  logic _core_with_l2_io_traceCoreInterface_toEncoder_groups_2_bits_ilastsize;
  logic [6:0] _core_with_l2_io_traceCoreInterface_toEncoder_groups_2_bits_iretire;
  logic [3:0] _core_with_l2_io_traceCoreInterface_toEncoder_groups_2_bits_itype;
  logic _intBuffer_auto_out_0;
  logic _jtag_reset_sync_resetSync_o_reset;
  logic [31:0] _linkMonitor_1_io_in_rx_dat_bits_be;
  logic [2:0] _linkMonitor_1_io_in_rx_dat_bits_cBusy;
  logic [1:0] _linkMonitor_1_io_in_rx_dat_bits_ccID;
  logic [255:0] _linkMonitor_1_io_in_rx_dat_bits_data;
  logic [31:0] _linkMonitor_1_io_in_rx_dat_bits_dataCheck;
  logic [1:0] _linkMonitor_1_io_in_rx_dat_bits_dataID;
  logic [3:0] _linkMonitor_1_io_in_rx_dat_bits_dataSource;
  logic [11:0] _linkMonitor_1_io_in_rx_dat_bits_dbID;
  logic [10:0] _linkMonitor_1_io_in_rx_dat_bits_homeNID;
  logic [3:0] _linkMonitor_1_io_in_rx_dat_bits_opcode;
  logic [3:0] _linkMonitor_1_io_in_rx_dat_bits_poison;
  logic [3:0] _linkMonitor_1_io_in_rx_dat_bits_qos;
  logic [2:0] _linkMonitor_1_io_in_rx_dat_bits_resp;
  logic [1:0] _linkMonitor_1_io_in_rx_dat_bits_respErr;
  logic [3:0] _linkMonitor_1_io_in_rx_dat_bits_rsvdc;
  logic [10:0] _linkMonitor_1_io_in_rx_dat_bits_srcID;
  logic [7:0] _linkMonitor_1_io_in_rx_dat_bits_tag;
  logic [1:0] _linkMonitor_1_io_in_rx_dat_bits_tagOp;
  logic [10:0] _linkMonitor_1_io_in_rx_dat_bits_tgtID;
  logic _linkMonitor_1_io_in_rx_dat_bits_traceTag;
  logic [1:0] _linkMonitor_1_io_in_rx_dat_bits_tu;
  logic [11:0] _linkMonitor_1_io_in_rx_dat_bits_txnID;
  logic _linkMonitor_1_io_in_rx_dat_valid;
  logic [2:0] _linkMonitor_1_io_in_rx_rsp_bits_cBusy;
  logic [11:0] _linkMonitor_1_io_in_rx_rsp_bits_dbID;
  logic [2:0] _linkMonitor_1_io_in_rx_rsp_bits_fwdState;
  logic [4:0] _linkMonitor_1_io_in_rx_rsp_bits_opcode;
  logic [3:0] _linkMonitor_1_io_in_rx_rsp_bits_pCrdType;
  logic [3:0] _linkMonitor_1_io_in_rx_rsp_bits_qos;
  logic [2:0] _linkMonitor_1_io_in_rx_rsp_bits_resp;
  logic [1:0] _linkMonitor_1_io_in_rx_rsp_bits_respErr;
  logic [10:0] _linkMonitor_1_io_in_rx_rsp_bits_srcID;
  logic [1:0] _linkMonitor_1_io_in_rx_rsp_bits_tagOp;
  logic [10:0] _linkMonitor_1_io_in_rx_rsp_bits_tgtID;
  logic _linkMonitor_1_io_in_rx_rsp_bits_traceTag;
  logic [11:0] _linkMonitor_1_io_in_rx_rsp_bits_txnID;
  logic _linkMonitor_1_io_in_rx_rsp_valid;
  logic [44:0] _linkMonitor_1_io_in_rx_snp_bits_addr;
  logic _linkMonitor_1_io_in_rx_snp_bits_doNotGoToSD;
  logic [10:0] _linkMonitor_1_io_in_rx_snp_bits_fwdNID;
  logic [11:0] _linkMonitor_1_io_in_rx_snp_bits_fwdTxnID;
  logic _linkMonitor_1_io_in_rx_snp_bits_mpam_mpamNS;
  logic [8:0] _linkMonitor_1_io_in_rx_snp_bits_mpam_partID;
  logic _linkMonitor_1_io_in_rx_snp_bits_mpam_perfMonGroup;
  logic _linkMonitor_1_io_in_rx_snp_bits_ns;
  logic [4:0] _linkMonitor_1_io_in_rx_snp_bits_opcode;
  logic [3:0] _linkMonitor_1_io_in_rx_snp_bits_qos;
  logic _linkMonitor_1_io_in_rx_snp_bits_retToSrc;
  logic [10:0] _linkMonitor_1_io_in_rx_snp_bits_srcID;
  logic _linkMonitor_1_io_in_rx_snp_bits_traceTag;
  logic [11:0] _linkMonitor_1_io_in_rx_snp_bits_txnID;
  logic _linkMonitor_1_io_in_rx_snp_valid;
  logic _linkMonitor_1_io_in_tx_dat_ready;
  logic _linkMonitor_1_io_in_tx_req_ready;
  logic _linkMonitor_1_io_in_tx_rsp_ready;
  logic _linkMonitor_1_io_out_rx_dat_lcrdv;
  logic _linkMonitor_1_io_out_rx_linkactiveack;
  logic _linkMonitor_1_io_out_rx_rsp_lcrdv;
  logic _linkMonitor_1_io_out_rx_snp_lcrdv;
  logic _linkMonitor_1_io_out_syscoreq;
  logic [421:0] _linkMonitor_1_io_out_tx_dat_flit;
  logic _linkMonitor_1_io_out_tx_dat_flitpend;
  logic _linkMonitor_1_io_out_tx_dat_flitv;
  logic _linkMonitor_1_io_out_tx_linkactivereq;
  logic [161:0] _linkMonitor_1_io_out_tx_req_flit;
  logic _linkMonitor_1_io_out_tx_req_flitpend;
  logic _linkMonitor_1_io_out_tx_req_flitv;
  logic [72:0] _linkMonitor_1_io_out_tx_rsp_flit;
  logic _linkMonitor_1_io_out_tx_rsp_flitpend;
  logic _linkMonitor_1_io_out_tx_rsp_flitv;
  logic _linkMonitor_1_io_out_txsactive;
  logic [31:0] _linkMonitor_2_io_in_rx_dat_bits_be;
  logic [2:0] _linkMonitor_2_io_in_rx_dat_bits_cBusy;
  logic [1:0] _linkMonitor_2_io_in_rx_dat_bits_ccID;
  logic [255:0] _linkMonitor_2_io_in_rx_dat_bits_data;
  logic [31:0] _linkMonitor_2_io_in_rx_dat_bits_dataCheck;
  logic [1:0] _linkMonitor_2_io_in_rx_dat_bits_dataID;
  logic [3:0] _linkMonitor_2_io_in_rx_dat_bits_dataSource;
  logic [11:0] _linkMonitor_2_io_in_rx_dat_bits_dbID;
  logic [10:0] _linkMonitor_2_io_in_rx_dat_bits_homeNID;
  logic [3:0] _linkMonitor_2_io_in_rx_dat_bits_opcode;
  logic [3:0] _linkMonitor_2_io_in_rx_dat_bits_poison;
  logic [3:0] _linkMonitor_2_io_in_rx_dat_bits_qos;
  logic [2:0] _linkMonitor_2_io_in_rx_dat_bits_resp;
  logic [1:0] _linkMonitor_2_io_in_rx_dat_bits_respErr;
  logic [3:0] _linkMonitor_2_io_in_rx_dat_bits_rsvdc;
  logic [10:0] _linkMonitor_2_io_in_rx_dat_bits_srcID;
  logic [7:0] _linkMonitor_2_io_in_rx_dat_bits_tag;
  logic [1:0] _linkMonitor_2_io_in_rx_dat_bits_tagOp;
  logic [10:0] _linkMonitor_2_io_in_rx_dat_bits_tgtID;
  logic _linkMonitor_2_io_in_rx_dat_bits_traceTag;
  logic [1:0] _linkMonitor_2_io_in_rx_dat_bits_tu;
  logic [11:0] _linkMonitor_2_io_in_rx_dat_bits_txnID;
  logic _linkMonitor_2_io_in_rx_dat_valid;
  logic [2:0] _linkMonitor_2_io_in_rx_rsp_bits_cBusy;
  logic [11:0] _linkMonitor_2_io_in_rx_rsp_bits_dbID;
  logic [2:0] _linkMonitor_2_io_in_rx_rsp_bits_fwdState;
  logic [4:0] _linkMonitor_2_io_in_rx_rsp_bits_opcode;
  logic [3:0] _linkMonitor_2_io_in_rx_rsp_bits_pCrdType;
  logic [3:0] _linkMonitor_2_io_in_rx_rsp_bits_qos;
  logic [2:0] _linkMonitor_2_io_in_rx_rsp_bits_resp;
  logic [1:0] _linkMonitor_2_io_in_rx_rsp_bits_respErr;
  logic [10:0] _linkMonitor_2_io_in_rx_rsp_bits_srcID;
  logic [1:0] _linkMonitor_2_io_in_rx_rsp_bits_tagOp;
  logic [10:0] _linkMonitor_2_io_in_rx_rsp_bits_tgtID;
  logic _linkMonitor_2_io_in_rx_rsp_bits_traceTag;
  logic [11:0] _linkMonitor_2_io_in_rx_rsp_bits_txnID;
  logic _linkMonitor_2_io_in_rx_rsp_valid;
  logic [44:0] _linkMonitor_2_io_in_rx_snp_bits_addr;
  logic _linkMonitor_2_io_in_rx_snp_bits_doNotGoToSD;
  logic [10:0] _linkMonitor_2_io_in_rx_snp_bits_fwdNID;
  logic [11:0] _linkMonitor_2_io_in_rx_snp_bits_fwdTxnID;
  logic _linkMonitor_2_io_in_rx_snp_bits_mpam_mpamNS;
  logic [8:0] _linkMonitor_2_io_in_rx_snp_bits_mpam_partID;
  logic _linkMonitor_2_io_in_rx_snp_bits_mpam_perfMonGroup;
  logic _linkMonitor_2_io_in_rx_snp_bits_ns;
  logic [4:0] _linkMonitor_2_io_in_rx_snp_bits_opcode;
  logic [3:0] _linkMonitor_2_io_in_rx_snp_bits_qos;
  logic _linkMonitor_2_io_in_rx_snp_bits_retToSrc;
  logic [10:0] _linkMonitor_2_io_in_rx_snp_bits_srcID;
  logic _linkMonitor_2_io_in_rx_snp_bits_traceTag;
  logic [11:0] _linkMonitor_2_io_in_rx_snp_bits_txnID;
  logic _linkMonitor_2_io_in_rx_snp_valid;
  logic _linkMonitor_2_io_in_tx_dat_ready;
  logic _linkMonitor_2_io_in_tx_req_ready;
  logic _linkMonitor_2_io_in_tx_rsp_ready;
  logic _linkMonitor_2_io_out_rx_dat_lcrdv;
  logic _linkMonitor_2_io_out_rx_linkactiveack;
  logic _linkMonitor_2_io_out_rx_rsp_lcrdv;
  logic _linkMonitor_2_io_out_rx_snp_lcrdv;
  logic _linkMonitor_2_io_out_syscoreq;
  logic [421:0] _linkMonitor_2_io_out_tx_dat_flit;
  logic _linkMonitor_2_io_out_tx_dat_flitpend;
  logic _linkMonitor_2_io_out_tx_dat_flitv;
  logic _linkMonitor_2_io_out_tx_linkactivereq;
  logic [161:0] _linkMonitor_2_io_out_tx_req_flit;
  logic _linkMonitor_2_io_out_tx_req_flitpend;
  logic _linkMonitor_2_io_out_tx_req_flitv;
  logic [72:0] _linkMonitor_2_io_out_tx_rsp_flit;
  logic _linkMonitor_2_io_out_tx_rsp_flitpend;
  logic _linkMonitor_2_io_out_tx_rsp_flitv;
  logic _linkMonitor_2_io_out_txsactive;
  logic [421:0] _linkMonitor_io_in_rx_dat_flit;
  logic _linkMonitor_io_in_rx_dat_flitpend;
  logic _linkMonitor_io_in_rx_dat_flitv;
  logic _linkMonitor_io_in_rx_linkactivereq;
  logic [72:0] _linkMonitor_io_in_rx_rsp_flit;
  logic _linkMonitor_io_in_rx_rsp_flitpend;
  logic _linkMonitor_io_in_rx_rsp_flitv;
  logic [114:0] _linkMonitor_io_in_rx_snp_flit;
  logic _linkMonitor_io_in_rx_snp_flitpend;
  logic _linkMonitor_io_in_rx_snp_flitv;
  logic _linkMonitor_io_in_rxsactive;
  logic _linkMonitor_io_in_syscoack;
  logic _linkMonitor_io_in_tx_dat_lcrdv;
  logic _linkMonitor_io_in_tx_linkactiveack;
  logic _linkMonitor_io_in_tx_req_lcrdv;
  logic _linkMonitor_io_in_tx_rsp_lcrdv;
  logic _linkMonitor_io_out_rx_dat_ready;
  logic _linkMonitor_io_out_rx_rsp_ready;
  logic _linkMonitor_io_out_rx_snp_ready;
  logic [31:0] _linkMonitor_io_out_tx_dat_bits_be;
  logic [2:0] _linkMonitor_io_out_tx_dat_bits_cBusy;
  logic [1:0] _linkMonitor_io_out_tx_dat_bits_ccID;
  logic [255:0] _linkMonitor_io_out_tx_dat_bits_data;
  logic [31:0] _linkMonitor_io_out_tx_dat_bits_dataCheck;
  logic [1:0] _linkMonitor_io_out_tx_dat_bits_dataID;
  logic [3:0] _linkMonitor_io_out_tx_dat_bits_dataSource;
  logic [11:0] _linkMonitor_io_out_tx_dat_bits_dbID;
  logic [10:0] _linkMonitor_io_out_tx_dat_bits_homeNID;
  logic [3:0] _linkMonitor_io_out_tx_dat_bits_opcode;
  logic [3:0] _linkMonitor_io_out_tx_dat_bits_poison;
  logic [3:0] _linkMonitor_io_out_tx_dat_bits_qos;
  logic [2:0] _linkMonitor_io_out_tx_dat_bits_resp;
  logic [1:0] _linkMonitor_io_out_tx_dat_bits_respErr;
  logic [3:0] _linkMonitor_io_out_tx_dat_bits_rsvdc;
  logic [10:0] _linkMonitor_io_out_tx_dat_bits_srcID;
  logic [7:0] _linkMonitor_io_out_tx_dat_bits_tag;
  logic [1:0] _linkMonitor_io_out_tx_dat_bits_tagOp;
  logic [10:0] _linkMonitor_io_out_tx_dat_bits_tgtID;
  logic _linkMonitor_io_out_tx_dat_bits_traceTag;
  logic [1:0] _linkMonitor_io_out_tx_dat_bits_tu;
  logic [11:0] _linkMonitor_io_out_tx_dat_bits_txnID;
  logic _linkMonitor_io_out_tx_dat_valid;
  logic [47:0] _linkMonitor_io_out_tx_req_bits_addr;
  logic _linkMonitor_io_out_tx_req_bits_allowRetry;
  logic _linkMonitor_io_out_tx_req_bits_expCompAck;
  logic _linkMonitor_io_out_tx_req_bits_likelyshared;
  logic [7:0] _linkMonitor_io_out_tx_req_bits_lpIDWithPadding;
  logic _linkMonitor_io_out_tx_req_bits_memAttr_allocate;
  logic _linkMonitor_io_out_tx_req_bits_memAttr_cacheable;
  logic _linkMonitor_io_out_tx_req_bits_memAttr_device;
  logic _linkMonitor_io_out_tx_req_bits_memAttr_ewa;
  logic _linkMonitor_io_out_tx_req_bits_mpam_mpamNS;
  logic [8:0] _linkMonitor_io_out_tx_req_bits_mpam_partID;
  logic _linkMonitor_io_out_tx_req_bits_mpam_perfMonGroup;
  logic _linkMonitor_io_out_tx_req_bits_ns;
  logic [6:0] _linkMonitor_io_out_tx_req_bits_opcode;
  logic [1:0] _linkMonitor_io_out_tx_req_bits_order;
  logic [3:0] _linkMonitor_io_out_tx_req_bits_pCrdType;
  logic [3:0] _linkMonitor_io_out_tx_req_bits_qos;
  logic [10:0] _linkMonitor_io_out_tx_req_bits_returnNID;
  logic [11:0] _linkMonitor_io_out_tx_req_bits_returnTxnID;
  logic [3:0] _linkMonitor_io_out_tx_req_bits_rsvdc;
  logic [2:0] _linkMonitor_io_out_tx_req_bits_size;
  logic _linkMonitor_io_out_tx_req_bits_snoopMe;
  logic _linkMonitor_io_out_tx_req_bits_snpAttr;
  logic [10:0] _linkMonitor_io_out_tx_req_bits_srcID;
  logic _linkMonitor_io_out_tx_req_bits_stashNIDValid;
  logic [1:0] _linkMonitor_io_out_tx_req_bits_tagOp;
  logic _linkMonitor_io_out_tx_req_bits_traceTag;
  logic [11:0] _linkMonitor_io_out_tx_req_bits_txnID;
  logic _linkMonitor_io_out_tx_req_valid;
  logic [2:0] _linkMonitor_io_out_tx_rsp_bits_cBusy;
  logic [11:0] _linkMonitor_io_out_tx_rsp_bits_dbID;
  logic [2:0] _linkMonitor_io_out_tx_rsp_bits_fwdState;
  logic [4:0] _linkMonitor_io_out_tx_rsp_bits_opcode;
  logic [3:0] _linkMonitor_io_out_tx_rsp_bits_pCrdType;
  logic [3:0] _linkMonitor_io_out_tx_rsp_bits_qos;
  logic [2:0] _linkMonitor_io_out_tx_rsp_bits_resp;
  logic [1:0] _linkMonitor_io_out_tx_rsp_bits_respErr;
  logic [10:0] _linkMonitor_io_out_tx_rsp_bits_srcID;
  logic [1:0] _linkMonitor_io_out_tx_rsp_bits_tagOp;
  logic [10:0] _linkMonitor_io_out_tx_rsp_bits_tgtID;
  logic _linkMonitor_io_out_tx_rsp_bits_traceTag;
  logic [11:0] _linkMonitor_io_out_tx_rsp_bits_txnID;
  logic _linkMonitor_io_out_tx_rsp_valid;
  logic _llcLogger_io_down_rx_dat_lcrdv;
  logic _llcLogger_io_down_rx_linkactiveack;
  logic _llcLogger_io_down_rx_rsp_lcrdv;
  logic _llcLogger_io_down_rx_snp_lcrdv;
  logic _llcLogger_io_down_syscoreq;
  logic [421:0] _llcLogger_io_down_tx_dat_flit;
  logic _llcLogger_io_down_tx_dat_flitpend;
  logic _llcLogger_io_down_tx_dat_flitv;
  logic _llcLogger_io_down_tx_linkactivereq;
  logic [161:0] _llcLogger_io_down_tx_req_flit;
  logic _llcLogger_io_down_tx_req_flitpend;
  logic _llcLogger_io_down_tx_req_flitv;
  logic [72:0] _llcLogger_io_down_tx_rsp_flit;
  logic _llcLogger_io_down_tx_rsp_flitpend;
  logic _llcLogger_io_down_tx_rsp_flitv;
  logic _llcLogger_io_down_txsactive;
  logic [421:0] _llcLogger_io_up_rx_dat_flit;
  logic _llcLogger_io_up_rx_dat_flitpend;
  logic _llcLogger_io_up_rx_dat_flitv;
  logic _llcLogger_io_up_rx_linkactivereq;
  logic [72:0] _llcLogger_io_up_rx_rsp_flit;
  logic _llcLogger_io_up_rx_rsp_flitpend;
  logic _llcLogger_io_up_rx_rsp_flitv;
  logic [114:0] _llcLogger_io_up_rx_snp_flit;
  logic _llcLogger_io_up_rx_snp_flitpend;
  logic _llcLogger_io_up_rx_snp_flitv;
  logic _llcLogger_io_up_rxsactive;
  logic _llcLogger_io_up_syscoack;
  logic _llcLogger_io_up_tx_dat_lcrdv;
  logic _llcLogger_io_up_tx_linkactiveack;
  logic _llcLogger_io_up_tx_req_lcrdv;
  logic _llcLogger_io_up_tx_rsp_lcrdv;
  logic _memLogger_io_down_rx_dat_lcrdv;
  logic _memLogger_io_down_rx_linkactiveack;
  logic _memLogger_io_down_rx_rsp_lcrdv;
  logic [421:0] _memLogger_io_down_tx_dat_flit;
  logic _memLogger_io_down_tx_dat_flitpend;
  logic _memLogger_io_down_tx_dat_flitv;
  logic _memLogger_io_down_tx_linkactivereq;
  logic [161:0] _memLogger_io_down_tx_req_flit;
  logic _memLogger_io_down_tx_req_flitpend;
  logic _memLogger_io_down_tx_req_flitv;
  logic _memLogger_io_down_txsactive;
  logic [421:0] _memLogger_io_up_rx_dat_flit;
  logic _memLogger_io_up_rx_dat_flitpend;
  logic _memLogger_io_up_rx_dat_flitv;
  logic _memLogger_io_up_rx_linkactivereq;
  logic [72:0] _memLogger_io_up_rx_rsp_flit;
  logic _memLogger_io_up_rx_rsp_flitpend;
  logic _memLogger_io_up_rx_rsp_flitv;
  logic _memLogger_io_up_rxsactive;
  logic _memLogger_io_up_tx_dat_lcrdv;
  logic _memLogger_io_up_tx_linkactiveack;
  logic _memLogger_io_up_tx_req_lcrdv;
  logic _mmioLogger_io_down_rx_dat_lcrdv;
  logic _mmioLogger_io_down_rx_linkactiveack;
  logic _mmioLogger_io_down_rx_rsp_lcrdv;
  logic [421:0] _mmioLogger_io_down_tx_dat_flit;
  logic _mmioLogger_io_down_tx_dat_flitpend;
  logic _mmioLogger_io_down_tx_dat_flitv;
  logic _mmioLogger_io_down_tx_linkactivereq;
  logic [161:0] _mmioLogger_io_down_tx_req_flit;
  logic _mmioLogger_io_down_tx_req_flitpend;
  logic _mmioLogger_io_down_tx_req_flitv;
  logic _mmioLogger_io_down_txsactive;
  logic [421:0] _mmioLogger_io_up_rx_dat_flit;
  logic _mmioLogger_io_up_rx_dat_flitpend;
  logic _mmioLogger_io_up_rx_dat_flitv;
  logic _mmioLogger_io_up_rx_linkactivereq;
  logic [72:0] _mmioLogger_io_up_rx_rsp_flit;
  logic _mmioLogger_io_up_rx_rsp_flitpend;
  logic _mmioLogger_io_up_rx_rsp_flitv;
  logic [114:0] _mmioLogger_io_up_rx_snp_flit;
  logic _mmioLogger_io_up_rx_snp_flitpend;
  logic _mmioLogger_io_up_rx_snp_flitv;
  logic _mmioLogger_io_up_rxsactive;
  logic _mmioLogger_io_up_syscoack;
  logic _mmioLogger_io_up_tx_dat_lcrdv;
  logic _mmioLogger_io_up_tx_linkactiveack;
  logic _mmioLogger_io_up_tx_req_lcrdv;
  logic _mmioLogger_io_up_tx_rsp_lcrdv;
  logic _nocMisc_auto_axi4xbar_in_0_ar_ready;
  logic _nocMisc_auto_axi4xbar_in_0_aw_ready;
  logic [5:0] _nocMisc_auto_axi4xbar_in_0_b_bits_id;
  logic _nocMisc_auto_axi4xbar_in_0_b_valid;
  logic [255:0] _nocMisc_auto_axi4xbar_in_0_r_bits_data;
  logic [5:0] _nocMisc_auto_axi4xbar_in_0_r_bits_id;
  logic _nocMisc_auto_axi4xbar_in_0_r_bits_last;
  logic _nocMisc_auto_axi4xbar_in_0_r_valid;
  logic _nocMisc_auto_axi4xbar_in_0_w_ready;
  logic _nocMisc_auto_axi4xbar_in_1_ar_ready;
  logic _nocMisc_auto_axi4xbar_in_1_aw_ready;
  logic [4:0] _nocMisc_auto_axi4xbar_in_1_b_bits_id;
  logic _nocMisc_auto_axi4xbar_in_1_b_valid;
  logic [255:0] _nocMisc_auto_axi4xbar_in_1_r_bits_data;
  logic [4:0] _nocMisc_auto_axi4xbar_in_1_r_bits_id;
  logic _nocMisc_auto_axi4xbar_in_1_r_bits_last;
  logic _nocMisc_auto_axi4xbar_in_1_r_valid;
  logic _nocMisc_auto_axi4xbar_in_1_w_ready;
  logic _nocMisc_auto_clint_int_out_0;
  logic _nocMisc_auto_clint_int_out_1;
  logic _nocMisc_auto_debugModule_debug_dmOuter_dmOuter_int_out_0;
  logic _nocMisc_auto_plic_int_out_0_0;
  logic _nocMisc_auto_plic_int_out_1_0;
  logic [63:0] _nocMisc_clintTime_bits;
  logic _nocMisc_clintTime_valid;
  logic _nocMisc_debug_module_io_debugIO_dmactive;
  logic _nocMisc_debug_module_io_resetCtrl_hartResetReq_0;
  logic _reset_sync_resetSync_o_reset;
  logic _rxdatArb_io_chosen;
  logic [31:0] _rxdatArb_io_out_bits_be;
  logic [2:0] _rxdatArb_io_out_bits_cBusy;
  logic [1:0] _rxdatArb_io_out_bits_ccID;
  logic [255:0] _rxdatArb_io_out_bits_data;
  logic [31:0] _rxdatArb_io_out_bits_dataCheck;
  logic [1:0] _rxdatArb_io_out_bits_dataID;
  logic [3:0] _rxdatArb_io_out_bits_dataSource;
  logic [11:0] _rxdatArb_io_out_bits_dbID;
  logic [10:0] _rxdatArb_io_out_bits_homeNID;
  logic [3:0] _rxdatArb_io_out_bits_opcode;
  logic [3:0] _rxdatArb_io_out_bits_poison;
  logic [3:0] _rxdatArb_io_out_bits_qos;
  logic [2:0] _rxdatArb_io_out_bits_resp;
  logic [1:0] _rxdatArb_io_out_bits_respErr;
  logic [3:0] _rxdatArb_io_out_bits_rsvdc;
  logic [10:0] _rxdatArb_io_out_bits_srcID;
  logic [7:0] _rxdatArb_io_out_bits_tag;
  logic [1:0] _rxdatArb_io_out_bits_tagOp;
  logic [10:0] _rxdatArb_io_out_bits_tgtID;
  logic _rxdatArb_io_out_bits_traceTag;
  logic [1:0] _rxdatArb_io_out_bits_tu;
  logic [11:0] _rxdatArb_io_out_bits_txnID;
  logic _rxdatArb_io_out_valid;
  logic _rxrspArb_io_chosen;
  logic [2:0] _rxrspArb_io_out_bits_cBusy;
  logic [11:0] _rxrspArb_io_out_bits_dbID;
  logic [2:0] _rxrspArb_io_out_bits_fwdState;
  logic [4:0] _rxrspArb_io_out_bits_opcode;
  logic [3:0] _rxrspArb_io_out_bits_pCrdType;
  logic [3:0] _rxrspArb_io_out_bits_qos;
  logic [2:0] _rxrspArb_io_out_bits_resp;
  logic [1:0] _rxrspArb_io_out_bits_respErr;
  logic [10:0] _rxrspArb_io_out_bits_srcID;
  logic [1:0] _rxrspArb_io_out_bits_tagOp;
  logic [10:0] _rxrspArb_io_out_bits_tgtID;
  logic _rxrspArb_io_out_bits_traceTag;
  logic [11:0] _rxrspArb_io_out_bits_txnID;
  logic _rxrspArb_io_out_valid;
  logic _rxsnpArb_io_chosen;
  logic [44:0] _rxsnpArb_io_out_bits_addr;
  logic _rxsnpArb_io_out_bits_doNotGoToSD;
  logic [10:0] _rxsnpArb_io_out_bits_fwdNID;
  logic [11:0] _rxsnpArb_io_out_bits_fwdTxnID;
  logic _rxsnpArb_io_out_bits_mpam_mpamNS;
  logic [8:0] _rxsnpArb_io_out_bits_mpam_partID;
  logic _rxsnpArb_io_out_bits_mpam_perfMonGroup;
  logic _rxsnpArb_io_out_bits_ns;
  logic [4:0] _rxsnpArb_io_out_bits_opcode;
  logic [3:0] _rxsnpArb_io_out_bits_qos;
  logic _rxsnpArb_io_out_bits_retToSrc;
  logic [10:0] _rxsnpArb_io_out_bits_srcID;
  logic _rxsnpArb_io_out_bits_traceTag;
  logic [11:0] _rxsnpArb_io_out_bits_txnID;
  logic _rxsnpArb_io_out_valid;
