// AUTO-GENERATED by scripts/gen_openncb.py -- do not hand-edit
`timescale 1ns/1ps
module tb;
  int unsigned NCYCLES = 200000;
  int unsigned WARMUP = 16;
  bit clk=0, rst;
  int errors=0, checks=0, cyc=0;
  always #5 clk = ~clk;

  logic auto_axi4_out_aw_ready;
  logic auto_axi4_out_w_ready;
  logic auto_axi4_out_b_valid;
  logic [5:0] auto_axi4_out_b_bits_id;
  logic auto_axi4_out_ar_ready;
  logic auto_axi4_out_r_valid;
  logic [5:0] auto_axi4_out_r_bits_id;
  logic [255:0] auto_axi4_out_r_bits_data;
  logic auto_axi4_out_r_bits_last;
  logic io_chi_txsactive;
  logic io_chi_tx_linkactivereq;
  logic io_chi_tx_req_flitpend;
  logic io_chi_tx_req_flitv;
  logic [161:0] io_chi_tx_req_flit;
  logic io_chi_tx_dat_flitpend;
  logic io_chi_tx_dat_flitv;
  logic [421:0] io_chi_tx_dat_flit;
  logic io_chi_rx_linkactiveack;
  logic io_chi_rx_rsp_lcrdv;
  logic io_chi_rx_dat_lcrdv;

  logic g_auto_axi4_out_aw_valid;
  logic [5:0] g_auto_axi4_out_aw_bits_id;
  logic [48:0] g_auto_axi4_out_aw_bits_addr;
  logic [7:0] g_auto_axi4_out_aw_bits_len;
  logic [2:0] g_auto_axi4_out_aw_bits_size;
  logic [1:0] g_auto_axi4_out_aw_bits_burst;
  logic [3:0] g_auto_axi4_out_aw_bits_qos;
  logic g_auto_axi4_out_w_valid;
  logic [255:0] g_auto_axi4_out_w_bits_data;
  logic [31:0] g_auto_axi4_out_w_bits_strb;
  logic g_auto_axi4_out_w_bits_last;
  logic g_auto_axi4_out_ar_valid;
  logic [5:0] g_auto_axi4_out_ar_bits_id;
  logic [48:0] g_auto_axi4_out_ar_bits_addr;
  logic [7:0] g_auto_axi4_out_ar_bits_len;
  logic [2:0] g_auto_axi4_out_ar_bits_size;
  logic [1:0] g_auto_axi4_out_ar_bits_burst;
  logic [3:0] g_auto_axi4_out_ar_bits_qos;
  logic g_io_chi_rxsactive;
  logic g_io_chi_tx_linkactiveack;
  logic g_io_chi_tx_req_lcrdv;
  logic g_io_chi_tx_dat_lcrdv;
  logic g_io_chi_rx_linkactivereq;
  logic g_io_chi_rx_rsp_flitpend;
  logic g_io_chi_rx_rsp_flitv;
  logic [72:0] g_io_chi_rx_rsp_flit;
  logic g_io_chi_rx_dat_flitpend;
  logic g_io_chi_rx_dat_flitv;
  logic [421:0] g_io_chi_rx_dat_flit;
  logic x_auto_axi4_out_aw_valid;
  logic [5:0] x_auto_axi4_out_aw_bits_id;
  logic [48:0] x_auto_axi4_out_aw_bits_addr;
  logic [7:0] x_auto_axi4_out_aw_bits_len;
  logic [2:0] x_auto_axi4_out_aw_bits_size;
  logic [1:0] x_auto_axi4_out_aw_bits_burst;
  logic [3:0] x_auto_axi4_out_aw_bits_qos;
  logic x_auto_axi4_out_w_valid;
  logic [255:0] x_auto_axi4_out_w_bits_data;
  logic [31:0] x_auto_axi4_out_w_bits_strb;
  logic x_auto_axi4_out_w_bits_last;
  logic x_auto_axi4_out_ar_valid;
  logic [5:0] x_auto_axi4_out_ar_bits_id;
  logic [48:0] x_auto_axi4_out_ar_bits_addr;
  logic [7:0] x_auto_axi4_out_ar_bits_len;
  logic [2:0] x_auto_axi4_out_ar_bits_size;
  logic [1:0] x_auto_axi4_out_ar_bits_burst;
  logic [3:0] x_auto_axi4_out_ar_bits_qos;
  logic x_io_chi_rxsactive;
  logic x_io_chi_tx_linkactiveack;
  logic x_io_chi_tx_req_lcrdv;
  logic x_io_chi_tx_dat_lcrdv;
  logic x_io_chi_rx_linkactivereq;
  logic x_io_chi_rx_rsp_flitpend;
  logic x_io_chi_rx_rsp_flitv;
  logic [72:0] x_io_chi_rx_rsp_flit;
  logic x_io_chi_rx_dat_flitpend;
  logic x_io_chi_rx_dat_flitv;
  logic [421:0] x_io_chi_rx_dat_flit;

  OpenNCB dut_g (
    .clock (clk),
    .reset (rst),
    .auto_axi4_out_aw_ready (auto_axi4_out_aw_ready),
    .auto_axi4_out_aw_valid (g_auto_axi4_out_aw_valid),
    .auto_axi4_out_aw_bits_id (g_auto_axi4_out_aw_bits_id),
    .auto_axi4_out_aw_bits_addr (g_auto_axi4_out_aw_bits_addr),
    .auto_axi4_out_aw_bits_len (g_auto_axi4_out_aw_bits_len),
    .auto_axi4_out_aw_bits_size (g_auto_axi4_out_aw_bits_size),
    .auto_axi4_out_aw_bits_burst (g_auto_axi4_out_aw_bits_burst),
    .auto_axi4_out_aw_bits_qos (g_auto_axi4_out_aw_bits_qos),
    .auto_axi4_out_w_ready (auto_axi4_out_w_ready),
    .auto_axi4_out_w_valid (g_auto_axi4_out_w_valid),
    .auto_axi4_out_w_bits_data (g_auto_axi4_out_w_bits_data),
    .auto_axi4_out_w_bits_strb (g_auto_axi4_out_w_bits_strb),
    .auto_axi4_out_w_bits_last (g_auto_axi4_out_w_bits_last),
    .auto_axi4_out_b_valid (auto_axi4_out_b_valid),
    .auto_axi4_out_b_bits_id (auto_axi4_out_b_bits_id),
    .auto_axi4_out_ar_ready (auto_axi4_out_ar_ready),
    .auto_axi4_out_ar_valid (g_auto_axi4_out_ar_valid),
    .auto_axi4_out_ar_bits_id (g_auto_axi4_out_ar_bits_id),
    .auto_axi4_out_ar_bits_addr (g_auto_axi4_out_ar_bits_addr),
    .auto_axi4_out_ar_bits_len (g_auto_axi4_out_ar_bits_len),
    .auto_axi4_out_ar_bits_size (g_auto_axi4_out_ar_bits_size),
    .auto_axi4_out_ar_bits_burst (g_auto_axi4_out_ar_bits_burst),
    .auto_axi4_out_ar_bits_qos (g_auto_axi4_out_ar_bits_qos),
    .auto_axi4_out_r_valid (auto_axi4_out_r_valid),
    .auto_axi4_out_r_bits_id (auto_axi4_out_r_bits_id),
    .auto_axi4_out_r_bits_data (auto_axi4_out_r_bits_data),
    .auto_axi4_out_r_bits_last (auto_axi4_out_r_bits_last),
    .io_chi_txsactive (io_chi_txsactive),
    .io_chi_rxsactive (g_io_chi_rxsactive),
    .io_chi_tx_linkactivereq (io_chi_tx_linkactivereq),
    .io_chi_tx_linkactiveack (g_io_chi_tx_linkactiveack),
    .io_chi_tx_req_flitpend (io_chi_tx_req_flitpend),
    .io_chi_tx_req_flitv (io_chi_tx_req_flitv),
    .io_chi_tx_req_flit (io_chi_tx_req_flit),
    .io_chi_tx_req_lcrdv (g_io_chi_tx_req_lcrdv),
    .io_chi_tx_dat_flitpend (io_chi_tx_dat_flitpend),
    .io_chi_tx_dat_flitv (io_chi_tx_dat_flitv),
    .io_chi_tx_dat_flit (io_chi_tx_dat_flit),
    .io_chi_tx_dat_lcrdv (g_io_chi_tx_dat_lcrdv),
    .io_chi_rx_linkactivereq (g_io_chi_rx_linkactivereq),
    .io_chi_rx_linkactiveack (io_chi_rx_linkactiveack),
    .io_chi_rx_rsp_flitpend (g_io_chi_rx_rsp_flitpend),
    .io_chi_rx_rsp_flitv (g_io_chi_rx_rsp_flitv),
    .io_chi_rx_rsp_flit (g_io_chi_rx_rsp_flit),
    .io_chi_rx_rsp_lcrdv (io_chi_rx_rsp_lcrdv),
    .io_chi_rx_dat_flitpend (g_io_chi_rx_dat_flitpend),
    .io_chi_rx_dat_flitv (g_io_chi_rx_dat_flitv),
    .io_chi_rx_dat_flit (g_io_chi_rx_dat_flit),
    .io_chi_rx_dat_lcrdv (io_chi_rx_dat_lcrdv)
  );

  OpenNCB_xs dut_x (
    .clock (clk),
    .reset (rst),
    .auto_axi4_out_aw_ready (auto_axi4_out_aw_ready),
    .auto_axi4_out_aw_valid (x_auto_axi4_out_aw_valid),
    .auto_axi4_out_aw_bits_id (x_auto_axi4_out_aw_bits_id),
    .auto_axi4_out_aw_bits_addr (x_auto_axi4_out_aw_bits_addr),
    .auto_axi4_out_aw_bits_len (x_auto_axi4_out_aw_bits_len),
    .auto_axi4_out_aw_bits_size (x_auto_axi4_out_aw_bits_size),
    .auto_axi4_out_aw_bits_burst (x_auto_axi4_out_aw_bits_burst),
    .auto_axi4_out_aw_bits_qos (x_auto_axi4_out_aw_bits_qos),
    .auto_axi4_out_w_ready (auto_axi4_out_w_ready),
    .auto_axi4_out_w_valid (x_auto_axi4_out_w_valid),
    .auto_axi4_out_w_bits_data (x_auto_axi4_out_w_bits_data),
    .auto_axi4_out_w_bits_strb (x_auto_axi4_out_w_bits_strb),
    .auto_axi4_out_w_bits_last (x_auto_axi4_out_w_bits_last),
    .auto_axi4_out_b_valid (auto_axi4_out_b_valid),
    .auto_axi4_out_b_bits_id (auto_axi4_out_b_bits_id),
    .auto_axi4_out_ar_ready (auto_axi4_out_ar_ready),
    .auto_axi4_out_ar_valid (x_auto_axi4_out_ar_valid),
    .auto_axi4_out_ar_bits_id (x_auto_axi4_out_ar_bits_id),
    .auto_axi4_out_ar_bits_addr (x_auto_axi4_out_ar_bits_addr),
    .auto_axi4_out_ar_bits_len (x_auto_axi4_out_ar_bits_len),
    .auto_axi4_out_ar_bits_size (x_auto_axi4_out_ar_bits_size),
    .auto_axi4_out_ar_bits_burst (x_auto_axi4_out_ar_bits_burst),
    .auto_axi4_out_ar_bits_qos (x_auto_axi4_out_ar_bits_qos),
    .auto_axi4_out_r_valid (auto_axi4_out_r_valid),
    .auto_axi4_out_r_bits_id (auto_axi4_out_r_bits_id),
    .auto_axi4_out_r_bits_data (auto_axi4_out_r_bits_data),
    .auto_axi4_out_r_bits_last (auto_axi4_out_r_bits_last),
    .io_chi_txsactive (io_chi_txsactive),
    .io_chi_rxsactive (x_io_chi_rxsactive),
    .io_chi_tx_linkactivereq (io_chi_tx_linkactivereq),
    .io_chi_tx_linkactiveack (x_io_chi_tx_linkactiveack),
    .io_chi_tx_req_flitpend (io_chi_tx_req_flitpend),
    .io_chi_tx_req_flitv (io_chi_tx_req_flitv),
    .io_chi_tx_req_flit (io_chi_tx_req_flit),
    .io_chi_tx_req_lcrdv (x_io_chi_tx_req_lcrdv),
    .io_chi_tx_dat_flitpend (io_chi_tx_dat_flitpend),
    .io_chi_tx_dat_flitv (io_chi_tx_dat_flitv),
    .io_chi_tx_dat_flit (io_chi_tx_dat_flit),
    .io_chi_tx_dat_lcrdv (x_io_chi_tx_dat_lcrdv),
    .io_chi_rx_linkactivereq (x_io_chi_rx_linkactivereq),
    .io_chi_rx_linkactiveack (io_chi_rx_linkactiveack),
    .io_chi_rx_rsp_flitpend (x_io_chi_rx_rsp_flitpend),
    .io_chi_rx_rsp_flitv (x_io_chi_rx_rsp_flitv),
    .io_chi_rx_rsp_flit (x_io_chi_rx_rsp_flit),
    .io_chi_rx_rsp_lcrdv (io_chi_rx_rsp_lcrdv),
    .io_chi_rx_dat_flitpend (x_io_chi_rx_dat_flitpend),
    .io_chi_rx_dat_flitv (x_io_chi_rx_dat_flitv),
    .io_chi_rx_dat_flit (x_io_chi_rx_dat_flit),
    .io_chi_rx_dat_lcrdv (io_chi_rx_dat_lcrdv)
  );

  task automatic drive_random();
    auto_axi4_out_aw_ready = $random;
    auto_axi4_out_w_ready = $random;
    auto_axi4_out_b_valid = $random;
    auto_axi4_out_b_bits_id = $random;
    auto_axi4_out_ar_ready = $random;
    auto_axi4_out_r_valid = $random;
    auto_axi4_out_r_bits_id = $random;
    auto_axi4_out_r_bits_data = {$random,$random,$random,$random,$random,$random,$random,$random};
    auto_axi4_out_r_bits_last = $random;
    io_chi_txsactive = $random;
    io_chi_tx_linkactivereq = $random;
    io_chi_tx_req_flitpend = $random;
    io_chi_tx_req_flitv = $random;
    io_chi_tx_req_flit = {$random,$random,$random,$random,$random,$random};
    io_chi_tx_dat_flitpend = $random;
    io_chi_tx_dat_flitv = $random;
    io_chi_tx_dat_flit = {$random,$random,$random,$random,$random,$random,$random,$random,$random,$random,$random,$random,$random,$random};
    io_chi_rx_linkactiveack = $random;
    io_chi_rx_rsp_lcrdv = $random;
    io_chi_rx_dat_lcrdv = $random;
  endtask

  task automatic check_outputs();
    checks++; if (g_auto_axi4_out_aw_valid !== x_auto_axi4_out_aw_valid) begin errors++; if (errors<=40) $display("MISMATCH cyc=%0d auto_axi4_out_aw_valid g=%h x=%h", cyc, g_auto_axi4_out_aw_valid, x_auto_axi4_out_aw_valid); end
    checks++; if (g_auto_axi4_out_aw_bits_id !== x_auto_axi4_out_aw_bits_id) begin errors++; if (errors<=40) $display("MISMATCH cyc=%0d auto_axi4_out_aw_bits_id g=%h x=%h", cyc, g_auto_axi4_out_aw_bits_id, x_auto_axi4_out_aw_bits_id); end
    checks++; if (g_auto_axi4_out_aw_bits_addr !== x_auto_axi4_out_aw_bits_addr) begin errors++; if (errors<=40) $display("MISMATCH cyc=%0d auto_axi4_out_aw_bits_addr g=%h x=%h", cyc, g_auto_axi4_out_aw_bits_addr, x_auto_axi4_out_aw_bits_addr); end
    checks++; if (g_auto_axi4_out_aw_bits_len !== x_auto_axi4_out_aw_bits_len) begin errors++; if (errors<=40) $display("MISMATCH cyc=%0d auto_axi4_out_aw_bits_len g=%h x=%h", cyc, g_auto_axi4_out_aw_bits_len, x_auto_axi4_out_aw_bits_len); end
    checks++; if (g_auto_axi4_out_aw_bits_size !== x_auto_axi4_out_aw_bits_size) begin errors++; if (errors<=40) $display("MISMATCH cyc=%0d auto_axi4_out_aw_bits_size g=%h x=%h", cyc, g_auto_axi4_out_aw_bits_size, x_auto_axi4_out_aw_bits_size); end
    checks++; if (g_auto_axi4_out_aw_bits_burst !== x_auto_axi4_out_aw_bits_burst) begin errors++; if (errors<=40) $display("MISMATCH cyc=%0d auto_axi4_out_aw_bits_burst g=%h x=%h", cyc, g_auto_axi4_out_aw_bits_burst, x_auto_axi4_out_aw_bits_burst); end
    checks++; if (g_auto_axi4_out_aw_bits_qos !== x_auto_axi4_out_aw_bits_qos) begin errors++; if (errors<=40) $display("MISMATCH cyc=%0d auto_axi4_out_aw_bits_qos g=%h x=%h", cyc, g_auto_axi4_out_aw_bits_qos, x_auto_axi4_out_aw_bits_qos); end
    checks++; if (g_auto_axi4_out_w_valid !== x_auto_axi4_out_w_valid) begin errors++; if (errors<=40) $display("MISMATCH cyc=%0d auto_axi4_out_w_valid g=%h x=%h", cyc, g_auto_axi4_out_w_valid, x_auto_axi4_out_w_valid); end
    checks++; if (g_auto_axi4_out_w_bits_data !== x_auto_axi4_out_w_bits_data) begin errors++; if (errors<=40) $display("MISMATCH cyc=%0d auto_axi4_out_w_bits_data g=%h x=%h", cyc, g_auto_axi4_out_w_bits_data, x_auto_axi4_out_w_bits_data); end
    checks++; if (g_auto_axi4_out_w_bits_strb !== x_auto_axi4_out_w_bits_strb) begin errors++; if (errors<=40) $display("MISMATCH cyc=%0d auto_axi4_out_w_bits_strb g=%h x=%h", cyc, g_auto_axi4_out_w_bits_strb, x_auto_axi4_out_w_bits_strb); end
    checks++; if (g_auto_axi4_out_w_bits_last !== x_auto_axi4_out_w_bits_last) begin errors++; if (errors<=40) $display("MISMATCH cyc=%0d auto_axi4_out_w_bits_last g=%h x=%h", cyc, g_auto_axi4_out_w_bits_last, x_auto_axi4_out_w_bits_last); end
    checks++; if (g_auto_axi4_out_ar_valid !== x_auto_axi4_out_ar_valid) begin errors++; if (errors<=40) $display("MISMATCH cyc=%0d auto_axi4_out_ar_valid g=%h x=%h", cyc, g_auto_axi4_out_ar_valid, x_auto_axi4_out_ar_valid); end
    checks++; if (g_auto_axi4_out_ar_bits_id !== x_auto_axi4_out_ar_bits_id) begin errors++; if (errors<=40) $display("MISMATCH cyc=%0d auto_axi4_out_ar_bits_id g=%h x=%h", cyc, g_auto_axi4_out_ar_bits_id, x_auto_axi4_out_ar_bits_id); end
    checks++; if (g_auto_axi4_out_ar_bits_addr !== x_auto_axi4_out_ar_bits_addr) begin errors++; if (errors<=40) $display("MISMATCH cyc=%0d auto_axi4_out_ar_bits_addr g=%h x=%h", cyc, g_auto_axi4_out_ar_bits_addr, x_auto_axi4_out_ar_bits_addr); end
    checks++; if (g_auto_axi4_out_ar_bits_len !== x_auto_axi4_out_ar_bits_len) begin errors++; if (errors<=40) $display("MISMATCH cyc=%0d auto_axi4_out_ar_bits_len g=%h x=%h", cyc, g_auto_axi4_out_ar_bits_len, x_auto_axi4_out_ar_bits_len); end
    checks++; if (g_auto_axi4_out_ar_bits_size !== x_auto_axi4_out_ar_bits_size) begin errors++; if (errors<=40) $display("MISMATCH cyc=%0d auto_axi4_out_ar_bits_size g=%h x=%h", cyc, g_auto_axi4_out_ar_bits_size, x_auto_axi4_out_ar_bits_size); end
    checks++; if (g_auto_axi4_out_ar_bits_burst !== x_auto_axi4_out_ar_bits_burst) begin errors++; if (errors<=40) $display("MISMATCH cyc=%0d auto_axi4_out_ar_bits_burst g=%h x=%h", cyc, g_auto_axi4_out_ar_bits_burst, x_auto_axi4_out_ar_bits_burst); end
    checks++; if (g_auto_axi4_out_ar_bits_qos !== x_auto_axi4_out_ar_bits_qos) begin errors++; if (errors<=40) $display("MISMATCH cyc=%0d auto_axi4_out_ar_bits_qos g=%h x=%h", cyc, g_auto_axi4_out_ar_bits_qos, x_auto_axi4_out_ar_bits_qos); end
    checks++; if (g_io_chi_rxsactive !== x_io_chi_rxsactive) begin errors++; if (errors<=40) $display("MISMATCH cyc=%0d io_chi_rxsactive g=%h x=%h", cyc, g_io_chi_rxsactive, x_io_chi_rxsactive); end
    checks++; if (g_io_chi_tx_linkactiveack !== x_io_chi_tx_linkactiveack) begin errors++; if (errors<=40) $display("MISMATCH cyc=%0d io_chi_tx_linkactiveack g=%h x=%h", cyc, g_io_chi_tx_linkactiveack, x_io_chi_tx_linkactiveack); end
    checks++; if (g_io_chi_tx_req_lcrdv !== x_io_chi_tx_req_lcrdv) begin errors++; if (errors<=40) $display("MISMATCH cyc=%0d io_chi_tx_req_lcrdv g=%h x=%h", cyc, g_io_chi_tx_req_lcrdv, x_io_chi_tx_req_lcrdv); end
    checks++; if (g_io_chi_tx_dat_lcrdv !== x_io_chi_tx_dat_lcrdv) begin errors++; if (errors<=40) $display("MISMATCH cyc=%0d io_chi_tx_dat_lcrdv g=%h x=%h", cyc, g_io_chi_tx_dat_lcrdv, x_io_chi_tx_dat_lcrdv); end
    checks++; if (g_io_chi_rx_linkactivereq !== x_io_chi_rx_linkactivereq) begin errors++; if (errors<=40) $display("MISMATCH cyc=%0d io_chi_rx_linkactivereq g=%h x=%h", cyc, g_io_chi_rx_linkactivereq, x_io_chi_rx_linkactivereq); end
    checks++; if (g_io_chi_rx_rsp_flitpend !== x_io_chi_rx_rsp_flitpend) begin errors++; if (errors<=40) $display("MISMATCH cyc=%0d io_chi_rx_rsp_flitpend g=%h x=%h", cyc, g_io_chi_rx_rsp_flitpend, x_io_chi_rx_rsp_flitpend); end
    checks++; if (g_io_chi_rx_rsp_flitv !== x_io_chi_rx_rsp_flitv) begin errors++; if (errors<=40) $display("MISMATCH cyc=%0d io_chi_rx_rsp_flitv g=%h x=%h", cyc, g_io_chi_rx_rsp_flitv, x_io_chi_rx_rsp_flitv); end
    checks++; if (g_io_chi_rx_rsp_flit !== x_io_chi_rx_rsp_flit) begin errors++; if (errors<=40) $display("MISMATCH cyc=%0d io_chi_rx_rsp_flit g=%h x=%h", cyc, g_io_chi_rx_rsp_flit, x_io_chi_rx_rsp_flit); end
    checks++; if (g_io_chi_rx_dat_flitpend !== x_io_chi_rx_dat_flitpend) begin errors++; if (errors<=40) $display("MISMATCH cyc=%0d io_chi_rx_dat_flitpend g=%h x=%h", cyc, g_io_chi_rx_dat_flitpend, x_io_chi_rx_dat_flitpend); end
    checks++; if (g_io_chi_rx_dat_flitv !== x_io_chi_rx_dat_flitv) begin errors++; if (errors<=40) $display("MISMATCH cyc=%0d io_chi_rx_dat_flitv g=%h x=%h", cyc, g_io_chi_rx_dat_flitv, x_io_chi_rx_dat_flitv); end
    checks++; if (g_io_chi_rx_dat_flit !== x_io_chi_rx_dat_flit) begin errors++; if (errors<=40) $display("MISMATCH cyc=%0d io_chi_rx_dat_flit g=%h x=%h", cyc, g_io_chi_rx_dat_flit, x_io_chi_rx_dat_flit); end
  endtask

  initial begin
    rst = 1'b1;
    auto_axi4_out_aw_ready = '0;
    auto_axi4_out_w_ready = '0;
    auto_axi4_out_b_valid = '0;
    auto_axi4_out_b_bits_id = '0;
    auto_axi4_out_ar_ready = '0;
    auto_axi4_out_r_valid = '0;
    auto_axi4_out_r_bits_id = '0;
    auto_axi4_out_r_bits_data = '0;
    auto_axi4_out_r_bits_last = '0;
    io_chi_txsactive = '0;
    io_chi_tx_linkactivereq = '0;
    io_chi_tx_req_flitpend = '0;
    io_chi_tx_req_flitv = '0;
    io_chi_tx_req_flit = '0;
    io_chi_tx_dat_flitpend = '0;
    io_chi_tx_dat_flitv = '0;
    io_chi_tx_dat_flit = '0;
    io_chi_rx_linkactiveack = '0;
    io_chi_rx_rsp_lcrdv = '0;
    io_chi_rx_dat_lcrdv = '0;
    repeat (6) @(posedge clk);
    @(negedge clk); rst = 1'b0;
    for (cyc=0; cyc<NCYCLES; cyc++) begin
      @(negedge clk);
      drive_random();
      @(posedge clk);
      #1;
      if (cyc >= WARMUP) check_outputs();
    end
    if (errors==0) $display("TEST PASSED: checks=%0d errors=0", checks);
    else $display("TEST FAILED: checks=%0d errors=%0d", checks, errors);
    $finish;
  end
endmodule
