// 自动生成：scripts/gen_probequeue.py —— 勿手改
module ProbeQueue_xs(
  input  clock,
  input  reset,
  output io_mem_probe_ready,
  input  io_mem_probe_valid,
  input  [2:0] io_mem_probe_bits_opcode,
  input  [1:0] io_mem_probe_bits_param,
  input  [47:0] io_mem_probe_bits_address,
  input  [255:0] io_mem_probe_bits_data,
  input  io_pipe_req_ready,
  output io_pipe_req_valid,
  output [1:0] io_pipe_req_bits_probe_param,
  output io_pipe_req_bits_probe_need_data,
  output [49:0] io_pipe_req_bits_vaddr,
  output [47:0] io_pipe_req_bits_addr,
  output [5:0] io_pipe_req_bits_id,
  input  io_lrsc_locked_block_valid,
  input  [47:0] io_lrsc_locked_block_bits,
  input  io_update_resv_set,
  output [5:0] io_perf_0_value,
  output [5:0] io_perf_1_value,
  output [5:0] io_perf_2_value,
  output [5:0] io_perf_3_value,
  output [5:0] io_perf_4_value
);
  xs_ProbeQueue_core u_core (
    .clock(clock),
    .reset(reset),
    .io_mem_probe_ready(io_mem_probe_ready),
    .io_mem_probe_valid(io_mem_probe_valid),
    .io_mem_probe_bits_opcode(io_mem_probe_bits_opcode),
    .io_mem_probe_bits_param(io_mem_probe_bits_param),
    .io_mem_probe_bits_address(io_mem_probe_bits_address),
    .io_mem_probe_bits_data(io_mem_probe_bits_data),
    .io_pipe_req_ready(io_pipe_req_ready),
    .io_pipe_req_valid(io_pipe_req_valid),
    .io_pipe_req_bits_probe_param(io_pipe_req_bits_probe_param),
    .io_pipe_req_bits_probe_need_data(io_pipe_req_bits_probe_need_data),
    .io_pipe_req_bits_vaddr(io_pipe_req_bits_vaddr),
    .io_pipe_req_bits_addr(io_pipe_req_bits_addr),
    .io_pipe_req_bits_id(io_pipe_req_bits_id),
    .io_lrsc_locked_block_valid(io_lrsc_locked_block_valid),
    .io_lrsc_locked_block_bits(io_lrsc_locked_block_bits),
    .io_update_resv_set(io_update_resv_set),
    .io_perf_0_value(io_perf_0_value),
    .io_perf_1_value(io_perf_1_value),
    .io_perf_2_value(io_perf_2_value),
    .io_perf_3_value(io_perf_3_value),
    .io_perf_4_value(io_perf_4_value)
  );
endmodule
