// 自动生成: verif/bt/Backend/gen_bt.py —— 勿手改
// ExuBlock_1_bt: 全 golden 端口 BT 包装, 例化已验证的 ExuBlock_1_xs(暴露 golden 名子集 + 真重写 glue),
//   golden-only input 悬空 / golden-only output 接 '0(rewrite 省略的透传/元数据端口)。
//   被接 '0 的 output 列入 tb nonfunc 名单, 打印不计 PASS(照 Frontend BT/README §4)。
module ExuBlock_1_bt(
  input clock,
  input reset,
  input io_flush_valid,
  input io_flush_bits_robIdx_flag,
  input [7:0] io_flush_bits_robIdx_value,
  input io_flush_bits_level,
  output io_in_2_0_ready,
  input io_in_2_0_valid,
  input [34:0] io_in_2_0_bits_fuType,
  input [8:0] io_in_2_0_bits_fuOpType,
  input [63:0] io_in_2_0_bits_src_0,
  input [63:0] io_in_2_0_bits_src_1,
  input [63:0] io_in_2_0_bits_src_2,
  input io_in_2_0_bits_robIdx_flag,
  input [7:0] io_in_2_0_bits_robIdx_value,
  input [7:0] io_in_2_0_bits_pdest,
  input io_in_2_0_bits_rfWen,
  input io_in_2_0_bits_fpWen,
  input io_in_2_0_bits_fpu_wflags,
  input [1:0] io_in_2_0_bits_fpu_fmt,
  input [2:0] io_in_2_0_bits_fpu_rm,
  input io_in_2_0_bits_perfDebugInfo_eliminatedMove,
  input [63:0] io_in_2_0_bits_perfDebugInfo_renameTime,
  input [63:0] io_in_2_0_bits_perfDebugInfo_dispatchTime,
  input [63:0] io_in_2_0_bits_perfDebugInfo_enqRsTime,
  input [63:0] io_in_2_0_bits_perfDebugInfo_selectTime,
  input [63:0] io_in_2_0_bits_perfDebugInfo_issueTime,
  input [63:0] io_in_2_0_bits_perfDebugInfo_writebackTime,
  input [63:0] io_in_2_0_bits_perfDebugInfo_runahead_checkpoint_id,
  input [63:0] io_in_2_0_bits_perfDebugInfo_tlbFirstReqTime,
  input [63:0] io_in_2_0_bits_perfDebugInfo_tlbRespTime,
  input [63:0] io_in_2_0_bits_debug_seqNum,
  output io_in_1_1_ready,
  input io_in_1_1_valid,
  input [34:0] io_in_1_1_bits_fuType,
  input [8:0] io_in_1_1_bits_fuOpType,
  input [63:0] io_in_1_1_bits_src_0,
  input [63:0] io_in_1_1_bits_src_1,
  input io_in_1_1_bits_robIdx_flag,
  input [7:0] io_in_1_1_bits_robIdx_value,
  input [7:0] io_in_1_1_bits_pdest,
  input io_in_1_1_bits_fpWen,
  input io_in_1_1_bits_fpu_wflags,
  input [1:0] io_in_1_1_bits_fpu_fmt,
  input [2:0] io_in_1_1_bits_fpu_rm,
  input io_in_1_1_bits_perfDebugInfo_eliminatedMove,
  input [63:0] io_in_1_1_bits_perfDebugInfo_renameTime,
  input [63:0] io_in_1_1_bits_perfDebugInfo_dispatchTime,
  input [63:0] io_in_1_1_bits_perfDebugInfo_enqRsTime,
  input [63:0] io_in_1_1_bits_perfDebugInfo_selectTime,
  input [63:0] io_in_1_1_bits_perfDebugInfo_issueTime,
  input [63:0] io_in_1_1_bits_perfDebugInfo_writebackTime,
  input [63:0] io_in_1_1_bits_perfDebugInfo_runahead_checkpoint_id,
  input [63:0] io_in_1_1_bits_perfDebugInfo_tlbFirstReqTime,
  input [63:0] io_in_1_1_bits_perfDebugInfo_tlbRespTime,
  input [63:0] io_in_1_1_bits_debug_seqNum,
  output io_in_1_0_ready,
  input io_in_1_0_valid,
  input [34:0] io_in_1_0_bits_fuType,
  input [8:0] io_in_1_0_bits_fuOpType,
  input [63:0] io_in_1_0_bits_src_0,
  input [63:0] io_in_1_0_bits_src_1,
  input [63:0] io_in_1_0_bits_src_2,
  input io_in_1_0_bits_robIdx_flag,
  input [7:0] io_in_1_0_bits_robIdx_value,
  input [7:0] io_in_1_0_bits_pdest,
  input io_in_1_0_bits_rfWen,
  input io_in_1_0_bits_fpWen,
  input io_in_1_0_bits_fpu_wflags,
  input [1:0] io_in_1_0_bits_fpu_fmt,
  input [2:0] io_in_1_0_bits_fpu_rm,
  input io_in_1_0_bits_perfDebugInfo_eliminatedMove,
  input [63:0] io_in_1_0_bits_perfDebugInfo_renameTime,
  input [63:0] io_in_1_0_bits_perfDebugInfo_dispatchTime,
  input [63:0] io_in_1_0_bits_perfDebugInfo_enqRsTime,
  input [63:0] io_in_1_0_bits_perfDebugInfo_selectTime,
  input [63:0] io_in_1_0_bits_perfDebugInfo_issueTime,
  input [63:0] io_in_1_0_bits_perfDebugInfo_writebackTime,
  input [63:0] io_in_1_0_bits_perfDebugInfo_runahead_checkpoint_id,
  input [63:0] io_in_1_0_bits_perfDebugInfo_tlbFirstReqTime,
  input [63:0] io_in_1_0_bits_perfDebugInfo_tlbRespTime,
  input [63:0] io_in_1_0_bits_debug_seqNum,
  output io_in_0_1_ready,
  input io_in_0_1_valid,
  input [34:0] io_in_0_1_bits_fuType,
  input [8:0] io_in_0_1_bits_fuOpType,
  input [63:0] io_in_0_1_bits_src_0,
  input [63:0] io_in_0_1_bits_src_1,
  input io_in_0_1_bits_robIdx_flag,
  input [7:0] io_in_0_1_bits_robIdx_value,
  input [7:0] io_in_0_1_bits_pdest,
  input io_in_0_1_bits_fpWen,
  input io_in_0_1_bits_fpu_wflags,
  input [1:0] io_in_0_1_bits_fpu_fmt,
  input [2:0] io_in_0_1_bits_fpu_rm,
  input io_in_0_1_bits_perfDebugInfo_eliminatedMove,
  input [63:0] io_in_0_1_bits_perfDebugInfo_renameTime,
  input [63:0] io_in_0_1_bits_perfDebugInfo_dispatchTime,
  input [63:0] io_in_0_1_bits_perfDebugInfo_enqRsTime,
  input [63:0] io_in_0_1_bits_perfDebugInfo_selectTime,
  input [63:0] io_in_0_1_bits_perfDebugInfo_issueTime,
  input [63:0] io_in_0_1_bits_perfDebugInfo_writebackTime,
  input [63:0] io_in_0_1_bits_perfDebugInfo_runahead_checkpoint_id,
  input [63:0] io_in_0_1_bits_perfDebugInfo_tlbFirstReqTime,
  input [63:0] io_in_0_1_bits_perfDebugInfo_tlbRespTime,
  input [63:0] io_in_0_1_bits_debug_seqNum,
  output io_in_0_0_ready,
  input io_in_0_0_valid,
  input [34:0] io_in_0_0_bits_fuType,
  input [8:0] io_in_0_0_bits_fuOpType,
  input [63:0] io_in_0_0_bits_src_0,
  input [63:0] io_in_0_0_bits_src_1,
  input [63:0] io_in_0_0_bits_src_2,
  input io_in_0_0_bits_robIdx_flag,
  input [7:0] io_in_0_0_bits_robIdx_value,
  input [7:0] io_in_0_0_bits_pdest,
  input io_in_0_0_bits_rfWen,
  input io_in_0_0_bits_fpWen,
  input io_in_0_0_bits_vecWen,
  input io_in_0_0_bits_v0Wen,
  input io_in_0_0_bits_fpu_wflags,
  input [1:0] io_in_0_0_bits_fpu_fmt,
  input [2:0] io_in_0_0_bits_fpu_rm,
  input io_in_0_0_bits_perfDebugInfo_eliminatedMove,
  input [63:0] io_in_0_0_bits_perfDebugInfo_renameTime,
  input [63:0] io_in_0_0_bits_perfDebugInfo_dispatchTime,
  input [63:0] io_in_0_0_bits_perfDebugInfo_enqRsTime,
  input [63:0] io_in_0_0_bits_perfDebugInfo_selectTime,
  input [63:0] io_in_0_0_bits_perfDebugInfo_issueTime,
  input [63:0] io_in_0_0_bits_perfDebugInfo_writebackTime,
  input [63:0] io_in_0_0_bits_perfDebugInfo_runahead_checkpoint_id,
  input [63:0] io_in_0_0_bits_perfDebugInfo_tlbFirstReqTime,
  input [63:0] io_in_0_0_bits_perfDebugInfo_tlbRespTime,
  input [63:0] io_in_0_0_bits_debug_seqNum,
  output io_out_2_0_valid,
  output [63:0] io_out_2_0_bits_data_0,
  output [63:0] io_out_2_0_bits_data_1,
  output [63:0] io_out_2_0_bits_data_2,
  output [7:0] io_out_2_0_bits_pdest,
  output io_out_2_0_bits_robIdx_flag,
  output [7:0] io_out_2_0_bits_robIdx_value,
  output io_out_2_0_bits_intWen,
  output io_out_2_0_bits_fpWen,
  output [4:0] io_out_2_0_bits_fflags,
  output io_out_2_0_bits_wflags,
  output io_out_2_0_bits_debugInfo_eliminatedMove,
  output [63:0] io_out_2_0_bits_debugInfo_renameTime,
  output [63:0] io_out_2_0_bits_debugInfo_dispatchTime,
  output [63:0] io_out_2_0_bits_debugInfo_enqRsTime,
  output [63:0] io_out_2_0_bits_debugInfo_selectTime,
  output [63:0] io_out_2_0_bits_debugInfo_issueTime,
  output [63:0] io_out_2_0_bits_debugInfo_writebackTime,
  output [63:0] io_out_2_0_bits_debugInfo_runahead_checkpoint_id,
  output [63:0] io_out_2_0_bits_debugInfo_tlbFirstReqTime,
  output [63:0] io_out_2_0_bits_debugInfo_tlbRespTime,
  output [63:0] io_out_2_0_bits_debug_seqNum,
  input io_out_1_1_ready,
  output io_out_1_1_valid,
  output [63:0] io_out_1_1_bits_data_0,
  output [63:0] io_out_1_1_bits_data_1,
  output [7:0] io_out_1_1_bits_pdest,
  output io_out_1_1_bits_robIdx_flag,
  output [7:0] io_out_1_1_bits_robIdx_value,
  output io_out_1_1_bits_fpWen,
  output [4:0] io_out_1_1_bits_fflags,
  output io_out_1_1_bits_wflags,
  output io_out_1_1_bits_debugInfo_eliminatedMove,
  output [63:0] io_out_1_1_bits_debugInfo_renameTime,
  output [63:0] io_out_1_1_bits_debugInfo_dispatchTime,
  output [63:0] io_out_1_1_bits_debugInfo_enqRsTime,
  output [63:0] io_out_1_1_bits_debugInfo_selectTime,
  output [63:0] io_out_1_1_bits_debugInfo_issueTime,
  output [63:0] io_out_1_1_bits_debugInfo_writebackTime,
  output [63:0] io_out_1_1_bits_debugInfo_runahead_checkpoint_id,
  output [63:0] io_out_1_1_bits_debugInfo_tlbFirstReqTime,
  output [63:0] io_out_1_1_bits_debugInfo_tlbRespTime,
  output [63:0] io_out_1_1_bits_debug_seqNum,
  output io_out_1_0_valid,
  output [63:0] io_out_1_0_bits_data_0,
  output [63:0] io_out_1_0_bits_data_1,
  output [63:0] io_out_1_0_bits_data_2,
  output [7:0] io_out_1_0_bits_pdest,
  output io_out_1_0_bits_robIdx_flag,
  output [7:0] io_out_1_0_bits_robIdx_value,
  output io_out_1_0_bits_intWen,
  output io_out_1_0_bits_fpWen,
  output [4:0] io_out_1_0_bits_fflags,
  output io_out_1_0_bits_wflags,
  output io_out_1_0_bits_debugInfo_eliminatedMove,
  output [63:0] io_out_1_0_bits_debugInfo_renameTime,
  output [63:0] io_out_1_0_bits_debugInfo_dispatchTime,
  output [63:0] io_out_1_0_bits_debugInfo_enqRsTime,
  output [63:0] io_out_1_0_bits_debugInfo_selectTime,
  output [63:0] io_out_1_0_bits_debugInfo_issueTime,
  output [63:0] io_out_1_0_bits_debugInfo_writebackTime,
  output [63:0] io_out_1_0_bits_debugInfo_runahead_checkpoint_id,
  output [63:0] io_out_1_0_bits_debugInfo_tlbFirstReqTime,
  output [63:0] io_out_1_0_bits_debugInfo_tlbRespTime,
  output [63:0] io_out_1_0_bits_debug_seqNum,
  input io_out_0_1_ready,
  output io_out_0_1_valid,
  output [63:0] io_out_0_1_bits_data_0,
  output [63:0] io_out_0_1_bits_data_1,
  output [7:0] io_out_0_1_bits_pdest,
  output io_out_0_1_bits_robIdx_flag,
  output [7:0] io_out_0_1_bits_robIdx_value,
  output io_out_0_1_bits_fpWen,
  output [4:0] io_out_0_1_bits_fflags,
  output io_out_0_1_bits_wflags,
  output io_out_0_1_bits_debugInfo_eliminatedMove,
  output [63:0] io_out_0_1_bits_debugInfo_renameTime,
  output [63:0] io_out_0_1_bits_debugInfo_dispatchTime,
  output [63:0] io_out_0_1_bits_debugInfo_enqRsTime,
  output [63:0] io_out_0_1_bits_debugInfo_selectTime,
  output [63:0] io_out_0_1_bits_debugInfo_issueTime,
  output [63:0] io_out_0_1_bits_debugInfo_writebackTime,
  output [63:0] io_out_0_1_bits_debugInfo_runahead_checkpoint_id,
  output [63:0] io_out_0_1_bits_debugInfo_tlbFirstReqTime,
  output [63:0] io_out_0_1_bits_debugInfo_tlbRespTime,
  output [63:0] io_out_0_1_bits_debug_seqNum,
  output io_out_0_0_valid,
  output [127:0] io_out_0_0_bits_data_0,
  output [127:0] io_out_0_0_bits_data_1,
  output [127:0] io_out_0_0_bits_data_2,
  output [127:0] io_out_0_0_bits_data_3,
  output [127:0] io_out_0_0_bits_data_4,
  output [7:0] io_out_0_0_bits_pdest,
  output io_out_0_0_bits_robIdx_flag,
  output [7:0] io_out_0_0_bits_robIdx_value,
  output io_out_0_0_bits_intWen,
  output io_out_0_0_bits_fpWen,
  output io_out_0_0_bits_vecWen,
  output io_out_0_0_bits_v0Wen,
  output [4:0] io_out_0_0_bits_fflags,
  output io_out_0_0_bits_wflags,
  output io_out_0_0_bits_debugInfo_eliminatedMove,
  output [63:0] io_out_0_0_bits_debugInfo_renameTime,
  output [63:0] io_out_0_0_bits_debugInfo_dispatchTime,
  output [63:0] io_out_0_0_bits_debugInfo_enqRsTime,
  output [63:0] io_out_0_0_bits_debugInfo_selectTime,
  output [63:0] io_out_0_0_bits_debugInfo_issueTime,
  output [63:0] io_out_0_0_bits_debugInfo_writebackTime,
  output [63:0] io_out_0_0_bits_debugInfo_runahead_checkpoint_id,
  output [63:0] io_out_0_0_bits_debugInfo_tlbFirstReqTime,
  output [63:0] io_out_0_0_bits_debugInfo_tlbRespTime,
  output [63:0] io_out_0_0_bits_debug_seqNum,
  input [2:0] io_frm,
  input cg_bore_cgen,
  input cg_bore_1_cgen,
  input cg_bore_2_cgen,
  input cg_bore_3_cgen,
  input cg_bore_4_cgen,
  input cg_bore_5_cgen,
  input cg_bore_6_cgen,
  input cg_bore_7_cgen,
  input cg_bore_8_cgen
);
  ExuBlock_1_xs u_xs (
    .clock(clock),
    .reset(reset),
    .io_flush_valid(io_flush_valid),
    .io_flush_bits_robIdx_flag(io_flush_bits_robIdx_flag),
    .io_flush_bits_robIdx_value(io_flush_bits_robIdx_value),
    .io_flush_bits_level(io_flush_bits_level),
    .io_in_2_0_valid(io_in_2_0_valid),
    .io_in_2_0_bits_fuType(io_in_2_0_bits_fuType),
    .io_in_2_0_bits_fuOpType(io_in_2_0_bits_fuOpType),
    .io_in_2_0_bits_src_0(io_in_2_0_bits_src_0),
    .io_in_2_0_bits_src_1(io_in_2_0_bits_src_1),
    .io_in_2_0_bits_src_2(io_in_2_0_bits_src_2),
    .io_in_2_0_bits_robIdx_flag(io_in_2_0_bits_robIdx_flag),
    .io_in_2_0_bits_robIdx_value(io_in_2_0_bits_robIdx_value),
    .io_in_2_0_bits_pdest(io_in_2_0_bits_pdest),
    .io_in_2_0_bits_rfWen(io_in_2_0_bits_rfWen),
    .io_in_2_0_bits_fpWen(io_in_2_0_bits_fpWen),
    .io_in_2_0_bits_fpu_wflags(io_in_2_0_bits_fpu_wflags),
    .io_in_2_0_bits_fpu_fmt(io_in_2_0_bits_fpu_fmt),
    .io_in_2_0_bits_fpu_rm(io_in_2_0_bits_fpu_rm),
    .io_in_2_0_bits_perfDebugInfo_enqRsTime(io_in_2_0_bits_perfDebugInfo_enqRsTime),
    .io_in_2_0_bits_perfDebugInfo_selectTime(io_in_2_0_bits_perfDebugInfo_selectTime),
    .io_in_2_0_bits_perfDebugInfo_issueTime(io_in_2_0_bits_perfDebugInfo_issueTime),
    .io_in_1_1_ready(io_in_1_1_ready),
    .io_in_1_1_valid(io_in_1_1_valid),
    .io_in_1_1_bits_fuType(io_in_1_1_bits_fuType),
    .io_in_1_1_bits_fuOpType(io_in_1_1_bits_fuOpType),
    .io_in_1_1_bits_src_0(io_in_1_1_bits_src_0),
    .io_in_1_1_bits_src_1(io_in_1_1_bits_src_1),
    .io_in_1_1_bits_robIdx_flag(io_in_1_1_bits_robIdx_flag),
    .io_in_1_1_bits_robIdx_value(io_in_1_1_bits_robIdx_value),
    .io_in_1_1_bits_pdest(io_in_1_1_bits_pdest),
    .io_in_1_1_bits_fpWen(io_in_1_1_bits_fpWen),
    .io_in_1_1_bits_fpu_wflags(io_in_1_1_bits_fpu_wflags),
    .io_in_1_1_bits_fpu_fmt(io_in_1_1_bits_fpu_fmt),
    .io_in_1_1_bits_fpu_rm(io_in_1_1_bits_fpu_rm),
    .io_in_1_1_bits_perfDebugInfo_enqRsTime(io_in_1_1_bits_perfDebugInfo_enqRsTime),
    .io_in_1_1_bits_perfDebugInfo_selectTime(io_in_1_1_bits_perfDebugInfo_selectTime),
    .io_in_1_1_bits_perfDebugInfo_issueTime(io_in_1_1_bits_perfDebugInfo_issueTime),
    .io_in_1_0_valid(io_in_1_0_valid),
    .io_in_1_0_bits_fuType(io_in_1_0_bits_fuType),
    .io_in_1_0_bits_fuOpType(io_in_1_0_bits_fuOpType),
    .io_in_1_0_bits_src_0(io_in_1_0_bits_src_0),
    .io_in_1_0_bits_src_1(io_in_1_0_bits_src_1),
    .io_in_1_0_bits_src_2(io_in_1_0_bits_src_2),
    .io_in_1_0_bits_robIdx_flag(io_in_1_0_bits_robIdx_flag),
    .io_in_1_0_bits_robIdx_value(io_in_1_0_bits_robIdx_value),
    .io_in_1_0_bits_pdest(io_in_1_0_bits_pdest),
    .io_in_1_0_bits_rfWen(io_in_1_0_bits_rfWen),
    .io_in_1_0_bits_fpWen(io_in_1_0_bits_fpWen),
    .io_in_1_0_bits_fpu_wflags(io_in_1_0_bits_fpu_wflags),
    .io_in_1_0_bits_fpu_fmt(io_in_1_0_bits_fpu_fmt),
    .io_in_1_0_bits_fpu_rm(io_in_1_0_bits_fpu_rm),
    .io_in_1_0_bits_perfDebugInfo_enqRsTime(io_in_1_0_bits_perfDebugInfo_enqRsTime),
    .io_in_1_0_bits_perfDebugInfo_selectTime(io_in_1_0_bits_perfDebugInfo_selectTime),
    .io_in_1_0_bits_perfDebugInfo_issueTime(io_in_1_0_bits_perfDebugInfo_issueTime),
    .io_in_0_1_ready(io_in_0_1_ready),
    .io_in_0_1_valid(io_in_0_1_valid),
    .io_in_0_1_bits_fuType(io_in_0_1_bits_fuType),
    .io_in_0_1_bits_fuOpType(io_in_0_1_bits_fuOpType),
    .io_in_0_1_bits_src_0(io_in_0_1_bits_src_0),
    .io_in_0_1_bits_src_1(io_in_0_1_bits_src_1),
    .io_in_0_1_bits_robIdx_flag(io_in_0_1_bits_robIdx_flag),
    .io_in_0_1_bits_robIdx_value(io_in_0_1_bits_robIdx_value),
    .io_in_0_1_bits_pdest(io_in_0_1_bits_pdest),
    .io_in_0_1_bits_fpWen(io_in_0_1_bits_fpWen),
    .io_in_0_1_bits_fpu_wflags(io_in_0_1_bits_fpu_wflags),
    .io_in_0_1_bits_fpu_fmt(io_in_0_1_bits_fpu_fmt),
    .io_in_0_1_bits_fpu_rm(io_in_0_1_bits_fpu_rm),
    .io_in_0_1_bits_perfDebugInfo_enqRsTime(io_in_0_1_bits_perfDebugInfo_enqRsTime),
    .io_in_0_1_bits_perfDebugInfo_selectTime(io_in_0_1_bits_perfDebugInfo_selectTime),
    .io_in_0_1_bits_perfDebugInfo_issueTime(io_in_0_1_bits_perfDebugInfo_issueTime),
    .io_in_0_0_valid(io_in_0_0_valid),
    .io_in_0_0_bits_fuType(io_in_0_0_bits_fuType),
    .io_in_0_0_bits_fuOpType(io_in_0_0_bits_fuOpType),
    .io_in_0_0_bits_src_0(io_in_0_0_bits_src_0),
    .io_in_0_0_bits_src_1(io_in_0_0_bits_src_1),
    .io_in_0_0_bits_src_2(io_in_0_0_bits_src_2),
    .io_in_0_0_bits_robIdx_flag(io_in_0_0_bits_robIdx_flag),
    .io_in_0_0_bits_robIdx_value(io_in_0_0_bits_robIdx_value),
    .io_in_0_0_bits_pdest(io_in_0_0_bits_pdest),
    .io_in_0_0_bits_rfWen(io_in_0_0_bits_rfWen),
    .io_in_0_0_bits_fpWen(io_in_0_0_bits_fpWen),
    .io_in_0_0_bits_vecWen(io_in_0_0_bits_vecWen),
    .io_in_0_0_bits_v0Wen(io_in_0_0_bits_v0Wen),
    .io_in_0_0_bits_fpu_wflags(io_in_0_0_bits_fpu_wflags),
    .io_in_0_0_bits_fpu_fmt(io_in_0_0_bits_fpu_fmt),
    .io_in_0_0_bits_fpu_rm(io_in_0_0_bits_fpu_rm),
    .io_in_0_0_bits_perfDebugInfo_enqRsTime(io_in_0_0_bits_perfDebugInfo_enqRsTime),
    .io_in_0_0_bits_perfDebugInfo_selectTime(io_in_0_0_bits_perfDebugInfo_selectTime),
    .io_in_0_0_bits_perfDebugInfo_issueTime(io_in_0_0_bits_perfDebugInfo_issueTime),
    .io_out_2_0_valid(io_out_2_0_valid),
    .io_out_2_0_bits_data_0(io_out_2_0_bits_data_0),
    .io_out_2_0_bits_data_1(io_out_2_0_bits_data_1),
    .io_out_2_0_bits_data_2(io_out_2_0_bits_data_2),
    .io_out_2_0_bits_pdest(io_out_2_0_bits_pdest),
    .io_out_2_0_bits_robIdx_flag(io_out_2_0_bits_robIdx_flag),
    .io_out_2_0_bits_robIdx_value(io_out_2_0_bits_robIdx_value),
    .io_out_2_0_bits_intWen(io_out_2_0_bits_intWen),
    .io_out_2_0_bits_fpWen(io_out_2_0_bits_fpWen),
    .io_out_2_0_bits_fflags(io_out_2_0_bits_fflags),
    .io_out_2_0_bits_wflags(io_out_2_0_bits_wflags),
    .io_out_2_0_bits_debugInfo_enqRsTime(io_out_2_0_bits_debugInfo_enqRsTime),
    .io_out_2_0_bits_debugInfo_selectTime(io_out_2_0_bits_debugInfo_selectTime),
    .io_out_2_0_bits_debugInfo_issueTime(io_out_2_0_bits_debugInfo_issueTime),
    .io_out_1_1_ready(io_out_1_1_ready),
    .io_out_1_1_valid(io_out_1_1_valid),
    .io_out_1_1_bits_data_1(io_out_1_1_bits_data_1),
    .io_out_1_1_bits_pdest(io_out_1_1_bits_pdest),
    .io_out_1_1_bits_robIdx_flag(io_out_1_1_bits_robIdx_flag),
    .io_out_1_1_bits_robIdx_value(io_out_1_1_bits_robIdx_value),
    .io_out_1_1_bits_fpWen(io_out_1_1_bits_fpWen),
    .io_out_1_1_bits_fflags(io_out_1_1_bits_fflags),
    .io_out_1_1_bits_wflags(io_out_1_1_bits_wflags),
    .io_out_1_1_bits_debugInfo_enqRsTime(io_out_1_1_bits_debugInfo_enqRsTime),
    .io_out_1_1_bits_debugInfo_selectTime(io_out_1_1_bits_debugInfo_selectTime),
    .io_out_1_1_bits_debugInfo_issueTime(io_out_1_1_bits_debugInfo_issueTime),
    .io_out_1_0_valid(io_out_1_0_valid),
    .io_out_1_0_bits_data_0(io_out_1_0_bits_data_0),
    .io_out_1_0_bits_data_1(io_out_1_0_bits_data_1),
    .io_out_1_0_bits_data_2(io_out_1_0_bits_data_2),
    .io_out_1_0_bits_pdest(io_out_1_0_bits_pdest),
    .io_out_1_0_bits_robIdx_flag(io_out_1_0_bits_robIdx_flag),
    .io_out_1_0_bits_robIdx_value(io_out_1_0_bits_robIdx_value),
    .io_out_1_0_bits_intWen(io_out_1_0_bits_intWen),
    .io_out_1_0_bits_fpWen(io_out_1_0_bits_fpWen),
    .io_out_1_0_bits_fflags(io_out_1_0_bits_fflags),
    .io_out_1_0_bits_wflags(io_out_1_0_bits_wflags),
    .io_out_1_0_bits_debugInfo_enqRsTime(io_out_1_0_bits_debugInfo_enqRsTime),
    .io_out_1_0_bits_debugInfo_selectTime(io_out_1_0_bits_debugInfo_selectTime),
    .io_out_1_0_bits_debugInfo_issueTime(io_out_1_0_bits_debugInfo_issueTime),
    .io_out_0_1_ready(io_out_0_1_ready),
    .io_out_0_1_valid(io_out_0_1_valid),
    .io_out_0_1_bits_data_1(io_out_0_1_bits_data_1),
    .io_out_0_1_bits_pdest(io_out_0_1_bits_pdest),
    .io_out_0_1_bits_robIdx_flag(io_out_0_1_bits_robIdx_flag),
    .io_out_0_1_bits_robIdx_value(io_out_0_1_bits_robIdx_value),
    .io_out_0_1_bits_fpWen(io_out_0_1_bits_fpWen),
    .io_out_0_1_bits_fflags(io_out_0_1_bits_fflags),
    .io_out_0_1_bits_wflags(io_out_0_1_bits_wflags),
    .io_out_0_1_bits_debugInfo_enqRsTime(io_out_0_1_bits_debugInfo_enqRsTime),
    .io_out_0_1_bits_debugInfo_selectTime(io_out_0_1_bits_debugInfo_selectTime),
    .io_out_0_1_bits_debugInfo_issueTime(io_out_0_1_bits_debugInfo_issueTime),
    .io_out_0_0_valid(io_out_0_0_valid),
    .io_out_0_0_bits_data_0(io_out_0_0_bits_data_0),
    .io_out_0_0_bits_data_1(io_out_0_0_bits_data_1),
    .io_out_0_0_bits_data_2(io_out_0_0_bits_data_2),
    .io_out_0_0_bits_data_3(io_out_0_0_bits_data_3),
    .io_out_0_0_bits_data_4(io_out_0_0_bits_data_4),
    .io_out_0_0_bits_pdest(io_out_0_0_bits_pdest),
    .io_out_0_0_bits_robIdx_flag(io_out_0_0_bits_robIdx_flag),
    .io_out_0_0_bits_robIdx_value(io_out_0_0_bits_robIdx_value),
    .io_out_0_0_bits_intWen(io_out_0_0_bits_intWen),
    .io_out_0_0_bits_fpWen(io_out_0_0_bits_fpWen),
    .io_out_0_0_bits_vecWen(io_out_0_0_bits_vecWen),
    .io_out_0_0_bits_v0Wen(io_out_0_0_bits_v0Wen),
    .io_out_0_0_bits_fflags(io_out_0_0_bits_fflags),
    .io_out_0_0_bits_wflags(io_out_0_0_bits_wflags),
    .io_out_0_0_bits_debugInfo_enqRsTime(io_out_0_0_bits_debugInfo_enqRsTime),
    .io_out_0_0_bits_debugInfo_selectTime(io_out_0_0_bits_debugInfo_selectTime),
    .io_out_0_0_bits_debugInfo_issueTime(io_out_0_0_bits_debugInfo_issueTime),
    .io_frm(io_frm),
    .cg_bore_cgen(cg_bore_cgen),
    .cg_bore_1_cgen(cg_bore_1_cgen),
    .cg_bore_2_cgen(cg_bore_2_cgen),
    .cg_bore_3_cgen(cg_bore_3_cgen),
    .cg_bore_4_cgen(cg_bore_4_cgen),
    .cg_bore_5_cgen(cg_bore_5_cgen),
    .cg_bore_6_cgen(cg_bore_6_cgen),
    .cg_bore_7_cgen(cg_bore_7_cgen),
    .cg_bore_8_cgen(cg_bore_8_cgen)
  );
  assign io_in_2_0_ready = '0;  // rewrite-omitted (nonfunc)
  assign io_in_1_0_ready = '0;  // rewrite-omitted (nonfunc)
  assign io_in_0_0_ready = '0;  // rewrite-omitted (nonfunc)
  assign io_out_2_0_bits_debugInfo_eliminatedMove = '0;  // rewrite-omitted (nonfunc)
  assign io_out_2_0_bits_debugInfo_renameTime = '0;  // rewrite-omitted (nonfunc)
  assign io_out_2_0_bits_debugInfo_dispatchTime = '0;  // rewrite-omitted (nonfunc)
  assign io_out_2_0_bits_debugInfo_writebackTime = '0;  // rewrite-omitted (nonfunc)
  assign io_out_2_0_bits_debugInfo_runahead_checkpoint_id = '0;  // rewrite-omitted (nonfunc)
  assign io_out_2_0_bits_debugInfo_tlbFirstReqTime = '0;  // rewrite-omitted (nonfunc)
  assign io_out_2_0_bits_debugInfo_tlbRespTime = '0;  // rewrite-omitted (nonfunc)
  assign io_out_2_0_bits_debug_seqNum = '0;  // rewrite-omitted (nonfunc)
  assign io_out_1_1_bits_data_0 = '0;  // rewrite-omitted (nonfunc)
  assign io_out_1_1_bits_debugInfo_eliminatedMove = '0;  // rewrite-omitted (nonfunc)
  assign io_out_1_1_bits_debugInfo_renameTime = '0;  // rewrite-omitted (nonfunc)
  assign io_out_1_1_bits_debugInfo_dispatchTime = '0;  // rewrite-omitted (nonfunc)
  assign io_out_1_1_bits_debugInfo_writebackTime = '0;  // rewrite-omitted (nonfunc)
  assign io_out_1_1_bits_debugInfo_runahead_checkpoint_id = '0;  // rewrite-omitted (nonfunc)
  assign io_out_1_1_bits_debugInfo_tlbFirstReqTime = '0;  // rewrite-omitted (nonfunc)
  assign io_out_1_1_bits_debugInfo_tlbRespTime = '0;  // rewrite-omitted (nonfunc)
  assign io_out_1_1_bits_debug_seqNum = '0;  // rewrite-omitted (nonfunc)
  assign io_out_1_0_bits_debugInfo_eliminatedMove = '0;  // rewrite-omitted (nonfunc)
  assign io_out_1_0_bits_debugInfo_renameTime = '0;  // rewrite-omitted (nonfunc)
  assign io_out_1_0_bits_debugInfo_dispatchTime = '0;  // rewrite-omitted (nonfunc)
  assign io_out_1_0_bits_debugInfo_writebackTime = '0;  // rewrite-omitted (nonfunc)
  assign io_out_1_0_bits_debugInfo_runahead_checkpoint_id = '0;  // rewrite-omitted (nonfunc)
  assign io_out_1_0_bits_debugInfo_tlbFirstReqTime = '0;  // rewrite-omitted (nonfunc)
  assign io_out_1_0_bits_debugInfo_tlbRespTime = '0;  // rewrite-omitted (nonfunc)
  assign io_out_1_0_bits_debug_seqNum = '0;  // rewrite-omitted (nonfunc)
  assign io_out_0_1_bits_data_0 = '0;  // rewrite-omitted (nonfunc)
  assign io_out_0_1_bits_debugInfo_eliminatedMove = '0;  // rewrite-omitted (nonfunc)
  assign io_out_0_1_bits_debugInfo_renameTime = '0;  // rewrite-omitted (nonfunc)
  assign io_out_0_1_bits_debugInfo_dispatchTime = '0;  // rewrite-omitted (nonfunc)
  assign io_out_0_1_bits_debugInfo_writebackTime = '0;  // rewrite-omitted (nonfunc)
  assign io_out_0_1_bits_debugInfo_runahead_checkpoint_id = '0;  // rewrite-omitted (nonfunc)
  assign io_out_0_1_bits_debugInfo_tlbFirstReqTime = '0;  // rewrite-omitted (nonfunc)
  assign io_out_0_1_bits_debugInfo_tlbRespTime = '0;  // rewrite-omitted (nonfunc)
  assign io_out_0_1_bits_debug_seqNum = '0;  // rewrite-omitted (nonfunc)
  assign io_out_0_0_bits_debugInfo_eliminatedMove = '0;  // rewrite-omitted (nonfunc)
  assign io_out_0_0_bits_debugInfo_renameTime = '0;  // rewrite-omitted (nonfunc)
  assign io_out_0_0_bits_debugInfo_dispatchTime = '0;  // rewrite-omitted (nonfunc)
  assign io_out_0_0_bits_debugInfo_writebackTime = '0;  // rewrite-omitted (nonfunc)
  assign io_out_0_0_bits_debugInfo_runahead_checkpoint_id = '0;  // rewrite-omitted (nonfunc)
  assign io_out_0_0_bits_debugInfo_tlbFirstReqTime = '0;  // rewrite-omitted (nonfunc)
  assign io_out_0_0_bits_debugInfo_tlbRespTime = '0;  // rewrite-omitted (nonfunc)
  assign io_out_0_0_bits_debug_seqNum = '0;  // rewrite-omitted (nonfunc)
endmodule
