// 自动生成:scripts/gen_coupledl2.py —— 勿手改(顶层 glue 为从 firtool 意图的具名可读重写)

// 可读核端口表(与 golden TL2CHICoupledL2 同名扁平端口,供 FM/ST 对接)。
// clock/reset 在核声明处单列,这里只列功能端口。
//   auto_in_0..3_*   北侧 TileLink client 节点(接 L1/core,A/B/C/D/E 五通道)
//   auto_mmioBridge_* MMIO(uncacheable)请求桥端口
//   io_chi_*         南侧 CHI 五通道 + 链路层(接 L3/home node)
//   io_perf_*        48 路性能计数;io_l2Miss/io_l2_hint/io_debugTopDown 监视
//   io_*PrefetchRecv_* prefetch 接收;io_error/io_nodeID/io_msStatus 等边界
  output auto_mmioBridge_mmio_in_a_ready,
  input auto_mmioBridge_mmio_in_a_valid,
  input [3:0] auto_mmioBridge_mmio_in_a_bits_opcode,
  input [2:0] auto_mmioBridge_mmio_in_a_bits_param,
  input [1:0] auto_mmioBridge_mmio_in_a_bits_size,
  input [2:0] auto_mmioBridge_mmio_in_a_bits_source,
  input [47:0] auto_mmioBridge_mmio_in_a_bits_address,
  input auto_mmioBridge_mmio_in_a_bits_user_memBackType_MM,
  input auto_mmioBridge_mmio_in_a_bits_user_memPageType_NC,
  input [7:0] auto_mmioBridge_mmio_in_a_bits_mask,
  input [63:0] auto_mmioBridge_mmio_in_a_bits_data,
  input auto_mmioBridge_mmio_in_a_bits_corrupt,
  input auto_mmioBridge_mmio_in_d_ready,
  output auto_mmioBridge_mmio_in_d_valid,
  output [3:0] auto_mmioBridge_mmio_in_d_bits_opcode,
  output [1:0] auto_mmioBridge_mmio_in_d_bits_param,
  output [1:0] auto_mmioBridge_mmio_in_d_bits_size,
  output [2:0] auto_mmioBridge_mmio_in_d_bits_source,
  output auto_mmioBridge_mmio_in_d_bits_sink,
  output auto_mmioBridge_mmio_in_d_bits_denied,
  output [63:0] auto_mmioBridge_mmio_in_d_bits_data,
  output auto_mmioBridge_mmio_in_d_bits_corrupt,
  output auto_in_3_a_ready,
  input auto_in_3_a_valid,
  input [3:0] auto_in_3_a_bits_opcode,
  input [2:0] auto_in_3_a_bits_param,
  input [2:0] auto_in_3_a_bits_size,
  input [6:0] auto_in_3_a_bits_source,
  input [47:0] auto_in_3_a_bits_address,
  input [4:0] auto_in_3_a_bits_user_reqSource,
  input [1:0] auto_in_3_a_bits_user_alias,
  input [43:0] auto_in_3_a_bits_user_vaddr,
  input auto_in_3_a_bits_user_needHint,
  input auto_in_3_a_bits_echo_isKeyword,
  input auto_in_3_a_bits_corrupt,
  input auto_in_3_b_ready,
  output auto_in_3_b_valid,
  output [2:0] auto_in_3_b_bits_opcode,
  output [1:0] auto_in_3_b_bits_param,
  output [47:0] auto_in_3_b_bits_address,
  output [255:0] auto_in_3_b_bits_data,
  output auto_in_3_c_ready,
  input auto_in_3_c_valid,
  input [2:0] auto_in_3_c_bits_opcode,
  input [2:0] auto_in_3_c_bits_param,
  input [2:0] auto_in_3_c_bits_size,
  input [6:0] auto_in_3_c_bits_source,
  input [47:0] auto_in_3_c_bits_address,
  input [255:0] auto_in_3_c_bits_data,
  input auto_in_3_c_bits_corrupt,
  input auto_in_3_d_ready,
  output auto_in_3_d_valid,
  output [3:0] auto_in_3_d_bits_opcode,
  output [1:0] auto_in_3_d_bits_param,
  output [6:0] auto_in_3_d_bits_source,
  output [7:0] auto_in_3_d_bits_sink,
  output auto_in_3_d_bits_denied,
  output auto_in_3_d_bits_echo_isKeyword,
  output [255:0] auto_in_3_d_bits_data,
  output auto_in_3_d_bits_corrupt,
  input auto_in_3_e_valid,
  input [7:0] auto_in_3_e_bits_sink,
  output auto_in_2_a_ready,
  input auto_in_2_a_valid,
  input [3:0] auto_in_2_a_bits_opcode,
  input [2:0] auto_in_2_a_bits_param,
  input [2:0] auto_in_2_a_bits_size,
  input [6:0] auto_in_2_a_bits_source,
  input [47:0] auto_in_2_a_bits_address,
  input [4:0] auto_in_2_a_bits_user_reqSource,
  input [1:0] auto_in_2_a_bits_user_alias,
  input [43:0] auto_in_2_a_bits_user_vaddr,
  input auto_in_2_a_bits_user_needHint,
  input auto_in_2_a_bits_echo_isKeyword,
  input auto_in_2_a_bits_corrupt,
  input auto_in_2_b_ready,
  output auto_in_2_b_valid,
  output [2:0] auto_in_2_b_bits_opcode,
  output [1:0] auto_in_2_b_bits_param,
  output [47:0] auto_in_2_b_bits_address,
  output [255:0] auto_in_2_b_bits_data,
  output auto_in_2_c_ready,
  input auto_in_2_c_valid,
  input [2:0] auto_in_2_c_bits_opcode,
  input [2:0] auto_in_2_c_bits_param,
  input [2:0] auto_in_2_c_bits_size,
  input [6:0] auto_in_2_c_bits_source,
  input [47:0] auto_in_2_c_bits_address,
  input [255:0] auto_in_2_c_bits_data,
  input auto_in_2_c_bits_corrupt,
  input auto_in_2_d_ready,
  output auto_in_2_d_valid,
  output [3:0] auto_in_2_d_bits_opcode,
  output [1:0] auto_in_2_d_bits_param,
  output [6:0] auto_in_2_d_bits_source,
  output [7:0] auto_in_2_d_bits_sink,
  output auto_in_2_d_bits_denied,
  output auto_in_2_d_bits_echo_isKeyword,
  output [255:0] auto_in_2_d_bits_data,
  output auto_in_2_d_bits_corrupt,
  input auto_in_2_e_valid,
  input [7:0] auto_in_2_e_bits_sink,
  output auto_in_1_a_ready,
  input auto_in_1_a_valid,
  input [3:0] auto_in_1_a_bits_opcode,
  input [2:0] auto_in_1_a_bits_param,
  input [2:0] auto_in_1_a_bits_size,
  input [6:0] auto_in_1_a_bits_source,
  input [47:0] auto_in_1_a_bits_address,
  input [4:0] auto_in_1_a_bits_user_reqSource,
  input [1:0] auto_in_1_a_bits_user_alias,
  input [43:0] auto_in_1_a_bits_user_vaddr,
  input auto_in_1_a_bits_user_needHint,
  input auto_in_1_a_bits_echo_isKeyword,
  input auto_in_1_a_bits_corrupt,
  input auto_in_1_b_ready,
  output auto_in_1_b_valid,
  output [2:0] auto_in_1_b_bits_opcode,
  output [1:0] auto_in_1_b_bits_param,
  output [47:0] auto_in_1_b_bits_address,
  output [255:0] auto_in_1_b_bits_data,
  output auto_in_1_c_ready,
  input auto_in_1_c_valid,
  input [2:0] auto_in_1_c_bits_opcode,
  input [2:0] auto_in_1_c_bits_param,
  input [2:0] auto_in_1_c_bits_size,
  input [6:0] auto_in_1_c_bits_source,
  input [47:0] auto_in_1_c_bits_address,
  input [255:0] auto_in_1_c_bits_data,
  input auto_in_1_c_bits_corrupt,
  input auto_in_1_d_ready,
  output auto_in_1_d_valid,
  output [3:0] auto_in_1_d_bits_opcode,
  output [1:0] auto_in_1_d_bits_param,
  output [6:0] auto_in_1_d_bits_source,
  output [7:0] auto_in_1_d_bits_sink,
  output auto_in_1_d_bits_denied,
  output auto_in_1_d_bits_echo_isKeyword,
  output [255:0] auto_in_1_d_bits_data,
  output auto_in_1_d_bits_corrupt,
  input auto_in_1_e_valid,
  input [7:0] auto_in_1_e_bits_sink,
  output auto_in_0_a_ready,
  input auto_in_0_a_valid,
  input [3:0] auto_in_0_a_bits_opcode,
  input [2:0] auto_in_0_a_bits_param,
  input [2:0] auto_in_0_a_bits_size,
  input [6:0] auto_in_0_a_bits_source,
  input [47:0] auto_in_0_a_bits_address,
  input [4:0] auto_in_0_a_bits_user_reqSource,
  input [1:0] auto_in_0_a_bits_user_alias,
  input [43:0] auto_in_0_a_bits_user_vaddr,
  input auto_in_0_a_bits_user_needHint,
  input auto_in_0_a_bits_echo_isKeyword,
  input auto_in_0_a_bits_corrupt,
  input auto_in_0_b_ready,
  output auto_in_0_b_valid,
  output [2:0] auto_in_0_b_bits_opcode,
  output [1:0] auto_in_0_b_bits_param,
  output [47:0] auto_in_0_b_bits_address,
  output [255:0] auto_in_0_b_bits_data,
  output auto_in_0_c_ready,
  input auto_in_0_c_valid,
  input [2:0] auto_in_0_c_bits_opcode,
  input [2:0] auto_in_0_c_bits_param,
  input [2:0] auto_in_0_c_bits_size,
  input [6:0] auto_in_0_c_bits_source,
  input [47:0] auto_in_0_c_bits_address,
  input [255:0] auto_in_0_c_bits_data,
  input auto_in_0_c_bits_corrupt,
  input auto_in_0_d_ready,
  output auto_in_0_d_valid,
  output [3:0] auto_in_0_d_bits_opcode,
  output [1:0] auto_in_0_d_bits_param,
  output [6:0] auto_in_0_d_bits_source,
  output [7:0] auto_in_0_d_bits_sink,
  output auto_in_0_d_bits_denied,
  output auto_in_0_d_bits_echo_isKeyword,
  output [255:0] auto_in_0_d_bits_data,
  output auto_in_0_d_bits_corrupt,
  input auto_in_0_e_valid,
  input [7:0] auto_in_0_e_bits_sink,
  input [63:0] auto_pf_recv_in_addr,
  input [4:0] auto_pf_recv_in_pf_source,
  input auto_pf_recv_in_addr_valid,
  input io_pfCtrlFromCore_l2_pf_master_en,
  input io_pfCtrlFromCore_l2_pf_recv_en,
  input io_pfCtrlFromCore_l2_pbop_en,
  input io_pfCtrlFromCore_l2_vbop_en,
  output io_l2_hint_valid,
  output [31:0] io_l2_hint_bits_sourceId,
  output io_l2_hint_bits_isKeyword,
  output io_l2_tlb_req_req_valid,
  output [49:0] io_l2_tlb_req_req_bits_vaddr,
  output [2:0] io_l2_tlb_req_req_bits_cmd,
  output io_l2_tlb_req_req_bits_kill,
  output io_l2_tlb_req_req_bits_no_translate,
  input io_l2_tlb_req_resp_valid,
  input [47:0] io_l2_tlb_req_resp_bits_paddr_0,
  input [1:0] io_l2_tlb_req_resp_bits_pbmt,
  input io_l2_tlb_req_resp_bits_miss,
  input io_l2_tlb_req_resp_bits_excp_0_gpf_ld,
  input io_l2_tlb_req_resp_bits_excp_0_pf_ld,
  input io_l2_tlb_req_resp_bits_excp_0_af_ld,
  input io_l2_tlb_req_pmp_resp_ld,
  input io_l2_tlb_req_pmp_resp_mmio,
  input io_debugTopDown_robHeadPaddr_valid,
  input [35:0] io_debugTopDown_robHeadPaddr_bits,
  output io_debugTopDown_l2MissMatch,
  output io_l2Miss,
  output io_error_valid,
  output [45:0] io_error_address,
  input io_dft_ram_hold,
  input io_dft_ram_bypass,
  input io_dft_ram_bp_clken,
  input io_dft_ram_aux_clk,
  input io_dft_ram_aux_ckbp,
  input io_dft_ram_mcp_hold,
  input io_dft_cgen,
  output [5:0] io_perf_1_value,
  output [5:0] io_perf_2_value,
  output [5:0] io_perf_3_value,
  output [5:0] io_perf_4_value,
  output [5:0] io_perf_5_value,
  output [5:0] io_perf_6_value,
  output [5:0] io_perf_7_value,
  output [5:0] io_perf_8_value,
  output [5:0] io_perf_9_value,
  output [5:0] io_perf_10_value,
  output [5:0] io_perf_11_value,
  output [5:0] io_perf_12_value,
  output [5:0] io_perf_13_value,
  output [5:0] io_perf_14_value,
  output [5:0] io_perf_15_value,
  output [5:0] io_perf_16_value,
  output [5:0] io_perf_17_value,
  output [5:0] io_perf_18_value,
  output [5:0] io_perf_19_value,
  output [5:0] io_perf_20_value,
  output [5:0] io_perf_21_value,
  output [5:0] io_perf_22_value,
  output [5:0] io_perf_23_value,
  output [5:0] io_perf_24_value,
  output [5:0] io_perf_25_value,
  output [5:0] io_perf_26_value,
  output [5:0] io_perf_27_value,
  output [5:0] io_perf_28_value,
  output [5:0] io_perf_29_value,
  output [5:0] io_perf_30_value,
  output [5:0] io_perf_31_value,
  output [5:0] io_perf_32_value,
  output [5:0] io_perf_33_value,
  output [5:0] io_perf_34_value,
  output [5:0] io_perf_35_value,
  output [5:0] io_perf_36_value,
  output [5:0] io_perf_37_value,
  output [5:0] io_perf_38_value,
  output [5:0] io_perf_39_value,
  output [5:0] io_perf_40_value,
  output [5:0] io_perf_41_value,
  output [5:0] io_perf_42_value,
  output [5:0] io_perf_43_value,
  output [5:0] io_perf_44_value,
  output [5:0] io_perf_45_value,
  output [5:0] io_perf_46_value,
  output [5:0] io_perf_47_value,
  output [5:0] io_perf_48_value,
  output io_chi_txsactive,
  input io_chi_rxsactive,
  output io_chi_syscoreq,
  input io_chi_syscoack,
  output io_chi_tx_linkactivereq,
  input io_chi_tx_linkactiveack,
  output io_chi_tx_req_flitpend,
  output io_chi_tx_req_flitv,
  output [161:0] io_chi_tx_req_flit,
  input io_chi_tx_req_lcrdv,
  output io_chi_tx_rsp_flitpend,
  output io_chi_tx_rsp_flitv,
  output [72:0] io_chi_tx_rsp_flit,
  input io_chi_tx_rsp_lcrdv,
  output io_chi_tx_dat_flitpend,
  output io_chi_tx_dat_flitv,
  output [421:0] io_chi_tx_dat_flit,
  input io_chi_tx_dat_lcrdv,
  input io_chi_rx_linkactivereq,
  output io_chi_rx_linkactiveack,
  input io_chi_rx_rsp_flitpend,
  input io_chi_rx_rsp_flitv,
  input [72:0] io_chi_rx_rsp_flit,
  output io_chi_rx_rsp_lcrdv,
  input io_chi_rx_dat_flitpend,
  input io_chi_rx_dat_flitv,
  input [421:0] io_chi_rx_dat_flit,
  output io_chi_rx_dat_lcrdv,
  input io_chi_rx_snp_flitpend,
  input io_chi_rx_snp_flitv,
  input [114:0] io_chi_rx_snp_flit,
  output io_chi_rx_snp_lcrdv,
  input [10:0] io_nodeID
