// 自动生成:scripts/gen_l2top.py —— 勿手改(顶层 glue 为从 Scala 意图的可读重写)

// 子模块(golden 黑盒)输出/互联网声明,宽度从 golden wire 声明收割。
//   _inner_<inst>_*  : 子模块输出网(含 diplomacy 扁平 TileLink 引脚);
//   inner_io_chi_*   : CHI 输出网(子模块输出引脚 -> 此 wire -> io assign)。
// 由 l2top_inst.svh 绑定子模块输出引脚,互联直连 / outassign 消费。

  logic inner_io_chi_rx_snp_lcrdv;
  logic inner_io_chi_rx_dat_lcrdv;
  logic inner_io_chi_rx_rsp_lcrdv;
  logic inner_io_chi_rx_linkactiveack;
  logic [421:0] inner_io_chi_tx_dat_flit;
  logic inner_io_chi_tx_dat_flitv;
  logic inner_io_chi_tx_dat_flitpend;
  logic [72:0] inner_io_chi_tx_rsp_flit;
  logic inner_io_chi_tx_rsp_flitv;
  logic inner_io_chi_tx_rsp_flitpend;
  logic [161:0] inner_io_chi_tx_req_flit;
  logic inner_io_chi_tx_req_flitv;
  logic inner_io_chi_tx_req_flitpend;
  logic inner_io_chi_tx_linkactivereq;
  logic inner_io_chi_syscoreq;
  logic inner_io_chi_txsactive;
  logic _inner_buffer_1_auto_in_a_ready;
  logic _inner_buffer_1_auto_in_d_valid;
  logic [3:0] _inner_buffer_1_auto_in_d_bits_opcode;
  logic [1:0] _inner_buffer_1_auto_in_d_bits_param;
  logic [1:0] _inner_buffer_1_auto_in_d_bits_size;
  logic [2:0] _inner_buffer_1_auto_in_d_bits_source;
  logic _inner_buffer_1_auto_in_d_bits_sink;
  logic _inner_buffer_1_auto_in_d_bits_denied;
  logic [63:0] _inner_buffer_1_auto_in_d_bits_data;
  logic _inner_buffer_1_auto_in_d_bits_corrupt;
  logic _inner_buffer_1_auto_out_a_valid;
  logic [3:0] _inner_buffer_1_auto_out_a_bits_opcode;
  logic [2:0] _inner_buffer_1_auto_out_a_bits_param;
  logic [1:0] _inner_buffer_1_auto_out_a_bits_size;
  logic [2:0] _inner_buffer_1_auto_out_a_bits_source;
  logic [47:0] _inner_buffer_1_auto_out_a_bits_address;
  logic _inner_buffer_1_auto_out_a_bits_user_memBackType_MM;
  logic _inner_buffer_1_auto_out_a_bits_user_memPageType_NC;
  logic [7:0] _inner_buffer_1_auto_out_a_bits_mask;
  logic [63:0] _inner_buffer_1_auto_out_a_bits_data;
  logic _inner_buffer_1_auto_out_a_bits_corrupt;
  logic _inner_buffer_1_auto_out_d_ready;
  logic _inner_buffers_5_auto_in_a_ready;
  logic _inner_buffers_5_auto_in_d_valid;
  logic [3:0] _inner_buffers_5_auto_in_d_bits_opcode;
  logic [1:0] _inner_buffers_5_auto_in_d_bits_param;
  logic [1:0] _inner_buffers_5_auto_in_d_bits_size;
  logic [2:0] _inner_buffers_5_auto_in_d_bits_source;
  logic _inner_buffers_5_auto_in_d_bits_sink;
  logic _inner_buffers_5_auto_in_d_bits_denied;
  logic [63:0] _inner_buffers_5_auto_in_d_bits_data;
  logic _inner_buffers_5_auto_in_d_bits_corrupt;
  logic _inner_buffers_4_auto_in_a_ready;
  logic _inner_buffers_4_auto_in_d_valid;
  logic [3:0] _inner_buffers_4_auto_in_d_bits_opcode;
  logic [1:0] _inner_buffers_4_auto_in_d_bits_param;
  logic [1:0] _inner_buffers_4_auto_in_d_bits_size;
  logic [2:0] _inner_buffers_4_auto_in_d_bits_source;
  logic _inner_buffers_4_auto_in_d_bits_sink;
  logic _inner_buffers_4_auto_in_d_bits_denied;
  logic [63:0] _inner_buffers_4_auto_in_d_bits_data;
  logic _inner_buffers_4_auto_in_d_bits_corrupt;
  logic _inner_buffers_4_auto_out_a_valid;
  logic [3:0] _inner_buffers_4_auto_out_a_bits_opcode;
  logic [1:0] _inner_buffers_4_auto_out_a_bits_size;
  logic [2:0] _inner_buffers_4_auto_out_a_bits_source;
  logic [29:0] _inner_buffers_4_auto_out_a_bits_address;
  logic [7:0] _inner_buffers_4_auto_out_a_bits_mask;
  logic [63:0] _inner_buffers_4_auto_out_a_bits_data;
  logic _inner_buffers_4_auto_out_d_ready;
  logic _inner_buffers_3_auto_out_a_valid;
  logic [3:0] _inner_buffers_3_auto_out_a_bits_opcode;
  logic [2:0] _inner_buffers_3_auto_out_a_bits_param;
  logic [1:0] _inner_buffers_3_auto_out_a_bits_size;
  logic [1:0] _inner_buffers_3_auto_out_a_bits_source;
  logic [47:0] _inner_buffers_3_auto_out_a_bits_address;
  logic _inner_buffers_3_auto_out_a_bits_user_memPageType_NC;
  logic _inner_buffers_3_auto_out_a_bits_user_memBackType_MM;
  logic [7:0] _inner_buffers_3_auto_out_a_bits_mask;
  logic [63:0] _inner_buffers_3_auto_out_a_bits_data;
  logic _inner_buffers_3_auto_out_a_bits_corrupt;
  logic _inner_buffers_3_auto_out_d_ready;
  logic _inner_buffers_2_auto_in_a_ready;
  logic _inner_buffers_2_auto_in_d_valid;
  logic [3:0] _inner_buffers_2_auto_in_d_bits_opcode;
  logic [1:0] _inner_buffers_2_auto_in_d_bits_param;
  logic [1:0] _inner_buffers_2_auto_in_d_bits_size;
  logic [1:0] _inner_buffers_2_auto_in_d_bits_source;
  logic _inner_buffers_2_auto_in_d_bits_sink;
  logic _inner_buffers_2_auto_in_d_bits_denied;
  logic [63:0] _inner_buffers_2_auto_in_d_bits_data;
  logic _inner_buffers_2_auto_in_d_bits_corrupt;
  logic _inner_buffers_2_auto_out_a_valid;
  logic [3:0] _inner_buffers_2_auto_out_a_bits_opcode;
  logic [2:0] _inner_buffers_2_auto_out_a_bits_param;
  logic [1:0] _inner_buffers_2_auto_out_a_bits_size;
  logic [1:0] _inner_buffers_2_auto_out_a_bits_source;
  logic [47:0] _inner_buffers_2_auto_out_a_bits_address;
  logic _inner_buffers_2_auto_out_a_bits_user_memPageType_NC;
  logic _inner_buffers_2_auto_out_a_bits_user_memBackType_MM;
  logic [7:0] _inner_buffers_2_auto_out_a_bits_mask;
  logic [63:0] _inner_buffers_2_auto_out_a_bits_data;
  logic _inner_buffers_2_auto_out_a_bits_corrupt;
  logic _inner_buffers_2_auto_out_d_ready;
  logic _inner_buffers_1_auto_in_a_ready;
  logic _inner_buffers_1_auto_in_d_valid;
  logic [3:0] _inner_buffers_1_auto_in_d_bits_opcode;
  logic [1:0] _inner_buffers_1_auto_in_d_bits_param;
  logic [1:0] _inner_buffers_1_auto_in_d_bits_size;
  logic _inner_buffers_1_auto_in_d_bits_source;
  logic _inner_buffers_1_auto_in_d_bits_sink;
  logic _inner_buffers_1_auto_in_d_bits_denied;
  logic [63:0] _inner_buffers_1_auto_in_d_bits_data;
  logic _inner_buffers_1_auto_in_d_bits_corrupt;
  logic _inner_buffers_1_auto_out_a_valid;
  logic [3:0] _inner_buffers_1_auto_out_a_bits_opcode;
  logic [2:0] _inner_buffers_1_auto_out_a_bits_param;
  logic [1:0] _inner_buffers_1_auto_out_a_bits_size;
  logic _inner_buffers_1_auto_out_a_bits_source;
  logic [47:0] _inner_buffers_1_auto_out_a_bits_address;
  logic [7:0] _inner_buffers_1_auto_out_a_bits_mask;
  logic [63:0] _inner_buffers_1_auto_out_a_bits_data;
  logic _inner_buffers_1_auto_out_a_bits_corrupt;
  logic _inner_buffers_1_auto_out_d_ready;
  logic _inner_buffers_auto_in_a_ready;
  logic _inner_buffers_auto_in_d_valid;
  logic [3:0] _inner_buffers_auto_in_d_bits_opcode;
  logic [1:0] _inner_buffers_auto_in_d_bits_param;
  logic [1:0] _inner_buffers_auto_in_d_bits_size;
  logic _inner_buffers_auto_in_d_bits_source;
  logic _inner_buffers_auto_in_d_bits_sink;
  logic _inner_buffers_auto_in_d_bits_denied;
  logic [63:0] _inner_buffers_auto_in_d_bits_data;
  logic _inner_buffers_auto_in_d_bits_corrupt;
  logic _inner_buffers_auto_out_a_valid;
  logic [3:0] _inner_buffers_auto_out_a_bits_opcode;
  logic [2:0] _inner_buffers_auto_out_a_bits_param;
  logic [1:0] _inner_buffers_auto_out_a_bits_size;
  logic _inner_buffers_auto_out_a_bits_source;
  logic [47:0] _inner_buffers_auto_out_a_bits_address;
  logic [7:0] _inner_buffers_auto_out_a_bits_mask;
  logic [63:0] _inner_buffers_auto_out_a_bits_data;
  logic _inner_buffers_auto_out_a_bits_corrupt;
  logic _inner_buffers_auto_out_d_ready;
  logic _inner_l2cache_auto_mmioBridge_mmio_in_a_ready;
  logic _inner_l2cache_auto_mmioBridge_mmio_in_d_valid;
  logic [3:0] _inner_l2cache_auto_mmioBridge_mmio_in_d_bits_opcode;
  logic [1:0] _inner_l2cache_auto_mmioBridge_mmio_in_d_bits_param;
  logic [1:0] _inner_l2cache_auto_mmioBridge_mmio_in_d_bits_size;
  logic [2:0] _inner_l2cache_auto_mmioBridge_mmio_in_d_bits_source;
  logic _inner_l2cache_auto_mmioBridge_mmio_in_d_bits_sink;
  logic _inner_l2cache_auto_mmioBridge_mmio_in_d_bits_denied;
  logic [63:0] _inner_l2cache_auto_mmioBridge_mmio_in_d_bits_data;
  logic _inner_l2cache_auto_mmioBridge_mmio_in_d_bits_corrupt;
  logic _inner_l2cache_auto_in_3_a_ready;
  logic _inner_l2cache_auto_in_3_b_valid;
  logic [2:0] _inner_l2cache_auto_in_3_b_bits_opcode;
  logic [1:0] _inner_l2cache_auto_in_3_b_bits_param;
  logic [47:0] _inner_l2cache_auto_in_3_b_bits_address;
  logic [255:0] _inner_l2cache_auto_in_3_b_bits_data;
  logic _inner_l2cache_auto_in_3_c_ready;
  logic _inner_l2cache_auto_in_3_d_valid;
  logic [3:0] _inner_l2cache_auto_in_3_d_bits_opcode;
  logic [1:0] _inner_l2cache_auto_in_3_d_bits_param;
  logic [6:0] _inner_l2cache_auto_in_3_d_bits_source;
  logic [7:0] _inner_l2cache_auto_in_3_d_bits_sink;
  logic _inner_l2cache_auto_in_3_d_bits_denied;
  logic _inner_l2cache_auto_in_3_d_bits_echo_isKeyword;
  logic [255:0] _inner_l2cache_auto_in_3_d_bits_data;
  logic _inner_l2cache_auto_in_3_d_bits_corrupt;
  logic _inner_l2cache_auto_in_2_a_ready;
  logic _inner_l2cache_auto_in_2_b_valid;
  logic [2:0] _inner_l2cache_auto_in_2_b_bits_opcode;
  logic [1:0] _inner_l2cache_auto_in_2_b_bits_param;
  logic [47:0] _inner_l2cache_auto_in_2_b_bits_address;
  logic [255:0] _inner_l2cache_auto_in_2_b_bits_data;
  logic _inner_l2cache_auto_in_2_c_ready;
  logic _inner_l2cache_auto_in_2_d_valid;
  logic [3:0] _inner_l2cache_auto_in_2_d_bits_opcode;
  logic [1:0] _inner_l2cache_auto_in_2_d_bits_param;
  logic [6:0] _inner_l2cache_auto_in_2_d_bits_source;
  logic [7:0] _inner_l2cache_auto_in_2_d_bits_sink;
  logic _inner_l2cache_auto_in_2_d_bits_denied;
  logic _inner_l2cache_auto_in_2_d_bits_echo_isKeyword;
  logic [255:0] _inner_l2cache_auto_in_2_d_bits_data;
  logic _inner_l2cache_auto_in_2_d_bits_corrupt;
  logic _inner_l2cache_auto_in_1_a_ready;
  logic _inner_l2cache_auto_in_1_b_valid;
  logic [2:0] _inner_l2cache_auto_in_1_b_bits_opcode;
  logic [1:0] _inner_l2cache_auto_in_1_b_bits_param;
  logic [47:0] _inner_l2cache_auto_in_1_b_bits_address;
  logic [255:0] _inner_l2cache_auto_in_1_b_bits_data;
  logic _inner_l2cache_auto_in_1_c_ready;
  logic _inner_l2cache_auto_in_1_d_valid;
  logic [3:0] _inner_l2cache_auto_in_1_d_bits_opcode;
  logic [1:0] _inner_l2cache_auto_in_1_d_bits_param;
  logic [6:0] _inner_l2cache_auto_in_1_d_bits_source;
  logic [7:0] _inner_l2cache_auto_in_1_d_bits_sink;
  logic _inner_l2cache_auto_in_1_d_bits_denied;
  logic _inner_l2cache_auto_in_1_d_bits_echo_isKeyword;
  logic [255:0] _inner_l2cache_auto_in_1_d_bits_data;
  logic _inner_l2cache_auto_in_1_d_bits_corrupt;
  logic _inner_l2cache_auto_in_0_a_ready;
  logic _inner_l2cache_auto_in_0_b_valid;
  logic [2:0] _inner_l2cache_auto_in_0_b_bits_opcode;
  logic [1:0] _inner_l2cache_auto_in_0_b_bits_param;
  logic [47:0] _inner_l2cache_auto_in_0_b_bits_address;
  logic [255:0] _inner_l2cache_auto_in_0_b_bits_data;
  logic _inner_l2cache_auto_in_0_c_ready;
  logic _inner_l2cache_auto_in_0_d_valid;
  logic [3:0] _inner_l2cache_auto_in_0_d_bits_opcode;
  logic [1:0] _inner_l2cache_auto_in_0_d_bits_param;
  logic [6:0] _inner_l2cache_auto_in_0_d_bits_source;
  logic [7:0] _inner_l2cache_auto_in_0_d_bits_sink;
  logic _inner_l2cache_auto_in_0_d_bits_denied;
  logic _inner_l2cache_auto_in_0_d_bits_echo_isKeyword;
  logic [255:0] _inner_l2cache_auto_in_0_d_bits_data;
  logic _inner_l2cache_auto_in_0_d_bits_corrupt;
  logic [31:0] _inner_l2cache_io_l2_hint_bits_sourceId;
  logic _inner_l2cache_io_error_valid;
  logic [45:0] _inner_l2cache_io_error_address;
  logic _inner_i_mmio_buffer_auto_out_a_valid;
  logic [3:0] _inner_i_mmio_buffer_auto_out_a_bits_opcode;
  logic [2:0] _inner_i_mmio_buffer_auto_out_a_bits_param;
  logic [1:0] _inner_i_mmio_buffer_auto_out_a_bits_size;
  logic _inner_i_mmio_buffer_auto_out_a_bits_source;
  logic [47:0] _inner_i_mmio_buffer_auto_out_a_bits_address;
  logic [7:0] _inner_i_mmio_buffer_auto_out_a_bits_mask;
  logic [63:0] _inner_i_mmio_buffer_auto_out_a_bits_data;
  logic _inner_i_mmio_buffer_auto_out_a_bits_corrupt;
  logic _inner_i_mmio_buffer_auto_out_d_ready;
  logic _inner_ptw_to_l2_buffer_auto_out_a_valid;
  logic [3:0] _inner_ptw_to_l2_buffer_auto_out_a_bits_opcode;
  logic [2:0] _inner_ptw_to_l2_buffer_auto_out_a_bits_param;
  logic [2:0] _inner_ptw_to_l2_buffer_auto_out_a_bits_size;
  logic [2:0] _inner_ptw_to_l2_buffer_auto_out_a_bits_source;
  logic [47:0] _inner_ptw_to_l2_buffer_auto_out_a_bits_address;
  logic [4:0] _inner_ptw_to_l2_buffer_auto_out_a_bits_user_reqSource;
  logic [31:0] _inner_ptw_to_l2_buffer_auto_out_a_bits_mask;
  logic [255:0] _inner_ptw_to_l2_buffer_auto_out_a_bits_data;
  logic _inner_ptw_to_l2_buffer_auto_out_a_bits_corrupt;
  logic _inner_ptw_to_l2_buffer_auto_out_d_ready;
  logic _inner_logger_2_auto_in_a_ready;
  logic _inner_logger_2_auto_in_d_valid;
  logic [3:0] _inner_logger_2_auto_in_d_bits_opcode;
  logic [1:0] _inner_logger_2_auto_in_d_bits_param;
  logic [2:0] _inner_logger_2_auto_in_d_bits_size;
  logic [2:0] _inner_logger_2_auto_in_d_bits_source;
  logic [9:0] _inner_logger_2_auto_in_d_bits_sink;
  logic _inner_logger_2_auto_in_d_bits_denied;
  logic [255:0] _inner_logger_2_auto_in_d_bits_data;
  logic _inner_logger_2_auto_in_d_bits_corrupt;
  logic _inner_logger_2_auto_out_a_valid;
  logic [3:0] _inner_logger_2_auto_out_a_bits_opcode;
  logic [2:0] _inner_logger_2_auto_out_a_bits_param;
  logic [2:0] _inner_logger_2_auto_out_a_bits_size;
  logic [2:0] _inner_logger_2_auto_out_a_bits_source;
  logic [47:0] _inner_logger_2_auto_out_a_bits_address;
  logic [4:0] _inner_logger_2_auto_out_a_bits_user_reqSource;
  logic [31:0] _inner_logger_2_auto_out_a_bits_mask;
  logic [255:0] _inner_logger_2_auto_out_a_bits_data;
  logic _inner_logger_2_auto_out_a_bits_corrupt;
  logic _inner_logger_2_auto_out_d_ready;
  logic _inner_logger_1_auto_out_a_valid;
  logic [3:0] _inner_logger_1_auto_out_a_bits_opcode;
  logic [2:0] _inner_logger_1_auto_out_a_bits_param;
  logic [2:0] _inner_logger_1_auto_out_a_bits_size;
  logic [3:0] _inner_logger_1_auto_out_a_bits_source;
  logic [47:0] _inner_logger_1_auto_out_a_bits_address;
  logic [1:0] _inner_logger_1_auto_out_a_bits_user_alias;
  logic [4:0] _inner_logger_1_auto_out_a_bits_user_reqSource;
  logic _inner_logger_1_auto_out_a_bits_user_needHint;
  logic [31:0] _inner_logger_1_auto_out_a_bits_mask;
  logic [255:0] _inner_logger_1_auto_out_a_bits_data;
  logic _inner_logger_1_auto_out_a_bits_corrupt;
  logic _inner_logger_1_auto_out_d_ready;
  logic _inner_logger_auto_out_a_valid;
  logic [3:0] _inner_logger_auto_out_a_bits_opcode;
  logic [2:0] _inner_logger_auto_out_a_bits_param;
  logic [2:0] _inner_logger_auto_out_a_bits_size;
  logic [5:0] _inner_logger_auto_out_a_bits_source;
  logic [47:0] _inner_logger_auto_out_a_bits_address;
  logic [1:0] _inner_logger_auto_out_a_bits_user_alias;
  logic [43:0] _inner_logger_auto_out_a_bits_user_vaddr;
  logic [4:0] _inner_logger_auto_out_a_bits_user_reqSource;
  logic _inner_logger_auto_out_a_bits_user_needHint;
  logic _inner_logger_auto_out_a_bits_echo_isKeyword;
  logic [31:0] _inner_logger_auto_out_a_bits_mask;
  logic [255:0] _inner_logger_auto_out_a_bits_data;
  logic _inner_logger_auto_out_a_bits_corrupt;
  logic _inner_logger_auto_out_b_ready;
  logic _inner_logger_auto_out_c_valid;
  logic [2:0] _inner_logger_auto_out_c_bits_opcode;
  logic [2:0] _inner_logger_auto_out_c_bits_param;
  logic [2:0] _inner_logger_auto_out_c_bits_size;
  logic [5:0] _inner_logger_auto_out_c_bits_source;
  logic [47:0] _inner_logger_auto_out_c_bits_address;
  logic [1:0] _inner_logger_auto_out_c_bits_user_alias;
  logic [43:0] _inner_logger_auto_out_c_bits_user_vaddr;
  logic [4:0] _inner_logger_auto_out_c_bits_user_reqSource;
  logic _inner_logger_auto_out_c_bits_user_needHint;
  logic _inner_logger_auto_out_c_bits_echo_isKeyword;
  logic [255:0] _inner_logger_auto_out_c_bits_data;
  logic _inner_logger_auto_out_c_bits_corrupt;
  logic _inner_logger_auto_out_d_ready;
  logic _inner_logger_auto_out_e_valid;
  logic [9:0] _inner_logger_auto_out_e_bits_sink;
  logic _inner_buffer_auto_in_3_a_ready;
  logic _inner_buffer_auto_in_3_b_valid;
  logic [2:0] _inner_buffer_auto_in_3_b_bits_opcode;
  logic [1:0] _inner_buffer_auto_in_3_b_bits_param;
  logic [2:0] _inner_buffer_auto_in_3_b_bits_size;
  logic [6:0] _inner_buffer_auto_in_3_b_bits_source;
  logic [47:0] _inner_buffer_auto_in_3_b_bits_address;
  logic [31:0] _inner_buffer_auto_in_3_b_bits_mask;
  logic [255:0] _inner_buffer_auto_in_3_b_bits_data;
  logic _inner_buffer_auto_in_3_b_bits_corrupt;
  logic _inner_buffer_auto_in_3_c_ready;
  logic _inner_buffer_auto_in_3_d_valid;
  logic [3:0] _inner_buffer_auto_in_3_d_bits_opcode;
  logic [1:0] _inner_buffer_auto_in_3_d_bits_param;
  logic [2:0] _inner_buffer_auto_in_3_d_bits_size;
  logic [6:0] _inner_buffer_auto_in_3_d_bits_source;
  logic [7:0] _inner_buffer_auto_in_3_d_bits_sink;
  logic _inner_buffer_auto_in_3_d_bits_denied;
  logic _inner_buffer_auto_in_3_d_bits_echo_isKeyword;
  logic [255:0] _inner_buffer_auto_in_3_d_bits_data;
  logic _inner_buffer_auto_in_3_d_bits_corrupt;
  logic _inner_buffer_auto_in_3_e_ready;
  logic _inner_buffer_auto_in_2_a_ready;
  logic _inner_buffer_auto_in_2_b_valid;
  logic [2:0] _inner_buffer_auto_in_2_b_bits_opcode;
  logic [1:0] _inner_buffer_auto_in_2_b_bits_param;
  logic [2:0] _inner_buffer_auto_in_2_b_bits_size;
  logic [6:0] _inner_buffer_auto_in_2_b_bits_source;
  logic [47:0] _inner_buffer_auto_in_2_b_bits_address;
  logic [31:0] _inner_buffer_auto_in_2_b_bits_mask;
  logic [255:0] _inner_buffer_auto_in_2_b_bits_data;
  logic _inner_buffer_auto_in_2_b_bits_corrupt;
  logic _inner_buffer_auto_in_2_c_ready;
  logic _inner_buffer_auto_in_2_d_valid;
  logic [3:0] _inner_buffer_auto_in_2_d_bits_opcode;
  logic [1:0] _inner_buffer_auto_in_2_d_bits_param;
  logic [2:0] _inner_buffer_auto_in_2_d_bits_size;
  logic [6:0] _inner_buffer_auto_in_2_d_bits_source;
  logic [7:0] _inner_buffer_auto_in_2_d_bits_sink;
  logic _inner_buffer_auto_in_2_d_bits_denied;
  logic _inner_buffer_auto_in_2_d_bits_echo_isKeyword;
  logic [255:0] _inner_buffer_auto_in_2_d_bits_data;
  logic _inner_buffer_auto_in_2_d_bits_corrupt;
  logic _inner_buffer_auto_in_2_e_ready;
  logic _inner_buffer_auto_in_1_a_ready;
  logic _inner_buffer_auto_in_1_b_valid;
  logic [2:0] _inner_buffer_auto_in_1_b_bits_opcode;
  logic [1:0] _inner_buffer_auto_in_1_b_bits_param;
  logic [2:0] _inner_buffer_auto_in_1_b_bits_size;
  logic [6:0] _inner_buffer_auto_in_1_b_bits_source;
  logic [47:0] _inner_buffer_auto_in_1_b_bits_address;
  logic [31:0] _inner_buffer_auto_in_1_b_bits_mask;
  logic [255:0] _inner_buffer_auto_in_1_b_bits_data;
  logic _inner_buffer_auto_in_1_b_bits_corrupt;
  logic _inner_buffer_auto_in_1_c_ready;
  logic _inner_buffer_auto_in_1_d_valid;
  logic [3:0] _inner_buffer_auto_in_1_d_bits_opcode;
  logic [1:0] _inner_buffer_auto_in_1_d_bits_param;
  logic [2:0] _inner_buffer_auto_in_1_d_bits_size;
  logic [6:0] _inner_buffer_auto_in_1_d_bits_source;
  logic [7:0] _inner_buffer_auto_in_1_d_bits_sink;
  logic _inner_buffer_auto_in_1_d_bits_denied;
  logic _inner_buffer_auto_in_1_d_bits_echo_isKeyword;
  logic [255:0] _inner_buffer_auto_in_1_d_bits_data;
  logic _inner_buffer_auto_in_1_d_bits_corrupt;
  logic _inner_buffer_auto_in_1_e_ready;
  logic _inner_buffer_auto_in_0_a_ready;
  logic _inner_buffer_auto_in_0_b_valid;
  logic [2:0] _inner_buffer_auto_in_0_b_bits_opcode;
  logic [1:0] _inner_buffer_auto_in_0_b_bits_param;
  logic [2:0] _inner_buffer_auto_in_0_b_bits_size;
  logic [6:0] _inner_buffer_auto_in_0_b_bits_source;
  logic [47:0] _inner_buffer_auto_in_0_b_bits_address;
  logic [31:0] _inner_buffer_auto_in_0_b_bits_mask;
  logic [255:0] _inner_buffer_auto_in_0_b_bits_data;
  logic _inner_buffer_auto_in_0_b_bits_corrupt;
  logic _inner_buffer_auto_in_0_c_ready;
  logic _inner_buffer_auto_in_0_d_valid;
  logic [3:0] _inner_buffer_auto_in_0_d_bits_opcode;
  logic [1:0] _inner_buffer_auto_in_0_d_bits_param;
  logic [2:0] _inner_buffer_auto_in_0_d_bits_size;
  logic [6:0] _inner_buffer_auto_in_0_d_bits_source;
  logic [7:0] _inner_buffer_auto_in_0_d_bits_sink;
  logic _inner_buffer_auto_in_0_d_bits_denied;
  logic _inner_buffer_auto_in_0_d_bits_echo_isKeyword;
  logic [255:0] _inner_buffer_auto_in_0_d_bits_data;
  logic _inner_buffer_auto_in_0_d_bits_corrupt;
  logic _inner_buffer_auto_in_0_e_ready;
  logic _inner_buffer_auto_out_3_a_valid;
  logic [3:0] _inner_buffer_auto_out_3_a_bits_opcode;
  logic [2:0] _inner_buffer_auto_out_3_a_bits_param;
  logic [2:0] _inner_buffer_auto_out_3_a_bits_size;
  logic [6:0] _inner_buffer_auto_out_3_a_bits_source;
  logic [47:0] _inner_buffer_auto_out_3_a_bits_address;
  logic [4:0] _inner_buffer_auto_out_3_a_bits_user_reqSource;
  logic [1:0] _inner_buffer_auto_out_3_a_bits_user_alias;
  logic [43:0] _inner_buffer_auto_out_3_a_bits_user_vaddr;
  logic _inner_buffer_auto_out_3_a_bits_user_needHint;
  logic _inner_buffer_auto_out_3_a_bits_echo_isKeyword;
  logic _inner_buffer_auto_out_3_a_bits_corrupt;
  logic _inner_buffer_auto_out_3_b_ready;
  logic _inner_buffer_auto_out_3_c_valid;
  logic [2:0] _inner_buffer_auto_out_3_c_bits_opcode;
  logic [2:0] _inner_buffer_auto_out_3_c_bits_param;
  logic [2:0] _inner_buffer_auto_out_3_c_bits_size;
  logic [6:0] _inner_buffer_auto_out_3_c_bits_source;
  logic [47:0] _inner_buffer_auto_out_3_c_bits_address;
  logic [255:0] _inner_buffer_auto_out_3_c_bits_data;
  logic _inner_buffer_auto_out_3_c_bits_corrupt;
  logic _inner_buffer_auto_out_3_d_ready;
  logic _inner_buffer_auto_out_3_e_valid;
  logic [7:0] _inner_buffer_auto_out_3_e_bits_sink;
  logic _inner_buffer_auto_out_2_a_valid;
  logic [3:0] _inner_buffer_auto_out_2_a_bits_opcode;
  logic [2:0] _inner_buffer_auto_out_2_a_bits_param;
  logic [2:0] _inner_buffer_auto_out_2_a_bits_size;
  logic [6:0] _inner_buffer_auto_out_2_a_bits_source;
  logic [47:0] _inner_buffer_auto_out_2_a_bits_address;
  logic [4:0] _inner_buffer_auto_out_2_a_bits_user_reqSource;
  logic [1:0] _inner_buffer_auto_out_2_a_bits_user_alias;
  logic [43:0] _inner_buffer_auto_out_2_a_bits_user_vaddr;
  logic _inner_buffer_auto_out_2_a_bits_user_needHint;
  logic _inner_buffer_auto_out_2_a_bits_echo_isKeyword;
  logic _inner_buffer_auto_out_2_a_bits_corrupt;
  logic _inner_buffer_auto_out_2_b_ready;
  logic _inner_buffer_auto_out_2_c_valid;
  logic [2:0] _inner_buffer_auto_out_2_c_bits_opcode;
  logic [2:0] _inner_buffer_auto_out_2_c_bits_param;
  logic [2:0] _inner_buffer_auto_out_2_c_bits_size;
  logic [6:0] _inner_buffer_auto_out_2_c_bits_source;
  logic [47:0] _inner_buffer_auto_out_2_c_bits_address;
  logic [255:0] _inner_buffer_auto_out_2_c_bits_data;
  logic _inner_buffer_auto_out_2_c_bits_corrupt;
  logic _inner_buffer_auto_out_2_d_ready;
  logic _inner_buffer_auto_out_2_e_valid;
  logic [7:0] _inner_buffer_auto_out_2_e_bits_sink;
  logic _inner_buffer_auto_out_1_a_valid;
  logic [3:0] _inner_buffer_auto_out_1_a_bits_opcode;
  logic [2:0] _inner_buffer_auto_out_1_a_bits_param;
  logic [2:0] _inner_buffer_auto_out_1_a_bits_size;
  logic [6:0] _inner_buffer_auto_out_1_a_bits_source;
  logic [47:0] _inner_buffer_auto_out_1_a_bits_address;
  logic [4:0] _inner_buffer_auto_out_1_a_bits_user_reqSource;
  logic [1:0] _inner_buffer_auto_out_1_a_bits_user_alias;
  logic [43:0] _inner_buffer_auto_out_1_a_bits_user_vaddr;
  logic _inner_buffer_auto_out_1_a_bits_user_needHint;
  logic _inner_buffer_auto_out_1_a_bits_echo_isKeyword;
  logic _inner_buffer_auto_out_1_a_bits_corrupt;
  logic _inner_buffer_auto_out_1_b_ready;
  logic _inner_buffer_auto_out_1_c_valid;
  logic [2:0] _inner_buffer_auto_out_1_c_bits_opcode;
  logic [2:0] _inner_buffer_auto_out_1_c_bits_param;
  logic [2:0] _inner_buffer_auto_out_1_c_bits_size;
  logic [6:0] _inner_buffer_auto_out_1_c_bits_source;
  logic [47:0] _inner_buffer_auto_out_1_c_bits_address;
  logic [255:0] _inner_buffer_auto_out_1_c_bits_data;
  logic _inner_buffer_auto_out_1_c_bits_corrupt;
  logic _inner_buffer_auto_out_1_d_ready;
  logic _inner_buffer_auto_out_1_e_valid;
  logic [7:0] _inner_buffer_auto_out_1_e_bits_sink;
  logic _inner_buffer_auto_out_0_a_valid;
  logic [3:0] _inner_buffer_auto_out_0_a_bits_opcode;
  logic [2:0] _inner_buffer_auto_out_0_a_bits_param;
  logic [2:0] _inner_buffer_auto_out_0_a_bits_size;
  logic [6:0] _inner_buffer_auto_out_0_a_bits_source;
  logic [47:0] _inner_buffer_auto_out_0_a_bits_address;
  logic [4:0] _inner_buffer_auto_out_0_a_bits_user_reqSource;
  logic [1:0] _inner_buffer_auto_out_0_a_bits_user_alias;
  logic [43:0] _inner_buffer_auto_out_0_a_bits_user_vaddr;
  logic _inner_buffer_auto_out_0_a_bits_user_needHint;
  logic _inner_buffer_auto_out_0_a_bits_echo_isKeyword;
  logic _inner_buffer_auto_out_0_a_bits_corrupt;
  logic _inner_buffer_auto_out_0_b_ready;
  logic _inner_buffer_auto_out_0_c_valid;
  logic [2:0] _inner_buffer_auto_out_0_c_bits_opcode;
  logic [2:0] _inner_buffer_auto_out_0_c_bits_param;
  logic [2:0] _inner_buffer_auto_out_0_c_bits_size;
  logic [6:0] _inner_buffer_auto_out_0_c_bits_source;
  logic [47:0] _inner_buffer_auto_out_0_c_bits_address;
  logic [255:0] _inner_buffer_auto_out_0_c_bits_data;
  logic _inner_buffer_auto_out_0_c_bits_corrupt;
  logic _inner_buffer_auto_out_0_d_ready;
  logic _inner_buffer_auto_out_0_e_valid;
  logic [7:0] _inner_buffer_auto_out_0_e_bits_sink;
  logic _inner_busPMU_auto_in_2_a_ready;
  logic _inner_busPMU_auto_in_2_d_valid;
  logic [3:0] _inner_busPMU_auto_in_2_d_bits_opcode;
  logic [1:0] _inner_busPMU_auto_in_2_d_bits_param;
  logic [2:0] _inner_busPMU_auto_in_2_d_bits_size;
  logic [2:0] _inner_busPMU_auto_in_2_d_bits_source;
  logic [9:0] _inner_busPMU_auto_in_2_d_bits_sink;
  logic _inner_busPMU_auto_in_2_d_bits_denied;
  logic [255:0] _inner_busPMU_auto_in_2_d_bits_data;
  logic _inner_busPMU_auto_in_2_d_bits_corrupt;
  logic _inner_busPMU_auto_in_1_a_ready;
  logic _inner_busPMU_auto_in_1_d_valid;
  logic [3:0] _inner_busPMU_auto_in_1_d_bits_opcode;
  logic [1:0] _inner_busPMU_auto_in_1_d_bits_param;
  logic [2:0] _inner_busPMU_auto_in_1_d_bits_size;
  logic [3:0] _inner_busPMU_auto_in_1_d_bits_source;
  logic [9:0] _inner_busPMU_auto_in_1_d_bits_sink;
  logic _inner_busPMU_auto_in_1_d_bits_denied;
  logic [255:0] _inner_busPMU_auto_in_1_d_bits_data;
  logic _inner_busPMU_auto_in_1_d_bits_corrupt;
  logic _inner_busPMU_auto_in_0_a_ready;
  logic _inner_busPMU_auto_in_0_b_valid;
  logic [2:0] _inner_busPMU_auto_in_0_b_bits_opcode;
  logic [1:0] _inner_busPMU_auto_in_0_b_bits_param;
  logic [2:0] _inner_busPMU_auto_in_0_b_bits_size;
  logic [5:0] _inner_busPMU_auto_in_0_b_bits_source;
  logic [47:0] _inner_busPMU_auto_in_0_b_bits_address;
  logic [31:0] _inner_busPMU_auto_in_0_b_bits_mask;
  logic [255:0] _inner_busPMU_auto_in_0_b_bits_data;
  logic _inner_busPMU_auto_in_0_b_bits_corrupt;
  logic _inner_busPMU_auto_in_0_c_ready;
  logic _inner_busPMU_auto_in_0_d_valid;
  logic [3:0] _inner_busPMU_auto_in_0_d_bits_opcode;
  logic [1:0] _inner_busPMU_auto_in_0_d_bits_param;
  logic [2:0] _inner_busPMU_auto_in_0_d_bits_size;
  logic [5:0] _inner_busPMU_auto_in_0_d_bits_source;
  logic [9:0] _inner_busPMU_auto_in_0_d_bits_sink;
  logic _inner_busPMU_auto_in_0_d_bits_denied;
  logic _inner_busPMU_auto_in_0_d_bits_echo_isKeyword;
  logic [255:0] _inner_busPMU_auto_in_0_d_bits_data;
  logic _inner_busPMU_auto_in_0_d_bits_corrupt;
  logic _inner_busPMU_auto_in_0_e_ready;
  logic _inner_busPMU_auto_out_2_a_valid;
  logic [3:0] _inner_busPMU_auto_out_2_a_bits_opcode;
  logic [2:0] _inner_busPMU_auto_out_2_a_bits_param;
  logic [2:0] _inner_busPMU_auto_out_2_a_bits_size;
  logic [2:0] _inner_busPMU_auto_out_2_a_bits_source;
  logic [47:0] _inner_busPMU_auto_out_2_a_bits_address;
  logic [4:0] _inner_busPMU_auto_out_2_a_bits_user_reqSource;
  logic [31:0] _inner_busPMU_auto_out_2_a_bits_mask;
  logic [255:0] _inner_busPMU_auto_out_2_a_bits_data;
  logic _inner_busPMU_auto_out_2_a_bits_corrupt;
  logic _inner_busPMU_auto_out_2_d_ready;
  logic _inner_busPMU_auto_out_1_a_valid;
  logic [3:0] _inner_busPMU_auto_out_1_a_bits_opcode;
  logic [2:0] _inner_busPMU_auto_out_1_a_bits_param;
  logic [2:0] _inner_busPMU_auto_out_1_a_bits_size;
  logic [3:0] _inner_busPMU_auto_out_1_a_bits_source;
  logic [47:0] _inner_busPMU_auto_out_1_a_bits_address;
  logic [1:0] _inner_busPMU_auto_out_1_a_bits_user_alias;
  logic [4:0] _inner_busPMU_auto_out_1_a_bits_user_reqSource;
  logic _inner_busPMU_auto_out_1_a_bits_user_needHint;
  logic [31:0] _inner_busPMU_auto_out_1_a_bits_mask;
  logic [255:0] _inner_busPMU_auto_out_1_a_bits_data;
  logic _inner_busPMU_auto_out_1_a_bits_corrupt;
  logic _inner_busPMU_auto_out_1_d_ready;
  logic _inner_busPMU_auto_out_0_a_valid;
  logic [3:0] _inner_busPMU_auto_out_0_a_bits_opcode;
  logic [2:0] _inner_busPMU_auto_out_0_a_bits_param;
  logic [2:0] _inner_busPMU_auto_out_0_a_bits_size;
  logic [5:0] _inner_busPMU_auto_out_0_a_bits_source;
  logic [47:0] _inner_busPMU_auto_out_0_a_bits_address;
  logic [1:0] _inner_busPMU_auto_out_0_a_bits_user_alias;
  logic [43:0] _inner_busPMU_auto_out_0_a_bits_user_vaddr;
  logic [4:0] _inner_busPMU_auto_out_0_a_bits_user_reqSource;
  logic _inner_busPMU_auto_out_0_a_bits_user_needHint;
  logic _inner_busPMU_auto_out_0_a_bits_echo_isKeyword;
  logic [31:0] _inner_busPMU_auto_out_0_a_bits_mask;
  logic [255:0] _inner_busPMU_auto_out_0_a_bits_data;
  logic _inner_busPMU_auto_out_0_a_bits_corrupt;
  logic _inner_busPMU_auto_out_0_b_ready;
  logic _inner_busPMU_auto_out_0_c_valid;
  logic [2:0] _inner_busPMU_auto_out_0_c_bits_opcode;
  logic [2:0] _inner_busPMU_auto_out_0_c_bits_param;
  logic [2:0] _inner_busPMU_auto_out_0_c_bits_size;
  logic [5:0] _inner_busPMU_auto_out_0_c_bits_source;
  logic [47:0] _inner_busPMU_auto_out_0_c_bits_address;
  logic [1:0] _inner_busPMU_auto_out_0_c_bits_user_alias;
  logic [43:0] _inner_busPMU_auto_out_0_c_bits_user_vaddr;
  logic [4:0] _inner_busPMU_auto_out_0_c_bits_user_reqSource;
  logic _inner_busPMU_auto_out_0_c_bits_user_needHint;
  logic _inner_busPMU_auto_out_0_c_bits_echo_isKeyword;
  logic [255:0] _inner_busPMU_auto_out_0_c_bits_data;
  logic _inner_busPMU_auto_out_0_c_bits_corrupt;
  logic _inner_busPMU_auto_out_0_d_ready;
  logic _inner_busPMU_auto_out_0_e_valid;
  logic [9:0] _inner_busPMU_auto_out_0_e_bits_sink;
  logic _inner_beu_auto_in_a_ready;
  logic _inner_beu_auto_in_d_valid;
  logic [3:0] _inner_beu_auto_in_d_bits_opcode;
  logic [1:0] _inner_beu_auto_in_d_bits_size;
  logic [2:0] _inner_beu_auto_in_d_bits_source;
  logic [63:0] _inner_beu_auto_in_d_bits_data;
  logic _inner_xbar_1_auto_in_1_a_ready;
  logic _inner_xbar_1_auto_in_1_d_valid;
  logic [3:0] _inner_xbar_1_auto_in_1_d_bits_opcode;
  logic [1:0] _inner_xbar_1_auto_in_1_d_bits_param;
  logic [1:0] _inner_xbar_1_auto_in_1_d_bits_size;
  logic [1:0] _inner_xbar_1_auto_in_1_d_bits_source;
  logic _inner_xbar_1_auto_in_1_d_bits_sink;
  logic _inner_xbar_1_auto_in_1_d_bits_denied;
  logic [63:0] _inner_xbar_1_auto_in_1_d_bits_data;
  logic _inner_xbar_1_auto_in_1_d_bits_corrupt;
  logic _inner_xbar_1_auto_in_0_a_ready;
  logic _inner_xbar_1_auto_in_0_d_valid;
  logic [3:0] _inner_xbar_1_auto_in_0_d_bits_opcode;
  logic [1:0] _inner_xbar_1_auto_in_0_d_bits_param;
  logic [1:0] _inner_xbar_1_auto_in_0_d_bits_size;
  logic _inner_xbar_1_auto_in_0_d_bits_sink;
  logic _inner_xbar_1_auto_in_0_d_bits_denied;
  logic [63:0] _inner_xbar_1_auto_in_0_d_bits_data;
  logic _inner_xbar_1_auto_in_0_d_bits_corrupt;
  logic _inner_xbar_1_auto_out_2_a_valid;
  logic [3:0] _inner_xbar_1_auto_out_2_a_bits_opcode;
  logic [2:0] _inner_xbar_1_auto_out_2_a_bits_param;
  logic [1:0] _inner_xbar_1_auto_out_2_a_bits_size;
  logic [2:0] _inner_xbar_1_auto_out_2_a_bits_source;
  logic [47:0] _inner_xbar_1_auto_out_2_a_bits_address;
  logic _inner_xbar_1_auto_out_2_a_bits_user_memBackType_MM;
  logic _inner_xbar_1_auto_out_2_a_bits_user_memPageType_NC;
  logic [7:0] _inner_xbar_1_auto_out_2_a_bits_mask;
  logic [63:0] _inner_xbar_1_auto_out_2_a_bits_data;
  logic _inner_xbar_1_auto_out_2_a_bits_corrupt;
  logic _inner_xbar_1_auto_out_2_d_ready;
  logic _inner_xbar_1_auto_out_1_a_valid;
  logic [3:0] _inner_xbar_1_auto_out_1_a_bits_opcode;
  logic [2:0] _inner_xbar_1_auto_out_1_a_bits_param;
  logic [1:0] _inner_xbar_1_auto_out_1_a_bits_size;
  logic [2:0] _inner_xbar_1_auto_out_1_a_bits_source;
  logic [29:0] _inner_xbar_1_auto_out_1_a_bits_address;
  logic [7:0] _inner_xbar_1_auto_out_1_a_bits_mask;
  logic [63:0] _inner_xbar_1_auto_out_1_a_bits_data;
  logic _inner_xbar_1_auto_out_1_a_bits_corrupt;
  logic _inner_xbar_1_auto_out_1_d_ready;
  logic _inner_xbar_1_auto_out_0_a_valid;
  logic [3:0] _inner_xbar_1_auto_out_0_a_bits_opcode;
  logic [2:0] _inner_xbar_1_auto_out_0_a_bits_param;
  logic [1:0] _inner_xbar_1_auto_out_0_a_bits_size;
  logic [2:0] _inner_xbar_1_auto_out_0_a_bits_source;
  logic [29:0] _inner_xbar_1_auto_out_0_a_bits_address;
  logic [7:0] _inner_xbar_1_auto_out_0_a_bits_mask;
  logic [63:0] _inner_xbar_1_auto_out_0_a_bits_data;
  logic _inner_xbar_1_auto_out_0_a_bits_corrupt;
  logic _inner_xbar_1_auto_out_0_d_ready;
  logic _inner_xbar_auto_in_2_a_ready;
  logic _inner_xbar_auto_in_2_d_valid;
  logic [3:0] _inner_xbar_auto_in_2_d_bits_opcode;
  logic [1:0] _inner_xbar_auto_in_2_d_bits_param;
  logic [2:0] _inner_xbar_auto_in_2_d_bits_size;
  logic [2:0] _inner_xbar_auto_in_2_d_bits_source;
  logic [9:0] _inner_xbar_auto_in_2_d_bits_sink;
  logic _inner_xbar_auto_in_2_d_bits_denied;
  logic [255:0] _inner_xbar_auto_in_2_d_bits_data;
  logic _inner_xbar_auto_in_2_d_bits_corrupt;
  logic _inner_xbar_auto_in_1_a_ready;
  logic _inner_xbar_auto_in_1_d_valid;
  logic [3:0] _inner_xbar_auto_in_1_d_bits_opcode;
  logic [1:0] _inner_xbar_auto_in_1_d_bits_param;
  logic [2:0] _inner_xbar_auto_in_1_d_bits_size;
  logic [3:0] _inner_xbar_auto_in_1_d_bits_source;
  logic [9:0] _inner_xbar_auto_in_1_d_bits_sink;
  logic _inner_xbar_auto_in_1_d_bits_denied;
  logic [255:0] _inner_xbar_auto_in_1_d_bits_data;
  logic _inner_xbar_auto_in_1_d_bits_corrupt;
  logic _inner_xbar_auto_in_0_a_ready;
  logic _inner_xbar_auto_in_0_b_valid;
  logic [2:0] _inner_xbar_auto_in_0_b_bits_opcode;
  logic [1:0] _inner_xbar_auto_in_0_b_bits_param;
  logic [2:0] _inner_xbar_auto_in_0_b_bits_size;
  logic [5:0] _inner_xbar_auto_in_0_b_bits_source;
  logic [47:0] _inner_xbar_auto_in_0_b_bits_address;
  logic [31:0] _inner_xbar_auto_in_0_b_bits_mask;
  logic [255:0] _inner_xbar_auto_in_0_b_bits_data;
  logic _inner_xbar_auto_in_0_b_bits_corrupt;
  logic _inner_xbar_auto_in_0_c_ready;
  logic _inner_xbar_auto_in_0_d_valid;
  logic [3:0] _inner_xbar_auto_in_0_d_bits_opcode;
  logic [1:0] _inner_xbar_auto_in_0_d_bits_param;
  logic [2:0] _inner_xbar_auto_in_0_d_bits_size;
  logic [5:0] _inner_xbar_auto_in_0_d_bits_source;
  logic [9:0] _inner_xbar_auto_in_0_d_bits_sink;
  logic _inner_xbar_auto_in_0_d_bits_denied;
  logic _inner_xbar_auto_in_0_d_bits_echo_isKeyword;
  logic [255:0] _inner_xbar_auto_in_0_d_bits_data;
  logic _inner_xbar_auto_in_0_d_bits_corrupt;
  logic _inner_xbar_auto_in_0_e_ready;
  logic _inner_xbar_auto_out_3_a_valid;
  logic [3:0] _inner_xbar_auto_out_3_a_bits_opcode;
  logic [2:0] _inner_xbar_auto_out_3_a_bits_param;
  logic [2:0] _inner_xbar_auto_out_3_a_bits_size;
  logic [6:0] _inner_xbar_auto_out_3_a_bits_source;
  logic [47:0] _inner_xbar_auto_out_3_a_bits_address;
  logic [4:0] _inner_xbar_auto_out_3_a_bits_user_reqSource;
  logic [1:0] _inner_xbar_auto_out_3_a_bits_user_alias;
  logic [43:0] _inner_xbar_auto_out_3_a_bits_user_vaddr;
  logic _inner_xbar_auto_out_3_a_bits_user_needHint;
  logic _inner_xbar_auto_out_3_a_bits_echo_isKeyword;
  logic [31:0] _inner_xbar_auto_out_3_a_bits_mask;
  logic [255:0] _inner_xbar_auto_out_3_a_bits_data;
  logic _inner_xbar_auto_out_3_a_bits_corrupt;
  logic _inner_xbar_auto_out_3_b_ready;
  logic _inner_xbar_auto_out_3_c_valid;
  logic [2:0] _inner_xbar_auto_out_3_c_bits_opcode;
  logic [2:0] _inner_xbar_auto_out_3_c_bits_param;
  logic [2:0] _inner_xbar_auto_out_3_c_bits_size;
  logic [6:0] _inner_xbar_auto_out_3_c_bits_source;
  logic [47:0] _inner_xbar_auto_out_3_c_bits_address;
  logic [4:0] _inner_xbar_auto_out_3_c_bits_user_reqSource;
  logic [1:0] _inner_xbar_auto_out_3_c_bits_user_alias;
  logic [43:0] _inner_xbar_auto_out_3_c_bits_user_vaddr;
  logic _inner_xbar_auto_out_3_c_bits_user_needHint;
  logic _inner_xbar_auto_out_3_c_bits_echo_isKeyword;
  logic [255:0] _inner_xbar_auto_out_3_c_bits_data;
  logic _inner_xbar_auto_out_3_c_bits_corrupt;
  logic _inner_xbar_auto_out_3_d_ready;
  logic _inner_xbar_auto_out_3_e_valid;
  logic [7:0] _inner_xbar_auto_out_3_e_bits_sink;
  logic _inner_xbar_auto_out_2_a_valid;
  logic [3:0] _inner_xbar_auto_out_2_a_bits_opcode;
  logic [2:0] _inner_xbar_auto_out_2_a_bits_param;
  logic [2:0] _inner_xbar_auto_out_2_a_bits_size;
  logic [6:0] _inner_xbar_auto_out_2_a_bits_source;
  logic [47:0] _inner_xbar_auto_out_2_a_bits_address;
  logic [4:0] _inner_xbar_auto_out_2_a_bits_user_reqSource;
  logic [1:0] _inner_xbar_auto_out_2_a_bits_user_alias;
  logic [43:0] _inner_xbar_auto_out_2_a_bits_user_vaddr;
  logic _inner_xbar_auto_out_2_a_bits_user_needHint;
  logic _inner_xbar_auto_out_2_a_bits_echo_isKeyword;
  logic [31:0] _inner_xbar_auto_out_2_a_bits_mask;
  logic [255:0] _inner_xbar_auto_out_2_a_bits_data;
  logic _inner_xbar_auto_out_2_a_bits_corrupt;
  logic _inner_xbar_auto_out_2_b_ready;
  logic _inner_xbar_auto_out_2_c_valid;
  logic [2:0] _inner_xbar_auto_out_2_c_bits_opcode;
  logic [2:0] _inner_xbar_auto_out_2_c_bits_param;
  logic [2:0] _inner_xbar_auto_out_2_c_bits_size;
  logic [6:0] _inner_xbar_auto_out_2_c_bits_source;
  logic [47:0] _inner_xbar_auto_out_2_c_bits_address;
  logic [4:0] _inner_xbar_auto_out_2_c_bits_user_reqSource;
  logic [1:0] _inner_xbar_auto_out_2_c_bits_user_alias;
  logic [43:0] _inner_xbar_auto_out_2_c_bits_user_vaddr;
  logic _inner_xbar_auto_out_2_c_bits_user_needHint;
  logic _inner_xbar_auto_out_2_c_bits_echo_isKeyword;
  logic [255:0] _inner_xbar_auto_out_2_c_bits_data;
  logic _inner_xbar_auto_out_2_c_bits_corrupt;
  logic _inner_xbar_auto_out_2_d_ready;
  logic _inner_xbar_auto_out_2_e_valid;
  logic [7:0] _inner_xbar_auto_out_2_e_bits_sink;
  logic _inner_xbar_auto_out_1_a_valid;
  logic [3:0] _inner_xbar_auto_out_1_a_bits_opcode;
  logic [2:0] _inner_xbar_auto_out_1_a_bits_param;
  logic [2:0] _inner_xbar_auto_out_1_a_bits_size;
  logic [6:0] _inner_xbar_auto_out_1_a_bits_source;
  logic [47:0] _inner_xbar_auto_out_1_a_bits_address;
  logic [4:0] _inner_xbar_auto_out_1_a_bits_user_reqSource;
  logic [1:0] _inner_xbar_auto_out_1_a_bits_user_alias;
  logic [43:0] _inner_xbar_auto_out_1_a_bits_user_vaddr;
  logic _inner_xbar_auto_out_1_a_bits_user_needHint;
  logic _inner_xbar_auto_out_1_a_bits_echo_isKeyword;
  logic [31:0] _inner_xbar_auto_out_1_a_bits_mask;
  logic [255:0] _inner_xbar_auto_out_1_a_bits_data;
  logic _inner_xbar_auto_out_1_a_bits_corrupt;
  logic _inner_xbar_auto_out_1_b_ready;
  logic _inner_xbar_auto_out_1_c_valid;
  logic [2:0] _inner_xbar_auto_out_1_c_bits_opcode;
  logic [2:0] _inner_xbar_auto_out_1_c_bits_param;
  logic [2:0] _inner_xbar_auto_out_1_c_bits_size;
  logic [6:0] _inner_xbar_auto_out_1_c_bits_source;
  logic [47:0] _inner_xbar_auto_out_1_c_bits_address;
  logic [4:0] _inner_xbar_auto_out_1_c_bits_user_reqSource;
  logic [1:0] _inner_xbar_auto_out_1_c_bits_user_alias;
  logic [43:0] _inner_xbar_auto_out_1_c_bits_user_vaddr;
  logic _inner_xbar_auto_out_1_c_bits_user_needHint;
  logic _inner_xbar_auto_out_1_c_bits_echo_isKeyword;
  logic [255:0] _inner_xbar_auto_out_1_c_bits_data;
  logic _inner_xbar_auto_out_1_c_bits_corrupt;
  logic _inner_xbar_auto_out_1_d_ready;
  logic _inner_xbar_auto_out_1_e_valid;
  logic [7:0] _inner_xbar_auto_out_1_e_bits_sink;
  logic _inner_xbar_auto_out_0_a_valid;
  logic [3:0] _inner_xbar_auto_out_0_a_bits_opcode;
  logic [2:0] _inner_xbar_auto_out_0_a_bits_param;
  logic [2:0] _inner_xbar_auto_out_0_a_bits_size;
  logic [6:0] _inner_xbar_auto_out_0_a_bits_source;
  logic [47:0] _inner_xbar_auto_out_0_a_bits_address;
  logic [4:0] _inner_xbar_auto_out_0_a_bits_user_reqSource;
  logic [1:0] _inner_xbar_auto_out_0_a_bits_user_alias;
  logic [43:0] _inner_xbar_auto_out_0_a_bits_user_vaddr;
  logic _inner_xbar_auto_out_0_a_bits_user_needHint;
  logic _inner_xbar_auto_out_0_a_bits_echo_isKeyword;
  logic [31:0] _inner_xbar_auto_out_0_a_bits_mask;
  logic [255:0] _inner_xbar_auto_out_0_a_bits_data;
  logic _inner_xbar_auto_out_0_a_bits_corrupt;
  logic _inner_xbar_auto_out_0_b_ready;
  logic _inner_xbar_auto_out_0_c_valid;
  logic [2:0] _inner_xbar_auto_out_0_c_bits_opcode;
  logic [2:0] _inner_xbar_auto_out_0_c_bits_param;
  logic [2:0] _inner_xbar_auto_out_0_c_bits_size;
  logic [6:0] _inner_xbar_auto_out_0_c_bits_source;
  logic [47:0] _inner_xbar_auto_out_0_c_bits_address;
  logic [4:0] _inner_xbar_auto_out_0_c_bits_user_reqSource;
  logic [1:0] _inner_xbar_auto_out_0_c_bits_user_alias;
  logic [43:0] _inner_xbar_auto_out_0_c_bits_user_vaddr;
  logic _inner_xbar_auto_out_0_c_bits_user_needHint;
  logic _inner_xbar_auto_out_0_c_bits_echo_isKeyword;
  logic [255:0] _inner_xbar_auto_out_0_c_bits_data;
  logic _inner_xbar_auto_out_0_c_bits_corrupt;
  logic _inner_xbar_auto_out_0_d_ready;
  logic _inner_xbar_auto_out_0_e_valid;
  logic [7:0] _inner_xbar_auto_out_0_e_bits_sink;
