// MbistPipeL2Prefetcher 包装层(golden 同名扁平端口 ↔ xs_MbistPipeL2Prefetcher_core)。
// 端口逐一直连(golden 端口已是扁平标量), 仅供 FM impl 侧与 ST 替换。
module MbistPipeL2Prefetcher(
  input         clock,
  input         reset,
  input         mbist_array,
  input         mbist_all,
  input         mbist_req,
  output        mbist_ack,
  input         mbist_writeen,
  input         mbist_be,
  input  [8:0]  mbist_addr,
  input  [12:0] mbist_indata,
  input         mbist_readen,
  input  [8:0]  mbist_addr_rd,
  output [12:0] mbist_outdata,
  output [8:0]  toSRAM_0_addr,
  output [8:0]  toSRAM_0_addr_rd,
  output [12:0] toSRAM_0_wdata,
  output        toSRAM_0_wmask,
  output        toSRAM_0_re,
  output        toSRAM_0_we,
  input  [12:0] toSRAM_0_rdata,
  output        toSRAM_0_ack,
  output        toSRAM_0_selectedOH,
  output        toSRAM_0_array,
  output [8:0]  toSRAM_1_addr,
  output [8:0]  toSRAM_1_addr_rd,
  output [12:0] toSRAM_1_wdata,
  output        toSRAM_1_wmask,
  output        toSRAM_1_re,
  output        toSRAM_1_we,
  input  [12:0] toSRAM_1_rdata,
  output        toSRAM_1_ack,
  output        toSRAM_1_selectedOH,
  output        toSRAM_1_array
);

  xs_MbistPipeL2Prefetcher_core u_core (
    .clock              (clock),
    .reset              (reset),
    .mbist_array        (mbist_array),
    .mbist_all          (mbist_all),
    .mbist_req          (mbist_req),
    .mbist_ack          (mbist_ack),
    .mbist_writeen      (mbist_writeen),
    .mbist_be           (mbist_be),
    .mbist_addr         (mbist_addr),
    .mbist_indata       (mbist_indata),
    .mbist_readen       (mbist_readen),
    .mbist_addr_rd      (mbist_addr_rd),
    .mbist_outdata      (mbist_outdata),
    .toSRAM_0_addr      (toSRAM_0_addr),
    .toSRAM_0_addr_rd   (toSRAM_0_addr_rd),
    .toSRAM_0_wdata     (toSRAM_0_wdata),
    .toSRAM_0_wmask     (toSRAM_0_wmask),
    .toSRAM_0_re        (toSRAM_0_re),
    .toSRAM_0_we        (toSRAM_0_we),
    .toSRAM_0_rdata     (toSRAM_0_rdata),
    .toSRAM_0_ack       (toSRAM_0_ack),
    .toSRAM_0_selectedOH(toSRAM_0_selectedOH),
    .toSRAM_0_array     (toSRAM_0_array),
    .toSRAM_1_addr      (toSRAM_1_addr),
    .toSRAM_1_addr_rd   (toSRAM_1_addr_rd),
    .toSRAM_1_wdata     (toSRAM_1_wdata),
    .toSRAM_1_wmask     (toSRAM_1_wmask),
    .toSRAM_1_re        (toSRAM_1_re),
    .toSRAM_1_we        (toSRAM_1_we),
    .toSRAM_1_rdata     (toSRAM_1_rdata),
    .toSRAM_1_ack       (toSRAM_1_ack),
    .toSRAM_1_selectedOH(toSRAM_1_selectedOH),
    .toSRAM_1_array     (toSRAM_1_array)
  );

endmodule
