// MMIOBridgeEntry_4 包装层(golden 同名扁平端口 ↔ xs_MMIOBridgeEntry_core #(.ID_W(3)))。
module MMIOBridgeEntry_4(
  input          clock,
  input          reset,
  output         io_req_ready,
  input          io_req_valid,
  input  [3:0]   io_req_bits_opcode,
  input  [1:0]   io_req_bits_size,
  input  [2:0]   io_req_bits_source,
  input  [47:0]  io_req_bits_address,
  input          io_req_bits_user_memBackType_MM,
  input          io_req_bits_user_memPageType_NC,
  input  [7:0]   io_req_bits_mask,
  input  [63:0]  io_req_bits_data,
  input          io_req_bits_corrupt,
  input          io_resp_ready,
  output         io_resp_valid,
  output [3:0]   io_resp_bits_opcode,
  output [1:0]   io_resp_bits_size,
  output [2:0]   io_resp_bits_source,
  output         io_resp_bits_denied,
  output [63:0]  io_resp_bits_data,
  output         io_resp_bits_corrupt,
  input          io_chi_tx_req_ready,
  output         io_chi_tx_req_valid,
  output [11:0]  io_chi_tx_req_bits_txnID,
  output [6:0]   io_chi_tx_req_bits_opcode,
  output [2:0]   io_chi_tx_req_bits_size,
  output [47:0]  io_chi_tx_req_bits_addr,
  output         io_chi_tx_req_bits_allowRetry,
  output [1:0]   io_chi_tx_req_bits_order,
  output [3:0]   io_chi_tx_req_bits_pCrdType,
  output         io_chi_tx_req_bits_memAttr_device,
  output         io_chi_tx_req_bits_memAttr_ewa,
  input          io_chi_tx_dat_ready,
  output         io_chi_tx_dat_valid,
  output [10:0]  io_chi_tx_dat_bits_tgtID,
  output [11:0]  io_chi_tx_dat_bits_txnID,
  output [1:0]   io_chi_tx_dat_bits_respErr,
  output [1:0]   io_chi_tx_dat_bits_ccID,
  output [1:0]   io_chi_tx_dat_bits_dataID,
  output         io_chi_tx_dat_bits_traceTag,
  output [31:0]  io_chi_tx_dat_bits_be,
  output [255:0] io_chi_tx_dat_bits_data,
  output [31:0]  io_chi_tx_dat_bits_dataCheck,
  output [3:0]   io_chi_tx_dat_bits_poison,
  output         io_chi_rx_rsp_ready,
  input          io_chi_rx_rsp_valid,
  input  [10:0]  io_chi_rx_rsp_bits_srcID,
  input  [4:0]   io_chi_rx_rsp_bits_opcode,
  input  [1:0]   io_chi_rx_rsp_bits_respErr,
  input  [11:0]  io_chi_rx_rsp_bits_dbID,
  input  [3:0]   io_chi_rx_rsp_bits_pCrdType,
  input          io_chi_rx_rsp_bits_traceTag,
  output         io_chi_rx_dat_ready,
  input          io_chi_rx_dat_valid,
  input  [1:0]   io_chi_rx_dat_bits_respErr,
  input  [255:0] io_chi_rx_dat_bits_data,
  input  [31:0]  io_chi_rx_dat_bits_dataCheck,
  input  [3:0]   io_chi_rx_dat_bits_poison,
  input  [2:0]   io_id,
  output         io_pCrd_query_valid,
  output [3:0]   io_pCrd_query_bits_pCrdType,
  output [10:0]  io_pCrd_query_bits_srcID,
  input          io_pCrd_grant,
  output         io_waitOnReadReceipt
);

  xs_MMIOBridgeEntry_core #(.ID_W(3)) u_core (
    .clock(clock),
    .reset(reset),
    .io_req_ready(io_req_ready),
    .io_req_valid(io_req_valid),
    .io_req_bits_opcode(io_req_bits_opcode),
    .io_req_bits_size(io_req_bits_size),
    .io_req_bits_source(io_req_bits_source),
    .io_req_bits_address(io_req_bits_address),
    .io_req_bits_user_memBackType_MM(io_req_bits_user_memBackType_MM),
    .io_req_bits_user_memPageType_NC(io_req_bits_user_memPageType_NC),
    .io_req_bits_mask(io_req_bits_mask),
    .io_req_bits_data(io_req_bits_data),
    .io_req_bits_corrupt(io_req_bits_corrupt),
    .io_resp_ready(io_resp_ready),
    .io_resp_valid(io_resp_valid),
    .io_resp_bits_opcode(io_resp_bits_opcode),
    .io_resp_bits_size(io_resp_bits_size),
    .io_resp_bits_source(io_resp_bits_source),
    .io_resp_bits_denied(io_resp_bits_denied),
    .io_resp_bits_data(io_resp_bits_data),
    .io_resp_bits_corrupt(io_resp_bits_corrupt),
    .io_chi_tx_req_ready(io_chi_tx_req_ready),
    .io_chi_tx_req_valid(io_chi_tx_req_valid),
    .io_chi_tx_req_bits_txnID(io_chi_tx_req_bits_txnID),
    .io_chi_tx_req_bits_opcode(io_chi_tx_req_bits_opcode),
    .io_chi_tx_req_bits_size(io_chi_tx_req_bits_size),
    .io_chi_tx_req_bits_addr(io_chi_tx_req_bits_addr),
    .io_chi_tx_req_bits_allowRetry(io_chi_tx_req_bits_allowRetry),
    .io_chi_tx_req_bits_order(io_chi_tx_req_bits_order),
    .io_chi_tx_req_bits_pCrdType(io_chi_tx_req_bits_pCrdType),
    .io_chi_tx_req_bits_memAttr_device(io_chi_tx_req_bits_memAttr_device),
    .io_chi_tx_req_bits_memAttr_ewa(io_chi_tx_req_bits_memAttr_ewa),
    .io_chi_tx_dat_ready(io_chi_tx_dat_ready),
    .io_chi_tx_dat_valid(io_chi_tx_dat_valid),
    .io_chi_tx_dat_bits_tgtID(io_chi_tx_dat_bits_tgtID),
    .io_chi_tx_dat_bits_txnID(io_chi_tx_dat_bits_txnID),
    .io_chi_tx_dat_bits_respErr(io_chi_tx_dat_bits_respErr),
    .io_chi_tx_dat_bits_ccID(io_chi_tx_dat_bits_ccID),
    .io_chi_tx_dat_bits_dataID(io_chi_tx_dat_bits_dataID),
    .io_chi_tx_dat_bits_traceTag(io_chi_tx_dat_bits_traceTag),
    .io_chi_tx_dat_bits_be(io_chi_tx_dat_bits_be),
    .io_chi_tx_dat_bits_data(io_chi_tx_dat_bits_data),
    .io_chi_tx_dat_bits_dataCheck(io_chi_tx_dat_bits_dataCheck),
    .io_chi_tx_dat_bits_poison(io_chi_tx_dat_bits_poison),
    .io_chi_rx_rsp_ready(io_chi_rx_rsp_ready),
    .io_chi_rx_rsp_valid(io_chi_rx_rsp_valid),
    .io_chi_rx_rsp_bits_srcID(io_chi_rx_rsp_bits_srcID),
    .io_chi_rx_rsp_bits_opcode(io_chi_rx_rsp_bits_opcode),
    .io_chi_rx_rsp_bits_respErr(io_chi_rx_rsp_bits_respErr),
    .io_chi_rx_rsp_bits_dbID(io_chi_rx_rsp_bits_dbID),
    .io_chi_rx_rsp_bits_pCrdType(io_chi_rx_rsp_bits_pCrdType),
    .io_chi_rx_rsp_bits_traceTag(io_chi_rx_rsp_bits_traceTag),
    .io_chi_rx_dat_ready(io_chi_rx_dat_ready),
    .io_chi_rx_dat_valid(io_chi_rx_dat_valid),
    .io_chi_rx_dat_bits_respErr(io_chi_rx_dat_bits_respErr),
    .io_chi_rx_dat_bits_data(io_chi_rx_dat_bits_data),
    .io_chi_rx_dat_bits_dataCheck(io_chi_rx_dat_bits_dataCheck),
    .io_chi_rx_dat_bits_poison(io_chi_rx_dat_bits_poison),
    .io_id(io_id),
    .io_pCrd_query_valid(io_pCrd_query_valid),
    .io_pCrd_query_bits_pCrdType(io_pCrd_query_bits_pCrdType),
    .io_pCrd_query_bits_srcID(io_pCrd_query_bits_srcID),
    .io_pCrd_grant(io_pCrd_grant),
    .io_waitOnReadReceipt(io_waitOnReadReceipt)
  );

endmodule
