// MMIOBridge —— 手写可读实现(TL2 shard 3, AUX assembly signoff)。
//
// MMIO 请求桥: 把 TileLink-UL MMIO(auto_mmio_in) 请求分派到 8 个事务条目,
// 每条目把请求翻成 CHI(ReadNoSnp/WriteNoSnp...)发到 tx_req/tx_dat, 收 rx_rsp/
// rx_dat 后回 D 通道。顶层 glue(纯组合)= 分配/仲裁/路由:
//  (1) selectOH: 从 8 条目的 req_ready 选最低空闲条目(优先级 one-hot), 驱动
//      entry.req_valid = a_valid & selectOH[i]; a_ready = |req_ready。
//  (2) block_i: 若条目要发 ReadNoSnp(opcode 0x4)且任一条目在 waitOnReadReceipt,
//      门控该条目 tx_req(CHI 顺序: 等 ReadReceipt 回来才放下一个 read)。
//  (3) rx 路由: rx_rsp/rx_dat 按 txnID(=条目号 0..7)分派到对应条目;
//      rx_dat_ready = |(条目 rx_dat_ready & txnID 命中); rx_rsp_ready=1。
//  (4) 3 仲裁器汇聚: txreqArb(RRArbiterInit_11)→tx_req; mmio_txdat_arb
//      (Arbiter8_CHIDAT)→tx_dat; mmio_channel_D_arb(Arbiter8_TLBundleD)→D。
//  (5) 大量 CHI 字段常量绑定(qos/srcID/tagOp...=0, tx_dat opcode=0x3 NCBWrData)。
//
// ★ FM assembly: 3 绿 AUX 仲裁器(txreqArb/mmio_txdat_arb/mmio_channel_D_arb)两侧
//   unresolved → 对称黑盒(depends_on 闭包); 8 MMIOBridgeEntry(_2/_4)两侧 elaborate
//   golden RTL(逻辑 child 非黑盒, 待独立 signoff)。可读核只证顶层分配/仲裁/路由 glue。
module xs_MMIOBridge_core(
  input clock,
  input reset,
  output auto_mmio_in_a_ready,
  input auto_mmio_in_a_valid,
  input [3:0] auto_mmio_in_a_bits_opcode,
  input [2:0] auto_mmio_in_a_bits_param,
  input [1:0] auto_mmio_in_a_bits_size,
  input [2:0] auto_mmio_in_a_bits_source,
  input [47:0] auto_mmio_in_a_bits_address,
  input auto_mmio_in_a_bits_user_memBackType_MM,
  input auto_mmio_in_a_bits_user_memPageType_NC,
  input [7:0] auto_mmio_in_a_bits_mask,
  input [63:0] auto_mmio_in_a_bits_data,
  input auto_mmio_in_a_bits_corrupt,
  input auto_mmio_in_d_ready,
  output auto_mmio_in_d_valid,
  output [3:0] auto_mmio_in_d_bits_opcode,
  output [1:0] auto_mmio_in_d_bits_param,
  output [1:0] auto_mmio_in_d_bits_size,
  output [2:0] auto_mmio_in_d_bits_source,
  output auto_mmio_in_d_bits_sink,
  output auto_mmio_in_d_bits_denied,
  output [63:0] auto_mmio_in_d_bits_data,
  output auto_mmio_in_d_bits_corrupt,
  input io_tx_req_ready,
  output io_tx_req_valid,
  output [3:0] io_tx_req_bits_qos,
  output [10:0] io_tx_req_bits_tgtID,
  output [10:0] io_tx_req_bits_srcID,
  output [11:0] io_tx_req_bits_txnID,
  output [10:0] io_tx_req_bits_returnNID,
  output io_tx_req_bits_stashNIDValid,
  output [11:0] io_tx_req_bits_returnTxnID,
  output [6:0] io_tx_req_bits_opcode,
  output [2:0] io_tx_req_bits_size,
  output [47:0] io_tx_req_bits_addr,
  output io_tx_req_bits_ns,
  output io_tx_req_bits_likelyshared,
  output io_tx_req_bits_allowRetry,
  output [1:0] io_tx_req_bits_order,
  output [3:0] io_tx_req_bits_pCrdType,
  output io_tx_req_bits_memAttr_allocate,
  output io_tx_req_bits_memAttr_cacheable,
  output io_tx_req_bits_memAttr_device,
  output io_tx_req_bits_memAttr_ewa,
  output io_tx_req_bits_snpAttr,
  output [7:0] io_tx_req_bits_lpIDWithPadding,
  output io_tx_req_bits_snoopMe,
  output io_tx_req_bits_expCompAck,
  output [1:0] io_tx_req_bits_tagOp,
  output io_tx_req_bits_traceTag,
  output io_tx_req_bits_mpam_perfMonGroup,
  output [8:0] io_tx_req_bits_mpam_partID,
  output io_tx_req_bits_mpam_mpamNS,
  output [3:0] io_tx_req_bits_rsvdc,
  input io_tx_dat_ready,
  output io_tx_dat_valid,
  output [3:0] io_tx_dat_bits_qos,
  output [10:0] io_tx_dat_bits_tgtID,
  output [10:0] io_tx_dat_bits_srcID,
  output [11:0] io_tx_dat_bits_txnID,
  output [10:0] io_tx_dat_bits_homeNID,
  output [3:0] io_tx_dat_bits_opcode,
  output [1:0] io_tx_dat_bits_respErr,
  output [2:0] io_tx_dat_bits_resp,
  output [3:0] io_tx_dat_bits_dataSource,
  output [2:0] io_tx_dat_bits_cBusy,
  output [11:0] io_tx_dat_bits_dbID,
  output [1:0] io_tx_dat_bits_ccID,
  output [1:0] io_tx_dat_bits_dataID,
  output [1:0] io_tx_dat_bits_tagOp,
  output [7:0] io_tx_dat_bits_tag,
  output [1:0] io_tx_dat_bits_tu,
  output io_tx_dat_bits_traceTag,
  output [3:0] io_tx_dat_bits_rsvdc,
  output [31:0] io_tx_dat_bits_be,
  output [255:0] io_tx_dat_bits_data,
  output [31:0] io_tx_dat_bits_dataCheck,
  output [3:0] io_tx_dat_bits_poison,
  output io_rx_rsp_ready,
  input io_rx_rsp_valid,
  input [3:0] io_rx_rsp_bits_qos,
  input [10:0] io_rx_rsp_bits_tgtID,
  input [10:0] io_rx_rsp_bits_srcID,
  input [11:0] io_rx_rsp_bits_txnID,
  input [4:0] io_rx_rsp_bits_opcode,
  input [1:0] io_rx_rsp_bits_respErr,
  input [2:0] io_rx_rsp_bits_resp,
  input [2:0] io_rx_rsp_bits_fwdState,
  input [2:0] io_rx_rsp_bits_cBusy,
  input [11:0] io_rx_rsp_bits_dbID,
  input [3:0] io_rx_rsp_bits_pCrdType,
  input [1:0] io_rx_rsp_bits_tagOp,
  input io_rx_rsp_bits_traceTag,
  output io_rx_dat_ready,
  input io_rx_dat_valid,
  input [3:0] io_rx_dat_bits_qos,
  input [10:0] io_rx_dat_bits_tgtID,
  input [10:0] io_rx_dat_bits_srcID,
  input [11:0] io_rx_dat_bits_txnID,
  input [10:0] io_rx_dat_bits_homeNID,
  input [3:0] io_rx_dat_bits_opcode,
  input [1:0] io_rx_dat_bits_respErr,
  input [2:0] io_rx_dat_bits_resp,
  input [3:0] io_rx_dat_bits_dataSource,
  input [2:0] io_rx_dat_bits_cBusy,
  input [11:0] io_rx_dat_bits_dbID,
  input [1:0] io_rx_dat_bits_ccID,
  input [1:0] io_rx_dat_bits_dataID,
  input [1:0] io_rx_dat_bits_tagOp,
  input [7:0] io_rx_dat_bits_tag,
  input [1:0] io_rx_dat_bits_tu,
  input io_rx_dat_bits_traceTag,
  input [3:0] io_rx_dat_bits_rsvdc,
  input [31:0] io_rx_dat_bits_be,
  input [255:0] io_rx_dat_bits_data,
  input [31:0] io_rx_dat_bits_dataCheck,
  input [3:0] io_rx_dat_bits_poison,
  output io_pCrd_0_query_valid,
  output [3:0] io_pCrd_0_query_bits_pCrdType,
  output [10:0] io_pCrd_0_query_bits_srcID,
  input io_pCrd_0_grant,
  output io_pCrd_1_query_valid,
  output [3:0] io_pCrd_1_query_bits_pCrdType,
  output [10:0] io_pCrd_1_query_bits_srcID,
  input io_pCrd_1_grant,
  output io_pCrd_2_query_valid,
  output [3:0] io_pCrd_2_query_bits_pCrdType,
  output [10:0] io_pCrd_2_query_bits_srcID,
  input io_pCrd_2_grant,
  output io_pCrd_3_query_valid,
  output [3:0] io_pCrd_3_query_bits_pCrdType,
  output [10:0] io_pCrd_3_query_bits_srcID,
  input io_pCrd_3_grant,
  output io_pCrd_4_query_valid,
  output [3:0] io_pCrd_4_query_bits_pCrdType,
  output [10:0] io_pCrd_4_query_bits_srcID,
  input io_pCrd_4_grant,
  output io_pCrd_5_query_valid,
  output [3:0] io_pCrd_5_query_bits_pCrdType,
  output [10:0] io_pCrd_5_query_bits_srcID,
  input io_pCrd_5_grant,
  output io_pCrd_6_query_valid,
  output [3:0] io_pCrd_6_query_bits_pCrdType,
  output [10:0] io_pCrd_6_query_bits_srcID,
  input io_pCrd_6_grant,
  output io_pCrd_7_query_valid,
  output [3:0] io_pCrd_7_query_bits_pCrdType,
  output [10:0] io_pCrd_7_query_bits_srcID,
  input io_pCrd_7_grant
);

  // ---- 8 条目输出信号(数组化, generate 例化时逐条目连) ----
  wire e_req_ready [0:7];
  wire e_resp_valid [0:7];
  wire [3:0] e_resp_bits_opcode [0:7];
  wire [1:0] e_resp_bits_size [0:7];
  wire [2:0] e_resp_bits_source [0:7];
  wire e_resp_bits_denied [0:7];
  wire [63:0] e_resp_bits_data [0:7];
  wire e_resp_bits_corrupt [0:7];
  wire e_chi_tx_req_valid [0:7];
  wire [11:0] e_chi_tx_req_bits_txnID [0:7];
  wire [6:0] e_chi_tx_req_bits_opcode [0:7];
  wire [2:0] e_chi_tx_req_bits_size [0:7];
  wire [47:0] e_chi_tx_req_bits_addr [0:7];
  wire e_chi_tx_req_bits_allowRetry [0:7];
  wire [1:0] e_chi_tx_req_bits_order [0:7];
  wire [3:0] e_chi_tx_req_bits_pCrdType [0:7];
  wire e_chi_tx_req_bits_memAttr_device [0:7];
  wire e_chi_tx_req_bits_memAttr_ewa [0:7];
  wire e_chi_tx_dat_valid [0:7];
  wire [10:0] e_chi_tx_dat_bits_tgtID [0:7];
  wire [11:0] e_chi_tx_dat_bits_txnID [0:7];
  wire [1:0] e_chi_tx_dat_bits_respErr [0:7];
  wire [1:0] e_chi_tx_dat_bits_ccID [0:7];
  wire [1:0] e_chi_tx_dat_bits_dataID [0:7];
  wire e_chi_tx_dat_bits_traceTag [0:7];
  wire [31:0] e_chi_tx_dat_bits_be [0:7];
  wire [255:0] e_chi_tx_dat_bits_data [0:7];
  wire [31:0] e_chi_tx_dat_bits_dataCheck [0:7];
  wire [3:0] e_chi_tx_dat_bits_poison [0:7];
  wire e_chi_rx_rsp_ready [0:7];
  wire e_chi_rx_dat_ready [0:7];
  wire e_waitOnReadReceipt [0:7];
  // 仲裁器->条目 ready
  wire txreq_arb_in_ready [0:7];
  wire txdat_arb_in_ready [0:7];
  wire d_arb_in_ready [0:7];

  // ---- A 通道(MMIO 请求)别名 ----
  wire        a_valid   = auto_mmio_in_a_valid;
  wire [3:0]  a_opcode  = auto_mmio_in_a_bits_opcode;
  wire [1:0]  a_size    = auto_mmio_in_a_bits_size;
  wire [2:0]  a_source  = auto_mmio_in_a_bits_source;
  wire [47:0] a_address = auto_mmio_in_a_bits_address;
  wire        a_mm      = auto_mmio_in_a_bits_user_memBackType_MM;
  wire        a_nc      = auto_mmio_in_a_bits_user_memPageType_NC;
  wire [7:0]  a_mask    = auto_mmio_in_a_bits_mask;
  wire [63:0] a_data    = auto_mmio_in_a_bits_data;
  wire        a_corrupt = auto_mmio_in_a_bits_corrupt;
  wire        d_ready   = auto_mmio_in_d_ready;

  // ---- (1) selectOH: 从 8 条目 req_ready 选最低空闲(优先级 one-hot) ----
  // 与 golden _selectOH_T_13 逐位一致(0>1>2>3>4>5>6>7 优先)。
  wire selT   = e_req_ready[0] | e_req_ready[1];
  wire [7:0] selectOH =
      (selT | e_req_ready[2] | e_req_ready[3])
        ? {4'h0,
           selT ? {2'h0, e_req_ready[0] ? 2'h1 : 2'h2}
                : (e_req_ready[2] ? 4'h4 : 4'h8)}
        : (e_req_ready[4] | e_req_ready[5])
            ? {2'h0, e_req_ready[4] ? 6'h10 : 6'h20}
            : (e_req_ready[6] ? 8'h40 : 8'h80);
  wire a_ready = |{e_req_ready[0],e_req_ready[1],e_req_ready[2],e_req_ready[3],
                   e_req_ready[4],e_req_ready[5],e_req_ready[6],e_req_ready[7]};

  // ---- (2) block_i: ReadNoSnp(0x4)且有条目等 ReadReceipt 时门控其 tx_req ----
  wire anyWaitRR = |{e_waitOnReadReceipt[0],e_waitOnReadReceipt[1],e_waitOnReadReceipt[2],
                     e_waitOnReadReceipt[3],e_waitOnReadReceipt[4],e_waitOnReadReceipt[5],
                     e_waitOnReadReceipt[6],e_waitOnReadReceipt[7]};
  wire block_e [0:7];
  genvar gb;
  generate for (gb=0; gb<8; gb=gb+1) begin : g_block
    assign block_e[gb] = (e_chi_tx_req_bits_opcode[gb] == 7'h4) & anyWaitRR;
  end endgenerate

  // ---- (3) rx 路由: txnID(=条目号)命中 ----
  wire rxrsp_hit [0:7];
  wire rxdat_hit [0:7];
  genvar gr;
  generate for (gr=0; gr<8; gr=gr+1) begin : g_rx
    assign rxrsp_hit[gr] = io_rx_rsp_bits_txnID == gr[11:0];
    assign rxdat_hit[gr] = io_rx_dat_bits_txnID == gr[11:0];
  end endgenerate

  // ---- 8 MMIOBridgeEntry(_2/_4)条目例化(逻辑 child, 两侧 elaborate) ----
  MMIOBridgeEntry entries_0 (
    .clock                             (clock),
    .reset                             (reset),
    .io_req_ready                      (e_req_ready[0]),
    .io_req_valid                      (a_valid & selectOH[0]),
    .io_req_bits_opcode                (a_opcode),
    .io_req_bits_size                  (a_size),
    .io_req_bits_source                (a_source),
    .io_req_bits_address               (a_address),
    .io_req_bits_user_memBackType_MM   (a_mm),
    .io_req_bits_user_memPageType_NC   (a_nc),
    .io_req_bits_mask                  (a_mask),
    .io_req_bits_data                  (a_data),
    .io_req_bits_corrupt               (a_corrupt),
    .io_resp_ready                     (d_arb_in_ready[0]),
    .io_resp_valid                     (e_resp_valid[0]),
    .io_resp_bits_opcode               (e_resp_bits_opcode[0]),
    .io_resp_bits_size                 (e_resp_bits_size[0]),
    .io_resp_bits_source               (e_resp_bits_source[0]),
    .io_resp_bits_denied               (e_resp_bits_denied[0]),
    .io_resp_bits_data                 (e_resp_bits_data[0]),
    .io_resp_bits_corrupt              (e_resp_bits_corrupt[0]),
    .io_chi_tx_req_ready               (txreq_arb_in_ready[0] & ~block_e[0]),
    .io_chi_tx_req_valid               (e_chi_tx_req_valid[0]),
    .io_chi_tx_req_bits_txnID          (e_chi_tx_req_bits_txnID[0]),
    .io_chi_tx_req_bits_opcode         (e_chi_tx_req_bits_opcode[0]),
    .io_chi_tx_req_bits_size           (e_chi_tx_req_bits_size[0]),
    .io_chi_tx_req_bits_addr           (e_chi_tx_req_bits_addr[0]),
    .io_chi_tx_req_bits_allowRetry     (e_chi_tx_req_bits_allowRetry[0]),
    .io_chi_tx_req_bits_order          (e_chi_tx_req_bits_order[0]),
    .io_chi_tx_req_bits_pCrdType       (e_chi_tx_req_bits_pCrdType[0]),
    .io_chi_tx_req_bits_memAttr_device (e_chi_tx_req_bits_memAttr_device[0]),
    .io_chi_tx_req_bits_memAttr_ewa    (e_chi_tx_req_bits_memAttr_ewa[0]),
    .io_chi_tx_dat_ready               (txdat_arb_in_ready[0]),
    .io_chi_tx_dat_valid               (e_chi_tx_dat_valid[0]),
    .io_chi_tx_dat_bits_tgtID          (e_chi_tx_dat_bits_tgtID[0]),
    .io_chi_tx_dat_bits_txnID          (e_chi_tx_dat_bits_txnID[0]),
    .io_chi_tx_dat_bits_respErr        (e_chi_tx_dat_bits_respErr[0]),
    .io_chi_tx_dat_bits_ccID           (e_chi_tx_dat_bits_ccID[0]),
    .io_chi_tx_dat_bits_dataID         (e_chi_tx_dat_bits_dataID[0]),
    .io_chi_tx_dat_bits_traceTag       (e_chi_tx_dat_bits_traceTag[0]),
    .io_chi_tx_dat_bits_be             (e_chi_tx_dat_bits_be[0]),
    .io_chi_tx_dat_bits_data           (e_chi_tx_dat_bits_data[0]),
    .io_chi_tx_dat_bits_dataCheck      (e_chi_tx_dat_bits_dataCheck[0]),
    .io_chi_tx_dat_bits_poison         (e_chi_tx_dat_bits_poison[0]),
    .io_chi_rx_rsp_ready               (e_chi_rx_rsp_ready[0]),
    .io_chi_rx_rsp_valid               (io_rx_rsp_valid & rxrsp_hit[0]),
    .io_chi_rx_rsp_bits_srcID          (io_rx_rsp_bits_srcID),
    .io_chi_rx_rsp_bits_opcode         (io_rx_rsp_bits_opcode),
    .io_chi_rx_rsp_bits_respErr        (io_rx_rsp_bits_respErr),
    .io_chi_rx_rsp_bits_dbID           (io_rx_rsp_bits_dbID),
    .io_chi_rx_rsp_bits_pCrdType       (io_rx_rsp_bits_pCrdType),
    .io_chi_rx_rsp_bits_traceTag       (io_rx_rsp_bits_traceTag),
    .io_chi_rx_dat_ready               (e_chi_rx_dat_ready[0]),
    .io_chi_rx_dat_valid               (io_rx_dat_valid & rxdat_hit[0]),
    .io_chi_rx_dat_bits_respErr        (io_rx_dat_bits_respErr),
    .io_chi_rx_dat_bits_data           (io_rx_dat_bits_data),
    .io_chi_rx_dat_bits_dataCheck      (io_rx_dat_bits_dataCheck),
    .io_chi_rx_dat_bits_poison         (io_rx_dat_bits_poison),
    .io_id                             (1'h0),
    .io_pCrd_query_valid               (io_pCrd_0_query_valid),
    .io_pCrd_query_bits_pCrdType       (io_pCrd_0_query_bits_pCrdType),
    .io_pCrd_query_bits_srcID          (io_pCrd_0_query_bits_srcID),
    .io_pCrd_grant                     (io_pCrd_0_grant),
    .io_waitOnReadReceipt              (e_waitOnReadReceipt[0])
  );
  MMIOBridgeEntry entries_1 (
    .clock                             (clock),
    .reset                             (reset),
    .io_req_ready                      (e_req_ready[1]),
    .io_req_valid                      (a_valid & selectOH[1]),
    .io_req_bits_opcode                (a_opcode),
    .io_req_bits_size                  (a_size),
    .io_req_bits_source                (a_source),
    .io_req_bits_address               (a_address),
    .io_req_bits_user_memBackType_MM   (a_mm),
    .io_req_bits_user_memPageType_NC   (a_nc),
    .io_req_bits_mask                  (a_mask),
    .io_req_bits_data                  (a_data),
    .io_req_bits_corrupt               (a_corrupt),
    .io_resp_ready                     (d_arb_in_ready[1]),
    .io_resp_valid                     (e_resp_valid[1]),
    .io_resp_bits_opcode               (e_resp_bits_opcode[1]),
    .io_resp_bits_size                 (e_resp_bits_size[1]),
    .io_resp_bits_source               (e_resp_bits_source[1]),
    .io_resp_bits_denied               (e_resp_bits_denied[1]),
    .io_resp_bits_data                 (e_resp_bits_data[1]),
    .io_resp_bits_corrupt              (e_resp_bits_corrupt[1]),
    .io_chi_tx_req_ready               (txreq_arb_in_ready[1] & ~block_e[1]),
    .io_chi_tx_req_valid               (e_chi_tx_req_valid[1]),
    .io_chi_tx_req_bits_txnID          (e_chi_tx_req_bits_txnID[1]),
    .io_chi_tx_req_bits_opcode         (e_chi_tx_req_bits_opcode[1]),
    .io_chi_tx_req_bits_size           (e_chi_tx_req_bits_size[1]),
    .io_chi_tx_req_bits_addr           (e_chi_tx_req_bits_addr[1]),
    .io_chi_tx_req_bits_allowRetry     (e_chi_tx_req_bits_allowRetry[1]),
    .io_chi_tx_req_bits_order          (e_chi_tx_req_bits_order[1]),
    .io_chi_tx_req_bits_pCrdType       (e_chi_tx_req_bits_pCrdType[1]),
    .io_chi_tx_req_bits_memAttr_device (e_chi_tx_req_bits_memAttr_device[1]),
    .io_chi_tx_req_bits_memAttr_ewa    (e_chi_tx_req_bits_memAttr_ewa[1]),
    .io_chi_tx_dat_ready               (txdat_arb_in_ready[1]),
    .io_chi_tx_dat_valid               (e_chi_tx_dat_valid[1]),
    .io_chi_tx_dat_bits_tgtID          (e_chi_tx_dat_bits_tgtID[1]),
    .io_chi_tx_dat_bits_txnID          (e_chi_tx_dat_bits_txnID[1]),
    .io_chi_tx_dat_bits_respErr        (e_chi_tx_dat_bits_respErr[1]),
    .io_chi_tx_dat_bits_ccID           (e_chi_tx_dat_bits_ccID[1]),
    .io_chi_tx_dat_bits_dataID         (e_chi_tx_dat_bits_dataID[1]),
    .io_chi_tx_dat_bits_traceTag       (e_chi_tx_dat_bits_traceTag[1]),
    .io_chi_tx_dat_bits_be             (e_chi_tx_dat_bits_be[1]),
    .io_chi_tx_dat_bits_data           (e_chi_tx_dat_bits_data[1]),
    .io_chi_tx_dat_bits_dataCheck      (e_chi_tx_dat_bits_dataCheck[1]),
    .io_chi_tx_dat_bits_poison         (e_chi_tx_dat_bits_poison[1]),
    .io_chi_rx_rsp_ready               (e_chi_rx_rsp_ready[1]),
    .io_chi_rx_rsp_valid               (io_rx_rsp_valid & rxrsp_hit[1]),
    .io_chi_rx_rsp_bits_srcID          (io_rx_rsp_bits_srcID),
    .io_chi_rx_rsp_bits_opcode         (io_rx_rsp_bits_opcode),
    .io_chi_rx_rsp_bits_respErr        (io_rx_rsp_bits_respErr),
    .io_chi_rx_rsp_bits_dbID           (io_rx_rsp_bits_dbID),
    .io_chi_rx_rsp_bits_pCrdType       (io_rx_rsp_bits_pCrdType),
    .io_chi_rx_rsp_bits_traceTag       (io_rx_rsp_bits_traceTag),
    .io_chi_rx_dat_ready               (e_chi_rx_dat_ready[1]),
    .io_chi_rx_dat_valid               (io_rx_dat_valid & rxdat_hit[1]),
    .io_chi_rx_dat_bits_respErr        (io_rx_dat_bits_respErr),
    .io_chi_rx_dat_bits_data           (io_rx_dat_bits_data),
    .io_chi_rx_dat_bits_dataCheck      (io_rx_dat_bits_dataCheck),
    .io_chi_rx_dat_bits_poison         (io_rx_dat_bits_poison),
    .io_id                             (1'h1),
    .io_pCrd_query_valid               (io_pCrd_1_query_valid),
    .io_pCrd_query_bits_pCrdType       (io_pCrd_1_query_bits_pCrdType),
    .io_pCrd_query_bits_srcID          (io_pCrd_1_query_bits_srcID),
    .io_pCrd_grant                     (io_pCrd_1_grant),
    .io_waitOnReadReceipt              (e_waitOnReadReceipt[1])
  );
  MMIOBridgeEntry_2 entries_2 (
    .clock                             (clock),
    .reset                             (reset),
    .io_req_ready                      (e_req_ready[2]),
    .io_req_valid                      (a_valid & selectOH[2]),
    .io_req_bits_opcode                (a_opcode),
    .io_req_bits_size                  (a_size),
    .io_req_bits_source                (a_source),
    .io_req_bits_address               (a_address),
    .io_req_bits_user_memBackType_MM   (a_mm),
    .io_req_bits_user_memPageType_NC   (a_nc),
    .io_req_bits_mask                  (a_mask),
    .io_req_bits_data                  (a_data),
    .io_req_bits_corrupt               (a_corrupt),
    .io_resp_ready                     (d_arb_in_ready[2]),
    .io_resp_valid                     (e_resp_valid[2]),
    .io_resp_bits_opcode               (e_resp_bits_opcode[2]),
    .io_resp_bits_size                 (e_resp_bits_size[2]),
    .io_resp_bits_source               (e_resp_bits_source[2]),
    .io_resp_bits_denied               (e_resp_bits_denied[2]),
    .io_resp_bits_data                 (e_resp_bits_data[2]),
    .io_resp_bits_corrupt              (e_resp_bits_corrupt[2]),
    .io_chi_tx_req_ready               (txreq_arb_in_ready[2] & ~block_e[2]),
    .io_chi_tx_req_valid               (e_chi_tx_req_valid[2]),
    .io_chi_tx_req_bits_txnID          (e_chi_tx_req_bits_txnID[2]),
    .io_chi_tx_req_bits_opcode         (e_chi_tx_req_bits_opcode[2]),
    .io_chi_tx_req_bits_size           (e_chi_tx_req_bits_size[2]),
    .io_chi_tx_req_bits_addr           (e_chi_tx_req_bits_addr[2]),
    .io_chi_tx_req_bits_allowRetry     (e_chi_tx_req_bits_allowRetry[2]),
    .io_chi_tx_req_bits_order          (e_chi_tx_req_bits_order[2]),
    .io_chi_tx_req_bits_pCrdType       (e_chi_tx_req_bits_pCrdType[2]),
    .io_chi_tx_req_bits_memAttr_device (e_chi_tx_req_bits_memAttr_device[2]),
    .io_chi_tx_req_bits_memAttr_ewa    (e_chi_tx_req_bits_memAttr_ewa[2]),
    .io_chi_tx_dat_ready               (txdat_arb_in_ready[2]),
    .io_chi_tx_dat_valid               (e_chi_tx_dat_valid[2]),
    .io_chi_tx_dat_bits_tgtID          (e_chi_tx_dat_bits_tgtID[2]),
    .io_chi_tx_dat_bits_txnID          (e_chi_tx_dat_bits_txnID[2]),
    .io_chi_tx_dat_bits_respErr        (e_chi_tx_dat_bits_respErr[2]),
    .io_chi_tx_dat_bits_ccID           (e_chi_tx_dat_bits_ccID[2]),
    .io_chi_tx_dat_bits_dataID         (e_chi_tx_dat_bits_dataID[2]),
    .io_chi_tx_dat_bits_traceTag       (e_chi_tx_dat_bits_traceTag[2]),
    .io_chi_tx_dat_bits_be             (e_chi_tx_dat_bits_be[2]),
    .io_chi_tx_dat_bits_data           (e_chi_tx_dat_bits_data[2]),
    .io_chi_tx_dat_bits_dataCheck      (e_chi_tx_dat_bits_dataCheck[2]),
    .io_chi_tx_dat_bits_poison         (e_chi_tx_dat_bits_poison[2]),
    .io_chi_rx_rsp_ready               (e_chi_rx_rsp_ready[2]),
    .io_chi_rx_rsp_valid               (io_rx_rsp_valid & rxrsp_hit[2]),
    .io_chi_rx_rsp_bits_srcID          (io_rx_rsp_bits_srcID),
    .io_chi_rx_rsp_bits_opcode         (io_rx_rsp_bits_opcode),
    .io_chi_rx_rsp_bits_respErr        (io_rx_rsp_bits_respErr),
    .io_chi_rx_rsp_bits_dbID           (io_rx_rsp_bits_dbID),
    .io_chi_rx_rsp_bits_pCrdType       (io_rx_rsp_bits_pCrdType),
    .io_chi_rx_rsp_bits_traceTag       (io_rx_rsp_bits_traceTag),
    .io_chi_rx_dat_ready               (e_chi_rx_dat_ready[2]),
    .io_chi_rx_dat_valid               (io_rx_dat_valid & rxdat_hit[2]),
    .io_chi_rx_dat_bits_respErr        (io_rx_dat_bits_respErr),
    .io_chi_rx_dat_bits_data           (io_rx_dat_bits_data),
    .io_chi_rx_dat_bits_dataCheck      (io_rx_dat_bits_dataCheck),
    .io_chi_rx_dat_bits_poison         (io_rx_dat_bits_poison),
    .io_id                             (2'h2),
    .io_pCrd_query_valid               (io_pCrd_2_query_valid),
    .io_pCrd_query_bits_pCrdType       (io_pCrd_2_query_bits_pCrdType),
    .io_pCrd_query_bits_srcID          (io_pCrd_2_query_bits_srcID),
    .io_pCrd_grant                     (io_pCrd_2_grant),
    .io_waitOnReadReceipt              (e_waitOnReadReceipt[2])
  );
  MMIOBridgeEntry_2 entries_3 (
    .clock                             (clock),
    .reset                             (reset),
    .io_req_ready                      (e_req_ready[3]),
    .io_req_valid                      (a_valid & selectOH[3]),
    .io_req_bits_opcode                (a_opcode),
    .io_req_bits_size                  (a_size),
    .io_req_bits_source                (a_source),
    .io_req_bits_address               (a_address),
    .io_req_bits_user_memBackType_MM   (a_mm),
    .io_req_bits_user_memPageType_NC   (a_nc),
    .io_req_bits_mask                  (a_mask),
    .io_req_bits_data                  (a_data),
    .io_req_bits_corrupt               (a_corrupt),
    .io_resp_ready                     (d_arb_in_ready[3]),
    .io_resp_valid                     (e_resp_valid[3]),
    .io_resp_bits_opcode               (e_resp_bits_opcode[3]),
    .io_resp_bits_size                 (e_resp_bits_size[3]),
    .io_resp_bits_source               (e_resp_bits_source[3]),
    .io_resp_bits_denied               (e_resp_bits_denied[3]),
    .io_resp_bits_data                 (e_resp_bits_data[3]),
    .io_resp_bits_corrupt              (e_resp_bits_corrupt[3]),
    .io_chi_tx_req_ready               (txreq_arb_in_ready[3] & ~block_e[3]),
    .io_chi_tx_req_valid               (e_chi_tx_req_valid[3]),
    .io_chi_tx_req_bits_txnID          (e_chi_tx_req_bits_txnID[3]),
    .io_chi_tx_req_bits_opcode         (e_chi_tx_req_bits_opcode[3]),
    .io_chi_tx_req_bits_size           (e_chi_tx_req_bits_size[3]),
    .io_chi_tx_req_bits_addr           (e_chi_tx_req_bits_addr[3]),
    .io_chi_tx_req_bits_allowRetry     (e_chi_tx_req_bits_allowRetry[3]),
    .io_chi_tx_req_bits_order          (e_chi_tx_req_bits_order[3]),
    .io_chi_tx_req_bits_pCrdType       (e_chi_tx_req_bits_pCrdType[3]),
    .io_chi_tx_req_bits_memAttr_device (e_chi_tx_req_bits_memAttr_device[3]),
    .io_chi_tx_req_bits_memAttr_ewa    (e_chi_tx_req_bits_memAttr_ewa[3]),
    .io_chi_tx_dat_ready               (txdat_arb_in_ready[3]),
    .io_chi_tx_dat_valid               (e_chi_tx_dat_valid[3]),
    .io_chi_tx_dat_bits_tgtID          (e_chi_tx_dat_bits_tgtID[3]),
    .io_chi_tx_dat_bits_txnID          (e_chi_tx_dat_bits_txnID[3]),
    .io_chi_tx_dat_bits_respErr        (e_chi_tx_dat_bits_respErr[3]),
    .io_chi_tx_dat_bits_ccID           (e_chi_tx_dat_bits_ccID[3]),
    .io_chi_tx_dat_bits_dataID         (e_chi_tx_dat_bits_dataID[3]),
    .io_chi_tx_dat_bits_traceTag       (e_chi_tx_dat_bits_traceTag[3]),
    .io_chi_tx_dat_bits_be             (e_chi_tx_dat_bits_be[3]),
    .io_chi_tx_dat_bits_data           (e_chi_tx_dat_bits_data[3]),
    .io_chi_tx_dat_bits_dataCheck      (e_chi_tx_dat_bits_dataCheck[3]),
    .io_chi_tx_dat_bits_poison         (e_chi_tx_dat_bits_poison[3]),
    .io_chi_rx_rsp_ready               (e_chi_rx_rsp_ready[3]),
    .io_chi_rx_rsp_valid               (io_rx_rsp_valid & rxrsp_hit[3]),
    .io_chi_rx_rsp_bits_srcID          (io_rx_rsp_bits_srcID),
    .io_chi_rx_rsp_bits_opcode         (io_rx_rsp_bits_opcode),
    .io_chi_rx_rsp_bits_respErr        (io_rx_rsp_bits_respErr),
    .io_chi_rx_rsp_bits_dbID           (io_rx_rsp_bits_dbID),
    .io_chi_rx_rsp_bits_pCrdType       (io_rx_rsp_bits_pCrdType),
    .io_chi_rx_rsp_bits_traceTag       (io_rx_rsp_bits_traceTag),
    .io_chi_rx_dat_ready               (e_chi_rx_dat_ready[3]),
    .io_chi_rx_dat_valid               (io_rx_dat_valid & rxdat_hit[3]),
    .io_chi_rx_dat_bits_respErr        (io_rx_dat_bits_respErr),
    .io_chi_rx_dat_bits_data           (io_rx_dat_bits_data),
    .io_chi_rx_dat_bits_dataCheck      (io_rx_dat_bits_dataCheck),
    .io_chi_rx_dat_bits_poison         (io_rx_dat_bits_poison),
    .io_id                             (2'h3),
    .io_pCrd_query_valid               (io_pCrd_3_query_valid),
    .io_pCrd_query_bits_pCrdType       (io_pCrd_3_query_bits_pCrdType),
    .io_pCrd_query_bits_srcID          (io_pCrd_3_query_bits_srcID),
    .io_pCrd_grant                     (io_pCrd_3_grant),
    .io_waitOnReadReceipt              (e_waitOnReadReceipt[3])
  );
  MMIOBridgeEntry_4 entries_4 (
    .clock                             (clock),
    .reset                             (reset),
    .io_req_ready                      (e_req_ready[4]),
    .io_req_valid                      (a_valid & selectOH[4]),
    .io_req_bits_opcode                (a_opcode),
    .io_req_bits_size                  (a_size),
    .io_req_bits_source                (a_source),
    .io_req_bits_address               (a_address),
    .io_req_bits_user_memBackType_MM   (a_mm),
    .io_req_bits_user_memPageType_NC   (a_nc),
    .io_req_bits_mask                  (a_mask),
    .io_req_bits_data                  (a_data),
    .io_req_bits_corrupt               (a_corrupt),
    .io_resp_ready                     (d_arb_in_ready[4]),
    .io_resp_valid                     (e_resp_valid[4]),
    .io_resp_bits_opcode               (e_resp_bits_opcode[4]),
    .io_resp_bits_size                 (e_resp_bits_size[4]),
    .io_resp_bits_source               (e_resp_bits_source[4]),
    .io_resp_bits_denied               (e_resp_bits_denied[4]),
    .io_resp_bits_data                 (e_resp_bits_data[4]),
    .io_resp_bits_corrupt              (e_resp_bits_corrupt[4]),
    .io_chi_tx_req_ready               (txreq_arb_in_ready[4] & ~block_e[4]),
    .io_chi_tx_req_valid               (e_chi_tx_req_valid[4]),
    .io_chi_tx_req_bits_txnID          (e_chi_tx_req_bits_txnID[4]),
    .io_chi_tx_req_bits_opcode         (e_chi_tx_req_bits_opcode[4]),
    .io_chi_tx_req_bits_size           (e_chi_tx_req_bits_size[4]),
    .io_chi_tx_req_bits_addr           (e_chi_tx_req_bits_addr[4]),
    .io_chi_tx_req_bits_allowRetry     (e_chi_tx_req_bits_allowRetry[4]),
    .io_chi_tx_req_bits_order          (e_chi_tx_req_bits_order[4]),
    .io_chi_tx_req_bits_pCrdType       (e_chi_tx_req_bits_pCrdType[4]),
    .io_chi_tx_req_bits_memAttr_device (e_chi_tx_req_bits_memAttr_device[4]),
    .io_chi_tx_req_bits_memAttr_ewa    (e_chi_tx_req_bits_memAttr_ewa[4]),
    .io_chi_tx_dat_ready               (txdat_arb_in_ready[4]),
    .io_chi_tx_dat_valid               (e_chi_tx_dat_valid[4]),
    .io_chi_tx_dat_bits_tgtID          (e_chi_tx_dat_bits_tgtID[4]),
    .io_chi_tx_dat_bits_txnID          (e_chi_tx_dat_bits_txnID[4]),
    .io_chi_tx_dat_bits_respErr        (e_chi_tx_dat_bits_respErr[4]),
    .io_chi_tx_dat_bits_ccID           (e_chi_tx_dat_bits_ccID[4]),
    .io_chi_tx_dat_bits_dataID         (e_chi_tx_dat_bits_dataID[4]),
    .io_chi_tx_dat_bits_traceTag       (e_chi_tx_dat_bits_traceTag[4]),
    .io_chi_tx_dat_bits_be             (e_chi_tx_dat_bits_be[4]),
    .io_chi_tx_dat_bits_data           (e_chi_tx_dat_bits_data[4]),
    .io_chi_tx_dat_bits_dataCheck      (e_chi_tx_dat_bits_dataCheck[4]),
    .io_chi_tx_dat_bits_poison         (e_chi_tx_dat_bits_poison[4]),
    .io_chi_rx_rsp_ready               (e_chi_rx_rsp_ready[4]),
    .io_chi_rx_rsp_valid               (io_rx_rsp_valid & rxrsp_hit[4]),
    .io_chi_rx_rsp_bits_srcID          (io_rx_rsp_bits_srcID),
    .io_chi_rx_rsp_bits_opcode         (io_rx_rsp_bits_opcode),
    .io_chi_rx_rsp_bits_respErr        (io_rx_rsp_bits_respErr),
    .io_chi_rx_rsp_bits_dbID           (io_rx_rsp_bits_dbID),
    .io_chi_rx_rsp_bits_pCrdType       (io_rx_rsp_bits_pCrdType),
    .io_chi_rx_rsp_bits_traceTag       (io_rx_rsp_bits_traceTag),
    .io_chi_rx_dat_ready               (e_chi_rx_dat_ready[4]),
    .io_chi_rx_dat_valid               (io_rx_dat_valid & rxdat_hit[4]),
    .io_chi_rx_dat_bits_respErr        (io_rx_dat_bits_respErr),
    .io_chi_rx_dat_bits_data           (io_rx_dat_bits_data),
    .io_chi_rx_dat_bits_dataCheck      (io_rx_dat_bits_dataCheck),
    .io_chi_rx_dat_bits_poison         (io_rx_dat_bits_poison),
    .io_id                             (3'h4),
    .io_pCrd_query_valid               (io_pCrd_4_query_valid),
    .io_pCrd_query_bits_pCrdType       (io_pCrd_4_query_bits_pCrdType),
    .io_pCrd_query_bits_srcID          (io_pCrd_4_query_bits_srcID),
    .io_pCrd_grant                     (io_pCrd_4_grant),
    .io_waitOnReadReceipt              (e_waitOnReadReceipt[4])
  );
  MMIOBridgeEntry_4 entries_5 (
    .clock                             (clock),
    .reset                             (reset),
    .io_req_ready                      (e_req_ready[5]),
    .io_req_valid                      (a_valid & selectOH[5]),
    .io_req_bits_opcode                (a_opcode),
    .io_req_bits_size                  (a_size),
    .io_req_bits_source                (a_source),
    .io_req_bits_address               (a_address),
    .io_req_bits_user_memBackType_MM   (a_mm),
    .io_req_bits_user_memPageType_NC   (a_nc),
    .io_req_bits_mask                  (a_mask),
    .io_req_bits_data                  (a_data),
    .io_req_bits_corrupt               (a_corrupt),
    .io_resp_ready                     (d_arb_in_ready[5]),
    .io_resp_valid                     (e_resp_valid[5]),
    .io_resp_bits_opcode               (e_resp_bits_opcode[5]),
    .io_resp_bits_size                 (e_resp_bits_size[5]),
    .io_resp_bits_source               (e_resp_bits_source[5]),
    .io_resp_bits_denied               (e_resp_bits_denied[5]),
    .io_resp_bits_data                 (e_resp_bits_data[5]),
    .io_resp_bits_corrupt              (e_resp_bits_corrupt[5]),
    .io_chi_tx_req_ready               (txreq_arb_in_ready[5] & ~block_e[5]),
    .io_chi_tx_req_valid               (e_chi_tx_req_valid[5]),
    .io_chi_tx_req_bits_txnID          (e_chi_tx_req_bits_txnID[5]),
    .io_chi_tx_req_bits_opcode         (e_chi_tx_req_bits_opcode[5]),
    .io_chi_tx_req_bits_size           (e_chi_tx_req_bits_size[5]),
    .io_chi_tx_req_bits_addr           (e_chi_tx_req_bits_addr[5]),
    .io_chi_tx_req_bits_allowRetry     (e_chi_tx_req_bits_allowRetry[5]),
    .io_chi_tx_req_bits_order          (e_chi_tx_req_bits_order[5]),
    .io_chi_tx_req_bits_pCrdType       (e_chi_tx_req_bits_pCrdType[5]),
    .io_chi_tx_req_bits_memAttr_device (e_chi_tx_req_bits_memAttr_device[5]),
    .io_chi_tx_req_bits_memAttr_ewa    (e_chi_tx_req_bits_memAttr_ewa[5]),
    .io_chi_tx_dat_ready               (txdat_arb_in_ready[5]),
    .io_chi_tx_dat_valid               (e_chi_tx_dat_valid[5]),
    .io_chi_tx_dat_bits_tgtID          (e_chi_tx_dat_bits_tgtID[5]),
    .io_chi_tx_dat_bits_txnID          (e_chi_tx_dat_bits_txnID[5]),
    .io_chi_tx_dat_bits_respErr        (e_chi_tx_dat_bits_respErr[5]),
    .io_chi_tx_dat_bits_ccID           (e_chi_tx_dat_bits_ccID[5]),
    .io_chi_tx_dat_bits_dataID         (e_chi_tx_dat_bits_dataID[5]),
    .io_chi_tx_dat_bits_traceTag       (e_chi_tx_dat_bits_traceTag[5]),
    .io_chi_tx_dat_bits_be             (e_chi_tx_dat_bits_be[5]),
    .io_chi_tx_dat_bits_data           (e_chi_tx_dat_bits_data[5]),
    .io_chi_tx_dat_bits_dataCheck      (e_chi_tx_dat_bits_dataCheck[5]),
    .io_chi_tx_dat_bits_poison         (e_chi_tx_dat_bits_poison[5]),
    .io_chi_rx_rsp_ready               (e_chi_rx_rsp_ready[5]),
    .io_chi_rx_rsp_valid               (io_rx_rsp_valid & rxrsp_hit[5]),
    .io_chi_rx_rsp_bits_srcID          (io_rx_rsp_bits_srcID),
    .io_chi_rx_rsp_bits_opcode         (io_rx_rsp_bits_opcode),
    .io_chi_rx_rsp_bits_respErr        (io_rx_rsp_bits_respErr),
    .io_chi_rx_rsp_bits_dbID           (io_rx_rsp_bits_dbID),
    .io_chi_rx_rsp_bits_pCrdType       (io_rx_rsp_bits_pCrdType),
    .io_chi_rx_rsp_bits_traceTag       (io_rx_rsp_bits_traceTag),
    .io_chi_rx_dat_ready               (e_chi_rx_dat_ready[5]),
    .io_chi_rx_dat_valid               (io_rx_dat_valid & rxdat_hit[5]),
    .io_chi_rx_dat_bits_respErr        (io_rx_dat_bits_respErr),
    .io_chi_rx_dat_bits_data           (io_rx_dat_bits_data),
    .io_chi_rx_dat_bits_dataCheck      (io_rx_dat_bits_dataCheck),
    .io_chi_rx_dat_bits_poison         (io_rx_dat_bits_poison),
    .io_id                             (3'h5),
    .io_pCrd_query_valid               (io_pCrd_5_query_valid),
    .io_pCrd_query_bits_pCrdType       (io_pCrd_5_query_bits_pCrdType),
    .io_pCrd_query_bits_srcID          (io_pCrd_5_query_bits_srcID),
    .io_pCrd_grant                     (io_pCrd_5_grant),
    .io_waitOnReadReceipt              (e_waitOnReadReceipt[5])
  );
  MMIOBridgeEntry_4 entries_6 (
    .clock                             (clock),
    .reset                             (reset),
    .io_req_ready                      (e_req_ready[6]),
    .io_req_valid                      (a_valid & selectOH[6]),
    .io_req_bits_opcode                (a_opcode),
    .io_req_bits_size                  (a_size),
    .io_req_bits_source                (a_source),
    .io_req_bits_address               (a_address),
    .io_req_bits_user_memBackType_MM   (a_mm),
    .io_req_bits_user_memPageType_NC   (a_nc),
    .io_req_bits_mask                  (a_mask),
    .io_req_bits_data                  (a_data),
    .io_req_bits_corrupt               (a_corrupt),
    .io_resp_ready                     (d_arb_in_ready[6]),
    .io_resp_valid                     (e_resp_valid[6]),
    .io_resp_bits_opcode               (e_resp_bits_opcode[6]),
    .io_resp_bits_size                 (e_resp_bits_size[6]),
    .io_resp_bits_source               (e_resp_bits_source[6]),
    .io_resp_bits_denied               (e_resp_bits_denied[6]),
    .io_resp_bits_data                 (e_resp_bits_data[6]),
    .io_resp_bits_corrupt              (e_resp_bits_corrupt[6]),
    .io_chi_tx_req_ready               (txreq_arb_in_ready[6] & ~block_e[6]),
    .io_chi_tx_req_valid               (e_chi_tx_req_valid[6]),
    .io_chi_tx_req_bits_txnID          (e_chi_tx_req_bits_txnID[6]),
    .io_chi_tx_req_bits_opcode         (e_chi_tx_req_bits_opcode[6]),
    .io_chi_tx_req_bits_size           (e_chi_tx_req_bits_size[6]),
    .io_chi_tx_req_bits_addr           (e_chi_tx_req_bits_addr[6]),
    .io_chi_tx_req_bits_allowRetry     (e_chi_tx_req_bits_allowRetry[6]),
    .io_chi_tx_req_bits_order          (e_chi_tx_req_bits_order[6]),
    .io_chi_tx_req_bits_pCrdType       (e_chi_tx_req_bits_pCrdType[6]),
    .io_chi_tx_req_bits_memAttr_device (e_chi_tx_req_bits_memAttr_device[6]),
    .io_chi_tx_req_bits_memAttr_ewa    (e_chi_tx_req_bits_memAttr_ewa[6]),
    .io_chi_tx_dat_ready               (txdat_arb_in_ready[6]),
    .io_chi_tx_dat_valid               (e_chi_tx_dat_valid[6]),
    .io_chi_tx_dat_bits_tgtID          (e_chi_tx_dat_bits_tgtID[6]),
    .io_chi_tx_dat_bits_txnID          (e_chi_tx_dat_bits_txnID[6]),
    .io_chi_tx_dat_bits_respErr        (e_chi_tx_dat_bits_respErr[6]),
    .io_chi_tx_dat_bits_ccID           (e_chi_tx_dat_bits_ccID[6]),
    .io_chi_tx_dat_bits_dataID         (e_chi_tx_dat_bits_dataID[6]),
    .io_chi_tx_dat_bits_traceTag       (e_chi_tx_dat_bits_traceTag[6]),
    .io_chi_tx_dat_bits_be             (e_chi_tx_dat_bits_be[6]),
    .io_chi_tx_dat_bits_data           (e_chi_tx_dat_bits_data[6]),
    .io_chi_tx_dat_bits_dataCheck      (e_chi_tx_dat_bits_dataCheck[6]),
    .io_chi_tx_dat_bits_poison         (e_chi_tx_dat_bits_poison[6]),
    .io_chi_rx_rsp_ready               (e_chi_rx_rsp_ready[6]),
    .io_chi_rx_rsp_valid               (io_rx_rsp_valid & rxrsp_hit[6]),
    .io_chi_rx_rsp_bits_srcID          (io_rx_rsp_bits_srcID),
    .io_chi_rx_rsp_bits_opcode         (io_rx_rsp_bits_opcode),
    .io_chi_rx_rsp_bits_respErr        (io_rx_rsp_bits_respErr),
    .io_chi_rx_rsp_bits_dbID           (io_rx_rsp_bits_dbID),
    .io_chi_rx_rsp_bits_pCrdType       (io_rx_rsp_bits_pCrdType),
    .io_chi_rx_rsp_bits_traceTag       (io_rx_rsp_bits_traceTag),
    .io_chi_rx_dat_ready               (e_chi_rx_dat_ready[6]),
    .io_chi_rx_dat_valid               (io_rx_dat_valid & rxdat_hit[6]),
    .io_chi_rx_dat_bits_respErr        (io_rx_dat_bits_respErr),
    .io_chi_rx_dat_bits_data           (io_rx_dat_bits_data),
    .io_chi_rx_dat_bits_dataCheck      (io_rx_dat_bits_dataCheck),
    .io_chi_rx_dat_bits_poison         (io_rx_dat_bits_poison),
    .io_id                             (3'h6),
    .io_pCrd_query_valid               (io_pCrd_6_query_valid),
    .io_pCrd_query_bits_pCrdType       (io_pCrd_6_query_bits_pCrdType),
    .io_pCrd_query_bits_srcID          (io_pCrd_6_query_bits_srcID),
    .io_pCrd_grant                     (io_pCrd_6_grant),
    .io_waitOnReadReceipt              (e_waitOnReadReceipt[6])
  );
  MMIOBridgeEntry_4 entries_7 (
    .clock                             (clock),
    .reset                             (reset),
    .io_req_ready                      (e_req_ready[7]),
    .io_req_valid                      (a_valid & selectOH[7]),
    .io_req_bits_opcode                (a_opcode),
    .io_req_bits_size                  (a_size),
    .io_req_bits_source                (a_source),
    .io_req_bits_address               (a_address),
    .io_req_bits_user_memBackType_MM   (a_mm),
    .io_req_bits_user_memPageType_NC   (a_nc),
    .io_req_bits_mask                  (a_mask),
    .io_req_bits_data                  (a_data),
    .io_req_bits_corrupt               (a_corrupt),
    .io_resp_ready                     (d_arb_in_ready[7]),
    .io_resp_valid                     (e_resp_valid[7]),
    .io_resp_bits_opcode               (e_resp_bits_opcode[7]),
    .io_resp_bits_size                 (e_resp_bits_size[7]),
    .io_resp_bits_source               (e_resp_bits_source[7]),
    .io_resp_bits_denied               (e_resp_bits_denied[7]),
    .io_resp_bits_data                 (e_resp_bits_data[7]),
    .io_resp_bits_corrupt              (e_resp_bits_corrupt[7]),
    .io_chi_tx_req_ready               (txreq_arb_in_ready[7] & ~block_e[7]),
    .io_chi_tx_req_valid               (e_chi_tx_req_valid[7]),
    .io_chi_tx_req_bits_txnID          (e_chi_tx_req_bits_txnID[7]),
    .io_chi_tx_req_bits_opcode         (e_chi_tx_req_bits_opcode[7]),
    .io_chi_tx_req_bits_size           (e_chi_tx_req_bits_size[7]),
    .io_chi_tx_req_bits_addr           (e_chi_tx_req_bits_addr[7]),
    .io_chi_tx_req_bits_allowRetry     (e_chi_tx_req_bits_allowRetry[7]),
    .io_chi_tx_req_bits_order          (e_chi_tx_req_bits_order[7]),
    .io_chi_tx_req_bits_pCrdType       (e_chi_tx_req_bits_pCrdType[7]),
    .io_chi_tx_req_bits_memAttr_device (e_chi_tx_req_bits_memAttr_device[7]),
    .io_chi_tx_req_bits_memAttr_ewa    (e_chi_tx_req_bits_memAttr_ewa[7]),
    .io_chi_tx_dat_ready               (txdat_arb_in_ready[7]),
    .io_chi_tx_dat_valid               (e_chi_tx_dat_valid[7]),
    .io_chi_tx_dat_bits_tgtID          (e_chi_tx_dat_bits_tgtID[7]),
    .io_chi_tx_dat_bits_txnID          (e_chi_tx_dat_bits_txnID[7]),
    .io_chi_tx_dat_bits_respErr        (e_chi_tx_dat_bits_respErr[7]),
    .io_chi_tx_dat_bits_ccID           (e_chi_tx_dat_bits_ccID[7]),
    .io_chi_tx_dat_bits_dataID         (e_chi_tx_dat_bits_dataID[7]),
    .io_chi_tx_dat_bits_traceTag       (e_chi_tx_dat_bits_traceTag[7]),
    .io_chi_tx_dat_bits_be             (e_chi_tx_dat_bits_be[7]),
    .io_chi_tx_dat_bits_data           (e_chi_tx_dat_bits_data[7]),
    .io_chi_tx_dat_bits_dataCheck      (e_chi_tx_dat_bits_dataCheck[7]),
    .io_chi_tx_dat_bits_poison         (e_chi_tx_dat_bits_poison[7]),
    .io_chi_rx_rsp_ready               (e_chi_rx_rsp_ready[7]),
    .io_chi_rx_rsp_valid               (io_rx_rsp_valid & rxrsp_hit[7]),
    .io_chi_rx_rsp_bits_srcID          (io_rx_rsp_bits_srcID),
    .io_chi_rx_rsp_bits_opcode         (io_rx_rsp_bits_opcode),
    .io_chi_rx_rsp_bits_respErr        (io_rx_rsp_bits_respErr),
    .io_chi_rx_rsp_bits_dbID           (io_rx_rsp_bits_dbID),
    .io_chi_rx_rsp_bits_pCrdType       (io_rx_rsp_bits_pCrdType),
    .io_chi_rx_rsp_bits_traceTag       (io_rx_rsp_bits_traceTag),
    .io_chi_rx_dat_ready               (e_chi_rx_dat_ready[7]),
    .io_chi_rx_dat_valid               (io_rx_dat_valid & rxdat_hit[7]),
    .io_chi_rx_dat_bits_respErr        (io_rx_dat_bits_respErr),
    .io_chi_rx_dat_bits_data           (io_rx_dat_bits_data),
    .io_chi_rx_dat_bits_dataCheck      (io_rx_dat_bits_dataCheck),
    .io_chi_rx_dat_bits_poison         (io_rx_dat_bits_poison),
    .io_id                             (3'h7),
    .io_pCrd_query_valid               (io_pCrd_7_query_valid),
    .io_pCrd_query_bits_pCrdType       (io_pCrd_7_query_bits_pCrdType),
    .io_pCrd_query_bits_srcID          (io_pCrd_7_query_bits_srcID),
    .io_pCrd_grant                     (io_pCrd_7_grant),
    .io_waitOnReadReceipt              (e_waitOnReadReceipt[7])
  );

  // ---- (4a) txreqArb = RRArbiterInit_11 (绿 AUX, 黑盒): 8 条目 tx_req 汇聚 ----
  RRArbiterInit_11 txreqArb (
    .clock (clock),
    .reset (reset),
    .io_in_0_ready               (txreq_arb_in_ready[0]),
    .io_in_0_valid               (e_chi_tx_req_valid[0] & ~block_e[0]),
    .io_in_0_bits_txnID          (e_chi_tx_req_bits_txnID[0]),
    .io_in_0_bits_opcode         (e_chi_tx_req_bits_opcode[0]),
    .io_in_0_bits_size           (e_chi_tx_req_bits_size[0]),
    .io_in_0_bits_addr           (e_chi_tx_req_bits_addr[0]),
    .io_in_0_bits_allowRetry     (e_chi_tx_req_bits_allowRetry[0]),
    .io_in_0_bits_order          (e_chi_tx_req_bits_order[0]),
    .io_in_0_bits_pCrdType       (e_chi_tx_req_bits_pCrdType[0]),
    .io_in_0_bits_memAttr_device (e_chi_tx_req_bits_memAttr_device[0]),
    .io_in_0_bits_memAttr_ewa    (e_chi_tx_req_bits_memAttr_ewa[0]),
    .io_in_1_ready               (txreq_arb_in_ready[1]),
    .io_in_1_valid               (e_chi_tx_req_valid[1] & ~block_e[1]),
    .io_in_1_bits_txnID          (e_chi_tx_req_bits_txnID[1]),
    .io_in_1_bits_opcode         (e_chi_tx_req_bits_opcode[1]),
    .io_in_1_bits_size           (e_chi_tx_req_bits_size[1]),
    .io_in_1_bits_addr           (e_chi_tx_req_bits_addr[1]),
    .io_in_1_bits_allowRetry     (e_chi_tx_req_bits_allowRetry[1]),
    .io_in_1_bits_order          (e_chi_tx_req_bits_order[1]),
    .io_in_1_bits_pCrdType       (e_chi_tx_req_bits_pCrdType[1]),
    .io_in_1_bits_memAttr_device (e_chi_tx_req_bits_memAttr_device[1]),
    .io_in_1_bits_memAttr_ewa    (e_chi_tx_req_bits_memAttr_ewa[1]),
    .io_in_2_ready               (txreq_arb_in_ready[2]),
    .io_in_2_valid               (e_chi_tx_req_valid[2] & ~block_e[2]),
    .io_in_2_bits_txnID          (e_chi_tx_req_bits_txnID[2]),
    .io_in_2_bits_opcode         (e_chi_tx_req_bits_opcode[2]),
    .io_in_2_bits_size           (e_chi_tx_req_bits_size[2]),
    .io_in_2_bits_addr           (e_chi_tx_req_bits_addr[2]),
    .io_in_2_bits_allowRetry     (e_chi_tx_req_bits_allowRetry[2]),
    .io_in_2_bits_order          (e_chi_tx_req_bits_order[2]),
    .io_in_2_bits_pCrdType       (e_chi_tx_req_bits_pCrdType[2]),
    .io_in_2_bits_memAttr_device (e_chi_tx_req_bits_memAttr_device[2]),
    .io_in_2_bits_memAttr_ewa    (e_chi_tx_req_bits_memAttr_ewa[2]),
    .io_in_3_ready               (txreq_arb_in_ready[3]),
    .io_in_3_valid               (e_chi_tx_req_valid[3] & ~block_e[3]),
    .io_in_3_bits_txnID          (e_chi_tx_req_bits_txnID[3]),
    .io_in_3_bits_opcode         (e_chi_tx_req_bits_opcode[3]),
    .io_in_3_bits_size           (e_chi_tx_req_bits_size[3]),
    .io_in_3_bits_addr           (e_chi_tx_req_bits_addr[3]),
    .io_in_3_bits_allowRetry     (e_chi_tx_req_bits_allowRetry[3]),
    .io_in_3_bits_order          (e_chi_tx_req_bits_order[3]),
    .io_in_3_bits_pCrdType       (e_chi_tx_req_bits_pCrdType[3]),
    .io_in_3_bits_memAttr_device (e_chi_tx_req_bits_memAttr_device[3]),
    .io_in_3_bits_memAttr_ewa    (e_chi_tx_req_bits_memAttr_ewa[3]),
    .io_in_4_ready               (txreq_arb_in_ready[4]),
    .io_in_4_valid               (e_chi_tx_req_valid[4] & ~block_e[4]),
    .io_in_4_bits_txnID          (e_chi_tx_req_bits_txnID[4]),
    .io_in_4_bits_opcode         (e_chi_tx_req_bits_opcode[4]),
    .io_in_4_bits_size           (e_chi_tx_req_bits_size[4]),
    .io_in_4_bits_addr           (e_chi_tx_req_bits_addr[4]),
    .io_in_4_bits_allowRetry     (e_chi_tx_req_bits_allowRetry[4]),
    .io_in_4_bits_order          (e_chi_tx_req_bits_order[4]),
    .io_in_4_bits_pCrdType       (e_chi_tx_req_bits_pCrdType[4]),
    .io_in_4_bits_memAttr_device (e_chi_tx_req_bits_memAttr_device[4]),
    .io_in_4_bits_memAttr_ewa    (e_chi_tx_req_bits_memAttr_ewa[4]),
    .io_in_5_ready               (txreq_arb_in_ready[5]),
    .io_in_5_valid               (e_chi_tx_req_valid[5] & ~block_e[5]),
    .io_in_5_bits_txnID          (e_chi_tx_req_bits_txnID[5]),
    .io_in_5_bits_opcode         (e_chi_tx_req_bits_opcode[5]),
    .io_in_5_bits_size           (e_chi_tx_req_bits_size[5]),
    .io_in_5_bits_addr           (e_chi_tx_req_bits_addr[5]),
    .io_in_5_bits_allowRetry     (e_chi_tx_req_bits_allowRetry[5]),
    .io_in_5_bits_order          (e_chi_tx_req_bits_order[5]),
    .io_in_5_bits_pCrdType       (e_chi_tx_req_bits_pCrdType[5]),
    .io_in_5_bits_memAttr_device (e_chi_tx_req_bits_memAttr_device[5]),
    .io_in_5_bits_memAttr_ewa    (e_chi_tx_req_bits_memAttr_ewa[5]),
    .io_in_6_ready               (txreq_arb_in_ready[6]),
    .io_in_6_valid               (e_chi_tx_req_valid[6] & ~block_e[6]),
    .io_in_6_bits_txnID          (e_chi_tx_req_bits_txnID[6]),
    .io_in_6_bits_opcode         (e_chi_tx_req_bits_opcode[6]),
    .io_in_6_bits_size           (e_chi_tx_req_bits_size[6]),
    .io_in_6_bits_addr           (e_chi_tx_req_bits_addr[6]),
    .io_in_6_bits_allowRetry     (e_chi_tx_req_bits_allowRetry[6]),
    .io_in_6_bits_order          (e_chi_tx_req_bits_order[6]),
    .io_in_6_bits_pCrdType       (e_chi_tx_req_bits_pCrdType[6]),
    .io_in_6_bits_memAttr_device (e_chi_tx_req_bits_memAttr_device[6]),
    .io_in_6_bits_memAttr_ewa    (e_chi_tx_req_bits_memAttr_ewa[6]),
    .io_in_7_ready               (txreq_arb_in_ready[7]),
    .io_in_7_valid               (e_chi_tx_req_valid[7] & ~block_e[7]),
    .io_in_7_bits_txnID          (e_chi_tx_req_bits_txnID[7]),
    .io_in_7_bits_opcode         (e_chi_tx_req_bits_opcode[7]),
    .io_in_7_bits_size           (e_chi_tx_req_bits_size[7]),
    .io_in_7_bits_addr           (e_chi_tx_req_bits_addr[7]),
    .io_in_7_bits_allowRetry     (e_chi_tx_req_bits_allowRetry[7]),
    .io_in_7_bits_order          (e_chi_tx_req_bits_order[7]),
    .io_in_7_bits_pCrdType       (e_chi_tx_req_bits_pCrdType[7]),
    .io_in_7_bits_memAttr_device (e_chi_tx_req_bits_memAttr_device[7]),
    .io_in_7_bits_memAttr_ewa    (e_chi_tx_req_bits_memAttr_ewa[7]),
    .io_out_ready                (io_tx_req_ready),
    .io_out_valid                (io_tx_req_valid),
    .io_out_bits_txnID           (io_tx_req_bits_txnID),
    .io_out_bits_opcode          (io_tx_req_bits_opcode),
    .io_out_bits_size            (io_tx_req_bits_size),
    .io_out_bits_addr            (io_tx_req_bits_addr),
    .io_out_bits_allowRetry      (io_tx_req_bits_allowRetry),
    .io_out_bits_order           (io_tx_req_bits_order),
    .io_out_bits_pCrdType        (io_tx_req_bits_pCrdType),
    .io_out_bits_memAttr_device  (io_tx_req_bits_memAttr_device),
    .io_out_bits_memAttr_ewa     (io_tx_req_bits_memAttr_ewa)
  );

  // ---- (4b) mmio_txdat_arb = Arbiter8_CHIDAT (绿 AUX, 黑盒): 8 条目 tx_dat 汇聚 ----
  Arbiter8_CHIDAT mmio_txdat_arb (
    .io_in_0_ready          (txdat_arb_in_ready[0]),
    .io_in_0_valid          (e_chi_tx_dat_valid[0]),
    .io_in_0_bits_tgtID     (e_chi_tx_dat_bits_tgtID[0]),
    .io_in_0_bits_txnID     (e_chi_tx_dat_bits_txnID[0]),
    .io_in_0_bits_respErr   (e_chi_tx_dat_bits_respErr[0]),
    .io_in_0_bits_ccID      (e_chi_tx_dat_bits_ccID[0]),
    .io_in_0_bits_dataID    (e_chi_tx_dat_bits_dataID[0]),
    .io_in_0_bits_traceTag  (e_chi_tx_dat_bits_traceTag[0]),
    .io_in_0_bits_be        (e_chi_tx_dat_bits_be[0]),
    .io_in_0_bits_data      (e_chi_tx_dat_bits_data[0]),
    .io_in_0_bits_dataCheck (e_chi_tx_dat_bits_dataCheck[0]),
    .io_in_0_bits_poison    (e_chi_tx_dat_bits_poison[0]),
    .io_in_1_ready          (txdat_arb_in_ready[1]),
    .io_in_1_valid          (e_chi_tx_dat_valid[1]),
    .io_in_1_bits_tgtID     (e_chi_tx_dat_bits_tgtID[1]),
    .io_in_1_bits_txnID     (e_chi_tx_dat_bits_txnID[1]),
    .io_in_1_bits_respErr   (e_chi_tx_dat_bits_respErr[1]),
    .io_in_1_bits_ccID      (e_chi_tx_dat_bits_ccID[1]),
    .io_in_1_bits_dataID    (e_chi_tx_dat_bits_dataID[1]),
    .io_in_1_bits_traceTag  (e_chi_tx_dat_bits_traceTag[1]),
    .io_in_1_bits_be        (e_chi_tx_dat_bits_be[1]),
    .io_in_1_bits_data      (e_chi_tx_dat_bits_data[1]),
    .io_in_1_bits_dataCheck (e_chi_tx_dat_bits_dataCheck[1]),
    .io_in_1_bits_poison    (e_chi_tx_dat_bits_poison[1]),
    .io_in_2_ready          (txdat_arb_in_ready[2]),
    .io_in_2_valid          (e_chi_tx_dat_valid[2]),
    .io_in_2_bits_tgtID     (e_chi_tx_dat_bits_tgtID[2]),
    .io_in_2_bits_txnID     (e_chi_tx_dat_bits_txnID[2]),
    .io_in_2_bits_respErr   (e_chi_tx_dat_bits_respErr[2]),
    .io_in_2_bits_ccID      (e_chi_tx_dat_bits_ccID[2]),
    .io_in_2_bits_dataID    (e_chi_tx_dat_bits_dataID[2]),
    .io_in_2_bits_traceTag  (e_chi_tx_dat_bits_traceTag[2]),
    .io_in_2_bits_be        (e_chi_tx_dat_bits_be[2]),
    .io_in_2_bits_data      (e_chi_tx_dat_bits_data[2]),
    .io_in_2_bits_dataCheck (e_chi_tx_dat_bits_dataCheck[2]),
    .io_in_2_bits_poison    (e_chi_tx_dat_bits_poison[2]),
    .io_in_3_ready          (txdat_arb_in_ready[3]),
    .io_in_3_valid          (e_chi_tx_dat_valid[3]),
    .io_in_3_bits_tgtID     (e_chi_tx_dat_bits_tgtID[3]),
    .io_in_3_bits_txnID     (e_chi_tx_dat_bits_txnID[3]),
    .io_in_3_bits_respErr   (e_chi_tx_dat_bits_respErr[3]),
    .io_in_3_bits_ccID      (e_chi_tx_dat_bits_ccID[3]),
    .io_in_3_bits_dataID    (e_chi_tx_dat_bits_dataID[3]),
    .io_in_3_bits_traceTag  (e_chi_tx_dat_bits_traceTag[3]),
    .io_in_3_bits_be        (e_chi_tx_dat_bits_be[3]),
    .io_in_3_bits_data      (e_chi_tx_dat_bits_data[3]),
    .io_in_3_bits_dataCheck (e_chi_tx_dat_bits_dataCheck[3]),
    .io_in_3_bits_poison    (e_chi_tx_dat_bits_poison[3]),
    .io_in_4_ready          (txdat_arb_in_ready[4]),
    .io_in_4_valid          (e_chi_tx_dat_valid[4]),
    .io_in_4_bits_tgtID     (e_chi_tx_dat_bits_tgtID[4]),
    .io_in_4_bits_txnID     (e_chi_tx_dat_bits_txnID[4]),
    .io_in_4_bits_respErr   (e_chi_tx_dat_bits_respErr[4]),
    .io_in_4_bits_ccID      (e_chi_tx_dat_bits_ccID[4]),
    .io_in_4_bits_dataID    (e_chi_tx_dat_bits_dataID[4]),
    .io_in_4_bits_traceTag  (e_chi_tx_dat_bits_traceTag[4]),
    .io_in_4_bits_be        (e_chi_tx_dat_bits_be[4]),
    .io_in_4_bits_data      (e_chi_tx_dat_bits_data[4]),
    .io_in_4_bits_dataCheck (e_chi_tx_dat_bits_dataCheck[4]),
    .io_in_4_bits_poison    (e_chi_tx_dat_bits_poison[4]),
    .io_in_5_ready          (txdat_arb_in_ready[5]),
    .io_in_5_valid          (e_chi_tx_dat_valid[5]),
    .io_in_5_bits_tgtID     (e_chi_tx_dat_bits_tgtID[5]),
    .io_in_5_bits_txnID     (e_chi_tx_dat_bits_txnID[5]),
    .io_in_5_bits_respErr   (e_chi_tx_dat_bits_respErr[5]),
    .io_in_5_bits_ccID      (e_chi_tx_dat_bits_ccID[5]),
    .io_in_5_bits_dataID    (e_chi_tx_dat_bits_dataID[5]),
    .io_in_5_bits_traceTag  (e_chi_tx_dat_bits_traceTag[5]),
    .io_in_5_bits_be        (e_chi_tx_dat_bits_be[5]),
    .io_in_5_bits_data      (e_chi_tx_dat_bits_data[5]),
    .io_in_5_bits_dataCheck (e_chi_tx_dat_bits_dataCheck[5]),
    .io_in_5_bits_poison    (e_chi_tx_dat_bits_poison[5]),
    .io_in_6_ready          (txdat_arb_in_ready[6]),
    .io_in_6_valid          (e_chi_tx_dat_valid[6]),
    .io_in_6_bits_tgtID     (e_chi_tx_dat_bits_tgtID[6]),
    .io_in_6_bits_txnID     (e_chi_tx_dat_bits_txnID[6]),
    .io_in_6_bits_respErr   (e_chi_tx_dat_bits_respErr[6]),
    .io_in_6_bits_ccID      (e_chi_tx_dat_bits_ccID[6]),
    .io_in_6_bits_dataID    (e_chi_tx_dat_bits_dataID[6]),
    .io_in_6_bits_traceTag  (e_chi_tx_dat_bits_traceTag[6]),
    .io_in_6_bits_be        (e_chi_tx_dat_bits_be[6]),
    .io_in_6_bits_data      (e_chi_tx_dat_bits_data[6]),
    .io_in_6_bits_dataCheck (e_chi_tx_dat_bits_dataCheck[6]),
    .io_in_6_bits_poison    (e_chi_tx_dat_bits_poison[6]),
    .io_in_7_ready          (txdat_arb_in_ready[7]),
    .io_in_7_valid          (e_chi_tx_dat_valid[7]),
    .io_in_7_bits_tgtID     (e_chi_tx_dat_bits_tgtID[7]),
    .io_in_7_bits_txnID     (e_chi_tx_dat_bits_txnID[7]),
    .io_in_7_bits_respErr   (e_chi_tx_dat_bits_respErr[7]),
    .io_in_7_bits_ccID      (e_chi_tx_dat_bits_ccID[7]),
    .io_in_7_bits_dataID    (e_chi_tx_dat_bits_dataID[7]),
    .io_in_7_bits_traceTag  (e_chi_tx_dat_bits_traceTag[7]),
    .io_in_7_bits_be        (e_chi_tx_dat_bits_be[7]),
    .io_in_7_bits_data      (e_chi_tx_dat_bits_data[7]),
    .io_in_7_bits_dataCheck (e_chi_tx_dat_bits_dataCheck[7]),
    .io_in_7_bits_poison    (e_chi_tx_dat_bits_poison[7]),
    .io_out_ready          (io_tx_dat_ready),
    .io_out_valid          (io_tx_dat_valid),
    .io_out_bits_tgtID     (io_tx_dat_bits_tgtID),
    .io_out_bits_txnID     (io_tx_dat_bits_txnID),
    .io_out_bits_respErr   (io_tx_dat_bits_respErr),
    .io_out_bits_ccID      (io_tx_dat_bits_ccID),
    .io_out_bits_dataID    (io_tx_dat_bits_dataID),
    .io_out_bits_traceTag  (io_tx_dat_bits_traceTag),
    .io_out_bits_be        (io_tx_dat_bits_be),
    .io_out_bits_data      (io_tx_dat_bits_data),
    .io_out_bits_dataCheck (io_tx_dat_bits_dataCheck),
    .io_out_bits_poison    (io_tx_dat_bits_poison)
  );

  // ---- (4c) mmio_channel_D_arb = Arbiter8_TLBundleD (绿 AUX, 黑盒): 8 条目 D 汇聚 ----
  wire        d_valid;
  wire [3:0]  d_opcode;
  wire [1:0]  d_size;
  wire [2:0]  d_source;
  wire        d_denied;
  wire [63:0] d_data;
  wire        d_corrupt;
  Arbiter8_TLBundleD mmio_channel_D_arb (
    .io_in_0_ready        (d_arb_in_ready[0]),
    .io_in_0_valid        (e_resp_valid[0]),
    .io_in_0_bits_opcode  (e_resp_bits_opcode[0]),
    .io_in_0_bits_size    (e_resp_bits_size[0]),
    .io_in_0_bits_source  (e_resp_bits_source[0]),
    .io_in_0_bits_denied  (e_resp_bits_denied[0]),
    .io_in_0_bits_data    (e_resp_bits_data[0]),
    .io_in_0_bits_corrupt (e_resp_bits_corrupt[0]),
    .io_in_1_ready        (d_arb_in_ready[1]),
    .io_in_1_valid        (e_resp_valid[1]),
    .io_in_1_bits_opcode  (e_resp_bits_opcode[1]),
    .io_in_1_bits_size    (e_resp_bits_size[1]),
    .io_in_1_bits_source  (e_resp_bits_source[1]),
    .io_in_1_bits_denied  (e_resp_bits_denied[1]),
    .io_in_1_bits_data    (e_resp_bits_data[1]),
    .io_in_1_bits_corrupt (e_resp_bits_corrupt[1]),
    .io_in_2_ready        (d_arb_in_ready[2]),
    .io_in_2_valid        (e_resp_valid[2]),
    .io_in_2_bits_opcode  (e_resp_bits_opcode[2]),
    .io_in_2_bits_size    (e_resp_bits_size[2]),
    .io_in_2_bits_source  (e_resp_bits_source[2]),
    .io_in_2_bits_denied  (e_resp_bits_denied[2]),
    .io_in_2_bits_data    (e_resp_bits_data[2]),
    .io_in_2_bits_corrupt (e_resp_bits_corrupt[2]),
    .io_in_3_ready        (d_arb_in_ready[3]),
    .io_in_3_valid        (e_resp_valid[3]),
    .io_in_3_bits_opcode  (e_resp_bits_opcode[3]),
    .io_in_3_bits_size    (e_resp_bits_size[3]),
    .io_in_3_bits_source  (e_resp_bits_source[3]),
    .io_in_3_bits_denied  (e_resp_bits_denied[3]),
    .io_in_3_bits_data    (e_resp_bits_data[3]),
    .io_in_3_bits_corrupt (e_resp_bits_corrupt[3]),
    .io_in_4_ready        (d_arb_in_ready[4]),
    .io_in_4_valid        (e_resp_valid[4]),
    .io_in_4_bits_opcode  (e_resp_bits_opcode[4]),
    .io_in_4_bits_size    (e_resp_bits_size[4]),
    .io_in_4_bits_source  (e_resp_bits_source[4]),
    .io_in_4_bits_denied  (e_resp_bits_denied[4]),
    .io_in_4_bits_data    (e_resp_bits_data[4]),
    .io_in_4_bits_corrupt (e_resp_bits_corrupt[4]),
    .io_in_5_ready        (d_arb_in_ready[5]),
    .io_in_5_valid        (e_resp_valid[5]),
    .io_in_5_bits_opcode  (e_resp_bits_opcode[5]),
    .io_in_5_bits_size    (e_resp_bits_size[5]),
    .io_in_5_bits_source  (e_resp_bits_source[5]),
    .io_in_5_bits_denied  (e_resp_bits_denied[5]),
    .io_in_5_bits_data    (e_resp_bits_data[5]),
    .io_in_5_bits_corrupt (e_resp_bits_corrupt[5]),
    .io_in_6_ready        (d_arb_in_ready[6]),
    .io_in_6_valid        (e_resp_valid[6]),
    .io_in_6_bits_opcode  (e_resp_bits_opcode[6]),
    .io_in_6_bits_size    (e_resp_bits_size[6]),
    .io_in_6_bits_source  (e_resp_bits_source[6]),
    .io_in_6_bits_denied  (e_resp_bits_denied[6]),
    .io_in_6_bits_data    (e_resp_bits_data[6]),
    .io_in_6_bits_corrupt (e_resp_bits_corrupt[6]),
    .io_in_7_ready        (d_arb_in_ready[7]),
    .io_in_7_valid        (e_resp_valid[7]),
    .io_in_7_bits_opcode  (e_resp_bits_opcode[7]),
    .io_in_7_bits_size    (e_resp_bits_size[7]),
    .io_in_7_bits_source  (e_resp_bits_source[7]),
    .io_in_7_bits_denied  (e_resp_bits_denied[7]),
    .io_in_7_bits_data    (e_resp_bits_data[7]),
    .io_in_7_bits_corrupt (e_resp_bits_corrupt[7]),
    .io_out_ready         (d_ready),
    .io_out_valid         (d_valid),
    .io_out_bits_opcode   (d_opcode),
    .io_out_bits_size     (d_size),
    .io_out_bits_source   (d_source),
    .io_out_bits_denied   (d_denied),
    .io_out_bits_data     (d_data),
    .io_out_bits_corrupt  (d_corrupt)
  );

  // ---- (5) 顶层输出: A ready / D 通道 / CHI 常量绑定 ----
  assign auto_mmio_in_a_ready       = a_ready;
  assign auto_mmio_in_d_valid       = d_valid;
  assign auto_mmio_in_d_bits_opcode = d_opcode;
  assign auto_mmio_in_d_bits_param  = 2'h0;
  assign auto_mmio_in_d_bits_size   = d_size;
  assign auto_mmio_in_d_bits_source = d_source;
  assign auto_mmio_in_d_bits_sink   = 1'h0;
  assign auto_mmio_in_d_bits_denied = d_denied;
  assign auto_mmio_in_d_bits_data   = d_data;
  assign auto_mmio_in_d_bits_corrupt= d_corrupt;
  assign io_tx_req_bits_qos               = 4'h0;
  assign io_tx_req_bits_tgtID             = 11'h0;
  assign io_tx_req_bits_srcID             = 11'h0;
  assign io_tx_req_bits_returnNID         = 11'h0;
  assign io_tx_req_bits_stashNIDValid     = 1'h0;
  assign io_tx_req_bits_returnTxnID       = 12'h0;
  assign io_tx_req_bits_ns                = 1'h0;
  assign io_tx_req_bits_likelyshared      = 1'h0;
  assign io_tx_req_bits_memAttr_allocate  = 1'h0;
  assign io_tx_req_bits_memAttr_cacheable = 1'h0;
  assign io_tx_req_bits_snpAttr           = 1'h0;
  assign io_tx_req_bits_lpIDWithPadding   = 8'h0;
  assign io_tx_req_bits_snoopMe           = 1'h0;
  assign io_tx_req_bits_expCompAck        = 1'h0;
  assign io_tx_req_bits_tagOp             = 2'h0;
  assign io_tx_req_bits_traceTag          = 1'h0;
  assign io_tx_req_bits_mpam_perfMonGroup = 1'h0;
  assign io_tx_req_bits_mpam_partID       = 9'h0;
  assign io_tx_req_bits_mpam_mpamNS       = 1'h0;
  assign io_tx_req_bits_rsvdc             = 4'h0;
  assign io_tx_dat_bits_qos         = 4'h0;
  assign io_tx_dat_bits_srcID       = 11'h0;
  assign io_tx_dat_bits_homeNID     = 11'h0;
  assign io_tx_dat_bits_opcode      = 4'h3;
  assign io_tx_dat_bits_resp        = 3'h0;
  assign io_tx_dat_bits_dataSource  = 4'h0;
  assign io_tx_dat_bits_cBusy       = 3'h0;
  assign io_tx_dat_bits_dbID        = 12'h0;
  assign io_tx_dat_bits_tagOp       = 2'h0;
  assign io_tx_dat_bits_tag         = 8'h0;
  assign io_tx_dat_bits_tu          = 2'h0;
  assign io_tx_dat_bits_rsvdc       = 4'h0;
  assign io_rx_rsp_ready = 1'h1;
  assign io_rx_dat_ready = |{
    e_chi_rx_dat_ready[0] & rxdat_hit[0],
    e_chi_rx_dat_ready[1] & rxdat_hit[1],
    e_chi_rx_dat_ready[2] & rxdat_hit[2],
    e_chi_rx_dat_ready[3] & rxdat_hit[3],
    e_chi_rx_dat_ready[4] & rxdat_hit[4],
    e_chi_rx_dat_ready[5] & rxdat_hit[5],
    e_chi_rx_dat_ready[6] & rxdat_hit[6],
    e_chi_rx_dat_ready[7] & rxdat_hit[7]
  };

endmodule
