// 自动生成:scripts/gen_openllc.py —— 勿手改(顶层 glue 为从 Scala 意图的可读重写)

// 可读核端口表(与 golden OpenLLC 同名扁平端口,供 FM/ST 对接)。
// clock/reset 在核声明处单列,这里只列功能端口。
//   io_rn_0_*       北侧 CHI RN 端口(接 core 集群,tx=core->LLC, rx=LLC->core)
//   io_sn_*         南侧 CHI SN 端口(NoSnp,接内存)
//   io_debugTopDown_* 调试/性能监视接口
//   io_l3Miss       L3 整体 miss 指示(各 slice miss 汇聚一拍)
  input io_rn_0_txsactive,
  output io_rn_0_rxsactive,
  input io_rn_0_syscoreq,
  output io_rn_0_syscoack,
  input io_rn_0_tx_linkactivereq,
  output io_rn_0_tx_linkactiveack,
  input io_rn_0_tx_req_flitpend,
  input io_rn_0_tx_req_flitv,
  input [161:0] io_rn_0_tx_req_flit,
  output io_rn_0_tx_req_lcrdv,
  input io_rn_0_tx_rsp_flitpend,
  input io_rn_0_tx_rsp_flitv,
  input [72:0] io_rn_0_tx_rsp_flit,
  output io_rn_0_tx_rsp_lcrdv,
  input io_rn_0_tx_dat_flitpend,
  input io_rn_0_tx_dat_flitv,
  input [421:0] io_rn_0_tx_dat_flit,
  output io_rn_0_tx_dat_lcrdv,
  output io_rn_0_rx_linkactivereq,
  input io_rn_0_rx_linkactiveack,
  output io_rn_0_rx_rsp_flitpend,
  output io_rn_0_rx_rsp_flitv,
  output [72:0] io_rn_0_rx_rsp_flit,
  input io_rn_0_rx_rsp_lcrdv,
  output io_rn_0_rx_dat_flitpend,
  output io_rn_0_rx_dat_flitv,
  output [421:0] io_rn_0_rx_dat_flit,
  input io_rn_0_rx_dat_lcrdv,
  output io_rn_0_rx_snp_flitpend,
  output io_rn_0_rx_snp_flitv,
  output [114:0] io_rn_0_rx_snp_flit,
  input io_rn_0_rx_snp_lcrdv,
  output io_sn_txsactive,
  input io_sn_rxsactive,
  output io_sn_tx_linkactivereq,
  input io_sn_tx_linkactiveack,
  output io_sn_tx_req_flitpend,
  output io_sn_tx_req_flitv,
  output [161:0] io_sn_tx_req_flit,
  input io_sn_tx_req_lcrdv,
  output io_sn_tx_dat_flitpend,
  output io_sn_tx_dat_flitv,
  output [421:0] io_sn_tx_dat_flit,
  input io_sn_tx_dat_lcrdv,
  input io_sn_rx_linkactivereq,
  output io_sn_rx_linkactiveack,
  input io_sn_rx_rsp_flitpend,
  input io_sn_rx_rsp_flitv,
  input [72:0] io_sn_rx_rsp_flit,
  output io_sn_rx_rsp_lcrdv,
  input io_sn_rx_dat_flitpend,
  input io_sn_rx_dat_flitv,
  input [421:0] io_sn_rx_dat_flit,
  output io_sn_rx_dat_lcrdv,
  input io_debugTopDown_robHeadPaddr_0_valid,
  input [47:0] io_debugTopDown_robHeadPaddr_0_bits,
  output io_debugTopDown_addrMatch_0,
  output io_l3Miss
