// 自动生成:scripts/gen_openllc.py —— 勿手改(顶层 glue 为从 Scala 意图的可读重写)

// 子模块(golden 黑盒)输出/互联网声明,宽度从 golden wire 声明收割。
//   _<inst>_io_*  : 子模块输出引脚网(slice/xbar/linkmon/mmio 之间的 CHI 互联);
//   _probe        : difftest/dontTouch 探针(_topDown 的 addrMatch 镜像)。
// 由 openllc_inst.svh 绑定子模块输出引脚,互联直连 / outassign 消费。

  logic _rnLinkMonitor_io_in_tx_req_valid;
  logic [3:0] _rnLinkMonitor_io_in_tx_req_bits_qos;
  logic [10:0] _rnLinkMonitor_io_in_tx_req_bits_tgtID;
  logic [10:0] _rnLinkMonitor_io_in_tx_req_bits_srcID;
  logic [11:0] _rnLinkMonitor_io_in_tx_req_bits_txnID;
  logic [10:0] _rnLinkMonitor_io_in_tx_req_bits_returnNID;
  logic _rnLinkMonitor_io_in_tx_req_bits_stashNIDValid;
  logic [11:0] _rnLinkMonitor_io_in_tx_req_bits_returnTxnID;
  logic [6:0] _rnLinkMonitor_io_in_tx_req_bits_opcode;
  logic [2:0] _rnLinkMonitor_io_in_tx_req_bits_size;
  logic [47:0] _rnLinkMonitor_io_in_tx_req_bits_addr;
  logic _rnLinkMonitor_io_in_tx_req_bits_ns;
  logic _rnLinkMonitor_io_in_tx_req_bits_likelyshared;
  logic _rnLinkMonitor_io_in_tx_req_bits_allowRetry;
  logic [1:0] _rnLinkMonitor_io_in_tx_req_bits_order;
  logic [3:0] _rnLinkMonitor_io_in_tx_req_bits_pCrdType;
  logic _rnLinkMonitor_io_in_tx_req_bits_memAttr_allocate;
  logic _rnLinkMonitor_io_in_tx_req_bits_memAttr_cacheable;
  logic _rnLinkMonitor_io_in_tx_req_bits_memAttr_device;
  logic _rnLinkMonitor_io_in_tx_req_bits_memAttr_ewa;
  logic _rnLinkMonitor_io_in_tx_req_bits_snpAttr;
  logic [7:0] _rnLinkMonitor_io_in_tx_req_bits_lpIDWithPadding;
  logic _rnLinkMonitor_io_in_tx_req_bits_snoopMe;
  logic _rnLinkMonitor_io_in_tx_req_bits_expCompAck;
  logic [1:0] _rnLinkMonitor_io_in_tx_req_bits_tagOp;
  logic _rnLinkMonitor_io_in_tx_req_bits_traceTag;
  logic _rnLinkMonitor_io_in_tx_req_bits_mpam_perfMonGroup;
  logic [8:0] _rnLinkMonitor_io_in_tx_req_bits_mpam_partID;
  logic _rnLinkMonitor_io_in_tx_req_bits_mpam_mpamNS;
  logic [3:0] _rnLinkMonitor_io_in_tx_req_bits_rsvdc;
  logic _rnLinkMonitor_io_in_tx_rsp_valid;
  logic [10:0] _rnLinkMonitor_io_in_tx_rsp_bits_srcID;
  logic [11:0] _rnLinkMonitor_io_in_tx_rsp_bits_txnID;
  logic [4:0] _rnLinkMonitor_io_in_tx_rsp_bits_opcode;
  logic [11:0] _rnLinkMonitor_io_in_tx_rsp_bits_dbID;
  logic _rnLinkMonitor_io_in_tx_dat_valid;
  logic [3:0] _rnLinkMonitor_io_in_tx_dat_bits_qos;
  logic [10:0] _rnLinkMonitor_io_in_tx_dat_bits_tgtID;
  logic [10:0] _rnLinkMonitor_io_in_tx_dat_bits_srcID;
  logic [11:0] _rnLinkMonitor_io_in_tx_dat_bits_txnID;
  logic [10:0] _rnLinkMonitor_io_in_tx_dat_bits_homeNID;
  logic [3:0] _rnLinkMonitor_io_in_tx_dat_bits_opcode;
  logic [1:0] _rnLinkMonitor_io_in_tx_dat_bits_respErr;
  logic [2:0] _rnLinkMonitor_io_in_tx_dat_bits_resp;
  logic [3:0] _rnLinkMonitor_io_in_tx_dat_bits_dataSource;
  logic [2:0] _rnLinkMonitor_io_in_tx_dat_bits_cBusy;
  logic [11:0] _rnLinkMonitor_io_in_tx_dat_bits_dbID;
  logic [1:0] _rnLinkMonitor_io_in_tx_dat_bits_ccID;
  logic [1:0] _rnLinkMonitor_io_in_tx_dat_bits_dataID;
  logic [1:0] _rnLinkMonitor_io_in_tx_dat_bits_tagOp;
  logic [7:0] _rnLinkMonitor_io_in_tx_dat_bits_tag;
  logic [1:0] _rnLinkMonitor_io_in_tx_dat_bits_tu;
  logic _rnLinkMonitor_io_in_tx_dat_bits_traceTag;
  logic [3:0] _rnLinkMonitor_io_in_tx_dat_bits_rsvdc;
  logic [31:0] _rnLinkMonitor_io_in_tx_dat_bits_be;
  logic [255:0] _rnLinkMonitor_io_in_tx_dat_bits_data;
  logic [31:0] _rnLinkMonitor_io_in_tx_dat_bits_dataCheck;
  logic [3:0] _rnLinkMonitor_io_in_tx_dat_bits_poison;
  logic _rnLinkMonitor_io_in_rx_rsp_ready;
  logic _rnLinkMonitor_io_in_rx_dat_ready;
  logic _rnLinkMonitor_io_in_rx_snp_ready;
  logic _slices_3_io_in_tx_req_ready;
  logic _slices_3_io_in_rx_rsp_valid;
  logic [10:0] _slices_3_io_in_rx_rsp_bits_tgtID;
  logic [10:0] _slices_3_io_in_rx_rsp_bits_srcID;
  logic [11:0] _slices_3_io_in_rx_rsp_bits_txnID;
  logic [4:0] _slices_3_io_in_rx_rsp_bits_opcode;
  logic [2:0] _slices_3_io_in_rx_rsp_bits_resp;
  logic [2:0] _slices_3_io_in_rx_rsp_bits_fwdState;
  logic [11:0] _slices_3_io_in_rx_rsp_bits_dbID;
  logic [3:0] _slices_3_io_in_rx_rsp_bits_pCrdType;
  logic _slices_3_io_in_rx_dat_valid;
  logic [10:0] _slices_3_io_in_rx_dat_bits_tgtID;
  logic [10:0] _slices_3_io_in_rx_dat_bits_srcID;
  logic [11:0] _slices_3_io_in_rx_dat_bits_txnID;
  logic [10:0] _slices_3_io_in_rx_dat_bits_homeNID;
  logic [3:0] _slices_3_io_in_rx_dat_bits_opcode;
  logic [2:0] _slices_3_io_in_rx_dat_bits_resp;
  logic [3:0] _slices_3_io_in_rx_dat_bits_dataSource;
  logic [11:0] _slices_3_io_in_rx_dat_bits_dbID;
  logic [1:0] _slices_3_io_in_rx_dat_bits_dataID;
  logic [31:0] _slices_3_io_in_rx_dat_bits_be;
  logic [255:0] _slices_3_io_in_rx_dat_bits_data;
  logic [31:0] _slices_3_io_in_rx_dat_bits_dataCheck;
  logic _slices_3_io_in_rx_snp_valid;
  logic [11:0] _slices_3_io_in_rx_snp_bits_txnID;
  logic [10:0] _slices_3_io_in_rx_snp_bits_fwdNID;
  logic [11:0] _slices_3_io_in_rx_snp_bits_fwdTxnID;
  logic [4:0] _slices_3_io_in_rx_snp_bits_opcode;
  logic [44:0] _slices_3_io_in_rx_snp_bits_addr;
  logic _slices_3_io_in_rx_snp_bits_doNotGoToSD;
  logic _slices_3_io_in_rx_snp_bits_retToSrc;
  logic _slices_3_io_out_tx_req_valid;
  logic [10:0] _slices_3_io_out_tx_req_bits_tgtID;
  logic [10:0] _slices_3_io_out_tx_req_bits_srcID;
  logic [11:0] _slices_3_io_out_tx_req_bits_txnID;
  logic [6:0] _slices_3_io_out_tx_req_bits_opcode;
  logic [2:0] _slices_3_io_out_tx_req_bits_size;
  logic [47:0] _slices_3_io_out_tx_req_bits_addr;
  logic _slices_3_io_out_tx_req_bits_allowRetry;
  logic [1:0] _slices_3_io_out_tx_req_bits_order;
  logic [3:0] _slices_3_io_out_tx_req_bits_pCrdType;
  logic _slices_3_io_out_tx_req_bits_memAttr_allocate;
  logic _slices_3_io_out_tx_req_bits_memAttr_cacheable;
  logic _slices_3_io_out_tx_req_bits_memAttr_device;
  logic _slices_3_io_out_tx_req_bits_memAttr_ewa;
  logic _slices_3_io_out_tx_req_bits_snpAttr;
  logic _slices_3_io_out_tx_req_bits_expCompAck;
  logic _slices_3_io_out_tx_dat_valid;
  logic [10:0] _slices_3_io_out_tx_dat_bits_tgtID;
  logic [10:0] _slices_3_io_out_tx_dat_bits_srcID;
  logic [11:0] _slices_3_io_out_tx_dat_bits_txnID;
  logic [10:0] _slices_3_io_out_tx_dat_bits_homeNID;
  logic [3:0] _slices_3_io_out_tx_dat_bits_opcode;
  logic [2:0] _slices_3_io_out_tx_dat_bits_resp;
  logic [3:0] _slices_3_io_out_tx_dat_bits_dataSource;
  logic [11:0] _slices_3_io_out_tx_dat_bits_dbID;
  logic [1:0] _slices_3_io_out_tx_dat_bits_dataID;
  logic [31:0] _slices_3_io_out_tx_dat_bits_be;
  logic [255:0] _slices_3_io_out_tx_dat_bits_data;
  logic [31:0] _slices_3_io_out_tx_dat_bits_dataCheck;
  logic _slices_3_io_snpMask_0;
  logic _slices_3_io_msStatus_0_valid;
  logic [11:0] _slices_3_io_msStatus_0_bits_set;
  logic [27:0] _slices_3_io_msStatus_0_bits_tag;
  logic [6:0] _slices_3_io_msStatus_0_bits_opcode;
  logic _slices_3_io_msStatus_0_bits_is_miss;
  logic _slices_3_io_msStatus_1_valid;
  logic [11:0] _slices_3_io_msStatus_1_bits_set;
  logic [27:0] _slices_3_io_msStatus_1_bits_tag;
  logic [6:0] _slices_3_io_msStatus_1_bits_opcode;
  logic _slices_3_io_msStatus_1_bits_is_miss;
  logic _slices_3_io_msStatus_2_valid;
  logic [11:0] _slices_3_io_msStatus_2_bits_set;
  logic [27:0] _slices_3_io_msStatus_2_bits_tag;
  logic [6:0] _slices_3_io_msStatus_2_bits_opcode;
  logic _slices_3_io_msStatus_2_bits_is_miss;
  logic _slices_3_io_msStatus_3_valid;
  logic [11:0] _slices_3_io_msStatus_3_bits_set;
  logic [27:0] _slices_3_io_msStatus_3_bits_tag;
  logic [6:0] _slices_3_io_msStatus_3_bits_opcode;
  logic _slices_3_io_msStatus_3_bits_is_miss;
  logic _slices_3_io_msStatus_4_valid;
  logic [11:0] _slices_3_io_msStatus_4_bits_set;
  logic [27:0] _slices_3_io_msStatus_4_bits_tag;
  logic [6:0] _slices_3_io_msStatus_4_bits_opcode;
  logic _slices_3_io_msStatus_4_bits_is_miss;
  logic _slices_3_io_msStatus_5_valid;
  logic [11:0] _slices_3_io_msStatus_5_bits_set;
  logic [27:0] _slices_3_io_msStatus_5_bits_tag;
  logic [6:0] _slices_3_io_msStatus_5_bits_opcode;
  logic _slices_3_io_msStatus_5_bits_is_miss;
  logic _slices_3_io_msStatus_6_valid;
  logic [11:0] _slices_3_io_msStatus_6_bits_set;
  logic [27:0] _slices_3_io_msStatus_6_bits_tag;
  logic [6:0] _slices_3_io_msStatus_6_bits_opcode;
  logic _slices_3_io_msStatus_6_bits_is_miss;
  logic _slices_3_io_msStatus_7_valid;
  logic [11:0] _slices_3_io_msStatus_7_bits_set;
  logic [27:0] _slices_3_io_msStatus_7_bits_tag;
  logic [6:0] _slices_3_io_msStatus_7_bits_opcode;
  logic _slices_3_io_msStatus_7_bits_is_miss;
  logic _slices_3_io_msStatus_8_valid;
  logic [11:0] _slices_3_io_msStatus_8_bits_set;
  logic [27:0] _slices_3_io_msStatus_8_bits_tag;
  logic [6:0] _slices_3_io_msStatus_8_bits_opcode;
  logic _slices_3_io_msStatus_8_bits_is_miss;
  logic _slices_3_io_msStatus_9_valid;
  logic [11:0] _slices_3_io_msStatus_9_bits_set;
  logic [27:0] _slices_3_io_msStatus_9_bits_tag;
  logic [6:0] _slices_3_io_msStatus_9_bits_opcode;
  logic _slices_3_io_msStatus_9_bits_is_miss;
  logic _slices_3_io_msStatus_10_valid;
  logic [11:0] _slices_3_io_msStatus_10_bits_set;
  logic [27:0] _slices_3_io_msStatus_10_bits_tag;
  logic [6:0] _slices_3_io_msStatus_10_bits_opcode;
  logic _slices_3_io_msStatus_10_bits_is_miss;
  logic _slices_3_io_msStatus_11_valid;
  logic [11:0] _slices_3_io_msStatus_11_bits_set;
  logic [27:0] _slices_3_io_msStatus_11_bits_tag;
  logic [6:0] _slices_3_io_msStatus_11_bits_opcode;
  logic _slices_3_io_msStatus_11_bits_is_miss;
  logic _slices_3_io_msStatus_12_valid;
  logic [11:0] _slices_3_io_msStatus_12_bits_set;
  logic [27:0] _slices_3_io_msStatus_12_bits_tag;
  logic [6:0] _slices_3_io_msStatus_12_bits_opcode;
  logic _slices_3_io_msStatus_12_bits_is_miss;
  logic _slices_3_io_msStatus_13_valid;
  logic [11:0] _slices_3_io_msStatus_13_bits_set;
  logic [27:0] _slices_3_io_msStatus_13_bits_tag;
  logic [6:0] _slices_3_io_msStatus_13_bits_opcode;
  logic _slices_3_io_msStatus_13_bits_is_miss;
  logic _slices_3_io_msStatus_14_valid;
  logic [11:0] _slices_3_io_msStatus_14_bits_set;
  logic [27:0] _slices_3_io_msStatus_14_bits_tag;
  logic [6:0] _slices_3_io_msStatus_14_bits_opcode;
  logic _slices_3_io_msStatus_14_bits_is_miss;
  logic _slices_3_io_msStatus_15_valid;
  logic [11:0] _slices_3_io_msStatus_15_bits_set;
  logic [27:0] _slices_3_io_msStatus_15_bits_tag;
  logic [6:0] _slices_3_io_msStatus_15_bits_opcode;
  logic _slices_3_io_msStatus_15_bits_is_miss;
  logic _slices_3_io_l3Miss;
  logic _slices_2_io_in_tx_req_ready;
  logic _slices_2_io_in_rx_rsp_valid;
  logic [10:0] _slices_2_io_in_rx_rsp_bits_tgtID;
  logic [10:0] _slices_2_io_in_rx_rsp_bits_srcID;
  logic [11:0] _slices_2_io_in_rx_rsp_bits_txnID;
  logic [4:0] _slices_2_io_in_rx_rsp_bits_opcode;
  logic [2:0] _slices_2_io_in_rx_rsp_bits_resp;
  logic [2:0] _slices_2_io_in_rx_rsp_bits_fwdState;
  logic [11:0] _slices_2_io_in_rx_rsp_bits_dbID;
  logic [3:0] _slices_2_io_in_rx_rsp_bits_pCrdType;
  logic _slices_2_io_in_rx_dat_valid;
  logic [10:0] _slices_2_io_in_rx_dat_bits_tgtID;
  logic [10:0] _slices_2_io_in_rx_dat_bits_srcID;
  logic [11:0] _slices_2_io_in_rx_dat_bits_txnID;
  logic [10:0] _slices_2_io_in_rx_dat_bits_homeNID;
  logic [3:0] _slices_2_io_in_rx_dat_bits_opcode;
  logic [2:0] _slices_2_io_in_rx_dat_bits_resp;
  logic [3:0] _slices_2_io_in_rx_dat_bits_dataSource;
  logic [11:0] _slices_2_io_in_rx_dat_bits_dbID;
  logic [1:0] _slices_2_io_in_rx_dat_bits_dataID;
  logic [31:0] _slices_2_io_in_rx_dat_bits_be;
  logic [255:0] _slices_2_io_in_rx_dat_bits_data;
  logic [31:0] _slices_2_io_in_rx_dat_bits_dataCheck;
  logic _slices_2_io_in_rx_snp_valid;
  logic [11:0] _slices_2_io_in_rx_snp_bits_txnID;
  logic [10:0] _slices_2_io_in_rx_snp_bits_fwdNID;
  logic [11:0] _slices_2_io_in_rx_snp_bits_fwdTxnID;
  logic [4:0] _slices_2_io_in_rx_snp_bits_opcode;
  logic [44:0] _slices_2_io_in_rx_snp_bits_addr;
  logic _slices_2_io_in_rx_snp_bits_doNotGoToSD;
  logic _slices_2_io_in_rx_snp_bits_retToSrc;
  logic _slices_2_io_out_tx_req_valid;
  logic [10:0] _slices_2_io_out_tx_req_bits_tgtID;
  logic [10:0] _slices_2_io_out_tx_req_bits_srcID;
  logic [11:0] _slices_2_io_out_tx_req_bits_txnID;
  logic [6:0] _slices_2_io_out_tx_req_bits_opcode;
  logic [2:0] _slices_2_io_out_tx_req_bits_size;
  logic [47:0] _slices_2_io_out_tx_req_bits_addr;
  logic _slices_2_io_out_tx_req_bits_allowRetry;
  logic [1:0] _slices_2_io_out_tx_req_bits_order;
  logic [3:0] _slices_2_io_out_tx_req_bits_pCrdType;
  logic _slices_2_io_out_tx_req_bits_memAttr_allocate;
  logic _slices_2_io_out_tx_req_bits_memAttr_cacheable;
  logic _slices_2_io_out_tx_req_bits_memAttr_device;
  logic _slices_2_io_out_tx_req_bits_memAttr_ewa;
  logic _slices_2_io_out_tx_req_bits_snpAttr;
  logic _slices_2_io_out_tx_req_bits_expCompAck;
  logic _slices_2_io_out_tx_dat_valid;
  logic [10:0] _slices_2_io_out_tx_dat_bits_tgtID;
  logic [10:0] _slices_2_io_out_tx_dat_bits_srcID;
  logic [11:0] _slices_2_io_out_tx_dat_bits_txnID;
  logic [10:0] _slices_2_io_out_tx_dat_bits_homeNID;
  logic [3:0] _slices_2_io_out_tx_dat_bits_opcode;
  logic [2:0] _slices_2_io_out_tx_dat_bits_resp;
  logic [3:0] _slices_2_io_out_tx_dat_bits_dataSource;
  logic [11:0] _slices_2_io_out_tx_dat_bits_dbID;
  logic [1:0] _slices_2_io_out_tx_dat_bits_dataID;
  logic [31:0] _slices_2_io_out_tx_dat_bits_be;
  logic [255:0] _slices_2_io_out_tx_dat_bits_data;
  logic [31:0] _slices_2_io_out_tx_dat_bits_dataCheck;
  logic _slices_2_io_snpMask_0;
  logic _slices_2_io_msStatus_0_valid;
  logic [11:0] _slices_2_io_msStatus_0_bits_set;
  logic [27:0] _slices_2_io_msStatus_0_bits_tag;
  logic [6:0] _slices_2_io_msStatus_0_bits_opcode;
  logic _slices_2_io_msStatus_0_bits_is_miss;
  logic _slices_2_io_msStatus_1_valid;
  logic [11:0] _slices_2_io_msStatus_1_bits_set;
  logic [27:0] _slices_2_io_msStatus_1_bits_tag;
  logic [6:0] _slices_2_io_msStatus_1_bits_opcode;
  logic _slices_2_io_msStatus_1_bits_is_miss;
  logic _slices_2_io_msStatus_2_valid;
  logic [11:0] _slices_2_io_msStatus_2_bits_set;
  logic [27:0] _slices_2_io_msStatus_2_bits_tag;
  logic [6:0] _slices_2_io_msStatus_2_bits_opcode;
  logic _slices_2_io_msStatus_2_bits_is_miss;
  logic _slices_2_io_msStatus_3_valid;
  logic [11:0] _slices_2_io_msStatus_3_bits_set;
  logic [27:0] _slices_2_io_msStatus_3_bits_tag;
  logic [6:0] _slices_2_io_msStatus_3_bits_opcode;
  logic _slices_2_io_msStatus_3_bits_is_miss;
  logic _slices_2_io_msStatus_4_valid;
  logic [11:0] _slices_2_io_msStatus_4_bits_set;
  logic [27:0] _slices_2_io_msStatus_4_bits_tag;
  logic [6:0] _slices_2_io_msStatus_4_bits_opcode;
  logic _slices_2_io_msStatus_4_bits_is_miss;
  logic _slices_2_io_msStatus_5_valid;
  logic [11:0] _slices_2_io_msStatus_5_bits_set;
  logic [27:0] _slices_2_io_msStatus_5_bits_tag;
  logic [6:0] _slices_2_io_msStatus_5_bits_opcode;
  logic _slices_2_io_msStatus_5_bits_is_miss;
  logic _slices_2_io_msStatus_6_valid;
  logic [11:0] _slices_2_io_msStatus_6_bits_set;
  logic [27:0] _slices_2_io_msStatus_6_bits_tag;
  logic [6:0] _slices_2_io_msStatus_6_bits_opcode;
  logic _slices_2_io_msStatus_6_bits_is_miss;
  logic _slices_2_io_msStatus_7_valid;
  logic [11:0] _slices_2_io_msStatus_7_bits_set;
  logic [27:0] _slices_2_io_msStatus_7_bits_tag;
  logic [6:0] _slices_2_io_msStatus_7_bits_opcode;
  logic _slices_2_io_msStatus_7_bits_is_miss;
  logic _slices_2_io_msStatus_8_valid;
  logic [11:0] _slices_2_io_msStatus_8_bits_set;
  logic [27:0] _slices_2_io_msStatus_8_bits_tag;
  logic [6:0] _slices_2_io_msStatus_8_bits_opcode;
  logic _slices_2_io_msStatus_8_bits_is_miss;
  logic _slices_2_io_msStatus_9_valid;
  logic [11:0] _slices_2_io_msStatus_9_bits_set;
  logic [27:0] _slices_2_io_msStatus_9_bits_tag;
  logic [6:0] _slices_2_io_msStatus_9_bits_opcode;
  logic _slices_2_io_msStatus_9_bits_is_miss;
  logic _slices_2_io_msStatus_10_valid;
  logic [11:0] _slices_2_io_msStatus_10_bits_set;
  logic [27:0] _slices_2_io_msStatus_10_bits_tag;
  logic [6:0] _slices_2_io_msStatus_10_bits_opcode;
  logic _slices_2_io_msStatus_10_bits_is_miss;
  logic _slices_2_io_msStatus_11_valid;
  logic [11:0] _slices_2_io_msStatus_11_bits_set;
  logic [27:0] _slices_2_io_msStatus_11_bits_tag;
  logic [6:0] _slices_2_io_msStatus_11_bits_opcode;
  logic _slices_2_io_msStatus_11_bits_is_miss;
  logic _slices_2_io_msStatus_12_valid;
  logic [11:0] _slices_2_io_msStatus_12_bits_set;
  logic [27:0] _slices_2_io_msStatus_12_bits_tag;
  logic [6:0] _slices_2_io_msStatus_12_bits_opcode;
  logic _slices_2_io_msStatus_12_bits_is_miss;
  logic _slices_2_io_msStatus_13_valid;
  logic [11:0] _slices_2_io_msStatus_13_bits_set;
  logic [27:0] _slices_2_io_msStatus_13_bits_tag;
  logic [6:0] _slices_2_io_msStatus_13_bits_opcode;
  logic _slices_2_io_msStatus_13_bits_is_miss;
  logic _slices_2_io_msStatus_14_valid;
  logic [11:0] _slices_2_io_msStatus_14_bits_set;
  logic [27:0] _slices_2_io_msStatus_14_bits_tag;
  logic [6:0] _slices_2_io_msStatus_14_bits_opcode;
  logic _slices_2_io_msStatus_14_bits_is_miss;
  logic _slices_2_io_msStatus_15_valid;
  logic [11:0] _slices_2_io_msStatus_15_bits_set;
  logic [27:0] _slices_2_io_msStatus_15_bits_tag;
  logic [6:0] _slices_2_io_msStatus_15_bits_opcode;
  logic _slices_2_io_msStatus_15_bits_is_miss;
  logic _slices_2_io_l3Miss;
  logic _slices_1_io_in_tx_req_ready;
  logic _slices_1_io_in_rx_rsp_valid;
  logic [10:0] _slices_1_io_in_rx_rsp_bits_tgtID;
  logic [10:0] _slices_1_io_in_rx_rsp_bits_srcID;
  logic [11:0] _slices_1_io_in_rx_rsp_bits_txnID;
  logic [4:0] _slices_1_io_in_rx_rsp_bits_opcode;
  logic [2:0] _slices_1_io_in_rx_rsp_bits_resp;
  logic [2:0] _slices_1_io_in_rx_rsp_bits_fwdState;
  logic [11:0] _slices_1_io_in_rx_rsp_bits_dbID;
  logic [3:0] _slices_1_io_in_rx_rsp_bits_pCrdType;
  logic _slices_1_io_in_rx_dat_valid;
  logic [10:0] _slices_1_io_in_rx_dat_bits_tgtID;
  logic [10:0] _slices_1_io_in_rx_dat_bits_srcID;
  logic [11:0] _slices_1_io_in_rx_dat_bits_txnID;
  logic [10:0] _slices_1_io_in_rx_dat_bits_homeNID;
  logic [3:0] _slices_1_io_in_rx_dat_bits_opcode;
  logic [2:0] _slices_1_io_in_rx_dat_bits_resp;
  logic [3:0] _slices_1_io_in_rx_dat_bits_dataSource;
  logic [11:0] _slices_1_io_in_rx_dat_bits_dbID;
  logic [1:0] _slices_1_io_in_rx_dat_bits_dataID;
  logic [31:0] _slices_1_io_in_rx_dat_bits_be;
  logic [255:0] _slices_1_io_in_rx_dat_bits_data;
  logic [31:0] _slices_1_io_in_rx_dat_bits_dataCheck;
  logic _slices_1_io_in_rx_snp_valid;
  logic [11:0] _slices_1_io_in_rx_snp_bits_txnID;
  logic [10:0] _slices_1_io_in_rx_snp_bits_fwdNID;
  logic [11:0] _slices_1_io_in_rx_snp_bits_fwdTxnID;
  logic [4:0] _slices_1_io_in_rx_snp_bits_opcode;
  logic [44:0] _slices_1_io_in_rx_snp_bits_addr;
  logic _slices_1_io_in_rx_snp_bits_doNotGoToSD;
  logic _slices_1_io_in_rx_snp_bits_retToSrc;
  logic _slices_1_io_out_tx_req_valid;
  logic [10:0] _slices_1_io_out_tx_req_bits_tgtID;
  logic [10:0] _slices_1_io_out_tx_req_bits_srcID;
  logic [11:0] _slices_1_io_out_tx_req_bits_txnID;
  logic [6:0] _slices_1_io_out_tx_req_bits_opcode;
  logic [2:0] _slices_1_io_out_tx_req_bits_size;
  logic [47:0] _slices_1_io_out_tx_req_bits_addr;
  logic _slices_1_io_out_tx_req_bits_allowRetry;
  logic [1:0] _slices_1_io_out_tx_req_bits_order;
  logic [3:0] _slices_1_io_out_tx_req_bits_pCrdType;
  logic _slices_1_io_out_tx_req_bits_memAttr_allocate;
  logic _slices_1_io_out_tx_req_bits_memAttr_cacheable;
  logic _slices_1_io_out_tx_req_bits_memAttr_device;
  logic _slices_1_io_out_tx_req_bits_memAttr_ewa;
  logic _slices_1_io_out_tx_req_bits_snpAttr;
  logic _slices_1_io_out_tx_req_bits_expCompAck;
  logic _slices_1_io_out_tx_dat_valid;
  logic [10:0] _slices_1_io_out_tx_dat_bits_tgtID;
  logic [10:0] _slices_1_io_out_tx_dat_bits_srcID;
  logic [11:0] _slices_1_io_out_tx_dat_bits_txnID;
  logic [10:0] _slices_1_io_out_tx_dat_bits_homeNID;
  logic [3:0] _slices_1_io_out_tx_dat_bits_opcode;
  logic [2:0] _slices_1_io_out_tx_dat_bits_resp;
  logic [3:0] _slices_1_io_out_tx_dat_bits_dataSource;
  logic [11:0] _slices_1_io_out_tx_dat_bits_dbID;
  logic [1:0] _slices_1_io_out_tx_dat_bits_dataID;
  logic [31:0] _slices_1_io_out_tx_dat_bits_be;
  logic [255:0] _slices_1_io_out_tx_dat_bits_data;
  logic [31:0] _slices_1_io_out_tx_dat_bits_dataCheck;
  logic _slices_1_io_snpMask_0;
  logic _slices_1_io_msStatus_0_valid;
  logic [11:0] _slices_1_io_msStatus_0_bits_set;
  logic [27:0] _slices_1_io_msStatus_0_bits_tag;
  logic [6:0] _slices_1_io_msStatus_0_bits_opcode;
  logic _slices_1_io_msStatus_0_bits_is_miss;
  logic _slices_1_io_msStatus_1_valid;
  logic [11:0] _slices_1_io_msStatus_1_bits_set;
  logic [27:0] _slices_1_io_msStatus_1_bits_tag;
  logic [6:0] _slices_1_io_msStatus_1_bits_opcode;
  logic _slices_1_io_msStatus_1_bits_is_miss;
  logic _slices_1_io_msStatus_2_valid;
  logic [11:0] _slices_1_io_msStatus_2_bits_set;
  logic [27:0] _slices_1_io_msStatus_2_bits_tag;
  logic [6:0] _slices_1_io_msStatus_2_bits_opcode;
  logic _slices_1_io_msStatus_2_bits_is_miss;
  logic _slices_1_io_msStatus_3_valid;
  logic [11:0] _slices_1_io_msStatus_3_bits_set;
  logic [27:0] _slices_1_io_msStatus_3_bits_tag;
  logic [6:0] _slices_1_io_msStatus_3_bits_opcode;
  logic _slices_1_io_msStatus_3_bits_is_miss;
  logic _slices_1_io_msStatus_4_valid;
  logic [11:0] _slices_1_io_msStatus_4_bits_set;
  logic [27:0] _slices_1_io_msStatus_4_bits_tag;
  logic [6:0] _slices_1_io_msStatus_4_bits_opcode;
  logic _slices_1_io_msStatus_4_bits_is_miss;
  logic _slices_1_io_msStatus_5_valid;
  logic [11:0] _slices_1_io_msStatus_5_bits_set;
  logic [27:0] _slices_1_io_msStatus_5_bits_tag;
  logic [6:0] _slices_1_io_msStatus_5_bits_opcode;
  logic _slices_1_io_msStatus_5_bits_is_miss;
  logic _slices_1_io_msStatus_6_valid;
  logic [11:0] _slices_1_io_msStatus_6_bits_set;
  logic [27:0] _slices_1_io_msStatus_6_bits_tag;
  logic [6:0] _slices_1_io_msStatus_6_bits_opcode;
  logic _slices_1_io_msStatus_6_bits_is_miss;
  logic _slices_1_io_msStatus_7_valid;
  logic [11:0] _slices_1_io_msStatus_7_bits_set;
  logic [27:0] _slices_1_io_msStatus_7_bits_tag;
  logic [6:0] _slices_1_io_msStatus_7_bits_opcode;
  logic _slices_1_io_msStatus_7_bits_is_miss;
  logic _slices_1_io_msStatus_8_valid;
  logic [11:0] _slices_1_io_msStatus_8_bits_set;
  logic [27:0] _slices_1_io_msStatus_8_bits_tag;
  logic [6:0] _slices_1_io_msStatus_8_bits_opcode;
  logic _slices_1_io_msStatus_8_bits_is_miss;
  logic _slices_1_io_msStatus_9_valid;
  logic [11:0] _slices_1_io_msStatus_9_bits_set;
  logic [27:0] _slices_1_io_msStatus_9_bits_tag;
  logic [6:0] _slices_1_io_msStatus_9_bits_opcode;
  logic _slices_1_io_msStatus_9_bits_is_miss;
  logic _slices_1_io_msStatus_10_valid;
  logic [11:0] _slices_1_io_msStatus_10_bits_set;
  logic [27:0] _slices_1_io_msStatus_10_bits_tag;
  logic [6:0] _slices_1_io_msStatus_10_bits_opcode;
  logic _slices_1_io_msStatus_10_bits_is_miss;
  logic _slices_1_io_msStatus_11_valid;
  logic [11:0] _slices_1_io_msStatus_11_bits_set;
  logic [27:0] _slices_1_io_msStatus_11_bits_tag;
  logic [6:0] _slices_1_io_msStatus_11_bits_opcode;
  logic _slices_1_io_msStatus_11_bits_is_miss;
  logic _slices_1_io_msStatus_12_valid;
  logic [11:0] _slices_1_io_msStatus_12_bits_set;
  logic [27:0] _slices_1_io_msStatus_12_bits_tag;
  logic [6:0] _slices_1_io_msStatus_12_bits_opcode;
  logic _slices_1_io_msStatus_12_bits_is_miss;
  logic _slices_1_io_msStatus_13_valid;
  logic [11:0] _slices_1_io_msStatus_13_bits_set;
  logic [27:0] _slices_1_io_msStatus_13_bits_tag;
  logic [6:0] _slices_1_io_msStatus_13_bits_opcode;
  logic _slices_1_io_msStatus_13_bits_is_miss;
  logic _slices_1_io_msStatus_14_valid;
  logic [11:0] _slices_1_io_msStatus_14_bits_set;
  logic [27:0] _slices_1_io_msStatus_14_bits_tag;
  logic [6:0] _slices_1_io_msStatus_14_bits_opcode;
  logic _slices_1_io_msStatus_14_bits_is_miss;
  logic _slices_1_io_msStatus_15_valid;
  logic [11:0] _slices_1_io_msStatus_15_bits_set;
  logic [27:0] _slices_1_io_msStatus_15_bits_tag;
  logic [6:0] _slices_1_io_msStatus_15_bits_opcode;
  logic _slices_1_io_msStatus_15_bits_is_miss;
  logic _slices_1_io_l3Miss;
  logic _slices_0_io_in_tx_req_ready;
  logic _slices_0_io_in_rx_rsp_valid;
  logic [10:0] _slices_0_io_in_rx_rsp_bits_tgtID;
  logic [10:0] _slices_0_io_in_rx_rsp_bits_srcID;
  logic [11:0] _slices_0_io_in_rx_rsp_bits_txnID;
  logic [4:0] _slices_0_io_in_rx_rsp_bits_opcode;
  logic [2:0] _slices_0_io_in_rx_rsp_bits_resp;
  logic [2:0] _slices_0_io_in_rx_rsp_bits_fwdState;
  logic [11:0] _slices_0_io_in_rx_rsp_bits_dbID;
  logic [3:0] _slices_0_io_in_rx_rsp_bits_pCrdType;
  logic _slices_0_io_in_rx_dat_valid;
  logic [10:0] _slices_0_io_in_rx_dat_bits_tgtID;
  logic [10:0] _slices_0_io_in_rx_dat_bits_srcID;
  logic [11:0] _slices_0_io_in_rx_dat_bits_txnID;
  logic [10:0] _slices_0_io_in_rx_dat_bits_homeNID;
  logic [3:0] _slices_0_io_in_rx_dat_bits_opcode;
  logic [2:0] _slices_0_io_in_rx_dat_bits_resp;
  logic [3:0] _slices_0_io_in_rx_dat_bits_dataSource;
  logic [11:0] _slices_0_io_in_rx_dat_bits_dbID;
  logic [1:0] _slices_0_io_in_rx_dat_bits_dataID;
  logic [31:0] _slices_0_io_in_rx_dat_bits_be;
  logic [255:0] _slices_0_io_in_rx_dat_bits_data;
  logic [31:0] _slices_0_io_in_rx_dat_bits_dataCheck;
  logic _slices_0_io_in_rx_snp_valid;
  logic [11:0] _slices_0_io_in_rx_snp_bits_txnID;
  logic [10:0] _slices_0_io_in_rx_snp_bits_fwdNID;
  logic [11:0] _slices_0_io_in_rx_snp_bits_fwdTxnID;
  logic [4:0] _slices_0_io_in_rx_snp_bits_opcode;
  logic [44:0] _slices_0_io_in_rx_snp_bits_addr;
  logic _slices_0_io_in_rx_snp_bits_doNotGoToSD;
  logic _slices_0_io_in_rx_snp_bits_retToSrc;
  logic _slices_0_io_out_tx_req_valid;
  logic [10:0] _slices_0_io_out_tx_req_bits_tgtID;
  logic [10:0] _slices_0_io_out_tx_req_bits_srcID;
  logic [11:0] _slices_0_io_out_tx_req_bits_txnID;
  logic [6:0] _slices_0_io_out_tx_req_bits_opcode;
  logic [2:0] _slices_0_io_out_tx_req_bits_size;
  logic [47:0] _slices_0_io_out_tx_req_bits_addr;
  logic _slices_0_io_out_tx_req_bits_allowRetry;
  logic [1:0] _slices_0_io_out_tx_req_bits_order;
  logic [3:0] _slices_0_io_out_tx_req_bits_pCrdType;
  logic _slices_0_io_out_tx_req_bits_memAttr_allocate;
  logic _slices_0_io_out_tx_req_bits_memAttr_cacheable;
  logic _slices_0_io_out_tx_req_bits_memAttr_device;
  logic _slices_0_io_out_tx_req_bits_memAttr_ewa;
  logic _slices_0_io_out_tx_req_bits_snpAttr;
  logic _slices_0_io_out_tx_req_bits_expCompAck;
  logic _slices_0_io_out_tx_dat_valid;
  logic [10:0] _slices_0_io_out_tx_dat_bits_tgtID;
  logic [10:0] _slices_0_io_out_tx_dat_bits_srcID;
  logic [11:0] _slices_0_io_out_tx_dat_bits_txnID;
  logic [10:0] _slices_0_io_out_tx_dat_bits_homeNID;
  logic [3:0] _slices_0_io_out_tx_dat_bits_opcode;
  logic [2:0] _slices_0_io_out_tx_dat_bits_resp;
  logic [3:0] _slices_0_io_out_tx_dat_bits_dataSource;
  logic [11:0] _slices_0_io_out_tx_dat_bits_dbID;
  logic [1:0] _slices_0_io_out_tx_dat_bits_dataID;
  logic [31:0] _slices_0_io_out_tx_dat_bits_be;
  logic [255:0] _slices_0_io_out_tx_dat_bits_data;
  logic [31:0] _slices_0_io_out_tx_dat_bits_dataCheck;
  logic _slices_0_io_snpMask_0;
  logic _slices_0_io_msStatus_0_valid;
  logic [11:0] _slices_0_io_msStatus_0_bits_set;
  logic [27:0] _slices_0_io_msStatus_0_bits_tag;
  logic [6:0] _slices_0_io_msStatus_0_bits_opcode;
  logic _slices_0_io_msStatus_0_bits_is_miss;
  logic _slices_0_io_msStatus_1_valid;
  logic [11:0] _slices_0_io_msStatus_1_bits_set;
  logic [27:0] _slices_0_io_msStatus_1_bits_tag;
  logic [6:0] _slices_0_io_msStatus_1_bits_opcode;
  logic _slices_0_io_msStatus_1_bits_is_miss;
  logic _slices_0_io_msStatus_2_valid;
  logic [11:0] _slices_0_io_msStatus_2_bits_set;
  logic [27:0] _slices_0_io_msStatus_2_bits_tag;
  logic [6:0] _slices_0_io_msStatus_2_bits_opcode;
  logic _slices_0_io_msStatus_2_bits_is_miss;
  logic _slices_0_io_msStatus_3_valid;
  logic [11:0] _slices_0_io_msStatus_3_bits_set;
  logic [27:0] _slices_0_io_msStatus_3_bits_tag;
  logic [6:0] _slices_0_io_msStatus_3_bits_opcode;
  logic _slices_0_io_msStatus_3_bits_is_miss;
  logic _slices_0_io_msStatus_4_valid;
  logic [11:0] _slices_0_io_msStatus_4_bits_set;
  logic [27:0] _slices_0_io_msStatus_4_bits_tag;
  logic [6:0] _slices_0_io_msStatus_4_bits_opcode;
  logic _slices_0_io_msStatus_4_bits_is_miss;
  logic _slices_0_io_msStatus_5_valid;
  logic [11:0] _slices_0_io_msStatus_5_bits_set;
  logic [27:0] _slices_0_io_msStatus_5_bits_tag;
  logic [6:0] _slices_0_io_msStatus_5_bits_opcode;
  logic _slices_0_io_msStatus_5_bits_is_miss;
  logic _slices_0_io_msStatus_6_valid;
  logic [11:0] _slices_0_io_msStatus_6_bits_set;
  logic [27:0] _slices_0_io_msStatus_6_bits_tag;
  logic [6:0] _slices_0_io_msStatus_6_bits_opcode;
  logic _slices_0_io_msStatus_6_bits_is_miss;
  logic _slices_0_io_msStatus_7_valid;
  logic [11:0] _slices_0_io_msStatus_7_bits_set;
  logic [27:0] _slices_0_io_msStatus_7_bits_tag;
  logic [6:0] _slices_0_io_msStatus_7_bits_opcode;
  logic _slices_0_io_msStatus_7_bits_is_miss;
  logic _slices_0_io_msStatus_8_valid;
  logic [11:0] _slices_0_io_msStatus_8_bits_set;
  logic [27:0] _slices_0_io_msStatus_8_bits_tag;
  logic [6:0] _slices_0_io_msStatus_8_bits_opcode;
  logic _slices_0_io_msStatus_8_bits_is_miss;
  logic _slices_0_io_msStatus_9_valid;
  logic [11:0] _slices_0_io_msStatus_9_bits_set;
  logic [27:0] _slices_0_io_msStatus_9_bits_tag;
  logic [6:0] _slices_0_io_msStatus_9_bits_opcode;
  logic _slices_0_io_msStatus_9_bits_is_miss;
  logic _slices_0_io_msStatus_10_valid;
  logic [11:0] _slices_0_io_msStatus_10_bits_set;
  logic [27:0] _slices_0_io_msStatus_10_bits_tag;
  logic [6:0] _slices_0_io_msStatus_10_bits_opcode;
  logic _slices_0_io_msStatus_10_bits_is_miss;
  logic _slices_0_io_msStatus_11_valid;
  logic [11:0] _slices_0_io_msStatus_11_bits_set;
  logic [27:0] _slices_0_io_msStatus_11_bits_tag;
  logic [6:0] _slices_0_io_msStatus_11_bits_opcode;
  logic _slices_0_io_msStatus_11_bits_is_miss;
  logic _slices_0_io_msStatus_12_valid;
  logic [11:0] _slices_0_io_msStatus_12_bits_set;
  logic [27:0] _slices_0_io_msStatus_12_bits_tag;
  logic [6:0] _slices_0_io_msStatus_12_bits_opcode;
  logic _slices_0_io_msStatus_12_bits_is_miss;
  logic _slices_0_io_msStatus_13_valid;
  logic [11:0] _slices_0_io_msStatus_13_bits_set;
  logic [27:0] _slices_0_io_msStatus_13_bits_tag;
  logic [6:0] _slices_0_io_msStatus_13_bits_opcode;
  logic _slices_0_io_msStatus_13_bits_is_miss;
  logic _slices_0_io_msStatus_14_valid;
  logic [11:0] _slices_0_io_msStatus_14_bits_set;
  logic [27:0] _slices_0_io_msStatus_14_bits_tag;
  logic [6:0] _slices_0_io_msStatus_14_bits_opcode;
  logic _slices_0_io_msStatus_14_bits_is_miss;
  logic _slices_0_io_msStatus_15_valid;
  logic [11:0] _slices_0_io_msStatus_15_bits_set;
  logic [27:0] _slices_0_io_msStatus_15_bits_tag;
  logic [6:0] _slices_0_io_msStatus_15_bits_opcode;
  logic _slices_0_io_msStatus_15_bits_is_miss;
  logic _slices_0_io_l3Miss;
  logic _topDown_io_debugTopDown_addrMatch_0;
  logic _snLinkMonitor_io_in_tx_req_ready;
  logic _snLinkMonitor_io_in_tx_dat_ready;
  logic _snLinkMonitor_io_in_rx_rsp_valid;
  logic [3:0] _snLinkMonitor_io_in_rx_rsp_bits_qos;
  logic [10:0] _snLinkMonitor_io_in_rx_rsp_bits_tgtID;
  logic [10:0] _snLinkMonitor_io_in_rx_rsp_bits_srcID;
  logic [11:0] _snLinkMonitor_io_in_rx_rsp_bits_txnID;
  logic [4:0] _snLinkMonitor_io_in_rx_rsp_bits_opcode;
  logic [1:0] _snLinkMonitor_io_in_rx_rsp_bits_respErr;
  logic [2:0] _snLinkMonitor_io_in_rx_rsp_bits_resp;
  logic [2:0] _snLinkMonitor_io_in_rx_rsp_bits_fwdState;
  logic [2:0] _snLinkMonitor_io_in_rx_rsp_bits_cBusy;
  logic [11:0] _snLinkMonitor_io_in_rx_rsp_bits_dbID;
  logic [3:0] _snLinkMonitor_io_in_rx_rsp_bits_pCrdType;
  logic [1:0] _snLinkMonitor_io_in_rx_rsp_bits_tagOp;
  logic _snLinkMonitor_io_in_rx_rsp_bits_traceTag;
  logic _snLinkMonitor_io_in_rx_dat_valid;
  logic [3:0] _snLinkMonitor_io_in_rx_dat_bits_qos;
  logic [10:0] _snLinkMonitor_io_in_rx_dat_bits_tgtID;
  logic [10:0] _snLinkMonitor_io_in_rx_dat_bits_srcID;
  logic [11:0] _snLinkMonitor_io_in_rx_dat_bits_txnID;
  logic [10:0] _snLinkMonitor_io_in_rx_dat_bits_homeNID;
  logic [3:0] _snLinkMonitor_io_in_rx_dat_bits_opcode;
  logic [1:0] _snLinkMonitor_io_in_rx_dat_bits_respErr;
  logic [2:0] _snLinkMonitor_io_in_rx_dat_bits_resp;
  logic [3:0] _snLinkMonitor_io_in_rx_dat_bits_dataSource;
  logic [2:0] _snLinkMonitor_io_in_rx_dat_bits_cBusy;
  logic [11:0] _snLinkMonitor_io_in_rx_dat_bits_dbID;
  logic [1:0] _snLinkMonitor_io_in_rx_dat_bits_ccID;
  logic [1:0] _snLinkMonitor_io_in_rx_dat_bits_dataID;
  logic [1:0] _snLinkMonitor_io_in_rx_dat_bits_tagOp;
  logic [7:0] _snLinkMonitor_io_in_rx_dat_bits_tag;
  logic [1:0] _snLinkMonitor_io_in_rx_dat_bits_tu;
  logic _snLinkMonitor_io_in_rx_dat_bits_traceTag;
  logic [3:0] _snLinkMonitor_io_in_rx_dat_bits_rsvdc;
  logic [31:0] _snLinkMonitor_io_in_rx_dat_bits_be;
  logic [255:0] _snLinkMonitor_io_in_rx_dat_bits_data;
  logic [31:0] _snLinkMonitor_io_in_rx_dat_bits_dataCheck;
  logic [3:0] _snLinkMonitor_io_in_rx_dat_bits_poison;
  logic _snXbar_io_in_0_tx_req_ready;
  logic _snXbar_io_in_0_tx_dat_ready;
  logic _snXbar_io_in_0_rx_rsp_valid;
  logic [10:0] _snXbar_io_in_0_rx_rsp_bits_srcID;
  logic [11:0] _snXbar_io_in_0_rx_rsp_bits_txnID;
  logic [4:0] _snXbar_io_in_0_rx_rsp_bits_opcode;
  logic [11:0] _snXbar_io_in_0_rx_rsp_bits_dbID;
  logic _snXbar_io_in_0_rx_dat_valid;
  logic [10:0] _snXbar_io_in_0_rx_dat_bits_srcID;
  logic [11:0] _snXbar_io_in_0_rx_dat_bits_txnID;
  logic [3:0] _snXbar_io_in_0_rx_dat_bits_opcode;
  logic [2:0] _snXbar_io_in_0_rx_dat_bits_resp;
  logic [1:0] _snXbar_io_in_0_rx_dat_bits_dataID;
  logic [255:0] _snXbar_io_in_0_rx_dat_bits_data;
  logic _snXbar_io_in_1_tx_req_ready;
  logic _snXbar_io_in_1_tx_dat_ready;
  logic _snXbar_io_in_1_rx_rsp_valid;
  logic [10:0] _snXbar_io_in_1_rx_rsp_bits_srcID;
  logic [11:0] _snXbar_io_in_1_rx_rsp_bits_txnID;
  logic [4:0] _snXbar_io_in_1_rx_rsp_bits_opcode;
  logic [11:0] _snXbar_io_in_1_rx_rsp_bits_dbID;
  logic _snXbar_io_in_1_rx_dat_valid;
  logic [10:0] _snXbar_io_in_1_rx_dat_bits_srcID;
  logic [11:0] _snXbar_io_in_1_rx_dat_bits_txnID;
  logic [3:0] _snXbar_io_in_1_rx_dat_bits_opcode;
  logic [2:0] _snXbar_io_in_1_rx_dat_bits_resp;
  logic [1:0] _snXbar_io_in_1_rx_dat_bits_dataID;
  logic [255:0] _snXbar_io_in_1_rx_dat_bits_data;
  logic _snXbar_io_in_2_tx_req_ready;
  logic _snXbar_io_in_2_tx_dat_ready;
  logic _snXbar_io_in_2_rx_rsp_valid;
  logic [10:0] _snXbar_io_in_2_rx_rsp_bits_srcID;
  logic [11:0] _snXbar_io_in_2_rx_rsp_bits_txnID;
  logic [4:0] _snXbar_io_in_2_rx_rsp_bits_opcode;
  logic [11:0] _snXbar_io_in_2_rx_rsp_bits_dbID;
  logic _snXbar_io_in_2_rx_dat_valid;
  logic [10:0] _snXbar_io_in_2_rx_dat_bits_srcID;
  logic [11:0] _snXbar_io_in_2_rx_dat_bits_txnID;
  logic [3:0] _snXbar_io_in_2_rx_dat_bits_opcode;
  logic [2:0] _snXbar_io_in_2_rx_dat_bits_resp;
  logic [1:0] _snXbar_io_in_2_rx_dat_bits_dataID;
  logic [255:0] _snXbar_io_in_2_rx_dat_bits_data;
  logic _snXbar_io_in_3_tx_req_ready;
  logic _snXbar_io_in_3_tx_dat_ready;
  logic _snXbar_io_in_3_rx_rsp_valid;
  logic [10:0] _snXbar_io_in_3_rx_rsp_bits_srcID;
  logic [11:0] _snXbar_io_in_3_rx_rsp_bits_txnID;
  logic [4:0] _snXbar_io_in_3_rx_rsp_bits_opcode;
  logic [11:0] _snXbar_io_in_3_rx_rsp_bits_dbID;
  logic _snXbar_io_in_3_rx_dat_valid;
  logic [10:0] _snXbar_io_in_3_rx_dat_bits_srcID;
  logic [11:0] _snXbar_io_in_3_rx_dat_bits_txnID;
  logic [3:0] _snXbar_io_in_3_rx_dat_bits_opcode;
  logic [2:0] _snXbar_io_in_3_rx_dat_bits_resp;
  logic [1:0] _snXbar_io_in_3_rx_dat_bits_dataID;
  logic [255:0] _snXbar_io_in_3_rx_dat_bits_data;
  logic _snXbar_io_out_tx_req_valid;
  logic [10:0] _snXbar_io_out_tx_req_bits_tgtID;
  logic [10:0] _snXbar_io_out_tx_req_bits_srcID;
  logic [11:0] _snXbar_io_out_tx_req_bits_txnID;
  logic [6:0] _snXbar_io_out_tx_req_bits_opcode;
  logic [2:0] _snXbar_io_out_tx_req_bits_size;
  logic [47:0] _snXbar_io_out_tx_req_bits_addr;
  logic _snXbar_io_out_tx_req_bits_allowRetry;
  logic [1:0] _snXbar_io_out_tx_req_bits_order;
  logic [3:0] _snXbar_io_out_tx_req_bits_pCrdType;
  logic _snXbar_io_out_tx_req_bits_memAttr_allocate;
  logic _snXbar_io_out_tx_req_bits_memAttr_cacheable;
  logic _snXbar_io_out_tx_req_bits_memAttr_device;
  logic _snXbar_io_out_tx_req_bits_memAttr_ewa;
  logic _snXbar_io_out_tx_req_bits_snpAttr;
  logic _snXbar_io_out_tx_req_bits_expCompAck;
  logic _snXbar_io_out_tx_dat_valid;
  logic [10:0] _snXbar_io_out_tx_dat_bits_tgtID;
  logic [10:0] _snXbar_io_out_tx_dat_bits_srcID;
  logic [11:0] _snXbar_io_out_tx_dat_bits_txnID;
  logic [10:0] _snXbar_io_out_tx_dat_bits_homeNID;
  logic [3:0] _snXbar_io_out_tx_dat_bits_opcode;
  logic [2:0] _snXbar_io_out_tx_dat_bits_resp;
  logic [3:0] _snXbar_io_out_tx_dat_bits_dataSource;
  logic [11:0] _snXbar_io_out_tx_dat_bits_dbID;
  logic [1:0] _snXbar_io_out_tx_dat_bits_dataID;
  logic [31:0] _snXbar_io_out_tx_dat_bits_be;
  logic [255:0] _snXbar_io_out_tx_dat_bits_data;
  logic [31:0] _snXbar_io_out_tx_dat_bits_dataCheck;
  logic _snXbar_io_out_rx_rsp_ready;
  logic _snXbar_io_out_rx_dat_ready;
  logic _rnXbar_io_in_0_tx_req_ready;
  logic _rnXbar_io_in_0_tx_rsp_ready;
  logic _rnXbar_io_in_0_tx_dat_ready;
  logic _rnXbar_io_in_0_rx_rsp_valid;
  logic [3:0] _rnXbar_io_in_0_rx_rsp_bits_qos;
  logic [11:0] _rnXbar_io_in_0_rx_rsp_bits_txnID;
  logic [4:0] _rnXbar_io_in_0_rx_rsp_bits_opcode;
  logic [1:0] _rnXbar_io_in_0_rx_rsp_bits_respErr;
  logic [2:0] _rnXbar_io_in_0_rx_rsp_bits_resp;
  logic [2:0] _rnXbar_io_in_0_rx_rsp_bits_fwdState;
  logic [2:0] _rnXbar_io_in_0_rx_rsp_bits_cBusy;
  logic [11:0] _rnXbar_io_in_0_rx_rsp_bits_dbID;
  logic [3:0] _rnXbar_io_in_0_rx_rsp_bits_pCrdType;
  logic [1:0] _rnXbar_io_in_0_rx_rsp_bits_tagOp;
  logic _rnXbar_io_in_0_rx_rsp_bits_traceTag;
  logic _rnXbar_io_in_0_rx_dat_valid;
  logic [11:0] _rnXbar_io_in_0_rx_dat_bits_txnID;
  logic [10:0] _rnXbar_io_in_0_rx_dat_bits_homeNID;
  logic [3:0] _rnXbar_io_in_0_rx_dat_bits_opcode;
  logic [2:0] _rnXbar_io_in_0_rx_dat_bits_resp;
  logic [3:0] _rnXbar_io_in_0_rx_dat_bits_dataSource;
  logic [11:0] _rnXbar_io_in_0_rx_dat_bits_dbID;
  logic [1:0] _rnXbar_io_in_0_rx_dat_bits_dataID;
  logic [31:0] _rnXbar_io_in_0_rx_dat_bits_be;
  logic [255:0] _rnXbar_io_in_0_rx_dat_bits_data;
  logic [31:0] _rnXbar_io_in_0_rx_dat_bits_dataCheck;
  logic _rnXbar_io_in_0_rx_snp_valid;
  logic [11:0] _rnXbar_io_in_0_rx_snp_bits_txnID;
  logic [10:0] _rnXbar_io_in_0_rx_snp_bits_fwdNID;
  logic [11:0] _rnXbar_io_in_0_rx_snp_bits_fwdTxnID;
  logic [4:0] _rnXbar_io_in_0_rx_snp_bits_opcode;
  logic [44:0] _rnXbar_io_in_0_rx_snp_bits_addr;
  logic _rnXbar_io_in_0_rx_snp_bits_doNotGoToSD;
  logic _rnXbar_io_in_0_rx_snp_bits_retToSrc;
  logic _rnXbar_io_out_0_tx_req_valid;
  logic [10:0] _rnXbar_io_out_0_tx_req_bits_tgtID;
  logic [10:0] _rnXbar_io_out_0_tx_req_bits_srcID;
  logic [11:0] _rnXbar_io_out_0_tx_req_bits_txnID;
  logic [6:0] _rnXbar_io_out_0_tx_req_bits_opcode;
  logic [2:0] _rnXbar_io_out_0_tx_req_bits_size;
  logic [47:0] _rnXbar_io_out_0_tx_req_bits_addr;
  logic _rnXbar_io_out_0_tx_req_bits_allowRetry;
  logic [1:0] _rnXbar_io_out_0_tx_req_bits_order;
  logic [3:0] _rnXbar_io_out_0_tx_req_bits_pCrdType;
  logic _rnXbar_io_out_0_tx_req_bits_memAttr_allocate;
  logic _rnXbar_io_out_0_tx_req_bits_memAttr_cacheable;
  logic _rnXbar_io_out_0_tx_req_bits_memAttr_device;
  logic _rnXbar_io_out_0_tx_req_bits_memAttr_ewa;
  logic _rnXbar_io_out_0_tx_req_bits_snpAttr;
  logic _rnXbar_io_out_0_tx_req_bits_expCompAck;
  logic _rnXbar_io_out_0_tx_rsp_valid;
  logic [10:0] _rnXbar_io_out_0_tx_rsp_bits_srcID;
  logic [11:0] _rnXbar_io_out_0_tx_rsp_bits_txnID;
  logic [4:0] _rnXbar_io_out_0_tx_rsp_bits_opcode;
  logic [11:0] _rnXbar_io_out_0_tx_rsp_bits_dbID;
  logic _rnXbar_io_out_0_tx_dat_valid;
  logic [10:0] _rnXbar_io_out_0_tx_dat_bits_srcID;
  logic [11:0] _rnXbar_io_out_0_tx_dat_bits_txnID;
  logic [3:0] _rnXbar_io_out_0_tx_dat_bits_opcode;
  logic [2:0] _rnXbar_io_out_0_tx_dat_bits_resp;
  logic [1:0] _rnXbar_io_out_0_tx_dat_bits_dataID;
  logic [255:0] _rnXbar_io_out_0_tx_dat_bits_data;
  logic _rnXbar_io_out_0_rx_rsp_ready;
  logic _rnXbar_io_out_0_rx_dat_ready;
  logic _rnXbar_io_out_0_rx_snp_ready;
  logic _rnXbar_io_out_1_tx_req_valid;
  logic [10:0] _rnXbar_io_out_1_tx_req_bits_tgtID;
  logic [10:0] _rnXbar_io_out_1_tx_req_bits_srcID;
  logic [11:0] _rnXbar_io_out_1_tx_req_bits_txnID;
  logic [6:0] _rnXbar_io_out_1_tx_req_bits_opcode;
  logic [2:0] _rnXbar_io_out_1_tx_req_bits_size;
  logic [47:0] _rnXbar_io_out_1_tx_req_bits_addr;
  logic _rnXbar_io_out_1_tx_req_bits_allowRetry;
  logic [1:0] _rnXbar_io_out_1_tx_req_bits_order;
  logic [3:0] _rnXbar_io_out_1_tx_req_bits_pCrdType;
  logic _rnXbar_io_out_1_tx_req_bits_memAttr_allocate;
  logic _rnXbar_io_out_1_tx_req_bits_memAttr_cacheable;
  logic _rnXbar_io_out_1_tx_req_bits_memAttr_device;
  logic _rnXbar_io_out_1_tx_req_bits_memAttr_ewa;
  logic _rnXbar_io_out_1_tx_req_bits_snpAttr;
  logic _rnXbar_io_out_1_tx_req_bits_expCompAck;
  logic _rnXbar_io_out_1_tx_rsp_valid;
  logic [10:0] _rnXbar_io_out_1_tx_rsp_bits_srcID;
  logic [11:0] _rnXbar_io_out_1_tx_rsp_bits_txnID;
  logic [4:0] _rnXbar_io_out_1_tx_rsp_bits_opcode;
  logic [11:0] _rnXbar_io_out_1_tx_rsp_bits_dbID;
  logic _rnXbar_io_out_1_tx_dat_valid;
  logic [10:0] _rnXbar_io_out_1_tx_dat_bits_srcID;
  logic [11:0] _rnXbar_io_out_1_tx_dat_bits_txnID;
  logic [3:0] _rnXbar_io_out_1_tx_dat_bits_opcode;
  logic [2:0] _rnXbar_io_out_1_tx_dat_bits_resp;
  logic [1:0] _rnXbar_io_out_1_tx_dat_bits_dataID;
  logic [255:0] _rnXbar_io_out_1_tx_dat_bits_data;
  logic _rnXbar_io_out_1_rx_rsp_ready;
  logic _rnXbar_io_out_1_rx_dat_ready;
  logic _rnXbar_io_out_1_rx_snp_ready;
  logic _rnXbar_io_out_2_tx_req_valid;
  logic [10:0] _rnXbar_io_out_2_tx_req_bits_tgtID;
  logic [10:0] _rnXbar_io_out_2_tx_req_bits_srcID;
  logic [11:0] _rnXbar_io_out_2_tx_req_bits_txnID;
  logic [6:0] _rnXbar_io_out_2_tx_req_bits_opcode;
  logic [2:0] _rnXbar_io_out_2_tx_req_bits_size;
  logic [47:0] _rnXbar_io_out_2_tx_req_bits_addr;
  logic _rnXbar_io_out_2_tx_req_bits_allowRetry;
  logic [1:0] _rnXbar_io_out_2_tx_req_bits_order;
  logic [3:0] _rnXbar_io_out_2_tx_req_bits_pCrdType;
  logic _rnXbar_io_out_2_tx_req_bits_memAttr_allocate;
  logic _rnXbar_io_out_2_tx_req_bits_memAttr_cacheable;
  logic _rnXbar_io_out_2_tx_req_bits_memAttr_device;
  logic _rnXbar_io_out_2_tx_req_bits_memAttr_ewa;
  logic _rnXbar_io_out_2_tx_req_bits_snpAttr;
  logic _rnXbar_io_out_2_tx_req_bits_expCompAck;
  logic _rnXbar_io_out_2_tx_rsp_valid;
  logic [10:0] _rnXbar_io_out_2_tx_rsp_bits_srcID;
  logic [11:0] _rnXbar_io_out_2_tx_rsp_bits_txnID;
  logic [4:0] _rnXbar_io_out_2_tx_rsp_bits_opcode;
  logic [11:0] _rnXbar_io_out_2_tx_rsp_bits_dbID;
  logic _rnXbar_io_out_2_tx_dat_valid;
  logic [10:0] _rnXbar_io_out_2_tx_dat_bits_srcID;
  logic [11:0] _rnXbar_io_out_2_tx_dat_bits_txnID;
  logic [3:0] _rnXbar_io_out_2_tx_dat_bits_opcode;
  logic [2:0] _rnXbar_io_out_2_tx_dat_bits_resp;
  logic [1:0] _rnXbar_io_out_2_tx_dat_bits_dataID;
  logic [255:0] _rnXbar_io_out_2_tx_dat_bits_data;
  logic _rnXbar_io_out_2_rx_rsp_ready;
  logic _rnXbar_io_out_2_rx_dat_ready;
  logic _rnXbar_io_out_2_rx_snp_ready;
  logic _rnXbar_io_out_3_tx_req_valid;
  logic [10:0] _rnXbar_io_out_3_tx_req_bits_tgtID;
  logic [10:0] _rnXbar_io_out_3_tx_req_bits_srcID;
  logic [11:0] _rnXbar_io_out_3_tx_req_bits_txnID;
  logic [6:0] _rnXbar_io_out_3_tx_req_bits_opcode;
  logic [2:0] _rnXbar_io_out_3_tx_req_bits_size;
  logic [47:0] _rnXbar_io_out_3_tx_req_bits_addr;
  logic _rnXbar_io_out_3_tx_req_bits_allowRetry;
  logic [1:0] _rnXbar_io_out_3_tx_req_bits_order;
  logic [3:0] _rnXbar_io_out_3_tx_req_bits_pCrdType;
  logic _rnXbar_io_out_3_tx_req_bits_memAttr_allocate;
  logic _rnXbar_io_out_3_tx_req_bits_memAttr_cacheable;
  logic _rnXbar_io_out_3_tx_req_bits_memAttr_device;
  logic _rnXbar_io_out_3_tx_req_bits_memAttr_ewa;
  logic _rnXbar_io_out_3_tx_req_bits_snpAttr;
  logic _rnXbar_io_out_3_tx_req_bits_expCompAck;
  logic _rnXbar_io_out_3_tx_rsp_valid;
  logic [10:0] _rnXbar_io_out_3_tx_rsp_bits_srcID;
  logic [11:0] _rnXbar_io_out_3_tx_rsp_bits_txnID;
  logic [4:0] _rnXbar_io_out_3_tx_rsp_bits_opcode;
  logic [11:0] _rnXbar_io_out_3_tx_rsp_bits_dbID;
  logic _rnXbar_io_out_3_tx_dat_valid;
  logic [10:0] _rnXbar_io_out_3_tx_dat_bits_srcID;
  logic [11:0] _rnXbar_io_out_3_tx_dat_bits_txnID;
  logic [3:0] _rnXbar_io_out_3_tx_dat_bits_opcode;
  logic [2:0] _rnXbar_io_out_3_tx_dat_bits_resp;
  logic [1:0] _rnXbar_io_out_3_tx_dat_bits_dataID;
  logic [255:0] _rnXbar_io_out_3_tx_dat_bits_data;
  logic _rnXbar_io_out_3_rx_rsp_ready;
  logic _rnXbar_io_out_3_rx_dat_ready;
  logic _rnXbar_io_out_3_rx_snp_ready;
  logic _mmioMerger_io_in_cache_tx_req_ready;
  logic _mmioMerger_io_in_cache_tx_dat_ready;
  logic _mmioMerger_io_in_cache_rx_rsp_valid;
  logic [10:0] _mmioMerger_io_in_cache_rx_rsp_bits_srcID;
  logic [11:0] _mmioMerger_io_in_cache_rx_rsp_bits_txnID;
  logic [4:0] _mmioMerger_io_in_cache_rx_rsp_bits_opcode;
  logic [11:0] _mmioMerger_io_in_cache_rx_rsp_bits_dbID;
  logic _mmioMerger_io_in_cache_rx_dat_valid;
  logic [10:0] _mmioMerger_io_in_cache_rx_dat_bits_srcID;
  logic [11:0] _mmioMerger_io_in_cache_rx_dat_bits_txnID;
  logic [3:0] _mmioMerger_io_in_cache_rx_dat_bits_opcode;
  logic [2:0] _mmioMerger_io_in_cache_rx_dat_bits_resp;
  logic [1:0] _mmioMerger_io_in_cache_rx_dat_bits_dataID;
  logic [255:0] _mmioMerger_io_in_cache_rx_dat_bits_data;
  logic _mmioMerger_io_in_uncache_tx_req_ready;
  logic _mmioMerger_io_in_uncache_tx_dat_ready;
  logic _mmioMerger_io_in_uncache_rx_rsp_valid;
  logic [3:0] _mmioMerger_io_in_uncache_rx_rsp_bits_qos;
  logic [10:0] _mmioMerger_io_in_uncache_rx_rsp_bits_tgtID;
  logic [11:0] _mmioMerger_io_in_uncache_rx_rsp_bits_txnID;
  logic [4:0] _mmioMerger_io_in_uncache_rx_rsp_bits_opcode;
  logic [1:0] _mmioMerger_io_in_uncache_rx_rsp_bits_respErr;
  logic [2:0] _mmioMerger_io_in_uncache_rx_rsp_bits_resp;
  logic [2:0] _mmioMerger_io_in_uncache_rx_rsp_bits_fwdState;
  logic [2:0] _mmioMerger_io_in_uncache_rx_rsp_bits_cBusy;
  logic [11:0] _mmioMerger_io_in_uncache_rx_rsp_bits_dbID;
  logic [3:0] _mmioMerger_io_in_uncache_rx_rsp_bits_pCrdType;
  logic [1:0] _mmioMerger_io_in_uncache_rx_rsp_bits_tagOp;
  logic _mmioMerger_io_in_uncache_rx_rsp_bits_traceTag;
  logic _mmioMerger_io_in_uncache_rx_dat_valid;
  logic [3:0] _mmioMerger_io_in_uncache_rx_dat_bits_qos;
  logic [10:0] _mmioMerger_io_in_uncache_rx_dat_bits_tgtID;
  logic [11:0] _mmioMerger_io_in_uncache_rx_dat_bits_txnID;
  logic [10:0] _mmioMerger_io_in_uncache_rx_dat_bits_homeNID;
  logic [3:0] _mmioMerger_io_in_uncache_rx_dat_bits_opcode;
  logic [1:0] _mmioMerger_io_in_uncache_rx_dat_bits_respErr;
  logic [2:0] _mmioMerger_io_in_uncache_rx_dat_bits_resp;
  logic [3:0] _mmioMerger_io_in_uncache_rx_dat_bits_dataSource;
  logic [2:0] _mmioMerger_io_in_uncache_rx_dat_bits_cBusy;
  logic [11:0] _mmioMerger_io_in_uncache_rx_dat_bits_dbID;
  logic [1:0] _mmioMerger_io_in_uncache_rx_dat_bits_ccID;
  logic [1:0] _mmioMerger_io_in_uncache_rx_dat_bits_dataID;
  logic [1:0] _mmioMerger_io_in_uncache_rx_dat_bits_tagOp;
  logic [7:0] _mmioMerger_io_in_uncache_rx_dat_bits_tag;
  logic [1:0] _mmioMerger_io_in_uncache_rx_dat_bits_tu;
  logic _mmioMerger_io_in_uncache_rx_dat_bits_traceTag;
  logic [3:0] _mmioMerger_io_in_uncache_rx_dat_bits_rsvdc;
  logic [31:0] _mmioMerger_io_in_uncache_rx_dat_bits_be;
  logic [255:0] _mmioMerger_io_in_uncache_rx_dat_bits_data;
  logic [31:0] _mmioMerger_io_in_uncache_rx_dat_bits_dataCheck;
  logic [3:0] _mmioMerger_io_in_uncache_rx_dat_bits_poison;
  logic _mmioMerger_io_out_tx_req_valid;
  logic [3:0] _mmioMerger_io_out_tx_req_bits_qos;
  logic [10:0] _mmioMerger_io_out_tx_req_bits_tgtID;
  logic [10:0] _mmioMerger_io_out_tx_req_bits_srcID;
  logic [11:0] _mmioMerger_io_out_tx_req_bits_txnID;
  logic [10:0] _mmioMerger_io_out_tx_req_bits_returnNID;
  logic _mmioMerger_io_out_tx_req_bits_stashNIDValid;
  logic [11:0] _mmioMerger_io_out_tx_req_bits_returnTxnID;
  logic [6:0] _mmioMerger_io_out_tx_req_bits_opcode;
  logic [2:0] _mmioMerger_io_out_tx_req_bits_size;
  logic [47:0] _mmioMerger_io_out_tx_req_bits_addr;
  logic _mmioMerger_io_out_tx_req_bits_ns;
  logic _mmioMerger_io_out_tx_req_bits_likelyshared;
  logic _mmioMerger_io_out_tx_req_bits_allowRetry;
  logic [1:0] _mmioMerger_io_out_tx_req_bits_order;
  logic [3:0] _mmioMerger_io_out_tx_req_bits_pCrdType;
  logic _mmioMerger_io_out_tx_req_bits_memAttr_allocate;
  logic _mmioMerger_io_out_tx_req_bits_memAttr_cacheable;
  logic _mmioMerger_io_out_tx_req_bits_memAttr_device;
  logic _mmioMerger_io_out_tx_req_bits_memAttr_ewa;
  logic _mmioMerger_io_out_tx_req_bits_snpAttr;
  logic [7:0] _mmioMerger_io_out_tx_req_bits_lpIDWithPadding;
  logic _mmioMerger_io_out_tx_req_bits_snoopMe;
  logic _mmioMerger_io_out_tx_req_bits_expCompAck;
  logic [1:0] _mmioMerger_io_out_tx_req_bits_tagOp;
  logic _mmioMerger_io_out_tx_req_bits_traceTag;
  logic _mmioMerger_io_out_tx_req_bits_mpam_perfMonGroup;
  logic [8:0] _mmioMerger_io_out_tx_req_bits_mpam_partID;
  logic _mmioMerger_io_out_tx_req_bits_mpam_mpamNS;
  logic [3:0] _mmioMerger_io_out_tx_req_bits_rsvdc;
  logic _mmioMerger_io_out_tx_dat_valid;
  logic [3:0] _mmioMerger_io_out_tx_dat_bits_qos;
  logic [10:0] _mmioMerger_io_out_tx_dat_bits_tgtID;
  logic [10:0] _mmioMerger_io_out_tx_dat_bits_srcID;
  logic [11:0] _mmioMerger_io_out_tx_dat_bits_txnID;
  logic [10:0] _mmioMerger_io_out_tx_dat_bits_homeNID;
  logic [3:0] _mmioMerger_io_out_tx_dat_bits_opcode;
  logic [1:0] _mmioMerger_io_out_tx_dat_bits_respErr;
  logic [2:0] _mmioMerger_io_out_tx_dat_bits_resp;
  logic [3:0] _mmioMerger_io_out_tx_dat_bits_dataSource;
  logic [2:0] _mmioMerger_io_out_tx_dat_bits_cBusy;
  logic [11:0] _mmioMerger_io_out_tx_dat_bits_dbID;
  logic [1:0] _mmioMerger_io_out_tx_dat_bits_ccID;
  logic [1:0] _mmioMerger_io_out_tx_dat_bits_dataID;
  logic [1:0] _mmioMerger_io_out_tx_dat_bits_tagOp;
  logic [7:0] _mmioMerger_io_out_tx_dat_bits_tag;
  logic [1:0] _mmioMerger_io_out_tx_dat_bits_tu;
  logic _mmioMerger_io_out_tx_dat_bits_traceTag;
  logic [3:0] _mmioMerger_io_out_tx_dat_bits_rsvdc;
  logic [31:0] _mmioMerger_io_out_tx_dat_bits_be;
  logic [255:0] _mmioMerger_io_out_tx_dat_bits_data;
  logic [31:0] _mmioMerger_io_out_tx_dat_bits_dataCheck;
  logic [3:0] _mmioMerger_io_out_tx_dat_bits_poison;
  logic _mmioMerger_io_out_rx_rsp_ready;
  logic _mmioMerger_io_out_rx_dat_ready;
  logic _mmioDiverger_io_in_0_tx_req_ready;
  logic _mmioDiverger_io_in_0_tx_rsp_ready;
  logic _mmioDiverger_io_in_0_tx_dat_ready;
  logic _mmioDiverger_io_in_0_rx_rsp_valid;
  logic [3:0] _mmioDiverger_io_in_0_rx_rsp_bits_qos;
  logic [11:0] _mmioDiverger_io_in_0_rx_rsp_bits_txnID;
  logic [4:0] _mmioDiverger_io_in_0_rx_rsp_bits_opcode;
  logic [1:0] _mmioDiverger_io_in_0_rx_rsp_bits_respErr;
  logic [2:0] _mmioDiverger_io_in_0_rx_rsp_bits_resp;
  logic [2:0] _mmioDiverger_io_in_0_rx_rsp_bits_fwdState;
  logic [2:0] _mmioDiverger_io_in_0_rx_rsp_bits_cBusy;
  logic [11:0] _mmioDiverger_io_in_0_rx_rsp_bits_dbID;
  logic [3:0] _mmioDiverger_io_in_0_rx_rsp_bits_pCrdType;
  logic [1:0] _mmioDiverger_io_in_0_rx_rsp_bits_tagOp;
  logic _mmioDiverger_io_in_0_rx_rsp_bits_traceTag;
  logic _mmioDiverger_io_in_0_rx_dat_valid;
  logic [3:0] _mmioDiverger_io_in_0_rx_dat_bits_qos;
  logic [11:0] _mmioDiverger_io_in_0_rx_dat_bits_txnID;
  logic [10:0] _mmioDiverger_io_in_0_rx_dat_bits_homeNID;
  logic [3:0] _mmioDiverger_io_in_0_rx_dat_bits_opcode;
  logic [1:0] _mmioDiverger_io_in_0_rx_dat_bits_respErr;
  logic [2:0] _mmioDiverger_io_in_0_rx_dat_bits_resp;
  logic [3:0] _mmioDiverger_io_in_0_rx_dat_bits_dataSource;
  logic [2:0] _mmioDiverger_io_in_0_rx_dat_bits_cBusy;
  logic [11:0] _mmioDiverger_io_in_0_rx_dat_bits_dbID;
  logic [1:0] _mmioDiverger_io_in_0_rx_dat_bits_ccID;
  logic [1:0] _mmioDiverger_io_in_0_rx_dat_bits_dataID;
  logic [1:0] _mmioDiverger_io_in_0_rx_dat_bits_tagOp;
  logic [7:0] _mmioDiverger_io_in_0_rx_dat_bits_tag;
  logic [1:0] _mmioDiverger_io_in_0_rx_dat_bits_tu;
  logic _mmioDiverger_io_in_0_rx_dat_bits_traceTag;
  logic [3:0] _mmioDiverger_io_in_0_rx_dat_bits_rsvdc;
  logic [31:0] _mmioDiverger_io_in_0_rx_dat_bits_be;
  logic [255:0] _mmioDiverger_io_in_0_rx_dat_bits_data;
  logic [31:0] _mmioDiverger_io_in_0_rx_dat_bits_dataCheck;
  logic [3:0] _mmioDiverger_io_in_0_rx_dat_bits_poison;
  logic _mmioDiverger_io_in_0_rx_snp_valid;
  logic [11:0] _mmioDiverger_io_in_0_rx_snp_bits_txnID;
  logic [10:0] _mmioDiverger_io_in_0_rx_snp_bits_fwdNID;
  logic [11:0] _mmioDiverger_io_in_0_rx_snp_bits_fwdTxnID;
  logic [4:0] _mmioDiverger_io_in_0_rx_snp_bits_opcode;
  logic [44:0] _mmioDiverger_io_in_0_rx_snp_bits_addr;
  logic _mmioDiverger_io_in_0_rx_snp_bits_doNotGoToSD;
  logic _mmioDiverger_io_in_0_rx_snp_bits_retToSrc;
  logic _mmioDiverger_io_out_cache_0_tx_req_valid;
  logic [3:0] _mmioDiverger_io_out_cache_0_tx_req_bits_qos;
  logic [10:0] _mmioDiverger_io_out_cache_0_tx_req_bits_tgtID;
  logic [10:0] _mmioDiverger_io_out_cache_0_tx_req_bits_srcID;
  logic [11:0] _mmioDiverger_io_out_cache_0_tx_req_bits_txnID;
  logic [10:0] _mmioDiverger_io_out_cache_0_tx_req_bits_returnNID;
  logic _mmioDiverger_io_out_cache_0_tx_req_bits_stashNIDValid;
  logic [11:0] _mmioDiverger_io_out_cache_0_tx_req_bits_returnTxnID;
  logic [6:0] _mmioDiverger_io_out_cache_0_tx_req_bits_opcode;
  logic [2:0] _mmioDiverger_io_out_cache_0_tx_req_bits_size;
  logic [47:0] _mmioDiverger_io_out_cache_0_tx_req_bits_addr;
  logic _mmioDiverger_io_out_cache_0_tx_req_bits_ns;
  logic _mmioDiverger_io_out_cache_0_tx_req_bits_likelyshared;
  logic _mmioDiverger_io_out_cache_0_tx_req_bits_allowRetry;
  logic [1:0] _mmioDiverger_io_out_cache_0_tx_req_bits_order;
  logic [3:0] _mmioDiverger_io_out_cache_0_tx_req_bits_pCrdType;
  logic _mmioDiverger_io_out_cache_0_tx_req_bits_memAttr_allocate;
  logic _mmioDiverger_io_out_cache_0_tx_req_bits_memAttr_cacheable;
  logic _mmioDiverger_io_out_cache_0_tx_req_bits_memAttr_device;
  logic _mmioDiverger_io_out_cache_0_tx_req_bits_memAttr_ewa;
  logic _mmioDiverger_io_out_cache_0_tx_req_bits_snpAttr;
  logic [7:0] _mmioDiverger_io_out_cache_0_tx_req_bits_lpIDWithPadding;
  logic _mmioDiverger_io_out_cache_0_tx_req_bits_snoopMe;
  logic _mmioDiverger_io_out_cache_0_tx_req_bits_expCompAck;
  logic [1:0] _mmioDiverger_io_out_cache_0_tx_req_bits_tagOp;
  logic _mmioDiverger_io_out_cache_0_tx_req_bits_traceTag;
  logic _mmioDiverger_io_out_cache_0_tx_req_bits_mpam_perfMonGroup;
  logic [8:0] _mmioDiverger_io_out_cache_0_tx_req_bits_mpam_partID;
  logic _mmioDiverger_io_out_cache_0_tx_req_bits_mpam_mpamNS;
  logic [3:0] _mmioDiverger_io_out_cache_0_tx_req_bits_rsvdc;
  logic _mmioDiverger_io_out_cache_0_tx_rsp_valid;
  logic [10:0] _mmioDiverger_io_out_cache_0_tx_rsp_bits_srcID;
  logic [11:0] _mmioDiverger_io_out_cache_0_tx_rsp_bits_txnID;
  logic [4:0] _mmioDiverger_io_out_cache_0_tx_rsp_bits_opcode;
  logic [11:0] _mmioDiverger_io_out_cache_0_tx_rsp_bits_dbID;
  logic _mmioDiverger_io_out_cache_0_tx_dat_valid;
  logic [3:0] _mmioDiverger_io_out_cache_0_tx_dat_bits_qos;
  logic [10:0] _mmioDiverger_io_out_cache_0_tx_dat_bits_tgtID;
  logic [10:0] _mmioDiverger_io_out_cache_0_tx_dat_bits_srcID;
  logic [11:0] _mmioDiverger_io_out_cache_0_tx_dat_bits_txnID;
  logic [10:0] _mmioDiverger_io_out_cache_0_tx_dat_bits_homeNID;
  logic [3:0] _mmioDiverger_io_out_cache_0_tx_dat_bits_opcode;
  logic [1:0] _mmioDiverger_io_out_cache_0_tx_dat_bits_respErr;
  logic [2:0] _mmioDiverger_io_out_cache_0_tx_dat_bits_resp;
  logic [3:0] _mmioDiverger_io_out_cache_0_tx_dat_bits_dataSource;
  logic [2:0] _mmioDiverger_io_out_cache_0_tx_dat_bits_cBusy;
  logic [11:0] _mmioDiverger_io_out_cache_0_tx_dat_bits_dbID;
  logic [1:0] _mmioDiverger_io_out_cache_0_tx_dat_bits_ccID;
  logic [1:0] _mmioDiverger_io_out_cache_0_tx_dat_bits_dataID;
  logic [1:0] _mmioDiverger_io_out_cache_0_tx_dat_bits_tagOp;
  logic [7:0] _mmioDiverger_io_out_cache_0_tx_dat_bits_tag;
  logic [1:0] _mmioDiverger_io_out_cache_0_tx_dat_bits_tu;
  logic _mmioDiverger_io_out_cache_0_tx_dat_bits_traceTag;
  logic [3:0] _mmioDiverger_io_out_cache_0_tx_dat_bits_rsvdc;
  logic [31:0] _mmioDiverger_io_out_cache_0_tx_dat_bits_be;
  logic [255:0] _mmioDiverger_io_out_cache_0_tx_dat_bits_data;
  logic [31:0] _mmioDiverger_io_out_cache_0_tx_dat_bits_dataCheck;
  logic [3:0] _mmioDiverger_io_out_cache_0_tx_dat_bits_poison;
  logic _mmioDiverger_io_out_cache_0_rx_rsp_ready;
  logic _mmioDiverger_io_out_cache_0_rx_dat_ready;
  logic _mmioDiverger_io_out_cache_0_rx_snp_ready;
  logic _mmioDiverger_io_out_uncache_tx_req_valid;
  logic [3:0] _mmioDiverger_io_out_uncache_tx_req_bits_qos;
  logic [10:0] _mmioDiverger_io_out_uncache_tx_req_bits_tgtID;
  logic [10:0] _mmioDiverger_io_out_uncache_tx_req_bits_srcID;
  logic [11:0] _mmioDiverger_io_out_uncache_tx_req_bits_txnID;
  logic [10:0] _mmioDiverger_io_out_uncache_tx_req_bits_returnNID;
  logic _mmioDiverger_io_out_uncache_tx_req_bits_stashNIDValid;
  logic [11:0] _mmioDiverger_io_out_uncache_tx_req_bits_returnTxnID;
  logic [6:0] _mmioDiverger_io_out_uncache_tx_req_bits_opcode;
  logic [2:0] _mmioDiverger_io_out_uncache_tx_req_bits_size;
  logic [47:0] _mmioDiverger_io_out_uncache_tx_req_bits_addr;
  logic _mmioDiverger_io_out_uncache_tx_req_bits_ns;
  logic _mmioDiverger_io_out_uncache_tx_req_bits_likelyshared;
  logic _mmioDiverger_io_out_uncache_tx_req_bits_allowRetry;
  logic [3:0] _mmioDiverger_io_out_uncache_tx_req_bits_pCrdType;
  logic _mmioDiverger_io_out_uncache_tx_req_bits_memAttr_allocate;
  logic _mmioDiverger_io_out_uncache_tx_req_bits_memAttr_cacheable;
  logic _mmioDiverger_io_out_uncache_tx_req_bits_memAttr_device;
  logic _mmioDiverger_io_out_uncache_tx_req_bits_memAttr_ewa;
  logic _mmioDiverger_io_out_uncache_tx_req_bits_snpAttr;
  logic [7:0] _mmioDiverger_io_out_uncache_tx_req_bits_lpIDWithPadding;
  logic _mmioDiverger_io_out_uncache_tx_req_bits_snoopMe;
  logic _mmioDiverger_io_out_uncache_tx_req_bits_expCompAck;
  logic [1:0] _mmioDiverger_io_out_uncache_tx_req_bits_tagOp;
  logic _mmioDiverger_io_out_uncache_tx_req_bits_traceTag;
  logic _mmioDiverger_io_out_uncache_tx_req_bits_mpam_perfMonGroup;
  logic [8:0] _mmioDiverger_io_out_uncache_tx_req_bits_mpam_partID;
  logic _mmioDiverger_io_out_uncache_tx_req_bits_mpam_mpamNS;
  logic [3:0] _mmioDiverger_io_out_uncache_tx_req_bits_rsvdc;
  logic _mmioDiverger_io_out_uncache_tx_dat_valid;
  logic [3:0] _mmioDiverger_io_out_uncache_tx_dat_bits_qos;
  logic [10:0] _mmioDiverger_io_out_uncache_tx_dat_bits_tgtID;
  logic [10:0] _mmioDiverger_io_out_uncache_tx_dat_bits_srcID;
  logic [11:0] _mmioDiverger_io_out_uncache_tx_dat_bits_txnID;
  logic [10:0] _mmioDiverger_io_out_uncache_tx_dat_bits_homeNID;
  logic [3:0] _mmioDiverger_io_out_uncache_tx_dat_bits_opcode;
  logic [1:0] _mmioDiverger_io_out_uncache_tx_dat_bits_respErr;
  logic [2:0] _mmioDiverger_io_out_uncache_tx_dat_bits_resp;
  logic [3:0] _mmioDiverger_io_out_uncache_tx_dat_bits_dataSource;
  logic [2:0] _mmioDiverger_io_out_uncache_tx_dat_bits_cBusy;
  logic [11:0] _mmioDiverger_io_out_uncache_tx_dat_bits_dbID;
  logic [1:0] _mmioDiverger_io_out_uncache_tx_dat_bits_ccID;
  logic [1:0] _mmioDiverger_io_out_uncache_tx_dat_bits_dataID;
  logic [1:0] _mmioDiverger_io_out_uncache_tx_dat_bits_tagOp;
  logic [7:0] _mmioDiverger_io_out_uncache_tx_dat_bits_tag;
  logic [1:0] _mmioDiverger_io_out_uncache_tx_dat_bits_tu;
  logic _mmioDiverger_io_out_uncache_tx_dat_bits_traceTag;
  logic [3:0] _mmioDiverger_io_out_uncache_tx_dat_bits_rsvdc;
  logic [31:0] _mmioDiverger_io_out_uncache_tx_dat_bits_be;
  logic [255:0] _mmioDiverger_io_out_uncache_tx_dat_bits_data;
  logic [31:0] _mmioDiverger_io_out_uncache_tx_dat_bits_dataCheck;
  logic [3:0] _mmioDiverger_io_out_uncache_tx_dat_bits_poison;
  logic _mmioDiverger_io_out_uncache_rx_rsp_ready;
  logic _mmioDiverger_io_out_uncache_rx_dat_ready;
  logic _probe;
