MODULE = MaxPeriodFibonacciLFSR_3
RTL_DIR = ../../../rtl
GOLDEN_RTL = ../../../golden/chisel-rtl
RTL_SRCS = $(RTL_DIR)/uncore/MaxPeriodFibonacciLFSR_3.sv
WRAPPER_SRCS =
GOLDEN_SRCS = $(GOLDEN_RTL)/MaxPeriodFibonacciLFSR_3.sv
TB_SRCS = variants_xs.sv tb.sv
FM_VARIANTS = MaxPeriodFibonacciLFSR_3
FM_REF_DEPS_MaxPeriodFibonacciLFSR_3 =
include ../../../scripts/ut_common.mk
VCS += +define+SYNTHESIS
