#!/usr/bin/env python3
"""gen_frontendtrigger.py — 机械派生 FrontendTrigger 可读核三件套 + UT tb。

来源: golden/chisel-rtl/FrontendTrigger.sv (firtool 展平单模块, 0 子模块 0 mem)。
产物:
  rtl/frontend/FrontendTrigger.sv          xs_FrontendTrigger_core(可读核)
  rtl/frontend/FrontendTrigger_wrapper.sv  FrontendTrigger(FM impl 顶层, 例化 u_core)
  rtl/frontend/FrontendTrigger_xs.sv       FrontendTrigger_xs(UT 变体)
  verif/ut/FrontendTrigger/tb.sv           golden vs _xs 双例化逐拍全输出比对

可读核纪律(ExceptionGen 定式): 逐字保留 golden 寄存器集(名/使能/异步 reset)与
next-state 表达式; 仅 _GEN_/_T_ 中间线重命名(RENAME 映射见 core 头注释)。
唯一收窄: tdataVec_j_tdata2 由 64 位收窄至 golden 读域 [49:0](fm-strict-unread
方法学) —— golden 比较只用 tdata2[49:5]/[4:0], [63:50] 写入后无读者(cone-dead),
留在 golden 侧作 dead_ref 申报(verif/signoff/dead_ref/FrontendTrigger.json)。
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GOLDEN = os.path.join(ROOT, "golden/chisel-rtl/FrontendTrigger.sv")
PW = 16
NT = 4

BANNER = "// Generated by scripts/gen_frontendtrigger.py — do not hand-edit."

FIELDS = [  # (field, width-decl, reset)
    ("matchType", "[1:0] ", "2'h0"),
    ("select", "      ", "1'h0"),
    ("timing", "      ", "1'h0"),
    ("action", "[3:0] ", "4'h0"),
    ("chain", "      ", "1'h0"),
    ("tdata2", "[49:0]", "50'h0"),
]


def parse_ports():
    txt = open(GOLDEN).read()
    m = re.search(r"module FrontendTrigger\((.*?)\n\);", txt, re.S)
    ports = []
    for line in m.group(1).split("\n"):
        line = line.strip().rstrip(",")
        mm = re.match(r"(input|output)\s*(\[\d+:\d+\])?\s*(\w+)$", line)
        if mm:
            ports.append((mm.group(1), mm.group(2) or "", mm.group(3)))
    assert ports and ports[0][2] == "clock" and ports[1][2] == "reset"
    return ports


def port_decls(ports):
    out = []
    for d, w, n in ports:
        ww = (" %-7s" % w) if w else "        "
        out.append("  %-6s%s %s" % (d, ww, n))
    return ",\n".join(out)


def gen_core(ports):
    L = []
    L.append(BANNER)
    L.append("""//
// xs_FrontendTrigger_core — readable faithful (bug-for-bug) core for golden
// FrontendTrigger (前端硬件断点/触发器: 4 个 tdata 触发器 × 16 取指 lane 的
// PC 匹配 + 链式触发 + action 译码)。
//
// 结构(golden firtool 单模块, 0 子模块 0 mem, 异步 reset):
//   REG:  tdataVec_0..3_{matchType,select,timing,action,chain,tdata2} —— tUpdate
//         按 addr 写入(timing 无更新位: 写入即清 0, 否则保持);
//         triggerEnableVec_0..3 逐拍采样 tEnableVec。
//   COMB: hit[j][i] = 触发器 j 在 lane i 的 PC 匹配(matchType: 3=less,
//         2=greater-equal, 0=equal, 1=保留不命中)。50 位比较拆成 高位块
//         pc[49:5](lane 跨 32B 半行时用块号+1)+低 5 位 —— 仅 lane0 的 PC 参与
//         高位比较, 其余 lane 用 bit5 翻转(laneCarry)选块号/块号+1;
//         canFire[i][j] = 链式发射资格(链中段不发射, 链尾需前驱命中+timing 一致);
//         io_triggered_i = 最低可发射触发器 action 译码(0=断点异常须
//         triggerCanRaiseBpExp, 1=进 debug, 否则 F=未触发)。
//
// RENAME 映射(golden → 本核, 其余 golden 具名 wire/reg 逐字保留):
//   _GEN/_GEN_0/_GEN_1/_GEN_2                → tdataWen[j] (tUpdate 命中触发器 j)
//   _triggerHitVec_highPC1_T_1/_3/_5/_7      → pcHigh1(4 份相同加法, 合 1 净)
//   triggerHitVec_highPC{Equal,Greater,Less}[_j]/highPC1* → highEq/highGt/highLt[j] 等
//   triggerHitVec_carry_[j_]i                → laneCarry[i] (与触发器无关, 合 1 净)
//   triggerHitVec_lowPC{Equal,Less}_[j_]i    → g_hit_t[j].g_hit_l[i].lowEq/lowLt
//   _triggerHitVec_overallGreater_i_T_*      → g_hit_t[j].g_hit_l[i].lowGe(保留冗余 equal|>=)
//   _triggerHitVec_ret_15_T*(matchType 译码) → (&matchTypeQ[j]) / ==2'h2 / ==2'h0 内联
//   triggerHitVec_<i>_<j>                    → hit[j][i]
//   triggerCanFireVec_[i_]j / _hasTriggerFire_T_<i> → canFire[i][j] / hasFire
//   triggerFireOH_enc_<i> + triggerFireAction_<i>   → fireAction(等价优先 mux 折叠)
// 寄存器集逐字保留; 唯一收窄 tdata2: 64b → [49:0](见文件头)。""")
    L.append("module xs_FrontendTrigger_core(")
    L.append(port_decls(ports))
    L.append(");")
    L.append("")
    L.append("  localparam int PW = %d;   // PredictWidth (取指 lane 数)" % PW)
    L.append("  localparam int NT = %d;   // 前端触发器数" % NT)
    L.append("")
    L.append("  // ---------------- 寄存器集(golden 名逐字保留) ----------------")
    for j in range(NT):
        for f, w, _ in FIELDS:
            L.append("  reg  %s tdataVec_%d_%s;" % (w, j, f))
    for j in range(NT):
        L.append("  reg         triggerEnableVec_%d;" % j)
    L.append("""
  // tdataWen[j]: tUpdate 命中触发器 j
  wire [NT-1:0] tdataWen;
  genvar i, j;
  generate
    for (j = 0; j < NT; j = j + 1) begin : g_wen
      assign tdataWen[j] = io_frontendTrigger_tUpdate_valid
                         & (io_frontendTrigger_tUpdate_bits_addr == j);
    end
  endgenerate

  always @(posedge clock or posedge reset) begin
    if (reset) begin""")
    for j in range(NT):
        for f, _, rv in FIELDS:
            L.append("      tdataVec_%d_%s <= %s;" % (j, f, rv))
    for j in range(NT):
        L.append("      triggerEnableVec_%d <= 1'h0;" % j)
    L.append("    end")
    L.append("    else begin")
    for j in range(NT):
        L.append("      if (tdataWen[%d]) begin" % j)
        L.append("        tdataVec_%d_matchType <= io_frontendTrigger_tUpdate_bits_tdata_matchType;" % j)
        L.append("        tdataVec_%d_select <= io_frontendTrigger_tUpdate_bits_tdata_select;" % j)
        L.append("        tdataVec_%d_action <= io_frontendTrigger_tUpdate_bits_tdata_action;" % j)
        L.append("        tdataVec_%d_chain <= io_frontendTrigger_tUpdate_bits_tdata_chain;" % j)
        L.append("        tdataVec_%d_tdata2 <= io_frontendTrigger_tUpdate_bits_tdata_tdata2[49:0];" % j)
        L.append("      end")
        L.append("      // tdata1 更新不带 timing 位: 写入即清 0, 否则保持")
        L.append("      tdataVec_%d_timing <= ~tdataWen[%d] & tdataVec_%d_timing;" % (j, j, j))
    for j in range(NT):
        L.append("      triggerEnableVec_%d <= io_frontendTrigger_tEnableVec_%d;" % (j, j))
    L.append("    end")
    L.append("  end")
    L.append("")
    L.append("  // ---------------- 数组视图(机械 扁平->数组 打包) ----------------")
    L.append("  wire [1:0]  matchTypeQ [0:NT-1];")
    L.append("  wire [3:0]  actionQ    [0:NT-1];")
    L.append("  wire [49:0] tdata2Q    [0:NT-1];")
    for j in range(NT):
        L.append("  assign matchTypeQ[%d] = tdataVec_%d_matchType;" % (j, j))
    for j in range(NT):
        L.append("  assign actionQ[%d] = tdataVec_%d_action;" % (j, j))
    for j in range(NT):
        L.append("  assign tdata2Q[%d] = tdataVec_%d_tdata2;" % (j, j))
    for name, field in (("selectQ", "tdataVec_%d_select"), ("timingQ", "tdataVec_%d_timing"),
                        ("chainQ", "tdataVec_%d_chain"), ("enableQ", "triggerEnableVec_%d")):
        L.append("  wire [NT-1:0] %s = {%s};" % (name, ", ".join(
            field % j for j in range(NT - 1, -1, -1))))
    L.append("  wire [49:0] pcVec [0:PW-1];")
    for i in range(PW):
        L.append("  assign pcVec[%d] = io_pc_%d;" % (i, i))
    L.append("""
  // ---------------- PC 高位块 / lane 进位 ----------------
  wire [44:0] pcHigh  = pcVec[0][49:5];             // 32B 半行块号(仅 lane0 参与)
  wire [44:0] pcHigh1 = 45'(pcVec[0][49:5] + 45'h1); // lane 跨半行进位后的块号
  // laneCarry[i]: lane 相对 lane0 跨入下一半行(bit5 翻转; lane0 恒 0 —— golden
  // 直接省略 lane0 的 carry 路径, 常量折叠一致)
  wire [PW-1:0] laneCarry;
  generate
    for (i = 0; i < PW; i = i + 1) begin : g_carry
      assign laneCarry[i] = pcVec[i][5] != pcVec[0][5];
    end
  endgenerate

  wire [NT-1:0] highEq, highEq1, highGt, highGt1, highLt, highLt1;
  generate
    for (j = 0; j < NT; j = j + 1) begin : g_high
      assign highEq[j]  = pcHigh  == tdata2Q[j][49:5];
      assign highEq1[j] = pcHigh1 == tdata2Q[j][49:5];
      assign highGt[j]  = pcHigh  >  tdata2Q[j][49:5];
      assign highGt1[j] = pcHigh1 >  tdata2Q[j][49:5];
      assign highLt[j]  = pcHigh  <  tdata2Q[j][49:5];
      assign highLt1[j] = pcHigh1 <  tdata2Q[j][49:5];
    end
  endgenerate

  // ---------------- hit[j][i]: 触发器 j 在 lane i 的 PC 匹配 ----------------
  wire [PW-1:0] hit [0:NT-1];
  generate
    for (j = 0; j < NT; j = j + 1) begin : g_hit_t
      for (i = 0; i < PW; i = i + 1) begin : g_hit_l
        wire lowEq = pcVec[i][4:0] == tdata2Q[j][4:0];
        wire lowLt = pcVec[i][4:0] <  tdata2Q[j][4:0];
        wire lowGe = lowEq | (pcVec[i][4:0] >= tdata2Q[j][4:0]);  // golden 冗余保留
        assign hit[j][i] =
          ((&matchTypeQ[j])
             ? ~laneCarry[i] & (highLt[j] | highEq[j] & lowLt)
               | laneCarry[i] & (highLt1[j] | highEq1[j] & lowLt)
             : (matchTypeQ[j] == 2'h2)
                 ? ~laneCarry[i] & (highGt[j] | highEq[j] & lowGe)
                   | laneCarry[i] & (highGt1[j] | highEq1[j] & lowGe)
                 : (matchTypeQ[j] == 2'h0)
                   & (~laneCarry[i] & highEq[j] & lowEq
                      | laneCarry[i] & highEq1[j] & lowEq))
          & enableQ[j] & ~selectQ[j] & ~io_frontendTrigger_debugMode;
      end
    end
  endgenerate

  // ---------------- 链式发射 + action 译码 ----------------
  // trigger2TimingSameVec(golden 名保留): 相邻触发器 timing 一致才可续链
  wire trigger2TimingSameVec_1 = tdataVec_0_timing == tdataVec_1_timing;
  wire trigger2TimingSameVec_2 = tdataVec_1_timing == tdataVec_2_timing;
  wire trigger2TimingSameVec_3 = tdataVec_2_timing == tdataVec_3_timing;
  wire [NT-1:0] timingSame = {trigger2TimingSameVec_3, trigger2TimingSameVec_2,
                              trigger2TimingSameVec_1, 1'b1};

  wire [NT-1:0] canFire [0:PW-1];
  wire [3:0] triggeredVec [0:PW-1];
  generate
    for (i = 0; i < PW; i = i + 1) begin : g_fire
      // 触发器 0 无前驱: 命中且自身非链中段即可发射
      assign canFire[i][0] = hit[0][i] & ~chainQ[0];
      for (j = 1; j < NT; j = j + 1) begin : g_chain
        assign canFire[i][j] =
          (chainQ[j-1] & hit[j-1][i] | ~chainQ[j-1])
          & (chainQ[j-1] & ~chainQ[j] & timingSame[j] | ~chainQ[j-1])
          & hit[j][i] & ~chainQ[j];
      end
      wire hasFire = |canFire[i];
      // 最低可发射触发器的 action(无可发射时缺省 actionQ[3], 被 hasFire 门控)
      wire [3:0] fireAction = canFire[i][0] ? actionQ[0]
                            : canFire[i][1] ? actionQ[1]
                            : canFire[i][2] ? actionQ[2] : actionQ[3];
      // triggered 编码: 0=断点异常(须 triggerCanRaiseBpExp), 1=进 debug, F=未触发
      assign triggeredVec[i] =
        hasFire & (fireAction == 4'h0) & io_frontendTrigger_triggerCanRaiseBpExp
          ? 4'h0
          : hasFire & (fireAction == 4'h1) ? 4'h1 : 4'hF;
    end
  endgenerate
""")
    for i in range(PW):
        L.append("  assign io_triggered_%d = triggeredVec[%d];" % (i, i))
    L.append("endmodule")
    return "\n".join(L) + "\n"


def gen_flat_wrapper(ports, modname, comment):
    conns = ",\n".join("    .%s(%s)" % (n, n) for _, _, n in ports)
    return "%s\n// %s\nmodule %s(\n%s\n);\n  xs_FrontendTrigger_core u_core(\n%s\n  );\nendmodule\n" % (
        BANNER, comment, modname, port_decls(ports), conns)


def gen_tb(ports):
    ins = [(w, n) for d, w, n in ports if d == "input" and n not in ("clock", "reset")]
    outs = [(w, n) for d, w, n in ports if d == "output"]
    L = []
    L.append(BANNER)
    L.append("// Double-instantiate golden FrontendTrigger vs FrontendTrigger_xs; 逐拍比对全部输出。")
    L.append("`timescale 1ns/1ps")
    L.append("module tb;")
    L.append("  int unsigned NCYCLES = 200000;")
    L.append("  int unsigned WARMUP  = 8;")
    L.append("  bit clk = 0;")
    L.append("  logic rst;")
    L.append("  int errors = 0, checks = 0, cyc = 0;")
    L.append("  int act_bp = 0, act_dbg = 0, act_any = 0;  // golden 触发活性审计")
    L.append("  always #5 clk = ~clk;")
    L.append("")
    for w, n in ins:
        L.append("  logic %s%s;" % ((w + " ") if w else "", n))
    L.append("")
    for w, n in outs:
        L.append("  wire %s g_%s, i_%s;" % (w if w else "     ", n, n))
    L.append("")
    conns_g = ",\n".join(["    .clock(clk)", "    .reset(rst)"] +
                         ["    .%s(%s)" % (n, n) for _, n in ins] +
                         ["    .%s(g_%s)" % (n, n) for _, n in outs])
    conns_i = ",\n".join(["    .clock(clk)", "    .reset(rst)"] +
                         ["    .%s(%s)" % (n, n) for _, n in ins] +
                         ["    .%s(i_%s)" % (n, n) for _, n in outs])
    L.append("  FrontendTrigger u_g(\n%s\n  );" % conns_g)
    L.append("")
    L.append("  FrontendTrigger_xs u_i(\n%s\n  );" % conns_i)
    L.append("""
  // 与 pc 同一小块号空间, 保证 equal/greater/less 三路都非蒸汽
  localparam logic [44:0] BASE_HI = 45'h1234;

  function automatic logic [1:0] rmt();  // matchType: 0=equal 多数, 1=保留, 2=geq, 3=less
    int r;
    r = $urandom_range(9);
    return (r < 4) ? 2'h0 : (r < 6) ? 2'h1 : (r < 8) ? 2'h2 : 2'h3;
  endfunction

  function automatic logic [3:0] ract();  // action: 0(断点)/1(debug) 多数
    int r;
    r = $urandom_range(9);
    return (r < 4) ? 4'h0 : (r < 7) ? 4'h1 : 4'($urandom);
  endfunction

  task automatic drive_random();
    logic [44:0] hi;
    logic [49:0] pcbase;
    io_frontendTrigger_tUpdate_valid = ($urandom_range(9) < 4);
    io_frontendTrigger_tUpdate_bits_addr = 2'($urandom_range(3));
    io_frontendTrigger_tUpdate_bits_tdata_matchType = rmt();
    io_frontendTrigger_tUpdate_bits_tdata_select = ($urandom_range(9) == 0);
    io_frontendTrigger_tUpdate_bits_tdata_action = ract();
    io_frontendTrigger_tUpdate_bits_tdata_chain = ($urandom_range(9) < 3);
    hi = BASE_HI + 45'($urandom_range(3));
    io_frontendTrigger_tUpdate_bits_tdata_tdata2 = {14'($urandom), hi, 5'($urandom)};""")
    for j in range(NT):
        L.append("    io_frontendTrigger_tEnableVec_%d = ($urandom_range(9) < 7);" % j)
    L.append("""    io_frontendTrigger_debugMode = ($urandom_range(19) == 0);
    io_frontendTrigger_triggerCanRaiseBpExp = 1'($urandom_range(1));
    // 顺序取指包; 5% 全随机 pc 打散
    if ($urandom_range(19) == 0) pcbase = {45'($urandom), 5'($urandom)};
    else pcbase = {BASE_HI + 45'($urandom_range(3)), 5'($urandom)};""")
    for i in range(PW):
        L.append("    io_pc_%d = 50'(pcbase + %d);" % (i, 2 * i))
    L.append("  endtask")
    L.append("")
    L.append("  initial begin")
    L.append("    rst = 1;")
    for w, n in ins:
        L.append("    %s = '0;" % n)
    L.append("""    repeat (5) @(posedge clk);
    @(negedge clk);
    rst = 0;
    repeat (WARMUP) @(posedge clk);
    for (cyc = 0; cyc < NCYCLES; cyc++) begin
      @(negedge clk);
      if ($urandom_range(199) == 0) begin  // 偶发异步复位脉冲(两侧共享)
        rst = 1;
        @(negedge clk);
        rst = 0;
      end
      drive_random();
      #1;
      checks++;""")
    for _, n in outs:
        L.append("      if (g_%s !== i_%s) begin errors++; if (errors < 20) $display(\"MISMATCH %s @%%0d g=%%h i=%%h\", cyc, g_%s, i_%s); end"
                 % (n, n, n, n, n))
    for _, n in outs:
        L.append("      if (g_%s == 4'h0) act_bp++; else if (g_%s == 4'h1) act_dbg++;" % (n, n))
        L.append("      if (g_%s != 4'hF) act_any++;" % n)
    L.append("""    end
    $display("ACTIVITY triggered_any=%0d bp_exception=%0d debug_mode=%0d", act_any, act_bp, act_dbg);
    if (errors == 0) $display("TEST PASSED checks=%0d errors=0", checks);
    else             $display("TEST FAILED checks=%0d errors=%0d", checks, errors);
    $finish;
  end
endmodule""")
    return "\n".join(L) + "\n"


def main():
    ports = parse_ports()
    rtl = os.path.join(ROOT, "rtl/frontend")
    ut = os.path.join(ROOT, "verif/ut/FrontendTrigger")
    os.makedirs(ut, exist_ok=True)
    open(os.path.join(rtl, "FrontendTrigger.sv"), "w").write(gen_core(ports))
    open(os.path.join(rtl, "FrontendTrigger_wrapper.sv"), "w").write(gen_flat_wrapper(
        ports, "FrontendTrigger",
        "FrontendTrigger — flat-port wrapper (FM impl 顶层). Instantiates xs_FrontendTrigger_core."))
    open(os.path.join(rtl, "FrontendTrigger_xs.sv"), "w").write(gen_flat_wrapper(
        ports, "FrontendTrigger_xs",
        "FrontendTrigger_xs — flat-port wrapper (UT 变体). Instantiates xs_FrontendTrigger_core."))
    open(os.path.join(ut, "tb.sv"), "w").write(gen_tb(ports))
    print("generated: %d ports" % len(ports))


if __name__ == "__main__":
    main()
