#!/usr/bin/env python3
"""gen_predchecker.py — 机械派生 PredChecker 可读核三件套 + UT tb。

来源: golden/chisel-rtl/PredChecker.sv (firtool 展平单模块, 0 子模块 0 mem)。
产物:
  rtl/frontend/PredChecker.sv          xs_PredChecker_core(可读核, 端口=golden 扁平端口)
  rtl/frontend/PredChecker_wrapper.sv  PredChecker(FM impl 顶层, 例化 u_core)
  rtl/frontend/PredChecker_xs.sv       PredChecker_xs(UT 变体, 同 wrapper 改名)
  verif/ut/PredChecker/tb.sv           golden vs _xs 双例化逐拍全输出比对

可读核纪律(ExceptionGen 定式): 逐字保留 golden 寄存器集(名/宽/使能 io_in_fire_in)
与 next-state 表达式; 仅把 firtool 的 _GEN_/_T_ 中间线重命名为可读名(RENAME 映射
见 core 头注释), 丢 randomize boilerplate。lane 对称组合逻辑收进 generate-for。
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GOLDEN = os.path.join(ROOT, "golden/chisel-rtl/PredChecker.sv")
PW = 16

BANNER = "// Generated by scripts/gen_predchecker.py — do not hand-edit."


def parse_ports():
    txt = open(GOLDEN).read()
    m = re.search(r"module PredChecker\((.*?)\n\);", txt, re.S)
    ports = []
    for line in m.group(1).split("\n"):
        line = line.strip().rstrip(",")
        mm = re.match(r"(input|output)\s*(\[\d+:\d+\])?\s*(\w+)$", line)
        if mm:
            ports.append((mm.group(1), mm.group(2) or "", mm.group(3)))
    assert ports and ports[0][2] == "clock"
    return ports


def port_decls(ports):
    out = []
    for d, w, n in ports:
        ww = (" %-7s" % w) if w else "        "
        out.append("  %-6s%s %s" % (d, ww, n))
    return ",\n".join(out)


def gen_core(ports):
    L = []
    L.append(BANNER)
    L.append("""//
// xs_PredChecker_core — readable faithful (bug-for-bug) core for golden
// PredChecker (IFU F3 预测检查器: 预译码 vs 分支预测一致性检查 + 目标重算)。
//
// 结构(golden firtool 单模块, 0 子模块 0 mem, 唯一使能 io_in_fire_in, 无 reset):
//   S1(组合): 逐 lane 检查预译码出的必然跳转(jal/jalr/ret)是否被预测漏掉
//             (jalFaultVec/jalrFaultVec/retFaultVec), 取最低 fault lane 截断
//             instrRange(fixedRange), 并重算 fixedTaken;
//   REG:      S1 结果 + 重算目标(jumpTargets=pc+offset, seqTargets=pc+2/4)
//             在 fire_in 下打 1 拍(*_Next 寄存器组, 逐字保留 golden 名);
//   S2(组合): 由寄存器重算 targetFault(预测目标 != 重算目标)、fixedTarget、
//             fixedMissPred、faultType(1=jal,6=jalr,2=ret,3=target,4=notCFI,5=invalid)。
//
// RENAME 映射(golden → 本核, 其余 golden 具名 wire/reg 逐字保留):
//   _GEN/_GEN_1.._GEN_29(奇偶交错)     → (brTypeIn[i] == 2'h2) 内联 / predUnseenTaken[i]
//     _GEN_0/_GEN_2/..(lane 特化 (|bits), |bits[3:1], bits>4'h2, bits[3], &bits, ~valid)
//     都是 (ftqOffset_bits > i) & valid | ~valid 的常量折叠 → predUnseenTaken[i]
//   _remaskIdx_T_17/_21/_23/_31 优先级树 → remaskIdx(always_comb 低位优先编码, 缺省 4'hF)
//   _fixedRange_T_6                     → fixedRangeMask
//   _GEN_30/32/../60(instrRange&mask)   → inFixedRange[i]
//   _GEN_31/33/../59, &bits(lane15)     → predTakenAt[i] (ftqOffset_bits == i)
// 寄存器集与 next-state 表达式逐字保留(fixedRangeNext/instrValidNext_*/takenIdxNext/
// predTakenNext/predTargetNext/jumpTargetsNext_*/seqTargetsNext_*/pdsNext_*_brType/
// jal|jalr|retFaultVecNext_*/notCFITakenNext_*/invalidTakenNext_*)。""")
    L.append("module xs_PredChecker_core(")
    L.append(port_decls(ports))
    L.append(");")
    L.append("")
    L.append("  localparam int PW = %d;   // PredictWidth" % PW)
    L.append("")
    L.append("  // ---------------- 输入数组视图(机械 扁平->数组 打包) ----------------")
    L.append("  wire [PW-1:0] instrRange = {%s};" % ", ".join(
        "io_in_instrRange_%d" % i for i in range(PW - 1, -1, -1)))
    L.append("  wire [PW-1:0] instrValid = {%s};" % ", ".join(
        "io_in_instrValid_%d" % i for i in range(PW - 1, -1, -1)))
    L.append("  wire [PW-1:0] isRetIn    = {%s};" % ", ".join(
        "io_in_pds_%d_isRet" % i for i in range(PW - 1, -1, -1)))
    L.append("  wire [1:0] brTypeIn [0:PW-1];")
    for i in range(PW):
        L.append("  assign brTypeIn[%d] = io_in_pds_%d_brType;" % (i, i))
    L.append("""
  // ---------------- S1: 预译码 vs 分支预测一致性检查(组合) ----------------
  // predUnseenTaken[i]: 预测 taken 点严格在 lane i 之后, 或本包无预测 taken。
  // 此时 lane i 的预译码必然跳转若存在, 即为预测漏报 fault。
  wire [PW-1:0] predUnseenTaken;
  wire [PW-1:0] jalFaultVec, jalrFaultVec, retFaultVec, remaskFault;
  genvar i;
  generate
    for (i = 0; i < PW; i = i + 1) begin : g_s1
      assign predUnseenTaken[i] =
        (io_in_ftqOffset_bits > i) & io_in_ftqOffset_valid | ~io_in_ftqOffset_valid;
      assign jalFaultVec[i] =
        (brTypeIn[i] == 2'h2) & instrRange[i] & instrValid[i] & predUnseenTaken[i];
      assign jalrFaultVec[i] =
        (brTypeIn[i] == 2'h3) & ~isRetIn[i] & instrRange[i] & instrValid[i]
        & predUnseenTaken[i];
      assign retFaultVec[i] =
        isRetIn[i] & instrRange[i] & instrValid[i] & predUnseenTaken[i];
      assign remaskFault[i] = jalFaultVec[i] | jalrFaultVec[i] | retFaultVec[i];
    end
  endgenerate

  // remaskIdx: 最低 fault lane 的优先编码(无 fault 时 4'hF, 与 golden 缺省一致;
  // golden 编码树只扫 lane0..14, lane15 fault 落缺省 4'hF —— 结果相同)。
  logic [3:0] remaskIdx;
  always_comb begin
    remaskIdx = 4'hF;
    for (int k = PW - 1; k >= 0; k = k - 1) begin
      if (remaskFault[k]) remaskIdx = 4'(k);
    end
  end
  // fixedRangeMask: 无 fault → 全 1; 有 fault → 只留 [remaskIdx:0]
  // (16'hFFFF >> ~idx = 16'hFFFF >> (15-idx))。
  wire [PW-1:0] fixedRangeMask = {PW{~(|remaskFault)}} | (16'hFFFF >> ~remaskIdx);
  wire [PW-1:0] fixedRange     = instrRange & fixedRangeMask;

  // fixedTaken(S1 组合输出): lane 有效且在修正范围内, 且预译码为必然跳转
  // (ret/jal/jalr), 或该 lane 恰是预测 taken 点且预译码确为 CFI(brType!=0)。
  wire [PW-1:0] inFixedRange;
  wire [PW-1:0] predTakenAt;
  wire [PW-1:0] fixedTaken;
  generate
    for (i = 0; i < PW; i = i + 1) begin : g_taken
      assign inFixedRange[i] = instrRange[i] & fixedRangeMask[i];
      assign predTakenAt[i]  = io_in_ftqOffset_bits == i;
      assign fixedTaken[i] =
        instrValid[i] & inFixedRange[i]
        & (isRetIn[i] | (brTypeIn[i] == 2'h2) | (brTypeIn[i] == 2'h3)
           | predTakenAt[i] & io_in_ftqOffset_valid & (brTypeIn[i] != 2'h0));
    end
  endgenerate

  // ---------------- 流水寄存器(golden 寄存器集逐字保留, fire_in 使能) --------""")
    L.append("  reg  [15:0] fixedRangeNext;")
    for i in range(PW):
        L.append("  reg         instrValidNext_%d;" % i)
    L.append("  reg  [3:0]  takenIdxNext;")
    L.append("  reg         predTakenNext;")
    L.append("  reg  [49:0] predTargetNext;")
    for i in range(PW):
        L.append("  reg  [49:0] jumpTargetsNext_%d;" % i)
    for i in range(PW):
        L.append("  reg  [49:0] seqTargetsNext_%d;" % i)
    for i in range(PW):
        L.append("  reg  [1:0]  pdsNext_%d_brType;" % i)
    for fam in ("jalFaultVecNext", "jalrFaultVecNext", "retFaultVecNext",
                "notCFITakenNext", "invalidTakenNext"):
        for i in range(PW):
            L.append("  reg         %s_%d;" % (fam, i))
    L.append("")
    L.append("  always @(posedge clock) begin")
    L.append("    if (io_in_fire_in) begin")
    L.append("      fixedRangeNext <= fixedRange;")
    for i in range(PW):
        L.append("      instrValidNext_%d <= io_in_instrValid_%d;" % (i, i))
    L.append("      takenIdxNext <= io_in_ftqOffset_bits;")
    L.append("      predTakenNext <= io_in_ftqOffset_valid;")
    L.append("      predTargetNext <= io_in_target;")
    for i in range(PW):
        L.append("      jumpTargetsNext_%d <= 50'(io_in_pc_%d + io_in_jumpOffset_%d[49:0]);"
                 % (i, i, i))
    for i in range(PW):
        L.append("      seqTargetsNext_%d <=" % i)
        L.append("        50'(io_in_pc_%d + {47'h0, io_in_pds_%d_isRVC | ~io_in_instrValid_%d ? 3'h2 : 3'h4});"
                 % (i, i, i))
    for i in range(PW):
        L.append("      pdsNext_%d_brType <= io_in_pds_%d_brType;" % (i, i))
    for fam, src in (("jalFaultVecNext", "jalFaultVec"),
                     ("jalrFaultVecNext", "jalrFaultVec"),
                     ("retFaultVecNext", "retFaultVec")):
        for i in range(PW):
            L.append("      %s_%d <= %s[%d];" % (fam, i, src, i))
    for i in range(PW):
        L.append("      notCFITakenNext_%d <=" % i)
        L.append("        inFixedRange[%d] & io_in_instrValid_%d & predTakenAt[%d]" % (i, i, i))
        L.append("        & (io_in_pds_%d_brType == 2'h0) & io_in_ftqOffset_valid;" % i)
    for i in range(PW):
        L.append("      invalidTakenNext_%d <=" % i)
        L.append("        inFixedRange[%d] & ~io_in_instrValid_%d & predTakenAt[%d] & io_in_ftqOffset_valid;"
                 % (i, i, i))
    L.append("    end")
    L.append("  end")
    L.append("")
    L.append("  // ---------------- S2: 由寄存器重算 targetFault(组合) --------------------")
    L.append("  // targetFault_i: 该 lane 是预测 taken 的条件分支/jal, 但预测目标与")
    L.append("  // 重算跳转目标不符。")
    for i in range(PW):
        L.append("  wire targetFault_%d =" % i)
        L.append("    fixedRangeNext[%d] & instrValidNext_%d" % (i, i))
        L.append("    & ((pdsNext_%d_brType == 2'h2) | (pdsNext_%d_brType == 2'h1))" % (i, i))
        L.append("    & (takenIdxNext == 4'h%X) & predTakenNext" % i)
        L.append("    & (predTargetNext != jumpTargetsNext_%d);" % i)
    L.append("")
    L.append("  // ---------------- 输出 ----------------")
    for i in range(PW):
        L.append("  assign io_out_stage1Out_fixedRange_%d = fixedRange[%d];" % (i, i))
    for i in range(PW):
        L.append("  assign io_out_stage1Out_fixedTaken_%d = fixedTaken[%d];" % (i, i))
    for i in range(PW):
        L.append("  assign io_out_stage2Out_fixedTarget_%d =" % i)
        L.append("    jalFaultVecNext_%d | targetFault_%d ? jumpTargetsNext_%d : seqTargetsNext_%d;"
                 % (i, i, i, i))
    for i in range(PW):
        L.append("  assign io_out_stage2Out_jalTarget_%d = jumpTargetsNext_%d;" % (i, i))
    for i in range(PW):
        L.append("  assign io_out_stage2Out_fixedMissPred_%d =" % i)
        L.append("    jalFaultVecNext_%d | jalrFaultVecNext_%d | retFaultVecNext_%d" % (i, i, i))
        L.append("    | notCFITakenNext_%d | invalidTakenNext_%d | targetFault_%d;" % (i, i, i))
    for i in range(PW):
        L.append("  assign io_out_stage2Out_faultType_%d_value =" % i)
        L.append("    jalFaultVecNext_%d ? 3'h1" % i)
        L.append("      : jalrFaultVecNext_%d ? 3'h6" % i)
        L.append("      : retFaultVecNext_%d ? 3'h2" % i)
        L.append("      : targetFault_%d ? 3'h3" % i)
        L.append("      : notCFITakenNext_%d ? 3'h4 : invalidTakenNext_%d ? 3'h5 : 3'h0;" % (i, i))
    L.append("endmodule")
    return "\n".join(L) + "\n"


def gen_flat_wrapper(ports, modname, comment):
    conns = ",\n".join("    .%s(%s)" % (n, n) for _, _, n in ports)
    return "%s\n// %s\nmodule %s(\n%s\n);\n  xs_PredChecker_core u_core(\n%s\n  );\nendmodule\n" % (
        BANNER, comment, modname, port_decls(ports), conns)


def gen_tb(ports):
    ins = [(w, n) for d, w, n in ports if d == "input" and n != "clock"]
    outs = [(w, n) for d, w, n in ports if d == "output"]
    L = []
    L.append(BANNER)
    L.append("// Double-instantiate golden PredChecker vs PredChecker_xs; 逐拍比对全部输出。")
    L.append("`timescale 1ns/1ps")
    L.append("module tb;")
    L.append("  int unsigned NCYCLES = 200000;")
    L.append("  int unsigned WARMUP  = 8;")
    L.append("  bit clk = 0;")
    L.append("  int errors = 0, checks = 0, cyc = 0;")
    L.append("  int act_ft[8];        // golden faultType 分布(非蒸汽激励审计)")
    L.append("  int act_taken = 0;    // golden fixedTaken 非零拍数")
    L.append("  always #5 clk = ~clk;")
    L.append("")
    for w, n in ins:
        L.append("  logic %s%s;" % ((w + " ") if w else "", n))
    L.append("")
    for w, n in outs:
        L.append("  wire %s g_%s, i_%s;" % (w if w else "     ", n, n))
    L.append("")
    conns_g = ",\n".join(["    .clock(clk)"] +
                         ["    .%s(%s)" % (n, n) for _, n in ins] +
                         ["    .%s(g_%s)" % (n, n) for _, n in outs])
    conns_i = ",\n".join(["    .clock(clk)"] +
                         ["    .%s(%s)" % (n, n) for _, n in ins] +
                         ["    .%s(i_%s)" % (n, n) for _, n in outs])
    L.append("  PredChecker u_g(\n%s\n  );" % conns_g)
    L.append("")
    L.append("  PredChecker_xs u_i(\n%s\n  );" % conns_i)
    L.append("""
  function automatic logic [63:0] rj();  // jump offset: 小偏移与全随机混合
    logic [63:0] v;
    v = {$urandom, $urandom};
    if ($urandom_range(1)) v &= 64'hFFF;
    return v;
  endfunction

  function automatic logic [1:0] rbrtype();  // brType 偏置: 多数 notCFI
    int r;
    r = $urandom_range(9);
    return (r < 5) ? 2'h0 : (r < 7) ? 2'h1 : (r < 9) ? 2'h2 : 2'h3;
  endfunction

  task automatic drive_random();
    logic [63:0] r64;
    logic [49:0] base;
    io_in_fire_in = ($urandom_range(9) < 8);
    io_in_ftqOffset_valid = $urandom_range(1);
    io_in_ftqOffset_bits = 4'($urandom_range(15));
    r64 = {$urandom, $urandom};
    base = r64[49:0];
    if ($urandom_range(3) != 0) base &= 50'hFFFF;  // 多数落小地址空间""")
    for i in range(PW):
        L.append("    io_in_pc_%d = 50'(base + %d);" % (i, 2 * i))
    for i in range(PW):
        L.append("    io_in_jumpOffset_%d = rj();" % i)
    for i in range(PW):
        L.append("    io_in_instrRange_%d = ($urandom_range(9) < 8);" % i)
        L.append("    io_in_instrValid_%d = ($urandom_range(9) < 8);" % i)
        L.append("    io_in_pds_%d_brType = rbrtype();" % i)
        L.append("    io_in_pds_%d_isRet = (io_in_pds_%d_brType == 2'h3) ? 1'($urandom_range(1)) : ($urandom_range(19) == 0);" % (i, i))
        L.append("    io_in_pds_%d_isRVC = 1'($urandom_range(1));" % i)
    L.append("    // 一半概率把预测目标钉成某 lane 的重算目标(触发 targetFault 相等支路)")
    L.append("    if ($urandom_range(1)) begin")
    L.append("      case ($urandom_range(15))")
    for i in range(PW):
        L.append("        %d: io_in_target = 50'(io_in_pc_%d + io_in_jumpOffset_%d[49:0]);" % (i, i, i))
    L.append("      endcase")
    L.append("    end else io_in_target = r64[49:0] ^ 50'h5A5A5;")
    L.append("  endtask")
    L.append("")
    L.append("  initial begin")
    for w, n in ins:
        L.append("    %s = '0;" % n)
    L.append("""    repeat (WARMUP) @(posedge clk);
    for (cyc = 0; cyc < NCYCLES; cyc++) begin
      @(negedge clk);
      drive_random();
      #1;
      checks++;""")
    for _, n in outs:
        L.append("      if (g_%s !== i_%s) begin errors++; if (errors < 20) $display(\"MISMATCH %s @%%0d g=%%h i=%%h\", cyc, g_%s, i_%s); end"
                 % (n, n, n, n, n))
    L.append("      // 激励活性审计(golden 侧)")
    for i in range(PW):
        L.append("      if (g_io_out_stage2Out_faultType_%d_value != 3'h0) act_ft[g_io_out_stage2Out_faultType_%d_value]++;" % (i, i))
    L.append("      if ({%s} != 16'h0) act_taken++;" % ", ".join(
        "g_io_out_stage1Out_fixedTaken_%d" % i for i in range(PW - 1, -1, -1)))
    L.append("""    end
    $display("ACTIVITY fixedTaken=%0d jal=%0d ret=%0d target=%0d notCFI=%0d invalid=%0d jalr=%0d",
             act_taken, act_ft[1], act_ft[2], act_ft[3], act_ft[4], act_ft[5], act_ft[6]);
    if (errors == 0) $display("TEST PASSED checks=%0d errors=0", checks);
    else             $display("TEST FAILED checks=%0d errors=%0d", checks, errors);
    $finish;
  end
endmodule""")
    return "\n".join(L) + "\n"


def main():
    ports = parse_ports()
    rtl = os.path.join(ROOT, "rtl/frontend")
    ut = os.path.join(ROOT, "verif/ut/PredChecker")
    os.makedirs(ut, exist_ok=True)
    open(os.path.join(rtl, "PredChecker.sv"), "w").write(gen_core(ports))
    open(os.path.join(rtl, "PredChecker_wrapper.sv"), "w").write(gen_flat_wrapper(
        ports, "PredChecker",
        "PredChecker — flat-port wrapper (FM impl 顶层). Instantiates xs_PredChecker_core."))
    open(os.path.join(rtl, "PredChecker_xs.sv"), "w").write(gen_flat_wrapper(
        ports, "PredChecker_xs",
        "PredChecker_xs — flat-port wrapper (UT 变体). Instantiates xs_PredChecker_core."))
    open(os.path.join(ut, "tb.sv"), "w").write(gen_tb(ports))
    print("generated: %d ports" % len(ports))


if __name__ == "__main__":
    main()
