  // ====================== leaf-output nets (golden 同名) ======================
  wire               _enqPtrGenModule_io_out_0_flag;
  wire [7:0]         _enqPtrGenModule_io_out_0_value;
  wire [7:0]         _enqPtrGenModule_io_out_1_value;
  wire [7:0]         _enqPtrGenModule_io_out_2_value;
  wire [7:0]         _enqPtrGenModule_io_out_3_value;
  wire [7:0]         _enqPtrGenModule_io_out_4_value;
  wire [7:0]         _enqPtrGenModule_io_out_5_value;
  wire               _deqPtrGenModule_io_out_0_flag;
  wire [7:0]         _deqPtrGenModule_io_out_0_value;
  wire [7:0]         _deqPtrGenModule_io_out_1_value;
  wire [7:0]         _deqPtrGenModule_io_out_2_value;
  wire [7:0]         _deqPtrGenModule_io_out_3_value;
  wire [7:0]         _deqPtrGenModule_io_out_4_value;
  wire [7:0]         _deqPtrGenModule_io_out_5_value;
  wire [7:0]         _deqPtrGenModule_io_out_6_value;
  wire [7:0]         _deqPtrGenModule_io_out_7_value;
  wire               _deqPtrGenModule_io_next_out_0_flag;
  wire [7:0]         _deqPtrGenModule_io_next_out_0_value;
  wire               _exceptionGen_io_state_valid;
  wire               _exceptionGen_io_state_bits_robIdx_flag;
  wire [7:0]         _exceptionGen_io_state_bits_robIdx_value;
  wire               _exceptionGen_io_state_bits_hasException;
  wire               _exceptionGen_io_state_bits_isEnqExcp;
  wire               _exceptionGen_io_state_bits_exceptionVec_0;
  wire               _exceptionGen_io_state_bits_exceptionVec_1;
  wire               _exceptionGen_io_state_bits_exceptionVec_2;
  wire               _exceptionGen_io_state_bits_exceptionVec_3;
  wire               _exceptionGen_io_state_bits_exceptionVec_4;
  wire               _exceptionGen_io_state_bits_exceptionVec_5;
  wire               _exceptionGen_io_state_bits_exceptionVec_6;
  wire               _exceptionGen_io_state_bits_exceptionVec_7;
  wire               _exceptionGen_io_state_bits_exceptionVec_8;
  wire               _exceptionGen_io_state_bits_exceptionVec_9;
  wire               _exceptionGen_io_state_bits_exceptionVec_10;
  wire               _exceptionGen_io_state_bits_exceptionVec_11;
  wire               _exceptionGen_io_state_bits_exceptionVec_12;
  wire               _exceptionGen_io_state_bits_exceptionVec_13;
  wire               _exceptionGen_io_state_bits_exceptionVec_14;
  wire               _exceptionGen_io_state_bits_exceptionVec_15;
  wire               _exceptionGen_io_state_bits_exceptionVec_16;
  wire               _exceptionGen_io_state_bits_exceptionVec_17;
  wire               _exceptionGen_io_state_bits_exceptionVec_18;
  wire               _exceptionGen_io_state_bits_exceptionVec_19;
  wire               _exceptionGen_io_state_bits_exceptionVec_20;
  wire               _exceptionGen_io_state_bits_exceptionVec_21;
  wire               _exceptionGen_io_state_bits_exceptionVec_22;
  wire               _exceptionGen_io_state_bits_exceptionVec_23;
  wire               _exceptionGen_io_state_bits_isFetchMalAddr;
  wire               _exceptionGen_io_state_bits_flushPipe;
  wire               _exceptionGen_io_state_bits_isVset;
  wire               _exceptionGen_io_state_bits_replayInst;
  wire               _exceptionGen_io_state_bits_singleStep;
  wire               _exceptionGen_io_state_bits_crossPageIPFFix;
  wire [3:0]         _exceptionGen_io_state_bits_trigger;
  wire               _exceptionGen_io_state_bits_vstartEn;
  wire [63:0]        _exceptionGen_io_state_bits_vstart;
  wire               _exceptionGen_io_state_bits_isVecLoad;
  wire               _exceptionGen_io_state_bits_isVlm;
  wire               _exceptionGen_io_state_bits_isStrided;
  wire               _exceptionGen_io_state_bits_isIndexed;
  wire               _exceptionGen_io_state_bits_isWhole;
  wire [2:0]         _exceptionGen_io_state_bits_nf;
  wire [1:0]         _exceptionGen_io_state_bits_vsew;
  wire [1:0]         _exceptionGen_io_state_bits_veew;
  wire [2:0]         _exceptionGen_io_state_bits_vlmul;
  wire               _snapshots_snapshotGen_io_snapshots_0_0_flag;
  wire [7:0]         _snapshots_snapshotGen_io_snapshots_0_0_value;
  wire               _snapshots_snapshotGen_io_snapshots_1_0_flag;
  wire [7:0]         _snapshots_snapshotGen_io_snapshots_1_0_value;
  wire               _snapshots_snapshotGen_io_snapshots_2_0_flag;
  wire [7:0]         _snapshots_snapshotGen_io_snapshots_2_0_value;
  wire               _snapshots_snapshotGen_io_snapshots_3_0_flag;
  wire [7:0]         _snapshots_snapshotGen_io_snapshots_3_0_value;
  wire               _vtypeBuffer_io_canEnq;
  wire               _vtypeBuffer_io_canEnqForDispatch;
  wire               _vtypeBuffer_io_toDecode_isResumeVType;
  wire               _vtypeBuffer_io_status_walkEnd;
  wire               _rab_io_canEnq;
  wire               _rab_io_canEnqForDispatch;
  wire               _rab_io_commits_isCommit;
  wire               _rab_io_commits_commitValid_0;
  wire               _rab_io_commits_commitValid_1;
  wire               _rab_io_commits_commitValid_2;
  wire               _rab_io_commits_commitValid_3;
  wire               _rab_io_commits_commitValid_4;
  wire               _rab_io_commits_commitValid_5;
  wire               _rab_io_commits_isWalk;
  wire               _rab_io_commits_walkValid_0;
  wire               _rab_io_commits_walkValid_1;
  wire               _rab_io_commits_walkValid_2;
  wire               _rab_io_commits_walkValid_3;
  wire               _rab_io_commits_walkValid_4;
  wire               _rab_io_commits_walkValid_5;
  wire [5:0]         _rab_io_commits_info_0_ldest;
  wire [7:0]         _rab_io_commits_info_0_pdest;
  wire               _rab_io_commits_info_0_rfWen;
  wire               _rab_io_commits_info_0_fpWen;
  wire               _rab_io_commits_info_0_vecWen;
  wire               _rab_io_commits_info_0_v0Wen;
  wire               _rab_io_commits_info_0_vlWen;
  wire               _rab_io_commits_info_0_isMove;
  wire [5:0]         _rab_io_commits_info_1_ldest;
  wire [7:0]         _rab_io_commits_info_1_pdest;
  wire               _rab_io_commits_info_1_rfWen;
  wire               _rab_io_commits_info_1_fpWen;
  wire               _rab_io_commits_info_1_vecWen;
  wire               _rab_io_commits_info_1_v0Wen;
  wire               _rab_io_commits_info_1_vlWen;
  wire               _rab_io_commits_info_1_isMove;
  wire [5:0]         _rab_io_commits_info_2_ldest;
  wire [7:0]         _rab_io_commits_info_2_pdest;
  wire               _rab_io_commits_info_2_rfWen;
  wire               _rab_io_commits_info_2_fpWen;
  wire               _rab_io_commits_info_2_vecWen;
  wire               _rab_io_commits_info_2_v0Wen;
  wire               _rab_io_commits_info_2_vlWen;
  wire               _rab_io_commits_info_2_isMove;
  wire [5:0]         _rab_io_commits_info_3_ldest;
  wire [7:0]         _rab_io_commits_info_3_pdest;
  wire               _rab_io_commits_info_3_rfWen;
  wire               _rab_io_commits_info_3_fpWen;
  wire               _rab_io_commits_info_3_vecWen;
  wire               _rab_io_commits_info_3_v0Wen;
  wire               _rab_io_commits_info_3_vlWen;
  wire               _rab_io_commits_info_3_isMove;
  wire [5:0]         _rab_io_commits_info_4_ldest;
  wire [7:0]         _rab_io_commits_info_4_pdest;
  wire               _rab_io_commits_info_4_rfWen;
  wire               _rab_io_commits_info_4_fpWen;
  wire               _rab_io_commits_info_4_vecWen;
  wire               _rab_io_commits_info_4_v0Wen;
  wire               _rab_io_commits_info_4_vlWen;
  wire               _rab_io_commits_info_4_isMove;
  wire [5:0]         _rab_io_commits_info_5_ldest;
  wire [7:0]         _rab_io_commits_info_5_pdest;
  wire               _rab_io_commits_info_5_rfWen;
  wire               _rab_io_commits_info_5_fpWen;
  wire               _rab_io_commits_info_5_vecWen;
  wire               _rab_io_commits_info_5_v0Wen;
  wire               _rab_io_commits_info_5_vlWen;
  wire               _rab_io_commits_info_5_isMove;
  wire               _rab_io_status_walkEnd;
  wire               _rab_io_status_commitEnd;

  // ====================== u_core 输出 wire (供 .* 绑定 + glue/assign 引用) ======================
  rob_state_e                 o_state;
  logic                       o_commits_isCommit;
  logic                       o_commits_isWalk;
  logic [COMMIT_WIDTH-1:0]    o_commits_commitValid;
  logic [COMMIT_WIDTH-1:0]    o_commits_walkValid;
  rob_commit_entry_t          o_commit_info  [COMMIT_WIDTH];
  rob_ptr_t                   o_commits_robIdx [COMMIT_WIDTH];
  logic [COMMIT_WIDTH-1:0]    o_deq_commit_v;
  logic [COMMIT_WIDTH-1:0]    o_deq_commit_w;
  logic                       o_intrBitSetReg;
  logic                       o_hasNoSpecExec;
  logic                       o_allowOnlyOneCommit;
  logic                       o_blockCommit;
  logic [COMMIT_WIDTH-1:0]    o_hasCommitted;
  logic                       o_allCommitted;
  logic                       o_allowEnqueue;
  logic                       o_hasBlockBackward;
  logic [RENAME_WIDTH-1:0]    o_enq_for_ptr;
  logic                       o_eg_flush;
  logic [UOP_CNT_W:0]         o_rab_commitSize;
  logic [UOP_CNT_W:0]         o_rab_walkSize;
  logic                       o_rab_walkEnd;
  logic                       o_flushOut_valid;
  logic                       o_flushOut_robIdx_flag;
  logic [PTR_W-1:0]           o_flushOut_robIdx_value;
  logic                       o_flushOut_level;
  logic                       o_flushOut_isRVC;
  logic [FTQ_PTR_W-1:0]       o_flushOut_ftqIdx_value;
  logic                       o_flushOut_ftqIdx_flag;
  logic [FTQ_OFFSET_W-1:0]    o_flushOut_ftqOffset;
  logic                       o_exception_valid;
  logic                       o_exceptionHappen;
  logic                       o_deqHasException;
  logic                       o_intrEnable;
  logic                       o_enq_canAccept;
  logic                       o_enq_canAcceptForDispatch;
  logic                       o_robFull;
  logic                       o_headNotReady;
  logic                       o_cpu_halt;
  logic                       o_wfiReq;
  logic [PTR_W:0]             o_numValidEntries;
  logic [5:0]                 o_perf_0_value;
  logic [5:0]                 o_perf_1_value;
  logic [5:0]                 o_perf_2_value;
  logic [5:0]                 o_perf_3_value;
  logic [5:0]                 o_perf_4_value;
  logic [5:0]                 o_perf_5_value;
  logic [5:0]                 o_perf_6_value;
  logic [5:0]                 o_perf_7_value;
  logic [5:0]                 o_perf_8_value;
  logic [5:0]                 o_perf_9_value;
  logic [5:0]                 o_perf_10_value;
  logic [5:0]                 o_perf_11_value;
  logic [5:0]                 o_perf_12_value;
  logic [5:0]                 o_perf_13_value;
  logic [5:0]                 o_perf_14_value;
  logic [5:0]                 o_perf_15_value;
  logic [5:0]                 o_perf_16_value;
  logic [5:0]                 o_perf_17_value;
  logic [COMMIT_WIDTH-1:0]    o_trace_valid;
  logic [FTQ_PTR_W-1:0]       o_trace_ftqIdx_value [COMMIT_WIDTH];
  logic [FTQ_OFFSET_W-1:0]    o_trace_ftqOffset    [COMMIT_WIDTH];
  logic [ITYPE_W-1:0]         o_trace_itype        [COMMIT_WIDTH];
  logic [IRETIRE_W-1:0]       o_trace_iretire      [COMMIT_WIDTH];
  logic [COMMIT_WIDTH-1:0]    o_trace_ilastsize;
  logic                       o_csr_fflags_valid;
  logic [4:0]                 o_csr_fflags_bits;
  logic                       o_csr_vxsat_valid;
  logic                       o_csr_vxsat_bits;
  logic                       o_csr_vstart_valid;
  logic [63:0]                o_csr_vstart_bits;
  logic                       o_csr_dirty_fs;
  logic                       o_csr_dirty_vs;
  logic [6:0]                 o_csr_perfinfo_retiredInstr;
  logic [34:0]                o_debugRobHead_fuType;
  logic                       o_debugTopDown_robHeadLsIssue;
  logic                       o_debugTopDown_robHeadVaddr_valid;
  logic [49:0]                o_debugTopDown_robHeadVaddr_bits;
  logic                       o_debugTopDown_robHeadPaddr_valid;
  logic [47:0]                o_debugTopDown_robHeadPaddr_bits;
  logic                       o_toVecExcpMod_excpInfo_valid;
  logic [6:0]                 o_toVecExcpMod_excpInfo_bits_vstart;
  logic [1:0]                 o_toVecExcpMod_excpInfo_bits_vsew;
  logic [1:0]                 o_toVecExcpMod_excpInfo_bits_veew;
  logic [2:0]                 o_toVecExcpMod_excpInfo_bits_vlmul;
  logic [2:0]                 o_toVecExcpMod_excpInfo_bits_nf;
  logic                       o_toVecExcpMod_excpInfo_bits_isStride;
  logic                       o_toVecExcpMod_excpInfo_bits_isIndexed;
  logic                       o_toVecExcpMod_excpInfo_bits_isWhole;
  logic                       o_toVecExcpMod_excpInfo_bits_isVlm;
  logic [COMMIT_WIDTH-1:0]    o_deq_entry_vls;
  logic                       o_deq_entry_valid_0;
  logic                       o_deq_entry_mmio_0;
  logic                       o_deqHasFlushed;
  logic o_commit_info_0_interrupt_safe;
  assign o_commit_info_0_interrupt_safe = o_commit_info[0].interrupt_safe;

  // ====================== body-glue 组合译码 ======================
  logic canEnqueueEG_0,canEnqueueEG_1,canEnqueueEG_2,canEnqueueEG_3,canEnqueueEG_4,canEnqueueEG_5;
  assign canEnqueueEG_0 = io_enq_req_0_valid & o_enq_canAccept;
  assign canEnqueueEG_1 = io_enq_req_1_valid & o_enq_canAccept;
  assign canEnqueueEG_2 = io_enq_req_2_valid & o_enq_canAccept;
  assign canEnqueueEG_3 = io_enq_req_3_valid & o_enq_canAccept;
  assign canEnqueueEG_4 = io_enq_req_4_valid & o_enq_canAccept;
  assign canEnqueueEG_5 = io_enq_req_5_valid & o_enq_canAccept;
  logic snptEnq;
  assign snptEnq = o_enq_canAccept & (
    io_enq_req_0_valid & io_enq_req_0_bits_snapshot | io_enq_req_1_valid & io_enq_req_1_bits_snapshot | io_enq_req_2_valid & io_enq_req_2_bits_snapshot | io_enq_req_3_valid & io_enq_req_3_bits_snapshot | io_enq_req_4_valid & io_enq_req_4_bits_snapshot | io_enq_req_5_valid & io_enq_req_5_bits_snapshot);
  reg rab_vecLoadExcp_valid_REG;
  always_ff @(posedge clock) rab_vecLoadExcp_valid_REG <= _exceptionGen_io_state_valid & _exceptionGen_io_state_bits_isVecLoad;

  // ====================== flat-port 译码重建(golden 内部 wire) ======================
  wire enqNeedWriteRFSeq_0 = io_enq_req_0_bits_rfWen | io_enq_req_0_bits_fpWen | io_enq_req_0_bits_vecWen | io_enq_req_0_bits_v0Wen | io_enq_req_0_bits_vlWen;
  wire enqNeedWriteRFSeq_1 = io_enq_req_1_bits_rfWen | io_enq_req_1_bits_fpWen | io_enq_req_1_bits_vecWen | io_enq_req_1_bits_v0Wen | io_enq_req_1_bits_vlWen;
  wire enqNeedWriteRFSeq_2 = io_enq_req_2_bits_rfWen | io_enq_req_2_bits_fpWen | io_enq_req_2_bits_vecWen | io_enq_req_2_bits_v0Wen | io_enq_req_2_bits_vlWen;
  wire enqNeedWriteRFSeq_3 = io_enq_req_3_bits_rfWen | io_enq_req_3_bits_fpWen | io_enq_req_3_bits_vecWen | io_enq_req_3_bits_v0Wen | io_enq_req_3_bits_vlWen;
  wire enqNeedWriteRFSeq_4 = io_enq_req_4_bits_rfWen | io_enq_req_4_bits_fpWen | io_enq_req_4_bits_vecWen | io_enq_req_4_bits_v0Wen | io_enq_req_4_bits_vlWen;
  wire enqNeedWriteRFSeq_5 = io_enq_req_5_bits_rfWen | io_enq_req_5_bits_fpWen | io_enq_req_5_bits_vecWen | io_enq_req_5_bits_v0Wen | io_enq_req_5_bits_vlWen;
  wire allow_interrupts = ~(~(io_enq_req_0_bits_commitType[2]) & io_enq_req_0_bits_commitType[1]) & ~(io_enq_req_0_bits_fuType[9]) & ~(io_enq_req_0_bits_fuType[5]) & ~(io_enq_req_0_bits_fuType[28] | io_enq_req_0_bits_fuType[29] | io_enq_req_0_bits_fuType[30]);
  wire allow_interrupts_1 = ~(~(io_enq_req_1_bits_commitType[2]) & io_enq_req_1_bits_commitType[1]) & ~(io_enq_req_1_bits_fuType[9]) & ~(io_enq_req_1_bits_fuType[5]) & ~(io_enq_req_1_bits_fuType[28] | io_enq_req_1_bits_fuType[29] | io_enq_req_1_bits_fuType[30]);
  wire allow_interrupts_2 = ~(~(io_enq_req_2_bits_commitType[2]) & io_enq_req_2_bits_commitType[1]) & ~(io_enq_req_2_bits_fuType[9]) & ~(io_enq_req_2_bits_fuType[5]) & ~(io_enq_req_2_bits_fuType[28] | io_enq_req_2_bits_fuType[29] | io_enq_req_2_bits_fuType[30]);
  wire allow_interrupts_3 = ~(~(io_enq_req_3_bits_commitType[2]) & io_enq_req_3_bits_commitType[1]) & ~(io_enq_req_3_bits_fuType[9]) & ~(io_enq_req_3_bits_fuType[5]) & ~(io_enq_req_3_bits_fuType[28] | io_enq_req_3_bits_fuType[29] | io_enq_req_3_bits_fuType[30]);
  wire allow_interrupts_4 = ~(~(io_enq_req_4_bits_commitType[2]) & io_enq_req_4_bits_commitType[1]) & ~(io_enq_req_4_bits_fuType[9]) & ~(io_enq_req_4_bits_fuType[5]) & ~(io_enq_req_4_bits_fuType[28] | io_enq_req_4_bits_fuType[29] | io_enq_req_4_bits_fuType[30]);
  wire allow_interrupts_5 = ~(~(io_enq_req_5_bits_commitType[2]) & io_enq_req_5_bits_commitType[1]) & ~(io_enq_req_5_bits_fuType[9]) & ~(io_enq_req_5_bits_fuType[5]) & ~(io_enq_req_5_bits_fuType[28] | io_enq_req_5_bits_fuType[29] | io_enq_req_5_bits_fuType[30]);



  // ====================== difftest-链 deep glue tie-off(无 top-output 影响, DPI sink only) ======================
  wire [255:0] _GEN_190 = '0;
  wire [255:0] _GEN_191 = '0;
  wire [255:0] _GEN_192 = '0;
  wire [7:0] _GEN_22 = '0;
  wire [255:0] _GEN_24 = '0;
  wire [9:0] _GEN_3185 = '0;
  wire [255:0] _GEN_3559 = '0;
  wire [255:0] _GEN_3560 = '0;
  wire [255:0] _GEN_3561 = '0;
  wire [255:0] _GEN_3562 = '0;
  wire [255:0] _GEN_3563 = '0;
  wire [255:0] _GEN_3564 = '0;
  wire [255:0] _GEN_3565 = '0;
  wire [255:0] _GEN_3566 = '0;
  wire [255:0] _GEN_3567 = '0;
  wire [255:0] _GEN_3568 = '0;
  wire [255:0] _GEN_3569 = '0;
  wire [2:0] _GEN_3570 = '0;
  wire [2:0] _GEN_3571 = '0;
  wire [2:0] _GEN_3572 = '0;
  wire [2:0] _GEN_3573 = '0;
  wire [2:0] _GEN_3574 = '0;
  wire [2:0] _GEN_3575 = '0;
  wire [2:0] _GEN_3576 = '0;
  wire [2:0] _GEN_3577 = '0;
  wire [31:0] _instr_T = '0;
  wire [31:0] _instr_T_1 = '0;
  wire [31:0] _instr_T_2 = '0;
  wire [31:0] _instr_T_3 = '0;
  wire [31:0] _instr_T_4 = '0;
  wire [31:0] _instr_T_5 = '0;
  wire [31:0] _instr_T_6 = '0;
  wire [31:0] _instr_T_7 = '0;
  wire [5:0] commitInfo_0_debug_ldest = '0;
  wire [2:0] commitInfo_0_instrSize = '0;
  wire [5:0] commitInfo_1_debug_ldest = '0;
  wire [2:0] commitInfo_1_instrSize = '0;
  wire [5:0] commitInfo_2_debug_ldest = '0;
  wire [2:0] commitInfo_2_instrSize = '0;
  wire [5:0] commitInfo_3_debug_ldest = '0;
  wire [2:0] commitInfo_3_instrSize = '0;
  wire [5:0] commitInfo_4_debug_ldest = '0;
  wire [2:0] commitInfo_4_instrSize = '0;
  wire [5:0] commitInfo_5_debug_ldest = '0;
  wire [2:0] commitInfo_5_instrSize = '0;
  wire [5:0] commitInfo_6_debug_ldest = '0;
  wire [2:0] commitInfo_6_instrSize = '0;
  wire [5:0] commitInfo_7_debug_ldest = '0;
  wire [2:0] commitInfo_7_instrSize = '0;
  wire deqHasCommitted = '0;
  wire difftest_1_valid = '0;
  wire difftest_2_valid = '0;
  wire difftest_3_valid = '0;
  wire difftest_4_valid = '0;
  wire difftest_5_valid = '0;
  wire difftest_6_valid = '0;
  wire difftest_7_valid = '0;
  wire [63:0] difftest_8_instrCnt = '0;
  wire [7:0] difftest_coreid = '0;
  wire difftest_valid = '0;
  wire h0 = '0;
  wire h1 = '0;
  wire h2 = '0;
  wire h3 = '0;
  wire h4 = '0;
  wire h5 = '0;
  wire h6 = '0;
  wire h7 = '0;
  wire hasWFI = '0;
  wire isVLoad = '0;
  wire isVLoad_1 = '0;
  wire isVLoad_2 = '0;
  wire isVLoad_3 = '0;
  wire isVLoad_4 = '0;
  wire isVLoad_5 = '0;
  wire isVLoad_6 = '0;
  wire isVLoad_7 = '0;
  wire [63:0] timer = '0;
  // io_commits_commitValid_N_0 = u_core o_commits_commitValid[N](golden 内部, difftest 用)
  wire io_commits_commitValid_0_0 = o_commits_commitValid[0];
  wire io_commits_commitValid_1_0 = o_commits_commitValid[1];
  wire io_commits_commitValid_2_0 = o_commits_commitValid[2];
  wire io_commits_commitValid_3_0 = o_commits_commitValid[3];
  wire io_commits_commitValid_4_0 = o_commits_commitValid[4];
  wire io_commits_commitValid_5_0 = o_commits_commitValid[5];
  wire io_commits_commitValid_6_0 = o_commits_commitValid[6];
  wire io_commits_commitValid_7_0 = o_commits_commitValid[7];
  wire io_commits_isCommit_0 = o_commits_isCommit;
  // dt_*_ext 内存读数据(difftest eliminatedMove/isRVC/isXSTrap 追踪, 无 top-output): tie 0
  wire _dt_eliminatedMove_ext_R0_data = '0;
  wire _dt_eliminatedMove_ext_R1_data = '0;
  wire _dt_eliminatedMove_ext_R2_data = '0;
  wire _dt_eliminatedMove_ext_R3_data = '0;
  wire _dt_eliminatedMove_ext_R4_data = '0;
  wire _dt_eliminatedMove_ext_R5_data = '0;
  wire _dt_eliminatedMove_ext_R6_data = '0;
  wire _dt_eliminatedMove_ext_R7_data = '0;
  wire _dt_isRVC_ext_R0_data = '0;
  wire _dt_isRVC_ext_R1_data = '0;
  wire _dt_isRVC_ext_R2_data = '0;
  wire _dt_isRVC_ext_R3_data = '0;
  wire _dt_isRVC_ext_R4_data = '0;
  wire _dt_isRVC_ext_R5_data = '0;
  wire _dt_isRVC_ext_R6_data = '0;
  wire _dt_isRVC_ext_R7_data = '0;
  wire _dt_isXSTrap_ext_R0_data = '0;
  wire _dt_isXSTrap_ext_R1_data = '0;
  wire _dt_isXSTrap_ext_R2_data = '0;
  wire _dt_isXSTrap_ext_R3_data = '0;
  wire _dt_isXSTrap_ext_R4_data = '0;
  wire _dt_isXSTrap_ext_R5_data = '0;
  wire _dt_isXSTrap_ext_R6_data = '0;
  wire _dt_isXSTrap_ext_R7_data = '0;
  // trace block valid_0(golden difftest 内部, 无 top-output): tie 0
  wire io_trace_traceCommitInfo_blocks_1_valid_0 = '0;
  wire io_trace_traceCommitInfo_blocks_2_valid_0 = '0;
  wire io_trace_traceCommitInfo_blocks_3_valid_0 = '0;
  wire io_trace_traceCommitInfo_blocks_4_valid_0 = '0;
  wire io_trace_traceCommitInfo_blocks_5_valid_0 = '0;
  wire io_trace_traceCommitInfo_blocks_6_valid_0 = '0;
  wire io_trace_traceCommitInfo_blocks_7_valid_0 = '0;

  // ====================== u_core 输入驱动(复用 tb_tap u_i 块, u_g. 去前缀, o_* 决 prelude) ======================
  // ===================================================================
  // ---- 黑盒子模块输出探针(从 u_g 内部 wire 取) ----
  logic                    eg_valid, eg_robidx_flag;
  logic [PTR_W-1:0]        eg_robidx_value;
  logic eg_is_exception, eg_flush_pipe, eg_replay_inst, eg_is_vls, eg_is_enq_excp, eg_is_vset;
  rob_ptr_t deq_ptr_vec [COMMIT_WIDTH]; rob_ptr_t deq_ptr_next0;
  rob_ptr_t enq_ptr_vec [RENAME_WIDTH]; rob_ptr_t snap_ptr0;
  logic rab_can_enq, rab_status_commit_end, rab_status_walk_end, vtype_status_walk_end;

  // exceptionGen 状态探针 -> eg_*
  assign eg_valid        = _exceptionGen_io_state_valid;
  assign eg_robidx_flag  = _exceptionGen_io_state_bits_robIdx_flag;
  assign eg_robidx_value = _exceptionGen_io_state_bits_robIdx_value;
  // eg_is_exception = (|exceptionVec[23:0]) | singleStep | (trigger==4'h1)  (Rob.scala 577)
  assign eg_is_exception = (|{
      _exceptionGen_io_state_bits_exceptionVec_23, _exceptionGen_io_state_bits_exceptionVec_22,
      _exceptionGen_io_state_bits_exceptionVec_21, _exceptionGen_io_state_bits_exceptionVec_20,
      _exceptionGen_io_state_bits_exceptionVec_19, _exceptionGen_io_state_bits_exceptionVec_18,
      _exceptionGen_io_state_bits_exceptionVec_17, _exceptionGen_io_state_bits_exceptionVec_16,
      _exceptionGen_io_state_bits_exceptionVec_15, _exceptionGen_io_state_bits_exceptionVec_14,
      _exceptionGen_io_state_bits_exceptionVec_13, _exceptionGen_io_state_bits_exceptionVec_12,
      _exceptionGen_io_state_bits_exceptionVec_11, _exceptionGen_io_state_bits_exceptionVec_10,
      _exceptionGen_io_state_bits_exceptionVec_9,  _exceptionGen_io_state_bits_exceptionVec_8,
      _exceptionGen_io_state_bits_exceptionVec_7,  _exceptionGen_io_state_bits_exceptionVec_6,
      _exceptionGen_io_state_bits_exceptionVec_5,  _exceptionGen_io_state_bits_exceptionVec_4,
      _exceptionGen_io_state_bits_exceptionVec_3,  _exceptionGen_io_state_bits_exceptionVec_2,
      _exceptionGen_io_state_bits_exceptionVec_1,  _exceptionGen_io_state_bits_exceptionVec_0})
    | _exceptionGen_io_state_bits_singleStep | (_exceptionGen_io_state_bits_trigger == 4'h1);
  assign eg_flush_pipe   = _exceptionGen_io_state_bits_flushPipe;
  assign eg_replay_inst  = _exceptionGen_io_state_bits_replayInst;
  assign eg_is_vls       = _exceptionGen_io_state_bits_isVecLoad; // 占位, vls 由 entry 决定
  assign eg_is_enq_excp  = _exceptionGen_io_state_bits_isEnqExcp;
  assign eg_is_vset      = _exceptionGen_io_state_bits_isVset;

  // ---- exceptionGen 向量 state 探针(供 toVecExcpMod.excpInfo 打包) ----
  //   golden vstart 源宽 [63:0], 锁存时切 [6:0]; 此处直接切齐核输入。
  logic [6:0] eg_state_vstart;  logic [1:0] eg_state_vsew, eg_state_veew;
  logic [2:0] eg_state_vlmul, eg_state_nf;
  logic eg_state_isStrided, eg_state_isIndexed, eg_state_isWhole, eg_state_isVlm;
  logic eg_state_vstartEn, eg_state_isVecLoad, eg_state_isEnqExcp;
  assign eg_state_vstart    = _exceptionGen_io_state_bits_vstart[6:0];
  assign eg_state_vsew      = _exceptionGen_io_state_bits_vsew;
  assign eg_state_veew      = _exceptionGen_io_state_bits_veew;
  assign eg_state_vlmul     = _exceptionGen_io_state_bits_vlmul;
  assign eg_state_nf        = _exceptionGen_io_state_bits_nf;
  assign eg_state_isStrided = _exceptionGen_io_state_bits_isStrided;
  assign eg_state_isIndexed = _exceptionGen_io_state_bits_isIndexed;
  assign eg_state_isWhole   = _exceptionGen_io_state_bits_isWhole;
  assign eg_state_isVlm     = _exceptionGen_io_state_bits_isVlm;
  assign eg_state_vstartEn  = _exceptionGen_io_state_bits_vstartEn;
  assign eg_state_isVecLoad = _exceptionGen_io_state_bits_isVecLoad;
  assign eg_state_isEnqExcp = _exceptionGen_io_state_bits_isEnqExcp;

  // deqPtr / enqPtr / next / snap 探针
  always_comb begin
    deq_ptr_vec[0] = '{flag: _deqPtrGenModule_io_out_0_flag, value: _deqPtrGenModule_io_out_0_value};
    deq_ptr_vec[1] = '{flag: io_commits_robIdx_1_flag, value: _deqPtrGenModule_io_out_1_value};
    deq_ptr_vec[2] = '{flag: io_commits_robIdx_2_flag, value: _deqPtrGenModule_io_out_2_value};
    deq_ptr_vec[3] = '{flag: io_commits_robIdx_3_flag, value: _deqPtrGenModule_io_out_3_value};
    deq_ptr_vec[4] = '{flag: io_commits_robIdx_4_flag, value: _deqPtrGenModule_io_out_4_value};
    deq_ptr_vec[5] = '{flag: io_commits_robIdx_5_flag, value: _deqPtrGenModule_io_out_5_value};
    deq_ptr_vec[6] = '{flag: io_commits_robIdx_6_flag, value: _deqPtrGenModule_io_out_6_value};
    deq_ptr_vec[7] = '{flag: io_commits_robIdx_7_flag, value: _deqPtrGenModule_io_out_7_value};
    deq_ptr_next0 = '{flag: _deqPtrGenModule_io_next_out_0_flag, value: _deqPtrGenModule_io_next_out_0_value};
    enq_ptr_vec[0] = '{flag: _enqPtrGenModule_io_out_0_flag, value: _enqPtrGenModule_io_out_0_value};
    enq_ptr_vec[1] = '{flag: _enqPtrGenModule_io_out_0_flag, value: _enqPtrGenModule_io_out_1_value};
    enq_ptr_vec[2] = '{flag: _enqPtrGenModule_io_out_0_flag, value: _enqPtrGenModule_io_out_2_value};
    enq_ptr_vec[3] = '{flag: _enqPtrGenModule_io_out_0_flag, value: _enqPtrGenModule_io_out_3_value};
    enq_ptr_vec[4] = '{flag: _enqPtrGenModule_io_out_0_flag, value: _enqPtrGenModule_io_out_4_value};
    enq_ptr_vec[5] = '{flag: _enqPtrGenModule_io_out_0_flag, value: _enqPtrGenModule_io_out_5_value};
    unique case (io_snpt_snptSelect)
      2'd0: snap_ptr0 = '{flag: _snapshots_snapshotGen_io_snapshots_0_0_flag, value: _snapshots_snapshotGen_io_snapshots_0_0_value};
      2'd1: snap_ptr0 = '{flag: _snapshots_snapshotGen_io_snapshots_1_0_flag, value: _snapshots_snapshotGen_io_snapshots_1_0_value};
      2'd2: snap_ptr0 = '{flag: _snapshots_snapshotGen_io_snapshots_2_0_flag, value: _snapshots_snapshotGen_io_snapshots_2_0_value};
      2'd3: snap_ptr0 = '{flag: _snapshots_snapshotGen_io_snapshots_3_0_flag, value: _snapshots_snapshotGen_io_snapshots_3_0_value};
      default: snap_ptr0 = '0;
    endcase
  end
  assign rab_can_enq           = _rab_io_canEnq;
  assign rab_status_commit_end = _rab_io_status_commitEnd;
  assign rab_status_walk_end   = _rab_io_status_walkEnd;
  assign vtype_status_walk_end = _vtypeBuffer_io_status_walkEnd;

  // ---- enq 抽象翻译: 直接 tap u_g 派生 wire/req 端口 ----
  logic [RENAME_WIDTH-1:0] enq_valid, enq_first_uop, enq_need_write_rf, enq_write_std;
  logic [RENAME_WIDTH-1:0] enq_block_backward, enq_wait_forward, enq_is_wfi;
  logic [RENAME_WIDTH-1:0] enq_has_exception, enq_trigger_dmode, enq_allow_interrupt;
  logic [UOP_CNT_W-1:0] enq_num_wb [RENAME_WIDTH];
  logic [PTR_W-1:0] enq_robidx_value [RENAME_WIDTH];
  rob_entry_t enq_info [RENAME_WIDTH];
  always_comb begin
    enq_valid[0]         = io_enq_req_0_valid;
    enq_first_uop[0]     = io_enq_req_0_bits_firstUop;
    enq_need_write_rf[0] = enqNeedWriteRFSeq_0;
    enq_write_std[0]     = io_enq_req_0_bits_fuType[16];
    enq_block_backward[0]= io_enq_req_0_bits_blockBackward;
    enq_wait_forward[0]  = io_enq_req_0_bits_waitForward;
    enq_is_wfi[0]        = (io_enq_req_0_bits_fuType == 35'h2) & (io_enq_req_0_bits_fuOpType == 9'h22);
    enq_has_exception[0] = io_enq_req_0_bits_hasException;
    enq_trigger_dmode[0] = io_enq_req_0_bits_trigger == 4'h1;
    enq_allow_interrupt[0]= allow_interrupts;
    enq_num_wb[0]        = io_enq_req_0_bits_numWB;
    enq_robidx_value[0]  = io_enq_req_0_bits_robIdx_value;
    enq_info[0]          = '0;
    enq_info[0].rf_wen        = io_enq_req_0_bits_rfWen;
    enq_info[0].fp_wen        = io_enq_req_0_bits_dirtyFs;
    enq_info[0].wflags        = io_enq_req_0_bits_wfflags;
    enq_info[0].dirty_vs      = io_enq_req_0_bits_dirtyVs;
    enq_info[0].commit_type   = io_enq_req_0_bits_commitType;
    enq_info[0].is_rvc        = io_enq_req_0_bits_preDecodeInfo_isRVC;
    enq_info[0].is_vset       = io_enq_req_0_bits_isVset;
    enq_info[0].instr_size    = io_enq_req_0_bits_instrSize;
    enq_info[0].ftq_idx_value = io_enq_req_0_bits_ftqPtr_value;
    enq_info[0].ftq_idx_flag  = io_enq_req_0_bits_ftqPtr_flag;
    enq_info[0].ftq_offset    = io_enq_req_0_bits_ftqOffset;
    enq_info[0].itype         = io_enq_req_0_bits_traceBlockInPipe_itype;
    enq_info[0].iretire       = io_enq_req_0_bits_traceBlockInPipe_iretire;
    enq_info[0].ilastsize     = io_enq_req_0_bits_traceBlockInPipe_ilastsize;
    enq_info[0].need_flush    = io_enq_req_0_bits_hasException | io_enq_req_0_bits_flushPipe;
    enq_info[0].vls           = io_enq_req_0_bits_vlsInstr;
    enq_valid[1]         = io_enq_req_1_valid;
    enq_first_uop[1]     = io_enq_req_1_bits_firstUop;
    enq_need_write_rf[1] = enqNeedWriteRFSeq_1;
    enq_write_std[1]     = io_enq_req_1_bits_fuType[16];
    enq_block_backward[1]= io_enq_req_1_bits_blockBackward;
    enq_wait_forward[1]  = io_enq_req_1_bits_waitForward;
    enq_is_wfi[1]        = (io_enq_req_1_bits_fuType == 35'h2) & (io_enq_req_1_bits_fuOpType == 9'h22);
    enq_has_exception[1] = io_enq_req_1_bits_hasException;
    enq_trigger_dmode[1] = io_enq_req_1_bits_trigger == 4'h1;
    enq_allow_interrupt[1]= allow_interrupts_1;
    enq_num_wb[1]        = io_enq_req_1_bits_numWB;
    enq_robidx_value[1]  = io_enq_req_1_bits_robIdx_value;
    enq_info[1]          = '0;
    enq_info[1].rf_wen        = io_enq_req_1_bits_rfWen;
    enq_info[1].fp_wen        = io_enq_req_1_bits_dirtyFs;
    enq_info[1].wflags        = io_enq_req_1_bits_wfflags;
    enq_info[1].dirty_vs      = io_enq_req_1_bits_dirtyVs;
    enq_info[1].commit_type   = io_enq_req_1_bits_commitType;
    enq_info[1].is_rvc        = io_enq_req_1_bits_preDecodeInfo_isRVC;
    enq_info[1].is_vset       = io_enq_req_1_bits_isVset;
    enq_info[1].instr_size    = io_enq_req_1_bits_instrSize;
    enq_info[1].ftq_idx_value = io_enq_req_1_bits_ftqPtr_value;
    enq_info[1].ftq_idx_flag  = io_enq_req_1_bits_ftqPtr_flag;
    enq_info[1].ftq_offset    = io_enq_req_1_bits_ftqOffset;
    enq_info[1].itype         = io_enq_req_1_bits_traceBlockInPipe_itype;
    enq_info[1].iretire       = io_enq_req_1_bits_traceBlockInPipe_iretire;
    enq_info[1].ilastsize     = io_enq_req_1_bits_traceBlockInPipe_ilastsize;
    enq_info[1].need_flush    = io_enq_req_1_bits_hasException | io_enq_req_1_bits_flushPipe;
    enq_info[1].vls           = io_enq_req_1_bits_vlsInstr;
    enq_valid[2]         = io_enq_req_2_valid;
    enq_first_uop[2]     = io_enq_req_2_bits_firstUop;
    enq_need_write_rf[2] = enqNeedWriteRFSeq_2;
    enq_write_std[2]     = io_enq_req_2_bits_fuType[16];
    enq_block_backward[2]= io_enq_req_2_bits_blockBackward;
    enq_wait_forward[2]  = io_enq_req_2_bits_waitForward;
    enq_is_wfi[2]        = (io_enq_req_2_bits_fuType == 35'h2) & (io_enq_req_2_bits_fuOpType == 9'h22);
    enq_has_exception[2] = io_enq_req_2_bits_hasException;
    enq_trigger_dmode[2] = io_enq_req_2_bits_trigger == 4'h1;
    enq_allow_interrupt[2]= allow_interrupts_2;
    enq_num_wb[2]        = io_enq_req_2_bits_numWB;
    enq_robidx_value[2]  = io_enq_req_2_bits_robIdx_value;
    enq_info[2]          = '0;
    enq_info[2].rf_wen        = io_enq_req_2_bits_rfWen;
    enq_info[2].fp_wen        = io_enq_req_2_bits_dirtyFs;
    enq_info[2].wflags        = io_enq_req_2_bits_wfflags;
    enq_info[2].dirty_vs      = io_enq_req_2_bits_dirtyVs;
    enq_info[2].commit_type   = io_enq_req_2_bits_commitType;
    enq_info[2].is_rvc        = io_enq_req_2_bits_preDecodeInfo_isRVC;
    enq_info[2].is_vset       = io_enq_req_2_bits_isVset;
    enq_info[2].instr_size    = io_enq_req_2_bits_instrSize;
    enq_info[2].ftq_idx_value = io_enq_req_2_bits_ftqPtr_value;
    enq_info[2].ftq_idx_flag  = io_enq_req_2_bits_ftqPtr_flag;
    enq_info[2].ftq_offset    = io_enq_req_2_bits_ftqOffset;
    enq_info[2].itype         = io_enq_req_2_bits_traceBlockInPipe_itype;
    enq_info[2].iretire       = io_enq_req_2_bits_traceBlockInPipe_iretire;
    enq_info[2].ilastsize     = io_enq_req_2_bits_traceBlockInPipe_ilastsize;
    enq_info[2].need_flush    = io_enq_req_2_bits_hasException | io_enq_req_2_bits_flushPipe;
    enq_info[2].vls           = io_enq_req_2_bits_vlsInstr;
    enq_valid[3]         = io_enq_req_3_valid;
    enq_first_uop[3]     = io_enq_req_3_bits_firstUop;
    enq_need_write_rf[3] = enqNeedWriteRFSeq_3;
    enq_write_std[3]     = io_enq_req_3_bits_fuType[16];
    enq_block_backward[3]= io_enq_req_3_bits_blockBackward;
    enq_wait_forward[3]  = io_enq_req_3_bits_waitForward;
    enq_is_wfi[3]        = (io_enq_req_3_bits_fuType == 35'h2) & (io_enq_req_3_bits_fuOpType == 9'h22);
    enq_has_exception[3] = io_enq_req_3_bits_hasException;
    enq_trigger_dmode[3] = io_enq_req_3_bits_trigger == 4'h1;
    enq_allow_interrupt[3]= allow_interrupts_3;
    enq_num_wb[3]        = io_enq_req_3_bits_numWB;
    enq_robidx_value[3]  = io_enq_req_3_bits_robIdx_value;
    enq_info[3]          = '0;
    enq_info[3].rf_wen        = io_enq_req_3_bits_rfWen;
    enq_info[3].fp_wen        = io_enq_req_3_bits_dirtyFs;
    enq_info[3].wflags        = io_enq_req_3_bits_wfflags;
    enq_info[3].dirty_vs      = io_enq_req_3_bits_dirtyVs;
    enq_info[3].commit_type   = io_enq_req_3_bits_commitType;
    enq_info[3].is_rvc        = io_enq_req_3_bits_preDecodeInfo_isRVC;
    enq_info[3].is_vset       = io_enq_req_3_bits_isVset;
    enq_info[3].instr_size    = io_enq_req_3_bits_instrSize;
    enq_info[3].ftq_idx_value = io_enq_req_3_bits_ftqPtr_value;
    enq_info[3].ftq_idx_flag  = io_enq_req_3_bits_ftqPtr_flag;
    enq_info[3].ftq_offset    = io_enq_req_3_bits_ftqOffset;
    enq_info[3].itype         = io_enq_req_3_bits_traceBlockInPipe_itype;
    enq_info[3].iretire       = io_enq_req_3_bits_traceBlockInPipe_iretire;
    enq_info[3].ilastsize     = io_enq_req_3_bits_traceBlockInPipe_ilastsize;
    enq_info[3].need_flush    = io_enq_req_3_bits_hasException | io_enq_req_3_bits_flushPipe;
    enq_info[3].vls           = io_enq_req_3_bits_vlsInstr;
    enq_valid[4]         = io_enq_req_4_valid;
    enq_first_uop[4]     = io_enq_req_4_bits_firstUop;
    enq_need_write_rf[4] = enqNeedWriteRFSeq_4;
    enq_write_std[4]     = io_enq_req_4_bits_fuType[16];
    enq_block_backward[4]= io_enq_req_4_bits_blockBackward;
    enq_wait_forward[4]  = io_enq_req_4_bits_waitForward;
    enq_is_wfi[4]        = (io_enq_req_4_bits_fuType == 35'h2) & (io_enq_req_4_bits_fuOpType == 9'h22);
    enq_has_exception[4] = io_enq_req_4_bits_hasException;
    enq_trigger_dmode[4] = io_enq_req_4_bits_trigger == 4'h1;
    enq_allow_interrupt[4]= allow_interrupts_4;
    enq_num_wb[4]        = io_enq_req_4_bits_numWB;
    enq_robidx_value[4]  = io_enq_req_4_bits_robIdx_value;
    enq_info[4]          = '0;
    enq_info[4].rf_wen        = io_enq_req_4_bits_rfWen;
    enq_info[4].fp_wen        = io_enq_req_4_bits_dirtyFs;
    enq_info[4].wflags        = io_enq_req_4_bits_wfflags;
    enq_info[4].dirty_vs      = io_enq_req_4_bits_dirtyVs;
    enq_info[4].commit_type   = io_enq_req_4_bits_commitType;
    enq_info[4].is_rvc        = io_enq_req_4_bits_preDecodeInfo_isRVC;
    enq_info[4].is_vset       = io_enq_req_4_bits_isVset;
    enq_info[4].instr_size    = io_enq_req_4_bits_instrSize;
    enq_info[4].ftq_idx_value = io_enq_req_4_bits_ftqPtr_value;
    enq_info[4].ftq_idx_flag  = io_enq_req_4_bits_ftqPtr_flag;
    enq_info[4].ftq_offset    = io_enq_req_4_bits_ftqOffset;
    enq_info[4].itype         = io_enq_req_4_bits_traceBlockInPipe_itype;
    enq_info[4].iretire       = io_enq_req_4_bits_traceBlockInPipe_iretire;
    enq_info[4].ilastsize     = io_enq_req_4_bits_traceBlockInPipe_ilastsize;
    enq_info[4].need_flush    = io_enq_req_4_bits_hasException | io_enq_req_4_bits_flushPipe;
    enq_info[4].vls           = io_enq_req_4_bits_vlsInstr;
    enq_valid[5]         = io_enq_req_5_valid;
    enq_first_uop[5]     = io_enq_req_5_bits_firstUop;
    enq_need_write_rf[5] = enqNeedWriteRFSeq_5;
    enq_write_std[5]     = io_enq_req_5_bits_fuType[16];
    enq_block_backward[5]= io_enq_req_5_bits_blockBackward;
    enq_wait_forward[5]  = io_enq_req_5_bits_waitForward;
    enq_is_wfi[5]        = (io_enq_req_5_bits_fuType == 35'h2) & (io_enq_req_5_bits_fuOpType == 9'h22);
    enq_has_exception[5] = io_enq_req_5_bits_hasException;
    enq_trigger_dmode[5] = io_enq_req_5_bits_trigger == 4'h1;
    enq_allow_interrupt[5]= allow_interrupts_5;
    enq_num_wb[5]        = io_enq_req_5_bits_numWB;
    enq_robidx_value[5]  = io_enq_req_5_bits_robIdx_value;
    enq_info[5]          = '0;
    enq_info[5].rf_wen        = io_enq_req_5_bits_rfWen;
    enq_info[5].fp_wen        = io_enq_req_5_bits_dirtyFs;
    enq_info[5].wflags        = io_enq_req_5_bits_wfflags;
    enq_info[5].dirty_vs      = io_enq_req_5_bits_dirtyVs;
    enq_info[5].commit_type   = io_enq_req_5_bits_commitType;
    enq_info[5].is_rvc        = io_enq_req_5_bits_preDecodeInfo_isRVC;
    enq_info[5].is_vset       = io_enq_req_5_bits_isVset;
    enq_info[5].instr_size    = io_enq_req_5_bits_instrSize;
    enq_info[5].ftq_idx_value = io_enq_req_5_bits_ftqPtr_value;
    enq_info[5].ftq_idx_flag  = io_enq_req_5_bits_ftqPtr_flag;
    enq_info[5].ftq_offset    = io_enq_req_5_bits_ftqOffset;
    enq_info[5].itype         = io_enq_req_5_bits_traceBlockInPipe_itype;
    enq_info[5].iretire       = io_enq_req_5_bits_traceBlockInPipe_iretire;
    enq_info[5].ilastsize     = io_enq_req_5_bits_traceBlockInPipe_ilastsize;
    enq_info[5].need_flush    = io_enq_req_5_bits_hasException | io_enq_req_5_bits_flushPipe;
    enq_info[5].vls           = io_enq_req_5_bits_vlsInstr;
  end

  // ---- writeback 翻译: exuWriteback(uopNum 递减 / std / fflags / vxsat / branch) ----
  logic [NUM_EXU_WB-1:0] wb_valid; logic [PTR_W-1:0] wb_robidx [NUM_EXU_WB];
  logic [4:0] wb_num [NUM_EXU_WB]; logic [NUM_EXU_WB-1:0] wb_is_std;
  logic [NUM_EXU_WB-1:0] wb_fflags_valid; logic [4:0] wb_fflags [NUM_EXU_WB];
  logic [NUM_EXU_WB-1:0] wb_vxsat_valid, wb_vxsat, wb_branch_taken;
  logic [NUM_WB-1:0] excp_wb_valid; logic [PTR_W-1:0] excp_wb_robidx [NUM_WB];
  logic [NUM_WB-1:0] excp_wb_need_flush;
  always_comb begin
    wb_valid[0]  = io_exuWriteback_0_valid;
    wb_robidx[0] = io_exuWriteback_0_bits_robIdx_value;
    wb_num[0]    = io_writebackNums_0_bits;
    wb_is_std[0] = 1'b0;
    wb_fflags_valid[0] = 1'b0;
    wb_fflags[0]       = 5'h0;
    wb_vxsat_valid[0] = 1'b0;
    wb_vxsat[0]       = 1'b0;
    wb_branch_taken[0] = 1'b0;
    wb_valid[1]  = io_exuWriteback_1_valid;
    wb_robidx[1] = io_exuWriteback_1_bits_robIdx_value;
    wb_num[1]    = io_writebackNums_1_bits;
    wb_is_std[1] = 1'b0;
    wb_fflags_valid[1] = 1'b0;
    wb_fflags[1]       = 5'h0;
    wb_vxsat_valid[1] = 1'b0;
    wb_vxsat[1]       = 1'b0;
    wb_branch_taken[1] = io_exuWriteback_1_bits_redirect_bits_cfiUpdate_taken;
    wb_valid[2]  = io_exuWriteback_2_valid;
    wb_robidx[2] = io_exuWriteback_2_bits_robIdx_value;
    wb_num[2]    = io_writebackNums_2_bits;
    wb_is_std[2] = 1'b0;
    wb_fflags_valid[2] = 1'b0;
    wb_fflags[2]       = 5'h0;
    wb_vxsat_valid[2] = 1'b0;
    wb_vxsat[2]       = 1'b0;
    wb_branch_taken[2] = 1'b0;
    wb_valid[3]  = io_exuWriteback_3_valid;
    wb_robidx[3] = io_exuWriteback_3_bits_robIdx_value;
    wb_num[3]    = io_writebackNums_3_bits;
    wb_is_std[3] = 1'b0;
    wb_fflags_valid[3] = 1'b0;
    wb_fflags[3]       = 5'h0;
    wb_vxsat_valid[3] = 1'b0;
    wb_vxsat[3]       = 1'b0;
    wb_branch_taken[3] = io_exuWriteback_3_bits_redirect_bits_cfiUpdate_taken;
    wb_valid[4]  = io_exuWriteback_4_valid;
    wb_robidx[4] = io_exuWriteback_4_bits_robIdx_value;
    wb_num[4]    = io_writebackNums_4_bits;
    wb_is_std[4] = 1'b0;
    wb_fflags_valid[4] = 1'b0;
    wb_fflags[4]       = 5'h0;
    wb_vxsat_valid[4] = 1'b0;
    wb_vxsat[4]       = 1'b0;
    wb_branch_taken[4] = 1'b0;
    wb_valid[5]  = io_exuWriteback_5_valid;
    wb_robidx[5] = io_exuWriteback_5_bits_robIdx_value;
    wb_num[5]    = io_writebackNums_5_bits;
    wb_is_std[5] = 1'b0;
    wb_fflags_valid[5] = io_exuWriteback_5_bits_wflags;
    wb_fflags[5]       = io_exuWriteback_5_bits_fflags;
    wb_vxsat_valid[5] = 1'b0;
    wb_vxsat[5]       = 1'b0;
    wb_branch_taken[5] = io_exuWriteback_5_bits_redirect_bits_cfiUpdate_taken;
    wb_valid[6]  = io_exuWriteback_6_valid;
    wb_robidx[6] = io_exuWriteback_6_bits_robIdx_value;
    wb_num[6]    = io_writebackNums_6_bits;
    wb_is_std[6] = 1'b0;
    wb_fflags_valid[6] = 1'b0;
    wb_fflags[6]       = 5'h0;
    wb_vxsat_valid[6] = 1'b0;
    wb_vxsat[6]       = 1'b0;
    wb_branch_taken[6] = 1'b0;
    wb_valid[7]  = io_exuWriteback_7_valid;
    wb_robidx[7] = io_exuWriteback_7_bits_robIdx_value;
    wb_num[7]    = io_writebackNums_7_bits;
    wb_is_std[7] = 1'b0;
    wb_fflags_valid[7] = 1'b0;
    wb_fflags[7]       = 5'h0;
    wb_vxsat_valid[7] = 1'b0;
    wb_vxsat[7]       = 1'b0;
    wb_branch_taken[7] = 1'b0;
    wb_valid[8]  = io_exuWriteback_8_valid;
    wb_robidx[8] = io_exuWriteback_8_bits_robIdx_value;
    wb_num[8]    = io_writebackNums_8_bits;
    wb_is_std[8] = 1'b0;
    wb_fflags_valid[8] = io_exuWriteback_8_bits_wflags;
    wb_fflags[8]       = io_exuWriteback_8_bits_fflags;
    wb_vxsat_valid[8] = 1'b0;
    wb_vxsat[8]       = 1'b0;
    wb_branch_taken[8] = 1'b0;
    wb_valid[9]  = io_exuWriteback_9_valid;
    wb_robidx[9] = io_exuWriteback_9_bits_robIdx_value;
    wb_num[9]    = io_writebackNums_9_bits;
    wb_is_std[9] = 1'b0;
    wb_fflags_valid[9] = io_exuWriteback_9_bits_wflags;
    wb_fflags[9]       = io_exuWriteback_9_bits_fflags;
    wb_vxsat_valid[9] = 1'b0;
    wb_vxsat[9]       = 1'b0;
    wb_branch_taken[9] = 1'b0;
    wb_valid[10]  = io_exuWriteback_10_valid;
    wb_robidx[10] = io_exuWriteback_10_bits_robIdx_value;
    wb_num[10]    = io_writebackNums_10_bits;
    wb_is_std[10] = 1'b0;
    wb_fflags_valid[10] = io_exuWriteback_10_bits_wflags;
    wb_fflags[10]       = io_exuWriteback_10_bits_fflags;
    wb_vxsat_valid[10] = 1'b0;
    wb_vxsat[10]       = 1'b0;
    wb_branch_taken[10] = 1'b0;
    wb_valid[11]  = io_exuWriteback_11_valid;
    wb_robidx[11] = io_exuWriteback_11_bits_robIdx_value;
    wb_num[11]    = io_writebackNums_11_bits;
    wb_is_std[11] = 1'b0;
    wb_fflags_valid[11] = io_exuWriteback_11_bits_wflags;
    wb_fflags[11]       = io_exuWriteback_11_bits_fflags;
    wb_vxsat_valid[11] = 1'b0;
    wb_vxsat[11]       = 1'b0;
    wb_branch_taken[11] = 1'b0;
    wb_valid[12]  = io_exuWriteback_12_valid;
    wb_robidx[12] = io_exuWriteback_12_bits_robIdx_value;
    wb_num[12]    = io_writebackNums_12_bits;
    wb_is_std[12] = 1'b0;
    wb_fflags_valid[12] = io_exuWriteback_12_bits_wflags;
    wb_fflags[12]       = io_exuWriteback_12_bits_fflags;
    wb_vxsat_valid[12] = 1'b0;
    wb_vxsat[12]       = 1'b0;
    wb_branch_taken[12] = 1'b0;
    wb_valid[13]  = io_exuWriteback_13_valid;
    wb_robidx[13] = io_exuWriteback_13_bits_robIdx_value;
    wb_num[13]    = io_writebackNums_13_bits;
    wb_is_std[13] = 1'b0;
    wb_fflags_valid[13] = io_exuWriteback_13_bits_wflags;
    wb_fflags[13]       = io_exuWriteback_13_bits_fflags;
    wb_vxsat_valid[13] = io_exuWriteback_13_bits_vxsat;
    wb_vxsat[13]       = io_exuWriteback_13_bits_vxsat;
    wb_branch_taken[13] = 1'b0;
    wb_valid[14]  = io_exuWriteback_14_valid;
    wb_robidx[14] = io_exuWriteback_14_bits_robIdx_value;
    wb_num[14]    = io_writebackNums_14_bits;
    wb_is_std[14] = 1'b0;
    wb_fflags_valid[14] = io_exuWriteback_14_bits_wflags;
    wb_fflags[14]       = io_exuWriteback_14_bits_fflags;
    wb_vxsat_valid[14] = 1'b0;
    wb_vxsat[14]       = 1'b0;
    wb_branch_taken[14] = 1'b0;
    wb_valid[15]  = io_exuWriteback_15_valid;
    wb_robidx[15] = io_exuWriteback_15_bits_robIdx_value;
    wb_num[15]    = io_writebackNums_15_bits;
    wb_is_std[15] = 1'b0;
    wb_fflags_valid[15] = io_exuWriteback_15_bits_wflags;
    wb_fflags[15]       = io_exuWriteback_15_bits_fflags;
    wb_vxsat_valid[15] = io_exuWriteback_15_bits_vxsat;
    wb_vxsat[15]       = io_exuWriteback_15_bits_vxsat;
    wb_branch_taken[15] = 1'b0;
    wb_valid[16]  = io_exuWriteback_16_valid;
    wb_robidx[16] = io_exuWriteback_16_bits_robIdx_value;
    wb_num[16]    = io_writebackNums_16_bits;
    wb_is_std[16] = 1'b0;
    wb_fflags_valid[16] = io_exuWriteback_16_bits_wflags;
    wb_fflags[16]       = io_exuWriteback_16_bits_fflags;
    wb_vxsat_valid[16] = 1'b0;
    wb_vxsat[16]       = 1'b0;
    wb_branch_taken[16] = 1'b0;
    wb_valid[17]  = io_exuWriteback_17_valid;
    wb_robidx[17] = io_exuWriteback_17_bits_robIdx_value;
    wb_num[17]    = io_writebackNums_17_bits;
    wb_is_std[17] = 1'b0;
    wb_fflags_valid[17] = io_exuWriteback_17_bits_wflags;
    wb_fflags[17]       = io_exuWriteback_17_bits_fflags;
    wb_vxsat_valid[17] = 1'b0;
    wb_vxsat[17]       = 1'b0;
    wb_branch_taken[17] = 1'b0;
    wb_valid[18]  = io_exuWriteback_18_valid;
    wb_robidx[18] = io_exuWriteback_18_bits_robIdx_value;
    wb_num[18]    = io_writebackNums_18_bits;
    wb_is_std[18] = 1'b0;
    wb_fflags_valid[18] = 1'b0;
    wb_fflags[18]       = 5'h0;
    wb_vxsat_valid[18] = 1'b0;
    wb_vxsat[18]       = 1'b0;
    wb_branch_taken[18] = 1'b0;
    wb_valid[19]  = io_exuWriteback_19_valid;
    wb_robidx[19] = io_exuWriteback_19_bits_robIdx_value;
    wb_num[19]    = io_writebackNums_19_bits;
    wb_is_std[19] = 1'b0;
    wb_fflags_valid[19] = 1'b0;
    wb_fflags[19]       = 5'h0;
    wb_vxsat_valid[19] = 1'b0;
    wb_vxsat[19]       = 1'b0;
    wb_branch_taken[19] = 1'b0;
    wb_valid[20]  = io_exuWriteback_20_valid;
    wb_robidx[20] = io_exuWriteback_20_bits_robIdx_value;
    wb_num[20]    = io_writebackNums_20_bits;
    wb_is_std[20] = 1'b0;
    wb_fflags_valid[20] = 1'b0;
    wb_fflags[20]       = 5'h0;
    wb_vxsat_valid[20] = 1'b0;
    wb_vxsat[20]       = 1'b0;
    wb_branch_taken[20] = 1'b0;
    wb_valid[21]  = io_exuWriteback_21_valid;
    wb_robidx[21] = io_exuWriteback_21_bits_robIdx_value;
    wb_num[21]    = io_writebackNums_21_bits;
    wb_is_std[21] = 1'b0;
    wb_fflags_valid[21] = 1'b0;
    wb_fflags[21]       = 5'h0;
    wb_vxsat_valid[21] = 1'b0;
    wb_vxsat[21]       = 1'b0;
    wb_branch_taken[21] = 1'b0;
    wb_valid[22]  = io_exuWriteback_22_valid;
    wb_robidx[22] = io_exuWriteback_22_bits_robIdx_value;
    wb_num[22]    = io_writebackNums_22_bits;
    wb_is_std[22] = 1'b0;
    wb_fflags_valid[22] = 1'b0;
    wb_fflags[22]       = 5'h0;
    wb_vxsat_valid[22] = 1'b0;
    wb_vxsat[22]       = 1'b0;
    wb_branch_taken[22] = 1'b0;
    wb_valid[23]  = io_exuWriteback_23_valid;
    wb_robidx[23] = io_exuWriteback_23_bits_robIdx_value;
    wb_num[23]    = io_writebackNums_23_bits;
    wb_is_std[23] = 1'b0;
    wb_fflags_valid[23] = 1'b0;
    wb_fflags[23]       = 5'h0;
    wb_vxsat_valid[23] = 1'b0;
    wb_vxsat[23]       = 1'b0;
    wb_branch_taken[23] = 1'b0;
    wb_valid[24]  = io_exuWriteback_24_valid;
    wb_robidx[24] = io_exuWriteback_24_bits_robIdx_value;
    wb_num[24]    = io_writebackNums_24_bits;
    wb_is_std[24] = 1'b0;
    wb_fflags_valid[24] = 1'b0;
    wb_fflags[24]       = 5'h0;
    wb_vxsat_valid[24] = 1'b0;
    wb_vxsat[24]       = 1'b0;
    wb_branch_taken[24] = 1'b0;
    wb_valid[25]  = io_exuWriteback_25_valid;
    wb_robidx[25] = io_exuWriteback_25_bits_robIdx_value;
    wb_num[25]    = 5'h0;
    wb_is_std[25] = 1'b1;
    wb_fflags_valid[25] = 1'b0;
    wb_fflags[25]       = 5'h0;
    wb_vxsat_valid[25] = 1'b0;
    wb_vxsat[25]       = 1'b0;
    wb_branch_taken[25] = 1'b0;
    wb_valid[26]  = io_exuWriteback_26_valid;
    wb_robidx[26] = io_exuWriteback_26_bits_robIdx_value;
    wb_num[26]    = 5'h0;
    wb_is_std[26] = 1'b1;
    wb_fflags_valid[26] = 1'b0;
    wb_fflags[26]       = 5'h0;
    wb_vxsat_valid[26] = 1'b0;
    wb_vxsat[26]       = 1'b0;
    wb_branch_taken[26] = 1'b0;
    // excp_wb: 默认全 0, 仅 golden needFlush 路径映射的端口有效
    for (int k=0;k<NUM_WB;k++) begin excp_wb_valid[k]=1'b0; excp_wb_robidx[k]=8'h0; excp_wb_need_flush[k]=1'b0; end
    excp_wb_valid[0]      = io_writeback_7_valid;
    excp_wb_robidx[0]     = io_writeback_7_bits_robIdx_value;
    excp_wb_need_flush[0] = io_writebackNeedFlush_0;
    excp_wb_valid[1]      = io_writeback_13_valid;
    excp_wb_robidx[1]     = io_writeback_13_bits_robIdx_value;
    excp_wb_need_flush[1] = io_writebackNeedFlush_1;
    excp_wb_valid[2]      = io_writeback_14_valid;
    excp_wb_robidx[2]     = io_writeback_14_bits_robIdx_value;
    excp_wb_need_flush[2] = io_writebackNeedFlush_2;
    excp_wb_valid[6]      = io_writeback_18_valid;
    excp_wb_robidx[6]     = io_writeback_18_bits_robIdx_value;
    excp_wb_need_flush[6] = io_writebackNeedFlush_6;
    excp_wb_valid[7]      = io_writeback_19_valid;
    excp_wb_robidx[7]     = io_writeback_19_bits_robIdx_value;
    excp_wb_need_flush[7] = io_writebackNeedFlush_7;
    excp_wb_valid[8]      = io_writeback_20_valid;
    excp_wb_robidx[8]     = io_writeback_20_bits_robIdx_value;
    excp_wb_need_flush[8] = io_writebackNeedFlush_8;
    excp_wb_valid[9]      = io_writeback_21_valid;
    excp_wb_robidx[9]     = io_writeback_21_bits_robIdx_value;
    excp_wb_need_flush[9] = io_writebackNeedFlush_9;
    excp_wb_valid[10]      = io_writeback_22_valid;
    excp_wb_robidx[10]     = io_writeback_22_bits_robIdx_value;
    excp_wb_need_flush[10] = io_writebackNeedFlush_10;
    excp_wb_valid[11]      = io_writeback_23_valid;
    excp_wb_robidx[11]     = io_writeback_23_bits_robIdx_value;
    excp_wb_need_flush[11] = io_writebackNeedFlush_11;
    excp_wb_valid[12]      = io_writeback_24_valid;
    excp_wb_robidx[12]     = io_writeback_24_bits_robIdx_value;
    excp_wb_need_flush[12] = io_writebackNeedFlush_12;
  end

  // ---- redirect / csr / wfi / misc ----
  // 这些核输入与 golden input 同名(io_redirect_*/io_csr_*/io_wfi_*/io_snpt_useSnpt/
  // io_fromVecExcpMod_busy/io_trace_blockCommit): 由顶部 golden 驱动 reg 直接经 .* 绑定,
  // 不再重复声明/赋值(同一根网络, 既喂 u_g 也喂 u_i, 保证同激励)。
  // io_misPredWb 是核独有端口(golden 内部聚合), 单独构造:
  logic io_misPredWb;
  // misPredWb: golden redirectWBs 聚合 = OR(io_writeback_{1,3,5,7} cfiUpdate.isMisPred & redirect.valid & valid)
  assign io_misPredWb =
      (io_writeback_1_bits_redirect_bits_cfiUpdate_isMisPred & io_writeback_1_bits_redirect_valid & io_writeback_1_valid)
    | (io_writeback_3_bits_redirect_bits_cfiUpdate_isMisPred & io_writeback_3_bits_redirect_valid & io_writeback_3_valid)
    | (io_writeback_5_bits_redirect_bits_cfiUpdate_isMisPred & io_writeback_5_bits_redirect_valid & io_writeback_5_valid)
    | (io_writeback_7_bits_redirect_bits_cfiUpdate_isMisPred & io_writeback_7_bits_redirect_valid & io_writeback_7_valid);

  // io_wb{1,3,5}_redir 是核独有端口(perf io_perf_16 的 misPred_probe 源), 由 golden exuWriteback tap 重建:
  logic io_wb1_redir, io_wb3_redir, io_wb5_redir;
  assign io_wb1_redir = io_exuWriteback_1_valid & io_exuWriteback_1_bits_redirect_valid;
  assign io_wb3_redir = io_exuWriteback_3_valid & io_exuWriteback_3_bits_redirect_valid;
  assign io_wb5_redir = io_exuWriteback_5_valid & io_exuWriteback_5_bits_redirect_valid;

  // ===================================================================
  // [csr/debug 组] C_DEEP csr(9)+debug(6) 端口的输入 tap + 输出线 (owner rob-csr-debug)
  //   与 u_i(.*) 同名绑定; 输入从 golden 内部/激励 tap, 输出与 golden io_* 比对。
  // ===================================================================
  logic        io_eg_vstartEn;  logic [63:0] io_eg_vstart;
  assign io_eg_vstartEn = _exceptionGen_io_state_bits_vstartEn;
  assign io_eg_vstart   = _exceptionGen_io_state_bits_vstart;
  // io_vstartIsZero / io_debugHeadLsIssue 已由顶部 golden 驱动 reg 同名 .* 绑定。
  logic [34:0] enq_fuType [RENAME_WIDTH];
  assign enq_fuType[0]=io_enq_req_0_bits_fuType; assign enq_fuType[1]=io_enq_req_1_bits_fuType;
  assign enq_fuType[2]=io_enq_req_2_bits_fuType; assign enq_fuType[3]=io_enq_req_3_bits_fuType;
  assign enq_fuType[4]=io_enq_req_4_bits_fuType; assign enq_fuType[5]=io_enq_req_5_bits_fuType;
  logic [PTR_W-1:0] io_lsTopdown_s1_robIdx [3]; logic [2:0] io_lsTopdown_s1_valid; logic [49:0] io_lsTopdown_s1_bits [3];
  logic [PTR_W-1:0] io_lsTopdown_s2_robIdx [3]; logic [2:0] io_lsTopdown_s2_valid; logic [47:0] io_lsTopdown_s2_bits [3];
  assign io_lsTopdown_s1_robIdx[0]=io_lsTopdownInfo_0_s1_robIdx; assign io_lsTopdown_s1_robIdx[1]=io_lsTopdownInfo_1_s1_robIdx; assign io_lsTopdown_s1_robIdx[2]=io_lsTopdownInfo_2_s1_robIdx;
  assign io_lsTopdown_s1_valid={io_lsTopdownInfo_2_s1_vaddr_valid,io_lsTopdownInfo_1_s1_vaddr_valid,io_lsTopdownInfo_0_s1_vaddr_valid};
  assign io_lsTopdown_s1_bits[0]=io_lsTopdownInfo_0_s1_vaddr_bits; assign io_lsTopdown_s1_bits[1]=io_lsTopdownInfo_1_s1_vaddr_bits; assign io_lsTopdown_s1_bits[2]=io_lsTopdownInfo_2_s1_vaddr_bits;
  assign io_lsTopdown_s2_robIdx[0]=io_lsTopdownInfo_0_s2_robIdx; assign io_lsTopdown_s2_robIdx[1]=io_lsTopdownInfo_1_s2_robIdx; assign io_lsTopdown_s2_robIdx[2]=io_lsTopdownInfo_2_s2_robIdx;
  assign io_lsTopdown_s2_valid={io_lsTopdownInfo_2_s2_paddr_valid,io_lsTopdownInfo_1_s2_paddr_valid,io_lsTopdownInfo_0_s2_paddr_valid};
  assign io_lsTopdown_s2_bits[0]=io_lsTopdownInfo_0_s2_paddr_bits; assign io_lsTopdown_s2_bits[1]=io_lsTopdownInfo_1_s2_paddr_bits; assign io_lsTopdown_s2_bits[2]=io_lsTopdownInfo_2_s2_paddr_bits;

  // ---- u_i 输出 ----
  // toVecExcpMod.excpInfo(10 口)
  // perf(18)/trace(48) 核输出(在 tb_perftrace.sv 中做 cycle-exact 比对; 此 tap tb 仅悬空占位供 .* 绑定)
  // lsq deep(4)核输出(在 tb_lsq_deep.sv 中做 cycle-exact 比对; 此 tap tb 悬空占位)
  // wrapper B_SHALLOW latch 门控用核输出(悬空占位)

  xs_Rob_core u_core (.*);
