// 自动生成：scripts/gen_fastarbiter.py —— 勿手改
module FastArbiter_30_xs(
  input io_in_0_valid,
  input [3:0] io_in_0_bits_qos,
  input [10:0] io_in_0_bits_tgtID,
  input [10:0] io_in_0_bits_srcID,
  input [11:0] io_in_0_bits_txnID,
  input [10:0] io_in_0_bits_returnNID,
  input io_in_0_bits_stashNIDValid,
  input [11:0] io_in_0_bits_returnTxnID,
  input [6:0] io_in_0_bits_opcode,
  input [2:0] io_in_0_bits_size,
  input [47:0] io_in_0_bits_addr,
  input io_in_0_bits_ns,
  input io_in_0_bits_likelyshared,
  input io_in_0_bits_allowRetry,
  input [1:0] io_in_0_bits_order,
  input [3:0] io_in_0_bits_pCrdType,
  input io_in_0_bits_memAttr_allocate,
  input io_in_0_bits_memAttr_cacheable,
  input io_in_0_bits_memAttr_device,
  input io_in_0_bits_memAttr_ewa,
  input io_in_0_bits_snpAttr,
  input [7:0] io_in_0_bits_lpIDWithPadding,
  input io_in_0_bits_snoopMe,
  input io_in_0_bits_expCompAck,
  input [1:0] io_in_0_bits_tagOp,
  input io_in_0_bits_traceTag,
  input io_in_0_bits_mpam_perfMonGroup,
  input [8:0] io_in_0_bits_mpam_partID,
  input io_in_0_bits_mpam_mpamNS,
  input [3:0] io_in_0_bits_rsvdc,
  output io_out_valid,
  output [3:0] io_out_bits_qos,
  output [10:0] io_out_bits_tgtID,
  output [10:0] io_out_bits_srcID,
  output [11:0] io_out_bits_txnID,
  output [10:0] io_out_bits_returnNID,
  output io_out_bits_stashNIDValid,
  output [11:0] io_out_bits_returnTxnID,
  output [6:0] io_out_bits_opcode,
  output [2:0] io_out_bits_size,
  output [47:0] io_out_bits_addr,
  output io_out_bits_ns,
  output io_out_bits_likelyshared,
  output io_out_bits_allowRetry,
  output [1:0] io_out_bits_order,
  output [3:0] io_out_bits_pCrdType,
  output io_out_bits_memAttr_allocate,
  output io_out_bits_memAttr_cacheable,
  output io_out_bits_memAttr_device,
  output io_out_bits_memAttr_ewa,
  output io_out_bits_snpAttr,
  output [7:0] io_out_bits_lpIDWithPadding,
  output io_out_bits_snoopMe,
  output io_out_bits_expCompAck,
  output [1:0] io_out_bits_tagOp,
  output io_out_bits_traceTag,
  output io_out_bits_mpam_perfMonGroup,
  output [8:0] io_out_bits_mpam_partID,
  output io_out_bits_mpam_mpamNS,
  output [3:0] io_out_bits_rsvdc
);
  xs_FastArbiter_30_core u_core (
    .io_in_0_valid(io_in_0_valid),
    .io_in_0_bits_qos(io_in_0_bits_qos),
    .io_in_0_bits_tgtID(io_in_0_bits_tgtID),
    .io_in_0_bits_srcID(io_in_0_bits_srcID),
    .io_in_0_bits_txnID(io_in_0_bits_txnID),
    .io_in_0_bits_returnNID(io_in_0_bits_returnNID),
    .io_in_0_bits_stashNIDValid(io_in_0_bits_stashNIDValid),
    .io_in_0_bits_returnTxnID(io_in_0_bits_returnTxnID),
    .io_in_0_bits_opcode(io_in_0_bits_opcode),
    .io_in_0_bits_size(io_in_0_bits_size),
    .io_in_0_bits_addr(io_in_0_bits_addr),
    .io_in_0_bits_ns(io_in_0_bits_ns),
    .io_in_0_bits_likelyshared(io_in_0_bits_likelyshared),
    .io_in_0_bits_allowRetry(io_in_0_bits_allowRetry),
    .io_in_0_bits_order(io_in_0_bits_order),
    .io_in_0_bits_pCrdType(io_in_0_bits_pCrdType),
    .io_in_0_bits_memAttr_allocate(io_in_0_bits_memAttr_allocate),
    .io_in_0_bits_memAttr_cacheable(io_in_0_bits_memAttr_cacheable),
    .io_in_0_bits_memAttr_device(io_in_0_bits_memAttr_device),
    .io_in_0_bits_memAttr_ewa(io_in_0_bits_memAttr_ewa),
    .io_in_0_bits_snpAttr(io_in_0_bits_snpAttr),
    .io_in_0_bits_lpIDWithPadding(io_in_0_bits_lpIDWithPadding),
    .io_in_0_bits_snoopMe(io_in_0_bits_snoopMe),
    .io_in_0_bits_expCompAck(io_in_0_bits_expCompAck),
    .io_in_0_bits_tagOp(io_in_0_bits_tagOp),
    .io_in_0_bits_traceTag(io_in_0_bits_traceTag),
    .io_in_0_bits_mpam_perfMonGroup(io_in_0_bits_mpam_perfMonGroup),
    .io_in_0_bits_mpam_partID(io_in_0_bits_mpam_partID),
    .io_in_0_bits_mpam_mpamNS(io_in_0_bits_mpam_mpamNS),
    .io_in_0_bits_rsvdc(io_in_0_bits_rsvdc),
    .io_out_valid(io_out_valid),
    .io_out_bits_qos(io_out_bits_qos),
    .io_out_bits_tgtID(io_out_bits_tgtID),
    .io_out_bits_srcID(io_out_bits_srcID),
    .io_out_bits_txnID(io_out_bits_txnID),
    .io_out_bits_returnNID(io_out_bits_returnNID),
    .io_out_bits_stashNIDValid(io_out_bits_stashNIDValid),
    .io_out_bits_returnTxnID(io_out_bits_returnTxnID),
    .io_out_bits_opcode(io_out_bits_opcode),
    .io_out_bits_size(io_out_bits_size),
    .io_out_bits_addr(io_out_bits_addr),
    .io_out_bits_ns(io_out_bits_ns),
    .io_out_bits_likelyshared(io_out_bits_likelyshared),
    .io_out_bits_allowRetry(io_out_bits_allowRetry),
    .io_out_bits_order(io_out_bits_order),
    .io_out_bits_pCrdType(io_out_bits_pCrdType),
    .io_out_bits_memAttr_allocate(io_out_bits_memAttr_allocate),
    .io_out_bits_memAttr_cacheable(io_out_bits_memAttr_cacheable),
    .io_out_bits_memAttr_device(io_out_bits_memAttr_device),
    .io_out_bits_memAttr_ewa(io_out_bits_memAttr_ewa),
    .io_out_bits_snpAttr(io_out_bits_snpAttr),
    .io_out_bits_lpIDWithPadding(io_out_bits_lpIDWithPadding),
    .io_out_bits_snoopMe(io_out_bits_snoopMe),
    .io_out_bits_expCompAck(io_out_bits_expCompAck),
    .io_out_bits_tagOp(io_out_bits_tagOp),
    .io_out_bits_traceTag(io_out_bits_traceTag),
    .io_out_bits_mpam_perfMonGroup(io_out_bits_mpam_perfMonGroup),
    .io_out_bits_mpam_partID(io_out_bits_mpam_partID),
    .io_out_bits_mpam_mpamNS(io_out_bits_mpam_mpamNS),
    .io_out_bits_rsvdc(io_out_bits_rsvdc)
  );
endmodule
