// 自动生成：scripts/gen_fastarbiter77.py —— 勿手改
module FastArbiter_77(
  input clock,
  input reset,
  input io_in_0_valid,
  input [3:0] io_in_0_bits_qos,
  input [10:0] io_in_0_bits_srcID,
  input [11:0] io_in_0_bits_txnID,
  input [10:0] io_in_0_bits_fwdNID,
  input [11:0] io_in_0_bits_fwdTxnID,
  input [4:0] io_in_0_bits_opcode,
  input [44:0] io_in_0_bits_addr,
  input io_in_0_bits_ns,
  input io_in_0_bits_doNotGoToSD,
  input io_in_0_bits_retToSrc,
  input io_in_0_bits_traceTag,
  input io_in_0_bits_mpam_perfMonGroup,
  input [8:0] io_in_0_bits_mpam_partID,
  input io_in_0_bits_mpam_mpamNS,
  input io_in_1_valid,
  input [3:0] io_in_1_bits_qos,
  input [10:0] io_in_1_bits_srcID,
  input [11:0] io_in_1_bits_txnID,
  input [10:0] io_in_1_bits_fwdNID,
  input [11:0] io_in_1_bits_fwdTxnID,
  input [4:0] io_in_1_bits_opcode,
  input [44:0] io_in_1_bits_addr,
  input io_in_1_bits_ns,
  input io_in_1_bits_doNotGoToSD,
  input io_in_1_bits_retToSrc,
  input io_in_1_bits_traceTag,
  input io_in_1_bits_mpam_perfMonGroup,
  input [8:0] io_in_1_bits_mpam_partID,
  input io_in_1_bits_mpam_mpamNS,
  input io_out_ready,
  output io_out_valid,
  output [3:0] io_out_bits_qos,
  output [10:0] io_out_bits_srcID,
  output [11:0] io_out_bits_txnID,
  output [10:0] io_out_bits_fwdNID,
  output [11:0] io_out_bits_fwdTxnID,
  output [4:0] io_out_bits_opcode,
  output [44:0] io_out_bits_addr,
  output io_out_bits_ns,
  output io_out_bits_doNotGoToSD,
  output io_out_bits_retToSrc,
  output io_out_bits_traceTag,
  output io_out_bits_mpam_perfMonGroup,
  output [8:0] io_out_bits_mpam_partID,
  output io_out_bits_mpam_mpamNS,
  output io_chosen
);
  xs_FastArbiter_77_core u_core (
    .clock(clock),
    .reset(reset),
    .io_in_0_valid(io_in_0_valid),
    .io_in_0_bits_qos(io_in_0_bits_qos),
    .io_in_0_bits_srcID(io_in_0_bits_srcID),
    .io_in_0_bits_txnID(io_in_0_bits_txnID),
    .io_in_0_bits_fwdNID(io_in_0_bits_fwdNID),
    .io_in_0_bits_fwdTxnID(io_in_0_bits_fwdTxnID),
    .io_in_0_bits_opcode(io_in_0_bits_opcode),
    .io_in_0_bits_addr(io_in_0_bits_addr),
    .io_in_0_bits_ns(io_in_0_bits_ns),
    .io_in_0_bits_doNotGoToSD(io_in_0_bits_doNotGoToSD),
    .io_in_0_bits_retToSrc(io_in_0_bits_retToSrc),
    .io_in_0_bits_traceTag(io_in_0_bits_traceTag),
    .io_in_0_bits_mpam_perfMonGroup(io_in_0_bits_mpam_perfMonGroup),
    .io_in_0_bits_mpam_partID(io_in_0_bits_mpam_partID),
    .io_in_0_bits_mpam_mpamNS(io_in_0_bits_mpam_mpamNS),
    .io_in_1_valid(io_in_1_valid),
    .io_in_1_bits_qos(io_in_1_bits_qos),
    .io_in_1_bits_srcID(io_in_1_bits_srcID),
    .io_in_1_bits_txnID(io_in_1_bits_txnID),
    .io_in_1_bits_fwdNID(io_in_1_bits_fwdNID),
    .io_in_1_bits_fwdTxnID(io_in_1_bits_fwdTxnID),
    .io_in_1_bits_opcode(io_in_1_bits_opcode),
    .io_in_1_bits_addr(io_in_1_bits_addr),
    .io_in_1_bits_ns(io_in_1_bits_ns),
    .io_in_1_bits_doNotGoToSD(io_in_1_bits_doNotGoToSD),
    .io_in_1_bits_retToSrc(io_in_1_bits_retToSrc),
    .io_in_1_bits_traceTag(io_in_1_bits_traceTag),
    .io_in_1_bits_mpam_perfMonGroup(io_in_1_bits_mpam_perfMonGroup),
    .io_in_1_bits_mpam_partID(io_in_1_bits_mpam_partID),
    .io_in_1_bits_mpam_mpamNS(io_in_1_bits_mpam_mpamNS),
    .io_out_ready(io_out_ready),
    .io_out_valid(io_out_valid),
    .io_out_bits_qos(io_out_bits_qos),
    .io_out_bits_srcID(io_out_bits_srcID),
    .io_out_bits_txnID(io_out_bits_txnID),
    .io_out_bits_fwdNID(io_out_bits_fwdNID),
    .io_out_bits_fwdTxnID(io_out_bits_fwdTxnID),
    .io_out_bits_opcode(io_out_bits_opcode),
    .io_out_bits_addr(io_out_bits_addr),
    .io_out_bits_ns(io_out_bits_ns),
    .io_out_bits_doNotGoToSD(io_out_bits_doNotGoToSD),
    .io_out_bits_retToSrc(io_out_bits_retToSrc),
    .io_out_bits_traceTag(io_out_bits_traceTag),
    .io_out_bits_mpam_perfMonGroup(io_out_bits_mpam_perfMonGroup),
    .io_out_bits_mpam_partID(io_out_bits_mpam_partID),
    .io_out_bits_mpam_mpamNS(io_out_bits_mpam_mpamNS),
    .io_chosen(io_chosen)
  );
endmodule
