// 自动生成：scripts/gen_fastarbiter.py —— 勿手改
module FastArbiter_47(
  input clock,
  input reset,
  input io_in_0_valid,
  input [10:0] io_in_0_bits_tgtID,
  input [10:0] io_in_0_bits_srcID,
  input [11:0] io_in_0_bits_txnID,
  input [6:0] io_in_0_bits_opcode,
  input [2:0] io_in_0_bits_size,
  input [47:0] io_in_0_bits_addr,
  input io_in_0_bits_allowRetry,
  input [1:0] io_in_0_bits_order,
  input [3:0] io_in_0_bits_pCrdType,
  input io_in_0_bits_memAttr_allocate,
  input io_in_0_bits_memAttr_cacheable,
  input io_in_0_bits_memAttr_device,
  input io_in_0_bits_memAttr_ewa,
  input io_in_0_bits_snpAttr,
  input io_in_0_bits_expCompAck,
  input io_in_1_valid,
  input [10:0] io_in_1_bits_tgtID,
  input [10:0] io_in_1_bits_srcID,
  input [11:0] io_in_1_bits_txnID,
  input [6:0] io_in_1_bits_opcode,
  input [2:0] io_in_1_bits_size,
  input [47:0] io_in_1_bits_addr,
  input io_in_1_bits_allowRetry,
  input [1:0] io_in_1_bits_order,
  input [3:0] io_in_1_bits_pCrdType,
  input io_in_1_bits_memAttr_allocate,
  input io_in_1_bits_memAttr_cacheable,
  input io_in_1_bits_memAttr_device,
  input io_in_1_bits_memAttr_ewa,
  input io_in_1_bits_snpAttr,
  input io_in_1_bits_expCompAck,
  input io_in_2_valid,
  input [10:0] io_in_2_bits_tgtID,
  input [10:0] io_in_2_bits_srcID,
  input [11:0] io_in_2_bits_txnID,
  input [6:0] io_in_2_bits_opcode,
  input [2:0] io_in_2_bits_size,
  input [47:0] io_in_2_bits_addr,
  input io_in_2_bits_allowRetry,
  input [1:0] io_in_2_bits_order,
  input [3:0] io_in_2_bits_pCrdType,
  input io_in_2_bits_memAttr_allocate,
  input io_in_2_bits_memAttr_cacheable,
  input io_in_2_bits_memAttr_device,
  input io_in_2_bits_memAttr_ewa,
  input io_in_2_bits_snpAttr,
  input io_in_2_bits_expCompAck,
  input io_in_3_valid,
  input [10:0] io_in_3_bits_tgtID,
  input [10:0] io_in_3_bits_srcID,
  input [11:0] io_in_3_bits_txnID,
  input [6:0] io_in_3_bits_opcode,
  input [2:0] io_in_3_bits_size,
  input [47:0] io_in_3_bits_addr,
  input io_in_3_bits_allowRetry,
  input [1:0] io_in_3_bits_order,
  input [3:0] io_in_3_bits_pCrdType,
  input io_in_3_bits_memAttr_allocate,
  input io_in_3_bits_memAttr_cacheable,
  input io_in_3_bits_memAttr_device,
  input io_in_3_bits_memAttr_ewa,
  input io_in_3_bits_snpAttr,
  input io_in_3_bits_expCompAck,
  input io_out_ready,
  output io_out_valid,
  output [10:0] io_out_bits_tgtID,
  output [10:0] io_out_bits_srcID,
  output [11:0] io_out_bits_txnID,
  output [6:0] io_out_bits_opcode,
  output [2:0] io_out_bits_size,
  output [47:0] io_out_bits_addr,
  output io_out_bits_allowRetry,
  output [1:0] io_out_bits_order,
  output [3:0] io_out_bits_pCrdType,
  output io_out_bits_memAttr_allocate,
  output io_out_bits_memAttr_cacheable,
  output io_out_bits_memAttr_device,
  output io_out_bits_memAttr_ewa,
  output io_out_bits_snpAttr,
  output io_out_bits_expCompAck,
  output [1:0] io_chosen
);
  xs_FastArbiter_47_core u_core (
    .clock(clock),
    .reset(reset),
    .io_in_0_valid(io_in_0_valid),
    .io_in_0_bits_tgtID(io_in_0_bits_tgtID),
    .io_in_0_bits_srcID(io_in_0_bits_srcID),
    .io_in_0_bits_txnID(io_in_0_bits_txnID),
    .io_in_0_bits_opcode(io_in_0_bits_opcode),
    .io_in_0_bits_size(io_in_0_bits_size),
    .io_in_0_bits_addr(io_in_0_bits_addr),
    .io_in_0_bits_allowRetry(io_in_0_bits_allowRetry),
    .io_in_0_bits_order(io_in_0_bits_order),
    .io_in_0_bits_pCrdType(io_in_0_bits_pCrdType),
    .io_in_0_bits_memAttr_allocate(io_in_0_bits_memAttr_allocate),
    .io_in_0_bits_memAttr_cacheable(io_in_0_bits_memAttr_cacheable),
    .io_in_0_bits_memAttr_device(io_in_0_bits_memAttr_device),
    .io_in_0_bits_memAttr_ewa(io_in_0_bits_memAttr_ewa),
    .io_in_0_bits_snpAttr(io_in_0_bits_snpAttr),
    .io_in_0_bits_expCompAck(io_in_0_bits_expCompAck),
    .io_in_1_valid(io_in_1_valid),
    .io_in_1_bits_tgtID(io_in_1_bits_tgtID),
    .io_in_1_bits_srcID(io_in_1_bits_srcID),
    .io_in_1_bits_txnID(io_in_1_bits_txnID),
    .io_in_1_bits_opcode(io_in_1_bits_opcode),
    .io_in_1_bits_size(io_in_1_bits_size),
    .io_in_1_bits_addr(io_in_1_bits_addr),
    .io_in_1_bits_allowRetry(io_in_1_bits_allowRetry),
    .io_in_1_bits_order(io_in_1_bits_order),
    .io_in_1_bits_pCrdType(io_in_1_bits_pCrdType),
    .io_in_1_bits_memAttr_allocate(io_in_1_bits_memAttr_allocate),
    .io_in_1_bits_memAttr_cacheable(io_in_1_bits_memAttr_cacheable),
    .io_in_1_bits_memAttr_device(io_in_1_bits_memAttr_device),
    .io_in_1_bits_memAttr_ewa(io_in_1_bits_memAttr_ewa),
    .io_in_1_bits_snpAttr(io_in_1_bits_snpAttr),
    .io_in_1_bits_expCompAck(io_in_1_bits_expCompAck),
    .io_in_2_valid(io_in_2_valid),
    .io_in_2_bits_tgtID(io_in_2_bits_tgtID),
    .io_in_2_bits_srcID(io_in_2_bits_srcID),
    .io_in_2_bits_txnID(io_in_2_bits_txnID),
    .io_in_2_bits_opcode(io_in_2_bits_opcode),
    .io_in_2_bits_size(io_in_2_bits_size),
    .io_in_2_bits_addr(io_in_2_bits_addr),
    .io_in_2_bits_allowRetry(io_in_2_bits_allowRetry),
    .io_in_2_bits_order(io_in_2_bits_order),
    .io_in_2_bits_pCrdType(io_in_2_bits_pCrdType),
    .io_in_2_bits_memAttr_allocate(io_in_2_bits_memAttr_allocate),
    .io_in_2_bits_memAttr_cacheable(io_in_2_bits_memAttr_cacheable),
    .io_in_2_bits_memAttr_device(io_in_2_bits_memAttr_device),
    .io_in_2_bits_memAttr_ewa(io_in_2_bits_memAttr_ewa),
    .io_in_2_bits_snpAttr(io_in_2_bits_snpAttr),
    .io_in_2_bits_expCompAck(io_in_2_bits_expCompAck),
    .io_in_3_valid(io_in_3_valid),
    .io_in_3_bits_tgtID(io_in_3_bits_tgtID),
    .io_in_3_bits_srcID(io_in_3_bits_srcID),
    .io_in_3_bits_txnID(io_in_3_bits_txnID),
    .io_in_3_bits_opcode(io_in_3_bits_opcode),
    .io_in_3_bits_size(io_in_3_bits_size),
    .io_in_3_bits_addr(io_in_3_bits_addr),
    .io_in_3_bits_allowRetry(io_in_3_bits_allowRetry),
    .io_in_3_bits_order(io_in_3_bits_order),
    .io_in_3_bits_pCrdType(io_in_3_bits_pCrdType),
    .io_in_3_bits_memAttr_allocate(io_in_3_bits_memAttr_allocate),
    .io_in_3_bits_memAttr_cacheable(io_in_3_bits_memAttr_cacheable),
    .io_in_3_bits_memAttr_device(io_in_3_bits_memAttr_device),
    .io_in_3_bits_memAttr_ewa(io_in_3_bits_memAttr_ewa),
    .io_in_3_bits_snpAttr(io_in_3_bits_snpAttr),
    .io_in_3_bits_expCompAck(io_in_3_bits_expCompAck),
    .io_out_ready(io_out_ready),
    .io_out_valid(io_out_valid),
    .io_out_bits_tgtID(io_out_bits_tgtID),
    .io_out_bits_srcID(io_out_bits_srcID),
    .io_out_bits_txnID(io_out_bits_txnID),
    .io_out_bits_opcode(io_out_bits_opcode),
    .io_out_bits_size(io_out_bits_size),
    .io_out_bits_addr(io_out_bits_addr),
    .io_out_bits_allowRetry(io_out_bits_allowRetry),
    .io_out_bits_order(io_out_bits_order),
    .io_out_bits_pCrdType(io_out_bits_pCrdType),
    .io_out_bits_memAttr_allocate(io_out_bits_memAttr_allocate),
    .io_out_bits_memAttr_cacheable(io_out_bits_memAttr_cacheable),
    .io_out_bits_memAttr_device(io_out_bits_memAttr_device),
    .io_out_bits_memAttr_ewa(io_out_bits_memAttr_ewa),
    .io_out_bits_snpAttr(io_out_bits_snpAttr),
    .io_out_bits_expCompAck(io_out_bits_expCompAck),
    .io_chosen(io_chosen)
  );
endmodule
