// 自动生成 scripts/gen_grantbuffer.py —— 勿手改
// GrantBuffer: golden 同名装配壳 = 可读核 xs_GrantBuffer_core + 4 个 FIFO 黑盒。
// 黑盒(两侧一致): grantQueue / grantQueueData0 / grantQueueData1 / pftRespQueue。
module GrantBuffer
  import l2_task_pkg::*;
(
  input clock,
  input reset,
  input io_d_task_valid,
  input [2:0] io_d_task_bits_task_channel,
  input [2:0] io_d_task_bits_task_txChannel,
  input [8:0] io_d_task_bits_task_set,
  input [30:0] io_d_task_bits_task_tag,
  input [5:0] io_d_task_bits_task_off,
  input [1:0] io_d_task_bits_task_alias,
  input [43:0] io_d_task_bits_task_vaddr,
  input io_d_task_bits_task_isKeyword,
  input [3:0] io_d_task_bits_task_opcode,
  input [2:0] io_d_task_bits_task_param,
  input [2:0] io_d_task_bits_task_size,
  input [6:0] io_d_task_bits_task_sourceId,
  input [1:0] io_d_task_bits_task_bufIdx,
  input io_d_task_bits_task_needProbeAckData,
  input io_d_task_bits_task_denied,
  input io_d_task_bits_task_corrupt,
  input io_d_task_bits_task_mshrTask,
  input [7:0] io_d_task_bits_task_mshrId,
  input io_d_task_bits_task_aliasTask,
  input io_d_task_bits_task_useProbeData,
  input io_d_task_bits_task_mshrRetry,
  input io_d_task_bits_task_readProbeDataDown,
  input io_d_task_bits_task_fromL2pft,
  input io_d_task_bits_task_needHint,
  input io_d_task_bits_task_dirty,
  input [2:0] io_d_task_bits_task_way,
  input io_d_task_bits_task_meta_dirty,
  input [1:0] io_d_task_bits_task_meta_state,
  input io_d_task_bits_task_meta_clients,
  input [1:0] io_d_task_bits_task_meta_alias,
  input io_d_task_bits_task_meta_prefetch,
  input [2:0] io_d_task_bits_task_meta_prefetchSrc,
  input io_d_task_bits_task_meta_accessed,
  input io_d_task_bits_task_meta_tagErr,
  input io_d_task_bits_task_meta_dataErr,
  input io_d_task_bits_task_metaWen,
  input io_d_task_bits_task_tagWen,
  input io_d_task_bits_task_dsWen,
  input [7:0] io_d_task_bits_task_wayMask,
  input io_d_task_bits_task_replTask,
  input io_d_task_bits_task_cmoTask,
  input io_d_task_bits_task_cmoAll,
  input [4:0] io_d_task_bits_task_reqSource,
  input io_d_task_bits_task_mergeA,
  input [5:0] io_d_task_bits_task_aMergeTask_off,
  input [1:0] io_d_task_bits_task_aMergeTask_alias,
  input [43:0] io_d_task_bits_task_aMergeTask_vaddr,
  input io_d_task_bits_task_aMergeTask_isKeyword,
  input [2:0] io_d_task_bits_task_aMergeTask_opcode,
  input [2:0] io_d_task_bits_task_aMergeTask_param,
  input [6:0] io_d_task_bits_task_aMergeTask_sourceId,
  input io_d_task_bits_task_aMergeTask_meta_dirty,
  input [1:0] io_d_task_bits_task_aMergeTask_meta_state,
  input io_d_task_bits_task_aMergeTask_meta_clients,
  input [1:0] io_d_task_bits_task_aMergeTask_meta_alias,
  input io_d_task_bits_task_aMergeTask_meta_prefetch,
  input [2:0] io_d_task_bits_task_aMergeTask_meta_prefetchSrc,
  input io_d_task_bits_task_aMergeTask_meta_accessed,
  input io_d_task_bits_task_aMergeTask_meta_tagErr,
  input io_d_task_bits_task_aMergeTask_meta_dataErr,
  input io_d_task_bits_task_snpHitRelease,
  input io_d_task_bits_task_snpHitReleaseToInval,
  input io_d_task_bits_task_snpHitReleaseToClean,
  input io_d_task_bits_task_snpHitReleaseWithData,
  input [7:0] io_d_task_bits_task_snpHitReleaseIdx,
  input io_d_task_bits_task_snpHitReleaseMeta_dirty,
  input [1:0] io_d_task_bits_task_snpHitReleaseMeta_state,
  input io_d_task_bits_task_snpHitReleaseMeta_clients,
  input [1:0] io_d_task_bits_task_snpHitReleaseMeta_alias,
  input io_d_task_bits_task_snpHitReleaseMeta_prefetch,
  input [2:0] io_d_task_bits_task_snpHitReleaseMeta_prefetchSrc,
  input io_d_task_bits_task_snpHitReleaseMeta_accessed,
  input io_d_task_bits_task_snpHitReleaseMeta_tagErr,
  input io_d_task_bits_task_snpHitReleaseMeta_dataErr,
  input [10:0] io_d_task_bits_task_tgtID,
  input [10:0] io_d_task_bits_task_srcID,
  input [11:0] io_d_task_bits_task_txnID,
  input [10:0] io_d_task_bits_task_homeNID,
  input [11:0] io_d_task_bits_task_dbID,
  input [10:0] io_d_task_bits_task_fwdNID,
  input [11:0] io_d_task_bits_task_fwdTxnID,
  input [6:0] io_d_task_bits_task_chiOpcode,
  input [2:0] io_d_task_bits_task_resp,
  input [2:0] io_d_task_bits_task_fwdState,
  input [3:0] io_d_task_bits_task_pCrdType,
  input io_d_task_bits_task_retToSrc,
  input io_d_task_bits_task_likelyshared,
  input io_d_task_bits_task_expCompAck,
  input io_d_task_bits_task_allowRetry,
  input io_d_task_bits_task_memAttr_allocate,
  input io_d_task_bits_task_memAttr_cacheable,
  input io_d_task_bits_task_memAttr_device,
  input io_d_task_bits_task_memAttr_ewa,
  input io_d_task_bits_task_traceTag,
  input io_d_task_bits_task_dataCheckErr,
  input [511:0] io_d_task_bits_data_data,
  input io_d_ready,
  output io_d_valid,
  output [3:0] io_d_bits_opcode,
  output [1:0] io_d_bits_param,
  output [6:0] io_d_bits_source,
  output [7:0] io_d_bits_sink,
  output io_d_bits_denied,
  output io_d_bits_echo_isKeyword,
  output [255:0] io_d_bits_data,
  output io_d_bits_corrupt,
  input io_e_valid,
  input [7:0] io_e_bits_sink,
  input [30:0] io_fromReqArb_status_s1_tags_1,
  input [8:0] io_fromReqArb_status_s1_sets_1,
  input io_pipeStatusVec_1_valid,
  input [2:0] io_pipeStatusVec_1_bits_channel,
  input io_pipeStatusVec_2_valid,
  input [2:0] io_pipeStatusVec_2_bits_channel,
  input io_pipeStatusVec_3_valid,
  input [2:0] io_pipeStatusVec_3_bits_channel,
  input io_pipeStatusVec_4_valid,
  input [2:0] io_pipeStatusVec_4_bits_channel,
  output io_toReqArb_blockSinkReqEntrance_blockA_s1,
  output io_toReqArb_blockSinkReqEntrance_blockB_s1,
  output io_toReqArb_blockSinkReqEntrance_blockC_s1,
  output io_toReqArb_blockMSHRReqEntrance,
  input io_prefetchResp_ready,
  output io_prefetchResp_valid,
  output [32:0] io_prefetchResp_bits_tag,
  output [8:0] io_prefetchResp_bits_set,
  output [43:0] io_prefetchResp_bits_vaddr,
  output [4:0] io_prefetchResp_bits_pfSource,
  output io_grantStatus_0_valid,
  output [8:0] io_grantStatus_0_set,
  output [30:0] io_grantStatus_0_tag,
  output io_grantStatus_1_valid,
  output [8:0] io_grantStatus_1_set,
  output [30:0] io_grantStatus_1_tag,
  output io_grantStatus_2_valid,
  output [8:0] io_grantStatus_2_set,
  output [30:0] io_grantStatus_2_tag,
  output io_grantStatus_3_valid,
  output [8:0] io_grantStatus_3_set,
  output [30:0] io_grantStatus_3_tag,
  output io_grantStatus_4_valid,
  output [8:0] io_grantStatus_4_set,
  output [30:0] io_grantStatus_4_tag,
  output io_grantStatus_5_valid,
  output [8:0] io_grantStatus_5_set,
  output [30:0] io_grantStatus_5_tag,
  output io_grantStatus_6_valid,
  output [8:0] io_grantStatus_6_set,
  output [30:0] io_grantStatus_6_tag,
  output io_grantStatus_7_valid,
  output [8:0] io_grantStatus_7_set,
  output [30:0] io_grantStatus_7_tag,
  output io_grantStatus_8_valid,
  output [8:0] io_grantStatus_8_set,
  output [30:0] io_grantStatus_8_tag,
  output io_grantStatus_9_valid,
  output [8:0] io_grantStatus_9_set,
  output [30:0] io_grantStatus_9_tag,
  output io_grantStatus_10_valid,
  output [8:0] io_grantStatus_10_set,
  output [30:0] io_grantStatus_10_tag,
  output io_grantStatus_11_valid,
  output [8:0] io_grantStatus_11_set,
  output [30:0] io_grantStatus_11_tag,
  output io_grantStatus_12_valid,
  output [8:0] io_grantStatus_12_set,
  output [30:0] io_grantStatus_12_tag,
  output io_grantStatus_13_valid,
  output [8:0] io_grantStatus_13_set,
  output [30:0] io_grantStatus_13_tag,
  output io_grantStatus_14_valid,
  output [8:0] io_grantStatus_14_set,
  output [30:0] io_grantStatus_14_tag,
  output io_grantStatus_15_valid,
  output [8:0] io_grantStatus_15_set,
  output [30:0] io_grantStatus_15_tag
);

  // ---- 核 <-> FIFO 边界 ----
  task_bundle_t gq_enq_task;
  wire        gq_enq_valid, gq_deq_ready, gq_deq_valid;
  wire        gq_deq_isKeyword, gq_deq_denied, gq_deq_corrupt;
  wire [3:0]  gq_deq_opcode;
  wire [2:0]  gq_deq_param;
  wire [6:0]  gq_deq_sourceId;
  wire [7:0]  gq_enq_grantid, gq_deq_grantid;
  wire [4:0]  gq_count;
  wire [255:0] gd0_deq_data, gd1_deq_data;
  wire [3:0]  pft_count;
  wire        gq_enq_ready;   // 队列满标志, 仅 golden assert 用; 此处接线以对齐黑盒引脚
  wire        pft_enq_ready;  // 同上

  // ===== 可读核 =====
  xs_GrantBuffer_core u_core (
    .clock(clock),
    .reset(reset),
    .io_d_task_valid(io_d_task_valid),
    .io_d_task_bits_task_channel(io_d_task_bits_task_channel),
    .io_d_task_bits_task_txChannel(io_d_task_bits_task_txChannel),
    .io_d_task_bits_task_set(io_d_task_bits_task_set),
    .io_d_task_bits_task_tag(io_d_task_bits_task_tag),
    .io_d_task_bits_task_off(io_d_task_bits_task_off),
    .io_d_task_bits_task_alias(io_d_task_bits_task_alias),
    .io_d_task_bits_task_vaddr(io_d_task_bits_task_vaddr),
    .io_d_task_bits_task_isKeyword(io_d_task_bits_task_isKeyword),
    .io_d_task_bits_task_opcode(io_d_task_bits_task_opcode),
    .io_d_task_bits_task_param(io_d_task_bits_task_param),
    .io_d_task_bits_task_size(io_d_task_bits_task_size),
    .io_d_task_bits_task_sourceId(io_d_task_bits_task_sourceId),
    .io_d_task_bits_task_bufIdx(io_d_task_bits_task_bufIdx),
    .io_d_task_bits_task_needProbeAckData(io_d_task_bits_task_needProbeAckData),
    .io_d_task_bits_task_denied(io_d_task_bits_task_denied),
    .io_d_task_bits_task_corrupt(io_d_task_bits_task_corrupt),
    .io_d_task_bits_task_mshrTask(io_d_task_bits_task_mshrTask),
    .io_d_task_bits_task_mshrId(io_d_task_bits_task_mshrId),
    .io_d_task_bits_task_aliasTask(io_d_task_bits_task_aliasTask),
    .io_d_task_bits_task_useProbeData(io_d_task_bits_task_useProbeData),
    .io_d_task_bits_task_mshrRetry(io_d_task_bits_task_mshrRetry),
    .io_d_task_bits_task_readProbeDataDown(io_d_task_bits_task_readProbeDataDown),
    .io_d_task_bits_task_fromL2pft(io_d_task_bits_task_fromL2pft),
    .io_d_task_bits_task_needHint(io_d_task_bits_task_needHint),
    .io_d_task_bits_task_dirty(io_d_task_bits_task_dirty),
    .io_d_task_bits_task_way(io_d_task_bits_task_way),
    .io_d_task_bits_task_meta_dirty(io_d_task_bits_task_meta_dirty),
    .io_d_task_bits_task_meta_state(io_d_task_bits_task_meta_state),
    .io_d_task_bits_task_meta_clients(io_d_task_bits_task_meta_clients),
    .io_d_task_bits_task_meta_alias(io_d_task_bits_task_meta_alias),
    .io_d_task_bits_task_meta_prefetch(io_d_task_bits_task_meta_prefetch),
    .io_d_task_bits_task_meta_prefetchSrc(io_d_task_bits_task_meta_prefetchSrc),
    .io_d_task_bits_task_meta_accessed(io_d_task_bits_task_meta_accessed),
    .io_d_task_bits_task_meta_tagErr(io_d_task_bits_task_meta_tagErr),
    .io_d_task_bits_task_meta_dataErr(io_d_task_bits_task_meta_dataErr),
    .io_d_task_bits_task_metaWen(io_d_task_bits_task_metaWen),
    .io_d_task_bits_task_tagWen(io_d_task_bits_task_tagWen),
    .io_d_task_bits_task_dsWen(io_d_task_bits_task_dsWen),
    .io_d_task_bits_task_wayMask(io_d_task_bits_task_wayMask),
    .io_d_task_bits_task_replTask(io_d_task_bits_task_replTask),
    .io_d_task_bits_task_cmoTask(io_d_task_bits_task_cmoTask),
    .io_d_task_bits_task_cmoAll(io_d_task_bits_task_cmoAll),
    .io_d_task_bits_task_reqSource(io_d_task_bits_task_reqSource),
    .io_d_task_bits_task_mergeA(io_d_task_bits_task_mergeA),
    .io_d_task_bits_task_aMergeTask_off(io_d_task_bits_task_aMergeTask_off),
    .io_d_task_bits_task_aMergeTask_alias(io_d_task_bits_task_aMergeTask_alias),
    .io_d_task_bits_task_aMergeTask_vaddr(io_d_task_bits_task_aMergeTask_vaddr),
    .io_d_task_bits_task_aMergeTask_isKeyword(io_d_task_bits_task_aMergeTask_isKeyword),
    .io_d_task_bits_task_aMergeTask_opcode(io_d_task_bits_task_aMergeTask_opcode),
    .io_d_task_bits_task_aMergeTask_param(io_d_task_bits_task_aMergeTask_param),
    .io_d_task_bits_task_aMergeTask_sourceId(io_d_task_bits_task_aMergeTask_sourceId),
    .io_d_task_bits_task_aMergeTask_meta_dirty(io_d_task_bits_task_aMergeTask_meta_dirty),
    .io_d_task_bits_task_aMergeTask_meta_state(io_d_task_bits_task_aMergeTask_meta_state),
    .io_d_task_bits_task_aMergeTask_meta_clients(io_d_task_bits_task_aMergeTask_meta_clients),
    .io_d_task_bits_task_aMergeTask_meta_alias(io_d_task_bits_task_aMergeTask_meta_alias),
    .io_d_task_bits_task_aMergeTask_meta_prefetch(io_d_task_bits_task_aMergeTask_meta_prefetch),
    .io_d_task_bits_task_aMergeTask_meta_prefetchSrc(io_d_task_bits_task_aMergeTask_meta_prefetchSrc),
    .io_d_task_bits_task_aMergeTask_meta_accessed(io_d_task_bits_task_aMergeTask_meta_accessed),
    .io_d_task_bits_task_aMergeTask_meta_tagErr(io_d_task_bits_task_aMergeTask_meta_tagErr),
    .io_d_task_bits_task_aMergeTask_meta_dataErr(io_d_task_bits_task_aMergeTask_meta_dataErr),
    .io_d_task_bits_task_snpHitRelease(io_d_task_bits_task_snpHitRelease),
    .io_d_task_bits_task_snpHitReleaseToInval(io_d_task_bits_task_snpHitReleaseToInval),
    .io_d_task_bits_task_snpHitReleaseToClean(io_d_task_bits_task_snpHitReleaseToClean),
    .io_d_task_bits_task_snpHitReleaseWithData(io_d_task_bits_task_snpHitReleaseWithData),
    .io_d_task_bits_task_snpHitReleaseIdx(io_d_task_bits_task_snpHitReleaseIdx),
    .io_d_task_bits_task_snpHitReleaseMeta_dirty(io_d_task_bits_task_snpHitReleaseMeta_dirty),
    .io_d_task_bits_task_snpHitReleaseMeta_state(io_d_task_bits_task_snpHitReleaseMeta_state),
    .io_d_task_bits_task_snpHitReleaseMeta_clients(io_d_task_bits_task_snpHitReleaseMeta_clients),
    .io_d_task_bits_task_snpHitReleaseMeta_alias(io_d_task_bits_task_snpHitReleaseMeta_alias),
    .io_d_task_bits_task_snpHitReleaseMeta_prefetch(io_d_task_bits_task_snpHitReleaseMeta_prefetch),
    .io_d_task_bits_task_snpHitReleaseMeta_prefetchSrc(io_d_task_bits_task_snpHitReleaseMeta_prefetchSrc),
    .io_d_task_bits_task_snpHitReleaseMeta_accessed(io_d_task_bits_task_snpHitReleaseMeta_accessed),
    .io_d_task_bits_task_snpHitReleaseMeta_tagErr(io_d_task_bits_task_snpHitReleaseMeta_tagErr),
    .io_d_task_bits_task_snpHitReleaseMeta_dataErr(io_d_task_bits_task_snpHitReleaseMeta_dataErr),
    .io_d_task_bits_task_tgtID(io_d_task_bits_task_tgtID),
    .io_d_task_bits_task_srcID(io_d_task_bits_task_srcID),
    .io_d_task_bits_task_txnID(io_d_task_bits_task_txnID),
    .io_d_task_bits_task_homeNID(io_d_task_bits_task_homeNID),
    .io_d_task_bits_task_dbID(io_d_task_bits_task_dbID),
    .io_d_task_bits_task_fwdNID(io_d_task_bits_task_fwdNID),
    .io_d_task_bits_task_fwdTxnID(io_d_task_bits_task_fwdTxnID),
    .io_d_task_bits_task_chiOpcode(io_d_task_bits_task_chiOpcode),
    .io_d_task_bits_task_resp(io_d_task_bits_task_resp),
    .io_d_task_bits_task_fwdState(io_d_task_bits_task_fwdState),
    .io_d_task_bits_task_pCrdType(io_d_task_bits_task_pCrdType),
    .io_d_task_bits_task_retToSrc(io_d_task_bits_task_retToSrc),
    .io_d_task_bits_task_likelyshared(io_d_task_bits_task_likelyshared),
    .io_d_task_bits_task_expCompAck(io_d_task_bits_task_expCompAck),
    .io_d_task_bits_task_allowRetry(io_d_task_bits_task_allowRetry),
    .io_d_task_bits_task_memAttr_allocate(io_d_task_bits_task_memAttr_allocate),
    .io_d_task_bits_task_memAttr_cacheable(io_d_task_bits_task_memAttr_cacheable),
    .io_d_task_bits_task_memAttr_device(io_d_task_bits_task_memAttr_device),
    .io_d_task_bits_task_memAttr_ewa(io_d_task_bits_task_memAttr_ewa),
    .io_d_task_bits_task_traceTag(io_d_task_bits_task_traceTag),
    .io_d_task_bits_task_dataCheckErr(io_d_task_bits_task_dataCheckErr),
    .io_d_ready(io_d_ready),
    .io_d_valid(io_d_valid),
    .io_d_bits_opcode(io_d_bits_opcode),
    .io_d_bits_param(io_d_bits_param),
    .io_d_bits_source(io_d_bits_source),
    .io_d_bits_sink(io_d_bits_sink),
    .io_d_bits_denied(io_d_bits_denied),
    .io_d_bits_echo_isKeyword(io_d_bits_echo_isKeyword),
    .io_d_bits_data(io_d_bits_data),
    .io_d_bits_corrupt(io_d_bits_corrupt),
    .io_e_valid(io_e_valid),
    .io_e_bits_sink(io_e_bits_sink),
    .io_fromReqArb_status_s1_tags_1(io_fromReqArb_status_s1_tags_1),
    .io_fromReqArb_status_s1_sets_1(io_fromReqArb_status_s1_sets_1),
    .io_pipeStatusVec_1_valid(io_pipeStatusVec_1_valid),
    .io_pipeStatusVec_1_bits_channel(io_pipeStatusVec_1_bits_channel),
    .io_pipeStatusVec_2_valid(io_pipeStatusVec_2_valid),
    .io_pipeStatusVec_2_bits_channel(io_pipeStatusVec_2_bits_channel),
    .io_pipeStatusVec_3_valid(io_pipeStatusVec_3_valid),
    .io_pipeStatusVec_3_bits_channel(io_pipeStatusVec_3_bits_channel),
    .io_pipeStatusVec_4_valid(io_pipeStatusVec_4_valid),
    .io_pipeStatusVec_4_bits_channel(io_pipeStatusVec_4_bits_channel),
    .io_toReqArb_blockSinkReqEntrance_blockA_s1(io_toReqArb_blockSinkReqEntrance_blockA_s1),
    .io_toReqArb_blockSinkReqEntrance_blockB_s1(io_toReqArb_blockSinkReqEntrance_blockB_s1),
    .io_toReqArb_blockSinkReqEntrance_blockC_s1(io_toReqArb_blockSinkReqEntrance_blockC_s1),
    .io_toReqArb_blockMSHRReqEntrance(io_toReqArb_blockMSHRReqEntrance),
    .io_grantStatus_0_valid(io_grantStatus_0_valid),
    .io_grantStatus_0_set(io_grantStatus_0_set),
    .io_grantStatus_0_tag(io_grantStatus_0_tag),
    .io_grantStatus_1_valid(io_grantStatus_1_valid),
    .io_grantStatus_1_set(io_grantStatus_1_set),
    .io_grantStatus_1_tag(io_grantStatus_1_tag),
    .io_grantStatus_2_valid(io_grantStatus_2_valid),
    .io_grantStatus_2_set(io_grantStatus_2_set),
    .io_grantStatus_2_tag(io_grantStatus_2_tag),
    .io_grantStatus_3_valid(io_grantStatus_3_valid),
    .io_grantStatus_3_set(io_grantStatus_3_set),
    .io_grantStatus_3_tag(io_grantStatus_3_tag),
    .io_grantStatus_4_valid(io_grantStatus_4_valid),
    .io_grantStatus_4_set(io_grantStatus_4_set),
    .io_grantStatus_4_tag(io_grantStatus_4_tag),
    .io_grantStatus_5_valid(io_grantStatus_5_valid),
    .io_grantStatus_5_set(io_grantStatus_5_set),
    .io_grantStatus_5_tag(io_grantStatus_5_tag),
    .io_grantStatus_6_valid(io_grantStatus_6_valid),
    .io_grantStatus_6_set(io_grantStatus_6_set),
    .io_grantStatus_6_tag(io_grantStatus_6_tag),
    .io_grantStatus_7_valid(io_grantStatus_7_valid),
    .io_grantStatus_7_set(io_grantStatus_7_set),
    .io_grantStatus_7_tag(io_grantStatus_7_tag),
    .io_grantStatus_8_valid(io_grantStatus_8_valid),
    .io_grantStatus_8_set(io_grantStatus_8_set),
    .io_grantStatus_8_tag(io_grantStatus_8_tag),
    .io_grantStatus_9_valid(io_grantStatus_9_valid),
    .io_grantStatus_9_set(io_grantStatus_9_set),
    .io_grantStatus_9_tag(io_grantStatus_9_tag),
    .io_grantStatus_10_valid(io_grantStatus_10_valid),
    .io_grantStatus_10_set(io_grantStatus_10_set),
    .io_grantStatus_10_tag(io_grantStatus_10_tag),
    .io_grantStatus_11_valid(io_grantStatus_11_valid),
    .io_grantStatus_11_set(io_grantStatus_11_set),
    .io_grantStatus_11_tag(io_grantStatus_11_tag),
    .io_grantStatus_12_valid(io_grantStatus_12_valid),
    .io_grantStatus_12_set(io_grantStatus_12_set),
    .io_grantStatus_12_tag(io_grantStatus_12_tag),
    .io_grantStatus_13_valid(io_grantStatus_13_valid),
    .io_grantStatus_13_set(io_grantStatus_13_set),
    .io_grantStatus_13_tag(io_grantStatus_13_tag),
    .io_grantStatus_14_valid(io_grantStatus_14_valid),
    .io_grantStatus_14_set(io_grantStatus_14_set),
    .io_grantStatus_14_tag(io_grantStatus_14_tag),
    .io_grantStatus_15_valid(io_grantStatus_15_valid),
    .io_grantStatus_15_set(io_grantStatus_15_set),
    .io_grantStatus_15_tag(io_grantStatus_15_tag),
    .gq_enq_task(gq_enq_task),
    .gq_enq_valid(gq_enq_valid),
    .gq_enq_grantid(gq_enq_grantid),
    .gq_deq_ready(gq_deq_ready),
    .gq_deq_valid(gq_deq_valid),
    .gq_deq_isKeyword(gq_deq_isKeyword),
    .gq_deq_opcode(gq_deq_opcode),
    .gq_deq_param(gq_deq_param),
    .gq_deq_sourceId(gq_deq_sourceId),
    .gq_deq_denied(gq_deq_denied),
    .gq_deq_corrupt(gq_deq_corrupt),
    .gq_deq_grantid(gq_deq_grantid),
    .gq_count(gq_count),
    .gd0_deq_data(gd0_deq_data),
    .gd1_deq_data(gd1_deq_data),
    .pft_count(pft_count)
  );

  // ===== grantQueue: TaskBundle+grantid FIFO(16 深) =====
  Queue16_GrantQueueTask grantQueue (
    .clock(clock), .reset(reset),
    .io_enq_ready(gq_enq_ready),
    .io_enq_valid(gq_enq_valid),
    .io_enq_bits_task_channel(gq_enq_task.channel),
    .io_enq_bits_task_txChannel(gq_enq_task.txChannel),
    .io_enq_bits_task_set(gq_enq_task.set),
    .io_enq_bits_task_tag(gq_enq_task.tag),
    .io_enq_bits_task_off(gq_enq_task.off),
    .io_enq_bits_task_alias(gq_enq_task.alias_),
    .io_enq_bits_task_vaddr(gq_enq_task.vaddr),
    .io_enq_bits_task_isKeyword(gq_enq_task.isKeyword),
    .io_enq_bits_task_opcode(gq_enq_task.opcode),
    .io_enq_bits_task_param(gq_enq_task.param),
    .io_enq_bits_task_size(gq_enq_task.size),
    .io_enq_bits_task_sourceId(gq_enq_task.sourceId),
    .io_enq_bits_task_bufIdx(gq_enq_task.bufIdx),
    .io_enq_bits_task_needProbeAckData(gq_enq_task.needProbeAckData),
    .io_enq_bits_task_denied(gq_enq_task.denied),
    .io_enq_bits_task_corrupt(gq_enq_task.corrupt),
    .io_enq_bits_task_mshrTask(gq_enq_task.mshrTask),
    .io_enq_bits_task_mshrId(gq_enq_task.mshrId),
    .io_enq_bits_task_aliasTask(gq_enq_task.aliasTask),
    .io_enq_bits_task_useProbeData(gq_enq_task.useProbeData),
    .io_enq_bits_task_mshrRetry(gq_enq_task.mshrRetry),
    .io_enq_bits_task_readProbeDataDown(gq_enq_task.readProbeDataDown),
    .io_enq_bits_task_fromL2pft(gq_enq_task.fromL2pft),
    .io_enq_bits_task_needHint(gq_enq_task.needHint),
    .io_enq_bits_task_dirty(gq_enq_task.dirty),
    .io_enq_bits_task_way(gq_enq_task.way),
    .io_enq_bits_task_meta_dirty(gq_enq_task.meta_dirty),
    .io_enq_bits_task_meta_state(gq_enq_task.meta_state),
    .io_enq_bits_task_meta_clients(gq_enq_task.meta_clients),
    .io_enq_bits_task_meta_alias(gq_enq_task.meta_alias),
    .io_enq_bits_task_meta_prefetch(gq_enq_task.meta_prefetch),
    .io_enq_bits_task_meta_prefetchSrc(gq_enq_task.meta_prefetchSrc),
    .io_enq_bits_task_meta_accessed(gq_enq_task.meta_accessed),
    .io_enq_bits_task_meta_tagErr(gq_enq_task.meta_tagErr),
    .io_enq_bits_task_meta_dataErr(gq_enq_task.meta_dataErr),
    .io_enq_bits_task_metaWen(gq_enq_task.metaWen),
    .io_enq_bits_task_tagWen(gq_enq_task.tagWen),
    .io_enq_bits_task_dsWen(gq_enq_task.dsWen),
    .io_enq_bits_task_wayMask(gq_enq_task.wayMask),
    .io_enq_bits_task_replTask(gq_enq_task.replTask),
    .io_enq_bits_task_cmoTask(gq_enq_task.cmoTask),
    .io_enq_bits_task_cmoAll(gq_enq_task.cmoAll),
    .io_enq_bits_task_reqSource(gq_enq_task.reqSource),
    .io_enq_bits_task_mergeA(gq_enq_task.mergeA),
    .io_enq_bits_task_aMergeTask_off(gq_enq_task.aMergeTask_off),
    .io_enq_bits_task_aMergeTask_alias(gq_enq_task.aMergeTask_alias),
    .io_enq_bits_task_aMergeTask_vaddr(gq_enq_task.aMergeTask_vaddr),
    .io_enq_bits_task_aMergeTask_isKeyword(gq_enq_task.aMergeTask_isKeyword),
    .io_enq_bits_task_aMergeTask_opcode(gq_enq_task.aMergeTask_opcode),
    .io_enq_bits_task_aMergeTask_param(gq_enq_task.aMergeTask_param),
    .io_enq_bits_task_aMergeTask_sourceId(gq_enq_task.aMergeTask_sourceId),
    .io_enq_bits_task_aMergeTask_meta_dirty(gq_enq_task.aMergeTask_meta_dirty),
    .io_enq_bits_task_aMergeTask_meta_state(gq_enq_task.aMergeTask_meta_state),
    .io_enq_bits_task_aMergeTask_meta_clients(gq_enq_task.aMergeTask_meta_clients),
    .io_enq_bits_task_aMergeTask_meta_alias(gq_enq_task.aMergeTask_meta_alias),
    .io_enq_bits_task_aMergeTask_meta_prefetch(gq_enq_task.aMergeTask_meta_prefetch),
    .io_enq_bits_task_aMergeTask_meta_prefetchSrc(gq_enq_task.aMergeTask_meta_prefetchSrc),
    .io_enq_bits_task_aMergeTask_meta_accessed(gq_enq_task.aMergeTask_meta_accessed),
    .io_enq_bits_task_aMergeTask_meta_tagErr(gq_enq_task.aMergeTask_meta_tagErr),
    .io_enq_bits_task_aMergeTask_meta_dataErr(gq_enq_task.aMergeTask_meta_dataErr),
    .io_enq_bits_task_snpHitRelease(gq_enq_task.snpHitRelease),
    .io_enq_bits_task_snpHitReleaseToInval(gq_enq_task.snpHitReleaseToInval),
    .io_enq_bits_task_snpHitReleaseToClean(gq_enq_task.snpHitReleaseToClean),
    .io_enq_bits_task_snpHitReleaseWithData(gq_enq_task.snpHitReleaseWithData),
    .io_enq_bits_task_snpHitReleaseIdx(gq_enq_task.snpHitReleaseIdx),
    .io_enq_bits_task_snpHitReleaseMeta_dirty(gq_enq_task.snpHitReleaseMeta_dirty),
    .io_enq_bits_task_snpHitReleaseMeta_state(gq_enq_task.snpHitReleaseMeta_state),
    .io_enq_bits_task_snpHitReleaseMeta_clients(gq_enq_task.snpHitReleaseMeta_clients),
    .io_enq_bits_task_snpHitReleaseMeta_alias(gq_enq_task.snpHitReleaseMeta_alias),
    .io_enq_bits_task_snpHitReleaseMeta_prefetch(gq_enq_task.snpHitReleaseMeta_prefetch),
    .io_enq_bits_task_snpHitReleaseMeta_prefetchSrc(gq_enq_task.snpHitReleaseMeta_prefetchSrc),
    .io_enq_bits_task_snpHitReleaseMeta_accessed(gq_enq_task.snpHitReleaseMeta_accessed),
    .io_enq_bits_task_snpHitReleaseMeta_tagErr(gq_enq_task.snpHitReleaseMeta_tagErr),
    .io_enq_bits_task_snpHitReleaseMeta_dataErr(gq_enq_task.snpHitReleaseMeta_dataErr),
    .io_enq_bits_task_tgtID(gq_enq_task.tgtID),
    .io_enq_bits_task_srcID(gq_enq_task.srcID),
    .io_enq_bits_task_txnID(gq_enq_task.txnID),
    .io_enq_bits_task_homeNID(gq_enq_task.homeNID),
    .io_enq_bits_task_dbID(gq_enq_task.dbID),
    .io_enq_bits_task_fwdNID(gq_enq_task.fwdNID),
    .io_enq_bits_task_fwdTxnID(gq_enq_task.fwdTxnID),
    .io_enq_bits_task_chiOpcode(gq_enq_task.chiOpcode),
    .io_enq_bits_task_resp(gq_enq_task.resp),
    .io_enq_bits_task_fwdState(gq_enq_task.fwdState),
    .io_enq_bits_task_pCrdType(gq_enq_task.pCrdType),
    .io_enq_bits_task_retToSrc(gq_enq_task.retToSrc),
    .io_enq_bits_task_likelyshared(gq_enq_task.likelyshared),
    .io_enq_bits_task_expCompAck(gq_enq_task.expCompAck),
    .io_enq_bits_task_allowRetry(gq_enq_task.allowRetry),
    .io_enq_bits_task_memAttr_allocate(gq_enq_task.memAttr_allocate),
    .io_enq_bits_task_memAttr_cacheable(gq_enq_task.memAttr_cacheable),
    .io_enq_bits_task_memAttr_device(gq_enq_task.memAttr_device),
    .io_enq_bits_task_memAttr_ewa(gq_enq_task.memAttr_ewa),
    .io_enq_bits_task_traceTag(gq_enq_task.traceTag),
    .io_enq_bits_task_dataCheckErr(gq_enq_task.dataCheckErr),
    .io_enq_bits_grantid(gq_enq_grantid),
    .io_deq_ready(gq_deq_ready),
    .io_deq_valid(gq_deq_valid),
    .io_deq_bits_task_isKeyword(gq_deq_isKeyword),
    .io_deq_bits_task_opcode(gq_deq_opcode),
    .io_deq_bits_task_param(gq_deq_param),
    .io_deq_bits_task_sourceId(gq_deq_sourceId),
    .io_deq_bits_task_denied(gq_deq_denied),
    .io_deq_bits_task_corrupt(gq_deq_corrupt),
    .io_deq_bits_grantid(gq_deq_grantid),
    .io_count(gq_count)
  );

  // ===== grantQueueData0/1: 两路 256bit beat FIFO; enq 直取 d_task.data 高/低半 =====
  Queue16_GrantQueueData grantQueueData0 (
    .clock(clock), .reset(reset),
    .io_enq_valid(gq_enq_valid),
    .io_enq_bits_data_data(io_d_task_bits_data_data[255:0]),
    .io_deq_ready(gq_deq_ready),
    .io_deq_bits_data_data(gd0_deq_data)
  );
  Queue16_GrantQueueData grantQueueData1 (
    .clock(clock), .reset(reset),
    .io_enq_valid(gq_enq_valid),
    .io_enq_bits_data_data(io_d_task_bits_data_data[511:256]),
    .io_deq_ready(gq_deq_ready),
    .io_deq_bits_data_data(gd1_deq_data)
  );

  // ===== pftRespQueue: 预取响应 FIFO(10 深); enq 取 HintAck, deq 回 Prefetcher =====
  wire [30:0] pft_deq_tag;
  Queue10_GrantBuffer_Anon pftRespQueue (
    .clock(clock), .reset(reset),
    .io_enq_ready(pft_enq_ready),
    .io_enq_valid(io_d_task_valid & io_d_task_bits_task_opcode == 4'h2 &
                  io_d_task_bits_task_fromL2pft),
    .io_enq_bits_tag(io_d_task_bits_task_tag),
    .io_enq_bits_set(io_d_task_bits_task_set),
    .io_enq_bits_vaddr(io_d_task_bits_task_vaddr),
    .io_enq_bits_pfSource(io_d_task_bits_task_reqSource),
    .io_deq_ready(io_prefetchResp_ready),
    .io_deq_valid(io_prefetchResp_valid),
    .io_deq_bits_tag(pft_deq_tag),
    .io_deq_bits_set(io_prefetchResp_bits_set),
    .io_deq_bits_vaddr(io_prefetchResp_bits_vaddr),
    .io_deq_bits_pfSource(io_prefetchResp_bits_pfSource),
    .io_count(pft_count)
  );
  assign io_prefetchResp_bits_tag = {2'h0, pft_deq_tag};

endmodule
