// 自动生成：scripts/gen_l2mbist.py —— 勿手改
module L2Slice(
  input clock,
  input reset,
  input [4:0] mbist_array,
  input mbist_all,
  input mbist_req,
  output mbist_ack,
  input mbist_writeen,
  input [7:0] mbist_be,
  input [12:0] mbist_addr,
  input [103:0] mbist_indata,
  input mbist_readen,
  input [12:0] mbist_addr_rd,
  output [103:0] mbist_outdata,
  output [3:0] toNextPipeline_0_array,
  output toNextPipeline_0_all,
  output toNextPipeline_0_req,
  input toNextPipeline_0_ack,
  output toNextPipeline_0_writeen,
  output [7:0] toNextPipeline_0_be,
  output [9:0] toNextPipeline_0_addr,
  output [103:0] toNextPipeline_0_indata,
  output toNextPipeline_0_readen,
  output [9:0] toNextPipeline_0_addr_rd,
  input [103:0] toNextPipeline_0_outdata,
  output [4:0] toNextPipeline_1_array,
  output toNextPipeline_1_all,
  output toNextPipeline_1_req,
  input toNextPipeline_1_ack,
  output toNextPipeline_1_writeen,
  output toNextPipeline_1_be,
  output [12:0] toNextPipeline_1_addr,
  output [68:0] toNextPipeline_1_indata,
  output toNextPipeline_1_readen,
  output [12:0] toNextPipeline_1_addr_rd,
  input [68:0] toNextPipeline_1_outdata
);
  xs_L2Slice_core u_core (
    .clock(clock),
    .reset(reset),
    .mbist_array(mbist_array),
    .mbist_all(mbist_all),
    .mbist_req(mbist_req),
    .mbist_ack(mbist_ack),
    .mbist_writeen(mbist_writeen),
    .mbist_be(mbist_be),
    .mbist_addr(mbist_addr),
    .mbist_indata(mbist_indata),
    .mbist_readen(mbist_readen),
    .mbist_addr_rd(mbist_addr_rd),
    .mbist_outdata(mbist_outdata),
    .toNextPipeline_0_array(toNextPipeline_0_array),
    .toNextPipeline_0_all(toNextPipeline_0_all),
    .toNextPipeline_0_req(toNextPipeline_0_req),
    .toNextPipeline_0_ack(toNextPipeline_0_ack),
    .toNextPipeline_0_writeen(toNextPipeline_0_writeen),
    .toNextPipeline_0_be(toNextPipeline_0_be),
    .toNextPipeline_0_addr(toNextPipeline_0_addr),
    .toNextPipeline_0_indata(toNextPipeline_0_indata),
    .toNextPipeline_0_readen(toNextPipeline_0_readen),
    .toNextPipeline_0_addr_rd(toNextPipeline_0_addr_rd),
    .toNextPipeline_0_outdata(toNextPipeline_0_outdata),
    .toNextPipeline_1_array(toNextPipeline_1_array),
    .toNextPipeline_1_all(toNextPipeline_1_all),
    .toNextPipeline_1_req(toNextPipeline_1_req),
    .toNextPipeline_1_ack(toNextPipeline_1_ack),
    .toNextPipeline_1_writeen(toNextPipeline_1_writeen),
    .toNextPipeline_1_be(toNextPipeline_1_be),
    .toNextPipeline_1_addr(toNextPipeline_1_addr),
    .toNextPipeline_1_indata(toNextPipeline_1_indata),
    .toNextPipeline_1_readen(toNextPipeline_1_readen),
    .toNextPipeline_1_addr_rd(toNextPipeline_1_addr_rd),
    .toNextPipeline_1_outdata(toNextPipeline_1_outdata)
  );
endmodule
