// 自动生成 scripts/gen_chi_channel.py —— 勿手改
module LCredit2Decoupled(
  input clock,
  input reset,
  input io_in_flitv,
  input [114:0] io_in_flit,
  output io_in_lcrdv,
  input io_out_ready,
  output io_out_valid,
  output [3:0] io_out_bits_qos,
  output [10:0] io_out_bits_srcID,
  output [11:0] io_out_bits_txnID,
  output [10:0] io_out_bits_fwdNID,
  output [11:0] io_out_bits_fwdTxnID,
  output [4:0] io_out_bits_opcode,
  output [44:0] io_out_bits_addr,
  output io_out_bits_ns,
  output io_out_bits_doNotGoToSD,
  output io_out_bits_retToSrc,
  output io_out_bits_traceTag,
  output io_out_bits_mpam_perfMonGroup,
  output [8:0] io_out_bits_mpam_partID,
  output io_out_bits_mpam_mpamNS,
  input [1:0] io_state_state,
  output io_reclaimLCredit
);
  xs_LCredit2Decoupled_core u_core (
    .clock(clock),
    .reset(reset),
    .io_in_flitv(io_in_flitv),
    .io_in_flit(io_in_flit),
    .io_in_lcrdv(io_in_lcrdv),
    .io_out_ready(io_out_ready),
    .io_out_valid(io_out_valid),
    .io_out_bits_qos(io_out_bits_qos),
    .io_out_bits_srcID(io_out_bits_srcID),
    .io_out_bits_txnID(io_out_bits_txnID),
    .io_out_bits_fwdNID(io_out_bits_fwdNID),
    .io_out_bits_fwdTxnID(io_out_bits_fwdTxnID),
    .io_out_bits_opcode(io_out_bits_opcode),
    .io_out_bits_addr(io_out_bits_addr),
    .io_out_bits_ns(io_out_bits_ns),
    .io_out_bits_doNotGoToSD(io_out_bits_doNotGoToSD),
    .io_out_bits_retToSrc(io_out_bits_retToSrc),
    .io_out_bits_traceTag(io_out_bits_traceTag),
    .io_out_bits_mpam_perfMonGroup(io_out_bits_mpam_perfMonGroup),
    .io_out_bits_mpam_partID(io_out_bits_mpam_partID),
    .io_out_bits_mpam_mpamNS(io_out_bits_mpam_mpamNS),
    .io_state_state(io_state_state),
    .io_reclaimLCredit(io_reclaimLCredit)
  );
endmodule
