// =============================================================================
//  RRArbiterInit_11 —— 8 输入 round-robin 仲裁器 (Chisel RRArbiter)  可读实现
// -----------------------------------------------------------------------------
//  对应 `chisel3.util.RRArbiter(gen, 8)` (OpenLLC/L2 CHI TXREQ 通道)。单个 3 位
//  lastGrant 寄存器记忆上次胜者下标; 本轮优先从 "下标 > lastGrant" 的 valid 里取最低
//  下标 (validMask 轮), 若该集合空则退化到对全部 valids 取固定最低下标 (baseChoice)。
//  胜者 fire (io_out_ready & io_out_valid) 时 lastGrant <- 胜者下标。
//
//  与 golden 逐位等价:
//    grantMask[i] = (lastGrant < i)              i=1..7  (index 0 无 mask 项)
//    validMask[i] = io_in_i_valid & grantMask[i]
//    chosen = validMask 里最低下标; 若 validMask 全 0 ⇒ 全 valids 里最低下标, 全 0 ⇒ 7
//    io_out_valid  = valids[chosen]
//    io_in_i_ready = (第 i 路在本轮被 grant) & io_out_ready
//  ready 表达式按 golden 的两段式 (masked 轮 grant 或 baseChoice grant) 重建。
// =============================================================================
module RRArbiterInit_11(
  input         clock,
  input         reset,
  output        io_in_0_ready,
  input         io_in_0_valid,
  input  [11:0] io_in_0_bits_txnID,
  input  [6:0]  io_in_0_bits_opcode,
  input  [2:0]  io_in_0_bits_size,
  input  [47:0] io_in_0_bits_addr,
  input         io_in_0_bits_allowRetry,
  input  [1:0]  io_in_0_bits_order,
  input  [3:0]  io_in_0_bits_pCrdType,
  input         io_in_0_bits_memAttr_device,
  input         io_in_0_bits_memAttr_ewa,
  output        io_in_1_ready,
  input         io_in_1_valid,
  input  [11:0] io_in_1_bits_txnID,
  input  [6:0]  io_in_1_bits_opcode,
  input  [2:0]  io_in_1_bits_size,
  input  [47:0] io_in_1_bits_addr,
  input         io_in_1_bits_allowRetry,
  input  [1:0]  io_in_1_bits_order,
  input  [3:0]  io_in_1_bits_pCrdType,
  input         io_in_1_bits_memAttr_device,
  input         io_in_1_bits_memAttr_ewa,
  output        io_in_2_ready,
  input         io_in_2_valid,
  input  [11:0] io_in_2_bits_txnID,
  input  [6:0]  io_in_2_bits_opcode,
  input  [2:0]  io_in_2_bits_size,
  input  [47:0] io_in_2_bits_addr,
  input         io_in_2_bits_allowRetry,
  input  [1:0]  io_in_2_bits_order,
  input  [3:0]  io_in_2_bits_pCrdType,
  input         io_in_2_bits_memAttr_device,
  input         io_in_2_bits_memAttr_ewa,
  output        io_in_3_ready,
  input         io_in_3_valid,
  input  [11:0] io_in_3_bits_txnID,
  input  [6:0]  io_in_3_bits_opcode,
  input  [2:0]  io_in_3_bits_size,
  input  [47:0] io_in_3_bits_addr,
  input         io_in_3_bits_allowRetry,
  input  [1:0]  io_in_3_bits_order,
  input  [3:0]  io_in_3_bits_pCrdType,
  input         io_in_3_bits_memAttr_device,
  input         io_in_3_bits_memAttr_ewa,
  output        io_in_4_ready,
  input         io_in_4_valid,
  input  [11:0] io_in_4_bits_txnID,
  input  [6:0]  io_in_4_bits_opcode,
  input  [2:0]  io_in_4_bits_size,
  input  [47:0] io_in_4_bits_addr,
  input         io_in_4_bits_allowRetry,
  input  [1:0]  io_in_4_bits_order,
  input  [3:0]  io_in_4_bits_pCrdType,
  input         io_in_4_bits_memAttr_device,
  input         io_in_4_bits_memAttr_ewa,
  output        io_in_5_ready,
  input         io_in_5_valid,
  input  [11:0] io_in_5_bits_txnID,
  input  [6:0]  io_in_5_bits_opcode,
  input  [2:0]  io_in_5_bits_size,
  input  [47:0] io_in_5_bits_addr,
  input         io_in_5_bits_allowRetry,
  input  [1:0]  io_in_5_bits_order,
  input  [3:0]  io_in_5_bits_pCrdType,
  input         io_in_5_bits_memAttr_device,
  input         io_in_5_bits_memAttr_ewa,
  output        io_in_6_ready,
  input         io_in_6_valid,
  input  [11:0] io_in_6_bits_txnID,
  input  [6:0]  io_in_6_bits_opcode,
  input  [2:0]  io_in_6_bits_size,
  input  [47:0] io_in_6_bits_addr,
  input         io_in_6_bits_allowRetry,
  input  [1:0]  io_in_6_bits_order,
  input  [3:0]  io_in_6_bits_pCrdType,
  input         io_in_6_bits_memAttr_device,
  input         io_in_6_bits_memAttr_ewa,
  output        io_in_7_ready,
  input         io_in_7_valid,
  input  [11:0] io_in_7_bits_txnID,
  input  [6:0]  io_in_7_bits_opcode,
  input  [2:0]  io_in_7_bits_size,
  input  [47:0] io_in_7_bits_addr,
  input         io_in_7_bits_allowRetry,
  input  [1:0]  io_in_7_bits_order,
  input  [3:0]  io_in_7_bits_pCrdType,
  input         io_in_7_bits_memAttr_device,
  input         io_in_7_bits_memAttr_ewa,
  input         io_out_ready,
  output        io_out_valid,
  output [11:0] io_out_bits_txnID,
  output [6:0]  io_out_bits_opcode,
  output [2:0]  io_out_bits_size,
  output [47:0] io_out_bits_addr,
  output        io_out_bits_allowRetry,
  output [1:0]  io_out_bits_order,
  output [3:0]  io_out_bits_pCrdType,
  output        io_out_bits_memAttr_device,
  output        io_out_bits_memAttr_ewa
);

  xs_RRArbiterInit_11_core u_core (
    .clock(clock), .reset(reset),
    .io_in_0_ready(io_in_0_ready), .io_in_0_valid(io_in_0_valid),
    .io_in_0_bits_txnID(io_in_0_bits_txnID), .io_in_0_bits_opcode(io_in_0_bits_opcode),
    .io_in_0_bits_size(io_in_0_bits_size), .io_in_0_bits_addr(io_in_0_bits_addr),
    .io_in_0_bits_allowRetry(io_in_0_bits_allowRetry), .io_in_0_bits_order(io_in_0_bits_order),
    .io_in_0_bits_pCrdType(io_in_0_bits_pCrdType),
    .io_in_0_bits_memAttr_device(io_in_0_bits_memAttr_device), .io_in_0_bits_memAttr_ewa(io_in_0_bits_memAttr_ewa),
    .io_in_1_ready(io_in_1_ready), .io_in_1_valid(io_in_1_valid),
    .io_in_1_bits_txnID(io_in_1_bits_txnID), .io_in_1_bits_opcode(io_in_1_bits_opcode),
    .io_in_1_bits_size(io_in_1_bits_size), .io_in_1_bits_addr(io_in_1_bits_addr),
    .io_in_1_bits_allowRetry(io_in_1_bits_allowRetry), .io_in_1_bits_order(io_in_1_bits_order),
    .io_in_1_bits_pCrdType(io_in_1_bits_pCrdType),
    .io_in_1_bits_memAttr_device(io_in_1_bits_memAttr_device), .io_in_1_bits_memAttr_ewa(io_in_1_bits_memAttr_ewa),
    .io_in_2_ready(io_in_2_ready), .io_in_2_valid(io_in_2_valid),
    .io_in_2_bits_txnID(io_in_2_bits_txnID), .io_in_2_bits_opcode(io_in_2_bits_opcode),
    .io_in_2_bits_size(io_in_2_bits_size), .io_in_2_bits_addr(io_in_2_bits_addr),
    .io_in_2_bits_allowRetry(io_in_2_bits_allowRetry), .io_in_2_bits_order(io_in_2_bits_order),
    .io_in_2_bits_pCrdType(io_in_2_bits_pCrdType),
    .io_in_2_bits_memAttr_device(io_in_2_bits_memAttr_device), .io_in_2_bits_memAttr_ewa(io_in_2_bits_memAttr_ewa),
    .io_in_3_ready(io_in_3_ready), .io_in_3_valid(io_in_3_valid),
    .io_in_3_bits_txnID(io_in_3_bits_txnID), .io_in_3_bits_opcode(io_in_3_bits_opcode),
    .io_in_3_bits_size(io_in_3_bits_size), .io_in_3_bits_addr(io_in_3_bits_addr),
    .io_in_3_bits_allowRetry(io_in_3_bits_allowRetry), .io_in_3_bits_order(io_in_3_bits_order),
    .io_in_3_bits_pCrdType(io_in_3_bits_pCrdType),
    .io_in_3_bits_memAttr_device(io_in_3_bits_memAttr_device), .io_in_3_bits_memAttr_ewa(io_in_3_bits_memAttr_ewa),
    .io_in_4_ready(io_in_4_ready), .io_in_4_valid(io_in_4_valid),
    .io_in_4_bits_txnID(io_in_4_bits_txnID), .io_in_4_bits_opcode(io_in_4_bits_opcode),
    .io_in_4_bits_size(io_in_4_bits_size), .io_in_4_bits_addr(io_in_4_bits_addr),
    .io_in_4_bits_allowRetry(io_in_4_bits_allowRetry), .io_in_4_bits_order(io_in_4_bits_order),
    .io_in_4_bits_pCrdType(io_in_4_bits_pCrdType),
    .io_in_4_bits_memAttr_device(io_in_4_bits_memAttr_device), .io_in_4_bits_memAttr_ewa(io_in_4_bits_memAttr_ewa),
    .io_in_5_ready(io_in_5_ready), .io_in_5_valid(io_in_5_valid),
    .io_in_5_bits_txnID(io_in_5_bits_txnID), .io_in_5_bits_opcode(io_in_5_bits_opcode),
    .io_in_5_bits_size(io_in_5_bits_size), .io_in_5_bits_addr(io_in_5_bits_addr),
    .io_in_5_bits_allowRetry(io_in_5_bits_allowRetry), .io_in_5_bits_order(io_in_5_bits_order),
    .io_in_5_bits_pCrdType(io_in_5_bits_pCrdType),
    .io_in_5_bits_memAttr_device(io_in_5_bits_memAttr_device), .io_in_5_bits_memAttr_ewa(io_in_5_bits_memAttr_ewa),
    .io_in_6_ready(io_in_6_ready), .io_in_6_valid(io_in_6_valid),
    .io_in_6_bits_txnID(io_in_6_bits_txnID), .io_in_6_bits_opcode(io_in_6_bits_opcode),
    .io_in_6_bits_size(io_in_6_bits_size), .io_in_6_bits_addr(io_in_6_bits_addr),
    .io_in_6_bits_allowRetry(io_in_6_bits_allowRetry), .io_in_6_bits_order(io_in_6_bits_order),
    .io_in_6_bits_pCrdType(io_in_6_bits_pCrdType),
    .io_in_6_bits_memAttr_device(io_in_6_bits_memAttr_device), .io_in_6_bits_memAttr_ewa(io_in_6_bits_memAttr_ewa),
    .io_in_7_ready(io_in_7_ready), .io_in_7_valid(io_in_7_valid),
    .io_in_7_bits_txnID(io_in_7_bits_txnID), .io_in_7_bits_opcode(io_in_7_bits_opcode),
    .io_in_7_bits_size(io_in_7_bits_size), .io_in_7_bits_addr(io_in_7_bits_addr),
    .io_in_7_bits_allowRetry(io_in_7_bits_allowRetry), .io_in_7_bits_order(io_in_7_bits_order),
    .io_in_7_bits_pCrdType(io_in_7_bits_pCrdType),
    .io_in_7_bits_memAttr_device(io_in_7_bits_memAttr_device), .io_in_7_bits_memAttr_ewa(io_in_7_bits_memAttr_ewa),
    .io_out_ready(io_out_ready), .io_out_valid(io_out_valid),
    .io_out_bits_txnID(io_out_bits_txnID), .io_out_bits_opcode(io_out_bits_opcode),
    .io_out_bits_size(io_out_bits_size), .io_out_bits_addr(io_out_bits_addr),
    .io_out_bits_allowRetry(io_out_bits_allowRetry), .io_out_bits_order(io_out_bits_order),
    .io_out_bits_pCrdType(io_out_bits_pCrdType),
    .io_out_bits_memAttr_device(io_out_bits_memAttr_device), .io_out_bits_memAttr_ewa(io_out_bits_memAttr_ewa)
  );
endmodule

