// 自动生成 scripts/gen_chi_channel.py —— 勿手改
module TXREQ(
  input clock,
  input reset,
  input io_pipeReq_valid,
  input [10:0] io_pipeReq_bits_tgtID,
  input [10:0] io_pipeReq_bits_srcID,
  input [11:0] io_pipeReq_bits_txnID,
  input [6:0] io_pipeReq_bits_opcode,
  input [47:0] io_pipeReq_bits_addr,
  input io_pipeReq_bits_likelyshared,
  input io_pipeReq_bits_allowRetry,
  input [3:0] io_pipeReq_bits_pCrdType,
  input io_pipeReq_bits_memAttr_allocate,
  input io_pipeReq_bits_memAttr_cacheable,
  input io_pipeReq_bits_memAttr_device,
  input io_pipeReq_bits_memAttr_ewa,
  input io_pipeReq_bits_expCompAck,
  output io_mshrReq_ready,
  input io_mshrReq_valid,
  input [3:0] io_mshrReq_bits_qos,
  input [10:0] io_mshrReq_bits_tgtID,
  input [11:0] io_mshrReq_bits_txnID,
  input [6:0] io_mshrReq_bits_opcode,
  input [2:0] io_mshrReq_bits_size,
  input [47:0] io_mshrReq_bits_addr,
  input io_mshrReq_bits_likelyshared,
  input io_mshrReq_bits_allowRetry,
  input [3:0] io_mshrReq_bits_pCrdType,
  input io_mshrReq_bits_memAttr_allocate,
  input io_mshrReq_bits_memAttr_cacheable,
  input io_mshrReq_bits_memAttr_ewa,
  input io_mshrReq_bits_snpAttr,
  input io_mshrReq_bits_expCompAck,
  input io_out_ready,
  output io_out_valid,
  output [3:0] io_out_bits_qos,
  output [11:0] io_out_bits_txnID,
  output [10:0] io_out_bits_returnNID,
  output io_out_bits_stashNIDValid,
  output [11:0] io_out_bits_returnTxnID,
  output [6:0] io_out_bits_opcode,
  output [47:0] io_out_bits_addr,
  output io_out_bits_ns,
  output io_out_bits_likelyshared,
  output io_out_bits_allowRetry,
  output [1:0] io_out_bits_order,
  output [3:0] io_out_bits_pCrdType,
  output io_out_bits_memAttr_allocate,
  output io_out_bits_memAttr_cacheable,
  output io_out_bits_memAttr_device,
  output io_out_bits_memAttr_ewa,
  output io_out_bits_snpAttr,
  output [7:0] io_out_bits_lpIDWithPadding,
  output io_out_bits_snoopMe,
  output io_out_bits_expCompAck,
  output [1:0] io_out_bits_tagOp,
  output io_out_bits_traceTag,
  output io_out_bits_mpam_perfMonGroup,
  output [8:0] io_out_bits_mpam_partID,
  output io_out_bits_mpam_mpamNS,
  output [3:0] io_out_bits_rsvdc,
  input io_pipeStatusVec_1_valid,
  input [2:0] io_pipeStatusVec_1_bits_txChannel,
  input io_pipeStatusVec_1_bits_mshrTask,
  input io_pipeStatusVec_2_valid,
  input [2:0] io_pipeStatusVec_2_bits_txChannel,
  input io_pipeStatusVec_2_bits_mshrTask,
  input io_pipeStatusVec_3_valid,
  input [2:0] io_pipeStatusVec_3_bits_txChannel,
  input io_pipeStatusVec_3_bits_mshrTask,
  input io_pipeStatusVec_4_valid,
  input [2:0] io_pipeStatusVec_4_bits_txChannel,
  input io_pipeStatusVec_4_bits_mshrTask,
  output io_toReqArb_blockMSHRReqEntrance,
  input [1:0] io_sliceId
);
  xs_TXREQ_core u_core (
    .clock(clock),
    .reset(reset),
    .io_pipeReq_valid(io_pipeReq_valid),
    .io_pipeReq_bits_tgtID(io_pipeReq_bits_tgtID),
    .io_pipeReq_bits_srcID(io_pipeReq_bits_srcID),
    .io_pipeReq_bits_txnID(io_pipeReq_bits_txnID),
    .io_pipeReq_bits_opcode(io_pipeReq_bits_opcode),
    .io_pipeReq_bits_addr(io_pipeReq_bits_addr),
    .io_pipeReq_bits_likelyshared(io_pipeReq_bits_likelyshared),
    .io_pipeReq_bits_allowRetry(io_pipeReq_bits_allowRetry),
    .io_pipeReq_bits_pCrdType(io_pipeReq_bits_pCrdType),
    .io_pipeReq_bits_memAttr_allocate(io_pipeReq_bits_memAttr_allocate),
    .io_pipeReq_bits_memAttr_cacheable(io_pipeReq_bits_memAttr_cacheable),
    .io_pipeReq_bits_memAttr_device(io_pipeReq_bits_memAttr_device),
    .io_pipeReq_bits_memAttr_ewa(io_pipeReq_bits_memAttr_ewa),
    .io_pipeReq_bits_expCompAck(io_pipeReq_bits_expCompAck),
    .io_mshrReq_ready(io_mshrReq_ready),
    .io_mshrReq_valid(io_mshrReq_valid),
    .io_mshrReq_bits_qos(io_mshrReq_bits_qos),
    .io_mshrReq_bits_tgtID(io_mshrReq_bits_tgtID),
    .io_mshrReq_bits_txnID(io_mshrReq_bits_txnID),
    .io_mshrReq_bits_opcode(io_mshrReq_bits_opcode),
    .io_mshrReq_bits_size(io_mshrReq_bits_size),
    .io_mshrReq_bits_addr(io_mshrReq_bits_addr),
    .io_mshrReq_bits_likelyshared(io_mshrReq_bits_likelyshared),
    .io_mshrReq_bits_allowRetry(io_mshrReq_bits_allowRetry),
    .io_mshrReq_bits_pCrdType(io_mshrReq_bits_pCrdType),
    .io_mshrReq_bits_memAttr_allocate(io_mshrReq_bits_memAttr_allocate),
    .io_mshrReq_bits_memAttr_cacheable(io_mshrReq_bits_memAttr_cacheable),
    .io_mshrReq_bits_memAttr_ewa(io_mshrReq_bits_memAttr_ewa),
    .io_mshrReq_bits_snpAttr(io_mshrReq_bits_snpAttr),
    .io_mshrReq_bits_expCompAck(io_mshrReq_bits_expCompAck),
    .io_out_ready(io_out_ready),
    .io_out_valid(io_out_valid),
    .io_out_bits_qos(io_out_bits_qos),
    .io_out_bits_txnID(io_out_bits_txnID),
    .io_out_bits_returnNID(io_out_bits_returnNID),
    .io_out_bits_stashNIDValid(io_out_bits_stashNIDValid),
    .io_out_bits_returnTxnID(io_out_bits_returnTxnID),
    .io_out_bits_opcode(io_out_bits_opcode),
    .io_out_bits_addr(io_out_bits_addr),
    .io_out_bits_ns(io_out_bits_ns),
    .io_out_bits_likelyshared(io_out_bits_likelyshared),
    .io_out_bits_allowRetry(io_out_bits_allowRetry),
    .io_out_bits_order(io_out_bits_order),
    .io_out_bits_pCrdType(io_out_bits_pCrdType),
    .io_out_bits_memAttr_allocate(io_out_bits_memAttr_allocate),
    .io_out_bits_memAttr_cacheable(io_out_bits_memAttr_cacheable),
    .io_out_bits_memAttr_device(io_out_bits_memAttr_device),
    .io_out_bits_memAttr_ewa(io_out_bits_memAttr_ewa),
    .io_out_bits_snpAttr(io_out_bits_snpAttr),
    .io_out_bits_lpIDWithPadding(io_out_bits_lpIDWithPadding),
    .io_out_bits_snoopMe(io_out_bits_snoopMe),
    .io_out_bits_expCompAck(io_out_bits_expCompAck),
    .io_out_bits_tagOp(io_out_bits_tagOp),
    .io_out_bits_traceTag(io_out_bits_traceTag),
    .io_out_bits_mpam_perfMonGroup(io_out_bits_mpam_perfMonGroup),
    .io_out_bits_mpam_partID(io_out_bits_mpam_partID),
    .io_out_bits_mpam_mpamNS(io_out_bits_mpam_mpamNS),
    .io_out_bits_rsvdc(io_out_bits_rsvdc),
    .io_pipeStatusVec_1_valid(io_pipeStatusVec_1_valid),
    .io_pipeStatusVec_1_bits_txChannel(io_pipeStatusVec_1_bits_txChannel),
    .io_pipeStatusVec_1_bits_mshrTask(io_pipeStatusVec_1_bits_mshrTask),
    .io_pipeStatusVec_2_valid(io_pipeStatusVec_2_valid),
    .io_pipeStatusVec_2_bits_txChannel(io_pipeStatusVec_2_bits_txChannel),
    .io_pipeStatusVec_2_bits_mshrTask(io_pipeStatusVec_2_bits_mshrTask),
    .io_pipeStatusVec_3_valid(io_pipeStatusVec_3_valid),
    .io_pipeStatusVec_3_bits_txChannel(io_pipeStatusVec_3_bits_txChannel),
    .io_pipeStatusVec_3_bits_mshrTask(io_pipeStatusVec_3_bits_mshrTask),
    .io_pipeStatusVec_4_valid(io_pipeStatusVec_4_valid),
    .io_pipeStatusVec_4_bits_txChannel(io_pipeStatusVec_4_bits_txChannel),
    .io_pipeStatusVec_4_bits_mshrTask(io_pipeStatusVec_4_bits_mshrTask),
    .io_toReqArb_blockMSHRReqEntrance(io_toReqArb_blockMSHRReqEntrance),
    .io_sliceId(io_sliceId)
  );
endmodule
