// 自动生成 scripts/gen_chi_channel.py —— 勿手改
module TXRSP(
  input clock,
  input reset,
  input io_pipeRsp_valid,
  input [2:0] io_pipeRsp_bits_txChannel,
  input io_pipeRsp_bits_denied,
  input [10:0] io_pipeRsp_bits_tgtID,
  input [10:0] io_pipeRsp_bits_srcID,
  input [11:0] io_pipeRsp_bits_txnID,
  input [11:0] io_pipeRsp_bits_dbID,
  input [6:0] io_pipeRsp_bits_chiOpcode,
  input [2:0] io_pipeRsp_bits_resp,
  input [2:0] io_pipeRsp_bits_fwdState,
  input [3:0] io_pipeRsp_bits_pCrdType,
  input io_pipeRsp_bits_traceTag,
  output io_mshrRsp_ready,
  input io_mshrRsp_valid,
  input [10:0] io_mshrRsp_bits_tgtID,
  input [11:0] io_mshrRsp_bits_txnID,
  input [4:0] io_mshrRsp_bits_opcode,
  input io_mshrRsp_bits_traceTag,
  input io_out_ready,
  output io_out_valid,
  output [3:0] io_out_bits_qos,
  output [10:0] io_out_bits_tgtID,
  output [11:0] io_out_bits_txnID,
  output [4:0] io_out_bits_opcode,
  output [1:0] io_out_bits_respErr,
  output [2:0] io_out_bits_resp,
  output [2:0] io_out_bits_fwdState,
  output [2:0] io_out_bits_cBusy,
  output [11:0] io_out_bits_dbID,
  output [3:0] io_out_bits_pCrdType,
  output [1:0] io_out_bits_tagOp,
  output io_out_bits_traceTag,
  input io_pipeStatusVec_1_valid,
  input [2:0] io_pipeStatusVec_1_bits_channel,
  input [2:0] io_pipeStatusVec_1_bits_txChannel,
  input io_pipeStatusVec_1_bits_mshrTask,
  input io_pipeStatusVec_2_valid,
  input [2:0] io_pipeStatusVec_2_bits_channel,
  input [2:0] io_pipeStatusVec_2_bits_txChannel,
  input io_pipeStatusVec_2_bits_mshrTask,
  input io_pipeStatusVec_3_valid,
  input [2:0] io_pipeStatusVec_3_bits_channel,
  input [2:0] io_pipeStatusVec_3_bits_txChannel,
  input io_pipeStatusVec_3_bits_mshrTask,
  input io_pipeStatusVec_4_valid,
  input [2:0] io_pipeStatusVec_4_bits_channel,
  input [2:0] io_pipeStatusVec_4_bits_txChannel,
  input io_pipeStatusVec_4_bits_mshrTask,
  output io_toReqArb_blockMSHRReqEntrance,
  output io_toReqArb_blockSinkBReqEntrance
);
  xs_TXRSP_core u_core (
    .clock(clock),
    .reset(reset),
    .io_pipeRsp_valid(io_pipeRsp_valid),
    .io_pipeRsp_bits_txChannel(io_pipeRsp_bits_txChannel),
    .io_pipeRsp_bits_denied(io_pipeRsp_bits_denied),
    .io_pipeRsp_bits_tgtID(io_pipeRsp_bits_tgtID),
    .io_pipeRsp_bits_srcID(io_pipeRsp_bits_srcID),
    .io_pipeRsp_bits_txnID(io_pipeRsp_bits_txnID),
    .io_pipeRsp_bits_dbID(io_pipeRsp_bits_dbID),
    .io_pipeRsp_bits_chiOpcode(io_pipeRsp_bits_chiOpcode),
    .io_pipeRsp_bits_resp(io_pipeRsp_bits_resp),
    .io_pipeRsp_bits_fwdState(io_pipeRsp_bits_fwdState),
    .io_pipeRsp_bits_pCrdType(io_pipeRsp_bits_pCrdType),
    .io_pipeRsp_bits_traceTag(io_pipeRsp_bits_traceTag),
    .io_mshrRsp_ready(io_mshrRsp_ready),
    .io_mshrRsp_valid(io_mshrRsp_valid),
    .io_mshrRsp_bits_tgtID(io_mshrRsp_bits_tgtID),
    .io_mshrRsp_bits_txnID(io_mshrRsp_bits_txnID),
    .io_mshrRsp_bits_opcode(io_mshrRsp_bits_opcode),
    .io_mshrRsp_bits_traceTag(io_mshrRsp_bits_traceTag),
    .io_out_ready(io_out_ready),
    .io_out_valid(io_out_valid),
    .io_out_bits_qos(io_out_bits_qos),
    .io_out_bits_tgtID(io_out_bits_tgtID),
    .io_out_bits_txnID(io_out_bits_txnID),
    .io_out_bits_opcode(io_out_bits_opcode),
    .io_out_bits_respErr(io_out_bits_respErr),
    .io_out_bits_resp(io_out_bits_resp),
    .io_out_bits_fwdState(io_out_bits_fwdState),
    .io_out_bits_cBusy(io_out_bits_cBusy),
    .io_out_bits_dbID(io_out_bits_dbID),
    .io_out_bits_pCrdType(io_out_bits_pCrdType),
    .io_out_bits_tagOp(io_out_bits_tagOp),
    .io_out_bits_traceTag(io_out_bits_traceTag),
    .io_pipeStatusVec_1_valid(io_pipeStatusVec_1_valid),
    .io_pipeStatusVec_1_bits_channel(io_pipeStatusVec_1_bits_channel),
    .io_pipeStatusVec_1_bits_txChannel(io_pipeStatusVec_1_bits_txChannel),
    .io_pipeStatusVec_1_bits_mshrTask(io_pipeStatusVec_1_bits_mshrTask),
    .io_pipeStatusVec_2_valid(io_pipeStatusVec_2_valid),
    .io_pipeStatusVec_2_bits_channel(io_pipeStatusVec_2_bits_channel),
    .io_pipeStatusVec_2_bits_txChannel(io_pipeStatusVec_2_bits_txChannel),
    .io_pipeStatusVec_2_bits_mshrTask(io_pipeStatusVec_2_bits_mshrTask),
    .io_pipeStatusVec_3_valid(io_pipeStatusVec_3_valid),
    .io_pipeStatusVec_3_bits_channel(io_pipeStatusVec_3_bits_channel),
    .io_pipeStatusVec_3_bits_txChannel(io_pipeStatusVec_3_bits_txChannel),
    .io_pipeStatusVec_3_bits_mshrTask(io_pipeStatusVec_3_bits_mshrTask),
    .io_pipeStatusVec_4_valid(io_pipeStatusVec_4_valid),
    .io_pipeStatusVec_4_bits_channel(io_pipeStatusVec_4_bits_channel),
    .io_pipeStatusVec_4_bits_txChannel(io_pipeStatusVec_4_bits_txChannel),
    .io_pipeStatusVec_4_bits_mshrTask(io_pipeStatusVec_4_bits_mshrTask),
    .io_toReqArb_blockMSHRReqEntrance(io_toReqArb_blockMSHRReqEntrance),
    .io_toReqArb_blockSinkBReqEntrance(io_toReqArb_blockSinkBReqEntrance)
  );
endmodule
