// 自动生成 scripts/gen_chi_channel.py —— 勿手改
module TXSNP(
  output io_task_ready,
  input io_task_valid,
  input [11:0] io_task_bits_set,
  input [1:0] io_task_bits_bank,
  input [27:0] io_task_bits_tag,
  input io_task_bits_snpVec_0,
  input [11:0] io_task_bits_txnID,
  input [10:0] io_task_bits_fwdNID,
  input [11:0] io_task_bits_fwdTxnID,
  input [6:0] io_task_bits_chiOpcode,
  input io_task_bits_retToSrc,
  input io_task_bits_doNotGoToSD,
  input io_snp_ready,
  output io_snp_valid,
  output [11:0] io_snp_bits_txnID,
  output [10:0] io_snp_bits_fwdNID,
  output [11:0] io_snp_bits_fwdTxnID,
  output [4:0] io_snp_bits_opcode,
  output [44:0] io_snp_bits_addr,
  output io_snp_bits_doNotGoToSD,
  output io_snp_bits_retToSrc,
  output io_snpMask_0
);
  xs_TXSNP_core u_core (
    .io_task_ready(io_task_ready),
    .io_task_valid(io_task_valid),
    .io_task_bits_set(io_task_bits_set),
    .io_task_bits_bank(io_task_bits_bank),
    .io_task_bits_tag(io_task_bits_tag),
    .io_task_bits_snpVec_0(io_task_bits_snpVec_0),
    .io_task_bits_txnID(io_task_bits_txnID),
    .io_task_bits_fwdNID(io_task_bits_fwdNID),
    .io_task_bits_fwdTxnID(io_task_bits_fwdTxnID),
    .io_task_bits_chiOpcode(io_task_bits_chiOpcode),
    .io_task_bits_retToSrc(io_task_bits_retToSrc),
    .io_task_bits_doNotGoToSD(io_task_bits_doNotGoToSD),
    .io_snp_ready(io_snp_ready),
    .io_snp_valid(io_snp_valid),
    .io_snp_bits_txnID(io_snp_bits_txnID),
    .io_snp_bits_fwdNID(io_snp_bits_fwdNID),
    .io_snp_bits_fwdTxnID(io_snp_bits_fwdTxnID),
    .io_snp_bits_opcode(io_snp_bits_opcode),
    .io_snp_bits_addr(io_snp_bits_addr),
    .io_snp_bits_doNotGoToSD(io_snp_bits_doNotGoToSD),
    .io_snp_bits_retToSrc(io_snp_bits_retToSrc),
    .io_snpMask_0(io_snpMask_0)
  );
endmodule
