// 自动生成：scripts/gen_missqueue.py —— 勿手改
module MissQueue_xs(
  input  clock,
  input  reset,
  output io_req_ready,
  input  io_req_valid,
  input  [3:0] io_req_bits_source,
  input  [2:0] io_req_bits_pf_source,
  input  [4:0] io_req_bits_cmd,
  input  [47:0] io_req_bits_addr,
  input  [49:0] io_req_bits_vaddr,
  input  io_req_bits_full_overwrite,
  input  [2:0] io_req_bits_word_idx,
  input  [127:0] io_req_bits_amo_data,
  input  [15:0] io_req_bits_amo_mask,
  input  [127:0] io_req_bits_amo_cmp,
  input  [1:0] io_req_bits_req_coh_state,
  input  [5:0] io_req_bits_id,
  input  io_req_bits_isBtoT,
  input  [3:0] io_req_bits_occupy_way,
  input  io_req_bits_cancel,
  input  [511:0] io_req_bits_store_data,
  input  [63:0] io_req_bits_store_mask,
  output [3:0] io_resp_id,
  output io_resp_handled,
  output io_resp_merged,
  output io_cmo_req_ready,
  input  io_cmo_req_valid,
  input  [2:0] io_cmo_req_bits_opcode,
  input  [63:0] io_cmo_req_bits_address,
  input  io_cmo_resp_ready,
  output io_cmo_resp_valid,
  output io_cmo_resp_bits_nderr,
  input  [3:0] io_queryMQ_0_req_bits_source,
  input  [47:0] io_queryMQ_0_req_bits_addr,
  input  [49:0] io_queryMQ_0_req_bits_vaddr,
  output io_queryMQ_0_ready,
  input  [3:0] io_queryMQ_1_req_bits_source,
  input  [47:0] io_queryMQ_1_req_bits_addr,
  input  [49:0] io_queryMQ_1_req_bits_vaddr,
  output io_queryMQ_1_ready,
  input  [3:0] io_queryMQ_2_req_bits_source,
  input  [47:0] io_queryMQ_2_req_bits_addr,
  input  [49:0] io_queryMQ_2_req_bits_vaddr,
  output io_queryMQ_2_ready,
  input  [3:0] io_queryMQ_3_req_bits_source,
  input  [47:0] io_queryMQ_3_req_bits_addr,
  input  [49:0] io_queryMQ_3_req_bits_vaddr,
  output io_queryMQ_3_ready,
  input  io_mem_acquire_ready,
  output io_mem_acquire_valid,
  output [3:0] io_mem_acquire_bits_opcode,
  output [2:0] io_mem_acquire_bits_param,
  output [2:0] io_mem_acquire_bits_size,
  output [5:0] io_mem_acquire_bits_source,
  output [47:0] io_mem_acquire_bits_address,
  output [1:0] io_mem_acquire_bits_user_alias,
  output [43:0] io_mem_acquire_bits_user_vaddr,
  output [4:0] io_mem_acquire_bits_user_reqSource,
  output io_mem_acquire_bits_user_needHint,
  output io_mem_acquire_bits_echo_isKeyword,
  output [31:0] io_mem_acquire_bits_mask,
  output io_mem_grant_ready,
  input  io_mem_grant_valid,
  input  [3:0] io_mem_grant_bits_opcode,
  input  [1:0] io_mem_grant_bits_param,
  input  [2:0] io_mem_grant_bits_size,
  input  [5:0] io_mem_grant_bits_source,
  input  [9:0] io_mem_grant_bits_sink,
  input  io_mem_grant_bits_denied,
  input  [255:0] io_mem_grant_bits_data,
  input  io_mem_grant_bits_corrupt,
  input  io_mem_finish_ready,
  output io_mem_finish_valid,
  output [9:0] io_mem_finish_bits_sink,
  input  io_l2_hint_valid,
  input  [3:0] io_l2_hint_bits_sourceId,
  input  io_main_pipe_req_ready,
  output io_main_pipe_req_valid,
  output io_main_pipe_req_bits_miss,
  output [3:0] io_main_pipe_req_bits_miss_id,
  output [3:0] io_main_pipe_req_bits_occupy_way,
  output io_main_pipe_req_bits_miss_fail_cause_evict_btot,
  output [3:0] io_main_pipe_req_bits_source,
  output [4:0] io_main_pipe_req_bits_cmd,
  output [49:0] io_main_pipe_req_bits_vaddr,
  output [47:0] io_main_pipe_req_bits_addr,
  output [2:0] io_main_pipe_req_bits_word_idx,
  output [127:0] io_main_pipe_req_bits_amo_data,
  output [15:0] io_main_pipe_req_bits_amo_mask,
  output [127:0] io_main_pipe_req_bits_amo_cmp,
  output [2:0] io_main_pipe_req_bits_pf_source,
  output io_main_pipe_req_bits_access,
  output [5:0] io_main_pipe_req_bits_id,
  input  io_main_pipe_resp_valid,
  input  [3:0] io_main_pipe_resp_bits_miss_id,
  input  io_main_pipe_resp_bits_ack_miss_queue,
  input  io_mainpipe_info_s2_valid,
  input  [3:0] io_mainpipe_info_s2_miss_id,
  input  io_mainpipe_info_s2_replay_to_mq,
  input  io_mainpipe_info_s2_evict_BtoT_way,
  input  [3:0] io_mainpipe_info_s2_next_evict_way,
  input  io_mainpipe_info_s3_valid,
  input  [3:0] io_mainpipe_info_s3_miss_id,
  input  io_mainpipe_info_s3_refill_resp,
  output io_refill_info_valid,
  output [511:0] io_refill_info_bits_store_data,
  output [63:0] io_refill_info_bits_store_mask,
  output [1:0] io_refill_info_bits_miss_param,
  output io_refill_info_bits_error,
  input  [47:0] io_probe_req_bits_addr,
  input  [49:0] io_probe_req_bits_vaddr,
  output io_probe_block,
  input  [47:0] io_replace_req_bits_addr,
  input  [49:0] io_replace_req_bits_vaddr,
  output io_replace_block,
  input  [7:0] io_evict_set,
  output [3:0] io_btot_ways_for_set,
  input  [7:0] io_occupy_set_0,
  input  [7:0] io_occupy_set_1,
  input  [7:0] io_occupy_set_2,
  output io_occupy_fail_0,
  output io_occupy_fail_1,
  output io_occupy_fail_2,
  input  io_wbq_block_miss_req,
  input  io_forward_0_valid,
  input  [3:0] io_forward_0_mshrid,
  input  [47:0] io_forward_0_paddr,
  output io_forward_0_forward_mshr,
  output [7:0] io_forward_0_forwardData_0,
  output [7:0] io_forward_0_forwardData_1,
  output [7:0] io_forward_0_forwardData_2,
  output [7:0] io_forward_0_forwardData_3,
  output [7:0] io_forward_0_forwardData_4,
  output [7:0] io_forward_0_forwardData_5,
  output [7:0] io_forward_0_forwardData_6,
  output [7:0] io_forward_0_forwardData_7,
  output [7:0] io_forward_0_forwardData_8,
  output [7:0] io_forward_0_forwardData_9,
  output [7:0] io_forward_0_forwardData_10,
  output [7:0] io_forward_0_forwardData_11,
  output [7:0] io_forward_0_forwardData_12,
  output [7:0] io_forward_0_forwardData_13,
  output [7:0] io_forward_0_forwardData_14,
  output [7:0] io_forward_0_forwardData_15,
  output io_forward_0_forward_result_valid,
  output io_forward_0_corrupt,
  input  io_forward_1_valid,
  input  [3:0] io_forward_1_mshrid,
  input  [47:0] io_forward_1_paddr,
  output io_forward_1_forward_mshr,
  output [7:0] io_forward_1_forwardData_0,
  output [7:0] io_forward_1_forwardData_1,
  output [7:0] io_forward_1_forwardData_2,
  output [7:0] io_forward_1_forwardData_3,
  output [7:0] io_forward_1_forwardData_4,
  output [7:0] io_forward_1_forwardData_5,
  output [7:0] io_forward_1_forwardData_6,
  output [7:0] io_forward_1_forwardData_7,
  output [7:0] io_forward_1_forwardData_8,
  output [7:0] io_forward_1_forwardData_9,
  output [7:0] io_forward_1_forwardData_10,
  output [7:0] io_forward_1_forwardData_11,
  output [7:0] io_forward_1_forwardData_12,
  output [7:0] io_forward_1_forwardData_13,
  output [7:0] io_forward_1_forwardData_14,
  output [7:0] io_forward_1_forwardData_15,
  output io_forward_1_forward_result_valid,
  output io_forward_1_corrupt,
  input  io_forward_2_valid,
  input  [3:0] io_forward_2_mshrid,
  input  [47:0] io_forward_2_paddr,
  output io_forward_2_forward_mshr,
  output [7:0] io_forward_2_forwardData_0,
  output [7:0] io_forward_2_forwardData_1,
  output [7:0] io_forward_2_forwardData_2,
  output [7:0] io_forward_2_forwardData_3,
  output [7:0] io_forward_2_forwardData_4,
  output [7:0] io_forward_2_forwardData_5,
  output [7:0] io_forward_2_forwardData_6,
  output [7:0] io_forward_2_forwardData_7,
  output [7:0] io_forward_2_forwardData_8,
  output [7:0] io_forward_2_forwardData_9,
  output [7:0] io_forward_2_forwardData_10,
  output [7:0] io_forward_2_forwardData_11,
  output [7:0] io_forward_2_forwardData_12,
  output [7:0] io_forward_2_forwardData_13,
  output [7:0] io_forward_2_forwardData_14,
  output [7:0] io_forward_2_forwardData_15,
  output io_forward_2_forward_result_valid,
  output io_forward_2_corrupt,
  input  io_l2_pf_store_only,
  input  io_lqEmpty,
  output io_prefetch_info_naive_late_miss_prefetch,
  output io_prefetch_info_fdp_late_miss_prefetch,
  output io_prefetch_info_fdp_prefetch_monitor_cnt,
  output io_prefetch_info_fdp_total_prefetch,
  input  io_wfi_wfiReq,
  output io_wfi_wfiSafe,
  input  io_debugTopDown_robHeadVaddr_valid,
  input  [49:0] io_debugTopDown_robHeadVaddr_bits,
  output io_debugTopDown_robHeadMissInDCache,
  output io_l1Miss,
  output [5:0] io_perf_0_value,
  output [5:0] io_perf_1_value,
  output [5:0] io_perf_2_value,
  output [5:0] io_perf_3_value,
  output [5:0] io_perf_4_value
);
  xs_MissQueue_core u_core (
    .clock(clock),
    .reset(reset),
    .io_req_ready(io_req_ready),
    .io_req_valid(io_req_valid),
    .io_req_bits_source(io_req_bits_source),
    .io_req_bits_pf_source(io_req_bits_pf_source),
    .io_req_bits_cmd(io_req_bits_cmd),
    .io_req_bits_addr(io_req_bits_addr),
    .io_req_bits_vaddr(io_req_bits_vaddr),
    .io_req_bits_full_overwrite(io_req_bits_full_overwrite),
    .io_req_bits_word_idx(io_req_bits_word_idx),
    .io_req_bits_amo_data(io_req_bits_amo_data),
    .io_req_bits_amo_mask(io_req_bits_amo_mask),
    .io_req_bits_amo_cmp(io_req_bits_amo_cmp),
    .io_req_bits_req_coh_state(io_req_bits_req_coh_state),
    .io_req_bits_id(io_req_bits_id),
    .io_req_bits_isBtoT(io_req_bits_isBtoT),
    .io_req_bits_occupy_way(io_req_bits_occupy_way),
    .io_req_bits_cancel(io_req_bits_cancel),
    .io_req_bits_store_data(io_req_bits_store_data),
    .io_req_bits_store_mask(io_req_bits_store_mask),
    .io_resp_id(io_resp_id),
    .io_resp_handled(io_resp_handled),
    .io_resp_merged(io_resp_merged),
    .io_cmo_req_ready(io_cmo_req_ready),
    .io_cmo_req_valid(io_cmo_req_valid),
    .io_cmo_req_bits_opcode(io_cmo_req_bits_opcode),
    .io_cmo_req_bits_address(io_cmo_req_bits_address),
    .io_cmo_resp_ready(io_cmo_resp_ready),
    .io_cmo_resp_valid(io_cmo_resp_valid),
    .io_cmo_resp_bits_nderr(io_cmo_resp_bits_nderr),
    .io_queryMQ_0_req_bits_source(io_queryMQ_0_req_bits_source),
    .io_queryMQ_0_req_bits_addr(io_queryMQ_0_req_bits_addr),
    .io_queryMQ_0_req_bits_vaddr(io_queryMQ_0_req_bits_vaddr),
    .io_queryMQ_0_ready(io_queryMQ_0_ready),
    .io_queryMQ_1_req_bits_source(io_queryMQ_1_req_bits_source),
    .io_queryMQ_1_req_bits_addr(io_queryMQ_1_req_bits_addr),
    .io_queryMQ_1_req_bits_vaddr(io_queryMQ_1_req_bits_vaddr),
    .io_queryMQ_1_ready(io_queryMQ_1_ready),
    .io_queryMQ_2_req_bits_source(io_queryMQ_2_req_bits_source),
    .io_queryMQ_2_req_bits_addr(io_queryMQ_2_req_bits_addr),
    .io_queryMQ_2_req_bits_vaddr(io_queryMQ_2_req_bits_vaddr),
    .io_queryMQ_2_ready(io_queryMQ_2_ready),
    .io_queryMQ_3_req_bits_source(io_queryMQ_3_req_bits_source),
    .io_queryMQ_3_req_bits_addr(io_queryMQ_3_req_bits_addr),
    .io_queryMQ_3_req_bits_vaddr(io_queryMQ_3_req_bits_vaddr),
    .io_queryMQ_3_ready(io_queryMQ_3_ready),
    .io_mem_acquire_ready(io_mem_acquire_ready),
    .io_mem_acquire_valid(io_mem_acquire_valid),
    .io_mem_acquire_bits_opcode(io_mem_acquire_bits_opcode),
    .io_mem_acquire_bits_param(io_mem_acquire_bits_param),
    .io_mem_acquire_bits_size(io_mem_acquire_bits_size),
    .io_mem_acquire_bits_source(io_mem_acquire_bits_source),
    .io_mem_acquire_bits_address(io_mem_acquire_bits_address),
    .io_mem_acquire_bits_user_alias(io_mem_acquire_bits_user_alias),
    .io_mem_acquire_bits_user_vaddr(io_mem_acquire_bits_user_vaddr),
    .io_mem_acquire_bits_user_reqSource(io_mem_acquire_bits_user_reqSource),
    .io_mem_acquire_bits_user_needHint(io_mem_acquire_bits_user_needHint),
    .io_mem_acquire_bits_echo_isKeyword(io_mem_acquire_bits_echo_isKeyword),
    .io_mem_acquire_bits_mask(io_mem_acquire_bits_mask),
    .io_mem_grant_ready(io_mem_grant_ready),
    .io_mem_grant_valid(io_mem_grant_valid),
    .io_mem_grant_bits_opcode(io_mem_grant_bits_opcode),
    .io_mem_grant_bits_param(io_mem_grant_bits_param),
    .io_mem_grant_bits_size(io_mem_grant_bits_size),
    .io_mem_grant_bits_source(io_mem_grant_bits_source),
    .io_mem_grant_bits_sink(io_mem_grant_bits_sink),
    .io_mem_grant_bits_denied(io_mem_grant_bits_denied),
    .io_mem_grant_bits_data(io_mem_grant_bits_data),
    .io_mem_grant_bits_corrupt(io_mem_grant_bits_corrupt),
    .io_mem_finish_ready(io_mem_finish_ready),
    .io_mem_finish_valid(io_mem_finish_valid),
    .io_mem_finish_bits_sink(io_mem_finish_bits_sink),
    .io_l2_hint_valid(io_l2_hint_valid),
    .io_l2_hint_bits_sourceId(io_l2_hint_bits_sourceId),
    .io_main_pipe_req_ready(io_main_pipe_req_ready),
    .io_main_pipe_req_valid(io_main_pipe_req_valid),
    .io_main_pipe_req_bits_miss(io_main_pipe_req_bits_miss),
    .io_main_pipe_req_bits_miss_id(io_main_pipe_req_bits_miss_id),
    .io_main_pipe_req_bits_occupy_way(io_main_pipe_req_bits_occupy_way),
    .io_main_pipe_req_bits_miss_fail_cause_evict_btot(io_main_pipe_req_bits_miss_fail_cause_evict_btot),
    .io_main_pipe_req_bits_source(io_main_pipe_req_bits_source),
    .io_main_pipe_req_bits_cmd(io_main_pipe_req_bits_cmd),
    .io_main_pipe_req_bits_vaddr(io_main_pipe_req_bits_vaddr),
    .io_main_pipe_req_bits_addr(io_main_pipe_req_bits_addr),
    .io_main_pipe_req_bits_word_idx(io_main_pipe_req_bits_word_idx),
    .io_main_pipe_req_bits_amo_data(io_main_pipe_req_bits_amo_data),
    .io_main_pipe_req_bits_amo_mask(io_main_pipe_req_bits_amo_mask),
    .io_main_pipe_req_bits_amo_cmp(io_main_pipe_req_bits_amo_cmp),
    .io_main_pipe_req_bits_pf_source(io_main_pipe_req_bits_pf_source),
    .io_main_pipe_req_bits_access(io_main_pipe_req_bits_access),
    .io_main_pipe_req_bits_id(io_main_pipe_req_bits_id),
    .io_main_pipe_resp_valid(io_main_pipe_resp_valid),
    .io_main_pipe_resp_bits_miss_id(io_main_pipe_resp_bits_miss_id),
    .io_main_pipe_resp_bits_ack_miss_queue(io_main_pipe_resp_bits_ack_miss_queue),
    .io_mainpipe_info_s2_valid(io_mainpipe_info_s2_valid),
    .io_mainpipe_info_s2_miss_id(io_mainpipe_info_s2_miss_id),
    .io_mainpipe_info_s2_replay_to_mq(io_mainpipe_info_s2_replay_to_mq),
    .io_mainpipe_info_s2_evict_BtoT_way(io_mainpipe_info_s2_evict_BtoT_way),
    .io_mainpipe_info_s2_next_evict_way(io_mainpipe_info_s2_next_evict_way),
    .io_mainpipe_info_s3_valid(io_mainpipe_info_s3_valid),
    .io_mainpipe_info_s3_miss_id(io_mainpipe_info_s3_miss_id),
    .io_mainpipe_info_s3_refill_resp(io_mainpipe_info_s3_refill_resp),
    .io_refill_info_valid(io_refill_info_valid),
    .io_refill_info_bits_store_data(io_refill_info_bits_store_data),
    .io_refill_info_bits_store_mask(io_refill_info_bits_store_mask),
    .io_refill_info_bits_miss_param(io_refill_info_bits_miss_param),
    .io_refill_info_bits_error(io_refill_info_bits_error),
    .io_probe_req_bits_addr(io_probe_req_bits_addr),
    .io_probe_req_bits_vaddr(io_probe_req_bits_vaddr),
    .io_probe_block(io_probe_block),
    .io_replace_req_bits_addr(io_replace_req_bits_addr),
    .io_replace_req_bits_vaddr(io_replace_req_bits_vaddr),
    .io_replace_block(io_replace_block),
    .io_evict_set(io_evict_set),
    .io_btot_ways_for_set(io_btot_ways_for_set),
    .io_occupy_set_0(io_occupy_set_0),
    .io_occupy_set_1(io_occupy_set_1),
    .io_occupy_set_2(io_occupy_set_2),
    .io_occupy_fail_0(io_occupy_fail_0),
    .io_occupy_fail_1(io_occupy_fail_1),
    .io_occupy_fail_2(io_occupy_fail_2),
    .io_wbq_block_miss_req(io_wbq_block_miss_req),
    .io_forward_0_valid(io_forward_0_valid),
    .io_forward_0_mshrid(io_forward_0_mshrid),
    .io_forward_0_paddr(io_forward_0_paddr),
    .io_forward_0_forward_mshr(io_forward_0_forward_mshr),
    .io_forward_0_forwardData_0(io_forward_0_forwardData_0),
    .io_forward_0_forwardData_1(io_forward_0_forwardData_1),
    .io_forward_0_forwardData_2(io_forward_0_forwardData_2),
    .io_forward_0_forwardData_3(io_forward_0_forwardData_3),
    .io_forward_0_forwardData_4(io_forward_0_forwardData_4),
    .io_forward_0_forwardData_5(io_forward_0_forwardData_5),
    .io_forward_0_forwardData_6(io_forward_0_forwardData_6),
    .io_forward_0_forwardData_7(io_forward_0_forwardData_7),
    .io_forward_0_forwardData_8(io_forward_0_forwardData_8),
    .io_forward_0_forwardData_9(io_forward_0_forwardData_9),
    .io_forward_0_forwardData_10(io_forward_0_forwardData_10),
    .io_forward_0_forwardData_11(io_forward_0_forwardData_11),
    .io_forward_0_forwardData_12(io_forward_0_forwardData_12),
    .io_forward_0_forwardData_13(io_forward_0_forwardData_13),
    .io_forward_0_forwardData_14(io_forward_0_forwardData_14),
    .io_forward_0_forwardData_15(io_forward_0_forwardData_15),
    .io_forward_0_forward_result_valid(io_forward_0_forward_result_valid),
    .io_forward_0_corrupt(io_forward_0_corrupt),
    .io_forward_1_valid(io_forward_1_valid),
    .io_forward_1_mshrid(io_forward_1_mshrid),
    .io_forward_1_paddr(io_forward_1_paddr),
    .io_forward_1_forward_mshr(io_forward_1_forward_mshr),
    .io_forward_1_forwardData_0(io_forward_1_forwardData_0),
    .io_forward_1_forwardData_1(io_forward_1_forwardData_1),
    .io_forward_1_forwardData_2(io_forward_1_forwardData_2),
    .io_forward_1_forwardData_3(io_forward_1_forwardData_3),
    .io_forward_1_forwardData_4(io_forward_1_forwardData_4),
    .io_forward_1_forwardData_5(io_forward_1_forwardData_5),
    .io_forward_1_forwardData_6(io_forward_1_forwardData_6),
    .io_forward_1_forwardData_7(io_forward_1_forwardData_7),
    .io_forward_1_forwardData_8(io_forward_1_forwardData_8),
    .io_forward_1_forwardData_9(io_forward_1_forwardData_9),
    .io_forward_1_forwardData_10(io_forward_1_forwardData_10),
    .io_forward_1_forwardData_11(io_forward_1_forwardData_11),
    .io_forward_1_forwardData_12(io_forward_1_forwardData_12),
    .io_forward_1_forwardData_13(io_forward_1_forwardData_13),
    .io_forward_1_forwardData_14(io_forward_1_forwardData_14),
    .io_forward_1_forwardData_15(io_forward_1_forwardData_15),
    .io_forward_1_forward_result_valid(io_forward_1_forward_result_valid),
    .io_forward_1_corrupt(io_forward_1_corrupt),
    .io_forward_2_valid(io_forward_2_valid),
    .io_forward_2_mshrid(io_forward_2_mshrid),
    .io_forward_2_paddr(io_forward_2_paddr),
    .io_forward_2_forward_mshr(io_forward_2_forward_mshr),
    .io_forward_2_forwardData_0(io_forward_2_forwardData_0),
    .io_forward_2_forwardData_1(io_forward_2_forwardData_1),
    .io_forward_2_forwardData_2(io_forward_2_forwardData_2),
    .io_forward_2_forwardData_3(io_forward_2_forwardData_3),
    .io_forward_2_forwardData_4(io_forward_2_forwardData_4),
    .io_forward_2_forwardData_5(io_forward_2_forwardData_5),
    .io_forward_2_forwardData_6(io_forward_2_forwardData_6),
    .io_forward_2_forwardData_7(io_forward_2_forwardData_7),
    .io_forward_2_forwardData_8(io_forward_2_forwardData_8),
    .io_forward_2_forwardData_9(io_forward_2_forwardData_9),
    .io_forward_2_forwardData_10(io_forward_2_forwardData_10),
    .io_forward_2_forwardData_11(io_forward_2_forwardData_11),
    .io_forward_2_forwardData_12(io_forward_2_forwardData_12),
    .io_forward_2_forwardData_13(io_forward_2_forwardData_13),
    .io_forward_2_forwardData_14(io_forward_2_forwardData_14),
    .io_forward_2_forwardData_15(io_forward_2_forwardData_15),
    .io_forward_2_forward_result_valid(io_forward_2_forward_result_valid),
    .io_forward_2_corrupt(io_forward_2_corrupt),
    .io_l2_pf_store_only(io_l2_pf_store_only),
    .io_lqEmpty(io_lqEmpty),
    .io_prefetch_info_naive_late_miss_prefetch(io_prefetch_info_naive_late_miss_prefetch),
    .io_prefetch_info_fdp_late_miss_prefetch(io_prefetch_info_fdp_late_miss_prefetch),
    .io_prefetch_info_fdp_prefetch_monitor_cnt(io_prefetch_info_fdp_prefetch_monitor_cnt),
    .io_prefetch_info_fdp_total_prefetch(io_prefetch_info_fdp_total_prefetch),
    .io_wfi_wfiReq(io_wfi_wfiReq),
    .io_wfi_wfiSafe(io_wfi_wfiSafe),
    .io_debugTopDown_robHeadVaddr_valid(io_debugTopDown_robHeadVaddr_valid),
    .io_debugTopDown_robHeadVaddr_bits(io_debugTopDown_robHeadVaddr_bits),
    .io_debugTopDown_robHeadMissInDCache(io_debugTopDown_robHeadMissInDCache),
    .io_l1Miss(io_l1Miss),
    .io_perf_0_value(io_perf_0_value),
    .io_perf_1_value(io_perf_1_value),
    .io_perf_2_value(io_perf_2_value),
    .io_perf_3_value(io_perf_3_value),
    .io_perf_4_value(io_perf_4_value)
  );
endmodule
