// ICacheMissUnit_xs —— UT 用变体（与 wrapper 同，仅模块名改为 ICacheMissUnit_xs）
//
// 本模块端口与 golden chisel-rtl/ICacheMissUnit.sv 完全一致（扁平），内部仅例化
// 可读核 xs_ICacheMissUnit。可读核端口本就是扁平标量（与 golden 同），故直通即可，
// 无需打包/拆包。供 Formality 对比（impl 侧顶层）与 ST 替换使用。
module ICacheMissUnit_xs(
  input          clock,
  input          reset,
  input          io_fencei,
  input          io_flush,
  input          io_wfi_wfiReq,
  output         io_wfi_wfiSafe,
  output         io_fetch_req_ready,
  input          io_fetch_req_valid,
  input  [41:0]  io_fetch_req_bits_blkPaddr,
  input  [7:0]   io_fetch_req_bits_vSetIdx,
  output         io_fetch_resp_valid,
  output [41:0]  io_fetch_resp_bits_blkPaddr,
  output [7:0]   io_fetch_resp_bits_vSetIdx,
  output [3:0]   io_fetch_resp_bits_waymask,
  output [511:0] io_fetch_resp_bits_data,
  output         io_fetch_resp_bits_corrupt,
  output         io_prefetch_req_ready,
  input          io_prefetch_req_valid,
  input  [41:0]  io_prefetch_req_bits_blkPaddr,
  input  [7:0]   io_prefetch_req_bits_vSetIdx,
  output         io_meta_write_valid,
  output [7:0]   io_meta_write_bits_virIdx,
  output [35:0]  io_meta_write_bits_phyTag,
  output [3:0]   io_meta_write_bits_waymask,
  output         io_meta_write_bits_bankIdx,
  output         io_data_write_valid,
  output [7:0]   io_data_write_bits_virIdx,
  output [511:0] io_data_write_bits_data,
  output [3:0]   io_data_write_bits_waymask,
  output         io_victim_vSetIdx_valid,
  output [7:0]   io_victim_vSetIdx_bits,
  input  [1:0]   io_victim_way,
  input          io_mem_acquire_ready,
  output         io_mem_acquire_valid,
  output [3:0]   io_mem_acquire_bits_source,
  output [47:0]  io_mem_acquire_bits_address,
  input          io_mem_grant_valid,
  input  [3:0]   io_mem_grant_bits_opcode,
  input  [2:0]   io_mem_grant_bits_size,
  input  [3:0]   io_mem_grant_bits_source,
  input  [255:0] io_mem_grant_bits_data,
  input          io_mem_grant_bits_corrupt
);
  xs_ICacheMissUnit u_core (
    .clock(clock),
    .reset(reset),
    .io_fencei(io_fencei),
    .io_flush(io_flush),
    .io_wfi_wfiReq(io_wfi_wfiReq),
    .io_wfi_wfiSafe(io_wfi_wfiSafe),
    .io_fetch_req_ready(io_fetch_req_ready),
    .io_fetch_req_valid(io_fetch_req_valid),
    .io_fetch_req_bits_blkPaddr(io_fetch_req_bits_blkPaddr),
    .io_fetch_req_bits_vSetIdx(io_fetch_req_bits_vSetIdx),
    .io_fetch_resp_valid(io_fetch_resp_valid),
    .io_fetch_resp_bits_blkPaddr(io_fetch_resp_bits_blkPaddr),
    .io_fetch_resp_bits_vSetIdx(io_fetch_resp_bits_vSetIdx),
    .io_fetch_resp_bits_waymask(io_fetch_resp_bits_waymask),
    .io_fetch_resp_bits_data(io_fetch_resp_bits_data),
    .io_fetch_resp_bits_corrupt(io_fetch_resp_bits_corrupt),
    .io_prefetch_req_ready(io_prefetch_req_ready),
    .io_prefetch_req_valid(io_prefetch_req_valid),
    .io_prefetch_req_bits_blkPaddr(io_prefetch_req_bits_blkPaddr),
    .io_prefetch_req_bits_vSetIdx(io_prefetch_req_bits_vSetIdx),
    .io_meta_write_valid(io_meta_write_valid),
    .io_meta_write_bits_virIdx(io_meta_write_bits_virIdx),
    .io_meta_write_bits_phyTag(io_meta_write_bits_phyTag),
    .io_meta_write_bits_waymask(io_meta_write_bits_waymask),
    .io_meta_write_bits_bankIdx(io_meta_write_bits_bankIdx),
    .io_data_write_valid(io_data_write_valid),
    .io_data_write_bits_virIdx(io_data_write_bits_virIdx),
    .io_data_write_bits_data(io_data_write_bits_data),
    .io_data_write_bits_waymask(io_data_write_bits_waymask),
    .io_victim_vSetIdx_valid(io_victim_vSetIdx_valid),
    .io_victim_vSetIdx_bits(io_victim_vSetIdx_bits),
    .io_victim_way(io_victim_way),
    .io_mem_acquire_ready(io_mem_acquire_ready),
    .io_mem_acquire_valid(io_mem_acquire_valid),
    .io_mem_acquire_bits_source(io_mem_acquire_bits_source),
    .io_mem_acquire_bits_address(io_mem_acquire_bits_address),
    .io_mem_grant_valid(io_mem_grant_valid),
    .io_mem_grant_bits_opcode(io_mem_grant_bits_opcode),
    .io_mem_grant_bits_size(io_mem_grant_bits_size),
    .io_mem_grant_bits_source(io_mem_grant_bits_source),
    .io_mem_grant_bits_data(io_mem_grant_bits_data),
    .io_mem_grant_bits_corrupt(io_mem_grant_bits_corrupt)
  );
endmodule
