// 自动生成:scripts/gen_exeunit.py（ExeUnit_4）—— 勿手改(逻辑为从设计意图的可读重写)
// impl 侧变体 ExeUnit_4_xs:例化可读核(UT 比对)。
module ExeUnit_4_xs(
  input  clock,
  input  reset,
  input  io_in_valid,
  input  [34:0] io_in_bits_fuType,
  input  [8:0] io_in_bits_fuOpType,
  input  [63:0] io_in_bits_src_0,
  input  [63:0] io_in_bits_src_1,
  input  io_in_bits_robIdx_flag,
  input  [7:0] io_in_bits_robIdx_value,
  input  [7:0] io_in_bits_pdest,
  input  io_in_bits_rfWen,
  input  [63:0] io_in_bits_perfDebugInfo_enqRsTime,
  input  [63:0] io_in_bits_perfDebugInfo_selectTime,
  input  [63:0] io_in_bits_perfDebugInfo_issueTime,
  output io_out_valid,
  output [63:0] io_out_bits_data_0,
  output [63:0] io_out_bits_data_1,
  output [7:0] io_out_bits_pdest,
  output io_out_bits_robIdx_flag,
  output [7:0] io_out_bits_robIdx_value,
  output io_out_bits_intWen,
  output [63:0] io_out_bits_debugInfo_enqRsTime,
  output [63:0] io_out_bits_debugInfo_selectTime,
  output [63:0] io_out_bits_debugInfo_issueTime
);
  xs_ExeUnit_4_core u_core (
    .clock(clock),
    .reset(reset),
    .io_in_valid(io_in_valid),
    .io_in_bits_fuType(io_in_bits_fuType),
    .io_in_bits_fuOpType(io_in_bits_fuOpType),
    .io_in_bits_src_0(io_in_bits_src_0),
    .io_in_bits_src_1(io_in_bits_src_1),
    .io_in_bits_robIdx_flag(io_in_bits_robIdx_flag),
    .io_in_bits_robIdx_value(io_in_bits_robIdx_value),
    .io_in_bits_pdest(io_in_bits_pdest),
    .io_in_bits_rfWen(io_in_bits_rfWen),
    .io_in_bits_perfDebugInfo_enqRsTime(io_in_bits_perfDebugInfo_enqRsTime),
    .io_in_bits_perfDebugInfo_selectTime(io_in_bits_perfDebugInfo_selectTime),
    .io_in_bits_perfDebugInfo_issueTime(io_in_bits_perfDebugInfo_issueTime),
    .io_out_valid(io_out_valid),
    .io_out_bits_data_0(io_out_bits_data_0),
    .io_out_bits_data_1(io_out_bits_data_1),
    .io_out_bits_pdest(io_out_bits_pdest),
    .io_out_bits_robIdx_flag(io_out_bits_robIdx_flag),
    .io_out_bits_robIdx_value(io_out_bits_robIdx_value),
    .io_out_bits_intWen(io_out_bits_intWen),
    .io_out_bits_debugInfo_enqRsTime(io_out_bits_debugInfo_enqRsTime),
    .io_out_bits_debugInfo_selectTime(io_out_bits_debugInfo_selectTime),
    .io_out_bits_debugInfo_issueTime(io_out_bits_debugInfo_issueTime)
  );
endmodule
