// 自动生成: _xs 变体(UT), 例化 xs_Trace_core。
module Trace_xs(
  input clock,
  input reset,
  input io_in_fromEncoder_enable,
  input io_in_fromEncoder_stall,
  input io_in_fromRob_blocks_0_valid,
  input [5:0] io_in_fromRob_blocks_0_bits_ftqIdx_value,
  input [3:0] io_in_fromRob_blocks_0_bits_ftqOffset,
  input [3:0] io_in_fromRob_blocks_0_bits_tracePipe_itype,
  input [3:0] io_in_fromRob_blocks_0_bits_tracePipe_iretire,
  input io_in_fromRob_blocks_0_bits_tracePipe_ilastsize,
  input io_in_fromRob_blocks_1_valid,
  input [5:0] io_in_fromRob_blocks_1_bits_ftqIdx_value,
  input [3:0] io_in_fromRob_blocks_1_bits_ftqOffset,
  input [3:0] io_in_fromRob_blocks_1_bits_tracePipe_itype,
  input [3:0] io_in_fromRob_blocks_1_bits_tracePipe_iretire,
  input io_in_fromRob_blocks_1_bits_tracePipe_ilastsize,
  input io_in_fromRob_blocks_2_valid,
  input [5:0] io_in_fromRob_blocks_2_bits_ftqIdx_value,
  input [3:0] io_in_fromRob_blocks_2_bits_ftqOffset,
  input [3:0] io_in_fromRob_blocks_2_bits_tracePipe_itype,
  input [3:0] io_in_fromRob_blocks_2_bits_tracePipe_iretire,
  input io_in_fromRob_blocks_2_bits_tracePipe_ilastsize,
  input io_in_fromRob_blocks_3_valid,
  input [5:0] io_in_fromRob_blocks_3_bits_ftqIdx_value,
  input [3:0] io_in_fromRob_blocks_3_bits_ftqOffset,
  input [3:0] io_in_fromRob_blocks_3_bits_tracePipe_itype,
  input [3:0] io_in_fromRob_blocks_3_bits_tracePipe_iretire,
  input io_in_fromRob_blocks_3_bits_tracePipe_ilastsize,
  input io_in_fromRob_blocks_4_valid,
  input [5:0] io_in_fromRob_blocks_4_bits_ftqIdx_value,
  input [3:0] io_in_fromRob_blocks_4_bits_ftqOffset,
  input [3:0] io_in_fromRob_blocks_4_bits_tracePipe_itype,
  input [3:0] io_in_fromRob_blocks_4_bits_tracePipe_iretire,
  input io_in_fromRob_blocks_4_bits_tracePipe_ilastsize,
  input io_in_fromRob_blocks_5_valid,
  input [5:0] io_in_fromRob_blocks_5_bits_ftqIdx_value,
  input [3:0] io_in_fromRob_blocks_5_bits_ftqOffset,
  input [3:0] io_in_fromRob_blocks_5_bits_tracePipe_itype,
  input [3:0] io_in_fromRob_blocks_5_bits_tracePipe_iretire,
  input io_in_fromRob_blocks_5_bits_tracePipe_ilastsize,
  input io_in_fromRob_blocks_6_valid,
  input [5:0] io_in_fromRob_blocks_6_bits_ftqIdx_value,
  input [3:0] io_in_fromRob_blocks_6_bits_ftqOffset,
  input [3:0] io_in_fromRob_blocks_6_bits_tracePipe_itype,
  input [3:0] io_in_fromRob_blocks_6_bits_tracePipe_iretire,
  input io_in_fromRob_blocks_6_bits_tracePipe_ilastsize,
  input io_in_fromRob_blocks_7_valid,
  input [5:0] io_in_fromRob_blocks_7_bits_ftqIdx_value,
  input [3:0] io_in_fromRob_blocks_7_bits_ftqOffset,
  input [3:0] io_in_fromRob_blocks_7_bits_tracePipe_itype,
  input [3:0] io_in_fromRob_blocks_7_bits_tracePipe_iretire,
  input io_in_fromRob_blocks_7_bits_tracePipe_ilastsize,
  output io_out_toPcMem_blocks_0_valid,
  output [5:0] io_out_toPcMem_blocks_0_bits_ftqIdx_value,
  output io_out_toPcMem_blocks_1_valid,
  output [5:0] io_out_toPcMem_blocks_1_bits_ftqIdx_value,
  output io_out_toPcMem_blocks_2_valid,
  output [5:0] io_out_toPcMem_blocks_2_bits_ftqIdx_value,
  output io_out_toEncoder_blocks_0_valid,
  output [3:0] io_out_toEncoder_blocks_0_bits_ftqOffset,
  output [3:0] io_out_toEncoder_blocks_0_bits_tracePipe_itype,
  output [6:0] io_out_toEncoder_blocks_0_bits_tracePipe_iretire,
  output io_out_toEncoder_blocks_0_bits_tracePipe_ilastsize,
  output io_out_toEncoder_blocks_1_valid,
  output [3:0] io_out_toEncoder_blocks_1_bits_ftqOffset,
  output [3:0] io_out_toEncoder_blocks_1_bits_tracePipe_itype,
  output [6:0] io_out_toEncoder_blocks_1_bits_tracePipe_iretire,
  output io_out_toEncoder_blocks_1_bits_tracePipe_ilastsize,
  output io_out_toEncoder_blocks_2_valid,
  output [3:0] io_out_toEncoder_blocks_2_bits_ftqOffset,
  output [3:0] io_out_toEncoder_blocks_2_bits_tracePipe_itype,
  output [6:0] io_out_toEncoder_blocks_2_bits_tracePipe_iretire,
  output io_out_toEncoder_blocks_2_bits_tracePipe_ilastsize,
  output io_out_blockRobCommit
);
  xs_Trace_core u_core (
    .clock(clock),
    .reset(reset),
    .io_in_fromEncoder_enable(io_in_fromEncoder_enable),
    .io_in_fromEncoder_stall(io_in_fromEncoder_stall),
    .io_in_fromRob_blocks_0_valid(io_in_fromRob_blocks_0_valid),
    .io_in_fromRob_blocks_0_bits_ftqIdx_value(io_in_fromRob_blocks_0_bits_ftqIdx_value),
    .io_in_fromRob_blocks_0_bits_ftqOffset(io_in_fromRob_blocks_0_bits_ftqOffset),
    .io_in_fromRob_blocks_0_bits_tracePipe_itype(io_in_fromRob_blocks_0_bits_tracePipe_itype),
    .io_in_fromRob_blocks_0_bits_tracePipe_iretire(io_in_fromRob_blocks_0_bits_tracePipe_iretire),
    .io_in_fromRob_blocks_0_bits_tracePipe_ilastsize(io_in_fromRob_blocks_0_bits_tracePipe_ilastsize),
    .io_in_fromRob_blocks_1_valid(io_in_fromRob_blocks_1_valid),
    .io_in_fromRob_blocks_1_bits_ftqIdx_value(io_in_fromRob_blocks_1_bits_ftqIdx_value),
    .io_in_fromRob_blocks_1_bits_ftqOffset(io_in_fromRob_blocks_1_bits_ftqOffset),
    .io_in_fromRob_blocks_1_bits_tracePipe_itype(io_in_fromRob_blocks_1_bits_tracePipe_itype),
    .io_in_fromRob_blocks_1_bits_tracePipe_iretire(io_in_fromRob_blocks_1_bits_tracePipe_iretire),
    .io_in_fromRob_blocks_1_bits_tracePipe_ilastsize(io_in_fromRob_blocks_1_bits_tracePipe_ilastsize),
    .io_in_fromRob_blocks_2_valid(io_in_fromRob_blocks_2_valid),
    .io_in_fromRob_blocks_2_bits_ftqIdx_value(io_in_fromRob_blocks_2_bits_ftqIdx_value),
    .io_in_fromRob_blocks_2_bits_ftqOffset(io_in_fromRob_blocks_2_bits_ftqOffset),
    .io_in_fromRob_blocks_2_bits_tracePipe_itype(io_in_fromRob_blocks_2_bits_tracePipe_itype),
    .io_in_fromRob_blocks_2_bits_tracePipe_iretire(io_in_fromRob_blocks_2_bits_tracePipe_iretire),
    .io_in_fromRob_blocks_2_bits_tracePipe_ilastsize(io_in_fromRob_blocks_2_bits_tracePipe_ilastsize),
    .io_in_fromRob_blocks_3_valid(io_in_fromRob_blocks_3_valid),
    .io_in_fromRob_blocks_3_bits_ftqIdx_value(io_in_fromRob_blocks_3_bits_ftqIdx_value),
    .io_in_fromRob_blocks_3_bits_ftqOffset(io_in_fromRob_blocks_3_bits_ftqOffset),
    .io_in_fromRob_blocks_3_bits_tracePipe_itype(io_in_fromRob_blocks_3_bits_tracePipe_itype),
    .io_in_fromRob_blocks_3_bits_tracePipe_iretire(io_in_fromRob_blocks_3_bits_tracePipe_iretire),
    .io_in_fromRob_blocks_3_bits_tracePipe_ilastsize(io_in_fromRob_blocks_3_bits_tracePipe_ilastsize),
    .io_in_fromRob_blocks_4_valid(io_in_fromRob_blocks_4_valid),
    .io_in_fromRob_blocks_4_bits_ftqIdx_value(io_in_fromRob_blocks_4_bits_ftqIdx_value),
    .io_in_fromRob_blocks_4_bits_ftqOffset(io_in_fromRob_blocks_4_bits_ftqOffset),
    .io_in_fromRob_blocks_4_bits_tracePipe_itype(io_in_fromRob_blocks_4_bits_tracePipe_itype),
    .io_in_fromRob_blocks_4_bits_tracePipe_iretire(io_in_fromRob_blocks_4_bits_tracePipe_iretire),
    .io_in_fromRob_blocks_4_bits_tracePipe_ilastsize(io_in_fromRob_blocks_4_bits_tracePipe_ilastsize),
    .io_in_fromRob_blocks_5_valid(io_in_fromRob_blocks_5_valid),
    .io_in_fromRob_blocks_5_bits_ftqIdx_value(io_in_fromRob_blocks_5_bits_ftqIdx_value),
    .io_in_fromRob_blocks_5_bits_ftqOffset(io_in_fromRob_blocks_5_bits_ftqOffset),
    .io_in_fromRob_blocks_5_bits_tracePipe_itype(io_in_fromRob_blocks_5_bits_tracePipe_itype),
    .io_in_fromRob_blocks_5_bits_tracePipe_iretire(io_in_fromRob_blocks_5_bits_tracePipe_iretire),
    .io_in_fromRob_blocks_5_bits_tracePipe_ilastsize(io_in_fromRob_blocks_5_bits_tracePipe_ilastsize),
    .io_in_fromRob_blocks_6_valid(io_in_fromRob_blocks_6_valid),
    .io_in_fromRob_blocks_6_bits_ftqIdx_value(io_in_fromRob_blocks_6_bits_ftqIdx_value),
    .io_in_fromRob_blocks_6_bits_ftqOffset(io_in_fromRob_blocks_6_bits_ftqOffset),
    .io_in_fromRob_blocks_6_bits_tracePipe_itype(io_in_fromRob_blocks_6_bits_tracePipe_itype),
    .io_in_fromRob_blocks_6_bits_tracePipe_iretire(io_in_fromRob_blocks_6_bits_tracePipe_iretire),
    .io_in_fromRob_blocks_6_bits_tracePipe_ilastsize(io_in_fromRob_blocks_6_bits_tracePipe_ilastsize),
    .io_in_fromRob_blocks_7_valid(io_in_fromRob_blocks_7_valid),
    .io_in_fromRob_blocks_7_bits_ftqIdx_value(io_in_fromRob_blocks_7_bits_ftqIdx_value),
    .io_in_fromRob_blocks_7_bits_ftqOffset(io_in_fromRob_blocks_7_bits_ftqOffset),
    .io_in_fromRob_blocks_7_bits_tracePipe_itype(io_in_fromRob_blocks_7_bits_tracePipe_itype),
    .io_in_fromRob_blocks_7_bits_tracePipe_iretire(io_in_fromRob_blocks_7_bits_tracePipe_iretire),
    .io_in_fromRob_blocks_7_bits_tracePipe_ilastsize(io_in_fromRob_blocks_7_bits_tracePipe_ilastsize),
    .io_out_toPcMem_blocks_0_valid(io_out_toPcMem_blocks_0_valid),
    .io_out_toPcMem_blocks_0_bits_ftqIdx_value(io_out_toPcMem_blocks_0_bits_ftqIdx_value),
    .io_out_toPcMem_blocks_1_valid(io_out_toPcMem_blocks_1_valid),
    .io_out_toPcMem_blocks_1_bits_ftqIdx_value(io_out_toPcMem_blocks_1_bits_ftqIdx_value),
    .io_out_toPcMem_blocks_2_valid(io_out_toPcMem_blocks_2_valid),
    .io_out_toPcMem_blocks_2_bits_ftqIdx_value(io_out_toPcMem_blocks_2_bits_ftqIdx_value),
    .io_out_toEncoder_blocks_0_valid(io_out_toEncoder_blocks_0_valid),
    .io_out_toEncoder_blocks_0_bits_ftqOffset(io_out_toEncoder_blocks_0_bits_ftqOffset),
    .io_out_toEncoder_blocks_0_bits_tracePipe_itype(io_out_toEncoder_blocks_0_bits_tracePipe_itype),
    .io_out_toEncoder_blocks_0_bits_tracePipe_iretire(io_out_toEncoder_blocks_0_bits_tracePipe_iretire),
    .io_out_toEncoder_blocks_0_bits_tracePipe_ilastsize(io_out_toEncoder_blocks_0_bits_tracePipe_ilastsize),
    .io_out_toEncoder_blocks_1_valid(io_out_toEncoder_blocks_1_valid),
    .io_out_toEncoder_blocks_1_bits_ftqOffset(io_out_toEncoder_blocks_1_bits_ftqOffset),
    .io_out_toEncoder_blocks_1_bits_tracePipe_itype(io_out_toEncoder_blocks_1_bits_tracePipe_itype),
    .io_out_toEncoder_blocks_1_bits_tracePipe_iretire(io_out_toEncoder_blocks_1_bits_tracePipe_iretire),
    .io_out_toEncoder_blocks_1_bits_tracePipe_ilastsize(io_out_toEncoder_blocks_1_bits_tracePipe_ilastsize),
    .io_out_toEncoder_blocks_2_valid(io_out_toEncoder_blocks_2_valid),
    .io_out_toEncoder_blocks_2_bits_ftqOffset(io_out_toEncoder_blocks_2_bits_ftqOffset),
    .io_out_toEncoder_blocks_2_bits_tracePipe_itype(io_out_toEncoder_blocks_2_bits_tracePipe_itype),
    .io_out_toEncoder_blocks_2_bits_tracePipe_iretire(io_out_toEncoder_blocks_2_bits_tracePipe_iretire),
    .io_out_toEncoder_blocks_2_bits_tracePipe_ilastsize(io_out_toEncoder_blocks_2_bits_tracePipe_ilastsize),
    .io_out_blockRobCommit(io_out_blockRobCommit)
  );
endmodule
