// 自动生成: _xs 变体(UT), 例化 xs_SnapshotGenerator_14_core。
module SnapshotGenerator_14_xs(
  input clock,
  input reset,
  input io_enq,
  input io_enqData_robIdx_0_flag,
  input [7:0] io_enqData_robIdx_0_value,
  input io_enqData_robIdx_1_flag,
  input [7:0] io_enqData_robIdx_1_value,
  input io_enqData_robIdx_2_flag,
  input [7:0] io_enqData_robIdx_2_value,
  input io_enqData_robIdx_3_flag,
  input [7:0] io_enqData_robIdx_3_value,
  input io_enqData_robIdx_4_flag,
  input [7:0] io_enqData_robIdx_4_value,
  input io_enqData_robIdx_5_flag,
  input [7:0] io_enqData_robIdx_5_value,
  input io_enqData_isCFI_0,
  input io_enqData_isCFI_1,
  input io_enqData_isCFI_2,
  input io_enqData_isCFI_3,
  input io_enqData_isCFI_4,
  input io_enqData_isCFI_5,
  input io_deq,
  input io_redirect,
  input io_flushVec_0,
  input io_flushVec_1,
  input io_flushVec_2,
  input io_flushVec_3,
  output io_snapshots_0_robIdx_0_flag,
  output [7:0] io_snapshots_0_robIdx_0_value,
  output io_snapshots_0_robIdx_1_flag,
  output [7:0] io_snapshots_0_robIdx_1_value,
  output io_snapshots_0_robIdx_2_flag,
  output [7:0] io_snapshots_0_robIdx_2_value,
  output io_snapshots_0_robIdx_3_flag,
  output [7:0] io_snapshots_0_robIdx_3_value,
  output io_snapshots_0_robIdx_4_flag,
  output [7:0] io_snapshots_0_robIdx_4_value,
  output io_snapshots_0_robIdx_5_flag,
  output [7:0] io_snapshots_0_robIdx_5_value,
  output io_snapshots_0_isCFI_0,
  output io_snapshots_0_isCFI_1,
  output io_snapshots_0_isCFI_2,
  output io_snapshots_0_isCFI_3,
  output io_snapshots_0_isCFI_4,
  output io_snapshots_0_isCFI_5,
  output io_snapshots_1_robIdx_0_flag,
  output [7:0] io_snapshots_1_robIdx_0_value,
  output io_snapshots_1_robIdx_1_flag,
  output [7:0] io_snapshots_1_robIdx_1_value,
  output io_snapshots_1_robIdx_2_flag,
  output [7:0] io_snapshots_1_robIdx_2_value,
  output io_snapshots_1_robIdx_3_flag,
  output [7:0] io_snapshots_1_robIdx_3_value,
  output io_snapshots_1_robIdx_4_flag,
  output [7:0] io_snapshots_1_robIdx_4_value,
  output io_snapshots_1_robIdx_5_flag,
  output [7:0] io_snapshots_1_robIdx_5_value,
  output io_snapshots_1_isCFI_0,
  output io_snapshots_1_isCFI_1,
  output io_snapshots_1_isCFI_2,
  output io_snapshots_1_isCFI_3,
  output io_snapshots_1_isCFI_4,
  output io_snapshots_1_isCFI_5,
  output io_snapshots_2_robIdx_0_flag,
  output [7:0] io_snapshots_2_robIdx_0_value,
  output io_snapshots_2_robIdx_1_flag,
  output [7:0] io_snapshots_2_robIdx_1_value,
  output io_snapshots_2_robIdx_2_flag,
  output [7:0] io_snapshots_2_robIdx_2_value,
  output io_snapshots_2_robIdx_3_flag,
  output [7:0] io_snapshots_2_robIdx_3_value,
  output io_snapshots_2_robIdx_4_flag,
  output [7:0] io_snapshots_2_robIdx_4_value,
  output io_snapshots_2_robIdx_5_flag,
  output [7:0] io_snapshots_2_robIdx_5_value,
  output io_snapshots_2_isCFI_0,
  output io_snapshots_2_isCFI_1,
  output io_snapshots_2_isCFI_2,
  output io_snapshots_2_isCFI_3,
  output io_snapshots_2_isCFI_4,
  output io_snapshots_2_isCFI_5,
  output io_snapshots_3_robIdx_0_flag,
  output [7:0] io_snapshots_3_robIdx_0_value,
  output io_snapshots_3_robIdx_1_flag,
  output [7:0] io_snapshots_3_robIdx_1_value,
  output io_snapshots_3_robIdx_2_flag,
  output [7:0] io_snapshots_3_robIdx_2_value,
  output io_snapshots_3_robIdx_3_flag,
  output [7:0] io_snapshots_3_robIdx_3_value,
  output io_snapshots_3_robIdx_4_flag,
  output [7:0] io_snapshots_3_robIdx_4_value,
  output io_snapshots_3_robIdx_5_flag,
  output [7:0] io_snapshots_3_robIdx_5_value,
  output io_snapshots_3_isCFI_0,
  output io_snapshots_3_isCFI_1,
  output io_snapshots_3_isCFI_2,
  output io_snapshots_3_isCFI_3,
  output io_snapshots_3_isCFI_4,
  output io_snapshots_3_isCFI_5,
  output io_enqPtr_flag,
  output [1:0] io_enqPtr_value,
  output io_deqPtr_flag,
  output [1:0] io_deqPtr_value,
  output io_valids_0,
  output io_valids_1,
  output io_valids_2,
  output io_valids_3
);
  xs_SnapshotGenerator_14_core u_core (
    .clock(clock),
    .reset(reset),
    .io_enq(io_enq),
    .io_enqData_robIdx_0_flag(io_enqData_robIdx_0_flag),
    .io_enqData_robIdx_0_value(io_enqData_robIdx_0_value),
    .io_enqData_robIdx_1_flag(io_enqData_robIdx_1_flag),
    .io_enqData_robIdx_1_value(io_enqData_robIdx_1_value),
    .io_enqData_robIdx_2_flag(io_enqData_robIdx_2_flag),
    .io_enqData_robIdx_2_value(io_enqData_robIdx_2_value),
    .io_enqData_robIdx_3_flag(io_enqData_robIdx_3_flag),
    .io_enqData_robIdx_3_value(io_enqData_robIdx_3_value),
    .io_enqData_robIdx_4_flag(io_enqData_robIdx_4_flag),
    .io_enqData_robIdx_4_value(io_enqData_robIdx_4_value),
    .io_enqData_robIdx_5_flag(io_enqData_robIdx_5_flag),
    .io_enqData_robIdx_5_value(io_enqData_robIdx_5_value),
    .io_enqData_isCFI_0(io_enqData_isCFI_0),
    .io_enqData_isCFI_1(io_enqData_isCFI_1),
    .io_enqData_isCFI_2(io_enqData_isCFI_2),
    .io_enqData_isCFI_3(io_enqData_isCFI_3),
    .io_enqData_isCFI_4(io_enqData_isCFI_4),
    .io_enqData_isCFI_5(io_enqData_isCFI_5),
    .io_deq(io_deq),
    .io_redirect(io_redirect),
    .io_flushVec_0(io_flushVec_0),
    .io_flushVec_1(io_flushVec_1),
    .io_flushVec_2(io_flushVec_2),
    .io_flushVec_3(io_flushVec_3),
    .io_snapshots_0_robIdx_0_flag(io_snapshots_0_robIdx_0_flag),
    .io_snapshots_0_robIdx_0_value(io_snapshots_0_robIdx_0_value),
    .io_snapshots_0_robIdx_1_flag(io_snapshots_0_robIdx_1_flag),
    .io_snapshots_0_robIdx_1_value(io_snapshots_0_robIdx_1_value),
    .io_snapshots_0_robIdx_2_flag(io_snapshots_0_robIdx_2_flag),
    .io_snapshots_0_robIdx_2_value(io_snapshots_0_robIdx_2_value),
    .io_snapshots_0_robIdx_3_flag(io_snapshots_0_robIdx_3_flag),
    .io_snapshots_0_robIdx_3_value(io_snapshots_0_robIdx_3_value),
    .io_snapshots_0_robIdx_4_flag(io_snapshots_0_robIdx_4_flag),
    .io_snapshots_0_robIdx_4_value(io_snapshots_0_robIdx_4_value),
    .io_snapshots_0_robIdx_5_flag(io_snapshots_0_robIdx_5_flag),
    .io_snapshots_0_robIdx_5_value(io_snapshots_0_robIdx_5_value),
    .io_snapshots_0_isCFI_0(io_snapshots_0_isCFI_0),
    .io_snapshots_0_isCFI_1(io_snapshots_0_isCFI_1),
    .io_snapshots_0_isCFI_2(io_snapshots_0_isCFI_2),
    .io_snapshots_0_isCFI_3(io_snapshots_0_isCFI_3),
    .io_snapshots_0_isCFI_4(io_snapshots_0_isCFI_4),
    .io_snapshots_0_isCFI_5(io_snapshots_0_isCFI_5),
    .io_snapshots_1_robIdx_0_flag(io_snapshots_1_robIdx_0_flag),
    .io_snapshots_1_robIdx_0_value(io_snapshots_1_robIdx_0_value),
    .io_snapshots_1_robIdx_1_flag(io_snapshots_1_robIdx_1_flag),
    .io_snapshots_1_robIdx_1_value(io_snapshots_1_robIdx_1_value),
    .io_snapshots_1_robIdx_2_flag(io_snapshots_1_robIdx_2_flag),
    .io_snapshots_1_robIdx_2_value(io_snapshots_1_robIdx_2_value),
    .io_snapshots_1_robIdx_3_flag(io_snapshots_1_robIdx_3_flag),
    .io_snapshots_1_robIdx_3_value(io_snapshots_1_robIdx_3_value),
    .io_snapshots_1_robIdx_4_flag(io_snapshots_1_robIdx_4_flag),
    .io_snapshots_1_robIdx_4_value(io_snapshots_1_robIdx_4_value),
    .io_snapshots_1_robIdx_5_flag(io_snapshots_1_robIdx_5_flag),
    .io_snapshots_1_robIdx_5_value(io_snapshots_1_robIdx_5_value),
    .io_snapshots_1_isCFI_0(io_snapshots_1_isCFI_0),
    .io_snapshots_1_isCFI_1(io_snapshots_1_isCFI_1),
    .io_snapshots_1_isCFI_2(io_snapshots_1_isCFI_2),
    .io_snapshots_1_isCFI_3(io_snapshots_1_isCFI_3),
    .io_snapshots_1_isCFI_4(io_snapshots_1_isCFI_4),
    .io_snapshots_1_isCFI_5(io_snapshots_1_isCFI_5),
    .io_snapshots_2_robIdx_0_flag(io_snapshots_2_robIdx_0_flag),
    .io_snapshots_2_robIdx_0_value(io_snapshots_2_robIdx_0_value),
    .io_snapshots_2_robIdx_1_flag(io_snapshots_2_robIdx_1_flag),
    .io_snapshots_2_robIdx_1_value(io_snapshots_2_robIdx_1_value),
    .io_snapshots_2_robIdx_2_flag(io_snapshots_2_robIdx_2_flag),
    .io_snapshots_2_robIdx_2_value(io_snapshots_2_robIdx_2_value),
    .io_snapshots_2_robIdx_3_flag(io_snapshots_2_robIdx_3_flag),
    .io_snapshots_2_robIdx_3_value(io_snapshots_2_robIdx_3_value),
    .io_snapshots_2_robIdx_4_flag(io_snapshots_2_robIdx_4_flag),
    .io_snapshots_2_robIdx_4_value(io_snapshots_2_robIdx_4_value),
    .io_snapshots_2_robIdx_5_flag(io_snapshots_2_robIdx_5_flag),
    .io_snapshots_2_robIdx_5_value(io_snapshots_2_robIdx_5_value),
    .io_snapshots_2_isCFI_0(io_snapshots_2_isCFI_0),
    .io_snapshots_2_isCFI_1(io_snapshots_2_isCFI_1),
    .io_snapshots_2_isCFI_2(io_snapshots_2_isCFI_2),
    .io_snapshots_2_isCFI_3(io_snapshots_2_isCFI_3),
    .io_snapshots_2_isCFI_4(io_snapshots_2_isCFI_4),
    .io_snapshots_2_isCFI_5(io_snapshots_2_isCFI_5),
    .io_snapshots_3_robIdx_0_flag(io_snapshots_3_robIdx_0_flag),
    .io_snapshots_3_robIdx_0_value(io_snapshots_3_robIdx_0_value),
    .io_snapshots_3_robIdx_1_flag(io_snapshots_3_robIdx_1_flag),
    .io_snapshots_3_robIdx_1_value(io_snapshots_3_robIdx_1_value),
    .io_snapshots_3_robIdx_2_flag(io_snapshots_3_robIdx_2_flag),
    .io_snapshots_3_robIdx_2_value(io_snapshots_3_robIdx_2_value),
    .io_snapshots_3_robIdx_3_flag(io_snapshots_3_robIdx_3_flag),
    .io_snapshots_3_robIdx_3_value(io_snapshots_3_robIdx_3_value),
    .io_snapshots_3_robIdx_4_flag(io_snapshots_3_robIdx_4_flag),
    .io_snapshots_3_robIdx_4_value(io_snapshots_3_robIdx_4_value),
    .io_snapshots_3_robIdx_5_flag(io_snapshots_3_robIdx_5_flag),
    .io_snapshots_3_robIdx_5_value(io_snapshots_3_robIdx_5_value),
    .io_snapshots_3_isCFI_0(io_snapshots_3_isCFI_0),
    .io_snapshots_3_isCFI_1(io_snapshots_3_isCFI_1),
    .io_snapshots_3_isCFI_2(io_snapshots_3_isCFI_2),
    .io_snapshots_3_isCFI_3(io_snapshots_3_isCFI_3),
    .io_snapshots_3_isCFI_4(io_snapshots_3_isCFI_4),
    .io_snapshots_3_isCFI_5(io_snapshots_3_isCFI_5),
    .io_enqPtr_flag(io_enqPtr_flag),
    .io_enqPtr_value(io_enqPtr_value),
    .io_deqPtr_flag(io_deqPtr_flag),
    .io_deqPtr_value(io_deqPtr_value),
    .io_valids_0(io_valids_0),
    .io_valids_1(io_valids_1),
    .io_valids_2(io_valids_2),
    .io_valids_3(io_valids_3)
  );
endmodule
