// 自动生成：scripts/gen_rxtxlinkmon.py —— 勿手改
module ReceiverLinkMonitor_xs(
  input clock,
  input reset,
  input io_in_txsactive,
  output io_in_rxsactive,
  input io_in_syscoreq,
  output io_in_syscoack,
  input io_in_tx_linkactivereq,
  output io_in_tx_linkactiveack,
  input io_in_tx_req_flitpend,
  input io_in_tx_req_flitv,
  input [161:0] io_in_tx_req_flit,
  output io_in_tx_req_lcrdv,
  input io_in_tx_rsp_flitpend,
  input io_in_tx_rsp_flitv,
  input [72:0] io_in_tx_rsp_flit,
  output io_in_tx_rsp_lcrdv,
  input io_in_tx_dat_flitpend,
  input io_in_tx_dat_flitv,
  input [421:0] io_in_tx_dat_flit,
  output io_in_tx_dat_lcrdv,
  output io_in_rx_linkactivereq,
  input io_in_rx_linkactiveack,
  output io_in_rx_rsp_flitpend,
  output io_in_rx_rsp_flitv,
  output [72:0] io_in_rx_rsp_flit,
  input io_in_rx_rsp_lcrdv,
  output io_in_rx_dat_flitpend,
  output io_in_rx_dat_flitv,
  output [421:0] io_in_rx_dat_flit,
  input io_in_rx_dat_lcrdv,
  output io_in_rx_snp_flitpend,
  output io_in_rx_snp_flitv,
  output [114:0] io_in_rx_snp_flit,
  input io_in_rx_snp_lcrdv,
  input io_out_tx_req_ready,
  output io_out_tx_req_valid,
  output [3:0] io_out_tx_req_bits_qos,
  output [10:0] io_out_tx_req_bits_srcID,
  output [11:0] io_out_tx_req_bits_txnID,
  output [10:0] io_out_tx_req_bits_returnNID,
  output io_out_tx_req_bits_stashNIDValid,
  output [11:0] io_out_tx_req_bits_returnTxnID,
  output [6:0] io_out_tx_req_bits_opcode,
  output [2:0] io_out_tx_req_bits_size,
  output [47:0] io_out_tx_req_bits_addr,
  output io_out_tx_req_bits_ns,
  output io_out_tx_req_bits_likelyshared,
  output io_out_tx_req_bits_allowRetry,
  output [1:0] io_out_tx_req_bits_order,
  output [3:0] io_out_tx_req_bits_pCrdType,
  output io_out_tx_req_bits_memAttr_allocate,
  output io_out_tx_req_bits_memAttr_cacheable,
  output io_out_tx_req_bits_memAttr_device,
  output io_out_tx_req_bits_memAttr_ewa,
  output io_out_tx_req_bits_snpAttr,
  output [7:0] io_out_tx_req_bits_lpIDWithPadding,
  output io_out_tx_req_bits_snoopMe,
  output io_out_tx_req_bits_expCompAck,
  output [1:0] io_out_tx_req_bits_tagOp,
  output io_out_tx_req_bits_traceTag,
  output io_out_tx_req_bits_mpam_perfMonGroup,
  output [8:0] io_out_tx_req_bits_mpam_partID,
  output io_out_tx_req_bits_mpam_mpamNS,
  output [3:0] io_out_tx_req_bits_rsvdc,
  input io_out_tx_rsp_ready,
  output io_out_tx_rsp_valid,
  output [3:0] io_out_tx_rsp_bits_qos,
  output [10:0] io_out_tx_rsp_bits_tgtID,
  output [10:0] io_out_tx_rsp_bits_srcID,
  output [11:0] io_out_tx_rsp_bits_txnID,
  output [4:0] io_out_tx_rsp_bits_opcode,
  output [1:0] io_out_tx_rsp_bits_respErr,
  output [2:0] io_out_tx_rsp_bits_resp,
  output [2:0] io_out_tx_rsp_bits_fwdState,
  output [2:0] io_out_tx_rsp_bits_cBusy,
  output [11:0] io_out_tx_rsp_bits_dbID,
  output [3:0] io_out_tx_rsp_bits_pCrdType,
  output [1:0] io_out_tx_rsp_bits_tagOp,
  output io_out_tx_rsp_bits_traceTag,
  input io_out_tx_dat_ready,
  output io_out_tx_dat_valid,
  output [3:0] io_out_tx_dat_bits_qos,
  output [10:0] io_out_tx_dat_bits_tgtID,
  output [10:0] io_out_tx_dat_bits_srcID,
  output [11:0] io_out_tx_dat_bits_txnID,
  output [10:0] io_out_tx_dat_bits_homeNID,
  output [3:0] io_out_tx_dat_bits_opcode,
  output [1:0] io_out_tx_dat_bits_respErr,
  output [2:0] io_out_tx_dat_bits_resp,
  output [3:0] io_out_tx_dat_bits_dataSource,
  output [2:0] io_out_tx_dat_bits_cBusy,
  output [11:0] io_out_tx_dat_bits_dbID,
  output [1:0] io_out_tx_dat_bits_ccID,
  output [1:0] io_out_tx_dat_bits_dataID,
  output [1:0] io_out_tx_dat_bits_tagOp,
  output [7:0] io_out_tx_dat_bits_tag,
  output [1:0] io_out_tx_dat_bits_tu,
  output io_out_tx_dat_bits_traceTag,
  output [3:0] io_out_tx_dat_bits_rsvdc,
  output [31:0] io_out_tx_dat_bits_be,
  output [255:0] io_out_tx_dat_bits_data,
  output [31:0] io_out_tx_dat_bits_dataCheck,
  output [3:0] io_out_tx_dat_bits_poison,
  output io_out_rx_rsp_ready,
  input io_out_rx_rsp_valid,
  input [3:0] io_out_rx_rsp_bits_qos,
  input [10:0] io_out_rx_rsp_bits_tgtID,
  input [10:0] io_out_rx_rsp_bits_srcID,
  input [11:0] io_out_rx_rsp_bits_txnID,
  input [4:0] io_out_rx_rsp_bits_opcode,
  input [1:0] io_out_rx_rsp_bits_respErr,
  input [2:0] io_out_rx_rsp_bits_resp,
  input [2:0] io_out_rx_rsp_bits_fwdState,
  input [2:0] io_out_rx_rsp_bits_cBusy,
  input [11:0] io_out_rx_rsp_bits_dbID,
  input [3:0] io_out_rx_rsp_bits_pCrdType,
  input [1:0] io_out_rx_rsp_bits_tagOp,
  input io_out_rx_rsp_bits_traceTag,
  output io_out_rx_dat_ready,
  input io_out_rx_dat_valid,
  input [3:0] io_out_rx_dat_bits_qos,
  input [10:0] io_out_rx_dat_bits_tgtID,
  input [10:0] io_out_rx_dat_bits_srcID,
  input [11:0] io_out_rx_dat_bits_txnID,
  input [10:0] io_out_rx_dat_bits_homeNID,
  input [3:0] io_out_rx_dat_bits_opcode,
  input [1:0] io_out_rx_dat_bits_respErr,
  input [2:0] io_out_rx_dat_bits_resp,
  input [3:0] io_out_rx_dat_bits_dataSource,
  input [2:0] io_out_rx_dat_bits_cBusy,
  input [11:0] io_out_rx_dat_bits_dbID,
  input [1:0] io_out_rx_dat_bits_ccID,
  input [1:0] io_out_rx_dat_bits_dataID,
  input [1:0] io_out_rx_dat_bits_tagOp,
  input [7:0] io_out_rx_dat_bits_tag,
  input [1:0] io_out_rx_dat_bits_tu,
  input io_out_rx_dat_bits_traceTag,
  input [3:0] io_out_rx_dat_bits_rsvdc,
  input [31:0] io_out_rx_dat_bits_be,
  input [255:0] io_out_rx_dat_bits_data,
  input [31:0] io_out_rx_dat_bits_dataCheck,
  input [3:0] io_out_rx_dat_bits_poison,
  output io_out_rx_snp_ready,
  input io_out_rx_snp_valid,
  input [3:0] io_out_rx_snp_bits_qos,
  input [10:0] io_out_rx_snp_bits_srcID,
  input [11:0] io_out_rx_snp_bits_txnID,
  input [10:0] io_out_rx_snp_bits_fwdNID,
  input [11:0] io_out_rx_snp_bits_fwdTxnID,
  input [4:0] io_out_rx_snp_bits_opcode,
  input [44:0] io_out_rx_snp_bits_addr,
  input io_out_rx_snp_bits_ns,
  input io_out_rx_snp_bits_doNotGoToSD,
  input io_out_rx_snp_bits_retToSrc,
  input io_out_rx_snp_bits_traceTag,
  input io_out_rx_snp_bits_mpam_perfMonGroup,
  input [8:0] io_out_rx_snp_bits_mpam_partID,
  input io_out_rx_snp_bits_mpam_mpamNS
);

  xs_ReceiverLinkMonitor_core u_core (
    .clock(clock),
    .reset(reset),
    .io_in_txsactive(io_in_txsactive),
    .io_in_rxsactive(io_in_rxsactive),
    .io_in_syscoreq(io_in_syscoreq),
    .io_in_syscoack(io_in_syscoack),
    .io_in_tx_linkactivereq(io_in_tx_linkactivereq),
    .io_in_tx_linkactiveack(io_in_tx_linkactiveack),
    .io_in_tx_req_flitpend(io_in_tx_req_flitpend),
    .io_in_tx_req_flitv(io_in_tx_req_flitv),
    .io_in_tx_req_flit(io_in_tx_req_flit),
    .io_in_tx_req_lcrdv(io_in_tx_req_lcrdv),
    .io_in_tx_rsp_flitpend(io_in_tx_rsp_flitpend),
    .io_in_tx_rsp_flitv(io_in_tx_rsp_flitv),
    .io_in_tx_rsp_flit(io_in_tx_rsp_flit),
    .io_in_tx_rsp_lcrdv(io_in_tx_rsp_lcrdv),
    .io_in_tx_dat_flitpend(io_in_tx_dat_flitpend),
    .io_in_tx_dat_flitv(io_in_tx_dat_flitv),
    .io_in_tx_dat_flit(io_in_tx_dat_flit),
    .io_in_tx_dat_lcrdv(io_in_tx_dat_lcrdv),
    .io_in_rx_linkactivereq(io_in_rx_linkactivereq),
    .io_in_rx_linkactiveack(io_in_rx_linkactiveack),
    .io_in_rx_rsp_flitpend(io_in_rx_rsp_flitpend),
    .io_in_rx_rsp_flitv(io_in_rx_rsp_flitv),
    .io_in_rx_rsp_flit(io_in_rx_rsp_flit),
    .io_in_rx_rsp_lcrdv(io_in_rx_rsp_lcrdv),
    .io_in_rx_dat_flitpend(io_in_rx_dat_flitpend),
    .io_in_rx_dat_flitv(io_in_rx_dat_flitv),
    .io_in_rx_dat_flit(io_in_rx_dat_flit),
    .io_in_rx_dat_lcrdv(io_in_rx_dat_lcrdv),
    .io_in_rx_snp_flitpend(io_in_rx_snp_flitpend),
    .io_in_rx_snp_flitv(io_in_rx_snp_flitv),
    .io_in_rx_snp_flit(io_in_rx_snp_flit),
    .io_in_rx_snp_lcrdv(io_in_rx_snp_lcrdv),
    .io_out_tx_req_ready(io_out_tx_req_ready),
    .io_out_tx_req_valid(io_out_tx_req_valid),
    .io_out_tx_req_bits_qos(io_out_tx_req_bits_qos),
    .io_out_tx_req_bits_srcID(io_out_tx_req_bits_srcID),
    .io_out_tx_req_bits_txnID(io_out_tx_req_bits_txnID),
    .io_out_tx_req_bits_returnNID(io_out_tx_req_bits_returnNID),
    .io_out_tx_req_bits_stashNIDValid(io_out_tx_req_bits_stashNIDValid),
    .io_out_tx_req_bits_returnTxnID(io_out_tx_req_bits_returnTxnID),
    .io_out_tx_req_bits_opcode(io_out_tx_req_bits_opcode),
    .io_out_tx_req_bits_size(io_out_tx_req_bits_size),
    .io_out_tx_req_bits_addr(io_out_tx_req_bits_addr),
    .io_out_tx_req_bits_ns(io_out_tx_req_bits_ns),
    .io_out_tx_req_bits_likelyshared(io_out_tx_req_bits_likelyshared),
    .io_out_tx_req_bits_allowRetry(io_out_tx_req_bits_allowRetry),
    .io_out_tx_req_bits_order(io_out_tx_req_bits_order),
    .io_out_tx_req_bits_pCrdType(io_out_tx_req_bits_pCrdType),
    .io_out_tx_req_bits_memAttr_allocate(io_out_tx_req_bits_memAttr_allocate),
    .io_out_tx_req_bits_memAttr_cacheable(io_out_tx_req_bits_memAttr_cacheable),
    .io_out_tx_req_bits_memAttr_device(io_out_tx_req_bits_memAttr_device),
    .io_out_tx_req_bits_memAttr_ewa(io_out_tx_req_bits_memAttr_ewa),
    .io_out_tx_req_bits_snpAttr(io_out_tx_req_bits_snpAttr),
    .io_out_tx_req_bits_lpIDWithPadding(io_out_tx_req_bits_lpIDWithPadding),
    .io_out_tx_req_bits_snoopMe(io_out_tx_req_bits_snoopMe),
    .io_out_tx_req_bits_expCompAck(io_out_tx_req_bits_expCompAck),
    .io_out_tx_req_bits_tagOp(io_out_tx_req_bits_tagOp),
    .io_out_tx_req_bits_traceTag(io_out_tx_req_bits_traceTag),
    .io_out_tx_req_bits_mpam_perfMonGroup(io_out_tx_req_bits_mpam_perfMonGroup),
    .io_out_tx_req_bits_mpam_partID(io_out_tx_req_bits_mpam_partID),
    .io_out_tx_req_bits_mpam_mpamNS(io_out_tx_req_bits_mpam_mpamNS),
    .io_out_tx_req_bits_rsvdc(io_out_tx_req_bits_rsvdc),
    .io_out_tx_rsp_ready(io_out_tx_rsp_ready),
    .io_out_tx_rsp_valid(io_out_tx_rsp_valid),
    .io_out_tx_rsp_bits_qos(io_out_tx_rsp_bits_qos),
    .io_out_tx_rsp_bits_tgtID(io_out_tx_rsp_bits_tgtID),
    .io_out_tx_rsp_bits_srcID(io_out_tx_rsp_bits_srcID),
    .io_out_tx_rsp_bits_txnID(io_out_tx_rsp_bits_txnID),
    .io_out_tx_rsp_bits_opcode(io_out_tx_rsp_bits_opcode),
    .io_out_tx_rsp_bits_respErr(io_out_tx_rsp_bits_respErr),
    .io_out_tx_rsp_bits_resp(io_out_tx_rsp_bits_resp),
    .io_out_tx_rsp_bits_fwdState(io_out_tx_rsp_bits_fwdState),
    .io_out_tx_rsp_bits_cBusy(io_out_tx_rsp_bits_cBusy),
    .io_out_tx_rsp_bits_dbID(io_out_tx_rsp_bits_dbID),
    .io_out_tx_rsp_bits_pCrdType(io_out_tx_rsp_bits_pCrdType),
    .io_out_tx_rsp_bits_tagOp(io_out_tx_rsp_bits_tagOp),
    .io_out_tx_rsp_bits_traceTag(io_out_tx_rsp_bits_traceTag),
    .io_out_tx_dat_ready(io_out_tx_dat_ready),
    .io_out_tx_dat_valid(io_out_tx_dat_valid),
    .io_out_tx_dat_bits_qos(io_out_tx_dat_bits_qos),
    .io_out_tx_dat_bits_tgtID(io_out_tx_dat_bits_tgtID),
    .io_out_tx_dat_bits_srcID(io_out_tx_dat_bits_srcID),
    .io_out_tx_dat_bits_txnID(io_out_tx_dat_bits_txnID),
    .io_out_tx_dat_bits_homeNID(io_out_tx_dat_bits_homeNID),
    .io_out_tx_dat_bits_opcode(io_out_tx_dat_bits_opcode),
    .io_out_tx_dat_bits_respErr(io_out_tx_dat_bits_respErr),
    .io_out_tx_dat_bits_resp(io_out_tx_dat_bits_resp),
    .io_out_tx_dat_bits_dataSource(io_out_tx_dat_bits_dataSource),
    .io_out_tx_dat_bits_cBusy(io_out_tx_dat_bits_cBusy),
    .io_out_tx_dat_bits_dbID(io_out_tx_dat_bits_dbID),
    .io_out_tx_dat_bits_ccID(io_out_tx_dat_bits_ccID),
    .io_out_tx_dat_bits_dataID(io_out_tx_dat_bits_dataID),
    .io_out_tx_dat_bits_tagOp(io_out_tx_dat_bits_tagOp),
    .io_out_tx_dat_bits_tag(io_out_tx_dat_bits_tag),
    .io_out_tx_dat_bits_tu(io_out_tx_dat_bits_tu),
    .io_out_tx_dat_bits_traceTag(io_out_tx_dat_bits_traceTag),
    .io_out_tx_dat_bits_rsvdc(io_out_tx_dat_bits_rsvdc),
    .io_out_tx_dat_bits_be(io_out_tx_dat_bits_be),
    .io_out_tx_dat_bits_data(io_out_tx_dat_bits_data),
    .io_out_tx_dat_bits_dataCheck(io_out_tx_dat_bits_dataCheck),
    .io_out_tx_dat_bits_poison(io_out_tx_dat_bits_poison),
    .io_out_rx_rsp_ready(io_out_rx_rsp_ready),
    .io_out_rx_rsp_valid(io_out_rx_rsp_valid),
    .io_out_rx_rsp_bits_qos(io_out_rx_rsp_bits_qos),
    .io_out_rx_rsp_bits_tgtID(io_out_rx_rsp_bits_tgtID),
    .io_out_rx_rsp_bits_srcID(io_out_rx_rsp_bits_srcID),
    .io_out_rx_rsp_bits_txnID(io_out_rx_rsp_bits_txnID),
    .io_out_rx_rsp_bits_opcode(io_out_rx_rsp_bits_opcode),
    .io_out_rx_rsp_bits_respErr(io_out_rx_rsp_bits_respErr),
    .io_out_rx_rsp_bits_resp(io_out_rx_rsp_bits_resp),
    .io_out_rx_rsp_bits_fwdState(io_out_rx_rsp_bits_fwdState),
    .io_out_rx_rsp_bits_cBusy(io_out_rx_rsp_bits_cBusy),
    .io_out_rx_rsp_bits_dbID(io_out_rx_rsp_bits_dbID),
    .io_out_rx_rsp_bits_pCrdType(io_out_rx_rsp_bits_pCrdType),
    .io_out_rx_rsp_bits_tagOp(io_out_rx_rsp_bits_tagOp),
    .io_out_rx_rsp_bits_traceTag(io_out_rx_rsp_bits_traceTag),
    .io_out_rx_dat_ready(io_out_rx_dat_ready),
    .io_out_rx_dat_valid(io_out_rx_dat_valid),
    .io_out_rx_dat_bits_qos(io_out_rx_dat_bits_qos),
    .io_out_rx_dat_bits_tgtID(io_out_rx_dat_bits_tgtID),
    .io_out_rx_dat_bits_srcID(io_out_rx_dat_bits_srcID),
    .io_out_rx_dat_bits_txnID(io_out_rx_dat_bits_txnID),
    .io_out_rx_dat_bits_homeNID(io_out_rx_dat_bits_homeNID),
    .io_out_rx_dat_bits_opcode(io_out_rx_dat_bits_opcode),
    .io_out_rx_dat_bits_respErr(io_out_rx_dat_bits_respErr),
    .io_out_rx_dat_bits_resp(io_out_rx_dat_bits_resp),
    .io_out_rx_dat_bits_dataSource(io_out_rx_dat_bits_dataSource),
    .io_out_rx_dat_bits_cBusy(io_out_rx_dat_bits_cBusy),
    .io_out_rx_dat_bits_dbID(io_out_rx_dat_bits_dbID),
    .io_out_rx_dat_bits_ccID(io_out_rx_dat_bits_ccID),
    .io_out_rx_dat_bits_dataID(io_out_rx_dat_bits_dataID),
    .io_out_rx_dat_bits_tagOp(io_out_rx_dat_bits_tagOp),
    .io_out_rx_dat_bits_tag(io_out_rx_dat_bits_tag),
    .io_out_rx_dat_bits_tu(io_out_rx_dat_bits_tu),
    .io_out_rx_dat_bits_traceTag(io_out_rx_dat_bits_traceTag),
    .io_out_rx_dat_bits_rsvdc(io_out_rx_dat_bits_rsvdc),
    .io_out_rx_dat_bits_be(io_out_rx_dat_bits_be),
    .io_out_rx_dat_bits_data(io_out_rx_dat_bits_data),
    .io_out_rx_dat_bits_dataCheck(io_out_rx_dat_bits_dataCheck),
    .io_out_rx_dat_bits_poison(io_out_rx_dat_bits_poison),
    .io_out_rx_snp_ready(io_out_rx_snp_ready),
    .io_out_rx_snp_valid(io_out_rx_snp_valid),
    .io_out_rx_snp_bits_qos(io_out_rx_snp_bits_qos),
    .io_out_rx_snp_bits_srcID(io_out_rx_snp_bits_srcID),
    .io_out_rx_snp_bits_txnID(io_out_rx_snp_bits_txnID),
    .io_out_rx_snp_bits_fwdNID(io_out_rx_snp_bits_fwdNID),
    .io_out_rx_snp_bits_fwdTxnID(io_out_rx_snp_bits_fwdTxnID),
    .io_out_rx_snp_bits_opcode(io_out_rx_snp_bits_opcode),
    .io_out_rx_snp_bits_addr(io_out_rx_snp_bits_addr),
    .io_out_rx_snp_bits_ns(io_out_rx_snp_bits_ns),
    .io_out_rx_snp_bits_doNotGoToSD(io_out_rx_snp_bits_doNotGoToSD),
    .io_out_rx_snp_bits_retToSrc(io_out_rx_snp_bits_retToSrc),
    .io_out_rx_snp_bits_traceTag(io_out_rx_snp_bits_traceTag),
    .io_out_rx_snp_bits_mpam_perfMonGroup(io_out_rx_snp_bits_mpam_perfMonGroup),
    .io_out_rx_snp_bits_mpam_partID(io_out_rx_snp_bits_mpam_partID),
    .io_out_rx_snp_bits_mpam_mpamNS(io_out_rx_snp_bits_mpam_mpamNS)
  );
endmodule
