// 自动生成：scripts/gen_fastarbiter.py —— 勿手改
module FastArbiter_46_xs(
  input clock,
  input reset,
  input io_in_0_valid,
  input [10:0] io_in_0_bits_tgtID,
  input [10:0] io_in_0_bits_srcID,
  input [11:0] io_in_0_bits_txnID,
  input [10:0] io_in_0_bits_homeNID,
  input [3:0] io_in_0_bits_opcode,
  input [2:0] io_in_0_bits_resp,
  input [3:0] io_in_0_bits_dataSource,
  input [11:0] io_in_0_bits_dbID,
  input [1:0] io_in_0_bits_dataID,
  input [31:0] io_in_0_bits_be,
  input [255:0] io_in_0_bits_data,
  input [31:0] io_in_0_bits_dataCheck,
  input io_in_1_valid,
  input [10:0] io_in_1_bits_tgtID,
  input [10:0] io_in_1_bits_srcID,
  input [11:0] io_in_1_bits_txnID,
  input [10:0] io_in_1_bits_homeNID,
  input [3:0] io_in_1_bits_opcode,
  input [2:0] io_in_1_bits_resp,
  input [3:0] io_in_1_bits_dataSource,
  input [11:0] io_in_1_bits_dbID,
  input [1:0] io_in_1_bits_dataID,
  input [31:0] io_in_1_bits_be,
  input [255:0] io_in_1_bits_data,
  input [31:0] io_in_1_bits_dataCheck,
  input io_in_2_valid,
  input [10:0] io_in_2_bits_tgtID,
  input [10:0] io_in_2_bits_srcID,
  input [11:0] io_in_2_bits_txnID,
  input [10:0] io_in_2_bits_homeNID,
  input [3:0] io_in_2_bits_opcode,
  input [2:0] io_in_2_bits_resp,
  input [3:0] io_in_2_bits_dataSource,
  input [11:0] io_in_2_bits_dbID,
  input [1:0] io_in_2_bits_dataID,
  input [31:0] io_in_2_bits_be,
  input [255:0] io_in_2_bits_data,
  input [31:0] io_in_2_bits_dataCheck,
  input io_in_3_valid,
  input [10:0] io_in_3_bits_tgtID,
  input [10:0] io_in_3_bits_srcID,
  input [11:0] io_in_3_bits_txnID,
  input [10:0] io_in_3_bits_homeNID,
  input [3:0] io_in_3_bits_opcode,
  input [2:0] io_in_3_bits_resp,
  input [3:0] io_in_3_bits_dataSource,
  input [11:0] io_in_3_bits_dbID,
  input [1:0] io_in_3_bits_dataID,
  input [31:0] io_in_3_bits_be,
  input [255:0] io_in_3_bits_data,
  input [31:0] io_in_3_bits_dataCheck,
  input io_out_ready,
  output io_out_valid,
  output [10:0] io_out_bits_tgtID,
  output [10:0] io_out_bits_srcID,
  output [11:0] io_out_bits_txnID,
  output [10:0] io_out_bits_homeNID,
  output [3:0] io_out_bits_opcode,
  output [2:0] io_out_bits_resp,
  output [3:0] io_out_bits_dataSource,
  output [11:0] io_out_bits_dbID,
  output [1:0] io_out_bits_dataID,
  output [31:0] io_out_bits_be,
  output [255:0] io_out_bits_data,
  output [31:0] io_out_bits_dataCheck,
  output [1:0] io_chosen
);
  xs_FastArbiter_46_core u_core (
    .clock(clock),
    .reset(reset),
    .io_in_0_valid(io_in_0_valid),
    .io_in_0_bits_tgtID(io_in_0_bits_tgtID),
    .io_in_0_bits_srcID(io_in_0_bits_srcID),
    .io_in_0_bits_txnID(io_in_0_bits_txnID),
    .io_in_0_bits_homeNID(io_in_0_bits_homeNID),
    .io_in_0_bits_opcode(io_in_0_bits_opcode),
    .io_in_0_bits_resp(io_in_0_bits_resp),
    .io_in_0_bits_dataSource(io_in_0_bits_dataSource),
    .io_in_0_bits_dbID(io_in_0_bits_dbID),
    .io_in_0_bits_dataID(io_in_0_bits_dataID),
    .io_in_0_bits_be(io_in_0_bits_be),
    .io_in_0_bits_data(io_in_0_bits_data),
    .io_in_0_bits_dataCheck(io_in_0_bits_dataCheck),
    .io_in_1_valid(io_in_1_valid),
    .io_in_1_bits_tgtID(io_in_1_bits_tgtID),
    .io_in_1_bits_srcID(io_in_1_bits_srcID),
    .io_in_1_bits_txnID(io_in_1_bits_txnID),
    .io_in_1_bits_homeNID(io_in_1_bits_homeNID),
    .io_in_1_bits_opcode(io_in_1_bits_opcode),
    .io_in_1_bits_resp(io_in_1_bits_resp),
    .io_in_1_bits_dataSource(io_in_1_bits_dataSource),
    .io_in_1_bits_dbID(io_in_1_bits_dbID),
    .io_in_1_bits_dataID(io_in_1_bits_dataID),
    .io_in_1_bits_be(io_in_1_bits_be),
    .io_in_1_bits_data(io_in_1_bits_data),
    .io_in_1_bits_dataCheck(io_in_1_bits_dataCheck),
    .io_in_2_valid(io_in_2_valid),
    .io_in_2_bits_tgtID(io_in_2_bits_tgtID),
    .io_in_2_bits_srcID(io_in_2_bits_srcID),
    .io_in_2_bits_txnID(io_in_2_bits_txnID),
    .io_in_2_bits_homeNID(io_in_2_bits_homeNID),
    .io_in_2_bits_opcode(io_in_2_bits_opcode),
    .io_in_2_bits_resp(io_in_2_bits_resp),
    .io_in_2_bits_dataSource(io_in_2_bits_dataSource),
    .io_in_2_bits_dbID(io_in_2_bits_dbID),
    .io_in_2_bits_dataID(io_in_2_bits_dataID),
    .io_in_2_bits_be(io_in_2_bits_be),
    .io_in_2_bits_data(io_in_2_bits_data),
    .io_in_2_bits_dataCheck(io_in_2_bits_dataCheck),
    .io_in_3_valid(io_in_3_valid),
    .io_in_3_bits_tgtID(io_in_3_bits_tgtID),
    .io_in_3_bits_srcID(io_in_3_bits_srcID),
    .io_in_3_bits_txnID(io_in_3_bits_txnID),
    .io_in_3_bits_homeNID(io_in_3_bits_homeNID),
    .io_in_3_bits_opcode(io_in_3_bits_opcode),
    .io_in_3_bits_resp(io_in_3_bits_resp),
    .io_in_3_bits_dataSource(io_in_3_bits_dataSource),
    .io_in_3_bits_dbID(io_in_3_bits_dbID),
    .io_in_3_bits_dataID(io_in_3_bits_dataID),
    .io_in_3_bits_be(io_in_3_bits_be),
    .io_in_3_bits_data(io_in_3_bits_data),
    .io_in_3_bits_dataCheck(io_in_3_bits_dataCheck),
    .io_out_ready(io_out_ready),
    .io_out_valid(io_out_valid),
    .io_out_bits_tgtID(io_out_bits_tgtID),
    .io_out_bits_srcID(io_out_bits_srcID),
    .io_out_bits_txnID(io_out_bits_txnID),
    .io_out_bits_homeNID(io_out_bits_homeNID),
    .io_out_bits_opcode(io_out_bits_opcode),
    .io_out_bits_resp(io_out_bits_resp),
    .io_out_bits_dataSource(io_out_bits_dataSource),
    .io_out_bits_dbID(io_out_bits_dbID),
    .io_out_bits_dataID(io_out_bits_dataID),
    .io_out_bits_be(io_out_bits_be),
    .io_out_bits_data(io_out_bits_data),
    .io_out_bits_dataCheck(io_out_bits_dataCheck),
    .io_chosen(io_chosen)
  );
endmodule
