# PTW FM 钉点: 由 gen_pins.py 从 unmatched_full.rpt 生成 —— ref 展平叶名 ↔ impl 结构体/改名寄存器
set _pin_n 0; set _pin_fail 0
foreach {rl il} {
  {hptw_resp_entry_level_reg[0]} {u_core/hptw_resp_r_reg\[level][0]}
  {hptw_resp_entry_level_reg[1]} {u_core/hptw_resp_r_reg\[level][1]}
  {hptw_resp_entry_n_reg} {u_core/hptw_resp_r_reg\[n]}
  {hptw_resp_entry_pbmt_reg[0]} {u_core/hptw_resp_r_reg\[pbmt][0]}
  {hptw_resp_entry_pbmt_reg[1]} {u_core/hptw_resp_r_reg\[pbmt][1]}
  {hptw_resp_entry_perm_a_reg} {u_core/hptw_resp_r_reg\[perm]\[a]}
  {hptw_resp_entry_perm_d_reg} {u_core/hptw_resp_r_reg\[perm]\[d]}
  {hptw_resp_entry_perm_g_reg} {u_core/hptw_resp_r_reg\[perm]\[g]}
  {hptw_resp_entry_perm_r_reg} {u_core/hptw_resp_r_reg\[perm]\[r]}
  {hptw_resp_entry_perm_u_reg} {u_core/hptw_resp_r_reg\[perm]\[u]}
  {hptw_resp_entry_perm_w_reg} {u_core/hptw_resp_r_reg\[perm]\[w]}
  {hptw_resp_entry_perm_x_reg} {u_core/hptw_resp_r_reg\[perm]\[x]}
  {hptw_resp_entry_ppn_reg[0]} {u_core/hptw_resp_r_reg\[ppn][0]}
  {hptw_resp_entry_ppn_reg[10]} {u_core/hptw_resp_r_reg\[ppn][10]}
  {hptw_resp_entry_ppn_reg[11]} {u_core/hptw_resp_r_reg\[ppn][11]}
  {hptw_resp_entry_ppn_reg[12]} {u_core/hptw_resp_r_reg\[ppn][12]}
  {hptw_resp_entry_ppn_reg[13]} {u_core/hptw_resp_r_reg\[ppn][13]}
  {hptw_resp_entry_ppn_reg[14]} {u_core/hptw_resp_r_reg\[ppn][14]}
  {hptw_resp_entry_ppn_reg[15]} {u_core/hptw_resp_r_reg\[ppn][15]}
  {hptw_resp_entry_ppn_reg[16]} {u_core/hptw_resp_r_reg\[ppn][16]}
  {hptw_resp_entry_ppn_reg[17]} {u_core/hptw_resp_r_reg\[ppn][17]}
  {hptw_resp_entry_ppn_reg[18]} {u_core/hptw_resp_r_reg\[ppn][18]}
  {hptw_resp_entry_ppn_reg[19]} {u_core/hptw_resp_r_reg\[ppn][19]}
  {hptw_resp_entry_ppn_reg[1]} {u_core/hptw_resp_r_reg\[ppn][1]}
  {hptw_resp_entry_ppn_reg[20]} {u_core/hptw_resp_r_reg\[ppn][20]}
  {hptw_resp_entry_ppn_reg[21]} {u_core/hptw_resp_r_reg\[ppn][21]}
  {hptw_resp_entry_ppn_reg[22]} {u_core/hptw_resp_r_reg\[ppn][22]}
  {hptw_resp_entry_ppn_reg[23]} {u_core/hptw_resp_r_reg\[ppn][23]}
  {hptw_resp_entry_ppn_reg[24]} {u_core/hptw_resp_r_reg\[ppn][24]}
  {hptw_resp_entry_ppn_reg[25]} {u_core/hptw_resp_r_reg\[ppn][25]}
  {hptw_resp_entry_ppn_reg[26]} {u_core/hptw_resp_r_reg\[ppn][26]}
  {hptw_resp_entry_ppn_reg[27]} {u_core/hptw_resp_r_reg\[ppn][27]}
  {hptw_resp_entry_ppn_reg[28]} {u_core/hptw_resp_r_reg\[ppn][28]}
  {hptw_resp_entry_ppn_reg[29]} {u_core/hptw_resp_r_reg\[ppn][29]}
  {hptw_resp_entry_ppn_reg[2]} {u_core/hptw_resp_r_reg\[ppn][2]}
  {hptw_resp_entry_ppn_reg[30]} {u_core/hptw_resp_r_reg\[ppn][30]}
  {hptw_resp_entry_ppn_reg[31]} {u_core/hptw_resp_r_reg\[ppn][31]}
  {hptw_resp_entry_ppn_reg[32]} {u_core/hptw_resp_r_reg\[ppn][32]}
  {hptw_resp_entry_ppn_reg[33]} {u_core/hptw_resp_r_reg\[ppn][33]}
  {hptw_resp_entry_ppn_reg[34]} {u_core/hptw_resp_r_reg\[ppn][34]}
  {hptw_resp_entry_ppn_reg[35]} {u_core/hptw_resp_r_reg\[ppn][35]}
  {hptw_resp_entry_ppn_reg[36]} {u_core/hptw_resp_r_reg\[ppn][36]}
  {hptw_resp_entry_ppn_reg[37]} {u_core/hptw_resp_r_reg\[ppn][37]}
  {hptw_resp_entry_ppn_reg[3]} {u_core/hptw_resp_r_reg\[ppn][3]}
  {hptw_resp_entry_ppn_reg[4]} {u_core/hptw_resp_r_reg\[ppn][4]}
  {hptw_resp_entry_ppn_reg[5]} {u_core/hptw_resp_r_reg\[ppn][5]}
  {hptw_resp_entry_ppn_reg[6]} {u_core/hptw_resp_r_reg\[ppn][6]}
  {hptw_resp_entry_ppn_reg[7]} {u_core/hptw_resp_r_reg\[ppn][7]}
  {hptw_resp_entry_ppn_reg[8]} {u_core/hptw_resp_r_reg\[ppn][8]}
  {hptw_resp_entry_ppn_reg[9]} {u_core/hptw_resp_r_reg\[ppn][9]}
  {hptw_resp_entry_tag_reg[0]} {u_core/hptw_resp_r_reg\[tag][0]}
  {hptw_resp_entry_tag_reg[10]} {u_core/hptw_resp_r_reg\[tag][10]}
  {hptw_resp_entry_tag_reg[11]} {u_core/hptw_resp_r_reg\[tag][11]}
  {hptw_resp_entry_tag_reg[12]} {u_core/hptw_resp_r_reg\[tag][12]}
  {hptw_resp_entry_tag_reg[13]} {u_core/hptw_resp_r_reg\[tag][13]}
  {hptw_resp_entry_tag_reg[14]} {u_core/hptw_resp_r_reg\[tag][14]}
  {hptw_resp_entry_tag_reg[15]} {u_core/hptw_resp_r_reg\[tag][15]}
  {hptw_resp_entry_tag_reg[16]} {u_core/hptw_resp_r_reg\[tag][16]}
  {hptw_resp_entry_tag_reg[17]} {u_core/hptw_resp_r_reg\[tag][17]}
  {hptw_resp_entry_tag_reg[18]} {u_core/hptw_resp_r_reg\[tag][18]}
  {hptw_resp_entry_tag_reg[19]} {u_core/hptw_resp_r_reg\[tag][19]}
  {hptw_resp_entry_tag_reg[1]} {u_core/hptw_resp_r_reg\[tag][1]}
  {hptw_resp_entry_tag_reg[20]} {u_core/hptw_resp_r_reg\[tag][20]}
  {hptw_resp_entry_tag_reg[21]} {u_core/hptw_resp_r_reg\[tag][21]}
  {hptw_resp_entry_tag_reg[22]} {u_core/hptw_resp_r_reg\[tag][22]}
  {hptw_resp_entry_tag_reg[23]} {u_core/hptw_resp_r_reg\[tag][23]}
  {hptw_resp_entry_tag_reg[24]} {u_core/hptw_resp_r_reg\[tag][24]}
  {hptw_resp_entry_tag_reg[25]} {u_core/hptw_resp_r_reg\[tag][25]}
  {hptw_resp_entry_tag_reg[26]} {u_core/hptw_resp_r_reg\[tag][26]}
  {hptw_resp_entry_tag_reg[27]} {u_core/hptw_resp_r_reg\[tag][27]}
  {hptw_resp_entry_tag_reg[28]} {u_core/hptw_resp_r_reg\[tag][28]}
  {hptw_resp_entry_tag_reg[29]} {u_core/hptw_resp_r_reg\[tag][29]}
  {hptw_resp_entry_tag_reg[2]} {u_core/hptw_resp_r_reg\[tag][2]}
  {hptw_resp_entry_tag_reg[30]} {u_core/hptw_resp_r_reg\[tag][30]}
  {hptw_resp_entry_tag_reg[31]} {u_core/hptw_resp_r_reg\[tag][31]}
  {hptw_resp_entry_tag_reg[32]} {u_core/hptw_resp_r_reg\[tag][32]}
  {hptw_resp_entry_tag_reg[33]} {u_core/hptw_resp_r_reg\[tag][33]}
  {hptw_resp_entry_tag_reg[34]} {u_core/hptw_resp_r_reg\[tag][34]}
  {hptw_resp_entry_tag_reg[35]} {u_core/hptw_resp_r_reg\[tag][35]}
  {hptw_resp_entry_tag_reg[36]} {u_core/hptw_resp_r_reg\[tag][36]}
  {hptw_resp_entry_tag_reg[37]} {u_core/hptw_resp_r_reg\[tag][37]}
  {hptw_resp_entry_tag_reg[3]} {u_core/hptw_resp_r_reg\[tag][3]}
  {hptw_resp_entry_tag_reg[4]} {u_core/hptw_resp_r_reg\[tag][4]}
  {hptw_resp_entry_tag_reg[5]} {u_core/hptw_resp_r_reg\[tag][5]}
  {hptw_resp_entry_tag_reg[6]} {u_core/hptw_resp_r_reg\[tag][6]}
  {hptw_resp_entry_tag_reg[7]} {u_core/hptw_resp_r_reg\[tag][7]}
  {hptw_resp_entry_tag_reg[8]} {u_core/hptw_resp_r_reg\[tag][8]}
  {hptw_resp_entry_tag_reg[9]} {u_core/hptw_resp_r_reg\[tag][9]}
  {hptw_resp_entry_vmid_reg[0]} {u_core/hptw_resp_r_reg\[vmid][0]}
  {hptw_resp_entry_vmid_reg[10]} {u_core/hptw_resp_r_reg\[vmid][10]}
  {hptw_resp_entry_vmid_reg[11]} {u_core/hptw_resp_r_reg\[vmid][11]}
  {hptw_resp_entry_vmid_reg[12]} {u_core/hptw_resp_r_reg\[vmid][12]}
  {hptw_resp_entry_vmid_reg[13]} {u_core/hptw_resp_r_reg\[vmid][13]}
  {hptw_resp_entry_vmid_reg[1]} {u_core/hptw_resp_r_reg\[vmid][1]}
  {hptw_resp_entry_vmid_reg[2]} {u_core/hptw_resp_r_reg\[vmid][2]}
  {hptw_resp_entry_vmid_reg[3]} {u_core/hptw_resp_r_reg\[vmid][3]}
  {hptw_resp_entry_vmid_reg[4]} {u_core/hptw_resp_r_reg\[vmid][4]}
  {hptw_resp_entry_vmid_reg[5]} {u_core/hptw_resp_r_reg\[vmid][5]}
  {hptw_resp_entry_vmid_reg[6]} {u_core/hptw_resp_r_reg\[vmid][6]}
  {hptw_resp_entry_vmid_reg[7]} {u_core/hptw_resp_r_reg\[vmid][7]}
  {hptw_resp_entry_vmid_reg[8]} {u_core/hptw_resp_r_reg\[vmid][8]}
  {hptw_resp_entry_vmid_reg[9]} {u_core/hptw_resp_r_reg\[vmid][9]}
  {io_perf_0_value_REG_reg} {u_core/perf_event_s1_reg[0]}
  {io_perf_1_value_REG_reg} {u_core/perf_event_s1_reg[1]}
  {io_perf_2_value_REG_reg} {u_core/perf_event_s1_reg[2]}
  {l3Hit_reg} {u_core/l3_hit_r_reg}
  {ppn_reg[0]} {u_core/root_or_cache_ppn_reg[0]}
  {ppn_reg[10]} {u_core/root_or_cache_ppn_reg[10]}
  {ppn_reg[11]} {u_core/root_or_cache_ppn_reg[11]}
  {ppn_reg[12]} {u_core/root_or_cache_ppn_reg[12]}
  {ppn_reg[13]} {u_core/root_or_cache_ppn_reg[13]}
  {ppn_reg[14]} {u_core/root_or_cache_ppn_reg[14]}
  {ppn_reg[15]} {u_core/root_or_cache_ppn_reg[15]}
  {ppn_reg[16]} {u_core/root_or_cache_ppn_reg[16]}
  {ppn_reg[17]} {u_core/root_or_cache_ppn_reg[17]}
  {ppn_reg[18]} {u_core/root_or_cache_ppn_reg[18]}
  {ppn_reg[19]} {u_core/root_or_cache_ppn_reg[19]}
  {ppn_reg[1]} {u_core/root_or_cache_ppn_reg[1]}
  {ppn_reg[20]} {u_core/root_or_cache_ppn_reg[20]}
  {ppn_reg[21]} {u_core/root_or_cache_ppn_reg[21]}
  {ppn_reg[22]} {u_core/root_or_cache_ppn_reg[22]}
  {ppn_reg[23]} {u_core/root_or_cache_ppn_reg[23]}
  {ppn_reg[24]} {u_core/root_or_cache_ppn_reg[24]}
  {ppn_reg[25]} {u_core/root_or_cache_ppn_reg[25]}
  {ppn_reg[26]} {u_core/root_or_cache_ppn_reg[26]}
  {ppn_reg[27]} {u_core/root_or_cache_ppn_reg[27]}
  {ppn_reg[28]} {u_core/root_or_cache_ppn_reg[28]}
  {ppn_reg[29]} {u_core/root_or_cache_ppn_reg[29]}
  {ppn_reg[2]} {u_core/root_or_cache_ppn_reg[2]}
  {ppn_reg[30]} {u_core/root_or_cache_ppn_reg[30]}
  {ppn_reg[31]} {u_core/root_or_cache_ppn_reg[31]}
  {ppn_reg[32]} {u_core/root_or_cache_ppn_reg[32]}
  {ppn_reg[33]} {u_core/root_or_cache_ppn_reg[33]}
  {ppn_reg[34]} {u_core/root_or_cache_ppn_reg[34]}
  {ppn_reg[35]} {u_core/root_or_cache_ppn_reg[35]}
  {ppn_reg[36]} {u_core/root_or_cache_ppn_reg[36]}
  {ppn_reg[37]} {u_core/root_or_cache_ppn_reg[37]}
  {ppn_reg[38]} {u_core/root_or_cache_ppn_reg[38]}
  {ppn_reg[39]} {u_core/root_or_cache_ppn_reg[39]}
  {ppn_reg[3]} {u_core/root_or_cache_ppn_reg[3]}
  {ppn_reg[40]} {u_core/root_or_cache_ppn_reg[40]}
  {ppn_reg[41]} {u_core/root_or_cache_ppn_reg[41]}
  {ppn_reg[42]} {u_core/root_or_cache_ppn_reg[42]}
  {ppn_reg[43]} {u_core/root_or_cache_ppn_reg[43]}
  {ppn_reg[4]} {u_core/root_or_cache_ppn_reg[4]}
  {ppn_reg[5]} {u_core/root_or_cache_ppn_reg[5]}
  {ppn_reg[6]} {u_core/root_or_cache_ppn_reg[6]}
  {ppn_reg[7]} {u_core/root_or_cache_ppn_reg[7]}
  {ppn_reg[8]} {u_core/root_or_cache_ppn_reg[8]}
  {ppn_reg[9]} {u_core/root_or_cache_ppn_reg[9]}
} {
  if {[catch {set_user_match "r:/WORK/$top/$rl" "i:/WORK/$top/$il"} msg]} {
    puts "PIN_FAIL: $rl <-> $il ($msg)"; incr _pin_fail
  } else { incr _pin_n }
}
puts "PTW_PINS: $_pin_n pinned, $_pin_fail failed"
